### ISSUE TITLE
Improvements to Users Online Page

### ISSUE THREAD

**Issue by NaturalSigns** [cubecart/v6#100]
I run a couple of stores on different shopping carts.  Firstly I really like the new cubebart and I'm not looking elsewhere,...but one of the features i like about others (e.g. Zencart or Prestashop) is the ability to see a users shopping cart contents via the Users Online page, example below.  (green circle is active cart/amber circle is inactive and red is no cart), when you click on the appropriate visitor to the site the shopping cart on the right updates accordingly.  I have no idea how difficult that would be to implement but it is really handy feature (I use it a lot).

![visitors online](https://cloud.githubusercontent.com/assets/10531097/5827178/4feb00a2-a0f0-11e4-9b45-5c72cfb5e661.png)
.

**Comment by abrookbanks** [comment]
Easy to do. I like this and would like to add this after priority bugs are fixed.
