### ISSUE TITLE
Add SEO title and meta data for translations

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1002]
As above for each area where translations are possible

**Comment by bhsmither** [comment]
I was working on a solution to that on CC528, and it's crazy.

I'm not sure where I left it, but my database has: `prueba-categor%C3%ADa-1/prueba-1`, `art%C3%ADculos-rebajados`, and `certificados-de-premio`, for example, with a new column labeled 'language'.

**Comment by havenswift-hosting** [comment]
Any chance of making this more important and getting it into a future version.  We have several customers that operate multiple language stores and this is crucial for any secondary languages

**Comment by caranx** [comment]
I'm one of those requesting SEO data for translations, I can surely note that on the spanish side I'm well positioned on search engines but on the english side I'm nowhere. It would be great if the costumers who are non primarily english business could get the best out of the software. Thanks, ciao Nicola

**Comment by Coffeecoffeecoffeehouse** [comment]
Hello, it would be helpful for me too, if I could also "meta-describe" the non-native languages. I guess keywords are not so important but google likes to use meta description for their search results display.
