### ISSUE TITLE
Log retention settings

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1004]
- Admin Logins
- Request Log
- Email Log
- Error log
etc....

**Comment by havenswift-hosting** [comment]
This is the sort of thing I was talking about in https://github.com/cubecart/v6/issues/991 but expanding this even further to include fuller details of everything an admin user does - not simple "logged in" or "record deleted"

**Comment by abrookbanks** [comment]
![screen shot 2016-02-08 at 11 21 25](https://cloud.githubusercontent.com/assets/4520803/12884434/1bcec51c-ce56-11e5-9bab-80026839fcbb.png)
Log retention added. Still room for improvement in logging.

**Comment by havenswift-hosting** [comment]
On upgrading to 6.1.0, will these be blank and therefore have log retention disabled by default ?  I think a default setting of say 30 days for each should be added as part of the upgrade ?
