### ISSUE TITLE
BUG in language.class.php - line 237 

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1005]
PHP Fatal error: Call to a member function attributes()

You get this error when trying to edit a language using 6.0.10 and a white screen.

Validated in a clean 6.0.10 store and a customer store.

**Comment by havenswift-hosting** [comment]
See also https://github.com/cubecart/v6/issues/992 for other problems with languages

**Comment by abrookbanks** [comment]
I've not been able to reproduce this. I have tried editing normal language strings and module language strings after clone to translation.

**Comment by Noodleyman** [comment]
after "clone to translation" ?

Not sure if you addedd an extra step, I managed to replicate on a clean install by simply trying to edit a language. instant white screen.

**Comment by abrookbanks** [comment]
Yes for extensions it will create say for example fr-FR.xml cloned from the master language file if it doesn't exist. That then allows translation to work (from a previous bug report).

The block of code you mentioned concerns this clone function for that. :-/

I'll give it more of a poke about.

**Comment by Noodleyman** [comment]
nevermind.. I've figured it out!

It is / was bieng caused by an old plugin which had an invalid module.definitions.xml file.

The file itself was missing the <group name=""> line. after updating the file the error is resolved. So, is an issue with a plugin, not CubeCart.
