### ISSUE TITLE
Hidden Prices in Emails

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1009]
I am sure this was mentioned before, but there is a report that an email or emails were sent with hidden prices ($x.xx).

**Comment by bhsmither** [comment]
In `Order->orderStatus()`, where order emails get populated, a call is made to `$this->getOrderDetails()`.

In `getOrderDetails()`, calls are made to Tax->priceFormat()`. In `priceFormat()`, a test is made against `Session[hide_prices]`. If true, prices are masked.

`Session[hide_prices]` is set true when the Tax class is being constructed and various conditions are met, specifically if a 'ghost' customer has placed an order.

There may be calls made from other methods for `getOrderDetails()`, but none I know of where the customer isn't logged in.

Therefore, suggest that in `getOrderDetails()`, memorize the current value of `Session[hide_prices]`, temporarily set `Session[hide_prices]` to false, get all the prices formatted, then return `Session[hide_prices]` to whatever it was before.

(I have not tested this as yet.)

**Comment by bhsmither** [comment]
Actually, when an IPN is received, for that session created for it, User->is() is false, and prices could end up being hidden. When the gateway moves the order to Processing, masked prices will end up in the email.

**Comment by bhsmither** [comment]
Please see: https://forums.cubecart.com/topic/50885-values-missing-from-confirmation-email/

**Comment by abrookbanks** [comment]
Thanks for this Brian.
