### ISSUE TITLE
Move Admin Search GO button

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1010]
Putting "Go" button above instead of below Search dropdown box is much easier to use.
https://forums.cubecart.com/topic/50874-resolved-product-search-small-bug/

**Comment by Dirty-Butter** [comment]
Thank you! In use now on plushcatalog. This makes searching for items faster, particularly if I want to clone one from a group of results.

**Comment by abrookbanks** [comment]
Great!! Duplicate of #1010
