### ISSUE TITLE
plugin free shiping bug

### ISSUE THREAD

**Issue by fabriceunko** [cubecart/v6#1014]
I install the plug-in free shipping, but in my basket when the store is the french word free shipping remain in English although in the languages I have translated in french.
How to Get in french?
thank you

![freeship1](https://cloud.githubusercontent.com/assets/17278496/13108817/58a775a6-d56d-11e5-9d4e-d1ade67e96ff.jpg)
![20160217_085322](https://cloud.githubusercontent.com/assets/17278496/13108830/66bdd45a-d56d-11e5-867c-4a3736f3e0f3.jpg)

**Comment by abrookbanks** [comment]
![screen shot 2016-03-08 at 15 00 51](https://cloud.githubusercontent.com/assets/4520803/13605297/b3933154-e53e-11e5-91f0-995c37c587cb.png)

**Comment by fabriceunko** [comment]
the translation is made in the right place, but not work in the store.

![capture4](https://cloud.githubusercontent.com/assets/17278496/13610360/3c919d40-e555-11e5-96c2-020373e13649.jpg)
