### ISSUE TITLE
Products with options may somewhat ignore stock level when ordering

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1018]
When disallowing out of stock purchases, it is still possible to place an order for a product with options in an amount greater than its stock level by purchasing the product with different option sets:
![cc_option_stock](https://cloud.githubusercontent.com/assets/14335170/13185615/fdad96d6-d6f6-11e5-943a-d675c05b1b9d.jpg)
Note that the stock level for 'Options Product' is set at 1, but there are 2 of that product in the cart; trying to order a quantity greater than that correctly resets the quantity of each to the stock level of 1, but fails to note that they are the pulling from the same stock.

Note that this is only an issue if the stock levels are not managed at the matrix level, i.e. if multiple product variations are set to use the product stock level such as might be the case with an option that is an addition to the product, such as 'Add glitter', as opposed to something like 'Red shirt' or 'Yellow shirt' which clearly should track stock separately.

Looking at the code in cart.class.php, my first thought was to change $max_stock to be an array keyed by product id so that it could track the current stock vs. quantity that way, but that doesn't play nicely if stock levels are handled at the matrix level. I'm not really sure of a way to solve this without getting overly complex.

**Comment by abrookbanks** [comment]
I had to put my hands on each side of my head, turn the music down and read this eight times to make sure I understood. I will test this. It should give a warning that you can't buy more than we have in stock. I think I can get this fixed up.

**Comment by abrookbanks** [comment]
Got this one nailed finally. It's been open too long. It checks on add to basket and returns the stock level minus the quantity existing in the basket for that ID already if its not using the options matrix. 

Works great.

**Comment by briansandall** [comment]
> I had to put my hands on each side of my head, turn the music down and read this eight times to make sure I understood.

Gems like this are why I enjoy working on this project. :)

My explanations tend to be a little verbose... in my attempts to clarify every aspect of an issue, I think sometimes the point can get lost, so I'm glad you figured this one out!

**Comment by abrookbanks** [comment]
Your explanation was superb. I just knew its was a complex area of CC so I prepared myself. LOL

Turned out to be quite easy. Yay!

Thanks again.
