### ISSUE TITLE
Review Stars Cannot Be Unset

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#102]
Enhancement:

When writing a review, one can click on any one star, and that star and all stars to the left get set.

Once set, they cannot be unset/cleared.

Generally, not an issue, but maddening if one has to reload the page to clear the stars.

Also for CC5.

**Comment by abrookbanks** [comment]
My findings:
v5: https://dl.dropboxusercontent.com/u/894044/stars-v5.mov
v6: https://dl.dropboxusercontent.com/u/894044/stars-v6.mov

Are you saying it should be possible to completely clear the stars so they all go back to grey?

**Comment by abrookbanks** [comment]
I don't want to implement this as as adding a review should require a star rating in my opinion. It's easy to change;

In the skins/soundation/js/cubecart.js (v6) or js/common.js (v5) find:
```
$('input[type=radio].rating').rating({
        required: true
});
```

Just replace with:
```$('input[type=radio].rating').rating();```

**Comment by abrookbanks** [comment]
Also be sure to check this out: https://www.cubecart.com/extensions/plugins/reviews-co-uk

**Comment by hairydogltd** [comment]
Would it be possible to have the star at the beginning "hollow" to represent 0 stars? As a customer, I'd have used that a few times. As a retailer, I'd be happy to have a way for customers to represent their views, rather than requiring a minimum of one star.

**Comment by abrookbanks** [comment]
Of course you can just change the image.

**Comment by hairydogltd** [comment]
Excuse my denseness, but how can I make it use one image for the first star and another for the rest? I'd try to work that out for myself, but the functionality doesn't work at present in any case.

**Comment by abrookbanks** [comment]
Something like..
```
div.star-rating a:nth-child(1) {
    background: url(../images/star_1.gif) no-repeat 0 0px;
}
div.star-rating a:nth-child(2) {
    background: url(../images/star_2.gif) no-repeat 0 0px;
}
div.star-rating a:nth-child(3) {
    background: url(../images/star_3.gif) no-repeat 0 0px;
}
div.star-rating a:nth-child(4) {
    background: url(../images/star_4.gif) no-repeat 0 0px;
}
div.star-rating a:nth-child(5) {
    background: url(../images/star_5.gif) no-repeat 0 0px;
}
```

**Comment by hairydogltd** [comment]
:+1:
