### ISSUE TITLE
Code Discrepancy

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1022]
In Tax->exchangeRate():
`price = $price / $currency[0]['value'];` // division
In Tax->priceConvertFX():
`return ($price / $this->_currency_vars['value']);` // division

In Tax->priceFormat(): (equivalent)
`$price = $price * $this->_currency_vars['value'];` // multiplication

I assert the `exchangeRate()` equation is not what is wanted.
(Currently, the `exchangeRate()` is only used in calculating tax on shipping rates. The `priceConvertFX()` is used to go back to internal currency from client's form entry foreign currency prices.)

**Comment by abrookbanks** [comment]
The call in shipping calculations to Tax->exchangeRate is completely redundant and thus removed. 

Thanks Brian.
