### ISSUE TITLE
Email admin for multiple order status types

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1025]
Going along with the theme of #991 and #1004, would it be possible to allow emailing order updates to the admins for multiple order status types? A multiple select in place of the single select box we have now would be nice.

For example, I would like to receive email updates for orders as soon as they are first placed, i.e. pending, and then again once payment is complete / the order is changed to processing, as well as if the order is cancelled.

**Comment by abrookbanks** [comment]
Nice suggestion thanks! :)

**Comment by Noodleyman** [comment]
Available as part of:
https://www.cubecart.com/extensions/plugins/custom-order-status-colours-emails
