### ISSUE TITLE
Replace FontAwesome with inline SVG

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1027]

**Comment by bhsmither** [comment]
We would also like SVG support for $STORE_LOGO.

See:
https://forums.cubecart.com/topic/51624-svg-support/

**Comment by abrookbanks** [comment]
I'm so pleased with this. We lose 742KB of Font Awesome and replace it with a single  23.5 KB SVG sprite!

**Comment by abrookbanks** [comment]
Reopened for logo SVG support to be done..
