### ISSUE TITLE
USPS International Rates Are Inserting Local USPS Rather Than International

### ISSUE THREAD

**Issue by LaughingHorse1** [cubecart/v6#1028]
You will notice from the two files attached that the postage rates for an order billed to and shipped the UK, shows the exact same USPS rate and transit times.

Looking at The Request Log for this Order (uploaded as pdf)
![local usps](https://cloud.githubusercontent.com/assets/16118768/13355743/d5ee2c5e-dc6f-11e5-98da-94c6bebe9190.png)
![usps to uk 2016-02-26](https://cloud.githubusercontent.com/assets/16118768/13355753/df076ba2-dc6f-11e5-83b4-2f7e92925dc8.png)
[Wrong International Postage request Log.pdf](https://github.com/cubecart/v6/files/148378/Wrong.International.Postage.request.Log.pdf)

**Comment by bhsmither** [comment]
Of the USPS services listed in the response (see PDF), all are appropriate for an International shipment - presumably from Florida USA to Surrey UK. The rate you suggest (see image #2) matches with Priority Mail International.

You are using the phrase "for this order". So, are we to assume this is just one single order, and not two different orders where the delivery address from the first order bled over to the delivery address of the second order?

If just this one single order, can we assume therefore that this order did, at one time, have this customer's actual delivery address of Florida USA? Then, at some time later, the customer's actual delivery address got changed to Surrey UK? If so, is it possible for you to determine when this change occurred?

**Comment by LaughingHorse1** [comment]
This is happening on any order shipping to outside the USA.
This particular order was the very first time the customer had ordered from us.

The system is going to the post office website.
It does find the right rates
It then inserts the rate for the postage from local shipping rather than use the international rates.

Also, when a customer puts a product in the cart, before the customer has confirmed the shipping address, the system uses the local rate e.g. shipping from Jacksonville FL, to Jacksonville FL regardless of where the customer is located. -- This makes sense as the customer has not yet confirmed a delivery address.

On any domestic shipping the local Jacksonville FL ship to rate gets replaced with the correct ship to rate... e.g. a customer from Hawaii enters an order. The cart shows estimated shipping as if the customer were located in Jacksonville FL.

The Customer confirms the ship to address in Hawaii, and the local Jacksonville ship to rate gets replaced with the shipping rate to Hawaii.

When an International customer places an order they are initially shown the estimated postage rate as if the order was shipping from Jacksonville FL to Jacksonville FL.
When the customer confirms their address (as the customer in Surrey UK) the postage rate is not replaced with the correct rate, It stays as the local Jacksonville ship to rate.

So I'm guessing the system is not recognizing the international rate thus is not replacing it. Perhaps when the USPS changed the names of fields something was missed when the USPS module was updated?

**Comment by bhsmither** [comment]
I would guess CubeCart is not recognizing a newly entered user-defined international delivery address as a new address.

Can you pretend to be a UK customer and try this yourself? Or have you done so already - where you make your assertion "This is happening on any order shipping to outside the USA."

In CC6.0.10, there is a new setting in admin, Store Settings, Features tab, "Disable initial shipping & tax estimates." Please check the box to disable the estimating. Does the behavior persist? That is, does a shipment to UK still not show a proper international rate that was given to CubeCart by USPS?

**Comment by Dirty-Butter** [comment]
I just tried using a Canadian customer login (who completed an order successfully on 1/19/2016). The shipping choice was handled correctly. (I DO have in place the small edit recently provided on the forum that causes Please Select to show initially in the drop down box - other than that this code is stock). I'm using USPS 1.1.2.

**Comment by Dirty-Butter** [comment]
I tried again this morning, making a test order using the same London, Ontario postal code, as if I were a NEW customer. The estimated s/h again is correct.

**Comment by LaughingHorse1** [comment]
I went to Store Settings | Features tab | "Disable initial shipping & tax estimates." 
Then I entered a new customer order using the UK address for the customer above.

The rates showed the correct international rates.

I am guessing there is a bug somewhere with the "Shipping and Tax estimates"
I have been using USPS version 1.1.0
I can try with 1.1.2 and see what happens.

I updated to 1.1.2

This is interesting...

I left the Store Settings | Features tab | "Disable initial shipping & tax estimates."
Ticked (no checkmark), and it automatically defaulted to international postage as expected.

I then UNticked Store Settings | Features tab | "Disable initial shipping & tax estimates."
I found it initially showed local postage rates.
The difference was in the drop down shipping method (where you can select your shipping method), the top line said "Please Select your Shipping Method" and it showed the local USPS shipping rate.

I clicked on the drop down box and the International Rates showed up below the
"Please Select your Shipping Method" 

I tried checking our without selecting a shipping rate (Using the "Please Select Shipping Method" showing the local postage rate) and the system let me check out, using the local domestic rate.

Summation:
When the  "Disable initial shipping & tax estimates."** is Ticked**, the system defaults to the correct International Shipping Rate and does not show "Please Select Shipping Method"

When the  "Disable initial shipping & tax estimates." **is UNticked,** the system apparently believes that "Please Select your Shipping Method" is a viable shipping method, and lets a person use that for checkout.

**Comment by abrookbanks** [comment]
Please see https://github.com/cubecart/v6/issues/1181#issuecomment-277706112
