### ISSUE TITLE
My Website suspended due to functions.inc.php

### ISSUE THREAD

**Issue by normie5** [cubecart/v6#1030]
Today I uploaded the files for Version 6
Immediately I lost access to my site
When I went to my hosting control panel it read:

Suspended (php.h.HackScript-15 | /home/a6099771//public_html/store/includes/functions.inc.php

I now have to set up all my site on another account

Has anyone heard of this false positive

**Comment by briansandall** [comment]
Contact your hosting provider, but also is your folder really named 'a6099771'? If it is, have the contents of functions.inc.php been altered in any way? Compare your version of the file to the one here on GitHub and make sure nothing is different.

**Comment by normie5** [comment]
My account with host isa6099771
If you look more closely the folder is store/includes
File unzipped from CubeCart-6.0.10.zip   includes/functions.inc.php  25,314  1/21/2016
not modified in any way

**Comment by abrookbanks** [comment]
Please open a technical support ticket if you require assistance. This is not relevant here. 

We can perform a security audit and cleanse as part of our "Technical Support & Management" plan. 
https://www.cubecart.com/technical-support

**Comment by bhsmither** [comment]
This is not a problem with CubeCart, nor is it a case where a Cubecart installation has become infected. (Well, *probably* not infected.)

This a false positive from a rule used by **mod_tonyscanner**:
https://github.com/ton31337/apache/tree/master/mod_tonyscanner

From what little I can understand of the code, the rules are in a database, and I cannot find where or how these rules are developed.

There is very little Google search has on this. Mostly it is complaints from people who are hosted by one or two certain providers where customer service is all automated canned replies.
