### ISSUE TITLE
Improvement to Edit Customer Tab

### ISSUE THREAD

**Issue by NaturalSigns** [cubecart/v6#1032]
A suggestion for improvement to the Edit Customer tab.  Could it show the orders associated with the customer on this screen? (as shown on the mock up below [possible use of the red number icon to show it has content/number of orders]).

![customer tweak](https://cloud.githubusercontent.com/assets/10531097/13556382/26fc97b8-e3d0-11e5-9a16-d6d23642d1e6.jpg)

Data I know can be found by (i) using the "log in as ....." button and viewing order history via the front end (which is what i tend to do now) or (ii) via the customer list as below but both methods can be a bit protracted.

![customer list](https://cloud.githubusercontent.com/assets/10531097/13556366/e5f51dc6-e3cf-11e5-8487-d451d2aa5437.png)

**Comment by abrookbanks** [comment]
Nice suggestion! Thanks.
