### ISSUE TITLE
Issue with smarty & Email template admin.order_received

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1034]
Steps to reproduce.

1) Edit the "New Order" email content via CubeCart admin area.
2) Save
3) Edit again
4) Save
5) Set store settings "Order status for admin email notifications" => "Pending"
6) try and checkout. white screen at payment section. In the error log:

[Exception] /home1/plop99/public_html/trophysupplier/includes/lib/smarty/sysplugins/smarty_internal_templatecompilerbase.php:66 - Syntax error in template "string:

{$DATA.first_name} {$DATA.last_name..." on line 66 "{if !empty($DATA.ship_method)}{$DATA.ship_method|replace:'_':' '}:{if !empty($DATA.ship_product)} ({$DATA.ship_product}){/if}{else}Shipping:{/if}

This is being caused by the text editor replacing some special characters which smarty then can not parse.

This:
{$DATA.ship_method|replace:'_':' '}

Becomes:
{$DATA.ship_method|replace:&#39;_&#39;:&#39; &#39;}

**Comment by bhsmither** [comment]
The database upgrade step at CC606 was supposed to have removed the replace modifier. According to #884, the problem surfaces when the template eventually gets edited.

**Comment by abrookbanks** [comment]
If this issue raises its head we need to look at it on a case by case scenario. It used to come up nearly daily on the support helpdesk and this is the first time I've heard of it in months. 

Pretty confident this won't affect majority of stores now.
