### ISSUE TITLE
BUG : Problems with foreign language strings in SEO urls

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1047]
Major problems when using multiple languages (say Spanish and English together) due to entries for the foreign language causing 404 errors - affects register, login, search and others

**Comment by abrookbanks** [comment]
This is quite a large one. SEO class needs to be rewritten to have language flag.

**Comment by abrookbanks** [comment]
This fixes this issue but will need to be removed when SEO with language support is introduced.
