### ISSUE TITLE
Requesting New Hook - user.class.php

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1048]
Within the user.class.php file in the function authenticate();

BEFORE:
//If there is a redirect
if (!empty($redir)) {

ADD:
foreach ($GLOBALS['hooks']->load('class.user.preredirect') as $hook) include $hook;

The hook allows you to perform actions on login before being redirected.

**Comment by Noodleyman** [comment]
didn't that commit just uupdate the hooks.xml file, and not also the user.class file?

:)

**Comment by abrookbanks** [comment]
Hmmmm there is a security update on the user class I don't want to commit yet. This will be added at the same time. Thanks for checking.

**Comment by Noodleyman** [comment]
Thanks :)
