### ISSUE TITLE
WorldPay Module

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1049]
(Re #762) The WorldPay module admin skin has a form element named `callbackURL`. I do not see where this value is used when creating the form elements that WP will eventually get.

http://support.worldpay.com/support/kb/bg/paymentresponse/pr0000.html

Also:
https://forums.cubecart.com/topic/50877-worldpay-payment-gateway-extension-error/

**Comment by bhsmither** [comment]
Also, the version 1.0.5 download has a config.xml file that says it is version 1.0.4.

**Comment by havenswift-hosting** [comment]
We have full server logs for a transaction that is doing the same thing - not updating from Pending and no  transaction logs recorded if that would help get this fixed as it is a major PITA !

Can also confirm that the config.xml has incorrect version which is confusing !

**Comment by abrookbanks** [comment]
It's a read only field for reference. The value needs to needs to be set in WorldPay. It works similar to PayPal IPN and doesn't redirect the customer to your store.

**Comment by abrookbanks** [comment]
> 1.0.6 - Added "MC_callback" parameter and removed "successURL". Callback changed to correct "call" method instead of "process" of Gateway class.

**Comment by havenswift-hosting** [comment]
Reports from our customer that this has made no difference and orders are still not changed from Pending to Processing - they have upgraded to 6.0.11 and also upgraded the Worldpay module to this latest version

**Comment by nihe2532** [comment]
Hi I am also having the same issues with the Pending to Processing order status, I've updated CubeCart to 6.0.11 and WorldPay module to 1.0.6 and still same issues.
Additionally I've needed to recode [country] to [country_iso] as per bhsmither guidance in https://forums.cubecart.com/topic/50877-worldpay-payment-gateway-extension-error/
