### ISSUE TITLE
Basket not accessible 

### ISSUE THREAD

**Issue by kealanm1** [cubecart/v6#105]
Potential knock on from issue https://github.com/cubecart/v6/issues/104
Demo store : http://www.gooutdoorireland.com/cc6test/store/

Issue seems reproducible with most variations of products / pages 

1. Add item to basket 
2. Wait for basket pop up to vanish 
3. Try and access the basket through the icon in the top right of the screen 

4. " # " is appended to the end of the url and no basket is shown 

P.S. this store is an upgrade. the original store had some serious gremlins so potentially this is a legacy issue not a cc6 issue

**Comment by abrookbanks** [comment]
Thanks for this!! :)
