### ISSUE TITLE
I just installed CubeCart

### ISSUE THREAD

**Issue by tjcusick** [cubecart/v6#1055]
I just installed cubecart on my website at godaddy.com and I am having a couple issues so far...

1. I continually get a 500 internal sever error with no explaination?
2. I cannot find where CubeCart is saving/storing the documents on my website?

Any suggestions?

**Comment by briansandall** [comment]
This is not the place for support questions - I suggest you open a support ticket with Al and/or post your issue on the [forums](https://forums.cubecart.com/).
