### ISSUE TITLE
6.0.11 - Cross site admin authentication issue

### ISSUE THREAD

**Issue by nihe2532** [cubecart/v6#1056]
Hi - I've just noticed that clearing my browser cache and logging into my test site with my admin account also bypasses my production site admin credentials with the session token from my test instance.
Mozilla:
navigate to test.domain.com/admin.php
login admin account
new tab
Navigate to www.domain.com/admin.php
automatically shows dashboard, I have a difference admin account name for prod also.

Session Token is the same in the CubeCart debug.

**Comment by bhsmither** [comment]
In /classes/session.class.php, near line 615, the constant `ROOT_REL` has not been defined anywhere. Thus, the PHP `session_name` (and cookie name but not the value) will be the same.

Suggest the constant `CC_ROOT_REL`.

**Comment by bhsmither** [comment]
Maybe not. The most common value for `CC_ROOT_REL` is a simple `/`.

Suggest the constant `CC_ROOT_DIR`. That should be unique enough.

**Comment by abrookbanks** [comment]
Thanks Brian! That's a good solution.

**Comment by Dirty-Butter** [comment]
We're still having this issue - see 
https://forums.cubecart.com/topic/51983-admin-side-filling-mobile-data-field/
