### ISSUE TITLE
Option Sets do not work correctly when using 6.0.11

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1060]
Stumbled across this whilst playing around with the latest version.

option sets are not working correctly.

Steps to reproduce:
1) Clean install of CC6.0.11
2) Build some options (I added 3 options groups)
3) Add options to the options groups
4) Build an option set, I added all options avaialble
5) From products -> Assign option sets add the option set to "test product".
6) Verify that the options are added when editing the product.

All options default to status disabled, but you can't enable them. If you check the box and save the setting is not stored. 

You also can't add these options to the option matrix, it doesn't respect the checkbox when saving.

If you manually add the options to the product it works correctly, so it's an issue with option sets.

**Comment by abrookbanks** [comment]
All good. This wasn't as monstrous as I expected.

**Comment by Dirty-Butter** [comment]
Is there anything in these code changes that might cause a Save of an edit of an existing product to show the Product not updated message when the product edit actually did save? I do not use Options.
