### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by keat63** [cubecart/v6#1061]
Any chance of a new feature request please.
An extra email step in the checkout process for admin purposes.

Emails are set to 'Pending' at secure checkout stage, but not set to processing until after payment.
An extra email step at the gateway stage would be good.

The customer chooses which gateway he wishes to pay with, and clicks the continue button.
At this stage an email is sent to admin, notifying of order.

**Comment by Noodleyman** [comment]
@abrookbanks , isn't this the same as setting the store setting "Order status for admin email notifications" to "Pending" in the store settings?

**Comment by abrookbanks** [comment]
@Noodleyman Yes exactly... Closing. Cheers guys.

**Comment by keat63** [comment]
It's not quite the same as setting notification at pending.

Customer clicks secure checkout Button.
Email is sent to admin
Customer clicks back button and makes a change.
Customer clicks secure checkout button, no second email is sent.

If we had another stage at transfer to gateway, then the customer has already committed to pay and is less likely to go back and change his order.

**Comment by keat63** [comment]
Email at processing relies on ipn from the gateway. If a customer doesn't pay then you are unaware of the order.
And email at pending is flawed in my opinion.

**Comment by Noodleyman** [comment]
but the point of the admin email is to notify you of a new "potential" order if sent when pending. The cart would have done that.  notifying you twice of the same potential order seems to be a bit overkill?  

would it make more sense to receive notifications when orders are in a processing state in this case?

"email are processing relies on IPN from gateway".
That would actually depend on the payment gateway as there are many different modules, all of which have different processes.

**Comment by keat63** [comment]
As it stands.

With notifcation at processing, if a customer chooses not to pay, then no email notifcation is sent, so admin would be unaware of the order.

Whereas, An email sent at the point where the customer has chosen his preferred gateway and clicked the continue button, an email would be sent to admin notifying of a potential order.
If the customer still chooses not to pay, we have the opportunity to contact him.

I'm not suggesting sending the email twice, but to be able to be notified when he's chosen his gateway.

**Comment by keat63** [comment]
Email at pending is fine, but in my opinion the 'secure checkout' button is the wrong place to send the email, This should be at the gateway 'continue' button, or at least a feature to allow it to be at this stage.

The gateway 'continue' button is a blind spot.

**Comment by Noodleyman** [comment]
"Whereas, An email sent at the point where the customer has chosen his preferred gateway and clicked the continue button, an email would be sent to admin notifying of a potential order.
If the customer still chooses not to pay, we have the opportunity to contact him."

what  you described here is exactly what it does when the notices are sent at the "Pending" stage. 

gateway button is normally within the payment modules themselves, so what you may be really wanting is some enhancement to the payment gateway modules you are using?

**Comment by keat63** [comment]
The trouble with email at pending being sent at 'secure checkout' is that customer can and quite often and do go back and change their order.

The order confirmation email only comes once and then doesn't match the payment. 

I'm not alone on this problem by the way.

**Comment by abrookbanks** [comment]
As Alec said the admin notification email is just a guide. CubeCart won't sent it more than once and it is sent once the order is created.

If you have a version 6 skin like Foundation or Galaxy you will have chosen the payment method already (as it shows them in the basket rather than after).

I think this issue should remain closed. You could always customise it to suite your particular requirements.

**Comment by abrookbanks** [comment]
You could always add an extra email to the admin saying the order has changed. Alternatively or as well you could amend the email sent to the admin staff to say that it is for guidance only and to check via the admin control panel.

**Comment by keat63** [comment]
I'm using Mican as it fits in with our colour scheme straight out of the box. I wasn't aware that Foundation worked differently.
Maybe I might have to go down the custom skin route then.

**Comment by abrookbanks** [comment]
The Foundation skin looks basic but has huge improvements over old v5 skins. 

- JS Validation on forms with tools like check to see if email addresses are already in use before page submit.
- The old skins functionality differently and may not take full advantage of v6 such as displaying social icons and moving payment choice earlier into the checkout process. 
- The new skins are responsive and have improved UX.
