### ISSUE TITLE
Skin Elements Feature Request

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1064]
Mainly in the GUI class, but also elsewhere...

For each method that uses a template, first test for the presence of that template.

Example:
`GUI->_displaySearchBox()`
If `box.search.php` does not exist, do not fetch it.

`GUI->_displaySkinSelect()`
If `box.skins.php` does not exist, do not fetch it.

GUI->_displaySocial()
This test is already being made, but it is too soon. A hook may provide an alternate template, but the early return deprives any chance of the hook happening.

Reasoning: If the skin developer chooses to not have a "Sign Up for Newsletter" box, simply do not include the template.

Currently, if a template cannot be found, a SmartyException is thrown.

Of course, the skin designer can simply remove or make a comment of
```
{include file='templates/box.newsletter.php'}
or {$MAIL_LIST}
```
in the parent template, but the template still must exist.

**Comment by abrookbanks** [comment]
I love this Brian. Thank you.

**Comment by cb2004** [comment]
Fantastic. I have a lot of zero byte files to get round errors.

**Comment by abrookbanks** [comment]
Yeah I like this one a lot! Why process all that code!?!
