### ISSUE TITLE
Issue with Fusion skin code with PHP 5.5+

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1067]
https://forums.cubecart.com/topic/51131-resolved-required-fusion-code-change-on-upgrade-to-php-55/
Please see Bsmither's suggestion at end of the thread about ShopDev.

**Comment by abrookbanks** [comment]
Our own version of Fusion Framework was released fixing this issue in October last year.

https://github.com/cubecart/Fusion
