### ISSUE TITLE
Product Price should show lowest option price when using absolute option prices

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1068]
If a product has any absolute option prices defined, the price in category view / search results etc should show the lowest option price instead of the price defined at the "price" level of the main product.

Perhaps even a new option within the options itself. A radio button that lets you select the "price to display" for absolute options.

**Comment by briansandall** [comment]
Related to #902, though I proposed using the highest listed price (among other things).

Per Al, multiple absolute price options are not currently supported, but if they were, being able to select which one takes precedence for each product could be useful, albeit tricky to implement.

**Comment by Noodleyman** [comment]
I've solved the issue of multiple absolute prices by building absolute pricing at the matrix level.

https://www.cubecart.com/extensions/plugins/absolute-matrix-option-prices-price-list-hide-out-of-stock-matrix-options

and yes, it was simply the display price for the product. It should either dynamically select the cheapest absolute option (if absolute options are enabled), or allow a selection of the price to show the customer before they hit the product page.

**Comment by abrookbanks** [comment]
Also need to consider cheapest out of quantity discounts

**Comment by abrookbanks** [comment]
Relates to #1094
