### ISSUE TITLE
Edit customer address takes you back to customer list

### ISSUE THREAD

**Issue by PeteW1959** [cubecart/v6#1070]
When editing a customer address (Dashboard - Customers - Joe Customer - Addresses tab), on save you are taken back to the customer list. I would expect to go back to the Addresses tab, or at the most the customer General tab as happens when deleting an address.

This is particularly annoying when arriving at the customer from the Orders page as you then need to go and find the order again to update the addresses on the invoice.

**Comment by abrookbanks** [comment]
Thanks for this.
