### ISSUE TITLE
Unregistered customer addresses duplicated

### ISSUE THREAD

**Issue by PeteW1959** [cubecart/v6#1072]
In most (but not all) cases, unregistered customers have 2 identical entries for both Billing and Delivery addresses. I have never seen this behaviour with registered customers.

**Comment by Noodleyman** [comment]
what version of the cart are you using, and what steps can you follow to reproduce the issue?

I've not seen this behaviour yet in any of the V6 releases so not sure how your able to get it to do it :)

**Comment by PeteW1959** [comment]
I am on 6.08 for my live store. So far I have not managed to reproduce the problem myself, but it isn't practical to find out if those affected are using a particular device\OS\browser combination. However as it affects most unregistered customers, it must be a very common combination.

It isn't a huge problem as it only affects unregistered customers, but I do like to keep a tidy database and this sticks out as unnecessary duplication of data. Also it is possibly an indication that there may be an error in the code that could lead to more serious problems in future releases.

**Comment by Noodleyman** [comment]
and, just to confirm.. when  you say "two duplicate for billing and delivery addresses"

Do you mean in the DB there are 2x delivery addresses and 2x billing addresses?

a total of 4 records?

**Comment by PeteW1959** [comment]
Yes, that is correct, and the two copies of each address are identical.

**Comment by Noodleyman** [comment]
I've tried to reproduce it again on 611, but not able to. Are you using a custom store skin or any plugins or mods that may be causing the issue?

**Comment by PeteW1959** [comment]
I am using a modified Foundation skin, but the mods are only colour changes or hiding some of the blocks; there is no additional code. I am also using your multi level shipping, and Crafty Clicks address lookup.

**Comment by Noodleyman** [comment]
can you disable the address lookup and see if you still get the same issue?

MultiLevel shipping doesn't do anything with addresses, but it sounds like address lookup might. I suspect that could be part of the problem, it's worth checking to make sure.

**Comment by PeteW1959** [comment]
I can't disable it at the moment as this is one of our busiest times of the year. I will have a play around early next month.

**Comment by Noodleyman** [comment]
What's the URL of your store? Will take a quick look at the checkout page and see if I can spot anything odd for you :)

**Comment by PeteW1959** [comment]
http://shop.whitbygothweekend.co.uk

**Comment by Noodleyman** [comment]
I didn't see any issue with the source on the checkout page, looks like it's not duplicated the inputs. You can do a really quick test to see if it's skin related, simply switch your store skin to foundation, checkout and see if you can replicate the issue. If you can't it's skin related, if you can it's something else.

If you rule out the skin, try disabling your plugins and see if those have an impact.

**Comment by PeteW1959** [comment]
The event is this weekend and I am leaving home today to go set things up so I am not going to have time to run any tests. I will look at it again when I get home end of next week.
