### ISSUE TITLE
Dont display thumbnail image if there is only one product image

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1075]
See https://forums.cubecart.com/topic/51197-product-images

There is no need to display the thumbnail image if there is only a single product image

**Comment by Dirty-Butter** [comment]
Bsmither provided a snippet solution that appears to have worked correctly for OP.
https://forums.cubecart.com/topic/51197-product-images/?do=findComment&comment=217217

**Comment by havenswift-hosting** [comment]
Agreed that the snippet solution seems to work but this seems common sense to include into the core rather than requiring everyone else to add the same snippet

**Comment by abrookbanks** [comment]
Thanks.

**Comment by claudia39** [comment]
When I use either fix, you cannot click the main image to enlarge it and my Product Description Tab is out of whack.  Might be my coding, I don't know. Custom skin based on Foundation 6.0.11.  Here's an example:  https://www.claudiasbargains.com/family-of-calico-cats-polyresin-photo-frame.html

**Comment by Dirty-Butter** [comment]
I get the same thing with my version of Foundation, which is certainly not stock. The listing image will not enlarge to full size.

**Comment by Dirty-Butter** [comment]
Bsmither fixed it with a core edit near the end of the forum discussion:
https://forums.cubecart.com/topic/51197-product-images/?do=findComment&comment=217217
