### ISSUE TITLE
Order Status Emails - orderStatus function issue

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1077]
Spotted this today whilst debugging an issue for somebody.

order.class.php, line 374 checks to see if the order status has changed. If it has not changed it sets
 $this->_email_enabled = false;

and also returns false to prevent any other actions.

However, later in the function the choice to send e-mails checks for  $this->_email_enabled = true.  At no point in this function does it get sent to true. It looks like it will only send e-mails if the $force variable is true.

To fix this:

// Insert order status if it's changed
if ((int)$status_id !== (int)$currentStatus[0]['status'] || $force) {
    $this->_addHistory($order_id, $status_id);
    $this->_email_enabled = true;
} else { // Don't send out emails already sent!
    $this->_email_enabled = false;
    return false;
}

This allows emails to be sent correctly based upon the order status without needing to use $force = true.

**Comment by abrookbanks** [comment]
I'm fearful of this as right now it seems to be working well. The code might not be spot on but it is behaving as it should. Does making this change cause any differences around email notifications?

**Comment by Noodleyman** [comment]
Not that I am aware of, since your using $force = true in most cases. You only really want to send the e-mail once, unless manually triggered in case you spam the customer ;)

**Comment by Noodleyman** [comment]
ran into the same issue again today where using the orderStatus function through a module/hook fails to send the order completed e-mail, because $this->_email_enabled never gets set to true.

Could really do with this being sorted in a future version ;)

**Comment by abrookbanks** [comment]
Hi Alec,

After reviewing this again I think that it was never set to true in the orderStatus method as by default the value is true (in the class default parameters). I do see that if for some reason the method needs to be called again and the situation has changed there is no way for it to go to true. For this reason I think your code change is acceptable.

Thanks for your kind patience with this one (and others)..... I'm getting there.
