### ISSUE TITLE
Differences in Address Book Logic

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1078]
As a customer, if you add a new address via the address book and you select a "state" from the select list the state in the CubeCart_addressbook is stored as the reference ID.

However, if you capture an address via the checkout process as part of an account registration then the actual textual value of the state is saved instead of the ID.

Although both methods work, it's a disconnect in the way the addresses are processed.

**Comment by Noodleyman** [comment]
cubecart.class.php, as part of _checkout() function the "state" field calls the getStateFormat() function, where as the address book $_POST variable is simply passed directly to the saveAddress() function without similar processing

**Comment by abrookbanks** [comment]
As there is no bug here and CC can handle either ID or string I think we can close this as it isn't broken.

**Comment by Noodleyman** [comment]
@abrookbanks , actually... it can't handle it correctly in all places. If you add a textual state, for example a US state abberviation, all of the HTML selects can't find a match and show as no state selected, but on screens that read the information such as displaying the address it is correct.  This means you have to use the HTML selects, then re-select the correct state from the drop down list and re-save it to change the format from text to ID.

Having a single, standard way to store, update and read address data would be beneficial as it would iron out the oddities that happen when using two systems for the same thing.

**Comment by abrookbanks** [comment]
Agreed.

**Comment by Noodleyman** [comment]
It might just required a minor update to make use of the zone "abbrev" data which is already in the zone table, perhaps try and match on ID, if no match then fall back to name, if no match fall back to abbreviation, if no match show the textual value. It might fill some of the gaps until such time that it can be revised?

**Comment by abrookbanks** [comment]
That's worth a shot.
