### ISSUE TITLE
Enhancement Request: Customer Log Out / Admin Log Out

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1079]
If you are logged into the CubeCart admin area and also logged into the storefront as a customer, when you use the log out button as the customer it also ends the logged in session for the admin.

The same is true when logging out as the admin, it logs you out as the customer.

It's been this way since CC5 came along, and perhaps earlier. I am opening the ticket to see if the behaviour can be changed. Logging out as a customer shouldn't need to log out an admin and vice versa.

**Comment by bhsmither** [comment]
See #1056 

In the past, I have had to install more than one Firefox (distinct profiles) so that each has a unique cookie/session.

**Comment by abrookbanks** [comment]
Fixed in #1056

Thanks all.
