### ISSUE TITLE
Address server side checks - Differences

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1080]
With JS disabled in your browser, if you try and add an address via the address book and don't populate all the required fields you still receive an error saying that the address couldn't be added. There are server side checks to ensure all the required fields are completed.

However, the same checks do not happen via the registration/address capture as part of the checkout process. If a customer has JS disabled in their browser you can submit partial or incomplete addresses. There are not the same level of server side checks on addresses. 

Recommending applying the same level of checks to the checkout process as exist within the address book.

Code snippit taken from cubecart.class.php _addressbook() function.

```
            $required_fields = array('first_name','last_name','line1','town','country','state','postcode');
            $empties = false;
            foreach($_POST as $key => $value) {
                if(in_array($key, $required_fields) && empty($value)) {
                    $empties = true;
                    break;
                }
            }
            // Update address data
            if (!$empties && $GLOBALS['user']->saveAddress($_POST)) {
                $message = ($_POST['address_id']) ? $GLOBALS['language']->account['notify_address_updated'] : $GLOBALS['language']->account['notify_address_added'];
                $GLOBALS['gui']->setNotify($message);
                httpredir('?_a='.$_a);
            } else {
                $message = ($_POST['address_id']) ? $GLOBALS['language']->account['error_address_updated'] : $GLOBALS['language']->account['error_address_added'];
                $GLOBALS['gui']->setError($message);
            }
```

**Comment by abrookbanks** [comment]
From what I can see the client side matches the server side validation.

# Address Form
![screen shot 2016-12-09 at 09 21 07](https://cloud.githubusercontent.com/assets/4520803/21043896/1f42c960-bdf1-11e6-973d-4060ed3de01a.png)

# Checkout Form Validation
![screen shot 2016-12-09 at 09 22 10](https://cloud.githubusercontent.com/assets/4520803/21043899/23b59a86-bdf1-11e6-99dc-bcdc8e25df0d.png)

**Comment by abrookbanks** [comment]
Struggling to test this because there is HTML5 validation too LOL.

**Comment by abrookbanks** [comment]
not working..

**Comment by bhsmither** [comment]
_"Struggling to test this because there is HTML5 validation, too."_

Would a different `<!DOCTYPE>` provide any relief from HTML5? (I haven't tested this myself.)
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" {* html *}>
```

**Comment by abrookbanks** [comment]
I just ran out of time. I'll remove the required tags and try again.
