### ISSUE TITLE
Something Wrong with PayPal Pro & Express Checkout

### ISSUE THREAD

**Issue by keat63** [cubecart/v6#1081]
I've tried all 3 PP-Express modules and all 3 are giving me issues.

V11 & v12 appear to calculate taxes incorrectly. Whilst it doesn't appear to charge them incorrectly, it is displaying them incorrectly on the store email notification.

V10. Customer placed an order under his registered name, we recieved the pending order email.
Customer completed his paymant via PP-Express, PP-Express updated the database with a different set of details. At this stage, I'm not sure if V11 & V12 have the same trait. 

I'm more than happy to work with you guys as a test guinea pig if you need it, but I can't use PP-Express in it's current guise.

https://forums.cubecart.com/topic/51213-still-having-issues-with-paypal-express/

**Comment by briansandall** [comment]
See issue #875

**Comment by abrookbanks** [comment]
The integration has been developed intentionally to take the data from PayPal and overwrite any data held in CubeCart.
