### ISSUE TITLE
Improvement Request - DB columns in varbinary

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1083]
Some DB columns are defined as type varbinary, however they really don't need to be.

For example, 
CubeCart_category.cat_image is varbinary(25) abd holds a reference to CubeCart_filemanager.file_id which is INT(10).

there is no reason to use this as a binary field, it can cause some issues when doing direct queries if you don't remember to CAST the field type.

**Comment by abrookbanks** [comment]
Thanks Alec
