### ISSUE TITLE
BUG : Unable to assign products to discount coupon

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1085]
The functionality around creating a discount coupon to apply to selected specific products is confusing and doesn't work.

It is possible to create a discount coupon with say a 5% discount.  If you then go to the Assigned Products tab -
 
1) There should be a way to browse and also search for specific products

2) There is no indication of what should be added (Product ID, Product Code etc)

3) Whatever "codes" are added to the list are initially displayed but after saving, are no longer recorded

**Comment by abrookbanks** [comment]
From my testing this works fine Ian.

**Comment by havenswift-hosting** [comment]
![admin control panel](https://cloud.githubusercontent.com/assets/6114431/15178814/30ad8872-1778-11e6-8e4b-6b4d90fad8a5.png)

Help offers no help as to what should be entered

**Comment by abrookbanks** [comment]
I'm improving the UX now...
