### ISSUE TITLE
Pricing Correct on Store front but customer paying different amount??

### ISSUE THREAD

**Issue by LEA-Laura** [cubecart/v6#1086]
I sell A4 card and I changed my prices last April 2015 - yes 2015.  I have just noticed that one of my customers is still getting the card at the old prices, yet it is showing on my store front at being the correct price and the item is also the correct price in the admin section.  Is there a simple explanation to this?   How do I ensure that the customer pays the correct price for future orders.  Luckily it is only 5p of a difference but I am glad I am not selling diamonds!

**Comment by Noodleyman** [comment]
If you are using customer groups, check your customer group level pricing. Most people usually only update the main price and forget the other groups. :)

**Comment by LEA-Laura** [comment]
Oh my, that's just brilliant, that fixed the problem....thank you so much.....very much appreciated as have not got a clue what I am doing half the time.  Think I need to go on a crash course I think!
thanks again
