### ISSUE TITLE
SAMEORIGIN

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1088]
According to:
https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options
the value is **SAMEORIGIN**.

index.php and admin.php.

**Comment by bhsmither** [comment]
This would break the iframe technique of showing publisher-hosted sites when viewing skins in the Marketplace.

**Comment by abrookbanks** [comment]
Thanks Brian!
