### ISSUE TITLE
US Territories can be selected as states instead of as countries

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1089]
This means that they cannot be specifically enabled or disabled as 'zones' if the customer selects 'United States' as the country and e.g. 'Puerto Rico' as the state.

Allowed and disabled countries are checked for each shipping module via `Cart::checkShippingModuleCountry`, so either that method can be modified to also check for matches with `$this->basket['delivery_address']['state_abbrev']`, OR the territories need to be removed from the list of states when 'United States' is selected as the country.

Note that this likely affects ALL shipping modules.

**Comment by briansandall** [comment]
Another solution would be to add specifically allowed / disabled states in addition to countries. Many retailers ship only to the contiguous 48, for example, or 48 + Alaska + Hawaii, but not to any other places overseas whether part of the US / armed forces or not.

**Comment by briansandall** [comment]
As a temporary hack, I edited the functions.inc.php state_json() function:
```
function state_json() {
	## Generate a JSON string for state selector
	if (($json = $GLOBALS['cache']->read('json.states')) === false) {
		// also select 'gc.iso' and 'gz.abbrev' for readable comparison
		$counties = $GLOBALS['db']->query('SELECT gc.iso, gc.numcode, gz.id, gz.abbrev, gz.name FROM `'.$GLOBALS['config']->get('config', 'dbprefix').'CubeCart_geo_zone` AS `gz` LEFT JOIN `'.$GLOBALS['config']->get('config', 'dbprefix').'CubeCart_geo_country` AS `gc` ON gc.id=gz.country_id ORDER BY gc.name, gz.name ASC');
		$json_array = array();
		if ($counties) {
			$current = '';
			// Allow shipping to continental US states plus Alaska and Hawaii
			$allowed = array('AL','AZ','AR','CA','CO','CT','DE','DC','FL','GA','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY','AK','HI');
			foreach ($counties as $state) {
				if ($state['iso'] === 'US' && !in_array($state['abbrev'], $allowed)) {
					continue; // hack to only allow designated states
				}
				if ($current != $state['numcode']) {
					$json_array[$state['numcode']][] = array('id' => '0', 'name' => '-- '.$GLOBALS['language']->common['please_select'].' --');
					$current = $state['numcode'];
				}
//				$json_array[$state['numcode']][] = array('id' => $state['id'], 'name' => utf8_encode($state['name'])); // data already utf-8
				$json_array[$state['numcode']][] = array('id' => $state['id'], 'name' => $state['name']);
			}

			$json = json_encode($json_array);
			$GLOBALS['cache']->write($json, 'json.states');
		}
	}
	return $json;
}
```
Note that you may need to clear the json.states file from the cache before this takes effect and there isn't any enforcement server side, but it should eliminate or at least limit addresses of this type.

**Comment by abrookbanks** [comment]
I'm putting this as a feature request as of now you can only have country and zone levels. There is no third level other than zip.

Although Puerto Rico is a territory the only way to deal with this is to have it as a US state (although it is not) or bring it to the top level country as America (Puerto Rico). For example the drop down menu may read;

- United States of America
- United States of America (Puerto Rico Territory)

Of course there is also Guam, Northern Mariana Islands, United States Virgin Islands and American Samoa.

It would be interesting to see how other platforms and mainstream retailers handle this.
