### ISSUE TITLE
Moving status from Pending to Processing

### ISSUE THREAD

**Issue by BarryWatson81** [cubecart/v6#1098]
I'm having an issue trying to move orders from "pending" to "processing".  Currently I have to do this completely manually and when I try to do it, the screen just freezes and won't change to "processing", which obviously means customers don't get their email for processing orders.

I am using the WorldPay gateway and it would be great if once payment is authorised, the "pending" changes automatically to "processing"Is there a way to do this?  If not, please help with how I can change "pending" to "processing" manually.

Cheers, 
Barry

**Comment by BarryWatson81** [comment]
In addition when I check orders I seem to have duplicate orders appearing with some customers with the same purchase orders only with a different ID. Obviously one of the orders is paid for and the other isn't.  Is there a reason for these duplicates turning up?

**Comment by abrookbanks** [comment]
This is specific to your store. If you can send a tech support ticket we can have a look for you.
