### ISSUE TITLE
Suggest replacing http://api.hostip.info in statistics.index.php

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1099]
This site has been down for some time. I suggest you change to another IP lookup site. I changed line 231 to
 ```   
 [<a href="http://whatismyipaddress.com/ip/{$user.ip_address}" class="colorbox hostip">{$user.ip_address}</a>]
```
and it works for me.
Another related issue: I normally use FireFox, and for some reason I have always gotten a blank popup for checking an IP address - including with this site change. I have to open the IP address in a new tab to see the results. Is there a way to change the code to fix this?

**Comment by abrookbanks** [comment]
Thanks Rosemary. I chose http://whois.domaintools.com/80.229.221.249 as the info is very comprehensive and advert free. Domain Tools is very established.
