### ISSUE TITLE
Add a welcome "Quick Start" to the admin CP with "JoyRide"

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#110]
A quick joyride to help new users find their way.

e.g. Go to Setup, add products, add categories etc..

**Comment by havenswift-hosting** [comment]
A great idea to help new users get the basic setup done as quickly as possible - even more important now that with CubeCart being open source there are a lot more new users testing it

**Comment by abrookbanks** [comment]
https://github.com/zurb/joyride

**Comment by abrookbanks** [comment]
Really pleased with the outcome of this. It will load only once ever once closed or completed.
![1](https://cloud.githubusercontent.com/assets/4520803/5874676/74e90404-a2fc-11e4-98bb-e9a4e034c33e.png)
![2](https://cloud.githubusercontent.com/assets/4520803/5874708/b6828ed0-a2fc-11e4-9e7c-65753be9f808.png)
![3](https://cloud.githubusercontent.com/assets/4520803/5874683/75332188-a2fc-11e4-9469-f426bb9cba2a.png)
![4](https://cloud.githubusercontent.com/assets/4520803/5874680/74ffb988-a2fc-11e4-9531-87bd457749e1.png)
![5](https://cloud.githubusercontent.com/assets/4520803/5874681/751efdac-a2fc-11e4-8831-e227a364d86a.png)
![6](https://cloud.githubusercontent.com/assets/4520803/5874682/7520641c-a2fc-11e4-9aff-78718135fe07.png)
![7](https://cloud.githubusercontent.com/assets/4520803/5874679/74fd26a0-a2fc-11e4-9417-8abf6d1939fa.png)

**Comment by Dirty-Butter** [comment]
Does it have to only be open once? Why not provide a link to it instead.

**Comment by abrookbanks** [comment]
It has both. :)

**Comment by abrookbanks** [comment]
![screen shot 2015-01-23 at 16 34 40](https://cloud.githubusercontent.com/assets/4520803/5878366/1a46c258-a31e-11e4-93c1-39691346c342.png)
![screen shot 2015-01-23 at 16 36 32](https://cloud.githubusercontent.com/assets/4520803/5878367/1c4b9858-a31e-11e4-81bf-5907e251c93e.png)
