### ISSUE TITLE
Hide out-of-stock product option selected and they still display

### ISSUE THREAD

**Issue by cb2004** [cubecart/v6#1104]
This doesnt seem to work, products that are out of stock show within a category view. Also I cant check, but if out-of-stock products are hidden then this should throw a 404 when the product is viewed and the product shouldnt display.

**Comment by briansandall** [comment]
If you are logged in to the admin panel in the same browser, you can see hidden products. Log out and try again.

**Comment by Noodleyman** [comment]
this can also be an issue with your store skin.
