### ISSUE TITLE
Page 1 canonical is duplicate content

### ISSUE THREAD

**Issue by cb2004** [cubecart/v6#1105]
`<link rel="canonical" href="http://www.mysite.com/mycategory.html?page=1">`

Is duplicate of:

`<link rel="canonical" href="http://www.mysite.com/mycategory.html">`

**Comment by Noodleyman** [comment]
yes it is, nice catch. 

perhaps a work around would be to use the category base URL for page 1, rather than the page parameters. It will solve it whilst keeping everything functional.

**Comment by abrookbanks** [comment]
This is tricky because the variable "page" is just that.. variable. 

Really we want something like:
http://www.mysite.com/mycategory
http://www.mysite.com/mycategory/2
http://www.mysite.com/mycategory/3 etc

**Comment by abrookbanks** [comment]
This works well but we may introduce other var names like the review one you mentioned on live chat Chris.
