### ISSUE TITLE
Feature request: No success message when product added to cart with Ajax cart switched off

### ISSUE THREAD

**Issue by cb2004** [cubecart/v6#1109]
When a product is added to cart and the Ajax basket code has been removed, there is no success message.

**Comment by Noodleyman** [comment]
This sounds like it's working as expected as you've turned off the functionality that gives you the success message. You will need to replace that functionality with something different in your code.

**Comment by cb2004** [comment]
I am thinking this may be a bug as you do not get a success message even with the foundation skin, the basket just opens. However in the languages under catalogue there is added_to_basket, but I cant see where that would be fired in the code.

**Comment by Noodleyman** [comment]
when you say "success message", what exactly do you mean? can you describe your expected result?

**Comment by cb2004** [comment]
Just a note within box.errors.php to say that the product was added to basket successfully.

**Comment by Noodleyman** [comment]
I've done this a few times for people. it's a simple enhancement to the included javascript files.
if you need this in a hurry, drop me a message and I will see if I can drop you the code you need for your skin. :)
