### ISSUE TITLE
Feature Request: unbuyable products

### ISSUE THREAD

**Issue by hairydogltd** [cubecart/v6#111]
It would be useful to have a way to set a product that is displayed like any other product, but can't be bought. 

At present the only way I can see of doing that is by making it out of stock, but that only works if you prevent OOS stock being bought.

**Comment by bhsmither** [comment]
I am curious: what would be a "product" that could not be bought?

There are a few conversations on the forums about changing the phrase "This item is currently out of stock." to something less specific, or not having anything at all. Thus, no way to buy the product, but no indication as to why.

**Comment by abrookbanks** [comment]
Very true. It seems like a rather unique requirement.

**Comment by bhsmither** [comment]
$CTRL_ALLOW_PURCHASE could be set to false from a test using an available hook.

In the skin, there isn't a means of showing why. $COMMENTS could be used to hold a data-list(?) for something in the `<div class="options">` block.

**Comment by hairydogltd** [comment]
I can think of quite a few stores that sell things "off the peg" but also sell bespoke or customised items. The one I have in mind wants to be able to give an idea of price, but not take an order until the customer has contacted them about it.
However, it is very widely applicable. Most of what I do comes into that category!

Is there somewhere that I can find out about available hooks? I've yet to find any documentation for CubeCart - I've had to work out how it works from reading the code.

**Comment by hairydogltd** [comment]
Oops!

**Comment by bhsmither** [comment]
https://support.cubecart.com/index.php?/Knowledgebase/List/Index/46/developer-articles
But, yes, it's coming to understand CubeCart by reverse engineering the code.

*"be able to give an idea of price, but not take an order until"*
OOS would certainly do that, but that is a store-wide setting - which you said you do not want.

What "setting" or "characteristic" would you want to name that aspect of a product such that it can be seen, but "individually" and "uniquely" not able to purchase?

**Comment by hairydogltd** [comment]
Ideally, you could mark a product (or a product option) "Display only" so that it is visible with a price, but can't be bought. 

As it stands, a product can be "on" or "off" depending on its status setting. If in a non-visible category It can be invisible but still buyable. It is only buyable if in stock or if buying OOS items is enabled. 

What is needed is to build on that logic so that a product can be visible or not visible, buyable or not buyable if in stock, and also if OOS. So the obvious (but maybe not the best or easiest to implement) is to have two options each with three statuses for a product

Visible if in stock / visible whether or not in stock / invisible
Buyable if in stock / buyable whether or not in stock / not buyable

How would an unbuyable product work? Perhaps the user can put it into a basket, but not buy it. Perhaps instead of "add to Basket" it says "add to wishlist" or "enquire about this product". I don't really mind how it works, but I'd like to see the basic functionality available. I can see quite a few applications for it.

**Comment by havenswift-hosting** [comment]
As Al said previously this is quite an unusual (unique) requirement and probably better suited to a custom plugin rather than having changes in the core product so maybe look for a developer to custom develop something for you

**Comment by abrookbanks** [comment]
I'm on the fence TBH.

**Comment by hairydogltd** [comment]
I can think of half a different current clients with ecommerce websites that would use this /today/. 

The ability to control OOS purchase by product is very important, and almost universally useful in my experience. 

Few stores have ALL products on the same availability: they will have some items they can sell when OOS and others that would take too long to restock. So a site-wide setting is not what they want. 

Usually they fudge this by setting the items that can be sourced more easily with a stock level of 1010 (assuming they have 10 in stock) and a low stock alert at 1005 but this isn't ideal.

**Comment by abrookbanks** [comment]
I agree. Implementing it now. Very simple and very powerful.

**Comment by abrookbanks** [comment]
We need a restock date too.

**Comment by abrookbanks** [comment]
# Admin Screenshot
![screen shot 2015-01-29 at 13 22 54](https://cloud.githubusercontent.com/assets/4520803/5958202/01ef765a-a7ba-11e4-85a5-a649819a340f.png)

**Comment by abrookbanks** [comment]
I've closed this. Please reply back if I missed anything and I can reopen.

**Comment by hairydogltd** [comment]
I'm not sure about the labels. I assume that the "Status" checkbox means "Visible" . If so, Visible would be a better label.

The "Available for purchase" checkbox presumably means people can buy it. But does that mean always? Or just when there is stock? 

This could be a three-state checkbox: selected meaning always, blank meaning never and the "filled in" undefined state meaning "when there is stock".

In face both checkboxes could have the same three states. Or they could be sets of three radio buttons - if easy to code, that would be clearer to shop owners.

**Comment by abrookbanks** [comment]
I'm not sure about the labels. I assume that the "Status" checkbox means "Visible" . If so, Visible would be a better label.

>> Maybe "Enabled" is better than status.

The "Available for purchase" checkbox presumably means people can buy it. But does that mean always? Or just when there is stock?

>> Other conditions come first. It will show out of stock if thats the case as a priority if those such restraints are in place.

This could be a three-state checkbox: selected meaning always, blank meaning never and the "filled in" undefined state meaning "when there is stock".

>> Thats getting too complex and may introduce bugs which I don't want to do at this stage of the game. I can add documentation. 

In face both checkboxes could have the same three states. Or they could be sets of three radio buttons - if easy to code, that would be clearer to shop owners.

**Comment by hairydogltd** [comment]
I think the label should be clear and explanatory. Neither "Enabled" nor "Status" actually tell you anything specific. Does it mean the product can be seen or that it can be purchased, or both? Whatever the checkbox does should be described by the label.

I think you are saying that "Available for Purchase" being selected means it will show "out of stock" (or be available for purchase if OOS purchases are enabled globally), but I'm not sure how that addresses the issue of per-product OOS purchases.

If not selected, the product can't be purchased. Clearly if it can't be purchased, the stock levels won't change unless the admin changes them.

**Comment by hairydogltd** [comment]
I think that what emerged in beta 4 looks fine.

**Comment by abrookbanks** [comment]
Excellent!!
