### ISSUE TITLE
NoImage Does Not get Rendered

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1111]
As opposed to product and category images that get rendered to alternate sizes according to the skin's config.xml, the default `noimage` does not. Thus, if a mod to the skin involves getting a product or category image displayed, and at this location there is no declared specific width in place, the `noimage` image gets displayed full size.

For example, in element.navigation_tree.php, where there is no maximum width -- to accommodate an unknown string length of category name:
```
<a href="{$BRANCH.url}" title="{$BRANCH.name}"><img src="{$BRANCH.img}" />{$BRANCH.name}</a>
```
where `{$BRANCH.img}` comes from:
```
$GLOBALS['catalogue']->imagePath($catData[0]['cat_image'], 'gallery', 'url')
```
the result is not a **gallery sized** `noimage` image.

Suggest that `Catalogue->imagePath()` send `$default_image` through GD to get the actual requested size.

**Comment by bhsmither** [comment]
I am making a reference to #366.

**Comment by abrookbanks** [comment]
I'm on the fence here. With responsive sites image width and height is becoming a little redundant.

**Comment by bhsmither** [comment]
This assertion implies that the general process of rendering/caching sized images is no longer a necessary thing.

So, use the source image for every purpose?

**Comment by abrookbanks** [comment]
Possibly.. or a halfway house... Instead of variations close together like.. 
30, 80, 105, 300, 600, 800

We have:
100, 300, 900

**Comment by abrookbanks** [comment]
I suppose strictly speaking as you have suggested the placeholder images should be adapted like the actual product images. In an ideal world a store would have no products without images.

**Comment by abrookbanks** [comment]
![screen shot 2016-08-08 at 17 42 55](https://cloud.githubusercontent.com/assets/4520803/17488071/8ff7a8b4-5d8f-11e6-8bad-9a81107e29b2.png)
![screen shot 2016-08-08 at 17 43 37](https://cloud.githubusercontent.com/assets/4520803/17488090/adb618a4-5d8f-11e6-97ab-71b3f989f02e.png)

**Comment by abrookbanks** [comment]
![screen shot 2016-08-08 at 17 45 18](https://cloud.githubusercontent.com/assets/4520803/17488125/db298c58-5d8f-11e6-986e-9754d0300c52.png)

**Comment by abrookbanks** [comment]
![screen shot 2016-08-08 at 17 46 13](https://cloud.githubusercontent.com/assets/4520803/17488163/fa893328-5d8f-11e6-9134-1a4a26bafaa7.png)

**Comment by bhsmither** [comment]
You might also want to add a comment in the config.xml file that for any new image size, one would also need to create a matching noimage in the skin's /images/ folder.

**Comment by bhsmither** [comment]
Well, let me double-check what you did to the GUI and Catalogue code.

**Comment by bhsmither** [comment]
I see what happens -- the skin's default image does get rendered and cached, but into a distinct folder for each skin.

Nice!

**Comment by abrookbanks** [comment]
Yeah it worked out well. Thanks for such a cool suggestion. :)
