### ISSUE TITLE
Auto-load more products as user scrolls down page

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1113]
Many modern websites dynamically load content as the user scrolls down the page, and it might be a nice addition to CubeCart.

CC already features the 'More v' button - it would simply be a matter of automatically 'clicking' this button for the user as they approach the bottom of the page.

**Comment by bhsmither** [comment]
Ebay used to do that. The latency drove me to invent a few new curse words.

While the ajax request was "asynchronous", rendering and re-running whatever javascript is involved caused the scroll action to stop until the DOM had finished updating.

Ebay stopped doing that a while ago. I think even Google's Image Search stopped doing that as well.

**Comment by abrookbanks** [comment]
I agree its a pain in the neck.. how do you ever get to click the document links art the bottom?

CubeCart can do this if you want with a little custom coding.

**Comment by briansandall** [comment]
Fair points. I was just on a website that it seemed to work very well for, and thought I'd throw the idea out there.

Since it can be implemented with just a little client-side skin editing and doing so may have undesirable consequences for some stores, there isn't really any reason to add it to the core code at this time.

Thanks for the feedback!
