### ISSUE TITLE
Ajax pagination with back button

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1115]
If a customer scrolls through several pages of items with the More button, clicks on a product, then uses the back button to return to the product list... they are taken back to the beginning. Hopefully there is some way to improve that behavior.

**Comment by cb2004** [comment]
This is exactly why I use traditional pagination. You can improve the behavior with a plugin, some $ and some custom code:

http://infiniteajaxscroll.com/

Or wait for Al to implement a solution.

**Comment by abrookbanks** [comment]
Yeah this is a bit of a killer. There's got to be a solution. Goin back either needs to somehow load cached data or it needs to alter the SQL to load x amount of pages at once.

**Comment by abrookbanks** [comment]
This works well but I want to make further improvements still tomorrow.

**Comment by Dirty-Butter** [comment]
I haven't added the cookie set code yet, but I DID add the pagination improvement to our test site last night - IT'S GREAT!!! Thank you!

**Comment by abrookbanks** [comment]
Wonderful. I've improved it a lot today ad on back it will even scroll the page down to where it was before.

**Comment by abrookbanks** [comment]
I think this can be closed now.

**Comment by havenswift-hosting** [comment]
An excellent enhancement  !!

**Comment by abrookbanks** [comment]
Here is a preview: http://static.cubecart.com/issue-1115.mp4

**Comment by Dirty-Butter** [comment]
VERY impressed!

**Comment by abrookbanks** [comment]
Determined to make CC the best in market segment. I think 2017 will be a good year.

**Comment by briansandall** [comment]
It would be even slicker if going back took you to exactly where you left off (i.e. the customer wouldn't have to scroll down). Even as is, it is much improved over the original - nice work!

**Comment by abrookbanks** [comment]
Yeah it would.. I think that would need a listener on the actual scroll rather than the button click. 

I'll have a think about this.
