### ISSUE TITLE
Requesting New Hooks - various files

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1116]
Search the admin/sources directory for 
`$GLOBALS['smarty']->assign('THEAD', $thead_sort);`

BEFORE EACH add a new hook.

Example:
`foreach ($GLOBALS['hooks']->load('admin.product.table_head_sort') as $hook) include $hook`

This will allow easier modification of table headers within the admin skin, ideal if youve edited the custom skin and want to make that column sortable and not lose the change when doing an update.

Files:
products.index.inc.php (admin.product.table_head_sort)
orders.transactions.inc.php
orders.index.inc.php  (admin.orders.table_head_sort)
customers.index.inc.php

**Comment by abrookbanks** [comment]
Thanks Alec
