### ISSUE TITLE
Issue #521 still an issue - Add to Basket button for negative stock values

### ISSUE THREAD

**Issue by jasehead** [cubecart/v6#1118]
Add to Basket is still an option when product value is set to minus one or less (eg. for managing backorders or preorders).  There was a fix attempted in May 2015 but the problem still persists in Cubecart 6.0.11.  The reason the fix didn't work is because the {if $product.available <= 0} line checks whether a 1 or 0 enum is set for availability.  What is required is that $product.quantity integer is checked - although this may be complicated if using a product matrix.  Files to be reviewed are Foundation/templates: content.category.php, content.homepage.php and content.product.php - to get close search for {if $product.available <= 0} - four occurrences in three files.

**Comment by jasehead** [comment]
To be clear - Add to Basket should not be available if no stock is available

**Comment by jasehead** [comment]
To be clear - Add to Basket should not be available if stock quantity/matrix is zero or less

**Comment by cb2004** [comment]
Same? https://github.com/cubecart/v6/issues/1103

**Comment by jasehead** [comment]
Yes. Any fix also needs to be tested with a product matrix and that there are four occurrences in three files affected: Foundation/templates: content.category.php, content.homepage.php and content.product.php

**Comment by Noodleyman** [comment]
this is actually a very complex issue, essentially you want to hide out of stock product options. Not an issue if you only have a single option, but gets more complex when you start to look at multiple item combinations within the matrix. Using standard code, it's just not going to happen. However... I solved it as part of this module
https://www.noodleman.co.uk/cubecart-absolute-prices-for-product-matrix-options.html

**Comment by abrookbanks** [comment]
I've spend so long on this issue and just haven't come up with the goods.

**Comment by Noodleyman** [comment]
at it's core, it would require a redesign of the way options work in CubeCart so will have a huge impact.... or use my module where I've essentially added an extra mode for product options ;)

**Comment by briansandall** [comment]
I've got a working (though somewhat outdated) branch that accomplishes this, among other things:
https://github.com/briansandall/v6/commits/902_prod_avail

I proposed integrating some or all of these changes into the core back on issue #814 and #902, but nothing ever came of it.

**Comment by jasehead** [comment]
The issue is: bad customer experience.  Showing an Add to Basket button means that the item should be in stock. Clicking on the Add to Basket button and then finding that the item is NOT in stock is a bad customer experience. The logic should be COUNT ANY POSITIVES, along the lines of (1) is the basic stock level greater than zero, and/or (2) are any of the stock matrix levels greater than zero - if any one of these is positive then the Add to Basket button should be visible. No point in summing the values because some admins might use negative stock values, so you have to count any positives rather than sum all items. The Add to Basket button should NOT be visible if all values (basic stock and stock matrix) are zero OR negative. This is a persistent bug in basic functionality and shouldn't require a mod purchase to fix. </RANT>

**Comment by Noodleyman** [comment]
it's not a bug if it's currently working as designed.

your talking about a re-design of the way it works. that will have huge impacts.

**Comment by jasehead** [comment]
No, I'm talking about a button that says you can buy something actually
letting you buy something - basic User Experience.  If it works as designed
for basic stock if stock = 0, then why can't it work if basic stock = ­1?
Just fix that one thing ­ stop the Add to Basket button showing if basic
stock is zero or less.

Forget about the product matrix.

From:  Noodleyman <notifications@github.com>
Reply-To:  cubecart/v6
<reply+00b66871680da1fc21d1ac7c4ddd5b005fbe278b12cda9de92cf000000011384b8409
2a169ce096a42c1@reply.github.com>
Date:  Friday, 24 June 2016 6:28 PM
To:  cubecart/v6 <v6@noreply.github.com>
Cc:  Jason Follett <jase@jasesbooks.com.au>, Author
<author@noreply.github.com>
Subject:  Re: [cubecart/v6] Issue #521 still an issue - Add to Basket button
for negative stock values (#1118)


it's not a bug if it's currently working as designed.

your talking about a re-design of the way it works. that will have huge
impacts. 


You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cubecart/v6/issues/1118#issuecomment-228293852> , or
mute the thread 
<https://github.com/notifications/unsubscribe/ALZocWKjMjkJno7DPcD3dIaH1zngNc
zgks5qO5xAgaJpZM4IrxPD> .

**Comment by jasehead** [comment]
No, I'm talking about a button that says you can buy something actually
letting you buy something - basic User Experience.  If it works as designed
for basic stock if stock = 0, then why can't it work if basic stock = ­1?
Just fix that one thing ­ stop the Add to Basket button showing if basic
stock is zero or less.

**Comment by jasehead** [comment]
No, I'm talking about a button that says you can buy something actually letting you buy something - basic User Experience.  If it works as designed for basic stock if stock = 0, then why can't it work if basic stock = ­1?

Just fix that one thing ­ stop the Add to Basket button showing if basic stock is zero or less.

Forget about the product matrix.

**Comment by jasehead** [comment]
No, I'm talking about a button that says you can buy something actually letting you buy something - basic User Experience. If it works as designed for basic stock if stock = 0, then why can't it work if basic stock = ­1?

Just fix that one thing -­ stop the Add to Basket button showing if basic stock is zero or less.

Forget about the product matrix.

**Comment by jasehead** [comment]
Tested and working.  This fixes the issue with the Add to Basket button showing if stock level is less than zero.

skins/foundation/templates/content.homepage.php
skins/foundation/templates/content.category.php

Find this (more than one occurrence):
{elseif $product.ctrl_stock && !$CATALOGUE_MODE}

Change to:
{elseif $product.ctrl_stock && $product.stock_level > 0 && !$CATALOGUE_MODE}

**Comment by briansandall** [comment]
@jasehead The problem with that solution is it doesn't take into account matrix stock levels, so if you have a product that is like a T-Shirt with size and color options, stock level is likely handled at the matrix level and the product will always appear out of stock on the homepage and category page.

Ideally, the base product stock level as used in these situations would be the max of the base product and all matrix entries for said product, in which case your edits would probably work great. I don't have time to mess with it right now, but it should be somewhere in catalogue.class.php.

**Comment by jasehead** [comment]
Also, still not working for products that are (1) available for purchase, (2) use stock level is set to no ($product.ctrl_stock), (3) stock level is zero

However, the way that the Add to Basket button is determined on the individual Product page appears to be more robust (skins/foundation/templates/content.product.php - lines 114 to 136) - maybe this method can be applied to content.homepage.php and content.category.php

But I'm unfamiliar with the code, so my attempts are a very blunt axe against hard timber - someone else could do better.

**Comment by jasehead** [comment]
Here is my very simple solution for showing out of stock for negative stock values - just check the first character in the string to see if it is negative.

Find this:
```
{elseif $product.ctrl_stock && !$CATALOGUE_MODE}
```

Change to:
```
{elseif $product.ctrl_stock && $product.stock_level|substr:0:1 neq '-' && !$CATALOGUE_MODE}
```

NOTE: The character immediately after $product.stock_level is a PIPE not a letter L

This fix works for content.homepage.php and content.category.php

It should also work for products using a product matrix because $product.stock_level is used by the product matrix to show stock ranges on the product page (specification tab).

**Comment by briansandall** [comment]
PR #1406 should resolve this issue.
