### ISSUE TITLE
Bug in cubecart.class.php

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1119]
When a customer is viewing their list of previous orders, the list is limited to 15 orders because the pagination is broken.

This is being caused by the re-use of the $orders variable to gather the paginated data from the DB which then overwrites the earlier list of obtained orders.

a count() is then done on $orders, but we only ever count the total orders in the paginated results, meaning max records = 15.

To fix:
around line 2370 FIND:
```
$page = (isset($_GET['page'])) ? $_GET['page'] : 1;
if (($orders = $GLOBALS['db']->select('CubeCart_order_summary', array('cart_order_id', 'ship_tracking', 'order_date', 'status', 'total', 'basket'), array('customer_id' => $GLOBALS['user']->get('customer_id')), array('cart_order_id' => 'DESC'), $per_page, $page)) !== false) {
					foreach ($orders as $i => $order) {
```

RENAME $orders to something different such as $paginated_orders. note there are two occurances, once in the query and once in the foreach. 

This fixes pagination of order history.

**Comment by abrookbanks** [comment]
I'll have to look deeper into this but renaming this means that the count will always return 0 as the array $orders is no longer set.

**Comment by Noodleyman** [comment]
but it is set, it already exists and then gets re-used it and overwritten with a different result. 

The proposed solution above is tested and working on a customer site ;)

**Comment by Noodleyman** [comment]
$orders exists, and contains the right amount of items which should be used for the count.

$orders then gets populated again with the paginated results.

$orders is then counted to see how many pages are required, but this will always return 1 as it happens after it's been repopulated with the paginated rows ;)

**Comment by abrookbanks** [comment]
Yes you are right. Duh!

**Comment by abrookbanks** [comment]
Thanks!! :)
