### ISSUE TITLE
One-item drop-downs

### ISSUE THREAD

**Issue by hairydogltd** [cubecart/v6#112]
When there is only one option in a list (such as delivery address or delivery method), why is there a drop-down list with just one option? 

It would be more user-friendly if a listbox was only offered when there was a choice.

**Comment by havenswift-hosting** [comment]
A very good point !  It is little things like this that can make a system feel much more user friendly

**Comment by abrookbanks** [comment]
I would say this is a bug. Thanks!! I'll get started on this on Monday hopefully.

**Comment by abrookbanks** [comment]
So if there is one option that is required CubeCart will pre select it by default.

**Comment by hairydogltd** [comment]
I completely disagree. It is crap to expect users to click a drop-down to discover there are no alternatives.

**Comment by abrookbanks** [comment]
Why have one option in the first place then? Surely that's crap store management??!!

**Comment by abrookbanks** [comment]
Ok, ok keep your knickers on!! :-) happy to discuss this and get it right.

**Comment by hairydogltd** [comment]
Fair enough. Let's give the reasons. There may only be one payment method, one delivery method, one delivery address. 

The opposite can be true too, though!
Sometimes it is good to make the customer actively choose, even if there is just one option in stock.

One of our clients sells LED lights in a range of shades of white (chosen from "extra warm/warm/commercial/natural/pure/bright/cool"). They actively make the customer choose a colour to be sure the customer has not just settled for the default - but they use radio buttons, not drop-downs. With radio buttons, you can see the available range at a glance: no need to open a list. With a drop-down, users often scroll the mouse wheel and change the option without noticing.

**Comment by abrookbanks** [comment]
Thanks for the feedback. I want to add radio buttons too and completely agree with you. I'll get this done tomorrow.

**Comment by hairydogltd** [comment]
A useful feature in Zen Cart that I'd like you to emulate is a "display only" option type. Also the default when set. 

So when the buyer is asked to select an option, the default is "choose a whatever" but because that default is display only, the item won't go into the basket with that option still selected. 

I'm reluctant to keep suggesting features in Zen Cart. I'm trying to get way from its featureitis and bloat. Hence me not wanting anything of the Foundation skin, which is several times the file size of the v5 skins. But a display-only option would be useful.

**Comment by hairydogltd** [comment]
Will you be updating the v5-derived skins to use this?

**Comment by abrookbanks** [comment]
No sorry.
