### ISSUE TITLE
Requesting New Hook - categories.index.inc.php

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1129]
requesting a new hook after
`if (!empty($update) && is_array($update) && Admin::getInstance()->permissions('categories', CC_PERM_EDIT)) {`

This will allow a hook to add additional data to the $update array, meaning dev's can update additional DB fields from the category overview page.

Recommending:
`foreach ($GLOBALS['hooks']->load('admin.category.list_pre_update') as $hook) include $hook;`

**Comment by abrookbanks** [comment]
Thanks.
