### ISSUE TITLE
Restrict Registration to selected countries

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#113]
It would be great to be able to restrict registration to chosen countries out of the complete list by having a tick box selector in the admin countries screen and then only displaying those selected countries in the dropdown in the registration page

**Comment by abrookbanks** [comment]
:+1:

**Comment by abrookbanks** [comment]
You can do this by deleting them but I suppose you might not always want to do that incase you want them back.

**Comment by havenswift-hosting** [comment]
Yes obviously can delete them but that causes problems with customers already registered if you then want to restrict whether temporarily or permanently who can register

**Comment by abrookbanks** [comment]
completely agree

**Comment by abrookbanks** [comment]
Done! :) This ONLY affects drop downs on the front end of the store.
![screen shot 2015-01-23 at 17 04 53](https://cloud.githubusercontent.com/assets/4520803/5878858/0269656a-a322-11e4-809f-5eac3ccb1719.png)

**Comment by abrookbanks** [comment]
![screen shot 2015-01-23 at 17 17 45](https://cloud.githubusercontent.com/assets/4520803/5879059/dfc258b2-a323-11e4-8eda-0d8ae1c9561b.png)

**Comment by havenswift-hosting** [comment]
Perfect - thanks for adding so quickly
