### ISSUE TITLE
Unused line in content.register

### ISSUE THREAD

**Issue by cb2004** [cubecart/v6#1132]
Probably super picky but I dont think this line is used:

`<div class="hide" id="validate_required">{$LANG.form.required}</div>`

**Comment by abrookbanks** [comment]
All the instances of {$LANG.form.required} in that file are in use? Which line do you mean?

**Comment by cb2004** [comment]
Sorry, it stripped my html. I have edited my first post. In the cubecart.validate.js file it doesnt look like this relates to anything.

**Comment by abrookbanks** [comment]
It's used here:
https://github.com/cubecart/v6/blob/master/skins/foundation/js/2.cubecart.js#L157
