### ISSUE TITLE
Change option_name DB type to VARCHAR

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1135]
Similar to #548 - the field is currently of type VARBINARY and limited to 30 characters.

**Comment by briansandall** [comment]
Searching through db/install/structure.sql for 'varbinary' reveals many more cases that could potentially use a re-type.

**Comment by abrookbanks** [comment]
It *should* be 50.
https://github.com/cubecart/v6/blob/master/setup/db/upgrade/5.0.0b1.sql#L447

However install sets it to 30!
https://github.com/cubecart/v6/blob/master/setup/db/install/structure.sql#L544

**Comment by abrookbanks** [comment]
Thanks for this!! :P
