### ISSUE TITLE
Explicit related products

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1138]
CubeCart currently polls the database for products purchased together and uses those results as 'related products'; it would be really nice to have an extra tab when editing a Product in which other products could be explicitly set as 'related' and thus always show up.

It would also be slick if related products showed up on the product page in addition to when viewing the basket.

**Comment by cb2004** [comment]
+1. We are up to version 6 now and this functionality has always been achievable but with a module.

**Comment by abrookbanks** [comment]
Thanks for this. I think it would be popular.
