### ISSUE TITLE
Enhancement Request - Enhance Order History

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1139]
Currently the order history tab only includes the date/time and status the order changed to. It would be very helpful to improve this to include if the status change was triggered by a user action or a gateway, and also capture the admin user details.

**Comment by abrookbanks** [comment]
I like this a lot.

**Comment by abrookbanks** [comment]
![screen shot 2016-08-09 at 13 27 38](https://cloud.githubusercontent.com/assets/4520803/17516227/0ceafede-5e35-11e6-87e5-ada7bb135c65.png)
If customer cancels the order the initiator will be "Customer".
