### ISSUE TITLE
6.0.12: order pagination is not working

### ISSUE THREAD

**Issue by cb2004** [cubecart/v6#1140]
I remember seeing a bug report about this being fixed, however I just upgraded to 6.0.12 and the order pagination does not show. Switched to the foundation skin and it doesn't show on that either.

**Comment by abrookbanks** [comment]
![screen shot 2016-08-08 at 11 48 01](https://cloud.githubusercontent.com/assets/4520803/17477576/f30505a0-5d5d-11e6-8eaa-f714a735d24d.png)

**Comment by abrookbanks** [comment]
"foundation skin" indicates front end.. I'll check this..
