### ISSUE TITLE
Wrong Timestamp on Sitemap product urls in 6.0.12

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1141]
https://forums.cubecart.com/topic/51402-sitemap-timestamp-issue-since-6012/

Creates a bad timestamp on the CC demo store as well.

**Comment by bhsmither** [comment]
In seo.class.php, line 722:
```
$this->_sitemap_link(array('key' => $key, 'id' => $id), (isset($record['updated']) && !empty($record['updated'])) ? (int)$record['updated'] : time(), $type);
```
This part, `(int)$record['updated']` is at fault.

`$record['updated']` is stored in the database as a SQL TIMESTAMP, which is a textual format rigidly looking like an international representation of a date/time expression. It is **not** the UNIX timestamp integer. Thus, casting this to (int) will get you zero. (Later, applying to date(), gets you the beginning of when computers keep track of time.

Suggest removing the casting, or casting to `(string)`.

**Comment by Dirty-Butter** [comment]
I'd be glad to test whatever you tell me to change - but you know me - you will have to spell it out in detail.

**Comment by Dirty-Butter** [comment]
PS. I have an old sitemap in a backup from 6/14/16 on 6.0.11 that worked properly.
