### ISSUE TITLE
Shopping Basket Maintenance

### ISSUE THREAD

**Issue by wairds** [cubecart/v6#1143]
Scenario:
1. Add item to shopping basket.
2. View basket. Item in basket.
3. Click on home button. Basket icon on home screen shows empty and states it is empty when clicked on.
4. Go to another screen and the basket shows an item.
5. Go to shopping basket and click Bin icon. Item still in shopping basket.
6. Click on Update Basket. The following message appears "Unfortunately there are no suitable shipping methods available for your order. This may be because the total weight of your order is too high or we cannot ship to your country. Please contact a member of our staff for any further inquiries."
7. Click Home button. Basket shows empty as on other screens.
8. Add item to basket.
9. View basket. The following message appears "Unfortunately there are no suitable shipping methods available for your order. This may be because the total weight of your order is too high or we cannot ship to your country. Please contact a member of our staff for any further inquiries."
10. Clear cache and things go back to normal.

**Comment by abrookbanks** [comment]
Hi @wairds I think this is specific to your store and some caching issue. Please do submit a technical support ticket if you want me to take a look for you.
