### ISSUE TITLE
content.addressbook.php has no validation messages

### ISSUE THREAD

**Issue by cb2004** [cubecart/v6#1145]
As the title says, this has no validation messages in the 3.cubecart.validate.js, or tags to link it to in the template file content.addressbook.php

**Comment by abrookbanks** [comment]
It doesn't? Maybe I misunderstand... Please let me know. 
![screen shot 2016-08-08 at 11 07 36](https://cloud.githubusercontent.com/assets/4520803/17476527/6f4e5b58-5d58-11e6-90c3-94e083f0f025.png)
![screen shot 2016-08-08 at 11 08 01](https://cloud.githubusercontent.com/assets/4520803/17476539/7816d396-5d58-11e6-965a-60c66303cf3b.png)

**Comment by cb2004** [comment]
These are the standard jQuery Validation plugin messages. Multilingual would not be managed.

**Comment by abrookbanks** [comment]
It is multilingual. 

Please see this in 3.cubecart.validate.js

```
$.extend(jQuery.validator.messages, {
        required: $('#validate_field_required').text()
    });
```

And in the page source:
content.addressbook.php:
```
<div class="hide" id="validate_field_required">{$LANG.form.field_required}</div>
```

**Comment by abrookbanks** [comment]
Happy to reopen if I'm wrong or misunderstood this.
