### ISSUE TITLE
6.0.12: update billing address and default delivery address sometimes does not work

### ISSUE THREAD

**Issue by cb2004** [cubecart/v6#1146]
I am unsure on the steps to reproduce this, however sometimes when you select to update and address for billing and default it does not work. This was verified using the Foundation skin.

To reproduce, make sure there are 2 addresses in the address book. Whatever address is not billing and default delivery, go into that address and try and select them both, hit save. You may get the failure message. If not and it saved, go back into the address which is now not billing/default delivery and try and save that. You will get the error if you repeat this step.

**Comment by abrookbanks** [comment]
I haven't been able to reproduce this. 
http://static.cubecart.com/github-1146.mp4

Maybe the issue happens with old addresses prior to v5/v6 upgrade?

Happy to reopen if we have more info.
