### ISSUE TITLE
DeleteOrder Deletes Related Without Regard

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1147]
Currently, `Order->deleteOrder()` attampts to delete the record from CubeCart_order_summary.

Regardless of success or failure, related records are deleted from five other tables.

Suggest not deleting related records unless the deletion of the order summary actually succeeds.

Suggest keeping the hook out of the "true" block, which means hook code should test for the value of `$deleted`.

**Comment by abrookbanks** [comment]
I think this is wise. Thanks Brian.
