### ISSUE TITLE
Navbar (Still) Has (Some) Absolute URLs

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1148]
See:
https://forums.cubecart.com/topic/51339-nav-bar-categories-ssl-problems/

**Comment by abrookbanks** [comment]
Thanks Brian! :)

**Comment by bhsmither** [comment]
I am not finding the suggestion made in this post:
https://forums.cubecart.com/topic/51339-resolved-nav-bar-categories-ssl-problems/?do=findComment&comment=218605
