### ISSUE TITLE
6.0.12: checkout image size cant be changed

### ISSUE THREAD

**Issue by cb2004** [cubecart/v6#1149]
The files for medium and small (although I do not use them) contain:

`<img src="{$item.image}" alt="{$item.name}" width="50">`

This is taken from the gallery reference in config.xml and cannot be changed to something else like it can elsewhere in cubecart, i.e. {$item.thumbnail}

**Comment by cb2004** [comment]
Not sure the fix I see here will fix what I was talking about. You have taken the width out of the html but you can't select a different image size from the configuration.xml

**Comment by abrookbanks** [comment]
Line in question is 1546 of cubecart.class.php
```$product['image'] = $GLOBALS['catalogue']->imagePath($gc['image'], 'gallery', 'url');```

A fall back will be needed for backward compatibility...
