### ISSUE TITLE
Star rating in Kurouto Skin

### ISSUE THREAD

**Issue by hairy-dog** [cubecart/v6#115]
Somehow this issue got closed without being fixed. You can't select a star rating in Kurouto skin - The review gets submitted with one star.

**Comment by hairydogltd** [comment]
How has this been fixed? I'd like to sort it on my local copy as well. The only files I can see in the commit are in the admin section, and that's not where the problem is/was. The admin side of reviews work fine: it's the customer side that is broken.

**Comment by abrookbanks** [comment]
It will be fixed when you upgrade to Beta 4.

**Comment by abrookbanks** [comment]
Alternatively.. download the latest build and apply any database changes in the  setup/db/upgrade/6.0.0b4.sql file. This issue *has* been resolved. It wasn't a simple one line code fix.

**Comment by hairydogltd** [comment]
Ah, that explains it, thanks. It was the tag on the commit that misled me.

**Comment by abrookbanks** [comment]
Yeah so the issue was that v5 skins use jQuery 1.7. I had to split out the admin side of the store from the /js folder and have a big reorganisation.  The /js folder now is only included for old v5 skins and the contents is the same as 5.2.16.

**Comment by hairydogltd** [comment]
Hmm. I've done that, but now the Store Settings page has two non-functional checkboxes where  there should be just one that works:
![feature settings](https://cloud.githubusercontent.com/assets/10561885/5904903/ffb1696c-a583-11e4-81d0-c1f6c9fac480.png)

**Comment by abrookbanks** [comment]
It's probably got something to do with the CSS change you made to change to checkboxes. If not try a hard refresh.

**Comment by hairydogltd** [comment]
I overwrote that CSS when upgrading, and made sure it isn't cached by making a trivial change and uploading it, and I cleared all the caches and I tried a browser I've not ever used before.

So I thought I'd try a clean install of the latest version. White screen.

**Comment by hairydogltd** [comment]
Just to confirm that replacing the whole of the Admin folder structure with one from the latest version seems to have resolved this issue for me, thanks.

**Comment by abrookbanks** [comment]
Thanks for letting me know. Looks like you had a late one!
