### ISSUE TITLE
6.0.12: coupon interactions in the checkout have no messages for add/remove

### ISSUE THREAD

**Issue by cb2004** [cubecart/v6#1153]
There are no messages when a coupon is added/removed

**Comment by abrookbanks** [comment]
This is a bit tricky because if there is a status message the checkout is blocked from moving on at next submit. "Something needs doing".

Maybe a "different" notification can be added.

**Comment by abrookbanks** [comment]
I don't think any changes are needed. There are three scenarios:

# Coupon is not recognised
![screen shot 2016-09-21 at 17 06 43](https://cloud.githubusercontent.com/assets/4520803/18719078/cb6b624a-801d-11e6-8895-3134e72eedbe.png)

# Coupon is added
![screen shot 2016-09-21 at 17 07 23](https://cloud.githubusercontent.com/assets/4520803/18719105/e646f138-801d-11e6-9a52-30d200028651.png)

# Coupon is removed
![screen shot 2016-09-21 at 17 08 03](https://cloud.githubusercontent.com/assets/4520803/18719119/fb65e8ee-801d-11e6-931c-434df9ecd02e.png)

**Comment by abrookbanks** [comment]
![screen shot 2016-09-21 at 17 15 17](https://cloud.githubusercontent.com/assets/4520803/18719357/fdb924de-801e-11e6-98ec-6575ae2cdeb8.png)

**Comment by abrookbanks** [comment]
![screen shot 2016-09-21 at 17 18 51](https://cloud.githubusercontent.com/assets/4520803/18719509/874c94ec-801f-11e6-94f3-7d3ab0dfa645.png)

**Comment by cb2004** [comment]
Cheers Al. UX is key for any site, especially ecommerce. It is such a worthwhile few lines of code in my eyes

**Comment by abrookbanks** [comment]
Welcome. I was worried before the notification would cause a block but I was wrong.

6.1 is looking fab. Thanks.

**Comment by abrookbanks** [comment]
I'm going to reopen on the grounds that it's a bit ambiguous on terms. Coupon, voucher and gift certificate.

Definitions need updating.

**Comment by Dirty-Butter** [comment]
I had to revert to 6.0.12 code for coupons.
See #1321
