### ISSUE TITLE
Credit Card Empty

### ISSUE THREAD

**Issue by rhonda604** [cubecart/v6#1154]
I have an issue that first appeared a couple of weeks ago--before I updated to CC6 6.0.11 -- I process my credit cards using a manual processing method and I had 2 customers who's cards just were captured and disappeared within 24 hours--My web developer was hired to update to the latest version and I checked with the Host server and nothing was out of place there with my SSL--so we waited to see if it was all corrected, but it has done it again with a fake card in place.

**Comment by abrookbanks** [comment]
The card capture module was not developed to store card data for any length of time. I would recommend restoreinbg a backup of the old store somewhere to regain access.

**Comment by rhonda604** [comment]
Thank you for the reply Al--can you tell me if this is something new--as I have sometimes had CC # on file for months while a special order was incoming and never had it 'empty' on me--can you tell me the time frame that it is 'safely held' for?

**Comment by abrookbanks** [comment]
Do you sell reviews, subscribers, likes, shares etc?

**Comment by rhonda604** [comment]
No, tangible products that ship ~
