### ISSUE TITLE
Basket and Checkout look the same

### ISSUE THREAD

**Issue by hairydogltd** [cubecart/v6#116]
I can't see a difference between View Basket and Checkout.
If they are different, what is the difference?
If they are not different, why have the extra step?

**Comment by abrookbanks** [comment]
They are completely different for me:

# Basket
![basket](https://cloud.githubusercontent.com/assets/4520803/5898978/3280ac5e-a54d-11e4-9ef9-5347e8273527.png)
# Checkout
![checkout](https://cloud.githubusercontent.com/assets/4520803/5898980/37fc6362-a54d-11e4-8d56-e4a677c59c35.png)

**Comment by abrookbanks** [comment]
Ahh I think I get it. If you ARE logged in they do the same. I believe this can be fixed by removing view basket is logged in. :)
