### ISSUE TITLE
6.0.12 Basic search results do not adhere to Product List Sorting set by admin 

### ISSUE THREAD

**Issue by jasehead** [cubecart/v6#1162]
Search results from a basic search (box.search) do not respect the Product List Sorting set by admin in Store Settings > Layout.

However, the advanced search (content.search) does use this setting to set one of the controls, and so search results for advanced search will respect the Product List Sorting setting.

Can the basic search results please use the Product List Sorting setting?

**Comment by abrookbanks** [comment]
I would say no because the search lists by "relevance" which should be (in most cases) more suitable for the customer to locate what they are looking for.

**Comment by bhsmither** [comment]
Simple skin edit seems to have solved it.

See: https://forums.cubecart.com/topic/51998-need-help-with-sort-with-search/

**Comment by abrookbanks** [comment]
@bhsmither I'm a bit lost here. Can you tell me specifically what code changes you recommend?
