### ISSUE TITLE
6.0.12 Remove Australian Bank Card from Card Capture

### ISSUE THREAD

**Issue by jasehead** [cubecart/v6#1163]
Bankcard in Australia and New Zealand was withdrawn from use in 2006. Any lines of code referring to Australian Bank Card in Card Capture and other gateway modules can be removed.

**Comment by jasehead** [comment]
VISA and MasterCard are the most common cards accepted by merchants in Australia (with American Express and Diners Club less common, and JCB or Discover very rare).
See: https://en.wikipedia.org/wiki/Bankcard and http://www.australia.com/en-us/facts/currency.html

**Comment by abrookbanks** [comment]
Thanks! I released 1.0.6 of this extension.
