### ISSUE TITLE
Feature request: handle 301 redirects if a url is changed

### ISSUE THREAD

**Issue by cb2004** [cubecart/v6#1164]
I use a fantastic CMS/CMF called ProcessWire, and if a url is changed the system handles this as a 301. It would be great if something like this was added to CubeCart.

**Comment by abrookbanks** [comment]
I like this a lot.

**Comment by cb2004** [comment]
@abrookbanks closed, not something that you would consider?

**Comment by abrookbanks** [comment]
All feature requests are now closed but have no milestone. We will review them in the future and reopen and add a milestone once in development. 

We have a lot of feature requests on here as open issues which makes CubeCart look buggy and unkempt. This way we see only current bugs and work in progress. :)

**Comment by cb2004** [comment]
@abrookbanks yeah, don't want it to look buggy. ProcessWire handles this situation like this:

https://github.com/processwire/processwire/issues/8

Works well.

**Comment by abrookbanks** [comment]
Kool, thanks for sharing.

**Comment by abrookbanks** [comment]
I still really like this one. I've moved it here: https://features.cubecart.com/topic/feature-request-handle-301-redirects-if-a-url-is-changed_8

**Comment by cb2004** [comment]
It's a good one. Massive SEO benefits.

**Comment by abrookbanks** [comment]
![Screenshot 2019-03-28 at 09 16 13](https://user-images.githubusercontent.com/4520803/55145862-763adc00-513b-11e9-9738-44b7ff0daa38.png)

**Comment by abrookbanks** [comment]
![Screenshot 2019-03-28 at 13 49 05](https://user-images.githubusercontent.com/4520803/55162706-45b96900-5160-11e9-8e6f-88bcbfb805cc.png)

**Comment by abrookbanks** [comment]
*** TESTING REQUIRED ***

**Comment by abrookbanks** [comment]
This seems to be working really well. No faults found.

**Comment by bhsmither** [comment]
I'm thinking that with the changes to the contents in the 'path' column in CubeCart_seo_urls, as well as the .htaccess file, this becomes very difficult for backwards compatibility.

Just making a comment -- I understand there was never a promise of backward compatibility.

**Comment by abrookbanks** [comment]
I don't think so but I'll check. They should be document relative.
