### ISSUE TITLE
Requesting New Hook - cart.class.php

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1165]
FIND:
if (isset($max_stock) && $max_stock <= 0) {

ADD AFTER:
foreach ($GLOBALS['hooks']->load('class.cart.add.max_stock') as $hook) include $hook;

REASON:
This allows custom logic/rules to be applied which can override the $max_stock variable, allowing selective overrides on a per product basis of stock level enforcement / rules.

**Comment by Noodleyman** [comment]
@abrookbanks , I made a cockup with this request... The hook was meant to go BEFORE the FIND line.. any chance it can be ammended?

**Comment by abrookbanks** [comment]
How very dare you! Hehe no problemo.. .

**Comment by Noodleyman** [comment]
Thank you Al :)

**Comment by abrookbanks** [comment]
Sorted.
