### ISSUE TITLE
Don't allow upgrade to 6.0.12 or above if php < 5.4

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1168]
With the minimum php requirement now being 5.4, then the current php version should be checked before going ahead with an upgrade and not allowed to continue otherwise it starts, fails and the store is left in a state where it doesn't work !

**Comment by abrookbanks** [comment]
If anything I think this should be a soft error with recommendation to upgrade PHP version in ACP. 

I believe that CubeCart will 99% work from PHP 5.2. The only known page to have issues < PHP 5.4 is the email templates admin management page.

**Comment by abrookbanks** [comment]
.. I am seeing lots of hosting companies only offering PHP 5.2!
