### ISSUE TITLE
Assign to Category Error

### ISSUE THREAD

**Issue by NaturalSigns** [cubecart/v6#117]
I'm running the new beta 6.0.0.b3 (really like some of the new feature by the way).  But ... using "Assign to Category" the first few products can be selected fine but the further down the products list I go the behavior gets erratic.  Example below, if i select the checkbox indicated it ticks the product 4 places above.  If i scroll down the list further i can't tick any products. 
![assign to category](https://cloud.githubusercontent.com/assets/10531097/5879687/3b884896-a329-11e4-9879-457c10e0ab37.png)

**Comment by hairydogltd** [comment]
replacing table width="70%" 
with table width="400px" 
solves the problem, and makes it much easier to use.

**Comment by hairydogltd** [comment]
The workaround that worked for me is to remove all the "reinventing the wheel" in the stylesheet, but whether that has adverse effects elsewhere I've not investigated.

In admin's layout.css around line 30

input[type="checkbox"]{
/*	margin: 0;
	position: absolute;
	z-index: 2;            
	cursor: pointer;
	outline: none;
	opacity: 0;
	_noFocusLine: expression(this.hideFocus=true); 
	-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";
	filter: alpha(opacity=0);
	-khtml-opacity: 0;
	-moz-opacity: 0;
	background-color: red; */
	width: 16px;
	height: 16px;
}
input[type="submit"].tiny {
	padding: 2px 4px !important;
}
.custom-checkbox {
/*	background: url(../images/0.png);
	width: 16px;
	height: 16px; */
}
.custom-checkbox.selected {
/*	background: url(../images/1.png); */
}

**Comment by abrookbanks** [comment]
@hairydogltd - For legacy reasons and consistency that block of CSS is needed unless you don't mind other "checkboxes" that are not actually checkboxes not keeping the theme. 

I can't reproduce this problem. Is there a specific browser?

**Comment by hairydogltd** [comment]
This problem shows in Firefox v35

I'm on a bit of a mission to reduce code bloat, so native checkboxes seem fine to me. 
My test site (which is responsive and is based on Kurouto) is 40k of js and 80k of templates. 
Your foundation skin is 578k of js and 358k of templates. Perhaps it adds functionality: I can't tell.

**Comment by abrookbanks** [comment]
It's yet to be minified which will help. It may be that some of the Foundation libraries can be removed too.

**Comment by abrookbanks** [comment]
On the current build the JS is approx 375Kb which is fairly acceptable in this day and age. I'll use Chrome Page Speed tools to optimize further.

**Comment by abrookbanks** [comment]
FF can't cope with the JS outside of the scroll area. Scroll area removed.
