### ISSUE TITLE
Editing customer order: one item's pricing options affecting other items

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1170]
When a product with price-affecting options is on an order for which inventory is being edited, any other product with options that has an option selection changed will be affected by the other item's currently selected option price value. Some screenshots ought to help explain:

Initial setup - note the first product option price modifier:
![cc_issue1170](https://cloud.githubusercontent.com/assets/14335170/16500095/ee5ab492-3eb7-11e6-8f0b-74474816dc39.png)

Changed selected option value for second product - note that the price has now changed by -$3.00 (the opposite of the above price modifier for the other product):
![cc_issue1170-2](https://cloud.githubusercontent.com/assets/14335170/16500125/157da6a6-3eb8-11e6-9805-3f57d681e937.png)

Testing with a negative value confirms that it is indeed the opposite value used - note that this was done after resetting the price to $20.00:
![cc_issue1170-3](https://cloud.githubusercontent.com/assets/14335170/16500137/29e00486-3eb8-11e6-8d15-1b4a1a821e8a.png)

**Comment by briansandall** [comment]
I suspect this is caused in admin.js, specifically the `productOptionPrices` function on line 160. Unfortunately, my JS / JQuery skills are not that brilliant especially when it comes to closures, but I'm pretty sure that the functions being returned from this function are not properly encapsulated, i.e. the same instance of each function is being used each time they are assigned, rather than distinct instances each with their own scope.

It's also notable that changing the second item's options to include price modifiers of their own does NOT overwrite the previously aggregated values: e.g. if the second product's 'Option A' has a modifier of +$5.00, changing the selected option for it still subtracts $3.00 from the unit price according to the first item's 'Option A.'

Note that the JS here also suffers from the same absolute pricing issues I have raised elsewhere.

**Comment by abrookbanks** [comment]
Line price wasn't reset for each product causing carry over values.

**Comment by briansandall** [comment]
Heh, of course. So simple - thanks Al!
