### ISSUE TITLE
6.0.12 Main product image does not zoom (related to #1075)

### ISSUE THREAD

**Issue by jasehead** [cubecart/v6#1175]
The fix used to not display a thumbnail if only one product image has broken the zoom on the main image.

In content.product.php - if $GALLERY && count($GALLERY)>1 - does not create a thumbnail gallery if there is only one image.

However, the script used in 2.cubecart.js for .open-clearing around line 62 says that when the main image is clicked then to simulate a click on the first thumbnail.  If there is only one image then the thumbnails are not created and so the script fails.

As per #1075, the workaround by B. Smither still allows the gallery to be created, but not displayed.  Because the thumbnail still exists the simulated click will work.

In content.product.php, try this (search for the first line to find the place)
```
            <a href="#" class="open-clearing" data-thumb-index="0"><img src="{$PRODUCT.medium}" alt="{$PRODUCT.name}" id="img-preview"></a>
            {if $GALLERY}
            <ul class="clearing-thumbs small-block-grid-3 medium-block-grid-5 marg-top" data-clearing>
               {foreach from=$GALLERY item=image}
               <li{if $image@total lt 2} style="display:none;"{/if}><a href="{$image.source}" class="th"><img src="{$image.small}" data-image-swap="{$image.medium}" data-caption="{$PRODUCT.name}{if !empty($image.description)}: {/if}{$image.description}" class="image-gallery" alt="{$LANG.catalogue.click_enlarge}"></a></li>
               {/foreach}
            </ul>
            {/if}
```

While this works, there may be a better solution in 2.cubecart.js so that a click on the main image actually does a thing rather simulate a click to another image.

**Comment by abrookbanks** [comment]
Thanks. I like this a lot and wouldn't say it was a work around. It's a good solution but I replaced class="hide" instead of using inline styles.

**Comment by abrookbanks** [comment]
Fixed with;
d6916ec & https://github.com/cubecart/v6/commit/58c4a1b004cd7355c76eca353757385e2792b3a7
