### ISSUE TITLE
Demo Site - Cannot Add / Update Product

### ISSUE THREAD

**Issue by daamonparker** [cubecart/v6#1177]
Hi,

I'm not sure if this is the right place but I couldn't see anywhere else where I could report this.

I logged in to the demo store (I don't have a stock install) and I can't add a new product, nor can I add Product Options (which I've set up - a single-line text field) to an existing product - I logged in with credentials provided on the demo home page. When I click "Save" I get:

Access to demo.cubecart.com was denied

You don't have authorization to view this page.

HTTP ERROR 403

**Comment by abrookbanks** [comment]
The demo store is locked down pretty hard. Thanks for letting us know.. server security levels may be a bit high.

**Comment by daamonparker** [comment]
Thanks for the info.

I've tried again and can now create a Product Option but can't add it to an existing product.

I'm wanting to do this as I think I have an issue in CC6012 and want to confirm it before raising a defect support ticket. I'm inclined to raise it anyway (in a new ticket) as trying to do it on a partially functioning demo site is becoming too time consuming.

The thread with the details I'm referring too:

https://forums.cubecart.com/topic/51338-database-has-sort-of-lost-previously-collected-mandatory-data/
