### ISSUE TITLE
Order Not Displaying Captured Text Data When Status Moved To Order Complete

### ISSUE THREAD

**Issue by daamonparker** [cubecart/v6#1179]
Hi,

Sequence of events to reproduce, where the issue is consistently occurring on our (basically clean) install:

1) Create a new Product Option Group of type "Textbox - single line" which is mandatory
2) For a product available for sale, add the above to the "Product Options"
3) When this product is purchased, the shop enforces the mandatory entering of this text data before proceeding to payment
4) Payment is made via PayPal
5) The product order status automatically moves from "Pending" to "Processing" once payment has been successful
6) At this point, the mandatory text data **IS** visible in the "Items" section of the "Order Summary" for this order
7) Manually move the Status to "Order Complete"
8) Now, the mandatory text data is **NO LONGER** visible in the "Items" section of the "Order Summary" where it was before.

Example:

- We have a product for motorcycle roadside assistance which requires "make, model, year of manufacture and registration" details to be entered when purchasing the product.
- At the time of purchase, before payment, these details are displayed in the Order Summary
- Once payment is made via PayPal, these details are still displayed
- Once the shop user moves the status to Order Complete these details are no longer displayed but do still exist in the database though not in all the locations they were previously.

This has been explored in a fair amount of detail, including analysis of database tables relating to orders and data captured, in the forums and will provide useful additional information for your analysis:

https://forums.cubecart.com/topic/51338-database-has-sort-of-lost-previously-collected-mandatory-data/

I tried to replicate this on the demo site before raising this issue ticket, but it was too locked down and I couldn't set up the Product Options to be able to run the test.

We're running CC6012 with PHP 5.4.45 - let me know if you need any other details.

Thanks.

**Comment by abrookbanks** [comment]
This is due to a bug in an old/3rd party skin.

**Comment by bhsmither** [comment]
Technically, it is due to a bad variable name in skins using the placeholder set found in (maybe almost) all CC5 skins - Devellion's and Third-party. See Issue #1196.

**Comment by daamonparker** [comment]
I have made the changes mentioned in 1196 and can confirm that this resolves the issue originally raised in this ticket (1179).
