### ISSUE TITLE
SEO url changes needed

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#118]
There are two issues here

1) The CubeCart_seo_urls tables cannot easily be cleared (only with an SQL TRUNCATE command) so add a new tick box option to the clear cache page in Maintenance

![new_clear_cache_option](https://cloud.githubusercontent.com/assets/6114431/5886780/38aac5d6-a3b0-11e4-9514-5d1d2eba09cb.png)

2) There is an option in Store Settings | Search Engine tab "Category name in new product URL" which adds the category name to product urls - there should also be a new option "Sub-category name in category url"

![new_category_url_option](https://cloud.githubusercontent.com/assets/6114431/5886794/71216208-a3b0-11e4-8a58-3ae747f836b9.png)

**Comment by havenswift-hosting** [comment]
In addition, if either the current "Category name in new product URL" or the new "Sub-category name in category url" is changed then the CubeCart_seo_urls table could be automatically truncated

**Comment by bhsmither** [comment]
And, on the Edit Product, Search Engine tab, when POSTing an empty field for Custom SEO URL Path, take that to mean to have CubeCart generate the default path and update the relevant record.

I feel adding a button, or automatic action, to truncate a table is too drastic - of a far greater degree than clearing the SQL cache for example. There may be many seo paths that have been painstakingly constructed only to have *everything* obliterated.

For the first issue, I suggest a dire warning (and even a second, "Are you really, really sure?" alert) on the "Clear SEO paths" button on the Rebuild tab.

For the second issue, I suggest the phrase "Complete category path in new categories" and a slight change to be "Category path in new product URL".

**Comment by havenswift-hosting** [comment]
>>And, on the Edit Product, Search Engine tab, when POSTing an empty field for Custom SEO URL Path, take that to mean to have CubeCart generate the default path and update the relevant record.

I suppose you are looking for a mechanism to overwrite single entries that are old and wrong in the seo_urls table and in that respect this suggestion is OK but see answer below for why it isnt needed !

>>I feel adding a button, or automatic action, to truncate a table is too drastic - of a far greater degree than clearing the SQL cache for example. There may be many seo paths that have been painstakingly constructed only to have everything obliterated.

Clearing the seo_urls table is perfectly safe as CubeCart simply rebuilds it from the custom urls entered against each product (hence not needing your suggestion above) or, if there is no custom entry against the product, then it uses the default value.  If either of the Store Settings have been changed (current one plus my new proposed one) then it makes sense to clear and rebuild the seo_urls table or the results dont reflect the new choices !

>>For the first issue, I suggest a dire warning (and even a second, "Are you really, really sure?" alert) on the "Clear SEO paths" button on the Rebuild tab.

Not needed !  

>>For the second issue, I suggest the phrase "Complete category path in new categories" and a slight change to be "Category path in new product URL".

The addition of the word "Complete" could and should be applied to both to make it clearer so instead would suggest.

"Complete category path in categories"
and
"Complete category path in product URL".

**Comment by bhsmither** [comment]
*"CubeCart simply rebuilds [the entry in the CubeCart_seo_urls table] from the custom urls entered against each product."*
Where is this product's custom url located, if not in the seo_urls table that was just truncated?

**Comment by havenswift-hosting** [comment]
Was answering this without being able to check the database structure and assumed that any custom url entered was stored on the inventory table against each product (and other tables for docs, categories etc) and then the seo_urls table was rebuilt from that.  Therefore two ways of achieving this -

1) Hold any custom url entered against the product (doc, category) as I had thought and then rebuild from that information

2) When clearing the seo_urls table (can be either via the new proposed auto clear or the new clear cache option) then dont truncate the table but check for a custom url entered for that item and use that setting.  This would need additional indexes and even then on large stores might take a reasonable amount of time so option one might be better.

The current situation means that stores using any custom urls anywhere cannot ever change the Store Setting "Sub-category name in category url" or the new proposed "Complete category path in categories"

**Comment by abrookbanks** [comment]
* This has been implemented with https://github.com/cubecart/v6/commit/e8c65bb8aacaf76057f72f9db44993cc6b938258
* This setting has been removed from v6 but from my testing its only adding the top level category. It needs to be fixed to include sublevels by default

**Comment by havenswift-hosting** [comment]
1) As far as I can see the way you have implemented it would suffer from the problems highlighted by Brian in that it would lose any custom seo urls that have been manually entered ?

2) I hadnt seen that this had been removed in V6 - why is that ?  I think it is important to allow store owners to decide to either have category names (full path I agree rather than just top) in product urls but also as a separate option on category urls.

**Comment by abrookbanks** [comment]
1) I thought that was the whole point?

2) I hate settings. Surely there is a best SEO practise and we should take that by default.

**Comment by havenswift-hosting** [comment]
1) My original post was an (attempted) solution to generate the correct seo_urls when changing the "Category name in new product URL" setting otherwise it can only be done manually.  Your change fixes that but ONLY if using the default generated urls.  If using custom urls in any area (products, categories, documents etc etc) then as these are not held anywhere else (like actually on that type of record) then simply clearing this table will lose all the work that has been put in.

2) Sometimes configuration settings are needed and generally are the only way of doing something correctly. There is no correct way of doing SEO in a generalised way and will vary from store to store based on directory structure and directory and product naming.  Having a default will likely mean it will never be correct for any store.

**Comment by abrookbanks** [comment]
Ok this is much improved now. I haven't added config options but will if the demand is there. ALso added ability to reset seo url by submitting an empty field.

**Comment by abrookbanks** [comment]
Closing for now. Happy to reopen if required.

**Comment by abrookbanks** [comment]
Reopening to add SEO path settings back

**Comment by abrookbanks** [comment]
![screen shot 2015-01-28 at 12 10 40](https://cloud.githubusercontent.com/assets/4520803/5937375/b4f452ae-a6e6-11e4-87b2-cdf78bbb54f1.png)

**Comment by abrookbanks** [comment]
![screen shot 2015-01-28 at 13 26 46](https://cloud.githubusercontent.com/assets/4520803/5938284/5cccfe54-a6f1-11e4-8948-2772d593fa60.png)

**Comment by abrookbanks** [comment]
![screen shot 2015-01-28 at 15 59 22](https://cloud.githubusercontent.com/assets/4520803/5941111/ad1d0c72-a706-11e4-973f-76e437de00f2.png)

All done. All works great form my tests. Ready for beta 4..

**Comment by havenswift-hosting** [comment]
Thanks for adding the extra functionality we discussed !  The dire danger warning only applies to the "Clear All" (why do you actually need that - isnt that the same as selecting the other two options ?) and the "Clear custom defined...".

I would suggest removing the Clear All tick box and then only having the warning next to the custom one ?

**Comment by abrookbanks** [comment]
Really appreciate your help today and for helping get my head in the right place about all this. Don't really need clear all. Might save having to have the extra click though. Ha.

**Comment by havenswift-hosting** [comment]
You are very welcome ! Removing the clear all would make it clearer which option is the dangerous one (custom url) plus it would have the added benefit for you of removing a setting (of sorts !)

**Comment by abrookbanks** [comment]
Done. Thanks. Onto #139 next. *gulp*
