### ISSUE TITLE
USPS Plugin can't handle LARGE size

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1181]
Changes in the USPS plugin have not kept up with the changes in how the dimensions of a package influence the shipping cost.

OVERSIZE is no longer used in the USPS API and LARGE requires a specific CONTAINER be specified and a girth measurement be provided. Only the REGULAR choice in the plugin works now. 

https://forums.cubecart.com/topic/51502-usps-shipping-module-issue/?do=findComment&comment=219194

**Comment by abrookbanks** [comment]
If some one wants to take on the USPS development they can do so and sell in on the marketplace.
