### ISSUE TITLE
Session Class File has Illegal Character

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1184]
In session.class.php, lines 196 and 209, there is a *space-like* character (C2 A0), but it needs to be an actual space.

**Comment by bhsmither** [comment]
In catalogue.class.php, line 1247, as well.

**Comment by abrookbanks** [comment]
Sublime text doesn't pick up on this? What editor are you using?

![screen shot 2016-07-26 at 09 07 20](https://cloud.githubusercontent.com/assets/4520803/17130442/651dd1ba-5310-11e6-97b7-261bb21db685.png)

**Comment by bhsmither** [comment]
I am using an editor (UltraEdit) that can show space characters as center-dots everywhere - including comment lines. Apparently, your editor chooses to not use an indicator for space characters within comments. If it did, like mine, you would see there is no center-dot where mentioned.

My editor can also switch to HEX View mode and have the text cursor remain on the target byte after the switch. So, placing the text cursor where the *space-like* character is, then switching to HEX mode, shows the C2 A0 bytes.

**Comment by abrookbanks** [comment]
I'm sorry Brian but I'm not sure how to go about this. I don't think there is an associated bug. 

Hex View in UltraEdit was unreadable to me. Are you human? LOL Hehe
