### ISSUE TITLE
Login without password (Mobile Connect)

### ISSUE THREAD

**Issue by jomagalo** [cubecart/v6#1189]
Hello,
Lately I'm seeing log in without password using Mobile Connect. You can see in some telephony operators as MoviStar, Orange, etc.

For me it would be perfect to use with Cubecart.

Know some plugin or php code to integrate?

Source: https://mobileconnect.io/

Best Regards

**Comment by jomagalo** [comment]
After a year that I suggested the implementation of this novel way of connecting, I see that it is not advancing. I do not understand, since it would be a great advantage for Cubecart. We all know that clients forget their passwords because of the multitude of sites to which they are registered. This would be a perfect solution in my opinion and very grateful for the customers.

**Comment by abrookbanks** [comment]
Please see.. https://features.cubecart.com/topic/login-without-password-mobile-connect_8

I doubt this will be integrated anytime soon.
