### ISSUE TITLE
6.0.12 Feature request: Coupons could offer free shipping

### ISSUE THREAD

**Issue by jasehead** [cubecart/v6#1190]
Please add an option in Coupons > Create Coupon under Coupon Value to add Free Shipping.

eg.
Coupon Value
Discount Type - [Percentage Discount/Fixed Price Discount]
Discount Value - [textbox]
Free Shipping - [x] Shipping not charged if checked

There are occasions where individual coupons are required for free shipping and it would be better to use a coupon with a use limit and expiry date rather than admin switching on/off the free shipping module.  Coupon would only apply to shipping.

**Comment by abrookbanks** [comment]
![screen shot 2016-09-02 at 16 12 58](https://cloud.githubusercontent.com/assets/4520803/18208637/25adb7bc-7128-11e6-878a-6a18ef5e01c6.png)

**Comment by abrookbanks** [comment]
![screen shot 2016-09-02 at 16 13 39](https://cloud.githubusercontent.com/assets/4520803/18208670/50f42690-7128-11e6-8047-1c6594edfca4.png)

**Comment by abrookbanks** [comment]
This need to also show paid shipping methods..
