### ISSUE TITLE
Glitch in cubecart.class.php

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1191]
The following statement needs to be improved:
`if (isset($order['price']) && $GLOBALS['config']->get('config', 'catalogue_sale_mode')) {`

Should be:
`if (is_array($order) && isset($order['price']) && $GLOBALS['config']->get('config', 'catalogue_sale_mode')) {`

if the $order variable is a string then it causes this behaviour on some PHP versions
https://bugs.php.net/bug.php?id=27677

this makes the SQL query malformed and fails.

**Comment by havenswift-hosting** [comment]
Occurs on older 5.3 versions as well (at least 5.3.29)

**Comment by abrookbanks** [comment]
Thanks guys. :)
