### ISSUE TITLE
.htaccess 404 Directive Not for Admin

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1192]
It is inappropriate for the web server to deliver `index.php` when something in admin was not found by the web server. Also, it is mostly inappropriate to deliver `index.php` when a page resource is not found.

There is a lot of unnecessary work done to deliver CC6's 404 page for no good reason.

Suggest ,htaccess have directives that perform:
If only %{REQUEST_FILENAME} does not contain any of:
"/admin/", ".png", ".jpg", ".gif", ".css", ".js"
Then respond  to 404 with index.php.

**Comment by bhsmither** [comment]
These are my edits:
```
/admin/.htaccess
## Default store 404 page
ErrorDocument 404 "<html></html>
```
```
/.htaccess
## Default store 404 page
ErrorDocument 404 /index.php
# Override default 404 error document for missing page resources
<FilesMatch "\.(gif|jpe?g|png|ico|css|js)$">
ErrorDocument 404 "<html></html>
</FilesMatch>
##### END CubeCart .htaccess #####
```

**Comment by abrookbanks** [comment]
I'm not sure how to implement this since the admin folder can be renamed.

**Comment by bhsmither** [comment]
Let expound on this:

In CubeCart's admin folder (**whatever it is ultimately named**), place a file named `.htaccess` and have as its contents:
```
## Default store 404 page - Note: no closing quote!
ErrorDocument 404 "<html></html>
```
In CubeCart's root folder, include in the existing `.htaccess` file, the added directives indicated earlier.

**Comment by abrookbanks** [comment]
I see now. I'll get this integrated tomorrow.

**Comment by bhsmither** [comment]
Be sure, now, to include `svg` file extensions in FilesMatch.
