### ISSUE TITLE
6.0.12 Checkout shipping dropdown is not clickable/unresponsive on small viewport

### ISSUE THREAD

**Issue by jasehead** [cubecart/v6#1194]
This only appears to be an issue on some browsers - possibly a scripting issue based on the class field_small_only. When the browser window is resized to a small viewport, the shipping dropdown becomes solid and is not clickable. Checkout can proceed, but with no option available only the first option can be used - customer has no choice.

Problem occurs in small viewport on:
* Firefox Mac v47
* Chrome Mac v48

Works OK in small viewport on these browsers:
* Android Internet v4.0
* Android Opera v37
* Android Chrome v52
* Android Firefox v48
* Safari Mac 5.1.10

Suggest testing checkout in small viewport, specifically popular browsers used on top selling smartphones.

**Comment by abrookbanks** [comment]
"When the browser window is resized to a small viewport"

Thats just the issue. If you do resize the page please refresh in order for the javascript to know it is at small viewport mode. It will still be in the mode it was resized from. 

Obviously when loaded on a small device the JS will be in sync with the loaded viewport size.

**Comment by jasehead** [comment]
You're right - the page needs to be refreshed.  I'm considering adding something like $(window).resize(function(){location.reload();});

**Comment by jasehead** [comment]
You're right - in part.  The shipping dropdown becomes responsive after reload in Chrome Mac v48, but in Firefox Mac v47 it is still a solid dark grey with no dropdown available.

While the page could be refreshed on resize automatically using jQuery - there may be something unique with Firefox:
https://www.sitepoint.com/jquery-refresh-page-browser-resize/

**Comment by jasehead** [comment]
You're right - in part. The shipping dropdown becomes responsive after reload in Chrome Mac v48, but in Firefox Mac v47 after reload the shipping is still a solid dark grey with no dropdown available. So the small version of this control on Firefox is not working for me.

While the page could be refreshed on resize automatically using jQuery - there may be something else unique with Firefox:
https://www.sitepoint.com/jquery-refresh-page-browser-resize/
