### ISSUE TITLE
No Default $path

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1195]
In `Catalogue->imagePath()`, a bad $mode is dealt with via trigger_error() and returning false.

No such escape is provided for a bad $path.

Suggest:
```
case 'rel':
case 'relative': ## Calculate the relative web path
	$img = $GLOBALS['rootRel'].'images/'.$folder.'/'.$filename;
	break;
case default:
	trigger_error('No image path set', E_USER_NOTICE);
	$img = $default_image; // or false
}
return $img;
```
(N.B.: Issue #1111 may be involved here.)

**Comment by abrookbanks** [comment]
Thanks. To be consistent I chose a return of false.
