### ISSUE TITLE
Bad Variable Name in Mican

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1196]
In the Mican template file content.product.php, lines 86-90, where `productOptions` are being populated, the variable used is `{$OPT.assign_id}` but should be `{$option.assign_id}`.

Might also want to verify this with all other CC5 skins.

**Comment by bhsmither** [comment]
A search in the skins: Crosshatch, Kurouto, Mauris, Mican, Mobile, Nota, and Vanilla -- as shipped with CC5216 -- all have `{$OPT.assign_id}`.

Also, Blueprint, e-Shift, e-Tone, Vector, Clean, and Lingerie have this condition. But not Minimaliser.

I say *as shipped with CC5216* because I am not going to freshly download each skin and check for this condition. I will just assume the condition exists for these CC5 standard skins. And probably any skin that copied the set of placeholders found in a CC5 skin and used them without question.

**Comment by abrookbanks** [comment]
Thanks all official CubeCart skins needed updating. 
![screen shot 2016-08-09 at 10 20 31](https://cloud.githubusercontent.com/assets/4520803/17511495/f1c7d54c-5e1a-11e6-8739-4ea3ac5383f9.png)

**Comment by fiandpz** [comment]
Hello... I have a trouble at Mica layout on currencies, where every time I select a currency on the front page it always goes to cubecart/.html it should be cubecart/index.php

the page displays:

Forbidden
You don't have permission to access this resource.

any suggestion will be appreciated
