### ISSUE TITLE
Feature Request - Reviews should be able to be added manually

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1198]
Within the admin area you can manage reviews submitted by customers, but there is no option to manually add reviews, for example a copy/paste from an e-mail etc.

Admins should be able to manually add reviews as well as manage submitted customer reviews.

**Comment by havenswift-hosting** [comment]
Plus one for this feature as it is something requested by many of our users and shouldn't be too difficult to add

**Comment by abrookbanks** [comment]
Yeah it needs this for sure.
