### ISSUE TITLE
Feature Request - Support for Redis

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#1199]
I have tested Redis and Memcached on 2 stores on the same platform and I have found Redis much faster, efficient and easier to use. Please add support for this on CubeCart.

**Comment by havenswift-hosting** [comment]
I would also strongly support the addition of REDIS as a caching method in CubeCart as we have previously discussed.  We have had great success using it on our Magento hosting and it is somewhat faster but more importantly, is easier to manage at a server level.  Using it for standard caching but also adding session storage (as in Magento), would make this even better !

**Comment by Spechal** [comment]
I would move to implement a generic caching  factory that can generate various handlers using a common interface.  Memcached is stupid easy to setup and manage, I don't have as extensive use of Redis but have not had issues with it.

**Comment by havenswift-hosting** [comment]
Can the priority of this request be made urgent ?  The memcached extension has not been updated for over 2.5 years and looks like it may have been abandoned and doesnt work under php7 so much so that cPanel are no longer supporting it at anything above 5.6   We are looking to move many of our servers to php7 but cannot until we have a reliable caching extension and REDIS would be our preferred method anyway

**Comment by havenswift-hosting** [comment]
memcached extension last updated 01/04/2014 - https://pecl.php.net/package/memcached

memcache extension even worse as last stable release updated 07/04/2013 - https://pecl.php.net/package/memcache

**Comment by abrookbanks** [comment]
I'm working on this but Redis doesn't support storage of arrays or objects so these need to be serialized is is really shitty. This commit seems to work but I have more work to do yet..

**Comment by bondimedical3** [comment]
If you could put a note here or mention it in the CubeCart newsfeed when it is done I would appreciate it.

**Comment by abrookbanks** [comment]
The next release will contain a note of new features. You can also use the issue tracker to filter features by milestone.

**Comment by havenswift-hosting** [comment]
We have done a couple of hours testing on the REDIS solution that has been created so far and it is looking very good.  Going to move onto some real live site testing today !

**Comment by abrookbanks** [comment]
Great. It works the same as all other cache tools but no full page cache & no session cache.

I'm going to close this for now as my tests were really good too. Maybe future enhancements to all cache mechanisms in seperate issue(s).

**Comment by havenswift-hosting** [comment]
I have been testing this on multiple test sites on one server and all seems to be working very well !

**Comment by abrookbanks** [comment]
GREAT!! Thanks for the feedback.
