### ISSUE TITLE
Show cache method in admin CP

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1200]

**Comment by abrookbanks** [comment]
![screen shot 2016-08-15 at 10 54 21](https://cloud.githubusercontent.com/assets/4520803/17661375/a412bfc2-62d6-11e6-8bc7-bfcbd2091fdd.png)

**Comment by havenswift-hosting** [comment]
I haven't looked at the code you have committed for this but assume it is looking at what is set in the global.inc.php file - is it possible to have this admin interface change which caching method is used and update that

**Comment by abrookbanks** [comment]
No it has to be done at deep config level. The configuration from database gets initiated was after cache is initiated so therefore it's not doable as a setting in the admin interface.
