### ISSUE TITLE
Hook Request - Category Products

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1201]
File:
/modules/plugins/hooks.xml

Find This:
```
 <hook trigger="class.catalogue.category_product_list_return" deprecated="" />
```
Below That Add This:
```
 <hook trigger="class.catalogue.category_products" deprecated="" />
```

File:
/classes/catalogue.class.php

Find This:
```
				$vars['products'][] = $product;
			}

			$GLOBALS['smarty']->assign('PRODUCTS', $vars['products']);
		}
```
Above That Add This:
```
				foreach ($GLOBALS['hooks']->load('class.catalogue.category_products') as $hook) include $hook;
```

**Comment by Noodleyman** [comment]
you don't need this hook, you can use "class.cubecart.display_category", loop the $vars['products'] array using a foreach statement, then update each of the product items with whatever custom logic is required.

**Comment by abrookbanks** [comment]
Hooks within a loop isn't a happy place for CC. :)
