### ISSUE TITLE
SEO May Damage URL

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1203]
In `SEO->generatePath()`, if the pattern matches, but is not a dynamic type, the return is:
```
default: $this->_url = 'index.php?_a=whatever...
```
Note the loss of the leading slash, which is included on any other returned value.

This becomes evident when a standard (aka, CC5-style) URL that does not get SEO'd is thereafter 301 Bounced - such as when SSL is switched on.

An example (non-SSL):
```
*http*://www.example.com/index.php?_a=download&accesskey=c1010bc5eff87e22e8ac798d86bded54
```
`SEO->generatePath()` returns:
```
index.php?_a=download&accesskey=c1010bc5eff87e22e8ac798d86bded54
```
Note that `$GLOBALS['storeURL']` is currently `*http*://www.example.com`.
When SSL is switched on, a 301 Bounce is sent with the target as:
```
*https*://www.example.comindex.php?_a=download&accesskey=c1010bc5eff87e22e8ac798d86bded54
```
Note the missing slash.

**Comment by bhsmither** [comment]
The problem may be exacerbated when the installation is in a sub-folder.

**Comment by bhsmither** [comment]
For a workaround - with unknown consequences - I switched the order of instantiation from the SEO then SSL to SSL then SEO in the controller.

See:
https://forums.cubecart.com/topic/51599-download-link-on-https/
But this treats the symptom, not the disease.

**Comment by abrookbanks** [comment]
I don't really know what to do about this without steps to reproduce?

**Comment by bhsmither** [comment]
1) Get yourself a didgital product download link that starts with http:
2) Have the site with SSL enabled
3) The site will restructure the link with https:
4) The link will also have a missing slash

It seems to me that if the site that has SSL already enabled and issues download links, they will have https:. But this scenario is when the site did not have SSL already enabled, links issued, and now does.

**Comment by abrookbanks** [comment]
The initiation of the SSL class should definitely go before SEO.
