### ISSUE TITLE
Admin never logs out

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#1204]
I have noticed even if I look at my Admin 24hrs later I am still logged in?

**Comment by bhsmither** [comment]
In CC6012, the session timeout is 604800 seconds for both customer and admin.
(/classes/session.class.php, line 33)

As long as you do not actually logout (being a customer or admin as logging out of either logs you out as both), change browser user agent string (such as a browser update), or change IP, you have 7 days of inactivity to expire a session.
