### ISSUE TITLE
gui.class.php - redirect glitch 

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1205]
Bit of an unusual one, but tripped up one of my modules today.

The following settings are required:
Allow users to change front-end skin? = yes

Then:
Login as the admin to the admin area, use "Login as customer" feature, and submit a custom form using http POST to the homepage of the site. 

This is done so you can listen for custom post requests using controller.index hook..

HOWEVER!!!!!!!

If those conditions above are in place, gui.class.php file thinks you are changing the skin choice, changes the skin and then redirects you back to the site. The redirect drops the $_POST data and you can't process it.

This code block is the issue:
`			if ($GLOBALS['config']->get('config', 'skin_change')) {
				// Switch Skins
				if (isset($_POST['select_skin']) && !empty($_POST['select_skin']) && ($switch = $_POST['select_skin']) || (isset($_GET['select_skin']) && !empty($_GET['select_skin']) && ($switch = $_GET['select_skin']))) {
					list($skin, $style) = explode('|', $switch);
					if (isset($this->_skins[$skin])) {
						$GLOBALS['session']->set('skin', $skin, 'client');
						$GLOBALS['session']->set('style', $style, 'client');
					}
					httpredir(currentPage(array('select_skin')));
				}
			}`

Solution:
Possibly compare existing skin selection to the posted one, if different do the redirect, otherwise ignore it.

**Comment by bhsmither** [comment]
I am not yet seeing this happening. My experiments show that neither `POST['skin_select']` or `GET['skin_select']` are arriving with the page request unbidden.

**Comment by Noodleyman** [comment]
Hmm, it's been a bit of a pain to reproduce. I think it all relates to the method in which the custom form is being added. for example if I inject a custom form using a hook, I get the issue. If I add the custom form directly into a template file then works OK. It's one of those edge cases where it doesn't happen very often and only tends to trip up custom modules doin ga specific thing.

**Comment by bhsmither** [comment]
Where is the "custom form" being added? In its own page (main content area), or on an existing page (using javascript maybe to locate were to insert the HTML)?
