### ISSUE TITLE
Replace $GLOBALS with a Registry

### ISSUE THREAD

**Issue by Spechal** [cubecart/v6#1208]
Feature Request: Get rid of $GLOBALS in favor of a Registry.

$GLOBALS are slow and JIT as of PHP 5.4.  Including them in all scopes seems unnecessary.

Using a Registry and grabbing things when needed was be far more readable in the code and provide less overhead.  Outside of the Registry class, implementation would look like a search/replace for $GLOBALS and calling the appropriate Registry static method, such as Registry::get('db')->query('...')

**Comment by abrookbanks** [comment]
I agree and hate this current coding. It will have a big knock on effect however.

**Comment by abrookbanks** [comment]
Relates to https://github.com/cubecart/v6/pull/1211
