### ISSUE TITLE
Update DBAL to support PHP7

### ISSUE THREAD

**Issue by Spechal** [cubecart/v6#1209]
The mysql connector will not work with PHP 7 as mysql_* functions are removed.  Recommend replacing with PDO or ORM.

**Comment by Noodleyman** [comment]
mysqli repalced mysql and was depreciated in php 5.5 and removed in php 7. 

you should be using mysqli instead. CubeCart will select mysqli or mysql based on function availability.

**Comment by abrookbanks** [comment]
My deve store works with MySQLi on PHP7 perfectly.
