### ISSUE TITLE
Move autoloader or adjust ini file

### ISSUE THREAD

**Issue by Spechal** [cubecart/v6#1210]
In an effort to work on #1208 the autoloader would need to be moved into the ini.inc.php file or the use of $GLOBAL needs removed from ini.inc.php ... there doesn't appear to be a need for the following to lines to be set in ini.inc.php 

```
$GLOBALS['rootRel'] = CC_ROOT_REL;
$GLOBALS['storeURL'] = CC_STORE_URL;
```

**Comment by Noodleyman** [comment]
just an observation, that would be a major MAJOR change in the cart and would also require all third party modules to be re-written as well as CubeCart supplied modules. I would be very surprised to see anything along these lines in CubeCart 6.

JIT offers some performance improvements, but what gains this would add to CubeCart isn't understood without extensive testing. It's not like $GLOBALS is end of life etc.

I don't see this request being added, although I can't speak on behalf of Al @ CubeCart. I can only offer my own personal opinion.

**Comment by Spechal** [comment]
I didn't realize it was that extensive.  There are also two camps on this topic, those who like $GLOBALS and those who prefer DI.  I think my PR is still valid provided there is interest in using a registry instead of strictly using global variables.

**Comment by briansandall** [comment]
I question the objective value of such a major change; your arguments for it per #1208:

1. far more readable in the code - `Registry::get('db')` vs. `$GLOBALS['db']` are both equally readable to me; this argument seems purely subjective.

2. provide less overhead - maybe, but is it worth rewriting so much of the code to obtain this? Some benchmarks would provide valuable data for making such a decision.

I'm not against using the Registry pattern, but I'd want to see some compelling evidence that it would be worth it. Also, I'd like to echo @Noodleyman and say such a major change (if Al decides to go this route) would be more suitable for the next major CubeCart release, not so much for CubeCart v6 as it would break probably every single module and skin, even the official ones provided by CubeCart.

**Comment by Spechal** [comment]
V7 would be completely understandable

-Travis

**Comment by Spechal** [comment]
Also, it is a more modern way to code and to use dependency injection as opposed to globals.  To each their own and it really doesn't matter. It just makes things a bit more flexible which is why Magento has adopted it as well.  I just wanted to spark discussion. :)

**Comment by briansandall** [comment]
Fair enough, though I think that using a Registry is actually part of the [Service Locator Pattern](https://en.wikipedia.org/wiki/Service_locator_pattern) which is kind of the opposite of [Dependency Injection](https://en.wikipedia.org/wiki/Dependency_injection).

That said, GLOBALS and Registry are both ways of implementing the Service Locator Pattern, so in what ways would a Registry be more flexible, especially considering that it is not Dependency Injection? [This article](http://bayou.io/draft/In_Defense_of_Service_Locator.html) covers many salient points regarding both patterns and could be useful in evaluating if it is really worth it for CubeCart.

**Comment by abrookbanks** [comment]
I like this a lot but the impact is huge.
