### ISSUE TITLE
6.0.12 Credit Card captured but details missing (intermittent)

### ISSUE THREAD

**Issue by jasehead** [cubecart/v6#1212]
This is an ongoing, intermittent issue and relates to #489 and #1154
Also mentioned in forums:
http://www.cubecartforums.org/index.php?showtopic=19575
https://forums.cubecart.com/topic/50302-payment-gateway-credit-card-capture-cc-607/
https://forums.cubecart.com/topic/51242-credit-card-capture-issues/
https://forums.cubecart.com/topic/51398-credit-card-capture-automatic-delete/

The customer pays by credit card using the card capture gateway. Card details are captured - there is a transaction history and there is encoded card data in the database. However, all fields in the Credit Card Details tab of the order are blank. The issue normally occurs within 12-24 hours of the order being placed - Admin may have previously seen credit card details but they have since vanished. No action or change needs to be made to the order for card details to disappear. There does not to appear to be a clear process to reliably reproduce the problem.

The issue appears to be due to the enc_key in the config table of the database. If the keys used to decode the credit card data do not match then the card details will not be shown. In my own backups, the enc_key had changed in 3 of the 4 backups over the past 7 weeks.

It may be possible for Admin to use the previous enc_key from backup to make the most recent credit card details visible again (if a backup exists). If this works, other card details encoded with different keys would not be visible.

My theory is that CubeCart looks for the enc_key and if it doesn't get the right response (maybe a server timeout) then CubeCart creates a new enc_key.  Even if an enc_key already exists, if there is some failure then it gets rewritten. Please review the CubeCart code to STOP the enc_key from continually being overwritten - maybe create an enc_key ONLY on first installation or when upgrading from CCv5 or prior.

**Comment by abrookbanks** [comment]
I think this really sheds some light on this. It seems that a new encryption key is being made with each transaction. Therefore is a new order comes in the previous one is not retrievable as the key has changed. 

Fix above prevents key regeneration.

**Comment by bhsmither** [comment]
A search in the codebase shows that `setEncryptKey()` is called only by `getEncryptKey()` -- dismissing any plugins that may call it. (Suggest `setEncryptKey()` be made private.)

`getEncryptKey()` runs the same tests that this fix adds to `setEncryptKey()`.

I believe focus should be on why, in `getEncryptKey()`, Config->has('config','enc_key') is returning `false` when an established value should be in the config array.
