### ISSUE TITLE
6.0.12 Two issues with customer using order history to complete payment

### ISSUE THREAD

**Issue by jasehead** [cubecart/v6#1215]
Issue 1 - Customer places an order during a sales event (say 20% off storewide) but does not complete payment.  The sale ends.  Admin asks customer to login, go to order history and click Complete Payment.  The amount in the order history shows the discounted total because the order was placed during the sale.  However, when the customer clicks Complete Payment the amounts are now without any discount.  Customer sees each item as the full amount.  On the admin side, admin sees each item as a discounted amount but the subtotal indicated the full amount.

What to fix: If a customer places an item during a sale but does not complete payment, the customer should still be able to complete payment at the sale price (the price when they placed their order) even after the sale has ended.

Issue 2 - Customer places an order for 4 items but does not complete payment, order remains pending and stock is still available for purchase. Another customer buys one of the items. Admin deletes the sold item from the first customer's order and notifies them that one item is no longer available and that they should complete their purchase ASAP in case the same thing happens again.  Admin asks customer to login, go to order history and click Complete Payment.  The customer logs into their order history and can see that the total to pay has changed.  If they click the order number they will see that one item has been deleted.  The customer returns to their Order History, clicks Complete Payment and the deleted item reappears.

Note tested: If the customer can complete their purchase with the deleted item or if that will return an error.

What to fix: A complete payment/retrieved order should return the order as it appears in admin, with any amendments or changes, not the original order.

**Comment by jasehead** [comment]
*note tested should be not tested

**Comment by havenswift-hosting** [comment]
Issue 1 - I believe that if the sale has finished then the items should revert back to their full price but what should happen is that a pop up message should be shown to the customer stating that the sale period has ended (or that the coupon has been removed as it has expired etc) so they understand why the prices have changed.

Issue 2 - Obviously if an item is deleted by an admin user it should never reappear on the order and be visible to a customer.  It should not be possible to complete payment on an order with items that are out of stock and a check should be made at that point (not sure whether this happens or works) but again a pop up message should be shown if items on an order are changed

**Comment by jasehead** [comment]
If the sales revert to full price then this should be reflected in the unpaid order before the customer clicks Complete Payment.

However, I don't agree with punishing customers for completing their order after the sale has ended - I had one customer that had misplaced their credit card and another who was focussed on their terminally ill spouse. I would prefer some leeway. Making the customer complete a discounted order at full price is likely to result in no purchase at all and losing that customer.

It would help if there was a direct URL link available to complete an order - much easier to send a link to a customer requesting they complete payment rather than step-by-step instructions.

**Comment by briansandall** [comment]
Re: Issue 1 - I agree with @havenswift-hosting that the sale has ended and the sale price should no longer be valid, and I agree with you that the price shown in the order should then reflect that fact.

Note that it is always possible to adjust price on an individual order basis, so if a customer began an order during a sale but didn't complete payment until after it had ended, you can cut the customer some slack and mark the price down on their specific order. I think handling expired sale prices manually on a case-by-case basis is the correct approach here, rather than allowing it by default.

**Comment by jasehead** [comment]
Issue 1 - OK, after the sale ends the prices should revert to the full price.  The customer clicks Complete Payment and they should be notified (a) if any products are no longer available (issue 2) and (b) that prices have changed, do they wish to proceed with their order.  If the customer checks their order in Order History while it is still pending, any notices and changes should also appear there.  There should also be information in the Admin area (order summary).

What if Admin has made changes to the order? How does CubeCart differentiate between admin changes and an expired storewide discount? Annoying if manual admin edits get wiped out.

If the pending order is placed BEFORE a sale, then the customer should benefit from the active sale price when they go to complete their order. Again, they should be notified that prices have changed.

**Comment by briansandall** [comment]
Sounds good to me.

I don't think CubeCart currently has a way to differentiate between admin edits and an item's price at the time it was ordered, but that could be done via an additional flag in the order table for whether an admin has modified the price or not.

**Comment by abrookbanks** [comment]
Issue 1 - I don't think any changes are needed.
Issue 2 - The order would get updated if they proceeded. Nothing is confirmed until they move to payment. 

I don't think anything should be changed.
