### ISSUE TITLE
Feature Request: Add USPS Shipping Labels

### ISSUE THREAD

**Issue by roboticsguy1988** [cubecart/v6#1216]
I would like to submit a feature request for the USPS plugin / extension to be able to automatically generate prepaid shipping labels in a PDF format. For those of us with a USPS business account it would be terrific to receive the order, print the label, and ship it all from one website.  Manually transferring the shipping information to another website takes a lot of time.

**Comment by Dirty-Butter** [comment]
We use Endicia's Dazzle, which can use an XML file to automatically fill in the label. So if it can be done in PDF, I'd appreciate considering offering an XML version as well.

**Comment by Noodleyman** [comment]
I've done this for one of my customers using UPS, so if you decide to persue this as a custom solution I would be happy to assist.  for the UPS module, orders are converted to shipping quotes, then approved and the courier is booked via the order page. labels can be printed direct from the same page.

**Comment by abrookbanks** [comment]
I'd love to see this.
