### ISSUE TITLE
Standardize code indentations for clarity

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1221]
CubeCart files have wildly differing indentation styles:

 - there are lines where the indentation is clearly incorrect (see e.g. commit 7f2a531 classes/acp.class.php: there are two closing curly braces with the same indentation on consecutive lines 168-169 making the code less clear)

- the use of spaces vs. tabs is inconsistent (e.g. classes/mailer.class.php uses both intermittently, sometimes even on the same line)

- the number of spaces used per indent differ (see e.g. pretty much any skin template where you will see 2, 3, or 4 spaces per indent and this often varies line by line)

I know this is kind of an OCD nitpick, but having consistent indentation throughout the code not only makes it easier to read, it also makes contributing to the project and merging changes into custom branches much easier. I'd be more than happy to help converting indentation styles if you let me know your preference (e.g. 4 spaces or one tab per indent are both common).

You can set your git to [automatically filter](http://stackoverflow.com/questions/2316677/can-git-automatically-switch-between-spaces-and-tabs) spaces or tabs so that you can work however you prefer but commit with the same indentation style every time, at least so long as you yourself are internally consistent.

**Comment by Spechal** [comment]
What about using a PSR and letting the IDE mass reformat ... do it all in one commit/branch/patch release.

**Comment by briansandall** [comment]
That would be the smart way to do it, yeah ;)

**Comment by abrookbanks** [comment]
On the whole I think its pretty good. It's all been run though IDE formatter in the past but maybe it needs to be done again.

**Comment by abrookbanks** [comment]
.. I'm actually going to trial PhpStorm which I have been meaning to try for a long time. I moved from Coda to Sublime and now time for a proper IDE I think. :)

**Comment by abrookbanks** [comment]
Reverted due to corruption.

**Comment by briansandall** [comment]
Heh, I'm still using Notepad++ and a fair amount of command-line Git ;)

Which files got corrupted?
