### ISSUE TITLE
Dashboard to show all years sales not just two years

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1225]
As above.

**Comment by Noodleyman** [comment]
It would be nice if this was a configurable option. Even the ability to toggle the dashboard charges on/off as not everybody wants it or needs it.

**Comment by havenswift-hosting** [comment]
The best option would be to have a selector for start and end years and then a single year could be selected or a range when each year within the range could be shown

**Comment by SemperFiWS** [comment]
Having the ability to switch between line and columns would a great addition too.

Line:
```
var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
```

Columns:
```
var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
```

**Comment by abrookbanks** [comment]
Could probably add a button underneath to toggle between them.

**Comment by bhsmither** [comment]
I also left this as a comment on the commit:

If `count($years)` does not equal zero, where does `$min_year` come from?

With respect to that and `$max_year`, are we just assuming the query will return the recordset in `'order_date'` order (as far as being clumped by year)?

For example, *suppose* `$result[0]` just happened to be from 2020, and `$result[1]` just happened to be from 1994. While not probable, it is possible.
