### ISSUE TITLE
Unsettled Orders tab improvements

### ISSUE THREAD

**Issue by NaturalSigns** [cubecart/v6#1228]
Currently, from the admin dashboard _UNSETTLED ORDERS_ tab you get a summary of the current pending and processing orders, as below.

![current unsettled orders](https://cloud.githubusercontent.com/assets/10531097/18419880/f91adcde-785c-11e6-8575-253e1a2ae1b1.jpg)

This is useful, but not as useful as having the **print** and **bulk processing options** you get from the main orders list. 

![orders list](https://cloud.githubusercontent.com/assets/10531097/18419888/7500c3cc-785d-11e6-9d4c-0d35e5c02daa.jpg)

I currently use a stored bookmark to replicate the above (e.g. search for processing orders),

 .....co.uk/admin.php?_g=orders&multi-status=&multi-action=&search[order_number]=&search[search_customer_id]=&search[status]=2&search[date][from]=&search[date][to] 

It works a treat, though technically should include multi select for PENDING orders too!

Ideally the unsettled tab should include the bulk processing functionality by default.

**Comment by Noodleyman** [comment]
+1, seems a very logical feature to have.

**Comment by abrookbanks** [comment]
Excellent suggestion. Thank you!
