### ISSUE TITLE
Require email address entry Confirmation

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1233]
See Bsmither's solution
https://forums.cubecart.com/topic/51671-would-like-to-require-two-attempts-to-write-email-address-that-must-match/

I need this in every instance where email addresses are input by a customer, guest or registered.

**Comment by havenswift-hosting** [comment]
Plus one for a solution to be implemented ASAP

**Comment by abrookbanks** [comment]
Note to Assignee: Investigate possibility making confirmation for typed emails and not autofill.

**Comment by Dirty-Butter** [comment]
I adjusted Bsmither's code so both Checkout and Register confirm the email addresses. I do NOT allow ghost customers, so I have not tested that.

https://forums.cubecart.com/topic/51671-would-like-to-require-two-attempts-to-write-email-address-that-must-match/?do=findComment&comment=220616
