### ISSUE TITLE
VAT Exemption

### ISSUE THREAD

**Issue by ayz11** [cubecart/v6#1234]
An option to store a customers VAT number and have the ability to exempt a customer from paying VAT would be good.

**Comment by Noodleyman** [comment]
That functionality already exists via a plugin.
https://www.cubecart.com/extensions/plugins/notax-exclude-specified-customers-from-tax

**Comment by havenswift-hosting** [comment]
I can see both sides here :  

If a 3rd party plugin exists to cover some missing functionality, then generally I think that should be the "solution" as often a lot of work has gone into developing and supporting it and have had it happen to us where we spent a lot of time developing a gateway, released it and then an independent solution was released as a free plugin !

However, there are also some pieces of functionality that really need to be in core as currently (at least until Brexit happens and the UK comes out of Europe when it may or may not be irrelevant anyway !!) as if a company is VAT registered and doing business with other VAT registered businesses outside of the UK, then this is required and isnt optional.

Also to take into account is that Al has more than enough bugs and feature requests in the open pile and his time would be best spent focusing on ones without existing solutions.

Just my two pennyworth and without an answer !

**Comment by abrookbanks** [comment]
My take on it is that CubeCart should do all the basic stuff merchants need to trade on line. I'd be inclined to say that this needs to be core and not a 3rd party plugin. 

If you sell in Europe from the UK this is a fundamental requirements and as a result I believe it should be core. On the other hand an integration to 3rd party system or wishful features that are not "order qualifying" should be developed and released as plugins.

6.1 is on the way and I want a push for a number of released up to Christmas. Hopefully we will have 6.2 by 2017.

**Comment by Noodleyman** [comment]
Don't overlook that this can ALREADY be done using customer groups and tax rules... The module just offers an EASIER way to do it ;)

The biggest hole in the entire process is that shipping methods DO NOT support customer groups, where as products do. This is a gap that must be bridged so you can configure multiple tax rules for shipping solutions. The module bridges that gap as does my other EU vat solution, but not in the most graceful of ways.

**Comment by abrookbanks** [comment]
I'd never thought of that. :)
