### ISSUE TITLE
CubeCart_order_history `initiator` should be CHAR(1) instead of VARCHAR(1)

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1235]
Fixed length columns should use CHAR instead of VARCHAR, [here](https://github.com/cubecart/v6/blob/master/setup/db/install/structure.sql#L588) and [here](https://github.com/cubecart/v6/blob/master/setup/db/upgrade/6.1.0.sql#L1).

CHAR(1) requires 1 byte of storage space whereas VARCHAR(1) requires 2. It won't be a big deal until the amount of data gets huge, but then it becomes a big deal.

**Comment by abrookbanks** [comment]
Thanks! :)
