### ISSUE TITLE
Use Established Resource

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1237]
In Session->cookiesBlocked(), there is a fixed list of EU countries.

Now that the database is the better place where this info can be managed, suggest getting $eu_countries from it.

Even better, query for it directly:
```
if( ($GLOBALS['db']->select('CubeCart_geo_zone', false, array('iso'=>$store_country_iso, 'eu'=>'1'))) ) !== false) return true;
```
I have not verified this code.

**Comment by abrookbanks** [comment]
I like it. Thanks.
