### ISSUE TITLE
Hook Request - JS After Opening Body Tag

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1238]
File:
/modules/plugins/hooks.xml
Find This:
```
 <hook trigger="class.gui.head_js" deprecated="" />
```
Below That Add This:
```
 <hook trigger="class.gui.body_js_top" deprecated="" />
```

File:
/classes/gui.class.php
Find This:
```
			// <head> JS
			foreach ($GLOBALS['hooks']->load('class.gui.head_js') as $hook) include $hook;
			if (isset($head_js) && !empty($head_js) && is_array($head_js)) {
				$GLOBALS['smarty']->assign('HEAD_JS', $head_js);
			}
```
Below That Add This:
```
			// <body> JS (Top)
			foreach ($GLOBALS['hooks']->load('class.gui.body_js_top') as $hook) include $hook;
			if (isset($body_js_top) && !empty($body_js_top) && is_array($body_js_top)) {
				$GLOBALS['smarty']->assign('BODY_JS_TOP', $body_js_top);
			}
```

File:
/skins/foundation/templates/main.php
Find This:
```
   <body>
```
Below That Add This:
```
   	  {foreach from=$BODY_JS_TOP item=js}{$js}{/foreach}
```

File:
/skins/foundation/templates/main.checkout.php
Find This:
```
   <body>
```
Below That Add This:
```
   	  {foreach from=$BODY_JS_TOP item=js}{$js}{/foreach}
```

This will provide functionality to include any JS before the rest of the page loads, with out being in the head or within HTML structure.

**Comment by Noodleyman** [comment]
I've no idea why you would need, this, because the BODY_JS smarty variable already exists in after the footer. 

Any well formed JS / jQuery code can be loaded from either the head or body. I am curious what the actualy real world usage case is for needing it at the start of the body section?

**Comment by SemperFiWS** [comment]
Real world example:
https://developers.google.com/tag-manager/quickstart

The current method in the footer is within existing HTML structure, so it throws an error.
The header method can be used, but to stick with their recommendations, immediately after the opening body tag is needed.

**Comment by Noodleyman** [comment]
I am curious what error it throws when it's added via the the body hook? Would you mind sharing the error?

**Comment by SemperFiWS** [comment]
You will get the error:
<script> tag must not be included in a <div>

**Comment by abrookbanks** [comment]
Should I revert this commit?

**Comment by SemperFiWS** [comment]
No, the commit is perfect as it follows their guidelines.
My previous response was answering Alec's question about the error.

**Comment by abrookbanks** [comment]
Oh ok. Haha. Thanks.

**Comment by Noodleyman** [comment]
Thanks for the info. I would say that actually raises another question. Should the inclusion of the $BODY_JS scripts actually be moved outside of divs? 

It's currently nested within
`      <div class="off-canvas-wrap" data-offcanvas>
         <div class="inner-wrap">`

**Comment by abrookbanks** [comment]
I don't know. I would expect the best way to tackle this is to do a complete review using Google PageSpeed Insights.
