### ISSUE TITLE
Improve email test tool

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1239]
The test button causes a lot of confusion. If mail is chosen it returns "Test failed to execute". Merchants then think it doesn't work. It needs it be made clear that it tests SMTP methods only.

**Comment by havenswift-hosting** [comment]
How about getting rid of mail() completely ??  It is no where near as good for ensuring guarantee, is insecure and many hosting companies disallow it's use and it will likely be phased out.  SMTP is far superior and isnt exactly difficult to setup

**Comment by abrookbanks** [comment]
> How about getting rid of mail() completely ??

The majority of stores use mail() right now and the majority of web hosts block external SMTP. Granted that most web hosting companies allow you to setup SMTP from within their network but some (like a very large UK hosting provider) will make you pay extra for this privilege. 

On the whole the mail function is pretty reliable with the majority of hosts. Effectively it does the same thing a different way right?

**Comment by havenswift-hosting** [comment]
>>On the whole the mail function is pretty reliable with the majority of hosts. Effectively it does the same thing a different way right?

No, it is quite different. mail() is unauthenticated and so is much less secure and for that reason any email sent using it is treated much more likely as spam.  Many of the standard CubeCart order related emails can often be treated as spam (depending on a lot of other factors of course and on the receiving mail server spam filters) but change the sending server to use authenticated SMTP and 9/10 that will solve the problem

Web hosting companies that charge their customers for using SMTP should be lined up against a wall and shot and if that is the type of service they are providing then the customer should look for a different hosting company !

**Comment by abrookbanks** [comment]
Ok cool. So probably the best solution is to recommend the secure SMTP options.

**Comment by abrookbanks** [comment]
![screen shot 2016-09-16 at 10 24 43](https://cloud.githubusercontent.com/assets/4520803/18581305/e550edbc-7bf7-11e6-8497-f390b58f45ae.png)

**Comment by abrookbanks** [comment]
A customer on tech support literally just said... 

> The hosting provider don't want to open the 465 port for us. They suggest to use PHP mail().

**Comment by havenswift-hosting** [comment]
There is absolutely no reason not to open port 465 and plenty of reasons to use SMTP and I cannot see any reason why they would say that unless of course they charge for it.  They can use php mail() but most dont understand the differences and then complain when their emails dont get delivered !  Maybe recommend a new hosting company ??

**Comment by abrookbanks** [comment]
Thanks for all your help here Ian. :)
