### ISSUE TITLE
Too Many Gets

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#124]
With B1, I saw two, sometimes three `GET /` entries, and sometimes the same number of `GET /#`, in the network waterfall.

With B3, I see one pair. The one is 60.8K, its mate is 60.6K (fluctuates with debug enabled).

What is the purpose of `GET /#`?

**Comment by abrookbanks** [comment]
I'm not sure I'm with you. The foundation skin has a number of anchor tags with pound symbol and a JavaScript event removing the default event. This is standard practice I believe. 

Maybe I have misunderstood.

**Comment by abrookbanks** [comment]
I have closed this, please reply back if you think it still needs attention and I'll reopen it.

**Comment by bhsmither** [comment]
(Beta 5)
Found it. In box.language.php, there are `<img src="#">` tags.

Unlike anchor-href tags, which require a click event that can be interdicted, an image tag (or so I believe) cannot.

So, when the browser is parsing through the document making GET requests for the page's resources, `#` is interpreted by the web server as the extra stuff to pass along to the script, but the web server still fires up PHP and orders PHP to execute the default document (index.php). This (probably*) sends a complete new page which the browser ignores because it is expecting an image to replace the `<img>` tag.

**Comment by bhsmither** [comment]
My waterfall chart shows 828ms of waiting for this (with debug enabled, caching disabled).

Whether the browser will also wait for an image that isn't an image on the next page load -- I don't know.

Well, now I know. Yes, the browser will make a `GET #` request on following page loads.

I don't have caching enabled, so I don't know what impact enabling caching would have.

**Comment by bhsmither** [comment]
```
<a class="button white small" data-dropdown="language-switch" href="#">
  <img class="flag flag-US" src="#" alt="English (US)">
</a>
```
The cubecart.css file, line 207, makes the appropriate section of the sprite_flags.png display, but because the browser has no legitimate type of resource to actually show, the browser will show the alt attribute value.

I am going to try replacing `<img>` with `<span class="img">` and adjust the CSS.

**Comment by bhsmither** [comment]
I didn't use `<span class="img">`, just `<span></span>` and changed the CSS in cubecart.css, line 196, from `.flag` to:
```
span.flag {
	display: inline-block;
	vertical-align:middle;
	width: 16px;
	height: 11px;
	background:url(../images/sprite_flags.png) no-repeat
```
That fixed the current language image, but not the drop-down. There may need to be some padding-left and width values to make the `{$language.title}` not sit on top of the image in the background.

**Comment by abrookbanks** [comment]
Thanks Brian.
