### ISSUE TITLE
Store name or logo visible on admin

### ISSUE THREAD

**Issue by NaturalSigns** [cubecart/v6#1242]
I think the admin page could be improved to include either the store name or site logo. 

For example, the view below, at the moment is generic for all new sites.

![store name](https://cloud.githubusercontent.com/assets/10531097/18608366/27e82d10-7cdf-11e6-847f-e781ca13746a.jpg)

It shows branding for CUBECART, (understandably) and all the plugin modules.  But no actual **STORE NAME** in **TEXT** or **LOGO**.  

I have replaced the cubecart logo with my own logo to gain confidence i'm logged into the correct store, (though that's a bit cheeky to cubecart and not ideal as it will obviously get overwritten on upgrade).

![custom brand](https://cloud.githubusercontent.com/assets/10531097/18608417/6fb02a16-7ce0-11e6-8ac1-7ce2fbb2a33e.jpg)

Other things that also work is modifying the background colour for the store admin to match your site (on both the login screen and admin home).

![custom colour](https://cloud.githubusercontent.com/assets/10531097/18608494/9d9ddf70-7ce2-11e6-9ed6-620ea5eb7e10.jpg)

This may only be a big issue for people who host or support multiple site, but personally it has given me confidence I'm logged into the correct site before i start recklessly deleting things.

**Comment by Dirty-Butter** [comment]
I changed the background color to distinguish my test site from the live one. I think this is a good idea.

**Comment by Noodleyman** [comment]
you can make your own admin skins based on the default. I've done it a few times for some of my customers who have special requirements. Not suggesting this will work out of the box, but suggesting it's a way of doing what you want without having to reapply changes after every update.

**Comment by Dirty-Butter** [comment]
I took your advice and cloned the admin skin folders, giving my version a defaultred name. Easy to do and much simpler in the long run. I can see where someone who managed other people's stores would like to have the store name in the Admin pages.

**Comment by abrookbanks** [comment]
CubeCart needs as much exposure as possible. You can change the logo if you want.

**Comment by briansandall** [comment]
Easy enough to get the best of both worlds:
![issue1242](https://cloud.githubusercontent.com/assets/14335170/18643952/341a4c98-7e5c-11e6-84e2-e7c69a0c8b03.jpg)
Changes in 2 files in admin/skins/default folder:
```
// styles/layout.css add:
#header>span.powered_by_cc{ position:relative;top:-7px;}

// templates/main.php add these 2 lines after line 22:
<div id="header"> // this is line 22
    <a href="?"><img src="{$STORE_URL}/images/logos/logo.png" height="30" id="store_logo"></a>
    <span class="powered_by_cc"> Powered By </span>
```
Note that I left off the width element for the store logo on purpose; otherwise it will look funky if the dimensions are not perfect when scaling to a height of 30.

**Comment by NaturalSigns** [comment]
All good advice thanks (i've opted for custom admin skin with Brian's edit above).  Hadn't noticed the admin skin was a selectable option under Settings>layout (My Bad!), Ta for the contributions!

**Comment by briansandall** [comment]
One thing to note when making a custom skin is that any improvements and changes to the default skin will not be available in yours unless you merge the changes in yourself. There are several ways to do this, but I'd suggest using Git to do it for you:

1. Clone/fork the CubeCart Git repository

2. Make a branch off of master named 'admin_skin' or whatever

3. Make your changes on that branch and commit them

4. Periodically pull changes from master to your skin branch (e.g. when you update your store to a new version of CubeCart) and resolve any conflicts that come up; most of the time there shouldn't be any and the merge will just work, especially if you put your .css changes on a separate line (keep the original line as the last line if possible) or even in a separate file

This is a super easy and efficient way of keeping your skin up to date while maintaining your customizations.

**Comment by Dirty-Butter** [comment]
Based on Briansandall's suggestion, I wanted to do something that would be automatic for all my different admin pages.
This would be a nice tweak to include in stock code, as it doesn't require any editing to get the store logo, but still identifies the Admin area easily.

`````
<div id="header">
	<a href="?"><img src="{$SKIN_VARS.admin_folder}/skins/	{$SKIN_VARS.skin_folder}/images/logo.cubecart.png" width="158" height="30" id="logo"></a>
	<strong>{$CONFIG.store_name}</strong>
	<span class="user_info">{$LANG.settings.title_welcome_back} <a href="?_g=settings&node=admins&action=edit&admin_id={$ADMIN_UID}">{$ADMIN_USER}</a> - <a href="?_g=logout">{$LANG.account.logout} <i class="fa fa-sign-out"></i></a></span>
</div>
`````

**Comment by Dirty-Butter** [comment]
I KNEW I had seen this somewhere before - but couldn't find it. Had forgotten I had commented on it.

**Comment by abrookbanks** [comment]
:-)
