### ISSUE TITLE
Enhancement Request - Move the Update Product Prices feature

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1249]
I believe this feature should be moved, it's not in a suitable location. The "Update Product Prices" functionality is currently found within the "Products --> Assign To Category" tab. 

It would be clearer to move this to it's own tab, or alternativley rename the existing tab. 

I can see why it's been put there, but it's hidden away.

**Comment by abrookbanks** [comment]
Relates to #1252

**Comment by abrookbanks** [comment]
I'll close this as it will be covered with aformentioned issue.

**Comment by abrookbanks** [comment]
![screen shot 2016-09-21 at 15 01 55](https://cloud.githubusercontent.com/assets/4520803/18714036/5e455c2c-800c-11e6-8d3b-8586392a406b.png)

**Comment by abrookbanks** [comment]
![screen shot 2016-09-21 at 15 02 29](https://cloud.githubusercontent.com/assets/4520803/18714080/8a3e43a2-800c-11e6-98b3-202a3640826e.png)
