### ISSUE TITLE
6.0.12 Order notes timestamp is from host server, not from store settings

### ISSUE THREAD

**Issue by jasehead** [cubecart/v6#1253]
In Admin > Orders > (order number) > Notes tab, if an internal note is added the timestamp appears to be that of the host server and not the time set in Store Settings > Advanced for either UTC Offset or Timezone.

**Comment by abrookbanks** [comment]
This has something to do with the MySQL timezone.

I changed the following code:
https://github.com/cubecart/v6/blob/master/controllers/controller.admin.pre_session.inc.php#L51-L52

To:
```
$tz = $GLOBALS['config']->get('config', 'time_zone');
$tz = !empty($tz) ? $tz : 'UTC';
date_default_timezone_set($tz);
$GLOBALS['db']->misc("SET time_zone = '$tz'");
```

.. but it made no difference.

**Comment by abrookbanks** [comment]
Thanks for this.

**Comment by Dirty-Butter** [comment]
I updated the database customer_notes table using the queries in the upgrade db folder. All appears to be correct there, but the Notes on an order no longer have ANY time showing on them.

![customer_notes](https://cloud.githubusercontent.com/assets/6146505/21033380/636d8714-bd75-11e6-986c-67f0ed9d4a2a.jpg)

There are no error messages when I add a test note.

I'll re-check all my code changes, but thought I should let you know what I'm getting in case it's a code issue and not my mistake somewhere.
