### ISSUE TITLE
Discount code visibility on invoice

### ISSUE THREAD

**Issue by NaturalSigns** [cubecart/v6#1257]
Currently when you **print** an order that has had a discount code applied, the order will print with an **extra page** used just to state the discount code (as below).

Ideally this would be quoted on the main sheet where the discount code is applied (similar to how it shows on the store side basket). 

![discount codes](https://cloud.githubusercontent.com/assets/10531097/18745618/be35f5b6-80ba-11e6-986c-c880dc998781.jpg)

**Comment by abrookbanks** [comment]
The second page prints all notes for the order. When an order is placed a note is created with the discount code.

**Comment by NaturalSigns** [comment]
That's fair enough.  I end up discarding the second printed page as in the case of used discount codes its not really worth printing (the extra page).  Can be quite a few sheets if batch printing invoices but as the method covers all notes i can appreciate the logic.  I'll close this and many thanks for the clarification.

**Comment by abrookbanks** [comment]
Hmmm can you double side print? I agree it seems like a bit of a waste of paper.

**Comment by NaturalSigns** [comment]
If you're printing a batch of say 10 invoices (using the bulk processing features) then it prints as a single job so double side printing doesn't really work.  Its not a big concern to me, just wondered if discount code could be included on the 1st sheet without the mandated page break.
