### ISSUE TITLE
Foundation skin: Add to basket quantity field issue

### ISSUE THREAD

**Issue by Rob-Tea** [cubecart/v6#1258]
On a product page listing you have **no limit** on the quantity value you can enter, but on the basket page you do (999 max, 3 digits).

So, if as below you added a qty 1000 from the product page, that would work ok.

![qty product](https://cloud.githubusercontent.com/assets/10531097/18751068/8976182c-80d5-11e6-9ed6-c67c5d1f59a8.jpg)

But on the shopping basket page you are limited to 3 digits so you can now **not edit** the quantity to 1001 etc (without re-visitng the product page).

![basket 999](https://cloud.githubusercontent.com/assets/10531097/18751231/29df11f6-80d6-11e6-95f8-5eb9a3b0c86b.jpg)

I've simply changed my basket quantity field to a 'max length' to 6, without any issues (3 seems to low).

**Comment by Noodleyman** [comment]
I've had to do this same thing for a few people as well. Quite a common change at the moment. would be nice to have it sorted. :)
