### ISSUE TITLE
Deal with Missing File Possibility

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1260]
In `controller.admin.session.true.inc.php`, dealing with faults is mostly accomplished.

One other fault needs to be caught: a missing or unreadable plugin `config.xml` file.

However, `file_get_contents` returns false in this case, and `SimpleXMLElement` will throw an exception. So, suggest catching that exception, logging a trigger_error, and `GUI->setError($lang['module']['read_error'])`.

**Comment by abrookbanks** [comment]
> Well... weird. If the config.xml file is missing, the plugin will not show in the Manage Plugins list.

Yes the config.xml file is required.

**Comment by Noodleyman** [comment]
I am not sure if this is an issue or not. config.xml is a required part of any module. without it the module is incomplete so wouldn't be expected to work correctly.

So, it's only an issue if the developer didn't write the module correctly, so shouldn't the responsability of this be with the developer?

**Comment by bhsmither** [comment]
Your comments have merit, yet there are tests for the plugin's /admin/index.inc.php file. Hopefully there are tests for including any other required parts of the module.

Sure, blame the module writer for publishing a module that is incomplete (or whatever), but then, that's why the ability to test and catch exceptions are available. I always appreciate a graceful result instead of a blank white page exit.

I am working through this:
https://forums.cubecart.com/topic/51692-click-paypal-express-checkout-gives-me-a-blank-page/

There is something about that module that is not being dealt with properly.

**Comment by Noodleyman** [comment]
In that thread, it does look like the module hasn't been uploaded correctly or a file failed. might be worth deleting the module and re-downloading, or installing via the marketplace using an install token.

so in this case, it's "probably" a case of the user not uploading all the files correctly. 

It may be a nice thing if all modules did a check for required files before they were allowed to be enabled. If you try and enable it and a required file is missing or corrupt, there should be an error and the module not enabled. 

That should catch any other oversights by both developers and users.
