### ISSUE TITLE
Feature Request: Free Shipping Coupons

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1262]
It would be nice to see a new checkbox within coupons that allow you to select if the coupon offers free shipping. For stores where the shipping rates vary it's near impossible to offer a voucher for a customer to use to obtain free shipping as currently they are either based on a fixed price discount, or percentage discount.

**Comment by Dirty-Butter** [comment]
There IS a checkbox in 6.1.0 on the Coupon page to provide Free Shipping. But when I create a coupon, using my 6.1.0 test site, with only the free shipping box checked - on Checkout I get the warning "Sorry that code has expired".

**Comment by Dirty-Butter** [comment]
I edited the coupon to discount the price by one cent, as well as checked the Discount applies to Shipping AND Free Shipping boxes, and the coupon was then accepted. But it will not work for me if I don't put the penny discount.

**Comment by abrookbanks** [comment]
Please see: https://github.com/cubecart/v6/issues/1190
