### ISSUE TITLE
Swedish Language Pack

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1263]
(Unknown relevance)

In the file email_se-SE.xml, line 2:
`<emails version="2.0" language="en-GB">`

Suggest this be:
`<emails version="2.0" language="se-SE">`

(I do not know if CubeCart may not database the strings properly with this file having the wrong language identifier.)

Maybe check other language packs that simply incorporated the contents from another source.

**Comment by bhsmither** [comment]
The resolution to:
https://forums.cubecart.com/topic/51676-cubecart-does-not-send-mail-when-an-order-is-placed/
suggests CC is not falling back to `email_definitions.xml` if there is a specified but missing email language file.

**Comment by bhsmither** [comment]
According to ISO-639, Swedish is "sv", not "se". ISO-639 codes make it easy to reference a language without having to explicitly name the language (which would be written differently depending who was doing the writing).

So, accordingly, "sv" is the main language code. A language pack named "sv-SV" would be mainland Sweden, while "sv-FI" would be a language pack specific to Finnish who speak Sweden. (Just like "en-US" is for United States people who speak a variant of English).

**Comment by bhsmither** [comment]
This is an interesting conversation:
https://forums.cubecart.com/topic/51703-swedish-language-pack-issue-changedelete-text-in-sale/

**Comment by abrookbanks** [comment]
This integration is provided by a 3rd party developer. I don't want to interfere in their coding whether right or wrong. :)
