### ISSUE TITLE
BUG - Sorting Sale Items does not work

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1264]
Tested in CC612. It isn't possible to sort sale items.  When you select a sort criteria, the form is POSTED. This triggers a redirect, changing the posted values into URL parameters.

The SEO class then re-writes the URL and performs another redirect, which drops the parameters and your back where you started. 

Details near the end of this forum thread:
https://forums.cubecart.com/topic/51662-sorting-search-or-advanced-search/#comment-220516

**Comment by bhsmither** [comment]
In CC614, if processing falls through to line 1770 (search terms is not an array and there are no joins to deal with), the search term must be on a cat_id or the word 'sale'.

Within this block of code, the default sort is on Name:ASC regardless of admin setting.

Suggest:
```
From 1784-1790:
} else {
  $order['name'] = 'ASC';
}

if(is_array($order)) { 
  $order_string = 'ORDER BY '.key($order).' '.current($order);
}

To:
} else {
  $order['field'] = $GLOBALS['config']->get('config', 'product_sort_column');
  $order['sort'] = $GLOBALS['config']->get('config', 'product_sort_direction');
  if (empty($order['field']) || empty($order['sort'])) {
    unset($order); // store settings were somehow invalid
  } 
}

if(is_array($order)) { 
  $order_string = 'ORDER BY '.$order['field'].' '.$order['sort'];
}
```

**Comment by bhsmither** [comment]
Also suggest line 1781:
```
From:
$order[$field] = (strtolower($direction) == 'asc') ? 'ASC' : 'DESC';

To:
$order['field'] = $field; $order['sort'] = (strtolower($direction) == 'asc') ? 'ASC' : 'DESC';
```

**Comment by abrookbanks** [comment]
This was a nightmare! Turned out that the regex expected an ampersand in the path. 

`?_a=saleitems` failed but `?_a=salesitems&foo=bar` worked.

Fix was to make the extra query parameters optional from the second parameter onwards. 

regex is the ultimate head screw.

**Comment by Noodleyman** [comment]
This needs to be reopened. the latest change to address the sort didn't fix the issue.

I replicated by installing a clean 6.1.5 store, adding two new products and checking the sale items list from the store front. You can't sort it, same behaviour related to the SEO redirect as originally noted in the forum thread

**Comment by Noodleyman** [comment]
as a temporary work around, I've wrapped the redirect in some logic specific to sale items page. 

if(!isset($_GET['_a']) || (isset($_GET['_a']) && $_GET['_a'] !== "saleitems")){					
httpredir($seo_url);
}

**Comment by abrookbanks** [comment]
Working on a weekend? :(

**Comment by Noodleyman** [comment]
Unfortunately so... Need to catch up on a backlog and I don't want to let people down, so a few weeks of gridning the weekends are required.
