### ISSUE TITLE
Enhancement Request - Adding Navigation Tree Depth

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1265]
A request for a minor change in CC to return some more data for use within the menu tree. This is quite useful when porting older themes which can make use of this type of data. The below changes add a new element that contains the depth of the menu items for use within the smarty "BRANCH" data which is used in the element.navigation_tree.php template file.  

catalogue.class.php
FIND:
`public function getCategoryTree($parent_id = 0) {`

REPLACE WITH:

```
public function getCategoryTree($parent_id = 0, $level = 0) {
$level++;
```

FIND:
`'cat_id' => $category['cat_id'],`

AFTER ON A NEW LINE ADD:
`'cat_level' => $level`

FIND:
`if ($GLOBALS['config']->get('config', 'catalogue_expand_tree') && $children = $this->getCategoryTree($category['cat_id'])) {`

REPLACE WITH:
`if ($GLOBALS['config']->get('config', 'catalogue_expand_tree') && $children = $this->getCategoryTree($category['cat_id'], $level)) {`

**Comment by abrookbanks** [comment]
Thanks, I can see the need for this.

**Comment by abrookbanks** [comment]
Fixed with commit https://github.com/cubecart/v6/commit/36f85029e542ddaf83a8c3b3b907afdf4c0cfc20
