### ISSUE TITLE
Display inconsistency when login required to view prices

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1268]
The home page and category views display products with 'Add to Basket' or 'Out of Stock' buttons, but the product pages themselves do not:
![cc1268-1](https://cloud.githubusercontent.com/assets/14335170/18920652/e9930744-8556-11e6-84cc-55373165e3e6.jpg)
Out of stock product - note there is no indication that it is out of stock at this level unless logged in:
![cc1268-2](https://cloud.githubusercontent.com/assets/14335170/18920654/ecdf3008-8556-11e6-9c2d-8c9f1ddc982e.jpg)
// In-stock product - note that the 'Add to Basket' element is not present unless logged in:
![cc1268-3](https://cloud.githubusercontent.com/assets/14335170/18920659/ee9396c8-8556-11e6-9107-f824bc28a8ff.jpg)

Perhaps we can change the buttons to something less revealing, such as:
![cc1268-4](https://cloud.githubusercontent.com/assets/14335170/18921035/227ac1a4-8558-11e6-856b-1fce3f7994db.jpg)

**Comment by briansandall** [comment]
@abrookbanks That commit seems to be for issue #1265, not this one... are you sure you meant to close this?

**Comment by abrookbanks** [comment]
Sorry yes typo..

**Comment by abrookbanks** [comment]
Thanks y'all
