### ISSUE TITLE
Customer Groups to be Editable

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1270]
Request that admin, Customer List, Customer Groups tab, the existing groups be **editable** as opposed to re-creating a group with updated info and deleting the existing group.

**Comment by Noodleyman** [comment]
the group name and description is already editable, you click on it and it becomes an editable field.

**Comment by bhsmither** [comment]
Right. My bad. I'll add a helpful hint to the page.

**Comment by Noodleyman** [comment]
:), I must admit, it's not obvious at all, I thought they were read only when I first started to work with customer groups as well, just by randomly clicking around I noted they can be edited.

The same process of editing a field is used on other pages in the admin area as well, for example the "Currency Name"
