### ISSUE TITLE
{BUG} Product Options not included in order overview and email

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1271]
I've had a customer report a strange issue to me this week and after researching it I've found a significant bug / gap in functionality.

When an order is placed, each item is added to the order_inventory table. If options exist they are added in raw array format to the order_inventory.options_array field, and then a serialized version using the function "serializeOptions()" is added to the order_inventory.product_options field.

In this case, there is a disconnect between the data in the fields. Not all options have made it into the product_options field, data is missing.

I looked into how this data is added to the field, and found that it uses the serializeOptions() function, which is where there is a gap. This function specifically queries the DB table CubeCart_option_assign to look for the assign_id, if it can't find it then it set's it to 0.  In this case, "Options Sets" are returning 0 as the assign_id.

The next step calls "getOptionData()" function with the option_id and assign_id (0). 

And this is where we have a problem. This function is not supporting option sets correctly.  if the assign_id is LESS THAN 0, it tries to check the option_value table. however, 0 is not less than 0. Even if it was less than or equal to 0, the logic used to gather the option sets / return data is flawed, it's actually not doing it at all.

The getOptionData function needs an overhaul as currently if you use option sets to assign your options the options as NOT included in the mail to the customer, or the order summary. you can only view them as an admin on the order inventory tab.

**Comment by abrookbanks** [comment]
I expect this is a skin fault. Older skins had an incorrect variable name for the product option key in this file: https://github.com/cubecart/v6/blob/master/skins/foundation/templates/content.product.php

This didn't matter in version 5 but does in version 6. If you view the template code and see;

> {$OPT.

changed it to;

> {$option.

I'm not sure if it affects the assign or option_id key or both.

**Comment by Noodleyman** [comment]
it's not skin related and is reproducable in foundation.

**Comment by abrookbanks** [comment]
Relates to #1060

**Comment by abrookbanks** [comment]
Relates to #788

**Comment by abrookbanks** [comment]
I believe there are known issues with options sets....

**Comment by Noodleyman** [comment]
is there an estimate on time to resolution?

**Comment by Noodleyman** [comment]
just confirming, I did trace the issue back to the getOptionData() function, it doesn't actually support option sets. the comments suggest it should but the code will never work with option sets, so it's this function that needs a re-write / overhaul. :)

**Comment by Noodleyman** [comment]
Are there any updates to this bug?

I've now got two customers who are being critically impacted by this issue using CC 6.1.3

**Comment by abrookbanks** [comment]
Not yet.

**Comment by Noodleyman** [comment]
Is there a version of CC that this will be targeted for?

Trying to guage timescales for my customers who are struggeling due to the glitch. Cheers :)

**Comment by abrookbanks** [comment]
It's the most important bug on my radar but I'm extremely thin on resources and still really need extra help I just can't afford.

**Comment by abrookbanks** [comment]
It's a really complex issue. I need to set aside at least a whole day which I just can't do right now. I've been fixing other lower priority bugs around gaps in the day.

**Comment by Noodleyman** [comment]
Thanks for the feedback, it's appreciated. :)

Totally agree with it's complexity, I think it's one of those items that once something is adjusted it's going to have a knock on effect, so will require some thorough testing.

**Comment by abrookbanks** [comment]
This is related to #1060 and will be part of that fix. The only way I can see this working is to convert option sets to normal options in bulk.

**Comment by abrookbanks** [comment]
Closed as it will be fixed with #1060.

**Comment by Noodleyman** [comment]
This issue was closed with a note saying it will be fixed in #1060.... but in 1060, there is a note saying that 1060 is closed and fixed as part of this issue... 

which one actually fixes it?

**Comment by abrookbanks** [comment]
#1060 is still open

**Comment by abrookbanks** [comment]
Tested option sets, standard options and mixture of both with positive results. All option data makes it to order details and email.
