### ISSUE TITLE
Skins dont display installed version

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1272]
Installed skins dont display the current installed version as all other extensions do so there is no way for a store owner to know if they are running the latest version

**Comment by abrookbanks** [comment]
Thanks this is a great suggestion.
![screen shot 2016-10-05 at 11 50 41](https://cloud.githubusercontent.com/assets/4520803/19110519/57be5c28-8af2-11e6-8976-7180f6208db4.png)
