### ISSUE TITLE
Saved session data doesn't get cleaned up

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1273]
If you have to create a sessions directory, and use a custom ini file with:
`session_save_path(CC_ROOT_DIR.'/sessions')`

The directory NEVER gets cleaned up. In one store today I found over 100,000 files in such a directory. This data should be cleaned / purged when older than X (X to be defined).

**Comment by havenswift-hosting** [comment]
This happens regardless of whether a custom path is used but is definitely a massive problem.  With a large number of CubeCart sites across various servers, we have to manually run Linux tmpwatch every eight hours as had many hundreds of thousands - space isnt an issue but number of available inodes for the /tmp partition is !
