### ISSUE TITLE
HiPay module doesnt work

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1276]
It appears that this module has never worked due to some syntax errors in the coding.  A modified version is attached with changes to the gateway.class.php and the config.xml (version increase)

[Hipay.zip](https://github.com/cubecart/v6/files/513372/Hipay.zip)

**Comment by abrookbanks** [comment]
Fixed. Thanks Ian. 

https://www.cubecart.com/extensions/payment-gateways/hipay - 1.0.2

**Comment by havenswift-hosting** [comment]
Please bear in mind that this current version doesnt work 100% yet.  It does take payments but doesnt update the status of the order correctly - we are working on fixing this (it isnt the change that you offered - that line should be commented out as it is).  Should have a fix in the next day or so
