### ISSUE TITLE
Number of Latest Products displayed not always correct

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1277]
The way the Latest Products is selected in cubecart.class is inefficient and due to the method used, often returns the wrong number of products.

Currently it does one select to get the products and then does a second to exclude any that are in hidden categories.  This is inefficient from an SQL point of view as it should do a join to the category index table, then have an additional where clause to exclude items where the category is disabled.  A consequence of this is if a store has the setting to display 12 and one is excluded because it is in a hidden category then only 11 will be displayed

**Comment by Dirty-Butter** [comment]
I have added code on the homepage so only in stock items show (essentially making them members of a hidden category). I get this same oddity with a blank space, and the same thing happens with a Homepage Sales items plugin if they are out of stock.

**Comment by briansandall** [comment]
It seems that only the status of a category has any effect on whether a product will show up as 'latest' using the existing code - the category 'visibility' only affects whether the category itself is listed in the menu.

Assuming that is the behavior we would like to keep:
```
// change line 93 to:
$where = $GLOBALS['catalogue']->outOfStockWhere(array('I.status' => '1', 'I.latest' => '1'));

// change line 96 to:
$latestProducts = $GLOBALS['db']->select('CubeCart_inventory AS I JOIN CubeCart_category AS C ON C.cat_id=I.cat_id AND C.`status`=1', 'I.*', $where, array('I.date_added' => 'DESC', 'I.product_id' => 'DESC'), (int)$GLOBALS['config']->get('config', 'catalogue_latest_products_count'));

// remove lines 99-110
```
I'll make a PR for it.

**Comment by abrookbanks** [comment]
Fixed with https://github.com/cubecart/v6/pull/1404
