### ISSUE TITLE
Canada Post plugin NEEDS a Warning

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1279]
Bsmither has helped several people on the forum who could not get Canada Post to work. There needs to be a prominent warning on the Marketplace description that the host must have Port 30000 open, or it will not work.

https://forums.cubecart.com/topic/51737-canada-post/#comment-220814

**Comment by abrookbanks** [comment]
I added a bold note to the extension listing. Thanks.

**Comment by abrookbanks** [comment]
https://www.cubecart.com/extensions/shipping-methods/canada-post
