### ISSUE TITLE
Unable to build sitemap is store is offline

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1286]
If your store is offline and you try to rebuild a new sitemap you get the error "failed to rebuild sitemap". There is no information within the error to suggest it is because your store is offline. I had to go through the source code to figure it out.

Looking at the code, it looks like an oversight. rebuilding the sitemap sends a ping to google to notify of a new sitemap.

Currently:
`		if($GLOBALS['config']->get('config', 'offline')=='0') {
			if (file_put_contents($filename, $mapdata)) {
				// Ping Google
				$request = new Request('www.google.com', '/webmasters/sitemaps/ping');
				$request->setMethod('get');
				$request->setData(array('sitemap' => $store_url.'/'.basename($filename)));
				$request->send();
				return true;
			}
		}`

But, this should be:
`		if (file_put_contents($filename, $mapdata)) {
			if($GLOBALS['config']->get('config', 'offline')=='0') {
				// Ping Google
				$request = new Request('www.google.com', '/webmasters/sitemaps/ping');
				$request->setMethod('get');
				$request->setData(array('sitemap' => $store_url.'/'.basename($filename)));
				$request->send();
				return true;
			}
		}`

**Comment by abrookbanks** [comment]
Good find thanks Alec.
