### ISSUE TITLE
Dashboard "My Notes" field can't be empty

### ISSUE THREAD

**Issue by NaturalSigns** [cubecart/v6#1287]
Working from the "my notes" field available on the dashboard.  Clear the contents and click save.  it will refresh with the same data.  To resolve this you can leave just a space in the field and click save (i.e. it won't allow the field to be empty).

![my notes field](https://cloud.githubusercontent.com/assets/10531097/19354913/58f8e044-9160-11e6-8020-0b00c29c5485.jpg)

**Comment by abrookbanks** [comment]
Thanks!! :)
