### ISSUE TITLE
Description and Length of product precis

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1288]
The "Length of product precis" setting only applies to the main product description. if you have a short description you can essentially make it as long as you like.

The Length of product precis setting should apply to both the short and main descriptions.

Secondly, the short description field used for latest products is pulled directly from the DB, there is no attempt to use the main description if the short description is undefined, or apply Length of product precis value to it. 

Recycling the code from the categopry view:
NOTE: this doesn't include an udpate to apply Length of product precis to both short and main desriptions.
`$product['description_short'] = ($product['description_short']) ? ($product['description_short']) : ((strlen($product['description']) > $GLOBALS['config']->get('config', 'product_precis')) ? substr(strip_tags($product['description']), 0, $GLOBALS['config']->get('config', 'product_precis')).'&hellip;' : strip_tags($product['description']));`

**Comment by abrookbanks** [comment]
Thanks Alec.

**Comment by Noodleyman** [comment]
this needs to be re-opened as it still isn't working correctly in 6.1. The short desc is still b eing directly read from the DB for latest prodcuts and not respecting the config.

**Comment by abrookbanks** [comment]
When you say config.. do you mean the length?

**Comment by Noodleyman** [comment]
The store setting "Length of product precis" which will trim lengthy text to a character limit.  The short description can be made up of either the prices / character limit of the main description, or the short description.

However, the setting Length of product precis is only respected for main product descriptions. Essentially if I have a length short description, it never gets trimmed to the configured limit

**Comment by abrookbanks** [comment]
This works fine on my development store.....

**Comment by Noodleyman** [comment]
try it for latest products "description_short" field.

**Comment by abrookbanks** [comment]
![screen shot 2016-11-28 at 13 30 39](https://cloud.githubusercontent.com/assets/4520803/20670009/e0a08c54-b56e-11e6-9c8f-3f0e41cdc052.png)
![screen shot 2016-11-28 at 13 30 33](https://cloud.githubusercontent.com/assets/4520803/20670010/e0a2aed0-b56e-11e6-8a3f-c7af1ee0ec52.png)
![screen shot 2016-11-28 at 13 30 25](https://cloud.githubusercontent.com/assets/4520803/20670011/e0ab251a-b56e-11e6-95a5-735b9bbc72fc.png)

**Comment by abrookbanks** [comment]
> try it for latest products "description_short" field

I wasn't aware it was used there.. maybe in a custom skin?

**Comment by Noodleyman** [comment]
Yes, it's used in custom skins, however the behaviour of the short description length should be consistant, if you add the short description to latest products, (as many customers want) it doesn't respect the same rules/logic as short descriptions do elsewhere in CubeCart.

**Comment by abrookbanks** [comment]
Ok it hadn't been tested elsewhere...

**Comment by Noodleyman** [comment]
it was part of the original description for this thread ;)

**Comment by abrookbanks** [comment]
I knew that. :-|

**Comment by abrookbanks** [comment]
Done! :)

**Comment by Noodleyman** [comment]
Thank you Sir 👍

**Comment by bhsmither** [comment]
The example entry of the Short Description isn't very short. Shorter than the (regular) Description, no doubt, as the regular description is intended for the View Product page and the Short Description is intended for elsewhere -- View Category for Foundation.

My opinion: have the View (template) truncate the Model (data) if the View doesn't have the space for it.
