### ISSUE TITLE
Customer ID not populated in CubeCart_downloads Table

### ISSUE THREAD

**Issue by svrabel** [cubecart/v6#1289]
Periodically, customers will report not receiving download emails and links not appearing in their account. Upon investigating, the CubeCart_downloads table for that order does not have a customer_id populated.

That is the only difference that I can see related to digital downloads in any of the related tables. Does this sound like a likely culprit?

**Comment by abrookbanks** [comment]
Bug existed with unregistered customers. Test checked with unregistered and registered customers always populated the customer id. Thanks for sharing the issue.
