### ISSUE TITLE
No gift certificate email sent if it is the only item

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1291]

**Comment by bhsmither** [comment]
Maybe a duplicate of #764?

**Comment by abrookbanks** [comment]
Yeah looks like it. 👍🏻

**Comment by bhsmither** [comment]
Some of this made it into the CC611 milestone, but fix 9fcb202 didn't.

May we have the state of this fix?

**Comment by abrookbanks** [comment]
This isn't needed because it checks against the database now instead if it's been sent or not.

See:
https://github.com/cubecart/v6/blob/master/classes/order.class.php#L1272-L1282
https://github.com/cubecart/v6/blob/master/setup/db/install/structure.sql#L198
https://github.com/cubecart/v6/blob/master/setup/db/upgrade/6.1.0.sql#L32
