### ISSUE TITLE
Make reCaptcha selectable per area

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1292]
It would be good to be able to select which areas the reCaptcha is switched on for - had several requests myself for this and it has recently been a forum topic

https://forums.cubecart.com/topic/51752-resolved-recaptcha

**Comment by Dirty-Butter** [comment]
I'm now using the code provided in the forum topic, and it works perfectly for me - even on our 6.1.0 test store.

**Comment by havenswift-hosting** [comment]
DB that would work for your specific requirements but maybe not for somebody else that wants it off / on in different areas. This code would not work in a situation where it was made selectable and also needs core code changes which is never a good idea :)

**Comment by Dirty-Butter** [comment]
I agree totally Ian. Just wanted to put my 2 cents in that being able to choose where recaptcha is applied would be a great improvement.

**Comment by havenswift-hosting** [comment]
:)

**Comment by Dirty-Butter** [comment]
Sorry to see this one closed, even with the invisible captcha :(

**Comment by abrookbanks** [comment]
Any closed feature request with no milestone is still under consideration. We don't want 1001 open feature requests which makes it look like CubeCart has many problems or to be badly managed.

**Comment by Dirty-Butter** [comment]
I just read your comment about that on  another thread I had commented on. THAT makes me feel MUCH better, as I completely agree that bugs and features need to be separated.

**Comment by abrookbanks** [comment]
Great thanks.
