### ISSUE TITLE
Replace PclZip with ZipArchive (PECL zip)

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1295]
I know PclZip is a third party tool but maybe there is a newer version that sorts this issue

PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; PclZip has a deprecated constructor in /home/cubecar3/public_html/includes/lib/pclzip/pclzip.lib.php on line 190

**Comment by abrookbanks** [comment]
YUK.. its not been updated in 7 years!!!!!!!!

Maybe its time to ditch it and use native PHP zip functions instead... 

http://php.net/manual/en/class.ziparchive.php
