### ISSUE TITLE
Install Docs error

### ISSUE THREAD

**Issue by hairy-dog** [cubecart/v6#130]
In the "how to install CC" page, it says to set various directories to chmod777 but it forgets to tell you to do it to: 
/backup 
/images
/languages

The installer asks you to, though.

**Comment by havenswift-hosting** [comment]
Also not relevant if using suPHP which any good hosting company will do.  If you are using a hosting company that requires you to set directory permissions to 777 then it is very insecure !

**Comment by abrookbanks** [comment]
It's a difficult area. CubeCart doesn't require them to be 0777 but uses the php function is_writable to check permission. I appreciate that 0777 may be insecure but many hosting configurations will ONLY write to that. It's impossible for PHP to detect what chmod value is the tightest keeping write access.

**Comment by abrookbanks** [comment]
At the same time CC needs to be as easy to install as possible. We risk losing users if this is too complex on install. 0777 works every time from my experience and it gives the user specific directions. Maybe on detection of suphp this value can be different. Surely web hosting companies should automatically fix insecure file permissions with automated scheduled tasks?

**Comment by hairydogltd** [comment]
"Surely web hosting companies should automatically fix insecure file permissions with automated scheduled tasks?"

You would soon piss off a lot of users if you routinely change the permissions on their files! chmod 777 is not secure and the instructions should say to change them back to a workable but safe settings when the install is done. It shouldn't be left to the users or their hosting companiy.. Yes, 777 is daft, but the webserver user needs to be able to write to directories owned by the user who uploaded them.

**Comment by abrookbanks** [comment]
Just thinking out loud really. I think the best option is not to suggest 0777 but merely tell the user to make the file/folder writable with a link to more detailed documentation.

**Comment by havenswift-hosting** [comment]
777 permissions on directories that need to be writeable are only required if your hosting company is not using suPHP or hasnt configured suexec with FCGI or CGI php handlers, as processes are run as user "nobody" rather than owned by yourself - hence 777 permissions being insecure, as ANY user on that server has permission to write to that directory.

The only reason hosting companies use this php configuration is because it is the quickest which means they can cram more users onto a single server which should tell people two things 1) the hosting company doesnt care about the security of your website and 2) they are likely to also fill the server up to capacity (and often oversell it).  Dont EVER use a hosting company that requires you to set 777 permissions.

Al - I agree that best approach is to specify that directories should be writeable - suPHP and suexec will do that automatically and will just work !

**Comment by abrookbanks** [comment]
How do you mean "will do that automatically and will just work". Will they secure it automatically?

**Comment by havenswift-hosting** [comment]
When a directory is created on a suPHP (or suexec) enabled php server it is owned by that user and created with 755 permissions so is writeable ONLY by that user and nobody else.  No directory permissions ever need to be changed on suPHP based systems - in fact changing them to 777 instantly makes a secure system insecure

**Comment by abrookbanks** [comment]
Thanks for this. I have added the extra folders and changed the wording to:

> Ensure that the following folders are writable by the web server. It's important to keep the folder permissions as tight as possible for security reasons. We recommend starting with an octal CHMOD value of "0755". If they are still not writable work up towards "0777" until they are.

**Comment by hairydogltd** [comment]
The core issue is that the manual CubeCart install is done by uploading directories full of files by ftp, which means they are owned by the user who uploaded them. That is almost certainly not the user account that the web server runs under, but that web server account does have to be able to write to some of the directories.

All that is needed is a simple install script that runs as the web server user that creates the directories, and unpacks the files. That would make it easier to do, and would also automatically give the directories the correct permissions. It would only have to be quite a small script.

You could also offer the "completely manual" option as it is.

**Comment by abrookbanks** [comment]
That makes sense. cPanel has same FTP user and web server normally. Appreciate the help.

**Comment by havenswift-hosting** [comment]
"The core issue is that the manual CubeCart install is done by uploading directories full of files by ftp, which means they are owned by the user who uploaded them. That is almost certainly not the user account that the web server runs under, but that web server account does have to be able to write to some of the directories."

This is only ever the case if the server is running DSO or is running CGI or FastCGI without suexec (all of which are insecure).
