### ISSUE TITLE
GC Page Hides Prices

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1301]
When the store is configured to hide product prices, the store page for Gift Certificates shows the hidden price string for the cert's MinVal and MaxVal.

This is because `CubeCart->_certificates()`, line 855, uses `Tax->priceFormat()`, which will return the hidden price string as appropriate.

While not _wrong_, per se, it just looks stupid.

**Comment by abrookbanks** [comment]
Fixed with https://github.com/cubecart/v6/commit/68ff0d4a83f5cc0a78f864ab104495cbf4e85cd2
