### ISSUE TITLE
Allow for Foreign Currency Notation for GC

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1303]
When purchasing Gift Certificates, the storefront Gift Certificate page requests the value of the cert.

In `CubeCart->_certificate()`, line 831, there is:

```
preg_replace('/[^0-9.]*/', '', $_POST['gc']['value'])
```

Some currencies use the comma as the decimal separator.

Suggest restricting (via 3.cubecart.validate.js) the value to whole units without currency symbol (i.e., dollars, pounds, euros). Add a clue in the skin next to the field to explain this, and/or the language string describing GCs.

There will still be the need for server-side handling of the returned value (non-updated skins).

Perhaps an enhanced version of `Tax->_removeSymbol()` (to deal with more than one leading non-digit characters, etc.). Perhaps use PHP's NumberFormatter.
http://php.net/manual/en/class.numberformatter.php
http://php.net/manual/en/numberformatter.parsecurrency.php

**Comment by abrookbanks** [comment]
Added support for comma and specified currency as default.
