### ISSUE TITLE
Add full page cache and session cache options

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1306]
Now that REDIS has been added as a cache handler, can we also get Full Page Cache and Session Cache added as options.

**Comment by havenswift-hosting** [comment]
FPC is quite a big implementation but session cache using REDIS should be relatively straight forward so could this be looked at ASAP rather than waiting for both ?

**Comment by abrookbanks** [comment]
Trying to bend my mind around this. It would need to cache documents, homepage, categories and products. I'm just not sure how to go about the dynamic parts like basket, session, language selection etc.

**Comment by abrookbanks** [comment]
.. error message etc.. Eeek.

**Comment by havenswift-hosting** [comment]
Full Page Cache does sound complicated and not sure how it is implemented either, however to be honest, I am not sure it is worth the effort at this stage.  Magento Community Edition doesnt even have it, it is only available with the full paid Enterprise Edition.

Of much more interest and considerably easier to implement would be using REDIS for session caching

**Comment by havenswift-hosting** [comment]
memcache and memcached could also be used for session storage

**Comment by abrookbanks** [comment]
I don't think we can do FPC but we can certainly cache whole sections like homepage and product detail page.

**Comment by havenswift-hosting** [comment]
It isnt possible with dynamic content - these are a couple of good (Magento based) explanations

https://www.demacmedia.com/magento-commerce/magento-tutorials/understanding-full-page-cache/
http://www.kingletas.com/2012/09/how-does-magento-full-page-cache-works.html

By all means, if you are able to implement static full page cache then that would be brilliant but as I said, session cache would be a great start

**Comment by abrookbanks** [comment]
I'd read that first one already. :) Thanks.

**Comment by abrookbanks** [comment]
I've got full page cache working using the existing cache methods. Now to see if I can bring in the dynamic elements!

**Comment by abrookbanks** [comment]
Page loads are down from about 0.15 seconds to 0.01 seconds.

**Comment by havenswift-hosting** [comment]
Great progress !

**Comment by abrookbanks** [comment]
This is proving to be exceptionally complex. Loading just the dynamic bits is just as heavy as a full page load. Close to pulling the plug on this. :(

**Comment by havenswift-hosting** [comment]
That is a shame as your early results seemed very promising although FPC is notoriously difficult.

Maybe look at the session caching as that should be much easier and would make a big difference. 

The main improvement with cache though would be with sorting out https://github.com/cubecart/v6/issues/1536 as that constantly removes cache benefits

**Comment by havenswift-hosting** [comment]
I know you spent some time look at FPC and had problems pulling in the dynamic elements so can that be put on the back burner and session cache be added for a quick win ?

**Comment by abrookbanks** [comment]
CubeCart needs a complete rewrite for any kind of decent cache.
