### ISSUE TITLE
Mass units in settings.index.inc.php

### ISSUE THREAD

**Issue by RedKiteDesigns** [cubecart/v6#1307]
Trivial - but irritating

Please replace "Lb" with "lb" and "Kg" with "kg"

I know you fixed Kg -> kg in the language file so I was surprised when "Kg" turned up again

**Comment by abrookbanks** [comment]
I can't see this in incorrect case?

![screen shot 2016-11-03 at 16 53 36](https://cloud.githubusercontent.com/assets/4520803/19976050/25770520-a1e6-11e6-86c2-e81b2d4ba725.png)

**Comment by RedKiteDesigns** [comment]
Sorry - didn't explain $CONFIG.product_weight_unit returned Lb or Kg

**Comment by abrookbanks** [comment]
I can't change this as the value is likely to be used by numerous extensions. Doing so could easily corrupt 1st and 3rd party extensions.

**Comment by RedKiteDesigns** [comment]
No worries - we'll always have lcase.
