### ISSUE TITLE
Enhancement to By_Weight shipping

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1309]
A client of ours wanted an enhancement to the By_Weight shipping method to be able to restrict shipping rates to certain shipping groups.  We have added this and happy to feedback the changes to core !

By Weight will now display customer groups that are configured with the default group 0 (Retail group) also shown.

![by_weight_cust_groups](https://cloud.githubusercontent.com/assets/6114431/19686617/3e64e0c8-9ac2-11e6-9226-3d5c4d1ae39b.png)

It is achieved by adding an additional parameter to the rate string for the customer group that it is applicable to 

So an example configuration where the store has 2 additional customer groups and the default

Example 1 - Links all rates to customer groups 0, 1 and 2
0.15:2.75:0-1-2,0.30:3.75:0-1-2,0.35:8.25:0-1-2,2:10.30:0-1-2

Example 2 - Links only to customer group 2:
0.5:11.00:2,2.5:17.00:2,5:27.50:2

So a hyphen is used to separate multiple customer groups ie 0-1-2 etc

[By_Weight.zip](https://github.com/cubecart/v6/files/550602/By_Weight.zip)

**Comment by abrookbanks** [comment]
Thanks so much Ian. I'll take a look at this as soon as I can.
