### ISSUE TITLE
setup fails ungracefully with renamed admin

### ISSUE THREAD

**Issue by hairydogltd** [cubecart/v6#131]
If you routinely change the name of the admin folder (as I do) for a small extra layer of security, you can't do it until after finishing the setuop, or the CC6 setup script fails with a white screen instead of saying it can't find its setup folder.

**Comment by abrookbanks** [comment]
Upgrading an existing store with renamed admin file/folder? I think fresh installs will need the default structure.

**Comment by hairydogltd** [comment]
This was a fresh install. I don't expect it to work:  just to fail more helpfully. An error message would be good!

**Comment by abrookbanks** [comment]
Got it! Thanks.

**Comment by abrookbanks** [comment]
In an attempt reproduce this I renamed admin.php and the admin folder. I then started a fresh install which worked successfully. The only issue was that the link to admin from the end of the setup process was wrong. How do I get a white screen. From what I can see the setup process has no dependency on any files or folders in the admin area.

Why would you change the name of the admin folder before install?

**Comment by hairydogltd** [comment]
I'm sorry, I don't know. I tried it on two different servers, both times simply renaming the admin folder before installing, and just got a white page.

The reason to change the name of the local copy is so that you can update an existing installation more easily. The reason to do it for a fresh install is because you forgot to change it back!

**Comment by abrookbanks** [comment]
OK thanks I'll experiment some more. :shipit:

**Comment by abrookbanks** [comment]
I'm sorry but I've not been able to reproduce this. Best practise would be to rename after install.
