### ISSUE TITLE
trivial issue - oversized icon file

### ISSUE THREAD

**Issue by RedKiteDesigns** [cubecart/v6#1315]
I noticed that images/icons/prod_type_1.png is ridiculously large for a tiny png. 47,945 bytes!

It seems it was saved incorrectly.

I have uploaded the original and a 'corrected' version of the file - a nice slim 559 bytes

![prod_type_1](https://cloud.githubusercontent.com/assets/13659798/19785899/4e6fc834-9c93-11e6-9ad8-71125a495213.png)
![prod_type_1_old](https://cloud.githubusercontent.com/assets/13659798/19785900/4e768fb6-9c93-11e6-8388-a82745fa5209.png)

**Comment by abrookbanks** [comment]
Thanks!! :)
