### ISSUE TITLE
Smarty IF Qualifiers

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#132]
With respect to:
http://www.smarty.net/docs/en/language.function.if.tpl

I suggest that where any kind of ambiguity could exist, use the `===`.

For example, in content.product.php:
```
		{foreach from=$OPTIONS item=option}
	  	  {if $option.type == '0'}
```
There may be the very odd case that $option.type is false-like: 0, '0', -zls-, false, null, or not set.

I accidentally (well, intentionally, actually), coded for an array element of `$OPTION` to be empty. I still got a drop-down selector for it because `type` was an illegal string offset for `$option`, which is good enough for `==`.

**Comment by bhsmither** [comment]
Be aware, if you choose to do this:
`{if $option.type === Catalogue::OPTION_SELECT}{* '0' *}`
it will fail because the constants are integers.

**Comment by abrookbanks** [comment]
Thanks Brian. I will bear this in mind. At the same time I am fearful to make changes as I don't want to risk introducing bugs.
