### ISSUE TITLE
6.1.0 BUG in Coupon Code

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1321]
See https://forums.cubecart.com/topic/51801-610-need-help-finding-flaw-in-my-coupon-code/

**Comment by Dirty-Butter** [comment]
I reverted all the code changes having to do with Coupon Code in 6.1.0 back to 6.0.12, and now Checkout with a Coupon is working correctly again. So your concern about checkout being blocked by the notification was evidently correct.

**Comment by abrookbanks** [comment]
Thanks Rosemary. This has now been resolved.
