### ISSUE TITLE
Include in latest products

### ISSUE THREAD

**Issue by Sandengen** [cubecart/v6#1324]
After update to 6.1.0 the option "include in latest products" (in the product-panel), is not working correctly here. When include in latest products is switched off for a given product, the products still show as latest products on the front page. I tried changing my template to the standard foundation template to see if it was related to my own template, but the problem is still the same. 
Is it a bug?

**Comment by briansandall** [comment]
Did you update your database schema as well? If not, do so and the problem should go away.

'Latest products' should only include those that are checked as such, but there is now also a 'featured product' setting for each product that controls whether they can appear in the 'Featured Product' box on the front page independently of the 'latest product' setting.

See #976 for the discussion about 'featured' vs 'latest' products.

**Comment by abrookbanks** [comment]
Did you run the setup process after uploading the files?

**Comment by Sandengen** [comment]
Yes, setup process was run before the problem occurred. 
But, now it's solved, I think the problem was related to my old admin folder and admin.php files - I had already custom named these before the upgrade. Changing these back to just to the default "admin" names, and doing the upgrade again made my day.  Without this prosess I ended up with doubles of admin files, and I guess something must have gone wrong in the name changing prosess. 
Thanks for looking at it and helping out.
