### ISSUE TITLE
Make it clear the dropzone box can be clicked for old style uploads

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1325]

**Comment by Dirty-Butter** [comment]
WP has a Browse for Image button in the Dropzone box.

**Comment by abrookbanks** [comment]
That's exactly what I had in mind. cPanel does too.

**Comment by abrookbanks** [comment]
![screen shot 2016-11-28 at 16 36 13](https://cloud.githubusercontent.com/assets/4520803/20676770/d1f5607a-b588-11e6-9c45-48d3e006d027.png)
