### ISSUE TITLE
Auto assign latest images in file manager reload

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1326]
Relates to #1325 and https://forums.cubecart.com/topic/51814-why/

Maybe on reload it puts the new image files at the top of the list under "Just Added" and checked ready for save.

**Comment by Dirty-Butter** [comment]
Just tested this. It arbitrarily assigned the star to the second image I uploaded all at the same time in a series of 4 numerically number named images - but it DID automatically check/star all four. On Save/reload the starred image automatically showed up. 

It would be very helpful if there could be a way to see the new images in the FileManager box without going on a hunt for them (I use the Browser search). I have many folders within FileManager, so "Just Added" would not be easily visible for me and others with folders.

**Comment by abrookbanks** [comment]
Yup that would be great. :) I'll see if we can improve it further.. This has been quite challenging..

**Comment by abrookbanks** [comment]
I think the best solution is to add a toggle to "Show all images" / "Show assigned" only. Maybe after upload it should default to "Show assigned only".

**Comment by Dirty-Butter** [comment]
That sounds great!! I hope at some point you will be able to code FileManager in the Product listing so that the assigned images can be moved into a folder.

**Comment by Dirty-Butter** [comment]
Tested this just now - the toggle isn't really obvious, but it works perfectly. Is there any way to make the toggle more obvious that it is a link? Would a pair of checkboxes be possible?

**Comment by abrookbanks** [comment]
Hmm yes. Maybe it can be a button. I'll see what I can do.

**Comment by abrookbanks** [comment]
When you click a folder it will now allow the files to be uploaded there. Big improvement.

**Comment by Dirty-Butter** [comment]
My install is anything but stock, although I don't think I have any modifications to anything to do with the FileManager - I see the Upload Destination:/(nothing after it like the name of the folder I clicked) but uploading an image does Not load it into that folder.

Am I doing it wrong?

**Comment by abrookbanks** [comment]
If you click a folder in the file manager it will change. Right now it doesn't create folders just allow you to upload to existing ones once clicked.

**Comment by Dirty-Butter** [comment]
I did click the folder and then upload, but it ends up as the file after all our image folders.

**Comment by abrookbanks** [comment]
👍

**Comment by Dirty-Butter** [comment]
OK, now that it's working - is there any way to rearrange the image section that is off to the right so the page would be responsive for small devices? It does not view properly until I get to 980 wide. I had previously used the master image, as it showed details better, but I had it stacked on top of the Filemanager box so it fit my Kindle width properly.

**Comment by abrookbanks** [comment]
> rearrange the image section that is off to the right so the page would be responsive for small devices

Probably. The admin control panel is not responsive at all so I don't think this is something I'd want to start unless we decide to make the whole admin panel responsive.
