### ISSUE TITLE
Fixed Discount to Pending Order Not Working

### ISSUE THREAD

**Issue by SteveCGS** [cubecart/v6#1327]
If an order status was Cancelled, and then changed to Pending, and a Fixed Price Discount is then applied in the 'Inventory' tab, although the discount shows correctly in the users Order History on the front end, once they click the Complete Payment button the discount is removed and does not show at the checkout.

**Comment by Dirty-Butter** [comment]
What version are you on? 6.1.0 had issues with Coupon Codes that were fixed in 6.1.1.

**Comment by SteveCGS** [comment]
It's not an issue with Coupon Codes; the discount was manually entered in:

Orders > [Select an order number] > Inventory (tab)

The version is 6.0.12.

**Comment by abrookbanks** [comment]
Once completed this isn't possible. I suppose the fix to prevent this is to disable the complete payment button if an order history of completed exists.

**Comment by abrookbanks** [comment]
There is no way to fix this without a complete rewrite. The complete payment button takes the saved basket data and populates the cart. It doesn't take the order information at all. 

This is beneficial in the sense that things like shipping get checked in real time and stock checks are taken again. It may be someone else purchased the last item for example.
