### ISSUE TITLE
Upgrade to 6.1.1 deletes REDIS options parameter

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1329]
Have just upgraded one test store that was running 6.0.12 and had the REDIS entries for caching

$glob['cache'] = 'redis';
$glob['redis_options']=array('parameters' => array('database' => 3));

After the upgrade, the new global.inc.php file had the following

$glob['cache'] = 'redis';
$glob['redis_options'] = '';

ie it removed the options !

**Comment by abrookbanks** [comment]
thats annoying.. it shouldn't after 6.1.1 though..

**Comment by abrookbanks** [comment]
I've closed this as I can't imagine the fallout is significant. Sorry for the inconvenience.

**Comment by havenswift-hosting** [comment]
The fallout is massively significant !  At the very least it removes the specification of which database is used so users then default to DB 0 - so if one or more users have the same thing, then they clear each others cache and too many users doing that at the same time will cause a cache rush which can cause performance issues.  At worst, if different server and port settings are being specified, then these will be lost causing redis connection issues and a store that doesnt work

**Comment by abrookbanks** [comment]
The way I see it Redis was introduced in 6.1.0. Very shortly after 6.1.1 was released. Surely this affects those who tried redis at that time. I know of yourself and one other only. Those using redis after this time will be adding it from 6.1.1 and as a result won't have their config wiped on upgrade. 

There seems little point in fixing this.

**Comment by havenswift-hosting** [comment]
Need to re-open this as another report that when doing an auto upgrade within admin, it retains the caching method as REDIS but removes the parameters. I.e. After upgrade

$glob['cache'] = 'redis';
$glob['redis_options']=array('parameters' => array('database' => 3));

After the upgrade, the new global.inc.php file had the following

$glob['cache'] = 'redis';
$glob['redis_parameters'] = '';

While this might not affect many users yet, it is significant for the reasons mentioned before and surely it cannot be difficult to preserve any settings already in the global.inc.php file ?
