### ISSUE TITLE
Search Logic Fault

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1330]
Regarding #487, there is an improper fallthrough in certain conditions.

At line 1650, when `$search_mode == 'fulltext'`, but `$search_str_len >= $max_word_len` is false, control is passed to line 1681.

In this section of code `$search_mode` is expected to be either **LIKE** or **RLIKE**.

I will experiment with lines 1681-1684 from:
```
  } else {

    $this->_sort_by_relevance = false;
    $like = '';
```
to:
```
  } else {
    // Use RLIKE if not already RLIKE or LIKE
    $search_mode = ($search_mode == 'RLIKE' || $search_mode == 'LIKE') ? $search_mode : 'RLIKE';
    $this->_sort_by_relevance = false;
    $like = '';
```

**Comment by abrookbanks** [comment]
Thanks Brian!

**Comment by abrookbanks** [comment]
Damnit the commit above of https://github.com/cubecart/v6/commit/a655ba4ede2addf364d750a9a0103b944fec6bd1 is for issue #1331

**Comment by bhsmither** [comment]
I've come across a situation where these three words:
'fulltext'
'like' vs 'LIKE'
'rlike' vs 'RLIKE'
could cause misunderstanding.

Because the method signature uses the lowercase 'fulltext' as a default for `$search_mode`, the implication is that the other search modes are also lowercase.

The code is using the actual value of `$search_mode` as the SQL keyword in the query.

Also, the fix https://github.com/cubecart/v6/commit/07df226fe2a22dd74895049a68c9db32b7ed9674 uses these actual SQL keywords.

Suggest adding necessary code to disconnect 'fulltext', 'like', and 'rlike' from the SQL keywords "LIKE" and "RLIKE", such as:
```
$search_mode = in_array(strtolower($search_mode), array('rlike','like')) ? $search_mode : 'rlike';
```
and everywhere else that compares for `$search_mode`, then
```
if(strtolower($search_mode) == 'rlike') {
  $like_keyword = "RLIKE";
  $like_prefix = '[[:<:]]';
  $like_postfix = '[[:>:]].*';
} else {
  $like_keyword = "LIKE";
  $like_prefix = '%';
  $like_postfix = '%';
}
```
then (partial statement follows)
```
$like = " AND (I.name ".$like_keyword." '".$regexp."' OR ......
```

**Comment by abrookbanks** [comment]
Thanks Brian!
