### ISSUE TITLE
Language REGEX

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1331]
For the constant LANG_REGEX, the pattern is: `^([a-z]{2})\-?([A-Z]{2})?$`
Starts with a group that is, [a-z] for two characters
Then a dash which may or may not be there
Then a group that is, [A-Z] for two characters that may or may not be there
End

Thus, the string `enUS` passes. Note the optional dash is missing

Suggest: `^([a-z]{2})(\-[A-Z]{2})?$`
Starts with a group that is, [a-z] for two characters
Then a group that is, a dash followed by [A-Z] for two characters, that may or may not be there
End

This may necessitate code tweaks elsewhere, to be discussed in other issues.

The constant EMAIL_FILE follows the suggestion above, but see the next comment.

**Comment by bhsmither** [comment]
Suggest this version: `^([a-z]{2})(?:\-([A-Z]{2}))?$`
Starts with a group that is, [a-z] for two characters
Then a **non-capturing group** that is, a dash followed by a group that is, [A-Z] for two characters, all of which may or may not be there
End

This *should* keep the $match array in `preg_match($a,$b,$match)` indexed as is currently expected.

**Comment by abrookbanks** [comment]
I couldn't get your regex to work but from my testing this did work. 

```
<?php
$code = 'en-US';
$regex = '#^([a-z]{2})\-([A-Z]{2})?$#';
echo "<h1>Match</h1>";
preg_match($regex, $code, $match);
var_dump($match);
echo "<h1>Validate</h1>";
var_dump(preg_match($regex, $code));
?>
```

The above PHP code had the same match values as ```#^([a-z]{2})\-?([A-Z]{2})?$#``` but requires the hyphen (or dash or whatever you want to call it.
