### ISSUE TITLE
Creating Language Setting to Config has Wrong Syntax

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1333]
In settings.language.inc.php, near lines 208-213:
```
} elseif (isset($_POST['create']) && !empty($_POST['create']['code'])) {
  if ($GLOBALS['language']->create($_POST['create'])) {
    $GLOBALS['main']->setACPNotify($lang['translate']['notify_language_create']);
    ## Set status to disabled to begin with
    $GLOBALS['config']->set('languages', false, array($_POST['create']['code'] => false));
    httpredir(currentPage(null, array('language' => $_POST['create']['code'])));
```
In the above `Config->set()`, because there is no `$element` specified, the incoming `$data` array replaces the entire existing `Config['languages']` array. That's not what is wanted.

Suggest:
```
$GLOBALS['config']->set('languages', $_POST['create']['code'], false);
```
This, for example, sets `Config['languages']['zz-ZZ']` to false.

However, there is an issue in `Config->set()` that presents an obstacle.

**Comment by bhsmither** [comment]
Considering that language statuses are JSON encoded as string zeroes, and the browser sends back checkbox values as string zeroes, suggest:
```
$GLOBALS['config']->set('languages', $_POST['create']['code'], "0");
```

**Comment by abrookbanks** [comment]
Thanks Brian.
