### ISSUE TITLE
Config->set() Rejects Acceptable Data

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1334]
For example:
```
Config->set('languages', 'zz-ZZ', false);
```
For the `$data` argument, the value is (bool)false`.

The values of the `$data array`, or `$data` itself, is run through `stripslashes(string $str)`.

My experiments show that `stripslashes(false)` returns corruption (actually, tab-space, or maybe an empty string, I cannot yet tell exactly).

(Line 235) When checking `$data` - now corrupted - against `Config->get('languages','zz-ZZ')` (Note: `Config['languages']['zz-ZZ']` **does not yet exist**), the result is `true` because `false == ''`.

So a false value fails getting set.

**Comment by abrookbanks** [comment]
```
$var = stripslashes(false);
var_dump($var);
```
Returns;
```
string(0) ""
```

**Comment by abrookbanks** [comment]
Tested with set of simple data such as a tab, line break, true, false, string and array and all came back positive! :)

**Comment by abrookbanks** [comment]
Code added for the ```_clean``` method of the config class.
