### ISSUE TITLE
Creating Language Creates Bad Header Info for File

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1335]
Compared to currently available language packs, `Language->create()` builds an XML file with three incorrect, and two missing, nodes.
```
268: $xml->setElement('locale', $array['code'], false, false);
Use: $xml->setElement('code', $array['code'], false, false);
See Note 2 below.

269: $xml->setElement('character_set', 'utf-8');
Use: $xml->setElement('character_set', 'utf-8', false, false);

273: $xml->setElement('maxVersion', '5.0.*', false, false);
Use: $xml->setElement('maxVersion', '6.1.*', false, false);
See Note 3 below.

Add: $xml->setElement('default_currency', $array['currency_iso'], false, false);

Add: $xml->setElement('text_direction', $array['text_direction'], false, false);

276: $xml->setElement('parent_language', $array['parent']);
277: $xml->setElement('override_parent', 'true', false, false);
See Note 1 below.
```
Note 1: I have not studied how identifying a parent language works, but the currently available language packs show `<override></override>` with presumably containing the language code of the parent.

But if 276 is, in fact, `'parent_language'` coming from `$array['parent']`, then the value will be a language code and the statement should be:
```
$xml->setElement('parent_language', $array['parent'], false, false);
```
Suggest these changes, as well as in admin, a free-form text entry box to specify the currency ISO for the language being created and a drop-down selector to choose 'ltr' or 'rtl'.

Note 2: Many of the other Language methods, and elsewhere, enumerate and use the `<code>` node to manage what languages are available.

Note 3: Presuming this language XML file format will remain at `version="2.0"` for the remainder of the CC61* family. Assuming there is any core code that actually uses this info.

(Also, please look at the Turkish language pack, `<default_currency>` being **TL**, which may be incorrect.)

**Comment by abrookbanks** [comment]
This all needs a bit of an overhaul.

**Comment by abrookbanks** [comment]
parent_language and override_parent are not used anywhere and I don't know the thinking behind it. As a result I removed them. There were a few bugs around this and the commit above should make it all a bit friendlier.
