### ISSUE TITLE
Redis parameters passed by redis_options not being used

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1340]
Using the line below in global.inc.php, the database parameter is not being used and all keys are being stored in the default DB0

$glob['redis_options'] = array('parameters' => array('database' => 3));

**Comment by abrookbanks** [comment]
Correct. redis_options are only set if redis_sentinals are too.. 

https://github.com/cubecart/v6/blob/master/classes/cache/redis.class.php#L32-L38

Try changing
```
$glob['redis_options'] = array('parameters' => array('database' => 3));
```

To:
```
$glob['redis_sentinels'] = array('parameters' => array('database' => 3));
```

**Comment by abrookbanks** [comment]
I'm not sure if this is a bug or not yet.

**Comment by havenswift-hosting** [comment]
Redis Sentinal is something totally different - it provides High Availability and is quite different to standard Redis

**Comment by bondimedical3** [comment]
follow

**Comment by abrookbanks** [comment]
This is just a naming convention issue. I changed redis_sentinels to redis_parameters.

If you want parameters and options to be sent then make sure both redis_parameters and redis_options are on the global file. If you just want parameters just specify redis_parameters. If you just want to use the defaults don't use either.

**Comment by havenswift-hosting** [comment]
Can you update the https://support.cubecart.com/Knowledgebase/Article/View/235/41/how-do-i-enable-apc-memcached-or-xcache page with specific examples of what should be used in each - I have no idea !

**Comment by abrookbanks** [comment]
It's all on here:
https://github.com/nrk/predis

You can just set a string or array. 

e.g. $client = new Predis\Client('tcp://10.0.0.1:6379');
```
$glob['redis_parameters'] = 'tcp://10.0.0.1:6379';
```

e.g. $client = new Predis\Client(['scheme' => 'unix', 'path' => '/path/to/redis.sock']);
```
$glob['redis_parameters'] = array('scheme' => 'unix', 'path' => '/path/to/redis.sock');
```

e.g. $client = new Predis\Client([
    'tcp://10.0.0.1?alias=first-node',
    ['host' => '10.0.0.2', 'alias' => 'second-node'],
]);
```
$glob['redis_parameters'] = array('tcp://10.0.0.1?alias=first-node' => array('host' => '10.0.0.2', 'alias' => 'second-node'));
```

e.g. $client = new Predis\Client('tcp://10.0.0.1', ['profile' => '2.8', 'prefix' => 'sample:']);
```
$glob['redis_parameters'] ='tcp://10.0.0.1';
$glob['redis_options'] = array('profile' => '2.8', 'prefix' => 'sample:');
```

etc...

**Comment by bondimedical3** [comment]
And how would you specify a particular database to be used instead of 0?

**Comment by abrookbanks** [comment]
Something like this I think....
```
$glob['redis_parameters'] = array('host'     => '127.0.0.1', 'port'     => 6379, 'database' => 15);
```

**Comment by havenswift-hosting** [comment]
I can confirm that this is now working as expected - tested on three different CubeCart installations all configured to use a different REDIS database.

**Comment by abrookbanks** [comment]
Great!
