### ISSUE TITLE
Config->set() Tweak

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1342]
Regarding #1334, considering the "cleanup" code deals strictly with strings, and yet attempts can be made to set non-string values, it would be wise to "stringify" what we can, and skip what we cannot.

The following accepts a non-string value by not corrupting the value by trying to shove it through stripslashes.
```
From:
//Clean up the config array
if (is_array($data) && !empty($element)) {
  array_walk_recursive($data, function(&$s,$k){return stripslashes($s);});
  $data = $this->_json_encode($data);
} else if (is_array($data)) {
  array_walk_recursive($data, function(&$s,$k){return stripslashes($s);});
} else {
  $data = stripslashes($data);
}

To:
//Clean up the config array
if (is_array($data) && !empty($element)) {
  array_walk_recursive($data, function(&$s,$k){return (is_string($s)) ? stripslashes($s) : $s;});
  $data = $this->_json_encode($data);
} elseif (is_array($data)) {
  array_walk_recursive($data, function(&$s,$k){return (is_string($s)) ? stripslashes($s) : $s;});
} else {
  $data = (is_string($data)) ? stripslashes($data) : $data;
}
```
**Also**, next, a check is made to see if the data is the same as it was. If it is, we don't need to do anything.

However, if a Config element does not yet exist, and it is compared against some thing that looks empty (the string `"0"` for example), then the test will evaluate to true and the key/value will not get set.

So, suggest:
```
From:
if ($this->get($config_name, $element) == $data) {

To:
if ($this->has($config_name, $element) && $this->get($config_name, $element) == $data) {
```

**Comment by bhsmither** [comment]
As alluded to in #1333, `json_encode()` restricts the type of input to scalar and array of scalar.

That is, the argument cannot contain `true`, `null`, or `false`, but rather can use the reserved lowercase strings `"true"`, `"null"`, `"false"`.

**Comment by abrookbanks** [comment]
Ok. I haven't got to that bug report yet. Thanks I'll keep this in mind.

**Comment by abrookbanks** [comment]
Right now;

```
$GLOBALS['config']->set('test', 'key', null);
var_dump($GLOBALS['config']->get('test', 'key');
```
returns;
```
bool(false)
```

**Comment by bhsmither** [comment]
Be careful!

You are setting it, then you are getting it.

But you have **not** proven that Config `has()` it. Config->get() returns false when Config does not have it.

**Comment by abrookbanks** [comment]
I checked the base64 encoded json string directly in the database all good.

More checks tomorrow...

**Comment by abrookbanks** [comment]
```
$GLOBALS['config']->set('test', 'key', false);
var_dump($GLOBALS['config']->get('test', 'key'));
var_dump($GLOBALS['config']->has('test', 'key'));
```
Output:
```
bool(false) bool(false)
```

Setting false is not working.

**Comment by abrookbanks** [comment]
After commit https://github.com/cubecart/v6/commit/de87f927ca4560e03617b7503a52a4b4fc11a133

```
$GLOBALS['config']->set('test', 'key', false);
var_dump($GLOBALS['config']->get('test', 'key'));
var_dump($GLOBALS['config']->has('test', 'key'));
```
Output:
```
bool(false) bool(true)
```
