### ISSUE TITLE
Force use of renamed admin.php file

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1343]
If the stores configuration has been set to use a custom admin.php filename then if there is an administrative error and the admin.php file is uploaded it must be blocked.

**Comment by abrookbanks** [comment]
I'm not sure this can be applied to the admin folder.

**Comment by Dirty-Butter** [comment]
If they can't get into the dashboard via admin.php - they wouldn't be able to use the admin folder files would they? Still doesn't make any sense to me that the old admin.php still worked. But I'm not the only one confused by this. See https://forums.cubecart.com/topic/51831-610-to-611-upgrade-issue/#comment-221570 - Perhaps make an Announcement?

**Comment by Dirty-Butter** [comment]
Is there supposed to be a blank page or a 404 statement when this dead end admin.php login is attempted? I get a blank white page.

**Comment by abrookbanks** [comment]
If the store is configured to use a renamed admin.php file then if there is an admin.php file it will give a 404 now. If not it won't.

In other words if the global file is configured for admin_123456.php then only that can now be used.

I'm not normally up at 5:40am but with the focus on US election I'm glued to twitter etc.

**Comment by Dirty-Butter** [comment]
Must have been a cache thing. Now that I've rebooted the computer, the admin.php file does goto my 404 page.
