### ISSUE TITLE
Minor bug in Advanced Search

### ISSUE THREAD

**Issue by mackecm2** [cubecart/v6#1344]
Minor bug, first discovered in release 6.1.1. 
From what I can see, it happens when a customer uses the "Advanced Search" facility and only enters two characters followed by a space. 
In the original case, the customer was searching for "ac dc", but it seems to happen with any advanced search that begins with two characters followed by a space, or just on their own. A search for "ac/dc" works fine.

From a customer's point of view, they see this:
![no_products](https://cloud.githubusercontent.com/assets/7928551/20107183/758f13ee-a5cf-11e6-9783-dac955def131.png)

instead of this:
![no_products_found](https://cloud.githubusercontent.com/assets/7928551/20107193/847a2790-a5cf-11e6-9000-dcee2db6ab1e.png)

but we get two system error messages:

`1	8 Nov 2016 09:58:06	File: [catalogue.class.php] Line: [1715] "SELECT I.* FROM CubeCart_inventory AS I LEFT JOIN (SELECT product_id, MAX(price) as price, MAX(sale_price) as sale_price FROM CubeCart_pricing_group WHERE group_id = 0 GROUP BY product_id) as G ON G.product_id = I.product_id WHERE I.product_id IN (SELECT product_id FROM `CubeCart_category_index` as CI INNER JOIN CubeCart_category as C where CI.cat_id = C.cat_id AND C.status = 1) AND I.status = 1 AND ((I.use_stock_level = '0') OR (I.use_stock_level = '1' AND I.stock_level > 0)) AND (I.name fulltext '%ac%%dc%' OR I.description fulltext '%ac%%dc%' OR I.product_code fulltext '%ac%%dc%') LIMIT 20 OFFSET 0 " - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'fulltext '%ac%%dc%' OR I.description fulltext '%ac%%dc%' OR I.product_code fullt' at line 1	`

`2	8 Nov 2016 09:58:06	File: [catalogue.class.php] Line: [1717] "SELECT I.* FROM CubeCart_inventory AS I LEFT JOIN (SELECT product_id, MAX(price) as price, MAX(sale_price) as sale_price FROM CubeCart_pricing_group WHERE group_id = 0 GROUP BY product_id) as G ON G.product_id = I.product_id WHERE I.product_id IN (SELECT product_id FROM `CubeCart_category_index` as CI INNER JOIN CubeCart_category as C where CI.cat_id = C.cat_id AND C.status = 1) AND I.status = 1 AND ((I.use_stock_level = '0') OR (I.use_stock_level = '1' AND I.stock_level > 0)) AND (I.name fulltext '%ac%%dc%' OR I.description fulltext '%ac%%dc%' OR I.product_code fulltext '%ac%%dc%') " - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'fulltext '%ac%%dc%' OR I.description fulltext '%ac%%dc%' OR I.product_code fullt' at line 1`

**Comment by bhsmither** [comment]
Probably related to #1330.
