### ISSUE TITLE
Performance - New DB index

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1345]
Adding a new DB index on CubeCart_seo_urls has had a huge improvement in perormance, and also caching capability on one of my larger stores (20k+ products).

Adding a new index on columns "type" and "item_id" allows MySQL to use the one index for both of the where conditions in the main SQL query that references the table.  After adding it all of those queries were also being cached where as previously there were not.

It's had a MAJOR impact on performance, and I am recommending this be added as part of the ugprader

**Comment by abrookbanks** [comment]
Relates to #1348 & #1346

**Comment by abrookbanks** [comment]
Here is another inconsistency.. The install structure SQL shows...

```
CREATE TABLE IF NOT EXISTS `CubeCart_seo_urls` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `path` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `type` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `item_id` int(25) unsigned DEFAULT NULL,
  `custom` enum('0','1') COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`path`),
  KEY `id` (`id`),
  KEY `type` (`type`),
  KEY `item_id` (`item_id`),
  KEY `custom` (`custom`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1; #EOQ
```

**Comment by abrookbanks** [comment]
The upgrade to 5.0.0b6 shows;

```
CREATE TABLE `CubeCart_seo_urls` (
	`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	`path` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
	`type` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
	`item_id` int(25) unsigned DEFAULT NULL,
  PRIMARY KEY (`path`),
  KEY `id` (`id`),
  KEY `type` (`type`),
  KEY `item_id` (`item_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ; #EOQ
```

So.. in theory your store should have keys anyway.. 

I think the only solution is for the 6.1.2 upgrade to check every table to make sure they have the correct indexes.

**Comment by abrookbanks** [comment]
...
6.6.6.sql upgrade later has;

```
ALTER TABLE `CubeCart_seo_urls` ADD `custom` ENUM('0','1') NOT NULL DEFAULT '0'; #EOQ
ALTER TABLE `CubeCart_seo_urls` ADD INDEX (`custom`); #EOQ
```

So they *should* all be covered.

**Comment by abrookbanks** [comment]
closing see #1348
