### ISSUE TITLE
Performance - DB Indexes

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1346]
Recommending adding the following list of indexes. It allows caching to work better and also improves overall performance.

ALTER TABLE CubeCart_pricing_quantity ADD INDEX (`group_id`, `product_id`);
ALTER TABLE `CubeCart_pricing_quantity` ADD INDEX (`quantity`);
ALTER TABLE `CubeCart_category_index` ADD INDEX (`product_id`, `cat_id`);

Will add others as/when I find them.

**Comment by abrookbanks** [comment]
This is tricky because my dev store has some of these indexes. Running the SQL commands to create them can cause duplicate indexes.

I think a PHP script needs to be written to check for indexes and act accordingly... 

Excuse me thinking out loud...

**Comment by abrookbanks** [comment]
Relates to #1348

**Comment by abrookbanks** [comment]
Closing .. see #1348
