### ISSUE TITLE
Database Table(s) Without Primary Key

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1348]
Please review the strategy for having some tables without a **Primary** Key.

For example, CubeCart_downloads, CubeCart_modules, and others.

(Not that I know the critical benefit of having a Primary Key vs a regular Key.)

**Comment by havenswift-hosting** [comment]
One difference is that a table with a PRIMARY key is editable via phpMyAdmin

**Comment by bhsmither** [comment]
Which is why I brought it up - but as such, that is a convenience. The table can still be updated with an appropriate query.

Having any kind of an index is crucial to optimize efficiency - as discussed by Noodleyman, but a Primary vs Regular, I still don't know.

**Comment by havenswift-hosting** [comment]
All tables should have a PRIMARY key and it is even more important when using Innodb tables.

The primary key for a table represents the column or set of columns that you use in your most vital queries. It has an associated index, for fast query performance. Query performance benefits from the NOT NULL optimization, because it cannot include any NULL values. With the InnoDB storage engine, the table data is physically organized to do ultra-fast lookups and sorts based on the primary key column or columns.

**Comment by bhsmither** [comment]
My initial research between a Primary Key, Unique Key, and a regular Key shows that each have their respective operational characteristics. Any kind of a key drastically improves searching and row maintenance.

In the specific case of CubeCart_downloads, having a Key is good, but the question that remains is, what are the consequences of _this table_ having an index which can hold non-unique, possibly including _null_ values?

This loose capability may help in constructing a "multiple download files per digital product" solution. (A project I am currently working on.) However, adding another column works just as well.

**Comment by abrookbanks** [comment]
From my testing all the upgrade SQL commands work so long as the keynames are consistent on all CubeCart stores. For example the `CubeCart_category_languag`e table has a keyname `id` for column `translation_id` whereas `CubeCart_modules` has keyname `module_id` for column  `module_id`.

**Comment by Dirty-Butter** [comment]
I tried running this as a Query within Admin and then in cPanel. Both times I get the error message shown below and nothing changes.
`````
ALTER TABLE `CubeCart_alt_shipping` DROP INDEX `id`, ADD PRIMARY KEY (`id`) USING BTREE; #EOQ
ALTER TABLE `CubeCart_alt_shipping_prices` DROP INDEX `id`, ADD PRIMARY KEY (`id`) USING BTREE; #EOQ
ALTER TABLE `CubeCart_category_language` DROP INDEX `id`, ADD PRIMARY KEY (`translation_id`) USING BTREE; #EOQ
ALTER TABLE `CubeCart_downloads` DROP INDEX `id`, ADD PRIMARY KEY (`digital_id`) USING BTREE;
ALTER TABLE `CubeCart_inventory_language` DROP INDEX `id`, ADD PRIMARY KEY (`translation_id`) USING BTREE; #EOQ
ALTER TABLE `CubeCart_modules` DROP INDEX `module_id`, ADD PRIMARY KEY (`module_id`) USING BTREE; #EOQ
`````
**## Error Message**

SQL query:

ALTER TABLE `CubeCart_alt_shipping` DROP INDEX `id` ,
ADD PRIMARY KEY ( `id` ) USING BTREE;

MySQL said: Documentation
#1091 - Can't DROP 'id'; check that column/key exists

**Comment by abrookbanks** [comment]
> Can't DROP 'id'; check that column/key exists
This is exactly what I was expecting as per comment https://github.com/cubecart/v6/issues/1346#issuecomment-261920924

I don't think every CubeCart store, depending on upgrade history may have the same key with the same key name necessarily.

**Comment by abrookbanks** [comment]
From what I can see the install schema now has good indexes.

I'd suggest a 6.1.2 upgrade script to list all database table keys and match them up against a mapped array. This can then remove any duplicate keys and add any missing ones ignoring any unrecognised ones from modified code.

**Comment by abrookbanks** [comment]
![screen shot 2017-02-06 at 16 52 27](https://cloud.githubusercontent.com/assets/4520803/22656914/aafe442e-ec8c-11e6-9bf9-44f8f9eb6873.png)

**Comment by abrookbanks** [comment]
![screen shot 2017-02-06 at 17 17 58](https://cloud.githubusercontent.com/assets/4520803/22657960/3a6cd460-ec90-11e6-8696-35214c8e66e9.png)

**Comment by Dirty-Butter** [comment]
I'm still not able to run the db queries to change keys manually - I DO now see the Maintenance screen with the triangles and orange background of the error messages, but no messages are there. All this part of my install is stock.
![maintenance_no_error_messages](https://cloud.githubusercontent.com/assets/6146505/22746040/2c2fbf4e-ede8-11e6-988d-058fe70a4009.png)

**Comment by Dirty-Butter** [comment]
I tried running upgrade setup but still get these blank orange bars.

**Comment by abrookbanks** [comment]
The blanks bars are most likely caused by missing phrases from the language/definitions.xml file.

**Comment by abrookbanks** [comment]
This block;
‘‘‘<group name="maintain">
    <string name="missing_index" introduced="6.1.5"><![CDATA[%s has no key set. Expecting %s.]]></string>
    <string name="wrong_index" introduced="6.1.5"><![CDATA[%s has a key type %s but expecting %s.]]></string>
    <string name="table_indexes" introduced="6.1.5"><![CDATA[Indexes]]></string>‘‘‘

**Comment by Dirty-Butter** [comment]
Ugh - as many times as I checked, I missed those definition additions. So, now the last questions on this topic (I hope!) Now that I have the information, I don't have a clue how to use it without taking the chance of ruining my database tables. Will there be any guidance on how to change these tables? What happens if the admin does nothing? I doubt I would be the only one who is reluctant to make manual changes of this type to their database.

**Comment by havenswift-hosting** [comment]
What happens if you do nothing is that your store will respond more slowly both because missing indexes slow down your store but it also puts more load on the MySQL server in general (an unindexed search puts a LOT more load on the server than an indexed one does).

As your sites are hosted with us, if you log a support ticket, I am happy to do this work for you

**Comment by abrookbanks** [comment]
I've only upgraded a few sites today but already found a lot of wrong,missing and even doubled indexes. This tool is pretty handy.

**Comment by havenswift-hosting** [comment]
I completely agree - upgraded and checked quite a few sites already today and all but one had one or more issues

**Comment by mackecm2** [comment]
I've just upgraded our store to 6.1.5, but I don't see this new "inmdexes" column in my database maintenance screen. Does it need to be switched on somewhere?

We are suffering from painfully slow response times in the admin panels. The store itself is fine, it just the admin screens.

![db maintenance](https://cloud.githubusercontent.com/assets/7928551/23995866/592712dc-0a43-11e7-81db-7b216698f620.png)

**Comment by havenswift-hosting** [comment]
@mackecm2 these are not problems with this tool

1) You have incorrectly done the upgrade and you have multiple admin directories including /admin and /admin_XXXXXX and teh same applies to the admin.php so you are still running the old admin files hence no new feature !

2) The slow admin is due to the very poor way that memcached caching is working within CubeCart admin which is due to https://github.com/cubecart/v6/issues/1536  That issue is general to all caching methods as it means that cache isnt used very effectively at all but seems to very badly affect memcached.  I have switched your store to use REDIS instead which seems much better for the admin side of things

**Comment by mackecm2** [comment]
Thanks for doing the switch to REDIS - I can see the improvement in response times straight away.

You say I have upgraded incorrectly; I have always used the supplied upgrade script and just clicked on the buttons when asked to do so.

I noticed that there was still a /admin folder, but the only file in there is a .htaccess that throws a 404, so I'd appreciate a bit more info on what you think is wrong with the upgrade.

**Comment by Dirty-Butter** [comment]
I wouldn't presume to tell you all that may or may not need doing to get your install setup properly, but I can tell you that you need to delete that admin folder that only has the .htaccess file in it.

**Comment by mackecm2** [comment]
Well I've deleted the old admin folder but I still don't see the new "indexes" column.

**Comment by abrookbanks** [comment]
There is no column. It will just show warnings if there are any. It won't show warnings if the code is not actually at the latest version. Please do a manual upgrade if possible or if you think you are at the latest version.. download 6.1.5 delete the setup folder and upload all remaining files.

**Comment by mackecm2** [comment]
I downloaded the 6.1.5 zip folder from the CC web site and compared it to my current folders using  WinMerge.

Discounting classes\gui.class.php which I have customised to show images agianst popular products, the files that were different were as follows:
\admin\skins\default\js\plugins\jquery.filetree.min.js
\admin\sources\*  (all files)
\admin\index.php

... so I have uploaded all of these from the 6.1.5 zip folder, into the renamed admin_XXX folder on my host.

So I figure everything is at 6.1.5 for the moment. When the next release comes around, I'll do a manual upgrade if I have time. Any idea why the screen driven update didn't work properly? 

There are no warning messages on my Database Maintenance Screen so I'll leave that as is for the moment.

**Comment by abrookbanks** [comment]
Sounds like its fine as it is. I think mainly people who have upgraded from v3 or v4 come across problems.

**Comment by mackecm2** [comment]
Well that would certainly include us - we've been running since the days of V3.

**Comment by Dirty-Butter** [comment]
I do all upgrades manually, so I copy/paste the queries from the latest sql file in setup/db/upgrade into phpMyAdmin SQL tab and run the queries from there. If the query has already been run it does evidently make duplicates. But the test in Maintenance will find any duplicates, and they are easy to delete.

**Comment by havenswift-hosting** [comment]
@mackecm2 if you have any concerns, then as you are hosted with us, please feel free to log a support ticket

**Comment by mackecm2** [comment]
I just checked the last entry in setup/db/upgrade/6.1.5.sql, which is adding the index (`time`) to the CubeCart_admin_log table. My database has that index so it looks as though the sql has been run successfully. Also there are no orange lines or triangles on my database table list, so I think I'm okay.
