### ISSUE TITLE
Cart maintained when switching between customers as admin

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1349]
If you use the "Login as customer" functionality as admin and add a product to the cart.  Then close the browser tab, select a different customer and login as them, the cart contents are retained.

Suggest when clicking on "Login as customer" that the cart is emptied

**Comment by bhsmither** [comment]
Very initial analysis suggests that the 'customer_id' of the target customer is not getting saved into CubeCart's internal SESSION array (as seen in the debug section). The current session, as recorded in the CubeCart_sessions table does get updated.

More analysis on the consequences of the database table versus the SESSION array.

**Comment by Noodleyman** [comment]
It's probably related to https://github.com/cubecart/v6/issues/532

**Comment by bhsmither** [comment]
**FYI:** I am working on a different solution as I can envision a use case where the admin may want to be visiting the storefront as himself, and also as Customer-A and also as Customer-B -- all at the same time.

I am examining having the Session class maintain separate session_ids.

**Comment by abrookbanks** [comment]
> I am examining having the Session class maintain separate session_ids.

That makes some sense.
