### ISSUE TITLE
Country List enhancement to prevent error log entries

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1351]
module.class.php

FIND:
if (($countries = $GLOBALS['db']->select('CubeCart_geo_country', array('numcode', 'name'), false, array('name' => 'ASC'))) !== false) {

AFTER ADD:
$enabled_countries = array();
$disabled_countries = array();

This creates the empty arrays, and will prevent modules from throwing an error to the error log (server, not cubecart) about them not existing when referenced later in the function.

**Comment by abrookbanks** [comment]
Thanks.
