### ISSUE TITLE
Session->get/set/has/isEmpty()

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1356]
Regarding #1343 and #1334, please be sure to analyze similar functions in the Session class.

**Comment by abrookbanks** [comment]
Maybe I am a bit code blind today but the session class sets everything into PHP sessions which will handle objects nicely (AFAIK).

Scanning those functions look good to me. I can't think of a real world example that would be problematic.  Closing for now but happy to reinvestigate.
