### ISSUE TITLE
Issues upgrading sites

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1357]
If you upgrade from 6.0.X to 6.1.0 it renames the admin directory and admin.php files as expected.  If you then later upgrade to 6.1.1, it renames them again AND also seems to leave the uploaded admin directory and in my case it left the setup directory as well.

I think consideration should also be given to keeping old copies of the global.inc.php file - I believe this should be deleted and not renamed for security reasons.  Many sites have multiple copies of this all with permissions not at 444.

**Comment by abrookbanks** [comment]
Must be a bug because its codes to only rename if it's not default..

**Comment by abrookbanks** [comment]
File permissions were set to 0444 before final write out of global file for admin file and folder. Now it has been moved to after which fixes this.
