### ISSUE TITLE
Feature Request: Shipping Group Name should be a setting

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1362]
Currently shipping groups are displayed based on the name of the shipping module directory.  This needs to be overhauled to allow it to optionally be a user defined name within the shipping modules. 

This would allow it to respect the language system and change accordingly.

In an idealy world, CubeCart should check for the override name, if it exists use that, otherwise use it's current method of the folder name with underscores becoming spaces.

**Comment by abrookbanks** [comment]
Nice idea!

**Comment by abrookbanks** [comment]
Done. Shipping modules will need updating to take advantage of this functionality.

**Comment by Noodleyman** [comment]
@abrookbanks , I know this has been available for quite a while, however I keep finding people request this feature. the only option is to add it to the existing shipping method, however that gets lost when the module is updated. Can this setting be added to the existing shipping modules supplied by CubeCart to prevent this? seems odd having the functionality there but not being used

**Comment by harris-organic** [comment]
@abrookbanks , the request was for an optional "user defined name within the shipping modules" I am confused as to how to change the name of "all_in_one_shipping" or "All in One Shipping" within the current module 1.0.16. Could you explain how to do this, please?

**Comment by bhsmither** [comment]
Please see:
https://forums.cubecart.com/topic/53130-all-in-one-shipping-module-gets-a-custom-name/

This conversation may need to be updated for CC629.

But I see that you are already participating in that conversation.

**Comment by harris-organic** [comment]
Thanks, Brian, you are correct, the conversation requires updating for CC629. I have edited the three files with your code from https://forums.cubecart.com/topic/53130-all-in-one-shipping-module-gets-a-custom-name/ with no luck. ie the code made no difference to the shipping name on the order form.

**Comment by bhsmither** [comment]
Taking this to the forums.

**Comment by harris-organic** [comment]
Thanks, All good now.
