### ISSUE TITLE
GC Page Coding

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1366]
(At least in Foundation), There exists the possibility that the choice of delivery will be only one choice.

Suggest that if such is the case, switch out the selector to a statement saying the GC will be delivered as `[the method chosen by the admin]`.

Which brings up:
https://forums.cubecart.com/topic/51931-physical-or-digital-gift-cards/

Has there been any issues regarding sending an email if the delivery method chosen was physical?

And, of course, when choosing physical, the only delivery address available is the purchaser's.

**Comment by abrookbanks** [comment]
From what I can see the email is always sent anyway.. requires testing..
