### ISSUE TITLE
Use of Function is Misunderstood

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1371]
The use of the PHP function `ctype_digit()` is being used ignorant of a peculiarity about it.

See: http://us1.php.net/manual/en/function.ctype-digit.php
and pay particular attention to the Notes.

Specifically:
If an integer between -128 and 255 inclusive is provided, it is interpreted as the ASCII value of a single character.

In the CubeCart functions `getCountryFormat()` and `getStateFormat()`, the use of PHP's `ctype_digit()` is being given an integer argument. It seems some values (208 for Denmark was tested and trued the expression, but 56 for Belgium did not true the expression) cause these CubeCart functions to return the input.

Suggest type casting to string:
```
function getCountryFormat($input, $match = 'numcode', $fetch = 'name') {
  if(($match == 'id' || $match == 'numcode') && !ctype_digit((string)$input)) return $input;
```
```
function getStateFormat($input, $match = 'id', $fetch = 'name') {
  if($match == 'id' && !ctype_digit((string)$input)) return $input;
```
And anywhere else `ctype_digit()` is used.

**Comment by abrookbanks** [comment]
Thanks.
