### ISSUE TITLE
email_definitions.xml typos

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1372]
We are **please** to  be sending you this gift card which you can use towards the purchase of any item(s) on our website.

To **reedeem** this gift card please enter the "Claim Code" above into the text field labeled "Promotional code or gift card" during checkout.

**Comment by abrookbanks** [comment]
Thanks Rosemary.

**Comment by briansandall** [comment]
@abrookbanks You forgot to fix 'We are please to...' on line 381; it should be 'We are pleased to...' ;)

**Comment by abrookbanks** [comment]
The "please" typo was fixed in a previous commit so it doesn't need
changing again.

**Comment by abrookbanks** [comment]
My mistake.. it was still in the plain text version.
