### ISSUE TITLE
Improve the manufacturer grid layout in advanced search

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1374]
When a manufacturer name is too long for the allotted space, it moves the entire name down to the next line below the check box. I think this could look better, but I'm not quite sure in what manner.

For multi-word names, it would be easy to break them up so at least part of it is next to the check box; for really long names, hyphenation could be an option.

Example of issue:
![cc_1374](https://cloud.githubusercontent.com/assets/14335170/20775913/3b69e320-b712-11e6-8f2e-bcf2dcba0f53.jpg)

**Comment by bhsmither** [comment]
This is a skin display issue, so it is up to the admin (store skin designer) to play with it until it pleases the store owner.

But Foundation does need to get sorted. The block grid may not be the best layout utility for an indeterminate length of text.

I like how this looks. From:
```
   <div class="row">
      <div class="small-12 columns">
         <ul class="small-block-grid-5">
            {foreach from=$MANUFACTURERS item=manufacturer}
            <li><input type="checkbox" value="{$manufacturer.id}" id="manufacturer_{$manufacturer.id}" name="search[manufacturer][]" {$manufacturer.selected}><label for="manufacturer_{$manufacturer.id}">{$manufacturer.name}</label></li>
            {/foreach}
         </ul>
      </div>
   </div>
```
To:
```
   <div class="row">
      <div class="small-8 columns">
{* Don't use this layout utility
         <ul class="small-block-grid-5">
            {foreach from=$MANUFACTURERS item=manufacturer}
            <li><input type="checkbox" value="{$manufacturer.id}" id="manufacturer_{$manufacturer.id}" name="search[manufacturer][]" {$manufacturer.selected}><label for="manufacturer_{$manufacturer.id}">{$manufacturer.name}</label></li>
            {/foreach}
         </ul>
// Use a Table *}
<table style="width:100%;">
   <tbody>
{foreach from=$MANUFACTURERS item=manufacturer}
      <tr>
         <td>
            <input style="margin:0.5rem 0;" type="checkbox" value="{$manufacturer.id}" id="manufacturer_{$manufacturer.id}" name="search[manufacturer][]" {$manufacturer.selected}><label for="manufacturer_{$manufacturer.id}">{$manufacturer.name}</label>
         </td>
      </tr>
{/foreach}
   </tbody>
</table>
      </div>
      <div class="small-4 columns">{* Maybe restructure columns on entire area? *}
      </div>
   </div>
```

**Comment by Dirty-Butter** [comment]
I can't even use the checkbox layout, as I have over 400 manufacturers. Bsmither helped me change it to a drop down layout.

**Comment by bhsmither** [comment]
How is that working out? A 400-item drop-down list must be very tall - taller than your screen height.

**Comment by briansandall** [comment]
Exactly, I brought this up because it is a display issue with the Foundation skin. The table looks nice, as does simply displaying one or even up to three per line (depending on the longest manufacturer name) by changing the <ul> class - that's what I'm doing for my own store and it works fine for that, but I'd like to see a more general solution.

Furthermore, for stores with many manufacturers (e.g. Dirty-Butter's), such a huge list, table or otherwise, would be unwieldy to scroll through for customers. Whatever solution we come up with should be able to accommodate such cases. I don't have any great ideas for solving this, but I figured I may as well mention the issue in case someone else does.

**Comment by briansandall** [comment]
Specifically I changed `<ul class="small-block-grid-5">` to `<ul class="small-block-grid-1 medium-block-grid-3">` - that way smaller display widths still look decent.

**Comment by bhsmither** [comment]
Maybe an ajax-powered suggestive list containing only those names that have an entered minimum three character sequence.

Such as entering 'ell' and getting a response containing:
Kellog, Well Spring, Snakwell, Bang Bells, etc.

The choice to 1)list everything, or 2)to make a suggestive response list, would be a skin coding decision, but CubeCart would have an ajax API available to deliver it.

The list is coded to allow for multiple selections, so it may use the jquery Chosen plugin.

**Comment by briansandall** [comment]
I like the sound of that.

**Comment by Dirty-Butter** [comment]
The drop down menu Bsmither coded for me works fine on our plushcatalog. The drop down box is a reasonable size, the list jumps to the first letter of the manufacturer (if the customer thinks to do that), and it works on a small screen.

**Comment by briansandall** [comment]
@Dirty-Butter How well does that work for selecting multiple manufacturers? Would you say that is a common use case for your store?

For stores with many manufacturers where searching among multiple manufacturers is relatively common (e.g. to compare similar product offerings), the ideal solution would provide the following:

1. Easily select multiple manufacturers
2. Easily see which manufacturers have already been selected
3. Easily remove a previously selected manufacturer
4. Do the above without taking up huge amounts of screen real estate

The dropdown menu could meet most of those criteria except for 2 and, as a side effect of that, 3 if the entry the user wants to remove is no longer in the visible window. Furthermore, a single mis-click could wipe out every selection made up to that point - with enough manufacturers, such a mis-click makes meeting criteria 1 quite difficult.

The AJAX powered selector meets all of those criteria, but wouldn't really be worth using as compared to a dropdown or checkboxes when there are only a handful of manufacturers to choose from.

**Comment by Dirty-Butter** [comment]
It's hard to be sure, but I don't think our customers would be trying to search for more than one manufacturer at a time. Many of our customers are very much search babies - I know that based on the terms they try to use to search with. For research's sake, it would be nice to be able to tell if a User Online is doing the search from the box or from the Advanced.

**Comment by bhsmither** [comment]
_"The drop-down box is a reasonable size."_

Of course!
http://stackoverflow.com/questions/570642/height-of-an-html-select-box-dropdown/

**Comment by Dirty-Butter** [comment]
"Maybe an ajax-powered suggestive list containing only those names that have an entered minimum three character sequence."
This would cause us problems, as one our major companies is TY.

**Comment by briansandall** [comment]
I'm not super familiar with jQuery, but I know from coding my own AJAX type-ahead dropdown that it can be done where even a single letter will trigger the call, but for performance reasons usually at least 2 letters are required.

It would also depend on the implementation - mine only checks for matches at the beginning of the string, so 'T' would bring up 'TY', but 'Y' would not, whereas it sounds like the jQuery plugin will try to match any portion of the string and would bring up ALL manufacturers with 'Y' in their name - that makes a huge difference in how many letters you may want to require.

**Comment by bhsmither** [comment]
I'm only mentioning the jQuery plugin Chosen. You can see it in action in the All-in-One Shipping module, Add new Shipping Zone, One or more countries selected.

It would be the ajax responder in CubeCart to determine the input requirements and how the search is performed.

**Comment by bhsmither** [comment]
You now have a choice of three ways of displaying the list of manufacturers.

The Select method shows the list like any other drop-down. But, the Chosen Select will allow the visitor to enter a sequence of letters, and the list will shrink to have only those options that contains that sequence of letters.

(I don't have a long list of manufacturers, so I do not know if Chosen limits the number of options in a scrolled drop-down.)

The following is a series of edits.

In the Foundation template `content.search.php`, find near line 44:
```
         <ul class="small-block-grid-5">
            {foreach from=$MANUFACTURERS item=manufacturer}
            <li><input type="checkbox" value="{$manufacturer.id}" id="manufacturer_{$manufacturer.id}" name="search[manufacturer][]" {$manufacturer.selected}><label for="manufacturer_{$manufacturer.id}">{$manufacturer.name}</label></li>
            {/foreach}
         </ul>
```
Replace with:
```
{* Uncomment the following include to show a grid of checkboxes. Manufacturers names should be very short. *}
{* include file='templates/element.search.manufacturers.checkbox.grid.php' *}

{* Uncomment the following include to show a table of checkboxes. Manufacturers names can be very long. *}
{* include file='templates/element.search.manufacturers.checkbox.table.php' *}

{* Uncomment the following include to show a drop-down selector. Manufacturers names can be long and numerous. *}
{include file='templates/element.search.manufacturers.select.chosen.php'}
```
Create this new file in the templates folder:
`element.search.manufacturers.checkbox.grid.php`
```
{* Adjust the grid number if manufacturer names are long. *}
         <ul class="small-block-grid-1 medium-block-grid-3 large-block-grid-5">
{foreach from=$MANUFACTURERS item=manufacturer}
            <li><input type="checkbox" value="{$manufacturer.id}" id="manufacturer_{$manufacturer.id}" name="search[manufacturer][]" {$manufacturer.selected}><label for="manufacturer_{$manufacturer.id}">{$manufacturer.name}</label></li>
{/foreach}
         </ul>
```
Create this new file in the templates folder:
`element.search.manufacturers.checkbox.table.php`
```
{* Good for long manufacturers names. *}
         <table style="width:100%;">
            <tbody>
{foreach from=$MANUFACTURERS item=manufacturer}
               <tr>
                  <td><input style="margin:0.25rem 0;" type="checkbox" value="{$manufacturer.id}" id="manufacturer_{$manufacturer.id}" name="search[manufacturer][]" {$manufacturer.selected}><label for="manufacturer_{$manufacturer.id}">{$manufacturer.name}</label></td>
               </tr>
{/foreach}
            </tbody>
         </table>
```
Create this new file in the templates folder:
`element.search.manufacturers.select.chosen.php`
```
{* Good for a really high number of manufacturers names. *}
         <style scoped>{* Need to override Chosen's hard rule for text input. May be solved in a later version of Chosen. *}
          {literal}.chosen-container-multi .chosen-choices li.search-field input[type="text"]{height:auto;}{/literal}
         </style>
         <select id="search_manufacturers" data-placeholder="{$LANG.common.please_select}" multiple="multiple" class="chzn-select" style="width:100%;" name="search[manufacturer][]">
{foreach from=$MANUFACTURERS item=manufacturer}
            <option {$manufacturer.selected} value="{$manufacturer.id}">{$manufacturer.name}</option>
{/foreach}
         </select>
```
Copy the following files:
`/admin/skins/default/js/plugins/jquery.chosen.min.js`
to:
`/skins/foundation/js/vendor/`

Copy the following files:
`/admin/skins/default/js/styles/jquery.chosen.min.css`
`/admin/skins/default/js/styles/chosen-sprite.png`
`/admin/skins/default/js/styles/chosen-sprite@2x.png`
to:
`/skins/foundation/css/`

Edit the Foundation template `main.php` as follows:
```
Find near line 28:
      <link href="{$STORE_URL}/skins/{$SKIN_FOLDER}/css/jquery.bxslider.css" rel="stylesheet">
Add After:
      <link href="{$STORE_URL}/skins/{$SKIN_FOLDER}/css/jquery.chosen.min.css" rel="stylesheet">

Find near line 127:
            <script src="{$STORE_URL}/skins/{$SKIN_FOLDER}/js/vendor/jquery.bxslider.min.js" type="text/javascript"></script>
Add After:
            <script src="{$STORE_URL}/skins/{$SKIN_FOLDER}/js/vendor/jquery.chosen.min.js" type="text/javascript"></script>

Find near line 136:
               $('.bxslider').bxSlider({auto:true,captions:true});
Add After:
               $('.chzn-select').chosen({width:"100%",search_contains:true});
```

**Comment by havenswift-hosting** [comment]
Liking this a lot !

**Comment by abrookbanks** [comment]
> I like the sound of that.

I don't LOL.

**Comment by abrookbanks** [comment]
This is fantastic... Thanks so much I have integrated this as it works flawlessly.

**Comment by Dirty-Butter** [comment]
Should be like this, so uncommenting already has the brackets.
`````
  {* {include file='templates/element.search.manufacturers.checkbox.grid.php'} *}
`````

**Comment by Dirty-Butter** [comment]
What does this mean?
"{* Need to override Chosen's hard rule for text input. May be solved in a later version of Chosen. *}"
I have to use the Select option, so what will this NOT do at this time?

**Comment by bhsmither** [comment]
Chosen's CSS rules set a height at 15px for `input[type='text']`. Of course, I do not know why. But 15px is rather squat.

Foundation has a CSS rule for `input[type='text']` at some value of `rem`. But because the Chosen CSS comes in after the Foundation CSS, Chosen has a higher priority.

Thus, we need to override Chosen's height value with a value set in the actual file.
