### ISSUE TITLE
Rating is not a function

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1375]
Unknown how long this has been going on, but Firefox reports:
`JavaScript Error: TypeError: $(...).rating is not a function`
This happens on the Dashboard and everywhere else in admin.

I see that plugins.php is loaded first, then admin.js, and the JavaScript Debug Console actually makes no mention of this error.

Probably not a CubeCart issue, but it would be nice if someone more practiced at debugging JavaScript might find why Firefox is making this complaint.

**Comment by Dirty-Butter** [comment]
What are you doing on FireFox to see this report?

**Comment by bhsmither** [comment]
There is a "Web Developer" toolbar:
http://chrispederick.com/work/web-developer/

There are three indicators that show up when the toolbar is installed, but customizing the toolbar group allows one to move these indicators to a different toolbar or off any toolbar into the "object pool".
1. Clicking this opens Firefox's View Page Info
2/3. Clicking this opens Firefox's Developer Tools, Console panel. 2 indicates CSS issues, 3 indicates javascript issues.

**Comment by bhsmither** [comment]
Well, something strange is going on. I moved the indicators to a different toolbar and they are now reporting other things.

So, cancel this issue -- seems it is highly unlikely to be something a code change to CubeCart can fix.

**Comment by abrookbanks** [comment]
Thanks Brian.
