### ISSUE TITLE
Add "Continue Shopping" to cart at all times

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1381]
See https://forums.cubecart.com/topic/51807-continue-shopping-button 

Continue Shopping should appear on basket page all the time not just when a basket has been emptied

**Comment by Dirty-Butter** [comment]
I agree - not everyone knows to click on the logo of a site, or home icon if there is one, to return to the homepage.

**Comment by abrookbanks** [comment]
This is a debatable one.. if you checking on high profile sites like amazon they intentionally do not show "continue shopping" links as they want you completing the order. See attached screenshot. You could argue that an obvious continue shopping button lowers conversion.

![screen shot 2016-12-06 at 11 50 17](https://cloud.githubusercontent.com/assets/4520803/20924618/5e587120-bbaa-11e6-981b-c375320f5a70.png)

**Comment by abrookbanks** [comment]
I'm going to close this. The merchant can add this themselves if they want.

**Comment by havenswift-hosting** [comment]
I see your point although shopping on Amazon is quite different to using CubeCart and you could argue that it should be displayed and then merchants can remove it if they want.  However, I am going to add this to our new Skin Configuration Plugin so it is an option users can toggle on/off without changing core skin files
