### ISSUE TITLE
Specificity Too Tight?

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1382]
In 2.cubcart.js, near line 38, the target is: `svg.icon-submit`. In versions prior to CC610, the target was `i.icon-submit`.

The change corresponds to the icon set and tag syntax used.

I question the need to be so specific with the selector.

Suggest not using the tag in the selector. That is, simply `$('.icon-submit')`.

Or, if needing to be specific, choose its parent - the `<p>` or `<div>` tag to assign the `icon-submit` class.

Other considerations aside, it won't matter to force the browser to reload this page resource.

**Comment by abrookbanks** [comment]
Totally agree its OTT.
