### ISSUE TITLE
Images previously FTP loaded now not appearing in File Manager

### ISSUE THREAD

**Issue by broadland** [cubecart/v6#1388]
Please accept apologies if covered elsewhere, newbie here! Have looked thoroughly but cannot see anything else regarding this.

I FTP loaded 3200+ images to "Source" folder and all was OK. One of my users loaded a handful of images within CubeCart individually. All was OK.

I believe the "Update File List" tab was then selected and now all that remains visible in File Manager is the few that were subsequently loaded within CubeCart and those that were FTP loaded are no longer visible, but do show up without issue with the Products they are associated to.

It would be most useful to regain access to those that were FTP loaded previously within File Manager so that they can be used as images for Categories.

Kindly advise.

**Comment by abrookbanks** [comment]
I'm sorry you have problems with this. If you want to open a tech support ticket we can take a look at this for you.  I haven't been able to reproduce this problem on my development store.

**Comment by broadland** [comment]
Thanks for looking at my post Al.

I do not have a support package in place and therefore assume it’s not something I am entitled to support on. As I could not understand what my user might have done to have caused this to happen I guess it’s something we must live with and hope as mysteriously as the images disappeared from File Manager that they come back!

Regards and appreciate your time,

Darren Rogers
Broadland Computers

**Comment by abrookbanks** [comment]
Maybe refresh the page a few times and it may build the index. I'd be happy to investigate if you can send a support ticket. I don't think this is a bug. I've actually worked on the file manager a lot this week.

**Comment by broadland** [comment]
Hi Al. I don't have a CubeCart support package, so I don't think I can open a ticket can I? If I have gotten this wrong and I can do that, which page do I go to please? Again, thank you for your time.
