### ISSUE TITLE
Options Matrix

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#139]
In the CubeCart_option_matrix table, I see a column for 'image' and 'status' which shows hope and promise about neat things to come.

Feature Request:
When creating the Options Matrix table entries (admin, Product, Options tab), please add the calculated sum total of price differentials and weights as entered in the Product Options table to the record, and/or allow for manual entry.

For example:
**Size:** Large +2.00, 1.00
**Material:** Gold: +10.00, 5.00
Large|Gold: +12.00 (or manually entered +20.00), 6.00 (or manually entered 20.00)

**Comment by abrookbanks** [comment]
Relates to #75

**Comment by bhsmither** [comment]
This does relate (adjacently) to #75. Here is the reasoning for the request:

I am modifying the catalogue class and the cart class, and the content.product.php template, to:
Catalogue: gather and assign a recordset straight from CubeCart_option_matrix
Cart: accept as $_POST['productOptions'] the $option_identifier_string
Product: display the recordset as a linear stack of radio buttons, disabled as appropriate.

It is in the stack of radio buttons that more information is necessary.

**Comment by abrookbanks** [comment]
I have done this for cost. I'm not sure weight is so vital. 
https://dl.dropboxusercontent.com/u/894044/2015-01-29%2010.20.42.mov
