### ISSUE TITLE
Review URL in category view - issues

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1391]
When using the $product.review_info data in the category view, the URL has issues.

1) It does not use an SEO URL

2) The URL is invalid. 

in catalogue.class.php FIND:
`				$link = currentPage(array('_a', 'cat_id'), null, false).'_a=product&product_id='.$product['product_id'].'#reviews';`

REPLACE WITH:
`$link = $GLOBALS['seo']->buildURL('prod', $product['product_id'], '&') . '#reviews';`

**Comment by abrookbanks** [comment]
Thanking you.

**Comment by bhsmither** [comment]
There is a comment on the code fix, but I'm sure you will notice this.
