### ISSUE TITLE
Negative Product Options should be capped

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1392]
Stumbled across this today whilst experimenting with some other features. If you set a product option to be negative, and it takes the product price below 0, the totals become negative.

For example. product price of £1000. Product option price of -£2000

If added to the cart, it shows the total as -£1000, so in the event of misconfiguration people can use it to get discounts off their order total. 

If the product price is going to be negative, it should be adjusted to be 0.

**Comment by abrookbanks** [comment]
Strictly speaking CubeCart is correct. Ha. Could there be any scenario where a client would want a negative price?

**Comment by Noodleyman** [comment]
Yes there can, which is why I stumbled across it ;)

A negative price, for a shop isn't valid. because essentially you would be paying the customer to take goods from you, thus a price of 0 is valid as the floor for the price.

**Comment by abrookbanks** [comment]
What if you had a really annoying wife you wanted to put online?

**Comment by bhsmither** [comment]
"Take my wife, please!"

**Comment by briansandall** [comment]
So in other words, it's not a bug, it's a feature?

I can see arguments for both cases: on the one hand, most stores aren't going to be purchasing items from their customers; on the other, what if you were trying to run a recycling business where you did indeed purchase rubbish from people?

Whether an ecommerce platform is suitable for such an endeavor is certainly debatable, but if that's the intent, then okay.

**Comment by Noodleyman** [comment]
you make a valid point, perhaps an option in settings to toggle on/off the ability to allow the cart total to become negative?

I've a customer at the moment who is heavily using product options and price adjustments across several thousand products. They have a specific option which when added to a product enables the selection of a free sample.  The free sample option has a negative price adjustment to either make the product free, or charge a minor fee.

for example, if the product price is £100, the option price may be -£99 or -£100 to charge either £1 or nothing for the sample. I have some deep concerns that due to human error they will not keep these price adjustments maintained in line with product prices, potentially allowing customers to find items that are misonfigured and reduce their overall order price.

So, for my customer, this behaviour is currently very dangerous and has the potential to cost them thousands. I can certainly modify their store to get this behaviour, but I had hoped we could make it part of the core cart engine to aboid unnessary customisation. :)

**Comment by briansandall** [comment]
Personally, I totally agree that price should not be allowed to be negative. I mean sure, it's technically correct given the options, but as far as I am aware CubeCart doesn't support sending out payments, only receiving them, so how would the person check out? Is it possible to check out with a negative balance?
