### ISSUE TITLE
Restrict to Selected GC Delivery Method

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1396]
In `Cart->add()`, near line 234, there is:
```
$this->basket['contents'][$hash] = array(
  'id'   => $product_id,
  'quantity'  => $quantity,
  'digital'  => ($optionsArray['method'] == 'e') ? true : false,
  'certificate' => array(
    'value'   => $optionsArray['value'],
    'name'   => $optionsArray['name'],
    'email'   => $optionsArray['email'],
    'message'  => $optionsArray['message'],
  ),
);
```
This fails to enter into what will be the 'custom' blob the chosen delivery method. It is true that 'digital' is set to true and gets databased in the 'digital' column of CubeCart_order_inventory, but more can be done.

Suggest:
```
$this->basket['contents'][$hash] = array(
  'id'   => $product_id,
  'quantity'  => $quantity,
  'digital'  => ($optionsArray['method'] == 'e') ? true : false,
  'certificate' => array( // CubeCart_order_inventory, 'custom' column, serialized
    'value'   => $optionsArray['value'],
    'name'   => $optionsArray['name'],
    'email'   => $optionsArray['email'],
    'message'  => $optionsArray['message'],
    'method' => $optionsArray['method'], // 'e' or 'm'
  ),
);
```
Then, knowing that `Order->_sendCoupon()` has this delivery method within `$data`, we can choose to email the `cart.gift_certificate` template, or prepare for something else - such as:
* send a different email to a card fabrication house
* prepare a file for printing

Also, have a hook: `class.order.send.physical.coupon`.

Alternately:

In `Order->orderStatus()`, `case:ORDER_COMPLETE`, there is:
```
// Send Gift Certificate
if (!empty($item['custom']) && !empty($item['coupon_id'])) {
  $this->_sendCoupon($item['coupon_id'], unserialize($item['custom']));
}
```
If wanting to only email if the GC order inventory item is `digital = 1`, suggest:
```
if (!empty($item['custom']) && !empty($item['coupon_id']) && $item['digital']) {
  $this->_sendCoupon($item['coupon_id'], unserialize($item['custom']));
}
```

See: #1366

**Comment by abrookbanks** [comment]
Email or Postal Gift Card
![screen shot 2017-02-03 at 15 52 31](https://cloud.githubusercontent.com/assets/4520803/22597753/d3eece78-ea28-11e6-9ae6-a34acc62ee91.png)
