### ISSUE TITLE
HOOK_TAB_CONTENT to be Finished Implementing

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1399]
The implementation of HOOK_TAB_CONTENT is not complete, as compared to PLUGIN_TABS. (Maybe PLUGIN_TABS isn't complete as well - such as settings.index.inc.php - I haven't checked all of it.)

Seeing that
```
{include file='templates/element.hook_form_content.php}
```
is within the `{$DISPLAY_FORM}` parts of the view (skin templates), one must conclude it, too, is meant only for adding content with the similar intent of PLUGIN_TABS.

The difference being that _any hook_ has access to `$GLOBALS['hook_tab_content']`.

Suggest assuring all the controllers (whatever.index.**inc**.php) have:
```
$GLOBALS['smarty']->assign('HOOK_TAB_CONTENT', $GLOBALS['hook_tab_content']);
```

However, that does not cover the `{$DISPLAY_LIST}` parts of the view.

Suggest also having
```
{include file='templates/element.hook_form_content.php'}
```
near the end of the `{$DISPLAY_LIST}` part of the view.

**Comment by abrookbanks** [comment]
Brian I'm going to close this for now. I'd like develops to request any extra implementations which can be added on an as and when basis.
