### ISSUE TITLE
Disentangle Literals

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1400]
A Suggestion...

In /admin/sources/orders.index.inc.php, near line 708:
```
$order['icon']   = ($order['type']==2 || empty($order['customer_id'])) ? 'user_ghost' : 'user_registered';
```
the literals `user_ghost` and `user_registered` appear to be used as glue for later specified CSS class names being specific to the skin being used.

Suggest passing only already existing indexes from the controller to the view. Therefore:
```
$order['icon']   = ($order['type']==2 || empty($order['customer_id'])) ? 'user_ghost' : 'user_registered';
```
can be ignored (kept for legacy), then adding:
```
$order['type'] = (empty($order['customer_id'])) ? 2 : $order['type'];
$order['cust_type'] = array(
  "1" => 'title_key_registered',
  "2" => 'title_key_unregistered',
);
```
 and in the template, from:
```
{if $order.icon=='user_registered'}
<i class="fa fa-user registered" title="{$LANG.customer.title_key_registered}"></i>
{else}
<i class="fa fa-user unregistered" title="{$LANG.customer.title_key_unregistered}"></i>
{/if}
```
to:
```
{append "cust_type" "registered" index="1"}
{append "cust_type" "unregistered" index="2"}
<i class="fa fa-user {$cust_type[$order.type]}" title="{$LANG.customer[$order.cust_type[$order.type]]}"></i>
```
In the case where the skin's CSS doesn't want to use 'registered' and 'unregistered' as class names, this keeps the identity of the type of user without any tanglement with the controller by making sure those class names are strictly within the scope of the skin.

It might be pointed out that 'registered' is not the same as the icon value 'user_registered'. Thus, there is the disconnect.

I reply, why invent this glue? The ID values already exist. And this will easily track any enhancements when more customer types are developed by way of plugins.

That is, aside from the `{assign/append}` statements. I've experimented with various approaches, but so far, I have no solution to dynamically generating this list.

Unless the class names are changed:
```
.cust_type_1 { color: green; }
.cust_type_2 { color: red; }
```
Then, hooks can load HEAD_CSS with additional rules as appropriate.

**Comment by abrookbanks** [comment]
I like this. Thanks! :)
