### ISSUE TITLE
Featured (Random) product, image enhancement

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1401]
It would be nice for the featured product array to contain multiple sizes of images, currently it defaults to "small" which is the default value of the getProductImage() function.

```
			$image = $this->getProductImage($random_product[0]['product_id']);
			$product['image'] = $image;

```
It would be nice if the array included as standard, small, medium and large giving choices to the designer which image size to use in the store skin

```

			$product['image'] = $this->getProductImage($random_product[0]['product_id']);
			$product['image_medium'] = $this->getProductImage($random_product[0]['product_id'], 'medium');
			$product['image_large'] = $this->getProductImage($random_product[0]['product_id'], 'large');
```

**Comment by bhsmither** [comment]
And for `GUI->_displaySaleItems()`.

I know there is CubeCart code somewhere that will serve as getAllImages() according to the skin's config.xml directives.

**Comment by bhsmither** [comment]
And for `Catalogue->displayCategory()`.
