### ISSUE TITLE
[To Check] Validate order number on view basket/checkout/gateway

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1403]
If the basket has a value for order number and the order exists in the database with a status > 1 either empty basket and say this order is done or generate a new order number. 

It may do this already but check required.

**Comment by Dirty-Butter** [comment]
I use an extension that creates Sequential order numbers. Do you think whatever this validation turns out to be would effect that plugin code?

**Comment by abrookbanks** [comment]
It's impossible to know with a deep understanding of the exremsion. :)

**Comment by abrookbanks** [comment]
*extension

**Comment by Dirty-Butter** [comment]
I'm including two files with Sequential Order code edits from Chuggyskins from v5 that works with edits in current commit of v6. All edits are commented before and after.
[order.class.txt](https://github.com/cubecart/v6/files/656011/order.class.txt)
[cubecart.class.txt](https://github.com/cubecart/v6/files/656014/cubecart.class.txt)

I think that's the only ones, but it's possible I'll find others.

Feel free to delete the files/comments if they are of no use to you.

**Comment by briansandall** [comment]
@Dirty-Butter You can compress the folder into a single archive using e.g. 7-Zip. That may allow you to send the entire plugin via the forum messaging system. I've never used it to send files, though, so no guarantees.

**Comment by Dirty-Butter** [comment]
Thanks, Brian. I never zip things and I always forget I can. LOL Forum message sent to Al. Hopefully I did it correctly.

**Comment by abrookbanks** [comment]
I've never used 7zip and I'm not sure what software a mac needs to understand it. Whats wrong with tar.gz or standard zip?

**Comment by Dirty-Butter** [comment]
I couldn't find the Compress choice last night - sent you a zipped version. Sorry about that! I also went back to the original instructions for this plugin and found the database table addition:
`````
	CREATE TABLE `{YOURPREFIX}CubeCart_sequential_order_numbers` (

		`id` INT( 30 ) NOT NULL AUTO_INCREMENT PRIMARY KEY ,

		`year` VARCHAR( 255 ) NOT NULL,

		`no_orders` INT( 30 ) NOT NULL

		) ENGINE = MYISAM ;
`````

**Comment by abrookbanks** [comment]
I'm not sure I'll be able to take your 3rd party code into account Rosemary I'm really behind in issues as it is without having to factor extra time in. If I can I will.

**Comment by Dirty-Butter** [comment]
I understand - Chuggyskins site hasn't been updated at all since v5 and the site itself doesn't even load properly any more. I thought you might want to look over the sequential code sometime. I didn't expect you to make this a priority, but in case it was a slam dunk it didn't hurt to ask.

**Comment by bhsmither** [comment]
Just as an educated guess, if the Sequential Order module requires its own dedicated table, then I would think the special order number is a simple added-on data item to the basic Order Summary dataset, to be displayed as required.

The `cart_order_id` is used as a locus for many features and functions, and thus cannot be discarded so that some other key context can be used.

To conclude, I think there are no issues to be concerned about regarding this third-party code.

**Comment by Dirty-Butter** [comment]
Thank you, Brian. I hope you are correct! We'll see......

**Comment by abrookbanks** [comment]
Nothing to see here as order status validation is already in place.
https://github.com/cubecart/v6/blob/master/classes/order.class.php#L570
