### ISSUE TITLE
Use consistent db query syntax when joining tables

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1409]
This issue is merely about a minor inconsistency notable for example in a typical catalogue search query as retrieved from the log, broken up for readability:
```
SELECT I.*, MATCH (I.product_code,I.description,I.name) AGAINST('search' IN BOOLEAN MODE) AS Relevance 
	FROM CubeCart_inventory AS I 
	LEFT JOIN (
		SELECT product_id, MAX(price) as price, MAX(sale_price) as sale_price
			FROM CubeCart_pricing_group 
			WHERE group_id = 0 
			GROUP BY product_id
		) as G ON G.product_id = I.product_id 
	WHERE I.product_id IN (
		SELECT product_id 
			FROM `CubeCart_category_index` as CI 
			INNER JOIN CubeCart_category as C 

			// JOIN clause followed by 'WHERE' instead of 'ON'
			where CI.cat_id = C.cat_id AND C.status = 1

		) 
		AND I.status = 1 AND (MATCH (I.product_code,I.description,I.name) AGAINST('search' IN BOOLEAN MODE)) >= 0.5 
	ORDER BY IF (G.sale_price IS NULL, IF (I.sale_price = 0, I.price, I.sale_price), IF (G.sale_price = 0, G.price, G.sale_price)) ASC 
	LIMIT 12 OFFSET 0
```
While both `WHERE` and `ON` are syntactically correct for a `JOIN` and neither show any difference when using `EXPLAIN` query, the rest of the joins that I have seen in CC use `ON` and suggest that the search queries be updated for consistency.

The above syntax is found in lines 1680, 1682, 1724, 1761 and 1763 in `catalogue.class.php`.

**Comment by abrookbanks** [comment]
Thanks for this. As it currently works well it's bet to leave it alone and concentrate on other things.
