### ISSUE TITLE
May Return Unintended Result

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#141]
In functions.inc.php, `recursive_implode()`, a test is made to make sure the `$pieces` argument is an array. And if it is not?

According to:
http://us1.php.net/manual/en/function.implode.php
When `$ret` is an empty array, a -zls- is returned. When `$ret` is a string, NULL is returned.

When `$ret` is not set, PHP will probably complain about the function missing an argument.

Suggest, if testing `$pieces` to be an array, return the appropriate result for `implode()` having an array to work with. Otherwise, return _false_. Or return `$pieces` as type string.

```
                $ret[] = $r_pieces;
            }
        }
        return implode($glue, $ret);
    }
    return (is_scalar($pieces)) ? (string)$pieces : false;
}
```

**Comment by abrookbanks** [comment]
Thanks Brian. From my testing this is flawless. The function is only used for product options on the basket. All still functions fine with this code change and prevents possible bugs in the future. 

Thanks again.
