### ISSUE TITLE
Search May Double 'Searched For' Log Count

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1421]
When using the Advanced Search, the method `CubeCart->_category()` puts the REQUESTed (from POST) keywords in `$terms`, then UPDATES/INSERTS the` CubeCart_search` database table.

Then the code places the `$terms` in a querystring and has the browser fetch that URL.

The code again puts the REQUESTed (from GET) keywords into `$terms` and the table is UPDATED.

This effectively doubles the logged count of searched terms.

No real issue here, but the count is misleading.

**Comment by bhsmither** [comment]
In CC614, lines 794-795:
```
    httpredir('?'.http_build_query($query, null, '&'));
    $GLOBALS['session']->delete('', 'search');
```
The second line in new.

Recall that `httpredir()` is an exit point of CubeCart. That is, when `httpredir()` is done, exit is called.

Therefore, the new line will never be executed.

**Comment by abrookbanks** [comment]
Thanks Brian. Moving it outside the condition worked.
