### ISSUE TITLE
Commentary to be Updated

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1422]
In `Catalogue->searchCatalogue()`, the DocBlock can be updated to show:

`@param mixed $search_data` : the valid input types are: a multi-dimensional associative array of strings, a string, a numeric string (that gets cast to int if possible), a real number (that gets cast to int), and null.

A few lines down, there is:
`The only guaranteed table alias is I for CubeCart_inventory`

Suggest adding:
`G for CubeCart_pricing_group`
`CI for CubeCart_category_index`
`C for CubeCart_category`

**Comment by abrookbanks** [comment]
Spotted ```G..sale_price``` and changed to ```G.sale_price```

Comments updated.
