### ISSUE TITLE
Bounce to Item Page when Result is One

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1427]
Feature Request:

If, from a "Search Catalogue" (keywords or Sale Items), there is only one item in the results list, offer the admin the the choice to have the customer get bounced directly to that item's description page, or proceed as normal to the View Category page.

**Comment by abrookbanks** [comment]
I think it should do this by default but add a message that only one result was found.

**Comment by abrookbanks** [comment]
![screen shot 2018-02-27 at 17 00 40](https://user-images.githubusercontent.com/4520803/36742513-c5678464-1bdf-11e8-823b-628b5d3db9e5.png)
