### ISSUE TITLE
Product Updated Message When Nothing Changed

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1440]
Bring up a product for editing. Without changing anything, when having Saved, CubeCart reports "Product Successfully Updated".

This destroys all truthfulness as to what actually happened.

The culprit will be found shortly.

**Comment by bhsmither** [comment]
The found culprit is: having clicked Save when editing a product, the `$record['updated']` is assigned a value from `time()`. This happens at line 102 (in CC611). 

It is a given that the database will respond with "Yes, something was different than what was there already, so the record did get updated" response. Therefore, `$updated` gets set to true.

Perhaps **move** `$record['updated']` to line 129. Also, delete line 123:
```
$record['updated'] = $date_added;
```
because it will be taken care of at line 129.

Line 129 (just before `unset($record);`) has:
```
if($updated || $inserted) $GLOBALS['db']->update('CubeCart_inventory', array('updated' => date('Y-m-d H:i:s', time())), array('product_id' => $_POST['product_id']), true, 'all');
```
This updates the record with the *updated time* but only if the database said something got updated (and not the updated time).

**Comment by briansandall** [comment]
I'm not so sure that this isn't working as intended - clicking 'Save' always updates the last date modified as saving is itself an act of updating the entry; that can be handy if you want to bump a product up to the latest product. If you haven't changed anything, you shouldn't click 'Save'. That's at least my assumption of the code's intent - perhaps it is an unintended bug/feature depending on your perspective.

**Comment by bhsmither** [comment]
I see your point of view regarding the Latest Product list.

But I would say that *even not changing anything* about a product, an order, a customer, or a document, that would indicate a physically inconsistent result, even if I choose to click Save, when actually nothing changed. This evident everywhere, such as viewing an order summary or a product review.

_Everywhere?_ Maybe I did something to my installation (Database class), but my criticism above stands.

**Comment by briansandall** [comment]
Yes, I completely agree that one wouldn't necessarily expect the entry to update if nothing changed, and in most cases the date should most definitely be left untouched. For product date last modified, I could personally go either way.

However, if we change this behavior to which some store admins may have become accustomed, we should offer the ability to easily update the last date modified, e.g. by exposing the last date modified in the product page or by having a checkbox for 'update last date modified even if nothing else has changed'.

The latter could be useful in reverse - there have been many times when I am editing a product to make a minor correction but would much prefer the date modified to remain unchanged (despite being technically correct to do so) for the sole reason that I don't wish to bump the product up to the top of 'Latest Products'.

**Comment by bhsmither** [comment]
I forgot to mention what brought this up:
https://forums.cubecart.com/topic/52025-image-issues/

Trying to focus on whether or not, as indicated by the results notice, if image selection is getting updated. (A comparison of `$hash_before` and `$hash_after` at line 421 will set `$updated`.)

This, or any, **specific** change cannot be determined if updating the "time updated" superimposes itself on the validity of the `$updated` variable.

**Comment by abrookbanks** [comment]
I hate the hash checks before and after so trying to figure out another way.

**Comment by abrookbanks** [comment]
hash check it is...

**Comment by Dirty-Butter** [comment]
I've suddenly started having issues with this - getting Failed to Update Product at random times when editing an existing listing - even when there was a definite change. Edit IS saved, but message shows.

**Comment by abrookbanks** [comment]
Do you have any customisations for products?

**Comment by Dirty-Butter** [comment]
Yes I do, but didn't have problems until the commit a few days ago. Trying to backtrack commit changes and getting cross-eyed with it.
