### ISSUE TITLE
Requesting New Hook - catalogue.class.php, getOptionData()

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1446]
requesting a new hook in the getOptionData function after

`$assigned = $GLOBALS['db']->select('CubeCart_option_assign', false, array('assign_id' => (int)$assign_id));`

This allows for the assigned option values to be overridden based on custom requirements.

**Comment by havenswift-hosting** [comment]
Added to 5.1.5 milestone ?

**Comment by abrookbanks** [comment]
hmm

**Comment by abrookbanks** [comment]
dyslexia strikes again.. :)

Updated to 6.1.5

**Comment by havenswift-hosting** [comment]
Saw it on a couple of other recent ones as well

**Comment by abrookbanks** [comment]
Thank yes all updated by editing the milestone.
