### ISSUE TITLE
Function/Method Appearance Order

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#145]
For CC5, I found the alphabetical order in which functions and methods appeared in their classes refreshing, as opposed to the hodge-podge order in CC3/4.

I request that after the beta testing is closed out, that the alphabetical order of the functions and methods be re-established in CC6.0.0 Gold.

**Comment by abrookbanks** [comment]
In the process of doing this now. The following image is proving REALLY handy!! LOL
![alphabet](https://cloud.githubusercontent.com/assets/4520803/6063665/e0fbf7e2-ad50-11e4-9770-c966f2eb7060.gif)

**Comment by abrookbanks** [comment]
Done. One of those jobs you wish you never started! :)
