### ISSUE TITLE
Confusing ID in Template

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1463]
In the admin template `products.index.php`, near lines 533 and 541, both `div`'s have `id="image"`.

This is preventing me from figuring out why the `"fm-actions"` block is acting squirrelly.

Suggest identifying the `"fm-filelist"` on the Images content div as `id="imageset"` and correcting the FileTree javascript, if necessary, to suit.

**Comment by bhsmither** [comment]
The javascript to fix that has been found so far is:
admin.js near lines 324 and 327:
```
From:
$("div#image.fm-filelist")
To:
$("div#imageset.fm-filelist")
Should also work:
$("div#imageset")
```
jquery.filetree.min.js, near line 65:
```
From:
if(typeof d.name == 'undefined') {
  d.name = "image"
}
To:
if(typeof d.name == 'undefined') {
  d.name = "imageset"
}
```
and near lines 332 and 347:
```
From:
$("div#image.fm-filelist")
To:
$("div#imageset.fm-filelist")
Should also work:
$("div#imageset")
```

**Comment by abrookbanks** [comment]
Relates to #1464

**Comment by abrookbanks** [comment]
Fixed with pull request. THANKS!! :)
