### ISSUE TITLE
FileTree Plugin Bad Bytes

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1467]
in the admin's jquery.filetree.min.js, near lines 328-332, 342, 343, 345, 346:

These lines have hard spaces `xC2 xA0`. Unless your programmer's text editor can switch the view of this file to examine the raw binary, you may not be able to see it. Some editors will show a special indicator for a regular space `x20` - usually a center-dot. These hard spaces will not have that special indicator.

I am investigating why, when clicking the `#fm-bcf`, the value for the security token inputs are not getting updated. See separate issue.

**Comment by abrookbanks** [comment]
I don't have the resources to look into trivial issues like this. If you can submit a pull request I'll consider it.
