### ISSUE TITLE
FileTree fm-bcf AJAX Return Misinterpreted

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1468]
When a Create Folder is submitted, this is in POST:
```
fm[create-dir]=folderName&token=currentSecurityHash
```
CubeCart sends back a simple string:
```
newSecurityHash
```
However, near line 327, where the AJAX call is made, the `success` function callback is not executed, rather the `error` function callback is executed.

Why, you may ask? When adding a `console.log(textStatus);` into the error function callback, I get:
"JSON.parse: unexpected non-whitespace character after JSON data"

The AJAX call parameters does not specify a dataType to be expected as the return. So, jQuery makes a best guess - in this case, a wrong guess and tries to json parse it. (The return headers say **Content-Type:text/html**, but I think jQuery is still making a wrong guess.)

The end result is that the newSecurityHash is not passed into the `$("input[name=token]")` and FileTree is not called, thus not showing an updated folder list.

Also, with now having an expired security token, any form submission made at this point will fail.

So, suggest forcing the issue and adding:
```
   dataType: "text",
```
within the group of AJAX parameters.

**Comment by abrookbanks** [comment]
Thanks Brian. :)
