### ISSUE TITLE
Discount amount varies after order status change

### ISSUE THREAD

**Issue by jasehead** [cubecart/v6#1469]
I logged in as a customer to reproduce a face-to-face sale to maintain inventory and produce an invoice.

Subtotal for two items was $69.90
Discount at 10.00% was $6.99 so I changed the discount to 10.01% to make the discount $7.00 - this was the amount shown during the order process.
Free Shipping/Pickup
Grand Total was $62.90

However, in admin orders (logged in as admin) and in customer order history (logged in as customer) both show the discount as $6.99 but still the grand total is $62.90.  The displayed figures here do not add up (one cent missing) and the discount does not match the amount shown during checkout.

**Comment by abrookbanks** [comment]
Might relate to #1442 and #1441

**Comment by jasehead** [comment]
I would think that it is a rounding issue. The issue is that the maths in the checkout display appears to be different to the admin orders/Customer order history, at least where the **coupon discount amount** is displayed.

**Comment by abrookbanks** [comment]
I can't reproduce this. Can you tell me the actual price of both products in the basket? Did you have any tax applied?

**Comment by jasehead** [comment]
Each item was $34.95 - no tax applied. The reason it was falling over may be because of the 5 cent, so 10% on one item would be 3.495 and so two items would be 6.990. However, the maths in the checkout is different to the maths used in admin orders/customer order history - that's the issue. Different figures showing in checkout vs orders.

**Comment by abrookbanks** [comment]
I still can't reproduce this. Is your store on recent code with no modifications?

Screenshots below... 

![screen shot 2017-02-16 at 12 16 33](https://cloud.githubusercontent.com/assets/4520803/23021035/d6da2de4-f441-11e6-8b36-4b6dfa016122.png)
![screen shot 2017-02-16 at 12 16 23](https://cloud.githubusercontent.com/assets/4520803/23021037/d6e01416-f441-11e6-82ee-c8ca52d6fb46.png)
![screen shot 2017-02-16 at 12 16 14](https://cloud.githubusercontent.com/assets/4520803/23021036/d6de4172-f441-11e6-9f28-a9947a1b4c17.png)

**Comment by jasehead** [comment]
I've had a go but can't reproduce it now. No updates since then or code changes that would make any difference. However, these are shots from the original order where $7.00 was displayed during checkout and $6.99 in the admin and customer views of the order after the fact.  You can see that 69.90 minus 6.99 should not be 62.90, but that's what was displayed in these views.  Also, in my store I'm not getting 10.01% showing as the discount in the Admin view, only 10% so perhaps you have made some changes in this area since CC6.0.12 

Admin > Orders
![admin - order summary](https://cloud.githubusercontent.com/assets/11954289/23091438/ff3fa4d8-f605-11e6-8564-d346bbf7af02.jpg)

Customer > Order History
![customer - order summary](https://cloud.githubusercontent.com/assets/11954289/23091439/02998022-f606-11e6-81e3-370ed6367b86.jpg)

**Comment by jasehead** [comment]
I FOUND IT!!!!
Look at the $7.00 discount in Admin/Orders, then change the status of the order and click Save & Reload - the amount then changes to $6.99.  YA HA!

**Comment by abrookbanks** [comment]
Percent was rounded to nearest whole number on the edit order page forcing it to 10% instead of 10.01%.

Thanks!! :)
