### ISSUE TITLE
Category images are malfunctioning

### ISSUE THREAD

**Issue by jetacera** [cubecart/v6#1470]
Saved category images are not displaying in the admin - they are not marked with the checkbox or displaying the selected image to the right of the list box. (this is after installing 6.1.4; 6.1.3 was working properly)

![admincategoryimages-selectedimagenot checked](https://cloud.githubusercontent.com/assets/11054131/22386839/e4d17042-e4a6-11e6-83fa-97b301270ac1.png)
![phpmyadmin-cccatstable-cat_image-selected](https://cloud.githubusercontent.com/assets/11054131/22386841/e4d1a8c8-e4a6-11e6-8f58-7a91519884ef.png)
![phpmyadmin-ccfilemanagertable-cat_image-info](https://cloud.githubusercontent.com/assets/11054131/22386840/e4d184b0-e4a6-11e6-80b1-619052b36d47.png)

**Comment by bhsmither** [comment]
It was? Not for me.

**Comment by bhsmither** [comment]
Anyway, I think I got it all sorted out on a CC613 installation. I will apply the edits to a CC614 installation and make a pull request (once I learn how).
