### ISSUE TITLE
Dropzone Missing in Categories

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1472]
When adding/Editing a category, the Images tab, below the FileTree, there is what I suspect should be a DropZone.

**Comment by bhsmither** [comment]
Will probably need to make `FileManager->_assignCategeory()` similar to `_assignProduct()`.

**Comment by bhsmither** [comment]
I am making a reference to #1470.

**Comment by abrookbanks** [comment]
Categories only take one image so for now it hasn't been added.

**Comment by bhsmither** [comment]
I have a package ready to be "pull requested" and @briansandall is helping me get it put in place.
