### ISSUE TITLE
Newsletter links associated with appending index.php?_a=newsletter with subscribe and unsubscribe.

### ISSUE THREAD

**Issue by appanage1** [cubecart/v6#1473]
Hi,
We may have found a bug within CubeCart itself involving Newsletter links associated with appending index.php?_a=newsletter with subscribe and unsubscribe.

If you go here:
https://suityourself.international/appanage/index.php?_a=newsletter&action=subscribe 

you will get links like this:
https://suityourself.international/appanage/index.php?_a=newsletter&action=subscribe&newsletter_id=17 
which do NOT work. 

However, if you go here:
https://suityourself.international/appanage/index.php?_a=newsletter

you will get links like this:
https://suityourself.international/appanage/index.php?_a=newsletter&newsletter_id=17 

that do work.

Regards,
Debra Spencer
(with assistance from Daren Clarke, semperfiwebservices)

**Comment by abrookbanks** [comment]
Thanks for this! :)
