### ISSUE TITLE
Import Snippets

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1480]
In `Hookloader->import_code_snippets()`, the xml node for `<php_code>` is placed in `$record` without first applying `base64_encode()`.

This is fine assuming the imported xml file contains php code already encoded. In `\docs\examples\code_snippet_import.xml`, the code samples are not encoded.

Expecting snippet xml files to have code already encoded is desirable, but not backward compatible, now that CC614 works with snippet code that is encoded in the database.

Suggest enforcing this with testing the first two or five characters for `<?` or `<?php` and encoding the data if found. (If not found, assume it is encoded.)

**Comment by abrookbanks** [comment]
Thanks Brian. I don't think the XML should ever have base64 encoding. Last commit will fix this.
