### ISSUE TITLE
Product options of catalogue page

### ISSUE THREAD

**Issue by keat63** [cubecart/v6#1484]
When clicking 'Add to Basket' from the catalogue page, no product options are set.
The only way to select a product option is to enter in to the product details first

I am aware that there is a paid plugin available for this, but shouldn't this really be part of the core engine ?

**Comment by briansandall** [comment]
@abrookbanks I believe this issue can be closed now ;)

It's curious that sometimes GitHub auto-resolves issues based on the commit message and other times not.

**Comment by abrookbanks** [comment]
Thanks :-)
