### ISSUE TITLE
Bracketed Querystring Param Borks at SEOable()

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1487]
Related to #1264.

In `currentPage()`, when creating a `$url_path` from `http_build_query()`, `$params` that are:
```
$params => Array (
    [seo_path] => sale-items
    [sort] => Array (
            [name] => ASC
    )
)
```
results in:
```
?seo_path=sale-items&sort%5Bname%5D=ASC
```
Sending this to `SEO->SEOable()` fails the `preg_match()` because (the % in) encoded brackets are not allowed. Thus, `_a=saleitems` is not SEO'd to `sale-items.html`.

This leads to VAL_SELF having non-SEO'd strings: `index.php?_a=saleitems`

This leads to SEO attempting to make an SEO'd string and 301 bounce the browser to it. This has, in the past, and maybe still, caused the `GET['sort']` to drop off.

Suggest:
The `preg_match()` `$path` argument be given to `urldecode()`:
```
From:
if (preg_match('#^(.*/)?[\w]+.[a-z]+\?_a\=([\w]+)\&(amp;)?([\w\[\]]+)\=([\w\-\_]+)([^"\']*)$#ieS', $path, $match)) {

To:
if (preg_match('#^(.*/)?[\w]+.[a-z]+\?_a\=([\w]+)\&(amp;)?([\w\[\]]+)\=([\w\-\_]+)([^"\']*)$#ieS', urldecode($path), $match)) {
```
Hmm. More to figure out here.

**Comment by abrookbanks** [comment]
From my testing it fails if there is no & in the query string and
