### ISSUE TITLE
After Killing SEO URLs, How to Completely Rebuild Instantly?

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1490]
See:
https://forums.cubecart.com/topic/52170-seo-link/

**Comment by havenswift-hosting** [comment]
I cannot really see any need for this.  As you say, the SEO urls are regenerated as needed and if they arent needed then there is nothing lost but it not existing - am I missing something.  Adding a new feature that puts a bulk load on a site / server (however big or small that may be) when it isnt needed is pointless

**Comment by Dirty-Butter** [comment]
> SEO urls are regenerated as needed>

Wouldn't the Google bots crawl cause the urls to be regenerated?  Site can be manually Fetched and Rendered easily via Google Webmaster Tools.

**Comment by abrookbanks** [comment]
>Wouldn't the Google bots crawl cause the urls to be regenerated? Site can be manually Fetched and Rendered easily via Google Webmaster Tools.

Yes so there should be no need for this.

**Comment by havenswift-hosting** [comment]
Agreed - customers accessing, Google or some of the many other bots that constantly crawl websites and as DB says, you can manually kick off a full site crawl anyway via GWT

**Comment by bhsmither** [comment]
Given from the conversation referenced, I inferred that the need to get the seo-friendly paths rebuilt "now" rather than let it happen organically, even if sending a web spider a special request, was not sufficient.

**Comment by havenswift-hosting** [comment]
There is nothing in the original thread that defines what "now" is nor the reason for needing it immediately.  I cannot see any reason for needing it, adding it wastes Al's time, bloats the software and potentially adds functionality that puts loads onto servers and sites that isnt needed.  If the original poster really wants that type of functionality for some reason, then better to be added as a plugin in my opinion

**Comment by abrookbanks** [comment]
I'm feeling smug right now as I have smashed the issues recently. At the time of writing only 4 issue are open that require investigation:

https://github.com/cubecart/v6/issues?utf8=%E2%9C%93&q=is%3Aopen%20-label%3A%22feature%20request%22%20

**Comment by Dirty-Butter** [comment]
You HAVE been busy! I do have an issue with one you have closed. https://github.com/cubecart/v6/issues/1348#issuecomment-278375994

**Comment by bhsmither** [comment]
I don't really concern myself with OP's reasons for wanting a solution. I try very very hard not to second guess. They have their reason and it's important to them.

Having a site "organically" regrow the seo_paths through _normal accesses_ or by _being spidered_ involves **a whole lot more activity** as opposed to coding in a simple SELECT/INSERT when making a sitemap.

Relying on normal page accesses cannot guarantee that all products will be seen, thus, being dependent on regrowing the seo_paths organically, by the time a sitemap is generated there is so nearly a certainty that a sitemap reference will not have a matching seo_path.

Requesting a full complete spider of a site, as I said, involves a degree of magnitude greater of PHP/database activity, **and** at many hundreds of products, categories and documents, could suck a hosting account's monthly bandwidth allocation bone dry. (Of course, not knowing what Google does after retrieving the sitemap, if that causes a massive crawl, you lose either way.)

So, creating a plugin would certainly solve this, but it would consist of much of what the sitemap does already.

**Comment by cb2004** [comment]
https://github.com/cubecart/v6/issues/1164
