### ISSUE TITLE
Option Values Sort

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1493]
I think there may be nothing wrong with the current query, but maybe the suggestion is better.

In products.options.inc.php, line 240, an array contains the SORT BY argument for Option Groups.

Line 253 has:
```
'IF(priority>0, priority, value_id) ASC'
```
which *should* cause an (unmanaged) `value_id` to appear at some unwanted position in the list otherwise sorted by `priority`.

Suggest:
```
  $sort_value = array('priority' => 'ASC', 'value_name' => 'ASC');
  $values = $GLOBALS['db']->select('CubeCart_option_value', false, false, $sort_value);
```
This gives same priority rows a sub-sort by name.

I am currently working out a solution to:
https://forums.cubecart.com/topic/52176-order-option-attributes-asc-in-admin/
that offers a checkbox to indicate a command to remove all priority.
```
// Still a work in progress
$update = array();
foreach ($_POST[$name] as $key => $id) {
  $update[$id]['priority'] = ($_POST["priority_reset[$name]"]) ? 0 : $key+1;
}
foreach ($update as $id => $array) {
  $GLOBALS['db']->update($table[0], $array, array($table[1] => $id), true);
}
```

**Comment by abrookbanks** [comment]
Thanks again.

**Comment by briansandall** [comment]
The whole point of that sort query was to allow unmanaged value_ids to appear in the order they were added.

As is (or was, haven't tested the new code yet), new entries that have yet to be given a priority have a potentially random sort order, which sucks when adding a bunch of new option values.

**Comment by abrookbanks** [comment]
Reverted for 6.1.6.

**Comment by briansandall** [comment]
See #1248 for original context.

**Comment by bhsmither** [comment]
I see I have contradicted myself in solving for two different but similar scenarios. Maybe this solution is not comprehensive enough.

**Comment by briansandall** [comment]
I don't believe it is possible to allow sorting by both at the same time, though we could perhaps add an admin option.

However, I submit that ordering secondarily by `value_id` is the correct choice. Test cases:

1. Option values `A`, `B`, `C` entered in order will order correctly by `value_id`, entered in any order will order by `value_name`

2. Option values `One`, `Two`, `Three` entered in order will order correctly by `value_id`, but are impossible to order correctly by `value_name` no matter in what order they are entered.

Whatever percentage of option values that can be ordered alphabetically, there exist enough that are not alphabetical to make `value_id` the preferred choice.

That said, I like the idea of re-prioritizing existing entries by `value_name` as an option.
