### ISSUE TITLE
Could Email When Shouldn't

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1494]
Actually, it won't. This issue is absolutely inconsequential, but the code flow needs tweak.

In `Order->orderStatus()`, for cases Pending, Processing, and Complete, if, for whatever reason, `Mailer->loadContent()` returns false, `$content` is now false.

Note that `$content` only gets unset if it is not false.

Later, below case Cancelled, a test is made if `$content` is set. Given the above, it is set to false.

`Mailer->sendEmail()` calls `_parseContents()` which returns something that is not set. (The docblock needs updating.)

The end result is that `sendMail()` does nothing of consequence and returns false.

The code flow tweak suggestion is:
Move `unset($content);` out of the `if()` block and place it just above each case `break;` statement.

**Comment by abrookbanks** [comment]
Thanks Brian. I actually put it after each if condition so not to try to unset something that might not be set in the first place. :)
