### ISSUE TITLE
Extra functionality for database index checker

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1495]
Great new tool but could also check for duplicate indexes on same column or combination of columns.  I was checking this on a variety of websites and had the following - if this could be checked and highlighted as well

![duplicate_indexes](https://cloud.githubusercontent.com/assets/6114431/22883571/12ffccd2-f1f1-11e6-929d-5d4e659bfd17.png)

**Comment by havenswift-hosting** [comment]
Also the indexes on CubeCart_config.name, CubeCart_ _lang_sort would be better to be PRIMARY and not UNIQUE

**Comment by abrookbanks** [comment]
Nice idea! I'll add this.

**Comment by abrookbanks** [comment]
![screen shot 2017-02-14 at 10 51 55](https://cloud.githubusercontent.com/assets/4520803/22926224/a336eb52-f2a3-11e6-890c-8ff5a0e49912.png)

**Comment by abrookbanks** [comment]
Actually this isn't quite there yet..

**Comment by cb2004** [comment]
Nice addition @abrookbanks. Should this also check InnoDB vs MyISAM. The majority of the tables with a fresh install are InnoDB however if people have upgraded from previous versions tables are set as MyISAM.

**Comment by abrookbanks** [comment]
Good point. It probably should..

**Comment by cb2004** [comment]
@abrookbanks good stuff. We all like a healthy db.

**Comment by abrookbanks** [comment]
They should all be inno unless they have full text index.

**Comment by cb2004** [comment]
Loads of mine are MyISAM from as far back as v3 so it would be good to add this check (even though I can compare the tables to a fresh install).

**Comment by abrookbanks** [comment]
I don't think it matters much.

**Comment by havenswift-hosting** [comment]
It would also be good if it could check the collation at all levels as well - many subtle problems happen if this is wrong

**Comment by havenswift-hosting** [comment]
CubeCart_system_error_log needs an INDEX on the `time` column.  Just had a site where debug was left switched on for a while and there were 375,000 messages in the log (rising at 100 or so a minute !) and the delete uses WHERE `time` < but with no index

**Comment by abrookbanks** [comment]
Fixed by turning debug mode off.. I'll add that index.
