### ISSUE TITLE
mailer.class.php  - hook request

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1496]
It would be handy to have a new hooks in the sendEmail function.

BEFORE:
`$this->ClearAddresses();`

ADD:
```
foreach ($GLOBALS['hooks']->load('class.mailer.send') as $hook) include $hook;
if(isset($stop_send) && $stop_send === 1){
return false;
}
```

This would allow for a module to prevent sending of e-mails on an adhoc basis, or add new fields like BCC via a module/custom functionality.

It also means if we populate $stop_send with an int of 1, it will return false to the function and prevent sending of mails.

**Comment by abrookbanks** [comment]
No need for; ```if(isset($stop_send) && $stop_send === 1){
return false;
}```
as this can be within the hook.

**Comment by Noodleyman** [comment]
nope, if you return false from the hook, it returns false to the include function, not the actual mail function ;)

**Comment by Noodleyman** [comment]
@abrookbanks , can you reconsider the code ammendment after the hook please? It's not possible to return false from the hook itself, so there isn't any way to prevent the mailer from performing additional steps beyond the hook without direct modification to the core files
