### ISSUE TITLE
Not receiving upgrade notifications 

### ISSUE THREAD

**Issue by claudia39** [cubecart/v6#1498]
I am not receiving the red banner or news announcement of upgrades for CC or plugins on my dashboard.  Plus the new extension thumbnails are not showing.  Found out this is why: 
"Once a version-check has been made, regardless of the response, that fact is stored in the SESSION and no further checks will be made until the SESSION is cleared - that is, until you logout (then log back in)."
Problem is I hardly log out of my admin so I will not get the notifications. Is there another way to do this so sessions aren't involved for those of us who do not log out of admin.

**Comment by abrookbanks** [comment]
Please open a support ticket if you need us to look at this.

**Comment by abrookbanks** [comment]
![screen shot 2017-02-15 at 09 21 20](https://cloud.githubusercontent.com/assets/4520803/22967896/396d473a-f360-11e6-9578-edf2fa1221a3.png)
![screen shot 2017-02-15 at 09 20 56](https://cloud.githubusercontent.com/assets/4520803/22967897/396fe83c-f360-11e6-8592-4fef54f63880.png)
