### ISSUE TITLE
Options Matrix - editable fields

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1500]
If you have a lot of options and you add them to the matrix, you can end up with a huge number of additional form fields added to the product edit page. This can trigger CSRF errors and prevent the product from being managed.

Recommending that matrix form fields (stock level, product code, UPC code, EAN code, JAN code, ISBN code etc) be set to click to edit, which prevents submission and reduces the risk of CSRF issues.

To support the complex products on a customer store, I had to set max_input_vars to 15,000

**Comment by briansandall** [comment]
Great idea! I put mine at 25,000 just because I was too lazy to calculate how many I'd actually need and it was already at 2,500.

**Comment by abrookbanks** [comment]
Good plan.

**Comment by briansandall** [comment]
It would be very nice when adding a product if it was possible to click a column header and make all of the inputs for that column editable, and to be able to do this for any arbitrary combination of columns. 

Adding products with huge matrix arrays would then become the best experience ever, being able to easily switch through only the inputs you care about via `TAB` and not having to worry about exceeding the max_input_vars limit.

**Comment by Noodleyman** [comment]
Nice idea Brian. :)

It got me thinking about other enhancements as well. It would be realllllly nice if there was a way to show a warning/error when editing a product (or any page really) if the number of form inputs is close to, or exceeds the configured max_input_vars value. It should be possible to count the fields using JS/jQuery.

The most common reason for CSRF failures I see is this threshold being reached. Having a warning about it may also help prevent frustration. I've had some comments from customers who hit this limit in the past suggesting they got frustrated after spending quite a bit of time editing/inputting data for it to then throw a CSRF error and discard their inputs. If they had a warning/error before making those changes it may have prevented them from losing time and thus, not so frustrated.
