### ISSUE TITLE
Dashboard Not Showing Two Years

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1502]
In dashboard.index.inc.php, line 156, an attempt is made to arrive at a unix timestamp of 12Noon, the 15th of this month, of this year, but the year value is using the wrong variable.

Then, line 157, `$last_year` is none other than `$this_year -1`. How can it be anything but?

Personally, after line 158, I add:
```
$last_year_start   = mktime(0, 0, 0, '01', '01', $this_year - 1);
```
Then, in Statistics (line 184), I used:
```
$sales = $GLOBALS['db']->select('CubeCart_order_summary', array('order_date', 'total'), array('order_date' => '>='.$last_year_start, 'status' => array(3), 'total' => '>0'));
```
to show a full last year.

(Impossible to see on C6 Demo as there are no orders that were made after 2012.)

**Comment by abrookbanks** [comment]
Thanks. This is spot on! :)

**Comment by abrookbanks** [comment]
I added status for 2 also. It should check processing and completed.

**Comment by bhsmither** [comment]
Line 156 is still using the wrong variable for the year parameter.

**Comment by bhsmither** [comment]
Not that it actually matters.
As of today, `mktime()` gives 12Noon Feb 15, 2002. One month back is January regardless of the year for all eternity.

Still, from a programmer's point of view, it is best to not be misleading.

**Comment by abrookbanks** [comment]
Thanks I'll check these things out...
