### ISSUE TITLE
Product Option translations

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1505]
See https://forums.cubecart.com/topic/52214-translations-for-product-options/

**Comment by briansandall** [comment]
I've come up with a basic outline of an implementation but haven't had a chance to actually code anything yet. Here's what I'm thinking:

A template `language/options_template.xml` file (rename to e.g. `langauge/options_en-US.xml` to create an actual translation) should be able to be auto-generated by an admin as well as refreshed after adding new or modifying existing product options.

Format for an options translations file would be e.g.:
```
<group name="{option_group.name}">
    <string name="group_name"><![CDATA[original_group_name_edit_to_translate]]></string>
    <string name="{option_value.name}"><![CDATA[original_value_name_edit_to_translate]]></string>
    // remaining option value entries
</group>
```
Loading an additional language file shouldn't be too much effort and, if it doesn't exist, the database entry values would be used instead.

The logical place to handle the translating would be in `catalogue.class.php::displayProductOptions` prior to making the data available to the skin, though I haven't checked where else they may appear.

I don't think the option groups or values should be translated when viewing from the admin panel, only on the customer end when they are browsing the catalogue, or placing or reviewing an order. If possible, they should also be used in any email sent to the customer, but not to the admin.

**Comment by hollisterca** [comment]
I would like to 2nd this request. You know how it is. Either you go the whole distance with the translation or not. Doing it half way should not be an option. There are 3 German speaking countries (DE, CH, AT) they like to order in their mother tongue. I think the same goes for any language.  In Switzerland especially, we have 3 languages, German, French and Italian. Just having the options and option attributes in English is bad

**Comment by abrookbanks** [comment]
This issue is closed until it's added to the roadmap. Thanks for the feedback. There are other areas too like SEO URLs
