### ISSUE TITLE
Search - Unknown column 'Relevance' in 'order clause'

### ISSUE THREAD

**Issue by Rieduci** [cubecart/v6#1506]
Hi,
Does anybody know how to solve problem with search on CubeCart V6 (any of skins)?
 I found that it doesn't performs search correctly in case less than 4 characters entered in the search box. 
In case product name is at least 4 characters - it works well. 
But there is problem in case  product name consist of 2 characters- for example  "K2".  In this case I have negative search result  (No product found).
Is there some possibility to perform search based on 2 characters?

System Error log generates new error message:

File: [catalogue.class.php] Line: [1760] "SELECT I.* FROM cc_CubeCart_inventory AS I LEFT JOIN (SELECT product_id, MAX(price) as price, MAX(sale_price) as sale_price FROM cc_CubeCart_pricing_group WHERE group_id = 0 GROUP BY product_id) as G ON G.product_id = I.product_id WHERE I.product_id IN (SELECT product_id FROM `cc_CubeCart_category_index` as CI INNER JOIN cc_CubeCart_category as C where CI.cat_id = C.cat_id AND C.status = 1) AND I.status = 1 AND (I.name RLIKE '[[:<:]]K2[[:>:]]' OR I.description RLIKE '[[:<:]]K2[[:>:]]' OR I.product_code RLIKE '[[:<:]]K2[[:>:]]') ORDER BY Relevance DESC LIMIT 12 OFFSET 0 " - Unknown column 'Relevance' in 'order clause'

Thank you in advance!

**Comment by briansandall** [comment]
In `classes\catalogue.class.php`, change the search_mode default to 'rlike':
```
// From:
public function searchCatalogue($search_data = null, $page = 1, $per_page = 10, $search_mode = 'fulltext') {

// To:
public function searchCatalogue($search_data = null, $page = 1, $per_page = 10, $search_mode = 'rlike') {
```
That should allow searching terms of any length.

**Comment by Rieduci** [comment]
Many thanks!
It works!
