### ISSUE TITLE
Language Packs

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1511]
Regarding #1263 and #196, is there a method (via the Github??? where pull requests can be made) where random contributions can be entered?

I downloaded the latest English language pack and it has the nested braces problem:
```
{if !empty({$BILLING.company_name})}{$BILLING.company_name}
```
The CKeditor will corrupt templates having nested braces.

I believe all language packs originally sourced from CC5 have the nested braces problem.

(I have no skill at making translations, but I can do this simple fix for these files in the Marketplace.)

**Comment by Dirty-Butter** [comment]
I created a trial store with stock code recently. I was merging the latest commit today and realized the US language pack still has all the nested braces. It's easy to tell the code has not been upgraded, as the breaks are still coded as 
`````
<br />
`````

**Comment by abrookbanks** [comment]
It does but code within CubeCart will correct them on import. It was much easier to do this than edit each language pack individually.

**Comment by Dirty-Butter** [comment]
Something is messed up then. I just installed the Spanish language pack on the stock test store, and all the braces and ````` <br /> ````` are still there. I used the lightning bolt to install it.

**Comment by abrookbanks** [comment]
I just installed Spanish. Can't find any faults. Maybe I misunderstand. 

![screen shot 2017-05-10 at 14 11 50](https://cloud.githubusercontent.com/assets/4520803/25900252/bc7f217c-358a-11e7-8dff-0714a89f0c11.png)

**Comment by Dirty-Butter** [comment]
OK - I was looking at the email_es-ES.xml file itself. The ````` <br />````` are still in the Source Code from within the Admin email templates. But the braces issue is not in the Admin templates. Sorry for wasting your time.

**Comment by abrookbanks** [comment]
Not wasting my time. It's good to make sure things are right and I very much appreciate your time Rosemary. :)
