### ISSUE TITLE
Ability to set ONE USE Coupon Code per Customer

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1512]
I really need a way to limit our sale coupons to one use per customer.

**Comment by bhsmither** [comment]
If you have tried this:
https://www.cubecart.com/extensions/plugins/coupon-enhancements
and it doesn't work for you, what would you need implemented in the core code?

**Comment by Dirty-Butter** [comment]
Ahhh! I called myself looking thru the extensions and the forum. THANKS!
