### ISSUE TITLE
Coupon Availability State

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1513]
In cart.class.php, near line 593:
```
$this->basket['coupons'][strtoupper($coupon['code'])] = array(
  ...
  'available' => ($coupon['allowed_uses'] > 0) ? $coupon['allowed_uses']-$coupon['count'] : 0,
```
What is the state of `'available'` supposed to represent? Zero? False? Unlimited?

I have not yet looked to see where this state is examined, though I think it may not be used anywhere - yet.

**Comment by abrookbanks** [comment]
I think you may be right but its probably best to leave it just in case. 

If the array key was coupon_available or something a bit more unique I'd be more confident to remove it. "available" is quite generic.
