### ISSUE TITLE
Indexes in Database

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1515]
The Maintenance, Database tab scan overthinks the response.

For example, in my database, CubeCart.admin_users has:
PRIMARY KEY ('admin_id')
KEY 'admin_id' ('admin_id')

The loop at line 850, according to `$index_map`, is expecting the first, and is satisfied that it exists. However, the loop then asserts that:
CubeCart_admin_users.admin_id has a key type KEY but expecting PRIMARY.

So, errors detected are for "missing" indexes and "wrong" indexes, but *extra* indexes throw misleading "wrong" errors.

**Comment by bhsmither** [comment]
I see you are working on it at #1495.

**Comment by abrookbanks** [comment]
You are right but it doesn't matter from my testing. It will report errors until set correctly. 

If adimin_id has a primary key and a key it will report that the key type is wrong. On investigation it should become clear why.
