### ISSUE TITLE
PayPal_Pro: PayPal_Pro_Mark payment displays on 'confirm' page

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1516]
In PayPal_Pro/hooks `class.cubecart.display_gateways.php`, the PayPal_Pro_Mark payment option may be added based on the module settings and under the following condition:
```
if(!in_array($_GET['_a'], array('basket', 'checkout'))) {
```
If the customer ends up at the `confirm` stage of the checkout process, they will see the PPP Mark option regardless of settings.

Suggest changing both instances (lines 69 and 102) to:
```
if(!in_array($_GET['_a'], array('basket', 'checkout', 'confirm'))) {
```

**Comment by abrookbanks** [comment]
Thanks. Fixed with 1.1.7.
