### ISSUE TITLE
Stripe module suggestions

### ISSUE THREAD

**Issue by cb2004** [cubecart/v6#1517]
I really like the Stripe module and it is working well, however there have been a few lost orders because of failed transactions. It looks like these lost orders are because people are leaving the expiry date as is, which selects the current month and year + 2, meaning their cards fail. I think the user should be made to input this data and the select fields should have the required="required" element.

Also where it has $LANG.basket.customer_info this is misleading, this should definitely be $LANG.address.billing_address.

**Comment by abrookbanks** [comment]
Thanks Chris.
