### ISSUE TITLE
CubeCart_customer.language - not used?

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1519]
I refernce this field to figure out the language of a customer, which means I can load a mail template according to the users language.

However, I am not seeing this field get updated/used correctly by CubeCart.

For example, a store with only the language en-US always populates it with en-GB, which means the lookup of mail templates fails when referencing en-GB.

It looks like en-GB is the default value both in the CC core code and also the DB table/column value. 

I think there are issues around this field being populated correctly. It should be set to the store default on user creation, and then updated to the new language on user language changes.

Outside of modules, this also appears to have broken the sending of notifications of order status changes as well. Without en-GB installed no mails are sent.

**Comment by bhsmither** [comment]
Just an observation: Since en-GB is part of the deliverable package, one would wonder why an admin would feel it necessary to delete it. It can be disabled.

**Comment by Noodleyman** [comment]
I agree.. but I assume it also means email notifications may be sent in the
wrong language. They should be sent according to the users selection.  The
difference between gb/us is minor, but the issue scales if your talking say
french/English and the recipient doesn't read English.  :)

**Comment by abrookbanks** [comment]
Looks to me like this column should be dropped.

**Comment by bhsmither** [comment]
I disagree.

I suggest that when an account is created by the customer, the language being used by the customer (assuming that the language was selected via the 'box.language.php' language selector) is what gets put here - or is `selected="selected"` on a drop-down chooser on the Registration and Profile pages. An admin-created customer has a best-guess by the admin.

This does provide highly desired versatility on a number of functions not related to the Order Summary (which logs the language in use when the order is made), such as Newsletters and 3rd Party extensions.

I can also see a use for a similar column added to the CubeCart_addressbook table (as well as an email column as requested in another issue) for customer Company contacts using a different language.

**Comment by abrookbanks** [comment]
Damn it that sounds like more work. Lol

**Comment by briansandall** [comment]
> Damn it that sounds like more work. Lol

I would say 'job security,' but you don't really get paid for this... ;)

**Comment by abrookbanks** [comment]
I'd better not piss off the boss as he's a nasty piece of work. 😥

**Comment by abrookbanks** [comment]
Speaking of job security I think it's time to plan 6.3.

**Comment by briansandall** [comment]
What happened to 6.2? Is there a specific point at which a jump in the minor version is made (where version is _major.minor.revision_), or do you just eyeball it?

**Comment by abrookbanks** [comment]
I was just testing you. Pleased you are on the ball. 😌

**Comment by abrookbanks** [comment]
6.2 I mean... It's been a long week....

**Comment by havenswift-hosting** [comment]
I think it would be better if we could adopt the standard version changes i.e. Major for a significant number of functional changes ; Minor for additional features ; Revision for bug fixes and security fixes.  This allows for quick revision releases where there is little risk in the upgrade but also more time for testing of Minor and Major releases

**Comment by abrookbanks** [comment]
I've removed this column as its utterly pointless. The customer can set the language for their session which should stick. I would expect that if they wanted a different language they would change it before logging in anyway.

**Comment by Noodleyman** [comment]
Can you review this again?

It really isn't a lot of effort to log what is in the session to the existing DB column at the customer level. This is really helpful when writing modules which make use of the language system, but where a customer hasn't placed an order.

An example of this is the abandoned carts module which will e-mail customers to remind them they have not yet completed an order. 

If their chosen language is stored in their session, and the language field is removed.. how do we know what language to send the e-mail using?

This could also lead to the newsletters functionality supporting the language system as well as other improvements.

It would be very VERY helpful on a number of fronts if this could be fixed rather than dropped.

**Comment by abrookbanks** [comment]
> An example of this is the abandoned carts module which will e-mail customers to remind them they have not yet completed an order.

But the language is saved against the order in the order_summary table.

**Comment by Noodleyman** [comment]
But they haven't placed an order yet? ;)

**Comment by abrookbanks** [comment]
https://github.com/cubecart/v6/blob/master/setup/db/install/structure.sql#L695

**Comment by abrookbanks** [comment]
> But they haven't placed an order yet? ;)

Hmm I suppose they only happens if they get to a certain stage. 

Ok I'll reopen...

**Comment by Noodleyman** [comment]
Thank you Al.

I think it's quite a simple piece of information to capture, but it can be very helpful for developers. 

As noted above in my earlier comment, it could also mean that the newsletters are also able to support multiple languages as well because the per-customer language is known. This would be quite helpful for larger stores who use multiple languages.

**Comment by abrookbanks** [comment]
Yes I'll get it done. I though you wanted an option on registration for default currency which would be naff. :)

I'll get this populated with lang change......

**Comment by Noodleyman** [comment]
Cheers Al,

I don't see any need for this to need any changes within the UI/Skins itself. The user gets the system default language unless they have changed it.

So I think it just needs an adjustment to the language change process to write out the new language to the customer record (if they are logged in).

It might be also a good idea to set the default to be whatever the store default language is at the time of registration rather than "en-GB". 

And as a maintenance task, if you delete a language it should also reset any customers languages to the store defatult where it matches the language being deleted.

It might also be nice to see what language the customer is using in the customer record/area via the admin section. I don't think it needs the admin to be able to change it, simply view it.

Off the back of that, stats can be added to show a breakdown of customers by language. although, this is just nice to have. I might add it to my advanced reporting module. :)

**Comment by abrookbanks** [comment]
Sorted...
