### ISSUE TITLE
#1499 broke autosubmit for sorting search results

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1522]
Not sure what it is yet, but I did narrow it down to this specific commit: 998766d

To test this for yourself (since that commit doesn't change anything that would obviously have any effect on sorting... but it does):
```
git checkout 042f144
// refresh search results page, change sort by column; sweet, it works
git checkout 998766d
// refresh again, try to change sort - fails
```

**Comment by abrookbanks** [comment]
This should have fixed it:
https://github.com/cubecart/v6/commit/64c7c6aa9059033dc23e2fa80c78aa2a6f4e5867

**Comment by briansandall** [comment]
Confirmed to be working now - thanks!

**Comment by abrookbanks** [comment]
Thanks for that!
