### ISSUE TITLE
Search: No products found redundant error message

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1530]
Added [here](https://github.com/cubecart/v6/blob/master/classes/cubecart.class.php#L811):
![cc_1530](https://cloud.githubusercontent.com/assets/14335170/23477014/6f5054de-fe71-11e6-8f5c-0cc1946f66e0.png)

Seems a little unnecessary, don't you think?

**Comment by abrookbanks** [comment]
Yeah certainly a bit OTT.. thanks.. I'll take a look.

**Comment by abrookbanks** [comment]
Thanks so much Brian!!! :)
