### ISSUE TITLE
Admin redirects to specific tabs no longer working

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1531]
Finally found a problem with #1521, a specific example is adding a manufacturer:
```
// URL generated before #1521 (still works if manually entered):
http://localhost/git/forks/cubecart/v6/admin.php?_g=products&node=manufacturers#tab_manufacturers#manu_add

// URL after:
http://localhost/git/forks/cubecart/v6/admin.php?_g=products&node=manufacturers%23tab_manufacturers#manu_add

// Results in /admin/sources/products/manufacturerstab_manufacturers.inc.php - not found
```
This seems to only affect the `node` when an additional tab is specified, i.e. when there is more than one hash tag in the URL. The URL is properly encoded, but does not seem to be compatible with the way CubeCart currently manages tabs.

Debugging `controller.admin.session.true.inc.php` reveals the issue:
```
// Before #1521
print_r($node): 'manufacturer'

// After #1521
print_r($node): 'manufacturers#tab_manufacturers'
```
It's not possible to manage the issue in `acp.class.php#importNode` due to stripping of all non-alphanumeric characters prior to calling that method, but I believe it can be fixed in the admin controller class, which is currently the only place that calls that function.

For example:
```
$node = (!empty($_GET['node'])) ? strtolower($_GET['node']) : 'index';
$node = explode('#', $node, 2)[0]; // drop everything after a hash sign
$node = preg_replace('/[^a-z0-9_-]/', '', $node);
```
This results in the correct `$node` output, but after adding a manufacturer it doesn't return you to the correct tab, but instead remains on the 'Add Manufacturer' tab.

**Comment by briansandall** [comment]
I've tracked the issue down to `admin.js`, which handles the tab controls. Since `window.location` is used as is, the (correctly) encoded URL with the tab content is not getting recognized.

As a quick hack:
```
// line 525
$("div.tab").each(function() {
   // decode the window location
    window.location = decodeURIComponent(window.location);

// Given:
http://localhost/git/forks/cubecart/v6/admin.php?_g=products&node=manufacturers%23tab_manufacturers#manu_add

// I now correctly end up at:
http://localhost/git/forks/cubecart/v6/admin.php?_g=products&node=manufacturers#tab_manufacturers#manu_add
```
However, the page will flash briefly with the incorrect tab prior to displaying the correct one, vs. when the hash is unencoded it loads directly.

It occurs to me that perhaps we are not adding the tab anchor correctly. Do we really need `#manu_add` in the URL, or should we be replacing that with the tab control instead? This would be a cleaner solution than the JS hack above.

The manufacturer page is the only example I have found so far were two hash tags end up in the URL.

**Comment by briansandall** [comment]
For example, changing line 57 in `products.manufacturers.inc.php`:
```
// From:
httpredir('?_g=products&node=manufacturers#tab_manufacturers');

// To:
httpredir('?_g=products&node=manufacturers', 'manufacturers');
```
This works correctly, even without the JS hack mentioned above.

**Comment by abrookbanks** [comment]
Fixed with pull request. Thanks!!! :)
