### ISSUE TITLE
Adding Option Set gets Malformed Options in List

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1533]
See:
https://forums.cubecart.com/topic/52268-options-issue/

Create an option set.
Edit a product, Options tab.
Choose an Option Set, Click the Add button.
The first letter of the Option Set name is shown for various data items for each element in the set.

**Comment by abrookbanks** [comment]
That's odd... I recently worked on this and tested it meticulously.. hmmm

**Comment by abrookbanks** [comment]
Clearly didn't test meticulously...

**Comment by kalyncomputers** [comment]
The problem still exists - please see this link https://forums.cubecart.com/topic/52461-options-strange-behaviour/

**Comment by Noodleyman** [comment]
I am getting reports of this in 6.1.8 although have not verfied it myself yet
