### ISSUE TITLE
Stock Levels chart feature request

### ISSUE THREAD

**Issue by jetacera** [cubecart/v6#1534]
For items using the stock matrix, would it be possible to display a chart of the quantity in stock rather than just the quantity range? i.e. if there are 5 Small Red, 10 Medium Black, 15 Large Blue, 20 X-Large Red, and 30 X-Large Black, these variations with each quantity are in a chart rather than just displaying 5-30

I have a customer requesting this.

**Comment by abrookbanks** [comment]
This would be possible. I can take on sponsored development if this is something you need sooner than later.

**Comment by jetacera** [comment]
How much?

Customer is requesting this, so if he agrees, I will purchase.

**Comment by abrookbanks** [comment]
Can you email sales at cubecart dot com with specific requirements and specification?
