### ISSUE TITLE
Non-Object

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1539]
In Debug `_writeErrorLog()`, a call to `$GLOBALS['config']->get()` is made.

A test should be made to make sure `$GLOBALS['config']` is set and is an instance of the Config class.

In setup.install.php, line 235, `$GLOBALS['config']` is holding an array.

In a certain sequence of events, this is a problem.

Suggest replacing everywhere `$GLOBALS['config']` with `$GLOBALS['glob']` where `$GLOBALS['config']` is understood to be holding the `$glob` array. `$glob` should be available everywhere using `$GLOBALS['glob']` since it was set in the global scope.

Then, after all that replacing, suggest assigning the instantiation of Config (line 266) to `$GLOBALS['config']` like such is done everywhere else.

**Comment by abrookbanks** [comment]
> In a certain sequence of events, this is a problem.

Thanks for this but there is a lot of scope for error with these changes. I agree that there is potential problems but is there actually one? I don't really want to embark on potentially introducing new bugs in an attempt to fix something that isn't actually a problem. 

If there are steps to reproduce the no-object fatal error I'd happily look into that. 

Happy to reopen if needs be.

**Comment by abrookbanks** [comment]
```
$log_days = $GLOBALS['config']->get('config', 'r_system_error');
```
