### ISSUE TITLE
English Language "not there" - but it IS there!

### ISSUE THREAD

**Issue by hairydogltd** [cubecart/v6#154]
I installed the b4 update. Then I went to check that my language file updates were still there. 

But when I click the link, I'm told 
"No languages have been found. Please visit the marketplace to get hold of the ones you want."

So I went to the marketplace, got the Auto Install/Upgrade Token, pasted it in the field of the Manage Plugins page and it seemed to install OK. And in fairness, I think it *has* installed OK. 

But it still shows "No languages have been found. Please visit the marketplace to get hold of the ones you want."

I can use the Edit Phrases tab to customise language string translations OK, and yes, all my previous updates are there. It all appears to have worked just fine: it is just the message that says there are no languages that seems to be the error.

**Comment by abrookbanks** [comment]
Hmmm I think this is since the ability to disable caching was added back.

**Comment by abrookbanks** [comment]
I'm pretty sure this is now resolved with:
https://github.com/cubecart/v6/commit/887ae7913eb7e9890a255574284c3d5ef9fe4d02
https://github.com/cubecart/v6/commit/3c8cc695fab0a8b6bf201529e603d18d9d1aa1b2

**Comment by abrookbanks** [comment]
Testing a fresh install....

**Comment by abrookbanks** [comment]
This is working fine since testing from commit 86e12240d23c71c40ce7bb4e491baacf7794d94e. A number of caching changes have been made.
