### ISSUE TITLE
Assumed ID When Installing SQL Data

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1541]
In data.sql, three records are being inserted for CubeCart_tax_class, one record is being inserted for CubeCart_tax_details, and three records are being inserted for CubeCart_tax_rates.

In CubeCart_tax_rates, specific values are being entered for `type_id` (this is `CubeCart_tax_class`.`id`?), `details_id`, and `country_id` (actually `CubeCart_geo_country`.`numcode`, which is a known and invariable value).

The `type_id` and `details_id` are **assumed** to be what could be expected from the database under most, but specific circumstances from installation.

Suggest the INSERT statements for CC_tax_class include values for `id`, and for CC_tax_details include values for `id`.

This was discovered during a fresh, complete installation, where, for other reasons, PHP crashed. SESSION still had me at 80%. When the errors were worked out and /setup/index.php restarted, I noticed that CC_tax_class had numerous sets of the three records because there was nothing to prevent duplicate records.

The same for CubeCart_documents, although there is no relationship with another table.

**Comment by abrookbanks** [comment]
Great find thanks Brian! :)

**Comment by bhsmither** [comment]
Give some consideration, also, to examples.sql.

Only from the point of view that restarting the installation without truncating what was already done, will add ore records because there is nothing to prevent duplicate records.
