### ISSUE TITLE
Can't progress to checkout using Google Chrome, but Microsoft Edge works fine.

### ISSUE THREAD

**Issue by manifest-tamar** [cubecart/v6#1544]
1. I click on "add to basket", in either the category or product page, and the item shows up correctly in the basket at the top. 
2. When I try to checkout or view my basket, the new checkout page says the basket is empty.
3. When I add to basket and refresh the page, the basket is empty.

I can reproduce this issue with a fresh install. It's obviously a browser issue, but I don't know if google made a new rule that invalidates the way cookies are currently being set? Chrome version 56.0.2924.87

I am running this locally using vagrant and virtualbox and am clearing the cache through the browser as well as through the administration management page, before I test to see if the basket works. I have php5.6 installed

- I tried following the answer here: https://forums.cubecart.com/topic/47534-resolved-sale-items-add-basket-not-working/
  - but the structure has changed significantly since that post, so it's difficult to know how I'm supposed to apply the hack.

- I also tried: https://forums.cubecart.com/topic/24070-add-to-basket-cart-empty-solution/
but chrome looks ok with the setting "Allow local data to be set (recommended)", for cookies, and I'm allowing javascript to run. 
  - The only setting that was off was the key generation. It was set to "Do not allow any site to use key generation in forms (recommended)". I changed this to allow all and tried again. I still had the same issue

I just wanted to bring it to your attention: 

- It is broken on all downloadable v6 versions well as the master branch from github.
- Version 5.2.17 works with no extra local browser changes for me.

**Comment by abrookbanks** [comment]
Please contact technical support if you require any assistance with this. It is not caused by a bug in CubeCart.
