### ISSUE TITLE
Unable to upgrade plugin on live site with SSL

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1545]
Getting server error 500 when I paste the token into the thunderbolt section and hit save:
```
ipaddress [Timestamp] "POST /admin.php?_g=plugins HTTP/1.1" 500 20 "https://sitename.com/admin.php?_g=plugins" "Browser info"
```
The upgrade process works flawlessly in my offline (non-SSL) test site running the same code, and worked on the live (SSL) site in at least 6.1.0 if not 6.1.2.

I haven't run into any other issues using CubeCart's admin control panel using the latest code from GitHub.

**Comment by abrookbanks** [comment]
We moved to a new server yesterday so it might be related.. I'll check.

**Comment by abrookbanks** [comment]
I think this was just unlucky timing. Maybe a fault our end with a server update or something as I can't reproduce this.

**Comment by briansandall** [comment]
I'm still getting this error today. I'll contact my hosting provider and see what they have to say about it.

**Comment by abrookbanks** [comment]
They may have cached the old IP address. If you can edit the hosts file to 45.32.179.53 it should work or maybe flush the DNS.

**Comment by briansandall** [comment]
Just got off the phone with my host - they don't cache IPs on shared hosting and pinging cubecart.com returned the above IP.

**Comment by abrookbanks** [comment]
Hmm. Does both www.cubecart.com and cubecart.com resolve to that IP? I think the code uses www.cubecart.com.

**Comment by abrookbanks** [comment]
Looks correct to me. I wonder if the server accepts the SSL cert if the ip address has changed.

**Comment by abrookbanks** [comment]
So maybest testing this may give clues.. 

> curl https://www.cubecart.com

**Comment by briansandall** [comment]
That return the HTML contents of the CubeCart website. Strange that that works but I am unable to ping the site.

**Comment by abrookbanks** [comment]
Suggest everything works. Happy to take a look if you want to send server access via sales dept https://support.cubecart.com/Tickets/Submit

You have helped me out loads so more than happy to look into this for you.

**Comment by briansandall** [comment]
Thanks, Al. I think I'm going to let it sit for a couple weeks and see if it doesn't resolve itself, rather than taking up time you could better spend with your family or drinking beer or whatever you do to relax. ;)

If it's still an issue at that time and my hosting provider can't get it sorted, I may take you up on your offer. Cheers!

**Comment by abrookbanks** [comment]
Hard boozing is always the priority.

**Comment by briansandall** [comment]
It's been scientifically proven to exponentially increase a coder's productivity... =D
