### ISSUE TITLE
Solution to AIOS submitting too many forms variables

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1550]
Brian has posted code to change AIOS so that each tab is submitted as a separate form

https://forums.cubecart.com/topic/52009-all-in-one-shipping-module-can-lose-data-a-hack/

I propose adopting this approach for this module as standard and considering it in other areas where similar problems occur.

What would also be great would be a check to detect if changes are made on that tab that have not been saved if a user is about to navigate away ?

**Comment by briansandall** [comment]
I much prefer the solution suggested in #1500 with respect to CubeCart itself, and it could possibly also work well for AIOS.

**Comment by havenswift-hosting** [comment]
I agree that https://github.com/cubecart/v6/issues/1500 is a better solution but this is a solution that would help immediately
