### ISSUE TITLE
Feature Request - Store contact form submissions

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1553]
It would be nice to capture these and store them in the DB, making it possible to review them from the admin area. There are occasions where mails don't arrive, in which case you may lose a lead or annoy a potential customer.

**Comment by Noodleyman** [comment]
Does the closure without comment mean this is no longer being considered for a future release?

**Comment by abrookbanks** [comment]
No it means it's still to be considered for a future release and has no milestone.

**Comment by abrookbanks** [comment]
Having so many issues open didn't give a good first impression. Vast majority are feature requests.
