### ISSUE TITLE
Specification Tab Query

### ISSUE THREAD

**Issue by Rob-Tea** [cubecart/v6#156]
I'm curious on how the specifications tab on the default theme can be populated.  The picture below shows an example on my test site.  Is this the maximum amount of data that will ever appear here?.

![current spec tab](https://cloud.githubusercontent.com/assets/10531097/5976428/78aac94a-a885-11e4-8895-1a6c8315b48e.png)

Ideally i was hoping in the admin side to define product details, an example from another website attached.

![ideal spec sheet](https://cloud.githubusercontent.com/assets/10531097/5976376/f190791e-a884-11e4-90d2-0ceff67ac3ff.png)

I was thinking that this would be good for many applications, .e.g. "Voltage:", "240v", "Size:","320 x 350mm".  I think they would just need to be dumb text fields and not calculated based on any product options selected.

**Comment by hairydogltd** [comment]
Unless there is a plan to be able to filter on the contents of these specifications, I'd suggest just putting the content into a div with a specific ID. That way it can be displayed as a tab or otherwise. I'd suggest something like how I've done it on led-lighthouse.co.uk - there are tabs for description, spec, reviews and extra images. I think that's done with a Zen Cart addon, but it was a long time ago - I forget the details.

**Comment by bhsmither** [comment]
The main.php template file has $BODY_JS and $JS_SCRIPTS arrays that a plugin can populate. Load the following into $BODY_JS:
```
jQuery(document).ready(function() {
  $('<dd><a href="#test_tab">Testing</a></dd>').appendTo('.tabs');
});
```
This will add a **Testing** tab to the sequence. The same technique can add a `<div class="content">` into the `<div class="tabs-content">` block.

**Comment by abrookbanks** [comment]
These specs come from the default fields in the order inventory table. It would be nice for extra functionality to add extra specification. I see that Brian has posted a possible workaround that seems good. Maybe a plugin can be developed to add this functionality or extra functionality for the 6.1 milestone.

**Comment by NaturalSigns** [comment]
Thanks for all the input, i will have a play (i'm a coding novice [for websites], but slowly learning).

**Comment by abrookbanks** [comment]
Good luck with it.

**Comment by bhsmither** [comment]
I may have mentioned that I love Chuggy's "Additional Product Fields" mod. It needs a bit of tidying up, however.

**Comment by NaturalSigns** [comment]
Thanks, I've not visited Chuggy's site before, great tip its exactly what i wanted!

**Comment by hairydogltd** [comment]
There is a bit of an "abandoned" feel about the Chuggy site, and I'm never happy paying money to someone with no address details available. Have you successfully bought from there?

**Comment by NaturalSigns** [comment]
Good point, I think it might be abandoned.   I did use the contact form to request information on whether it would work on cc6, (i was also interested interested in the module "Product Specific Shipping [for cc4]").  As yet no response from 'Chuggy' so its not looking promising.
