### ISSUE TITLE
Add filesize to images / filemanager

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1561]
It would be really useful to have an additional column showing the image file size and also have the ability to sort by this (highest / lowest) and then also add sorting back to the filename column

**Comment by abrookbanks** [comment]
![screen shot 2017-03-21 at 16 20 53](https://cloud.githubusercontent.com/assets/4520803/24157811/624dcd0c-0e52-11e7-94f8-0b59bb110941.png)

Sorting to come another time..

**Comment by havenswift-hosting** [comment]
That is a great start and thanks for adding so quickly - did you want to leave it open for the sorting or to create a new issue ?
