### ISSUE TITLE
LIKE and RLIKE Signature Params

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1563]
In `Catalogue->searchCatalogue()`:
At lines 1717, 1758, 1771, 1804, 1808, 1820, 1822, 1837, and 1851 all should all force `$search_mode` to lowercase.

Issue #1330 makes mention of this.

**Comment by abrookbanks** [comment]
Probably better to convert all to lowercase instead of repeated strtolower function calls.

**Comment by abrookbanks** [comment]
See https://github.com/cubecart/v6/commit/953b4f259ff10c53cf17dba3b039985e3f5540e3 (wrong issue ID on commit).

**Comment by briansandall** [comment]
Another option to avoid any potential case sensitivity issues would have been (and still could be) to use `strcasecmp` instead of `==` for the comparison check.
