### ISSUE TITLE
Preg_Split Can Result in Empty Array Elements

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1564]
In Catalogue->searchCatalogue(), near lines 1811 to 1815 (according to code in the Github), the use of `preg_split()` on commas and spaces may result in empty array elements if the search term has leading, trailing, or neighboring occurrences of the delimiter.

This will frustrate the query.

Suggest:
```
$searchwords = preg_split( '/[\s,]+/', $GLOBALS['db']->sqlSafe($search_data['keywords']), null, PREG_SPLIT_NO_EMPTY);
```

**Comment by bhsmither** [comment]
Maybe not that because '0' may be a wanted search term.

So, suggest:
```
if (!empty($search_data['keywords'])) {
  $searchwords = preg_split( '/[\s,]+/', $GLOBALS['db']->sqlSafe($search_data['keywords']));
  foreach ($searchwords as $word) {
    if(empty($word) && !is_numeric($word)) continue;
    $searchArray[] = $word;
  }
```

**Comment by abrookbanks** [comment]
Thanks for this Brian. Why continue on a number? A product code for example could just be numeric.

**Comment by bhsmither** [comment]
Originally I suggested just being empty. (Also, see CubeCart class, line 760, uses `explode()` but do not know if it can create empty elements.)

If it is empty, it could be 0, '0', or '0.0'.

Only if it is also NOT numeric, then continue.

**Comment by abrookbanks** [comment]
Gotcha. Thanks.
