### ISSUE TITLE
All errors and warnings should be logged in debug mode

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1568]
As above. They are not logged otherwise.

**Comment by Dirty-Butter** [comment]
WOW! Lots of errors in the logs now. Do they MEAN anything? Everything is working correctly AFAIK.

**Comment by abrookbanks** [comment]
Warnings and notices are not important 99.9% of the time. CubeCart uses trigger_error which won't be logged until debug mode is on now.

**Comment by abrookbanks** [comment]
Essentially this could be useful.

**Comment by Dirty-Butter** [comment]
Would it be possible to toggle viewing the Notices vs Warnings? - kind of like the Customers/Bots choice?

**Comment by abrookbanks** [comment]
Yes that would be a useful improvement.

**Comment by Dirty-Butter** [comment]
I'm on today's commit on our test site. Is this something that needs to be addressed as a problem with my install or a problem in the code?
`````
Today, 04/07/2017 3:47PM 	[Warning] /home/butter01/public_html/XXX/classes/cache/cache.class.php:162 - unlink(/home/butter01/public_html/XXX/cache/skin) [function.unlink.php]: Is a directory
`````

**Comment by abrookbanks** [comment]
Hi Rosemary,

I don't think that's a problem. :)

**Comment by Dirty-Butter** [comment]
ok :)
