### ISSUE TITLE
Improvement Request: Cleanup hooks when deleting modules

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1569]
When deleting a module via the admin area, the deletion process does not disable/clean up the hooks. Once the module is removed the cart still tries to call the hooks and it throws errors to the server error logs. 

the deletion process should be improved to clean up hooks when deleted, or for modules which are missing, perhaps as part of the process of calling a hook. I think adding a check "does this file exist" in a hook execution. If it can't find the file, disable the hook.

**Comment by abrookbanks** [comment]
Agreed. This is important.

**Comment by abrookbanks** [comment]
From my testing hooks are deleted at the same time the extension is deleted.

**Comment by havenswift-hosting** [comment]
I think the problem comes when people manual delete an extension directory rather than doing it through admin CP so the second part of Alec's request does still apply

**Comment by abrookbanks** [comment]
I can't do much about that really.

**Comment by abrookbanks** [comment]
All CubeCart does it make a PHP notice that it's missing after its not found. I don't think deleting or disabling the hook is a good idea. It could cause development headaches. Also if the store was live and the module was being updated with a page load it could have adverse effects. Not that anyone upgrades a store whilst live obviously. :)

I think this should stay as it is.
