### ISSUE TITLE
Missing Argument

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#157]
In /admin/sources/maintenance.index.inc.php, in _every_ version of CC5 and CC6, (lines 289 and 290 in CC600b4):
```
	$message = preg_match('/\_error_log$/', $_GET['delete']) ? $lang['filemanager']['notify_file_delete'] : $lang['maintain']['backup_deleted'];
	$GLOBALS['main']->setACPWarning();
```
`$message` is not supplied as the argument to `setACPWarning()`.

**Comment by abrookbanks** [comment]
Thank you!
