### ISSUE TITLE
Resend email feature required from email log

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1571]

**Comment by abrookbanks** [comment]
![screen shot 2017-04-04 at 13 36 05](https://cloud.githubusercontent.com/assets/4520803/24656788/ba906c6a-193b-11e7-91c6-185d11743766.png)

**Comment by Dirty-Butter** [comment]
VERY nice! Long since needed. The only way to make it better would be some way to be able to edit just this instance of the email template, without messing up the normal one.

**Comment by abrookbanks** [comment]
Yup. I think that would be good...
