### ISSUE TITLE
Cannot Delete Customer Groups

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#1572]
When click Delete (Bin) to remove a Customer Group with NO Customers (No Customers are assigned this Group).  It shows it remove Group but when you refresh screen, the Group is not removed,  This needs fixing

When click Delete (Bin) to remove a Customer Group with Customers (Customers assigned this Group).  It shows it remove Group but when you refresh screen, the Group is not removed,  Although it does not remove Group, it should not show that it removed Group but rather give an error message something like this "Customers Exist for Customer Group, move Customers to another Group before removing"

**Comment by abrookbanks** [comment]
Click save after delete.
