### ISSUE TITLE
Feature Request - Checkbox in Image Filemanager to delete image

### ISSUE THREAD

**Issue by claudia39** [cubecart/v6#1574]
I am so sorry if I am adding this feature request incorrectly - I've not done this before.  Also sorry if it has been addressed before.  Anyway, in the image filemanager can a checkbox be added next to each image and when you check one or more you can click on a delete button and the selected images are deleted?
Thanks, Claudia

**Comment by Dirty-Butter** [comment]
You are talking about the Filemanager tab in the Product Listing, right? There has been discussion of some way to get rid of images that are not in use - but I don't remember a request for this specifically. And I'd like this, too! My image folder has lots of images I'm no longer using that would be easier to delete from the Product listing phase when I add new photos of a toy for whatever reason.

**Comment by claudia39** [comment]
Actually I'm talking about the Filemanager/Images menu location in admin, but it would be nice to have it in both locations. I'm always afraid I'll accidentally delete the wrong image when a product sells.

**Comment by Dirty-Butter** [comment]
Hmmm I have a trashcan icon on each image in the admin Filemanager folder. It's there in the CC demo store Filemanager as well. It's way over on the right hand side.

**Comment by claudia39** [comment]
Yes, I know there is a trashcan icon. But if you have several photos you have to delete it can be time consuming to go back and delete each one at a time.  Plus the risk of accidentally deleting the wrong photo.

**Comment by Dirty-Butter** [comment]
Yep - re-read your original post.
