### ISSUE TITLE
CSRF protection to front end and CSRF protection on GET to admin control panel

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1576]
As above. More details to follow....

**Comment by Dirty-Butter** [comment]
Not sure if this is related:
On Mailing List - checkbox allows an email address to be deleted, but the trashcan icon delete causes the CSRF no matter if I refresh before attempting. I tried going back to 6.1.5 for customers.subscribers.php and customers.subscribers.inc.php, but still CSRF for delete icon.

**Comment by abrookbanks** [comment]
Certainly a few issues I missed the AJAX functions of the email validation..
