### ISSUE TITLE
Update foundation to latest version of framework

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1578]
Would be quite handy to have the latest versions of the framework available as it offers some really nice, useful features.

Can it be updated in the bundled default theme ?

**Comment by abrookbanks** [comment]
Foundation 6?

**Comment by Noodleyman** [comment]
Yes, 6.  from the version info I pulled from the latest theme it's still using 5.

in 6 you can make better use of dynamic size/screen info using JS. really handy :)

**Comment by abrookbanks** [comment]
OK cool. I'm not sure its very simple to upgrade though... looking into it.

**Comment by abrookbanks** [comment]
.. I don't think its a very simple transition. 

Maybe we should make a totally new skin. I've had some brutal feedback about how poor the default theme is. 

```
I mean come'n, it looks shit 
```

```
for god sake, make it look modern
``` 

LOL

**Comment by havenswift-hosting** [comment]
I think one of the main issues with CubeCart not being more widely is the lack of good skins so one (or lots) more good skins would be great.

However, there are a lot of third party skins based on current Foundation and if they become outdated / obsolete overnight then the situation will become worse not better

**Comment by abrookbanks** [comment]
Maybe a bootstrap one to please developers who are more on board with that. 

I can't imagine the conversion is that hard as the principals are the same.

**Comment by Noodleyman** [comment]
If we had a room full of monkeys with computers, eventually they would randomly write the code for the worlds best theme which everybody would love.. :), if tenacious D did themes, this would be it. 

The problem is themes are subjective to each store/person/business, Skins take a lot of time to develop, so it's understandable there isn't a large number of them available.

**Comment by abrookbanks** [comment]
Haha yeah true.

**Comment by abrookbanks** [comment]
On that note I'm playing the best song in the world. Thanks Spotify.

**Comment by briansandall** [comment]
That song is the best - I love it.

As for updating Foundation, even if custom skins don't make the switch, changing the Foundation skin shouldn't affect them at all since each skin should contain everything it needs within its own folder, no? So any CSS, JS, element classes or IDs that the skin relies on won't change until such time as the skin creator decides to also update to the newer Foundation.

I'm not saying it won't (eventually) be rough on people that have custom skins, but it seems like it _should_ be able to be safely updated without (immediately) affecting any third party skins.

That said, I think it might be better to hold off if possible until the next major CubeCart release.

**Comment by havenswift-hosting** [comment]
Yes custom skins do contain everything they need and wont be directly affected except forever being labelled V1 old skins !  I am torn because the idea of a bootstrap based one to possibly draw in a new set of people is great and in the end any new skin for CubeCart is desperately needed

**Comment by briansandall** [comment]
I wonder what types of skins people would like to see? Are there any websites that have a 'modern' skin that would be a good template for CubeCart to strive for?

One thing I've always thought would be a great addition to the skin's functionality would be a way to _filter_ search results, like on Amazon or many other online stores. I'm not sure how feasible it would be to populate filters based on the various options available from a potentially large number of loosely-related items, but it sure would be awesome!

**Comment by Noodleyman** [comment]
filterint search results is a module I am close to releasing.. it's related to the SEO thread on the forum ;)

**Comment by abrookbanks** [comment]
I think we need a slick clean skin with admin configurable interface for colours and maybe even to enable / disable features like mailing list.

**Comment by abrookbanks** [comment]
> filtering search results is a module I am close to releasing.. it's related to the SEO thread on the forum ;)

Cool!! :)

**Comment by briansandall** [comment]
Any examples of sites with a 'slick clean skin'?

I consider the current CubeCart Foundation skin to be pretty 'clean', and it looks a lot nicer once you throw a non-white background on it and extend the top nav section to fit the whole screen.

**Comment by briansandall** [comment]
> filtering search results is a module I am close to releasing.. it's related to the SEO thread on the forum ;)
Nice - I'd sure love to see it as part of core, though. ;)

**Comment by abrookbanks** [comment]
> I consider the current CubeCart Foundation skin to be pretty 'clean'

I do too but on occasions I've had some pretty brutal feedback.

**Comment by briansandall** [comment]
> I do too but on occasions I've had some pretty brutal feedback.

Welcome to both being a content creator and the internet ;)

It's always easier to criticize than to produce something.

**Comment by abrookbanks** [comment]
Haha so true.

**Comment by havenswift-hosting** [comment]
> I think we need a slick clean skin with admin configurable interface for colours and maybe even to enable / disable features like mailing list

This is what I started to do for our Retail Therapy skin using our free skin configuration module - this doesnt yet do colours but many other functions can be toggled on / off.  It does make one skin so much more versatile.
