### ISSUE TITLE
Blueprint works on 6.0.0b3 but layout won't work on 6.0.0b4

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#158]
Could it be that the js bug fix that was supposed improve use of v5 skins is at fault?

This is an install with our live database, but stock install. Stock Foundation works as expected.

![6 0 04b blueprint issue dirty butter plush animal shoppe 2015-01-31 15-58-06](https://cloud.githubusercontent.com/assets/6146505/5990196/cb62a302-a96a-11e4-900d-d744629d7cd1.jpeg)

**Comment by abrookbanks** [comment]
Hi Rosemary, I'd like to take a look at this if thats ok. Any chance you can send me FTP access? The sales dept is secure; https://support.cubecart.com/index.php?/Tickets/Submit

**Comment by Dirty-Butter** [comment]
I’d appreciate that!

 

Host address – dirtybutter.com

Username – buttero1

Password – 2wx3EC4rv5TB

**Comment by abrookbanks** [comment]
I removed your login from this page for security reasons. I'm recommend changing the password ASAP.

**Comment by abrookbanks** [comment]
Hi Rosemary, please can you send FTP access via our sales dept following this line?
https://support.cubecart.com/index.php?/Tickets/Submit 

I'll take a look for you then.

**Comment by Dirty-Butter** [comment]
Sorry I didn't read your email carefully enough, and I thought you were saying the return email was secure. PW has been changed.

**Comment by Dirty-Butter** [comment]
Did you make any changes? Blueprint skin is working today on 6.0.04b, but it sure wouldn't yesterday!!

**Comment by abrookbanks** [comment]
I haven't changed a thing. Makes me wonder if it's over caching.

**Comment by Dirty-Butter** [comment]
I had manually emptied cache when I had problems. I had tried everything I could think of, but nothing worked yesterday. Oh well, thanks for your willingness to help. If I have trouble with this in the future I'll let you know.
