### ISSUE TITLE
Radio Button Products Options Sometimes Not Displayed In Store

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1581]
Clean 6.1.6 store, no code edits or plugins or code hooks, not modified foundation skin with:
- 3 drop down product options
- 2 radio button product options
- 2 text input product options
- 2 text area product options

In the following scenarios no radio button product options will be displayed on the product page in the store.
For the last scenario, product options are also displayed in the incorrect order, without the assigned radio button product options.

Test Optioned Product 05 - Test optioned product, everything, assigned manually.
Admin:
![image](https://cloud.githubusercontent.com/assets/6945093/25145446/38807454-243f-11e7-8d48-895e037e8bf3.png)
Store:
<image>
![image](https://cloud.githubusercontent.com/assets/6945093/25145464/43b0be56-243f-11e7-894b-b0c940d99c2e.png)
http://www.cubecartservices.biz/test-category-01/test-optioned-product-05.html
- no radio options displayed

Test Optioned Product 06 - Test optioned product, everything, assigned using option set.
Admin:
![image](https://cloud.githubusercontent.com/assets/6945093/25145479/541ee6dc-243f-11e7-8bbd-263d9ab0edd8.png)
Store:
![image](https://cloud.githubusercontent.com/assets/6945093/25145491/5ae1b440-243f-11e7-898a-986161afe2ed.png)
http://www.cubecartservices.biz/test-category-01/test-optioned-product-06.html
- no radio options displayed

Test Optioned Product 09 - Test optioned product, 2 drop down + 2 radio + 2 text input + 2 text area product options, assigned manually.
Admin:
![image](https://cloud.githubusercontent.com/assets/6945093/25145517/689f031c-243f-11e7-9c4a-3d57a83935d8.png)
Store:
![image](https://cloud.githubusercontent.com/assets/6945093/25145527/70dd0d62-243f-11e7-807c-5994aaa995a7.png)
http://www.cubecartservices.biz/test-category-01/test-optioned-product-09.html
- no radio options displayed

Test Optioned Product 11 - Test optioned product, 2 drop down + 2 radio + 1 text input + 1 text area product options, assigned manually.
Admin:
![image](https://cloud.githubusercontent.com/assets/6945093/25145550/810bdc54-243f-11e7-9a48-70010123a4f2.png)
Store:
![image](https://cloud.githubusercontent.com/assets/6945093/25145561/87bfb9c6-243f-11e7-9f08-e56a39c248b6.png)
http://www.cubecartservices.biz/test-category-01/test-optioned-product-11.html
- no radio options displayed

Test Optioned Product 12 - Test optioned product, 1 drop down + 1 radio + 2 text input + 2 text area product options, assigned manually.
Admin:
![image](https://cloud.githubusercontent.com/assets/6945093/25145639/a143de68-243f-11e7-9dfc-c9fc6e11efdd.png)
Store:
![image](https://cloud.githubusercontent.com/assets/6945093/25145605/9abe4312-243f-11e7-9163-c9645b0d13ec.png)
http://www.cubecartservices.biz/test-category-01/test-optioned-product-08.html
- no radio options displayed + options displayed in incorrect order

Feel free to look at the other 'Test Optioned' products to see examples of where they do work correctly.

**Comment by abrookbanks** [comment]
Thanks for such a detailed explanation sire.
