### ISSUE TITLE
Product Options Option Sets Tab, Nothing Selected, Options Set Values Displayed

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1582]
Clean 6.1.6 store, no code edits or plugins or code hooks.

After setting up various product option groups + attributes, click the option sets tab.
Go ahead with creating an option set containing whatever options you want.

Now click the 'Product Options' link in admin navigation.
Then click the options sets tab.

Nothing is set as selected in the drop down, yet the selections made creating the option set above are displayed.
i.e.
![image](https://cloud.githubusercontent.com/assets/6945093/25145769/defb2b94-243f-11e7-9211-ed52b7e0fdf8.png)

But if you select the option set from the drop down, then select the 'Please Select' option from the drop down, page is displayed correctly.

**Comment by abrookbanks** [comment]
Thanks so much for this Daren.
