### ISSUE TITLE
URL Select Javascript

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1583]
In previous CC6 versions there was this:
```
    $('.url_select').bind('change', function () {
        var url = $(this).value(); // get selected value
        if (url) { // require a URL
            window.location = url; // redirect
        }
        return false;
    });
```
in the '/admin/skins/default/js/admin.js' file.

That code needed to be altered to this:
```    
    $('.url_select').bind('change', function () {
        var url = $(this).val(); // get selected value
        if (url) { // require a URL
            window.location = url; // redirect
        }
        return false;
    });
```
otherwise it would not work.

With the 6.1.6 release:
- the incorrect code has been removed from the '/admin/skins/default/js/admin.js' file
- the correct code has been added to the '/skins/foundation/js/2.cubecart.js' file instead

However, as a result the 'url_select' functionality no longer works on the admin side of a store.

**Comment by abrookbanks** [comment]
From what I found it was removed as it was no longer used. Was I wrong? Can you tell me where this is used?

**Comment by abrookbanks** [comment]
The code wasn't added to /skins/foundation/js/2.cubecart.js as it has been there prior to 6.1.6.

The code was removed from /admin/skins/default/js/admin.js as it is no longer used. 
See: https://github.com/cubecart/v6/commit/a1a4487b89c573439d54dac948e026f0b3a5a7c8
