### ISSUE TITLE
CSRF Alert Attempting To Delete Image

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1584]
Clean 6.1.6 store, no code edits or plugins or code hooks.

Click 'Images' in the 'File Manager' section in admin navigation.
Locate the image you want to delete.
Click the delete icon.
Click ok for the confirm prompt.

You will get this:
![image](https://cloud.githubusercontent.com/assets/6945093/25145832/1416ca40-2440-11e7-8a6d-80cec8e94154.png)
and be left at a URL like this:
admin_Abcxyz.php?_g=filemanager&delete=1&token=6b972e4a127d75552a7f024ad9cbc9fa

**Comment by briansandall** [comment]
I get the same thing trying to delete a customer.

**Comment by abrookbanks** [comment]
So frustrating to get an error like this after having felt like this had been tested thoroughly.

**Comment by abrookbanks** [comment]
Thanks for this fixed now.

**Comment by Dirty-Butter** [comment]
That fixed not being able to use the delete icon for Customers and  Products, too!

**Comment by abrookbanks** [comment]
That's right. :)

I'm content.

**Comment by briansandall** [comment]
6.1.7 is spot on - thanks Al!

**Comment by abrookbanks** [comment]
Fab!
