### ISSUE TITLE
Admin Edit Product, Upload and Assign Image Only, 'No Product Changes Were Made' Alert Displayed

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1585]
Clean 6.1.6 store, no code edits or plugins or code hooks.

Click 'Products' in the 'Inventory' section in admin navigation.
Locate a product that currently does not have an image assigned.
Click the edit link.
Click the images tab.
Upload an image.
Click Save & Reload button.

You will receive the 'No Product Changes Were Made' alert.

**Comment by abrookbanks** [comment]
No changes are made as it is assigned on upload.
