### ISSUE TITLE
Traditional Pagination Per Page Bug

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1586]
Clean 6.1.6 store, no code edits or plugins or code hooks.
Altered the '/skins/foundation/templates/content.category.php' file so traditional pagination is used.

Select a category that contains more than 12 products.
Click the page 2 link.
Select 24 from the per page drop down.

Doing this will result in the 'No products found.' message being displayed, with no products.

**Comment by Dirty-Butter** [comment]
Another issue with Traditional Pagination with 6.1.7????
https://forums.cubecart.com/topic/52522-traditional-pagination-in-foundation-skin/

**Comment by briansandall** [comment]
Specifically, this can only happen when you have a number of products in the displayed category between the lowest and highest number displayed per page, AND you are on the second (which is the last) page.

So if you have > 12 but <= 24 products and you are viewing the second page (products 13-24) when you switch to show 24 per page, the URL still tries to access page 2 even though there are no products to display on that page - all of them are now on the first page.

**Comment by abrookbanks** [comment]
Fixed with https://github.com/cubecart/v6/pull/1620

**Comment by SemperFiWS** [comment]
Thank you to Brian and Al for getting this fixed.

**Comment by abrookbanks** [comment]
Thank Brain. He was the man here. :)

**Comment by SemperFiWS** [comment]
A well deserved thanks to Brain too then! 🥇
