### ISSUE TITLE
Google ReCaptcha terms hidden behind other page elements

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1587]
Related to #1546 - should be easily fixable by increasing the z-index of the terms and/or altering its position so it does not overlap with the `Top` button.
![cc_recaptcha](https://cloud.githubusercontent.com/assets/14335170/25155121/581ec280-2448-11e7-9ffa-3e6507af06af.jpg)

**Comment by abrookbanks** [comment]
I think this is more of a bug with Googles CSS.

The CSS for Google is remote:
https://www.gstatic.com/recaptcha/api2/r20170411114922/styles__ltr.css

I expect Google will resolve this over time.

**Comment by abrookbanks** [comment]
Thanks, I was able to control it.

**Comment by abrookbanks** [comment]
After.. 
![screen shot 2017-04-19 at 09 53 55](https://cloud.githubusercontent.com/assets/4520803/25171546/2342b118-24e6-11e7-9eca-00d951894a6a.png)
