### ISSUE TITLE
[Notice] settings.errorlog.inc.php:61 - Undefined variable: smarty_data

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1588]
This error is logged once each time the admin control panel page loads.

Granted, this is only when debugging is enabled, which also leads to a lot of other PHP notices and such getting logged. Perhaps it's not a high priority for live sites, but it does lead to error log spam when working with test sites.

**Comment by abrookbanks** [comment]
CubeCart hasn't been coded to strict standards. That will be one of hundreds if not thousands.

**Comment by briansandall** [comment]
That's unfortunate :(
