### ISSUE TITLE
Unable to register account

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1590]
Using the 6.1.6 release, clicking the `Register` button after filling out the form does not submit the form.

Inspecting the HTML shows that the 'button' is actually a form input:
```
<input class="g-recaptcha button" name="register" value="Register" type="submit">
```
The test store does not have Recaptcha enabled and is using 100% stock code and skin.

I tried enabling Invisible Recaptcha on my live site (yes, with new credentials from Google) and registering an account; the `Register` button exhibited erratic behavior. Sometimes it would do nothing, other times (even without refreshing the page) Google's visible Recaptcha challenge would pop up.

After completing the challenge successfully, the dialog box disappeared and I was left sitting on the same page, account still unregistered.

**Comment by briansandall** [comment]
This also affects the checkout process for customers that do not yet have an account.

**Comment by abrookbanks** [comment]
I can't reproduce this..

**Comment by abrookbanks** [comment]
Hmm I really can't reproduce this. Have your cleared your browser cache? CubeCart needs a new CSRF session token after the email is validated. If the browser is caching old JS it won't receive it and this behaviour would be expected.

**Comment by briansandall** [comment]
Yes, I've tried clearing the browser cache, using different browsers, 3 different stores (unmodified fork, local test site, live site), all with the same result.

Also note that if a customer has ever visited your site but not registered an account, they will also experience this problem and most likely have no idea that they need to clear the browser cache, much less how to do it.

**Comment by abrookbanks** [comment]
Well they shouldn't need to clear the browser cache as I think each version appends a random string to the JS to clear the cache for that version. Maybe that's just on the admin side. 

I've put all upgrade for customers on the support plan on hold until I get to the bottom of this. 

Are there any of these stores I can look at privately?

**Comment by abrookbanks** [comment]
Are there any JS errors in the console?

**Comment by briansandall** [comment]
Yes, actually. I wonder if anyone else is experiencing this same problem?
```
Uncaught TypeError: Cannot read property 'sticky_class' of undefined
    at Object.is_sticky (1.foundation.min.js:5520)
    at HTMLElement.<anonymous> (1.foundation.min.js:5781)
    at Function.each (jquery.js:14)
    at _.fn.init.each (jquery.js:14)
    at Object.resize (1.foundation.min.js:5761)
    at 1.foundation.min.js:5701
    at 1.foundation.min.js:456
```

**Comment by briansandall** [comment]
Btw, that's from the unmodified CubeCart clone.

**Comment by briansandall** [comment]
Note that my own test store seems to be working correctly, but not the clone or my live site.

I did a comparison of the HTML on the register.html page and found that my test store has an extra form input for the token, whereas the other two stores do not.

It does sound very much like a caching issue... let me mess around with it a bit more and get back to you.

**Comment by briansandall** [comment]
Yes, but that token is missing for some reason on my unmodified clone as well as my live site.

**Comment by abrookbanks** [comment]
can you go to settings and just click save?

**Comment by briansandall** [comment]
Yes, the admin side works fine - it's the store front that is failing.

**Comment by briansandall** [comment]
Note however that I can log in as a customer and, once logged in, proceed with orders, so it's not all forms that are broken.

**Comment by abrookbanks** [comment]
Saving settings might update the config correctly. Can you try?

**Comment by briansandall** [comment]
It seems to have worked, actually. I just registered as a new customer on the cloned store, now I'm going to try the live one.

**Comment by abrookbanks** [comment]
hmmmmm ok..

**Comment by briansandall** [comment]
Well, I'm not having any luck personally, but there is a new customer account so clearly other people are able to register.

It's looking to be pretty clearly a caching issue, so I'll close this for now. Thanks for your time!

**Comment by abrookbanks** [comment]
I think it may be a mix of cache and setting that may only be written after settings are updated.

**Comment by abrookbanks** [comment]
OK so I will leave this closed now. Any merchant facing this issue will need to clear cache and save their store settings.

**Comment by havenswift-hosting** [comment]
Might be worthwhile adding this as a release note on your announcement on the forum ?

**Comment by abrookbanks** [comment]
I want to do better than that and automate it so no action is needed.. I'm working on this now...

**Comment by abrookbanks** [comment]
OK that commit should fix this. Keeping this closed and 6.1.7 tomorrow.

**Comment by briansandall** [comment]
Live site works now - turns out I had not uploaded the skin's config.xml file with the `<csrf>` tag in it, so of course the form token was missing... doh! (>.<)

**Comment by abrookbanks** [comment]
That would do it. I think my commits are good too keep too. 

Thanks for all your help.
