### ISSUE TITLE
Missing Permissions In Admin

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1592]
The following don't check permissions:
- ?_g=plugins
- ?_g=settings&node=requestlog
- ?_g=settings&node=errorlog
- ?_g=statistics&node=emaillog
and therefore can be accessed by admin(s) without 'super user' checked and no permissions assigned.

Plugins can probably be handled by:
Admin::getInstance()->permissions('settings', CC_PERM_READ, true);

Logs could also be handled by that or a new logs permissions section.

**Comment by SemperFiWS** [comment]
Following on from that, it would be beneficial if 'element.navigation.inc.php' only loaded links that the logged in administrator has permission to access.

**Comment by abrookbanks** [comment]
Thanks for this Daren. Maybe each permission should have a visibility setting. You could say that its nice to know that certain features are available and can therefore be requested for access. I also see why you may want them hidden.

**Comment by SemperFiWS** [comment]
Anytime Al.

I think you might be onto something regarding implementing a visibility setting.
Perhaps for a future version down the line?

In the meantime, were permission checks added to those locations I initially outlined?

**Comment by abrookbanks** [comment]
> were permission checks added to those locations I initially outlined

Yup. :)
