### ISSUE TITLE
Session handling cleanup by using the "stfu" operator (session_save_path and open_basedir issue)

### ISSUE THREAD

**Issue by Swiftyhu** [cubecart/v6#1596]
I had a few warning messages like this:

`[21-Apr-2017 11:38:42 UTC] PHP Warning:  file_exists() [<a href='http://docs.php.net/manual/en/function.file-exists.php'>function.file-exists.php</a>]: open_basedir restriction in effect. File(/var/lib/php/sessions) is not within the allowed path(s): (/usr/share/php/:/var/www/include/:/var/www/sites/somedomain/shop/:/var/www/upload-tmp/somedomain/) in /var/www/sites/somedomain/shop/classes/session.class.php on line 638
`

Clearly, the session save path is not in the open_basedir allowed paths. That is my problem and I already solved it.

When I looked on the specified file I saw this code:

```
		$save_path = session_save_path();
		if(!file_exists($save_path) || !is_writeable($save_path)) {	
```

I think this can be cleaned up a bit:
```
		if(!@is_writeable(session_save_path())) {	
```

Because:
1. The "stfu" operator "@" will silence any error.
2. We do not need to double check the same path.
3. The $save_path variable is not used anywere else.

**Comment by abrookbanks** [comment]
STFU operator it is. Thanks! :)
