### ISSUE TITLE
Foundation Mailing List Field Crashes Javascript

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1598]
Testing the demo store:
Entering an email address in the Mailing List field and clicking Subscribe:
"SyntaxError: JSON.parse: unexpected character at line 2 column 1 of the JSON data"
3.cubecart.validate.js, line 124, column 36

However, after forcing the browser to reload the page resources, it seemed to work.

**Comment by bhsmither** [comment]
See:
https://forums.cubecart.com/topic/52458-add-e-mail-to-mailing-list-doesnt-work-617/

**Comment by bhsmither** [comment]
Watching the POST when clicking the Subscribe button (at the footer), only the 'token' is getting sent.

Additionally, it seems that the javascript debugger only breaks when the new page comes in - not when the Subscribe button is clicked.

**Comment by abrookbanks** [comment]
Just needs to clear cache. This can be forced with mod_expires if necessary.

**Comment by briansandall** [comment]
I was able to reproduce this with a clean version of the latest code. The issue is the subscribe form in the footer of the home page and the validation JS attached to it do not play well together.

**Comment by briansandall** [comment]
Narrowed the source of this issue down to [this commit](https://github.com/cubecart/v6/commit/1fb1f830245943924b91bfcfb863ed89c901963a).
