### ISSUE TITLE
6.1.7 not getting payment received response from gateways

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1599]
See https://forums.cubecart.com/topic/52301-resolved-missing-transaction-logspaypal-ipn/?do=findComment&comment=226138 and comments after that point.

PayPal and WorldPay are specifically mentioned as CC not processing the payment received "message" from the gateway.

**Comment by abrookbanks** [comment]
Whooops.. I made another issues. 

See #1601
