### ISSUE TITLE
Replace file_get_contents with request class for reCaptcha

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1600]

**Comment by Dirty-Butter** [comment]
What problem does this solve? I've downgraded plushcatalog to an earlier commit for now, but will still be testing on our test site and dirtybutterestates.

**Comment by abrookbanks** [comment]
The request class allows for both cURL and fopen. file_get_contents just uses fopen which is often disabled in hosting accounts for remote URLs. Essentially this improves compatibility.

**Comment by Dirty-Butter** [comment]
Thanks
