### ISSUE TITLE
Add or Update Manufacturer Bug

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#1602]
On Save when Adding or Updating Manufacturer I get the following error message

"/sources/products/manufacturerstab_manufacturers.inc.php - not found."

It does not display the tabs for Manufacturers, however when I click Manufacturers in Main menu it displays the Manufacturers Tabs and also shows that the Manufacturer was added/updated.

As this would be a common issue as I have done nothing to a clean install v6.1.5 then upgraded to v6.1.7, and was in the stage of setting up my cart.  I searched to see if others had a similar issue and could not find any.  So I am stumped why I would have this issue.

I have had a look to see if file exists but cannot find it.

**Comment by Dirty-Butter** [comment]
I've just tested my 6.1.7 store and had no problem adding and then deleting a test manufacturer. Please, if you haven't already, post this issue on the forum, and maybe someone there can solve your problem.

**Comment by briansandall** [comment]
The admin.js file was modified but your browser may be caching the previous version.

Try clearing your browser cache or hard-refreshing the page (Ctrl-F5 in most browsers).

**Comment by sumwonlost** [comment]
Thanks for replies, I tried your suggestions but it did not work.  It was easier (as I have just started setting up) to download latest version and re-install again.  All works well now.
