### ISSUE TITLE
Bulk Print Invoice Needs Page Break

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1605]
See https://forums.cubecart.com/topic/52494-bulk-print-an-invoice-not-working-well-no-page-break/

Copying page-break code from #Footer section to #printLabel section in print.css makes this work:

`````
#printLabel {
    width: 80mm;
    height: 50mm;
    float: right;
    padding: 4mm;
    z-index: 100
}

.page-break {
    page-break-after: always
}

`````

**Comment by abrookbanks** [comment]
I can't reproduce this problem. 
[Invoices.pdf](https://github.com/cubecart/v6/files/983017/Invoices.pdf)

**Comment by abrookbanks** [comment]
I can't reproduce this on Windows 10 in IE 11 or on a Mac with Chrome. Happy to look again if needs be. There are three orders in the demo store.
