### ISSUE TITLE
Paypal Authorizations

### ISSUE THREAD

**Issue by tbonerocketeer** [cubecart/v6#1606]
Can we add the ability to use authorizations from paypal to the cubecart? I would like to have the status go to processing upon authorization notification from the ipn, and then an option to capture in cubecart would also be nice. This allows cost adjustments for the shipping corrections as is typical for orders, while removing refunds(PayPal got mad at me for excessive refunds). Once the capture button is pressed, the order status can change to complete.

**Comment by havenswift-hosting** [comment]
Ref https://forums.cubecart.com/topic/52426-authorizations-with-paypal/
