### ISSUE TITLE
Admin Stock Change in Processed order does not make Product stock change

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1607]
See https://forums.cubecart.com/topic/52505-changes-in-orders-dont-affect-to-inventory/#comment-226483

**Comment by abrookbanks** [comment]
From my testing it worked fine. I haven't tested with product option stock yet..

**Comment by abrookbanks** [comment]
Happy to reopen and investigate if you still think the issue persists. From my testing stock changed via admin when the stock change time was at "Processing". If it is at "Pending" then it has already changed and won't change again.

**Comment by Dirty-Butter** [comment]
I asked Sergei to test it again:

https://forums.cubecart.com/topic/52505-changes-in-orders-dont-affect-to-inventory/?do=findComment&comment=226771
