### ISSUE TITLE
Hooks to allow more control over which products get displayed

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1608]
Most places have a hook already but it occurs too late to affect the results of the database query, for example `_displayPopularProducts` has a hook near the end of the function.

Functions that I found which fetch products to display include:

- Catalogue::getCategoryProducts*

- Catalogue::searchCatalogue (already has a hook but it does not work when viewing sale items)

- Cubecart::displayHomePage*

- Gui::_displayPopularProducts*

- Gui::_displayRandomProduct (hook at beginning will work with minor modification)

- Gui::_displaySaleItems*

Those marked with an asterisk each have a hook at the end of the function which can be used for inefficient filtering of the results, but it would be much nicer to be able to filter the results directly with the database query by adding on to the WHERE clause.

**Comment by briansandall** [comment]
Let's examine each case in more detail.

1. `Catalogue::getCategoryProducts`, add a hook in `catalogue.class.php` after line 691:
```
// I considered adding the hook earlier to allow passing an array to outOfStockWhere, but 
// doing so ends up with a missing ' AND ' if given a non-empty array.
// Contrast to cubecart.class.php::95 where the $where variable is expected to be non-empty
// and thus an ' AND ' is included explicitly in the query.

// line 691:
$where2 = $this->outOfStockWhere(false, 'INV', true);
// add new hook here to allow modifying $where2
// example hook code: <?php $where2 .= ' AND INV.custom_field=1'; ?>
```

2. `Catalogue::searchCatalogue` already works except for the sale items view.
```
// One possibility is to use the $where array that was already potentially modified by the initial hook;
// Line 1880 plus one new line:
$whereString = 'IF (G.sale_price IS NULL, I.sale_price, G.sale_price) > 0'.$where2;
if (!empty($where)) { $whereString .= ' AND ' . implode(' AND ', $where); }

// Alternatively add a new hook explicitly for sale item 'category' view and include it prior to 
// building the final query string
```

3. `Cubecart::displayHomePage`, add a hook just before line 93:
```
$filters = array('I.status' => '1', 'I.latest' => '1');
// add new hook here to allow adding additional product filters
$where = $GLOBALS['catalogue']->outOfStockWhere($filters, 'I');
// original: $where = $GLOBALS['catalogue']->outOfStockWhere(array('I.status' => '1', 'I.latest' => '1'), 'I');
```

4. `Gui::_displayPopularProducts`, might need a hook for each case or perhaps rewrite the second query to use the same table alias so that a single hook can add `$filters` for `outOfStockWhere`; note that the first query would have to possibly include an ' AND ' prior to `$whereStr` in cases where it is non empty and does not already include a leading ' AND '.

5. `Gui::_displayRandomProduct`, a simple change allows the existing hook to modify product filters:
```
$filters = array('status' => '1', 'featured' => '1');
foreach ($GLOBALS['hooks']->load('class.gui.display_random_product_pre') as $hook) include $hook;

$where = $GLOBALS['catalogue']->outOfStockWhere($filters);
```

6. `Gui::_displaySaleItems`, add a hook after line 1290 so that an implementation might do the following:
```
$sale_sql_standard_where .= ' AND `custom_field`=1';
$sale_sql_group_where .= ' AND `I`.`custom_field`=1';
```

**Comment by briansandall** [comment]
For reference, this is related to this [forum post] (https://forums.cubecart.com/topic/52463-feature-request-hide-product-but-make-it-active/#comment-226494) requesting `hidden` products.

My own use case for hidden products is some of our manufacturers have minimum order requirements; of those, some allow orders below the minimum for a fee. I've set up the fees as products that can be added to the cart during checkout for orders that will need them, but I don't want these 'products' to show up anywhere on the site.

If we were to add a `hidden` field to the core `CubeCart_inventory` table, each of those 6 locations mentioned in the previous post would still need to be modified to exclude any such products.

Adding the suggested hooks would allow it to be done with no core modifications, and I believe other plugins might also find those hooks useful. Plus, most stores probably have no need for `hidden` products, so it may not make sense to add such a field to the core code.

**Comment by abrookbanks** [comment]
It would be nice if you could have some kind of identifier for each query and then get the where method of the database class to be able to overrule them somehow rather than a hook in each of those methods.

**Comment by abrookbanks** [comment]
So if you like an array of where overrides that is can pick up on if set.. hard to explain.

**Comment by briansandall** [comment]
My first thought was to put it in the `Catalogue::outOfStockWhere` function, but that ended up causing problems as that function is used elsewhere, e.g. in `getProductData`, so the filtered products became inaccessible.

It could be possible if we added an extra flag to the function parameters, for example:
```
public function outOfStockWhere($original = false, $label = false, $force = false, $include_hook = false) {
// original function contents
if ($include_hook) { /* include new hook */ }
// original return statement
}
```
I'd have to go back and review all the cases I listed above to see if this would cover them all; we might be able to get away with one hook, or we might need a few more.

**Comment by briansandall** [comment]
> So if you like an array of where overrides that is can pick up on if set.. hard to explain.

I see what you mean; each `where` clause would be included in an array, and then before the query is run we could include a hook allowing folks to manipulate the array. That could work - it would certainly be easy to add filters that way.

We would need a way to identify which function the `where` array was being called from.

One downside to doing it this way vs. adding individual hooks is that if I use that one hook and say I only want to modify the home page array, my hook still gets called for every other case.

Based on my non-thorough impressions of the hook system, adding a hook has very little overhead, much less than actually using the hook, so wouldn't it be more efficient to have the hook only called when needed?

**Comment by abrookbanks** [comment]
I like this a lot and I want to have a think about it in more detail at a later time. For now I'd like to close but take influence. Maybe CubeCart v7.
