### ISSUE TITLE
Apostrophe character escaped in product names, emails

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1609]
For product names, the apostrophe is escaped as an HTML character even before being stored in the database, so it ends up as `&#39;`.

Same happens with emails, both the sender (our company name has an apostrophe in it) and the contents.

Note that this did not happen previously, it has only been in the last couple of versions that I've noticed it.

**Comment by Dirty-Butter** [comment]
6.1.5 handles it correctly for me, although that may be because of some edits Bsmither provided. 6.1.7 does not.

**Comment by briansandall** [comment]
The search code isn't related to how products and email templates get stored in the database and those code tweaks should no longer be necessary after the fix for http redirect.

However, I notice now that the apostraphe is also being encoded when it appears in the URL, for example if a customer searches for `M&M's`, causing the search to fail. Apostraphes do not need to be encoded when part of a URL as they have no special meaning in that context.

I suspect some of the recent security fixes are to blame for this issue.

**Comment by briansandall** [comment]
Apostrophe is spelled with o's...

**Comment by briansandall** [comment]
This issue makes it impossible to search for certain products - for example if you have `M&M's` in your product description, it gets stored in the database as `M&amp;M&#39;s`. Still searching for where all of this data gets encoded - it should be stored exactly as entered and only escaped when displayed as HTML.

[This change](https://github.com/cubecart/v6/commit/4dbf7345db4e7e8b11021858fc88a2d83d8f11c5#diff-06e7ae0189a32233335a6e95cc1f0ff3L99) is responsible for the URL apostrophe getting encoded; I'm not sure what to do about that as I do not know the context for why this line was changed.

**Comment by briansandall** [comment]
Note that after re-adding `FILTER_FLAG_NO_ENCODE_QUOTES` and running the SQL query noted below, I am able to search for `M&M's` and retrieve a result.

SQL
```
UPDATE `CubeCart_inventory` SET name=REPLACE(REPLACE(name,'&amp;','&'),'&#39;','\''), description=REPLACE(REPLACE(description,'&amp;','&'),'&#39;','\''), description_short=REPLACE(REPLACE(description_short,'&amp;','&'),'&#39;','\'');
```

**Comment by briansandall** [comment]
Hm, it looks like product descriptions have _always_ been stored with special HTML characters (aside from the markup) encoded.

This does make a full text search involving any of these special characters fail, as is easily demonstrated by the M&M case if you remove the ampersand from the product name and product code but leave it in the description; searching `M&M` will turn up no results.

However, the issue with the apostrophe is definitely recent and as mentioned affects both product names (where they were previously unencoded - ampersands and the like are still unencoded) and emails.

**Comment by Dirty-Butter** [comment]
My search is not on description, but meta_keywords. The search terms are copied into the "Products found matching..."
This is latest commit (colors are bad to keep me from being confused about what site I'm on)

![m m](https://cloud.githubusercontent.com/assets/6146505/25631572/67a2af2a-2f36-11e7-8752-c6c9a1c2f4fb.png) 
url does have ....[keywords]=m%26m&_a=category....

![carter s](https://cloud.githubusercontent.com/assets/6146505/25631751/f377d6ba-2f36-11e7-80d2-566680307bb4.png)
url has ...search[keywords]=carter's+dog&_a=category...

**Comment by briansandall** [comment]
Exactly - the ampersand works fine after the httpredir fixes I made previously, _except_ that ampersands in the product descriptions are html-encoded. Your search for M&M works because ampersands are _not_ being encoded for the product name or seo fields. However, your store is an exception - searching against product descriptions is the norm.

Apostrophes in product name and the seo title, description and keywords are all encoded as well, which you will notice your search results query (due to your code tweaks): `Products found matching 'carter&#39;s dog'` - `&#39;` is an HTML-encoded apostrophe and you are only getting results back because the search term from the URL is also (erroneously) getting encoded. You can see this in the debug output.

The database should store data in its unaltered format, the search terms not be encoded before being sent to the database (though they must be properly escaped, not as HTML but as SQL), and the display can be escaped for HTML output.

Your code is doing that last part a second time which is why you get that funky search message, but that code is not actually addressing any of the root problems.

If you re-add the `FILTER_FLAG_NO_ENCODE_QUOTES` parameter I mentioned earlier to the `Sanitize::_safety` function implementation, then you don't need to use `stripslashes`:
```
$GLOBALS['catalogue']->setCategory('cat_name', sprintf($GLOBALS['language']->catalogue['notify_product_search'], htmlspecialchars($_REQUEST['search']['keywords'])));
```
That will display e.g. `Carter's` perfectly fine. ;)

**Comment by briansandall** [comment]
On the plus side, encoding any apostrophes in the search terms allows them to be searched against the ones stored in the database, since those are also encoded - this may be why the FILTER_FLAG was removed, or it may just be a side benefit.

If that's the case, then _any_ special character should be HTML-encoded prior to searching so that it can correctly match against the database. While I still believe this is the wrong approach, it may be the only option that doesn't involve tweaking ckeditor, in which case we would need to figure out a way to properly display the customer's search terms so they don't see e.g. `Search results for 'Carter&#39;s'`

**Comment by briansandall** [comment]
That also doesn't address the issue with emails.

**Comment by abrookbanks** [comment]
It's due to this commit: (Line 131 of classes/sanitize.class.php)
https://github.com/cubecart/v6/commit/4dbf7345db4e7e8b11021858fc88a2d83d8f11c5

**Comment by briansandall** [comment]
@abrookbanks Is that something we can change back, or was the filter flag removed for a security reason?

**Comment by claudia39** [comment]
I did a test order today, as I always do after upgrading, and I'm getting the &#39; in my emails, my store name is Claudia's Bargains, and in my search. Is there a reliable fix for this yet?
Thanks, Claudia

**Comment by abrookbanks** [comment]
I'll try to get a solution to this on Monday.

**Comment by claudia39** [comment]
Thank You!

**Comment by abrookbanks** [comment]
Closed by mistake. https://github.com/cubecart/v6/commit/3b50817fc42f276be53d223c79b7bcb41ed6bc7c fixed senders name in email.

**Comment by abrookbanks** [comment]
![screen shot 2017-05-08 at 09 23 59](https://cloud.githubusercontent.com/assets/4520803/25796091/1bad5c52-33d0-11e7-96dc-f936b0baba6c.png)

**Comment by abrookbanks** [comment]
I believe this issue is now resolved but I am keeping it open to perform more checks and to think if any other areas may be affected.

**Comment by abrookbanks** [comment]
I think we can close this for now. Please let me know if you disagree or if you still believe there are issues. All my tests pass.

**Comment by briansandall** [comment]
@abrookbanks Does this also resolve the issue with encoded apostrophes and other characters in emails?

**Comment by claudia39** [comment]
Just did a test order so I would receive an email.  Name is correct at Claudia's Bargains.  Also my search is working correctly now too.  Thank You!!!!

**Comment by briansandall** [comment]
Awesome! Thanks for testing it. ;)

**Comment by abrookbanks** [comment]
Fab! Thank for bearing with me and sorry for this problem.

**Comment by briansandall** [comment]
@abrookbanks This issue also affected the contents of emails.

For example, emails sent via the store's Contact page show up in my inbox with the contents encoded, e.g.:
```
Hello,

We&#39;d like to obtain an official price quote for...
```

**Comment by abrookbanks** [comment]
Ok cool. Let's reopen and look into that. Most email in CubeCart is HTML so I expect this affects  any plain text ones only.

**Comment by claudia39** [comment]
Sorry, I didn't check the contact of the emails.  Just did.  HTML sent for orders are fine - it's just the plain text

**Comment by abrookbanks** [comment]
That's what I thought. I'd say this is low priority as most email clients will default to HTML.

**Comment by briansandall** [comment]
Pardon my ignorance - is there a setting somewhere that controls that? I don't see how to switch between HTML and plain text on the contact form...

**Comment by abrookbanks** [comment]
No its a perfectly valid question. CubeCart sends mixed multi part email of both html and plain text. The client then decided to show html or text version.

**Comment by claudia39** [comment]
I have my preference in Outlook set to HTML.  I sent myself a message using the contact form from the store and got we&#39;d  instead of we'd.  The emails sent for orders were fine - not the contact form

**Comment by briansandall** [comment]
Ah, that makes sense. Yes, I'm using a plain-text email software, so that makes sense. Not much to do about that, then, as far as CubeCart is concerned.

I think that concludes this scene. ;)

**Comment by claudia39** [comment]
we &# 39; d not we'd.  Put the spaces to show what I got

**Comment by claudia39** [comment]
That fixed it!  Thanks

**Comment by briansandall** [comment]
And that, folks, is why Al is the CEO. ;)

**Comment by abrookbanks** [comment]
Chief executive orangutanagram. I'm available to hire for parties.

**Comment by abrookbanks** [comment]
I'll close this again now. Hopefully there are no other consequences.

**Comment by claudia39** [comment]
I did a test order today and got all the way to the PayPal login/payment page.  My store name shows as 
Claudia&#39;s Bargains in the dropdown menu to see more info on the order.  I don't know if it shows
like that anywhere else.

**Comment by claudia39** [comment]
I was looking at my page source on a product page and my title looks like this:
<title>Jumping Dolphins Electric Scented Oil Fragrance Warmer - Claudia&#39;s Bargains</title>

And see GitHub #1641: this was so far in the post it might not have been caught:
 "Also when I reentered the password, but not the email I get the error message:  &#;s  is not a correct email."

**Comment by claudia39** [comment]
<title>Jumping Dolphins Electric Scented Oil Fragrance Warmer - Claudia & # 39 ; s Bargains</title>
with no spaces.  Commenting here changed it.

**Comment by Dirty-Butter** [comment]
Put 5 of these ticks before and after code to keep it from being processed, so your source code shows:
`````
code
``````

**Comment by briansandall** [comment]
For inline code, you only need one tick on each side, e.g. `code`.
For blocks of code, you only need three:
```
Block of code.
```

**Comment by claudia39** [comment]
I don't understand this at all.  The title comes from admin/store settings/general ... Store Name.  What block of code are you talking about?

**Comment by Dirty-Butter** [comment]
Just an example of using the ticks to show a block of code in a GitHub Comment. There's a link bottom left just below this box that links you to an explanation of Styling with Markdown.

**Comment by claudia39** [comment]
Well what do you know!  Thank you
