### ISSUE TITLE
Suggestion: Fix The Database Index/Key Issues

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1610]
Identifying database index and key issues was a great addition.

Unfortunately the majority of store owners:
a) have no idea what they mean
b) have even less of an idea of how to correct them

You could deal with detected issues on two levels:
- as part of the upgrade itself
- via a 'fix issue(s)' function (individual + all) on the existing database page in the store admin

In both scenarios it is probably best to first advise what is going to be done and have the store owner confirm they want to proceed.
A built in table backup/restore function should also be utilized, just in case something goes wrong.

**Comment by abrookbanks** [comment]
CubeCart is unmanaged software and a web developer is expected to be able to handle issues like this. I like the idea but there are more important things to spend resources on I think .

**Comment by briansandall** [comment]
The problem seems to be that most CubeCart users seem not to be web developers, nor do they have typically seem to have the resources to hire one.

Not that that nullifies your point about more important things to spend resources on, but it is something to consider.

**Comment by abrookbanks** [comment]
Agreed.

**Comment by SemperFiWS** [comment]
Understood completely regarding prioritizing resources.

Having a correct database structure is not the responsibility of the store owner or them paying a web developer to correct it.
It should be correct (upon install) or corrected (upon upgrade) by the software being used.

Would it be simple enough to add a new step to the upgrade process that checks if everything is correct?

Then only if any tables are detected as being incorrect present a single button that would: 
- remove all indexes/keys for the tables detected as being incorrect
- add all the correct indexes/keys to these applicable table

**Comment by briansandall** [comment]
What about stores with plugins or other customizations that have created additional indexes? How would we differentiate those from 'incorrect' indexes left over from previous versions of CubeCart?

I'm sure it's possible, but I can't think of a good way to do so. If we can, then I agree this would be a very useful feature for long-time users of CubeCart whose databases have suffered over the course of countless upgrades.

**Comment by abrookbanks** [comment]
The tool could "glob" the modules/plugins/*/indexes.xml (or something to look for external indexes to check.
