### ISSUE TITLE
Suggestion: Better GitHub Organization

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1611]
When it comes to store owners (or potential store owners) coming here for the first time, I have received two keys things as feedback:
- wow there is 170+ issues, CubeCart is full of bugs
- some of these issues are incredibly dated

It might be beneficial to implement some specific groups/sections to help with organizing things a little better.
e.g.
- Bug Report
- Hook Request
- Feature Request / Suggestion
- Marketplace Bug Report
- Marketplace Feature Request / Suggestion
etc

When creating a new 'issue' these 'groups/sections' should be available in a drop down.
The selection made can then be altered, if necessary.

Then rather than having the generic 170 (or whatever the number is) issues, break it down.
e.g.
- 20 Bug Reports
- 10 Hook Requests
- 120 Feature Requests / Suggestions
- 10 Marketplace Bug Reports
- 10 Marketplace Feature Requests / Suggestions
etc

Having a separate/hidden 'Potential Security Issue' group/section that can only be accessed via:
- the person creating the issue
- those with appropriate permissions
would also be beneficial.

Plus its probably a good idea not to make these public, at least until a verified solution is available.

There is already a label system in place.
But it is a little limited and not utilized in a very effective way.

These existing labels plus what I have outlined above could help organize things, especially for those coming here for the first time.

**Comment by abrookbanks** [comment]
Thanks for this but issues are already categorized. I don't want market place issues reported here. This is for CubeCart core only.

**Comment by abrookbanks** [comment]
I always filter GitHub issues excluding features requests. You then see the current issues at hand which is normally about 10 to 20.

**Comment by abrookbanks** [comment]
https://github.com/cubecart/v6/issues?utf8=%E2%9C%93&q=is%3Aopen%20-label%3A%22feature%20request%22%20

**Comment by briansandall** [comment]
I thought it was clear enough with the `Feature Request` tag next to the vast majority of issues. Now it is unclear what issues may still be worked on vs. which have already been implemented. :(

**Comment by abrookbanks** [comment]
> I thought it was clear enough with the Feature Request tag next to the vast majority of issues. Now it is unclear what issues may still be worked on vs. which have already been implemented. :(

Search for closed feature requests with no milestone. ;)

**Comment by abrookbanks** [comment]
e.g. https://github.com/cubecart/v6/issues?q=is%3Aissue+is%3Aclosed+no%3Amilestone+label%3A%22feature+request%22 or filter 
```
is:issue is:closed no:milestone label:"feature request" 
```

**Comment by abrookbanks** [comment]
I think this makes a lot of sense actually and I've seen other projects doing something similar.

**Comment by abrookbanks** [comment]
We're down to 13 open now. I need to think about a solution for issue tracking for official extensions. 

Maybe a repo can be setup for each of them but there are loads and its very admin intensive.. time that could be spent in the pub. Ha.

**Comment by briansandall** [comment]
Yes, of course that mostly works, but some of those were surely closed because they were either implemented and not given a milestone or because it was decided not to implement them.

For example: #222, #7, etc.

**Comment by abrookbanks** [comment]
That's true but there is a label for won't fix/unsure which can be used to exclude them. There are very few if any that I have said no to.

**Comment by briansandall** [comment]
Definitely do not create a repo for each issue - that would be insane.

I'm sure you are experienced with Git, but it may be a good idea to read or re-read the chapter on [Git Branching](https://git-scm.com/book/en/v1/Git-Branching).

Also, a quick web search for 'git branching model' or 'git workflow' brings up loads of good ideas on how to effectively use Git to manage issues, releases, etc.

**Comment by abrookbanks** [comment]
I have to say that from a very selfish point of view I have configured the issue labels and process for myself. I haven't given much thought as to how other use and interpret it but I should have... hence this issue! 

I always view issues excluding feature requests. This way I see unlabelled issues and current bugs of which there are not many.

I will look into using branching.

**Comment by briansandall** [comment]
> I have to say that from a very selfish point of view I have configured the issue labels and process for myself.

That's the lovely part about being the sole developer, you get to set everything up where it works exactly how it needs to for you - nothing wrong with that!

Honestly, I think the current issue labels are/were working fine. Does GitHub even support separate issue tabs as suggested in the OP? If it does, though, that would be neat.

I think branching is the most important thing to look into at this point - I use the heck out of it in my own work and it makes my life so much easier when a critical bug pops up or a feature implementation doesn't pan out the way I expected.

**Comment by abrookbanks** [comment]
I don't think you can have a separate issues tab. I'll create a CONTRIBUTING.md file which may help.

**Comment by briansandall** [comment]
Is there any way to allow average users to add labels to issues when they create them, or is that something you wish to continue managing yourself?

**Comment by abrookbanks** [comment]
How does this proposal sound guys concerning GitHub branches and developer previews?

Master - Latest stable code pulled from Developer after a week. 
Developer - Proposed release pulled from either of the branches below. 
6.1.x-dev - Bug fix development branch.
6.2.0-dev - Minor revision branch.

**Comment by havenswift-hosting** [comment]
Sounds good - no new functionality in bug fix releases.  What would be good is say four scheduled minor release per year and some sort of roadmap (maybe two releases ahead ?) of what new functionality is going to be included.

**Comment by abrookbanks** [comment]
It would be nice if all pull requests could be reviews by someone not developing but the resources just aren't here.

**Comment by briansandall** [comment]
Looks good, Al.

I've used variations of [this branching model](http://nvie.com/posts/a-successful-git-branching-model/) in my own work and have found it to be quite beneficial. It's really nice to be able to drop a failed feature implementation or add a hotfix without everything becoming a tangled mess.

**Comment by abrookbanks** [comment]
Yes totally agree. Great. Thanks so much for all your help everyone.

**Comment by abrookbanks** [comment]
6.1.8-branch created working from there form now. I'll then push to developer branch when 6.1.8 is ready then push to master a week later. This will happen on Mondays or Tuesdays preferentially.

**Comment by abrookbanks** [comment]
OK so our first developer release is here. https://github.com/cubecart/v6/releases/tag/v6.1.8

I then changed the due date for 6.1.8 to 22 May.

**Comment by havenswift-hosting** [comment]
The URL is https://github.com/cubecart/v6/releases/tag/v6.1.8pr

**Comment by abrookbanks** [comment]
Sorry yes I tagged it 6.1.8 to start which we need for final.

**Comment by havenswift-hosting** [comment]
Any thoughts about a features board where everyone can add requests for new features and if possible comment and vote - see cPanel's version of this that works well https://features.cpanel.net/ You can then use this to decide on what features are planned for the next one or two releases and ideally publish these as discussed

**Comment by abrookbanks** [comment]
I have. Many organisations have similar ones.

I don't think we have the budget for it.

**Comment by abrookbanks** [comment]
I like it a lot.

**Comment by SemperFiWS** [comment]
Great see things are looking a lot cleaner and not so overwhelming for new visitors.

Is it possible to not set to closed, without them appearing as an issue?
If not, is it possible to alter the built in filters/labels so they include closed by default?
That way someone can just click the 'Feature Request' label and not have to utilize the advanced search syntax to see what they are looking for, rather than getting nothing.

Or is all of that a limitation of github that is out of your control?

**Comment by SemperFiWS** [comment]
Also great to see that the branch system is in place :)

**Comment by SemperFiWS** [comment]
Regarding a features board, you could do something simpler than what cpanel has on the existing forums.

Just keep it incredibly simple:
- title
- description
- yes or no poll
-ability to reply / add comments
 
The key to it being beneficial will obviously be if anyone looks at it and then votes on the poll + add their comments.
So putting the new forum below 'report an issue' rather than being buried down in the 'General' section might be a good idea.

Couple clicks, type a few words, create the forum, no reason to blow the budget :)

**Comment by abrookbanks** [comment]
> Or is all of that a limitation of github that is out of your control?

That's right.

> Regarding a features board, you could do something simpler than what cpanel has on the existing forums.

That's true actually. Also there is no reason why people can't click this icon to rate on GitHub. 
![screen shot 2017-05-18 at 09 04 53](https://cloud.githubusercontent.com/assets/4520803/26192307/13469930-3ba9-11e7-95f4-b46ca9881c3d.png)

Thanks for coming back to me. I want to make things better.

**Comment by havenswift-hosting** [comment]
>>Also there is no reason why people can't click this icon to rate on GitHub.

The problem is that features arent visible (most people wont find closed items) and so will not happen.  I understand the thinking behind closing them on here but that just re-enforces the view that this isnt the correct way to deal with feature requests.  I used cPanel system as an example of what cvould be done and there are open source free solutions available that could be used

**Comment by abrookbanks** [comment]
I like the cPanel idea best. Lets see if we can get a copy.

**Comment by abrookbanks** [comment]
Spotify use: https://www.lithium.com/powered-by-lithium (doubt this is affordable)
cPanel use: https://www.useresponse.com .. the cloud version could be an option at $15 USD a month

**Comment by abrookbanks** [comment]
Anyone know of any others? I'm not very familiar with this market.

**Comment by abrookbanks** [comment]
https://www.uservoice.com

**Comment by abrookbanks** [comment]
Trialling UseResponse here http://features.cubecart.com/

**Comment by havenswift-hosting** [comment]
Excellent - thanks Al !  Can you add some of the closed github feature request issues ?

**Comment by havenswift-hosting** [comment]
Not to worry, registered and will transfer a few across myself

**Comment by abrookbanks** [comment]
Thanks.

**Comment by havenswift-hosting** [comment]
Creating new topic gives SSL error on features.cubecart.com

**Comment by abrookbanks** [comment]
no idea.. it just asked me to setup a cname on setup which I did.

**Comment by havenswift-hosting** [comment]
Trying to use a secure connection and no valid SSL for features.cubecart.com

**Comment by abrookbanks** [comment]
Just use http://features.cubecart.com

**Comment by abrookbanks** [comment]
I can buy SSL for this if we decide to go ahead. I need you guys to let me know what you think. I see Ian has submit a lot of feature requests already. Thanks for this.

**Comment by havenswift-hosting** [comment]
I like this system and used to using it with cPanel - simple and clear.  I did click on the link initially which is http and at some stage it switched me to https and gave the error so an SSL may be needed sooner rather than later (Comodo do a free 30 or maybe even 90 day trial or you have Let's Encrypt but depends what options you have with the hosted system).

Having a link on the forums which you have already added should help greatly and then it is about encouraging people to vote and comment which will happen if feedback is given and features are clearly scheduled (roadmap for maybe two versions ahead).

A great move forward Al !

**Comment by abrookbanks** [comment]
great.. thanks for the encouragement. Things need to change. We need a new website too.

Luckily I can do 50 things at once standing on my head..... NOT. Hehe

**Comment by abrookbanks** [comment]
Hoping I can export/import https://api.github.com/repos/cubecart/v6/issues?state=closed&labels=feature%20request

**Comment by havenswift-hosting** [comment]
Only 50 ??

I will stop adding any more for a while then although if you are going to export / import, you may want to look through and maybe discard some - some are old and not relevant etc

**Comment by abrookbanks** [comment]
No its paginated.. 

https://api.github.com/repos/cubecart/v6/issues?state=closed&labels=feature%20request&page=1
https://api.github.com/repos/cubecart/v6/issues?state=closed&labels=feature%20request&page=2
.. etc

**Comment by abrookbanks** [comment]
The API docs for UseResponse are thin so import is proving tricky.

**Comment by havenswift-hosting** [comment]
It isnt difficult to copy and paste title and content anyway and as not too many people have added feature requests, it might be a way for people to filter out anything that isnt relevant any longer ?

**Comment by abrookbanks** [comment]
Yes maybe.

**Comment by briansandall** [comment]
This is getting close to the record for most-commented issue!

@abrookbanks I like the new features link on the forums - it seems more accessible for the majority of users and easy to see at a glance what the most-wanted features are.

**Comment by abrookbanks** [comment]
yeah it needs a lot of exposure to be successful.. Maybe even a link in CubeCart itself.

**Comment by briansandall** [comment]
> Maybe even a link in CubeCart itself.

That right there is gold.

**Comment by abrookbanks** [comment]
Yeah I've got to keep the lights on somehow. Hehehe.

**Comment by havenswift-hosting** [comment]
>>Just use http://features.cubecart.com

Try going to http://features.cubecart.com/topics and it redirects to the https version and then you get the security warning - already had two of our customers say this is putting them off

**Comment by abrookbanks** [comment]
I've fixed it now. I've also written a script to import everything from GitHub.

**Comment by havenswift-hosting** [comment]
>>I've fixed it now.

Not seeing that myself

>>I've also written a script to import everything from GitHub.

As discussed yesterday, you will probably want to filter out some / many before importing them - might as well try to start out with just relevant ones rather than clog up new system with outdated or irrelevant topics

**Comment by abrookbanks** [comment]
I'll filter once imported.

**Comment by abrookbanks** [comment]
Ok I got there all in. I need to go though them now and be ruthless. There may be five or six duplicates.

**Comment by SemperFiWS** [comment]
Great job on getting them imported :)

You might want to correct the GitHub URLS.
e.g.
Topic: https://features.cubecart.com/topic/separate-admin-and-customer-sessions_1
GitHub URL: https://api.github.com/repos/cubecart/v6/issues/646

**Comment by abrookbanks** [comment]
Yeah. whoops. I can't change them now but the links are for me really so not such a biggie.

I've gone over about 100 feature requests so far and I'll try to get the rest done asap. 

Excited about getting clear roadmaps started.

**Comment by SemperFiWS** [comment]
How about a query like this:
```UPDATE `_change_this_to_the_table_name` SET `change_this_to_the_field_name` = replace(also_change_this_to_the_field_name, 'https://api.github.com/repos/', 'https://github.com/');```

**Comment by abrookbanks** [comment]
Its a cloud service so I don't have SQL access.

**Comment by SemperFiWS** [comment]
Do you have file access?
If so, then run it via a PHP script or using the 'adminer' database tool.
