### ISSUE TITLE
Suggestion: Upgrade, Then Retire The CC5 Skins

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1612]
At this stage I think everyone can agree that whilst the CC5 skins 'work' using CC6, they are vastly outdated.

Some of them are missing basic functionality.
e.g.
Radio button product options

So you have store owners using a CC5 skin (for whatever reason) that set those up, then are perplexed when they don't display in their store.

All of them are missing the majority of advanced functionality the foundation skin has.
e.g.
The new invisible recaptcha 
Social accounts
Shipping + tax estimates
etc

Some of these functions have a notice displayed in admin, but when functionality doesn't work for a skin that is labeled as 'CC6 compatible' it is a little misleading.

Ideally all the CC5 skins could be upgraded so they contain all available functionality.
But realistically that might not even be possible.

So perhaps upgrade them to be as close as possible, then alter their descriptions (marketplace) to indicate what does and does not work.
You could also include a note that this is the final update and that they are effectively retired.

Expanding on this further, looking towards the future, I wonder if it would be possible to:
- move the foundation functionality into the core
- have a setting within the skin that determines whether it is used or not
- ability to customize the core foundation functionality as required from within the skin

**Comment by Dirty-Butter** [comment]
It's obvious from the tip of the iceberg we see on the forum that many people are trying to upgrade without understanding there is functionality that a stock v5 skin won't have.

**Comment by abrookbanks** [comment]
I disagree. We should keep them. It does say they were developed for version 5. Maybe an added note should be added to explain what that means. We need all the skins we can get.

**Comment by SemperFiWS** [comment]
Whilst I agree that having a large selection of skins available is ideal, having skins that cannot take advantage of all of the CC6 functionality is not the way to go about it.

You want a skin to showcase how great using CC6 can be, not be an inferior representation.

Obviously I have no clue how successful the last skin design contest was overall, but it did result in new CC6 skins being created.
Likewise I have no clue if it is within budget to run a similar contest again or if it would be better to allocate those resources to having a second official CC6 skin created.

**Comment by abrookbanks** [comment]
> I have no clue how successful the last skin design contest was overall

It was not particularly successful sadly. The only one that sells is Galaxy X.. probably a few times a week. 

> I have no clue if it is within budget to run a similar contest again

Things are a bit different now we are open source. I'm lucky to have a small amount of great supporters like you guys but we need a whole lot more.
