### ISSUE TITLE
Check for redundant admin folder try auto delete or prompt for delete

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1613]
The recent recommndation that store owners manually upgrade their store (due to issues with the admin upgrade system) has resulted in stores not being upgraded correctly.
i.e.
- uploaded the 6.1.7 'admin' directory without renaming it to match what it is called in the '/includes/global.inc.php' file
- uploaded the 6.1.7 'admin.php' file without renaming it to match what it is called in the '/includes/global.inc.php' file

Stores end up with multiple admin folders and files.
Plus when they access their store admin, they are still using the admin from the version they are upgrading from.

1 - Install
When doing a fresh install have two new configurable fields:
- admin folder name (populate it with the random name, allow it to be edited)
- admin file name (populate it with the random name, allow it to be edited)
That way a store owner can choose to go with the random names or easily change them to something they will actually remember.
You could even explicitly block using 'admin' and 'admin.php' so they cannot be used.

2 - Upgrades
Expand on the existing checks so it:
- looks for a folder called 'admin' and for a folder matching the '$glob['adminFolder']' value
- looks for a file called 'admin.php' and for a folder matching the '$glob['adminFile']' value
If it is detected that there is multiple 'admin' folders or 'admin.php' files, halt the upgrade and provide a method to correct it via the browser.
Adding a new 'admin-ini.inc.php' file into the 'admin' directory containing only the CubeCart version might also be useful. 

3 - Ongoing
Add a new 'admin security' page to the store admin, separate to the store settings page.
On this page allow the main store admin only to alter both the admin directory and admin file values for themselves.
Any time they hit save:
- a confirm prompt is displayed (like when deleting something)
- the '/includes/global.inc.php' file is backed up
- the '/includes/global.inc.php' file is altered to use the new variables
- the store admin gets redirected to the new admin url automatically, notice displayed that it has changed

Additional options (e.g. lock admin to specific IP address(es) could also be implemented on this page.

**Comment by Dirty-Butter** [comment]
Hoo! This would make things a lot less confusing, based on all the recent forum requests for help. People also need to understand that they should not share what the renamed values are. Hardly a day goes by that I don't obfuscate admin_XXX in a post for someone on the forum.

**Comment by abrookbanks** [comment]
Thanks. Some good suggestions here. The auto upgrade tool is now working well once at 6.1.7. 

The manual upgrade instructions explains that the file and folder need to be renamed. I would say the pressing issue is that the old admin folder should be deleted if it exists and the global file is using the correct obfuscated one.

**Comment by Dirty-Butter** [comment]
The manual upgrade is fixed in 6.1.7, but is there any way to mark the Admin upgrade warning for stores on earlier than 6.1.7 that they must upgrade MANUALLY?

**Comment by abrookbanks** [comment]
nowp. :(

**Comment by abrookbanks** [comment]
This is a bug/feature requests. Closing for now as the main issue is resolved with https://github.com/cubecart/v6/commit/92a686c44b3ce616589fd635b5d7aa3ae862fee2

Maybe a future release can have tools to rename paths.

**Comment by abrookbanks** [comment]
I opened a new feature request for the extra suggestions by @SemperFiWS

**Comment by SemperFiWS** [comment]
Thanks Al, many store owners have requested an admin URL that is secure, but something they will actually remember.
Having it as an easy to access admin setting is much simpler for those store owners that have no idea how to FTP + edit a file.

**Comment by Dirty-Butter** [comment]
While you are working on whatever you come up with for this admin way to change url - please try to work in some instruction to store owners to NOT share their secure admin naming on the forum.

**Comment by abrookbanks** [comment]
> something they will actually remember

Agreed. I see the benefit of that. The admin folder isn't so important.
