### ISSUE TITLE
Suggestion: Implement A Patch System

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1614]
There have been times when a full new release isn't really required (or ready), but an issue needs to be addressed.

With the current system there is two options:
- release a new CC6 version, address the issue
- wait until the next release, then address the issue

An improvement on that would be having a 3rd option by establishing and introducing a patch system.

Example
- problem X gets reported (here or even on the forums or behind the scenes if security related)
- a solution to problem X is created and tested (confirmed as being 100% working)
- a patch 'package' is created (single or multiple files as applicable)
- store owners get notified a patch is available in their store admin (with details about what it will do / the problem it's addressing etc)
- they can then apply the patch and a record is kept that they have done so (or they can dismiss it)
- in addition to displaying the store version in admin, also display details of applied patches too

**Comment by briansandall** [comment]
Releasing patches as e.g. v6.1.7.1 would be the simplest solution that can use the same upgrade mechanics that everyone is already familiar with.

The real issue is that Al commits and auto-pushes every change he makes to the master branch, so there is no way to release a 'patch' version without including however many WIP and/or not completely tested features that have been committed prior to the patch.

If there were a branch for the next version, e.g. 6.1.8, and all changes were pushed to that before being merged or rebased onto the master branch at the time of release, then it would be feasible to commit critical fixes to the master branch that is still at 6.1.7 and release it as a patch e.g. 6.1.7.1.

**Comment by Dirty-Butter** [comment]
I like the idea of v6.1.7.1 type patches. Patches for specific issues would make it much more logical and easier to tell if a patch had any unintended consequences. It would be easier to undo, too. I pray for the day that CC upgrades work as smoothly as WordPress upgrades do!

**Comment by havenswift-hosting** [comment]
We don't need another level of releases !   6.1.X for bug fixes and security issues. 6.X.0 for functional improvements and X.0.0 i.e. 7.0.0 for new major release.  That way a 6.2.0 branch could be developed and TESTED and have a set release schedule of say once every three months, while still allowing immediate small bug fixes and critical issues that should need less testing.  Look no further than the way WordPress does it

**Comment by briansandall** [comment]
That would work, too - I'm not pushing for a particular version numbering system so much as I am for fixes, features or whatever that are not fully-tested to not be immediately committed and pushed to the stable branch.

Ideally, the stable branch would only ever have critical bug and security fixes applied to it which could be immediately released as a minor version patch, and once the functional improvement branch proves stable and has enough juicy changes, it can be merged into the stable branch and released as a 6.X.0.

**Comment by havenswift-hosting** [comment]
I completely agree - have been pushing for this for a long time !

**Comment by abrookbanks** [comment]
Thanks for your thoughts guys. All taken on board.

**Comment by SemperFiWS** [comment]
Anytime.

The one perfect example of what I was getting at with this suggestion was the recent phpmailer security issue.

Rather than having to either do a full upgrade or the manual patch, you could have:
- bright red alert in the store admin stating the security patch is available for all CC5 + CC6 stores
- store owner clicks the link, patch gets applied, store is secure again

That way it's a simple process, that all store owners would be aware of, including the majority that never go anywhere near the forums.

**Comment by abrookbanks** [comment]
Good point. Taken on board. :)
