### ISSUE TITLE
Requesting a new hook in cart.class.php

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1618]
The same hook will need to be added in two places due to an if/else statement. This hook allows for manipulation of option prices correctly and must be used in combination with the existing class.cart.get.product_prices to ensure tax works correctly when making price adjustments.

**FIND:**
`$value = $GLOBALS['catalogue']->getOptionData((int)$option_id, (int)$option_data);`

**ADD AFTER:**
`foreach ($GLOBALS['hooks']->load('class.cart.get.product_option_prices') as $hook) include $hook;`

and secondly:
**FIND:**
`$value = $GLOBALS['catalogue']->getOptionData((int)$option_id, $assign_id);`

**ADD AFTER:**
`foreach ($GLOBALS['hooks']->load('class.cart.get.product_option_prices') as $hook) include $hook;`

**Comment by abrookbanks** [comment]
Your wish is my command sir. :sparkles:

**Comment by Noodleyman** [comment]
Thank you Al :)
