### ISSUE TITLE
Live zoom of product pictures

### ISSUE THREAD

**Issue by NaturalSigns** [cubecart/v6#162]
When a listing has multiple images the zoom feature doesn't appear to refresh the active zoom area per picture (i.e. i think it currently requires all images the same size or orientation).  A mock up can be found here e.g. http://www.naturalsigns.co.uk/new_cc/rectangular-sign-medium.html if you select the lower thumbnails you can end up with the zoom magnifying glass being stuck on so that you can't select any alternative images (tested on firefox and chrome).

**Comment by abrookbanks** [comment]
This can be fixed by increasing the z-index on the gallery images..  (I think.. working on a fix)
