### ISSUE TITLE
Incorrect hook in customers.index.php?

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1622]
Hook used for sorting the customer list table is the same as is used for sorting products:
```
foreach ($GLOBALS['hooks']->load('admin.product.table_head_sort') as $hook) include $hook;
```
I assume this is intentional?

**Comment by abrookbanks** [comment]
Hmm.. I think this is a mistake! 
![screen shot 2017-05-08 at 09 50 35](https://cloud.githubusercontent.com/assets/4520803/25797111/d56402f6-33d3-11e7-9872-a0e5a1aed5ad.png)
