### ISSUE TITLE
Incorrect URL Breaks Module Languages

### ISSUE THREAD

**Issue by CubeCartExtended** [cubecart/v6#1628]
Admin > Settings > Languages
Click on the default language (e.g. English (US))
Select a module from the phrase group drop down (e.g. Modules - Gateway - Print_Order_form)

After doing that you will end up with:
- no language entries displayed
- the option is not selected in the drop down
- an incorrect breadcrumb

6.1.5
```?_g=settings&node=language&language=en-US&type=modules%2Fgateway%2FPrint_Order_Form%2Flanguage%2Fmodule.definitions.xml#general```
6.1.7
```?_g=settings&node=language&language=en-US&type=modules%252Fgateway%252FPrint_Order_Form%252Flanguage%252Fmodule.definitions.xml#general```

This can be replicated for languages that are not set as default too.

6.1.5
```?_g=settings&node=language&language=en-GB&type=modules%2Fgateway%2FPrint_Order_Form%2Flanguage%2Fmodule.definitions.xml#general```
6.1.7
```?_g=settings&node=language&language=en-GB&type=modules%252Fgateway%252FPrint_Order_Form%252Flanguage%252Fmodule.definitions.xml#general```

**Comment by abrookbanks** [comment]
Thanks for this.
