### ISSUE TITLE
Requesting a minor code addition - catalogue.class.php

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1629]
After the existing hook:
`foreach ($GLOBALS['hooks']->load('class.cubecart.display_product') as $hook) include $hook;`

Add:
`			if(isset($contentDefined) && $contentDefined === true){
				return true;
			}`

Reason:
You can't return true to a function via a hook since it returns true to the include of the hook call itself. If you use the above hook to link to a custom template file for the content you can't prevent the core code from then replacing your custom content. The addition allows you to define a variable via the hook which tells CubeCart to stop so your custom template can be used.

**Comment by abrookbanks** [comment]
I see your point but I don't like this. Why would one have this and not all and then the admin around updating them all. 

I want to think about this more to see if there is any other way..

**Comment by Noodleyman** [comment]
in my specific case, I've a module for a customer which allows them to select which template file they wish to use for a product. It's a configurable option at the product level. Based on the selection the selected file will be parsed instead of content.product.php.

Without the ability to return true in the hook, you can't prevent CubeCart replacing the contents of $content with content.product.php.

The only thing after this line of code in this function is to parse the content.product.php template file and return true, so it's reasonably safe.

**Comment by bhsmither** [comment]
I don't like this either as one hook co-opting the method and deterring the program flow.

But then, I have been frustrated dozens of times wanting to exit a method at the final hook.

Personally, I would have added another hook just before the existing `return true;`. This is where one can derive different $content and re-assign `PAGE_CONTENT`.
