### ISSUE TITLE
Minor bug: short description may display part of an encoded character

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1633]
![cc_1632](https://cloud.githubusercontent.com/assets/14335170/25971513/613604e4-3651-11e7-83ba-5463872ad5e5.jpg)

I suspect this is because special HTML characters are stored in the database in an encoded format, and when the short description takes a substring of that raw data, e.g. "... 36&quot; ...", it can end up with a partial character, e.g. "36&quo".

A rare edge case, to be sure, but there it is.

Example text to replicate with default 120 product precision length:

Here is a description of a specific length, ending in a quotation mark, this quotation mark will be displayed fine 36" (not actually, though, and also force an ellipsis).

**Comment by abrookbanks** [comment]
Thanks Brian. I changed the target branch of the merge to "6.1.8-branch".

**Comment by Noodleyman** [comment]
I ran into this issue on a 6.1.8 store today, to resolve it I had to remove the code modification and revert back to the original. 

I think this needs a little more testing as the new code can cause the issue as well as resolve it.

**Comment by briansandall** [comment]
@Noodleyman Can you provide the text (as stored in the database) that caused this issue for you?

**Comment by Noodleyman** [comment]
`<p>Children&#39;s Jorgie&#39;s Buddies&nbsp;Hoody available in a wide range of colours&nbsp;as either a hoody or zip up.</p>

<p>The Zoodies (Zip up&#39;s) are onlly available in the colours marked with an *.</p>`

**Comment by abrookbanks** [comment]
You need three apostrophes (`) to get ```pure format like this ```

**Comment by abrookbanks** [comment]
Is ` an apostrophes? Or '?

I have no idea I failed English (and Math) spectacularly.

**Comment by briansandall** [comment]
Al, ` is known as a backtick or backquote when used in these contexts; otherwise, it is known as the _accent grave_ (in French).

@Noodleyman I'll give that a try and see what happens.

**Comment by Noodleyman** [comment]
out of interest, what if you try that with an older version of foundation theme (as the site where I spotted this was using a theme based on an older version)

**Comment by briansandall** [comment]
Sorry, turns out I hadn't yet updated my local fork to the latest code. The apostrophes show up as `&#39;` in the description now, which is indeed caused by this but a different issue.

Changing either `ENT_COMPAT` to `ENT_QUOTES` or vice versa will probably fix this.

**Comment by briansandall** [comment]
@abrookbanks Made a PR for the 6.1.9 branch. Let me know if I need to switch to a different target branch.

**Comment by abrookbanks** [comment]
Thank you.
