### ISSUE TITLE
'More' button pagination broken after #1619

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1635]
Suggest reverting #1619 and moving the instructions about hiding the button to just above the actual button link, as that is the only element that needs 'hide-for-medium-up' added to it.

**Comment by briansandall** [comment]
Suggest that lines 216-221 of `content.category.php` should look like this:
```
   <div class="hide" id="ccScrollCat">{$category.cat_id}</div>
   {if $page!=='all' && ($page < $total)}
   {$params[$var_name] = $page + 1}
   {* Add "hide-for-medium-up" to the class attribute to not display the more button *}
   <a href="{$current}{http_build_query($params)}{$anchor}" data-next-page="{$params[$var_name]}" data-cat="{$category.cat_id}" class="button tiny expand ccScroll-next">{$LANG.common.more} <svg class="icon"><use xlink:href="#icon-angle-down"></use></svg></a>
   {/if}
```

**Comment by abrookbanks** [comment]
I get so muddled when there are "two" issue numbers in a subject. I reverted the code for #1619 updated 6.1.8-branch from master then applied this. :confounded: Haha

See: https://github.com/cubecart/v6/commit/0f0fdc41286b23f9d99da90e02e11eef882ff04a

**Comment by briansandall** [comment]
Looks good! Thanks!

**Comment by abrookbanks** [comment]
Great! :P
