### ISSUE TITLE
Page auto-scrolls to next page even after loading a different page

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1636]
To replicate, you must be using the modern pagination, not the traditional version:

- Click a category with enough products to be paginated

- Click the 'More' button to view more products in that category

- Navigate to one or more other pages on the site, even other categories or sub-categories

- Click on the original category; the page will 'remember' how far you went in your pagination last time, display that many products, and auto-scroll you down to the top of the last 'page' you viewed

There doesn't seem to be any way to return the page to 'normal'; even editing the URL to remove the anchor doesn't work.

**Comment by abrookbanks** [comment]
It's supposed to do that on the grounds that if you expend a few times then view one of the products clicking back would not return you to the same place. This code was added so it would reload it back to how it was. It will remember this for 10 mins:

https://github.com/cubecart/v6/blob/master/skins/foundation/js/2.cubecart.js#L300-L303

Maybe 10 mins is too long.

**Comment by abrookbanks** [comment]
Maybe the cookie should be deleted if other category pages are visited or if the next page is not a product detail page. Hmm.

**Comment by briansandall** [comment]
Hm, yeah that makes sense. I believe the customer experience would be improved if it exhibited that behavior when using the back button only, and not when clicking on a link.

**Comment by abrookbanks** [comment]
But thats the 65 million dollar question. How do you detect the browser back button?

.. I don't think you can.

**Comment by briansandall** [comment]
While there may be many people still using older browsers, couldn't we at least give a nice experience to those using HTML5-compatible browsers by using pushstate?

For example, if each time the 'More' button is pressed, we add a history entry for that 'page'... or maybe just the last time they press the button (so replace each previous entry when clicked) so that they don't have to press back a bunch of times to get to the actual previous page, though they would still have to click back twice if they clicked the 'More' button.

A tricky situation, to be sure.

**Comment by abrookbanks** [comment]
I'll look into that. Thanks!

**Comment by abrookbanks** [comment]
I'm closing this with prospect of adding to new future skin. See https://features.cubecart.com/topic/update-foundation-to-latest-version-of-framework_8
