### ISSUE TITLE
sources/maintenance/indexbackup.inc.php - not found.

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1639]
Redirect from backup produces an error as in the subject.

**Comment by Dirty-Butter** [comment]
Has the code for tab # been changed to a comma on every tab? There have been a couple of forum issues with the Clone #Extra in the error messages.

**Comment by abrookbanks** [comment]
Yes I think that may be an issue....

**Comment by abrookbanks** [comment]
From my search these have all been covered now.

**Comment by abrookbanks** [comment]
Spotify use: https://www.lithium.com/powered-by-lithium (doubt this is affordable)

**Comment by abrookbanks** [comment]
cPanel use: https://www.useresponse.com/

**Comment by Dirty-Butter** [comment]
Create Newsletter tab is doing it, too.

**Comment by abrookbanks** [comment]
> Create Newsletter tab is doing it, too.

Oakeydokey... I'll check this out.

**Comment by Dirty-Butter** [comment]
Is there anything to do with this when printing the invoice via Order Summary? When I try to print a Packing Slip I get my domain 404 page. The file is correct, as I can download it, change the suffix to html, and it prints just fine. I've tested every way I know how with no success. 
The Print Invoice on the Customer's Order page does print properly.
