### ISSUE TITLE
Modifying Products Deselects Digital Option

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#164]
The following issue may still be unresolved (CC5/6):
https://forums.cubecart.com/topic/48674-modifying-products-deselects-digital-option/page-2?hl=+digital%20+download

**Comment by abrookbanks** [comment]
The only thing I can assume is that they have clicked save before the page has finished loading therefore losing the data. Maybe some JS to disable the submit until the page has loaded.

**Comment by abrookbanks** [comment]
From my testing this works nicely but there is an issue in that if there is a digital file with id = 1 it gets selected after the digital path is emptied.
