### ISSUE TITLE
MySQL version on install screen shows wrong value

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1640]
When installing / updating CubeCart it shows the MySQL version - however the version shown is actually for the PHP MySQL library and not for the MySQL server itself. So for example a server may have the following

MySQL Server 5.6.35
PHP MySQL library : 5.1.73

CubeCart reports the second of these which can be confusing.  Normal practice is not to upgrade the PHP MySQL library unless there are serious issues, as long as the major versions are the same and the PHP library is a lower version than the MySQL server version

**Comment by abrookbanks** [comment]
It's not possible to know the exact version without establishing a connection. In most cases the client version should match the server version. CubeCart isn't very pick about MySQL version  so this is unlikely to cause an issue.
