### ISSUE TITLE
Unable to checkout as guest with Invisible ReCAPTCHA

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1641]
See https://forums.cubecart.com/topic/52448-unable-to-checkout-as-guest-with-invisible-recaptcha

**Comment by havenswift-hosting** [comment]
This is affecting several of our clients as well ! Plus one for getting this looked at ASAP although not before https://github.com/cubecart/v6/issues/1536 of course lol

**Comment by abrookbanks** [comment]
I'll get to #1536 one day.
