### ISSUE TITLE
Adding Manufacture's to V 6.1.7 Bug

### ISSUE THREAD

**Issue by TheMixtapeChannel** [cubecart/v6#1643]
Hi, just noticed that when trying to add a manufacture via admin panel, you get error: /admin_xxxxxx/sources/products/manufacturerstab_manufacturers.inc.php - not found. There's no products folder in sources directory and therefore it can't find the php call file.

Eddie

**Comment by abrookbanks** [comment]
This was fixed here I believe:
https://github.com/cubecart/v6/issues/1531

I'm unable to reproduce this on latest build. Thanks for the report.
