### ISSUE TITLE
Plugin breadcrumb uses incorrect url

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1644]
If you have a plugin that adds a page to the store admin, you would have code similar to this:
```
$GLOBALS['gui']->addBreadcrumb($this->_language_strings['admin_manage_list_page_breadcrumb'], '?_g=plugin&name=deluxe_document_manager');
```
to create a breadcrumb, which it does do correctly and you end up with breadcrumbs like this:
Dashboard >Plugin > Deluxe Document Manager

Both the 'Dashboard' and 'Deluxe Document Manager' links in this example are correct.

However, the 'Plugin' link gets set to:
?_g=plugins
which will result in this error:
/admin_123XYZ/sources/plugin/index.inc.php - not found.

The link should be this instead:
?_g=plugin&node=index
 
Another alternative would be to remove the 'Plugin' link from the breadcrumb entirely.

**Comment by abrookbanks** [comment]
I can't reproduce this in 6.1.8. Can you? I suspect this may have been an issue on 6.1.7. 

May relate to https://github.com/cubecart/v6/issues/1639

**Comment by SemperFiWS** [comment]
Still an issue in a freshly installed 6.1.8 store.

Link is:
?_g=plugin&node=index
Link should be:
?_g=plugin**s**&node=index

**Comment by abrookbanks** [comment]
Can you send me the extension code with this bug?

**Comment by abrookbanks** [comment]
.. I added the code in your original post to a plugin and couldn't reproduce this.

**Comment by abrookbanks** [comment]
> Link is:
?_g=plugin&node=index
Link should be:
?_g=plugins&node=index

In that case change the code to:
```
$GLOBALS['gui']->addBreadcrumb($this->_language_strings['admin_manage_list_page_breadcrumb'], '?_g=plugins&name=deluxe_document_manager');
```

Am I missing something?

**Comment by SemperFiWS** [comment]
I was actually thinking that exact same thing last night and that the breadcrumb code I was using was creating the problem.

But if you use something like:
?_g=plugins&name=deluxe_document_manager'
it loads the plugin index page, not the new page.

**Comment by abrookbanks** [comment]
Can you not add a new link to the navigation menu?
See: https://support.cubecart.com/Knowledgebase/Article/View/203/46/how-can-i-create-a-plugin-using-the-code-hooks-system

The code in this example plugin (http://support.cubecart.com/assets/visitor_stats.zip) works;
```
$nav_items['visitor_stats'] = array($vistor_stats->_language_strings['child_admin_menu'] => '?_g=plugin&amp;name=visitor_stats');
```

I don't see why this wouldn't work?

```
$GLOBALS['gui']->addBreadcrumb($this->_language_strings['admin_manage_list_page_breadcrumb'], '?_g=plugin&amp;name=visitor_stats');
```

Happy to look at your code.

**Comment by sumwonlost** [comment]
I will try and explain issue.

Pre-install of Deluxe Documents Manager when you click Documents it load Documents page and breadcrumbs show Dashboard > Documents

After install the breadcrumbs show Dashboard > Plugin > Deluxe Document Manager

The issue is when clicking Plugin link (which btw should be Plugins) it takes you to ?_g=plugin&node=index rather than ?_g=plugins&node=index.

Note it should be plugins not plugin.

**Comment by abrookbanks** [comment]
Can someone send me a copy of the extension? I have no means to reproduce this.

**Comment by sumwonlost** [comment]
I can but I would have thought it is for SemperFiWS to send to you as I don't want to have breach of terms issues.  All I can do is try to explain issue best I can.

**Comment by abrookbanks** [comment]
I understand now..

**Comment by abrookbanks** [comment]
`https://example.com/cc6/admin.php?_g=plugin&node=index` will redirect to `https://example.com/cc6/admin.php?_g=plugins`
