### ISSUE TITLE
database.class.php Error on Line 900

### ISSUE THREAD

**Issue by conanctran** [cubecart/v6#1647]
Hi CubeCart,

I am currently running on version 6.1.8
and under Manufacturer as soon I add a Manufacture named "Gigabyte" with the link to www.gigabyte.com.au
This error appears.

Notice: `name` is not allowed as a key in 'CubeCart_config' table! in /home1/hyperbyt/public_html/store/classes/db/database.class.php on line 900

Is this a CubeCart Bug?

Conan

**Comment by abrookbanks** [comment]
HI Conan, this isn't a bug. If you want to open a technical support ticket we can take a look for you.
