### ISSUE TITLE
Unable to update Plugin language files 

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#1650]
I am unable to change language files for Plugins.

Settings -> Languages -> US (eg) ->Select Phrase Group from dropdown (eg Extensions - Modules - Shipping - All_In_One_Shipping)

On select it creates the language file for the plugin correctly and reloads the same page rather than taking me to phrases for editing, this needs fixing.  This applies to all plugins using this method.

Using Deluxe Document Manager, it has a link to the default Store language file and when clicked it correctly creates the language file and takes me to the phrases page which I can edit and save.  

To change other languages for DDM, you have to change store language and then follow above process again for each language.  This is a long work around and not all Plugins have links to their language pages.

**Comment by Dirty-Butter** [comment]
Since Deluxe Document Manager is a plugin, have you contacted SFWS about this issue?

**Comment by sumwonlost** [comment]
It's not just DDM it is ALL plugins including those from CubeCart if you read my post that is why I use All In One Shipping in the example.  DDM actually works correctly for default store language which is more than the described method does.

**Comment by abrookbanks** [comment]
This was due to a bug in the value for the name attribute of the group section of the module.definitions.xml file of the AIO shipping module. 1.0.9 has just been released fixing this.

**Comment by sumwonlost** [comment]
Hi Al

I just downloaded and installed AIO shipping module 1.0.9 and still had same issue.

I did a clean install and the problem fixed.

I agree there was an issue with as you stated in AIO 1.0.8 and fixed in 1.0.9 as I have loaded both and tested them.

But now there is a NEW issue in 1.0.9, please see attached screenshot.

Regards

Hany

**Comment by abrookbanks** [comment]
No attached screenshot. Please can you upload it to https://github.com/cubecart/v6/issues/1650

**Comment by havenswift-hosting** [comment]
Upgrading from 1.0.8 to 1.0.9 causes the following on the general screen.  Reverting back to 1.0.8 fixes the issue - confirmed on several client sites and on our demo site

![aio_admin screen](https://cloud.githubusercontent.com/assets/6114431/26761610/32efd7dc-4933-11e7-95cc-ff726cb33466.png)

**Comment by abrookbanks** [comment]
Fixed with 1.0.10 https://www.cubecart.com/extensions/shipping-methods/-all-in-one-shipping
