### ISSUE TITLE
Weight field definitions are different

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1651]
At the inventory level, weights are decimal(10,3) but at the option level they are decimal(10,2)

I would assume they should both be 10,3

**Comment by briansandall** [comment]
This was [already fixed](https://github.com/cubecart/v6/commit/8a2c9c9d5d0157be55814eb764220d24942a9a5c) in 6.1.6 - did you run the update script for that version?

**Comment by Noodleyman** [comment]
your right, I was working on an earlier version and confirmed it's solved in a newer build. my bad :)
