### ISSUE TITLE
Categories still display even when no products

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1652]
Reproducible in multiple skins including core foundation.  Even with the flag set to not display empty categories, these do still display

**Comment by briansandall** [comment]
To add my observations: the setting does work, but only for a category with neither products nor sub-categories. Basically, a sub-category prevents a parent category from being hidden, even if that sub-category has no products.

Empty categories with no sub-categories and sub-categories without any further sub-categories will be hidden correctly.

**Comment by Noodleyman** [comment]
This has been raised before, sure of it. it's because CubeCart counts objects in the category. A sub category counts as an object, so simply the existance of a sub category is enough to prevent the setting from working correctly.

**Comment by havenswift-hosting** [comment]
Not sure this should be a "Feature Request" !

There is also two identical ones still open

https://features.cubecart.com/topic/hiding-categories-with-no-products_8
https://features.cubecart.com/topic/hiding-categories-with-no-products_1
