### ISSUE TITLE
Weight - products that weights less then a gram.

### ISSUE THREAD

**Issue by demand73** [cubecart/v6#1657]
I have lots of products in my CC that weights less than a gram and thats not a problem when customers order 5pcs of something but when they orders 1000pcs the weight adds up to 1kg and shipping gets super expensive in cart but in reality the weight is 40grams. May i ask for one more decimal digit in the weight like 10.4 instead of 10.3?

**Comment by abrookbanks** [comment]
Can you provide steps to reproduce this?

**Comment by Noodleyman** [comment]
Makes sense, the precision is to 1gram in CubeCart. if your product weighs a fraction of a gram, you can't capture it, thus your product at a minimum is 1g.

might be worth increasing the precision to 5DP

**Comment by abrookbanks** [comment]
I'll check the code for rounding.

**Comment by Noodleyman** [comment]
the DB only stores to 3DP, so you won't be able to store it at anything less than 1g.
0.999 is 999grams, 

It would need the field to be taken to 4, maybe even 5DP's and that may simply be enough (without checking code). :)

**Comment by abrookbanks** [comment]
Yup, also https://github.com/cubecart/v6/blob/master/classes/cart.class.php#L844

**Comment by abrookbanks** [comment]
@demand73 is 4 decimal places enough? I can't imagine many things weigh less than 0.1 grams?

**Comment by Noodleyman** [comment]
what if he sells feathers ;) 

just adding for the sake of saying it out loud.. don't forget option weights if you do make a change

**Comment by abrookbanks** [comment]
Yeah I had that in mind. :)

**Comment by abrookbanks** [comment]
That should do it.

**Comment by demand73** [comment]
4 decimal places is perfect. I sell Electronic Components and in this case Surface mounted resitors that weights less than a gram. Here in sweden we have ordinary letter mail and the weight limit is 50grams for the smallest fee and if i sell 100pcs of resistors it adds upp to 100grams which is double the cost but not needed cause they only weights 38grams.
Thanks for doing a wounderful job, i love CC.

**Comment by abrookbanks** [comment]
OK great the next release should now solve this for you then.
