### ISSUE TITLE
Forgot your Password errow 

### ISSUE THREAD

**Issue by Prism-Solar** [cubecart/v6#1658]
Hi Not sure if just us everyone else has the same problem updated to latest version and when our clients click forgot your password , they put there email in and get the following 

The following errors were detected:
Email not sent. Please check your email address, and try again.

**Comment by Dirty-Butter** [comment]
I tried it with the same result.

**Comment by abrookbanks** [comment]
I can't reproduce this. If you can open a support ticket I'll take a look for you. 
http://support.cubecart.com/issue-1658.mp4

**Comment by Prism-Solar** [comment]
Hi the support link does not work

**Comment by abrookbanks** [comment]
I edited it after you got the email notification. 

http://static.cubecart.com/issue-1658.mp4
