### ISSUE TITLE
Sorting by Price still doesn't work for sale items

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1659]
This has been kicking around for a while, but is still an issue in the latest verion of CubeCart.

To test, sort by price.. it doesn't work
https://demo.cubecart.com/cc6/sale-items.html

Relates to (Closed):
https://github.com/cubecart/v6/issues/821
https://github.com/cubecart/v6/issues/1264
https://github.com/cubecart/v6/issues/1432
https://github.com/cubecart/v6/issues/1487

**Comment by briansandall** [comment]
I forget which issue it was mentioned in, but it seems that the sale-items page discards all query parameters during a redirect and that is what is causing this problem.

Select any sort criteria and note the URL does not change when the page loads.

**Comment by abrookbanks** [comment]
This old chestnut. Hehe. I think we can open an award for the most "unclosable" bug of all time.

**Comment by abrookbanks** [comment]
Totally expecting this to come back again. LOL
