### ISSUE TITLE
Stats error message

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#166]
This problem probably only exists in a new store where there are no customers, orders etc but in Stats on various tabs (Best Selling Products, Search Terms, Best Customer etc) you can get the following error "Data column(s) for axis #0 cannot be of type string" - see http://awesomescreenshot.com/0104bun11b

**Comment by abrookbanks** [comment]
Thanks for this! Resolved now. The charts seem to load with a smaller width than intended between tabs.
