### ISSUE TITLE
Sorting by price uses incorrect field in sort criteria for sale items

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1660]
When you filter by "Price" whislt viewing sale items, the inventory is sorted by the field "price", but it should really be using sale_price.

catalogue.class.php
```
} else if (strtolower($search_data) == 'sale') {
	if (isset($_GET['sort']) && is_array($_GET['sort'])) {
		foreach ($_GET['sort'] as $field => $direction) {
			$order[$field] = (strtolower($direction) == 'asc') ? 'ASC' : 'DESC';
			break;
		}
	} else {
		$order['name'] = 'ASC';
	}

	if(is_array($order)) { 
		$order_string = 'ORDER BY '.key($order).' '.current($order);
	}
```

I've made a couple of adjustments specific to a customer request in the following code, 1) default sort is now by price, 2) if sorting by price it will actually sort by sale_price

This isn't the most graceful solution, but works and shows the concept... :)

```
} else if (strtolower($search_data) == 'sale') {
	if (isset($_GET['sort']) && is_array($_GET['sort'])) {
		foreach ($_GET['sort'] as $field => $direction) {
			$order[$field] = (strtolower($direction) == 'asc') ? 'ASC' : 'DESC';
			break;
		}
	} else {
		$order['sale_price'] = 'ASC';
	}

	if(is_array($order)) { 
		$order_string = 'ORDER BY '.key($order).' '.current($order);

		if(key($order) == "price"){
			$order_string = 'ORDER BY sale_price '.current($order);
		}
	}
```

**Comment by briansandall** [comment]
I would recommend having a backup plan for items that do not have a sale price, e.g.:
```
ORDER BY COALESCE(IF(sale_price=0.00,NULL,sale_price), price)
```
It's a little unfortunate that the database schema allows sale_price to be NULL when it also provides a default value of 0.00, at least when writing queries such as this.

**Comment by Noodleyman** [comment]
just use a coalesce statement ib the sql to swap out null as 0.... just in
case ;)

**Comment by briansandall** [comment]
Assuming that neither the core code nor any plugins ever set it to null, sure, but as a coder myself I would never want to bet on that. Much safer to have the additional check in the query until such time as the schema is updated.

**Comment by abrookbanks** [comment]
Thanks guys.

**Comment by abrookbanks** [comment]
Typo in commit 045daf3 "login" = "logic".
