### ISSUE TITLE
Upgrading removes REDIS parameter settings

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1662]
I did report this before but it is still happening -

When doing an upgrade on a site that is using REDIS caching, the $glob['cache'] = 'redis'; line stays intact but the $glob['redis_parameters'] is set to blank !  This means that all sites on the same server end up using the same REDIS cache database !!

**Comment by abrookbanks** [comment]
What version do you need to upgrade from to reproduce this?

**Comment by abrookbanks** [comment]
(You can check the upgrade history at ```admin_xxxxxx.php?_g=maintenance#upgrade```

**Comment by abrookbanks** [comment]
This works really well. Tested with 6.0.10 to 6.1.9 branch upgrade. 

Before Upgrade:
![screen shot 2017-08-02 at 11 18 08](https://user-images.githubusercontent.com/4520803/28869359-54e5966e-7774-11e7-859f-58f6e2e16ec4.png)

After Upgrade:
![screen shot 2017-08-02 at 11 18 18](https://user-images.githubusercontent.com/4520803/28869366-5dfbbc7e-7774-11e7-8c6a-007d6d967c1f.png)

**Comment by havenswift-hosting** [comment]
Is that really your database username and password ???

In your example you dont have the cache set to redis or have the $glob['redis_parameters'] set to a database value.  As I said, the $glob['redis_parameters'] line remains but all content is removed which effectively sets the database back to default value of 0

I dont know what versions it is a problem from / to but it has happened multiple times on different sites - I have been correcting it manually on sites that I have been upgrading.

Just checked on a site where I havent done the upgrades myself and where the problem has happened and it went from 6.1.5 to 6.1.8

**Comment by abrookbanks** [comment]
> Is that really your database username and password ???

On a temporary virtual host yes. It's destroyed already.

> In your example you dont have the cache set to redis or have the $glob['redis_parameters'] set to a database value. As I said, the $glob['redis_parameters'] line remains but all content is removed which effectively sets the database back to default value of 0

It won't make a difference.
