### ISSUE TITLE
Admin Skin missing some jQuery UI images

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1664]
some jQuery functions make use of ui-images, such as accordian. some ui-images are included with the default admin theme but there are some missing.

- ui-icons_888888_256x240.png
- ui-icons_454545_256x240.png
- ui-icons_2e83ff_256x240.png
- ui-bg_glass_75_e6e6e6_1x400.png
- ui-bg_glass_75_dadada_1x400.png

Links to files:
https://code.google.com/archive/p/vallalarblogs/downloads?page=2

This issue was noted  via a module due to trying to use the Accordian function of jQuery which references the UI images in the/js/styles/images directory of the admin skin and getting 404 errors to the above images.

**Comment by abrookbanks** [comment]
Thankyou.
