### ISSUE TITLE
Spelling error "mising"

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1665]
in the controller.admin.session.true.inc.php file.

$GLOBALS['main']->setACPWarning("Extension has mising or corrupt config.xml file.");

should be "Missing"

This should also be using language strings, it is currently hard coded as are some other errors in this file

**Comment by Noodleyman** [comment]
This still isn't using languages though? Still room for improvement?

**Comment by abrookbanks** [comment]
I didn't read the last bit.. Reopening..

**Comment by abrookbanks** [comment]
You may have noticed how much I love closing issues!!

**Comment by Noodleyman** [comment]
;)

**Comment by abrookbanks** [comment]
I'm actually going to close this. The language file will get bloated and the message really is to the developer. I'm not sure it needs translation.
