### ISSUE TITLE
Issues with sample code in a module

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1667]
I tend to add any skin changes / custom code to an install guide within each of my modules. I am currently testing out a module with 6.1.8 before release and I've noted a very odd issue.

In my install guide I use the smarty {literal} tags to prevent smarty from parsing the code. I add the code to a textarea for easy copy/paste. However, CubeCart has started to add it's own lines to this code.

Specifically, CubeCart appears to have noted the end of a form close tag </form> and before it is adding 
	`	<input type="hidden" name="token" value="b5459489d31859cdf53345529fb609ac">`

Since the install guide is now having the token auto added, when you copy/paste the sample code the token at the time is also copied in error. 

How can we prevent this from being auto added for code samples?

**Comment by abrookbanks** [comment]
Can you send me the plugin code to experiment? I don't know exactly how this is being generated in the first place.  CubeCart globally adds the session token to forms here: https://github.com/cubecart/v6/blob/master/classes/gui.class.php#L328

**Comment by Noodleyman** [comment]
Fix would be to prevent it from adding the token if the </form> tag was found within a <textarea>

I worked around the issue by linking to text files with source code in instead.

**Comment by abrookbanks** [comment]
That would make sense.

**Comment by abrookbanks** [comment]
Fancy writing me the regex for that? LOL

**Comment by Noodleyman** [comment]
I totally, 100% suck at regex... there would be tears

**Comment by abrookbanks** [comment]
I'm pretty bad at it too.

**Comment by briansandall** [comment]
I don't think you'd have to get too fancy, something like the following would probably be specific enough:
```
$regexp = '/(name="token")/';
if (!preg_match($regexp, $text_to_search)) {
  // add token
}
```

**Comment by abrookbanks** [comment]
Can you just add some logic to the smarty template files?

```
if (version_compare(CC_VERSION, '6.1.5', '<')) {
$GLOBALS['smarty']->assign('show_toekn', true);
}
```

```
{if $show_token==true}
<input type="hidden" name="token" value="{$SESSION_TOKEN}">
{/if}
```

**Comment by abrookbanks** [comment]
I'll reopen if my suggestion isn't acceptable.

**Comment by bhsmither** [comment]
Does the sample code include the `</form>` tag as part of the example, or is it there simply to make the presence of `<textarea>` standards compliant?

My Firefox will render a textarea with it being the only code in a `.html` file.
