### ISSUE TITLE
Session Token can appear twice in forms

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1668]
A very minor thing since it doesn't really cause a problem, but just an observation. If you already have code to add a hidden input to a form which contains the session token, the process which is now auto adding tokens to the end of a form is adding a duplicate.  

As a minor enhancement it would be nice to check if the token already exists, if it does don't re-add it. If it doesn't, add it. 

This doesn't impact functionality at all, but just being a little OCD about tidy code ;)

**Comment by abrookbanks** [comment]
Can you show me an example of where you see this?

**Comment by abrookbanks** [comment]
I can't add an exception. CubeCart globally adds the token to all forms. 

https://github.com/cubecart/v6/blob/master/classes/gui.class.php#L328

This means that lines like this need to be removed:
```<input type="hidden" name="token" value="{$SESSION_TOKEN}">```

**Comment by Noodleyman** [comment]
Source code:
![image](https://user-images.githubusercontent.com/10614018/27638775-36bb902c-5c0c-11e7-8f5a-c6db865c15cb.png)

View source on page load:
![image](https://user-images.githubusercontent.com/10614018/27638789-42eb4734-5c0c-11e7-9674-5758fa6b55e2.png)

I assume it's doing a find/replace for </form>, but since it's jQuery can't it be a bit smarted to check each form, look for an input named "token", if it doesn't exist then add it?

Really only minor, but everything prior to the release this was added needed the token manually adding to the source, everything there after will end up with doubles.

**Comment by abrookbanks** [comment]
Yup just remove this line:
![27638775-36bb902c-5c0c-11e7-8f5a-c6db865c15cb](https://user-images.githubusercontent.com/4520803/27638911-9ffa1a40-5c0c-11e7-9c46-a14b5c305578.png)

**Comment by Noodleyman** [comment]
Then, all versions of CubeCart prior to when this was added wouldn't work since the token is missing ;)

**Comment by abrookbanks** [comment]
I think the duplicates will have to remain then... Harmless. :)

**Comment by Noodleyman** [comment]
I did say it was a minor thing.... ;)

**Comment by abrookbanks** [comment]
Yup you did. I think we may have to leave this as is.
