### ISSUE TITLE
AllInOneShipping problem

### ISSUE THREAD

**Issue by Geoff1958** [cubecart/v6#1673]
Having problems with AllInOneShipping-1.0.7 after upgrade to 6.1.8 its started to calculate postage wrongly 

At 9.99 to 19.99 with £4 +25% 

With an order for £12.00 it charged £2.80 postage not £7.00 to the customer.

Order Summary shows correct subtotal of 12 and postage of 7 but total of 14.80 which is what was charged to customer by PayPal.
Upgraded to AllInOneShipping-1.0.10 but the General tab is blank! So gone to AllInOneShipping-1.0.8 where General tab is not blank.
Will this cure it?

**Comment by abrookbanks** [comment]
Please contact tech support if you want us to look into this.
