### ISSUE TITLE
Products are deleted when no bulk action is selected

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1674]
in the admin area, if you check the checkbox to select products and press the save button, the products are deleted.

This happens even with the bulk action undefined.

Looks like it's been there a while.  I replicated it on some older CubeCart versions as well as the latest. 

![image](https://user-images.githubusercontent.com/10614018/27373241-76cc0bb8-565f-11e7-864d-f304aaf91466.png)

**Comment by abrookbanks** [comment]
Thanks.
