### ISSUE TITLE
CubeCart just installed, Fatal Error gets me

### ISSUE THREAD

**Issue by stojkovicd** [cubecart/v6#1677]
I have just installed CubeCart last week and today need to start testing the payment structure. However, the  error 

Fatal error: Connection refused in /home/********/*******/classes/db/mysqli.class.php on line 38

appears all of a sudden. There were three visits to the site in the past week, I haven't even started setting up the store, it was all in default. Line 38 states 

trigger_error($this->_db_connect_id->connect_error, E_USER_ERROR);

What is the cure here, thank you in advance :-) I am not a programmer, but can follow instructions if it is not insanely complicated.

**Comment by abrookbanks** [comment]
Please contact tech support if you require installation assistance. 

https://www.cubecart.com/technical-support
