### ISSUE TITLE
Minimum PHP version needs to be reviewed

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1678]
It's becoming more and more painful to have to support old versions of PHP in modules. It would be very helpful if the supported PHP versions of CubeCart for new releases referenced the PHP lifecycle.

http://php.net/supported-versions.php

with this in mind, curently PHP 5.6 should be the minimum supported version until the end of 2018.

**Comment by abrookbanks** [comment]
I would love to see this but from experience keeping up with PHP life cycle just bites you on the ass. After we forced PHP 5.4 we saw a dramatic decline in new stores month on month as so many defaulted to PHP 5.2. On those grounds I don't think this is achievable.

**Comment by Noodleyman** [comment]
Would it be possible to add a warning to the admin dashboard if using PHP 5.5 or lower,  recommending that PHP be updated?

**Comment by abrookbanks** [comment]
That's not such a bad idea. :)

**Comment by abrookbanks** [comment]
Min required version vs recommended min version.

**Comment by Noodleyman** [comment]
You've put PHP 7.1 as the recommended version, but this might cause a lot of issues with modules since 7.1 doesn't yet support IonCube loaders. Might be worth recommending as a minimum 5.6, or 7.0

**Comment by abrookbanks** [comment]
Oh ok without 3rd party extension CubeCart works really well on PHP 7.1.
