### ISSUE TITLE
Hook Request - catalogue.class.php

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1679]
within the searchCatalogue function

FIND:
```
$this->_category_count  = (int)count($count);
$this->_category_products = $sale;
```

AFTER ADD:
`foreach ($GLOBALS['hooks']->load('class.catalogue.search_catalogue.sale_items.post') as $hook) include $hook;`

This allows for manipulation of the sale items search criteria, entirely replacing it with something custom if required (which is what I needed)

**Comment by Noodleyman** [comment]
@abrookbanks, this one was closed without a fixed link? Just checking if it was added?

Thanks,

**Comment by abrookbanks** [comment]
Yup I missed the hash tag thanks for checking https://github.com/cubecart/v6/commit/5f127108aa9d5d881d5a7d0031a147c510fd564e
