### ISSUE TITLE
"$TRIAL_LIMITS" show in login.php file of admin templates

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#168]
As above...

**Comment by SemperFiWS** [comment]
File:
/admin/skins/default/templates/login.php
Code:
	  {if $TRIAL_LIMITS} 
  		<p>
  		<strong style="display: inline-block; width: 55px;">Version:</strong> CubeCart Lite (<a href="{$TRIAL_LIMITS.url}">Upgrade</a>)<br>
  		<strong style="display: inline-block; width: 55px;">Limits:</strong> {$TRIAL_LIMITS.orders} orders / {$TRIAL_LIMITS.customers} customers / {$TRIAL_LIMITS.administrator} Administrator<br>
  		</p>
  	  {/if}

File:
/admin/skins/default/templates/settings.index.php
Code:
            {if $MOBILE_DISABLED}
            (<a href="{$TRIAL_LIMITS.url}">Upgrade</a>)
            <input type="hidden" name="skin_style_mobile" value="mobile">
            <input type="hidden" name="skin_folder_mobile" value="blue">
            {/if}

File:
/admin/skins/default/templates/upgrade.index.php
Code:
  <p>Right now your store uses &quot;CubeCart Lite&quot; the free version of CubeCart which has restricted features and a limit of {$TRIAL_LIMITS.customers} customers or {$TRIAL_LIMITS.orders} orders (whichever comes first) and {$TRIAL_LIMITS.administrator} administrator. Below is our website showing our pricing and links to further information.</p>
  <p>Please note that the software license key can be added in the &quot;Advanced&quot; tab of your stores <a href="?_g=settings#Advanced_Settings">General Settings</a>.</p>
  <iframe src="{$TRIAL_LIMITS.url}" width="100%" height="500" style="border: 3px solid grey;"></iframe>

**Comment by SemperFiWS** [comment]
Now just the files where 'TRIAL_LIMITS' is still present:
- /admin/skins/default/templates/login.php
- /admin/skins/default/templates/settings.index.php
- /admin/skins/default/templates/upgrade.index.php

**Comment by abrookbanks** [comment]
Thanks for this those files have been fixed/deleted as appropriate.
