### ISSUE TITLE
CSS Syntax

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1688]
In the foundation skin, cubecart.css, lines 329-336:
```
  .small-collapse {
    padding:0;
    margin:0;
    .columns {
      padding:0;
      margin:0;
    }
  }
```
I believe the nested rules are illegal.

That is, `.columns` is nested in `.small-collapse`. (This is working syntax for SASS/LESS, but probably not for 'pure' CSS.)

**Comment by abrookbanks** [comment]
Thanks Brian, well spotted! Great to see you back. Hope all is good. :)
