### ISSUE TITLE
Shipping Error Message

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#169]
Going to these:
/index.php?_a=basket
/index.php?_a=checkout
with no shipping modules installed returns this error:
Unfortunately there are no suitable shipping methods available for your order. This may be because the total weight of your order is too high or we cannot ship to your country. Please contact a member of our staff for any further inquiries.

Sure, that makes sense seeing there is no shipping modules.
But would setting shipping to 0.00 (displayed or not) in this scenario (no modules) so customers can complete checkout be a better solution?

**Comment by abrookbanks** [comment]
The introductory quick tour shows the merchant how to enable a shipping module from the marketplace. CubeCart should really default to this error if no shipping methods are configured as most merchants selling tangible goods will need to charge shipping.

Skip to: 8 mins https://vimeo.com/118638908

**Comment by SemperFiWS** [comment]
What about those stores that do not charge shipping, tangible or digital?

**Comment by abrookbanks** [comment]
They can enable the setting "Allow physical orders even if no shipping options are available".

**Comment by abrookbanks** [comment]
I put a note in the tutorial movie.

**Comment by SemperFiWS** [comment]
Perfect, thank you.

**Comment by abrookbanks** [comment]
I have also embedded this movie into the final joyride tooltip on first login.
