### ISSUE TITLE
Sessions.gc_maxlifetime

### ISSUE THREAD

**Issue by keat63** [cubecart/v6#1692]
I'm not sure if I need to log this, or whether Al has it logged elsewhere.
Working with Al, we discovered that PHP setting sessions.gc_maxlifetime may be causing issues with stale browsers.    If a browser window is left open and untouched for around 40 minutes, the cart contents are deleted. Cart contents can be deleted without the end user noticing, resulting in null cart contents in the database, store and customer emails.
Or if using the foundation skin, a CSRF warning is generated and then the cart contents are deleted.

The standard php settings are 1440 (24 minutes).
Increasing this threshold seems to fix the issue, however, most end users will not have access to php.ini, so is beyond the control of most cart admins.
I believe sessions.class.php should be handling this, but it doesn't appear to do so, or certainly not in my case and 2 known others.

This may also be related to an issue which has been reported to me by our admin staff, where they have to log in to the admin side of the cart after returning back to their browser after an abscence.

**Comment by abrookbanks** [comment]
The only solution is to create a custom session save path then write a bespoke script on the server to manage this session data. This is way above most of our users ability, they are unlikely to have server level access to be able to do this and as a script isn't able to manage this. 

I suppose the storage engine could be changed to database, redis or memcache.

**Comment by abrookbanks** [comment]
My development store is using the includes/extra folder to store session data. This is with a gc_maxlifetime of 604800 and it is purging well. (I tested it by changing it to 30 seconds).

CubeCart will only use the includes/extra folder if the default PHP session path is not writable. If it is writable which in most cases it will be then the session data will be purged by the server (cPanel maybe) at a set time specified outside of CubeCart. So the solution is to use a custom session path?

No. This has problems too. In cPanel the session file permissions won't have the right permission to be able to delete them and as a result the directory will just grow and grow. 

So.. what can we do? Not a lot.... Maybe advanced users could use the custom session save path then create a bash script for garbage collection.

**Comment by abrookbanks** [comment]
Added ability to specify session save path with not about garbage collection.

**Comment by abrookbanks** [comment]
We need protection against null cart items.. reopened.

**Comment by havenswift-hosting** [comment]
>>I suppose the storage engine could be changed to database, redis or memcache.

This is 100% the answer and the subject of another open issue - it would solve this issue, plus give all the speed benefits (at least from memory based engines) of better session storage

**Comment by abrookbanks** [comment]
Very few stores have memcache or redis available. I see it will benefit your clients. :)

I'm not sure about the performance issues with database storage.

**Comment by abrookbanks** [comment]
I think we have a solid solution here now. 

We have the ability to set a custom session save path which will allow CubeCart to work with its gc_maxlifetime and for those stores which don't we have protection against "null" items in the cart by checking the validity of basket data prior to building the order.
