### ISSUE TITLE
Clone a product , does not match and link to store setting

### ISSUE THREAD

**Issue by Stephan35** [cubecart/v6#1693]
Hello,
Using last cubeart 6.xx
I am a new user, filling product.
I wished to clone a product, this doesn't do so, and redirect link to store settings.
Do on each 3 product available ...
Best regards

**Comment by keat63** [comment]
Maybe this should have been posted on the forum https://forums.cubecart.com/.
Clone product needs to be enabled in store settings/extra.

**Comment by Stephan35** [comment]
Yes works fine now ...
Maybe clone icon can be disable when option is not activated ?
And over Tip to tell how to ?
thanks
regards
