### ISSUE TITLE
Email Templates and HTML Comment Tags

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1694]
In definitions.xml, group='email', string='important', notice is given that `{foreach}` dynamic content need to be enclosed in HTML comment tags.

Yet, email_en-GB.xml has not been modified as such.

I do not find any SQL update script to change what may be in the database already, nor any code in an admin script to change this on the fly.

The editor will move the {foreach} block for the **sole** reason that this content (which looks like regular - but protected - text) is not inside a cell, nor is claimed to be tag parameters. This content sits between row blocks and strict HTML says this is an illegal place to put text. So, the editor moves it to the closest legal place.

That is to say:
```
<tr><td>{foreach $a $b} Hi! {/foreach}</td></tr>
```
should work. But this does not:
```
{foreach $a $b}<tr><td> Hi! </td></tr>{/foreach}
```
not without putting them in HTML comments.

**Comment by abrookbanks** [comment]
This is how it is supposed to be. 
https://github.com/cubecart/v6/blob/master/admin/sources/documents.email.inc.php#L486-L491

CC will automatically brace specific loop tags with HTML comments to satisfy the rich text editor but store them correctly without by stripping HTML comments on save.

**Comment by bhsmither** [comment]
Line 345 implies it will be a really bad idea to have HTML comments (such that to survive the rendering) in email templates. The delimiters will be removed exposing the text. The delimiters in this case will not be added back, possibly causing some consternation.

**Comment by abrookbanks** [comment]
Some more complex regex to remove the comment tags if there are no curly braces between could be added I suppose. This is an interesting post but I don't think I will make any changes. 

I've not seen any problems arising from this yet.
