### ISSUE TITLE
Dashboard Questionable Code Execution Sequence

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1697]
There is also a database code problem - explained elsewhere.

In dashboard.index.inc.php, near line 160 starts a block of code that gets executed only if the logged in admin has permission to read.

Assume no permission to read. That means a number of variables useful and used elsewhere do not get set. For example, line 198 where `$sales` gets set from a query that is now malformed - `$last-year-start` is not defined.

Suggest declaring all the calendar-based variables get set before line 160.

Also suggest deciding if showing the chart is permitted for an admin with no Read Statistics permission. Not that it does, as the HTML for the chart is in the `QUICK_STATS` block. But the controller code to fetch and process the data for the chart is not.

**Comment by abrookbanks** [comment]
Fixed with https://github.com/cubecart/v6/commit/ea06cc48745d6ce9efef67572dafeea6a8458cad

Thanks.
