### ISSUE TITLE
Superfluous Code

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1700]
In cubecart.class.php, near line 2387:
```
$per_page = 15;
$page = (isset($_GET['page'])) ? $_GET['page'] : 1;
$order_count = $GLOBALS['db']->select('CubeCart_order_summary', false, array('customer_id' => $GLOBALS['user']->get('customer_id')));
$order_count   = count($order_count);
```
This query for `$order_count` does very little. 

There is better coding relying on SQL_CALC_FOUND_ROWS and DB->pagination() using the results of SELECT FOUND ROWS.

Also, suggest a global programming strategy of using _false_ for the columns argument (line 2389 vs. line 2392) unless there is a _very good reason_ for not doing so. This gives complete info that follow-on hooks may appreciate having.

**Comment by abrookbanks** [comment]
Reopening this as there are lots of cases... I'll do some more but probably won't catch them all.

**Comment by abrookbanks** [comment]
I've done a few. I noticed that if the first argument sent to Database->pagination is false CubeCart will look for $this->_found_rows.

**Comment by abrookbanks** [comment]
Closing for now but I'll keep an eye out for more on my journeys.

**Comment by bhsmither** [comment]
`Database->pagination()`, if used, must be called immediately after the call to `Database->select()` which has the per_page argument. Any calls to `Database` methods between those two calls will likely affect `_found_rows`.

**Comment by abrookbanks** [comment]
That's right. I didn't see any.

**Comment by bhsmither** [comment]
I say again:
`Database->pagination()`, if used, must be called immediately after the call to `Database->select()` which has the per_page argument. Any calls to `Database` methods between those two calls will likely affect `_found_rows`.

For example, in settings.errorlog.inc.php, lines 63 and 86 were changed in how `$count` is obtained. Yet, these calls to the Database class were not moved to **immediately** following the call to the `select()` method.

Working through `$error_log` and `$system_error_log`, a call to `formatTime()` is made. This CubeCart function calls `$GLOBALS['config']->get()`, which _could_ call `_fetchConfig()`. The `_fetchConfig()` **will** access the database. This will change `Database->_found_rows`.

If it is desired to use the SQL_CALC_FOUND_ROWS, I stress it is **very important** to get the rows count **immediately** following the `select()` call.

**Comment by bhsmither** [comment]
It might even work to simply move:
```
$GLOBALS['smarty']->assign('PAGINATION_ADMIN_ERROR_LOG', $GLOBALS['db']->pagination(false,
```
to follow `select()` and do away with assigning to `$count`. Where feasible.

**Comment by abrookbanks** [comment]
Thanks Brian. I'll take a look at this at some point.

**Comment by abrookbanks** [comment]
Sorted.. there are still other areas this can be implemented however.
