### ISSUE TITLE
Debug Red Query May Not Be an Error

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1705]
In commit https://github.com/cubecart/v6/commit/f998d334b729726e5ce7003ced3aa7a3893d7976, some code was added to the Debug class;
```
if($type=='error' || preg_match('/CubeCart_system_error_log/',$message)) {
  $tag = empty($tag) ? 'ERROR' : 'ERROR - '.$tag;
  $colour = 'FF0000';
}
```
Presumably to flag the query that INSERTed data to this table.

But, since other queries can be made against this table, these other red-flagged entries in the Debug list may be misleading.

For example, in admin, Maintenance, when issuing `SHOW TABLE STATUS` and `SHOW INDEX FROM`, those queries will show in red and have ERROR. As well as any SELECT, DELETE, and TRUNCATE query to show the System Error Log records.

Suggest looking for INSERT only:
```
preg_match('/^INSERT .*CubeCart_system_error_log/',$message)
```

**Comment by abrookbanks** [comment]
Thanks. That works really well.
