### ISSUE TITLE
Javascript Crash on Email Log

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1706]
If a store comes from CC5 (latest version) to CC6, in the database table CubeCart_email_content, in the 'subject' column, these phrases may still have leading and trailing whitespace. (See CC5's email_definitions.xml file.)

Suggest issuing a query in an update script to change all email 'subject' columns in all tables that hold email contents (that would include CubeCart_email_log, although not so much a problem with CubeCart_newsletter) to strip whitespace.

In statistics.emaillog.php, this part:
```
onclick="{literal}$.colorbox({title:'{/literal}{$log.subject} ({$LANG.common.html})'
```
will result in the HTML:
```
onclick="$.colorbox({title:'
      New Order #170814-143538-1487
     (HTML)'
```
Javascript crashes with "SyntaxError: unterminated string literal" when clicking on the links in the Read column of the Email Log page.

**Comment by abrookbanks** [comment]
Thanks Brian!
