### ISSUE TITLE
Country May Not Have States - But Enforced Anyway

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1708]
See https://forums.cubecart.com/topic/52776-customize-fields-on-order/

In User->formatAddress(), the logic at line 457 imposes the idea that if there is a 'country', there must also be a 'state'.

That is not always true (apparently).

Specifically (line split apart for readability):
```
(
    (empty($address['state']) && !empty($address['country']))
  ||
    ($GLOBALS['db']->select('CubeCart_geo_zone',false, array($state_field => $address['state']))==false) 
     && $GLOBALS['db']->select('CubeCart_geo_zone',false, array('country_id' => $country_id))
)
```
Either of these two expressions being true means there is a problem.
1. Have some kind of 'country' and missing any kind of 'state'.
2. The 'country' was found in geo_zone (means it has states) and the 'state' name|id cannot be found.~

The first expression seems unreasonably over-broad.

And, the whole point of this test is to make sure there is a valid state. See #1290.

Suggest that an initial test is made to make sure the 'country' is in geo_zone. If not, then do not bounce out with Error:check_state.~~

~ Although this could be written as one query, the odds of each separate query being in the cache is high.
~~ Working on modifying the skin and elsewhere to not require a state.

**Comment by Dirty-Butter** [comment]
I have found this with a few orders over the years - would love to see a good fix!

**Comment by abrookbanks** [comment]
Ok so I changed the logic. If state is empty, country is not but there are states to choose from. 

My mind is boggling.. if someone can confirm this I would be grateful.

**Comment by abrookbanks** [comment]
Fix here: https://github.com/cubecart/v6/commit/0e410d196622a268b9dcdc6b8798e4b8da2e40c2 (issue ID typo)

**Comment by abrookbanks** [comment]
On hindsight I've reverted this as state is a required field and the whole point of this block of code was to help fix stores upgraded from v3 or v4 that had "bad" values in the database for state. 

I agree in that we need to make CubeCart more flexible over which fields are required or not but right now state is required and I don't want to undermine the whole reason for the logic behind this bit of code.
