### ISSUE TITLE
Adding Digital Product - Incorrect Product Type When Using Custom File Path

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#171]
Adding a new digital product via entering the file path/name.ext directly in the Custom File path field (digital_path) creates the product as tangible, not digital.

This happens when using either the 'Save' or 'Save & Reload' buttons.
Going back and editing the product, it does set the product to digital correctly.

**Comment by SemperFiWS** [comment]
Adding something like this:
		// Update product
		if (isset($_POST['download']) || !empty($_POST['digital_path'])) {
			if (!empty($record['digital_path'])) {
				$record['digital'] = 1;
			} else {
				$record['digital'] = 0;
				foreach ($_POST['download'] as $key => $enabled) {
					if ($enabled) {
						$record['digital'] = $key;
						break;
					}
				}
				if (!$record['digital'] && isset($_POST['download'][$old_product_data[0]['digital']]) && !$_POST['download'][$old_product_data[0]['digital']]) {
					$record['digital'] = 0;
				} elseif (!$record['digital']) {
					$record['digital'] = $old_product_data[0]['digital'];
				}

			}
			unset($_POST['download']);
		} else {
			$record['digital'] = 0; // no path nor list of files
		}

into the add product section of '/admin/sources/products.index.inc.php' should correct the issue.

**Comment by bhsmither** [comment]
I think just this much should work:
```
      if (!empty($record['digital_path'])) {
        $record['digital'] = 1;
      } elseif (isset($_POST['download']) {
        foreach ($_POST['download'] as $key => $enabled) {
          if ($enabled) {
            $record['digital'] = $key; break;
          }
        }
      }
```
Why didn't I see that? This applies to CC5 as well.

**Comment by abrookbanks** [comment]
Excellent help chaps. Brians fix works well from my tests.
