### ISSUE TITLE
USA tax

### ISSUE THREAD

**Issue by bsapackman** [cubecart/v6#1710]
If you live in usa tax only by your home state or if you have other state work from

if you check out  shipped items in North Carolina (state in USA) then tax

then rest will not be tax      way program made will not let update will not work

1 tax only state you need
2 rest will be no tax

**Comment by abrookbanks** [comment]
Please submit a technical support request if you require any further assistance with this.

**Comment by Noodleyman** [comment]
just found this ticket, I've raised other issues related to this in the past. It's not a bug, but definately an enhancement. was taking another look as this just came up in one of my ongoing projects.
