### ISSUE TITLE
Hook Request - products.options.inc.php

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1711]
FIND:
`$page_content = $GLOBALS['smarty']->fetch('templates/products.options.php');`

ADD BEFORE
`foreach ($GLOBALS['hooks']->load('admin.products.options') as $hook) include $hook;`

REASON:
Allows any of the previously constructed arrays to be manipulated before loading the template file

**Comment by abrookbanks** [comment]
Please note I used `admin.product.options` not `admin.products.options`
