### ISSUE TITLE
Recaptcha v1 issues

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#1714]
I came across this issue in v6.1.8 and still have same issue in upgrade whilst developing a plugin.

I spent over 60 hrs trying to find the issue within my plugin before I realized it was a cubecart bug after testing on a clean 6.1.9 install.  Although not recommended, whilst it is an available option it needs to work correctly. 

If user enter incorrectly (register, contact form, review etc) they receive error message but if user only enter 1st part of image and submit it accepts without error.

**Comment by abrookbanks** [comment]
Thats how reCaptcha v1 works. It only validates against the first work. The second one is not verified yet and those solving it help towards what the valid answer will be when it is shown as a first word.

Test here too: http://www.spectrum-nashville.com/reCAPTCHA/demo.php

**Comment by abrookbanks** [comment]
https://stackoverflow.com/questions/17820472/recaptcha-valid-if-first-word-is-correct
https://stackoverflow.com/questions/3309864/recaptcha-accepting-one-word-out-of-two
