### ISSUE TITLE
Bug and improvements to Zones (States)

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#1720]
Using Adddressbook as example

Currently if User select Country with no Zone (States/County) it insert a textbox for user to enter Zone.
If User select Country with Zones these populate the Zone dropdown, forcing a user to select from dropdown.

So what happens if the Zone the User requires is not there in dropdown? - Bug

You require an Other option at the bottom of dropbox that when selected it replace the dropbox with textbox so User can enter their Zone.  Ideally you need to toggle back to dropbox in the event Other was selected for no other reason than to see what happens, so need a way of going back.

This then raises the issue of populating the Zones table.  It is very difficult to obtain a free accurate Countries/Zones database.  Accurate versions are available however this can be costly.  I like many small business am happy to populate this on a as needed basis.

As Needed - therefore on Submit above form if textbox is filled then it should also send these details (create record) to Zone table (Country ID and Zone Name).  The Status can be 2 (pending) & a Note sent to Administrator that new Zone has been created with Address ID.  The Administrator then confirms Zone details (existence, spelling, etc), adds abbreviation and changes status to 1.  If changes have been made to Zone Name it also Update the Zone (state) in for the Address ID in Addressbook table.  Ideally validation for duplicate Zone Names with same Country ID.  Currently when User enter a Zone in Addressbook, how do I know it even exist? Is it fictional?

Similarly the same should apply when adding addresses through Admin with No Zones or Other selected.

This allow the adding of Zones on a as needed basis whilst having a verification method.

This also ensures the integrity of both Addressbook and Zones tables.

**Comment by abrookbanks** [comment]
This is a really cool idea. I like it.

**Comment by abrookbanks** [comment]
Please see: https://features.cubecart.com/topic/bug-and-improvements-to-zones-states

We will reopen this if/when we come to develop this.
