### ISSUE TITLE
Certain Complex MySQL Database Passwords May Fail On Install

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1722]
When initially installing CubeCart, the use of certain complex MySQL passwords will fail.
e.g.
```L}e;x&N@v~m7```

If that password is used, you will get this error:
Incorrect database host, username, and/or password. Access denied for user 'someuser'@'localhost' (using password: YES)

But if you use the same username + password to access the database directly (e.g. using adminer) it does actually work.

**Comment by abrookbanks** [comment]
This is not reproducible on a basic LAMP setup without mod_security or Suhosin. 

I expect that one of those two technologies is disallowing one of more of those characters in the post data.
