### ISSUE TITLE
Admin - Customer Form Submissions - CSRF Error

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1728]
Steps To Replicate
1. Load up any form page in the store admin (e.g. edit product).
2. Go to and submit any form on the customer side of the store (e.g. add product to basket).
3. Go back to the form page in admin from step 1.
4. Submit that form and you will get:
Security Alert: Possible Cross-Site Request Forgery (CSRF) or browser back button used.

**Comment by abrookbanks** [comment]
Thanks Daren.

**Comment by abrookbanks** [comment]
Fixed with https://github.com/cubecart/v6/commit/8d8b359f3032c968d9afe9f3b3f0af3bd450f11f
