### ISSUE TITLE
Creating A New Option Attribute Sets Its Priority To 0

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1729]
Steps To Replicate
1. Go to the product options page in the store admin.
2. Add X amount of option groups.
3. Go to the 'option attributes' tab.
4. Select any option group from the drop down.
5. Enter a new option attribute name.
6. Click the plus symbol.
7. Click save.

If you then look for this entry in the 'CubeCart_option_value' table, the 'priority' field is set to 0.

You also end up with the same problem when adding multiple option attributes to a group (instead on just one) following the steps above.
In that scenario, all new entries end up getting a 0 for their 'priority' value.

To correct the problem (either scenario) you need to adjust the order (if required) then click on save again.
Doing the second save will then set all the 'priority' values correctly.

**Comment by abrookbanks** [comment]
Thanks Daren.
