### ISSUE TITLE
Feature Request - Combine Registrations

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#173]
In both CC5/CC6 you have:
Standard Registration - /index.php?_a=register
Checkout Registration - /index.php?_a=confirm

Why not go with a single registration page where all required details are collected in one location?

**Comment by bhsmither** [comment]
I think, at **confirm**, you need to be *almost ready* to make payment on a cart that has something in it.

**Comment by abrookbanks** [comment]
Thanks for the suggestion. Right now the PHP code is recycled with OO classes for both parts. The templates do need to be different and have to duplicate some of the fields.
