### ISSUE TITLE
Possible Product Images Bug #2 - Main Product Image Not Expanding

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1731]
Steps To Replicate
1. Add or edit a product in the store admin.
2. Set its main image, using one set of dimensions for the original image (e.g. 400px X 400px).
3. Assign additional images that have a height dimension taller than the main image (e.g. 400px X 600px).
4. Go to this product on the customer side of the store.

The main image will be displayed correctly.
The thumbnails for the additional images will also be displayed correctly.

However, swapping the main image with any of the additional images results in the additional image only getting partially displayed.

This issue doesn't appear to occur when using the 'element.product.vertical_gallery.php' template.
Only when using the 'element.product.horizontal_gallery.php' template.

**Comment by SemperFiWS** [comment]
As a test, I comment out this line:
```$('.horizontal a.open-clearing').css({'min-height':ip_height+'px', 'max-height': ip_height+'px'});```
in the '2.cubecart.js' file.

After doing that, the issue above no longer occurs.
As an added bonus, the issue outlined in #1730 also no longer occurs.

**Comment by abrookbanks** [comment]
I can't reproduce this. I followed your steps exactly but added an extra image of 400x700px for good measure. On rollover none of them get truncated. Please see movie below...

**Comment by abrookbanks** [comment]
Please note that the image dimensions are correct. The preview tool in the admin CP has a max height.  
http://static.cubecart.com/github-1731.mp4

**Comment by abrookbanks** [comment]
Closed but I will reopen if I did something wrong.

**Comment by laruetactical** [comment]
The video has the thumbnails as vertical option the problem happens when they are horizontal. The screenshot I attached shows how it cuts off the bottom instead of just shrinking the image. 
![blw](https://user-images.githubusercontent.com/1591043/30875092-f2e61f32-a2b7-11e7-9c5d-e364ef06a5dd.jpg)
You can see it at https://boatliftworld.com/store6/3000-lb-sling-boat-lift.html

**Comment by bhsmither** [comment]
This harkens back to Issue #1449.

**Comment by abrookbanks** [comment]
The whole reason the vertical layout was introduced was to make it better for irregular image sizes. 

The thumbnails look all wonkey too. Personally I would say you are best off uploading images with the same proportions to keep a professional look but I'll see if there is a solution here.

**Comment by abrookbanks** [comment]
Uploading my test images here so I don't lose them again.... 
![400x800](https://user-images.githubusercontent.com/4520803/30902939-133a53fe-a365-11e7-9d6e-081516cff9e4.jpg)
![400x600](https://user-images.githubusercontent.com/4520803/30902942-1345ebd8-a365-11e7-810c-608e72513707.jpg)
![400x400](https://user-images.githubusercontent.com/4520803/30902940-133f6cae-a365-11e7-8d85-d69e9d7d8a46.jpg)

**Comment by abrookbanks** [comment]
Turned out to be an very simple fix! Thanks for your patience with me.
