### ISSUE TITLE
Duplicate Fields In Checkout

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1732]
When in checkout, the fields from both of these:
- content.checkout.medium-up.php
- content.checkout.small.php
are present, with only those applicable displayed on the actual screen.

So even though one set is 'hidden' they still get rendered then submitted upon submitting the form.

Is it possible to only load the applicable template only, depending what is actually required?

**Comment by abrookbanks** [comment]
> Is it possible to only load the applicable template only, depending what is actually required?

No because the server side can't determine viewport size. We are dependant on JS form the client side. Right now this loads but the fields are all disabled so this shouldn't be an issue.

**Comment by abrookbanks** [comment]
This is a better solution now.

**Comment by briansandall** [comment]
Is there a way to put the content back if, say, the user changes veiwport size?

Compare to toggling the disable status on form inputs which is trivial in such a case. I'm not sure the current solution is an improvement over the previous.

**Comment by abrookbanks** [comment]
We'd have to add a listener on resize. I'm not sure this is a problem from small to medium or vice versa but could be for medium up.

**Comment by briansandall** [comment]
Agreed - just playing devil's advocate and pointing out that the current solution makes it more difficult to handle that situation, should the need arise.

**Comment by abrookbanks** [comment]
All good. I'd had the same thoughts but decided it would be ok like this. In reality maybe it could be written better altogether with one block of HTML for all.
