### ISSUE TITLE
Structured Data needs improving

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1733]
Review products, breadcrumbs, company info, search etc..

**Comment by havenswift-hosting** [comment]
Is there really a need when we have a perfectly good plugin that works well - surely time would be better spent adding features that cannot (easily) be done with plugins or have been outstanding for a while ?

**Comment by abrookbanks** [comment]
Yes for a few reasons;

1. CubeCart already had this functionality but it was fairly limited.
2. As you have pointed out its easy. This took all of about 30 mins.
3. The demand for this has increased recently. If we service it out the box we may have more happy users. 

Sorry if I'm stepping on your toes here but I want to enhance it further.

**Comment by havenswift-hosting** [comment]
Doesnt really encourage the very limited number of developers working with CubeCart to develop plugins 
 does it !  In addition, it deprives you of revenue via the marketplace as that is one plugin that will not sell again

**Comment by abrookbanks** [comment]
This was a basic feature long before you created that extension and version 6 was developed with the intention of having this integrated as standard. Basic structured data has been in version 6 since first launch. It was always the intention to improve on this. 

The snippet of code below is from the content.product.php file in 6.0.0.

```
<div itemscope itemtype="http://schema.org/Product">
   <form action="{$VAL_SELF}" method="post" class="add_to_basket">
      <div class="row">
         <div class="small-12 columns">
            <h1 itemprop="name">{$PRODUCT.name}</h1>
         </div>
      </div>
```
