### ISSUE TITLE
IP Address capture - should also capture IPv6

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1735]
Since IPv6 is getting more use now, CC should check for IPv6 and IPv4 IP's rather than just IPv4

**Comment by abrookbanks** [comment]
`$_SERVER['REMOTE_ADDR']` should pick out IPv6 and IPv4.

**Comment by abrookbanks** [comment]
The database is ready for IPv6 and $_SERVER['REMOTE_ADDR'] already compatible. No changes should be needed.

e.g. var_char(45) https://github.com/cubecart/v6/blob/master/setup/db/install/structure.sql#L9
