### ISSUE TITLE
enhance the shortening of descriptions

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1736]
descriptions which are cut short and have heliip added needs to be refinded to make it a little smarter. Instead of simply cutting off the string at the Nth character, it should look backwards for the first whitespace and trim from there. 

This avoids situations where special encoded characters may get trimmed, for example &nbsp; being cut to &nb&hellip;

**Comment by Noodleyman** [comment]
Here is how I fixed it in catalogue.class.php

FIND:
$product['description_short'] = substr($short_description, 0, $product_precis).'&hellip;';

REPLACE WITH:
$product['description_short'] = substr(substr($short_description, 0, $product_precis), 0, strrpos(substr($short_description, 0, $product_precis), " ")).'&hellip;';

**Comment by abrookbanks** [comment]
```
$product['description_short'] = substr($short_description, 0, $product_precis).'…';
```

That doesn't exists in the latest version?

**Comment by Noodleyman** [comment]
slightly different in the latest version because it's wrapped with strip_tags.

$short_description = strip_tags($product['description']);

same code adjustment applies though, just needs tag stripping added ;)

**Comment by abrookbanks** [comment]
But the HTML has already been decoded so there should be no HTML to cut in half?

**Comment by abrookbanks** [comment]
e.g. `Shortened text &` should show as `Shortened text ` and not `Shortened text &am`

**Comment by Noodleyman** [comment]
looks like it's already sorted in the latest version then :)

**Comment by abrookbanks** [comment]
Kool :) Thanks anyway. :)
