### ISSUE TITLE
Quantity Discounts Error on Checkout Page

### ISSUE THREAD

**Issue by Vicky-VCC** [cubecart/v6#1737]
I have a product with quantity discounts, if the customer buys one, the total is £2.99, if the customer buys two it's £5.29. So, the customer selects a quantity of one item within the product screen. They then go to the checkout and it displays the correct unit price for that selected product (£2.99). However, if the customer decides to increase the quantity to two, the unit price is displayed as £5.29 but, because the user set the quantity to two, the checkout multiplies the unit price by two giving a total of £10.58. This is incorrect, the total should read £5.29.

**Comment by abrookbanks** [comment]
So you need to enter the value for two or more as £2.65 not £5.29.

**Comment by Vicky-VCC** [comment]
It's not a very intuitive solution for a customer. I think the most professional solution is for me to stop using the quantity discounts option. Thanks for your time.

**Comment by abrookbanks** [comment]
If you can suggest how it can be more intuitive it will be considered for a future version. Most websites show quantity discounts as the price per item so you can compare the cost or one item at various price points. 

e.g. https://www.screwfix.com/p/lap-13a-2g-sp-switched-socket-3-1a-2g-usb-charger-white/4087p

CubeCart works the same as that.

e.g. https://demo.cubecart.com/cc6/3d-glasses-tdg-br200/w.html

**Comment by abrookbanks** [comment]
Following on your website would show:

1 = £2.99
2+ = £2.65

I think thats very clear. :)

**Comment by Vicky-VCC** [comment]
Yes, that makes more sense than the way I was wanting to display it. I was trying to give the customer the total cost pre-checkout but I can see how that can cause problems. Thank-you for clearing that up for me.
