### ISSUE TITLE
Recaptcha - Human Checkbox

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#174]
When Enable reCAPTCHA is set to Human Checkbox, with the recaptcha key fields empty, the 'Verify you are a human' heading is displayed in checkout.
But without anything for the customer to verify.

This results in the:
The verification code was incorrect. Please try again.
error message being displayed.

But setting it to the old style will show the customer the verify just fine.

The help page in admin simply states:
Enable reCAPTCHA: Enable the spam prevention reCATPCHA boxes on the registration, review submission and tell-a-friend pages. 

Possible Solution #1
Use the coded recaptcha key if empty, if this is possible.

Possible Solution #2 
Make the key fields in admin required if that option is selected.

**Comment by abrookbanks** [comment]
> Possible Solution #1
Use the coded recaptcha key if empty, if this is possible.

This doesn't work from my testing which is a shame. 

> Possible Solution #2 
Make the key fields in admin required if that option is selected.

This is the only solution.

**Comment by abrookbanks** [comment]
![screen shot 2015-02-04 at 11 13 31](https://cloud.githubusercontent.com/assets/4520803/6039483/6411b07e-ac5f-11e4-8adb-052fea9c716a.png)
