### ISSUE TITLE
product select more then one category not working properly

### ISSUE THREAD

**Issue by harshitnayak45** [cubecart/v6#1740]
Hello,
When i select a product for multiple category, and then show on front-end then product category id shows primary category id, but should be show all category ids which ever selected for product.

Thanks

**Comment by abrookbanks** [comment]
I'm sorry I don't understand. 

> and then show on front-end then product category id shows primary category id

Where does it show primary category ID?

**Comment by bhsmither** [comment]
A product must gave a primary category assigned to it. The product may also have secondary categories assigned to it.

When asking CubeCart (on the storefront) to show products in any of these secondary categories, the product having had that secondary category assigned will get listed.

However, viewing the View Product page of that product, the primary category (and its path) gets added to the breadcrumbs.

I believe the OP is confounding the category's 'id' with the category's 'name'.

I also believe the OP is wanting to have the breadcrumb show the path through the categories that the customer took to get to the View Product page. (I have given some little thought to trying this.)

**Comment by abrookbanks** [comment]
That makes sense. Certainly possible. Feature request to be opened..

**Comment by abrookbanks** [comment]
https://features.cubecart.com/topic/show-breadcrumb-based-on-path-taken-when-product-is-in-multiple-categories

**Comment by harshitnayak45** [comment]
Still have problem, I just want to know. when fetched all product by category then and also print $product.cat_id then that return primary category id. Not return current category id.

**Comment by abrookbanks** [comment]
Primary.

**Comment by harshitnayak45** [comment]
Primary, I mean when we create product on back-end then we have option to select more then one category for a single product, In of them we have to define a category primary

**Comment by abrookbanks** [comment]
That's right. A primary category is required.

**Comment by harshitnayak45** [comment]
Yes. So when showing product on category page, then that product cat_id displays always primary cat_id.
So we have problem to filter by subcategory. 
I have made code to filter by subcategory, in that just i have select product cat_id and show/hide that one

**Comment by abrookbanks** [comment]
You'll have to make an SQL query to get all category IDs form the CubeCart_category_index table where product_id = ?

**Comment by harshitnayak45** [comment]
Please let me know how can we fire custom query in template

**Comment by abrookbanks** [comment]
Please contact sales for a quote.
