### ISSUE TITLE
Authorize.net Testing the Result

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1741]
The Authorize.net module, gateway.class.php, line 202 (new to version 1.1.2):

Earlier, the `$resp` from `$request->send()` is presumably a string, that is exploded to presumably an array of strings.

Following that, tests use the type-juggled comparison operator against integers. No problem there.

However, the new code uses a strict comparison operator `!==` that will always fail (evaluates to `true`), as it is comparing a presumed string against an integer.

Suggest changing:
```
if($results[0] !== 1) {

to

if($results[0] != 1) {
```
See:
https://forums.cubecart.com/topic/52794-authorizenet-pending-verification-transactions/?tab=comments#comment-229064

If the Authorize API docs say that $results[0] being a '4' is a proper result for "Authorize Only", the module needs to be coded to deal with that as something other than an error, with the order being Pending.

**Comment by abrookbanks** [comment]
Released 1.1.3. :) Thanks. 

I haven't tested this but trust your findings.
