### ISSUE TITLE
basket price not calculated correct

### ISSUE THREAD

**Issue by rbckits** [cubecart/v6#1742]
my shopping basket is not calculated correct  the first product is not in , total should be €180,69., sometimes we also have this with the shipping cost that is not calculated in the end how to solve this ?
![basket cc](https://user-images.githubusercontent.com/11742650/30900921-0dc88124-a366-11e7-9223-d1a80cf66807.png)

**Comment by Noodleyman** [comment]
Havenswifts enhanced order module solves this and adds a lot more functionality ;)

**Comment by abrookbanks** [comment]
This is complex. I need full detailed steps to reproduce (STR) this. Closing until STR provided.

**Comment by abrookbanks** [comment]
I assume you mean this Alec? https://www.cubecart.com/extensions/plugins/enhanced-admin-order-entry

**Comment by havenswift-hosting** [comment]
That's the one ! (thanks Alec and Al for the prompts !)

As Alec said, this plugin massively enhances the standard order entry process and designed to streamline manual (telephone / postal) orders greatly

**Comment by abrookbanks** [comment]
Unless I have clear steps to reproduce this issue and I am able to do so that extension is your best bet. Of course I want this fixed but as I said its massively complex and there are a lot of parameters.

**Comment by Noodleyman** [comment]
the enhanced module also solves the issues with VAT being recalculated, and shipping wiht tax being recalculated on the fly with manual order changes :)

**Comment by abrookbanks** [comment]
Cool. It must have been a lot of work to develop.

**Comment by rbckits** [comment]
well it happends fortunatly not very often, i cannot reproduce the error.
 it is a customer and he bought something, but 1 item is not calculated, other problem what happened was that there should be shipping calculated but it did not..
btw that looks good noodleman , is it possible to display items included vat tax and recalculate depending on area without tax ?

**Comment by rbckits** [comment]
btw what is str ?

**Comment by abrookbanks** [comment]
Steps To Reproduce. :)

**Comment by Noodleyman** [comment]
Yes, it recalcualtes based on your tax rules/configuration.

**Comment by rbckits** [comment]
ok str , i can not it is something wrong in the shop

**Comment by abrookbanks** [comment]
> it happends fortunatly not very often, i cannot reproduce the error

I need to know what situation causes it. Certain products in the basket? Specific customers? A certain shipping method? A certain tax setting specific to a product? A certain time of day?

...
