### ISSUE TITLE
Default weight unit should be kg

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1743]
Pretty much the only people using Lbs are the Americans, so Kg should be the default on new store installation

**Comment by abrookbanks** [comment]
Wholeheartedly agree. What are pounds anyway?! :)

**Comment by abrookbanks** [comment]
... the world will be saying that about sterling soon. LOL

**Comment by briansandall** [comment]
Hey, at least we don't use stones... :P

**Comment by abrookbanks** [comment]
Hahaha.

**Comment by havenswift-hosting** [comment]
lol neither do we any longer - not one of the UK's best exports (Imperial weights and measures) - you do still use gallons and an American variation of it as well !

What could be done which would be better still is if the country chosen during installation is USA, then set USD as default currency (similarly for other countries / currencies), set lbs as default weight and maybe even download that different language called US English and set as store default

**Comment by abrookbanks** [comment]
> What could be done which would be better still is if the country chosen during installation is USA, then set USD as default currency (similarly for other countries / currencies), set lbs as default weight and maybe even download that different language called US English and set as store default

Yeah that would be cool.
