### ISSUE TITLE
PayPal Pro module does not respect the DISABLE_CHECKOUT_BUTTON smarty variable

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1744]
smarty variable DISABLE_CHECKOUT_BUTTON is used to disable checkout button, however with this set to TRUE you can still checkout using PayPal Pro.

The pro module should respect this and not allow checkout if TRUE.

**Comment by abrookbanks** [comment]
I'll take a look at this but... this is a MUCH better integration including JS hosted field card payments:
https://www.cubecart.com/extensions/plugins/paypal-powered-by-braintree

**Comment by abrookbanks** [comment]
Sadly this is at skin level so I can only fix it in Foundation.
