### ISSUE TITLE
Secure Checkout & View Basket buttons sometimes not accessible

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1745]
It is possible to have situations where the Secure Checkout and View Basket buttons are below the bottom of the screen and while there is a scroll bar for the page, there isnt for the popup basket window meaning those buttons are unavailable.

This can happen easily if you have a reasonable number of products in the basket and is made worse as quite often the price is pushed to a second line where the product name doesnt fit onto one line.

Reproduced on CC demo store - can easily be done by making height of browser window very small and adding 3 or 4 products (or simply adding 15 plus products)

**Comment by abrookbanks** [comment]
We put a max limit of ten items on this as a fix in the past.

**Comment by abrookbanks** [comment]
Easy fix.. if the popup basket is bigger than the page height redirect to the basket view page instead. ;)

**Comment by havenswift-hosting** [comment]
Wouldnt it be better to do the test first and redirect if bigger and only display the popup basket if smaller ?

**Comment by abrookbanks** [comment]
No because I think it has to expand to know how big it will be otherwise the height will return 0 or null. Another way is to detect the amount of items in the basket and work out if there is enough room but skin customisations may break that.
