### ISSUE TITLE
SQL queries with escape characters issue

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1750]
working on an import, trying to strip \ from a field. CubeCart is stripping the already escaped characters from the SQL query.

SQL query:
`$sql = "
    INSERT INTO
      " . $GLOBALS['config']->get('config', 'dbprefix') . "CubeCart_category
        (
            cat_name,
            cat_image,
            seo_meta_title,
            seo_meta_description,
            seo_meta_keywords
        )
    SELECT
        TRIM(REPLACE(Category1, '\\', '')) as cat1,
        '',
        '',
        '',
        ''
    FROM
      source_data
    WHERE
        Category1 != ''
        AND
        Category1 IS NOT NULL
    GROUP BY
        Category1
    ORDER BY
        Category1
";
$GLOBALS['db']->query($sql, false, 0, false);`

If you run the query manually, it works. if you run it via CubeCart, it fails with the following:
`Line: [101] " INSERT INTO CubeCart_category ( cat_name, cat_image, seo_meta_title, seo_meta_description, seo_meta_keywords ) SELECT TRIM(REPLACE(Category1, '', '')) as cat1, '', '', '', '' FROM source_data WHERE Category1 != '' AND Category1 IS NOT NULL GROUP BY Category1 ORDER BY Category1 " - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''', '')) as cat1, '', '', '', '' FROM ' at line 11`

**Comment by bhsmither** [comment]
`Database->query()` does not get `Database->sqlSafe()` involved. I am not seeing anywhere any code that might otherwise do this.

Therefore, I would start exploring what the PHP MySQL Extension may be doing to the string.

As a temp workaround, what I would do is instead of `'//'`, try `CHAR(92)`.

Running it manually... I suppose you are using a client other than CubeCart, perhaps the MySQL Workbench.

**Comment by bhsmither** [comment]
What happens if:
```
REPLACE(Category1, '\\\\', '')
```

**Comment by bhsmither** [comment]
This looks interesting:
```
REPLACE(@"\", "")
```
Apparently, the '@' prefix says to take the quoted string **literally**.

**Comment by Noodleyman** [comment]
will check it out. I worked around my issue by sorting the data in the source table, meaning I didn't need to escape it in the other query in the source table via direct SQL (using PHPMyAdmin).

I just thought it was odd that the slashes are being stripped, and wanted to share it as it may cause an issue in the future for more complex SQL statements. 

will test these things a little later once I've done what I need with the DB :)

**Comment by Noodleyman** [comment]
double escaping seemed to do the trick.. odd!

the @ symbol didn't work as the slash was still stripped, but that makes sense as it's essentially escaping the single quote

**Comment by abrookbanks** [comment]
Closed but let me know if you have any recommendations.
