### ISSUE TITLE
Stripe app

### ISSUE THREAD

**Issue by mgr88** [cubecart/v6#1753]
Hi, I have recently installed the stripe app on cubecart and run into an invalid email error. When I consulted with stripe the said this:

Jessica
What this error means is that some PHP code on your site is passing the word "false" where Stripe's API expects to receive an email address. Cubecart are passing us that in their integration set up so you need to reach out to them and ensure that for the email field, they're passing us the actual email and not just 'False'.

Thanks for taking a look at this.

Also, in the stripe app, what defines the steps and page layout the costumer sees during checkout? Of all the years of online shopping, I find this cubecart interface to be quite confusing and difficult to follow. First time I used it, I couldn't even figure out where to input the credit card number on the make a payment page.
Where are these checkout files located so I can modify them?

**Comment by abrookbanks** [comment]
Fixed with 2.1.1. Please contact tech support regarding your other queries.
