### ISSUE TITLE
Admin Breadcrumb Trail, URL differences

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1755]
From the admin menu, clicking the "Products" link takes you to the URL admin.php?_g=products

However, the breadcrumb trail link to "Products" is admin.php?_g=products&node=index

Although only a minor difference, it can cause an issue with modules which check URL parameters. Can these links be made the same?

**Comment by havenswift-hosting** [comment]
Agreed - this is also causing issues with some of our plugins.  The admin.php?_g=products would be the better url to use in both

**Comment by havenswift-hosting** [comment]
Thanks !
