### ISSUE TITLE
Check for Pending Orders for Store Visitors

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#176]
There are many times when a customer creates an order and then doesnt pay for it either because they have forgotten their PayPal or other payment login details, cant find their card or simply get interrupted.  They then come back and create the same order again not realising that they could simply login and complete payment on that order.  This creates extra unnecessary orders and hassle for store owners and also means customers spend lots of unnecessary time creating duplicate orders and might leave.

Suggest as soon as a visitor hits a store page, check the IP address they are using against the IP address recorded for all Pending orders and if there any that match popup a message to say something like "There appears to be a Pending order created by this IP address.  In order to pay for this, you can login and click make Payment".  As they would have to login first before being able to see any details of the order there is no chance of the wrong person accessing the order just because they happen to be using the same IP address

I would also suggest a check if / when somebody logs in for orders in their account

**Comment by jetacera** [comment]
I agree that "Complete Payment" should be available for ANY Pending orders. Another benefit of this would be for admin-created orders, so customers could login to pay using any gateway enabled in the system. Mods existed for earlier versions of CC that allowed for this. Much requested by our web-development clients.

**Comment by Noodleyman** [comment]
Some of this functionality is available as part of this module:
https://www.cubecart.com/extensions/plugins/abandoned-carts-capture-missed-opportunities

**Comment by havenswift-hosting** [comment]
It would be helpful if you could summerise which points are included and which are not ?  I was considering writing a plugin to offer this functionality so need to know how close your plugin is to offering this

**Comment by Noodleyman** [comment]
The module currently sends notifications to the customer if an order has not been converted from basket to actual order. In the next update to the module it will also be considering orders that have been converted, but are in a pending status.  It sends an e-mail as defined in e-mail templates to the customer to prompt them to return. :)
