### ISSUE TITLE
Control Panel - Language

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#1762]
I don't know if I am doing something wrong but my Control Panel does not use my Stores default language in Admin Control Panel.  It seems to only use UK language files.

If I am not doing anything wrong and this is how it is, I ask what is the purpose of being able to change these definitions for other languages if they are not going to be used?

Furthermore why cannot Administrators select which language the Control Panel loads when they login?  You can have the dropdown with available languages in Login page or you can add an extra field in Administrator details page where this is saved and when login it loads their selected language.

The 1st option is easiest to implement.

You could also like front end have a language selector, so admin can change language once logged in.

**Comment by bhsmither** [comment]
Please examine admin, Administrators, click the Edit icon of your name.

The General tab should have a drop-down of the language you want to use.

If the choice isn't working for you, let us know.

**Comment by sumwonlost** [comment]
Thank you.   I will test now.

**Comment by sumwonlost** [comment]
Works perfectly, I now know how to change language in Control Panel for Admin, there it was staring me in the eye, thanks bhsmither.  I have just one issue, for language to take effect I have to logout then login.

This should take effect on saving Admin settings, reload page with language rather than having to logout then in.

**Comment by bhsmither** [comment]
Should be somewhat simple to implement. The front-side works that way.
