### ISSUE TITLE
Check out cubecart/v6  

### ISSUE THREAD

**Issue by kochieng50** [cubecart/v6#1764]
The following errors were detected:

    Unfortunately there are no suitable shipping methods available for your order. This may be because the total weight of your order is too high or we cannot ship to your country. Please contact a member of our staff for any further inquiries.

**Comment by abrookbanks** [comment]
This is not a bug. Please install a suitable shipping system or configure any existing ones correctly.

**Comment by briansandall** [comment]
This can also occur if, for example, the shipping provider's system is not responding for whatever reason.

It happens to us occasionally with UPS. Frustrating, but nothing we can really do about it.

**Comment by abrookbanks** [comment]
Understood.

**Comment by kochieng50** [comment]
Thanks
