### ISSUE TITLE
General Improvement - Admin theme (Categories)

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1766]
Added this to a site recently, thought it was quite useful and may want to be added to the stock admin theme.

categories.index.php
FIND:
<a href="{$category.translate}" title="{$LANG.translate.trans_add}"><i class="fa fa-plus-circle" title="{$LANG.translate.trans_add}"></i></a>

ADD BEFORE:
<a href="?_g=products&cat_id={$category.cat_id}" title="Products"><i class="fa fa-search" title="Products"></i></a>

It simply adds a search button beside the category, when you press is you get taken to the product list for that category. simple, but useful. Just needs language strings added.

**Comment by bhsmither** [comment]
Please use code ticks as the Find and Add code is not being shown.

**Comment by Noodleyman** [comment]
Ah, doh..

FIND:
`<a href="{$category.translate}" title="{$LANG.translate.trans_add}"><i class="fa fa-plus-circle" title="{$LANG.translate.trans_add}"></i></a>`

ADD BEFORE:
`<a href="?_g=products&cat_id={$category.cat_id}" title="Products"><i class="fa fa-search" title="Products"></i></a>`

**Comment by sumwonlost** [comment]
Thanks. Very useful.

**Comment by abrookbanks** [comment]
Small & mighty. Thanks for this.
