### ISSUE TITLE
PHP notices

### ISSUE THREAD

**Issue by hollisterca** [cubecart/v6#1768]
I had 2 notices in the error.log
- PHP Notice: Undefined variable: current_language in ../classes/gui.class.php on line 1067
- PHP Notice: Undefined index: X-Forwarded-For in ../includes/functions.inc.php on line 527

CC V6.1.12

**Comment by bhsmither** [comment]
Due to the style of programming employed, these Undefined notices can be ignored.

**Comment by abrookbanks** [comment]
In an ideal work CubeCart would be coded to strict standards. It's not. I would hope that the next major release is.

**Comment by havenswift-hosting** [comment]
Is it possible to have a setting / switch to stop these notices from being recorded in the error_log file - the latest versions of CubeCart record a HUGE number of these effectively making the error_log file unusable

**Comment by abrookbanks** [comment]
> Is it possible to have a setting / switch to stop these notices from being recorded in the error_log file - the latest versions of CubeCart record a HUGE number of these effectively making the error_log file unusable

Only if debug mode is on I believe. Make sure it is turned off.

**Comment by hollisterca** [comment]
Well an easy way is in php.ini
error_reporting = E_ALL & ~E_NOTICE;
but fixing the issue is better. :)

**Comment by abrookbanks** [comment]
I don't believe there is anything to fix. This version will not be coded to strict standard. :)

**Comment by bhsmither** [comment]
In one of my experiments, I have added code to suppress the database logging of Notices when debugging is enabled, and suppress the logging of Notices to the error_log file at all times. This suppression can be switched off.
