### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by hollisterca** [cubecart/v6#1769]
see also screenshot
- the mailing list button on the homepage, the word "abonn" is cut of and does not work
when switching to US language, signup to ML works.
- the mailing list text on the Contact Us page. the Checkbox and the text are on 2 different lines

![german-translation-issues](https://user-images.githubusercontent.com/23412806/31650266-d85df3c8-b316-11e7-9acc-288284da6a24.jpeg)

**Comment by hollisterca** [comment]
definitely a bug in the ML signup when German is selected.

**Comment by hollisterca** [comment]
When ordering in German, on the last page with the invoice the Store Logo is not set. When setting the logo there is no option to english and german nor would I want to have a different logo. So something wrong the the German translation?

**Comment by hollisterca** [comment]
The Admin notification email "Order received" is not arriving. Not sure if this is related.

**Comment by hollisterca** [comment]
Problem can be resolved by changing it to the proper translation.
see
https://forums.cubecart.com/topic/52955-mailing-list-signup-not-working-with-german/

I do have a suggestion/feature request though.
I used to translate and used Poedit
well there you see the source and your translation, maybe that column could be added in the different phrases to translate screen.
Extensions - Manage Extensions - Languages - Deutsch (edit) - Newsletter 
![translation](https://user-images.githubusercontent.com/23412806/31847275-60cc197e-b619-11e7-98f6-858dc151a816.jpg)
![abonnieren](https://user-images.githubusercontent.com/23412806/31847278-6fbd7608-b619-11e7-94b2-0632090b0414.jpg)

**Comment by hollisterca** [comment]
Additional Problem.
After I made this modification I was going to change the Product Translation and German/Deutsch is no longer an option in the dropdown list
![cc-languages](https://user-images.githubusercontent.com/23412806/31934055-4d4b524a-b8ab-11e7-953f-a8d09e204c4a.jpg)
![cc-product-translation](https://user-images.githubusercontent.com/23412806/31934057-4d66e9ce-b8ab-11e7-8bf8-08d7f4f177b1.jpg)

**Comment by hollisterca** [comment]
Another issue:
Admin - Filemanager - Documents
I have 'About us' and 'Ueber uns' each marked with the language. Problem is that on either language on the homepage, it shows both in the footer area

How should this translation work when you select the radio button homepage? or T&C
The language column does not make sense. The translation needs to be within each site document and displayed per language translated.
![cc-sitedocuments](https://user-images.githubusercontent.com/23412806/31936955-609c98f6-b8b3-11e7-9c97-ddd9e5eb4759.jpg)
![cc-sitedocuments2](https://user-images.githubusercontent.com/23412806/31937027-95fc3d3a-b8b3-11e7-8e45-c401da3205f1.jpg)

**Comment by hollisterca** [comment]
I am based in Switzerland and we have 3 main languages here. You can start with a minimum of 2 languages. (German and English) later I can add French and Italian.  Not having a way to translate the options or features of the products, is a shop stopper for cubecart. I can not be the only one complaining about this. Sorry a proper translation of product options and the about page is a must have, otherwise why bother with translation. (Just wanted to add that)

**Comment by havenswift-hosting** [comment]
>>I have 'About us' and 'Ueber uns' each marked with the language. Problem is that on either language on the homepage, it shows both in the footer area

You are using this incorrectly.  Create the document in your main store language for example the "About Us" and then click on the green plus sign to add a translation - you should then delete the "Uber uns" document

However, with regard to your other points, there are some major missing areas for stores wanting to use multiple languages - we have several clients that also need  this added to core ASAP

Product Option Translation is not possible - see https://features.cubecart.com/topic/product-option-translations_9

It isnt possible to add translated Title or other meta tags to translated products - see https://features.cubecart.com/topic/add-seo-title-and-meta-data-for-translations

It isnt possible to have translated SEO urls in many areas - see https://features.cubecart.com/topic/foreign-language-seo-urls_1

You might want to "Like" these feature requests and add supporting comments

**Comment by abrookbanks** [comment]
Sorry but I'm completely confused by this. Please can you submit one issue for each bug found.

Maybe if there are translation faults you can be so kind as to let me know the current text and then what it should be and I'll get the German language pack updated. :)

Thanks for your feedback and sorry I'm not so helpful maybe.

**Comment by hollisterca** [comment]
Hello Al,
closing the bug is easy, but it will not solve it. Take the time if you like to look through it or don't, your choice. As CC stands now, it is not usable for 2 languages, I can not be more clear about this. Read the reply from havenswift-hosting or not, again your choice. As nice as the admin interface is, and the UI for the customer, 2 languages (en, de) is a must for me. If these do not work then it is a no go for CC. I think that means CC will not be really be used in Italy, Germany, Switzerland, Canada, just to name a few.

**Comment by abrookbanks** [comment]
I have looked through it and it makes no sense at all.

**Comment by abrookbanks** [comment]
I'll have another look. Please in the future open one issue for each issue found.

**Comment by abrookbanks** [comment]
Thanks for this. I released 1.0.2 with the phrase change. The rest of your findings are either feature requests or user error. If you can post feature requests to https://features.cubecart.com we will look at these when we can. 

I agree that CubeCart needs some improvement with it's multi lingual capabilities.

**Comment by hollisterca** [comment]
Hello Al,
one request for each issue is noted. I joined the features.cubecart and voted on the 3 issues that havenswift-hosting added. Not really sure that helps. A spike in CC usage will only show after these features work, otherwise it a download, test, disappointment and maybe never try again.
I like that you agree that it needs come improvement. But I think if not you, who decides how important this is?
PS: thanks for fixing at least the ML in German. The other issue with the checkbox being by itself on the line was that the translation was to long and did not fit on the line.

**Comment by abrookbanks** [comment]
CubeCart is free and open source and I run it alone. Occasionally I get help from the community but not as much as I need to move it forward as fast as I would want to. I hope to be able to move forward on prioritised feature requests soon.

**Comment by abrookbanks** [comment]
Reopened to check issue concerning line height.

**Comment by abrookbanks** [comment]
![screen shot 2017-11-21 at 10 50 48](https://user-images.githubusercontent.com/4520803/33068697-fc14d7ba-cea9-11e7-97ae-55e08ff46598.png)
