### ISSUE TITLE
Issue with Invoices Layout

### ISSUE THREAD

**Issue by NaturalSigns** [cubecart/v6#177]
I'm not sure if it just me but if i got to print an invoice the formatting is all left aligned (possibly in mobile format, even though browsing on PC).  I dont recall this style on earlier builds.
![invoice error](https://cloud.githubusercontent.com/assets/10531097/6040761/7683d468-ac6d-11e4-9886-00ba69332cc2.jpg)

**Comment by abrookbanks** [comment]
This is defo a bug. Please find fix above.
