### ISSUE TITLE
Login as customer no longer works

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1771]
This came about after a customer with a large store upgraded from 6.1.1 to 6.1.11, although I've replicated the issue on a clean install of 6.1.12 with no modications.

SImply installed the store, created a test user and tried to login using the tab/link. 

From a customer record, using the link/tab to login as customer redirects you to the store home page without being logged in.

From what I can tell, the session ID for the admin session is different to the store front, thus the incorrect record in the DB is being updated. If I manually update the record in the session table with the customer ID/Admin ID it works correctly.

Not sure when it broke, but still a critical issue.

**Comment by sumwonlost** [comment]
I noticed this the other day with Foundation skin but was not too concerned as I use my own custom skin and this is not an issue.    This also relates to #1759.  I possibly similar issue with ID's.

**Comment by Noodleyman** [comment]
Figured it out.

in session.class.php, 

FIND:
```
if(ADMIN_CP) {
	$session_prefix .= '_ACP';
}
```

Comment it out... this stops CubeCart from generating a different sesion ID for Admin session / Store front, however does bring back that issue where if you log out of the store front you are also logged out of the admin area, but it's a work around not a fix. :)

**Comment by abrookbanks** [comment]
Thats a work around for now for sure.

**Comment by abrookbanks** [comment]
The session were separated to stop front end session causing CSRF errors in the back end. I expect viewing the store whilst logged in as admin and hidden prices may be affected by this too. Maybe a better solution is to call the admin CSRF token a different session name.

**Comment by abrookbanks** [comment]
Relates to https://github.com/cubecart/v6/issues/1728

**Comment by havenswift-hosting** [comment]
It also stops the ability to switch skins on the front end when logged in as admin as the skin switch option doesnt even display

**Comment by briansandall** [comment]
Note that fixing this issue reverted the changes made in #1728.

**Comment by abrookbanks** [comment]
Thats right. :) All good now we have separate front end and backend CSRF session tokens.

**Comment by phucluke** [comment]
Hi CubeCart team,

Please let me know which release include fix for this issue? Thanks.

**Comment by havenswift-hosting** [comment]
If you click on the commit references above you will see that it is 6.1.13 but why would you not upgrade to the latest version anyway ?  The last couple of versions include important Security fixes so always upgrade to latest.
