### ISSUE TITLE
Enhancement to Coupons

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1772]
This is a very low priority request...

Currently if a coupon is limited to, or excludes specific products those products are stored as a serialized array in CubeCart_coupons.product_id.

Can this be exploded out into a new table and work in a similar way to the image index? 

The reason for the request is that I've a requirement to dynamically associate products with coupons for a large store. there will be several thousand products associated with each coupon. In order to dynamically add, and keep the list up to date the array has to be pulled from the DB and compared with several thousand product ID's to see if they exist and add missing ones, as well as remove those no longer required. 

This takes quite a bit of time to do and I'm concerned about performance, where as if it was in it's own DB table the same action can be completed in a split second with a couple of SQL queries.

**Comment by abrookbanks** [comment]
I'm going to put this as a question and close because I think there are a lot of area of CubeCart that should also work like this. Not to mention the config array (YUK).

We should look at this as a v6 (&v5) pitfall and learn from the mistake for CubeCart v7 (*passes out*).

**Comment by Noodleyman** [comment]
just for info, I found the most effecient way to address the issue was to simply build a new array each time and overwrite the old one. However, this introduces a higher risk of data issue if the update goes wrong, everything is lost. it shouldn't happen... but many things shouldn't and do sometimes :)

but, yes it could mean a model change and simply exploding things out into tables would be a significant change. you can even keep the code the same simply by updating the methods used to gather the data, perhaps reference a view in the DB to gather the data, then built it into an array and pass to the existing code which expects an array. manyyy different approaches, all with pro's and cons. :)

**Comment by abrookbanks** [comment]
Totally agree. Should be fine with built in tests though.
