### ISSUE TITLE
Customers sometimes unable to checkout - "Please enter a valid email address"

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1775]
Store version 6.1.10 (updating soon)

Sometimes when going through the checkout process a customer has entered all their data, including a valid email address, but an error occurs and they are asked to enter a valid email address, despite having a valid one already.

When this happens, it is impossible for the customer to continue with the order no matter what they use for their email address.

I believe this error is related to an invalid state getting selected for the customer. Example error log:
```
UPS Error: UPS SOAP Request failed - An exception has been raised as a result of client data. - Serialized Details: O:8:"stdClass":2:{s:8:"Severity";s:4:"Hard";s:16:"PrimaryErrorCode";O:8:"stdClass":2:{s:4:"Code";s:6:"111286";s:11:"Description";s:51:"AE is not a valid state for the specified shipment.";}}
```
This is despite the fact that the customer's addresses are not in AE, wherever that is. A previous case had actually set the user's state to I think Puerto Rico (in which case fixing their address in the system resolved the issue), but in this most recent case (and a few others just like it) the customer's addresses were correct.

Note that in all cases I was able to log in to the customer's account and place the order with no issues, and the user when viewing their cart did receive an accurate shipping quote, so I'm not really sure how to reproduce this or what the actual cause may be.

Hopefully updating to the latest version will fix this, but since it is so rare for a customer to call in when this happens instead of simply abandoning their purchase, I wanted to raise this issue in case it hasn't been fixed yet.

**Comment by abrookbanks** [comment]
I suppose instead of trying to debug this we need a lockout reset tool. If disabled it should show a small bit of text at the end "reset" which clears the field and enables it.

**Comment by briansandall** [comment]
I found a way to reliably reproduce this that may shed some light on the root cause:

1. Place an order without being logged in and go to checkout

2. Fill out contact and billing details for new account

3. Proceed to (secure) checkout

4. Click on 'Make Changes'

5. Edit the billing address and update basket

Now the email field is marked as invalid and the form becomes difficult / impossible to use.

I haven't tried this with your form reset fix yet, but it seems like that will still have the same issue just a way for the customer to get around it.

**Comment by abrookbanks** [comment]
My fix works really well. Essentially if the field is disabled and you click it, it will reset. It makes it quite natural.

**Comment by briansandall** [comment]
It isn't working for me - turns out I am using the latest code for 6.1.13.

Following the steps above, I end up with an invalid email address. The form input clears, which is great, but no matter what I input as my email address I keep getting the same error over and over again when clicking 'Update' or 'Checkout'.

**Comment by abrookbanks** [comment]
Thanks I'll try those steps.

**Comment by abrookbanks** [comment]
Hmm. I could reproduce this. For some reason the email key of the user post array goes astray here: https://github.com/cubecart/v6/blob/master/classes/cubecart.class.php#L1030

**Comment by briansandall** [comment]
Indeed, it's very bizarre. My guess is it gets lost somewhere in the JS before posting.

**Comment by briansandall** [comment]
Is 6.1.13/14 still a target, or is 6.2.0 the new focus?

**Comment by abrookbanks** [comment]
Both 6.1.14 & 6.2.0 are coming.

**Comment by abrookbanks** [comment]
Extensively tested on latest build code and I can't reproduce this. I CAN reproduce it on our demo store running older email validation code. I believe the issue happens because the field is disabled and therefore has no value. 

On those grounds I believe the current code validation works and this can be closed.
