### ISSUE TITLE
/modules/plugins/PayPal_Pro/

### ISSUE THREAD

**Issue by kochieng50** [cubecart/v6#1777]
I seems to be missing config.xml. Any idea where I can get this file?

**Comment by bhsmither** [comment]
I have this file in PayPal_Pro v1.1.4, v1.1.7, and v1.1.10 (the only versions I checked).

Please verify you have the latest version from:
https://www.cubecart.com/extensions/plugins/paypal-pro-express-checkout

You may also want to evaluate:
https://www.cubecart.com/extensions/plugins/paypal-powered-by-braintree
