### ISSUE TITLE
Obsolete 'county' list in Cube Cart v6

### ISSUE THREAD

**Issue by BigGwil** [cubecart/v6#1778]
Request to replace Cardiganshire with Ceredigion in future versions of CC v6's drop-down menu for counties. 
This is because the county of Cardiganshire was abolished in 1974 by the UK's Local Government Act 1972 — and it was succeeded by the renamed County of Ceredigion on the 2nd of April 1996. So whoever compiled the database of counties in Cube Cart software must have been drawing on a very old reference.

**Comment by abrookbanks** [comment]
Thanks for this! :)
