### ISSUE TITLE
TidyOrders() to Log Its Actions

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1780]
Suggest that `Order->_tidyOrders()` call `$this->logTransaction()` and `$this->_addHistory()` with appropriate data.

**Comment by abrookbanks** [comment]
LOVE this. Thank you. 
![screen shot 2017-11-20 at 10 39 44](https://user-images.githubusercontent.com/4520803/33014429-2e736de6-cddf-11e7-8e7d-1f30387f1f1b.png)
![screen shot 2017-11-20 at 10 39 35](https://user-images.githubusercontent.com/4520803/33014430-2ea04f14-cddf-11e7-91d2-749f835ce884.png)
