### ISSUE TITLE
Authorize.net Module To Handle Fraud/Hold Response

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1783]
Received an email today:
> The Advanced Fraud Detection Suite™ (AFDS) is now a standard part of the Authorize.Net payment gateway account. Since August 2017, all new accounts have been created with a sensible set of AFDS filters enabled by default, which help protect merchants from malicious and fraudulent payment submissions (e.g. card number testing) through their web sites and other payment form applications. To ensure all merchants have the same level of protection and security, we are rolling out the same set of default settings to all existing merchants on-boarded before August.

Currently, the Authorize.net payment gateway treats a "Hold for Review" response as a failed transaction.

See recent forum conversations about this.

**Comment by abrookbanks** [comment]
Thanks. This is fixed with 1.1.4.
