### ISSUE TITLE
Error on Checkout

### ISSUE THREAD

**Issue by kochieng50** [cubecart/v6#1784]
The following errors were detected:

    Unfortunately there are no suitable shipping methods available for your order. This may be because the total weight of your order is too high or we cannot ship to your country. Please contact a member of our staff for any further inquiries.

I have added the Shippo

**Comment by havenswift-hosting** [comment]
This almost always means you dont have a shipping module installed or you haven't configured it correctly. You should post queries / requests for help like this on the forums where people are more likely to help, rather than here which is for proven issues / bugs that have been found
