### ISSUE TITLE
Tax::productTax() May Return Insufficient Data

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1786]
The function Tax->productTax() function returns the last tax amount calculated, which then gets assigned to cart.class.php near line 818:
```
$this->basket['contents'][$hash]['tax_each'] = $product_tax;
```
which may be insufficient, **as this value is used elsewhere**, such as in `Cart->_applyDiscounts()` and `Tax->_getInheritedTax()` -- possibly elsewhere.

It is insufficient as there may be more than one applicable tax.

For example, state-wide plus local taxes. The database Tax Rates makes a unique key against:
`type_id`,`details_id`,`country_id`,`county_id`
where values for this key could be:
```
Type: ID = 1, Tax Class = 'Standard'
Detail: ID = 2, Unique Name = 'GST', Display As = 'State'
Country: ID = 840
County: ID = 62

Type: ID = 1, Tax Class = 'Standard'
Detail: ID = 6, Unique Name = 'LST', Display As = 'Local'
Country: ID = 840
County: ID = 62
```
In this case, Tax->productTax() returns with:
```
'amount' => 0
'tax_inclusive' => false (from the arguments)
'tax_name' => "Local (Standard Tax 0%)"  // ignore the zero percent
```
(I am working on a local taxes plugin. The 'Local' will be managed via snippet. Current needs require it to be in the Tax Table.)

**Comment by abrookbanks** [comment]
I think after 5 years we can close this one... 5 years!! I just don't know what to do about it. 

If we have a real world reproducible bug I'll take a look.
