### ISSUE TITLE
Language issue/bug

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#1789]
I am having issue with languages.  As example I will use 3 languages, en-UK, en-US and en-AU, in essence all identical with minor changes.

There are 2 methods on how languages work, the first works correctly, the second has me in a spin.

Method 1 - create individual xml language files for each with required changes that override changed strings in definitions.xml - works perfectly.

Method 2 - Goto CP -> Languages -> Create Language, it creates the language.xml and takes you to language group/string page, were I make changes and save - all perfect for the first language created and saved to db correctly, however when I create 2nd language and do same, it does not update changes if I use a term in 1st language, however if I use a different term it saves correctly.

CubeCart comes with UK file so lets start here. I am a sporting store, so I need to change "Shop by Category" in all 3 languages to "Shop by Sport" as this is global.  When I change this in UK it works correctly, I then create and change this in new language, it works correctly but when I do this to next language it will not save if I use "Shop by Sport" but updates if I use another term.

Looking at the db, I notice that if a single string is changed in a group it saves the whole group.  Is this necessary?  Why not only the changed strings be saved?  This does not solve the above but reduces db resources.

The best option rather than having a db for this, why does it not make changes directly to the xml files rather than db? saving on db resources and as this is how method 1 works it should work perfectly.

**Comment by sumwonlost** [comment]
Another example, I do not use basket in wording and use cart (due to space restriction) with the later 2 characters less fitting perfectly.

Again I go to CP -> Languages -> select language (UK) then in dropdown select Checkout.

Change "Your Shopping Basket" to "Your Shopping Cart" and save.  It Save correctly.

Now go back to languages and do same with US language and save.  It does not save the change, but if i change to something else it will save the changes.  Also if I use "Your Shopping Cart" and change another field and save, it will save the changes to other field but not "Your Shopping Cart" reverting back to "Your Shopping Basket".

I have not been able to diagnose a reason for this.  It has me perplexed why it saves some changes and not others.  I have just about given up using the languages module preferring to hard code the changes in xml files as these work correctly.

**Comment by sumwonlost** [comment]
Sorry all - I just found the Merge File feature.  I will try this.  If issue persists I will re-open.

**Comment by sumwonlost** [comment]
I still have same issue even after Merge File.   I have given up using the Language Module to add languages or edit language stings and will do these in xml files as I know this works correctly.

The main issue I have with using module for this (let alone the other issues) is that depending on the number of languages I have and the number of string changes, the db could theoretically run into 000's of entries.  Wouldn't it be wiser when these are merged to file that they be deleted from db?  Keeping the db to a minimum, technically 0 entries once all language/groups were merged to files.

**Comment by abrookbanks** [comment]
I haven't been able to reproduce this. I create a language and changed a phrase then merged to file (without compression). I then enabled the language file and changed the language on the front end and I saw the changes. I repeated the process again and it worked too. Maybe I'll make a movie....

**Comment by abrookbanks** [comment]
Please see http://static.cubecart.com/issue-1789.mp4

I have closed this but I will reopen it if you think the issue remains or if I have misunderstood. I agree about the DB bloat and that could be improved in the future.

**Comment by abrookbanks** [comment]
I just did more testing on this and it still worked without merging to file.
