### ISSUE TITLE
Improvement to Dashboard -> Categories navigation

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#1790]
Using following for illustration.  

Categories,

1
1.1
1.1.1
1.1.2
1.1.1.1

As I navigate to 1.1.1.1 it should put the parent category/s in dashboard for easier navigation.  Similar to front end and filemanager (folder structure).

Currently if I make a change to 1.1.1.1 and save then need to go to 1.1.2 or even 1.1, I have to go through the entire process to get to a lower level category within a category hierachy.

**Comment by abrookbanks** [comment]
Do you mean in a breadcrumb?

**Comment by sumwonlost** [comment]
Yes.
