### ISSUE TITLE
Improvements - Filemanager

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#1792]
Currently I can move files between folders,  Can this be extended to folders and its contents?

I want to move a folders (its contents and folders) to another folder.  

It should not be too difficult to implement as it basically would work same how files are moved to other folders.

Maybe it needs a warning before proceeding to the effect "You will need to update changes wherever used".  Therefore if the folder moved contained category images, I would have to go to my categories and change Image to point to moved folder.

The reasoning behind this is as a new store, we all make mistakes how we set it up and it is not until we grow we realize we could have done it better.

Yes I could create the same directory (folder) structure under the folder I wish to move files then individually move files from old directory structure to new directory structure then delete old directory structure BUT would it not be easier to move whole folders?

**Comment by abrookbanks** [comment]
Please can you submit feature requests here: http://features.cubecart.com
