### ISSUE TITLE
Postcodes to be Forced Uppercase

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1793]
In `User::saveAddress()`, the postcode is forced uppercase.

However, in `CubeCart::_checkout()`, `$_POST['billing']['postcode']` and `$_POST['delivery']['postcode']` is not.

Suggest sending these values through `strtoupper()`. (Satisfies shipper's recommendations.)

**Comment by abrookbanks** [comment]
Thanks Brian.
