### ISSUE TITLE
Reviews - General improvement

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1794]
For larger sites, the "Reviews" section of the admin area can become a bit of a pain to manage. Splitting out the section into multiple tabs would be very useful.

Recommending tabs for "Approved" , "Pending Review" so any pending items can be quickly identified and managed.

**Comment by bhsmither** [comment]
A tab on the Dashboard is not sufficient?

On the Reviews page, tabs would be nice - I did that for order statuses in CC3.
Maybe add a "sort by" or have a "filter on" `Not Enabled` status.

**Comment by Noodleyman** [comment]
It just seems to make sense to have it also within the "reviews" section, rather than outside of the area specific to reviews.

Perhaps move the tab to Reviews and make the dashboard tab a link to it?
