### ISSUE TITLE
New customer registrations loop on "add address"

### ISSUE THREAD

**Issue by Rob-Tea** [cubecart/v6#180]
When checking out as a new customer. You first register name, email etc, next screen prompts for an address.  Once youve added this it states "Address has been saved" but then locks you in the loop of adding another address (you can't complete checkout).  I'm pretty sure this previously used to work ok?
![add address](https://cloud.githubusercontent.com/assets/10531097/6049904/74b8c562-acb3-11e4-9877-b90df479a01e.png)

**Comment by abrookbanks** [comment]
Thanks for this. Please can you provide steps to reproduce. I can't relate to this..

> When checking out as a new customer. You first register name, email etc, next screen prompts for an address.

That's not what I am familiar with. It should ask for your address on the same screen. I tried adding an item to the basket and then going back to the homepage and clicking "Register" this seemed to work ok and  could then checkout.

**Comment by NaturalSigns** [comment]
Ok, just checked again and still an issue (for me).  Follow steps below (click register)
![step 1](https://cloud.githubusercontent.com/assets/10531097/6062473/fcbdeffc-ad47-11e4-952d-230deddcc23a.png)

then fill out this form (registration details without address)...
![step 2](https://cloud.githubusercontent.com/assets/10531097/6062480/08a9c426-ad48-11e4-8684-7cc1d09534ca.png)
then, you can browse the website, add something to your cart and then click checkout, you get the following warning which is understandable.....
![step 3](https://cloud.githubusercontent.com/assets/10531097/6062537/75982f50-ad48-11e4-96c4-bc2baf790b5e.png)
At this point you get stuck in the "Address has been saved" / "Add Address" loop shown on my earlier post".

Possibly the registration should include the address on the first screen?

**Comment by demeterbee** [comment]
I am also seeing this problem, although the store front keeps looping back to the 'add address' screen the address is being added. If I go into the admin view customers page, all the added addresses are listed for the customer.

**Comment by abrookbanks** [comment]
Thanks for all the info. This will be a priority for Monday allong with issue #184

**Comment by abrookbanks** [comment]
I still can't reproduce this. I register and then checkout. It asks me for an address which I add then I can simply checkout. Am I doing something different? Movie here: 

https://dl.dropboxusercontent.com/u/894044/issue_180.mov

**Comment by NaturalSigns** [comment]
Fair play, you've been busy today, some great improvements.  

This particular issues seems to appear when you register with an EMPTY shopping cart, just tried it on https://demo.cubecart.com/cc6 and getting the same error.

**Comment by abrookbanks** [comment]
I still can't reproduce this. Today has been a nightmare. I'll pick this up tomorrow. Maybe a fresh head will help.

**Comment by demeterbee** [comment]
Hi Al,
Have a look at what happens if you just try and register as a new user. ( As NaturalSigns says an EMPTY cart)
This is what i am seeing:

First page " I would like to create an account"
Enter the info and get through the reCaptcha.

Next page is "Your Address Book"
Enter your address and click save.
A green banner appears telling you the address has been saved, all the fields that you just entered have been cleared. (implying there was a problem )
Enter your details again and same thing happens, you can go around this loop forever.
If you break the loop by clicking on "Your Account" 
Select "Address Book" from the list and you are back in the loop.

Seems to be no way of seeing that you have successfully saved an address, seeing your list of addresses  or selecting a saved address to edit it.

If you log in as admin you can see that all of the addresses that you entered have been saved even if they are identical.

Think the problem is that its not obvious that the address has been saved and there doesn't seem to be a way of seeing/editing/deleting  a list of saved addresses.

Kev.

**Comment by abrookbanks** [comment]
Thanks for the clarification Kev. I still absolutely cannot reproduce this at all. I need to see this in action. 

Do either of you use a Mac? If so Quicktime will do a screen recording under the "File" option. 

I'm sorry and appreciate this must be frustrating for you. I have tried all combinations I can think of registering before or during checkout with and without a basket contents.

**Comment by bhsmither** [comment]
*"A green banner appears telling you the address has been saved, all the fields that you just entered have been cleared. (implying there was a problem )"*
I am not going to make that inference.

**Comment by abrookbanks** [comment]
Can you reproduce this Brian? It's pestering me..

**Comment by bhsmither** [comment]
@demeterbee, @NaturalSigns, please let us know the exact version of CC6 you are seeing this issue with. Please always state the version. We can assume you are using the latest release, but we choose not to.

**Comment by demeterbee** [comment]
Hi, 
Sorry yes, I should have stated the version of CC6 that I am using. Its V6.0.0b4.
The reason that I think that the cleared fields imply a problem is that CC stays on that page, so it seems to still be requiring you to enter the information. And there seems to be no way forward or backwards, without going to the link at the top of the page. If you break the "loop" and go to the user account>Address Book you are back in the same "loop" with no way to see any addresses that you have previously entered or select or edit them. Hence the assumption that the address wasn't accepted.

**Comment by demeterbee** [comment]
Hi Al,
Just re-reading all of the posts in this thread. 
Looking at the Screen recording that you posted, at 0:40 there is a page titled "Your Address Book" that DOES allow you to see/select/edit and delete previously entered addresses. I am NOT seeing that screen. And can find no links to it in the user profile.
Sorry Yesterday was hectic and missed what was right in front of me.

**Comment by NaturalSigns** [comment]
For reference I'm using 6.0.0b4, the original issue can be seen on video here... https://www.dropbox.com/s/knj4r0kj6lft4hh/Orignial%20Issue.avi?dl=0 , 

I was also experiencing the same issue on demo.cubecart.com/cc6/ earlier today though that now seems ok, has that been updated this afternoon? https://www.dropbox.com/s/undn7s6562ew85m/Address%20Loop%20-%20Working.avi?dl=0

(Note: Even though it looks to now be fixed (2nd video link) should you need the "Your Address Book" step [at 1:02] if  you have selected default billing and shipping address?, should it just go to the checkout stage?.

**Comment by bhsmither** [comment]
Please let us know what you see when:
* in admin, Store Settings, Advanced tab, Enable debugging: Enabled (and enter your IP address if the store is online: www.whatismyip.com)
* Enable Caching: Disabled

Call for the Addressbook from the storefront. In the debug section at the bottom of the page, you should see a long list of SQL queries. Find the one that says (near query 25):
`[25] SELECT * FROM `CubeCart_addressbook` WHERE CubeCart_addressbook.customer_id = '5' ORDER BY billing DESC ; -- (0.015625 sec) [CACHED]`

If that's not there, we can start looking to find out why.

At the bottom of the query list, there will be a list of any queries that had any errors.

**Comment by bhsmither** [comment]
Also, can you activate your browser's Developer Mode and engage the Network tab. This will show what the browser POSTs, GETs, the responses from CubeCart and any 302 Redirects.

The Address Book link is correct (as seen at the browser window bottom at time 1:48). So I wonder if there is a 302 Redirect that is malformed.

**Comment by NaturalSigns** [comment]
...well, changing "Enable Caching" to Disabled has fixed if for me, system now behaves fine (is this is a school boy error...[apologies in advance]).

**Comment by demeterbee** [comment]
Like wise, changing the caching to disabled make the site work, changing it back to enabled (think that was the default but not sure) breaks it again.

**Comment by demeterbee** [comment]
Apologies, looks like an error in the setup on my part.

**Comment by abrookbanks** [comment]
Please don't apologise. It should have worked. The cache has undergone some changes recently and should be ok from beta 5. There have been issues over disabling it and "empty" queries. Hopefully you find no issues now.

**Comment by demeterbee** [comment]
Hi Al,
All seems OK now, can turn the problem on and off with the cache setting. Will just leave it disabled.
Kev

**Comment by demeterbee** [comment]
Hi Al,
Upgraded to V6.0.0b5 - problem has gone, works with the cache turned on or off. 

Kev

**Comment by abrookbanks** [comment]
Excellent. Thank you!! :)

**Comment by abrookbanks** [comment]
Finally reproduce this!! It was over caching the address book. After adding a new one the previous SQL query was still empty. Preventing caching of that query resolved this.

**Comment by techxpert9** [comment]
We are still on Cube cart 5 due to some historical reasons and facing exact same issue, Can you tell us what changes you did to fix this i.e "Preventing caching of that query resolved this",

So we can fix it without upgrading to CC6

we do not mind going deep into files and custom code if you can give us a pointed of this issue or just tell files names where to look it will really help

Many Thanks,

**Comment by abrookbanks** [comment]
I'm sorry it's not something I can help with.

**Comment by techxpert9** [comment]
Correction : Our Version is CC 6.0.0

**Comment by abrookbanks** [comment]
There are HUNDREDS of bug fixes since then and some vital security updates. It's vital that you upgrade.

**Comment by s3ok3v** [comment]
OK - but there is only one bug fix that you're being asked for advice on, so I'm not sure why the hundreds of unrelated bugs are relevant to this question? You stated that the bug fix for this issue related to preventing the caching of a query, can you shed more light on this so that this one bug causing the issue can be resolved without upgrading?
Thanks

**Comment by abrookbanks** [comment]
No I'm sorry I can't spend time helping you with this. You can open a technical support ticket if you want or you should be able to find it somewhere in this thread.

**Comment by s3ok3v** [comment]
I Have opened a ticket

**Comment by abrookbanks** [comment]
Great thanks.
