### ISSUE TITLE
Clear Cache creates Error Log Warning

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1802]
```
[Warning] /XXX/plushcatalog/classes/cache/cache.class.php:162 - unlink(/XXX/plushcatalog/cache/skin) [function.unlink.php]: Is a directory
```
The next section of cache.class.php provides a way for the skin folder to be cleared, but the line 162 section does not have any code that allows it to ignore the skin folder.

I had 48MB of error log - It would be great if we could toggle view of Notices vs the Warnings and ideal to have an automatic delete of Notices after X time.

**Comment by havenswift-hosting** [comment]
>>I had 48MB of error log - It would be great if we could toggle view of Notices vs the Warnings and ideal to have an automatic delete of Notices after X time.

The recent change has caused error_logs to get to stupid sizes all filled with irrelevant PHP Notices - we have e apples on busier sites where they are growing to many hundreds of MB very quickly which are unusable and so they just get deleted.  Notices should not be recorded by default but have the ability to toggle that on would be good.

**Comment by abrookbanks** [comment]
> recent change has caused error_logs to get to stupid sizes all filled with irrelevant PHP Notices

Only if debug mode is turned on. It shouldn't log notices or warnings when debug mode is off.

**Comment by havenswift-hosting** [comment]
>>Only if debug mode is turned on. It shouldn't log notices or warnings when debug mode is off.

That is how it should work but in most recent versions, even with debug off, these get logged and there are tens of thousands of notices about undefined indexes and variables (one not even especially busy site has logged 50,000 plus in 20 hours !)

**Comment by abrookbanks** [comment]
Eeeek. Thats no good. Hopefully [this](https://github.com/cubecart/v6/commit/eeb159f3cfbdaa85ad77f5a114622b4feb72221c) fixes it for 6.1.13 then.

**Comment by havenswift-hosting** [comment]
Saw that after I left my comment - that should hopefully do it.  Deleted a log file yesterday that was 490 MB !

**Comment by abrookbanks** [comment]
> Saw that after I left my comment - that should hopefully do it. Deleted a log file yesterday that was 490 MB !

Crikey.. you'll have to send me the upgraded SSD hardware bill!!
