### ISSUE TITLE
FedEx Shipping Module - Needs immediate overhaul

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1803]
The API on which the FedEx module is based is now discontinued and offline which makes the FedEx module non functional.

FedEx have now switched to a SOAP API as standard, so the module needs a re-write to use SOAP.

This has impacted a couple of my customers who no longer can use FedEx for their shipping quotes.

**Comment by bhsmither** [comment]
The FedEx module (https://www.cubecart.com/extensions/shipping-methods/fedex) already uses SOAP.

(Trying to attach the v22 WSDL zip file and failing.)

Minor edits in shipping.class.php to reference v22 instead of v13.

**Comment by abrookbanks** [comment]
Thanks SO much @bhsmither for your hard work on this. I have published 1.0.5 and verify it working on a merchant store. I'm very grateful.

**Comment by Noodleyman** [comment]
Thank you Guys :)
