### ISSUE TITLE
Skin text file for Upgrades.

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#1804]
Upgrades can be time consuming for those using Custom skins.

The issue is not so much with Custom Admin Skins as generally if any changes made (such as mine) are to the header in main.php, therefore I copy/rename the default skin and copy and paste my coding from upgrade to upgrade.  No other coding is altered.  Less than 5 mins.

The issue is changes/additions/deletions to Foundation Skin folder.  As I use my own custom skin I need to make the alterations/additions/deletions to my skin, I assume this applies to most stores as let's face it the Foundation skin is crap.  Having said that now I think about it, it also applies to those using Foundation skin who have added plugin includes/changes as these would be overwritten with each upgrade and need to be added again and again. 

How do I currently do it?

When I was new to this, I would open each file in Foundation skin and go though them comparing them to previous version, finding additions and alterations and making changes to my skin.  Very very time consuming to find sometimes minimal changes/additions (if any) to skins as most upgrades relate to core files.

More recently I began doing these through this site, I would go to closed issues, click through to fix and see if it applied to skins folder and would then make changes to my skin.  I would do this for each issue. No changes are made to any core files.  This method is faster but does not help me with unreported fixes/additions/deletions made by Cubecart not listed here, so in effect to do it correctly I still need to do it using the above slow method.  

A better way, ideally with each upgrade you include a skin.txt that outlines changes/additions/deletions to Foundation skin folder similar to following:

------------------------------------------------------------
#issue no (bug fixes/feature requests)
directory/filename       change/add/delete
-------------------------------------------------------------

Therefore I would open skin.txt, if it has an #issue no I come here find the fix/update and apply it to my skin. 

If it has directory/filename followed by change, I open the file in Foundation skin and find the change by comparing it to previous version then make changes to my skin.

If it has directory/filename followed by add, I then copy the new file added from Foundation skin into my skin.

If it has directory/filename followed by delete, I then delete the file from my skin. 

This method depending on the number of entries in file, I could do the skin upgrade very quickly, in most cases less than 1 hr, simply by the inclusion of a text file with each upgrade which realistically would not take much time for you to compile which would save stores many many hours upgrading skins.

**Comment by havenswift-hosting** [comment]
You can simply use a file diff program to compare the Foundation skin directory from last version and new version which will show any new files and files changed and then allow you to open up the two versions side by side for any with differences - would take about five minutes

**Comment by bhsmither** [comment]
There is also this... (I do not see a link to start a wizard):
`https://github.com/cubecart/v6/compare/v6.1.11...v6.1.12`
Specify the tag/release to start, three dots, the tag/release to end.
