### ISSUE TITLE
Add indexes to table and update database checker

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1808]
Add indexes to table CubeCart_option_assign for columns

`product` and `set_enabled`

Both columns used in following query as part of WHERE statement but have no index set

SELECT   * FROM `CubeCart_option_assign` WHERE CubeCart_option_assign.product = '7403' AND CubeCart_option_assign.set_member_id = '0' AND CubeCart_option_assign.set_enabled = '1'

**Comment by havenswift-hosting** [comment]
Also another index on column `last_updated` needs adding to table CubeCart_saved_cart

**Comment by havenswift-hosting** [comment]
And another one !

Index required on `featured` in table CubeCart_inventory

**Comment by abrookbanks** [comment]
Thanks for this. I couldn't find ````CubeCart_saved_cart `.`last_updated ````

**Comment by havenswift-hosting** [comment]
Sorry, yes it is and I thought I had deleted that comment !

**Comment by abrookbanks** [comment]
Ok cool. :) All good then. Thanks for this.
