### ISSUE TITLE
Statistics graph formatting error

### ISSUE THREAD

**Issue by NaturalSigns** [cubecart/v6#181]
With reference to the image below I find each statistic graph is badly formatted as standard.  If you go to to toggle to the various pages (link highlighted pink), it will format correctly.
![chart error](https://cloud.githubusercontent.com/assets/10531097/6050397/17167d2e-acb7-11e4-85d0-3f61b4e75e2b.jpg)

**Comment by abrookbanks** [comment]
Hmm they are not loading at the size specified...

**Comment by abrookbanks** [comment]
Fixed with commit https://github.com/cubecart/v6/commit/3e5d9e78148e595cec1ecd944c4b7f74826ae08c
