### ISSUE TITLE
Bug with Complete Payment

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1810]
in cubecart.class.php the following code detects the "complete payment" URL being opened and calls the placeOrder function.

```
if (!isset($_REQUEST['gateway']) || (isset($_GET['cart_order_id']) && $_GET['retrieve'])) {
	Order::getInstance()->placeOrder();
}
```

In the placeOrder function, the first thing that is validated is if the basket contains any items.
```
if(!isset($this->_basket['contents'])) {
	$GLOBALS['gui']->setError($GLOBALS['language']->orders['expired_basket'], true);
	httpredir('index.php');
	return false;
}
```

As a customer, if you don't have any items in your basket and try to complete an order, it triggers this condition rather than repopulating the basket/cart and going to checkout.

To fix it, simply pickup the check and move it after the if/else, as follows:
```
		} else if (!empty($this->_basket)) {

			if(!isset($this->_basket['contents'])) {
				$GLOBALS['gui']->setError($GLOBALS['language']->orders['expired_basket'], true);
				httpredir('index.php');
				return false;
			}
```

**Comment by abrookbanks** [comment]
Thanks for this. Code formatting fix too with commit.

**Comment by Noodleyman** [comment]
Thanks Al :)
