### ISSUE TITLE
Wrong Use of Function

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1814]
In `Debug->_getTime()`, PHP's function `microtime()` has the argument of `false`. According to PHP docs, this returns the time as a string of the format:
`decimalsecond wholesecond`
Such as:
```
Page Load Time:
Start: 0.33441700 1511890779 End:0.58441800 1511890779 (Diff: 0.250001 seconds)
```
PHP is probably ignoring the whole number part in calculating the difference in `Debug->endTimer()` and `Debug->display()`.

As such, the result of the calculation would probably be completely wrong - even a negative number.

Suggest `microtime(true)` which returns a float value.

**Comment by abrookbanks** [comment]
Thanks.
