### ISSUE TITLE
Upgrade Issue

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#1818]
I am able to upgrade 6.1.12 to 6.1.13 without issue on my test site. However on my development site running 6.1.10 as 6.1.11 and 6.1.12 had too many issues, I decided not to upgrade until these were fixed in 6.1.13.

I am unable to do an upgrade from 6.1.10 to 6.1.13.  The upgrade process starts normally asking me whether I wish to Upgrade from 6.1.10 to 6.1.13 or do a new install (normal).  

I select the Upgrade option and it commences but stops here at 80% and showing that it will upgrade to 6.1.11 in installation bar and not 6.1.13.

I let it run overnight hoping it would do this possibly in order of updates but to no avail.

I would have assumed I can go from 6.1.10 to 6.1.13 without having to install the other updates in order.

**Comment by bhsmither** [comment]
If it "stops", but there is a Continue button, then click the Continue button.

My experience has shown some browsers (with the help of some browser helpers) sometimes prevent auto-submission of forms - which the setup code does as it steps (otherwise invisibly) through making required changes to the database according to the various versions.

**Comment by sumwonlost** [comment]
Thanks but still not doing it.  I have tried using Chrome, Edge, Opera, Firefox and Safari and still same issue in all browsers.

I have attached files showing procedure and progress

![screenshot 16](https://user-images.githubusercontent.com/23044524/33413747-fafa7b8a-d5e5-11e7-9c9e-07d62181477f.png)
![screenshot 17](https://user-images.githubusercontent.com/23044524/33413838-06bec4ee-d5e6-11e7-88e9-53d6ee5ee6ac.png)
![screenshot 18](https://user-images.githubusercontent.com/23044524/33413894-0e83fba4-d5e6-11e7-8d06-1ab86d3ecaab.png)
![screenshot 19](https://user-images.githubusercontent.com/23044524/33413937-1501063e-d5e6-11e7-9ba6-38db3ee951d3.png)

**Comment by bhsmither** [comment]
I wonder if creating the error_log would give a clue...
https://forums.cubecart.com/topic/51550-how-to-create-the-error-log/

**Comment by sumwonlost** [comment]
I created page, I get a white screen and cannot see/find the mentioned log file.

When logging into Admin, it gives me message that I am using 6.1.13 files but not databases and to run setup procedure.

When I check System Log files I get the following error

File: [database.class.php] Line: [517] "ALTER TABLE `CubeCart_option_matrix` ADD `cached_array` TEXT NOT NULL AFTER `cached_name` " - Duplicate column name 'cached_array'

I will now clean cache and check db for issues, unless you have a better option/recommendation/solution?

If all fails, I will revert back to 6.1.10 and upgrade to 6.1.11 and so on.

**Comment by sumwonlost** [comment]
Keep getting same error message. > 300 in less than a few mins.

**Comment by sumwonlost** [comment]
Found the error Log file in Setup Folder.  I keep getting the following repeated.

PHP Notice:  Undefined index: db_converted in /var/www/vhosts/XYZ.com/site1/XYZ.com/setup/setup.upgrade.php on line 111

PHP Notice:  Undefined index: config_converted in /var/www/vhosts/XYZ.com/site1/XYZ.com/setup/setup.upgrade.php on line 142

**Comment by bhsmither** [comment]
A "white screen"... that rarely happens.

You get the `ALTER TABLE` error message 300 times? Interesting.

PHP Notices can be ignored.

**Comment by sumwonlost** [comment]
Issue Fixed - I previously upgraded to 6.1.11 then 6.1.12 before deciding to revert back to 6.1.10.

When checking Update History, it showed that I had previously Updated to these, I went to history db and deleted 6.1.11 and 6.1.12 entries then tried again, this time it worked without issue.

All errors are now gone

**Comment by sumwonlost** [comment]
Thanks for your assistance.
