### ISSUE TITLE
Product Options Display

### ISSUE THREAD

**Issue by sparrowme** [cubecart/v6#1824]
After upgrade to 6.1.13  Product Options displays labels with only the first character.
![image](https://user-images.githubusercontent.com/1423504/33517620-69d2bde0-d755-11e7-9491-45c65c06fe0d.png)

**Comment by bhsmither** [comment]
Possibly a duplicate of:
https://github.com/cubecart/v6/issues/1533
Please see:
https://forums.cubecart.com/topic/52268-resolved-with-1533-github-options-issue/
https://forums.cubecart.com/topic/52461-options-strange-behaviour/

Please verify if your installation of CubeCart may have more than one admin folder. If you upgraded from CC616 or earlier, and if there are more than one admin folder, CubeCart may be using the older folder.

**Comment by sparrowme** [comment]
I tried every variation of moving/removing any admin folders restoring/ reupgrading etc.. couldn't find it.  Resorted to new install and manually moving images, plugins etc..  working now.  Thanks for the ideas @bhsmither
