### ISSUE TITLE
AIOS Assignment to EXTRA_JS

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1825]
The AIOS module, admin.inc.php file is using `Smarty->assign()` an array to `EXTRA_JS`.

Suggest using `Smarty->append()` a string to `EXTRA_JS` as a requirement for modules.

This allows for other non-plugins to add their javascript files. (Only plugins can use hooks.)

**Comment by abrookbanks** [comment]
Thanks for this. Confirmed working with AIOS 1.0.11
