### ISSUE TITLE
Admin Skin to Stand Apart

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1826]
In `controller.admin.session.true.inc.php`, some CSS files are loaded from CubeCart's /js/styles/ folder.

Suggest that the CC6 admin skins restrict loading their page resources from their own respective folder.

(There is currently some styling conflicts affecting jQuryUI and its style files, and those style files are referencing images that do not exist in the other location.)

**Comment by abrookbanks** [comment]
The whole block is redundant as far as I can see but it might explain mix of versions in your other issue.
