### ISSUE TITLE
jQueryUI to be Updated

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1827]
Suggest getting the latest "all-inclusive" package of jQueryUI.

Currently at 1.12.1, the default admin skin seems to have 1.10.4 (although filename claims 1.11.2), and /js/ probably loads 1.7 and the CSS for parts of it.

**Comment by abrookbanks** [comment]
/js was left for legacy skins that rely on it.

**Comment by abrookbanks** [comment]
This has introduced a number of bugs so reverting to previous version which has proved stable.

**Comment by bhsmither** [comment]
A buggy version of jQueryUI? Or are there some incompatibilities of CubeCart skin code with it?

If incompatible, curious to know of a few instances.

**Comment by Dirty-Butter** [comment]
I've commented twice on GitHub about problems I'm having with 6.1.14. No amount of double checking my code has found the issue. So I'll revert jQueryUI and report my results.

**Comment by bhsmither** [comment]
Are you referring to #1847?

**Comment by Dirty-Butter** [comment]
That was the one I posted. I reverted to 6.1.13 and then tried more recent 6.1.14 again with exactly the same results. The enable/disable process is very unpredictable. I can see the JS throbber trying to load for just a second, and then it crashes. I also commented on something else in 6.1.4 that didn't work for me - but I can't think now exactly what it was - I couldn't get that to work without commenting out one line of code - something to do with coupons.
Haven't had time today to revert the script yet.

**Comment by Dirty-Butter** [comment]
I reverted per #1827 and the check boxes appear to be working correctly now. Will continue to test several places and report back if I find any pages where enable/disable is still not operating correctly. The plugin that I originally was having issues with is still crashing, but the enable/disable for that plugin on the summary plugins page IS working correctly.
