### ISSUE TITLE
Sort Search Results Broken?

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1828]
A few 6.1.13 store owners have mentioned that sorting the search results does not actually change the order products are displayed in.

I believe this is because the '$order' variable in the 'searchCatalogue' function does not get populated and sticks with the default sorting set in config.

Has anyone else encountered this in a 6.1.13 store?

**Comment by briansandall** [comment]
Can confirm, but to me the problem seems to be that the sort parameters never get added to the URL - the page redirects to the exact same URL every time.

**Comment by abrookbanks** [comment]
Is this with stock skin?

**Comment by briansandall** [comment]
Yep; on my vanilla test store that was on v6.1.10, search and sort were working.

Pulled v6.1.13 and hard refreshed the page that had sorted search results, but now shows "No products found"

URL from 6.1.10:
http://localhost/git/forks/cubecart/v6/search.html?_a=category&search%5Bkeywords%5D=product&sort%5Bprice%5D=ASC

URL from 6.1.13 after re-running search:
http://localhost/git/forks/cubecart/v6/search.html?search%5Bkeywords%5D=product&_a=category&token=f233f919cd0318b12e4150728b7c1dd3

And after trying to sort:
http://localhost/git/forks/cubecart/v6/search.html?_a=category&search%5Bkeywords%5D=product

Note how it is now missing the token and did not have any sort parameter added.

**Comment by whitepandaltd** [comment]
I'm also having the same issues I use semperfi custom foundation 5 skin but it is doing exactly the same on the cubecart foundation skin.

https://indoorxtreme.co.uk

Sort does not work and search does not bring up the correct products on the store front, an example is that if you search 'foam bo', the semperfi ajax dropdown search brings up the correct products where as the cubecart search results are incorrect products and can not be sorted. This is the same that in any category products can not be sorted.

**Comment by abrookbanks** [comment]
Pretty sure this is fixed with #1855.

**Comment by whitepandaltd** [comment]
Search now works slightly better but 'sort by' does not work when you do a search. It seems to default and stay at relevance low/high.
example:
https://indoorx.uk/index.php
search: mesh bag

Nothing with mesh bag in the title is shown in the first 4 products

**Comment by abrookbanks** [comment]
Not sure is this helps https://github.com/cubecart/v6/blob/6.1.14-branch/classes/cubecart.class.php#L747
