### ISSUE TITLE
Remove useless id field in Admin ->Categories

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#1831]
What is the purpose of displaying this field?  It has no purpose that I can see.  Do I care what id number it is in my db?

**Comment by abrookbanks** [comment]
Please see: https://support.cubecart.com/Knowledgebase/Article/View/32/41/how-do-i-use-the-bulk-product-import-tool

When using the import tool the cat_id is useful to know.

**Comment by sumwonlost** [comment]
Thanks Al for the explanation, I can live with it now I know.  It was annoying me as I could not see the purpose.
