### ISSUE TITLE
Options Absolute Price - Symbols Bug

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1834]
When using an option with absolute price enabled, then purchase that item.. as the admin review the order and check the Items list. 

In that list the product options still reference the +/- symbols, but for absolute prices there should be no symbols. 

The same information is then used by the email templates for order confirmations, including the +/- symbol in the mail. As the price was absolute no symbols should be included.

**Comment by abrookbanks** [comment]
Turned out to be pretty simple. :P
