### ISSUE TITLE
Add indexes to DB

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1836]
A few more columns that need indexes plus they should be added to the DB check

CubeCart_shipping_rates.zone_id
CubeCart_shipping_rates.min_weight
CubeCart_shipping_rates.max_weight
CubeCart_shipping_rates.min_value
CubeCart_shipping_rates.method_name
CubeCart_shipping_zones.zone_name

CubeCart_customer_group.group_name
CubeCart_pricing_group.tax_type
CubeCart_tax_rates.type_id
CubeCart_tax_rates.active
CubeCart_tax_rates.country_id

CubeCart_order_inventory.quantity

CubeCart_code_snippet.enabled

There are more but this is a start !

**Comment by abrookbanks** [comment]
Thanks Ian!! :)

**Comment by havenswift-hosting** [comment]
CubeCart_hooks.enabled

CubeCart_documents.doc_home
CubeCart_documents.doc_status
CubeCart_currency.active

**Comment by abrookbanks** [comment]
Looking at `CubeCart_shipping_rates` I only see DB queries indexing `id` and `zone_id`. `id` is the primary index so I think we just need an index for `zone_id`. Have you seen conditions or joins on the other ones listed above? I'm not sure we need to add them?

**Comment by havenswift-hosting** [comment]
I did, which is what prompted me adding them to the list above.  I was going through the MySQL generated slow-query log to which unindexed queries had also been added

**Comment by abrookbanks** [comment]
OK thanks. :)

**Comment by abrookbanks** [comment]
Thanks so much Ian.
