### ISSUE TITLE
Indexes not being added or detected

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1837]
The DB checker has been a great addition but just discovered an unusual situation.

Site was upgraded from V4 to V6 and went smoothly. The MySQL profiler tool I use highlighted some poorly performing queries due to missing indexes which were CubeCart_sessions.session_last and CubeCart_sessions.customer_id

Two issues

1) These should have been added in the 5.0.0b1.sql upgrade script but werent for some reason
2) The database index checking tool should have picked these up as missing but didnt

Not sure if this is something to do with the upgrade, the fact the database has a prefix or something else ?

**Comment by abrookbanks** [comment]
Mine does...

![screen shot 2017-12-14 at 14 32 05](https://user-images.githubusercontent.com/4520803/33997222-9ac59082-e0db-11e7-8b4c-df05019d294f.png)

**Comment by abrookbanks** [comment]
Pretty confident the index checker tool is working.

**Comment by havenswift-hosting** [comment]
Well the syntax error with adding the indexes explains why they werent created - this will have happened to thousands of sites !

The index checker works for me on 99% of the many hundreds of sites that I have used it on but there are always exceptions or differences to the way your test site is setup.

![database_indexes](https://user-images.githubusercontent.com/6114431/33999315-779b0d44-e0ea-11e7-8f16-2d10f58c9a0d.png)

The above shows that the two additional indexes dont exist on the database

![no_errors](https://user-images.githubusercontent.com/6114431/33999418-b962458a-e0ea-11e7-8ffc-9d25d33a7933.png)

The above shows that those two missing indexes are not displayed as missing

**Comment by abrookbanks** [comment]
Are these stores all on the same mySQL version? Maybe the syntax isn't right for all versions or config.

**Comment by havenswift-hosting** [comment]
Yep, on one of our shared hosting servers with a large number of other V6 CubeCart sites and running PHP7.0 which many others are doing as well on that server

**Comment by abrookbanks** [comment]
I'd need to debug this on a store not finding the missing index.

**Comment by havenswift-hosting** [comment]
Happy to give you access - let me know what you need and how to securely pass login information to you and you can take a look
