### ISSUE TITLE
Update Basket Quantity Fails

### ISSUE THREAD

**Issue by nklisic** [cubecart/v6#184]
In desktop site don't work update chart.

**Comment by abrookbanks** [comment]
Please can you provide more information.

**Comment by nklisic** [comment]
​Hi Al,
Update shopping chart in desktop site don't work. When change quantity of
product or shipping options ​(i don't check promotional code) after click
on Update Chart button don't update shopping chart.

Regards,
Nebojsa

2015-02-05 15:54 GMT+01:00 Al Brookbanks <notifications@github.com>:

**Comment by abrookbanks** [comment]
I see.. thanks for this. :) I'll get onto it ASAP.

**Comment by abrookbanks** [comment]
Fixed with media query detection
