### ISSUE TITLE
USPS Requests Twice

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1841]
With certain situations, USPS is requested twice. (Not that it matters all that much to them. But it does take time.)

I have not determined where/when this happens.

It could even be that the request happens once, but the Request/Response gets logged twice.

**Comment by briansandall** [comment]
Only USPS, or all shipping APIs?

Does it get requested twice in a single page load, or could it be a customer refreshing the page and/or the initial shipping estimate during checkout?

**Comment by bhsmither** [comment]
I am currently analyzing my tracing of the CubeCart's code execution when _a=basket and _a=checkout.

I notice this situation based on the fact that there are two log entries in the Request log, one dated instantaneously after the other. This is my development installation, with myself testing the next version of the USPS shipping module, so I am acutely aware of what buttons are being pressed.

The USPS module is currently the only module enabled (during development) that uses the Request logging capability.

**Comment by abrookbanks** [comment]
I can reproduce this with about one second between each log. I expect a redirect is loading the code more than once. Maybe the solution is to cache the request. Currently it is set to false. 

As you will have seen CubeCart relies on a load of redirects all the time. I think this issue has to just be taken in the sense that its a major architecture thing. A page may load to 95% then reload based on a condition. Does this make CubeCart a badly written beast. Yes, maybe so. 

I added some debug code to write to file the value of the _GET variable "_a" and it had a value of "checkout" with both logs and one second between. 

```
$request	= new Request($this->_url, $this->_path);
$fp = fopen('usps.txt', 'a+');
fwrite($fp, $_GET['_a'].' - '.(string)time()."\r\n");
fclose($fp);
$xmlData = $xml->getDocument();
$request->setData("API=".$this->_api."&XML=".$xmlData);
```

**Comment by abrookbanks** [comment]
Somewhere for some reason the page is redirecting. This is why it's sometimes. 

Clearly too much is happening before the page reloads. I don't think I can fix this other then encouraging caching on the curl request.
