### ISSUE TITLE
Hook Request - catalogue.class.php

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1842]
A hook after the search query would be useful, meaning the results can be modified or the query overwritten with a custom one.

FIND:
`if (($sale = $GLOBALS['db']->query($query)) !== false) {`

BEFORE ADD:
`foreach ($GLOBALS['hooks']->load('class.cubecart.search_catalogue') as $hook) include $hook;`

**Comment by abrookbanks** [comment]
:)
