### ISSUE TITLE
Newsletter Signup Box Temperamental 

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1843]
![screen shot 2017-12-21 at 15 26 39](https://user-images.githubusercontent.com/4520803/34262136-5bc57612-e663-11e7-9495-6ab27784334f.png)

Seems to work some times and not others.

**Comment by bhsmither** [comment]
I cannot discern what the screen grab is supposed to illustrate. "Work" and "not work" isn't descriptive.

**Comment by abrookbanks** [comment]
I don't really know why I added it. Anyway from my tests it's not working. Page just reloads. No email added.

**Comment by bhsmither** [comment]
CSRF?

**Comment by abrookbanks** [comment]
Dunno yet. Maybe but no message about it...

**Comment by abrookbanks** [comment]
`$_POST['subscribe']` is missing when we get here:
https://github.com/cubecart/v6/blob/master/classes/gui.class.php#L1086

Changing the variable name shows but I can't see where this is unset....
