### ISSUE TITLE
Code Intent

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1846]
In `Tax->priceFormat()`, if the `$default_currency` flag is true-ish, then `Tax->loadCurrencyVars()` is called having an argument of `Config->default_currency`.

In `Tax->loadCurrencyVars()`, if the argument is **not false-ish** - meaning it is possible that this function could be asked to load any currency by its code - the only result is to load `Config->default_currency`.

1. Is the intent of `Tax->loadCurrencyVars()` to restrict the choice to either the client's current currency or the default currency?

2. Is the intent of `Tax->priceFormat()` , after having loaded the default currency, to have no code to somehow switch it back to the client's current currency?

**Comment by abrookbanks** [comment]
I don't know to be honest Brian but I can't see any bug resulting from this so I'm going to leave it as it is.

**Comment by bhsmither** [comment]
Working on a code edit to have the PayPal (standard) gateway be able to send the currency the customer had chosen to display. (A one-off project, so far. Store owner says his PayPal account can hold a mish-mash of currencies.)

I will reconfirm that `Tax->priceFormat()` will not switch back to the client's current currency, and develop some alternate plan.
