### ISSUE TITLE
Possible heads up to 6.1.14 issue

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1847]
This is probably just some error I've made, but I had our plushcatalog store running just fine on 6.1.14 and needed to change the status of a couple of plugins today. The status box would not accept the change to the check mark. Or course it could be the plugins were not yet compatible with 6.1.14. Anyway, thought I'd let you know.

**Comment by bhsmither** [comment]
Does the status box on the general Extensions List work? (Before you get into the settings screen of any one extension?)

**Comment by Dirty-Butter** [comment]
No - it was unchecked and nothing I did would make it check. I even tried going into phpMyAdmin and manually changing the status - still didn't show as enabled. I tried several different plugins and could not get any to change the checkmark. The estates site is still on 6.1.14 and it is working properly - doesn't have as many plugins though. I did a compare of the two sites and could not find the difference that was causing it. I DO realize it's likely my error, but so strange.

**Comment by bhsmither** [comment]
If I recall, those checked boxes are actually images and the images of the checked box and unchecked box is javascript controlled.

Perhaps forcing your browser to reload the admin pages' resources?

**Comment by abrookbanks** [comment]
Sorry but I can't reproduce this problem. Please look in your browser console for any JS errors.

**Comment by bhsmither** [comment]
When this was happening, did your product image FilePicker box also malfunction (wrt checkboxes)?

**Comment by Dirty-Butter** [comment]
I don't remember trying that. - sorry, I've been dx with memory issues - a lot of short term stuff just disappears from my head these days
