### ISSUE TITLE
Smarty variable $CRUMBS outside of main

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1848]
The smarty variable "CRUMBS" only appears to exist/work on the main pages. Trying to access it elsewhere, such as the product page the variable is NULL, this limits the layout if you want to use crumbs in a different way based on each templated page.

It doesn't exist within the $PAGE_CONTENT data

**Comment by abrookbanks** [comment]
I don't understand as I see this on the product page of both admin and front end?

![screen shot 2018-01-02 at 12 32 22](https://user-images.githubusercontent.com/4520803/34483862-0caea1fc-efb9-11e7-84e0-29666496e2f9.png)
![screen shot 2018-01-02 at 12 32 12](https://user-images.githubusercontent.com/4520803/34483863-0cc7fbfc-efb9-11e7-9b0c-0b3d1e8c00dc.png)

What are you trying to do?

**Comment by Noodleyman** [comment]
building a custom theme which requires different trails based on the page being loaded, try and use $CRUMBS within content.product.php ;)

It doesn't exist.

**Comment by abrookbanks** [comment]
Ah ok I see. :)

**Comment by abrookbanks** [comment]
Hi Alec, I can't find a solution for this unless we change `{$PAGE_CONTENT}` into something like `{include file='templates/content.{{DYNAMIC_VALUE}}.php'}`. 

That might or might not work but either way its a fairly considerable architectural change. I think for now I have to admit defeat over this hopefully not too critical issue.

**Comment by abrookbanks** [comment]
If you can use a hook to execute this in the suitable section it might work so long as the associatd CRUMBS template syntax is there too....

```
$GLOBALS['smarty']->assign('CRUMBS',$GLOBALS['gui']->getBreadcrumbs());
```
