### ISSUE TITLE
Code improvements

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1849]
in gui.class.php  the following placement of hooks allows modules to add scripts/css for skins. However, it expects the module/hook to create the array. if you have two or more modules installed which create the array they conflict.

This should be resolved by creating the array in the class file, then allowing modules to add to it.
```
			foreach ($GLOBALS['hooks']->load('class.gui.css') as $hook) include $hook;
			if (isset($css) && !empty($css) && is_array($css)) {
				$GLOBALS['smarty']->assign('CSS', $css);
			}

			// <head> JS
			foreach ($GLOBALS['hooks']->load('class.gui.head_js') as $hook) include $hook;
			if (isset($head_js) && !empty($head_js) && is_array($head_js)) {
				$GLOBALS['smarty']->assign('HEAD_JS', $head_js);
			}

			// <body> JS (Top)
            foreach ($GLOBALS['hooks']->load('class.gui.body_js_top') as $hook) include $hook;
            if (isset($body_js_top) && !empty($body_js_top) && is_array($body_js_top)) {
                $GLOBALS['smarty']->assign('BODY_JS_TOP', $body_js_top);
            }

			// <body> JS
			foreach ($GLOBALS['hooks']->load('class.gui.body_js') as $hook) include $hook;
			if (isset($body_js) && !empty($body_js) && is_array($body_js)) {
				$GLOBALS['smarty']->assign('BODY_JS', $body_js);
			}
```

**Comment by abrookbanks** [comment]
I can't see anything needs to be changed as you can check and [array_merge](http://php.net/manual/en/function.array-merge.php). 

Say you have two hooks for class.gui.head_js.php

1. modules/plugins/**A**/hooks/class.gui.head_js.php
```
$a_js = array('A.js');
if (isset($head_js)  && is_array($head_js)) {
  $head_js = array_merge($head_js, $a_js);
} else {
  $head_js =$a_js;
}
```
2. modules/plugins/**B**/hooks/class.gui.head_js.php
```
$b_js = array('B.js');
if (isset($head_js)  && is_array($head_js)) {
  $head_js = array_merge($head_js, $b_js);
} else {
  $head_js =$b_js;
}
```
Result:
```
$head_js =array (
  'A.js',
  'B.js'
);
```

**Comment by abrookbanks** [comment]
Please let me know if I missed something or if I misunderstood and I will reopen.

**Comment by abrookbanks** [comment]
Actually you can just use array_push like;

```array_push($head_js, "A.js");```

**Comment by abrookbanks** [comment]
Reopening as I agree that this code can be improved.

**Comment by Noodleyman** [comment]
one of the reasons for creating the array before you start to use it is to prevent an error in the server log.

**Comment by abrookbanks** [comment]
Yup. I got that as I was staring out the kitchen window making my 3rd cup of tea.

**Comment by Noodleyman** [comment]
hah, there's the problem... it's coffee time :)

**Comment by abrookbanks** [comment]
> hah, there's the problem... it's coffee time :)

LOL. Quick coffee then first alcoholic drink before 9am.

**Comment by abrookbanks** [comment]
Thanks for the cool suggestion. It will work well and Smarty is very forgiving so this will work without having to add conditionals to the template files.

**Comment by Noodleyman** [comment]
turbo coffee, to get to the peak of the curve..... 

11am, crash :(,

your welcome :)

**Comment by abrookbanks** [comment]
Right next bug report.. p.s. can you lot stop giving me work!! :stuck_out_tongue_winking_eye:
