### ISSUE TITLE
Order->_sendCoupon() to use Language

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1852]
Suggest two hard-coded phrases be re-coded to use the language pack.

**Comment by abrookbanks** [comment]
Thanks. I moved to language pack.

**Comment by Dirty-Butter** [comment]
I'm having an issue with this gc_specific_error code change in order.class.php. Using the new version in order.class.php causes the orders page in admin to crash. I do have the new wording added to the definitions.xml file.

**Comment by Dirty-Butter** [comment]
Commenting out line 1351 (gc_specific_error) in stock 6.1.14 order.class.php allows the order page to load properly.
