### ISSUE TITLE
Gift Certificate Email Not Sending + Other Issues

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1854]
Recently I encountered an issue with a customers store where the gift certificate email was not being sent.

In a clean 6.1.13 '/classes/order.class.php' file there is this:
```
	private function _sendCoupon($coupon_id, $data) {
		if (!empty($coupon_id)) {
			if (($coupon = $GLOBALS['db']->select('CubeCart_coupons', false, array('coupon_id' => (int)$coupon_id, 'email_sent' => 0))) !== false) {
				$mailer = new Mailer();
				if (isset($coupon[0]['value'])) {
					$coupon[0]['value'] = Tax::getInstance()->priceFormat($coupon[0]['value']);
				}
				$data['storeURL']  = $GLOBALS['storeURL'];
				if (($content = $mailer->loadContent('cart.gift_certificate', $this->_order_summary['lang'], array_merge($this->_order_summary, $data, $coupon[0]))) !== false) {
					$GLOBALS['db']->update('CubeCart_coupons', array('email_sent' => 1), array('coupon_id' => (int)$coupon_id));
					if(($return = $mailer->sendEmail($data['email'], $content)) !== false) {
						$GLOBALS['db']->update('CubeCart_coupons', array('email_sent' => 1), array('coupon_id' => (int)$coupon_id));
					} else {
						$error = 'Failed to send gift card by email. Please check <a href="?_g=settings#Advanced_Settings">email configuration</a>.';
						if(isset($mailer->ErrorInfo) && !empty($mailer->ErrorInfo)) {
							trigger_error($mailer->ErrorInfo, E_USER_WARNING);
							$GLOBALS['gui']->setError($error.' A specific error message may be found in the <a href="?_g=settings&node=errorlog#system_error_log">error log</a>.', true);
						} else {
							$GLOBALS['gui']->setError($error, true);
						}
					}
					return $return;
				}
			}
		}
		return false;
	}
```

Problem 1 - Attempt Made To Format Price On Invalid Value
This:
```
				if (isset($coupon[0]['value'])) {
					$coupon[0]['value'] = Tax::getInstance()->priceFormat($coupon[0]['value']);
				}
```
Should Be This:
```
				if (isset($data['value'])) {
					$data['value'] = Tax::getInstance()->priceFormat($data['value']);
				}
```
As the 'value' is in the '$data' array, not the '$coupon' array.
There is also the possibility that the price has already been formatted, so this could probably be removed.

Problem 2 - Incorrect Update Of 'email_sent' Value In 'CubeCart_coupons' Table
That first update should not happen as the attempt to send the email has not happened yet.
So in stock 6.1.13 code, the update on line 1346 should be removed.

Problem 3 - Incorrect Case In The '$item['custom']' / '$data' Array
In the 'orderStatus' function, the '_sendCoupon' function (above) is invoked using this:
```
					if ($this->_email_enabled) {
						foreach ($this->_order_inventory as $item) {
							// Send Gift Certificate
							if (!empty($item['custom']) && !empty($item['coupon_id']) && $item['digital']) {
								$this->_sendCoupon($item['coupon_id'], unserialize($item['custom']));
							}
						}
					}
```
as part of the order complete status, more on that in problem 4.
When looking into this, I found that the '$data' array had uppercase first letters for each key.
i.e.
```
Data Key: Value
Data Value: $100.00
Data Key: Name
Data Value: Test Recipient
Data Key: Email
Data Value: semperfi@cubecartservices.biz
Data Key: Message
Data Value: A Gift Certificate For You!
Data Key: Method
Data Value: Email
```
But when looking in 'basket' array in the store itself, the keys first letter was lowercase.
i.e.
```
'__basket' =>
'contents' =>
'dbe10ed6da2de76c3919cbd4e067a569' =>
'id' => GC
'quantity' => 1
'digital' => 1
'certificate' =>
	'value' => 100
	'name' => Test Recipient
	'email' => semperfi@cubecartservices.biz
	'message' => A Gift Certificate For You!
	'method' => e
'tax_each' =>
'weight' => 0.0000
'discount' => 0.00
'subtotal' => 100.00
'total_tax' => 0.00
'total' => 100.00
'shipping_hash' => a2072c8a50f1127f73a55a6b5f574da7
'order_taxes' =>
'shipping' => 0
'digital_only' => 1
```
So somewhere in the process of serializing/unserializing the the data, the incorrect casing is used.
This causes the email not to send as it expects lowercase.
i.e.
```
					if(($return = $mailer->sendEmail($data['email'], $content)) !== false) {
						$GLOBALS['db']->update('CubeCart_coupons', array('email_sent' => 1), array('coupon_id' => (int)$coupon_id));
					} else {
						$error = 'Failed to send gift card by email. Please check <a href="?_g=settings#Advanced_Settings">email configuration</a>.';
						....
```
To resolve it, I forced lowercase keys for the '$data' array in the '_sendCoupon' function.
i.e.
```
	private function _sendCoupon($coupon_id, $data) {
		if (!empty($coupon_id) && !empty($data) && is_array($data)) {
			$data = array_change_key_case($data, CASE_LOWER);
```
As you can see above, I also implemented checks for:
- $data not being empty
- $data is an array

Problem 4 - Gift Certificate Gets Sent When Order Set To Complete
As noted in problem 3 above, the '_sendCoupon' function gets invoked as part of the 'orderStatus' function when an order is set to complete.
This is fine if the order is digital only, as setting an order to processing will then automatically change the status to complete.
But if the order is not digital only, the attempt to send the email won't be done until the store owner manually changes the order status to complete.
As a suggestion, move (or copy) this:
```
					if ($this->_email_enabled) {
						foreach ($this->_order_inventory as $item) {
							// Send Gift Certificate
							if (!empty($item['custom']) && !empty($item['coupon_id']) && $item['digital']) {
								$this->_sendCoupon($item['coupon_id'], unserialize($item['custom']));
							}
						}
					}
```
from the 'ORDER_COMPLETE' case to the 'ORDER_PROCESS' case.
i.e.
```
					if ($this->_email_enabled) {
						foreach ($this->_order_inventory as $item) {
							// Send Gift Certificate
							if (!empty($item['custom']) && !empty($item['coupon_id']) && $item['digital']) {
								$this->_sendCoupon($item['coupon_id'], unserialize($item['custom']));
							}
						}
					}

					// Send digital files
					$this->_digitalDelivery($order_id, $this->_order_summary['email']);
```

**Comment by SemperFiWS** [comment]
Here is my complete '_sendCoupon' function.
```
	private function _sendCoupon($coupon_id, $data) {
		if (!empty($coupon_id) && !empty($data) && is_array($data)) {
			$data = array_change_key_case($data, CASE_LOWER);
			if (($coupon = $GLOBALS['db']->select('CubeCart_coupons', false, array('coupon_id' => (int)$coupon_id, 'email_sent' => 0))) !== false) {
				$mailer = new Mailer();
				if (isset($data['value'])) {
					$data['value'] = Tax::getInstance()->priceFormat($data['value']);
				}
				$data['storeURL']  = $GLOBALS['storeURL'];
				if (($content = $mailer->loadContent('cart.gift_certificate', $this->_order_summary['lang'], array_merge($this->_order_summary, $data, $coupon[0]))) !== false) {
					if(($return = $mailer->sendEmail($data['email'], $content)) !== false) {
						$GLOBALS['db']->update('CubeCart_coupons', array('email_sent' => 1), array('coupon_id' => (int)$coupon_id));
						$GLOBALS['gui']->setNotify('Successfully sent gift card by email!', true);
					} else {
						$error = 'Failed to send gift card by email. Please check <a href="?_g=settings#Advanced_Settings">email configuration</a>.';
						if(isset($mailer->ErrorInfo) && !empty($mailer->ErrorInfo)) {
							trigger_error($mailer->ErrorInfo, E_USER_WARNING);
							$GLOBALS['gui']->setError($error.' A specific error message may be found in the <a href="?_g=settings&node=errorlog#system_error_log">error log</a>.', true);
						} else {
							$GLOBALS['gui']->setError($error, true);
						}
					}
					return $return;
				}
			}
		}
		return false;
	}
```

**Comment by bhsmither** [comment]
P1. There is no 'value' column for CubeCart_coupons. So, `isset($coupon[0]['value'])` resolves to `false`.

P2. See #1853. But there is no harm done as it is.

P3. I cannot duplicate. This is sample data from `CubeCart_order_inventory.custom`:
```
a:5:{s:5:"value";s:5:"35.00";s:4:"name";s:12:"GC Recipient";s:5:"email";s:34:"gc_recipient@xxx.com";s:7:"message";s:7:"Test #4";s:6:"method";s:1:"m";}
```
Note your contents of `$data` where:
```
'Method' => 'Email'
```
CubeCart uses a single letter, `e` or `m`. (I think for both digital and physical (set in admin, GC), there is insufficient code in `Order->_orderAddProduct()` to handle this.)

If I saw your `$data`, I would verify with the contents of `CubeCart_order_inventory.custom`. If the database `custom` data is correct, I would start looking for where `$data` gets corrupted. If the database `custom` data is not correct, I would look for where that is happening.

P4. I concur with a digital GC.

**Comment by bhsmither** [comment]
This is where I last worked on this:
https://forums.cubecart.com/topic/53174-giftcard-not-sending-email/
A bad spelling for the key 'email' would certainly cause the mailer to return false.

**Comment by bhsmither** [comment]
Well, now I am seeing P3. This was not the case when I looked in the database, CubeCart_order_inventory, 'custom' column from... ew, December 2016.

So, comparing CC611 with CC6113, I find that in orders.index.inc.php, lines 317-342, there is code that will pretty-fy GC parameters.

However, this is for display purposes only, yet the altered parameters are loaded into form text entry boxes.

When the order is moved to Completed, all form data is updated in `CubeCart_order_inventory` prior to calling `Order::orderStatus(3)` (probably, will verify shortly, including GC parameters that act as keys to the 'custom' array).

See `element.product_options.php`.

**Comment by abrookbanks** [comment]
Thanks guys some good finds here. I think I covered them all aside from problem 2 which is covered in a different issue. Sending formatted prices to the formatPrice method doesn't matter:
https://github.com/cubecart/v6/blob/6.1.14-branch/classes/tax.class.php#L332
