### ISSUE TITLE
Add product category name to Google Analytics for ecommerce

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1859]
This makes the category name available for use in analytics, using either Google ga.js or analytics.js 

looks like a simple query change in cubecart.class.php to just join CubeCart_inventory and then CubeCart_category,  or just query the category index to get the cat_id then lookup the cat name to get the correct category

**Comment by abrookbanks** [comment]
~~Does it need to be an approved Google defined category or anything?~~

Sorry I'm being lazy. Looks like it can be any format. 

![screen shot 2018-02-19 at 11 18 10](https://user-images.githubusercontent.com/4520803/36375275-9bdb49f2-1566-11e8-9470-04bc5541c703.png)

**Comment by abrookbanks** [comment]
![screen shot 2018-02-20 at 16 06 52](https://user-images.githubusercontent.com/4520803/36434963-3a5891e2-1658-11e8-95bd-cf55a075b530.png)

**Comment by havenswift-hosting** [comment]
Will you be going back and updating https://github.com/cubecart/v6/issues/1858 with this ?

**Comment by abrookbanks** [comment]
It has been on the 6.2 branch but not the 6.1.14 branch.

**Comment by havenswift-hosting** [comment]
Would have seen that if I checked the commit but it was 01:30 !

Using $item.product_id for the category name though ?

**Comment by abrookbanks** [comment]
> Using $item.product_id for the category name though ?

Nope. It uses the product id index to find it.
