### ISSUE TITLE
Admin Order Creation

### ISSUE THREAD

**Issue by demeterbee** [cubecart/v6#186]
Seems to be a problem with the admin order creation. 
On the 'Delivery' page the Shipping Method doesn't seem to do anything. As at this point it may not know the weight of the shipment maybe needs to be on the inventory page ?
On the inventory page, the first product line is fine but if additional product lines are added using the + and the Save button is pressed then the last line added is lost on the Overview although the totals still think its there.
The shipping line has no value, Maybe could be a drop down that lists the available shipping methods based on weight and the delivery address?
The VAT line currently doesn't seem to do anything. Even if a value is entered and the totals are refreshed the value is not included in the totals. Could it be automatically calculated using the existing drop down to select the rate but based on the delivery location?

**Comment by havenswift-hosting** [comment]
There is an old issue under the 5.2.14 list (https://github.com/cubecart/v5.2.14/issues/94) that requested a lot of enhancements to make the admin order entry program much more useful.  As enhancements are only being added to V6, can those be added / merged with this issue

**Comment by abrookbanks** [comment]
I'd like to overhaul this for 6.1.

**Comment by demeterbee** [comment]
That would be good, I use this alot for instance when a customer phones I can take a verbal order and get it into 'the system', likewise when a customer comes into the shop I use it to create an order/invoice.

**Comment by jetacera** [comment]
To add to this request, it would be very helpful to have a function where the admin can request to send an email to the customer when the order is created. This would notify the customer to login and make the payment (if needed) - which would require a way for them to  "Complete Payment" (see the issues from the cubecart.com forums [http://forums.cubecart.com/topic/48763-create-manual-order-complete-payment/?hl=%2Bcomplete+%2Bpayment] and [http://forums.cubecart.com/topic/48060-manually-adding-orders/?hl=%2Bcomplete+%2Bpayment#entry198755])

**Comment by abrookbanks** [comment]
@jetacera this has already been added to v6. It's in the repository and will be available from the next release.

**Comment by havenswift-hosting** [comment]
We are currently working on a plugin that will add lots of additional functionality to the admin order program, including this.  This will take all features from our CubeCart V4 Enhanced Admin Order Entry mod that arent already in V6 and add them as a plugin - all of the above will be included

**Comment by havenswift-hosting** [comment]
Our Enhanced Order Entry plugin has now been released - details here https://www.havenswift-hosting.co.uk/cubecart-enhanced-admin-order-entry-plugin/

**Comment by abrookbanks** [comment]
The buy link just goes to an empty basket.

**Comment by havenswift-hosting** [comment]
Thanks Al - not sure how that happened but fixed now.  Will be adding it to the marketplace shortly as well

**Comment by abrookbanks** [comment]
Awesome. Great work Ian.

**Comment by Noodleyman** [comment]
available as part of:
https://www.cubecart.com/extensions/plugins/enhanced-admin-order-entry
