### ISSUE TITLE
Incorrect Email Template being sent

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1860]
I currently have no idea how this is happening or how to reproduce it.....

We have a proveable situation where the email template that was sent out to a customer (we have the actual email and can also see via the Email Logs) is the one taken from the default language file rather than the databased and changed version

**Comment by abrookbanks** [comment]
I've never seen this before. Please can you provide steps to reproduce this and I might be able to see whats going on.

**Comment by havenswift-hosting** [comment]
I havent seen it before either and as I said, I cannot provide steps to reproduce but there are also not a lot of stores using 2/3/4 languages so whether it is something to do with that ?  What I do is provide access to client store where you can clearly see from the Email Logs that some emails (not all) have been sent incorrectly - happy to provide these details

**Comment by abrookbanks** [comment]
Maybe you can get the client to submit a support ticket and I'll take a look.

**Comment by havenswift-hosting** [comment]
OK we also now have the cause of this issue.

At some stage US English was installed and some customers chose that as their language, it was later deleted but this doesnt tidy up correctly

When a language is deleted, it should

1) Delete all email templates installed for that language - these templates were being sent for these customers but werent editable as they didnt appear in the list of installed languages

2) All customers set to use a deleted language should be converted to store default

**Comment by havenswift-hosting** [comment]
OK we now also have the root cause of this issue - simple when you know what it is !

At some stage US English was installed on this site (along with various other languages as well) and some customers had chosen that and so had it recorded against their customer record.  This and the other languages were then deleted but this doesnt update / delete certain areas in Cubecart as it should do

If a language is deleted, it should also...

1) Any customers that have the deleted language set as their choice, should be updated to the store default language

2) Delete the email templates for that language !  These were the email templates that were being sent out to store customers but because the language had been "deleted", they werent visible or editable by the store admin !

**Comment by havenswift-hosting** [comment]
OK we now also have the root cause of this issue - simple when you know what it is !

At some stage US English was installed on this site (along with various other languages as well) and some customers had chosen that and so had it recorded against their customer record.  This and the other languages were then deleted but this doesnt update / delete certain areas in Cubecart as it should do

If a language is deleted, it should also...

1) Any customers that have the deleted language set as their choice, should be updated to the store default language

2) Delete the email templates for that language !  These were the email templates that were being sent out to store customers but because the language had been "deleted", they werent visible or editable by the store admin !

**Comment by havenswift-hosting** [comment]
Maybe also suggest when doing an upgrade to check whether customer records have invalid language settings and update to store default language if wrong and also check what languages are installed and delete any email templates installed where the language isnt - this will clean up any / all stores where this has happened

**Comment by abrookbanks** [comment]
I'll check tomorrow but it sounds like the other issue will fix this too. Not sure I agree with your first point about updating the record. I'd say keep it as it is and load the default language. What if it was say Spanish, the store takes it off and adds it back later.

**Comment by havenswift-hosting** [comment]
If the store owner deletes a language then it is usually because they dont want to use it any longer - keeping orphaned records in a database just in case they might change their mind later doesnt seem a good idea.  If they add it back at any time, then the email templates will be loaded again and customers can then switch to the language choice again if they wish

**Comment by abrookbanks** [comment]
Essentially since the fix of #1653 this is fixed too but yes I think some data integrity improvements can be made.

> 1. Any customers that have the deleted language set as their choice, should be updated to the store default language

Yes I think that is a good idea.

> Delete the email templates for that language !

From my testing it does. :)

> Maybe also suggest when doing an upgrade to check whether customer records have invalid language settings and update to store default language

I don't think we need to do this as its a bit of an over kill.. also there could be a issue that the store upgrades with just one language only for more languages to be added later down the major upgrade process. Some work can be done here but its not essential. Nothing is orphaned at any time.

**Comment by abrookbanks** [comment]
I don't think anything else is necessary. Code patches for issue #1653 will have most certainly fixed this too.
