### ISSUE TITLE
Bad UI behaviour in cart when customer adds a coupon code

### ISSUE THREAD

**Issue by PloughGuy** [cubecart/v6#1864]
Version: 6.1.13
Skin: Foundation as delivered

When customers add a coupon code, it is rejected and a red error banner directs them further down the page to select a payment method.  Once the payment method has been selected, the user is able to go back up the page to re-enter the coupon code.

To demonstrate:

- Definite a promotional coupon
- Create a cart
- Assign the Promotional Coupon to the cart
- Customer gets a red banner further down the page, below the payment method options, that says "Please select a payment method." The discount code is not accepted.
- Customer selects payment method.
- Now customer can go back up the page to apply the coupon a second time.

Why is there a dependency between the payment method and the coupon?  They are independent.

**Comment by abrookbanks** [comment]
You just need to make sure one of your payment methods is set to default. If non of them are this unwanted experience may happen.
