### ISSUE TITLE
Extra data for order summary smarty variable

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1866]
related to this:
https://forums.cubecart.com/topic/52966-google-opt-in-survey-reviews/

it won't work without a CubeCart code change because Google needs the ISO code for the delivery country but the solution in the thread says to use "country_d" which returns the country name.

requires a change in cubecart.class.php to add the ISO value, recommending adding to smarty as 'country_d_iso'

for reference:
https://support.google.com/merchants/answer/7106244

**Comment by bhsmither** [comment]
It seems Smarty has access to functions made available in `/includes/functions.inc.php`.

An experiment showed success. Assuming we have the name, go fetch the ISO:
```
{$SUM.country_d|getCountryFormat:'name':'iso'}
```
Hoping that `CubeCart->_complete()` and `_orders()`, which both use the `content.receipt.php` template, keeps the conversion* of `$order['country_d']` from 'numcode' to 'name'.

(*A horrible programming practice, IMO.)

**Comment by abrookbanks** [comment]
Nice solution!! Closing but let me know if it still needs work.
