### ISSUE TITLE
Option Matrix Product Codes - Clone issue

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1868]
When Product Clone is enabled and configured to clone Product Options Matrix options, as well as Generate a new product code, it doesn't work correctly.

If you clone a product, the product code at the main product product is generated. However, the product codes for the matrix items are that of the original item.

With the setting defined as "Generate" matrix codes should also be regenerated. 

The only way to get the codes to regenerate is by deleting the records for the new product in DB table CubeCart_option_matrix, but this isn't a desirable approach as you lose the other data at the matrix level.

**Comment by bhsmither** [comment]
The following does not add or subtract to the clone issue, but rather to refute the assertion that the only way to get product_codes different than the source item is to delete database records.

According to the code in `products.index.inc.php`, near line 247, if there is a `$_POST['option_matrix']`, which there will be if the Matrix Table is present, and then if the option_matrix`['product_code']` is missing or blank, there will be a code generated based on the master `product_code` appended with a postfix (auto-incrementing numerical suffix).

Therefore, deleting the values in the Options Matrix table, Product Code column will auto-create just these values when processing the saved form.

**Comment by abrookbanks** [comment]
Awesome! Thanks chaps!!
