### ISSUE TITLE
PayPal Pro Billing Address issue

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1872]
found this whilst performing validation on a store due to go live shortly.

I've replicated this issue using PayPal pro 1.1.11 and using PayPal Sandbox (also happens in live). I also replicated using the Foundation theme.

![image](https://user-images.githubusercontent.com/10614018/36377277-81ac6720-156e-11e8-8d3a-31fbd616b35e.png)

1) Add a product
2) go to checkout
3) Click Checkout with PayPal
4) Log into PayPal
5) provide your address details and pay
6) redirect back to CubeCart, now logged in as the created customer, but the error as per screen shot above is visible.

It appears that this happens if the County supplied in PayPal is either missing or does not exactly match the County in CubeCart, you then get stuck in a loop and can't pay for the goods.

For example, "London" is the county of choice in PayPal, but in CubeCart it is "Greater London", this causes a mismatch and the problem above. 

If you test with another county, for example "Somerset" it works correctly. 

Seems like a critical bug as it's preventing customers from paying.

**Comment by abrookbanks** [comment]
The solution is to add London right?

**Comment by Noodleyman** [comment]
not really..... that was just an example.

County is Optional in PayPal. so if a customer doesn't supply it then this also causes the problem. There is no way to identify the problem unless a customer tells you, so you may be losing customers and not know.

Ideally this shouldn't fail at all... if it can't match a county it should fall back to inserting the county as text, not ID and reflecting this on the theme/ui

**Comment by abrookbanks** [comment]
Ok keeping this closed for now. More and more signs we need to implement #1870.

**Comment by Noodleyman** [comment]
if it's closed does that mean it won't be worked on? :)

**Comment by abrookbanks** [comment]
It won't be worked on until we start on the issue mentioned here https://github.com/cubecart/v6/issues/1872#issuecomment-366711404 because its the same issue effectively.

**Comment by Noodleyman** [comment]
is there an ETA on that item?

**Comment by abrookbanks** [comment]
No.

**Comment by abrookbanks** [comment]
Without dedicated resources I can't give an ETA on anything.

**Comment by Noodleyman** [comment]
crude work around for the time being:
TRUNCATE TABLE CubeCart_geo_zone

this stops the county enforcement via the theme. if I get chance I'll work on a proper fix.

**Comment by abrookbanks** [comment]
Thanks Alec.

**Comment by abrookbanks** [comment]
I'm working on 2.0 so maybe this should be pulled into the roadmap for it.
