### ISSUE TITLE
Abandoning Duplicating Addresses May Be Ineffectual

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1877]
Regarding #94 (Duplicate addresses in address book), creating a hash based on serializing the contents of everything passed in `$array` to `User->saveAddres()` is making an unrealized assumption:

1. Nothing but what you want is passed in
2. The order of the array elements is consistent
3. Nothing then later changes any of the data

These premises are not guaranteed.

Knowing that Database unsets any column that does not exist in the table, there is no penalty for supplying more data than actually used.

It is the skin's layout that determines in which order the form fields are submitted, thus the order of the array being passed in. So, over time, the skin layout may change.

The following statements then do, in fact, change the data by `ucword()` that data.

I understand the intent was to stop inadvertent duplicates as a solution for a specific situation. It is not a general solution.

Suggest serializing specific fields in a specific order and making the test just after the `update()` with `$reset`.

**Comment by abrookbanks** [comment]
Thanks this makes a big improvement to reliability. Also it returns the found hash address id instead of false. I think is some one or something tries to add an address it doesn't think it exists to being with. Makes sense to pretend it worked and then return the address ID as if it were added.
