### ISSUE TITLE
Customer visible notes

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#188]
See thread https://forums.cubecart.com/topic/48559-notes-to-customer-after-order-placed/

**Comment by NaturalSigns** [comment]
This is a feature I use all the time in v4, my products can take several weeks to manufacture and ship so its nice that the customer can log in to see a status update (example in v4 below).
![notes to customer](https://cloud.githubusercontent.com/assets/10531097/6091965/0576b774-aebe-11e4-8faf-ea791293bc88.png)

**Comment by abrookbanks** [comment]
Notes will be adde to the order confirmation email and are visible form their account area.

**Comment by abrookbanks** [comment]
![screen shot 2015-02-09 at 16 05 01](https://cloud.githubusercontent.com/assets/4520803/6109808/7257c10e-b075-11e4-921e-e5108da03109.png)
![screen shot 2015-02-09 at 16 04 26](https://cloud.githubusercontent.com/assets/4520803/6109809/725c34e6-b075-11e4-9442-25600c906650.png)
