### ISSUE TITLE
Print Order Form

### ISSUE THREAD

**Issue by MrGweb** [cubecart/v6#1880]
Feature Request
ive noticed that POF does not send email to the store admin when customer places order 
, generally this would not be an issues as due if never transferred moneys after that who cares, 

would be good thou if store admin wanted to know by email that was chosen,  were back end did not have to be checked all the time. also here some back group payments for each day - it does allways show clearly in bank statment 
could a cc and or bcc to store admin be added so they been alerted that is was triggered with an order like other methods
Cheers

**Comment by bhsmither** [comment]
In admin, Store Settings, Features tab, Misc section, "Order status for admin email notifications" can be set to Pending.

Using any payment gateway, whether a successful transaction eventually happens or not, CubeCart initially sets the order to Pending.

**Comment by MrGweb** [comment]
I did see that but the MORON owner of the store does not want to monitor the back end (YEP thats what i thought - nut case) 
when a sale goes through with NAB bank or pay pal ALL GOOD
the other one (POF only ever can go pending as not way to auto trigger it - so they never get an email
The bank and PP we don't need to email to processed is  triggered -  then they know they have the money
we can write a plugin to do the job all good 

we know NAB gives a double pending if it fails and PP gives you a Invalid so we can do a Cron job for that

Thanks MrB
