### ISSUE TITLE
User->getGhostId() Wanted

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1881]
There is the setter `User->setGhostId()` (not a proper setter/getter of a User property), which simply puts/clears the value in `Session['ghost_customer_id']` and presumably is generated from inserting/selecting a record into/from `CubeCart_customer`.

Suggest the companion getter, `User->getGhostId()` which returns the value in `Session['ghost_customer_id']` or false.

Just in case the actual variable holding the ghost customer id changes in the future.

Also suggest to find all locations of `Session->xx('ghost_customer_id')` and replace with `User->getGhostId()`.

However, there may be an issue if `User` is not instantiated (See: #939).

**Comment by abrookbanks** [comment]
Tidier and more consistent. :)
