### ISSUE TITLE
Text field not imported

### ISSUE THREAD

**Issue by NaturalSigns** [cubecart/v6#189]
If i have a product with a text field it imports to the basket correctly (see steps 1 & 2), but data is not correctly passed to the "print order form' page (see step 3, "SIGN TEXT").  

When I visit the admin page the field is empty (See step 4) (also the muliline text field "COMMENTS" is empty here, though the multi line text value  is correct on the overview page [step 5] and invoice print [step 6]).

I first noticed this when i was trying to change an order from pending to processing.  It won't allow you to change the status if a required field is blank on the 'admin>inventory' page (which is a good check).

![order issue - step 1](https://cloud.githubusercontent.com/assets/10531097/6093324/d2523ccc-aef6-11e4-940e-b4e0bc5e2ef4.png)
![order issue - step 2](https://cloud.githubusercontent.com/assets/10531097/6093325/d9f0a04a-aef6-11e4-9b15-c332161a948a.png)
![order issue - step 3](https://cloud.githubusercontent.com/assets/10531097/6093326/defa299e-aef6-11e4-88b2-c50bea5260b1.png)
![order issue - step 4](https://cloud.githubusercontent.com/assets/10531097/6093327/e52e6dd4-aef6-11e4-9978-2905cb9c3b96.png)
![order issue - step 5](https://cloud.githubusercontent.com/assets/10531097/6093328/ea8c7938-aef6-11e4-9593-a276e23f5e7b.png)
![order issue - step 6](https://cloud.githubusercontent.com/assets/10531097/6093329/f05dfc42-aef6-11e4-8bdc-06cc2a768c2b.png)

**Comment by bhsmither** [comment]
I think one of the problems is that (well, at least if having upgraded from CC5*) the `CubeCart_order_inventory.product_options` is held in an indexed array as opposed to an associated array where the assign_id is the key. Sending this array to `Catalogue->displayProductOptions()` gets no option with a selected attribute.

*I haven't made an order using CC6, so I can't verify if the product_options are serialized with the assign_id.

**Comment by abrookbanks** [comment]
This was a nightmare.

**Comment by abrookbanks** [comment]
That's painful to hear as this was a killer. I'll take another look at it.

**Comment by abrookbanks** [comment]
I found a stupid mistake after a great deal of digging. This now works fine from my testing. The text field was given the option_id array key instead of assign_id.

Sorry for any inconvenience caused.
