### ISSUE TITLE
$mailer->loadContent() does not return default language version?

### ISSUE THREAD

**Issue by romanklabal** [cubecart/v6#1890]
I am running a heavily modded 5.1.* so I cant guarantee this is a general bug, but when looking at the loadContent() method, its virtually identical to the one I am running so I believe it is.

Our store default language is en-GB and we have several other languages. So when sending an e-mail, I use this:

`$content = $mailer->loadContent('account.post_reg_coupon_confirmed', null, $data);`

The null param is the same as using **$GLOBALS['language']->current()** which is **fr-FR** in our case.

Now, the loadContent() method is trying to find the e-mail content in the current language (fr-FR), then trying to import new email contents, then find the content in the parent language identifier (fr) if it doesnt find anything and ultimately falls back to the store default language (en-GB). 

When I call the method with the null param, I expect the en-GB version to be returned since I dont have the fr-FR version created yet. However the method returns false.

I believe this is because of this line in the import condition: https://github.com/cubecart/v6/blob/6.1.14-branch/classes/mailer.class.php#L128

I believe it should return itself, not just call itself. If its just called, it loads the data but does not return them.

When I skip this condition, the method works as expected.

**Comment by abrookbanks** [comment]
Please provide steps to reproduce in a clean 6.1.14 install. I can't debug a "heavily modded 5.1.*" store.

**Comment by romanklabal** [comment]
Clean 6.1.8 install, and like I said, the code of the loadContent() method is virtually same since 5.* so I believe it doesnt matter.
```
$mail     = new Mailer();
$content = $mail->loadContent('admin.order_received', 'ab-CD', array());
var_dump($content);
```
Replace 'ab-CD' with 'fr-FR' or anything that passes the Language::LANG_REGEX regex and I would expect this method to return the only and default (en-GB) e-mail content.

Return **false** instead.

If you put **return** on this line - https://github.com/cubecart/v6/blob/6.1.14-branch/classes/mailer.class.php#L128 - like I suggested above, the method works and returns the default english content.

**Comment by abrookbanks** [comment]
This is probably fixed already. https://github.com/cubecart/v6/issues/1653

**Comment by romanklabal** [comment]
I dont think so. Forget I said modded or old version, forget languages, just look at the method.

You return the method call itself in the last two conditions:

```
} elseif (isset($match[2]) && preg_match(Language::LANG_REGEX, $match[2])) {
	// Try the parent language, if this is a regional translation (i.e. en-GB)
	return $this->loadContent($content_type, $match[1], $data);
} else if ($language !=  $GLOBALS['config']->get('config', 'default_language')) {
	// Try loading the default language content
	return $this->loadContent($content_type, $GLOBALS['config']->get('config', 'default_language'), $data);
}
```

But only call it during the first import condition:

`$this->loadContent($content_type, $language, $data);`

I believe thats all there is to it. Yes, it reaches the default language in the end, but doesnt return it. The initial method call just reaches return false; and thats it.

**Comment by abrookbanks** [comment]
Can you give me steps to reproduce with real world example.

**Comment by romanklabal** [comment]
Have more than one language in your store.
Dont have your e-mail contents translated.
Switch to non-default language on the front.
Get the frontend to send an e-mail.

This will be called:

`$content = $mailer->loadContent('account.password_recovery', $GLOBALS['language']->current(), $data);`

->

`$content = $mailer->loadContent('account.password_recovery', 'fr-FR', $data);`

return false instead of the default english version.

**Comment by abrookbanks** [comment]
Ok thanks. I will try.

**Comment by abrookbanks** [comment]
Got it. Thanks so much for this. Sorry to be defensive to start with but theoretical bugs can be a waste of time.
