### ISSUE TITLE
Sanitize->_stopToken() to Use Language Pack

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1895]
As above, the Security Alert message and trigger_error() phrase could be in the language packs.

**Comment by abrookbanks** [comment]
I'm not sure it can be as the language class isn't initialised yet but I'll have a look.

**Comment by bhsmither** [comment]
Other than four instances of calling `Smarty->assign()` -- which could be put elsewhere -- there is no other obstacle to instantiating `Language` ahead of `Sanitize::checkToken()`.

For example, in language.class.php:
```
118: $GLOBALS['smarty']->assign("CURRENT_LANGUAGE", $this->_language);
and
202: $GLOBALS['smarty']->assign('LANG', $this->_language_strings);
```
Delete this, and after Smarty is instantiated in `controller.index.inc.php`, have:
```
$GLOBALS['smarty']->assign("CURRENT_LANGUAGE", $GLOBALS['language']->getLanguage());
and
$GLOBALS['smarty']->assign("LANG", $GLOBALS['language']->getLanguageStrings());
```
Etc.

You can put the four mentioned statements in GUI.

**Comment by abrookbanks** [comment]
With the [relaxed CSRF token](https://github.com/cubecart/v6/issues/1921) we shouldn't be seeing this anymore!
