### ISSUE TITLE
Paypal standard shipping

### ISSUE THREAD

**Issue by demand73** [cubecart/v6#1896]
Why does Paypal standard gateway send the total order amount to Paypal?

It would be much better to divide it so shipping, VAT and discount are sent separately and what I can see in the API documentation it seems to support that with the following varibles in the old webscr api "amount", "tax", "shipping" and "discount_amount".

Probably you wonder why this does matter?

The paypal fee is calculated in the current way on the entire sum including shipping which would not happen if it was separated.

An example if I get an order where the goods cost $0.40 and the postage $0.90 and the fee is calculated at $1.30 which will be around $0.40 so I will only get payed for the postage but not the Product or one third and some cents of the shipping if you like. 

Paypal pro would solve this but i have to small turnover of my hobbyist operation with a personal paypal account. And in the example above with a commercial paypal account the paypal fee would be larger than the sold goods =)

If above is not fixable maybe a way to limit the minimal order value for being able to pay with a payment gateway or paypal standard is a way forward? Or may i should stop doing this for peanuts but its my way of relaxing from my normal work and therefore i should not whine about doing a few bad deals a month and i get if this does not have any priority at all =)

Regards
Krister

**Comment by abrookbanks** [comment]
You don't need to use PayPal Pro with the monthly fee. You can use same extension in "Express Checkout" mode. This has no monthly cost.
