### ISSUE TITLE
It is possible to create duplicated Option Groups and Option Sets

### ISSUE THREAD

**Issue by PloughGuy** [cubecart/v6#1897]
It is possible to create two options groups with the same name.  Ditto for option sets.
This probably isn't going to kill anyone, but it is generally not considered tasteful.

**To demonstrate** - create an option group named "Colour"
Create another option group named "Colour"

**Result** - you have two option groups named Colour.

**Comment by abrookbanks** [comment]
Maybe the option group "option_name" should be given a unique key.

**Comment by PloughGuy** [comment]
Definitely.
And maybe detect it is a dup and update instead?

**Comment by abrookbanks** [comment]
Fixed with unique key. Thanks.
