### ISSUE TITLE
Strict Update File List Management

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#190]
Enhancement:

If files are moved _en mass_ (FTP, perhaps) to sub-folder, then Update File List tab is clicked, the association in CubeCart_image_index between the Inventory _product_id_ and Filemanager _file_id_ becomes unglued.

Because the filename, filesize, and md5hash is likely to not change, I wish to see some method where the glue is maintained.

**Comment by abrookbanks** [comment]
Eeeeeep!! I agree. :)

**Comment by havenswift-hosting** [comment]
Some sort of mechanism within CubeCart Image Filemanager to bulk move images from one directory to another and preserve links to products.

What would also be very useful is to be able to select product and then search for all images associated with that product

**Comment by abrookbanks** [comment]
Wow you guys are keeping me busy! :P
Great suggestions. :)

**Comment by Dirty-Butter** [comment]
Way back - maybe v3 - it was possible to search for images by name from the Product Image tab. I've missed it ever since is was changed. Ian's idea to be able to search for all images connected to a given product would be fantastic, too.

**Comment by bobdonkey** [comment]
Would like to see this fixed as well, I download all my images via FTP and extract them into the images folder. If the references in image_index become wrong, I will loose the images on all of my products.

**Comment by bhsmither** [comment]
I think this is no longer an issue. The Update File List seems to no longer lose the file_id to product_id association.

However, still some more work to do.

**Comment by abrookbanks** [comment]
Thanks for letting me know Brian.
