### ISSUE TITLE
Bug when I use "add to basket" using Mobile Browser (tested with an actual smartphone and using chrome dev-tools)

### ISSUE THREAD

**Issue by theoneandonly-vector** [cubecart/v6#1900]
When I surf to my website using a mobile device it will result in a bug, when I add am item to my basket.

**Comment by havenswift-hosting** [comment]
You’ll need to give a bit more information - there are many thousands of sites using CubeCart without problems

**Comment by theoneandonly-vector** [comment]
.json profile from chrome (error occures at ~7300ms)
https://mega.nz/#!s0BQXCpI!vHpBWzww9ki6xXUWpB32vV0f_gyhood9_8R2e97Pwrc

**Comment by theoneandonly-vector** [comment]
when I make a fresh setup on a 2nd server the same bug occurs.

I'm using v. 6.1.14

**Comment by theoneandonly-vector** [comment]
If I use it using (use desktop version) there's no bug.

**Comment by theoneandonly-vector** [comment]
﻿jquery.js:27 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
VM273:24 Uncaught TypeError: Cannot read property 'toString' of null
    at l (https://ajax.cloudflare.com/cdn-cgi/scripts/935cb224/cloudflare-static/rocket.min.js:2:7995)
    at s.(anonymous function) (https://ajax.cloudflare.com/cdn-cgi/scripts/935cb224/cloudflare-static/rocket.min.js:2:8619)
    at Object.add (eval at globalEval (https://urwaldpflanzen.ch/skins/foundation/js/vendor/jquery.js:14:11778), <anonymous>:24:30571)
    at eval (eval at globalEval (https://urwaldpflanzen.ch/skins/foundation/js/vendor/jquery.js:14:11778), <anonymous>:25:5900)
    at Function.each (eval at globalEval (https://urwaldpflanzen.ch/skins/foundation/js/vendor/jquery.js:14:11778), <anonymous>:14:12113)
    at _.fn.init.each (eval at globalEval (https://urwaldpflanzen.ch/skins/foundation/js/vendor/jquery.js:14:11778), <anonymous>:14:10087)
    at _.fn.init.on (eval at globalEval (https://urwaldpflanzen.ch/skins/foundation/js/vendor/jquery.js:14:11778), <anonymous>:25:5876)
    at _.fn.init._.fn.(anonymous function) (eval at globalEval (https://urwaldpflanzen.ch/skins/foundation/js/vendor/jquery.js:14:11778), <anonymous>:25:25726)
    at _.fn.init._.fn.load (eval at globalEval (https://urwaldpflanzen.ch/skins/foundation/js/vendor/jquery.js:14:11778), <anonymous>:27:3616)
    at Object.events (eval at globalEval (https://urwaldpflanzen.ch/skins/foundation/js/vendor/jquery.js:14:11778), <anonymous>:5702:46)
VM279:5520 Uncaught TypeError: Cannot read property 'sticky_class' of undefined
    at Object.is_sticky (eval at globalEval (jquery.js:14), <anonymous>:5520:58)
    at HTMLElement.eval (eval at globalEval (jquery.js:14), <anonymous>:5781:18)
    at Function.each (eval at globalEval (jquery.js:14), <anonymous>:14:12113)
    at _.fn.init.each (eval at globalEval (jquery.js:14), <anonymous>:14:10087)
    at Object.resize (eval at globalEval (jquery.js:14), <anonymous>:5761:44)
    at eval (eval at globalEval (jquery.js:14), <anonymous>:5701:23)
    at eval (eval at globalEval (jquery.js:14), <anonymous>:456:20)
rocket.min.js:2 GET https://urwaldpflanzen.ch/cdn-cgi/pe/bag2?r[]=https%3A%2F%2Fwww.google.com%…oudflare.com%2Fviewer%2Frtv%2F011-4-71%2Famp-viewer.js%3F_%3D1520933155518 400 ()

**Comment by abrookbanks** [comment]
This is meaningless to me. Please provide clearer information or open a technical support ticket.

**Comment by theoneandonly-vector** [comment]
I sent a .json -file with the exact error and timestamp, do you need a video?

The Bug occurs when I use chrome-dev-tools and select Galaxy S5 and then want to add a product to the basket.
Could you provide me with a link to another CubeCart Installation, so I can try to replicate it there?

**Comment by abrookbanks** [comment]
Please can you open a technical support ticket if you require any further assistance. This is not a bug I can reproduce or have had any other reports about.

**Comment by theoneandonly-vector** [comment]
please.. give me at least another site so I can check if I can reproduce it
there...

as I said I reproduced it on 3 setups now..
It doesn't fail every time..



Al Brookbanks <notifications@github.com> schrieb am Di., 13. März 2018,
17:11:

**Comment by abrookbanks** [comment]
You can try the demo store https://demo.cubecart.com/cc6

**Comment by theoneandonly-vector** [comment]
I can even set it up from 0 when I git clone this project and it gives me
the same error.

**Comment by theoneandonly-vector** [comment]
as I said.. same error
(screenshot)

Al Brookbanks <notifications@github.com> schrieb am Di., 13. März 2018,
17:17:

**Comment by theoneandonly-vector** [comment]
![screenshot_20180313-171931](https://user-images.githubusercontent.com/10380051/37354865-e2731a7e-26e2-11e8-994f-851804493c82.jpg)
![screenshot_20180313-171927](https://user-images.githubusercontent.com/10380051/37354866-e2e4228c-26e2-11e8-987a-e2b82dc0d024.jpg)

**Comment by abrookbanks** [comment]
Where do I see this screen shot?

**Comment by abrookbanks** [comment]
Which browser are you using on your android device?

**Comment by theoneandonly-vector** [comment]
it somehow renders the site a 2nd time, where it should show the basket..
this doesnt' happen with every device I've tested, nor eith every browser.. but you can reproduce using chrome dev tools and set to galaxy s5 or ipad pro (doesn't happen every but nearly every time)

my phone (screenshot) is running  stable chrome.

**Comment by theoneandonly-vector** [comment]
I even sent a .json file with a timestamp which shows the exact error..

**Comment by abrookbanks** [comment]
It's 24 megabytes! That's not an exact error. :)

**Comment by abrookbanks** [comment]
I can't reproduce this on Chrome 65.0.3325.109 on Android 7.0.

**Comment by theoneandonly-vector** [comment]
As I said.. It isn't failing every time.. on every device (probably it
changes with different screen sizes etc.. as my phone is tge OnePlus 5 )..
Should I reproduce it at home and send the .json file?
Try it with chrome's dev tools.. and use S5 or ipad pro  and try 2-3 times.

Am 13.03.2018 17:27 schrieb "Al Brookbanks" <notifications@github.com>:

I can't reproduce this on Chrome 65.0.3325.109 on Android 7.0.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cubecart/v6/issues/1900#issuecomment-372728539>, or mute
the thread

**Comment by abrookbanks** [comment]
> Uncaught TypeError: Cannot read property 'toString' of null

That may be of interest.

**Comment by abrookbanks** [comment]
I have reopened this because I believe I have enough info now.

**Comment by abrookbanks** [comment]
Can you try making [this code change](https://github.com/cubecart/v6/commit/9b4c598bbb39491254270e92c3ba5d405f4fe7ec) to see if it then works?

**Comment by abrookbanks** [comment]
Ok. I'm pretty confident I fixed this now. If you can replace your `classes/session.class.php` with this one https://raw.githubusercontent.com/cubecart/v6/6.1.15-branch/classes/session.class.php it should be ok. 

I'd be very grateful if you could let me know.

**Comment by theoneandonly-vector** [comment]
hey there
yes it works!
thank you so much :-)

Al Brookbanks <notifications@github.com> schrieb am Di., 13. März 2018,
18:19:

**Comment by abrookbanks** [comment]
GREAT! Thanks so much for all your help today.
