### ISSUE TITLE
Language Phrase Editing

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1903]
When showing the list of phrases, hovering the mouse over the actual phrase will show a tooltip "Click to Edit".

However, since these fields are `disabled="disabled"`, a mouse click is not recognized. (Might be specific to Firefox 58.)

Clicking on the `<label>` area works.

**Comment by abrookbanks** [comment]
Not a great deal I can do. See discussions here from many years ago:
https://bugzilla.mozilla.org/show_bug.cgi?id=274626
https://bugzilla.mozilla.org/show_bug.cgi?id=436770

**Comment by abrookbanks** [comment]
![screen shot 2018-03-13 at 13 22 00](https://user-images.githubusercontent.com/4520803/37344179-927880de-26c1-11e8-88fe-7907275742b0.png)
