### ISSUE TITLE
Allow customised print order template to be customised without upgrade overwrite

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1904]
As above. A WYSIWYG editor would be good.

**Comment by abrookbanks** [comment]
![screen shot 2018-03-14 at 13 55 16](https://user-images.githubusercontent.com/4520803/37406561-5b703c52-278f-11e8-89cf-1d0235b520cf.png)

**Comment by bhsmither** [comment]
Did you mean to include the textarea for the email **contents** editor? See:
https://github.com/cubecart/v6/commit/059e8cf8cb1b0830195d5eebfe51a7c0b66c0bbe#diff-ec3350c6cbe91f80d4c935e2187021ea

Where the **contents** sit inside the **template**, the template should have the `fck-full` attribute, but not the contents editor.

**Comment by abrookbanks** [comment]
No I don't think I did. I just removed the "textbox" class. 

See: 7a437ab0aef018b6e87ade9167a43d86ce8411b8

I think that's what you meant. Thanks.

**Comment by bhsmither** [comment]
No, I disagree with this change.

The `fck-full` attribute causes CKEditor to create a complete HTML document (has `<html>`, `<head>`, and `<body>` tags. These tags are not wanted in an email content template.

**Comment by abrookbanks** [comment]
Gotcha. Sorry for the confusion. :)
