### ISSUE TITLE
Minor Improvements to Estimated Shipping

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1908]
1) The word "Estimated" could be changed to something like "Refine Estimate" to make it clearer that clicking that link will provide that - many people never realise that this is a link

2) The Country, County and Postcode should default to those for the store which is what the estimate is based on - currently it shows "Afghanistan" which is unlikely to be useful to anyone

**Comment by bhsmither** [comment]
Point 2 -- I cannot duplicate. (As of CC6112, it does default to using the store's address. I haven't verified this for the later versions.)

**Comment by abrookbanks** [comment]
I like this. I also can't reproduce point 2.

**Comment by havenswift-hosting** [comment]
Point two validated as not working correctly on three test sites and three different client sites

**Comment by abrookbanks** [comment]
Demo store works. https://demo.cubecart.com/cc6

**Comment by abrookbanks** [comment]
Thanks for this Ian. Seems to be a fault with your three clients stores regarding point 2.

**Comment by abrookbanks** [comment]
![screen shot 2018-03-15 at 16 20 11](https://user-images.githubusercontent.com/4520803/37476317-c38c4528-286c-11e8-8b9c-5558ccc73ede.png)

**Comment by havenswift-hosting** [comment]
> Demo store works. https://demo.cubecart.com/cc6

Verifying that it works in a freshly installed latest version store is obviously a good starting point (and one I didnt do !) but simply proves that there is no problem in the latest version and isnt a particularly good real world test.  I have done more tests and can confirm that it works fine with a newly installed store and doesnt appear to be skin / plugin related.  However, as with most of these types of problems, it is usually data related caused by older problems that have been fixed but where the data was never sorted out at the same time.

> Seems to be a fault with your three clients stores regarding point 2

They are not all "our clients" but are all older stores that have been upgraded multiple times and affects a lot of stores such that many simply switch off estimated shipping which is a shame as it is now a useful option.

I would still also say that it should use the store postcode as well as the Country and County especially as AIOS can have zones based on postcode - a large number of store owners across multiple countries define shipping zones by postcode region

**Comment by abrookbanks** [comment]
See if it works using default Foundation skin. Make sure the stores country, county and postcode are set in settings. 

I expect this is a hangover from a bug in a custom skin no core updates can fix. On those grounds there's nothing that can be done other than looking at each of these shops with case by case technical support.

**Comment by havenswift-hosting** [comment]
> See if it works using default Foundation skin.

No, exactly the same problem - always check things like this against unchanged Foundation skin !

> Make sure the stores country, county and postcode are set in settings.

Yeah, wouldnt work without those being set - not my first rodeo !  Also as I have pointed out, it doesnt do anything with the postcode which I think it should

You have closed it, so no worries
