### ISSUE TITLE
Small Improvements to All in One Shipping Plugin

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1909]
When adding a new shipping zone and choosing "One or more states/provinces", you can choose a country and then click into the "States/provinces" box (is this phrase hard-coded as not correct for en-GB) but then every single option is listed and not just those for the selected country

**Comment by abrookbanks** [comment]
Fixed with 1.0.12. The states are now ajaxy to the country. Much better thanks Ian.
