### ISSUE TITLE
CSRF(?) issues adding items to basket

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1912]
Unmodified v6.1.14 - click add to basket, go somewhere else and add an item from there, then use the back button and add another item from the original page.

You should now have your store displayed *twice* with the version above being a bit narrower; scroll down and you'll see your store front displayed again.

Repeat all of the steps above to have any number of narrower and narrower stores displayed.

**Comment by briansandall** [comment]
As a further test, navigate to a product page and add to basket from there, click back to get to the category, and add a product from there.

This should bring you back (well, shouldn't but does) to the home page with a brief CSRF message displaying before it auto-hides. Not nearly enough time to read it, but it's there.

**Comment by briansandall** [comment]
Of further note is that the store front is displaying even though the URL still shows where I would expect to be, e.g. the category or product I was last viewing when trying to add to the basket.

I've been able to reproduce this on CubeCart code going back to 6.1.10 so far... probably goes back all the way to whenever CSRF tokens were added.

**Comment by briansandall** [comment]
Note the URL, but displaying the home page (which is displayed 3 times here but only seeing the top one):
![cc1912](https://user-images.githubusercontent.com/14335170/37531532-b358c6b2-28f9-11e8-89b3-c122ffaf2e1b.jpg)

**Comment by briansandall** [comment]
I think the user experience would be much improved if the CSRF token was generated once per session, rather than every single page request (at least on the customer side).

**Comment by bhsmither** [comment]
The visual effect you are seeing is that when adding an item to the cart, the page uses AJAX to inform CubeCart of the change in basket contents. Sent along with the product data is the security token.

CubeCart then sends back **just** the relevant HTML (the box.basket.php template populated with new basket contents) and AJAX will replace the related chunk of the page.

If CubeCart determines the security token is wrong or missing, CubeCart sends back the entire index.php page.

**Comment by briansandall** [comment]
Exactly, and it gives a very poor impression to the customer.

We can't expect customers to not ever use the back button, and no other online store I've ever purchased from restricts usage of the back button. It's a basic browser functionality that should not be compromised.

**Comment by Dirty-Butter** [comment]
We had an order today where someone bought more than one item (unusual for us). She could not get past the basket. She wrote back when I asked what happened, and she said it worked when she closed out the store website completely, came back, and was able to proceed. I suspect this was this same issue.

**Comment by abrookbanks** [comment]
This should be resolved with https://github.com/cubecart/v6/issues/1900

**Comment by abrookbanks** [comment]
Fix: https://github.com/cubecart/v6/commit/88518877396812935677b4b02eef0234fcfaebd7

I will reopen and look again if need be.

**Comment by briansandall** [comment]
Nice.

Btw, looks like you've got some 6.2.0 code in the 6.1.15 branch, specifically width/height/depth/dimension_units in the language definitions file. ;)

**Comment by briansandall** [comment]
Tested this out on my live store and it still has the same problem:

1. Attempt to add any product (with options that requires you to navigate to the product page) to basket

2. Click back

3. Add any product to basket

**Comment by briansandall** [comment]
Tested on unmodified store as well - not fixed.

**Comment by abrookbanks** [comment]
It won't work with a back button. Nothing I can do about that.

**Comment by abrookbanks** [comment]
I don't know if a work around like this may help:
https://codepen.io/derekjp/pen/Bguwz

Out dated page content is a problem with CSRF.

**Comment by briansandall** [comment]
I suppose that could work, but ideally the CSRF token would only be generated once per user session on the front end, then they could use the back button, multiple tabs, etc. as much as they want.

What's the reasoning behind having such a strict CSRF policy on the front end that it impacts the customer experience so negatively? I have never been on any other online store with such a restrictive front end experience - Amazon, for an obvious example, works just fine if you use the back button or multiple tabs.

I think this can be much improved while still maintaining security standards.

**Comment by abrookbanks** [comment]
That's true on the front end it could stay constant. It was added after a 3rd party security company gave me a hard time about it.

**Comment by abrookbanks** [comment]
I think relaxing it to a constant value is a good option.

**Comment by briansandall** [comment]
I wonder if we could also have some sort of check in the AJAX request to prevent re-rendering the whole page as well, just in case the CSRF token is regenerated (e.g. due to the session regenerating) while the user has a page open.

**Comment by abrookbanks** [comment]
Resolved with https://github.com/cubecart/v6/issues/1921 

I googled this quite a bit and it does seem to be common to keep it static for UX reasons such as multiple tabs, back etc. I'm sure this will be very welcome!
