### ISSUE TITLE
unselected images stick to products

### ISSUE THREAD

**Issue by jac0511** [cubecart/v6#1922]
Updating product images only adds images to products but doesn't remove them. Unselecting is supposed to remove the unselected images from the product, isn't it? Now the images must be deleted in order to remove them from products.

**Comment by abrookbanks** [comment]
What version of CubeCart are you using?

**Comment by abrookbanks** [comment]
Unable to reproduce on 6.1.14 build.

**Comment by jac0511** [comment]
ah, I have 6.1.13, have to update.. Thanks!
