### ISSUE TITLE
Code Notice

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1923]
Adding so the code can be improved and not generate notices/warnings. clean install of CC 6.1.14. 

Notice: Undefined index: taxes in <path>/classes/cubecart.class.php on line 1292

**Comment by abrookbanks** [comment]
CubeCart v6 isn't coded to strict standards. There are thousands of these.

**Comment by Noodleyman** [comment]
yup, I was intending to raise them as/when I noticed them so things can be improved over time ;)

**Comment by abrookbanks** [comment]
Thanks but I think there are thousands. Really notices and warnings should be turned off in error reporting. Version 7 *gulp* will be strict.

**Comment by Noodleyman** [comment]
and to tackle thousands, you need to start somewhere ;) it'll make everything better in the end
