### ISSUE TITLE
BETA - Clean install issue

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1927]
Not sure what the root cause is, but I just did a clean install of the 6.2 beta, however after a successful install it isn't possible to log into the admin area.  

No error/warning, just returned to the login prompt every time. No errors in the Server error log or in the CubeCart DB tables.

Tested with multiple browsers. Using PHP Version 7.1.15-1, Apache2 on Ubuntu.

Clean installs of 6.1x versions are working correctly..

**Comment by abrookbanks** [comment]
Can't believe this is the only bug report in a week. Clearly nobody is using it. We will have to release it as final for real world testing. :)

Thanks Alec I'll look into this.

**Comment by Noodleyman** [comment]
I wasn’t even aware it existed until I went to download a fresh copy of 6.1

The only testing I’ve done so far is installing it… but since I can’t log in I’ve not done much else yet

**Comment by abrookbanks** [comment]
LOL - It should show in the store dashboard, on the homepage of our website, in the forum announcements and Twitter/Facebook. :)

**Comment by Noodleyman** [comment]
I don’t social media, totally missed the announcement on the dashboard and for some reason didn’t get the mail with the notification from the forums (I subscribed to them). DOH.

 

I’m wondering if the login issue is specific to my own server, not sure.. thus raised a ticket for a 2nd pair of eyes to confirm.

**Comment by abrookbanks** [comment]
I don't blame you I hate it too but use it just for work. I'll test this out after lunch and report back.

**Comment by abrookbanks** [comment]
Worked fine for me. Please note that 6.2 uses MySQL triggers. Does the MySQL user have permission?

Anything in the error logs?

**Comment by abrookbanks** [comment]
Also make sure that MySQL is not in strict mode. Much like PHP notices and warnings. It's not coded to strict standards.

**Comment by Noodleyman** [comment]
logs are 100% clear, full permissions at the DB level. I'll test it again in a moment

Out of interest... what triggers are being used and why?  I've had issues where triggers just randomly stop working and have to be dropped/recreated in the past, so try to avoid using them.

**Comment by abrookbanks** [comment]
They are used for sequential order numbers. Actually they are off by default so it shouldn't be an issue. If they are turned on and the trigger setup fails it will warn and keep off.

**Comment by Noodleyman** [comment]
right... it's related to something weird/odd..... perhaps cookie related. If I access the beta site with the FQDN then it allows me to log in, however my local URL which is simply the network name of the server locally won't allow login.

It's because I installed CubeCart using my local machine name 
http://fluffles-lamp2/cubecart/6-2-0beta

and the installer set the Cooke Domain to be ".fluffles-lamp2" which isn't a valid domain. browsers blocked me logging in until I updated this to something fake, I added .co.uk to it.

So, this is some sort of browser security feature which appears to be a lot more common than I thought.

This raises a general question:
Should the cookie domain be validated before being set as part of initial setup? It's unlikely to be an issue outside of an R&D instance, but could trip up other people.

**Comment by abrookbanks** [comment]
Thanks for the thorough feedback. Maybe if the hostname has no dot in it the cookie shouldn't set a domain? Maybe thats tooooooo simples.

**Comment by abrookbanks** [comment]
BTW I work locally too but use the hosts file to fake a domain. This is pretty much the same across OS's.

`127.0.0.1       localhost       www.example.com`

**Comment by abrookbanks** [comment]
Sorted. Thanks!

**Comment by Noodleyman** [comment]
if this was included in beta2, it still isn't working correctly. tested with a clean store install

**Comment by abrookbanks** [comment]
It should only set a cookie domain if the hostname contains a dot. I'll test it again.

**Comment by bhsmither** [comment]
Until this is sorted, I suggest:
https://forums.cubecart.com/topic/51551-resolved-500-internal-server-error-after-wampserver-installation/?tab=comments#comment-219520

**Comment by abrookbanks** [comment]
This is fixed now but related to #1954 (which is driving me nuts).
