### ISSUE TITLE
$SUM after checkout should also include unformatted numbers

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1928]
Currently the totals are only available with currency formatting, but would be useful to also have them in their raw format so it makes integrating additional conversion / tracking code possible without modification

**Comment by abrookbanks** [comment]
Agreed... you can use this in the interim... 
`{$data|regex_replace:'/[^0-9.]+/':''}`

**Comment by abrookbanks** [comment]
It's probably lighter to use the regex than assigning even more smarty variables to memory.
