### ISSUE TITLE
$GA_SUM on content.receipt is conditional and shouldn't be...

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1930]
$GA_SUM is currently only sent to the receipt page if the order status is 2 or 3, processing/complete.  This means you can't track conversions for things such as print order form or manual card payments.

Or, if an IPN doesn't respond promptly, the conversion may be missed as the status was not 2 at the time of the page load

Not 100% sure if this should be changed, but wanted to raise it as a concern as it just caught me out. perhaps it needs to be a configurable option

**Comment by abrookbanks** [comment]
I *think* should should stay as it is because the sale should only be tracked in Google Analytics for eCommerce when paid for.

**Comment by Noodleyman** [comment]
it would be useful if the variable was available without the condition, then perhaps add the payment status as a field in the array. this way data is always available for other uses

**Comment by abrookbanks** [comment]
Agreed but older skins will invoke the tracking code based on the presence of the $GA_SUM variable alone. So by making it present at all times isn't backward compatible.

**Comment by Noodleyman** [comment]
perhaps a new, additional variable would be a better solution.

**Comment by abrookbanks** [comment]
There isn't actually any need for `$GA_SUM` at all. I wish I never made a specific array for it. Everything should be available under `$ITEMS` and `$SUM` albeit with a bit of regex to format it to your wishes.

**Comment by Noodleyman** [comment]
apart from the subtotal/totals unformatted ;)

**Comment by abrookbanks** [comment]
But you can unformat them with lightweight regex no?

**Comment by abrookbanks** [comment]
```
{$SUM.total|regex_replace:'/[^0-9.]+/':''}
```

**Comment by Noodleyman** [comment]
you can, but ideally this isn't something that should be done by the store theme, it's a refinement. :)
