### ISSUE TITLE
Image sprite_flags is 404

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1933]
CC620b1

Watching the Network traffic, I see that the request for the image is 404.

In `/foundation/css/cubecart.css`, there is:
```
span.flag
background:url(../images/sprite_flags.png)
```
The browser wants to fetch `/images/sprite_flags.png`, but the image is not at that absolute root-based folder.

Working on the assumption that the path should be in quotes, I edited the cubecart.css file.

**Question 1**: How to force CC620 to rebuild the `/cache/css.foundation_YYYYMMDDHHMMSS.css`?

Manually deleting it made it disappear forever.

**Comment by bhsmither** [comment]
Managed to force a rebuild by also manually deleting `css.foundation.css.cache`.

**Comment by bhsmither** [comment]
The image file `sprite_flags.png` is still 404 because the browser wants to load from `/images/`.

This makes sense because `css.foundation_YYMMDDHHMMSS.css` is not in the skin folder.

Thus, either the minifier is skipping over some CSS `url` values (rewriting to what?), or this becomes a RPITA having to recode CSS rules to `data:base64` images.

**Comment by abrookbanks** [comment]
Is an inline image a PITA? Thanks for this bug report though. I might be able to find and replace ../images/ dynamically.

**Comment by abrookbanks** [comment]
Fixed up. Thanks Brian!
