### ISSUE TITLE
text overwrite 6.2beta

### ISSUE THREAD

**Issue by Mandevles** [cubecart/v6#1934]
Hi,
when inserting a product code and a description into products propogation, there appears to be an overwrite situation on the product code ?
It seems like the product description (short) takes priority over product code.
![image](https://user-images.githubusercontent.com/38245593/38552514-39571458-3cb4-11e8-8b7e-37e1673f1802.png)

**Comment by abrookbanks** [comment]
I can't reproduce this problem. 

It's showing the alternate text tag badly because there are missing images. Have you deleted any images from the images/source folder?

Was this a fresh install or upgrade?

**Comment by Mandevles** [comment]
All content was deleted and it was a clean CSV upload.  There are no pictures. 
Even when altering the name in the products section this occurs.  Might just be with the amount of characters ?
I have just done a complete refresh and I cannot get it to do the same again - sorry
