### ISSUE TITLE
Bulk Price Change 6.2Beta

### ISSUE THREAD

**Issue by Mandevles** [cubecart/v6#1935]
When adjusting prices in Bulk Price Change, you cannot update product in selected category, it defaults to every category
It would also be nice to see existing price with option of updating individual prices per product (in bulk).
When selecting what to adjust - sale price, retail price, cost price etc it would also be nice to see the adjustment before going ahead with "save".  This would enable you to see what has already been updated and what has not ?

**Comment by abrookbanks** [comment]
You can submit feature request here:
https://features.cubecart.com

**Comment by abrookbanks** [comment]
Worked fine for me but the changes didn't show until the cache was cleared. 

![screen shot 2018-04-10 at 12 15 52](https://user-images.githubusercontent.com/4520803/38554033-038e7168-3cb9-11e8-917c-bd2abecc3aa1.png)
