### ISSUE TITLE
BETA - Recaptcha JS error

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1937]
Seems to happen regardless of the configuration in store settings, JS error.

![image](https://user-images.githubusercontent.com/10614018/38610958-5acb6780-3d7a-11e8-8bc0-ba91041b1cad.png)

**Comment by abrookbanks** [comment]
Fixed by deferring to explicit fields.

**Comment by Noodleyman** [comment]
Please can you share the code change you made? I'd like to apply it to my test store

**Comment by abrookbanks** [comment]
Sure see the [first commit](https://github.com/cubecart/v6/commit/d11cf75330c3c6ac6d8175e3c6937a21c429ab96).

**Comment by Noodleyman** [comment]
Is there an additional change not mentioned in the commit?

The JS error is gone, but it's been replaced with the following console output:

![image](https://user-images.githubusercontent.com/10614018/38613681-96af0ca4-3d82-11e8-8edc-30442d322704.png)

**Comment by abrookbanks** [comment]
Clear the cache?

**Comment by abrookbanks** [comment]
You might need to manually empty the `/cache` folder.

**Comment by Noodleyman** [comment]
I don't have cache enabled, however cache cleared to test, but still the same output.  /cache directory manually cleared.. no change.

**Comment by abrookbanks** [comment]
Are you using reCaptcha v2?

**Comment by Noodleyman** [comment]
invisible... looks like a bug with the change in content.recaptcha.php.

<div class="g-recaptcha" data-sitekey="{$CONFIG.recaptcha_public_key}"></div> is within the if $RECAPTCHA==2 statment, but invisible is 3..

**Comment by abrookbanks** [comment]
Ok. I'll try invisible.

**Comment by Noodleyman** [comment]
looks like content.recaptcha is only for v1 or v2, nothing here will work for invisible as it's not in the initial checks

**Comment by abrookbanks** [comment]
Still buggy with invisible.. working on it.. V2 seems ok now...

**Comment by abrookbanks** [comment]
Ok all sorted! Sorry quite a lot of code changes but its a much more professional integration and Invisible reCaptcha is more reliable now.
