### ISSUE TITLE
BETA: Foundation, main.php

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1938]
`<div class="small-12" id="main_content">`

should be

`<div class="small-12 columns" id="main_content">`

**Comment by abrookbanks** [comment]
[Looks ok to me](https://github.com/cubecart/v6/blob/6.1.15-branch/skins/foundation/templates/main.php#L95)

**Comment by Noodleyman** [comment]
hmm, perhaps a typo on my part when I did a code change. my bad
