### ISSUE TITLE
Beta - Menu items and caret

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1939]
Using beta foundation theme, with categories that contain no children. on page load the categories in the menu initially load with the caret, then they are removed. this causes the menu to expand from left to right, then contract again. 

It happens with every page load.

It happens when the setting "Expand category navigation tree"  is No.

**Comment by abrookbanks** [comment]
This is how the top bar JS in the Foundation framework works. It's pretty complex. 

Ideally we need to upgrade to a newer responsive framework.
