### ISSUE TITLE
BETAb2- Email test fails

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1942]
all details are valid, but test fails with
![image](https://user-images.githubusercontent.com/10614018/38663956-35183642-3e30-11e8-8bdb-a9854f632f1e.png)

**Comment by abrookbanks** [comment]
What details did you use? mail(), SMTP? If you can send me a censored screenshot it would help loads. 

It worked with my test setup.

**Comment by abrookbanks** [comment]
Hmm tested again with success. All Ajax params match the test parameters.

**Comment by abrookbanks** [comment]
I can reproduce this if "Sender's Email Address" is empty but it needs a value so on those grounds it works as expected.

**Comment by Noodleyman** [comment]
I just sent you two screen shots via email with data to review. The fields all have valid values. the test was working until I did the update to the beta version

**Comment by abrookbanks** [comment]
Thank you.
