### ISSUE TITLE
Add support for hreflang  to foundation

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1944]
I happened to notice this wasn't in the stock theme, but as it's multi lingual it's probably a good idea to add.

https://support.google.com/webmasters/answer/189077?hl=en

Google uses hreflang tags to match the user's language preference to the right variation of your pages.

**Comment by abrookbanks** [comment]
New to me.. I like it! Lets get it added..

**Comment by abrookbanks** [comment]
Thanks for sharing.
