### ISSUE TITLE
BETAb2 - Cache issue

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1945]
If you edit a product and change it's status from Available to Unavailable, the store front does not pick  up the change until you manually clear the cache. 

This kind of changes shouldn't require a cache clearing, or should clear the cache upon making the changes in the admin area.

Not sure if this is by design, if it is then admins need to be made aware of the additional steps required to enforce the config changes.

**Comment by abrookbanks** [comment]
Sorry but it does. The cache needs to be cleared manually. Yes its a shag maybe but overall is makes the cache meaningful. 6.0 cleared the cache with every admin page load which did the polar opposite to any good caching actually does.

**Comment by Noodleyman** [comment]
There needs to be some notification to inform admins that if they want their config changes applied they must clear the cache.  If you don't know about this new feature then people will assume their changes are live on the site or wonder why the changes are not working.

Shouldn't the cache be cleared when product data is modified (on product save) so your changes are applied in real time?

**Comment by abrookbanks** [comment]
The button at the top changes colour top draw attention. With final release we will make this feature clear. I expect people won't like it but for a performance point of view its necessary and will become second nature.

**Comment by abrookbanks** [comment]
![screen shot 2018-04-12 at 13 49 12](https://user-images.githubusercontent.com/4520803/38678233-5c42919a-3e58-11e8-9a43-802a39bb2834.png)

**Comment by Noodleyman** [comment]
if your going to have to manually clear the cache after every product edit, why not auto clear the cache when saving a product change?  

Otherwise, it's adding an additional step/click for the admin with no benefit and introduced a risk of people forgetting to reset cache and not apply changes.

**Comment by abrookbanks** [comment]
It's probably better practise to clear the cache when you have finished making all your changes.

**Comment by abrookbanks** [comment]
If they forget to clear the cache over time it will sort itself out.

**Comment by Noodleyman** [comment]
Ultimately, your decision but I feel this needs refinement. at the very least a setting that allows somebody to enable the auto clearing of cache on product/category saves. 

I get that everybody can press the clear cache button as part of a process, but is it really necessary to force users to have to push the button especially if editing things frequently? It's adding additional admin tasks/clicks unnecessarily and opens the risk of people forgetting to clear the cache and apply their changes. 

Even doing things like changing a price are not picked up. I believe this should be enhanced further

how much time does it take to sort itself out?

**Comment by abrookbanks** [comment]
The cache as it was before was useless. It's now meaningful.

**Comment by Noodleyman** [comment]
I don't disagree with that statement. this topic is more focused on the admin processes. Is there any reason to not clear the cache after editing a product or category?

**Comment by abrookbanks** [comment]
If you have a busy store and the store admin spends 2 hours editing products clearing the cache every few seconds while visitors are writing the cache out every second it will decimate the server read write processes.

**Comment by Noodleyman** [comment]
but, they have to clear it anyway after they edit every product, so what's the difference between automating it and manually doing it?

**Comment by abrookbanks** [comment]
> but, they have to clear it anyway after they edit every product

Do they? I don't think they do unless its something they need done urgently.

**Comment by abrookbanks** [comment]
Relevant: https://github.com/cubecart/v6/issues/1536

**Comment by Noodleyman** [comment]
They do if they want their edits to become active immediately.  This is quite a major change and I can see it catching a lot of people out, will there be a notice to clear cache to apply the changes added before the final release? 

Do you have any documentation about how cache now works? I'm going to need to review how some of my modules work with smarty, especially if smarty content isn't being dynamically changed unless cache is cleared.

**Comment by abrookbanks** [comment]
Its pretty simple. Skins and inventory is cached for x amount of time. Once that time is passed it gets deleted and written again.

**Comment by Noodleyman** [comment]
I just found a valid example where this is a problem. As a test customer I placed an order on my site, then navigated to my user account page and reviewed my recent orders. The order doesn't show up until I clear the cache as an admin.

**Comment by abrookbanks** [comment]
So we need to remove caching form that query. This is why we have a beta (nobody is using).

**Comment by abrookbanks** [comment]
I'll open a separate issue.

**Comment by abrookbanks** [comment]
> I just found a valid example where this is a problem. As a test customer I placed an order on my site, then navigated to my user account page and reviewed my recent orders. The order doesn't show up until I clear the cache as an admin.

Surely this is a bug in 6.1 too? What if no admin is working at the time you have that scenario?

**Comment by Noodleyman** [comment]
I was not able to replicate the issue on 6.1.14, only in the beta

**Comment by abrookbanks** [comment]
Weird because it works the same way in theory. Probably proves that its clearing the cache even more than with admin page loads.

Thanks.

**Comment by abrookbanks** [comment]
Got to finish early today as I need to get into London for 5pm meeting (beers).

**Comment by havenswift-hosting** [comment]
>>If you have a busy store and the store admin spends 2 hours editing products clearing the cache every few seconds while visitors are writing the cache out every second it will decimate the server read write processes

It is even worse in bigger stores with multiple admin users - currently each admin is clearing cache after each admin page load, so much so that we have sites where even as quick as it is to delete files on a Linux system, one set of cached files isnt fully deleted before another admin user is trying to delete some of the same cache files.  With two or more admin users actively working, it is better to switch off cache completely !  The way it is proposed to work in 6.2 is exactly how WordPress cache and Magento cache and many other systems work.

>>but, they have to clear it anyway after they edit every product, so what's the difference between automating it and manually doing it?

There is absolutely no need to be clearing cache after every edit otherwise you might as well switch it back to automatic although even that would be better than what it currently does which renders caching almost useless

**Comment by abrookbanks** [comment]
I think when people understand they will appreciate it. I'm expecting a backlash after release so I might need the help of kind folk like yourself to set them straight.

**Comment by abrookbanks** [comment]
Thanks Ian.
