### ISSUE TITLE
BETA2 - Product unavailable button on product page

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1948]
the button is misaligned when visible with the latest theme version.

![image](https://user-images.githubusercontent.com/10614018/38682507-2646673c-3e63-11e8-857d-81c708c0dc7a.png)

**Comment by abrookbanks** [comment]
Sorry I can't reproduce this. Have you cleared your cache?

![screen shot 2018-04-16 at 15 13 06](https://user-images.githubusercontent.com/4520803/38814147-b8ad8fba-4188-11e8-854e-aa5bfe22b149.png)

**Comment by Noodleyman** [comment]
Still reproducible, clean install of beta2, stock theme and a test product made unavailable. 

![image](https://user-images.githubusercontent.com/10614018/38814788-46d21a08-418a-11e8-9f9b-02cfbfb54d65.png)

**Comment by abrookbanks** [comment]
Ah its on the PDP page!

**Comment by abrookbanks** [comment]
Thanks Alec.
