### ISSUE TITLE
BETA2 - Foundation, element.navigation_tree.php

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1949]
The "rel" value in the following line should be an absolute URL, currently it is not. 

`<li itemprop="name"><label itemprop="url" content="{$BRANCH.url}" rel="{$BRANCH.url}">{$BRANCH.name}</label></li>`

I tried to fix it using the {$STORE_URL} variable, but for some reason this variable does not work within this file. 

![image](https://user-images.githubusercontent.com/10614018/38684208-173d5fbc-3e67-11e8-8e6e-2651a9d3b9b2.png)

**Comment by abrookbanks** [comment]
This will also be fixed by [this](https://github.com/cubecart/v6/commit/2b4705dcb3dd858ff68358a3399f7183a5c12ac6).
