### ISSUE TITLE
Currency Symbols

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#195]
I am running CC5216 and CC600b4 side-by-side, using the same webserver, PHP, and database (installed and populated starting at CC520 upgrading as required).

Viewing the Currency table in admin, CC5216 shows the various symbols, but CC006B4 shows question marks and white '? in black diamonds' for all foreign characters.

So, I think something isn't talking UTF-8 properly.

I see that I am using a specially crafted CC5216 where this has been updated:
```
CC600B4: mysqli.class.php
		//Force UTF-8
		@mysqli_query($this->_db_connect_id, "SET NAMES 'utf8'");
		@mysqli_query($this->_db_connect_id, "SET CHARACTER SET 'utf8'");
CC5216: mysqli.class.php
		//Force UTF-8
		//@mysqli_query($this->_db_connect_id, "SET NAMES 'utf8'");
		//@mysqli_query($this->_db_connect_id, "SET CHARACTER SET 'utf8'");
		@mysqli_set_charset($this->_db_connect_id, 'utf8');
CC5216: mysql.class.php:
		@mysql_set_charset('utf8', $this->_db_connect_id);
```
I will switch up the CC6 code and report.

**Comment by bhsmither** [comment]
Yes, all the symbols are displaying properly.

**Comment by abrookbanks** [comment]
EXCELLENT WORK!!! :+1: 

.. testing now ..

**Comment by abrookbanks** [comment]
This didn't make any difference for me.. Screenshot below after fresh install. 
![screen shot 2015-02-10 at 16 39 36](https://cloud.githubusercontent.com/assets/4520803/6131411/98381922-b143-11e4-87a3-b00d4e966de1.png)

**Comment by abrookbanks** [comment]
This didn't work either:

```$this->_db_connect_id->set_charset("utf8");```

**Comment by bhsmither** [comment]
You have some of them: euro, pound, yen -- unless the database setup data file uses the HTML entity for these characters -- checking the data.sql file, that's what is happening.

**Comment by abrookbanks** [comment]
I think the code is better than we had before according to the  PHP docs so keen to keep this anyway. I'll continue experimenting and check the SQL file has correct encoding.

**Comment by bhsmither** [comment]
My programmer's text editor says data.sql is being seen (by it, anyway) as UTF-8.

**Comment by abrookbanks** [comment]
Same here.. "Unicode (UTF-8)"

**Comment by bhsmither** [comment]
Also, I mentioned it many moons ago, the order of arguments for `mysql_query()` is *string*, *connection*.

Please check line 223 in mysql.class.php.

**Comment by abrookbanks** [comment]
TINYBLOB to the rescue!

**Comment by abrookbanks** [comment]
.. checking order of arguments

**Comment by bhsmither** [comment]
I also see in structure.sql that some tables are being setup with the MyISAM engine, and some with the InnoDB engine.

Is there a legitimate strategy for mixing the engines? Any solid reasons for using InnoDB?

**Comment by abrookbanks** [comment]
Some tables need fulltext search so have to have MyISAM. From what I have read InnoDB is best where possible.

**Comment by bhsmither** [comment]
Please search on *huge ibdata1 file*. I don't understand the fine, technical details of the argument, but it 'scared' me. A busy store has the *potential* (as I see it) of pissing off the server admin.

Probably making a mountain out of a molehill.

**Comment by abrookbanks** [comment]
Hmm I wonder what @havenswift-hosting thinks?

**Comment by havenswift-hosting** [comment]
InnoDB is generally preferred over MyISAM for many reasons and the ibdata1 file is the system tablespace for the InnoDB infrastructure containing table data space, table index space, data dictionary as well as other things and it is usually the undo / rollback that causes this file to grow - you are generally storing the same amount of data but in one file rather than multiple database files.  You can also separate Data and Index Pages from ibdata1 by enabling innodb_file_per_table and this has some pros and cons.

To be honest, servers come with pretty big disks these days and having a ibdata1 file that is tens or even hundred GB shouldnt be an issue

**Comment by abrookbanks** [comment]
Ah.. excellent he got my nudge. :pager: 

Thanks Ian! Excellent stuff!!

**Comment by bhsmither** [comment]
Thanks Ian! We appreciate the insights.

**Comment by abrookbanks** [comment]
Thrilled this issue is fixed at last. Whoop!
