### ISSUE TITLE
BETA2 - Clean install - SQL errors and bad SEO paths

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1950]
performed a fresh install of CC using the latest beta, noted no page links on the store front worked. reviewed the Error log and found 213 SQL errors from the install.

![image](https://user-images.githubusercontent.com/10614018/38731804-b7ef1d72-3f13-11e8-84cd-cfc2fcf52beb.png)

the table contains:
![image](https://user-images.githubusercontent.com/10614018/38731823-cda8e580-3f13-11e8-9b1c-025cdded2de5.png)

Turns out this is cache related, after install none of the page URLs work until cache is manually cleared. the installer / upgrade should trigger a cache clear at the end to resolve.

**Comment by Dirty-Butter** [comment]
Maybe the beta comment I put here and then closed on my own is not so much my own error after all. I thought it was cache related at the time: https://github.com/cubecart/v6/issues/1924
