### ISSUE TITLE
BETA - Package Count?

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1952]
What is the Package Count field for in the Product Dimensions admin tab?

**Comment by bhsmither** [comment]
On what screen?

**Comment by Dirty-Butter** [comment]
On a specific listing - Products>Dimensions

**Comment by bhsmither** [comment]
I don't have a Dimensions tab. Maybe new to B2 (as opposed to B1)?

**Comment by Dirty-Butter** [comment]
I'm on current commit I think. Just beginning to kick all the tires. I think I've had a Dimension tab for some time on beta commits. But I hadn't looked at any tabs on anything until today. Mainly just trying to get it all to work at this point.

**Comment by bhsmither** [comment]
"Current commit"? Would this then be something past the published CC62B2?

Looking at the (published) B2 code, I see there to be tabs for:
General, Description, Pricing, Category, Options, Image, Digital, Search Engines, Translations, and Reviews - if any.

Where is the Dimensions tab in that lineup?

**Comment by Dirty-Butter** [comment]
I'm using the most recent commit, which is past the published beta, https://github.com/cubecart/v6/commit/4535281380ff22a9c6ae1b981e4443068deae8e5

When you open a product listing in Admin, the last tab is the Dimensions.

**Comment by abrookbanks** [comment]
I think this is an extension or something. I can't find any reference to a global search for "Package Count".

**Comment by Dirty-Butter** [comment]
Sorry - I didn't realize I still had SFWS's Dimensions plugin installed on this test site.
