### ISSUE TITLE
BETA - flag images

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1953]
On the Email Contents screen, my Translation Flags are touching each other - no space in between.

**Comment by bhsmither** [comment]
There is a space character in the HTML source.

But, as a result of the squeeze algorithm implemented in Smarty, almost every line ending and white space, and HTML comments, are stripped.

There will need to be a CSS rule to counter-act this loss of spacing, or use a `&nbsp;` character.

**Comment by abrookbanks** [comment]
Fixed with 869610217fdfa5440c54b58e246c797b6f9976fe typo on issue ID.
