### ISSUE TITLE
SSL Admin Settings

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1954]
These settings initially had correct values for what I had used as the FQDN for the B1 installation.

Then I changed the FQDN.

These settings retained their values and did not change to match the new FQDN.

So, I blanked them, believing CC62B1 would redetermine the correct values and populate the fields.

The Cookie Domain did update, but the Store URL is simply a forward slash.

I entered the suggested value and saved. The Store URL is still simply a forward slash.

I cleared the cache, and tried again. Still simply a forward slash.

**Comment by abrookbanks** [comment]
Honestly I thought I was going mad! Hahaha.
