### ISSUE TITLE
OID Config Setting Not Available

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1955]
Just for reference:
https://github.com/cubecart/v6/commit/c98a11fe160e3bc9936a5d12a57a80bd294b97d3#comments

It seems that the new Custom OID setting is not immediately available until at some point the Store Settings are saved.

1. Install a fresh CC62.
2. Install (via token) the US language pack.
3. View admin, Email Templates, **Admin: Order Received** (US).
4. Note there is nothing (cart_order_id or whatever) as the element part of the $DATA variable for the Order Number.

Config['oid_col'] could be pre-set during install.

Or, right after the install, as the link to the admin, go straight to Store Settings (instead of the default Dashboard) with a warning banner to advise the admin to enter (at least) the Store Name and Save.

**Comment by abrookbanks** [comment]
Thanks Brian. Should be safe now.
