### ISSUE TITLE
Doc Add Translation List of Language Choices Wrong

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1956]
CC62B1:

Install the English-US language pack and make sure it is enabled.

In admin, Documents, note that the Language shows the flag for the language that was in use during install. (If that's important?)

Click the **Add Translation** icon for "Welcome to [Store Name once it is known]".

Note the Language drop-down contains **only** the language already assigned to the document.

**Comment by abrookbanks** [comment]
Hmmm... I think all version may do this. Great bug find.

**Comment by bhsmither** [comment]
CC6114 works correctly, but then it had that bleed through issue.
