### ISSUE TITLE
Language Bleed-Through

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1958]
CC6114:
This is a duplicate from long ago - I am sure I've seen this reported somewhere.

Install a language not being used by anyone anywhere.

In admin, Languages, click the Edit icon for that language.

Various parts of the admin screen are displayed in that language.

I cannot duplicate this in CC620B1. So, I assume this has been fixed for CC6115 as well?

**Comment by abrookbanks** [comment]
I don't know but if you can't reproduce it then there is nothing to do right?

If you can and have steps to reproduce then I'll have a look at this.
