### ISSUE TITLE
Language Files

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#196]
With at least the DK language file, regardless that it is compatible with CC6, it has little to no CC6-specific phrases.

**Comment by abrookbanks** [comment]
This is correct. They will show phrases from the master language file if no translation has been made. Looking for volunteers after 6.0.0 final to fill in the gaps. There is no budget for using an agency sadly.

**Comment by abrookbanks** [comment]
It might be nice for there to be a built in tool to pickout missing translations. US and UK English are intentionally only about 5% translated.

**Comment by bhsmither** [comment]
This issue was prompted by:
http://www.cubecartforums.org/index.php?showtopic=19130

**Comment by bhsmither** [comment]
http://www.cubecartforums.org/index.php?showtopic=19130&view=findpost&p=77895

**Comment by abrookbanks** [comment]
We need to seek developers/merchants to take on translations as their own projects.
