### ISSUE TITLE
Stock levels not increased when deleting an order

### ISSUE THREAD

**Issue by bos4711** [cubecart/v6#1960]
CC 6.1.13

Settings -> Store settings -> "Reduce stock levels" is set to "When the order is placed (Pending)".

If a buyer adds PRODUCT (1 left in stock) to his basket and checks out, and I delete the order, the stock level for PRODUCT is zero (0).

Expected value here would be one (1) since the order was deleted.

**Comment by bos4711** [comment]
Update: same behaviour when an order is "Denied"; the product does not re-stock to the amount that was set in the order.

**Comment by abrookbanks** [comment]
How do I deny an order?

**Comment by bos4711** [comment]
Sorry, I meant "Declined".

![declined](https://user-images.githubusercontent.com/11036018/39989774-24034b5e-576b-11e8-8c3d-a30d759342bf.png)

**Comment by abrookbanks** [comment]
Thanks for your patience with this one! This will be resolved in 6.2.3. Please find patched attached.
