### ISSUE TITLE
RC2 - product tabs on storefront issue?

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1962]
I'm working on merging my edits with rc2 foundation, and nothing I do gets the tabs to look correct on a product storefront listing. Even when I use a stock content.product.php I get the specification
 table showing on description and the description showing on the spec table. It looks the same no matter which tab you click on.
Is there another file I need to fiddle with besides content.product.php?

![6 2rc2-screenshottabsissue](https://user-images.githubusercontent.com/6146505/38958180-1a4acc3e-4322-11e8-9927-5abfc045d764.png)

**Comment by abrookbanks** [comment]
I can't reproduce this Rosemary. I'm sorry.

**Comment by Dirty-Butter** [comment]
I was able to get a clean install on a test site with R2, so now I can make such comparisons for myself. Thanks.
