### ISSUE TITLE
Add support for secure database connections

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1963]
Given the current climate of security issues, can we put adding support for secure MySQL connections on the road map?

It should be fairly simple to add support for this via some additional advanced settings, although as with all things it does have dependencies on the MySQL server version & configuration.

**Comment by abrookbanks** [comment]
The vast majority of customer use localhost or internal network hostname. This would be a welcome feature but as an internal process it's not critical.

Granted this would be good for those using an external host (which must be a performance bottleneck).
