### ISSUE TITLE
Problem with email field after failing error checking

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1968]
This has been around a while, but I only just remembered to report it. I've replicated this on the latest beta build to validate it still exists.

If you are adding an email address, for example on the registration page of the store front and you trigger the "That email address is already being used." error, it's very difficult to type your new email address. Every time you type a new character the focus is lost on the email field.

**Comment by abrookbanks** [comment]
I'm really pleased you mentioned this. Since the CSRF token is now static we can remove this annoying fail safe. It was introduced to make sure the CSRF token got updated before submitting again therefore stopping CSRF error on email check.

**Comment by Noodleyman** [comment]
Thank you Al :)

**Comment by abrookbanks** [comment]
I think we can strip it back even further..

**Comment by abrookbanks** [comment]
Ok so I nearly made a stupid mistake changing the JSON format in the core code which would upset any custom skins currently using CSRF. Reverted back but only used required data from it ignoring the returned token.
