### ISSUE TITLE
RC2- duplicate boxslider line templates\element.css

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1971]
'skins/{$SKIN_FOLDER}/css/cubecart.helpers.css',
                                'skins/{$SKIN_FOLDER}/css/jquery.bxslider.css',
                                'skins/{$SKIN_FOLDER}/css/jquery.bxslider.css',
                                'skins/{$SKIN_FOLDER}/css/jquery.chosen.css']}

**Comment by abrookbanks** [comment]
Thank you!!
