### ISSUE TITLE
BETA issue - currency

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1972]
minor thing, not sure if this is by design or not. If you only had a single currency enabled then the currency selector on the store front would be hidden, why show something with only one choice, right?

but, I just noticed that it does still show in the latest versions, only with a single currency available.

**Comment by bhsmither** [comment]
Also a minor thing, but may come to bite you later: several countries use the same symbol --
Mexico, USA, Australia, Canada, New Zealand, Singapore use $.

**Comment by abrookbanks** [comment]
On the grounds of shared symbol I'd suggest adding a suffix.

E.g. $9.99 USD, $9.99 CAD etc.

**Comment by abrookbanks** [comment]
It's one of those preference things. Some people like to see what currency the store operates in.

We could easily add some code to remove it. I'm not sure why the decision to show it was made. Maybe another user asked for it. I don't know. It can easily be removed with a simple code change. 

Let's leave this as it is for now but keep in mind.

**Comment by Noodleyman** [comment]
just an observation. the code in smarty is designed to hide it today, but for some reason isn't.. :)

it uses:
`{if count($CURRENCIES)>1}`

I've not looked at it in detail

**Comment by abrookbanks** [comment]
Thats right. There is an else to the clause to show just the one currency. [Those lines](https://github.com/cubecart/v6/blob/6.1.15-branch/skins/foundation/templates/box.currency.php#L22-L23) could be removed.
