### ISSUE TITLE
categories 6.2.0-rc2

### ISSUE THREAD

**Issue by LibertineNL** [cubecart/v6#1974]
Just upgraded to newest version.
It seems that I can't change the categories in my store.
New category doesn't show up online, visible/status on or off doesn't work either

**Comment by bhsmither** [comment]
CC62 incorporates a "Clear Cache on Demand". That is, make your edits, then when necessary, clear the cache. There is a "Clear Cache" button in the upper right corner.  It should be lit when databased edits are ready to be re-cached.

If this is frustrating for you, especially when initially building and stocking your store, see if disabling the cache makes things easier. In admin, Store Settings, Advanced tab, "Enable Caching" to Disabled.

**Comment by abrookbanks** [comment]
I made a note about this on the 6.2 release announcement.
