### ISSUE TITLE
Language Key Consistency

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1975]
Suggestion: add language key to `$email_types` and `CubeCart_email_content`.

Note the inconsistency:
```
title_macro_admin_order >> admin.order_received
title_macro_admin_password >> admin.password_recovery
title_macro_admin_review >> admin.review_added
title_macro_cart_certificate >> cart.gift_certificate
etc.
```
Note: If the language key and the content type were consistent, enhancements could be more easily done. For example:
```
title_macro_admin_order_received >> admin.order_received
title_macro_admin_password_recovery >> admin.password_recovery
title_macro_admin_review >> admin.review
title_macro_cart_certificate >> cart.certificate
etc.
```
Since this is not likely to change, add the column `name` to `CubeCart_email_content`. The value would be the language string attribute `"name"`, thus gluing the definitions.xml title phrase to email type.

One can associate `<string name="title_macro_user_newsletter">` to `newsletter.verify_email`.

**Comment by abrookbanks** [comment]
Agreed I can't change the keys which is annoying. I have added the description e.g. Admin: Order Received to the database to help tie it all together. I hope that ticks this box and I understood right. 

I have to say this this has pestered me in the past too as it makes finding the right email content tricky.
