### ISSUE TITLE
Leading Zeros is a misleading label

### ISSUE THREAD

**Issue by hairy-dog** [cubecart/v6#1976]
In 6.2.0 the new order number setup (which is great, thanks) has a setting labelled "Leading Zeros", but that is simply not what it is. It is the number of digits in the order number. There may or may not not be leading zeros, depending on how many digits are in the order number.
I can't see any reason why the label can't be "Digits in Order Number" or "Number of Digits". or "Number Length". 
I don't think that the precise wording matters much, but "Leading Zeros" is both incorrect and misleading.

**Comment by abrookbanks** [comment]
Number Length is probably better. Something for 6.2.1. Thanks.
