### ISSUE TITLE
Forum 

### ISSUE THREAD

**Issue by MrGweb** [cubecart/v6#1978]
sorry to post here but the forum has this error - you cant do anything it wont let you reply or post 

this is on the bottom of the page 
![screen shot 2018-04-25 at 7 13 30 pm](https://user-images.githubusercontent.com/30888410/39236711-d1490b86-48bc-11e8-837f-d765f469d733.png)

[[Template core/global/global/includeJS is throwing an error. This theme may be out of date. Run the support tool in the AdminCP to restore the default theme.]]

**Comment by abrookbanks** [comment]
Looking at this now..

**Comment by abrookbanks** [comment]
Fixed now. Redis had died.
