### ISSUE TITLE
GDPR Keep evidence of consent – who, when, how, and what you told people

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1979]
As above. CubeCart needs a subscription consent log and bulk emailer log as to when marketing was sent.

**Comment by abrookbanks** [comment]
Also log when terms and conditions accepted on checkout probably with current terms and conditions saved against it.

**Comment by abrookbanks** [comment]
![screen shot 2018-04-27 at 12 06 11](https://user-images.githubusercontent.com/4520803/39359834-7e031072-4a13-11e8-83e8-315eaef76136.png)

**Comment by abrookbanks** [comment]
![screen shot 2018-04-27 at 13 35 51](https://user-images.githubusercontent.com/4520803/39362873-ed639e12-4a1f-11e8-9cef-8b402c7e380c.png)

**Comment by havenswift-hosting** [comment]
Looking good - might also be useful to be able to select all newsletter signups based on whether they have opted in or not and then be able to send an email to those not double opted in and also a method to delete those not double opted in

**Comment by abrookbanks** [comment]
![screen shot 2018-04-27 at 14 03 28](https://user-images.githubusercontent.com/4520803/39363908-e133534a-4a23-11e8-8a99-5e5e29b0ebca.png)

**Comment by charles111444** [comment]
Recording consent
 We keep a record of when and how we got consent from the individual ?
 We keep a record of exactly what they were told at the time ?

**Comment by charles111444** [comment]
Recording consent
Any consent and log of privacy policy (accept or not) Or Except as the only option. Is this needed ? Eg I accept your cookies used on this website. Logged at? By?  or denied. If denied then a facility to stop them purchasing on website.

**Comment by abrookbanks** [comment]
You mean accept not except?

**Comment by charles111444** [comment]
yes lol thank you oops.

**Comment by charles111444** [comment]
Think a news letter opt in opt out ain't needed. Just opt in opt out accepted or denied cookies. They the one who signs up to them in the first place and pretty sure you could put in privacy policy that if you want us to stop sending you news letter to give us a email or call.

**Comment by charles111444** [comment]
Think a news letter opt in opt out ain't needed. Just opt in opt out accepted or denied cookies. They the one who signs up to them in the first place and pretty sure you could put in privacy policy that if you want us to stop sending you news letter to give us a email or call.
