### ISSUE TITLE
What cookies are used by CubeCart

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1980]
I know it is possible to find out what cookies are being used via Chrome developer tools and various websites but many store owners may not be able to use or understand this so it might be useful to have a KB article saying what cookies are used by a standard CubeCart store (maybe include cookies such as Analytics that are part of core code although not necessarily present on all stores).  Obviously you will need to mention that 3rd party plugins / skins could add additional cookies

**Comment by abrookbanks** [comment]
Funny this was on my mind.. I'll create a KB article.

**Comment by abrookbanks** [comment]
https://support.cubecart.com/Knowledgebase/Article/View/241/20/what-cookies-are-used-by-cubecart
