### ISSUE TITLE
Feature Request - Restrict access to admin panel via IP address.

### ISSUE THREAD

**Issue by keat63** [cubecart/v6#1981]
Not sure if this has been considered, but a feature to restrict admin panel login to IP address or addresses would be a nice feature.
Easpecially given the new GDPR nonsense.

**Comment by havenswift-hosting** [comment]
It isnt really a GDPR issue but is a good idea if you have a fixed IP address from your ISP.  However, it is much better if this is done manually rather than through CubeCart and is very simple to do by creating a .htaccess in the admin directory with the IP's allowed / denied

**Comment by abrookbanks** [comment]
This should not within the realms of CubeCart. Instead it should be at firewall/web server level which will by nature be much more efficient.

**Comment by keat63** [comment]
Not everyone has access to a firewall or web server access.

**Comment by abrookbanks** [comment]
You have access to the .htaccess file. :)
