### ISSUE TITLE
Selecting a category image after uploading a new one does not work

### ISSUE THREAD

**Issue by romanklabal** [cubecart/v6#1982]
Steps to reproduce:

1. Edit a category in the backend
2. Upload a new image using the AJAX CC Dropzone
3. Select any image in the fileTree
4. No changes are saved, because the $_POST['imageset'] array is not present in the request

I have found the bug in the admin.js file. When you create a new fileTree, you set the name based on the id attribute:

`name: $(this).attr("id")`

However when you refresh the fileTree after a new AJAX upload, you use a fixed name value:

`name: 'image'`

Which means instead of $_POST['imageset'], it sends $_POST['image'].

https://github.com/cubecart/v6/blob/b1d7c3ab0c074ee81568fa9682d1ede829c1fd48/admin/skins/default/js/admin.js#L341

I have used this workaround for the dynamic fileTree refresh after upload:

```
var name = $("div#imageset.fm-filelist").attr("id");
$("div#imageset.fm-filelist").fileTree({
    root: "/",
    script: "./" + t,
    group: '1',
    name: name == null ? 'image' : name,
    unique: false
});
```

This probably affects more than just the categories and I guess the fileTree instance after an upload should be more versatile, but I am sure you will know what to do Al.

**Comment by romanklabal** [comment]
To be honest the more I look into this the more confused I am, as it should not work for products as well, huh. I trust you with it though, as its definitely broken for categories!

**Comment by abrookbanks** [comment]
Thanks for the detailed report.

**Comment by abrookbanks** [comment]
Thanks!! We got there eventually.
