### ISSUE TITLE
6.2.0 State Required??

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1986]
https://github.com/cubecart/v6/commit/01c4032dd8a3f6a7959354cf1927c5cdff82d779

I've checked on two of my test sites and the Required State Status db change is not being applied to USA.

**Comment by bhsmither** [comment]
Were these two sites an upgrade from CC6.1.X to CC6.2.0?

If so, I have found a problem. Issue to be posted soon.

**Comment by Dirty-Butter** [comment]
6.1.14 to 6.2.0 - haven't applied the latest change Al mentioned on a forum post - otherwise to current. I have issues in both test site databases as far as error messages on key.

**Comment by bhsmither** [comment]
(If the "error messages on key" does not relate to this Country vs State issue, may I humbly recommend that we do not pollute this (or any) thread with unrelated comments.)

See issue #1989.

Does the choice of 'State Required' stick if changed from within admin?

**Comment by Dirty-Butter** [comment]
Sorry, since your explanation of the cause of the State Required not working at this point deals with table structure settings - I thought it might be related. That's my lack of understanding, as usual.

And, yes, the Required sticks when changed within admin.  Optional countries like the UK, with states already in the database, DO have the drop down choices, however.

**Comment by abrookbanks** [comment]
Thanks guys. I'll close this due to #1989 and pick it up form there.

**Comment by abrookbanks** [comment]
Fixed with recent commit.
