### ISSUE TITLE
Database Index

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1987]
CC620:
Looking at the 6.2.0-b1.sql file, there is a new column `custom_oid` added with `NOT NULL DEFAULT ''`.

This adds the column and fills all rows with a zero-length string.

Then there is a new index added with `UNIQUE` attribute.

My database manager is complaining about `Duplicate entry` for `custom_oid`.

**Comment by Dirty-Butter** [comment]
I have the same issue - thought it was my fault. I have a support ticket into host, but maybe it's a CC issue?

**Comment by abrookbanks** [comment]
It can't be a unique column at the time of setup. I'd suggest we lose this from install/upgrade and apply at the time of creating the trigger.

**Comment by abrookbanks** [comment]
It just can't be a unique key.

**Comment by bhsmither** [comment]
It can be a UNIQUE KEY if you allow this column to contain nulls.

That would mean a graceful fallback to using `cart_order_id` if `custom_oid` for an order summary is a zero-length string **or null**.

(An alternate, but ultimately unsatisfactory solution, is to span the UNIQUE KEY across `custom_oid` **and** `id`, **in that order**. This will allow the index to be unique and searchable just on the `custom_oid` column, but it also means `custom_oid` could hold duplicated content -- just like it does now.)

**Comment by abrookbanks** [comment]
Great work Brian! :)
