### ISSUE TITLE
6.2.0 predis??

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1988]
I don't understand this code, but it just looks like it needs a / before lib to me.

redis.class.php in classes\cache

	require CC_INCLUDES_DIR."lib/predis/autoload.php";

Wondering if it might be a typo or, more likely, my ignorance of the code

**Comment by bhsmither** [comment]
In ini.inc.php, a constant is set up to be:
`CC_INCLUDES_DIR` is `CC_ROOT_DIR.'/includes/'`
where
`CC_ROOT_DIR` is `realpath(dirname(__FILE__))`
where
`realpath(dirname(__FILE__))` is the server-level path the operating system says the file `ini.inc.php` is located - without a trailing slash.

In conclusion, all the special DIR constants have trailing slashes - except CC_ROOT_DIR.

**Comment by Dirty-Butter** [comment]
Figured it was my lack of understanding. Thanks Bsmither. I'll close this.
