### ISSUE TITLE
Wording on CC Download page

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#199]
as above - " Please note that some older versions contain encrypted code and will require a software license key to work."

**Comment by abrookbanks** [comment]
Changed to "Please note that any version not released under GPL 3.0 may require a legacy software license key to work.". Is that better? I failed all my English exams at school!!

**Comment by Dirty-Butter** [comment]
Sorry, but I'm still confused. I interpreted your original announcement on the forums to mean that ANY version downloaded and installed NOW would be open source.

**Comment by abrookbanks** [comment]
There is too much admin to go back though all versions of code and trip out the license system. Thats why it says;

> License: GPL 3.0 (from 5.2.15)

Only the green downloads are open source license.

![screen shot 2015-02-11 at 14 15 51](https://cloud.githubusercontent.com/assets/4520803/6148371/c8902212-b1f8-11e4-96be-fddee0795849.png)
