### ISSUE TITLE
Newsletter Confirm Subscription language packs

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1992]
The newsletter confirmation section needs to be added to the language packs when you have time (lol)

**Comment by abrookbanks** [comment]
I can't do it because I am monolingual. Actually thats a lie as I can order a beer in French, Spanish, Italian and German. (Don't test me please!!!).

I have to leave this work to someone else.

**Comment by Dirty-Butter** [comment]
I don't think the opt-in choice for newsletters is going to work if there is no confirmation email to send. I got an error message when I tried.

**Comment by abrookbanks** [comment]
Yes it will send now since these fixes even if the translation for the current language doesn't exist. It will send it in English.
