### ISSUE TITLE
Skin Select - Clear Cache Required

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#1994]
Scenario:
- 6.2.0 store, clean install
- multiple skins
- switch skin enabled for all

If a customer uses the skin selector to change skins, it will result in a blank white page in the storefront.
I believe that occurs as there is no cached CSS + JS files for skin being switched to.

Clicking on the 'clear cache' link on the admin dashboard will resolve the issue, somewhat.

Suggestion:
Add clear/rebuild cache functionality into the change skin function.

**Comment by bhsmither** [comment]
There will be the bare-bones HTML sent to the browser. Sure, browser may get a 404 if the "combined" files are not in the cache. But there will be a page - it will look ugly.

The fault must lie elsewhere.

**Comment by bhsmither** [comment]
I didn't do a CC620 clean install, but I changed through several skins no problem. Are you saying this **must** be a clean install?

**Comment by bhsmither** [comment]
A fresh install of Beta1 (on a standby server) switched fine to Kurouto.

A skin needs to utilize the new Smarty plugin {combine} to get those massive CSS and JS files located in the /cache/ folder. Otherwise, the page makes requests to the skin's own css and js files.

**Comment by abrookbanks** [comment]
I can't reproduce this at all.

**Comment by abrookbanks** [comment]
Movie: http://static.cubecart.com/issue-1994-skin-switch.mp4

**Comment by abrookbanks** [comment]
I'll reopen if needs be. Please come back with more info if this persist.
