### ISSUE TITLE
Default Language entries cannot be edited

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1995]
In the Demo store (where all language phrases are stock) - terms cannot be edited. On my test stores the previous edits that are saved in my lang_strings table can be edited.

**Comment by bhsmither** [comment]
Please see #1903.

**Comment by Dirty-Butter** [comment]
Ah - didn't occur to me to check other browsers. So it works properly in Chrome. Is this fixable from CC's side?
But #1903 seems to say that clicking on the area does allow editing. My FF only allows editing if it had previously been edited, no matter where or how I click.

**Comment by bhsmither** [comment]
My Firefox, I have to click on the language key, or basically anywhere directly to the left of the text-entry box.

**Comment by Dirty-Butter** [comment]
THAT works! Not intuitive, but it works. THANK YOU!!

**Comment by abrookbanks** [comment]
Use Chrome instead its much nicer. :)
