### ISSUE TITLE
Column Sort May Not be Acted Upon

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1999]
In orders.transactions.inc.php, line 79, the query includes `JOIN` and an array for the sort. Also, line 28.

In `DB->select()`, if `JOIN` is found, `$allowed` is not set.

Later, when constructing `$orderString`, `$order` is an array but `$allowed` is not an array, and `$orderArray` is not built.

Therefore, `$orderString` is _null_.

Quick fix is to fix orders.transactions.inc.php by changing `$_GET['order']` to a string at line 64.

Maybe a better fix is to build `$assign` in `select()` somewhere after line 602 with an array of all columns from all tables found in the query - which would require some creative coding. Reference #2003.

**Comment by abrookbanks** [comment]
Fixed with https://github.com/cubecart/v6/commit/ca4f4358e94a133efbf0771ec1e7b9293b9294c0
