### ISSUE TITLE
Last Ditch Skin

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#20]
Similar to #16, if upgrading from CC5 to CC6, the existing config settings will be used.

So, there may also be an issue with no valid skin to use ("Last ditch skin" - GUI line 1330).

Session may have a client skin, but (I cleared cookies and changed `ini_set('session.name', 'HTDOCSCC600B1');` maybe not. Then Config may have a skin, but it won't be in `$this->_skins`. Finally, if `$this->_skins` does exist, the first skin found in the skins folder will be used.

Suggest that foundation always be the last ditch skin and do **not** trigger_error().

**Comment by abrookbanks** [comment]
Thanks for this Brain. :)
