### ISSUE TITLE
Recommended PHP version

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2000]
CubeCart is still showing 5.6 as the recommended PHP version - this should be at least 7.1 or maybe even 7.2 (although cPanel dont yet support ionCube loaders 10.2.0 for PHP 7.2) now as these are the only actively supported versions (5.6 and 7.0 dont have active support and only have security support for six months)

**Comment by abrookbanks** [comment]
Agreed. As ioncube isn't required by default lets go with 7.2.

**Comment by abrookbanks** [comment]
See commit: a2d11cb30fb3b5877f23dd881f4a0eab14ef19f9
