### ISSUE TITLE
Bad URL

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2001]
New to CC620:
Jpayam has found that Foundation main.php (and probably main.checkout.php) uses `{$ROOT_PATH}`, which includes a trailing slash, causes a double-slash at the favicon link.

**Comment by abrookbanks** [comment]
Thank you

**Comment by havenswift-hosting** [comment]
I haven’t checked Foundation code, but don’t you need to make the change to main.checkout.php as well ?

**Comment by abrookbanks** [comment]
Absolutely!! I'm pleased you have your head screwed on this morning. I clearly don't.

**Comment by sumwonlost** [comment]
CC 6.2.5 - not working without the inclusion of slash.
