### ISSUE TITLE
Delivery Same as Billing Checkbox problem 6.2.1?

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#2004]
Works on 6.2.0 but not on 6.2.1 current commit.

https://forums.cubecart.com/topic/53961-delivery-same-as-billing-checkbox-problem-with-621/

My fault or a possible cache bug?

**Comment by Dirty-Butter** [comment]
It appears it WAS a cache issue, but is also was my fault. It dawned on me in the night that I still had cache disabled for testing purposes. When I enabled cache this morning and went through the checkout process on the front end again - it worked.

**Comment by abrookbanks** [comment]
Thanks for the update.

**Comment by Dirty-Butter** [comment]
This needs to be opened again. Since this issue has cropped back up for me, I created a test site with 100% STOCK of today's commit. 

Making sure to check the box choosing Billing and Delivery Addresses are the same does nothing. The next screen asks for a Billing Address.
The only plugins I have enabled are the PayPal, Google Base, and USPS. Cache is Enabled and Debugging is Disabled.

**Comment by Dirty-Butter** [comment]
I'm using file cache.

**Comment by Dirty-Butter** [comment]
The last time a commit created a default Billing/Delivery address correctly in the database was 05/05/18.

That was with the commit I downloaded on 05/03/18.

**Comment by abrookbanks** [comment]
See notes on #2057

**Comment by abrookbanks** [comment]
Sorry Rosemary but I just can't reproduce this.

**Comment by abrookbanks** [comment]
I was able to reproduce this and fixed with #2038
