### ISSUE TITLE
Non-Super Can Make Itself Super

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2005]
In a round-about way-- A non-super-user can create a code snippet (needs Settings:Edit permission), that tweaks the CubeCart_admin_users table by updating their record `'super_user' = 1`.

Suggest in settings.hooks.inc.php, change `permissions('settings'` to `permissions('maintenance'`.

Therefore, since there is no section called 'maintenance' in `Admin->_getSectionId)`, only a Super User can get access to admin, Manage Hooks.

~~And, since there is no `CC_PERM_FULL` in `Admin->_convertPermission()`, only a Super User can get full access.~~ No, wrong context.

**Comment by abrookbanks** [comment]
Code Snippet should be SU only really. I'll get this fixed.
