### ISSUE TITLE
Non-Super Can Install Plugins

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2006]
In plugins.index.inc.php, the code suggests that any admin with permissions of Settings:Read can install, enable, and delete plugins. No further checks and deterents based on permissions is made.

Also, near lines 167-171, `$request` is being built, but nothing is done with it.

**Comment by abrookbanks** [comment]
lines 167-171 tell CubeCart that the token has ben used and it is then deleted on our side. I'm not sure this is really necessary as they are cleaned up regularly anyway.
