### ISSUE TITLE
HEAD_JS cannot be combined as it expects script tags

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2008]
As above.

**Comment by SemperFiWS** [comment]
Seeing #2012 was closed, is the suggestion of moving the '{foreach from=$HEAD_JS item=js}{$js}{/foreach}' going to be applied?

**Comment by abrookbanks** [comment]
Yes this is resolved already

**Comment by abrookbanks** [comment]
Oh sorry. They should go below. Yes. I'll change it.

**Comment by SemperFiWS** [comment]
Thanks Al, much appreciated.

**Comment by bhsmither** [comment]
Would this also apply to $JS_SCRIPTS in element.js_foot.php?

**Comment by abrookbanks** [comment]
No I don't think so.

**Comment by bhsmither** [comment]
Case in point:
In the current element.js_foot.php file, there is a separate <script> tag. So, we know that {combine} needs to be before script tags that would reference these vendor (or module) scripts.

Suggest:
From:
```
{foreach from=$BODY_JS item=js}
    {$js_foot[] = $js}
{/foreach}
{foreach from=$JS_SCRIPTS key=k item=script}
    {$js_foot[] = $script}
{/foreach}
{combine input=$js_foot output='cache/js_foot.{$SKIN_FOLDER}.js' age='604800' debug=$CONFIG.debug||!$CONFIG.cache}
```
To:
```
{foreach from=$BODY_JS item=js}
    {$js_foot[] = $js}
{/foreach}
{combine input=$js_foot output='cache/js_foot.{$SKIN_FOLDER}.js' age='604800' debug=$CONFIG.debug||!$CONFIG.cache}
{foreach from=$JS_SCRIPTS key=k item=script}{$script}{/foreach}
```
Note that `$JS_SCRIPTS` now does not push onto `$js_foot`.

**Comment by abrookbanks** [comment]
As far as I can see JS_SCRIPTS will hold and array or file paths so it should be fine as it is.

```
//Put in the javascripts
$js = glob('skins/'.$this->_skin.'/'.'{js,scripts}/*.js', GLOB_BRACE);
foreach ($GLOBALS['hooks']->load('class.gui.javascripts') as $hook) include $hook;

$GLOBALS['smarty']->assign('JS_SCRIPTS', $js);
```
