### ISSUE TITLE
Bad adittional Image select in detailed product page

### ISSUE THREAD

**Issue by nklisic** [cubecart/v6#201]
In detailed product page additional picture not properly selected form db.
Currently select all pictures from db.

![cc605b_imagegalery](https://cloud.githubusercontent.com/assets/10867308/6145619/f8fc0eee-b1e3-11e4-8df1-05c7febcf038.jpg)

**Comment by abrookbanks** [comment]
Hm I can't reproduce this one. If you login to the admin side of your store and got to Maintenance then clear all caches does the issue persists?

**Comment by nklisic** [comment]
Hi Al,
After deleting cache nothing has changed. The same situation is on CubeCart
V6 demo site.


2015-02-11 12:16 GMT+01:00 Al Brookbanks <notifications@github.com>:

**Comment by abrookbanks** [comment]
Tested fix on demo store and all good.
