### ISSUE TITLE
Addresses stored multiple times as check for existence caches false

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2010]
As above. Existing address always returns false even after insert leading to duplicates.

**Comment by Dirty-Butter** [comment]
This one does not show up in the list of changes on 6.2.0. By the way, why is there not an actual link to 6.1.16 or 6.2.1 - the only current way to get to it is via Milestones.

**Comment by abrookbanks** [comment]
6.2.1 hasn't been released yet

**Comment by Dirty-Butter** [comment]
I know it's not released, but with 6.2.0/6.1.15 you were keeping a updated developer as well as a released branch version. So that was just because of 6.2?

**Comment by abrookbanks** [comment]
I've messed it up but will try to do so again in the future.

**Comment by Dirty-Butter** [comment]
Thanks! I try to keep one test site updated with any new commits. It's easier for me, because of all my edits, to upgrade in tiny bites :) Helps me to understand what the code is doing, although I don't expect to ever really grasp it all.
