### ISSUE TITLE
Cache Cleared by Only Admin Foils Decision Making

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2013]
CC620:

See: https://forums.cubecart.com/topic/53975-database-errors/

Also making refrence to https://github.com/cubecart/v6/commit/ddf50b12523270f165291a70e906e94d33017c9b

The `Database->insert()` and `->update()` functions now have this added to the test whether the cache should be cleared: `if (CC_IN_ADMIN && $purge...`

(Then we have `SEO->setDbPath()` which **does not** properly use select()'s `$cache` flag.)

Thus, we have a situation where a SELECT being used to determine whether to INSERT or UPDATE will invariable get it wrong.

**Comment by abrookbanks** [comment]
This should be resolved already with https://github.com/cubecart/v6/commit/e70d89431ba7f37d4d9782fa9527d3dfb886548d#diff-d56b75ca5f64dafedeb953b843b58b54.

Please note that I changed the constant name to keep more inline too.. 
https://github.com/cubecart/v6/commit/72700263cf5b2400d51ae99289f8b650b8fa5186#diff-d56b75ca5f64dafedeb953b843b58b54.

**Comment by abrookbanks** [comment]
This should be good now. Please pick me up if I missed something.

**Comment by abrookbanks** [comment]
Cache notice now impossible to clear..
