### ISSUE TITLE
GDPR Report - Then What?

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2014]
I get the table displayed. (Is it supposed to be downloaded like a report?)

Request a link to take me back to the Customer list.

Maybe have an icon in the action column (edit, delete, etc) to get the report of that customer, instead of a separate page load entering an email address.

**Comment by abrookbanks** [comment]
> Is it supposed to be downloaded like a report?

You can print it as a PDF if you like. Or you can use it to locate data to delete.

**Comment by bhsmither** [comment]
My point being - I seem to be at a deadend.

(My browser seems to be against sending a page request if the page being displayed is equal to the URL in the address bar.)

So, my request is for the Create Report button to be opening a new window, or there be a link back to the admin.

**Comment by abrookbanks** [comment]
Yeah its pretty basic and thrown together just so we have something. We can polish it up in the future.
