### ISSUE TITLE
6.2.0 State Required Countries Missing Zones?

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#2017]
Argentina, Brazil, India, and Japan are listed in 6.2.0 db query as Requiring "States". But there are no Zones listed in the admin. This causes a Required placeholder to show when one of those countries is chosen. 

So, if the zones are needed - will CC add them to 6.2.1, or do we need to manually add them. If manually, where do we find a list to use?

Also, to clarify - does the UK require "States" or not?

**Comment by abrookbanks** [comment]
Yes they require a value which will need to be put in the text field.

**Comment by abrookbanks** [comment]
UK does not require states ("Counties").

**Comment by Dirty-Butter** [comment]
https://en.wikipedia.org/wiki/Provinces_of_Argentina#List_of_provinces
https://en.wikipedia.org/wiki/States_of_Brazil#List
https://en.wikipedia.org/wiki/ISO_3166-2:IN
https://en.wikipedia.org/wiki/Prefectures_of_Japan#By_English_name

Maybe these will help if you need to add them to CC.

**Comment by Dirty-Butter** [comment]
Ah, I didn't notice you had answered. I remember the big mess the database got in way back when customers were allowed to add in whatever they thought belonged in State. I was hoping this would be added to Zones. Guess I'll do it myself.

**Comment by Dirty-Butter** [comment]
I never could get the Required placeholder to not show up on State Optional countries, so I've changed them all to State Disabled. 

Just as feedback: I also realized today that the list of enabled countries includes mostly countries I did not have listed in previous versions. It took a while to disable all the ones I don't want to ship to.

**Comment by Dirty-Butter** [comment]
Working on the Japan zones - there is no abbreviation for the prefectures as far as I could find. The ISO does not work, because the field needs at least 5 characters and only has 4. 

The same thing is going to happen with India.

**Comment by abrookbanks** [comment]
We can probably invent them ourselves.

**Comment by Dirty-Butter** [comment]
Personally, I'd rather change to 5 characters and stick to something that is found in Wikipedia. I finished Argentina and Brazil. But I don't know how to get the Hispanic diacritical marks. And I have no idea how to send the results to you to add to CC.

**Comment by Dirty-Butter** [comment]
OR maybe better, use the ISO but leave out the hyphen??

**Comment by Dirty-Butter** [comment]
Well, for Japan at least it's easy to take the first two letters of each one. Tell me how to send it to you and I'll get this done for you.

**Comment by Dirty-Butter** [comment]
OK - All four are done (with the special characters) whenever you tell me what format you want them exported from the database for you to import.

**Comment by abrookbanks** [comment]
Thank you. Just copy/paste to here is fine. 👍🏻😊

**Comment by Dirty-Butter** [comment]
| Argentina | Catamarca | CT | 
  | Argentina | Chaco | CC |   |  
  | Argentina | Chubut | CH |   |  
  | Argentina | Ciudad de Buenos Aires | DF |   |  
  | Argentina | Corrientes | CN |   |  
  | Argentina | Córdoba | CB |   |  
  | Argentina | Entre Ríos | ER |   |  
  | Argentina | Formosa | FM |   |  
  | Argentina | Jujuy | JY |   |  
  | Argentina | La Pampa | LP |   |  
  | Argentina | La Rioja | LR |   |  
  | Argentina | Mendoza | MZ |   |  
  | Argentina | Misiones | MN |   |  
  | Argentina | Neuquén | NQ |   |  
  | Argentina | Río Negro | RN |   |  
  | Argentina | Salta | SA |   |  
  | Argentina | San Juan | SJ |   |  
  | Argentina | San Luis | SL |   |  
  | Argentina | Santa Cruz | SC |   |  
  | Argentina | Santa Fe | SF |   |  
  | Argentina | Santiago del Estero | SE |   |  
  | Argentina | Tierra del Fuego | TF |   |  
  | Argentina | Tucumán | TM |   |

**Comment by Dirty-Butter** [comment]
| Brazil | Acre | AC |   | 
  | Brazil | Alagoas | AL |   |  
  | Brazil | Amapá | AP |   |  
  | Brazil | Amazonas | AM |   |  
  | Brazil | Bahia | BA |   |  
  | Brazil | Ceará | CE |   |  
  | Brazil | Distrito Federal | DF |   |  
  | Brazil | Espírito Santo | ES |   |  
  | Brazil | Goiás | GO |   |  
  | Brazil | Maranhão | MA |   |  
  | Brazil | Mato Grosso | MT |   |  
  | Brazil | Mato Grosso do Sul | MS |   |  
  | Brazil | Minas Gerais | MG |   |  
  | Brazil | Paraná | PR |   |  
  | Brazil | Paraíba | PB |   |  
  | Brazil | Pará | PA |   |  
  | Brazil | Pemambuco | PE |   |  
  | Brazil | Piauí | PI |   |  
  | Brazil | Rio Grande do Norte | RN |   |  
  | Brazil | Rio Grande do Sul | RS |   |  
  | Brazil | Rio de Janeiro | RJ |   |  
  | Brazil | Rondônia | RO |   |  
  | Brazil | Roraima | RR |   |  
  | Brazil | Santa Catarina | SC |   |  
  | Brazil | Sergipe | SE |   |  
  | Brazil | São Paulo | SP |   |  
  | Brazil | Tocatins | TO |   |

**Comment by Dirty-Butter** [comment]
| India | Andaman and Nicobar Islands | INAN |   |  
  | India | Andhra Pradesh | INAP |   |  
  | India | Arunachal Pradesh | INAR |   |  
  | India | Assam | INAS |   |  
  | India | Bihar | INBR |   |  
  | India | Chandigarh | INCH |   |  
  | India | Chhattisgarh | INCT |   |  
  | India | Dadra and Nagar Haveli | INDN |   |  
  | India | Daman and Diu | INDD |   |  
  | India | Delhi | INDL |   |  
  | India | Goa | INGA |   |  
  | India | Gujarat | INGJ |   |  
  | India | Haryana | INHR |   |  
  | India | Himachal Pradesh | INHP |   |  
  | India | Jammu and Kashmir | INJK |   |  
  | India | Jharkhand | INJH |   |  
  | India | Karnataka | INKA |   |  
  | India | Kerala | INKL |   |  
  | India | Lakshadweep | INLD |   |  
  | India | Madhya Pradesh | INMP |   |  
  | India | Maharashtra | INMH |   |  
  | India | Manipur | INMN |   |  
  | India | Meghalaya | INML |   |  
  | India | Mizoram | INMZ |   |  
  | India | Nagaland | INNL |   |  
  | India | Odisha | INOR |   |  
  | India | Puducherry | INPY |   |  
  | India | Punjab | INPB |   |  
  | India | Rajasthan | INRJ |   |  
  | India | Sikkim | INSK |   |  
  | India | Tamil Nadu | INTN |   |  
  | India | Telangana | INTG |   |  
  | India | Tripura | INTR |   |  
  | India | Uttar Pradesh | INUP |   |  
  | India | Uttarakhand | INUT |   |  
  | India | West Bengal | INWB |   |

**Comment by Dirty-Butter** [comment]
| Japan | Aichi | AI |   |  
  | Japan | Akita | AK |   |  
  | Japan | Aomori | AO |   |  
  | Japan | Chiba | CH |   |  
  | Japan | Ehime | EH |   |  
  | Japan | Fukui | FI |   |  
  | Japan | Fukuoka | FA |   |  
  | Japan | Gifu | GI |   |  
  | Japan | Gunma | GU |   |  
  | Japan | Hiroshima | HI |   |  
  | Japan | Hokkaido | HO |   |  
  | Japan | Hyogo | HY |   |  
  | Japan | Ibaraki | IB |   |  
  | Japan | Ishikawa | IS |   |  
  | Japan | Iwate | IW |   |  
  | Japan | Kagawa | KAG |   |  
  | Japan | Kanagawa | KAN |   |  
  | Japan | Kochi | KO |   |  
  | Japan | Kumamoto | KU |   |  
  | Japan | Kyoto | KY |   |  
  | Japan | Mie | MIE |   |  
  | Japan | Miyagi | MIGI |   |  
  | Japan | Miyazaki | MIKI |   |  
  | Japan | Nagano | NAO |   |  
  | Japan | Nagasaki | NAKI |   |  
  | Japan | Nara | NARA |   |  
  | Japan | Niigata | NI |   |  
  | Japan | Oita | OI |   |  
  | Japan | Okayama | OKA |   |  
  | Japan | Okinawa | OKI |   |  
  | Japan | Osaka | OS |   |  
  | Japan | Saga | SAGA |   |  
  | Japan | Saitama | SAIT |   |  
  | Japan | Shiga | SHGA |   |  
  | Japan | Shimane | SHNE |   |  
  | Japan | Shizuoka | SHKA |   |  
  | Japan | Tochigi | TOCH |   |  
  | Japan | Tokushima | TOKU |   |  
  | Japan | Tokyo | TOKY |   |  
  | Japan | Tottori | TOTT |   |  
  | Japan | Toyama | TOY |   |  
  | Japan | Wakayama | WAK |   |  
  | Japan | Yamagata | YATA |   |  
  | Japan | Yamaguchi | YAGU |   |  
  | Japan | Yamanashi | YANA |   |

**Comment by Dirty-Butter** [comment]
Seems like there should be a better way for me to give it to you.

**Comment by abrookbanks** [comment]
Thank you. No that's perfect with a find and replace using an editor

**Comment by Dirty-Butter** [comment]
Good - glad to help.

**Comment by abrookbanks** [comment]
Thank you. I've added this to install only and not upgrade as the countries may have been edited or removed. If you want to add then (and assuming your country ID's match us). Please run the following SQL command;

```
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 10, `name` = 'Catamarca', `abbrev` = 'CT'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 10, `name` = 'Chaco', `abbrev` = 'CC'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 10, `name` = 'Chubut', `abbrev` = 'CH'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 10, `name` = 'Ciudad de Buenos Aires', `abbrev` = 'DF'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 10, `name` = 'Corrientes', `abbrev` = 'CN'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 10, `name` = 'Córdoba', `abbrev` = 'CB'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 10, `name` = 'Entre Ríos', `abbrev` = 'ER'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 10, `name` = 'Formosa', `abbrev` = 'FM'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 10, `name` = 'Jujuy', `abbrev` = 'JY'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 10, `name` = 'La Pampa', `abbrev` = 'LP'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 10, `name` = 'La Rioja', `abbrev` = 'LR'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 10, `name` = 'Mendoza', `abbrev` = 'MZ'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 10, `name` = 'Misiones', `abbrev` = 'MN'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 10, `name` = 'Neuquén', `abbrev` = 'NQ'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 10, `name` = 'Río Negro', `abbrev` = 'RN'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 10, `name` = 'Salta', `abbrev` = 'SA'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 10, `name` = 'San Juan', `abbrev` = 'SJ'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 10, `name` = 'San Luis', `abbrev` = 'SL'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 10, `name` = 'Santa Cruz', `abbrev` = 'SC'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 10, `name` = 'Santa Fe', `abbrev` = 'SF'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 10, `name` = 'Santiago del Estero', `abbrev` = 'SE'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 10, `name` = 'Tierra del Fuego', `abbrev` = 'TF'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 10, `name` = 'Tucumán', `abbrev` = 'TM'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Acre', `abbrev` = 'AC'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Alagoas', `abbrev` = 'AL'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Amapá', `abbrev` = 'AP'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Amazonas', `abbrev` = 'AM'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Bahia', `abbrev` = 'BA'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Ceará', `abbrev` = 'CE'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Distrito Federal', `abbrev` = 'DF'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Espírito Santo', `abbrev` = 'ES'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Goiás', `abbrev` = 'GO'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Maranhão', `abbrev` = 'MA'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Mato Grosso', `abbrev` = 'MT'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Mato Grosso do Sul', `abbrev` = 'MS'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Minas Gerais', `abbrev` = 'MG'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Paraná', `abbrev` = 'PR'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Paraíba', `abbrev` = 'PB'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Pará', `abbrev` = 'PA'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Pemambuco', `abbrev` = 'PE'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Piauí', `abbrev` = 'PI'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Rio Grande do Norte', `abbrev` = 'RN'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Rio Grande do Sul', `abbrev` = 'RS'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Rio de Janeiro', `abbrev` = 'RJ'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Rondônia', `abbrev` = 'RO'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Roraima', `abbrev` = 'RR'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Santa Catarina', `abbrev` = 'SC'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Sergipe', `abbrev` = 'SE'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'São Paulo', `abbrev` = 'SP'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 30, `name` = 'Tocatins', `abbrev` = 'TO'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Andaman and Nicobar Islands', `abbrev` = 'INAN'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Andhra Pradesh', `abbrev` = 'INAP'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Arunachal Pradesh', `abbrev` = 'INAR'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Assam', `abbrev` = 'INAS'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Bihar', `abbrev` = 'INBR'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Chandigarh', `abbrev` = 'INCH'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Chhattisgarh', `abbrev` = 'INCT'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Dadra and Nagar Haveli', `abbrev` = 'INDN'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Daman and Diu', `abbrev` = 'INDD'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Delhi', `abbrev` = 'INDL'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Goa', `abbrev` = 'INGA'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Gujarat', `abbrev` = 'INGJ'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Haryana', `abbrev` = 'INHR'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Himachal Pradesh', `abbrev` = 'INHP'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Jammu and Kashmir', `abbrev` = 'INJK'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Jharkhand', `abbrev` = 'INJH'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Karnataka', `abbrev` = 'INKA'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Kerala', `abbrev` = 'INKL'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Lakshadweep', `abbrev` = 'INLD'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Madhya Pradesh', `abbrev` = 'INMP'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Maharashtra', `abbrev` = 'INMH'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Manipur', `abbrev` = 'INMN'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Meghalaya', `abbrev` = 'INML'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Mizoram', `abbrev` = 'INMZ'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Nagaland', `abbrev` = 'INNL'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Odisha', `abbrev` = 'INOR'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Puducherry', `abbrev` = 'INPY'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Punjab', `abbrev` = 'INPB'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Rajasthan', `abbrev` = 'INRJ'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Sikkim', `abbrev` = 'INSK'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Tamil Nadu', `abbrev` = 'INTN'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Telangana', `abbrev` = 'INTG'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Tripura', `abbrev` = 'INTR'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Uttar Pradesh', `abbrev` = 'INUP'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'West Bengal', `abbrev` = 'INWB'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Aichi', `abbrev` = 'AI'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Akita', `abbrev` = 'AK'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Aomori', `abbrev` = 'AO'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Chiba', `abbrev` = 'CH'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Ehime', `abbrev` = 'EH'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Fukui', `abbrev` = 'FI'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Fukuoka', `abbrev` = 'FA'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Gifu', `abbrev` = 'GI'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Gunma', `abbrev` = 'GU'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Hiroshima', `abbrev` = 'HI'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Hokkaido', `abbrev` = 'HO'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Hyogo', `abbrev` = 'HY'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Ibaraki', `abbrev` = 'IB'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Ishikawa', `abbrev` = 'IS'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Iwate', `abbrev` = 'IW'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Kagawa', `abbrev` = 'KAG'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Kanagawa', `abbrev` = 'KAN'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Kochi', `abbrev` = 'KO'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Kumamoto', `abbrev` = 'KU'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Kyoto', `abbrev` = 'KY'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Mie', `abbrev` = 'MIE'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Miyagi', `abbrev` = 'MIGI'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Miyazaki', `abbrev` = 'MIKI'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Nagano', `abbrev` = 'NAO'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Nagasaki', `abbrev` = 'NAKI'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Nara', `abbrev` = 'NARA'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Niigata', `abbrev` = 'NI'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Oita', `abbrev` = 'OI'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Okayama', `abbrev` = 'OKA'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Okinawa', `abbrev` = 'OKI'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Osaka', `abbrev` = 'OS'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Saga', `abbrev` = 'SAGA'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Saitama', `abbrev` = 'SAIT'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Shiga', `abbrev` = 'SHGA'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Shimane', `abbrev` = 'SHNE'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Shizuoka', `abbrev` = 'SHKA'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Tochigi', `abbrev` = 'TOCH'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Tokushima', `abbrev` = 'TOKU'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Tokyo', `abbrev` = 'TOKY'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Tottori', `abbrev` = 'TOTT'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Toyama', `abbrev` = 'TOY'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Wakayama', `abbrev` = 'WAK'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Yamagata', `abbrev` = 'YATA'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Yamaguchi', `abbrev` = 'YAGU'; #EOQ
INSERT INTO `CubeCart_geo_zone` SET `country_id` = 99, `name` = 'Yamanashi', `abbrev` = 'YANA'; #EOQ
```

**Comment by abrookbanks** [comment]
How do we delivery to Brazilian Favelas?

**Comment by abrookbanks** [comment]
Maybe with this.. https://what3words.com

**Comment by Dirty-Butter** [comment]
I'm confused. The addition of Japan zones using the database install query from 6.2.+ did not work. India and Brazil did.  From what I can decipher in the query - they are missing.

**Comment by Dirty-Butter** [comment]
Found it! The country ID for Japan is the same as India's - 99.

**Comment by abrookbanks** [comment]
Whoops!!! I'll get it fixed.

**Comment by abrookbanks** [comment]
Thanks Rosemary.
