### ISSUE TITLE
Question - Update Error

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#2019]
I am running 6.1.15 on 1 site and 6.2.0 on another.

As of last week, I no longer receive version update/info on both sites.

Also when I go to Maintenance I get "Failed to look up latest version" message.

I ask is this a Cubecart issue, ie the update server is down or have I done something causing this issue?

The only thing I have done is disable updates on various plugins that I have made custom changes (some purchased others free).  I no longer require the updates for these as they will overwrite my changes.

**Comment by abrookbanks** [comment]
Please contact support if you need us to look into this. It's not a known issue and from my tests works fine in all versions of CubeCart.

**Comment by sumwonlost** [comment]
I found issue.

The problem does not occur when using php 5.6.63 and when I go back to this version, all is ok.

The problem occurs when I upgrade to php 7.1.17.

**** Edit to above
This is not case.  I went back to php 5.6.63 - all then worked correctly.
I then went to php 7.1.17 and all working correctly now.

Must of been a minor glitch.

I will update you if it occurs again
