### ISSUE TITLE
Hide SMTP settings if mail() is chosen

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2023]
This will prevent confusion with noobs.

**Comment by havenswift-hosting** [comment]
Why not remove PHP mail() as an option and then there is no confusion - most hosting companies disable PHP mail() anyway due to the big security issues with it.  SMTP is also a much more reliable way of sending and having emails actually delivered

**Comment by abrookbanks** [comment]
Vast majority of CubeCart stores are using mail().

**Comment by abrookbanks** [comment]
Also many, many hosts block external SMTP connections in their firewall.
