### ISSUE TITLE
Cache folder with half a million files???

### ISSUE THREAD

**Issue by andysarcade** [cubecart/v6#2026]
hi..

Yesterday my hosting company told me i have over 300,000 files in the cache folder and that i needed to address it promptly, i went to try and delete by ftp but couldn't get a file list cos the folder is so huge... I then got distracted.. today they say there's over 500,000 files in there and they're threatening to pull my package if i dont get it under control..

Is this a leak somewhere in the software? I have the latest version of cubecart, and i went to use the 'clear cache' option in the admin menu, got endless spinning wheels, the store software eventually 504'd out and then came back up. i still can't view the folder over ftp, still too many files...

any ideas?

**Comment by abrookbanks** [comment]
Which cache folder?
/cache or /images/cache

Can you let us know how many product and categories you have?

**Comment by abrookbanks** [comment]
I haven't seen any other store with this issue. If you can open a sales ticket (no support needed) with FTP access we will investigate this for you. 
https://support.cubecart.com/Tickets/Submit

**Comment by andysarcade** [comment]
What should the permissions be set for on the cache folder? I wondered if these were wrong and cubecart can't clean up as it goes is a problem?

**Comment by abrookbanks** [comment]
I don't think that is relevant.

**Comment by abrookbanks** [comment]
How many products and categories do you have?

**Comment by abrookbanks** [comment]
Have you tried a different cache method?
https://support.cubecart.com/Knowledgebase/Article/View/235/41/how-do-i-enable-apc-memcached-redis-or-xcache

**Comment by andysarcade** [comment]
880 products, 89 categories... I have not tried the other cache methods, did you see my email about the FTP details..?

**Comment by abrookbanks** [comment]
Please delete the cache folder via SSH or ask the hosting company to do it. Once done create the folder again and keep an eye on it.
