### ISSUE TITLE
SEO May Cause Warning

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2033]
See: https://forums.cubecart.com/topic/53997-keep-getting-this-php-warning/

If a plugin is disabled/uninstalled, its **seo path** would still remain in `CubeCart_seo_urls`. It will be fetched in a query in `SEO->getItem()`.

Then, when that data is passed to `SEO->_getItemVars()`, there is no code there to return a set but empty array.

Back at `SEO->getItem()`, PHP will issue a warning regarding `array_merge($item_vars, $_GET)`.

A comment at http://docs.php.net/manual/en/function.array-merge.php states that the result will be `null`.

So, it seems that `$_GET` will get trashed.

**Comment by abrookbanks** [comment]
Thanks for this.

**Comment by bhsmither** [comment]
I disagree with this solution.

The `switch()` will happen. Therefore, the `default` could happen.

As such, whatever the hook tried to catch is now clobbered.

Suggest above the hook, `$array = array();` which allows for the hook to assign to $array what it needs to, the `switch()` will do it's thing if appropriate, and we still return a zero-element array if nothing gets caught.

**Comment by abrookbanks** [comment]
Ok thanks I'll look again.

**Comment by abrookbanks** [comment]
Totally agree. I missed that. :)
