### ISSUE TITLE
stock levels dont change

### ISSUE THREAD

**Issue by hershbergj** [cubecart/v6#2036]
Stock levels don't decrease after customers order is placed after upgrade to 6.2.0-b1.
settings are "when payment has been made"
also stock levels don't change when changing quantities on the product page as well.
did through the maintenence panel a repair of product inventory but it did not find anything.
Please help!

**Comment by abrookbanks** [comment]
Fixed with 9ab975105a891e26867eb7f7c2a9b253cd084a19
