### ISSUE TITLE
Smarty Combine to Honor CubeCart Debug Mode

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2037]
Suggest:
```
{combine input=$css_input output='cache/css.{$SKIN_FOLDER}.css' age='604800' debug=$CONFIG.debug||!$CONFIG.cache}
```
Same for javascript.

**Comment by abrookbanks** [comment]
Thanks. I had planned to do this so it must have escaped my mind. :)

**Comment by abrookbanks** [comment]
Your solution is spot on. Thanks as always. :)

**Comment by abrookbanks** [comment]
We could think about a setting for the combine age maybe. 
`age='604800'`

**Comment by abrookbanks** [comment]
But I'm not a big fan of settings.
