### ISSUE TITLE
Address issues for guest checkout

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2038]
- unregistered customers: 
If you go under their address book, you will see that their billing address is missing if the billing and the delivery are the same.
If the billing and the delivery are different, both are listed in the address book, no problem there.

This does not affect the orders where I can see both prefectly. It is only under the customer's address book the issue.

- registered customers:
Not a critical issue but again under the customer's address book I noticed that the header "default billing address" is now called "Billing/Delivery address", normal ?

**Comment by Dirty-Butter** [comment]
This is what I'm STILL seeing, even though the choice is pre-checked for billing and delivery to be the same. My only way around it is to fill out the separate Billing address. after the pre-checked same box does not work for me. I have this same issue on 3 test sites now. It's driving me crazy double checking files with no sign of anything but cosmetic differences. I do require creating an account, but the same thing happens either way - either guest option or registered only. Screenshot shows that what SHOULD have been the initial Contact information for Billing is being databased as the Default Delivery address.
![billingdeliveryaddressissue2](https://user-images.githubusercontent.com/6146505/40249732-891c2f0c-5a99-11e8-9a53-5333f028e00a.png)

**Comment by SemperFiWS** [comment]
I have encountered something similar to this.

In checkout, for unregistered customers, it appears to drop the state selection that was made.

Then when you look at the address book entries:
- the billing address is set to 0
- nothing is set in the state field

**Comment by Dirty-Butter** [comment]
THANK YOU!!! It's working on the two sites I've tried so far. I really appreciate your patience with me. LATER on when you have the time, I'd like to know what the difference was in your setup and mine that caused you to not be able to reproduce it for so long. Did it have anything to do with you being on the default language and me using US?  A difference in servers or php version?
