### ISSUE TITLE
Price Error when using product options.

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#204]
This applies to both dynamic price updates as well as the actual price of the item in the basket.

Steps to reproduce:

1) Create a new product with a price of £30

2)  Setup a global sales discount of 30% for all products

3) Assign a new product option to the product with a +5 cost

The price for the base product shows correctly.
£30 / 0.7 = £21

When you add your option which is +5 it should be.
£30 / 0.7 = £21
+
£5 / 0.7 = £3.50

£21 + 3.50 = £24.50

But, the cart actually does £21 + £5 and charges £26 total.

The same issue also exists in CubeCart 5.

**Comment by abrookbanks** [comment]
Fixed with commit https://github.com/cubecart/v6/commit/de248733d82a5086759e8959218d262be564b5f3
