### ISSUE TITLE
Assumption of Available Data

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2040]
In `Order->getOrderDetails()`, it is assumed that `_getInventory()` has already been called.

The `getOrderDetails()` is public, yet `_getInventory()` is private. The only place `_getInventory()` is called is in `Order->orderStatus()`.

Suggest in `getOrderDetails()`, to have this:
```
$order_summary = $this->getSummary($order_id);
$this->_getInventory($order_id);
```

Suggest in `orderStatus()`, instead of this:
```
// Retrieve order details
$this->getSummary($order_id);
$this->_getInventory($order_id);
(six lines later)
$this->getOrderDetails($order_id);
```
to have just this:
```
// Retrieve order details
$this->getOrderDetails($order_id);
```

**Comment by abrookbanks** [comment]
Thank you. From my testing this is working well.
