### ISSUE TITLE
Cookie Dialogue ISSUE with 05/21/18 commit

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#2041]
As of 05/20/18 commit - I cannot access the login screen for admin in a normal way. If I go to the url, the page crashes (not even the CC login box). But I can access the storefront. I did not click anything yet about accepting or denying cookies.  I can immediately go back and access the admin dashboard normally. This strange behavior is occurring on a 100% stock site and with a test site with my edited files. I turned on Safe Mode on both sites and get the same odd behavior. I manually cleared all caches before testing. Surely this is cookie related in some way????

FYI I was still having the odd Billing/Delivery address issue that YOU were not seeing on stock - hoping something in the latest commit would have fixed that HA!

**Comment by Dirty-Butter** [comment]
Also, previous commit was on 05/18/18.

**Comment by Dirty-Butter** [comment]
I've narrowed it down to the cookie dialogue. If the use of the Cookie Dialogue is disabled in admin then admin loads as expected.

If Cookie Dialogue is enabled the workaround of going to storefront first and then admin in order to access admin is the only thing that "works".  I decoded the config in phpMyAdmin and changed the Cookie Dialogue choice to "0", encoded again and replaced in the table. With that done, I can now login to Admin normally.

The wording issue turned out to be my fault, so please disregard the error message section below.

But the wording of the dialogue does NOT show on the top of the storefront - only the buttons - and this is the error message: [21-May-2018 15:33:15 America/Chicago] PHP Warning:  str_replace() expects at least 3 parameters, 2 given in /home/XXXX/classes/gui.class.php on line 913

**Comment by abrookbanks** [comment]
Thanks for this Rosemary. I'll close this as I am still working on this area and keep your findings in my mind.

**Comment by mike4kz** [comment]
I keep getting messages for gui.class.php:915, that "it expects 3 parameters". The line really has two parameters, perhaps parenthesis missing between functions?

**Comment by havenswift-hosting** [comment]
Still also commonly seeing this across multiple sites
