### ISSUE TITLE
Can't change default mail template

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2042]
verified in two stores on 6.2

After pressing save the newly selected template becomes deselected and the chosen template is once again Default. aka, changes are not saved :)

**Comment by bhsmither** [comment]
This goes back quite a few versions. Probably all the way back to CC6.1.0.

It has to do with the filetree plugin code, starting near line 360.

**Comment by bhsmither** [comment]
I made a comment on #476, fourth entry. Also, #1285 discusses this.

Work-around: uncheck existing first, then check what you want. Save.

**Comment by abrookbanks** [comment]
![screen shot 2018-06-08 at 14 43 12](https://user-images.githubusercontent.com/4520803/41161300-49b421c0-6b2a-11e8-8f6f-3ee48e392afc.png)
