### ISSUE TITLE
mcrypt deprecated in PHP7.1 and removed in 7.2

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2043]
As above and this is used in at least the SagePay gateway plugin which means it doesnt work under 7.2

**Comment by havenswift-hosting** [comment]
mcrypt relies on libmcrypt which is dead and has been unmaintained since 2007 
 - see http://php.net/manual/en/intro.mcrypt.php

This needs to be rewritten to use openssl_encrypt

**Comment by abrookbanks** [comment]
Cool thanks for the heads up.

**Comment by abrookbanks** [comment]
Fixed with 1.0.7 release. From my testing it works fine.

**Comment by havenswift-hosting** [comment]
A client has tested this and now orders are not being moved from Pending to Processing and when looking at the transaction log for the order, the transaction ID is blank and the status is set to Not Available

**Comment by abrookbanks** [comment]
Yeah. I'm going to pull this version.

**Comment by abrookbanks** [comment]
I really need to make progress on this. So far everything I have tried has failed.

**Comment by abrookbanks** [comment]
Ok I think I got it. It's encrypting and decrypting successfully with openssl the only potential issues is SagePay understanding it as the PKCS5 padding may or may not be required. 

I don't have a SagePay test account.

**Comment by abrookbanks** [comment]
Closing for now.

**Comment by abrookbanks** [comment]
Relates to #2113

**Comment by sumwonlost** [comment]
Also CardCapture plugin not working

**Comment by abrookbanks** [comment]
The card capture plugin at the latest version with the latest version of CubeCart is coded to use OpenSSL instead of Mcrypt.

**Comment by abrookbanks** [comment]
This is relevant but should be in 6.2.5:
https://github.com/cubecart/v6/commit/5d4ac244673ef646911e733a8ad6ea71b75be517#diff-310c014724437648134a1d0f52066cae
