### ISSUE TITLE
6.1.14 - Loading... not showing for More button click on Chrome/Safari

### ISSUE THREAD

**Issue by jasehead** [cubecart/v6#2044]
With Firefox, clicking the More button to load more products shows Loading with an icon spinner - as expected.

With Chrome and Safari (webkit browsers) there is no change, just a long pause while the user stares at the More button wondering if anything is going to happen... (no loading text or spinner)... and then the next page of images loads.

Related files are:
- /skins/foundation/js/2.cubecart.js (search for "loading")
- /skins/foundation/templates/content.category.php (last two divs - ccScrollCat has the More button and lang_loading has the loading text)

This was discussed on the Forums but no one tested browsers for quirks:
[https://forums.cubecart.com/topic/52183-loading-does-not-work-in-foundation-614/](https://forums.cubecart.com/topic/52183-loading-does-not-work-in-foundation-614/)

BTW - the loading spinner WAS working in 6.0.12, so maybe there was a code change.

This Foundation loading button works on Chrome, Safari and Firefox and parts might be adaptable for the More button in Cubecart:
[https://foundation.zurb.com/building-blocks/blocks/ecommerce-loading-button.html](https://foundation.zurb.com/building-blocks/blocks/ecommerce-loading-button.html)

**Comment by jasehead** [comment]
Found it - in 2.cubecart.js search for:
async: false,

This was not in 6.0.12, and commenting out this line allows the Loading text to show.  However, the loading spinner SVG is not animated (tested on Chrome, Safari and Firefox).

// async: false, // comment out if More button does not change to Loading...

**Comment by jasehead** [comment]
Still having trouble getting #icon-spinner animated when loading more results.

**Comment by jasehead** [comment]
Related - the icon spinner for transferring to a payment gateway is also not spinning.  However, if I stop the page loading it begins to spin.

**Comment by abrookbanks** [comment]
I can't see any relevant code changes between 6.1.12 and 6.1.14 annoyingly. I'll have a good look at this today.

**Comment by jasehead** [comment]
I referred to 6.0.12.  My workaround was to comment out async: false in 2.cubecart.js, and also to hardcode the style in the same file - so AFTER this:

`var next_link = $('a.ccScroll-next');`

my line is now

`var loadingHtml = '<p class="text-center" id="loading"><svg class="icon" style="-webkit-animation: spinner 1s infinite steps(8); animation: spinner 1s infinite steps(8);"><use xlink:href="#icon-spinner"></use></svg> ' + $('#lang_loading').text() + '&hellip;<p>';`

Because that hack seems to be working for me, I think the issue could be css priority.

**Comment by abrookbanks** [comment]
Sorted! :)

**Comment by jasehead** [comment]
#Icon-spinner is also used in foundation/templates/content.gateway.php for transfer to gateway (6.1.14):
`<p><svg class="icon icon-submit"><use xlink:href="#icon-spinner"></use></svg></p>`

**Comment by abrookbanks** [comment]
Should still work but I'll test it on Monday.

**Comment by abrookbanks** [comment]
Yes works fine just a bit small. I made it bigger..
