### ISSUE TITLE
Bugs - Countries/Zones

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#2045]
Goto Admin -> Countries/Zones

BUG - at the bottom "Select With" options are wrong. These should be:
Disabe
Enable (County Required)
Enable (County Optional)
Enable (County Disabled)
Delete

Now Disable ALL then Enable (County Disabled) for Australia,  Enable (County Required) for UK,  Enable (County Optional) for US so we test for BUGS.

Login as Customer then ADD/EDIT ADDRESS - Addressbook
The Country Dropdown work correctly as it does not display (Disabled - status = 0).
The BUG occurs in Zone (County)  

If Country (UK) - Enable (County Required)  - Status = 1.
     It display Zone/County field (required) and correct if no active zones exist.

     I have active Zones for UK therefore the dropdown should display with active zones.
     The first option should be "Select County (Required)"
     The last option should be "Other County" -  When "Other County" is selected the dropdown is 
     replaced with a textbox.  The placeholder "Required".  After the textbox you need an icon with on 
     click it toggle back to dropdown.
     
If Country (US) - Enable (County Optional) - Status = 2
     It display Zone/County field (required) - BUG it should be optional and not required if no active 
     zones exist.

     I have active Zones for USA therefore the dropdown should display with active zones.
     The first option should be "Select County (Optional)"
     The last option should be "Other County"  -  When "Other County" is selected the dropdown is 
     replaced with a textbox.  The placeholder "Optional".  After the textbox you need an icon with on 
     click it toggle back to dropdown.

If Country (Australia) - Enable (County Disabled) - Status = 3

     It display Zone/County field (required) - BUG.  I have  County Disabled so this field should not be 
     displayed or it should be disabled (user cannot enter data).

In Admin, Store Address, Customer Addresses (add/edit) and Orders (create/edit) Billing and Delivery Addresses (add/edit) should all work the same as outlined.

**Comment by sumwonlost** [comment]
Ref #1720

With above fixes, the last thing remaining.  On submit if new Zone, it adds record in zones table (status=2) and create Note to Administrator that new Zone has been Added with details for Administrator to confirm/update details.  

In Admin -> Countries/Zones -> Zones it require a dropdown for Status instead of checkbox.  The dropdown options for each Zone (County) are:

Disabled = 0
Active = 1
Pending = 2

Administrator verifies new Zone and adds/edits missing details and change status to Active.

**Comment by sumwonlost** [comment]
Whilst on Zones page, can you add a Search dropdown at top of page.

The dropdown populate with Countries (irrespective of status) that have Zones.  When I select a Country it populate the page table with the Zones for selected Country instead of ALL Zones.

**Comment by abrookbanks** [comment]
Thanks for the bug report. I believe you had already posted these feature requests which we may be able to add in the future.
