### ISSUE TITLE
ReCaptcha Could be Forced Off

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2047]
See:
https://forums.cubecart.com/topic/54025-re-captcha-keeps-switching-off/

I have not verified this as I do not yet have the utility to create custom POST requests.

**Comment by bhsmither** [comment]
Confirmed.
Using Postman (www.getpostman.com), I constructed a custom POST request. ReCaptcha switched off as described in the forum conversation.

This experiment was performed on CC620, but may also apply to CC6115.

**Comment by abrookbanks** [comment]
I think this is fixed as a result of https://github.com/cubecart/v6/issues/2030

**Comment by bhsmither** [comment]
The same for the CC6.1 series?

**Comment by abrookbanks** [comment]
It only affects 6.2.0.
