### ISSUE TITLE
Coding Standards Against PHP 7.1+

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2049]
See: http://docs.php.net/manual/en/language.types.array.php
Creating/modifying with square bracket syntax

> Note: As of PHP 7.1.0, applying the empty index operator on a string throws a fatal error. Formerly, the string was silently converted to an array.

So, code that looks like:
```
$arrListOfStrings = array();
$arrListOfStringType[] = $strItem; // Fails
$arrListOfStringType[] = array($strItem;) // Works
array_push($arrListOfStringType,$strItem;) // Works
```
Edit:
This is so strange. The docs say this isn't supposed to work, and I see error messages in this regard, but elsewhere, statements that should fail don't.

**Comment by abrookbanks** [comment]
Odd! Thanks for sharing. I can't sift thought the code trying to figure out where to change this as it will take an eternity but lets keep it in mind.
