### ISSUE TITLE
SQL Cache Hits

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#205]
With caching disabled, I see dozens of queries in the debug section. All but a few are green [CACHED].

Enabled, I see just a dozen plus, and all but a few are green [CACHED].

What I cannot tell is if these are cache reads/hits or queries written to the cache. If written, maybe a color not green -- red/purple, perhaps?

And if written, when cache is disabled, obviously the queries are **not** being cached.

Some time ago I suggested all queries be listed, with (green)[Cache Read] and (red)[Cache Write] indicators.

So... Enhancement?

**Comment by abrookbanks** [comment]
There are STILL cache issues. It's partially working but some empty queries are still being executed... 

I'll try to do this at the same time. It's a really complex area..

**Comment by abrookbanks** [comment]
This issue has completely consumed me. I've got the cache showing the state which is colour coded. You'll see some orange ones. which are not being read from cache after write. This is proving a monumental headache.

![screen shot 2015-02-18 at 08 49 41](https://cloud.githubusercontent.com/assets/4520803/6244424/404cfb66-b74b-11e4-81ca-d18e6974f7f8.png)

**Comment by abrookbanks** [comment]
Finally resolved this. It was a *fr!ck!n* nightmare but runs beautifully now.

**Comment by abrookbanks** [comment]
# Homepage First Load
Black queries are never cached. Orange ones are written  to cache on that page load (CACHE WRITE)
![home_first_load](https://cloud.githubusercontent.com/assets/4520803/6246057/b2aa4a40-b75c-11e4-9af3-01e52f5e3cb7.png)

# Homepage Second Load (No
Green queries are read from cache without SQL query (CACHE READ)
![home_second_load](https://cloud.githubusercontent.com/assets/4520803/6246060/b63405f2-b75c-11e4-962c-edb385af46da.png)
