### ISSUE TITLE
What does "Global percentage discount" do? Is it Bug?

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#2050]
Definition - Global discount percentage: Enter a percentage here to reduce all standard pricing by the entered amount. This overrides the individual product sales prices.

Admin -> Settings -> Features - in Global percentage discount, I enter 10% and save.

Now what does this do?  It does not display prices (discounted) anywhere on site.  Not in any boxes (Featured, Popular, On Sale), nor Products, nor Checkout,

It seems to do nothing, so what is it's purpose?

I assumed by its definition that ALL products would be discounted by the nominated percentage (10%) and displayed.  If this is what it is supposed to do, it isn't doing it.

A better option than applying the discount to ALL products is to apply it to individual products.

Admin -> Products - Add Product/Select Product -> Pricing.
Here you need "Apply Global percentage discount" checkbox.  If checked it apply the % rate else it does not if unchecked.

**Comment by Dirty-Butter** [comment]
My store is very heavily edited, so it may be something I did to the skin - but I have https://dirtybutterestates.com on global percentage sale and the prices are marked the same way on the storefront as they would be if only individual products were on sale. I'm on the latest commit of 6.2 on that store, so it could also be that this has been fixed in 6.2+ code.

**Comment by sumwonlost** [comment]
I am using 6.2.0 and my skin has also been heavily edited, I always refer to foundation skin when upgrading my skin.  This does not work in foundation skin. 

I did download the latest commit last week however after upgrade it would not load admin screen, I tried 2 times before reverting back to 6.2.0 so i decided to wait for official release.

**Comment by Dirty-Butter** [comment]
I have a work around for the commit not loading admin screen. https://github.com/cubecart/v6/issues/2041 But I'm having a major issue with the Billing/Delivery during checkout, so it's not ready for live site yet. The estates store is live, but we don't get customers any more - I keep it as my last testing step before upgrading our "real" store.

**Comment by sumwonlost** [comment]
I have been developing my site for past 6-8 months with due date to go live Feb next year.

My skin originally started out as e-tone but has been heavily modified, the only thing of the original is the 3 column layout and parts of the navigation menu.

With each CubeCart upgrade, I look at foundation skin and find new changes from previous version then add/edit/delete the changes into my skin.  But I always check to see how these work in foundation skin.  If they don't work (bugs) in foundation skin, they are not going to work in mine.  Therefore any bugs I report are tested in foundation skin.

Have you tried switching to foundation skin and seeing if these work?

**Comment by Dirty-Butter** [comment]
Yes, I have one test site that is 100% stock code. The workaround with the cookies works for me. I can access my 6.2+ sites either by turning off the cookie notice or going to storefront before going to admin.

**Comment by sumwonlost** [comment]
Ok.  Switch to foundation skin, are prices displayed with or without Global percentage discount taken into account.

**Comment by bhsmither** [comment]
In admin, after making an adjustment to global discount rate and saving, please note if a button at the upper-right of the window is lit - "Clear Cache".

If so, click that button. Examine the pricing on the storefront.

**Comment by Dirty-Butter** [comment]
Yes, with Global, the regular price is crossed out and the sale price shows next to it, just as it should. Hopefully Bsmither hit on your issue and it's a cache clearing problem.

**Comment by havenswift-hosting** [comment]
Just FYI - this type of question should really be put on the forums and not as a github issue until / unless it is proved it is a bug and is reproducible - let's keep Al's workload down as much as possible as he has enough on his plate right now !

**Comment by sumwonlost** [comment]
If only it was as simple as clearing the cache.

I officially declare it a bug then.  I have just done a clean virginal install (6.2.0b) as downloaded from Cubecart.  The only changes I made are as follows.

1.  Added 10% to Global percentage discount.  This did not work.  So I went to step 2.
2.  Entered 0 for Sale Price for Test Product.  This still did not do anything other than remove the sale price.

Am I missing something as I don't think it is dependant/reliant on anything else.

I am using php 7.1.17 and does not work also when I change to 5.6.xx, so that is not issue.

**Comment by bhsmither** [comment]
Just checking... In admin, Store Settings, Features tab:

You entered a value in the "Global percantage discount" text entry field.

Did you also set the "Sales Mode" drop-down selector to 'Global percentage discount'.

**Comment by sumwonlost** [comment]
Sorry everybody, I feel like a goose, thank you for your help.  I found the issue.

I assumed I only had to put the % in.  I had not realised I needed to change the mode from Sales to Global percentage discount in the dropdown above.  All working correctly.

Thanks bhsmithers, yes that was the issue as i just found it as you sent me your reply.
