### ISSUE TITLE
Abnormally high number of files in cache folder

### ISSUE THREAD

**Issue by andysarcade** [cubecart/v6#2051]
I've had my hosting package scripting switched off twice since they are reporting the cache folder has 250,000+ files (and growing) in it and it will affect server performance, they switch my scripting off until i fix it. 

I changed the caching method in global.inc.php to all of the other methods one by one and all resulted in errors on the main page, mostly looking for included files that aren't there... only 'file' works - but i've switched it off in store settings now.. the site works, but the dashboard is telling me cache is off and to switch it back on...

I have questions : what is a 'normal' amount of files in this folder, does it ever get flushed periodically? and lastly, why does no other method other than 'file' work when set in the global.inc.php ? Can anyone shed any light on why this is happening?

**Comment by bhsmither** [comment]
I have 3,000. ~~Many groups have identical contents, but different hashed filenames.~~ Stupid comment.

**Comment by bhsmither** [comment]
#2026 was closed (with presumably a "Could Not Duplicate" flag) and this effectively reopens that.
#2013 may have some complicity in this.

**Comment by bhsmither** [comment]
A "normal" amount is very dependent on how many products and categories are in your store. Somewhere in the ballpark would be 150 cache files per product.

**Comment by briansandall** [comment]
150 per product seems quite excessive; is that really necessary for performance? If so, perhaps the PHP / JS code should be profiled for bottlenecks (again?) to see what can be done there while easing off on the aggressive caching.

**Comment by bhsmither** [comment]
Again, how many unique queries are executed against the database per product varies. One can get a sense of this by viewing CubeCart's debug output. (I have about 200 cached queries when viewing the Test Product in a fresh install. Roughly 50 cached queries relate to processes not associated with showing the product.)

There is a trade-off, of course. Aggressive caching or aggressive database connectivity.

I will say - and have said - that queries should be more generalized. That is to say, a cached `SELECT *` instead of several cached `SELECT specific_list_of_columns`. Also, a single cached query `WHERE 'file_id' IN (1,2,3,4,5,6,7,8,9,10)` instead of a foreach loop having ten cached queries.

**Comment by andysarcade** [comment]
Products 880
Categories 89

Thats how my store is set up, and its been running fine for years, its only appeared recently, maybe after an upgrade possibly 1 or two versions ago ?

**Comment by andysarcade** [comment]
I have two entires in the error log : 
File: [catalogue.class.php] Line: [1874] "SELECT I.* FROM CubeCart_inventory AS I LEFT JOIN (SELECT product_id, MAX(price) as price, MAX(sale_price) as sale_price FROM CubeCart_pricing_group WHERE group_id = 0 GROUP BY product_id) as G ON G.product_id = I.product_id WHERE I.product_id IN (SELECT product_id FROM `CubeCart_category_index` as CI INNER JOIN CubeCart_category as C where CI.cat_id = C.cat_id AND C.status = 1) AND I.status = 1 AND ((I.use_stock_level = '0') OR (I.use_stock_level = '1' AND I.stock_level > 0)) AND (I.name RLIKE '[[:<:]]aEBu[[:>:]].*[[:<:]]))('("(.[[:>:]]' OR I.description RLIKE '[[:<:]]aEBu[[:>:]].*[[:<:]]))('("(.[[:>:]]' OR I.product_code RLIKE '[[:<:]]aEBu[[:>:]].*[[:<:]]))('("(.[[:>:]]') ORDER BY `name` ASC LIMIT 12 OFFSET 0 " - Got error 'unmatched parentheses at offset 27' from regexp
and:
File: [catalogue.class.php] Line: [1876] "SELECT I.* FROM CubeCart_inventory AS I LEFT JOIN (SELECT product_id, MAX(price) as price, MAX(sale_price) as sale_price FROM CubeCart_pricing_group WHERE group_id = 0 GROUP BY product_id) as G ON G.product_id = I.product_id WHERE I.product_id IN (SELECT product_id FROM `CubeCart_category_index` as CI INNER JOIN CubeCart_category as C where CI.cat_id = C.cat_id AND C.status = 1) AND I.status = 1 AND ((I.use_stock_level = '0') OR (I.use_stock_level = '1' AND I.stock_level > 0)) AND (I.name RLIKE '[[:<:]]aEBu[[:>:]].*[[:<:]]))('("(.[[:>:]]' OR I.description RLIKE '[[:<:]]aEBu[[:>:]].*[[:<:]]))('("(.[[:>:]]' OR I.product_code RLIKE '[[:<:]]aEBu[[:>:]].*[[:<:]]))('("(.[[:>:]]') " - Got error 'unmatched parentheses at offset 27' from regexp

**Comment by bhsmither** [comment]
The error log entries would be a different problem. Probably a visitor just randomly entering letters and other characters in the search box.

**Comment by andysarcade** [comment]
I had assumed they were unrelated but wanted to make sure for completeness.

**Comment by abrookbanks** [comment]
Closing as I don't think this can be resolved. Most linux systems should be able to handle massive folder contents. Alternatively it may be a good idea to [use a different cache system](https://support.cubecart.com/Knowledgebase/Article/View/235/41/how-do-i-enable-apc-memcached-redis-or-xcache).

**Comment by abrookbanks** [comment]
FINALLY found that there was an issue with caching unnecessary files. 

See: https://github.com/cubecart/v6/commit/c16efa14cfb25b57768f173354f8ebb925ab8114 (wrong issue id).

> //Cache the result **if needed**

**Comment by andysarcade** [comment]
this is good to know, i wonder if it will solve my issue!

Andrew Welburn
andys-arcade

**Comment by andysarcade** [comment]
Tried the code change, i still get one or two files per second created 
in the cache folder, so i have to keep caching switched off :(

Andrew Welburn
andys-arcade

**Comment by bhsmither** [comment]
Two files per second. I wonder if your site is getting hit hard by random searches.

CubeCart will cache the Catalogue->searchCatalogue query regardless if anything was found.

If you have access to your web server access log, please determine if you are getting hit hard with searches.

It would be interesting to diagnose this situation by adding more data to the cached query: the REQUEST_URI and the actual query.

In `file.class.php`, `write()`, `$meta` can have this data added for manual inspection later.

**Comment by bhsmither** [comment]
Having backported the code changes (respecting `$cache` argument) to CC621, cache writes have dropped significantly. Previously, cache write activity was higher than I thought reasonable, but the **number** of cache files grew well within expectations.

CubeCart was writing fresh copies (only the 'time' had been changed), overwriting existing same-named cache files.

**Comment by abrookbanks** [comment]
Maybe the search tool shouldn't cache or it should have flood control.
