### ISSUE TITLE
Sub-category links and images not visible on smallest screen sizes

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2052]
When viewing a category page on a mobile screen is in vertical orientation (horizontal orientation is fine), the clickable links and images of any sub-categories disappear

**Comment by abrookbanks** [comment]
This is by design as they can take up too much screen. The navigation will show subcategories and "show-for-medium-up" can be removed in the template if so desired.

**Comment by abrookbanks** [comment]
https://github.com/cubecart/v6/blob/6.2.0-branch/skins/foundation/templates/content.category.php#L24

**Comment by havenswift-hosting** [comment]
I understand it is by design but I (and quite a few clients) believe it is incorrect design. Yes of course it is easy to remove and I will make it a selectable option via our skin config plugin for our skins but many use Foundation as is.

1) It makes no sense and gives a horrible user experience to show sub-category images and links when a phone is horizontal but then not when turned vertical.

2) On category pages, product images are displayed in portrait mode on phones so why treat sub-category images any different ?

**Comment by abrookbanks** [comment]
OK from testing it still sits well. Thanks for arguing the case. :)

**Comment by havenswift-hosting** [comment]
YW and thanks ! Works well even with three sub-category images per row and gives a much better UX

**Comment by abrookbanks** [comment]
Thanks Ian. I'm back in the game now. We had a baby girl four days before
moving house!!! Omg. Probably my craziest week ever.... Pushing to get
6.2.1 out now. 👍🏻

**Comment by havenswift-hosting** [comment]
Congratulations to you both !

**Comment by abrookbanks** [comment]
Thanks Ian. I hope all is well in Spain.
