### ISSUE TITLE
Plugin Cookies Not blocked by default

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#2054]
AddThis _atuvc, _atuvs cookies are not effected by Cookie code. There are possibly other plugins, etc, this would apply to as well.

**Comment by Dirty-Butter** [comment]
Is there any way to code the google analytics so the "if  code" applies to any and all snippets/mods/plugins as wel?l Otherwise any that create/use cookies will need to be modified before they work properly with GDPR.

**Comment by abrookbanks** [comment]
I can't do anything about this. The developers need to code accordingly.
