### ISSUE TITLE
Pre-6.2 branches?

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#2055]
Looks like they've all been culled - any chance we could get some of them back?

I've got a store still on 6.1.14 that I'd like to update to the latest 6.1.x before moving up to 6.2.x, and having the branches available would make that job much simpler.

**Comment by bhsmither** [comment]
Go to <>Code. Click the Branch drop-down selector. Click Tags tab. Select v6.1.15. Download.

**Comment by bhsmither** [comment]
You can also get any and all versions from CubeCart's downloads page.

**Comment by abrookbanks** [comment]
I messed it up. I'm sorry. From the next release I'll get it back in shape.

**Comment by briansandall** [comment]
@bhsmither Ah, I see what you mean. The tags are still there, though the branches themselves are not. That'll work.
