### ISSUE TITLE
Extension Not Available

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2059]
This does not download (for me, anyway):
https://www.cubecart.com/extensions/download/106/AddThis-1.0.1.zip/manual

**Comment by Dirty-Butter** [comment]
It installed for me on a 6.1.15 store and on the latest 6.2+ commit. I tried the token way and downloaded and extracted it.

**Comment by bhsmither** [comment]
The /manual/ part is the manual download link (that is, **not** the lightning bolt).

Try that.

**Comment by Dirty-Butter** [comment]
I did download it as well as ttry he lightning bolt way. It downloaded as usual, and then I extracted it and took a look at the files. All looks fine to me.

**Comment by abrookbanks** [comment]
Works for me???!

**Comment by abrookbanks** [comment]
Closing until you tell me it still doesn't work. :)

**Comment by bhsmither** [comment]
Working fine today.

**Comment by abrookbanks** [comment]
Thanks for letting me know. Must be those Gremlins again!
