### ISSUE TITLE
Users Online May Show Confusing Data

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2061]
Edge Case (and not verified).

If an admin and a user is logged in, and using the same browser, even though using different cookies (to be confirmed), the Users Online table shows the User's name or "Guest", as opposed to the Admin's name, and no line item of where the User is at.

**Comment by bhsmither** [comment]
Using two different browsers (thus two different values for the same-named cookie), still shows "Guest" as the name of the logged in admin.

**Comment by abrookbanks** [comment]
It does show a separate session but "Is Admin?" has a check under it.

**Comment by abrookbanks** [comment]
Now it just shows front end online sessions. Makes much more sense.
