### ISSUE TITLE
Products per page setting

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2064]
What was the thinking behind making this setting deprecated and adding it into the skin config.xml and what are the plans for it ie will it stay deprecated forever or do you have plans to remove it. I think it would be much more flexible to revert this, so take it out of config.xml and restore this setting.  Any changes made to the config.xml file are over-written when a skin is upgraded.

An alternative, if you want to keep this, would be to change the word deprecated to something different (deprecated means you have specific plans to remove it in a stated future version) then third party skins can remove that section from their skins without admin users being put off from using that setting by that wording.

Even better would be a check to see which skin is selected and then an indication as to whether the setting is used or whether it uses the config.xml setting

**Comment by abrookbanks** [comment]
It's because it's more than just products per page. Agreed though, it would be better to have this as a feature. I'll stick this down as a feature request. Keen to get this done.
