### ISSUE TITLE
See #2017 Japan

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#2066]
setup query has wrong ID for Japan.

**Comment by Dirty-Butter** [comment]
You asked earlier in the thread about Brazil's Favelas. This is interesting: https://motherboard.vice.com/en_us/article/5395w3/the-mailman-mapping-brazils-largest-favela-by-hand

**Comment by abrookbanks** [comment]
Residents have to pay for the service. If they live in Favelas how will they have the money to pay for that? Seems odd to me. https://what3words.com/ is a better solution I think. 

I added the correct ID for Japan.

**Comment by abrookbanks** [comment]
See commit to #2017
