### ISSUE TITLE
Submitting an email address to the newsletter should optionally require recaptcha

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2067]
Although there is double opt-in, it would be useful to have a mechanism to reduce bots spamming lists with email addresses. It doesn't look like the newsletter signup process currently uses recaptcha, but it probably should.

Request raised on behalf of my customers who have requested this be changed.

**Comment by abrookbanks** [comment]
It does already. Invisible reCaptcha has a better UX.

![screen shot 2018-06-11 at 11 13 09](https://user-images.githubusercontent.com/4520803/41226144-814c70d4-6d68-11e8-80a1-c27bcd98c84b.png)
