### ISSUE TITLE
On image delete show image name in confirmation dialogue for clarity

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2070]
As above. Right now it just says "Are you sure you want to delete this?"

**Comment by claudia39** [comment]
We must be psychic Al.  I was deleting some photos this morning and thought how nice it would be if it showed the name just to be sure I deleted the right image!  Thanks for considering this.

**Comment by abrookbanks** [comment]
![screen shot 2018-06-25 at 09 59 00](https://user-images.githubusercontent.com/4520803/41840758-7d86c75a-785e-11e8-983e-492983018cf7.png)
