### ISSUE TITLE
Add Email Template Translation Issues

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#2072]
The email translation attempt needs an error message

            1. A Language is listed in the Languages, but it is NOT enabled
            2. The flag does not show in the flags for a specific email template
            3. When you add the translation to a specific template, the language shows in the drop down list of possibles
            4. It the language is NOT enabled in Languages, the save does not save the new translation, but sends you back to the main Email Template page.

It really needs to have an error message that this language is not currently enabled in Languages, rather than reverting to the main list of templates.
********
The other problem is found on my test 6.2.1 stock site. There is no way to test it on the Demo store since only UK is installed. (It also happens on an edited test store copied from a 6.1.15 database and upgraded.)

            1. UK and US are both installed and enabled in the Language section
            2. Store Setting has Language set to US
            3. Attempt to add US translation to any default email template.
            4. Only UK is in the list of possibilities for language to use in translation

**Comment by abrookbanks** [comment]
Thanks Rosemary!!!
