### ISSUE TITLE
Further Improvements to Product Specifications

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#2074]
In 6.2.0 you added Product Dimensions which is great inclusion.

The Dimension Units are cm and inches.  Can you include mm, m, feet and yards in the dropdown.

Two other additions that would be helpful improvement to Product Specifications

1. Volume Dimensions dropdown (ml, l, oz, gal)
1.1 Volume textbox (enter amount)

2. Material textbox (enter material) eg Metal, Plastic, Copper, Timber, Cotton etc.

If left blank they do not display in Products - Specifications frontend.

And again like Product Dimensions if left blank it can be set in Product Options should Volume and/or Material are Options/Option Sets 

These are better suited in Product Specifications than putting them in Product Description.

This way you have Weight, Dimensions, Volume and Material all in Specifications.

**Comment by bhsmither** [comment]
Product Dimensions were (most likely) added to solve a problem with commercial carrier requirements that rate requests would be accurate if, in addition to weight (Lb or Kg), packaging sizes was included to get a more accurate shipping quote.

As such, composition and other dimensional units, being elements of product specs, probably would not solve any pressing obstacle to selling and shipping inventory.

That said, if you can identify an obstacle to these core functions that having said distinctly identifiable properties of an item of inventory would solve, please let us know.

There are third-party extensions that will solve your particular needs.

**Comment by sumwonlost** [comment]
Fair enough with dimensions for shipping, however I see an issue if dimensions are used for shipping as I have it (Size/Dimensions) set up as an Option where I have different sizes/dimensions (attributes) at different sale price.

I can override weight in Product Options so how do I override Dimensions if I set Size (Dimensions) as an Option/Option Set?

eg 
Size1 (Dimentions1) - Price1 - Weight1
Size2 (Dimentions2) - Price2 - Weight2
Size3 (Dimentions3) - Price3 - Weight3

Do I now need to set up each as a separate Product with its dimensions as opposed to using it as an Option/Option Set for shipping purposes?

I only recommended Volume & Material as an improvement to Product Specifications useful to all/most stores.  My philosophy being if it is useful to ALL/MOST stores then it should be standard feature, if not then it should be a plugin.  The more features the greater uptake of CubeCart, isn't that part of the goal?

I am not so much concerned about my store as I develop my own plugins and I can include this in my Product functions plugin.

**Comment by bhsmither** [comment]
With respect to dimensions, I agree this is a valid concern to be able to pass to the shipping modules something similar if not precisely the product options that relate to dimensions. If one could also add columns to the table that assigns an option type and option values, as like the weight column, then this can be passed in the cart array to anything that needs it. (Weight can be summed when shipping more than one item in a box, but this concept is not easily conferable to dimensions.)

As mentioned, there are plugins that afford the assignment of arbitrary properties to products (not usable as options): Suitable for X+ Ages, Shipping Lead Times, Hazmat, Requires X-number of Batteries, etc.

**Comment by sumwonlost** [comment]
I see an issue if dimensions are used for shipping.

Example I have dimensions for a Towel as 75 x 150 cm but when shipped this is folded down to approx 25 x 25 x 1 cm

BTW can you tell me which plugin provides the options you listed?

**Comment by bhsmither** [comment]
I don't see your handle on the forums - which is where I would otherwise post this reply:

https://www.cubecart.com/extensions/plugins/additional-global-product-fields
https://www.cubecart.com/extensions/plugins/additional-product-fields
https://www.cubecart.com/extensions/plugins/additional-global-product-tabs
https://www.cubecart.com/extensions/plugins/additional-product-tabs
(Not sure of the exact differences between "global" and otherwise.)
http://www.chuggyskins.co.uk/index.php?act=viewProd&productId=27
(I have improved this mod to work on CC6 with better functionality.)
