### ISSUE TITLE
6.2.1 Sort not working on Transaction Logs

### ISSUE THREAD

**Issue by richosr** [cubecart/v6#2075]
When applying a sort on transaction log page no change happens the default sort remains.

![image](https://user-images.githubusercontent.com/992654/41497910-d36b59b4-7189-11e8-8469-08b974218fec.png)
![image](https://user-images.githubusercontent.com/992654/41497916-eb81fae4-7189-11e8-9250-901ebc4b6e3c.png)

**Comment by Dirty-Butter** [comment]
Url shows ASC and DESC, but it does not sort for me, either, on two 6.2.1 test sites that have Transactions.

**Comment by bhsmither** [comment]
Possible duplicate of #1999

**Comment by Dirty-Butter** [comment]
Looks like it, Bsmither!

**Comment by abrookbanks** [comment]
Duplicate of #1999
