### ISSUE TITLE
Unable to change from foundation skin if cache disabled

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2079]
Using stock 6.2.1 with foundation skin, if cache is disabled and you switch to foundation skin, it is impossible to then switch to any other skin.

**Comment by abrookbanks** [comment]
I can't reproduce this at all.

**Comment by abrookbanks** [comment]
Any special scenario? My settings are below:
![screen shot 2018-06-25 at 10 03 42](https://user-images.githubusercontent.com/4520803/41841001-13c7559a-785f-11e8-83ba-ed0d9c0a07cb.png)

I can switch between skins and they hold.

**Comment by abrookbanks** [comment]
Happy to reopen...
