### ISSUE TITLE
Plugins that use ionCube cannot be uninstalled if ionCube is not installed.

### ISSUE THREAD

**Issue by bos4711** [cubecart/v6#2082]
I added a plugin that requires ionCube, which my hosting does not have (nor will install). The plugin is therefore of no use to me, but when trying to uninstall it by clicking the delete icon under "Manage Extensions", this message pops up:

> Site error: the ionCube PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking. Please visit get-loader.ioncube.com for install assistance. 

This makes everything a Catch 22.

![cc6](https://user-images.githubusercontent.com/11036018/41710067-04dfc430-7545-11e8-8bec-c7509f39ec64.png)

**Comment by bos4711** [comment]
Update: I can't even access the admin-page anymore, because of this.

**Comment by havenswift-hosting** [comment]
This is not a bug and there is nothing that CubeCart can do about it.  Any plugins that require ionCube, clearly say this in the description so you shouldnt try and install one without first checking (and find a better hosting company that provides this lol) but the solution is to simply use FTP or your hosting File Manager to remove the plugin directory

**Comment by bos4711** [comment]
Either I'm blind or there's not a word about ionCube at the plugin page: https://www.cubecart.com/extensions/plugins/related-products-manual-automated-recommendations

**Comment by bos4711** [comment]
Alright, renaming the plugin directory solved it. Thanks.

Closing ticket.

**Comment by abrookbanks** [comment]
Turn on safe mode in the global.inc.php file. For notes refer to the global.inc.php.dist file.
