### ISSUE TITLE
stock level cache

### ISSUE THREAD

**Issue by hershbergj** [cubecart/v6#2084]
upgraded to 6.2.1 and checked that your manual repair for this issue was included. storefront quantities still don't get updated. only by manual clear cache. receiving because of this issue out of stock sales. Thank you

**Comment by abrookbanks** [comment]
Should be resolved with https://github.com/cubecart/v6/commit/f9e905983aa9daa09bb1a7e9d4b1d7413304a57f

**Comment by matanhershberg** [comment]
Any estimates for a release date on this?

Wondering if I should just apply manually or wait for release.
