### ISSUE TITLE
Add option to cache sessions using redis or memcache

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2085]
This was part of https://github.com/cubecart/v6/issues/1306 but responses seemed to only focus on adding Full Page Cache which is a much more complex proposal.

Sessions can already be located in an account specific directory which helps with session files being deleted early via garbage cleanup but caching small session files is exactly what memcache / redis is brilliant at doing

**Comment by abrookbanks** [comment]
Thanks Ian.
