### ISSUE TITLE
There should be a defined max quantity limit

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2086]
Had somebody come to me with this over the weekend after playing around with CubeCart. There are no safeguards to prevent somebody from entering stupid quantities and adding to their basket when stock control is disabled, for example adding "999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999" items.

Depending on the server on which the store is running, this can cause some issues. In the case of the recent example I was given it caused an "Internal server error" on the store. 

Ideally there should be a "max quantity" defined as a store setting, which caps the total quantity of any one item that can be added to the cart with a reasonable default value (perhaps 1000). It should support larger numbers in case people are using minor volume UOM as their quantity.

**Comment by abrookbanks** [comment]
I don't think we should have a setting for this unless it is per product or 999 if not set. I can see some niche store needing 99999 but most will probably need 99 max.

**Comment by Noodleyman** [comment]
one of those scenarios where people sell liquids by the millilitre and somebody wants several a 55 gallon drum, seems unlikely but I have seen this kind of thing happen and cause some very interesting results, the thought of a global limit is purely a safety net to prevent errors rather.

**Comment by abrookbanks** [comment]
I think for the vast majority 999 as a max is ample.

**Comment by bhsmither** [comment]
What was the cause of the 500ISE? Integer overflow on the variable(s) holding the quantity?

**Comment by Noodleyman** [comment]
I'm not sure. I was going to check, but didn't have access to the server logs for the site used in the test

**Comment by bhsmither** [comment]
See if it crashes on your dev environment.

**Comment by Noodleyman** [comment]
I tried, I wasn't able to replicate it there or on the official cubecart demo site.

**Comment by abrookbanks** [comment]
Let me know if you think I need to look at this more.

**Comment by bhsmither** [comment]
Do you have any sense if the server where this happened is 32-bit? (A max integer on a 64-bit machine is 9,223,372,036,854,775,807 - so even that input would have overflowed. And if so, PHP converts to a float. But then, CC type casts it back to `(int)` (Cart class near lines 158 and 166 for `POST['quantity']`.)

**Comment by abrookbanks** [comment]
I wish I listened more in my computer science lectures at uni. 🤣😀

**Comment by demand73** [comment]
Well 999 is to small some of my Products like resistors sells in thousands some times. http://www.demand.nu/retrotech/r0805-4k7.html
The most i have sold in the same order is 2500pcs.

**Comment by tbonerocketeer** [comment]
I also sell stuff that can exceed 999. I have chord sold by the foot and needed to sell 3000ft, of course the customer wasn't able to do so.
