### ISSUE TITLE
Sitemap uses http or https in urls based on whichever the admin is using at the time

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2087]
See:
https://forums.cubecart.com/topic/54134-sitemap-question/?tab=comments#comment-234303

with SSL set to YES in store settings...

if logged into the admin area using http and you rebuild sitemap, it uses http in URL's. 
if logged into the admin area using https and you rebuild sitemap, it uses https in URL's. 

with SSL set to yes it should always use HTTPS in sitemap

**Comment by abrookbanks** [comment]
Thanks.
