### ISSUE TITLE
Meta title missing from element.meta.php

### ISSUE THREAD

**Issue by vidmarc** [cubecart/v6#2088]
This line needs adding:

<meta name="title" content="{if isset($META_TITLE)}{$META_TITLE}{/if}">

**Comment by vidmarc** [comment]
`<meta name="title" content="{if isset($META_TITLE)}{$META_TITLE}{/if}">`

**Comment by abrookbanks** [comment]
https://moz.com/community/q/title-vs-meta-name-title-both-or-just-one-of-them

> To put it bluntly, the `<meta name="title">` is a waste of code.

**Comment by vidmarc** [comment]
Suggest removal of field: Products -> Search Engines -> Meta Title if it is not used.

**Comment by abrookbanks** [comment]
> Suggest removal of field: Products -> Search Engines -> Meta Title if it is not used.

That is used but in the title tag.
