### ISSUE TITLE
Can't use special characters in password for SMTP server

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2089]
Tested using Gmail as SMTP server, If your password contains special characters, for example:
!
&
^

The password is rejected as being incorrect. if you remove those special characters from the password it works correctly.

**Comment by abrookbanks** [comment]
Is it obvious I do the easy ones first? :)

**Comment by abrookbanks** [comment]
Thanks for this

**Comment by Noodleyman** [comment]
I do the same when slammed, quick wins. Thanks :)

**Comment by Noodleyman** [comment]
I think this needs another review. I tested the fix today, but still faced the issue. once I used less complex passwords it worked

**Comment by havenswift-hosting** [comment]
I completely agree - this caught me out again today - any password with a special character in cannot be used in the SMTP settings - accepts it but validation fails
