### ISSUE TITLE
SUGGESTION - Timing of v6 release

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#209]
I have a suggestion about the timing of providing the v6 release to the public. Please consider providing the code to the public on a Monday, not Friday, so you and your staff will be available to the forum and here on GitHub all that first week. 

It's been frustrating in the past to need help with a new upgrade, and almost immediately it was the weekend - ie. no CC staff available.

**Comment by abrookbanks** [comment]
We never ever release on a Friday. EVER! Monday to Wednesday is preferable but sometimes Thursday happens.

**Comment by Dirty-Butter** [comment]
LOL Well it always felt like you did to me. Sorry for wasting your time on this.
