### ISSUE TITLE
Impliment CSP to enhance security

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2090]
Reference:
https://infosec.mozilla.org/guidelines/web_security#content-security-policy

This should help reduce the risk of XSS issues on sites.

https://observatory.mozilla.org/analyze/demo.cubecart.com

**Comment by abrookbanks** [comment]
Nice!!

**Comment by abrookbanks** [comment]
I'll cover this with 2092.

**Comment by abrookbanks** [comment]
I'll cover this with #2092
