### ISSUE TITLE
Nochex IPN Address

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2093]
In Nochex's 2.0 gateway.class.php file, the `callback_url` is:
```
$GLOBALS['storeURL'].'/index.php?_g=rm&amp;type=gateway&amp;cmd=call&amp;module=nochex',
```
but the folder name is `Nochex_APC`.

This will cause a failure in the `_g=rm` process.

Suggest having the `module` value and folder name match.

**Comment by abrookbanks** [comment]
Thank you... 2.1 released.
