### ISSUE TITLE
Taxes: improving the order editing experience

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#2097]
1. Display at least County next to each Tax Rule entry in the list so that they are distinguishable

2. Increase the drop-down element width (or leave unspecified) to allow displaying entire entry

3. Auto-populate the amount to tax when selecting a tax rule and/or include the tax rate and whether it applies to shipping with each entry on the list so we can determine the amount to charge

I may just be using the system wrong, but I have all of the US state sales tax rules under "Standard Rate: Sales Tax" for their tax class and tax details, making them indistinguishable when trying to add or switch a tax rule on an existing order.

**Comment by abrookbanks** [comment]
## 1. County added next to country ##

![screenshot 2019-02-12 at 14 21 47](https://user-images.githubusercontent.com/4520803/52641871-bae31e80-2ed1-11e9-9fef-d70f7cb10ab3.png)

**Comment by abrookbanks** [comment]
## 2. Removed width restriction on tax drop down ##
![screenshot 2019-02-12 at 14 25 20](https://user-images.githubusercontent.com/4520803/52642060-2927e100-2ed2-11e9-9f09-7f2b8bdb8559.png)

**Comment by abrookbanks** [comment]
## 3. I think I can make this work. ##

WIP... 
![screenshot 2019-02-12 at 14 39 33](https://user-images.githubusercontent.com/4520803/52643037-157d7a00-2ed4-11e9-9261-7baefe81af53.png)

**Comment by abrookbanks** [comment]
This is really complex. Each product can have a different tax class. I need to match them up for existing products (in the inventory) and push by default to added ones.
