### ISSUE TITLE
New Product not showing up on Latest Products or Category Pages

### ISSUE THREAD

**Issue by Mateo1966** [cubecart/v6#2099]
Added a product to my store...running CC v6.2.0
BUT the product is not being added to Latest Products or the category pages, but can be searched for individually and it shows up...
How to fix this?

Thanks,
Matthew

**Comment by havenswift-hosting** [comment]
You need to clear cache - read the release notes https://forums.cubecart.com/topic/53894-cubecart-6115-620-released/

**Comment by Mateo1966** [comment]
I'm not finding a clear cache button on the top right of any page in the admin...

**Comment by bhsmither** [comment]
Please determine if you have more than one administrative folder at your site. Using FTP or the hosting account's control panel, in Cubecart's main folder, there should be one administrative folder.

The folder's name could be **admin** or **admin_aBcDeF** using random characters.

If you have more than one administrative folder, determine which is the newest folder.

Then, in `includes/global.inc.php`, makes sure the value for 'adminFolder' matches.

Delete any other administrative folder.

You should now have a Clear Cache button next to the Help button just below the "Welcome back Admin" message in the upper right.

**Comment by Mateo1966** [comment]
Ok, I did that and saw it...then logged out...
Now I am unable to log back in
What happened?
Just to let you know, the website is still working, customers can log in and checkout, but I just can't access the admin area...
I do get the cross-site error message, but i've clean my cache and so on and nothing works

thanks

**Comment by bhsmither** [comment]
Please realize that the administration folder may have a name you have not created a desktop shortcut  for. Or your browser is using a (now) incorrect remembered web address.

When you say you cannot access admin, do you first get the admin logon page, and thereafter get nowhere? Or do you not even get the logon page?

Make sure the /includes/global.inc.php file has the matching names of the administration folder and administration PHP script.

Clear your browser's cookies for your site.

**Comment by Mateo1966** [comment]
I get to the log on page for admin...and the global.php has both the correct admin and folder info.
yes, cleared all cookies from both browsers.
i've tried in chrome and edge browsers...just goes nowhere...

**Comment by bhsmither** [comment]
Then this should probably have a ticket submitted to Support or start a conversation on the Forums. I will assert this situation isn't a bug with CubeCart code.

See you on the Forums!

**Comment by Mateo1966** [comment]
hey thanks...I put the old file back in and reconfigured the global.inc.php to point to the admin page and old folder....at least can have access to the admin area now...
Still no clear cache situation...
Wonder what's in the old file that isn't in the latest file that will allow access to the admin area...?
Or, what's in the latest file that can be transferred to the old admin file to show and allow the clear cache
I'm perplexed...

Thanks

**Comment by abrookbanks** [comment]
Please follow the [upgrade instructions](https://support.cubecart.com/Knowledgebase/Article/View/228/43/how-do-i-upgrade-from-cubecart-v6-to-latest-v6).
