### ISSUE TITLE
Debug->display()

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#21]
Line 230, suggest creating a style rule in the main CSS file for the skin:
`debug { from line 230 }`

Also, line 272 needs a `<br />` at the end of Queries (count).

Also, suggest not having lines 267 and 268 as this creates an unnecessary line break.

**Comment by abrookbanks** [comment]
Thanks for this Brian. I have made all those changes apart from removing the inline style. The reason it is inline is so that it looks ok with older v5 skins. I agree in that it would be best practise to have it in the CSS file but in practise I think it needs to stay like this.
