### ISSUE TITLE
Social Media Icon Link Issues V6.0.0b6

### ISSUE THREAD

**Issue by chilled35** [cubecart/v6#210]
Twitter is ok, as is the Facebook icon, when you hover over the icon, the status area of the browser suggests the URL is correct.  However, adding an Instagram username in the admin panel, returns another Facebook URL when the Insta icon is hovered over.  YouTube is even worse... The backend is hard coded to a user, no option exists to point it to a channel.  Accordingly, entering a channel name won't work.  This shop I'm setting up for my friend, they have a channel on YT with no associated username for it, so the YT icon on the shop homepage doesn't work either.

**Comment by abrookbanks** [comment]
Thank you!! :)
