### ISSUE TITLE
Coupon for Subtotal Only

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2100]
My research suggests that in admin, Promotional Codes, Add/Edit Coupon, Assigned Products tab, `Discount applies to subtotal only` setting, while it is databased, there is no code in CC621's Cart class that uses it.

(Three hooks exist but are probably not well positioned to effectively use this setting.)

Suggest adding verbage explaining this setting is ignored, or removing this setting from the admin page and database table.

(History: In CC5, this setting, appearing on the Assigned Products page, implied it affected how discounts were to be applied to the products. The actual effect was to cause the list of included/excepted list of products to be ignored.)

**Comment by Dirty-Butter** [comment]
We sell many low cost items and cannot afford to discount s/h. I have always used this check box. Please consider changing the code so it actually does what it says it does. Evidently we've just been lucky!
