### ISSUE TITLE
Stripe - White screen on checkout

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2103]
Getting this for existing customers who are logged in using the latest version of Stripe.

[Exception] /var/www/html/lanmatrix/modules/gateway/Stripe/stripe-php-5.2.0/lib/ApiRequestor.php:124 - Customer already exists.

**Comment by abrookbanks** [comment]
That's odd as it trys to retrieve the customer and catches an exception if the ID doesn't exists to then create the customer. This means it shouldn't create a customer if it already exists. 

Can you reproduce this?

**Comment by abrookbanks** [comment]
I wonder if the call to retrieve failed for some reason like a network time out.

**Comment by Noodleyman** [comment]
Can you give me some pointers on the call to retrieve and I'll check into it. :)

**Comment by abrookbanks** [comment]
Yup. Line 83 of gateway.class.php

```
$customer = \Stripe\Customer::retrieve($customer_id);
```

**Comment by abrookbanks** [comment]
Actually I see line 87 a line to create the source but it doesn't look like thats the issue. Maybe it is.

**Comment by abrookbanks** [comment]
Closing until we have steps to reproduce this.
