### ISSUE TITLE
Print Layout tweak needed where no State/Province provided

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#2104]
See https://forums.cubecart.com/topic/54178-address-layout-for-disabled-state-62/

**Comment by abrookbanks** [comment]
Is this from printing in the admin control panel, the "print order form" gateway or customer print?

**Comment by Dirty-Butter** [comment]
As far as I can tell it's anywhere the address is printed. Plus on the storefront Customer's Addressbook it leaves the blank line there. And in Admin the Order summary page shows the  comma ZIP in the address.

**Comment by Dirty-Butter** [comment]
Just change a country to State Disabled and you'll see the issue everywhere the address is displayed or printed.

**Comment by Dirty-Butter** [comment]
There's no way to test this on the CC Demo store, so I brought a stock store back up to current commit. I do not see the extraneous comma or the blank space in addresses anywhere. So this is NOT a CC bug. But I have the issue in all my test and live stores. UGH

**Comment by abrookbanks** [comment]
Hmm mine shows.. 

```
{if !empty($order.state_d)}{$order.state_d|upper}, {/if}
```

**Comment by abrookbanks** [comment]
You can change the code to check for it as above. :)

**Comment by Dirty-Butter** [comment]
I was talking about the comma showing on the Admin and storefront pages with addresses. But it WAS my fault. I'm so sorry for wasting your time.
