### ISSUE TITLE
Custom Actions

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2106]
In cubecart.class.php, the `default` method (near line 426) suggests that a user created `_a=whatever` will auto load any `/classes/` class file.

The code actually looks for `CubeCart->_whatever()` (lines 430-432), and then will trigger a code snippet or plugin hook.

So, the question is, how does one get `CubeCart->_whatever()` (from `$this->{$method}();`) into the class?

Any notes on how this was supposed to work?

**Comment by abrookbanks** [comment]
I didn't write this code so I'm in the same position as you. It would be nice if the class could be extended maybe. However a hook follows `class.cubecart.construct` allowing you to use it. 

From there you can do a lot of things.
