### ISSUE TITLE
Skin to Determine Structure

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2107]
In Foundation's `content.product.php`, there is:
```
         {foreach from=$PRODUCT_TABS_TITLES item=product_tab_title}
            {$product_tab_title}
         {/foreach}
```
and
```
         {if isset($PRODUCT_TABS_CONTENTS)}
            {foreach from=$PRODUCT_TABS_CONTENTS item=product_tab_content}
               {$product_tab_content}
            {/foreach}
         {/if}
```
(Note: Smarty can handle a missing or empty array. There is no need to check if it isset.)

The above **requires any hook** to prepare in advance how any additional tabs are structured. That is, Foundation uses `dl, dt, dd` and `<div class="content"` to create tabs and visible blocks. Other skins may have a different structure.

Suggest the skin determine this structure.

One solution is, for Foundation:
```
         {foreach from=$PRODUCT_TABS_TITLES item=product_tab_title}
         <dd><a href="#{$product_tab_title.content_id">{$product_tab_title.title}</a></dd>
         {/foreach}
```
and
```
         {foreach from=$PRODUCT_TABS_CONTENTS item=product_tab_content}
         <div class="content" id="product_tab_content.content_id">{$product_tab_content.content}</div>
         {/foreach}
```
Another solution is to compose `element` templates having the above structure, for which hooked code can populate and fetch (if the template exists for this skin), and push onto PRODUCT_TABS_TITLES and PRODUCT_TABS_CONTENTS.

**Comment by abrookbanks** [comment]
This is much nicer. I had to code it with backward compatibility so not to upset any existing extensions.
