### ISSUE TITLE
config.xml <csrf> and email validation issue

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2108]
I've noted this before and shared it elsewhere, but it has come back around again over the past week and been causing a lot of pain for a handful of customers.

CubeCart 6.2x may not work correctly with older themes, specifically those who port/update their themes based on foundation. Foundation also will not work correctly if "csrf" is defined as false.

Specifically a customer can't checkout if they are not logged in. A customer also can't register.

this has been a pita to track, but finally got there. In newer foundation themes "csrf" was added.

CubeCart.class.php specifically checks if this is set to true when it returns a reply to an ajax email request (customer exists/not exists).
![image](https://user-images.githubusercontent.com/10614018/42769028-f6973d3a-8918-11e8-9b12-59ad2b2d6858.png)

Note, if "csrf" is false, we simply return the string true or false to the browser. if it is true an array is returned after being json encoded.

In the 3.cubecart.validate.js file the email validation rules always assume the reply will be an array. 
![image](https://user-images.githubusercontent.com/10614018/42769126-3e8f0d84-8919-11e8-8756-502f60ecfaa6.png)

This means you can never pass validation with "csrf" as false. 

for some older themes, and those themes who have overlooked adding "csrf" to their config.xml file, or even those who don't want to use "csrf" it breaks the store.

**Comment by abrookbanks** [comment]
The Foundation skin is designed to always have CSRF on. The setting was added for backward compatibility so it it doesn't exist then ajax data returns as expected instead of as an array. 

Older skins without CSRF should not have that code in it. Instead use;

```
return json;
```

**Comment by Noodleyman** [comment]
what if you don't want to run it with CSRF on?

**Comment by abrookbanks** [comment]
It's hard coded to use CSRF. Since 6.2.x (can't remember which one exactly) the token doesn't change so you can have multiple tabs, windows and work with premature page data. On those grounds there's no good reason not to use it.
