### ISSUE TITLE
Fixed VAT number showing on Invoice

### ISSUE THREAD

**Issue by NaturalSigns** [cubecart/v6#211]
If you log in as a customer and view previous orders you have the option to print invoice (nice feature).  Problem is though it seems to have a hard coded VAT number showing (as below).
![vat number](https://cloud.githubusercontent.com/assets/10531097/6172636/f68deadc-b2d9-11e4-91e5-9d58f378d513.png)

I'm not sure where this is defined/if it is required. 
Rob

**Comment by abrookbanks** [comment]
First tab of store settings... 

![screen shot 2015-02-12 at 17 25 09](https://cloud.githubusercontent.com/assets/4520803/6172962/3da1f63c-b2dc-11e4-802a-60e745e8cb99.png)

**Comment by NaturalSigns** [comment]
Yep i noticed that, (and mine is blank), but the above number appears on the invoice when printed from the customer side (think it might have been hard coded (try searching google for EU875677676 ).

**Comment by abrookbanks** [comment]
It is hard coded!! Thanks fix coming...

**Comment by abrookbanks** [comment]
Fixed. Thanks for this!! :)
