### ISSUE TITLE
Enhancement: promotional codes, exclude sale items

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2110]
Enhance promotional codes to exclude sale items.

Added here as the request a feature portal is offline

**Comment by abrookbanks** [comment]
I think this is an important one actually. You regularly see discount codes that can't be used against existing promotions.

**Comment by Noodleyman** [comment]
I already implemented it via hooks, was quite a chunk of code when you consider all of the different possible configurations (sale mode, is the product on sale, is it included/excluded, and what is already included/excluded in the array).  It works well.  Should you want a glance at the code I can send it to you so you can refine it into core code.

**Comment by abrookbanks** [comment]
Kool, thanks.
