### ISSUE TITLE
Multiple order confirmation emails sent incorrectly

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2114]
The scenario is

Order placed 15th July at 12:52 for a physical product with a cost and print order form selected as payment method as customer (not a registered customer but as a guest) was paying via bank transfer - entry at Pending as expected in Order History

It sent out admin "Order Received" and Customer "Order Confirmed" emails at that point as expected.  It then sent out another Customer Order Confirmed email at 14:46 that day.  All of these are recorded in the transaction log and the email log.

The order was manually moved to Processing when the money was received at 09:47 on the 17th July and this is recorded in the Order History BUT another Order Confirmed email was sent (instead of the Payment Received that should be sent).  Order was then moved to Completed which correctly sent the Order Complete email.

So already two issues (an additional Order Confirmed email sent to the customer for no reason and the wrong email sent when order moved to Processing) but this should be the end of that order but it now gets even worse

On 17th July at 21:41, 18th July at 12:46, 18th July at 13:21 and 19th July at 19:32 it records a Pending transaction in the transaction log and sends the customer an Order Confirmed email !

This client has lots orders from guest registrations and they all work with no problem but the difference is that all of these are either paid for via PayPal or a free (a free promotional digital download).  This is the only order placed by a guest using the Print Order Form so looks like the problems are within that module

**Comment by bhsmither** [comment]
The POF has a setting to send a complimentary email. I believe the POF uses the Customer's (Cart) Order Confirmation email template. And this is the end of the POF's involvement.

WRT the admin moving the order to Processing and Completed, and there being multiple Pending entries in the Transaction Log, perhaps a correlation with web server access logs can reveal some info.

**Comment by abrookbanks** [comment]
If the merchant can  open a support ticket with steps to reproduce and I'll look into this.

**Comment by abrookbanks** [comment]
This can be fixed by turning off the IPN URL in the PayPal account. I think this issue affects PayPal powered by Braintree users only who also have the correct PayPal IPN URL specified in their PayPal account. Braintree triggers the order confirmation email and also PayPal.

**Comment by havenswift-hosting** [comment]
This issue had nothing to do with PayPal and while the client in question has standard PayPal gateway installed (the order didnt involve that gateway but used the POF) they dont even have Braintree installed (the Braintree gateway doesnt work with most third party skins as previously reported)

**Comment by abrookbanks** [comment]
OK still keeping this closed until I have steps to reproduce. Thanks.
