### ISSUE TITLE
Errors in hreflang tags

### ISSUE THREAD

**Issue by vidmarc** [cubecart/v6#2117]
From Google webmaster tools:

We found the hreflang tags on your site, but a few of them have technical problems. Take a look at our hreflang report to see which of your hreflang tags have issues. Until you fix these tag errors, your website will not benefit from additional language or region targeting.

_International Targeting | Language > 'x-default' - no return tags_

**Comment by havenswift-hosting** [comment]
This problem was introduced with https://github.com/cubecart/v6/issues/1944 and many sites are receiving exactly the same issue.  Also reported several times on the forums ie https://forums.cubecart.com/topic/54221-errors-in-hreflang-tags/

**Comment by abrookbanks** [comment]
Let me know if that helps.
