### ISSUE TITLE
Jump to Single Result May Fail

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2118]
See: #1427.

This is a very edgy case.

`Catalogue->searchCatalogue()` is used to find products matching search words, products assigned to a given category, and sale items.

In the search and sale code, `$this->_category_products` is the direct result of the query recordset. It is an indexed array with a default index, and 1427 uses the zeroth (or [0]) array element.

In the category code, `$this->_category_products` is the result of the trip through `getCategoryProducts(cat_id)` then `getProductData()`, and is an associative array with the index being the integer product_id.

This difference **may** cause consternation with other code wanting to get the first (or 'zeroth') array element from `$this->_category_products` which the key will not be zero.

**Comment by bhsmither** [comment]
I just learned from other CC code that one can `sort()` the array which will re-index it with sequential integers.

**Comment by abrookbanks** [comment]
Thanks for the cool theory. I'm sure you are right. If you can give me steps to reproduce this happening  I'll have a look into it.
