### ISSUE TITLE
Search Results may be Incomplete When Admin Logged In

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2119]
In admin, Store Settings, Stock tab, "Hide out-of-stock product" is enabled, but does not affect admin.

The admin is logged in.

Latest Products will then show out of stock items.

But, using the Quick Search box will not include out of stock items.

Suggest using `$this->outOfStockWhere()`.

Catalogue class near line 1766:
```
Existing:
			// Only look for items that are in stock
			if (isset($search_data['inStock']) || $GLOBALS['config']->get('config', 'hide_out_of_stock')) {
				$where[] = "((I.use_stock_level = '0') OR (I.use_stock_level = '1' AND I.stock_level > 0))";
			}

Change to:
			// Only look for items that are in stock
			$where[] = $this->outOfStockWhere();
```

**Comment by abrookbanks** [comment]
Thanks.
