### ISSUE TITLE
Upgrade Enhancement

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2120]
Upgrading from CC4...

If the format of `CubeCart_order_sum.ship_date` **is known to be stable**, then a hard conversion is not the optimum approach.

That is, since 'ship_date' (VARCHAR-50) for CC4 could hold _anything_, it was meant for "general information" (as opposed to being used to calculate something else). The format of the value could be anything -- assume it is MM/DD/YYYY.

In the file /setup/db/upgrade/5.0.0.0b1.sql, line 490, a hard CHANGE is made to the 'ship_date' column to make it hold DATE values. A DATE column has a specific format (YYYY-MM-DD). MySQL will "do its best" (which isn't all that great) to make the hard conversion.

The correct approach is to apply a "mask" to the values to annotate what part of the string belongs to what part of the date. UPDATE all the values to the CC5/6 format. Then make the CHANGE to the column data type.

See:
https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_str-to-date

Otherwise, a 'ship_date' of "07/12/2018" will hard convert to 2007-12-18 (or be _null_).

I do not know that much about CC4 to be certain what code recorded the ship_date, and whether the format used was programmed into CC4, or if was up to the admin to freely enter something, or the shipping module was responsible.

FYI: CC6 has a Date Picker that will force the correct format to be saved in the 'ship_date' column.

**Comment by abrookbanks** [comment]
Thanks for this and its very valid. However v4 upgrades are SO rare now. I haven't done one for six months plus. I'm best of spending time elsewhere. :)
