### ISSUE TITLE
Latest Products May Show Out of Stock Items

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2121]
The admin is not logged in. "Hide out-of-stock items" is enabled.

The item's "Use Stock Level" is enabled, and has main stock. However, all available option combinations in the Options Matrix Table has "Use Stock Level" enabled with zero stock.

The query for Latest Products uses the item's main stock level to determine its inclusion in the list, but the derived stock level for the Buy button uses a query against the item's Options Matrix Table stock level.

**Comment by abrookbanks** [comment]
Nearly five years old this one. 🫥

Pleased to say it's no longer reproducible.
