### ISSUE TITLE
Database Table Enumeration Anomalies

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2124]
In admin/sources/maintenance.index.inc.php, the `$index_map` array has an extra `cubeCart_access_log` key (misspelled), an extra `cubecart_order_notes` key, and a missing `cubecart_cookie_consent` key.

**Comment by abrookbanks** [comment]
I can't find the missing cubecart_cookie_consent key?

**Comment by bhsmither** [comment]
Can't find it?

Seems it was placed into the array `$index_map` close to where it would be alphabetical instead of at the bottom where all the other new tables are.

**Comment by abrookbanks** [comment]
Yes its not in alphabetical order.
