### ISSUE TITLE
Error on clicking on Mailing List in Stock 6.2.2 current commit

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#2125]
[03-Aug-2018 12:01:50 Europe/London] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in XXX/sources/customers.subscribers.inc.php on line 211

When I manually change a customer to being a Subscriber (No to Yes) to the mailing list, the error message shows when I click on the Mailing List. If I login as the customer, subscribe, and confirm the subscription via email, the error message does not show. In other words the response in the opt-in email is completed.

Shouldn't the admin be able to tell in the Customer information that they did not confirm their subscription (subscription is not valid), preferably with some way to send the confirmation email again?

**Comment by abrookbanks** [comment]
The system should send another opt in email if they try to sign up again.

**Comment by Dirty-Butter** [comment]
As it is, however, the Edit Customer page shows them as Subscribed when they really are not - until they complete the opt-in. Shouldn't they be shown as NOT subscribed at that point? Or even better, something like In Progress?
