### ISSUE TITLE
6.1.14 - Create store account during checkout makes customer_id zero for newsletter subscriber

### ISSUE THREAD

**Issue by jasehead** [cubecart/v6#2129]
(Possibly still an issue in CubeCart 6.2.2)

A guest adds an item to their basket and proceeds to checkout. They add their address details and tick all checkboxes, including:

- Subscribe to mailing list
- I would like to create an account

They complete the form and click Checkout. They are logged in with their address and shipping updated (green notice) and then prompted to click Checkout again.

THE PROBLEM: The customer is being added to the CubeCart_newsletter_subscriber﻿ table with a customer_id﻿ of zero, which is the same as if they were signing up just using their email in the subscription box. When exporting a mailing list no names can be matched to the email address because CubeCart is trying to match the customer_id (which is zero for customers who signed up during the checkout process).

SUGGESTION: Subscription during checkout should occur after the new customer is logged in for the first time and the customer_id should be correct (not zero). Also, please provide a way to verify subscribers by email address and update any with a customer_id of zero to their actual customer_id - either as an automatic check (on subscription, or on mailing list export) or a manual update tool in Admin > Mailing List.

**Comment by abrookbanks** [comment]
I can't reproduce this on 6.2.2.
