### ISSUE TITLE
in_array() Bad Argument

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#213]
Catalogue->_productGallery():
```
// Look for images
if (($gallery = $GLOBALS['db']->select('CubeCart_image_index AS i INNER JOIN CubeCart_filemanager AS f ON i.file_id = f.file_id', false, array('product_id' => $product_id), array('main_img' => 'DESC'))) !== false) {
```
Sends an array in the $order argument of DB->select(), which is not allowed when the $table argument contains 'JOIN'.

Suggest `"ORDER BY main_img DESC"`

https://forums.cubecart.com/topic/49254-v600b5-error-message-expects-parameter-2-to-be-in-array/

**Comment by abrookbanks** [comment]
Well done that man! ;) I'll patch that in the morning.
