### ISSUE TITLE
Cookie Consent Bug - Impacting admin area performance

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2131]
When adding a new user manually via the admin area, the Cookie Consent tab is populated with ALL records from CubeCart_cookie_consent where the customer id = 0;

$cookie_consent = $GLOBALS['db']->select('CubeCart_cookie_consent', false, array('customer_id' => (int)$_GET['customer_id']))

Which when run on the "ADD" page, triggers:
SELECT * FROM `CubeCart_cookie_consent` WHERE CubeCart_cookie_consent.customer_id = '0'

For large stores with a lot of traffic this can load tens of thousands of records which is then processed by smarty. eventually you run out of memory as the list is too large.

recommend making the default ID -1 instead of 0 to fix the issue, then as part of the upgrader set all 0 to -1.

**Comment by abrookbanks** [comment]
This is fixed already on 6.2.2. :)

**Comment by Noodleyman** [comment]
Ah. I couldn't find a related issue for it on GitHub so assumed it was new

**Comment by abrookbanks** [comment]
Thanks for posting though. :)
