### ISSUE TITLE
Catalogue->productCount to be Enhanced

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2132]
This function does not solely count products in a category because the given category's **children** are recursed and added into the result total.

Request:
```
public function productCount($cat_id, $inc_children = true) {
...
if ($children && $inc_children) {
...
```

**Comment by abrookbanks** [comment]
Very nice. I took a slightly different approach as the value created by the `$children` query isn't needed if `$inc_children` is false. Hopefully you agree.
