### ISSUE TITLE
Email log troubleshooting Bug??

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#2133]
![screenshotemaillogtroubleshootbug](https://user-images.githubusercontent.com/6146505/43964599-cc6f99bc-9c82-11e8-9fe9-7ca395f88e41.png)

I had some kind of Windows/Outlook glitch and had to create new passwords for all my email addresses. I forgot that meant I would need to fix the CC ones, too.

The one re-sent email that I did received was the Order Confirmation for the Eden Yellow Chick in the Blue Gingham outfit. But ALL the resent ones show the red troubleshooting alarm even though the Sent is checked.

**Comment by abrookbanks** [comment]
Thanks Rosemary.
