### ISSUE TITLE
Tax rounding issue

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2135]
Continuation of this thread:
https://github.com/cubecart/v6/issues/1801

There are still some issues which are causing some business users of CubeCart a headache.  Here is an example on a clean install of CubeCart 6.2.2, with tax at 20% on both shipping and products. Everything is priced excluding tax.

![image](https://user-images.githubusercontent.com/10614018/44033951-d3406b9e-9f03-11e8-83cf-6df95ffa14e0.png)

Tax should be 30.03 and the total 180.17

140.39 + 9.75 = 150.14

150.14 * 1.2 = 180.168 (rounded to 180.17)

This gets more complex, because for UK, you can opt to either round  up, or down for retail businesses. Typically this would be round down, however there are cases where a business already has a financial system in place and opted to round up.  Both are correct, BUT this needs to be able to be defined in the store config to tune the store to the business accounting practices to prevent sync issue with accounts systems.

I can see there being a requirement for three rules.
1 always round down to the nearest penny at the invoice total
2 always round up to the nearest penny at the invoice total
3 round up if >= 0.5 or down if < 0.5

**Comment by abrookbanks** [comment]
This has been a bloody nightmare for years.

At the moment CubeCart is using code like `sprintf('%.2F',$variable)`. This doesn't round correctly. I think.... 

`sprintf('%.2F',1.55)` = 1.55
`sprintf('%.2F',1.559)` = 1.55

I believe this should be replaced with  `round($variable,2)`.

Then in a few months time another issue will be created on here as it won't work again. LOL

**Comment by abrookbanks** [comment]
Nope. I'm wrong.

`sprintf('%.2F',1.559)` = 1.56

**Comment by Noodleyman** [comment]
There are cases where rounding up is valid, and so is rounding down, it depends on tax rules in the country. For example, in the UK you can opt to round up, or down. I’m not sure if that’s still the case, but last time I checked it was. So, rounding up or down needs to be configurable based on the tax rules for the region.


I think it needs a little more than a tweak to address properly.

**Comment by abrookbanks** [comment]
`sprintf('%.2F',1.555)` however = 1.55 which is an issue.

**Comment by abrookbanks** [comment]
Relates to #2210

**Comment by abrookbanks** [comment]
Also relates to #2150 #2147

**Comment by abrookbanks** [comment]
This has been added to the 6.2.4 milestone because more granular logging of tax has been added to 6.2.3. This means if this issue can be reproduced in 6.2.4 we should be able to see where it went wrong and finally put a nail in this coffin.

**Comment by abrookbanks** [comment]
Any sign on this since 6.2.5? If so there should be a better breakdown in the order summary table.

**Comment by Noodleyman** [comment]
the same example provided in my original ticket still behaves the same in 6.2.5. unless there is a mechanism added to control round up/down in these scenarios I don't think this will ever be resolved. both are technically correct based on tax rules and it becomes a per business accounting practice to which method is used.

**Comment by abrookbanks** [comment]
Yup. Thanks.

**Comment by Noodleyman** [comment]
I've not tested any of the other examples I've provided in the past. My assumption is we should never have more than a penny discrepancy overall, however this may be an incorrect assumption since tax is being calculated per line item and aggregated. As it is per line item, a control to round up/down per line item calculation may be required, and possibly a new field in the CubeCart_order_inventory table to capture the difference in calculated price v's rounded price.

The new field can be aggregated and summed in the Order Summary table, thus showing on the order UI the total value added or subtracted due to rounding in the overall order.

**Comment by havenswift-hosting** [comment]
Can this issue be revisited as seeing it is various forms in several different sites
