### ISSUE TITLE
Invoice Editor to have Conditioner

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2138]
The new Invoice Editor uses the admin template `orders.print.php`.

But, this template has not been 'conditioned' to survive being edited by CKEditor.

Suggest something like issue #1694 and/or #1229 in `documents.invoice.inc.php`.

CKEditor will move
```
{foreach from=$item.options item=option}
and
{/foreach}
```
outside the `<ul>` block.

**Comment by abrookbanks** [comment]
Thanks for this. :)
