### ISSUE TITLE
seo_url not stored in translation

### ISSUE THREAD

**Issue by mike4kz** [cubecart/v6#2139]
Hi,

I've started playing with a translations, and noticed, that when I create a translation for a category, "Custom SEO URL" nor "keywords" are not stored. I checked the database, and fields are empty. When I manually modified SQL record for the translation, and then refreshed the page, it's still not shown. I didn't check the page URL (manually put a "custom seo url" same way as it works in main language), I got 404 page.

Sincerely,

Mike

**Comment by mike4kz** [comment]
That's probably going to be "feature request". All SEO URLs are stored in the database. All document translations stored under unique number, while category has the same number but additional "translation".

Also product translations have no separate SEO information.

**Comment by bhsmither** [comment]
All seo path (friendly URLs) are maintained in CubeCart_seo_urls.

Currently, there is no means to have more than one of the same 'type' and 'item_id' combination.

Yes, a feature request to have 'lang_code' as an additional element to the unique combination.

**Comment by mike4kz** [comment]
Yes, I understood this. My initial question was to have a mechanism to provide separate SEO_META data for each translation. Keywords, description, url, etc.

**Comment by havenswift-hosting** [comment]
This is not a "bug" as such and feature requests covering this have been open for a while

https://features.cubecart.com/topic/foreign-language-seo-urls_1

https://features.cubecart.com/topic/add-seo-title-and-meta-data-for-translations

Please add comments and support for these on those topics

**Comment by mike4kz** [comment]
I saw that. However what I consider "a bug":
* When I create a translation for a category, there is a fields for "Custom SEO URL Path" and "Meta Keywords".
* When I look into the database CubeCart_category_language, there are fields for "seo_meta_keywords" and "seo_custom_url".

However when I fill this information in the translation, they don't go to the database. And when I manually updated a database record with some test values, these values are not propagated back to the form. And when system processes a category page with the "non-default language", URL shows "?seo_path" and the original path (even though the page itself shown translated).

Perhaps it's "work in progress" situation, however I want to bring attention to this.

**Comment by havenswift-hosting** [comment]
I would also love this to be sorted ASAP - we have many UK and international clients that use multiple languages but cannot use them anywhere near to their full functionality

**Comment by abrookbanks** [comment]
Need a permanently moved redirect for changed URL's too.

**Comment by havenswift-hosting** [comment]
> Need a permanently moved redirect for changed URL's too.

There is already a feature request for this - and agree this would be great !

https://features.cubecart.com/topic/feature-request-handle-301-redirects-if-a-url-is-changed_8
