### ISSUE TITLE
Is it possible to Beautify files with our own edits to match the system you are using?

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#2140]
As title indicates

**Comment by abrookbanks** [comment]
Sure: https://github.com/FriendsOfPHP/PHP-CS-Fixer

**Comment by Dirty-Butter** [comment]
THANKS!

**Comment by Dirty-Butter** [comment]
LOL! I downloaded the files HA! I'm sure you got a big smile, knowing how lost I would be. Anyway, maybe this info will help somebody.
