### ISSUE TITLE
Multiple hook requests

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2141]
Request 1
In /classes/cubecart.class find

foreach ($latestProducts as $product) {

Before this add

foreach ($GLOBALS['hooks']->load('class.cubecart.latest_products') as $hook) include $hook;

Request 2
In /classes/tax.class.php near line 435 find

$amount	= sprintf('%.2F', $price*($tax['percent']/100));

After this add

foreach ($GLOBALS['hooks']->load('class.tax.producttax.amount') as $hook) include $hook;

Request 3
In /classes/user.class.php near line 393 find

$customer_id = $GLOBALS['db']->insert('CubeCart_customer', $data);

After this add

foreach ($GLOBALS['hooks']->load('class.user.register_user.insertedAgain') as $hook) include $hook;

Request 4
In /admin/sources/customers.index.inc.php near line 353 find

$GLOBALS['gui']->addBreadcrumb(sprintf('%s %s', $customer['first_name'], $customer['last_name']), currentPage(array('address_id')));

After this add

foreach ($GLOBALS['hooks']->load('admin.customer.noodle.edit') as $hook) include $hook;

**Comment by abrookbanks** [comment]
`class.cubecart.latest_products` already exists :)

`class.tax.producttax.amount` doesn't exist but it seems like if we need a hook for products ex tax then we should add one for inc tax too and name accordingly. 

`class.user.register_user.insertedAgain` I can't see a problem with that one.

`admin.customer.noodle.edit'` - we can add one here but can we change the hook name to be relative to position rather than relative to developer? (We all love Noodleman but it need to be more descriptive).

**Comment by havenswift-hosting** [comment]
Over to him - just getting fed up having to change core files for some plugins when there is no need

**Comment by abrookbanks** [comment]
Yes I can imagine. Lets get it done nicely.

**Comment by Noodleyman** [comment]
Ah, one of the hooks from my first module before I learnt better.. :)   It's on my roadmap to go back and sort out at some point, but for now it's low on my priority list as the addition of the hook is in the install guide that comes with the module.

**Comment by abrookbanks** [comment]
Closing until request is updated.

**Comment by Noodleyman** [comment]
update:
Please add the hook to tax.class.php as follows: 

FIND:
`$amount = sprintf('%.2F', $price - ($price/(($tax['percent']/100)+1)));`

ADD AFTER:
`foreach ($GLOBALS['hooks']->load('class.tax.producttax.amount') as $hook) include $hook;`

REASON: 
Can be used to interact with tax rates (as used by EU VAT module)
