### ISSUE TITLE
Braintree PayPal plugin doesnt work with most skins

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2142]
The way that the Braintree PayPal plugin has been coded means that it doesnt work with most skins other than the stock Foundation.

Skins not based on Foundation dont work

Skins based on Foundation that use a `<header>` tag will also not work as the plugin has a "braintree.css" file which has CSS rules. Some of those CSS rules are very high level, for example binding with the <header> HTML tag and this impacts any theme that uses `<header>` tags within it

**Comment by bhsmither** [comment]
Please edit the above to put code inside code-backticks.

**Comment by abrookbanks** [comment]
Ian you are right but I'm closing this for reasons that will come clear in the coming weeks. Let's just say it's a waste of effort to put development time into this.

**Comment by havenswift-hosting** [comment]
This was closed nearly a year ago as supposedly Braintree was going to be phased out but as it is still available and people still try to use it, was that decision reversed - if so can this issue be addressed.  If not then can the Braintree extension be removed

**Comment by abrookbanks** [comment]
I'll raise this with  PayPal as I have a meeting with them on Friday.

**Comment by abrookbanks** [comment]
I expect we will remove it as PayPal are pushing their Braintree products to larger enterprises which is not our typical merchant.
