### ISSUE TITLE
Custom Order Numer issue

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2143]
After placing an order, the customer will see traditional order numbers:
![image](https://user-images.githubusercontent.com/10614018/44300039-510a0380-a2f8-11e8-95a9-c64461165db3.png)

But, this doesn't match the ACTUAL order number being generated when using sequential numbers
![image](https://user-images.githubusercontent.com/10614018/44300043-667f2d80-a2f8-11e8-804b-8c391af479a2.png)
****

**Comment by bhsmither** [comment]
I do not recognize what that is an image of. Please indicate the template that this information is coming from.

**Comment by bhsmither** [comment]
Ok, the template content.receipt.php (as well as print.receipt.php having similar) has this:
```
<h2>{$LANG.orders.order_number}: {if $CONFIG.oid_mode=='i'}{$SUM.{$CONFIG.oid_col}}{else}{$SUM.cart_order_id}{/if}</h2>
```
Please verify the skin you are using has this code.

I conclude this because Foundation templates do not have a hash mark in the string.

**Comment by Noodleyman** [comment]
I had this very thought last night after logging off, it's probably a smarty thing, thanks for following up. it'll be a custom template issue. I'll get it fixed
