### ISSUE TITLE
Incorrect Sequential Order ID (Issue with trigger)

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2144]
The trigger calls the MySQL LAST_INSERT_ID() function when working out the custom order ID, however this pulls the last ID from CubeCart_order_inventory, not order summary. 

This makes the sequential order numbers non-sequential and causes unexpected results. 

A trigger really isn't the correct mechanism for this custom order ID, it should be done via PHP at the time the order/record is generated. Triggers should be avoided at all costs, they have a reputation for breaking.

Note, the call to get the order ID in order.class.php returns the correct ID from the summary table
if ($order_id = $GLOBALS['db']->insert('CubeCart_order_summary', $record)) {

**Comment by Dirty-Butter** [comment]
Since I had been using Chuggyskins's Sequential Order Numbers for years, I had a terrible time getting any kind of CC sequential numbers to be predictable. (I was careful to clear any signs of the old mod out of the database before attempting the CC one.) Maybe this is why. I look forward to seeing what is done with this Issue.

**Comment by abrookbanks** [comment]
> Triggers should be avoided at all costs, they have a reputation for breaking.

Any reliable sources for that? MySQL is very stable and highly respected.

**Comment by Noodleyman** [comment]
10 years of experience having to fix them when they "just stop" in corporate environments, with the only fixing being to delete then and re-add it.  Happens randomly, MsSQL suffers from the same problem as well. I'm not sure why it even needed a trigger, it's a simple thing to add in PHP.

**Comment by abrookbanks** [comment]
What causes them to stop?

**Comment by Noodleyman** [comment]
An excellent question which has never been answered. no issues in logs. for the MsSQL stuff, Microsoft couldn't even provide the reason. I've noted the same behaviour in MySQL, but again, never seen any issues reported in logs.

**Comment by abrookbanks** [comment]
I don't understand why MySQL and MariaDB have this feature if it isn't reliable.

**Comment by abrookbanks** [comment]
I suppose it could be recoded to use PHP only but at the time of writing how it works isn't fresh in my mind.

**Comment by Noodleyman** [comment]
you can say that about any software that has a glitch.. :)

Regardless of the history to triggers, there is a problem with this functional area at the moment. I had to work around it by updating the custom order Id to be ID, which worked fine for my customer needs.

**Comment by abrookbanks** [comment]
So true. My Mac has some unbearably annoying glitches that have been going on for years.

**Comment by abrookbanks** [comment]
I'm doing a MySQL course at the moment and not got to triggers yet so I'll be interested to see what they say about them. I might ask the lecturer too.

**Comment by Dirty-Butter** [comment]
This just happened on plushcatalog:
![messed up sequential order numbers](https://user-images.githubusercontent.com/6146505/44351827-656d0e00-a468-11e8-846f-729c92804bb6.png)

**Comment by briansandall** [comment]
I'm not sure on the context, but the last insert ID is [known to be finicky](https://secure.php.net/manual/en/mysqli-stmt.insert-id.php) in loops, at least if you are using prepared statements:

> It should be noted that using mysqli_stmt->insert_id will not result in a unique ID being returned for each execution of a prepared insert statement.  In practice, it appears that the first insertion ID is returned.  If you are performing multiple inserts with the same prepared statement (one invocation of mysqli_stmt::prepare and multiple invocations of mysqli_stmt::execute() for a given statement), and need to keep the unique ID for each insert, use mysqli_connection->insert_id.

**Comment by abrookbanks** [comment]
I'm at a loss as to what to do here. Is there a better way to get the ID, should we bin this feature or something else.

**Comment by Noodleyman** [comment]
feel free to catch me on Skype tomorrow for a call, happy to bounce this around. it should be a pretty simple thing to sort using existing php and mysql features.

**Comment by Dirty-Butter** [comment]
It doesn't happen very often, and I have no idea why, or even what "bin this feature" means.

![wrong sequential order number](https://user-images.githubusercontent.com/6146505/53587322-a8aee480-3b4f-11e9-96b9-9c99dc26d30f.png)

**Comment by Dirty-Butter** [comment]
I did search for all COID in order_inventory that matched PC-33, and those outlier order numbers are consecutive, if that helps in any way.

**Comment by abrookbanks** [comment]
> bin this feature

means to put it in the trash can. Sorry it's modern British slang from dust bin.

**Comment by abrookbanks** [comment]
I just don't now what to do about this. CubeCart v7 needs to work from auto increment ID with traditional order ID.
