### ISSUE TITLE
Line item options - name value pairs

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2145]
Please consider as an enhancement, currently when options are selected against an ordered item the name/value of those options get stored in the inventory table, product_options column as a serialised array. 

However, within that array we simply have a string for each option and value combination. It would be VERY helpful to actually have an additional field to store the name/value pairs in an array as well.

Currently:
![image](https://user-images.githubusercontent.com/10614018/44307589-a26bce80-a39c-11e8-98a8-c5ef0671d3ae.png)

which is:
![image](https://user-images.githubusercontent.com/10614018/44307592-aa2b7300-a39c-11e8-811f-927a324bc25f.png)

Would be VERY helpful to have:
![image](https://user-images.githubusercontent.com/10614018/44307611-11e1be00-a39d-11e8-8575-6da799d1ab6c.png)

For the moment I have to grab the string, then split it on the ":" character, however this only works if the actual option name or value doesn't already contain the same character (which has happened). 

using name value pairs would solve a lot of problems. 

I'm aware the values can be pulled from "options_array" column, HOWEVER, this ONLY works if the options have not been modified or deleted. if they have been modified and you reference it then you can get the wrong option/value against the order item.

**Comment by abrookbanks** [comment]
Agreed this could be improved. The whole basket can be found in the order_summary table too as a serialised might be some handy info there. Closing as feature request for now.
