### ISSUE TITLE
Applies tax rate should be stored by line item

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2147]
The tax rate (percentage) applied to each product line should be stored against the ordered items. 

If the tax rate changes, it's handy to quickly see the applied % to an order without needing to work it out.  useful in case of an audit.

**Comment by abrookbanks** [comment]
Agreed. I'm on this.

**Comment by abrookbanks** [comment]
![screenshot 2019-02-07 at 16 27 32](https://user-images.githubusercontent.com/4520803/52426266-89dfa400-2af5-11e9-92a8-9cb0f7a6f860.png)
