### ISSUE TITLE
Discounts - line item

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2148]
It would be very helpful to log at line item level any adjustments based on applied discounts.  For example, if a promotional code was applied which discounted only a single item in the order, against that record in the order inventory table, the actual discount applied and new total would be useful for reference.

Currently this is only recorded at the order summary level, which isn't granular enough for a lot of external, third party integrations.

**Comment by Noodleyman** [comment]
Adding an additional update to capture the reason behind this request.

I am currently working on a solution which will allow CubeCart to interface with cloud based management systems,  multi site management software etc. However, all of those sites and services work on a per SKU basis and then calculate the order totals based on line items, shipping and tax.

This gets complicated in CubeCart, especially when factoring in tax and shipping. Tax is calculated per line item, but only the total tax is stored at the order summary level. If items in the cart contain a mixture of tax rates it's impossible to know what those rates are, unless you go back and re-calculate them from the tax class associated with the inventory. This can cause to discrepancies, especially if you are looking at historic orders and the tax class has changed.

Things then get even more complex when discounts are involved. Discounts can be applied per item, but this isn't reflected on the line items themselves. Instead, the total discount is stored at the order summary level. It's impossible to understand exactly which items had what discounts applied simply by pulling the order summary and order inventory data. 

It may be possible to get the information by looking it up based on the discount code in the order notes, but again if the code is removed or reconfigured then the information is lost.

CubeCart should at the very least capture all of the above on a line item by line item basis, even if it's only for reference otherwise it may be impossible to go back and audit orders which have had both tax and discounts applied.

**Comment by abrookbanks** [comment]
This isn't straightforward. The private method `_applyDiscounts` in `Cart` class will need to be rewritten.

**Comment by Noodleyman** [comment]
This may not be the best way to ask this, but is there a way I can track feature requests which are under consideration, v's those which are denied? Having all feature requests as closed makes it hard to know what is still under consideration for a future version

**Comment by abrookbanks** [comment]
You're always welcome to contribute features. ;)
Features.cubecart.com is the best place.

**Comment by Noodleyman** [comment]
did closed requests like this one get ported to that?

**Comment by abrookbanks** [comment]
It will be found.
