### ISSUE TITLE
Pass by Reference

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#215]
PHP doesn't like this, complains that only variables should be passed by reference:
seo.class.php, line 234:
`$path = array_pop(explode('/', $path));`

It's a Strict Standards notice, so no harm done. Not sure where CubeCart failed to switch off Strict notices.

I prefer to use `'seo_add_cats'` and `'seo_cats_add_cats'` consistently, as opposed to assigning it to a `$category_scope` variable that really is redundant.

**Comment by abrookbanks** [comment]
I'm not not able to reproduce the strict notice error.
