### ISSUE TITLE
Hook and code change request

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2151]
orders.class.php
FIND:
`$GLOBALS['db']->update('CubeCart_order_inventory', array('quantity' => $item['quantity']), array('id' => $stored_items[$hash]['id'], 'cart_order_id' => $this->_order_id));`

REPLACE WITH:
`$GLOBALS['db']->update('CubeCart_order_inventory',$record, array('id' => $stored_items[$hash]['id'], 'cart_order_id' => $this->_order_id));`

AND BEFORE ADD:
```
$record = array('quantity' => $item['quantity']);
foreach ($GLOBALS['hooks']->load('class.order.products.update.pre') as $hook) include $hook;
```

REASON:
This allows for the data being updated in the order inventory table to be manipulated by hooks on cart update.  Essentially, the same way the hook for insert works, but for updates.

**Comment by abrookbanks** [comment]
Thanks. I've added this but its a shame its hook in a loop.
