### ISSUE TITLE
Tax incorrect in CubeCart_order_inventory

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2152]
tax is correctly added to CubeCart_order_inventory when the record is added, but if it gets updated the tax is not revised.  You can replicate this by going through checkout, hitting the payment gateway and then using the back button, revising the quantity and checking out. 

The tax value will always reflect the tax at the time the record was added.

Fixed as follows:
Add this:
https://github.com/cubecart/v6/issues/2151

and then modify the $record:
```
$record = array(
    'quantity'  => $item['quantity'],
    'tax'       => ($item['tax_each'] !== false ? $item['tax_each']['amount'] : 0)
);
```

**Comment by abrookbanks** [comment]
Nice find. Thanks for this Alec.
