### ISSUE TITLE
Error message for class.gui.php line 948 (str_replace require 3 parameters...)

### ISSUE THREAD

**Issue by mike4kz** [cubecart/v6#2155]
Looks like misplaced parentheses:

$dialogue = str_replace('%s', $GLOBALS['config']->get('config', 'store_name', $GLOBALS['language']->notification['cookie_dialogue']));

... should be (???):

$dialogue = str_replace('%s', $GLOBALS['config']->get('config', 'store_name'**)**, $GLOBALS['language']->notification['cookie_dialogue']**)**;

**Comment by abrookbanks** [comment]
Thanks for this.
