### ISSUE TITLE
SagePay Form issue

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2156]
PHP Warning:  Use of undefined constant CLEAN_INPUT_FILTER_TEXT - assumed 'CLEAN_INPUT_FILTER_TEXT' (this will throw an Error in a future version of PHP) in /modules/gateway/SagePay/gateway.class.php on line 238

This is on multiple lines

**Comment by abrookbanks** [comment]
Thanks this is fixed with 1.0.9.
