### ISSUE TITLE
Can't change default language in CubeCart

### ISSUE THREAD

**Issue by Jeroen321** [cubecart/v6#2157]
Hi!
I already posted a similar question, but I think I miswrote the title and question also because unfortunately I got no response.

I think it might be a CC issue what I experience.
I have two CC shops and both CC shops are going haywire when changing the main language.
Both CC shops are up to date (6.2.2) and on different servers.

What happens? After I switch to the English US language as default all the translated documents (filemanager\documents) aren’t working anymore after setting the main language to another default language (store settings).
The language flags are also gone and replaced by a question mark.
The way to get it resolved is by deleting the old database and create a new one and import a fresh backup database.
And replacing the store files with a backup also.

**Comment by bhsmither** [comment]
I think the solution to issue #1956 is contributing to this.

**Comment by Jeroen321-b** [comment]
Thank you for reading my question.
Sorry for not responding sooner.. I will look into it very soon and will let you know.
Thanks again!

**Comment by bhsmither** [comment]
Also look at #2162.

**Comment by Jeroen321-b** [comment]
The solution #1956 does not apply to my shop. The languages (English US and UK) are both installed in the shop and active.
So, next step is #2162 ...

**Comment by Jeroen321-b** [comment]
Do I understand correctly that for now the language setting switch cannot be done with the switch to another language option un CubeCart?

**Comment by bhsmither** [comment]
If allowed, the visitor can switch the store's displayed language for himself by using the Language selector on the storefront page.

We are currently working on ways to make sure the appropriate documents are displayed.

**Comment by Jeroen321-b** [comment]
Great that you are currently working on it :) 
Yes, I do have the option in the shop that visitors can use the language selector, but many thanks for helping me by pointing to this option.

**Comment by abrookbanks** [comment]
See https://github.com/cubecart/v6/issues/2162 which should resolve this one. Please note that if the child/parent relations are already broken it won't fix it. 

Massive thanks to Brian!!
