### ISSUE TITLE
Unneeded Link

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2158]
Line 160 of `documents.index.inc.php` is creating a delete link.

However, this link is also created and displayed when **adding a new translation**.

There is
```
unset($document[0]['doc_id'])
```
 which causes
```
array('delete' => $data['doc_id']
```
to not appear in that link, making the link ineffectual and pointless.

**Comment by abrookbanks** [comment]
Took me a while to get my head round this one. Great find. Thanks.
