### ISSUE TITLE
mysql error when you click the button 'CLEAR CACHE'

### ISSUE THREAD

**Issue by aaaple2010** [cubecart/v6#2159]
it report that server error '500' when you click 'CLEAR CACHE',i find the error log,it report mysql syntax error.

[Aug 22 2018, 03:42 am] File: [maintenance.index.inc.php] Line: [454] " TABLE `store1_CubeCart_sessions`; " - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TABLE `store1_CubeCart_sessions`' at line 1

[Aug 25 2018, 03:41 am] File: [catalogue.class.php] Line: [1877] "SELECT I.* FROM store1_CubeCart_inventory AS I LEFT JOIN (SELECT product_id, MAX(price) as price, MAX(sale_price) as sale_price FROM store1_CubeCart_pricing_group WHERE group_id = 0 GROUP BY product_id) as G ON G.product_id = I.product_id WHERE I.product_id IN (SELECT product_id FROM `store1_CubeCart_category_index` as CI INNER JOIN store1_CubeCart_category as C where CI.cat_id = C.cat_id AND C.status = 1) AND I.status = 1 AND (I.name RLIKE '[[:<:]]SvTQ.')(.((("([[:>:]]' OR I.description RLIKE '[[:<:]]SvTQ.')(.((("([[:>:]]' OR I.product_code RLIKE '[[:<:]]SvTQ.')(.((("([[:>:]]') " - Got error 'parentheses not balanced' from regexp

**Comment by abrookbanks** [comment]
Clearing the cache has no correlation to any MySQL query. Please check your PHP error log to find out what the actual PHP error is and open a support ticket or ask on our forums if you need further help. 

This may be fixed by manually emptying the ./cache folder and upgrading to the latest version.
