### ISSUE TITLE
Illegal String Offset

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#216]
Please check `Catalogue->displayProductOptions()` where `case self::OPTION_TEXTAREA`.

Six lines down, $value is presumed to be a string.

Fifteen lines after that, is:
```
if($option[0]['option_price']>0 && $option[0]['option_negative'] == 0) { 
  $this->_options_line_price +=  $option[0]['option_price'];
} elseif($value['option_price']>0) { 
  $this->_options_line_price -=  $option[0]['option_price'];
}
```
`$value['option_price']` was probably supposed to be `$option[0]['option_price']`.

**Comment by abrookbanks** [comment]
Fixed. I wish some of the variable names were more uniform though. Lack of planning...
