### ISSUE TITLE
Verify Database Action

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2160]
In `maintenance.index.inc.php`, code beginning line 444, suggest that `$_POST['action']` be tested against an enumerated list of valid commands. (Do not want TRUNCATE to mysteriously be POSTed.)

Also use this list of valid commands to create the drop-selector:
From:
```
<option value="OPTIMIZE">{$LANG.settings.optimize}</option>
<option value="REPAIR">{$LANG.settings.repair}</option>
<option value="CHECK">{$LANG.settings.check}</option>
<option value="ANALYZE">{$LANG.settings.analyze}</option>
```
To something like:
```
{foreach $DB_MAINT_CMDS as $cmd}
<option value="{$cmd.action}">{$LANG.settings[$cmd.action]}</option>
{/foreach}
```

**Comment by abrookbanks** [comment]
That's a great one thanks!
