### ISSUE TITLE
Advisory to Update Currency Rates

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2161]
Suggest putting an advisory message next to Store Settings, General tab, Default Currency that, after changing this to some other currency, to visit the Currencies admin page to update exchange rates.

This is because it seems all that changing the default currency does is to `DB->update` the `value` to 1.0, without regard to any other existing exchange rate value.

**Comment by abrookbanks** [comment]
Thanks!! :)
![screenshot 2019-01-31 at 16 20 56](https://user-images.githubusercontent.com/4520803/52068300-4eccf600-2574-11e9-8ced-b2975a364963.png)
