### ISSUE TITLE
Change Default Language - Swap Documents P/C Relationship

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2162]
For your consideration:

Also, in regards to an edit with respect to: #1956.

When choosing a different default language, code in settings.index.inc.php will set all documents to that language code regardless of the language it is written in. It then removes the language code from all children.
```
$existing_defaults = $GLOBALS['db']->select('CubeCart_documents', 'doc_lang', array('doc_parent_id' => 0), false, 1);
if($existing_defaults[0]['doc_lang'] !== $config_new['default_language']) {
	$GLOBALS['db']->update('CubeCart_documents', array('doc_lang' => $config_new['default_language']), array('doc_parent_id' => 0));
	$GLOBALS['db']->update('CubeCart_documents', array('doc_lang' => ''), 'doc_parent_id > 0');
}
```

I disagree with this. (Unless the code has a mistake in its logic.)

Following is code that will look through all parents to find those that have a child of the new language. If found, all children of the old parent become children of the new parent, the child having the new language becomes the new parent, and the old parent becomes a child of the new parent.

This then has the effect of now showing parent documents to include those in the new default language, showing translated (child) documents if the store visitor switches to an alternate language, and proper language identification in admin, Documents.
```
// Switch US to ES
$wasLang = $config_old['default_language']; // "en-US"
$nowLang = $config_new['default_language']; // "es-ES"
$make_parent = 0;
$make_child = 0;

$docs = $GLOBALS['db']->select('CubeCart_documents',false,array('doc_lang' => $wasLang, 'doc_parent_id' => 0)); // doc_ids: 1,2,3,4,7,8
if($docs){
	foreach($docs as $doc){  // array('id'=>1,'parent_id'=>0,'lang'=>"EN")
                                                // array('id'=>2,'parent_id'=>0,'lang'=>"EN")
                                                // array('id'=>3,'parent_id'=>0,'lang'=>"EN")
                                                // array('id'=>4,'parent_id'=>0,'lang'=>"EN") ** Has ES child
                                                // array('id'=>7,'parent_id'=>0,'lang'=>"EN")
                                                // array('id'=>8,'parent_id'=>0,'lang'=>"EN")

		$children = $GLOBALS['db']->select('CubeCart_documents', false, array('doc_parent_id' => $doc['doc_id'])); // 6
		if($children){
			foreach($children as $child){ // array('id'=>6,'parent_id'=>4,'lang'=>"ES") ** Is ES child to this parent

				$to_have_new_parent[] = $child['doc_id']; // 6, etc
				// Find child having $nowLang
				if($child['doc_lang'] = $nowLang){
					$make_parent = $child['doc_id']; // 6
					$make_child = $doc['doc_id'];	// 4
				}
			}

			// If swap is to be made...
			if(!empty($make_parent)){
				$GLOBALS['db']->update('CubeCart_documents', array('doc_parent_id' => $make_parent), array('doc_id' => $to_have_new_parent)); // 6, etc:'parent_id'=>6
				$GLOBALS['db']->update('CubeCart_documents', array('doc_parent_id' => 0),            array('doc_id' => $make_parent)); // 6:'parent_id'=>0
				$GLOBALS['db']->update('CubeCart_documents', array('doc_parent_id' => $make_parent), array('doc_id' => $make_child)); // 4:'parent_id'=>6
			}
		}
	}
}
```
The EN document that has an ES child is now a child to that ES document that is now a parent. Other siblings in that family also now recognize the new parent.

**Comment by abrookbanks** [comment]
I wasn't able to get this to work. Maybe you could make a pull request?

**Comment by abrookbanks** [comment]
I got it working well. Thank you. There is however a related bug on creating a translation I'm looking at now..

**Comment by abrookbanks** [comment]
I take that back. It's not working at all... still looking at this.

**Comment by abrookbanks** [comment]
Works well for two languages but falls apart with more than that. Real brain bender this one.
