### ISSUE TITLE
ajaxNewsletter() Could Infinite Loop

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2164]
If a newsletter config setting has 'dbl_opt' enabled, but no records have `'dbl_opt' = "1"`, the `Ajax::search('newsletter')` will return `{'error':'true'}`.

In admin.js, `ajaxNewsletter()`, there is no code to handle this specific return. Instead, this function recurses -- infinitely.

**Comment by abrookbanks** [comment]
Thanks.
