### ISSUE TITLE
Cannot update currencies 6.2.2

### ISSUE THREAD

**Issue by richosr** [cubecart/v6#2165]
Everything was fine until today and now every attempt to update currencies fails.

Error log shows:

  | Today, 07:11 | [Exception] 	/home/richoso2/public_html/newshop/admin_*******/sources/settings.currency.inc.php:37 - String could not be parsed as XML

regards
Steve

**Comment by bhsmither** [comment]
Put this in your browser address bar, and see what shows:
http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml

I just did, and I got (what looks like) a valid XML string.

Maybe there was a temporary glitch between your server and the bank.

Also, in admin, Request Log, see if there is an entry for the attempt to get the rates. Examine the **Response recieved**.

**Comment by richosr** [comment]
I get the valid XML in the browser , I tried that already. But still cubecart won't process it.

**Comment by bhsmither** [comment]
Also, in admin, Request Log, see if there is an entry for the attempt to get the rates. Examine the Response received.

**Comment by richosr** [comment]
I just edited the code and changed the location of the xml to a local folder on my host and downloaded the xml to there.

It then processes OK.

	if (($request = new Request('www.**********.co.uk', '/_private/eurofxref-daily.xml')) !== false) {
		$request->setMethod('get');
		$rates_xml = $request->send();

**Comment by richosr** [comment]
The response log does not show any requests for the rates either when requested from eurofx or locally.

**Comment by bhsmither** [comment]
That's odd.

**Comment by bhsmither** [comment]
Check your PHP environment to determine if the version of PHP has been upgraded without your knowledge. In admin, PHP Info.

If so, make sure that CURL is enabled. If so, there will be a table for it.

If the Request class cannot use CURL, it will try to use `fsockopen()`.

In either case, there will be a log entry. (see next comment.)

If the Request class cannot get the response, CubeCart will then try `file_get_contents()`.

**Comment by bhsmither** [comment]
I think it is not getting logged because there is no `_request_body`.

**Comment by richosr** [comment]
I have raised a ticket with my host and hopefully they can get information from the server log.
Thanks for your help.

I will update the thread when I hear back from them.

**Comment by bhsmither** [comment]
I think I have the real reason:

The Request class has commented out this statement at line 80:
```
/*$this->_curl_options[CURLOPT_FOLLOWLOCATION] 	= true;*/
```
The Request class is defaulting to:
```
private $_request_protocol  = 'http';
```
The bank is responding with:
```
HTTP/1.1 301 Moved Permanently
Server: myracloud
Date: Fri, 07 Sep 2018 07:54:58 GMT
Content-Type: text/html
Content-Length: 177
Connection: keep-alive
Location: https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml
```
I believe, because of the current push to make everything `https`, the fail is happening because CURL is not making a follow-on request to the secure version of the URL.

So, in settings.currency.inc.php, find:
```
if (($request = new Request('www.ecb.europa.eu', '/stats/eurofxref/eurofxref-daily.xml')) !== false) {
  $request->setMethod('get');
  $rates_xml = $request->send();
```
Change to:
```
if (($request = new Request('www.ecb.europa.eu', '/stats/eurofxref/eurofxref-daily.xml')) !== false) {
  $request->setMethod('get');
  $request->setSSL();
  $rates_xml = $request->send();
```
A few lines later, find:
```
$rates_xml = file_get_contents('http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml');
```
Change to:
```
$rates_xml = file_get_contents('https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml');
```

**Comment by richosr** [comment]
Yes that fixed it Thanks very much.

That will need to be updated in a new version - I think.

regards
Steve

**Comment by abrookbanks** [comment]
Confirmed working now.

**Comment by havenswift-hosting** [comment]
This solution fixes the protocol issue and enables rates to be fetched correctly but the "Last Updated" date always shows "Yesterday 00:00"

**Comment by jahrralf** [comment]
Same on my server (which is not using cubecart). I can't download the XML with wget, no connection, time out. I think they blocked me. Is cubecart loading the XML very often? If yes, they might have stricter policies now...
