### ISSUE TITLE
Deprecated Messages in Log

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2168]
See:
https://forums.cubecart.com/topic/54316-error-log-query/

Suggest:
In the file ini.inc.php, near line 19:
```
From:
error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING);

To:
error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED);﻿
```
﻿In the file /controllers/controller.index.inc.php, near line 37:﻿
```
$GLOBALS['smarty']->error_reporting = E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED;﻿
﻿﻿```
This is specific to Smarty. We can change this,﻿﻿ but as yet, it is not really necessary (to the best of our knowledge).

**Comment by abrookbanks** [comment]
Thanks

**Comment by havenswift-hosting** [comment]
The problem with this solution is that the first anyone will find out about changed or removed functions in PHP is when a program crashes - recent case in point is deprecated message in SagePay payment gateway under 7.1 which would have crashed it under 7.2

**Comment by abrookbanks** [comment]
Yes totally agree. I'm tired and not thinking straight today.
