### ISSUE TITLE
Invoice Editor URL

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2170]
Inconsequential:

In /admin/sources/documents.index.inc.php, near line 189:
```
$GLOBALS['main']->addTabControl($lang['orders']['invoice_editor'], '_blank','?_g=documents&node=invoice');
```
In the above, the second argument is not correct. And it is not semantically correct, either.

This argument is actually to have the browser scroll to the named anchor, or specifically for CubeCart, to the non-default `<div class="tab_content">` having that `id`.

Since there isn't a non-default `<div>`, this argument should be `null`.

**Comment by abrookbanks** [comment]
Thanks.
