### ISSUE TITLE
Zones Tabs to be at End of Array

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2172]
For modules that wish to have zones control, the class instantiation is:
```
$module = new Module(__FILE__, $_GET['module'], 'admin/index.tpl', true, false);
```
where the fourth argument has CubeCart show the "Allowed Zones" and "Disabled Zones" tabs in Tab Control.

However, should the module **also** wish to add it's own tab to Tab Control via `Main->addTabControl()`, it will appear after the Zones tabs. (Using the hook `admin.tabs` is not much better - one would need to make a thorough examination of the existing array.)

The placement of the new tab after the Zones tab may not be desirable.

Suggest in `Module->__construct()` these two changes:
```
$GLOBALS['main']->addTabControl($GLOBALS['language']->settings['allowed_zones'], 'zone-list', null, null, count($enabled_countries),'',999999);
and
$GLOBALS['main']->addTabControl($GLOBALS['language']->settings['disabled_zones'], 'disabled-zone-list', null, null, count($disabled_countries),'',999999);
```
By setting the priority to a ridiculously high number, then the `ksort()` at `Main->showTabs()` will have the Zones tabs at the end of the array.

**Comment by abrookbanks** [comment]
Thanks!!!! ;P

**Comment by havenswift-hosting** [comment]
Excellent - that has bugged me for years !
