### ISSUE TITLE
CSRF Token vs 2Checkout Gateway

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2174]
See:
https://forums.cubecart.com/topic/54328-2checkout-gateway-not-working-anymore/

2CO docs say to not use an optional parameter from any of their parameter sets. See "Custom Parameters" from:
https://www.2checkout.com/documentation/checkout/parameters/

With CubeCart now appending `token=SESSION_TOKEN` into every form at `GUI->display()`, this (unconfirmed, but likely) results in 2CO objecting to the POST request. The "token' keyword is used in 2CO's parameter set for the Payment API (https://www.2checkout.com/documentation/payment-api/create-token).

Suggestion:
Have the gateway class temporarily switch off `Config['csrf']`. This will require additional work in the Config class.

**Comment by abrookbanks** [comment]
Dropping in `$GLOBALS['config']->set('config', 'csrf', '0');` works well. Thanks 1.0.2 fixes this.
