### ISSUE TITLE
2Checkout Anomaly

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2176]
This extension declares the private property `$_config` and uses it on line 62:
```
'lang' => (strtoupper(substr($this->_config['default_language'],0,2))=='ES') ? 'sp' : 'en',
```
but does not assign by reference in `__construct()`.

**Comment by abrookbanks** [comment]
Fixed with 1.0.1. Thanks. I'm aware of the other issue around 2CO so I'll have a look at that and see if we can get another release out soon.
