### ISSUE TITLE
Issue with payment gateways and custom OID

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2177]
$this->_basket only contains 'cart_order_id', and does not contain custom_oid if it's enabled. this causes the order number shown in any gaateway to be wrong and is causing confusion.

if custom order numbers are enabled, cart_order_id should be populated with the customer order number and sent to the module, otherwise every single payment module needs to be revised.

**Comment by Noodleyman** [comment]
Summing up again, at the root of the issue, CubeCart uses two order ID's if you have custom order numbers enabled, but almost every payment system only supports ONE. If you feed the custom OID to the module, the displays work correctly, but the remote call back to the store won't match order ID to the internal OID, thus order will be stock on processing.

The only "fix" I can see is a total overhaul of custom order numbers, although there are a few custom code work arounds.

**Comment by abrookbanks** [comment]
I think we have to put this down to a downside of the custom order ID for now. I hope we can revisit it but the implications for change are significant.

**Comment by mmagalla** [comment]
Can at least the Custom Order Id be displayed as   / Custom Order Id: xxxxxxx alongside the other order number as a temporary workaround?

**Comment by mmagalla** [comment]
Or can the  OrderId field and language text be hidden and the Custom Order Id  and its language text be visible. Kind of toggling the two values visibility but keeping the internal call with the order number?  Not super elegant but an easy workaround in my opinion.
