### ISSUE TITLE
Stock warning for product with Product option matrix went havoc [6.2.1]

### ISSUE THREAD

**Issue by bos4711** [cubecart/v6#2178]
I used to have a product which I tested product matrix on in earlier days, but decided to scrap that and use a plain product instead.

Now, when the product is out of stock, the Stock Warning went totally havoc despite the matrix is cleared.

![product_options](https://user-images.githubusercontent.com/11036018/45646154-125f9880-bab2-11e8-843d-ece2b0e186ca.png)
![stock_warnings](https://user-images.githubusercontent.com/11036018/45646159-155a8900-bab2-11e8-9ddd-c79dab743abc.png)

**Comment by abrookbanks** [comment]
Yuk! I don't think I can do anything unless I have clear steps to reproduce this. Happy to reopen if you can provide that. Sorry II can't be more help.
