### ISSUE TITLE
RFE: Sitemap for other languages...

### ISSUE THREAD

**Issue by mike4kz** [cubecart/v6#2179]
In addition to lack of "seo URLs" for other languages, existing URLs are not exported to the sitemap.xml. When you switch a language, system accepts "seo_urls" for a translated documents (About Us, Contact, Terms, etc.), however they are not exported to the sitemap. Perhaps it's "feature enhancement" (part of SEO update), but want to present the idea.

**Comment by mike4kz** [comment]
Found where to turn it off (if needed):
classes/class.seo.php [line: 746]
Replace this:
`# 'document' => $GLOBALS['db']->select('CubeCart_documents', array('doc_id'), array('doc_parent_id' => '0', 'doc_status' => 1)),`
with this:
`'document' => $GLOBALS['db']->select('CubeCart_documents', array('doc_id'), array('doc_status' => 1)),`

Generally, by default system exports only documents with doc_parent_id=0. All "translations" have "doc_parent_id" equal to their "default language" product.

**Comment by mike4kz** [comment]
Theoretically, without modifying a code, it's possible to do it through the "class.seo.sitemap" hook, just add it to `$this->_sitemap_link();`.

**Comment by abrookbanks** [comment]
CubeCart doesn't support language specific SEO at this time. A feature request is open for this. :)
