### ISSUE TITLE
Issue with admin permissions and promotional codes

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2180]
There is a mismatch of security rules. in earlier CubeCart versions an admin needed at least read access to 'documents', and permissions to edit/create are linked with 'documents'.

To delete, the permission is linked with 'products'.

In the later versions of CubeCart the 'documents' group was swapped out with 'settings', which kind of makes sense. the problem is if you want an admin to modify promotional codes you have to open up your store settings to them.

Please can this be changed, perhaps adding a new security group and making permissions more granular. In an ideal world, the admin area should be able to be locked down with view/edit/delete permissions across every possible screen and implement security groups.

**Comment by abrookbanks** [comment]
I agree that this needs to be more granular. Settings access isn't good enough. Products access is too much. 

I've put this as a feature request. I agree that every page should have access writes. Maybe it could even be configurable to page/input type somehow. Closed.. for now.
