### ISSUE TITLE
Custom Dashboard Tasks - Sort order

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2181]
related with:
https://github.com/cubecart/v6/issues/2171

It would be handy if all of the dashboard items are sent to the admin theme , rather than having them hard coded into the theme itself. This means that a sort order could then be applied, or modified via hooks, meaning items can be arranged as required and custom items placed in a desired location within the list of links.

Please can this be added?

**Comment by bhsmither** [comment]
Would this solve any dilemmas not solvable by creating a custom admin skin -- which is entirely do-able -- just as one would create a custom front-side skin?

**Comment by Noodleyman** [comment]
That comes with it's own Down sides. Every upgrade you need to remake the
custom theme to get the new settings/features and updates, which is less
desirable.

**Comment by bhsmither** [comment]
Such is the curse we must all live with respecting said skins - admin and front-side.

**Comment by Noodleyman** [comment]
So true. But this change would make it so we can avoid it in some cases
with the use of hooks ;)

**Comment by havenswift-hosting** [comment]
>Such is the curse we must all live with respecting said skins - admin and front-side.

Not if there is an easy and neat solution to prevent that.  It is enough of a pain when having to do this for your own single store but when you are supporting tens or many hundreds as we do, then this becomes a major PITA.  In an ideal world, no core files would ever need to be changed and far too many "solutions" to problems offer this as a solution - sometimes it is unavoidable, but lets try to avoid them when we can.  Many applications have admin panels that are drag and drop so each user can easily re-arrange or hide the blocks /item that they want - now that would be a better solution !

**Comment by abrookbanks** [comment]
I like this. :)
