### ISSUE TITLE
SEO tab on the product translation...

### ISSUE THREAD

**Issue by mike4kz** [cubecart/v6#2183]
Found that the product translation already has all SEO fields in the database. Default admin template also has all necessary to fill these fields. However "content" was not accessible due to the missing tab. 

In the file `admin/sources/product.index.inc.php line 674` (just before the line `$GLOBALS['smarty']->assign('DISPLAY_TRANSLATE_FORM', true);`) added:

`$GLOBALS['main']->addTabControl($lang['settings']['tab_seo'], 'seo');`

Now product translation has "Search Engines" tab, and it's propagated to the database. 

After this, all SEO information (description, keywords) are properly propagated to the page.

**Comment by abrookbanks** [comment]
CubeCart doesn't support language specific SEO at this time. A feature request is open for this. :)
