### ISSUE TITLE
Product gallery images not rendered correctly after #1449

### ISSUE THREAD

**Issue by humantex** [cubecart/v6#2184]
I've copied the default Foundation skin to use as my site's default, and have only been changing CSS styling and some minimal HTML rearranging. Up till now I've been using the underlying code for the image gallery.

Whether choosing to use that as a vertical or horizontal gallery by swapping the includes doesn't matter, it will still distort image aspect ratios for some product images. If every image I loaded was the same ratio, it wouldn't be an issue. However, that will not be the case for me - and I suspect a large number of other CC users. Even if I shot/edited/resized my photos to create the original/large image I upload as product images (and, I do), I will NEVER end up with suitable images that are always the same aspect ratio for everything I'll list. If I were using images supplied by a number of vendors, or using manufacturer supplied photos... I'll guarentee that there won't always be an exact match in aspects, and the product image results would be horrendous.

![screenshot from 2018-09-19 15-16-21](https://user-images.githubusercontent.com/16087649/45775848-06ddb000-bc1f-11e8-9cf2-fd42b22b9645.png)

The issue is caused by one single line in "2.cubecart.js".

`$('a.open-clearing img').css({'min-height':ip_height+'px', 'max-height': ip_height+'px'});`

It is absolutely impossible to force any css style override for sizing on any element when the styling is voided by embedded style-statements in the element itself.

I understand that this was an attempt to fix the 'Bouncing' in issue #1449 but the fix as-it-is, goes against any notion of proper responsive image handling. The only logical way to do that is not to use element values for anything dealing with either height or width, and that's exactly what's happening when an event loop in the gallery's js code is spitting out rewrites to element code with every mouse hover. Some might see the fix as a solution, yet it's only introduced a new bug that was preventable.

To fix the so-called bouncing issue refereed to above, I'd suggest that no code be in place to manipulate image sizes/widths/heights, and instead, manipulate the container element for the gallery component itself.

Force that container div to whatever size is appropriate for any device's display with a 'min-height/max-height' value, and leave the images unmanipulated. Optimize the container for size, and let the images then fill it (as per CSS styles) as-needed. Use whatever cached version of resized images are needed to optimize the page size per the device serving it, but I'd suggest for the default CC skin you'd leave the actual responsive display of images to CSS where it belongs.

Until I can fix the container 'bounce', I'll remove the line of code in the script. I'd even prefer the bounce effect, than looking like an idiot photographer who finds it acceptable to post squished images on his product pages, or to end up reshooting/re-editing photos to all be identical in size and ratio.

**Comment by abrookbanks** [comment]
Do you think you could attache the original images used in the gallery so I can try to reproduce this?

**Comment by humantex** [comment]
I'll be glad to make them available. Rather than add them as attachments, I've added them all to a folder in my Drive account to view/download. These are the original hi-res full size images - as-uploaded as the product images shown above. They are all 1600x1600px, with the exception of the 'hero' shot, which is 1600x975px.

I've standardized on using a 1600px image width as the better choice for viewing on 2k HD screens and Retina displays, and be resized for caching without detail loss for anything smaller. They can also scale up reasonably well in case the viewing device has a 4k capable display.

All 5 images: https://drive.google.com/open?id=1SY9_M7Mg91VPsMt7_ZBYr6ncKdQ5V7KC

Here's the link to the working page for these - which has had the js line removed, but I've yet to modify the script to address the 'bounce' issue.... https://4sale.lumiworx.com/lenses/canon-fd-55mm-f-1-2.html

I will at some point be reworking the featured items in the sidebar, to be either smaller or relocate the sidebar entirely... so the product gallery will be larger than it currently is, to take better advantage of the hi-res images. In my case, the photos and their presentation of detailed condition are the 'salesman' for anything I'll list, so they have to be unmanipulated in their aspect ratio.

**Comment by humantex** [comment]
After a bit of experimentation, I've found - quite by accident - a solution to both the squished image and the content 'bounce' when changing gallery images.

The first thing I did was to include a new outer div around the entire gallery, so the section that inserts the vertical (or horizontal) gallery inside `content.product.php` now looks like this:
```
      <div id="gallery-outer-div">
      {*
         Change include below to 'templates/element.product.horizontal_gallery.php'
         for horizontal gallery and vice versa.vertical_gallery
      *}
      {include file='templates/element.product.vertical_gallery.php'}
      <hr>
      </div>
```
After that addition I had an element that I could size without trying to adjust the gallery images, so they'd be free to resize with responsive CSS.

Added CSS for `#gallery-outer-div`:
```
#gallery-outer-div {
    width: 100%;
}
#gallery-outer-div .small-7.medium-5.columns.thinpad-left {
    max-width: 250px;
    float: left;
}
#gallery-outer-div {
    height: auto;
    transition: max-height 2.8s;
    max-height:1000px;
}
```
Modified and added for `#img-preview` CSS:
```
.horizontal a.open-clearing #img-preview {
	max-width: 100%;
	max-height: 100%;
}
#img-preview {
	max-width: 100%;
	height: auto;
}
#img-preview {
	height: unset !important;
	width: unset !important;
	max-width: 100%;
	height: auto !important;
	margin-left: auto;
	margin-right: auto;
}
@media only screen and (max-width: 400px) { 
#img-preview {
	margin: 17px;
	max-width: 100% !important;
	height: auto !important;
}
}
```
I tried to solve the bounce issue by introducing the CSS transform for the outer gallery div, but it was pretty flakey and wouldn't trigger on a height:auto value on the div without some way to introduce a toggle element - so - I went back to the 2.cubecart.js and made the following change to the whole code block.
```
    if($('a.open-clearing img#img-preview').length) {
        $('a.open-clearing img#img-preview').load(function() {
            var ip = $('a.open-clearing img#img-preview');
            var ip_height = ip.height();
            var ip_width = ip.width();
            var min_height = ip_width * 1.07;
            if(ip_height<min_height) {
                ip_height = min_height;
            }
            $('#gallery-outer-div').css({'min-height':ip_height+'px', 'max-height': ip_height+'px'});
        });
    }
```
The intent was to get the transform to fire, but instead, it seems to have created a fixed-size for the outer div on the gallery. I'm guessing that part of that occurred because of my changing the calculation multiplier above to 1.07, instead of the original 0.7.

I'll live without the transform for now, and find a better fix for myself later. I don't know what, if any of this, will be useful to anyone else - but - given the large size of my images, and the requirement of having proper aspect ratios, it's a fix I can live with.

**Comment by abrookbanks** [comment]
I haven't looked at the fixes proposed above yet but the following seems to work well adding a #open-clearing-wrapper to the hyper link.

```
if($('a.open-clearing img#img-preview').length) {
        //$('a.open-clearing img#img-preview').load(function() {
            var ip = $('a.open-clearing img#img-preview');
            var ip_height = ip.height();
            var ip_width = ip.width();
            var min_height = ip_width * 0.7;
            if(ip_height<min_height) {
                ip_height = min_height;
            }
            $('a.open-clearing img').css({'max-height': ip_height+'px'});
            $('#open-clearing-wrapper').css({'min-height':ip_height+'px', 'max-height': ip_height+'px'});
        //});
    }
```
