### ISSUE TITLE
Admin skin correction required...

### ISSUE THREAD

**Issue by mike4kz** [cubecart/v6#2185]
I had an issue before, than the category translation was not showing and not saving "seo_url" and "keywords" to the database.

Found that field names in `admin/skins/default/templates/categories.index.php` need to be changed:

`<input type="text" name="seo_path" id="seo_path" class="textbox" value="{$TRANS.seo_path}">`
to 
`<input type="text" name="translate[seo_custom_url]" id="seo_path" class="textbox" value="{$TRANS.seo_custom_url}">`

and:

`<textarea name="translate[cat_meta_keywords]" id="seo_meta_keywords" class="textbox">{$TRANS.seo_meta_keywords}</textarea>`
to 
`<textarea name="translate[seo_meta_keywords]" id="seo_meta_keywords" class="textbox">{$TRANS.seo_meta_keywords}</textarea>`

**Comment by abrookbanks** [comment]
CubeCart doesn't support language specific SEO at this time. A feature request is open for this. :)
