### ISSUE TITLE
Dont display download items for cancelled orders

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2187]
If a user or admin cancels an order, digital items are still shown on the users account download page.  While they cant be downloaded, wouldnt it be a better UX to not display them there ?

**Comment by bhsmither** [comment]
I slightly disagree. As a customer, I would like to see the download link struck through, and the download button label say 'Order Cancelled', or 'Loss of License' (I'm looking at you, iTunes!). That is, show the state of the digital download availability before attempting to download it, but do not hide it with no explanation.

**Comment by abrookbanks** [comment]
Thanks guys this is a good one. It will disable download links unless the order status us processing or complete.
![screenshot 2019-01-25 at 10 51 05](https://user-images.githubusercontent.com/4520803/51741567-3ac65780-208f-11e9-9901-97ed87f30565.png)
