### ISSUE TITLE
Zendesk Chat Plugin

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2188]
This plugin causes a fatal error under certain (reasonably common) conditions

With the plugin enabled, if invalid login details are entered, on clicking login, the "Invalid username or password" error message is not shown but uses are shown a blank white screen as the following error is thrown

[Exception] /home/XXXXXXXX/public_html/classes/user.class.php:244 - Call to a member function setError() on null

**Comment by abrookbanks** [comment]
Thanks Ian! Fixed with 1.0.1.
