### ISSUE TITLE
Category Status Query Enhancement

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2189]
In `Catalogue->getCategoryStatusByProductId()`, the query includes `ORDER BY CI.product_id`.

Because the function argument represents only one product, it makes no sense to sort the query on the product_id.

However, one can benefit from having the query `ORDER BY CI.primary DESC` such that
```
Catalogue->getCategoryStatusByProductID($product_id)[0]
```
will always be the primary category.

**Comment by abrookbanks** [comment]
Great find. I thought dropping in a LIMIT of 1 would further improve it but we may need a deeper recordset.
