### ISSUE TITLE
Thumbnail quality when viewing product images

### ISSUE THREAD

**Issue by NaturalSigns** [cubecart/v6#219]
I'm not sure if there is a setting for this somewhere but the default quality on the gallery thumbnails  (along the bottom) is really poor (in my opinion). Example shown below. Rob.

![thumbnail quality](https://cloud.githubusercontent.com/assets/10531097/6186668/61335ada-b374-11e4-9151-4db6beb4802a.png)

**Comment by abrookbanks** [comment]
Nice easy one :)
