### ISSUE TITLE
any admin with edit rights can self elevate permission

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2190]
Raising this as something to be reviewed. As a small business owner, you may want to delegate a staff member to be able to reset passwords, or create/remove admins as required, but also have them not be able to change store settings.

however, any admin with this permission can modify their own user account and give them self access to everything, essentially making them a super admin. 

It's presumed than an admin without super rights should not be able to self-elevate their own permissions, but currently today it is possible which is a security concern.

**Comment by abrookbanks** [comment]
Totally agree. Thanks for this.
