### ISSUE TITLE
FCK Editor, image selection "You do not have the correct privileges to perform that action"

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2191]
An administrator account who has "Read" and "Edit" rights for File Manager is shown the warning "You do not have the correct privileges to perform that action" when browsing images via FCK editor to include in a product description. The admin is able to select and use the images correctly.

If the user is given "Delete" access, the warning does not appear

**Comment by abrookbanks** [comment]
Thanks Alec

**Comment by abrookbanks** [comment]
See: https://github.com/cubecart/v6/commit/a0ff9d6772a53cdbd28c672927f341c9830d8cb9 wrong issue ID added there.
