### ISSUE TITLE
Fetch Rates does not work after upgrade from 6.2.0 -> 6.2.2

### ISSUE THREAD

**Issue by demand73** [cubecart/v6#2192]
After upgrading from 6.2.0 -> 6.2.2 Fetch Rates does not work any more and worked before the upgrade.

I just get a white page after pressing the button and my error log says:
"PHP Warning:  SimpleXMLElement::__construct()"

Has anything changed with Fetch Rates?

Regards
Krister

**Comment by demand73** [comment]
Sorry i did not check closed issues before writing this. Did find issue 2165 that solves this problem.

**Comment by abrookbanks** [comment]
Duplicate of #2165

**Comment by abrookbanks** [comment]
Ignore "Fixed file permission logic" accidental typo in commit.
