### ISSUE TITLE
Added Product to Cart is Corrupted

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2193]
Still tracing this one:

Best to have completely separate sessions between admin and customer, although I am not 100% positive this is necessary.

Enable debugging.

1. Customer signs in and puts items in basket - four different things, for example.
2. Customer gets to Checkout and selects a gateway.
3. Customer logs out.
4. Admin changes the stock level of the fourth item to zero. Clear cache.
5. Customer logs in, goes to Checkout, and clicks Update Basket.
6. CubeCart notifys that the zero-stock item has been removed. Verify in the debug section.
7. Admin changes the stock level back to non-zero. Clear cache.
8. Customer clicks to add the product back into the cart.
9. The shopping basket flyout appears with product not added.
10. Customer goes to Checkout, the product is not listed.
11. Debug section has only the hash and one other property of that item.

**Comment by bhsmither** [comment]
This next experiment, I accidentally failed to clear the cache at step 4, but I think it does not actually matter.

It is at step 6 that the debug section reveals the out-of-stock item has not been properly removed from the `basket{'contents']`, or that some parts of that item are being erroneously added back in:
`'hash'=>['quantity'=>1,'total_price_each'=>33]`

The hash being present in `basket['contents']` will have CubeCart just increase the quantity.

My analysis so far indicates that `Cart->update()` calls `remove()` which in turn calls `update()` for itself. This second time through processes POST which adds some data back into the `basket`. (More thorough tracing is needed.)

**Comment by bhsmither** [comment]
In `Cart->update()`, if an item must be removed, `Cart->remove()` is called.

`remove()` unsets the item from the basket, saves the basket, then exits with the result of calling `update()`.

`update()` does its whole thing, and code execution returns to the next statement after `remove()`.

Note that at this point, we are still working on the `$hash` that was removed.

Thus, lines 1108:
```
$this->basket['contents'][$hash]['quantity'] = (int)$quantity; // or ceil($quantity);
```
and 1112:
```
$this->basket['contents'][$hash]['total_price_each'] = ($pprice+$this->basket['contents'][$hash]['option_line_price']);
```
adds back into the `basket['contents']` values for specific properties of this `$hash`.

Suggest (but not yet verified) that after `remove()` is called at line 1101, abandon all further processing of that `$hash` by `continue`ing out of the `foreach($_POST['quan'])` loop.

**Comment by abrookbanks** [comment]
@bhsmither - You are a genius. Fabulous clear steps to reproduce. Thanks so much.
