### ISSUE TITLE
Digital download reset link issue

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2194]
If a store has a time period set for "Download expiry time" and then removes this so there should be no expiry time on downloads there are two problems.

a) If the admin user edits an order with a digital product with an expiry time that was original set, clicks to Reset, the new time for expiry is the current time whereas there should be no expiry set.

b) If the download expiry time setting is changed, it would be very useful to have a function that allows for all digital products on orders in the system to be updated with the new expiry time.

While testing this, also came across the following

1) If an order is free (ie products have a total value of 0.00) then the choice of "Payment Methods" should be hidden and this could be set to free on the order

2) After completing a free order there is a message that says "Thanks for your payment" - this could be confusing for customers.  A new message should be added which could be displayed in the case of free orders.

**Comment by abrookbanks** [comment]
Some really cool findings here. Thanks Ian.

**Comment by abrookbanks** [comment]
Just b) to do. Maybe detect if the setting has changed and ask the store admin if they want existing downloads updated with link to perform action.

**Comment by abrookbanks** [comment]
![screenshot 2019-02-06 at 17 47 24](https://user-images.githubusercontent.com/4520803/52361941-50e0fa00-2a37-11e9-87fa-151ee3acd1ee.png)

**Comment by abrookbanks** [comment]
Works great. If changing from 0 to a time it will add the time from now.

**Comment by havenswift-hosting** [comment]
Looking good - that will really please a couple of clients where these issues were driving them crazy as they "sell" a lot of free digital products

**Comment by abrookbanks** [comment]
Great!!!
