### ISSUE TITLE
Use of undefined constant will throw an Error in a future version of PHP

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2197]
Under PHP 7.2 this is a Warning but in future versions of PHP this will throw an error

Examples (although I am sure there will be loads !)

PHP Warning:  Use of undefined constant CC_IN_ADMIN - assumed 'CC_IN_ADMIN' (this will throw an Error in a future version of PHP) in /home/XXXXXXXX/public_html/classes/debug.class.php on line 121
PHP Warning:  Use of undefined constant CC_IN_ADMIN - assumed 'CC_IN_ADMIN' (this will throw an Error in a future version of PHP) in /home/XXXXXXXX/public_html/classes/db/database.class.php on line 933

**Comment by bhsmither** [comment]
Line 28 of admin.php defines `CC_IN_ADMIN` and line 14 of index.php defines `CC_IN_ADMIN`.

Please try to determine what page request is being processed that enters CubeCart other than index.php or admin.php.

**Comment by bhsmither** [comment]
P.S. It's been a very long time since I last saw an undefined constant in CubeCart.

**Comment by abrookbanks** [comment]
I agree with @bhsmither 

Maybe those classes are being used in scripts other than admin/index.php? If so let me know and I can revisit this. Thanks for the report anyway. :)
