### ISSUE TITLE
PHP Warning:  A non-numeric value encountered in catalogue.class.php on line 116

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2199]
Been reported on forums and also seeing it across multiple sites

https://forums.cubecart.com/topic/54220-error-warning-non-numeric-value/

**Comment by Dirty-Butter** [comment]
Thanks, Ian.

**Comment by abrookbanks** [comment]
I can't reproduce this. Please provide steps to reproduce.

**Comment by abrookbanks** [comment]
Thanks I figured it out.

**Comment by Dirty-Butter** [comment]
Something you've done recently has again fixed it so using More pages, then clicking to view product, then returning to pages - sends you back where you left off. Glad to see this working again!
