### ISSUE TITLE
Frontend Broken After New Install

### ISSUE THREAD

**Issue by KissMyCart** [cubecart/v6#22]
After a fresh installation the frontend is blank. System Errors within Admin CP shows:

"/classes/language.class.php:93 - No valid language found!"

I've checked which language is shown as default in Admin CP which does show "English UK" as the 'Master Language' and there are no additional languages shown :o)

**Comment by abrookbanks** [comment]
Duplicate to issue #16. It can be fixed by saving the store settings in the admin control panel which corrects the language value.
