### ISSUE TITLE
Sale price incorrectly shown

### ISSUE THREAD

**Issue by chilled35** [cubecart/v6#220]
Create new product, enter price, leave sale and cost price *blank*, save the product, view product listing, shows retail price crossed out and £0.00 in red. Go back to admin panel, check the product entry, both cost/sale boxes have 0.00 in them. Sitewide sale disabled too.  Add the product to the cart, shows proper price.

**Comment by abrookbanks** [comment]
Closed wrong ticket (similar issue)

**Comment by abrookbanks** [comment]
I can't reproduce this at all in my development store. Please can you log a sales ticket at https://support.cubecart.com/index.php?/Tickets/Submit with URL, admin login and FTP access and I'll pick it up and take a look.
