### ISSUE TITLE
Add new hook

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2200]
In classes/filemanager.class.php around line 1061 find

`move_uploaded_file($file['tmp_name'], $target);
chmod($target, chmod_writable());`

After add

`foreach ($GLOBALS['hooks']->load('classes.filemanager.upload') as $hook) include $hook;`

**Comment by abrookbanks** [comment]
Done but **please change to** `class.filemanager.upload` for the sake on consistency. :)

**Comment by havenswift-hosting** [comment]
Thanks and have changed
