### ISSUE TITLE
Language System issue

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2201]
It's possible to set your default store language to a number of pre-defined languages, however, there doesn't appear to be any dependency checking for those languages to be enabled.

For example, if you have a store configured with English US as your default language, but only have English UK enabled, then the entire language system stops working (meaning, only default strings are loaded, no overrides work).

In an ideal world, any time a language is disabled or removed AND if it is configured as the store default then the default should change back to English UK (The default).

And, from the list of languages to select from in the store configuration, only those languages that are ENABLED should be available for selection. Currently you can choose disabled languages which means it won't work.

**Comment by abrookbanks** [comment]
> It's possible to set your default store language to a number of pre-defined languages

How? The install script only allows you to choose en-GB unless you upload others first. The admin control panel only allows you to set the default language to ones that are installed and enabled. 

Maybe I misunderstood (I normally do).

**Comment by abrookbanks** [comment]
So for example if you disable the current default language there is a problem?

I think the easy solution is to disallow the language to be disabled if it is set to default.

**Comment by Noodleyman** [comment]
disable or delete. I don't think there is any validation to prevent you from removing a language that is in use.  So, really this ticket is about preventing the issue by stopping users doing silly things :)

**Comment by abrookbanks** [comment]
yup you are right! Well done Mr Noodle. I'm on this...

**Comment by abrookbanks** [comment]
![screenshot 2019-02-07 at 09 49 17](https://user-images.githubusercontent.com/4520803/52403057-ba0b5080-2abd-11e9-81df-3da993c76741.png)

Working on delete now...

**Comment by abrookbanks** [comment]
Brilliant. Thanks Sir Noodlelot.

**Comment by Noodleyman** [comment]
Could you also add a step to correct this if noted on upgrade? I've seen this happen to a few stores over the past 12 months. If they are using a language which isn't enabled or does not exist, reset back to the default, or to a language they have installed?

**Comment by abrookbanks** [comment]
Yup.. good call...

**Comment by abrookbanks** [comment]
Seems to already be code in place:
https://github.com/cubecart/v6/blob/6.2.0-branch/setup/index.php#L465-L471

**Comment by abrookbanks** [comment]
Should be good now.
