### ISSUE TITLE
PayPal IPN incorrectly updates order

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2205]
The attached image shows the history from one order.  For some reason the PayPal IPN wasnt received after payment and so the client manually changed the order from Pending to Processing after receiving email notification from PayPal of the payment and then to Completed. 

Nine days later it appears that the IPN notification was received and the PayPal module changed the order status back to Processing !

Regardless of the reason for the delay, payment gateways should only change Pending orders to Processing

![admin control panel](https://user-images.githubusercontent.com/6114431/47721323-27eae500-dc50-11e8-92be-d8a727b72fc6.png)

**Comment by richosr** [comment]
I am getting the same issue the past few days. The order is processed and history shows complete and emails are being sent as complete but the order status appears as Processing and not completed like it should be.

I am getting the following error on every sale in the error log which may or may not be related to the  issue above:

File: [catalogue.class.php] Line: [1932] "SELECT I.* FROM ns_CubeCart_inventory AS I LEFT JOIN (SELECT product_id, MAX(price) as price, MAX(sale_price) as sale_price FROM ns_CubeCart_pricing_group WHERE group_id = 0 GROUP BY product_id) as G ON G.product_id = I.product_id WHERE I.product_id IN (SELECT product_id FROM `ns_CubeCart_category_index` as CI INNER JOIN ns_CubeCart_category as C where CI.cat_id = C.cat_id AND C.status = 1) AND I.status = 1 AND ORDER BY (I.price - (I.price / 100) * 25) DESC " - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ORDER BY (I.price - (I.price / 100) * 25) DESC' at line 1

Steve

**Comment by abrookbanks** [comment]
> Regardless of the reason for the delay, payment gateways should only change Pending orders to Processing

It looks to me like Express Checkout already has this code to make sure the status is pending only before updating to processing.. 

Is this merchant using the old PayPal Standard extension? If so we can port the code to that extension from Express Checkout. 

I want to check so I can rule out it not working in Express Checkout.

**Comment by abrookbanks** [comment]
Thanks guys. This is fixed this in 1.0.9 which I just released.

**Comment by abrookbanks** [comment]
@richosr - I don't think your error log entry is related.
