### ISSUE TITLE
Large stores with high volume can experience performance issues due to sessions

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2207]
Maximum execution time of 30 seconds exceeded in /home/xxx/domains/xxx/public_html/classes/session.class.php on line 350

```
		// Clean up expired sessions
		if($this->_manage_session_files) {
			$files = glob(CC_INCLUDES_DIR.'extra/sess_*');
	  		$now   = time();
	  		foreach ($files as $file) {
	      		if ($now - filemtime($file) >= $this->_session_timeout) {
	        		unlink($file);
	        	}
	        }
    	}
```

if you have a large number of session files (number varies based on server performance), the foreach loop can get hung up longer than execution time which results in a HTTP 500 server error on the store UI. 

Assuming more than one thread/process can run this action at the same time (Session start), it's possible another process can also delete the file before the current thread gets to it (after runbing glob(), but before looping this file). This results in the following in the server error logs:

No such file or directory in /home/xxx/domains/xxx/public_html/classes/session.class.php on line 351

This process should be refined, and also validate if the file exists. in theory it should as glob() got the list, but there are cases where it may not, and thus needs additional validation before deletion.

**Comment by Noodleyman** [comment]
follow up. to give some context, the store I am seeing this happen appears to have around 200,000 hits per day, thus a large number of session files & session data in the DB.

**Comment by havenswift-hosting** [comment]
One solution would be to change the session save path to a local account directory (/home/XXXXXXXX/sessions for example) and make the garbage collection something like 2 days (172800 seconds).  Not affected by general server garbage collection and has multiple other benefits.

A MUCH better solution would be https://github.com/cubecart/v6/issues/2085

**Comment by Noodleyman** [comment]
I would love sessions cached in memory... would be ideal, but doesn't look like it's been implemented yet.

Garbage collection is something I am looking into, although I don't necessarily want to reduce the session time from the default of 7 days, to 2 days. seems a step backwards. The issue is CubeCart looping hundreds of thousands of files and asking each one it's timestamp, then comparing. it's really inefficient.  I'm working on a code solution, just testing it now.

**Comment by havenswift-hosting** [comment]
Agreed re sessions by memcached (dont really need REDIS although if doing one, then why not both) - been trying for a while to get that included and would be great.

Garbage collection defaults on most servers to 20 minutes !  7 days is extreme and far longer than really needed

If it was databased, that would at least allow indexed lookups based on time which would be much more efficient although memcached would be orders of magnitude quicker than that.  Caching has always been an area in CubeCart that was never very good - although at least changes in 6.2 helped with general caching

**Comment by Noodleyman** [comment]
I was looking at selectively deleting the files when the data in the CubeCart_session table is removed, seems like it could self manage those files rather than doing it in batches now and then. Kinda got it working, but wasn't happy with it so for the time being as a work around I've commented out the current code which removes these files, and ported it to a cron job. This does need some attention though for an actual refinement/fix in CubeCart itself.

**Comment by abrookbanks** [comment]
Yes I've seen this too. Really it's an emergency fallback. If sessions are configured correctly on the server this code shouldn't execute. The garbage collection should match the session length time in CubeCart.

**Comment by Noodleyman** [comment]
I did a quick search in the code, 
`$session_save_path = $GLOBALS['config']->get('config','session_save_path');`

The path gets pulled from config, but there isn't a "session_save_path" configurable option in the admin area. I also wasn't able to find where this value gets set. I'm probably wrong on this, but if it's not getting set or redefined, then won't that mean CubeCart will always try and use the fallback?

I checked this setting value on a few different stores and they all returned "false" as the value, which would force the fallback to always be used. This seems like an issue...

**Comment by abrookbanks** [comment]
session_save_path can be set in the global file. https://github.com/cubecart/v6/blob/6.2.0-branch/includes/global.inc.php-dist#L24

**Comment by Noodleyman** [comment]
"can be", it isn't defined as part of a standard install, meaning unless you go in there for every install and manually edit the file with a path of your own, it won't work. So, this should be either added as part of the installer, made a configurable option in the admin area or auto detect?

**Comment by abrookbanks** [comment]
That code is fine as false is loosely empty. session save path in the store settings seems a bit nasty. 

The merchant just needs a hosting environment which is configured well. 

p.s. You might have noticed that I haven't worked on these bugs for a while. I'm totally tied up on something else CubeCart related. 6.2.2 is pretty stable so its having a bit of an unofficial code freeze.

**Comment by abrookbanks** [comment]
Going back to the original issue I think the code works well in theory. I have a feeling that the session file unlink may fail in many cases due to permissions. Have a look at the chmod/chown value of them.

**Comment by Noodleyman** [comment]
Sure, 

Could you put out a 6.2.3 update with the cache fix at the very least? :) That's causing no end of problems for people. I've had to manually apply it to a whole bunch of stores as it keeps taking larger ones offline.

I did deep dive this issue, and it was caused by the overall volume of files. for large, high traffic stores you can see a large number of sessions all with small amounts of time between them. The problem was looping thousands of files, and looking up the properties of them one by one to check each files timestamp. The more files, the longer this takes until eventually you exceed the servers max timeout threshold and throw an error. 

glob() is returning every file, then every file is evaluated for timestamp. this is inefficient. 

Ideally, as/when files are updated the timestamp should be cached in the database, then the DB used to query the files to delete based on the timestamp. this would give a shorter list of files to loop, which would reduce IO, improve performance and solve this issue for larger stores. 

To work around this issue, I ported this section of code to a scheduled cron job so it wouldn't impact the store UI.

**Comment by abrookbanks** [comment]
Already fixed with this unless this relates to something I don't know about.
https://github.com/cubecart/v6/commit/c16efa14cfb25b57768f173354f8ebb925ab8114#diff-94fc41c13ce99260929fb4c53aa292d3

Better plan is to use memcacheD or redis.

**Comment by abrookbanks** [comment]
> glob() is returning every file, then every file is evaluated for timestamp. this is inefficient.

Is there an issue open about this? Using the database sounds counter intuitive but I haven't looked into it.

**Comment by abrookbanks** [comment]
> That's causing no end of problems for people.

I haven't seen any stores with this issue and no support tickets to match.

**Comment by Noodleyman** [comment]
ah... cheers. I guess I missed this was in 6.2.2, thought it was for 6.2.3. my bad :)

And yes, there is an issue open for this... This ticket..., it's the root cause of the reported problem. 

glob() is returning all session files (matching prefix), it doesn't filter based on timestamp. so if you have 500,000 session files spanning a week it will grab all 500,000 and loop those to lookup the timestamp and evaluate if it should be cleaned up. 

Ideally, it should only check an explicit list of files gathered from the DB. IE, grab a list of filenames as an array where the cached timestamp exceeded the required threshold, loop those, check if it exists and clean up.  This should drop the overall list of files to evaluate in this example from 500,000 to perhaps 1,000 (Assumed number)

**Comment by abrookbanks** [comment]
> ah... cheers. I guess I missed this was in 6.2.2, thought it was for 6.2.3. my bad :) 

Oh good.

> And yes, there is an issue open for this... This ticket..., it's the root cause of the reported problem.

Ah I see. The mention of cache confused me. This is session data.

I'm with you and I agree/understand. I think maybe a better option is to warn the merchant that the session path needs correcting to one which has garbage management by the server if the store is writing to includes/extra. The code first mentioned doesn't work reliably. There are two best options;

1. Use the PHP config with garbage collection.
2. Use the cache tool like memcache(d), redis etc....

**Comment by havenswift-hosting** [comment]
Agreed - best solution is to add the ability to use memcached / redis for session file - small session data files are exactly what these are brilliant at doing.

Until that is added, do not ever save session files to includes/extra

1) From a securty point of view session files should be saved outside of public visible area (even if “protected”) - so use something like /home/userdir/sessions

2) This path and the GC time value should be set via cPanel and then the OS takes care of garbage cleanup - as a default, we use 2 days which works well

**Comment by abrookbanks** [comment]
> From a securty point of view session files should be saved outside of public visible 

The .htaccess file blocks them so its fine unless you are stupid enough to use Windows.

**Comment by havenswift-hosting** [comment]
Agree it “should” be fine but hosting best practice (and explicit advice from cPanel) is to not store these in public accessible areas.  In addition, if you are changing the path and GC maxlifetime via cPanel in order to ensure that the OS deals with garbage collection, then why not set it correctly

**Comment by abrookbanks** [comment]
I've removed this method of session storage as it's most likely that garbage collection won't ever be configured correctly around it.

**Comment by Noodleyman** [comment]
I know this is handled, but wanted to share an update. So far, the largest number of sess_ files I've found on a single site covering a 48 hour window is.....

1,544,722,382

I jaw dropped...

**Comment by Noodleyman** [comment]
@abrookbanks , I think this needs a minor refinement as part of the upgrade process. Although the issue has been addressed, the upgrade doesn't clear out existing sess_* files which exist. this can orphan multiple thousands of files which will never be cleared. The upgrade should clean up those files

**Comment by abrookbanks** [comment]
Agree but a lot of the time Apache can't. I'll check the code is there or not and if not add it in the hope it clears it up.

**Comment by havenswift-hosting** [comment]
memcached or redis session storage solves so many problems - speed issues, the physical number of files being stored, no worries about deleting files - seems a no brainer to me

Until memory based session storage is available and as I have also said several time before, a local session directory but above public_html is both secure and as owned by the user account, all files are deletable.

**Comment by abrookbanks** [comment]
Agreed. :)
