### ISSUE TITLE
Hook Request - order.class.php

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2209]
FIND: 
```
			// Set order as 'Pending'
			$this->_basket['order_status'] = constant('ORDER_PENDING');
			foreach ($GLOBALS['hooks']->load('class.order.place_order.basket') as $hook) include $hook;
			// Insert/Update the order summary
			$this->_orderSummary($update, $force_order);
```

AFTER ADD:
`foreach ($GLOBALS['hooks']->load('class.order.place_order.postbasket') as $hook) include $hook;	`

REASON:
Allows for actions to be performed after an order has been written to the database table and before a redirect which in some cases is required based on the custom requirement.

**Comment by abrookbanks** [comment]
;)
