### ISSUE TITLE
Customer cancelling an order can be redirected before key processing....

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2211]
This took me a while to figure out and broke my brain, but finally got to the bottom of it... If a customer has placed an order, but then cancels it via the customer account feature, 

A note is added to the order via the following code in cubecart.class.php
```
if (isset($_GET['cancel']) && Order::validOrderId(trim($_GET['cancel']))) {
    $order = Order::getInstance();
    if ($order->orderStatus(Order::ORDER_CANCELLED, $_GET['cancel'])) {
        // Specify order was cancelled by customer
        $note	= array(
            'admin_id'		=> 0,
            'cart_order_id'	=> $_GET['cancel'],
            'content'		=> $GLOBALS['language']->orders['cancel_by_customer'],
        );
        $GLOBALS['db']->insert('CubeCart_order_notes', $note);
        $GLOBALS['gui']->setError($GLOBALS['language']->orders['notify_order_cancelled']);
    }
    httpredir(currentPage(array('cancel')));
}
```
Note, the redirection after adding the note and setting the message to the customer.

Now, here comes the kicker... When an order has it's status changed the function orderStatus() is called, towards the end of this function is a hook, class.order.order_status_return which allows you to apply post orderStatus code. I ran into a problem with this hook not getting called when a user cancelled an order. The reason? The REDIRECT above is redirecting whilst the orderStatus() function is still processing. In my test store it stopped whilst calling the _manageStock function.

Obviously, this is hard to replicate as system performance, user latency etc may be a factor. 

In my case, this is causing me an issue because the hook doesn't get called, which means post processing events are not always triggered in the event of a customer cancelling an order.

Once I commented out the redirect line of code, everything works correctly. It appears the redirect is being called before the order status function has completed which is a problem.

**Comment by bhsmither** [comment]
To me, this seems that PHP is doing some predictive processing or is spawning a new thread to handle the method call.

Is your PHP compiled to be something special?

**Comment by Noodleyman** [comment]
Bog standard LAMP install with some extra modules such as mod rewrite

**Comment by abrookbanks** [comment]
Hmm this code is synchronous so it doesn't make sense but I'll take a deeper look.

**Comment by abrookbanks** [comment]
I'm sorry but I just don't know what direction I can take this. Closing for now but happy to open again if anyone can help direct me. This is truly mind boggling. I can only think that there could be separate instances for the order class somehow or something.
