### ISSUE TITLE
Cookie Dialogue Box only shows once (Cookies set without permission)

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2213]
If you ignore the cookie dialogue box, but don't specifically accept or deny... the box never comes back for future page loads until you clear your browser history / cookies.... 

This is because CubeCart is actually setting cookies BEFORE the end user has given permission for cookies to be used. 

This essentially makes this setting non-functional.

**Comment by abrookbanks** [comment]
It was intentional so it shows once giving them opportunity to block or continue. Maybe it shouldn't be.

**Comment by abrookbanks** [comment]
Confirmed as intentional:
https://github.com/cubecart/v6/blob/6.2.0-branch/skins/foundation/js/2.cubecart.js#L68-L71

That code could be removed.
