### ISSUE TITLE
Tax Rules - Countries sort order.

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#2215]
Admin -> Taxes -> Tax Rules

The Countries dropdown is all over the place.  It need to order ASC.

**Comment by sumwonlost** [comment]
Also it lists All Countries in dropdown.  It stands to reason if I wish to set a Tax Rule for a Country then the Country must surely be enabled country.status = 1 (ver 6.1.15 or less) or country.status > 0 (for ver 6.2.0+).

If country.status = 0 (disabled) then what is the purpose of setting Tax Rules for that Country?

The dropdown need to display Countries where country.status > 0 order ASC.

**Comment by abrookbanks** [comment]
Thanks for this. :)
