### ISSUE TITLE
Max Download Attempts

### ISSUE THREAD

**Issue by sporrencense** [cubecart/v6#2216]
Hi. Using version 6.2.2 - have set up a digital product however the Max Download Attempts doesn't seem to be enforced. I have it set to 3 and have been able to download the file, acting as a customer, about 20 times. The download count on customer digital downloads page always stays at 1.

**Comment by abrookbanks** [comment]
Thank you.

**Comment by havenswift-hosting** [comment]
A bug but closed without a fix ?

**Comment by abrookbanks** [comment]
hmm it hadn't synced for some reason :-/ Thanks
