### ISSUE TITLE
error in gift card image handling CC v6.2.2 

### ISSUE THREAD

**Issue by kitsguru** [cubecart/v6#2217]
I am receiving a series of errors when I try to add an image to the gift card.

```
 Invalid argument supplied for foreach() in /classes/ajax.class.php on line 162
 Invalid argument supplied for foreach() in //admin_Xxxx/sources/settings.giftcertificates.inc.php on line 23
```

**Comment by abrookbanks** [comment]
I can't reproduce this. I was able to assign an image no problem and see it in the basket. 

Maybe you can give me more detailed steps to reproduce this or I can have a look at your store via the support help desk.

**Comment by abrookbanks** [comment]
I will reopen with more info.
