### ISSUE TITLE
Exchange Rate - issue fetching rates

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2219]
CubeCart calls the following URL: 
http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml

however, this redirects to https URL, which some times can't be followed and results in a 301 error and a white screen in CubeCart.

The URL's need to be updated to HTTPS rather than HTTP for both the initial request, and fall back method.

**Comment by bhsmither** [comment]
Probable duplicate of #2165.
