### ISSUE TITLE
Billing address on invoice

### ISSUE THREAD

**Issue by NaturalSigns** [cubecart/v6#222]
I notice that CC5 shows both billing and invoice addresses on the printed invoices, as below

![invoice - billing address](https://cloud.githubusercontent.com/assets/10531097/6192462/1c857522-b3aa-11e4-9ace-453e6c90408b.png)

But on CC6 (also on my live store running CC4) it just shows the delivery address.  Is this an option somewhere?, normally i end up writing the invoice address into the notes to customer field (which isn't a big issue, just thought i'd ask). Ta, Rob

**Comment by abrookbanks** [comment]
There are three places orders can be printed in CubeCart. From the admin CP, print order form (shipping module) and from the customer area. 

Which one are you referring to? If you can copy and paste the URL without the domain it will help. 

Thanks Rob

**Comment by NaturalSigns** [comment]
Sorry Al, I wasn't very clear on my point (plus i made a typo!). What i was hoping to add to CC6 is that the billing address shows up on the invoice as well as the shipping address.  Similar to the CC5 version above [on the example above they would have shown different fields if i had changed them during checkout, so, bad example, sorry!] (at the moment CC6 just shows shipping address via any of the print order options ... /admin.php?_g=orders&node=index&print[]=    [#order number#] .  

There is no error on the existing files it was just a feature request (to be fair we are keeping you busy enough, so feel free to put on the back burner).
Ta, Rob

**Comment by Noodleyman** [comment]
@abrookbanks , this should be closed. it's not a feature request anymore. it's part of CC ;)

**Comment by abrookbanks** [comment]
Yeah thanks. I generally filter the issues by those which are open and not feature requests.
