### ISSUE TITLE
Dimensional Unit default doesn't respect store settings

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2221]
if you have NOT defined the product dimension unit of measurement, it will always default to cm as it's first in the select list.

in this scenario it should fall back to use store settings, or when updating set all undefined values to the store setting default.

**Comment by bhsmither** [comment]
That's the way the `<select>` order of `<option>`'s is coded in the template.

You are suggesting there be a default store setting?

**Comment by Noodleyman** [comment]
That is correct. Assume you are a large store who uses Imperial measurements. All of your inventory will default to Metric (admin UI) until you change and save every product. Ideally the product level setting should default to that of your store settings (Weight Unit), or perhaps a new setting for the default UOM for dimensions.

The lack of a real default caught a customer off guard since all their products showed the default value of Metric, and they use imperial thus the request. I solved it by bulk updating all inventory via the DB to use  Imperial, but for those less technical this could be a bit of a pain to update everything

**Comment by abrookbanks** [comment]
Thanks!! :)

**Comment by Noodleyman** [comment]
this doesn't quite fix the issue. if your store is using imperial, your default for measurements are now metric.

**Comment by abrookbanks** [comment]
So if they set it to "lb" for weight you think the default value for `dimension_unit` should change to "in"?

**Comment by Noodleyman** [comment]
that would make sense, since it's rare to mix both units of measurement.  The default of "cm" would still have resulted in the same issue reported, because all the dimensions needed to be imperial. without a way to bulk change all the products via the UI to the preferred UOM it's a painful job for a user to update/switch product by product.

**Comment by hairy-dog** [comment]
I recall that when I worked at a timber supplier (a very long time ago) some types of wood were measured in mm for thickness and width, sold by the linear (or maybe cubic: I forget) yard.
Ideally, and dimension or weight would have a default unigt for numeric entry, but also accept a text suffix to denote the unit. So 5 would be 5 of the default units, but 5mm 5M 5in 5" 5ft 5' etc would be parsed and accepted.
