### ISSUE TITLE
Code Improvement - Admin Area / Manufacturers

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2222]
Within the admin area, products.manufacturers.inc.php file there is a block of code to update/insert manufacturers. 

```
if(!$GLOBALS['db']->select('CubeCart_manufacturers', array('id'), array('name' => $_POST['manufacturer']['name']))) {
	if ($GLOBALS['db']->insert('CubeCart_manufacturers', $_POST['manufacturer'])) {
		$GLOBALS['main']->setACPNotify($lang['catalogue']['notify_manufacturer_create']);
	} else {
		$GLOBALS['main']->setACPWarning($lang['catalogue']['error_manufacturer_create']);
	}
} else {
	$GLOBALS['main']->setACPWarning($lang['catalogue']['error_manufacturer_create']);
}
```

However, this block of code does not do any data validation which can impact third party modules. In my case, I've added a new tab to the Manufacturers area with fields to be posted, whenever the form is submitted the insert code is triggered, which on first submission creates a new Manufacturer with empty field values. On second submission it errors because the record with empty values already exists. 

There is client side validation of the fields being submitted using JS, but this is only triggered if the tab is active.

Requesting the additional of some basic server side data validation for newly submitted manufacturers which would fix the issue.

```
if(isset($_POST['manufacturer']['name']) && !empty($_POST['manufacturer']['name'])){
	if(!$GLOBALS['db']->select('CubeCart_manufacturers', array('id'), array('name' => $_POST['manufacturer']['name']))) {
		if ($GLOBALS['db']->insert('CubeCart_manufacturers', $_POST['manufacturer'])) {
			$GLOBALS['main']->setACPNotify($lang['catalogue']['notify_manufacturer_create']);
		} else {
			$GLOBALS['main']->setACPWarning($lang['catalogue']['error_manufacturer_create']);
		}
	} else {
		$GLOBALS['main']->setACPWarning($lang['catalogue']['error_manufacturer_create']);
	}			
}
```

**Comment by abrookbanks** [comment]
Thanks for this.
