### ISSUE TITLE
Selecting Shipping Choice Anomaly

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2226]
Please see:
https://forums.cubecart.com/topic/54647-update-shipping-in-basket-not-working/

Related to #1732.

Using radio buttons for shipping choices require a change to the selector (not a Foundation issue).

Removing duplicated form elements (see #1732) requires re-checking checked elements (may not be evident in Foundation's use of drop-down chooser).

**Comment by bhsmither** [comment]
Rechecking checked elements may be relevant elsewhere that has multiple copies of form elements used in different viewport sizes.

**Comment by abrookbanks** [comment]
Thanks Brian. I added the code which makes a lot of sense. This will make it easier for the merchants to use radio buttons instead of a drop down.
