### ISSUE TITLE
setACPNotify & setACPWarning inconsistency

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2227]
setACPWarning uses the gui class method setError

setACPWarning should be setACPError

This needs changing with backward compatibility.

**Comment by Dirty-Butter** [comment]
AN ALIAS TO A BADLY NAMED METHOD (setACPNotify) Does that mean that plugins that still use setAPCNotify will be OK, or will the substitution to errormessage, etc, need to be made in the plugins?

**Comment by abrookbanks** [comment]
Yes they will be fine without change.

**Comment by Dirty-Butter** [comment]
Thanks - hope your "man flu" is better!

**Comment by Dirty-Butter** [comment]
Did all this code get reverted in today's commit?

**Comment by Dirty-Butter** [comment]
NEver mind - I see what I did - accidently picked up an older commit to compare - sorry!!

**Comment by abrookbanks** [comment]
👍🏻
