### ISSUE TITLE
Missing SEO Tab for Product Translate

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2229]
There seems to be all the code necessary to accept and database seo_meta values* in CubeCart_inventory_language, but the admin template has no tab to show the panel to collect that data.

Suggest in products.index.inc.php near line 642:
```
} else if (strtolower($_GET['action']) == 'translate' && isset($_GET['product_id'])) {
  $GLOBALS['main']->addTabControl($lang['settings']['tab_seo'], 'seo');
```
Note: Collecting a Custom SEO URL Path for a translation will collide with the existing (one and only one for all languages) seo_path.

**Comment by abrookbanks** [comment]
Blimey this is a big one!! EASY fix and confirmed working.

**Comment by havenswift-hosting** [comment]
A good start but without the ability to add a custom language url it isnt going to help too much - any chance you can add that so languages work correctly from an SEO point of view

**Comment by abrookbanks** [comment]
Yes thats too big to cover in this issue though. We have a feature request for that already. ;)

We also need to add other tools like permanent move redirects for changes SEO paths to the new one.

**Comment by abrookbanks** [comment]
Big push this year to take CC forward.

**Comment by havenswift-hosting** [comment]
>>Yes thats too big to cover in this issue though. We have a feature request for that already. ;)

Yes I agree it is a bigger issue but has been a critical missing piece of functionality for a long time that prevents SEO in multi language stores - just asking if you can prioritise this

>>We also need to add other tools like permanent move redirects for changes SEO paths to the new one.

That is a nice feature to have as well
