### ISSUE TITLE
AIO Module Display Malfunction in Admin

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#223]
When adding a new Shipping Zone, the selectors are hidden until one of the radio buttons is selected. When a button is selected, the appropriate selectors show up. This part works.

However, the actual display of the selectors is generally corrupted.

It seems to me the javascript is (probably*) not at fault, but rather some kind of interference with surrounding CSS.

* The jQuery Chosen module is copyright 2011, which suggests this version may not be compatible with the version of jQuery being used -- although my javascript console is not complaining.

** Inconsequential, but suggest moving the AIO javascript file out of the main /js/plugins/ folder and keeping it with the AIO module.

**Comment by bhsmither** [comment]
Hmm. I see the jQuery scripts and styles have been duplicated into the admin skin folder.

**Comment by abrookbanks** [comment]
Yes v5 used to rely on the /js folder for skins and admin (stupid). V6h as all jQuery updated to latest version. This means the libraries in the /js folder are not compatible. At the same time it needs to stay for legacy reasons (v5 skins).

**Comment by bhsmither** [comment]
Initial observance suggests `<select class="chzn-select" style="width: 350px;">` is not being read correctly, thus the result is:
`<div id="zone_countries_chosen" class="chosen-container chosen-container-multi" style="width: 0px;" title="">`

**Comment by bhsmither** [comment]
Secondary observance suggests the statement in AIO_shipping.min.js:
`$(".chzn-select").chosen();`
does not have a set of configuration settings. Such as:
`$(".chzn-select").chosen({width:$(this).attr("width")});`
(I don't know if the syntax is correct.)

**Comment by bhsmither** [comment]
From Chosen Docs:
"Option: width -- The width of the Chosen select box. By default, Chosen attempts to match the width of the select box you are replacing. If your select is hidden when Chosen is instantiated, you must specify a width or the select will show up with a width of 0."

Since index.tpl has embedded javascript (no help from CSS) that gets executed before the aio_shipping.min.js file is loaded and run, these selectors are not displayed and not seen by Chosen.

Would it be possible to set height to 0?

**Comment by bhsmither** [comment]
I have made a number of code edits to the layout.css, and to the index.tpl file. It all looks a lot better -- not 100% -- still need two or three more tweaks.

**Comment by abrookbanks** [comment]
Thanks I got this fixed up now and removed the JS from the main package into the module.
