### ISSUE TITLE
Incorrect order emails being sent

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2230]
Currently the "Cart: Order Confirmed" email is sent when an order is switched from Pending to Processing and most payment gateways then trigger the sending of the "Cart: Payment Received" email once they confirm that payment has been received.  As these are almost simultaneous, in most situations this makes little difference - however when using the Print Order Form "gateway" this causes a problem.

The POF has a setting "Send order confirmation email?" so that customers can be notified immediately that an order they have placed has been received by the store - this sends the "Cart: Order Confirmed" email which is fine and required.  However, one or two days later when the store owner has received payment for example by bank transfer, and the order is changed by them from Pending to Processing, the same  "Cart: Order Confirmed" email is sent out again and the "Cart: Payment Received" email is never sent.

What is needed in the order class is a check to see if the gateway is POF and if so send the "Cart: Payment Received" email instead of sending the normal "Cart: Order Confirmed" email when the order status is changed from Pending to Processing

**Comment by abrookbanks** [comment]
I understand now. :blush:

Thanks for this. Hopefully get this sorted mañana.

**Comment by abrookbanks** [comment]
Turned out to be an easy one.

**Comment by havenswift-hosting** [comment]
Thanks and understand that you had your head buried in loads of other issues today !

However, doesn't that just block the sending of the duplicate Order Confirmation email ?  What is also  needed if it is POF, is for the "Cart: Payment Received" email to be sent

**Comment by havenswift-hosting** [comment]
Minor point : spelling mistake on variable used "already_semt"

**Comment by abrookbanks** [comment]
Is that really needed? The store can't actually now of it has. What I don't like about this is that it's a bit hackie. Adding code for specific extension in core is a bit dirty. I'll reopen this to see if it can be improved.

**Comment by abrookbanks** [comment]
> Minor point : spelling mistake on variable used "already_semt"

Cheers.

**Comment by havenswift-hosting** [comment]
Yes it is needed, otherwise customers paying using POF payment methods never get confirmation that their payment has been received. "Cart: Payment Received" is sent for all other methods of payment and that step is needed as there can be a gap between that and Competing an order

**Comment by abrookbanks** [comment]
OK so if the gateway is POF and the order status is processing the email gets sent. 

I think the best way to do this is to look for a class or public variable in the gateway class so it's not specific to POF. Same for sending the confirm email.

Thinking out loud. I'll get that done.

**Comment by abrookbanks** [comment]
OK this is done. From my testing it works well.

- The order processing email will only send for the POF at status "Processing" if it hasn't already been sent.
- The print order form will now send the payment received email at order status of processing. 

After adding this code please update the POF extension to 1.2.0.

**Comment by havenswift-hosting** [comment]
Thanks Al !

**Comment by abrookbanks** [comment]
Welcome. I think this is a great improvement. Thanks.

**Comment by DiMarca-Online** [comment]
Thank you, I am so happy with this :-D!!

**Comment by abrookbanks** [comment]
Great.
