### ISSUE TITLE
Product Options error

### ISSUE THREAD

**Issue by amandav8** [cubecart/v6#2231]
I have been trying to add be product options but I keep getting this error...

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator to inform of the time the error occurred and of anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Web Server at badboyztoyz.com

I contacted my server company and they said I need to contact cubecart. Below is the error information from the log.

[Thu Feb 07 09:57:47 2019] [warn] [client 50.233.239.173] mod_fcgid: read data timeout in 45 seconds, referer: http://badboyztoyz.com/store/admin_1CQnaB.php?_g=products&node=options
[Thu Feb 07 09:57:47 2019] [error] [client 50.233.239.173] Premature end of script headers: admin_1CQnaB.php, referer: http://badboyztoyz.com/store/admin_1CQnaB.php?_g=products&node=options

**Comment by abrookbanks** [comment]
Please contact support or seek assistance on our forums.
