### ISSUE TITLE
Address has been updated...appears twice

### ISSUE THREAD

**Issue by jeff1452** [cubecart/v6#2232]
https://forums.cubecart.com/topic/54563-address-has-been-updatedappears-twice/ has multiple descriptions and people with the issue.  I think it's part of the account validation as it doesn't occur when a user is logged in.  This only occurs when someone is using guest checkout.  The wording was in the languages under account.  But... it can also be in the shipping methods and modules.  We installed the module for by price and flat rate and the same issues occured.  The scenario is one shipping method, flat rate per order total and only one gateway installed.  I tried editing the core code in the classes but I'm not good enough and only white screened my site so I went back to the default code.

**Comment by jeff1452** [comment]
The templates I modified so I could see where the message was coming from are the content.gateway, content.checkout, main.checkout, the two checkout pages (small, and medium) and the confirm.  None of these actually address or allow you to remove the duplicated pages, this is in the core code.  Thanks.

**Comment by abrookbanks** [comment]
I've not been able to reproduce this and a proposed fix is above. This needs more testing before the issue can be closed.
