### ISSUE TITLE
Github Annotations

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2234]
Using #1987 as an example:

This was assigned to Milestone 6.2.1 and closed in May 2018.

Milestone 6.2.1 was then closed in June.

Then, more work was done on this issue but there is no annotation as to what milestone this follow-on work first appeared in.

It can be discerned that some specific work was done on Aug 9 (https://github.com/cubecart/v6/commit/18970743591ab98cfc729365a27e48ecc8be5891).

One would need to do some calculations to show that this specific work _should_ now appear in CC623.

Is there a way to annotate any changes that were made to a previously closed (and attached to a milestone) issue, probably re-opened and re-closed, to what milestone those changes will appear in?

If not possible, then suggest that closed issues not be re-openend, but a new issue created referencing the original. Then, the "summary of changes" (milestone report) for any specific milestone will be sure to have this "added" work mentioned.

**Comment by abrookbanks** [comment]
Thanks I'll bear this in mind. For safety we should probably make new issues relating to closed milestones.
