### ISSUE TITLE
Tables on Mobile Screen

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2238]
Please check Foundation for `<table>`s too wide to fit the small width for a logged in customer viewing Digital Downloads and Order History.

**Comment by abrookbanks** [comment]
![screenshot 2019-02-15 at 11 40 59](https://user-images.githubusercontent.com/4520803/52854539-9926a900-3116-11e9-96ec-ed6c4a88123b.png)

**Comment by abrookbanks** [comment]
![screenshot 2019-02-15 at 11 52 39](https://user-images.githubusercontent.com/4520803/52855041-39c99880-3118-11e9-8041-42cc295301f0.png)
