### ISSUE TITLE
Foundation Small View Off-Canvas Footer

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2239]
Feature Request:

On Foundations "small" view, put the Footer contents in one or more off-canvas boxes. Show in its place a bar with trigger links (similar to Session, Search, and Cart). Keep the Copyright visible?

**Comment by abrookbanks** [comment]
I think it's ok as it is on just the footer of the main page. Have I misunderstood?

![screenshot 2019-02-14 at 11 00 26](https://user-images.githubusercontent.com/4520803/52782769-c193a200-3047-11e9-9ed9-d20ec5d4403d.png)
![screenshot 2019-02-14 at 11 00 13](https://user-images.githubusercontent.com/4520803/52782770-c22c3880-3047-11e9-9352-e41fd501200f.png)

**Comment by abrookbanks** [comment]
Plans to overhaul the skin for Q2 2019 on.
