### ISSUE TITLE
While in Beta

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#224]
Suggest to use non-min versions of scripts where possible and practical, and non-collapsed CSS files.

This makes it so much easier to find and tweak as necessary until Gold is published.

(Even though it is trivial for a programmer's text editor to explode it all out.)

**Comment by abrookbanks** [comment]
Hopefully we are very close to being out of beta.. It only takes a second to beautify and then recompress. 

It took a while to compress them all.
