### ISSUE TITLE
Admin Order Summary to Show Language Used

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2242]
Feature Request:

Knowing the language in which an order was placed may be desirable.

Suggest on the Order Summary page, in the Contact Details, the name (and flag?) of the language recorded in CubeCart_order_summary be shown.

**Comment by abrookbanks** [comment]
Thank you. 
![screenshot 2019-02-28 at 16 58 10](https://user-images.githubusercontent.com/4520803/53583869-546d2a00-3b7a-11e9-89e8-87b3da33f70d.png)
