### ISSUE TITLE
Language Flags bug

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#2244]
I have created en-AU language definitions file and works.

I have added en-AU.png to flags folder, it displays flag correctly in Admin sections,  however it does not display the flag correctly on front end.  It displays unknown.png.

**Comment by abrookbanks** [comment]
Not really a bug you need to add the CSS and edit the sprite image accordingly.

**Comment by abrookbanks** [comment]
I agree however that it would be best of picked up from the images/flags folder so maybe we can work from there instead.

**Comment by abrookbanks** [comment]
I had a change of heart on this one. Although it's good to use sprites there is a time and a place and this probably isn't one of them.

**Comment by sumwonlost** [comment]
Thanks.  Much simpler to add image to folder than having to make changes to files for each flag that will be overwritten with updates.
