### ISSUE TITLE
Part of Querystring Could Get Lost

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2246]
(I can't find my notes on how I found this.)

In `SEO->__construct()`, there is:
```
if (preg_match('#^'.self::PCRE_REQUEST_URI.'$#Sui', $_SERVER['REQUEST_URI'], $match)) {
```
A few lines later:
```
$seo_url = html_entity_decode($this->generatePath($match[5], $match[2], $match[4], true, true));
```
If `$_SERVER['REQUEST_URI']` has, for example:
```
anything/anything/an-th_ng.sufx?_a=product&product_id=40001&the_rest
```
then `$match[6]` will have `&the_rest`. But, after `generatePath()`, it is not part of `$seo_url`.

This statement:
```
if (str_replace($GLOBALS['rootRel'], '', $_SERVER['REQUEST_URI']) != $seo_url) {
```
will then always succeed and may execute an unwanted bounce.

Suggest after the line `$seo_url =`, on a new line:
```
if(isset($match[6]) && $match[6][0]=='&'){$match[6][0]='?';$seo_url.=$match[6];}
```

**Comment by abrookbanks** [comment]
Fabulous find. Thanks Brian. Tested and extra query string is now appended.
