### ISSUE TITLE
IP Blocker - Unblock feature request

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#2248]
Site Administrators are unable to unblock IP/User in CubeCart unless they have knowledge on how to query the db.  Not all site administrators are system administrators and lack this knowledge. 

Can we get a page for this in Maintenance?  Wouldn't take too long to knock-up.

It should list all blocked IP's/Users - Date Blocked - Delete (delete record to unblock)

**Comment by abrookbanks** [comment]
You are best off doing this via firewall, apache "deny" rule or via your hosting control panel (same thing) in order to be as efficient as possible. Building this int CubeCart is possible but the traffic will still use a certain amount of overhead which is best avoided.
