### ISSUE TITLE
Spelling mistake in Bank Transfer gateway plugin

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2250]
There are two minor spelling mistakes in the skin/form.php file

<p>Your order will be completed one payment has been recieved.</p>

Obviously "one" should be "once" and received spelt incorrectly

This text is also hard coded rather than being a language string

**Comment by abrookbanks** [comment]
That's not like me is it?!?! :laughing:

**Comment by abrookbanks** [comment]
Fixed with 1.0.1
