### ISSUE TITLE
Facebook Social Plugin to Have I18N

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2251]
Aside from the language definitions for the settings panel, suggest to also allow for the Facebook API call to use the current language.

Please see:
https://developers.facebook.com/docs/internationalization

Suggest in social.class.php, near line 18:
```
From:
private $_path	= '/en_US/all.js';
To:
private $_path	= '/'.$GLOBALS['language']->current().'/all.js';
```

**Comment by abrookbanks** [comment]
Fixed with 1.0.1. Thanks!
