### ISSUE TITLE
Wrong Class Instantiation

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2252]
Just guessing at this point... (CC623)

In filemanager.class.php, near line 899, Ctalaogue is instantiated with
```
new Catalogue();
```
However, now that Catalogue has a non-imaginary
```
final protected function __construct()
```
I believe the `new` instantiation won't work. (Your testing may have shown otherwise.)

I think the following is now necessary:
```
$catalogue = $GLOBALS['catalogue']->getInstance();
```
I think the reason it worked in CC622 and earlier is because the class was presumed to have an inherited **public** magic `__construct()` method.

**Comment by havenswift-hosting** [comment]
I can confirm that this fixes this issue in 6.2.3

**Comment by abrookbanks** [comment]
What does this fix?

**Comment by bhsmither** [comment]
Either or both, in admin, FileManager, a white screen (aka 500 ISE - PHP Fatal Error), or a missing list of images on the admin's Add/Edit Product, Images tab, Image FilePicker.

**Comment by abrookbanks** [comment]
Thanks for this. Big one so we need a new release. Damn it.
