### ISSUE TITLE
Email settings - 6.2.3

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#2255]
Irrespective of what method I use, after Save, I run Test and get following message "This content failed to load."

**Comment by abrookbanks** [comment]
I can't reproduce this.

**Comment by abrookbanks** [comment]
![screenshot 2019-03-06 at 15 18 18](https://user-images.githubusercontent.com/4520803/53891844-17de7a00-4023-11e9-8a85-a462f14f2162.png)
![screenshot 2019-03-06 at 15 18 10](https://user-images.githubusercontent.com/4520803/53891845-17de7a00-4023-11e9-9987-10eab4c3af16.png)
![screenshot 2019-03-06 at 15 18 03](https://user-images.githubusercontent.com/4520803/53891846-18771080-4023-11e9-8b1d-b2a7c39e65f1.png)
![screenshot 2019-03-06 at 15 17 54](https://user-images.githubusercontent.com/4520803/53891847-18771080-4023-11e9-9550-0d793dd1123c.png)

**Comment by abrookbanks** [comment]
I'd need to look at this individual case. From my testing it works on my development store and a number of client stores.

**Comment by sumwonlost** [comment]
All well after re-installing.  Sorry about opening issue.
