### ISSUE TITLE
File: [controller.admin.pre_session.inc.php] Line: [24] "SET @@time_zone = 'Europe/London'" - Unknown or incorrect time zone: 'Europe/London'

### ISSUE THREAD

**Issue by hairy-dog** [cubecart/v6#2256]
I am getting loads and loads of the same error in the System Error Log, running 6.0.4

File: [controller.admin.pre_session.inc.php] Line: [24] "SET @@time_zone = 'Europe/London'" - Unknown or incorrect time zone: 'Europe/London'

Line 24 says:
$GLOBALS['db']->misc("SET @@time_zone = '".$GLOBALS['config']->get('config', 'time_zone')."'");

I tried choosing a different time zone from the drop-down list. That way, the result is the same, except that a different time zone is unknown or incorrect.

A few munutes ago, I saw a variation:

File: [controller.index.inc.php] Line: [25] "SET @@time_zone = 'Europe/London'" - Unknown or incorrect time zone: 'Europe/London'
and it's no surprise that line 25 says:
$GLOBALS['db']->misc("SET @@time_zone = '".$GLOBALS['config']->get('config', 'time_zone')."'");

but there are only a few of those errors. Several each minute for the [controller.admin.pre.... version

**Comment by sumwonlost** [comment]
I am using 6.2.3 and can confirm I am getting same error messages.

**Comment by abrookbanks** [comment]
Your hosting isn't compatible. 

https://dev.mysql.com/doc/refman/8.0/en/time-zone-support.html

**Comment by Noodleyman** [comment]
@abrookbanks , as a few people are running into this issue, and they only seem to find it after an upgrade, would it be possible to add some additional checks to the upgrade/setup process to validate if the server meets the requirement?

Can the hosting requirement notes on the website also be updated with more details specific to this topic as well?, it may be useful for reference.

**Comment by abrookbanks** [comment]
We could add a configuration setting to disable timezone support.

**Comment by abrookbanks** [comment]
@hairydogltd  I don't see what's unsatisfactory about it. Your hosting isn't compatible and I've given you a link to show you why!? Enable mysql timezone support and it will fix this.

**Comment by havenswift-hosting** [comment]
While people may not have been affected by or noticed the issue that this code fixes, it was added to 6.2.3 for very good reasons.  The timezone tables are unfortunately not added to MySQL as standard but the manual addition takes somebody with server level access about five seconds to add and has no negative impacts so I never understand why hosting companies dont do it as part of their new server configuration - we have done it on all of our servers for many years.

**Comment by abrookbanks** [comment]
I agree Ian.

**Comment by sumwonlost** [comment]
I found a solution.

Login as root via ssh and enter following:

`# mysql_tzinfo_to_sql /usr/share/zoneinfo | MYSQL_PWD=`cat /etc/psa/.psa.shadow` mysql -u admin mysql`

Worked for me.

**Comment by abrookbanks** [comment]
@sumwonlost 
That is exactly right.

**Comment by havenswift-hosting** [comment]
As Al pointed out on this thread 14 days ago and both of us have mentioned in forum threads, this is all it takes - however, only the server admin can do this

**Comment by abrookbanks** [comment]
I think in conclusion this needs to be able to be turned off for people stuck within the bounds of dare I say crappy generic hosting.

**Comment by havenswift-hosting** [comment]
I certainly wouldnt remove it - maybe limit error reporting to once an hour or once a day so it doesnt fill up the logs and improve the error message.  Giving the ability to turn it off simply encourages crappy, cheap hosting

**Comment by abrookbanks** [comment]
Maybe the best option is to disable error logging for just that query.

**Comment by Noodleyman** [comment]
going back to my comment, if it's pointed out as part of an upgrade, and tested as part of the installer then that should be enough. This requirement should be clearly documented, outlining why the error is generated and some general steps to be taken if you experience it. 

This should clearly point out there is a limitation before people get caught out as part of an upgrade/install, and IF they run into the problem there should be clear documentation to help them navigate the issue. So may different skill levels out there, posting links to technical articles may go over the heads of many and isn't always that helpful. 

can this be clearly documented rather than removed?

**Comment by abrookbanks** [comment]
I'd describe it as a soft error. It doesn't stop anything working other than database timestamps only returning time based on the server time and not store time. It's only useful if say you have a server in the UK with a merchant hosted on it in say for example Canada. Which is actually exactly what bought this about.

I'd have said the best bet is to suppress the error but document the recommendation for mysql timezone support.

**Comment by abrookbanks** [comment]
Do we think this is an acceptable solution?

**Comment by sumwonlost** [comment]
Yes that will get rid of the annoying error messages, however how are users to know to upgrade the mysql timezones if no error message is given

**Comment by havenswift-hosting** [comment]
No it is a very bad idea to suppress error messages - that is just avoiding the problem - several suggestions from myself and Alec on best way to handle this.  Do it this way and people will just ignore and then complain later when there is a date/time issue - you are working around crappy, cheap hosting.  If people are told up front as Alec has suggested, plus given occasional error messages then they are taking an informed decision to stay with that hosting company

**Comment by abrookbanks** [comment]
CubeCart hasn't had proper timezone support since its inception. Maybe this error should remain suppressed to avoid huge logs but add a notice next to the timezone setting if it isn't fully supported with the server configuration.

**Comment by abrookbanks** [comment]
![Screenshot 2019-03-21 at 11 33 02](https://user-images.githubusercontent.com/4520803/54749668-35881380-4bcd-11e9-95f8-a5dae64309b9.png)

**Comment by sumwonlost** [comment]
Why not a dropdown with 2 options.
1 - Server time
2 - Database time

If database time is selected and not installed (active), they get error messages until Server Time is selected or they load database time.

**Comment by abrookbanks** [comment]
I think that's a good suggestion. Thank you.

**Comment by abrookbanks** [comment]
Actually there is a bug here around the value..

**Comment by abrookbanks** [comment]
![Screenshot 2019-03-21 at 12 31 36](https://user-images.githubusercontent.com/4520803/54752281-6704dd00-4bd5-11e9-9a31-1b8d4e11a01e.png)
