### ISSUE TITLE
Order Status - caching issue

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2264]
As a customer on the store front I place an order, go through payment and then am returned to the store. If I sit on the order confirmation page, or review the order via my user account it still shows a "Pending" status even though it's actually processing or completed.

Once the cache is cleared, the UI shows the correct status. This is confusing customers who think their payment didn't go through correctly after receiving an email notification saying it had. 

tested and reproduced in 6.2.4

**Comment by abrookbanks** [comment]
Thanks!! :)
