### ISSUE TITLE
Unsettled Orders - Invalid column in query

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2265]
Admin dashboard, unsettled orders tab calls this SQL query:

`$unsettled_orders = $GLOBALS['db']->select('CubeCart_order_summary', array('custom_oid', 'id', 'cart_order_id', 'name', 'first_name', 'last_name', 'order_date', 'customer_id', 'total', 'status'), 'status IN (1,2) OR `dashboard` = 1', $order_by, $results_per_page, $page);`

But, the column 'name' isn't valid for this table

**Comment by abrookbanks** [comment]
Thanks. I have a feeling in my bones it was added as backward compatibility from orders made in v3/v4 that have empty first_name and last_name fields.

**Comment by abrookbanks** [comment]
Yes..

```
               <td>
                  <a href="?_g=customers&action=edit&customer_id={$order.customer_id}">{if empty($order.first_name) && empty($order.last_name)}
                  {$order.name}
                  {else}
                  {$order.first_name|capitalize} {$order.last_name|capitalize}
                  {/if}</a>
               </td>
```
