### ISSUE TITLE
Admin -> Language cache issue

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#2268]
Admin - >Languages

When I disable/enable a language and Save, I get error message

"Failed to update language status"

However when I clear cache, the status is correctly updated.

Also a disabled Language does correctly not display on front end.

However it displays in dropdown in Store Settings and Administrators - If a Language is disabled it should not display in these dropdowns.

**Comment by abrookbanks** [comment]
> Also a disabled Language does correctly not display on front end.

In what way?

**Comment by abrookbanks** [comment]
Thanks.
