### ISSUE TITLE
Enhancement to Coupons

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#227]
See:
https://forums.cubecart.com/topic/49257-creating-gift-certificates/

Summary:
It would be helpful to have a coupon with a starting value. Each time the coupon is used the starting value is decreased until the coupon has been used in full.

Example: 
Start Value £10

Customer places an order for the value of £6 and uses the coupon. They get order 1 for free.

Customer then places a second order for the value of £20 and again uses the same coupon code. only £4 remains on the coupon, so the amount to pay this order will be £16. 

The coupon now has £0 remaining, and should be disabled.

**Comment by bhsmither** [comment]
I'm distressed at **not** being able to find where a "real money" GC's balance is stored.

**Comment by Noodleyman** [comment]
CubeCart_coupons.discount_price ?

AS for "Balance", there isn't one as of today that I know of. if the coupon has a value of £10, you can use it multiple times and get £10 off each time.

**Comment by Noodleyman** [comment]
Redeemed values go into CubeCart_order_summary.discount

BUT, that is just an aggregate of all applied discounts rather than specific to coupons

**Comment by bhsmither** [comment]
Ok, sure. Looks like a reasonable place. I'll trace through the code shortly.

**Comment by bhsmither** [comment]
Order->placeOrder(), about 40 lines down, if the order has coupons/certificates, then update CubeCart_coupons.

**Comment by Noodleyman** [comment]
It only updates the balance on gift certificates, not coupons.  The problem is you can't manually create gift certificates, only coupons. It would be good to extend the same behaviour to coupons and make it a configurable option within each coupon.

						if ($data['gc']) {
							// Update gift certificate balance
							$GLOBALS['db']->update('CubeCart_coupons', array('discount_price' => $data['remainder']), array('code' => $data['voucher']));
							$certificates_used[] = $data['voucher'];
						} else {
							$vouchers_used[] = $data['voucher'];
							// Update usage count
							$product_data = unserialize($data['product']);
							if (is_array($product_data) && count($product_data) > 1) {
								## Per product coupons
								foreach ($this->_basket['contents'] as $hash => $item) {

									if (!in_array($item['id'], $product_data)) {
										continue;
									}
									$GLOBALS['db']->update('CubeCart_coupons', array('count' => '+'.(int)$item['quantity']), array('code' => $data['voucher']));
								}
							} else {
								$GLOBALS['db']->update('CubeCart_coupons', array('count' => '+1'), array('code' => $data['voucher']));
							}

**Comment by bhsmither** [comment]
How is a GC made unique? There is no product_id number, and the GC has the same product_code for all GCs sold -- until the admin changes it.

In Cart->add(), near line 211, starts to create a hash from the $optionsArray. This array has value, method, name, email, and message. The hash is stored in CubeCart_order_inventory and a record of the discount is stored in CubeCart_coupons under the GC's code.

If two GCs were purchased with the exact same options, the hashes would be identical and the cart would show a quantity of two.

Question: Does CubeCart properly handle the databasing and redemption of two identical GCs purchased with the same cart_order_id?

**Comment by bhsmither** [comment]
I'm seeing a reference to a 'taxType' in the $gc array in Cart->get(). I do not see a corresponding config setting for GCs.

**Comment by abrookbanks** [comment]
CubeCart has a simple approach to this. If a "coupon" has a cart_order_id associated to it with a status of 2 (processing) or 3 (complete) it will then be treated as a gift certificate and it will keep tabs on the remainder.

**Comment by abrookbanks** [comment]
.. so in theory we can add a field in the ACP for the CubeCart order ID to get gift certificate functionality. 

Thats a bit dirty though so maybe a different flag can be added. I'll give this some thought.

**Comment by abrookbanks** [comment]
![screen shot 2015-02-18 at 12 02 43](https://cloud.githubusercontent.com/assets/4520803/6246988/cb5ce61a-b766-11e4-9d82-ab3ac08a2cec.png)

**Comment by Noodleyman** [comment]
Hi Al.

Can I get some clarification on the change. I've not had time to check further into it yet.

An order number must be provided in the coupon, which essentially turns it into a manually created gift certificate. In order for the balance to be kept track of correctly does there need to be a 1-1 relationship between the coupon & order?

Or, can a single dummy order be created to link a batch of coupons to and the remaining balances calculated correctly?

Thanks,

**Comment by bhsmither** [comment]
When CubeCart has received a discount code entered by the customer at checkout, one of the tests to 'validate' its GC status is to query the CubeCart_order_summary table for the cart_order_id that was logged when the GC was purchased.

The result[0]['status'] of that query must be 2 or 3.

There **is no further test** to correlate the Order Inventory for that order to contain a GC that was sold for that order. There simply must exist a record in CubeCart_order_summary that the CubeCart_coupon record can form a relationship on the cart_order_id where the status is 2 or 3. The order_summary does not even have to have a customer or totals.

**Comment by abrookbanks** [comment]
> Or, can a single dummy order be created to link a batch of coupons to and the remaining balances calculated correctly?

Yes I'm pretty sure you can do that. It just needs an order number with a status of processing or complete.

**Comment by Noodleyman** [comment]
thank you for confirming.
