### ISSUE TITLE
PHP Error - cubecart.class.php

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2270]
CubeCart.class.php

`$_POST['user']['password'] = (isset($_POST['register']) && $_POST['register']==1) ? md5($_POST['password']) : md5(time().$SERVER['HTTP_USER_AGENT'].$_SERVER['REMOTE_ADDR']);`

$SERVER['HTTP_USER_AGENT']

should be

$_SERVER['HTTP_USER_AGENT']

**Comment by abrookbanks** [comment]
Great find. Thanks Mr Noodles.
