### ISSUE TITLE
E-Commerce tracking for POF orders

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2272]
As orders placed and "paid" through the Print Order Form never reach the content.receipt.php template, e-commerce tracking in Google Analytics is never triggered.  For many this wont be an issue or will be insignificant but for some a significant proportion of orders can come in this way

**Comment by abrookbanks** [comment]
Relates to this: https://features.cubecart.com/topic/move-google-analytics-for-ecommerce-from-client-to-server-side_8

**Comment by abrookbanks** [comment]
I can't really see a solution to this. Google don't seem to have an API to update the status other than via their JS library.

**Comment by abrookbanks** [comment]
Note added to POF extension page and Bank Transfer

> NOTE: This payment gateway will not log sales data to Google eCommerce Analytics as payments can not be digitally verified.
