### ISSUE TITLE
Multi Skins May Confuse skin.custom Cache

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2273]
In Foundation's config.xml file, there is a `<custom>` node that ends up in the `skin.custom.cache` file.

This file is written and read with no consideration given to what skin it belongs to.

When changing the skin from the frontside selector, the cache is not deleted (probably no reason to) and `skin.custom.cache` will continue to exist.

This behavior will present the possibility of pertinent data related to the new skin not being employed and impertinent data being given to the skin (if the skin has the same template variables).

**Comment by bhsmither** [comment]
I would also argue for the case where the `<custom>` node might contain more than a one-dimension array.

Therefore, the code that parses `$xml->custom` should recurse in an attempt to reconstruct that array.

**Comment by bhsmither** [comment]
Perhaps move/incorporate the GUI code that parses `$xml->custom` over to the processes at `GUI->listskins()`.

**Comment by abrookbanks** [comment]
Thanks Brian.
