### ISSUE TITLE
setGhostId() not called before writing to DB

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2277]
the function setGhostId() and getGhostId() are useful, however the ID doesn't get set until an order is placed.

Ideally, the ID should be set the moment the ghost customer is essentially logged in and the record added to the CubeCart_customer table. that being the moment via checkout they have provided their details, opted not to create an account and then proceed to the next stage.

**Comment by abrookbanks** [comment]
The existing calls to setGhostId may no longer be needed but harmless keeping to avoid the risk of creating bugs.
