### ISSUE TITLE
Cookie Consent improvements

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#2278]
I don't know how long a store has to keep cookie consent for customers?

Customer List -> select Customer -> Cookie Consent

The log can become rather large if customer regularly clear their browser cache.

1.  Can you add pagination to this.

2.  How do I delete entries after the expired period?  Can you add checkboxes with delete selected or are these dropped automatically after a set period?  A little housekeeping as eventually largish stores will have 0,000's of useless entries in the log.

Also how do I view log for non registered users who accept cookie consent?

**Comment by abrookbanks** [comment]
> Also how do I view log for non registered users who accept cookie consent?

You can't but it is stored in the database table `CubeCart_cookie_consent ` if you really did need to dig it out.

> The log can become rather large

It shouldn't get too large as once clicked it won't show again for a year or until they clear their browser cache. If the customer doesn't click it and makes a huge amount of page loads it could amount up.
