### ISSUE TITLE
Corrupted SQL Statement

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2279]
Regarding #2119 and #2249, together they will cause a corrupted SQL statement.

`_where_live_from` is created using ` AND `.

2249 adds `_where_live_from` into the `outOfStockWhere()` results.

2119 sends the `outOfStockWhere()` results to a `$where` array.

The `$where` array is imploded using ` AND `.

This results in a SQL query that looks like (only part of it reproduced here):
```
... INNER JOIN CubeCart_category as C where CI.cat_id = C.cat_id AND C.status = 1)
AND I.status = 1
AND  AND `live_from` < UNIX_TIMESTAMP()
AND ((CubeCart_inventory.stock_level > 0 AND CubeCart_inventory.use_stock_level = 1) OR CubeCart_inventory.use_stock_level = 0)
AND `live_from` < UNIX_TIMESTAMP()
AND (I.name RLIKE ...
```

**Comment by abrookbanks** [comment]
Can you tell me how to reproduce this as I haven't been able to?

**Comment by bhsmither** [comment]
Please use this URL:
```
/search.html?search[keywords]=*&_a=category&search[inStock]=1
```
See the last few posts in:
https://forums.cubecart.com/topic/54251-list-all-products-link-is-this-possible/

**Comment by abrookbanks** [comment]
Checking the forum post as I still can't reproduce this...

**Comment by abrookbanks** [comment]
Duplicate of #2320
