### ISSUE TITLE
Bug - Edit Customer Email address.

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#2280]
In Admin if I edit a customer email address to an existing address and Save.

1.  The email address correctly does not update as exists, however I get message "Customer Successfully Updated" - I should get "Email Address Exists - No Details Updated" error message or something to that affect.

2.  It creates a record in error log.  If no details updated (see 1) then why an error in log?

**Comment by abrookbanks** [comment]
Thanks!!
