### ISSUE TITLE
One Remaining Not Good for More

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2281]
More testing is required.

For this experiment:

Have the skin's config default to 12 items per page.

Have 13 items in a search result. Having 13 items in a category may also work.

Request the search. At the bottom will be a More button.

Because there is only one more product to be shown, after clicking the button, CubeCart's AJAX return is not usable because CubeCart sent a 302 Bounce to the one single product:
```
Location: ?_a=product&product_id=21
```

**Comment by abrookbanks** [comment]
I like this fix but I'm not 100% sure how compatible it will be with server config.
