### ISSUE TITLE
CKEDITOR Weirdness

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2284]
Regarding CKEDITOR's `config.js, please verify that:
```
config.protectedSource.push(/{[\s\S]*?}/g);
```
is the desired regex. According to an online tester, their report:
```
/{[\s\S]*?}/g
match the character { literally (case sensitive)
match a single character present in the list [\s\S]
*? Quantifier — Matches between zero and unlimited times, as few times as possible, expanding as needed (lazy)
\s matches any whitespace character (equal to [\r\n\t\f\v ])
\S matches any non-whitespace character (equal to [^\r\n\t\f\v ])
match the character } literally (case sensitive)
```
`{$EMAIL_CONTENT}` matches

`{ $EMAIL_CONTENT }` matches but will **not** be parsed by Smarty

This regex: `{\S*?.*\S}` requires a non-space character to sit next to each brace.
```
/{\S*?.*?\S}/g
match the character { literally (case sensitive)
match a single character \S
*? Quantifier — Matches between zero and unlimited times, as few times as possible, expanding as needed (lazy)
\S matches any non-whitespace character (equal to [^\r\n\t\f\v ])
match any single character 
*? Quantifier — Matches between zero and unlimited times, as few times as possible, expanding as needed (lazy)
match a single character \S
\S matches any non-whitespace character (equal to [^\r\n\t\f\v ])
match the character } literally (case sensitive)
```
I bring this up because on `Email Templates`, `Default Emails`, `HTML Content` tab, there is erroneous protected content (do not know why CKEDITOR is showing that), and in Source mode, the display of the structure of the code is really messed up.

I do not know if the regex is causing this. Still playing with this.

**Comment by abrookbanks** [comment]
Thank you. I was able to reproduce and verify your updated Regex. Great job. Thank you.
