### ISSUE TITLE
Later Versions of CKEDITOR Removes Spaces Around Protected Source

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2289]
This also manifests:
https://dev.ckeditor.com/ticket/16976

I discovered I was able to work around it by having a regular character as the first non-tag in the line:
```
Source:
<p>{$DATA.first_name} {$DATA.last_name} {if !empty($BILLING.company_name)}

From (editor removed all spaces):
<p>{$DATA.first_name}{$DATA.last_name}{if !empty($BILLING.company_name)}

To:
<p>Admin, {$DATA.first_name} {$DATA.last_name} {if !empty($BILLING.company_name)}
or
<p><wbr />{$DATA.first_name} {$DATA.last_name} {if !empty($BILLING.company_name)}
```
Oddly, the `<wbr>` also stops the removing of spaces.

**Comment by Dirty-Butter** [comment]
I tried the new CKeditor version on a test site. Everything else seems OK except the actual editor box is missing in those places that use the CKeditor. The description, etc. is still seen on the store front. Of course, my store is not stock by any means. But I thought I had better let you know. 

(I just checked, the Debug messages I reported are still there even with the old CKeditor, so I've deleting the messages.)

**Comment by Dirty-Butter** [comment]
New CKeditor does not work properly for me in a stock install either.

**Comment by bhsmither** [comment]
From a fresh CC625 distribution, copy over the folder `/includes/ckeditor/plugins/showprotected/`.

It is missing as of today.

**Comment by bhsmither** [comment]
My experiment involved downloading CKEditor 4.12.1 directly from the CKEditor website, renaming the existing `ckeditor` folder to `ckeditor-4.5.7`, and copying into `/includes/` the new `ckeditor` folder.

Initial tests showed that CKEditor complained about a missing 'showprotected' reference. After copying over that plugin, all is good for me.

**Comment by bhsmither** [comment]
The "removing spaces" problem still exists, however.

**Comment by abrookbanks** [comment]
Good opportunity to update the 3rd party code. I've added protected source back before reinvestigating this issue.

**Comment by abrookbanks** [comment]
Maybe we need to retire FCKEditor and use a different solution. It's never worked for us with macros.

I just don't know what to do about this and other reported issues around this. The protected source plugin is extensive and I'm not able to take on its development.

**Comment by Dirty-Butter** [comment]
I was attempting to find some place in the CKeditor config or some such place that showed the version number, so I would not get the old and new confused with each other. I noticed there is a list of plugins in build-config.js and the showprotected is not in that list. Should it be added? Does that have anything at all to do with whether or not the features of that plugin are available to CC?

**Comment by bhsmither** [comment]
One can custom-build a package of CKEditor. In doing so, the list of functions (standard plugins) are enumerated in that file. Even so, a pre-built "full" package will still enumerate all plugins included for that package. This does not interfere with adding third-party plugins. 

Look for a question mark on the bottom row of the editor toolbars.

**Comment by bhsmither** [comment]
In the CKEditor folder, find a file CHANGES.md.

There is also a clue in the file ckeditor.js, line 5, column 170.
