### ISSUE TITLE
Shop - Product Discounts TAB bug

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#2290]
If you set quantity discounts for a product, in front-end (shop) when you go to product it has (Quantity discounts available) link which does nothing.  On click it should open the Quantity Discounts TAB.

**Comment by bhsmither** [comment]
This is a known issue with Zurb's Foundation system:
https://github.com/zurb/foundation-sites/issues/4791

**Comment by abrookbanks** [comment]
It doesn't look like we will get a fix for this. 

We need a new skin really.

**Comment by sumwonlost** [comment]
Best solution I found is to remove the link and make text italic
