### ISSUE TITLE
On Sale with Quantity Discounts bug

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#2291]
Settings are as follows::

![image](https://user-images.githubusercontent.com/23044524/56456349-4edbd580-63ae-11e9-9b0f-cbbfaf25ec82.png)

As you can see the product is On Sale and has Quantity Discounts.

In front-end (shop) it display correctly in both On Sale box and in Page as shown below

![product_store_on_sale](https://user-images.githubusercontent.com/23044524/56456486-82b7fa80-63b0-11e9-9b2e-8e4a131c81e6.png)

However if I Buy (Add to Basket) quantity that meets Quantity Discounts it display the following

![product_store_on_sale_purchases](https://user-images.githubusercontent.com/23044524/56456733-d6781300-63b3-11e9-9941-4e619479fc9c.png)

Also the Add to Basket does not update prices if Quantities have been reached until page is refreshed.

In Product page (not Added to Basket) see below

![product_store_on_sale_front](https://user-images.githubusercontent.com/23044524/56457426-1a701580-63be-11e9-891c-aa610ef32129.png)

In Product page (Add to Basket - quantity that meets Quantity Discounts) see below

![product_store_on_sale_purchases_front](https://user-images.githubusercontent.com/23044524/56457445-602cde00-63be-11e9-9665-002dc1c99466.png)

I haven't tested these with Group Memberships and suggest that #2080 be done first,

**Comment by sumwonlost** [comment]
I have now tested with Group Memberships and have found many more issues with the pricing, on sale and quantity discounts with group memberships which many if not all can be fixed as outlined in #2080.

This bug is "doing my head in" on how prices are displayed.  And if it is "doing my head in" as a store owner then customers must surely be confused.

**Comment by sumwonlost** [comment]
Just to further explain.  Using the pricing settings above.  Go to front end and they display correctly, Retail, Sale and Discounts.

Now give a customer a membership group and login as that customer.

Pricing does not include sale price nor quantity discounts.  Call me stupid but are memberships not entitled to prices available pre login?

Prices displayed pre-login must be available to all including memberships (global) unless superseded (entered for a membership group).

**Comment by abrookbanks** [comment]
This is fixed now. A feature request is needed to adjust the dynamic price based on quantity.
