### ISSUE TITLE
new search forces user to page bottom

### ISSUE THREAD

**Issue by sparrowme** [cubecart/v6#2292]
If a user has searched by keyword (and maybe other methods) for a product and uses the **More** button at the bottom of the page to expand the listing, a new search for new keywords will cause the user to move to the bottom of the page when the results come back and automatically issue a **More** click as if the user did it.  The user then has to scroll back to the top of the page to review the earlier results of his new search.

**Comment by abrookbanks** [comment]
Great find thank you.
