### ISSUE TITLE
Large stores error when clearing cache

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2293]
This in some regard is a continuation of issue #2207 

Large stores with a large number of files in the cache directory have performance issues when clearing cache, in some cases throwing max execution errors.

`PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /home/.../domains/.../public_html/classes/cache/file.class.php on line 114`

The file cache clear function suffers from the same issue as the extra session data, it loops files 1 by 1 to unlink them, which can take an excessive amount of time, especially on larger stores.

**Comment by havenswift-hosting** [comment]
For "large" stores you might want to suggest they move different and better hosting - pay peanuts etc.  Just amazes me that people can run stores turning over tens of thousands per month and try to do with 2.99 per month hosting

1) Looping and unlinking files is an extremely quick operation unless the server is I/O bound

2) 30 seconds for max execution isnt enough for several different operations and if that is the maximum they allow.....

3) Switch to use memcached or Redis for cache and then not only does the cache work MUCH faster as it is memory based, you dont have these issues

**Comment by abrookbanks** [comment]
Best recommendation is to use Redis or Memcached etc...

All hosted cubecart stores use Memcached and provide enough resources for serious stores.
