### ISSUE TITLE
Search Tab in Admin Inactive

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#23]
Search tab is at top, but sidebar does NOT pop open when clicked. 
Everyone is used to Search on right - Suggest you make box more prominent, a color change perhaps???? Also, some liked click and others liked hover on v5 popup (like that it's no longer on right and in the way) - Could this be an optional setting?

https://dirtybutter.com/plushcatalog/v6/admin.php?_g=#sidebar

**Comment by abrookbanks** [comment]
I want to avoid settings and create a user interface that is friendly for as many as possible. The old side pop out was easy to miss. Maybe it can be more prominent. Investigating the search tab...

**Comment by abrookbanks** [comment]
Added JS to search tab toggle.
