### ISSUE TITLE
Plugin Language Changes Don't Work

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#230]
Example - UPS Shipping Plugin

File:
/modules/shipping/skin/admin/index.tpl

Code:
```
<div><label for="packagingWeight">{$LANG.ups.package_weight}</label><span><input name="module[packagingWeight]" id="packagingWeight" class="textbox" type="text" value="{$MODULE.packagingWeight}" /></span></div>
```

Step 1:
Go to the language entries for UPS shipping module.
i.e.
admin.php?_g=settings&node=language&language=en-GB&type=modules/shipping/UPS/language/module.definitions.xml#general
Change the text for the package_type entry to something else.

Step 2:
Go to the UPS shipping module.
i.e.
admin.php?_g=plugins&type=shipping&module=UPS
You will see the change made in the step above is not reflected.

The language change does exist in the 'CubeCart_lang_strings' table.
i.e.
![alt text](http://www.semperfiwebservices.com/cubecart-bug-screenshots/ups-language-entry-database.png "Database Entry")

Even after clearing all 3 caches, the language change is not used.

**Comment by havenswift-hosting** [comment]
I also believe that languages for any type of module (plugins, gateway, shipping etc) dont work

1) There is a French language file for the Canada Post shipping module (this is called fr_FR.xml which I think is a typo anyway as think it should be fr-FR.xml) but I dont think it ever picks up these language files.  We have a plugin where we are supplying a Spanish language file in the /public_html/modules/plugins/PLUGIN-NAME/language/ directory but this doesnt ever seem to get picked up by the system.

2) If I translate the plugin strings via the admin languages option, then these language strings are picked up (eventually although clearing cache doesnt seem to work immediately !) but if I then export these changes it either creates or overwrites (depending on what option I choose) a file in the main language directory - surely module language files should be written back to the correct module language directory

**Comment by abrookbanks** [comment]
This does actually work but it's purely a case of lack of documentation. Checkout CanadaPost... 

https://www.cubecart.com/extensions/shipping-methods/canada-post

So long as the modules/{type}/{name}/language/en_GB.xml etc exists this should work. 

CubeCart won't translate the modules.definitions.xml file the corresponding xx_XX.xml file is needed.

**Comment by abrookbanks** [comment]
Even that doesn't work though.. reopening.

**Comment by abrookbanks** [comment]
OK so it does work but the language file needs to take the following format:

modules/{type}/{name}/language/en-GB.xml NOT en_GB.xml Sample content:
```
<?xml version="1.0" encoding="UTF-8" ?>
<!--
 * CubeCart v6
 * ========================================
 * CubeCart is a registered trade mark of CubeCart Limited
 * Copyright CubeCart Limited 2014. All rights reserved.
 * UK Private Limited Company No. 5323904
 * ========================================
 * Web:   http://www.cubecart.com
 * Email:  sales@devellion.com
 * License:  GPL-2.0 http://opensource.org/licenses/GPL-2.0
-->
<language version="1.0">
  <info>
    <title>British</title>
    <code>en_GB</code>
    <character_set>utf-8</character_set>
    <version>1.0.0</version>
    <minVersion>5.0.0a</minVersion>
    <maxVersion>5.1.*</maxVersion>
  </info>
  <translation>
	<!-- Common Strings -->
	<string>
	  <name>name</name>
	  <value><![CDATA[Canada Post 123]]></value>
	  <type>canada_post</type>
	</string>
  </translation>
</language>
```

**Comment by abrookbanks** [comment]
![screen shot 2015-03-04 at 10 36 20](https://cloud.githubusercontent.com/assets/4520803/6482044/513884ee-c25a-11e4-935a-d0b7562b7016.png)

![screen shot 2015-03-04 at 10 35 56](https://cloud.githubusercontent.com/assets/4520803/6482062/6b822120-c25a-11e4-82b1-1dc354fe28d3.png)

**Comment by havenswift-hosting** [comment]
So any additional language files have to be manually created ?  

Any reason why the format of module language files is different to standard language files - just seems confusing ?

Can you confirm that if a language file is created such as modules/{type}/{name}/language/es-ES.xml for example and then changes are made through the Admin Languages program and then written out, that it is this file that is updated ?  In my tests changes were written out to /language/es-ES.xml which seems completely wrong

**Comment by abrookbanks** [comment]
> So any additional language files have to be manually created ?

Correct

> Any reason why the format of module language files is different to standard language files - just seems confusing ?

I didn't notice a difference? The code used to parse master language files is the same as module language files. 

Can you confirm that if a language file is created such as modules/{type}/{name}/language/es-ES.xml for example and then changes are made through the Admin Languages program and then written out, that it is this file that is updated ? In my tests changes were written out to /language/es-ES.xml which seems completely wrong

> No its stored in the database and overwrites the es-ES.xml file after its loaded with the changes. This is how the main languages work too.
