### ISSUE TITLE
Invalid PCRE Modifier

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2301]
In seo.class.php, line 637:
```
if (preg_match('#^(.*/)?[\w]+.[a-z]+\?_a\=([\w]+)(?:\&(amp;)?([\w\[\]]+)\=([\w\-\_]+)([^"\']*))$#ieS', $path, $match)) {
```
PHP 7 is complaining that the `e` modifier is no longer supported.

This page:
`https://www.php.net/manual/en/reference.pcre.pattern.modifiers.php`
claims the `e` modifier is ignored by all PCRE functions other than preg_replace, and that `e` is now deprecated(PHP5.5.0) and removed(PHP7.0.0).

Suggest removing the `e` modifier, to read:
```
if (preg_match('#^(.*/)?[\w]+.[a-z]+\?_a\=([\w]+)(?:\&(amp;)?([\w\[\]]+)\=([\w\-\_]+)([^"\']*))$#iS', $path, $match)) {
```

**Comment by abrookbanks** [comment]
Thanks but this has been done already:
https://github.com/cubecart/v6/pull/2220
