### ISSUE TITLE
Card Capture Module to Query Encryption Class for Capabilities

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2302]
Currently, Card Capture 1.0.6 makes a hard test (gateway.class.php line 100) for the MCRYPT extension.

Suggest having the Encryption class return a result that callers can use to verify if **any** encryption that can be setup by the Encryption class is available.

Then, in Card Capture, instantiate the Encryption class, then test `$this->_encryption` for not empty if something is available.

**Comment by abrookbanks** [comment]
Card capture upgraded to better handle encryption method
