### ISSUE TITLE
Product Specifications - include Digital

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#2303]
In content.product.php at bottom of specifications section need to include the following code:

`                  {if $PRODUCT.digital > 0}
                  <tr>
                     <td>{$LANG.catalogue.product_type_digital}</td>
                     <td>{$LANG.common.download}</td>
                  </tr>
                  {/if}`

This displays whether the product is digital download.  I cannot see anywhere else in product that it tells customer that it is a download.

**Comment by abrookbanks** [comment]
Nice little touch. Thank you.
