### ISSUE TITLE
Product Options and Quantity Discounts display despite being Unavailable or Out of Stock

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#2304]
In content.products.php it dispay Product Options and Quantity Discounts if Unavailable or Out of Stock.

Why do these need to display if Customer is unable to Buy?  The only reason I can think of is for information purposes for future when product is available and in stock.  Pretty much useless with preference not to display these until Available and In Stock.

Following the include {include file='templates/content.checkout.medium-up.php'} and {include file='templates/content.checkout.small.php'} files, they both have the following include {include file='templates/element.product.options.php'} which needs to be replaced with following code.

`{if $PRODUCT.available > 0}` 
`   {if !$CTRL_OUT_OF_STOCK}` 
`      {include file='templates/element.product.options.php'}`
`      {if isset($PRODUCT.discounts)}` 
`         <p>({$LANG.catalogue.bulk_discount})</p>` 
`      {/if}` 
`   {/if}` 
`{/if}` 

Note, I have moved Quantity Discounts from element.product.call_to_action.php to here.  I also remove the dead link see #2290 as what is point of having a link to nowhere?  It can be added later when working or in new skin.

In content.product.php the Quantity Discount TAB needs to also be encapsulated.  Again there is no need to display the TAB if product is unavailable or out of stock.

`{if $PRODUCT.available > 0}` 
`   {if !$CTRL_OUT_OF_STOCK}` 
`      {if isset($PRODUCT.discounts)}` 
`         <dd><a href="#quantity_discounts">{$LANG.catalogue.quantity_discounts}</a></dd>` 
`      {/if}` 
`   {/if}` 
`{/if}`

**Comment by bhsmither** [comment]
I would use "Hide out of Stock" in admin.

**Comment by sumwonlost** [comment]
I have tried "Hide out of Stock" and in Products -> select Product, I have checked "Use Stock Level" and set "Stock Level" = 0.  The Product still displays showing "This product is currently out of stock" message.  It also displays the Options and Quantity Discounts TAB.

As I said, I have no issue with the Product displaying details, description, specifications and reviews when Out of Stock or Unavailable.

I cannot see the logic in displaying Options and Quantity Discounts.  Irrespective what Options or Quantity Discounts are displayed, a Customer cannot Buy, so what is the point in displaying these until Available and In Stock?

**Comment by sumwonlost** [comment]
After a bit of testing I found another post that directed me to problem.  I have to have Store online and be logged out of Admin.  All works correctly for Out of Stock products, not displaying these.

The issue is now it needs to do same if product Unavailable.

Furthermore this can be improved by displaying "Coming Soon" message if a List from Date is entered with the option to display date.

**Comment by abrookbanks** [comment]
Right now stock is checked after product option combination is submit. It would be better to show options first agreed but this gets complex with many option groups.

I have to put this down as a feature request.
