### ISSUE TITLE
Store Product Condition in order_inventory table.

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#2306]
It would be ideal if Product Condition is stored in order_inventory table especially for dispute resolution.  Eg the product is sold as Used or Refurbished but Customer claims it was advertised as New.

**Comment by Dirty-Butter** [comment]
SemperFi created a ProductDescription addition to the database for me for just that reason. Not sure if he ever turned that into something for sale.
We sell used toys - condition descriptions change as one sells and I edit to add another one as it is found. VERY important that we and the customer get a copy of exactly what they bought.

**Comment by sumwonlost** [comment]
You said it, VERY important.  So I need a plugin for something that should be standard?  Seriously what business cannot give you exact details of a sale, irrespective the type of business?  This is a failure in auditing procedures.  I must be able to replicate a sale exactly as sold.
