### ISSUE TITLE
When cloning a product, none of the translations are cloned

### ISSUE THREAD

**Issue by bos4711** [cubecart/v6#2310]
See attached screenshot. The second row is the original product, with an English translation. The first row is the clone, without the translation.

**Comment by bos4711** [comment]
Github don't like my attachments, so here's a Dropbox-link to the screenshot:

https://www.dropbox.com/s/36qwmjzqz6xwgf7/2019-05-21_190749.png?dl=0

**Comment by bhsmither** [comment]
Please verify that you have Store Settings, Extra tab, **Product Clone** section, Translations: checked.

**Comment by bos4711** [comment]
Confirming that this checkbox was not checked. My bad.

Closing ticket.
