### ISSUE TITLE
Search String Construction

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2312]
Please verify in class.catalogue.php, lines 1880-1887:
```
                    default:
                        $search_data['keywords'] = str_replace(' ', '*) +(*', $search_data['keywords']);
                        $search_data['keywords'] .= '*)';
                        $search_data['keywords'] = '+(*'.$search_data['keywords'];
                        $mode = 'IN BOOLEAN MODE';
                        break;
                    }
                    $words = preg_replace('/[^\p{Greek}a-zA-Z0-9\s]+/u', '', $search_data['keywords']);
```
With no modifiers on `foo bar`, the string constructed should be:
```
+(*foo*) +(*bar*)
```
However, line 1887 then strips all that out.

(Not sure why the Unicode Greek block is being included, and not any others.)

**Comment by abrookbanks** [comment]
I honestly don't know. This code has been there since 6.0.0.

**Comment by abrookbanks** [comment]
It seems pointless to remove the operators after adding them!? I'll figure this out.

**Comment by abrookbanks** [comment]
I'm going to close this as the original developer is long gone from the CubeCart team. 

The search needs a comprehensive rewrite.
