### ISSUE TITLE
admin.category.tabs placement issue

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2315]
The mentioned hook is only called when the action is add/edit, so the hook can't be used on the general "categories" list page, it should be available for both.

**Comment by abrookbanks** [comment]
For fear of upsetting any existing extensions that want it in the add/edit view I added a second hook.

**Comment by abrookbanks** [comment]
.... hope that's ok.

**Comment by Noodleyman** [comment]
seems reasonable and the best approach, thank you.

**Comment by abrookbanks** [comment]
Holy sh!t you are quick. Have you been refreshing this page for 28 days? LOL

**Comment by Noodleyman** [comment]
I've pretty much got an entire screen dedicated to notifications (for many things), the joy of using 6 screens for R&D :)

**Comment by abrookbanks** [comment]
Blimey 6 screens. I have three. 
![IMG_20190627_165948](https://user-images.githubusercontent.com/4520803/60281626-27007500-98fd-11e9-83fa-933c84085cae.jpg)

**Comment by Noodleyman** [comment]
where the magic happens (old pic from a tidy day!). got a lamp on the laptop and added another screen to the right since this was taken.

![image](https://user-images.githubusercontent.com/10614018/60282048-f836ce80-98fd-11e9-8092-864626b4b9f4.png)

**Comment by abrookbanks** [comment]
Blimey. We have matching Ikea bins. :laughing:

**Comment by Noodleyman** [comment]
It's not really an office without something from Ikea :p

**Comment by abrookbanks** [comment]
Petty much all mine is Ikea. Wife keeps her Gin in here too. haha

![IMG_20190627_171936](https://user-images.githubusercontent.com/4520803/60282884-db9b9600-98ff-11e9-8ad4-a21fc68cc736.jpg)
