### ISSUE TITLE
CKEditor ProtectedSource RegEx

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2316]
Is the change for #2284 still working for you?

In the discussion, there is (erroneously) two versions of the regex:
`/{\S*?.*\S}/g` and `/{\S*?.*?\S}/g`

Note the extra question mark.

The version with the extra question mark works for me. The one without seems to gather up too much of the text.

**Comment by abrookbanks** [comment]
I think I reverted it to how it was before. I need to get onto these issues.

**Comment by abrookbanks** [comment]
I must have tested the correct regex then copied and paste the wrong one to source control.

Thanks for your help here.
