### ISSUE TITLE
Search improvements

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2317]
It would be very useful to be able to configure which fields are used in a search - currently product name, product code and product description but some stores would not want the description field included for example as a keyword can be included in a description but not display a relevant product

I also know there are people that have modified the search to include searching in the meta keywords fields (which as they arent used for anything else for the last X number of years).  A simple set of check boxes would give store owners a lot of control

**Comment by Dirty-Butter** [comment]
I'm one Bsmither helped modify to use meta keywords, as some would search for cat, another kitty, and others for kitten - but I would not want to clutter a description with every such alternate word.

**Comment by Dirty-Butter** [comment]
It would also be great it there were stock admin choices to create searches to be term AND term, as well as a choice for term OR term. That took quite a bit of coding from Bsmither to get AND to work for our store. OR was useless for us.

**Comment by sumwonlost** [comment]
I would also like to see the option to search selected categories.  ie I know the category/s but need to find product.  Similar to how Manufacturers works.

This helps to refine search for larger stores where Keywords alone might throw up many results.

**Comment by sumwonlost** [comment]
It is also suggested that a min of 3 characters be entered as a Keyword, a single character is likely to return most products.

**Comment by abrookbanks** [comment]
It needs a complete overhaul I think.
