### ISSUE TITLE
Invoice formatting of products with options

### ISSUE THREAD

**Issue by NaturalSigns** [cubecart/v6#232]
Hi, with reference to the figure below, ideally on the invoice all product options should be on new lines to make it easier to read (also preferably in the default order as used on the product listing page [though not essential]).
![printed invoice - not formatted](https://cloud.githubusercontent.com/assets/10531097/6256417/debbbab2-b7af-11e4-9d8e-189e8fc17417.png)

**Comment by abrookbanks** [comment]
This is one of those debatable ones.. a new line = wasted paper in some people eyes. 

You can easily change line 54 in admin/skins/templates/orders.print.php from:

```<br>{$LANG.catalogue.title_options} {foreach from=$item.options item=option}&raquo; {$option}{/foreach}```

.. to something like:

```<br>{$LANG.catalogue.title_options} {foreach from=$item.options item=option}<br>{$option}{/foreach}```

**Comment by abrookbanks** [comment]
I decided to make the changes... Screenshot below (testing profanity censored).

![screen shot 2015-02-19 at 08 41 32](https://cloud.githubusercontent.com/assets/4520803/6263712/6a207300-b813-11e4-862d-55d4086da8c4.png)
