### ISSUE TITLE
Syntax error in search query

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2320]
Seen in multiple client stores and also reproduced in a clean store with basic demo data.

Ensure "Hide out-of-stock product" is unticked in Store Settings | Stock tab

Do a search via advanced search for "test" and it returns the one product expected

Then do same search but tick "In stock" tickbox and it returns no product and throws the following errors

File: [catalogue.class.php] Line: [1895] "SELECT I.*, MATCH (I.product_code,I.description,I.name) AGAINST('test' IN BOOLEAN MODE) AS Relevance FROM CubeCart_inventory AS I LEFT JOIN (SELECT product_id, MAX(price) as price, MAX(sale_price) as sale_price FROM CubeCart_pricing_group WHERE group_id = 0 GROUP BY product_id) as G ON G.product_id = I.product_id WHERE I.product_id IN (SELECT product_id FROM `CubeCart_category_index` as CI INNER JOIN CubeCart_category as C where CI.cat_id = C.cat_id AND C.status = 1) AND I.status = 1 AND (MATCH (I.product_code,I.description,I.name) AGAINST('test' IN BOOLEAN MODE)) >= 0.5 AND AND `live_from` < UNIX_TIMESTAMP() AND `live_from` < UNIX_TIMESTAMP() ORDER BY `Relevance` ASC LIMIT 12 OFFSET 0 " - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND `live_from` < UNIX_TIMESTAMP() AND `live_from` < UNIX_TIMESTAMP() ORDER BY' at line 1
--
File: [catalogue.class.php] Line: [1897] "SELECT COUNT(I.product_id) as count, MATCH (I.product_code,I.description,I.name) AGAINST('test' IN BOOLEAN MODE) AS Relevance FROM CubeCart_inventory AS I LEFT JOIN (SELECT product_id, MAX(price) as price, MAX(sale_price) as sale_price FROM CubeCart_pricing_group WHERE group_id = 0 GROUP BY product_id) as G ON G.product_id = I.product_id WHERE I.product_id IN (SELECT product_id FROM `CubeCart_category_index` as CI INNER JOIN CubeCart_category as C where CI.cat_id = C.cat_id AND C.status = 1) AND I.status = 1 AND (MATCH (I.product_code,I.description,I.name) AGAINST('test' IN BOOLEAN MODE)) >= 0.5 AND AND `live_from` < UNIX_TIMESTAMP() AND `live_from` < UNIX_TIMESTAMP() GROUP BY I.product_id ORDER BY `Relevance` ASC " - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND `live_from` < UNIX_TIMESTAMP() AND `live_from` < UNIX_TIMESTAMP() GROUP BY' at line 1

**Comment by bhsmither** [comment]
So, line 1895 returns something that is true-ish even though the database reports an error.

See #2279.

**Comment by abrookbanks** [comment]
I can't reproduce this. This issue is familiar though and I believe it may be fixed already. 

The SQL on the left comes from my test under same conditions.

![Screenshot 2019-06-28 at 10 01 40](https://user-images.githubusercontent.com/4520803/60331065-c2d8c200-998b-11e9-841e-da2e8962b4f2.png)

**Comment by abrookbanks** [comment]
Please check the catalogue class against the current one in version control and see if the issue persists.

**Comment by havenswift-hosting** [comment]
I have tested this using the current catalogue class file from git and it is still happening exactly as described - this is in multiple client stores and also in a fresh install with no changes and no plugins

**Comment by abrookbanks** [comment]
I have to be doing something differently then....

**Comment by abrookbanks** [comment]
http://static.cubecart.com/issue-2320.mp4 

Maybe the product has a different setting. This store is using default value and all test products are cloned from the default one.

**Comment by havenswift-hosting** [comment]
You are doing one search which is the one that I have said works -  I detailed one that works and then one that didnt !

Advanced search, then click "In Stock" button and search.  Will return no items due to syntax error

**Comment by abrookbanks** [comment]
I was just testing you again Ian. Honest!😜

You love it.

**Comment by abrookbanks** [comment]
On a serious note I'm dyslexic and miss things like this all the time. PERFECT for this job.🤪

**Comment by havenswift-hosting** [comment]
No worries at all - I see from the submit that you managed to reproduce.

Unfortunately it isnt a complete fix - works if you tick "In Stock" but the same problem happens if you tick "Featured Products Only" - double AND

Always amazes me that people with dyslexia always seem to be able to spell that lol

**Comment by abrookbanks** [comment]
Cool thanks Ian. I'll check that. Thanks for putting up with me.

**Comment by abrookbanks** [comment]
Thanks again. Fix above corrects that for me.

**Comment by havenswift-hosting** [comment]
That fixes it if you only select "Featured Products Only" and first fix is when only selecting "In Stock" but if you select both tick boxes it still has a double AND and fails - one more go lol

**Comment by abrookbanks** [comment]
Hmm I tested many combinations.. I'll try again.

**Comment by abrookbanks** [comment]
All sorted. All scenarios in advanced search tested.

**Comment by havenswift-hosting** [comment]
Confirmed as fixed - thanks

**Comment by abrookbanks** [comment]
Great! Thanks for confirming.
