### ISSUE TITLE
Download Links not in Customer Account and download count not incrementing

### ISSUE THREAD

**Issue by richosr** [cubecart/v6#2321]
Since the last few updates download links are not appearing in customer accounts, it says the download link is no longer available when it is.

In addition the downloads count is not incrementing when a download is actioned.

![dl001](https://user-images.githubusercontent.com/992654/59364058-745adf00-8d60-11e9-9081-dda41e55ca50.jpg)
![dl002](https://user-images.githubusercontent.com/992654/59364059-745adf00-8d60-11e9-80a5-9777135f7fd9.jpg)
 
regards
Steve

**Comment by richosr** [comment]
Just checked the error log and perhaps the issue is down to?


Today, 16:24 | File:  [controller.admin.pre_session.inc.php] Line: [26] "SET @@time_zone =  'Europe/London'" - Unknown or incorrect time zone: 'Europe/London'
-- | --
  | Today, 16:24 | File: [controller.index.inc.php] Line:  [27] "SET @@time_zone = 'Europe/London'" - Unknown or incorrect time  zone: 'Europe/London'
  | Today, 16:24 | File:  [controller.admin.pre_session.inc.php] Line: [26] "SET @@time_zone =  'Europe/London'" - Unknown or incorrect time zone: 'Europe/London'
  | Today, 16:24 | File: [controller.index.inc.php] Line:  [27] "SET @@time_zone = 'Europe/London'" - Unknown or incorrect time  zone: 'Europe/London'
  | Today, 16:24 | File:  [controller.admin.pre_session.inc.php] Line: [26] "SET @@time_zone =  'Europe/London'" - Unknown or incorrect time zone: 'Europe/London'
  | Today, 16:24 | File: [controller.index.inc.php] Line:  [27] "SET @@time_zone = 'Europe/London'" - Unknown or incorrect time  zone: 'Europe/London'
  | Today, 16:24 | File: [controller.index.inc.php] Line:  [27] "SET @@time_zone = 'Europe/London'" - Unknown or incorrect time  zone: 'Europe/London'
  | T

**Comment by bhsmither** [comment]
Possibly related to (closed) issue #2313.

The timezone issue is unrelated - and is known.

**Comment by abrookbanks** [comment]
Pretty confident this is resolved. There were a number of issues recently relating to downloads and with prefixed database tables.
