### ISSUE TITLE
keep getting error in error log saying column doesn't exist in query

### ISSUE THREAD

**Issue by richosr** [cubecart/v6#2322]
keep getting this error in error log:

File: [cubecart.class.php] Line: [2076] "SELECT `ns_CubeCart_order_inventory`.*, `ns_CubeCart_order_summary`.`status` FROM `ns_CubeCart_order_inventory` INNER JOIN `ns_CubeCart_order_summary` ON `CubeCart_order_inventory`.`cart_order_id` = `CubeCart_order_summary`.`cart_order_id` WHERE ns_CubeCart_order_inventory.id = '4751' ;" - Unknown column 'CubeCart_order_inventory.cart_order_id' in 'on clause'

Steve

**Comment by richosr** [comment]
Fixed that issue by changing Line 2076 in cubecart.class.php to as the table prefix code was missing from the sql statement on two or three of the field names:

if (($product = $GLOBALS['db']->select('`'.$GLOBALS['config']->get('config', 'dbprefix').'CubeCart_order_inventory` INNER JOIN `'.$GLOBALS['config']->get('config', 'dbprefix').'CubeCart_order_summary` ON `'.$GLOBALS['config']->get('config', 'dbprefix').'CubeCart_order_inventory`.`cart_order_id` = `'.$GLOBALS['config']->get('config', 'dbprefix').'CubeCart_order_summary`.`cart_order_id`', '`'.$GLOBALS['config']->get('config', 'dbprefix').'CubeCart_order_inventory`.*, `'.$GLOBALS['config']->get('config', 'dbprefix').'CubeCart_order_summary`.`status`', array('id' => $download['order_inv_id']))) !== false) {
 

So have fixed the issue here temporarily but it will need fixing for next release.

Steve

**Comment by bhsmither** [comment]
This is (closed) issue #2313.
