### ISSUE TITLE
CubeCart_inventory.stock_warning to be Signed

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2323]
Request that `CubeCart_inventory.stock_warning` be a `signed` column.

This allows for:
* set negative for one-off items to not show up in Stock Warning reports
* comport with SQL code `$where` in `dashboard.index.inc.php (341)` comparing less-than zero
* other uses on per-product basis

**Comment by bhsmither** [comment]
Duplicate of #1796

**Comment by abrookbanks** [comment]
Thanks Brian.
