### ISSUE TITLE
Bug - GEO json form display

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#2334]
Globally Country and State fields should work as per Countries & Zones settings.

All forms should work as follows.

IF geo_country.status = 0 it correctly does not display the Country in dropdown

IF geo_country.status = 1 (State required) it correctly list All States for the selected Country that are in geo_zones.  As there is no select option (value = 0) in the States dropdown, it displays States listed, this ensures that the "required" condition is met.
ELSE it display textbox if No States exist in geo_zones for selected Country.   BUG - This has been set as "required" and as such needs validation.  It currently allows empty field submission.

IF geo_country.status = 2 (State optional) it correctly list All States for the selected Country that are in geo_zones.  BUG - Here you need select option (value = 0) in the States dropdown, this is "optional" and not be **forced** to make a selection.
ELSE it display textbox if No States exist in geo_zones for selected Country.   It correctly allows empty field submission.

IF geo_country.status = 4 (States disabled) - BUG - it displays the States field.  If disabled the States field should be hidden for selected Country.

**Comment by sumwonlost** [comment]
The next BUG - the States dropdown assumes the list is comprehensive and no omissions. 

What happens if Zone is not on list?  User has no choice but to select from dropdown list.

Need an "Other" option at bottom of States dropdown - not so much for Admin as they can firstly add the new State to db, primarily the issue is on Customers side (addresses).

When "Other" selected, it hides (replaces) the dropdown with textbox.  You would need a toggle icon to go back to dropdown.  You need validation to ensure an existing Zone has not been re-entered if "Other" which isn't required in Status 2 & 3 textboxes as no records (Zones) exist.

Ideally Admin could have control which Country/Zones are completed and in Countries, you have a checkbox for each Country.  If checked it display "Other" in State dropdown, if unchecked it does not display as Admin has deemed the list of Zones for Country to be comprehensive/complete.

**Comment by sumwonlost** [comment]
The last remaining thing #1720.

On Save if State is textbox (status 2 & 3 or "Other") it save new Zone to geo_zone with status = 2 (pending).  It add Note to Administrator who then confirms new Zone, adds missing details (abbrev) and changes Status = 1.  Done,  populating our DB as we go along.

**Comment by sumwonlost** [comment]
You could then go 1 step further.  Following on from last post, it can also send CubeCart the new Zone details (collected from stores) which would help build a comprehensive geo_zones and available to all.

We as a community build our own comprehensive geo_zones.

**Comment by abrookbanks** [comment]
These conditions wee designed for the front end. 

> States dropdown assumes the list is comprehensive and no omissions.
> 
> What happens if Zone is not on list? User has no choice but to select from dropdown list.

True but then there is a good chance they can proceed though the checkout but get incorrect or no shipping. They will need to contact the store to get the state added and shipping configured accordingly. 

There are some interesting points here but none that need attention in my opinion.

**Comment by abrookbanks** [comment]
> You could then go 1 step further. Following on from last post, it can also send CubeCart the new Zone details (collected from stores) which would help build a comprehensive geo_zones and available to all.

Nice idea. Ive though the same about translating CubeCart to other languages.

**Comment by sumwonlost** [comment]
Yes it currently works but what was the purpose of changing country statuses if they don't work as per settings as outlined?  

The idea of adding new zones as outlined is to comprehensively build zones as to limit rubbish (misspelling and case/capitals).  Once it has been verified and enabled by Admin it appears in dropdown correctly and saved to db addresses correctly.  It is all about getting the required details by limiting the mistakes the "dummies" can make.  

Customers do not need to contact store to add Zone to be able to checkout with my method, it is all about automation, no inconvenience to customer and minimal work for Admin in verifying new zone without the need to interact with customer.

**Comment by abrookbanks** [comment]
> Yes it currently works but what was the purpose of changing country statuses if they don't work as per settings as outlined?

It's for the front end not the back end. If you do not use a recent version of the Foundation skin then it might not be coded to use it. 

> Customers do not need to contact store to add Zone to be able to checkout with my method

Agreed but many merchants configure shipping by state and there wouldn't be appropriate shipping setup.

**Comment by sumwonlost** [comment]
I understand it is for front end as explained admin can firstly add new zone before adding address that uses the new zone.

When I find bugs using my skin, I go to my demo site and do all my testing with latest version of CubeCart using Foundation skin to confirm.  I can guarantee it is not working as outlined, however I will do a new install tonight and retest again.  Let you know tomorrow.

Configuring shipping by state may not be the case for international shipping where the cost is the same for all zones, so it may not be necessarily be picked up.

**Comment by abrookbanks** [comment]
OK let me know your findings. Please separate individual issues and feature requests.

**Comment by sumwonlost** [comment]
I re-tested over weekend, yes the status part work correctly. 

I will breakdown the remainder and submit them as Features
