### ISSUE TITLE
CubeCart not recording IPv6 against customer records

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2336]
It appears that CubeCart isnt recording the IPv6 address against the customer record if the website is setup to allow IPv6 connections and the customer is coming from an ISP that uses IPv6 - customer records in this situation are blank.

Not normally a major problem but for any customers using the eWay payment gateway, this stops customers from making payments as they validate the IP address of the payee before allowing them to enter card details - obviously a MAJOR issue for these customers !

**Comment by havenswift-hosting** [comment]
This also means that sites cannot use Cloudflare as they enable IPv6 by default

**Comment by abrookbanks** [comment]
The customer IP address table column is varchar(45) which should be long enough for IP v6 so long as the IP address is detected correctly. 

I need steps to reproduce this probably on the clients store. Maybe they can open a support ticket. CubeCart predominantly uses $_SERVER['REMOTE_ADDR'] to detect this value which should get IPv4 and IPv6 addressed. 

I need to look at this as a case situation.

**Comment by havenswift-hosting** [comment]
The database may be able to hold IPv6 values but those arent being passed through to be stored and it is happening in every single store, not simply the specific client that was using eWay (that just highlighted the initial problem) - simply check the IP address field in the customer table and also against the newsletter subscriber history - always blank whenever a visitor is connecting from a IPv6

**Comment by abrookbanks** [comment]
Cloudflair will return it under server variable HTTP_CF_CONNECTING_IP but there is also HTTP_X_FORWARDED_FOR which should probably be taken first. CubeCart checks for this so it should work. 

Maybe you can add a script to the server with the code:

```
<?php
echo "<pre>";
var_dump($_SERVER);
echo "</pre>";
```

Then look for the variable name foe the IP V6 string.

**Comment by Dirty-Butter** [comment]
I can concur that I've not seen IP addresses for some time now. Just assumed it was something I had done wrong :)

**Comment by Dirty-Butter** [comment]
Is this what an IPv6 IP address should look like?
2600:6c64:5180:909:f4e8:7d8d:b6a0:3caa

**Comment by havenswift-hosting** [comment]
Yes that is an IPv6 address
