### ISSUE TITLE
These need urgent looking at #2080, #2291

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#2337]
I have had related issues outstanding for 12 months. 

#2080, #2291

I am glad you agree it is a bug otherwise you would have closed these,

How prices are displayed is a major part of a cart and currently as outlined do not comply with Australian Consumer Laws and question how they do in UK.

The **"Retail Price"** should always be displayed and similar to "On Sale", "Qty Discounts" price should display with "Retail Price" crossed out.  This fixes how prices are displayed for "Qty Discounts"

If a "Membership Price" does not exist or > "On Sale" if exist, members get the "On Sale" else "Retail Price".  This ensure members get "On Sale" if "Membership Price" does not exist or "Membership Price" is greater than "On Sale".  If "On Sale" does not exist then "Retail Price".  This fixes pre-login "On Sale" and logged in "On Sale" for Members.  As above it display the "Membership Price" with the "Retail Price" crossed out.

**Comment by abrookbanks** [comment]
Both these tickets are still open and we will get to them in due course. If you need urgent support please open a technical support ticket.
