### ISSUE TITLE
Bug - Read Only -> Store Settings + others

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#2338]
I have Set an Admin as Read-Only for All sections to test.

Bug Store Settings - These can be edited and Saved.  #2329 may have fixed this but have not tested yet.

Bug Customer List -> GDPR Tools - I can delete Customers & Guests

I will post others as i find them

**Comment by abrookbanks** [comment]
Relates to #2329

**Comment by abrookbanks** [comment]
Most of this was fixed with #2329. Added extra read only insurances.

**Comment by abrookbanks** [comment]
Please add any new ones as new issues. Thanks.
