### ISSUE TITLE
Email Log - improvement

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#2341]
Can you add an extra column displaying the Department the email was sent to if department email same as contact form email.  It helps to identify the Departments if they use the same (optional) email.

**Comment by bhsmither** [comment]
We can try this. In `/classes/cubecart.class.php`, near line 1523:
```
From:
'to' => $email,

To:
'to' => $department." || ".$email,
```
The Email Log will now show in the To column for Contact Us emails (for example):
Department 1: `Dept1 || email@example.com`
Default: `StoreName || email.com`

**Comment by sumwonlost** [comment]
Thanks.  It does the job of identifying the Department making it easy for Admin,  Need Al to add it to master.

Next Bug - It has a link to Search Customers.  What is purpose of having link to search Customers if the email address is store.email, contact.email (contact form) or department.email?

This also eliminates the fact that a record will never be found even if email exist for customer that has one of the 3 addresses above as the above fix searches $department." || ".$email

**Comment by abrookbanks** [comment]
This is a bit more complex than it first seems. See commits above.
