### ISSUE TITLE
Error Logs not HTML encoded

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2343]
This can cause smarty parse error.

**Comment by bhsmither** [comment]
Do you have a case where this happened?

As I see it, the Smarty variable `$log.message` contains a string - which is not further parsed. Thus, Smarty is not influenced by the string value.

What converting these five characters to html entities does, actually, is to stop the browser from acting on these characters and possibly hiding or distorting the display.

(See Example 5.10 at https://www.smarty.net/docs/en/language.modifier.escape.tpl)

Please re-evaluate #1354 and #657.

**Comment by abrookbanks** [comment]
I'll see if I can dig out the support ticket tomorrow. Essentially an error around some JS in a front end template stored curly brackets in the error log causing the admin error log page to corrupt too.
