### ISSUE TITLE
Merge to File and redundant Lang Strings table 

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#2344]
Sorry to be a pain but I have taken CubeCart as a personal project and aim to help to make it better.

Ref #1838

The fixes made work perfectly but still ask why the need for language strings table in db?

Looking at how language files work.

You need to create new language,xml file,  It can have no strings as it defaults to definitions.xml strings OR you can have ALL strings unchanged OR you can have ONLY changed strings and it defaults to definitions.xml for unchanged strings OR you have both changed and unchanged strings.

Importantly in all instances it uses the changed strings in language.xml, so why the need to save to db when they can be written directly to the language.xml file.

OK.  I see Merge to File.  I Merge to File and it saves ONLY the changed strings to language.xml file and leaving other strings unchanged (if any).

Running a test - Admin -> Languages -> select language -> Find a string (phrase) that you know where it appears, change it and Save.  It adds changed string to db.  Goto where string (phrase) appears to confirm changes (clear cache first).  Now go back to the Languages page and Merge to File.  To confirm open languages/language.xml.  Next reset the edited string back to default and Save.  This has now removed the entry from db.  Clear cache and go to where the string appears, it still displays the changed string from language.xml

So why the need to save to db when it can be saved directly to language.xml and works perfectly?

Similarly plugins work the same way and should be able to Merge to File.

Now let's look at the whole process.  

Admin -> Languages -> Add Language (complete details and Save).  It creates the language.xml with no strings (defaults to definitions.xml strings)

Next you would make changes as currently do but on save it Merge to File directly (adding as currently does) ONLY the changed fields.

The Phrases Form would list all Phrases as it currently does from the definitions.xml EXCEPT it no longer goes to db to find the changed strings to highlight AS it now goes to languages.xml and gets these.  The ONLY strings in the language.xml should be changed (edited) strings using this method.

What happens if user imports a language.xml file that has unchanged strings in it?

Everything works correctly EXCEPT the Phrases Form would have the unchanged strings highlighted.  Reset the phases (if it bothers you) back to original (which would be the same) and save.  On save it Merge to File removing the string/s.

Plugins should work the same, when creating the module.language.xml it should be empty rather than a replication of module.definitions.xml.

All done without the need for db using CubeCart languages system.

**Comment by sumwonlost** [comment]
The default language strings are always those in definitions.xml and module.definitions.xml unless superseded (edited) by those in language.xml and module.language.xml.  If a string does not exist in these it fallback to the strings in definitions.xml and module.definitions.xml.

**Comment by abrookbanks** [comment]
This would need to come into new major version.
