### ISSUE TITLE
Update needed for SagePay module?

### ISSUE THREAD

**Issue by romanklabal** [cubecart/v6#2347]
SagePay has released information about PSD2 and 3D Secure v2 which takes place on September 14th 2019. Will you please be able to go through the tech specs and update the CC SagePay module if necessary?

More information:
https://www.sagepay.co.uk/support/12/36/3d-secure-explained

Technical guide:
https://www.sagepay.co.uk/library/document/directintegrationandprotocol4guidelinespdf

Thanks.

**Comment by abrookbanks** [comment]
No update needed. I've been in contact with them concerning this already. The payment pages are hosted by SagePay and are compliant. 

Saying this we plan to build a new integration taking advantage of their hosted JS checkout shortly.

**Comment by romanklabal** [comment]
Awesome, thanks for the info Al.
