### ISSUE TITLE
FileManager - directory named 0 (zero)

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2348]
trying to setup a naming convetion, top level 0-9 and a-z based on product codes,  however a directory named "0" (zero) cannot be browsed via the FileManager

admin.php?_g=filemanager&subdir=0

I'm assuming because subdir=0 is evaluating to false somewhere. 0 as a directory name should be valid.

**Comment by bhsmither** [comment]
I have not yet tried it, but in `filemanager.class.php`, `public function findDirectories()`:
If `$search_dir` is to be a string, possibly "0" then :
```
public function findDirectories($search_dir = false, $i = 0)
to
public function findDirectories($search_dir = "", $i = 0)

$search_dir = (!$search_dir) ? $this->_manage_dir : $search_dir;
to
$search_dir = ($search_dir === "") ? $this->_manage_dir : (string)$search_dir;

if ($search_dir && file_exists($search_dir)) {
to
if (file_exists($search_dir)) {
```

**Comment by abrookbanks** [comment]
Thanks both!! :)
