### ISSUE TITLE
Check $regexp and $regexp_desc not empty prior to executing search

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2349]
```
File: [catalogue.class.php] Line: [1954] "SELECT I.* FROM CubeCart_inventory AS I LEFT JOIN (SELECT product_id, MAX(price) as price, MAX(sale_price) as sale_price FROM CubeCart_pricing_group WHERE group_id = 0 GROUP BY product_id) as G ON G.product_id = I.product_id WHERE I.product_id IN (SELECT product_id FROM `CubeCart_category_index` as CI INNER JOIN CubeCart_category as C where CI.cat_id = C.cat_id AND C.status = 1) AND I.status = 1 AND `live_from` < UNIX_TIMESTAMP() AND (I.name RLIKE '' OR I.description RLIKE '' OR I.product_code RLIKE '') " - Got error 'empty (sub)expression' from regexp
```

**Comment by bhsmither** [comment]
As of PHP 7.2, `count()` now returns `1` for arrays or objects that are not countable, and `0` for null.

See: https://forums.cubecart.com/topic/54973-what-does-this-php-warning-mean/

This also happens with no search terms found. See `catalogue.class.php` line 1922 when `$searchArray` did not get set.

No search terms can be true with (near) line 1823 (CC625) when searching for the keyword `0`:
```
if (empty($search_data['keywords']) && $order['field'] == 'Relevance') {
```
Also, line 1856 tests for `!empty($search_data['keywords'])` which could be a false negative.
