### ISSUE TITLE
HTML Coding Choice

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#235]
I am comparing the CC5 admin skin to the CC6 admin skin because, frankly, I like the CC5 admin skin better.

In customers.email.php, I find at line 69 a {foreach} loop that has a <tbody> tag inside. I think that is a mistake.

I am interested to know the rational for going with a table.

**Comment by abrookbanks** [comment]
Correct in a purest sense it doesn't need to be a table. The loop was in the incorrect boundary. This is fixed now. I don't see the harm leaving it as it is. 

What don't you like about it? Keen to take on feedback and make appropriate changes. The idea was to;

- make it look slightly different to distinguish major version tag.
- get it working with latest jQuery.
- improve some of the UX like that ghastly sidebar search. People either missed this or didn't know what it was.

*Closing for now but feel free to reply back if you have any handy feedback* :)

**Comment by havenswift-hosting** [comment]
I also dont like the feel of the V6 admin - colour scheme I think which is obviously subjective but isnt clean or modern looking

**Comment by abrookbanks** [comment]
Well thats the third person who has said that and no one has said they like it. 

Buggerations.

**Comment by havenswift-hosting** [comment]
I think for me it is mainly the black patterned background that doesnt look right - doesnt look good at all on login screen or when logged in

**Comment by abrookbanks** [comment]
OK well thats easy to change.

**Comment by abrookbanks** [comment]
WIP...

![screen shot 2015-02-19 at 10 44 53](https://cloud.githubusercontent.com/assets/4520803/6265294/674aafb8-b824-11e4-937c-0818698b949b.png)

**Comment by havenswift-hosting** [comment]
Looking much better !
