### ISSUE TITLE
Add Price Valid Until date to inventory

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2350]
It would be very useful to have a simple date field to store this information which can be used to indicate how long a sale price is valid until or even regular prices where these fluctuate

**Comment by abrookbanks** [comment]
This is a good one thanks.

**Comment by havenswift-hosting** [comment]
You added this to the 6.2.6 milestone - are you going to be able to add it before release ?

**Comment by abrookbanks** [comment]
Thanks for pointing out. I've removed it for now. Another silly mistake.

**Comment by havenswift-hosting** [comment]
lol - that isnt what I meant !  Should be easy to add one extra date field please and would prove really useful for quite a few people

**Comment by abrookbanks** [comment]
Haha. OK I'll see what I can do. Big push now especially as SCA has eased off. CC needs hit of energy.

**Comment by havenswift-hosting** [comment]
Thanks - would appreciate it

> especially as SCA has eased off

You have to be a bit careful with that - it is only at this stage the FCA that is doing this and even then, their statement says

"The FCA will not take enforcement action against firms if they do not meet the relevant requirements for SCA from 14 September 2019 in areas covered by the agreed plan, where there is evidence that they have taken the necessary steps to comply with the plan."

Also many payment companies will be mandating it anyway as they have changed their systems already, meaning the gateways will still need updating

**Comment by havenswift-hosting** [comment]
Any chance of getting this date field added for next release please ?

**Comment by abrookbanks** [comment]
Always up against it but I will try. The merchant could always sponsor it.
