### ISSUE TITLE
When manually creating an order, stock is not decreased for the selected items

### ISSUE THREAD

**Issue by bos4711** [cubecart/v6#2351]
Before creating an order I had 10 in stock for item #1 and 20 for item #2. After adding 2pcs #1 and 1pc #2 into the order, and set it to "Complete", I still have 10 in stock for #1 and 20 in stock for #2.

**Comment by abrookbanks** [comment]
I can't reproduce this see http://static.cubecart.com/issue-2351.mp4 

Maybe it needs to go to "Processing" first. Please try.

**Comment by bos4711** [comment]
Confirmed. If the order is left at "Pending" or "Processed", the stock is decreased. But if it's immediately set to "Complete" (which I did), stock is not decreased.

**Comment by abrookbanks** [comment]
Ok so we need to go to pending first then confirmed if its not been there before.

**Comment by abrookbanks** [comment]
Can you check your store settings?  In the features section under "Misc" check for:

`Allow order "Processing" status to be skipped?`

This should be unchecked and that it works correctly.

**Comment by bos4711** [comment]
That setting is, and has AFAIK always been, unchecked.

**Comment by abrookbanks** [comment]
I'm sorry but I just can't reproduce this. When you change from pending to complete please have a look at the History tab of the order. It should show a change to Processing before Complete.

Maybe I need to look at this on your store.
