### ISSUE TITLE
Email Log - script error 

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2353]
If an email contains single quotes, for example "it's" then the script to open the email in the mail log does not work and throws a script error.

The existing smarty code escape function doesn't work.

statistics.emaillog.php
FIND:
`<a href="#" onclick="{literal}$.colorbox({title:'{/literal}{$log.subject|escape:'javascript'} ({$LANG.common.html}){literal}',width:'90%', height:'90%', html:'<iframe width=\'100%\' height=\'95%\' frameBorder=\'0\' src=\'?_g=xml&amp;function=viewEmail&amp;id={/literal}{$log.id}{literal}&amp;mode=content_html\'></iframe>'}){/literal}">{$LANG.common.html}</a>`

REPLACE WITH:
`<a href="#" onclick="{literal}$.colorbox({title:'{/literal}{htmlentities($log.subject)} ({$LANG.common.html}){literal}',width:'90%', height:'90%', html:'<iframe width=\'100%\' height=\'95%\' frameBorder=\'0\' src=\'?_g=xml&amp;function=viewEmail&amp;id={/literal}{$log.id}{literal}&amp;mode=content_html\'></iframe>'}){/literal}">{$LANG.common.html}</a>`

FIND:
`<a href="#" onclick="{literal}$.colorbox({title:'{/literal}{$log.subject|escape:'javascript'} ({$LANG.common.plain_text}){literal}',width:'90%', height:'90%', html:'<iframe width=\'100%\' height=\'95%\' frameBorder=\'0\' src=\'?_g=xml&amp;function=viewEmail&amp;id={/literal}{$log.id}{literal}&amp;mode=content_text\'></iframe>'}){/literal}">{$LANG.common.plain_text}</a>`

REPLACE WITH:
`<a href="#" onclick="{literal}$.colorbox({title:'{/literal}{htmlentities($log.subject)} ({$LANG.common.plain_text}){literal}',width:'90%', height:'90%', html:'<iframe width=\'100%\' height=\'95%\' frameBorder=\'0\' src=\'?_g=xml&amp;function=viewEmail&amp;id={/literal}{$log.id}{literal}&amp;mode=content_text\'></iframe>'}){/literal}">{$LANG.common.plain_text}</a>`

**Comment by abrookbanks** [comment]
Thank you.
