### ISSUE TITLE
ID conflicts in admin area

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2355]
within the order Inventory tab, if a product has options the HTML input is assigned an ID for each option.

the naming of this is "option_X" with X being the option ID.

However, in the case of multiple products with the same option, the ID is duplicated, meaning any JS which may want to target based on ID could run into issues. ID's should be unique.

this needs to be revised:
`id="option_{$option.option_id}"`

**Comment by abrookbanks** [comment]
Thanks Alec.
