### ISSUE TITLE
Estimate Shipping dropdown bug?

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#2357]

**Comment by Dirty-Butter** [comment]
I use Enabled (State Disabled) for all countries that do not require State/Province. My dropdown when using the Estimate link still shows the standard boxes - Country, State, Zip.

If Countries/Zones is set to State Disabled, the drop down should abide by that setting just like the Checkout address blanks do.

Also, I've noticed in testing that I get a proper choice of International shipping and a proper s/h amount even if I only choose the country from the dropdown - no zip. Curious as to how zip could be required (isn't it?) and still give an estimate without it. Are there countries that do not use zip codes?

**Comment by abrookbanks** [comment]
Brilliant find Rosemary.

**Comment by Dirty-Butter** [comment]
Even a broken clock is right twice a day. Glad it was an easy fix. While I have you, take a look at my refinement of the Estimate link. Most countries are left to right, so moving the Estimate box to the left and changing the Estimate link wording is better IMHO.

![Screenshot_2019-08-12 https dirtybutter com](https://user-images.githubusercontent.com/6146505/62877889-9c79a680-bced-11e9-9d8d-4454a37be39e.png)

**Comment by abrookbanks** [comment]
Ha. I like that saying. :)

Your changes look good. Maybe we can roll out something similar.  Thanks again.
