### ISSUE TITLE
County List script error

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2359]
`Uncaught SyntaxError: Unexpected token ;`

This can be thrown if you have a single country and that country is configured as "County Disabled". The JS side of things is not checking if this is a valid object or not and is assuming it will always exist and be populated, this is not the case.

resolved with:
```
<script type="text/javascript">
   var county_list = {if !empty($STATE_JSON)}{$STATE_JSON}{else}false{/if};
</script>
```

I've not done a lot of validation with the above, it needs more validation and there are other places that need changes as well.

**Comment by abrookbanks** [comment]
I'm leaving it as it is for fear of making bugs and upsetting external plugins but the naming convention is horrendous. What were we thinking!??

```var county_list = {$STATE_JSON};```

This should be;
```var state_list = {$STATE_JSON};```

**Comment by abrookbanks** [comment]
Thanks so much Alec.
