### ISSUE TITLE
Add more units of measurement

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2360]
It's great that we now have UOM at the product level, however it's only as CM or INCH at the moment.

I'm seeing use cases for other UOM, such as millimetres, and meters to accommodate very small, and very large tangible goods. 

The current values are hard coded into the admin theme, it would be useful to port this to a DB table where UOM can be configured, one record for each UOM and then populate the list of measurements from that table, thus allowing anybody to easily setup a new UOM as required, ideally via a configuration screen however just the ability to modify directly via the DB will be fine for now since it probably will not get changed frequently

**Comment by abrookbanks** [comment]
Took me forever to work out what UOM was. :laughing: 

Good shout BTW.
