### ISSUE TITLE
Catalogue Search Returns Incorrect Results ..

### ISSUE THREAD

**Issue by ChrisNColeman** [cubecart/v6#2364]
On line 1840 of catalogue.class -

`// Only look for items that are in stock
if (isset($search_data['inStock'])) {
$where[] = $this->outOfStockWhere();
}`
Creates an sql $whereString on line 1845 -> AND `live_from` < UNIX_TIMESTAMP()  AND `live_from` < UNIX_TIMESTAMP(), which probably works but is incorrect because it returns out of stock products even when you don't want them (ie. selected _in stock_ as part of the search).

Changing the code as follows works (as does foundation skin) - 
// Only look for items that are in stock, except if admin. -
if (!(!(isset($search_data['inStock']) || $GLOBALS['config']->get('config', 'hide_out_of_stock')) || Admin::getInstance()->is())) {
    $where[] = ' AND `STOCK_LEVEL` > 0';
}
$whereString =  AND `STOCK_LEVEL` > 0 AND `live_from` < UNIX_TIMESTAMP() - ?

**Comment by ChrisNColeman** [comment]
Actually better like this-

`// Only look for items that are in stock, except if admin. -
 if (!(Admin::getInstance()->is() || !(isset($search_data['inStock']) || $GLOBALS['config']->get('config', 'hide_out_of_stock')) )) {
                $where[] = ' AND `STOCK_LEVEL` > 0';
            }`

**Comment by ChrisNColeman** [comment]
Sorry the above is fundamentally incorrect - Please ignore for now !

**Comment by abrookbanks** [comment]
Please see: https://github.com/cubecart/v6/issues/2320

This issue should be resolved at latest build.
