### ISSUE TITLE
CKEditor to Use Placeholder Plugin

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2365]
Re: #2289 and #2285

Suggest dropping ProtectedSource and ShowProtected, and using Placeholder.

https://ckeditor.com/cke4/addon/placeholder

Initial tests with CKEditor 4.12.1 show promise.

It is necessary to make a few edits in the Placeholder plugin.js file to replace instances of `[[x]]` to `{x}` - 5 lines.

**Comment by abrookbanks** [comment]
I too and getting positive results. Other sections to convert before this ticket is closed.

**Comment by abrookbanks** [comment]
Closed by accident.

**Comment by abrookbanks** [comment]
Reverted to attempt to change format. 

I'm struggling to reformat `validNameRegex = /^[^\[\]<>]+$/;` in the placeholder.js file.

**Comment by bhsmither** [comment]
Line 39:
```
From:
template: '<span class="cke_placeholder">[[]]</span>',
To:
template: '<span class="cke_placeholder">{}</span>',
```
Line 42:
```
From:
return new CKEDITOR.htmlParser.text( '[[' + this.data.name + ']]' );
To:
return new CKEDITOR.htmlParser.text( '{' + this.data.name + '}' );
```
Line 47:
```
From:
this.setData( 'name', this.element.getText().slice( 2, -2 ) );
To:
this.setData( 'name', this.element.getText().slice( 1, -1 ) );
```
Line 51:
```
From:
this.element.setText( '[[' + this.data.name + ']]' );
To:
this.element.setText( '{' + this.data.name + '}' );
```
Line 68:
```
From:
var placeholderReplaceRegex = /\{([^\{\}])+\}/g;
To:
var placeholderReplaceRegex = /{\S*?.*?\S}/g;
```

**Comment by abrookbanks** [comment]
Thanks for this. 
```
validNameRegex = /^[^\{\}<>]+$/;
```

I think it works now. Let's replace the yellow hi-light however.

**Comment by abrookbanks** [comment]
![Screenshot 2019-08-16 at 15 56 58](https://user-images.githubusercontent.com/4520803/63176795-83029280-c03e-11e9-8838-d9a49ef49f6c.png)

**Comment by abrookbanks** [comment]
It's working well. Thanks for sharing this Brian. It's much better too.

**Comment by bhsmither** [comment]
Placeholder download panel says Line Utilities is a dependency. I installed it, but do not know if it is actually needed.
https://ckeditor.com/cke4/addon/lineutils

CKEditor's config.js:
```
	/* config.protectedSource.push(/{\S*?.*?\S}/g); */ /* Issue #2316 */
	config.extraPlugins = 'lineutils,placeholder';/* 'showprotected'; */
```
Unfortunately, still require `{foreach}` etc in HTML coments. Otherwise, CKEditor will still insist on correcting their placement in between `<ul>` and `<li>` tags.

**Comment by bhsmither** [comment]
Might need to edit the dialog code to add:
```
Do not include the surrounding braces in the placeholder name.
```

**Comment by abrookbanks** [comment]
Yes it seems to work without the dependancy.

**Comment by bhsmither** [comment]
Personally, I would not comment out the entire `onLoad()` function. I do nor know how javascript would handle a missing method.

Maybe style it differently? A rounded ridge border with a light-grey background, perhaps?

**Comment by abrookbanks** [comment]
Really pleased with this. Thanks again Brian. 

We should be due 6.2.6 early next week.

**Comment by bhsmither** [comment]
I just saw in the language file:
```
invalidName: 'The placeholder can not be empty and can not contain any of following characters: [, ], <, >',
```
I can understand the illegal use of brackets - which should no longer be necessary - but angles?

I think the reason for illegal angles need to be discovered and dealt with. Angle characters will be necessary for Smarty code - as well as brackets - and this phrase should now mention braces as being illegal.
