### ISSUE TITLE
CKEditor Placeholders are not Protected or Ignored

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2367]
Regarding #2365

Really... what did this actually attempt to solve? Placeholders for what? A placeholder is a 'widget', but offers no direct benefit to us because each 'widget' would be a single Smarty phrase. Thus, CKEditor is free to muck about with it in relation to it's placement in HTML code and the enforcement of code completeness and DOM structure.

Did we not just find ourselves back at square 1? Or did we actually never get off of square 1?

Re: #523, #723, and maybe others.

At least Placeholders do not cause the problems #2289 and #2285.

**Comment by bhsmither** [comment]
It has been said by one of the CKEditor programmers:
"But that means that you are overusing CKEditor. It's a text editor, not a code editor. I understand that it's easy to put some non-HTML markup into the editor, but that does not mean it's the right way of doing things."

So, maybe another editor?

Or lower our expectations?

**Comment by abrookbanks** [comment]
Replace with ACE Editor probably the best solution.

**Comment by bhsmither** [comment]
Is that the PHP Code Snippet editor? If so, I have issues with it regarding where the text insertion cursor appears to be blinking and between what characters the cursor is actually at. (Might be something I did.)

**Comment by abrookbanks** [comment]
> Is that the PHP Code Snippet editor? If so, I have issues with it regarding where the text insertion cursor appears to be blinking and between what characters the cursor is actually at. (Might be something I did.)

Yes. And I also have that issue. It's actually a common issue but no fixes I have tried have worked.

**Comment by abrookbanks** [comment]
.. the suggestions seems to be to change the font but I haven't seen a difference.

**Comment by bhsmither** [comment]
Were you suggesting replacing a WYSIWYG editor with a code editor?

**Comment by abrookbanks** [comment]
> Were you suggesting replacing a WYSIWYG editor with a code editor?

If its the only solid solution but merchants will hate it. The new Placeholder seems to work ok for me. Have you reproduced a bug with it?

**Comment by bhsmither** [comment]
My experiments with
```
{if $i < 5.5}
Less
{else}
More
{/if}
 than 6.
```
did not give acceptable results. CKEditor wants to make paragraphs of each line.

**Comment by bhsmither** [comment]
https://github.com/JefMari/awesome-wysiwyg

**Comment by abrookbanks** [comment]
I wonder if changing:
https://github.com/cubecart/v6/blob/6.2.0-branch/includes/ckeditor/plugins/placeholder/dialogs/placeholder.js#L17

To `validNameRegex = /^[^\{\}]+$/;` would help.

**Comment by abrookbanks** [comment]
> My experiments with
> 
> ```
> {if $i < 5.5}
> Less
> {else}
> More
> {/if}
>  than 6.
> ```
> 
> did not give acceptable results. CKEditor wants to make paragraphs of each line.

It fails with:

<p>{if $i < 5.5}</p>

<p>less than 5.5</p>

<p>{else}</p>

<p>More than 5.5</p>

<p>{/if}</p>


:(
