### ISSUE TITLE
saveAddress Hash check not limited to current customer

### ISSUE THREAD

**Issue by JonathanFullCircles** [cubecart/v6#2368]
In the user class, the saveAddress function runs a hash comparison to see if the address already exists. This isn't customer id limited however, so can lead to it altering the address in another customers login, which could be an issue if multiple company employees deliver to the same address, as it just won't add the address to the new login

Recommended change Line 938:

`if ($result = $GLOBALS['db']->select('CubeCart_addressbook', array('address_id'), array('hash' => $array['hash']), false, 1, false, false)) {`

To:

`if ($result = $GLOBALS['db']->select('CubeCart_addressbook', array('address_id'), array('hash' => $array['hash'], 'customer_id' => $user_id), false, 1, false, false)) {`

**Comment by abrookbanks** [comment]
Great find thank you.
