### ISSUE TITLE
Exit Modal for Newsletter Signup

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2369]
![Screenshot 2019-08-21 at 09 23 50](https://user-images.githubusercontent.com/4520803/63415283-688d3800-c3f5-11e9-8b86-38c1d4c5e4c9.png)

**Comment by havenswift-hosting** [comment]
Nice addition

**Comment by Dirty-Butter** [comment]
What triggers this? I have popups allowed on dirtybutterestates.com on the current commit. I have not seen this. I am NOT logged in to admi.

OK, I found it. When I moved the curser up to the browser near my bookmarks it popped up. But it only does it once.
