### ISSUE TITLE
Drop meta keyword support

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2370]
This is widely recognised as being irrelevant in 2019.

**Comment by abrookbanks** [comment]
Honestly I feel like I have just emptied the loft or something. LOL

Great feeling. Haha.

**Comment by bhsmither** [comment]
Downvote.

I would have removed (comment out) the Smarty variable from the skin. Add `(Deprecated)` to the field labels. Update the help pages.

Even if having removed the Smarty variable from the packaged skin - meaning others who really, really want to have it on their site are able to simply add the HTML code - I would re-purpose the data item by adding it to the fulltext index.

**Comment by abrookbanks** [comment]
Are you using it for something bespoke?

**Comment by abrookbanks** [comment]
It's more than depreciated. It's defunct right?

**Comment by havenswift-hosting** [comment]
Yes, none of the big search engines use them at all for any reason and havent done in 6 to 8 years - they were too easy to key stuff

**Comment by havenswift-hosting** [comment]
> I would re-purpose the data item by adding it to the fulltext index.

This is what DB has in her store to add keyword variations to the search.  As per my forum reply, a good addition to search but shouldnt have been using the meta keywords.  Done properly, it would be very useful to add this information "Search Keywords" to each product and as you said, add it to the fulltext index

**Comment by bhsmither** [comment]
The `<meta name="keywords">` tag is not illegal. I have not come across any mention of an RFC that repeals its legitimacy - and thus would then crash web browsers trying to parse it (that will never happen). There is a strategy for not having it in a competitive SER fight.

So, I suppose a better word is "ignored" by the few most used search engines (as opposed to deprecated), but could be useful and used by atypical users of CubeCart (or any website).

**Comment by havenswift-hosting** [comment]
It was announced by Matt Cutts at Google more than ten years ago that Google no longer used meta keywords and while they dont view the use of these as a spam signal (ie penalize pages that use them) there are strong signals that Bing do and rank site pages lower if they are used.  Even if Google don’t penalize their use, including them in CubeCart gives the impression they are important which is a huge waste of time for store owners

**Comment by abrookbanks** [comment]
I still can't see any reason to keep it.

**Comment by abrookbanks** [comment]
Why repurpose to full index? I'm lost there.

**Comment by abrookbanks** [comment]
> Even if Google don’t penalize their use, including them in CubeCart gives the impression they are important which is a huge waste of time for store owners

Totally agree. It's complex enough as it is.

**Comment by havenswift-hosting** [comment]
>>Why repurpose to full index? I'm lost there.

Rosemary mentioned her use of this field but in a forum thread.  She enters different spelling variations for product specific keywords (not something you would want to do within the description which is visible on the site) so for example Carter, Carters, Carter's - this greatly helps customers when searching for a product when they wont necessarily enter exactly as the store owner does

**Comment by abrookbanks** [comment]
Can't they do in the description as a comment?

`<!-- Carter, Carters, Carter's -->`

**Comment by abrookbanks** [comment]
.. not as good as a specific column I'm sure.

**Comment by Dirty-Butter** [comment]
I worked it out. Renamed meta_keywords to search_keywords and re-worked places in code to reference it. All references to meta_keywords are gone, per new commits, and search is working properly. I have some keyword inconsistency, but that's my fault - not the code.

I tried it as a separate tab on the Products, but changed my mind and put the search_keywords box back where it had been in the Search Engine tab. That's because in my work flow, I write the description in the Search tab and then create the search keywords based on that description. THEN I copy the description to the Description tab.

**Comment by havenswift-hosting** [comment]
DB - might be worthwhile documenting the changes to core to add this as a feature and ask for it to be added as a new feature - I think it is worthy of being added

**Comment by Dirty-Butter** [comment]
OK - will get a list made.

**Comment by Dirty-Butter** [comment]
Easier said than done. I know what I did, but I'm not sure I know how to write it down for other people to use. sorry

**Comment by Dirty-Butter** [comment]
Well, I tried. I've added the Feature Request.
