### ISSUE TITLE
Store Settings - disable mobile skin

### ISSUE THREAD

**Issue by Malvarlin** [cubecart/v6#2374]
Whenever I try to deselect 'disable mobile skin' in store settings, it turns back on after clicking save?

**Comment by Dirty-Butter** [comment]
What skin are you using?

**Comment by Malvarlin** [comment]
Custom foundation 5 skin, that said, the test store I also have no longer has this option at all, possibly its a glitch between versions?  Especially as I now have the mobile version of foundation 5 working as well, without unchecking the box

**Comment by Dirty-Butter** [comment]
That's a SemperFi skin isn't it? I think you need to ask on the forum instead of here.
