### ISSUE TITLE
Sale Items Indication is False Negative

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2376]
See: https://forums.cubecart.com/topic/55227-sale-setting-issues/

In the template box.sale_items.php, the test
```{if empty($product.sale_price)}```
will always be false because `sale_price` arrives with a currency symbol.

**Comment by abrookbanks** [comment]
I can't reproduce this but the issue is familiar. I wonder if it is fixed already.

**Comment by abrookbanks** [comment]
Excuse the stupid product names. We have one sale item and one non sale item. 
![Screenshot 2019-10-28 at 17 12 27](https://user-images.githubusercontent.com/4520803/67700655-43451900-f9a6-11e9-8af1-c1b6c9e098ff.png)

**Comment by bhsmither** [comment]
Please change the name of one of the items.

**Comment by bhsmither** [comment]
And set the non-sale item to have a sale price of zero.

**Comment by abrookbanks** [comment]
Thanks. I'll try this.

**Comment by abrookbanks** [comment]
I just can't reproduce it. This issue is familiar and I'm pretty sure it was fixed already.

**Comment by abrookbanks** [comment]
Reproduced. The sales box is taking the value of `$GLOBALS['smarty']->assign('PRODUCTS', $xxx);` from a different area. If you change category the sale items listed reflect the products in that category.
