### ISSUE TITLE
Memcached - Error when enabled?

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2380]
Maybe I am missing something config wise here, but following the support article, enabling memcached CubeCart throws a class not found error.

CubeCart 6.2.5

Article:
https://support.cubecart.com/Knowledgebase/Article/View/235/41/how-do-i-enable-apc-memcached-redis-or-xcache

Fatal error: Uncaught Error: Class 'memcached' not found in /var/www/vhosts/####/httpdocs/classes/cache/memcached.class.php:36 
Stack trace: 
#0 /var/www/vhosts/####/httpdocs/classes/cache/memcached.class.php(64): Cache->__construct() 
#1 /var/www/vhosts/####/httpdocs/controllers/controller.admin.pre_session.inc.php(19): Cache::getInstance() 
#2 /var/www/vhosts/####/httpdocs/admin_UunmHy.php(34): include('/var/www/vhosts...') 
#3 {main} thrown in /var/www/vhosts/####/httpdocs/classes/cache/memcached.class.php on line 36

added
$glob['cache'] = 'memcached';
$glob['memcached_servers'] = array();

is memcached broken in CubeCart?

**Comment by havenswift-hosting** [comment]
Memcached works perfectly and use it on most of our client sites - you dont need the memcached_servers entry in the global file unless you are using an external memcached server

Are you sure that you have memcached PHP library installed and not just the memcache one ?

**Comment by Noodleyman** [comment]
hmm, that might be the issue. will check into it. not set this one up before so on a learning curve :)

**Comment by havenswift-hosting** [comment]
If you have shell access then try

php -m | grep memcache

**Comment by abrookbanks** [comment]
Yeah its working perfectly on CubeCart Hosted too. Sounds like a local issue. Hope you get it fixed.
