### ISSUE TITLE
Upgrader issue with memory caching..

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2382]
Unrelated to my other memory cache ticket this week. Had this come to me as an issue from a customer. 

Their store uses FILE cache, and FILE cache is defined in the global.inc.php file. trying to upgrade the store to the latest release, but the SETUP process fails to load with error:

Fatal error: session_start(): Failed to initialize storage module: memcache (path: /var/sites/w/####/public_html/___sessions_0893d27h49) in /var/sites/a/####/public_html/setup/index.php on line 39

MEMCACHE modules are installed in PHP, but not used by this site, thus the setup process shouldn't make use of it and thus fail.

I'm looking into it, but suspect a defect around this, thus opening a ticket.

**Comment by Noodleyman** [comment]
root cause is ini-custom.inc.php where session_save_path is defined to a directory (since CubeCart uses file cache)

However, the setup process is making use of the default session handling on the server which is configured to use memcache. 

memcache with a file path is invalid. I think there needs to be an improvement in the installer to catch this condition and handle accordingly.

**Comment by abrookbanks** [comment]
CubeCart doesn't use memcache for session storage AFAIK.

**Comment by Noodleyman** [comment]
exactly, which caused a conflict with configuration and made the installer non functional

**Comment by abrookbanks** [comment]
I don't know what to suggest here. I have 101 customer stores using memcached and never seen this issue on upgrade.

**Comment by Noodleyman** [comment]
it is an edge case :)

If the web server itself handles sessions in memory, but the store is using file cache you get this issue.

**Comment by abrookbanks** [comment]
You are probably in a better situation to find a solution than me.

**Comment by Noodleyman** [comment]
checking some PHP config as part of setup should be enough. 

if session.save_handler != files, and session.save_path has a valid file system  path (which came from the ini file) it will break. simply removing the file path should be enough via ini_set

**Comment by abrookbanks** [comment]
Makes sense. Did it work and if so can you share your code changes?

**Comment by Noodleyman** [comment]
I didn't have time to write a patch so as a work around I removed the session directory path from the ini file so I could run the upgrade, then put it back once done.

**Comment by abrookbanks** [comment]
Ok got it. This is very much an edge case as you suggested so I think we can keep this as a thing to watch out for.

**Comment by havenswift-hosting** [comment]
Using memcache for session handling is becoming far more common because it is just so much better than file handling so not sure how much of an edge case it will be.  Also a better solution would be to add memcache session handling to CubeCart - should be relatively simple ?

**Comment by abrookbanks** [comment]
Yeh it would be better. Maybe we can reference this in the feature request about that. CubeCart hosted uses Memcached so I'm keen.

**Comment by abrookbanks** [comment]
> I didn't have time to write a patch so as a work around I removed the session directory path from the ini file so I could run the upgrade, then put it back once done.

There is no session directory path in the ini file. Did you mean global.inc.php file?

**Comment by Noodleyman** [comment]
it's an option you can add (and CubeCart recommends it) in some cases when there are session path issues on the server.

session.class.php, 
```

if(is_writeable(CC_INCLUDES_DIR.'extra')) {
	$this->_manage_session_files = true;
	session_save_path(CC_INCLUDES_DIR.'extra');
} else {
	die("Error: Failed to create PHP session. It may be possible to fix this by following these steps:
<ol>
	<li>Create a folder in the root directory of your store called &quot;sessions&quot;</li>
	<li>Create a file in the root folder of your store called &quot;ini-custom.inc.php&quot;</li>
	<li>Add the following code to this file and save the changes.
	<pre>".htmlspecialchars("<?php
session_save_path(CC_ROOT_DIR.'/sessions');")."</pre>
	</li>
</ol>Once that has been done refresh this page.");
}
	
```

**Comment by abrookbanks** [comment]
This isn't in any recent version is it??

> session.class.php,
> 
> ```
> 
> if(is_writeable(CC_INCLUDES_DIR.'extra')) {
> 	$this->_manage_session_files = true;
> 	session_save_path(CC_INCLUDES_DIR.'extra');
> } else {
> 	die("Error: Failed to create PHP session. It may be possible to fix this by following these steps:
> <ol>
> 	<li>Create a folder in the root directory of your store called &quot;sessions&quot;</li>
> 	<li>Create a file in the root folder of your store called &quot;ini-custom.inc.php&quot;</li>
> 	<li>Add the following code to this file and save the changes.
> 	<pre>".htmlspecialchars("<?php
> session_save_path(CC_ROOT_DIR.'/sessions');")."</pre>
> 	</li>
> </ol>Once that has been done refresh this page.");
> }
> 	
> ```

**Comment by Noodleyman** [comment]
Code copy/paste from 6.2.2, so not too old. However, there are stores out there which followed the advice from earlier versions if seeing a session path issue and will have it configured.

**Comment by abrookbanks** [comment]
It's gone since then so especially as this is such an edge case it's unlikely to raise affect a significant amount of merchants (if any).
