### ISSUE TITLE
HTML Commented Smarty Tags

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2383]
There is code to add HTML comments around certain Smarty tags (documents.email.inc.php line 505) so that CKEditor will leave them alone.
```
'#{(/?)(section|foreach|foreachelse|for)(.*?)}#'
```
However, on POSTing back, HTML comment markers are indiscriminately removed (line 363).

There may be the case the admin actually wants to have HTML comments in the email content.

**Comment by abrookbanks** [comment]
Agreed but it's unlikely. Leaving as it for now.. we can cross this bridge if/when we get to it.
