### ISSUE TITLE
Gigantic cookie_consent table

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#2384]
With a lot of help from Ian I moved our store from dirtybutter to plushmemories. I was surprised to see how much larger the old database was than the new one. It's the cookie_consent table that is gigantic (well over a million entries) in the old store. Several other log tables are also much larger on the original database. Even though all the necessary data appears to have copied correctly, the old db was 660 MB and the new is about 90 MB.

Shouldn't there be a way to flush entries in some of these logs after some period of time?

**Comment by havenswift-hosting** [comment]
Thanks Al !
