### ISSUE TITLE
request - cart update as a seperate submit

### ISSUE THREAD

**Issue by unviva** [cubecart/v6#2385]
![update-cart-required](https://user-images.githubusercontent.com/27769339/65219992-769caa00-dac2-11e9-9507-f40611e1a1ce.png)

For visitors not logged in, update basket button doesn't work as expected due to required fields. I believe they should be able to update cart even they are not registered/logged in yet.

**Comment by abrookbanks** [comment]
Thanks for this. Right now that are attached to the same form. Your screenshot looks corrupt. There should be JavaScript validation not just browser validation. 

I think this issue actually relates to a broader feature request for more granular data change for a more app based checkout.
