### ISSUE TITLE
Items removed from basket when use_stock_level = 0

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2387]
https://github.com/cubecart/v6/blob/6.2.0-branch/classes/cart.class.php#L1154 

Replace with:
```
if ($product['use_stock_level'] && isset($max_stock)) {
```

Testing required.

**Comment by Dirty-Butter** [comment]
Are you satisfied with this one or still testing?

**Comment by abrookbanks** [comment]
happy :)

**Comment by Dirty-Butter** [comment]
thanks
