### ISSUE TITLE
Disabled Customer was Able to Order - bug?

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#2388]
See https://forums.cubecart.com/topic/55293-disabled-customer-still-ordered/

**Comment by Dirty-Butter** [comment]
It would be helpful if the admin had an easy option or automatic process to unsubscribe a disabled customer from the newsletter subscriptions.

**Comment by abrookbanks** [comment]
The above fix combined with 1.2.6 release of PayPal Checkout will resolve this.

**Comment by Dirty-Butter** [comment]
I use Standard PayPal plugin. Can whatever fixed the Express be applied to Standard as well?

**Comment by abrookbanks** [comment]
No because PayPal standard doesn't authenticate a customer and return their email to check if its disabled like Express does.
