### ISSUE TITLE
Unset Variable in foreach()

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2389]
In ajax.class.php, line 169, the return could set `$dir` to *null*. Then, `$dir` as the key to the array `$dirs` will be cast to a -zls-.

Anyway, if the top folder has no sub-folders, `$dirs[-zls-]` should be *false*.

PHP will complain about the following `foreach()`.

**Comment by abrookbanks** [comment]
Thanks Brian.

**Comment by bhsmither** [comment]
I disagree with this solution. `$dir` is the index into an array, thus it will never be an array itself.

Perhaps just check if it is true-like. Try:
```
if($dir) {
```
(I haven't tried this.)

**Comment by abrookbanks** [comment]
> I disagree with this solution. `$dir` is the index into an array, thus it will never be an array itself.
> 
> Perhaps just check if it is true-like. Try:
> 
> ```
> if($dir) {
> ```
> 
> (I haven't tried this.)

No that doesn't work either. Lets just leave it as it was before. There was no bug in the first place. Commit reverted.
