### ISSUE TITLE
AIOS Edit delets Shipping Rates

### ISSUE THREAD

**Issue by Crysties** [cubecart/v6#2391]
Supposedly Edit issue was fixed in AIOS GH issue #365 but I dowloaded 1.0.15 (20190930) and when I Edit Shipping Rates it deletes previous rate setup and I have to re-enter the whole setup again.  Using CC 6.2.6

**Comment by abrookbanks** [comment]
I think this is an issue with the server config value for "max_input_vars".

**Comment by Crysties** [comment]
So what does this mean for me.  Let's get my website moved to CC.  Hopefully all will clear up.  Rosalyn Rich
Crysties Gifts - Cowboy,  American and Fine Art
http://crystiesgifts.com
530-214-8447

---------- Original Message ----------

**Comment by Crysties** [comment]
I am still having problems with the shipping rates staying.  I save them but then they don't save.  If I look in the click on the tabs only about 5 or 6 actually have shipping rates even though I have keyed in a lot more sets of rates than that. See your comment below.  Rosalyn Rich
Crysties Gifts - Cowboy,  American and Fine Art
http://crystiesgifts.com
530-214-8447

---------- Original Message ----------

**Comment by abrookbanks** [comment]
Caused by input vars exceeding 1000.
