### ISSUE TITLE
Bulk Import Tool Tax Class to be Named

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2392]
In reviewing this KB article (https://support.cubecart.com/Knowledgebase/Article/View/32/41/how-do-i-use-the-bulk-product-import-tool), I see that the Master Category ID column can contain text and the named category will be created if not found.

Suggest that Tax Class ID follow this capability.

**Comment by abrookbanks** [comment]
Ignore the above commit. Typo on issue id.
