### ISSUE TITLE
Bulk Import Tool KB to be Clarified

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2396]
In https://support.cubecart.com/Knowledgebase/Article/View/32/41/how-do-i-use-the-bulk-product-import-tool, the example for Condition is shown as "New".

Relative to the code that prepends `condition_` to the database value, to have the appropriate key word into the language pack, suggest the example be these specific keys: `new`, `used`, `refurbished`, with a note that they must be lowercase (or fix that when inserting into the database), and that any other key words must be processed via plugin or code snippet to create the language phrase.

**Comment by abrookbanks** [comment]
Done thanks.
