### ISSUE TITLE
Nochex plugin issue

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2404]
Just upgraded a client to the latest version of the Nochex payment plugin and they have noticed that the Transaction Description passed through to Nochex and relayed back to them in the Payment Confirmation email from Nochex has changed

It used to simply say Payment for order XXXXXX-XXXXXX-XXXX

Now it contains the Product name, product description, product price, quantity - for every single item that was paid for. This is badly formatted and gets extremely long on big orders and is pointless in a payment notification.  Can it be reverted to what it was before

**Comment by abrookbanks** [comment]
Experiment with "Detailed Product Information" mode.

**Comment by FABPress** [comment]
I am having this problem. Latest Nochex confirmation e-mail, the Transaction Description field contained more than 1,000 characters! Very unnecessary and would appreciate a fix please.

**Comment by abrookbanks** [comment]
See above. Please turn XML mode on.

**Comment by havenswift-hosting** [comment]
There is no "XML Mode" and it makes no difference whether "Detailed Product Information" is ticked or unticked

**Comment by abrookbanks** [comment]
Ok the code suggests otherwise. I'll take a look.

**Comment by abrookbanks** [comment]
Forced to `Order created for: xxxx-xxxx-xxxx-xxxx` in 2.2.
