### ISSUE TITLE
[Security issue] SMTP password is exposed during testing

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2407]
When using the TEST utility, a HTTP GET request is made which passes the parameters via URL, including the password in plain text. this will be written to web server logs and stored, as well as sites which may not use https (I hope nobody does), the traffic can be sniffed and password exposed.

This should be replaced with a HTTP POST method

**Comment by abrookbanks** [comment]
Relates to #2089

**Comment by Dirty-Butter** [comment]
`                return "<div class=\"mail_modal\"><h3>Testing ".$method_name."</h3><p>It isn't possible  to get a definitive test result for the &quot;PHP mail() Function&quot; method.</p><p>We have attempted to send a test email to &quot;".$GLOBALS['RAW']['POST']['email_address']."&quot; with the subject of &quot;".$subject."&quot; Please note that it can take ten minutes or even longer for a busy mail server to deliver email. Don't forget to check your spam folder!</p><p>This method can fail if the server hasn't been configured properly and may refuse to send mail from &quot;untrusted&quot; sources such as Hotmail, Yahoo, AOL etc&hellip;. We recommend using an email address from a domain hosted on this server such as sales@".parse_url(CC_STORE_URL, PHP_URL_HOST)." for example and this may need to be setup form within your web hosting account.</p></div>";
`
Shouldn't this long set of directions in ajax.class.php be instead coded in the definitions.xml file, so it can be in other languages besides English?
