### ISSUE TITLE
All in One Shipping Tweak

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2414]
Request in the file /admin/index.inc.php (and all other files in the module), to replace any sensible occurrence of `All_In_One_Shipping` to `$_GET['module']`.

This solves the edge case where the module has been renamed (for example, to `AIOS_1015`).

(I have made this replacement to many other modules.)

**Comment by abrookbanks** [comment]
There seems to be only one occurance. 

`$GLOBALS['smarty']->append('EXTRA_JS', 'modules/shipping/All_In_One_Shipping/js/all_in_one_shipping.min.js');`

**Comment by bhsmither** [comment]
In shipping_rates.tpl, lines 59 and 65, replace with `{$MODULE.folder}`.

In index.tpl, line 8 and 155, replace `id="All_In_One_Shipping"` with `id="{$GENERAL_TAB_ID}"`.

Same file, line 156, replace with `{$MODULE.folder}`.

In all_in_one_shipping.min.js, line 70, replace with something like:
```
$("div#page_content form div:first-child").attr("id")
```

**Comment by abrookbanks** [comment]
Thanks. I'll get this done before release next week...

**Comment by abrookbanks** [comment]
Implemented in AllInOneShipping-1.0.16.zip. All seems to be working well. Thank you.
