### ISSUE TITLE
Feature request : easier movement of images

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2416]
There are a great many stores which store all of their images in the /source directory often having many thousands or tens of thousands of images, which isnt very practical and can cause speed or timeout issues in some circumstances

Re-arranging images into sub-directories is tedious but could easily be improved either by allowing drag and drop and / or having a tick box where tens or hundreds of images could be ticked and then a directory selected to move them into.  A simple change that would help many larger and older sites

**Comment by abrookbanks** [comment]
Some sample code that was never added to the package was removed just the other day:
https://github.com/cubecart/v6/commit/169d0d7b3db71c337c51c1a8c89e6576106138a3#diff-f63081b2a3d13b40568f191ddd95419a

It works by putting images into alphabetical folders. 

e.g.
image1.jpg -> i/image1.jpg
picture.png -> p/picture.png
Banana.gif -> b/banana.gif
etc..

**Comment by havenswift-hosting** [comment]
That might be useful maybe as a default option for new stores so at least they dont all go into the one directory.

However, it would have to be one of a number of selectable options as many store owners like to sub-divide by category, manufacturer  or even by product if they use a lot of images on each product or some combination of these.

I was requesting a simple method for manually sub-dividing them but if it was possible to select an option from a list of say 1) First character of image name 2) By category / sub-category of product 3) by manufacturer and then it automatically re-arranged them and updated the file path - that would be great !

**Comment by Dirty-Butter** [comment]
I have a small store that did not have any image folders. I used the previous alphanumeric choice and it worked quite well. It was a disaster when I tried to use it on the big store where I already had quite a few brand folders. I ended up with a conglomeration that I did not like at all. I reverted to my own folders via a database table drop/copy from backup.
