### ISSUE TITLE
Performance issues with Matrix in admin area

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2421]
When trying to revise a product which has matrix data performance is significantly impacted by the code to update the matrix cached data. 

Update queries are quite expensive and in some stores with large matrix sets I am seeing upwards of 30 seconds page load time due to the following code:

```
// update cached name
if (isset($smarty_data['option_matrix']['all_possible']) && is_array($smarty_data['option_matrix']['all_possible'])) {
    $pc_postfix = 1;
    foreach ($smarty_data['option_matrix']['all_possible'] as $option_group) {
        if ($GLOBALS['db']->select('CubeCart_option_matrix', 'matrix_id', array('options_identifier' => $option_group['options_identifier']))) {
            $GLOBALS['db']->update('CubeCart_option_matrix', array('cached_array' => $option_group['cached_array'], 'cached_name' => $option_group['options_values'], 'status' => 1), array('options_identifier' => $option_group['options_identifier'], 'product_id' => $product_id));
        } else {
            $GLOBALS['db']->insert('CubeCart_option_matrix', array('cached_array' => $option_group['cached_array'], 'cached_name' => $option_group['options_values'], 'status' => 1, 'options_identifier' => $option_group['options_identifier'], 'product_id' => $product_id, 'product_code' => $result[0]['product_code'].'-'.(string)$pc_postfix));
        }
        $pc_postfix++;
    }
}
```

This needs refinement.

**Comment by Noodleyman** [comment]
relates to #1655

**Comment by Noodleyman** [comment]
Noted a defect: the SQL query used to check if the record exists is searching the entire DB table, it should be also matching on product_id.

`if ($GLOBALS['db']->select('CubeCart_option_matrix', 'matrix_id', array('options_identifier' => $option_group['options_identifier']))) {`

REPLACE WITH:
`if ($GLOBALS['db']->select('CubeCart_option_matrix', 'matrix_id', array('options_identifier' => $option_group['options_identifier'], 'product_id' => $product_id))) {`

This one changes boosts performance, however it's still not refined enough.

**Comment by Noodleyman** [comment]
I have also found an additional defect. If the option name to update cached_array includes a double quote ", this is escaped in the json to be written to the database, however it's translated to the " character  in the database which makes the json invalid when you read it back.

example:
`[{"name":"Door Type","value":"Fire Door"},{"name":"Door Style","value":"Bevelled Glass"},{"name":"Door Size","value":"35 x 1981 x 457 | 78 x 18\""},{"name":"Door Finish","value":"Finished"}]`

becomes:
`[{"name":"Door Type","value":"Fire Door"},{"name":"Door Style","value":"Bevelled Glass"},{"name":"Door Size","value":"35 x 1981 x 457 | 78 x 18""},{"name":"Door Finish","value":"Finished"}]`

**Comment by Noodleyman** [comment]
this is as far as I got to refinement, however due to the issue with json escaped strings being read from the DB, it's not able to match the majority of my test cases and still issues an update. however, for the store in question this has prevented about 600 UPDATE queries with around 400 still running, which is time consuming.
```

// update cached name
if (isset($smarty_data['option_matrix']['all_possible']) && is_array($smarty_data['option_matrix']['all_possible'])) {
    $pc_postfix = 1;
    foreach ($smarty_data['option_matrix']['all_possible'] as $option_group) {
        if ($mdata = $GLOBALS['db']->select('CubeCart_option_matrix', array('matrix_id', 'cached_array', 'cached_name'), array('options_identifier' => $option_group['options_identifier'], 'product_id' => $product_id))) {
            if($mdata[0]['cached_array'] != $option_group['cached_array'] || $mdata[0]['cached_name'] != $option_group['options_values']){
                $GLOBALS['db']->update('CubeCart_option_matrix', array('cached_array' => $option_group['cached_array'], 'cached_name' => $option_group['options_values'], 'status' => 1), array('options_identifier' => $option_group['options_identifier'], 'product_id' => $product_id));
            }
        } else {
            $GLOBALS['db']->insert('CubeCart_option_matrix', array('cached_array' => $option_group['cached_array'], 'cached_name' => $option_group['options_values'], 'status' => 1, 'options_identifier' => $option_group['options_identifier'], 'product_id' => $product_id, 'product_code' => $result[0]['product_code'].'-'.(string)$pc_postfix));
        }
        $pc_postfix++;
    }
}
```

**Comment by abrookbanks** [comment]
Thank you. Thats a great contribution. JSON issue next..

**Comment by Noodleyman** [comment]
Did you manage to find any further refinements that could be made? this specific feature still kills performance, although not as much with the changes noted above.

On the store in question, we currently have over 400,000 valid matrix records, almost every product uses it and it makes the admin area painful to use sometimes depending on the product complexity.

**Comment by abrookbanks** [comment]
How many rows in the table?

**Comment by Noodleyman** [comment]
revised comment above. around 400,000

**Comment by Noodleyman** [comment]
@abrookbanks , looks like this change introduced an oddity which is causing some problems in the matrix.

the matrix status gets set to 1 when a matrix record is added, or revised because something changed, cached array or cached name.

However, if you disable an option used in an option set, the matrix record status = 0.

Nothing EVER will set this back to 1 again, even if you enable the option again, this impacts stock levels if aggregating matrix inventory to the parent product as those records are excluded, in short.. it b0rks stuff over time.

There needs to be a way to toggle the status back ON for disabled items, or rather than set status = 0, just delete disabled matrix records. it will help with performance as well.

**Comment by abrookbanks** [comment]
Thanks. I'll look into this.

**Comment by abrookbanks** [comment]
Assuming you are referring to https://github.com/cubecart/v6/commit/e766079ee7c9772bec5c676150822c2156c878b3 I can't see how this would make a difference as it's only updating if `cached_array `or `cached_name` has changed?

Can you provide steps to reproduce this? That would make it much easier to delve into.

**Comment by Noodleyman** [comment]
setup options, assign to product. add to matrix. check matrix DB table (status = 1).

toggle the status of one option, save. check matrix db table. it flipped to disabled. 

enable the option again, matrix option still disabled. 

once disabled, the only way an option in the matrix gets enabled again is if the option name (cached name changes), or if it's deleted manually, then re-added by CC.  nothing will ever flip it to enabled again unless the option names change.

**Comment by abrookbanks** [comment]
Thanks. I believe our mutual client said you fixed this? If that's the case I'd be grateful if you could share.

**Comment by abrookbanks** [comment]
Reproduced. Thanks! :)

**Comment by Noodleyman** [comment]
I simply commented out the if statement to allow it to update on page load as it used to, which will prevent anything with an incorrect status from staying disabled. 

and then, to correct the impacted data, I set everything to status  1, then ran the same large block of code for every product in the store to correct existing data. it flipped invalid matrix entries to disabled. 

not an issue on the mutual store due to small number of records overall, but this isn't a viable workaround for larger stores, I've seen some with almost 1 million matrix records. is there any reason the status is set to disabled for matrix records rather than remove them? 

perhaps it's time to consider a scheduled cron job to run routine maintenance tasks, offloading some of the jobs from "on page load" methods.

**Comment by abrookbanks** [comment]
> is there any reason the status is set to disabled for matrix records rather than remove them?

I think the idea was to allow for them to be added back if there was a mistake remembering what the product codes etc where.

**Comment by Noodleyman** [comment]
perhaps a new store setting, delete/keep matrix data?

**Comment by abrookbanks** [comment]
I'd be interested to know what percent of matrix entries are disabled on a high count table. Maybe delete is better after all. 

A setting would be hard to educate merchants about as we couldn't expect them to understand the concept of SQL load.

**Comment by abrookbanks** [comment]
CubeCart is due some cron tasks. There are lots of things we can do to improve performance such as batch processing email instead of having them "block" the code making a page load slower. It would be more asynchronous this way.

Development has slacked due to this bloody virus with kids at home so much. 

Back to the issue at hand. Did you notice a significant performance improvement with the condition below?

`if($mdata[0]['cached_array'] != $option_group['cached_array'] || $mdata[0]['cached_name'] != $option_group['options_values']){`

I wouldn't have thought it would make much difference.

I wonder if a better solution is to have table per product. 

e.g. `CubeCart_option_matrix_{product_id}`

**Comment by abrookbanks** [comment]
The store in question only has ~2k rows in the  CubeCart_option_matrix table. This shouldn't be a big deal.

**Comment by Noodleyman** [comment]
from a store with just shy of 400,000 options, 372,510 with status - 0.

**Comment by abrookbanks** [comment]
Blimey. I did also notice that the football store has over 50% status = 0;

Maybe its time to only save status 1.

**Comment by Noodleyman** [comment]
Cron, with hooks would be super helpful as I've got a backlog of things I intend to port to CRON anyway. If one already exists with hooks, it'll be one job rather than multiple. I've built several already for CC, easy to setup just needs core tasks adding to it and then those items removed from page loads etc. HOWEVER, it may be a good idea to have a setting to toggle on/off the use of cron, in case it can't be setup for some reason.

**Comment by Noodleyman** [comment]
"Did you notice a significant performance improvement with the condition below"

Yes, page load from > 40 seconds (aka, timeout with default 30 seconds), to about 5-10 seconds.  It depends on the number of options / unique combinations of options since they are essentially Cartesian joined.  it can be tens of thousands for a single, complex product.

**Comment by abrookbanks** [comment]
> from a store with just shy of 400,000 options, 372,510 with status - 0

I think that is enough to warrant a delete.

**Comment by abrookbanks** [comment]
The status column doesn't even have an index!

**Comment by Noodleyman** [comment]
the index didn't help much when I tested it. the real drag was it calculating every unique combination on page load, then cross referencing the DB. but yes, more records = more work.

**Comment by abrookbanks** [comment]
Thanks Alec. Big help here. 

I haven't dropped the status column in case we need to back track on these changes. 

We should be in a much better place now.

**Comment by Noodleyman** [comment]
you may want to consider making a setting, which defaults to existing behaviour, giving the option to toggle the delete ON. (default off), for legacy reasons. then if people have data sets which is causing performance issues the setting can be toggled on

**Comment by abrookbanks** [comment]
With the level of bloat on just two stores (over 50% status = 0) I'd be included to think this is a bug which will eventually cause performance issues.

**Comment by abrookbanks** [comment]
If we put it back to work with status and introduced a cron to see if a status has been 0 for more than say a few days that could make the current solution work without bloat.

**Comment by havenswift-hosting** [comment]
> perhaps it's time to consider a scheduled cron job to run routine maintenance tasks, offloading some of the jobs from "on page load" methods.

This is something that a LOT of other systems do and something I think would be ideal for CubeCart -the batch email process for example (although we do have a plugin that does this already but would be happy for this to be core !)

>  HOWEVER, it may be a good idea to have a setting to toggle on/off the use of cron, in case it can't be setup for some reason.

I disagree.  Cron is almost universally available with hosting accounts and we shouldnt be bloating code and maintaining old ways of doing things for the few odd hosting companies that disallow the use of cron - these should just be considered incompatible hosting in the same way they are if other requirements arent available.  In addition you can always use third party cron anyway

**Comment by abrookbanks** [comment]
@havenswift-hosting thanks fr your thoughts :)

I think I've come up with the optimal solution now. Essentially it will allow option matrix rows with status 0 live for three days. This allows for the merchant to get their product setup right with a 3 day memory if they add or remove to the matrix based on a time stamp when added.  I've tested the delete which works correctly for timestamps older than 3 days.

**Comment by havenswift-hosting** [comment]
I agree that sounds like a good solution for this situation, the cron is a potential solution to other problems and also an opportunity for better functionality

**Comment by abrookbanks** [comment]
@havenswift-hosting totally agree.

I think email is a particular one. One connection can be opened for say 10 emails at a time or something rather than each time on the fly. It could even be restricted by the hour to say 100. The rest could be sent at quieter times.

**Comment by Noodleyman** [comment]
@abrookbanks, just revisiting this to double check something. 
I know that a delete is now issued, however the upgrade to the version with this change MUST correct the status of all matrix records to avoid deletion of valid data which has an incorrect status.

revisiting this as I'm working on correcting this issue on a large store at the moment as it appears to be the root cause of many weird matrix related oddities.

**Comment by Noodleyman** [comment]
FYI, I threw this into products.index.inc.php so I could manually call the fix on demand.  it corrects all the status.

```
        /**
         * Added to call manually to FIX matrix status problems
         */
        if(isset($_GET['fix_matrix_stuff'])){

            set_time_limit(0);

            $all_prod_ids = $GLOBALS['db']->select('CubeCart_inventory', array('product_id'));

            function option_matrix_again($unique_groups)
            {
                $no_groups = count($unique_groups);
                if ($no_groups <= 1) {
                    return $no_groups ? array_map(function ($v) {
                        return array($v);
                    }, $unique_groups[0]) : $unique_groups;
                }

                $last_value = array_pop($unique_groups);
                foreach ($last_value as $value_id) {
                    $appends = option_matrix_again($unique_groups);
                    foreach ($appends as $append) {
                        $output[] = is_array($append) ? array_merge($append, array($value_id)) : array($append, $value_id);
                    }
                }
                return $output;
            }

            if(isset($all_prod_ids) && is_array($all_prod_ids) && !empty($all_prod_ids)){
                // Reset all...
                $GLOBALS['db']->update('CubeCart_option_matrix', array('status' => 1));

                foreach($all_prod_ids as $pids){

                    // Reset vars
                    $group_list = array();
                    $value_list = array();
                    $unique_keys = array();
                    $smarty_data['option_matrix'] = array();


                    $pid = $pids['product_id'];


                    // Generate list of groups and values
                    if (($groups = $GLOBALS['db']->select('CubeCart_option_group', false, false, array('priority'=>'ASC'))) !== false) {
                        foreach ($groups as $group) {
                            $group_list[$group['option_id']] = $group;
                        }
                        if (($values = $GLOBALS['db']->select('CubeCart_option_value', false, false, array('priority'=>'ASC'))) !== false) {
                            foreach ($values as $value) {
                                $value_list[$value['option_id']][$value['value_id']] = $value;
                            }
                        }
                    }

                    // Product Options (Additional)
                    if (isset($group_list) && is_array($group_list) && !empty($group_list)) {
                        foreach ($group_list as $i => $group) {
                            if (isset($value_list[$group['option_id']])) {
                                foreach ($value_list[$group['option_id']] as $value) {
                                    $group['members'][] = $value;
                                }
                            } else {
                                $group['option_id'] = (-1)*$group['option_id'];
                            }
                            $smarty_data['list_options_select'][$i] = $group;
                        }
                    }

                    // Stock for product options
                    $options = $GLOBALS['db']->misc('SELECT A.option_id, A.value_id ,V.value_name, G.option_name FROM `'.$GLOBALS['config']->get('config', 'dbprefix').'CubeCart_option_assign` AS `A` INNER JOIN `'.$GLOBALS['config']->get('config', 'dbprefix').'CubeCart_option_value` AS `V` ON A.value_id = V.value_id INNER JOIN `'.$GLOBALS['config']->get('config', 'dbprefix').'CubeCart_option_group` AS `G` ON A.option_id = G.option_id WHERE `product` = '.$pid.' AND `set_enabled` = 1 AND `matrix_include` = 1 ORDER BY A.option_id, IF(V.priority>0, V.priority, V.value_id) ASC');
                    /*
                        option_id = group name e.g. size
                        value_id = value id e.g. 7
                        value_name = value name e.g. large
                    */

                    $unique_groups = array();
                    if ($options) {
                        // Work out unique groups
                        $key_id = -1;

                        foreach ($options as $key => $data) {
                            $option[$data['value_id']] = array(
                                'option_name' => $data['value_name'],
                                'option_group' => $data['option_name'],
                                'option_id' => $data['option_id'],
                                'value_id' => $data['value_id'],
                            );
                            if (!isset($unique_keys[$data['option_id']])) {
                                $unique_keys[$data['option_id']] = true;
                                $key_id++;
                            }
                            $unique_groups[$key_id][$data['value_id']] = $data['value_id'];
                        }
                    }

                    $option_matrix = option_matrix_again($unique_groups);



                    $possible = false;

                    if (is_array($option_matrix)) {
                        foreach ($option_matrix as $matrix_values) {
                            foreach ($matrix_values as $matrix_value_id) {
                                $options_nvp[] =  array('name' => $option[$matrix_value_id]['option_group'], 'value' => $option[$matrix_value_id]['option_name']);

                                $options_values[] =  '<strong>'.$option[$matrix_value_id]['option_group'].'</strong>: '.$option[$matrix_value_id]['option_name'];
                                $options_identifier[]  =  $option[$matrix_value_id]['option_id'].$option[$matrix_value_id]['value_id'];
                            }
                            $option_identifier_string = md5(implode('', $options_identifier));
                            $smarty_data['option_matrix']['all_possible'][] = array(
                                'options_identifier' => $option_identifier_string,
                                'options_values' => implode(', ', $options_values),
                                'cached_array' => json_encode($options_nvp)
                            );
                            $possible[] = $option_identifier_string;
                            unset($options_identifier, $options_values, $options_nvp);
                        }
                    }

                    if (is_array($possible)) {
                        $delete_query = "UPDATE `".$GLOBALS['config']->get('config', 'dbprefix')."CubeCart_option_matrix` SET `status` = 0 WHERE `product_id` = $pid AND `options_identifier` NOT IN ('".implode("','", $possible)."')";
                        $GLOBALS['db']->misc($delete_query);
                    } else {
                        $GLOBALS['db']->update('CubeCart_option_matrix', array('status'=>0), array('product_id'=>$pid));
                    }
                }
            }

            echo "Repaired!";
            die();
        }
```
