### ISSUE TITLE
Bug ..

### ISSUE THREAD

**Issue by ChrisNColeman** [cubecart/v6#2422]
` //=====[ Private ]=======================================

    /**
     * Parse contents though Smarty
     *
     * @param string $contents
     * @return string
     */
    private function _parseContents($contents)
    {
        if (is_string($contents)) {
            return $GLOBALS['smarty']->fetch('string:'.$content);
        } elseif (is_array($contents)) {
            $out = array();
            foreach ($contents as $key => $content) {
                $out[$key] = $GLOBALS['smarty']->fetch('string:'.$content);
            }
            return $out;
        }
        return false;
    `}``

Maybe not so important but first $content can never be set ..

Chris.

**Comment by bhsmither** [comment]
A misspelled variable.

**Comment by abrookbanks** [comment]
Thanks guys.
