### ISSUE TITLE
PHP Function Parameters

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2426]
Please check Smarty `function.combine.php`, line 132.

The variable `$last_mtime` will contain the contents of a file, if it exists.

That variable, treated as an integer, is then used in PHP's `date()` function.

I haven't debugged this yet, but it doesn't look right.

I don't see what I chasing after, but I think this is the cause.

What I am chasing after is that some stores are showing rogue binary as the first ten characters or so of the page HTML. I don't see this on the demo store.

**Comment by abrookbanks** [comment]
It's not actually a bug. The file content will be a timestamp. Crazy world we live in. :)

I will reopen if I am wrong.
