### ISSUE TITLE
PayPal Standard Module

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2428]
See:
https://forums.cubecart.com/topic/55502-paypal-problem/
(Reports of a 301 bounce.)

I tested the web address as specified in the module's /admin/index.inc.php file and got a 302 to a landing homepage.

The changelog says a tool was added to test the IPN endpoints. Next, the web addresses for the endpoints was updated.

But was the tool updated? Does it need to be updated?

Note: I also note that a commented out
```
/* $this->_curl_options[CURLOPT_FOLLOWLOCATION]  = true; */
```
was deleted in CC628.

**Comment by abrookbanks** [comment]
We are no longer developing this extension. Merchants should move over to PayPal Commerce.

**Comment by havenswift-hosting** [comment]
This needs to be made VERY clear somehow to merchants - there will be a VERY large number using this plugin
