### ISSUE TITLE
Upgraded from 6.2.6 to 6.2.8

### ISSUE THREAD

**Issue by SyronV** [cubecart/v6#2430]
Hi can anyone tell me what has happened? I upgraded from 6.2.6 to 6.2.8 and I am getting these symbols at the top of the shop page? It does it in Foundation?

www,shop.boltlock.com.au

Any help would be great?

Tyrone

![2019-11-25](https://user-images.githubusercontent.com/23268337/69503995-d86a0c00-0f6a-11ea-8929-cdcd1edc0464.png)

**Comment by SyronV** [comment]
I checked the error report and this is what is says: 
File: [controller.admin.pre_session.inc.php] Line: [26] "SET @@time_zone = 'Australia/Brisbane'" - Unknown or incorrect time zone: 'Australia/Brisbane

**Comment by SyronV** [comment]
and there is this error:

  | [<strong>Notice</strong>] 	 /home/boltadmin/public_html/shop/admin_6LeVae/sources/settings.errorlog.inc.php:69  - Undefined variable: smarty_data


  | [<strong>Notice</strong>] 	 /home/boltadmin/public_html/shop/modules/social/Facebook/social.class.php:53  - Undefined index: comments_width
-- | --


[<strong>Notice</strong>] /home/boltadmin/public_html/shop/classes/ssl.class.php:39 - Undefined index: _g
-- | --

**Comment by bhsmither** [comment]
There has been a couple of discussions about this on the forums.

It turns out that there was an active code snippet that behaves differently under CC628.

Please view your admin, Manage Hooks, Code Snippet tab, to determine if any snippets are active.

If so, disable them and let us know if the rogue characters disappear.

**Comment by SyronV** [comment]
Legend! You and Al deserve a pay rise for your efforts!
The symbols was being caused by Apply Discount Code via URL - which is a free extension on the Cubecart website
And the date error was resolved when I disabled the time and date in the time and date settings in the Advance store setting, which changes the invoice numbers to a different time stamp, which I like but close enough is good enough!
Thanks very much!

**Comment by bhsmither** [comment]
"Apply Discount Code via URL - which is a free extension on the Cubecart website"

Do you have a web address for this?

**Comment by bhsmither** [comment]
Never mind -- found it.

**Comment by bhsmither** [comment]
Are you sure? I just installed it, and I do not get these characters.

**Comment by SyronV** [comment]
I will try to reinstall it but once I disabled it, the characters disappeared? It was the first and only thing I did and I checked after I disabled it, after you advised about the code snippets? The characters only appeared after the upgrade from 6.2.6 to 6.2.8, I haven't reinstalled it after the upgrade? I will let you know if I have any further issues after I reinstall it... Thanks very much...

**Comment by abrookbanks** [comment]
Please seek technical support on our forums or via our official channel. 

Forums: https://forums.cubecart.com/ 
Official Support:  https://www.cubecart.com/technical-support
