### ISSUE TITLE
Coupon conditions validation not performed when removing items from basket

### ISSUE THREAD

**Issue by romanklabal** [cubecart/v6#2432]
Promo coupons in CC can have several conditions which are being validated within the method Cart::discountAdd().

Lets say I create a coupon with a minimum subtotal of €100. 

- When I add one item costing €99 to the basket and try to apply the coupon, naturally it wont let me.
- I increase the quantity to 2, bringing the subtotal to €198, and then it lets me add the coupon.
- When I decrease the quantity back to 1, the basket correctly removes the coupon with a "Sorry, your basket does not qualify for that promotional code." message.

**However!**

- I then add a completely different product to the basket, which brings my subtotal over €100 and lets me use the coupon again.
- I then **remove** the latest product from the basket, bringing the subtotal back below €100, yet the coupon is still applied!

Tested on the latest CC 6 online demo.

Funny thing - I discovered this bug on my butchered 5.0.7 CC website, so I went to check the latest v6 cart.php class and compare the update() method to see you have correctly moved this check outside the $_POST['quan'] check to be performed even when there are no changes to the quantity: https://github.com/cubecart/v6/blob/6.2.0-branch/classes/cart.class.php#L1185

And when I did the same change on my v5, this somehow fixed the issue. It does not display the error message, but the coupon disappears from the basket as it should. The only difference I see I dont call the save() method in the block I linked above - but its hard to say what else has changed since 5.0.7.

**Comment by abrookbanks** [comment]
It's embarrassing that this was from 2019!! The discount code login was totally rewritten after this time.

I'm pleased to say that I'm no longer available to reproduce this.
