### ISSUE TITLE
Count() Problem

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2433]
Another count() problem.

classes/db/database.class.php on line 708

See #2401.

The difference is that there is a second test that asks if the parameter is an array.

I had once read that PHP will make a quick scan on the collection of tests in a condition argument to determine if a truthness or falseness can be determined. PHP would then do the actual work if the result could not be determined.

However, at:
https://forums.cubecart.com/topic/55537-php-error-cubecart-628-php-ver-7224/
it may be the case that PHP has adopted a different strategy. 

So, perhaps put the `is_array()` first, so that when it evaluates to false, the rest of the condition argument is not performed.

**Comment by abrookbanks** [comment]
That makes sense. Thank you.
