### ISSUE TITLE
CubeCart Newsletter sends forever when no subscribers

### ISSUE THREAD

**Issue by GUNFAI** [cubecart/v6#2434]
Minor; I made a new installation of Cubecart 6.2.8 and set up mail working with TLS. During testing of the new site I found that when it is no subscribers to newsletters and you try to send a newsletter to subscribers it stucks in "sending" until you cancel. When adding at least one subscriber then it works. Removing the subscribers gives the same fault.

It should give a notice "No subscribers" instead.

**Comment by abrookbanks** [comment]
Thank you!
