### ISSUE TITLE
clearImageCache Reports Success Regardless

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2438]
In `maintenance.index.inc.php`, line 388, regardless of the outcome of `cleanImageCache()` - which does not return a value - a success message is displayed.

So does a few other tasks in the **Rebuild** group.

**Comment by abrookbanks** [comment]
e.g. 
![Untitled](https://user-images.githubusercontent.com/4520803/75252852-60171f00-57d5-11ea-95d7-e1355bf62f66.png)
