### ISSUE TITLE
After Plugin Import check the folder name matched what is specified in config.xml

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#244]
For example the plugin below should be in folder "modues/livehelp/zopim":

![screen shot 2015-02-19 at 17 44 54](https://cloud.githubusercontent.com/assets/4520803/6272429/6b99def0-b85f-11e4-9c1f-7d887c8d5e4c.png)

Error message needs to be displayed.

**Comment by havenswift-hosting** [comment]
Excellent idea !

**Comment by abrookbanks** [comment]
I was born excellent!

**Comment by abrookbanks** [comment]
This can actually be done before its extracted which is nice.

**Comment by havenswift-hosting** [comment]
How do zip files need to be constructed (and how will your new checking routine cope with) where plugins also need to add files into other higher level directories such as admin/skins or admin/source ?

**Comment by abrookbanks** [comment]
I can't actually find a way to do this. The developer submitting the plugin will need to test it.
