### ISSUE TITLE
6.2.9 Zopim chat issue?

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#2441]
I have installed the Zopim chat code and now have a conflict with the Joyride script. If I try to edit a product in Admin the Tour popup suddenly appears on each attemp to save the product tab I'm on. I can't proceed without x-ing out the tour popup. Next button save and tour is back.
I have tour disabled in Administrator. And the popup occurs whether Zopim chat is enabled or not.
The only way I found that stops it is to comment out the Zopim script in main.php.

**Comment by abrookbanks** [comment]
I think we would need to look at this as a single case.
