### ISSUE TITLE
Search defect 

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2442]
confirmed on a fresh install of the latest CubeCart version. If you perform a keyword search and there are enough results to trigger pagination, and you have a result set which totals the pagination number + 1, you get odd behaviour.

For example. you search and get 13 results, pagination is set at 12 items per page.

When you go to page 2, instead of seeing the results you are redirected with the "Just one product was found matching ...." phrasing.

**Comment by bhsmither** [comment]
Possible continuation of #2281.

**Comment by abrookbanks** [comment]
Thanks guys.
