### ISSUE TITLE
controller.index.ic.php time zone repeated setting fail many instances per minute?

### ISSUE THREAD

**Issue by andysarcade** [cubecart/v6#2444]
hi all, i hadn't looked for a while, but my error log is up to 1.3 million entries, related to a time zone thing? the two repeated erros are :

 File: [controller.admin.pre_session.inc.php] Line: [26] "SET @@time_zone = 'Africa/Abidjan'" - Unknown or incorrect time zone: 'Africa/Abidjan'

File: [controller.index.inc.php] Line: [27] "SET @@time_zone = 'Africa/Abidjan'" - Unknown or incorrect time zone: 'Africa/Abidjan'

5-10 entries per minute...

**Comment by andysarcade** [comment]
just to add, i see my store time zone was actually set to Africa/Abidjan, but when i put it on my actual time zone, it still error logs the same way but with the new time zone name instead of Africa/Abidjan.

**Comment by havenswift-hosting** [comment]
This is not a bug but a problem / missing entry with the MySQL server on the server that your website is hosted on.  There are several threads on the forums that explain it and how it can be fixed although unless you have root level access you won’t be able to do it yourself

**Comment by andysarcade** [comment]
ok thanks, I will go look to see this. But can't this known issue be caught by cubecart and not cause such repeated server load?

**Comment by abrookbanks** [comment]
Set Timezone to "Disabled" in the advanced section of your admin control panel or enable time zone support:
https://dev.mysql.com/doc/refman/8.0/en/time-zone-support.html
