### ISSUE TITLE
Self-reference hreflang annotation missing  - Missing reciprocal hreflang (no return-tag)

### ISSUE THREAD

**Issue by azitafomo** [cubecart/v6#2447]
please help me my website has one languge [](:[20bekhar.com](https://20bekhar.com/))
and these errors are in hrefs error that I need to solve
![001](https://user-images.githubusercontent.com/57670369/71640364-b49e9200-2c9d-11ea-824e-fa952ba5db7b.JPG)
![003](https://user-images.githubusercontent.com/57670369/71640365-b49e9200-2c9d-11ea-94f9-ea7b6ac9bb79.JPG)

**Comment by bhsmither** [comment]
Please verify that you are using CubeCart.

Evidence suggests that you are using PrestaShop.

**Comment by azitafomo** [comment]
> Please verify that you are using CubeCart.
> 
> Evidence suggests that you are using PrestaShop.

Could you tell me about it?

**Comment by abrookbanks** [comment]
Wrong platform.
