### ISSUE TITLE
Unknown column 'seo_meta_keywords' in 'field list

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2449]
As of CubeCart version 6.2.6 the structure.sql file no longer contains a column named **seo_meta_keywords** for the table **CubeCart_category**

However. Although I realise that this is an outdated column, dropping it from the DB is impacting third party modules/hooks which expect the column to exist. In some stores this is causing significant numbers of errors to be logged. 

Please can this column be restored if it doesn't exist and simply drop the references to it instead?

It's broken a large number of SQL queries in a bunch of my modules and some other parties modules as the column had no default value, meaning SQL queries adding records needed to have this column included in the fields and add an empty value for them to work. Now it's missing, all of those queries fail.

**Comment by abrookbanks** [comment]
Sorry I didn't think this would be used by 3rd party.
