### ISSUE TITLE
CubeCart_cookie_consent needs maintaining

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2452]
I'm seeing this table get to crazy sizes on busy stores, and even on less busy stores.

For example, a store I reviweed today had > 28,000,000 records in this table. Table size being 9.5GB in size. This can't be considered valid.

Can records with a 0 value be purged after a period of time?

I am also seeing a large number of duplicate records (same session, customer ID etc), with a different time.

**Comment by Dirty-Butter** [comment]
I had noted this huge file some time ago and CC now has a manual way to delete all records. in Maintenance I would have preferred a way to delete all older than xxx, or some such setting. Maybe your request will get this issue dealt with more completely.

**Comment by Noodleyman** [comment]
@abrookbanks 
Found another one today.. this needs some attention as part of the next CubeCart update
![image](https://user-images.githubusercontent.com/10614018/72889058-c4dae780-3d06-11ea-8497-a8aab96eb1a7.png)

**Comment by Noodleyman** [comment]
I randomly just spot checked a hand full of site databases. all show this issue, not a single one was under 1GB for that table.

**Comment by abrookbanks** [comment]
It now logs who it was displayed to, when, what and where instead of logging for every page load. This should make the table considerably lighter and probably more useful too.

**Comment by abrookbanks** [comment]
This means that per session a maximum of two logs will now be made. 

1. The dialogue (where, when and who).
2. Accept or Blocked (where, when and who).

**Comment by Noodleyman** [comment]
does it also clean up the several GB of data in the table on upgrade?

**Comment by abrookbanks** [comment]
> does it also clean up the several GB of data in the table on upgrade?

No but there is a tool to purge it in 6.2.9 via the maintenance section. I'm not sure how we can clean it up without deleting all. That could be unfavourable.

**Comment by Noodleyman** [comment]
removing all duplicates would help on upgrade,. probably an 90% reduction there ;)

**Comment by abrookbanks** [comment]
Yeah could well be.. not sooooo easy though. The log column has no index so an SQL query to do this on upgrade could be rather heavy. I will see what I can do.

**Comment by Noodleyman** [comment]
Add an index, select query from one table to a temp table, use group by to reduce dupes, truncate and move back ;)

Shouldn't take too long to do and the upgrade process does suggest grab coffee whilst you wait ;)

**Comment by abrookbanks** [comment]
This seems to do the job:

```
CREATE TEMPORARY TABLE `tmp_cookie_table` (SELECT * FROM `CubeCart_cookie_consent` GROUP BY `log`,`session_id`);
DELETE FROM `CubeCart_cookie_consent`;
ALTER TABLE `CubeCart_cookie_consent` MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;
INSERT INTO `CubeCart_cookie_consent` (SELECT * FROM `tmp_cookie_table`);
```

**Comment by Noodleyman** [comment]
I would truncate CubeCart_cookie_consent, it's faster and also resets auto_increment values. 

don't forget to drop the temp table ;)

**Comment by abrookbanks** [comment]
Some sound advice there! :)

```
CREATE TEMPORARY TABLE `tmp_cookie_table` (SELECT * FROM `CubeCart_cookie_consent` GROUP BY `log`,`session_id`); #EOQ
TRUNCATE `CubeCart_cookie_consent`; #EOQ
INSERT INTO `CubeCart_cookie_consent` (SELECT * FROM `tmp_cookie_table`); #EOQ
DROP TEMPORARY TABLE `tmp_cookie_table`; #EOQ
```

**Comment by abrookbanks** [comment]
It's working well. I don't know if you have a backup of a large old table to try it on?

**Comment by Noodleyman** [comment]
sorry, I do not. I clear the table of data before I export as they can be quite large otherwise.

**Comment by abrookbanks** [comment]
No probs. I’ll look out for a merchant with a big one.

**Comment by Dirty-Butter** [comment]
I have a large one I can try it on - brb

**Comment by abrookbanks** [comment]
That sounds a bit dodgy!! LOL

**Comment by abrookbanks** [comment]
This is the final code;

```
ALTER TABLE `CubeCart_cookie_consent` ADD `log_hash` VARCHAR(32) NOT NULL; #EOQ
ALTER TABLE `CubeCart_cookie_consent` ADD `url_shown` VARCHAR(255) NOT NULL; #EOQ
UPDATE `CubeCart_cookie_consent` SET `log_hash` = MD5(`log`); #EOQ
ALTER TABLE `CubeCart_cookie_consent` ADD INDEX(`log_hash`); #EOQ
CREATE TEMPORARY TABLE `tmp_cookie_table` (SELECT * FROM `CubeCart_cookie_consent` GROUP BY `log_hash`,`session_id`); #EOQ
TRUNCATE `CubeCart_cookie_consent`; #EOQ
INSERT INTO `CubeCart_cookie_consent` (SELECT * FROM `tmp_cookie_table`); #EOQ
DROP TEMPORARY TABLE `tmp_cookie_table`; #EOQ
```

**Comment by Dirty-Butter** [comment]
I tried to use it via cpanel one a test store and I'm getting an error message that will not let it run - can't copy paste it, as it disappears on SQL screen - but it's something about A reserved keyword cannot be used as a column name without backquotes (near SELECT)
Also - Atleast one column definition was expected (near SELECT)
Error is on the CREATE TEMPORARY TABLE line

Maybe it's because this install not on the most recent commit - is that why you said dodgy???

**Comment by abrookbanks** [comment]
Thanks for trying. I can't see any columns or tables without backquotes. Can you Alec? 

> is that why you said dodgy???

No. :) Ignore that. I'm just being weird.

**Comment by Dirty-Butter** [comment]
It's underlining SELECT as being the spot of the error on (SELECT * FROM

**Comment by Dirty-Butter** [comment]
I don't read weird very well :)

**Comment by Noodleyman** [comment]
you don't need brackets for the select * from sub query when used with an insert. maybe that's it (untested)

**Comment by Dirty-Butter** [comment]
I took off the parenteses but now I get:
ALTER TABLE `CubeCart_cookie_consent` ADD `log_hash` VARCHAR(32) NOT NULL

MySQL said: Documentation
#1060 - Duplicate column name 'log_hash'

**Comment by abrookbanks** [comment]
Ok run just this part...

```
CREATE TEMPORARY TABLE `tmp_cookie_table` (SELECT * FROM `CubeCart_cookie_consent` GROUP BY `log_hash`,`session_id`); #EOQ
TRUNCATE `CubeCart_cookie_consent`; #EOQ
INSERT INTO `CubeCart_cookie_consent` (SELECT * FROM `tmp_cookie_table`); #EOQ
DROP TEMPORARY TABLE `tmp_cookie_table`; #EOQ
```

**Comment by Dirty-Butter** [comment]
It's still complaining about the "a symbol name was expected" SELECT is still underscored. 
It did try to run the query however, but results:

Show query box
MySQL returned an empty result set (i.e. zero rows). (Query took 9.1601 seconds.)
CREATE TEMPORARY TABLE `tmp_cookie_table` (SELECT * FROM `CubeCart_cookie_consent` GROUP BY `log_hash`,`session_id`)
[Edit inline] [ Edit ] [ Create PHP code ]
MySQL returned an empty result set (i.e. zero rows). (Query took 0.1607 seconds.)
#EOQ TRUNCATE `CubeCart_cookie_consent`
[Edit inline] [ Edit ] [ Create PHP code ]
112262 rows inserted. (Query took 9.4253 seconds.)
#EOQ INSERT INTO `CubeCart_cookie_consent` (SELECT * FROM `tmp_cookie_table`)
[Edit inline] [ Edit ] [ Create PHP code ]
MySQL returned an empty result set (i.e. zero rows). (Query took 0.1233 seconds.)
#EOQ DROP TEMPORARY TABLE `tmp_cookie_table`
[Edit inline] [ Edit ] [ Create PHP code ]
MySQL returned an empty result set (i.e. zero rows). (Query took 0.0001 seconds.)

**Comment by Dirty-Butter** [comment]
Maybe somebody else better try this - I know just enough about all this stuff to be trouble, but not enough to be helpful. LOL

**Comment by abrookbanks** [comment]
That's wierd. I don't think it's pasting in what is expected from here. Your error has no bsckquotes in but the code here does.

**Comment by Dirty-Butter** [comment]
The backquotes are there - just did not pick them up for some reason on copy/paste. Just to be sure I tried it again - same

**Comment by abrookbanks** [comment]
I'm going to close this as I'm confident the fix is good. I'll seek a big database to test it on but it works nicely on a small one.
