### ISSUE TITLE
Tax is not granular enough for some US based states/businesses

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2453]
@abrookbanks , this is reasonably urgent.

Found out today of a use case which CubeCart tax system cannot handle.

A customer in US, GA has to pick a tax rate based on Country / State and County. the rate can vary per county within the state.

CubeCart can only handle Country/State level at the moment. for the tax system to be usable the tax for some customers must be refined based on Country / State and then Country within the state. 

there are a dozen or so states in the U.S which now require this level of tax. CubeCart needs to be updated to be able to handle this or we may need to move away from CubeCart for those stores in these areas.

**Comment by Noodleyman** [comment]
The only way I can think to get this working today, is to add lots of phantom states. 

Instead of the State being "Georgia" , I'll have to create 159 states of "Georgia - X" with X being the County name.  Tax rules can then be setup per State/County combination.

I think this will break existing customer accounts which have address book data as those will point to the original state ID in the geo data tables, but it will need to be removed due to the more granular breakdown.

It would be great if this can be considered for the next CubeCart release and supported in a better way. It's really impacting some US companies who just got told they have to fix this in their stores or get fined.

**Comment by tbonerocketeer** [comment]
https://smallbiztrends.com/2019/01/list-of-states-with-internet-sales-tax.html

This is the current list of states that require this.

**Comment by abrookbanks** [comment]
I know of a CubeCart merchant doing just that with Ohio by adding multiple derivatives of Ohio. 

How would you se it working from a UX perspective on the front end. Another field after State?

**Comment by Noodleyman** [comment]
Another select for county (much like state) would be ideal, naturally only if there are counties setup for the state otherwise either hide the field or offer a text input.
What we wanted to avoid was the state becoming a state/county list as it would contain thousands of entries making it pretty unusable for customers

**Comment by abrookbanks** [comment]
I think `Counties` is the correct terminology. Two things for 2020;

- Updated extensions
- New midpoint release (roadmap to be decided)
- New default theme (one is started already)

**Comment by abrookbanks** [comment]
make that 3 :laughing:

**Comment by Noodleyman** [comment]
Yes, Counties.  so it's three tiers (in some cases)

Country -> State -> County

Some U.S states are just by Country -> State

so it's one of those hierarchical solutions based on whatever is configured at the most granular level being applicable.

**Comment by abrookbanks** [comment]
Exactly that.

**Comment by Dirty-Butter** [comment]
Is there some way to deal with existing accounts by using the zip code to generate the additional County designation once it's added to CC? Luckily for us, Alabama does not require this level yet. But if GA is doing it, we will too eventually, more than likely.

**Comment by Dirty-Butter** [comment]
Here's a list of GA Zips with counties. A ZIP range looks like it could be used to populate the new County field on old accounts in GA at least.
[http://www.georgiahealthdata.info/Georgia_Zip_Code_County_Lookup.PDF](url)

**Comment by bhsmither** [comment]
Depends on the state. See:
https://forums.cubecart.com/topic/55235-tax-zones-by-county/
Github #1786

**Comment by abrookbanks** [comment]
> Instead of the State being "Georgia" , I'll have to create 159 states of "Georgia - X" with X being the County name. Tax rules can then be setup per State/County combination.

This feels like a work around to me. It would need to work off a typical US address that would be on a letter. 

On those grounds how do we go about it? We can't expect US customers to enter their billing address in a non standard way.

**Comment by Noodleyman** [comment]
Morning Al,

We fixed this issue on a site by using USPS address validation API. we cross check all addresses and improve them as needed. customers are warning about addresses that do not align with US postal standards. they can still be overridden, but in most cases customers go with the suggested addresses.

In an ideal world, the tax rules should check for the most granular tax rule first (Country -> State -> County). If a match is found use that tax rate. If it is not found, then fall back to the next tier (Country -> State) and apply a rule there if it exists.  This solves the need of having to add additional records for counties who have the same tax rate as the state, and thus lowers the administrative overhead. 

I am currently looking for the most suitable place to acquire updated tax rates for the U.S to setup this kind of thing. It would be great if those rates could sync (on request) with a central repository to refresh based on changes, or some method to bulk adjust the rates.

**Comment by abrookbanks** [comment]
US State Counties (via ChatGPT)

ChatGTP:
> That’s a huge dataset — the U.S. has 3,143 counties and county equivalents (parishes in Louisiana, boroughs in Alaska, independent cities in Virginia, etc.).

**Comment by abrookbanks** [comment]
Python script to generate json file of data: [counties.py](https://github.com/user-attachments/files/22381162/counties.py)

Output: [us_counties.json](https://github.com/user-attachments/files/22381088/us_counties.json)
Output Compressed: [us_counties.zip](https://github.com/user-attachments/files/22381092/us_counties.zip)

**Comment by Noodleyman** [comment]
Yup, the more I am digging into this one, the more it's turning into a more complex beast. Cross checking other ecommerce platforms, most of them use some form of central API based solution, or centrally maintained repository of tax rules for the U.S. I think there are more than 11,000 tax jurisdictions.  I'm now pondering if a module that can extend the taxation system to integrate with a third party tax rule system to get rates based on store address & recepient details may be a more viable route forward.  It's a painful topic.

**Comment by abrookbanks** [comment]
Yes I've seen the same. 3rd party management seems the best solution but there are huge issues with CubeCart as a free open source self hosted solution.

**Comment by abrookbanks** [comment]
I guess "we" should research how competitors have overcome this.

**Comment by Noodleyman** [comment]
agreed. I am still researching options as well
