### ISSUE TITLE
Feature Request: Unique tax codes

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2454]
Relates to #2453,
In some cases, simply knowing the total tax charged isn't enough information, especially when integrating with third party accounting systems. 

It would be helpful if it was possible to define custom tax codes (unique) for tax rules which are then recorded at the order summary and/or order inventory level so it's possible to track which tax rule applied. 

Background for request:
Interfacing with an accountancy application which requires transactions to be mapped to tax codes so it can reconcile correctly, but we currently can only pass the tax financial details. without the tax codes we can't break the tax into the various local tax containers in the accountancy software.

**Comment by russellhurst** [comment]
My export software also cannot cope with other than standard tax rate so to have tax codes, preferably lining up with Sage's system would be very helpful.

**Comment by Noodleyman** [comment]
productTax() needs to return the ID from CubeCart_tax_rates, which can then be stored in the order inventory table, and used in joins at the query level to get a tax code defined at the tax rule.

It would also be useful to store the tax code that existed at the time against the inventory, in case the tax rule ever changes and breaks the ID association. perhaps just storing the code would be best.

**Comment by abrookbanks** [comment]
Let me know if this isn't an acceptable solution.

**Comment by Noodleyman** [comment]
the references need to be user defined via admin area so it can be aligned with other systems as needed.
