### ISSUE TITLE
Feature Missing

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#246]
In admin template settings.currency.php, in the groups of statements at 60-65, there are no fields to record the symbol_decimal and symbol_thousand characters.

And most of the lines have the same `id="currency-code"`.

I came across a conversation that indicated some currencies use a space as the thousands separator. But this character needs to be `&nbsp;` so that line wrapping won't happen. This will need to be checked.

**Comment by abrookbanks** [comment]
There were a number of issues fixed here:

* Added decimal symbol, thousand separator & status to add form
* Added legend to fieldset
* Redirect changed to currency list after add instead of empty form
* Whitespace converted to &nbsp; (no matter how many)
* id's fixed on add form
