### ISSUE TITLE
Code Review for Order->setOrderFormat

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2461]
The database table CubeCart_order_summary declares `custom_oid` as DEFAULT NULL.

In `Order->setOrderFormat()`, near line 844, the database will update all records where `custom_oid` currently has a zero length string.

A zero length string is not the same as *null*.

**Comment by bhsmither** [comment]
Unless the **intent** is to fill an **actual blank value** (not the same as *null*) with something -- either the value in the `id` or the `cart_order_id` column.

But I cannot discern what that intent is supposed to accomplish. (The `id` column?)

**Comment by abrookbanks** [comment]
Coincidentally I was looking at this this morning. There are circumstances where the `custom_oid` column can be empty or null. On those grounds it needs to work with either.

**Comment by bhsmither** [comment]
I think this edit does not answer the secondary question of **why use the `Cart_order_summary.id` value** for the `custom_oid` when in Incremental mode where the `custom_oid` column is currently *null* or a *zls*.

Wouldn't it make more sense to use the existing `cart_order_id`?

In admin, Promotional Codes, Gift Cards tab, there is:
```
<td><a href="?_g=orders&action=edit&order_id={$certificate.cart_order_id}">{if $CONFIG.oid_mode=='i'}{$certificate.{$CONFIG.oid_col}}{else}{$certificate.cart_order_id}{/if}</a></td>
```
For example, for orders made before switching over to Incremental mode, the **Order Number** column will contain nonsensical values.

**Comment by abrookbanks** [comment]
Let me know if I missed the boat on this one. I tested this and it seems fine.
