### ISSUE TITLE
CubeCart_order_summary.currency empty

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2462]
Noted after a recent support ticket related to invalid data in the currency field. this field is populated using:

`'currency' => $GLOBALS['session']->get('currency', 'client')`

This does not always have a value, which can lead to an empty string being added into the currency field rather than the actual currency used.  This is causing an issue with site-site integrations for financial transactions since the currency isn't getting passed and it breaks the financials.

Noted happening with the SagePay module as the payment gateway in case that is related.

**Comment by abrookbanks** [comment]
Good find. Thanks.
