### ISSUE TITLE
Other Option Choosers

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2463]
Feature Request:

In the skin template element.product.options.php, the structure is currently:
```
if radio
elseif selector
else (if textbox elseif textarea)
```
To facilitate adding other types of option choosers, request adding after `else`:
```
{else}
{if $OTHER_CHOOSERS}{include file='templates/element.product.other_choosers.php'}{/if}
```
Plugins will populate OTHER_CHOOSERS which will trigger the inclusion.

**Comment by abrookbanks** [comment]
Please ignore commit above. It's for a different issue. Typo on commit.

**Comment by abrookbanks** [comment]
Thanks!
