### ISSUE TITLE
Not removing unavailable matrix items from cart 

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2466]
Should a customer add a MATRIX item to their cart, and between the addition and checkout that item is no longer available the item doesn't get flagged as unavailable and removed. The behaviour should be the same as standard products without options.

in my test case, I disabled/removed the already selected matrix items/options but was still allowed to checkout the unavailable item. 

Assumed it's because they still exist in the matrix table and it's not validating the status

**Comment by bhsmither** [comment]
To clarify: in Store Settings, Stock tab, "Reduce Stock Levels" is set to what choice?

**Comment by Noodleyman** [comment]
in this case it's reducing on order pending.

However, this issue isn't related to ordering the last in stock item. It's related to the admin making changes to the product by disabling options, thus making them unavailable. as a customer with the item already in a basket, or saved card you can still order it. Where as, a standard item (no options or matrix) will tell you the item is no longer available and prevent the purchase.

**Comment by abrookbanks** [comment]
When you say no longer available, have you deleted the product, set the status to disabled or removed the matrix entry?

**Comment by Noodleyman** [comment]
disable an option which makes up a matrix item. (set option status to disabled)

**Comment by abrookbanks** [comment]
Thanks. I'll try it.

**Comment by abrookbanks** [comment]
This was inadvertently fixed with https://github.com/cubecart/v6/commit/cf2b8f8e0ca0be5d12ab9e23368f21564cd4a8a7
