### ISSUE TITLE
Advanced Search - Failing SQL Query #2

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2469]
related to #2468 

catalogue.class.php Line: 1904

`$query = sprintf("SELECT I.*, %2\$s AS Relevance FROM %1\$sCubeCart_inventory AS I LEFT JOIN (SELECT product_id, MAX(price) as price, MAX(sale_price) as sale_price FROM %1\$sCubeCart_pricing_group $group_id GROUP BY product_id) as G ON G.product_id = I.product_id $joinString WHERE I.product_id IN (SELECT product_id FROM `%1\$sCubeCart_category_index` as CI INNER JOIN %1\$sCubeCart_category as C where CI.cat_id = C.cat_id AND C.status = 1) AND I.status = 1 AND (%2\$s) >= %4\$s %3\$s %5\$s %6\$s", $GLOBALS['config']->get('config', 'dbprefix'), $match, $whereString, $match_val, $order_string, $limit);`

evaluates SQL query to be:
```
SELECT
   I.*,
   MATCH (I.product_code, I.description, I.name) AGAINST('1111' IN BOOLEAN MODE) AS Relevance 
FROM
   CubeCart_inventory AS I 
   LEFT JOIN
      (
         SELECT
            product_id,
            MAX(price) as price,
            MAX(sale_price) as sale_price 
         FROM
            CubeCart_pricing_group 
         WHERE
            group_id = 0 
         GROUP BY
            product_id
      )
      as G 
      ON G.product_id = I.product_id 
WHERE
   I.product_id IN 
   (
      SELECT
         product_id 
      FROM
         `CubeCart_category_index` as CI 
         INNER JOIN
            CubeCart_category as C 
      where
         CI.cat_id = C.cat_id 
         AND C.status = 1
   )
   AND I.status = 1 
   AND 
   (
      MATCH (I.product_code, I.description, I.name) AGAINST('1111' IN BOOLEAN MODE)
   )
   >= 0.5 IF (G.product_id IS NULL, IF (I.sale_price = 0, I.price, I.sale_price) >= 0.2, IF (G.sale_price = 0, G.price, G.sale_price) >= 0.2) IF (G.product_id IS NULL, IF (I.sale_price IS NULL 
   OR I.sale_price = 0, I.price, I.sale_price) <= 0.5, IF (G.sale_price IS NULL 
   OR G.sale_price = 0, G.price, G.sale_price) <= 0.5) 
   AND `live_from` < UNIX_TIMESTAMP() 
   AND `live_from` < UNIX_TIMESTAMP() 
ORDER BY
   `Relevance` ASC LIMIT 12 OFFSET 0
```

 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF (G.product_id IS NULL, IF (I.sale_price = 0, I.price, I.sale_price) >= 0.2, I' at line 1

**Comment by bhsmither** [comment]
Perhaps caused by #2320. Maybe fix for Featured to be implemented on price searching (and everywhere else that adds to the `$where` array?
