### ISSUE TITLE
Split shiping into two columns

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#247]
Change "FedEx: Ground" back to "FedEx" and put "Ground" elsewhere.

Do this for v5 too.

**Comment by havenswift-hosting** [comment]
Yes please !  No end of problems caused by this simple change !

**Comment by abrookbanks** [comment]
One particular mod right?

**Comment by havenswift-hosting** [comment]
Yes as discussed with you before - if you can do this for the next V5 release as well please

**Comment by abrookbanks** [comment]
I'd rather set v5 back to how it was.. there are quite a lot of implications around this. Checkout my last code submit. LOTS of changes.
