### ISSUE TITLE
Misleading Error Message

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2475]
In `Cart->discountAdd()`, if the `$order` in which a Gift Card was purchased is not in status 2 or 3, an error message is displayed that says:
"Sorry but that code can't be used against an order of this status."

Considering that the error is displayed against a customer attempting to apply it to their **current** purchase, the phrase is misleading.

Suggest:
"Sorry, but this Gift Certificate is invalid at this time."

**Comment by abrookbanks** [comment]
Thanks!
