### ISSUE TITLE
Update Stated Version of PHP

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2482]
In /setup/index.php, line 257 should match line 258, re PHP version.

**Comment by abrookbanks** [comment]
This was subtly slipped in here already https://github.com/cubecart/v6/commit/d697fbc993726708b1ea7cc6edff5341f22a5058 

Of course you weren't to know especially as no issue was opened. 

Thanks Brian. I hope you had a terrific weekend.

**Comment by bhsmither** [comment]
Sorry, no.
```
From:
      'title' => 'PHP 5.4+ (7.3 Recommended)',
      'status' => version_compare(PHP_VERSION, '5.5', '>='),
To:
      'title' => 'PHP 5.5+ (7.3 Recommended)',
      'status' => version_compare(PHP_VERSION, '5.5', '>='),
```
**PHP 5.5+** in 'title' to match 'status'.
