### ISSUE TITLE
Deprecated Issue #2

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2488]
In `language.class.php`, line 716, using braces for string offsets is deprecated as of PHP 7.4.

See:
https://wiki.php.net/rfc/deprecate_curly_braces_array_access
https://www.php.net/manual/en/migration74.deprecated.php
Seems the actual doc page has not been updated:
https://www.php.net/manual/en/language.types.string.php#language.types.string.substr
"String access and modification by character"

**Comment by bhsmither** [comment]
As well as:
`settings.language.inc.php`, line 116
`products.options.inc.php`, line 55

**Comment by abrookbanks** [comment]
Thanks
