### ISSUE TITLE
PHP 7.4 Issue #3

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2490]
In `catalogue.class.php, line 1317, PHP 7.4 will be issuing notices about accessing variables as if they were arrays, but actually aren't. (1)
```
From:
if (is_array($GLOBALS['cart']->basket['contents'])) {

To:
if (is_array($GLOBALS['cart']->basket) && is_array($GLOBALS['cart']->basket['contents'])) {
```
`basket` might not be an array.

Find in `cart.class.php`, line 1095:
```
if (!empty($this->basket) && isset($this->basket['contents'])) {
```
`basket` might not be empty, but it might also not be an array.

Right now, as of PHP 7.4.3, **Notice** is issued. That may change.

(1) https://wiki.php.net/rfc/notice-for-non-valid-array-container

**Comment by bhsmither** [comment]
Same for `customers.index.inc.php`, line 534. `$smarty_data` comes into existence only if there are enables external modules that are actually present.

If there is an enabled external module but that folder does not exist, PHP 7.4 will issue a Notice about `$smarty_data['customers_export_list']` saying 'Array access on null'.

Suggest line 331 (blank):
```
$smarty_data = []; // Issue #2490
```

**Comment by bhsmither** [comment]
And cubecart.class.php, line 2302.

**Comment by bhsmither** [comment]
And catalogue.class.php, near line 1374, where `$products_matrix` could be false, causing complaints about the next line.

Suggest wrapping `$products_matrix` in an `if((expression)!==false)` test and the following six lines in the true block.

**Comment by abrookbanks** [comment]
Thanks for this. I think it's best however to define an array like;
```
$array = array();
```
