### ISSUE TITLE
SQL Query - SQL_CALC_FOUND_ROWScauses performance problems

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2493]
I've started to log and address poor performing SQL queries, I am seeing an issue where SQL_CALC_FOUND_ROWS is used, as this causes index avoidance and unnecessary data to be reviewed, thus adds a significant overhead. Take this example:

Note. I do not necessarily consider this a "problem", but I do see it in the wild causing slow downs, should be a simple change and could unlock some reasonable performance improvements for little effort. 

```
SELECT
   SQL_CALC_FOUND_ROWS CubeCart_order_summary.*,
   CubeCart_customer.type,
   CONCAT(CubeCart_order_summary.last_name, CubeCart_order_summary.first_name) AS `customer`,
   CubeCart_order_summary.status 
FROM
   `CubeCart_order_summary` 
   LEFT JOIN
      `CubeCart_customer` 
      ON CubeCart_order_summary.customer_id = CubeCart_customer.customer_id 
ORDER BY
   `order_date` DESC LIMIT 20 OFFSET 0;
```
![image](https://user-images.githubusercontent.com/10614018/76519045-23dff180-6458-11ea-8397-43d162aefc88.png)

run time - 4.7 seconds

Removing calc rows from the selection

```
SELECT
   CubeCart_order_summary.*,
   CubeCart_customer.type,
   CONCAT(CubeCart_order_summary.last_name, CubeCart_order_summary.first_name) AS `customer`,
   CubeCart_order_summary.status 
FROM
   `CubeCart_order_summary` 
   LEFT JOIN
      `CubeCart_customer` 
      ON CubeCart_order_summary.customer_id = CubeCart_customer.customer_id 
ORDER BY
   `order_date` DESC LIMIT 20 OFFSET 0;
```
![image](https://user-images.githubusercontent.com/10614018/76519136-54c02680-6458-11ea-8823-bc62867e700c.png)

Run time, 0.0015 seconds.

Also, note in this SQL query that the status column is being returned twice, once by the select all, and again explicitly. 

Reworking the query to get the count...
```
select count(1) from (
SELECT
   CubeCart_order_summary.*,
   CubeCart_customer.type,
   CONCAT(CubeCart_order_summary.last_name, CubeCart_order_summary.first_name) AS `customer`,
   --CubeCart_order_summary.status 
FROM
   `CubeCart_order_summary` 
   LEFT JOIN
      `CubeCart_customer` 
      ON CubeCart_order_summary.customer_id = CubeCart_customer.customer_id 
ORDER BY
   `order_date` DESC LIMIT 20 OFFSET 0) a
```

same result, a record count but with a 0.0001 second execution time. 

There seems to be room for a significant improvement, and I would recommend dropping the use of SQL_CALC_FOUND_ROWS where possible and use  alternate methods.

**Comment by havenswift-hosting** [comment]
SQL_CALC_FOUND_ROWS is well known for causing significant performance issues especially on larger tables and I raised it several years ago and agree that a rework would be very helpful.  Also note that while not an immediate issue as most people arent even using MySQL 5.7 yet, SQL_CALC_FOUND_ROWS is deprecated in V 8.0 and will be removed quickly after that

**Comment by Noodleyman** [comment]
It's only called in two locations within CubeCart.

catalogue.class,
database.class

one being a manual query, one being automated as part of the DB class. a rework of the select() function could solve this entirely, thus minimal effort, potentially a vast boost in performance

**Comment by bhsmither** [comment]
Is `select count(1)` returning how many rows are in the SELECT statement enclosed in parenthesis? If so, my experiment shows a result of 20. (My dev server has 140 rows in this table.)

So, asking for a count of a `LIMIT 20` recordset is asking for the wrong thing.

CubeCart has used a procedure of sending a follow-on query without the SORT, LIMIT, and OFFSET parts, and having PHP count the number of array elements in the result. *That*, we need to identify and move away from.

This MySQL Docs page :
```
https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_found-rows
```
suggests having the database perform the same query, without limits, the way some places in CubeCart still do (where `DB->select()` cannot be used) but return the count -- thus saving transporting large recordsets of needless data.

So, try the reworked query without SORT, LIMIT, and OFFSET components.

**Comment by abrookbanks** [comment]
Thanks for all your input.
