### ISSUE TITLE
Customers sorted by orders gives incorrect result

### ISSUE THREAD

**Issue by bos4711** [cubecart/v6#2494]
In the admin interface, I click "Customers", then column "Orders", then column "Orders" once again. Expected result here is to see the list of customers sorted by descending amount of orders. Actual result is that I see my test user, with 0 orders, appearing in this list.

Reproducable every time.

CubeCart Version
    6.2.8 
PHP Version (7.2 Recommended)
    7.3.15
MySQL Version
    5.5.5-10.3.21-MariaDB-1:10.3.21+maria~bionic

NB: This issue could be related to #887 (marked as fixed in 2015).

![customer_sorting](https://user-images.githubusercontent.com/11036018/76534149-6239d880-6479-11ea-8333-be0ca9ddc592.png)

**Comment by abrookbanks** [comment]
This may be due to old data issues looking at the dates in the customers accounts.
