### ISSUE TITLE
Bad Argument for Loop

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2497]
In `settings.index.inc.php`, it is possible that the foreach argument `$fields_find` at line 58 may not exist if:
* Store Settings set Incremental Order Mode
* Database fails to honor TRIGGER permissions (that is, `$oid_data` is false-like)

FYI: I installed MariaDB and did not switch off the binary log. I got:

> You do not have the SUPER Privilege and Binary Logging is Enabled

http://wiki.ispirer.com/sqlways/troubleshooting-guide/mysql/import/binary-logging

**Comment by abrookbanks** [comment]
Surely it will always have a value from the else statement off the back of;

`if ($_POST['config']['oid_mode']=='i') {`

**Comment by bhsmither** [comment]
The first condition above hits the 'true' part of the mentioned `if` block. The `else` part is moot.

The second condition above hits the 'true' part of the
```
if (!$oid_data) {
```
block. The `else` part is moot.
