### ISSUE TITLE
Code Review for Debug Class

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2498]
All information I have been reading states that, other than PHP's built-in error handler, there can be only one custom error-handler in a running script.

I see that Smarty registers an error handler, then the Debug class registers its error handler -- knocking out Smarty's.

This **may** explain why template coding errors, almost always, do not show up in PHP's error_log file (if enabled).

But because there are two actors setting their respective error handler, I will be tracing this out more comprehensively.

**Comment by bhsmither** [comment]
Oops! My bad. (I was experimenting...)

Debug comes first and Smarty takes note of it. Then clobbers it.

Still tracing it out (the correct code) as explained above.

**Comment by bhsmither** [comment]
Explaining Smarty template coding errors involves the fact that Smarty throws exceptions, and it is up to the package that uses Smarty to deal with it.

The Debug class has an exception handler, and does cause a message to be written to the database.

However, I would like to see the Debug exception handler create an Error (trigger_error), but the `Debug->errorLogger()`, `$error_no` argument, is expecting an integer. (There is a case for the string 'EXCEPTION'.)

Now, the function's `$error_no` can accept a string, but only if called directly - it will be an integer when catching errors.

The ultimate goal, again, is to get Smarty exceptions logged in PHP's error_log file.

**Comment by bhsmither** [comment]
This is what I did:
```
From:
    public function exceptionHandler($e)
    {
        $message = "[<strong>Exception</strong>] \t".$e->getFile().":".$e->getLine()." - ".$e->getMessage();
        $this->_errors[] = $message;
        $this->_writeErrorLog($message, 'Exception');
    }

To:
    public function exceptionHandler($e)
    {
        $message = "[<strong>Exception</strong>] \t".$e->getFile().":".$e->getLine()." - ".$e->getMessage();
        trigger_error($message,E_USER_ERROR);
//        $this->_errors[] = $message;
//        $this->_writeErrorLog($message, 'Exception');
    }
```
This gets me an entry in PHP's **error_log**:
```
[22-Mar-2020 11:44:02 America/Los_Angeles] PHP Fatal error:  [<strong>Exception</strong>]
/includes/lib/smarty/sysplugins/smarty_internal_templatecompilerbase.php:24
- Syntax error in template "file:/skins/foundation/templates/content.homepage.php"  on line 24
"<form action="{$VAL_SELF}" method="post" class="panel add_to_basket">"
- Unexpected "<" in /classes/debug.class.php on line 482
```
There is info here that makes interpreting the fault message confusing, unless one knows what to specifically look for.

With some *regex* on the message, it could be cleaned up: drop the location that threw the exception, drop the location that called `trigger_error()` - but only for Smarty-thrown exceptions.

**Comment by abrookbanks** [comment]
I don't know what to do here other than to take lessons from this for future development. To date I've never not been able to debug a CubeCart syntax error and clearly this comes under core structural flaws that fall into major version territory.
