### ISSUE TITLE
$SKIN_SUBSET caching issue in Foundation skin

### ISSUE THREAD

**Issue by NiteTowerDesign** [cubecart/v6#2499]
I recently ran in to a bug with one of my skins relating to the skin changer feature which got inherited from the Foundation skin.

The Foundation skin checks for $SKIN_SUBSET in element.css.php and adds it to the $css_input[] array which caches the style if caching is enabled. Now this isn't a problem by default as Foundation has no subset styles but for anyone who follows foundations core coding structure and adds multiple styles it disables the skin changer when caching is enabled as the default style of the selected skin is cached as is always used.

Easy fix is to remove it from the css_input array so it any subset style doesn't get cached or more complex fix would be to cache each subset style separately and call the cache file based on current selected style. 

At least that is my take on the issue so correct me if i am wrong haha

**Comment by bhsmither** [comment]
Suggest in `element.css.php`, near line 15:
```
From:
{combine input=$css_input output='cache/css.{$SKIN_FOLDER}.css' age='604800' debug=$CONFIG.debug||!$CONFIG.cache}
To:
{combine input=$css_input output='cache/css.{$SKIN_FOLDER}{$SKIN_SUBSET}.css' age='604800' debug=$CONFIG.debug||!$CONFIG.cache}
```

**Comment by abrookbanks** [comment]
I'm not 100% following. Is there a bug that needs changing?

**Comment by bhsmither** [comment]
Yes.

Customize a Foundation skin by adding a sub-style (requisite folders, files, and changes to config.xml) -- for example, "red".

Now there is the 'default' and 'red' sub-styles.

Note: have **debug disabled**, and have **caching enabled**.

Take note that the CSS combined file in the cache is named "css.foundation.css".

When the customer (if allowed) switches the skin to "Foundation|Red", the existing cached CSS file is given to the skin template because there is no distinction in the filename that specifies a sub-style.

**Comment by abrookbanks** [comment]
Thanks for the clarification. :)

**Comment by cb2004** [comment]
Stepping back into the community after many years here, been a while. Isn't customers changing skin a bit before dinosaurs? I am all for fixing bugs but not maintaining what a large percentage dont use

**Comment by bhsmither** [comment]
Please keep in mind the sub-styles are CSS-based.

As such, please be aware that CSS can change **much more** than just a color pallet.

If a website has a small amount of clientele, out of compassion or legal requirement, that should/must be catered to, providing a means for that clientele to choose their preferred skin is incredibly important.

A sub-skin could accomplish: (intelligent) large-print, larger-print, high-contrast, reverse color, monochromatic, intelligent layouts conducive to screen magnifiers and screen readers.

**Comment by cb2004** [comment]
I agree that could be a use case, but accessibility wise, desktop software handles this better. I can't remember the last time I visited an ecommerce site that gave me options to change appearance. I can remember the last time I saw something about cookies :)

**Comment by havenswift-hosting** [comment]
It is functionality that already exists and so any bug found should be fixed.  I agree that there are few cases where I would consider or recommend a user allows visitors to change the skin but the feature is very useful on a developer's demo site when allowing visitors to preview a number of different skins to compare and contrast and also useful to the developers themselves to switch back and forth
