### ISSUE TITLE
Make memcache session caching optional

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2501]
If a site uses memcache / memcached for normal caching, it now automatically uses it for session handling as well - it is very important that this should be optional - ideally giving a choice of other methods but initially allowing file session handling

**Comment by abrookbanks** [comment]
Why? It works very well.

**Comment by havenswift-hosting** [comment]
> Why? It works very well.

Everything works well until it doesnt - and there could be any number of reasons for that

Every other package configures caching, session management and where available, FPC separately with each being able to be enabled or use different methods and just offers flexibility.

For example, in CC, if you are using memcached for caching and disable caching,  session management still uses memcached and the only way of stopping that is switching the caching method to file

Also seen several examples on different sites / servers where there are problems with session management (session_start) with problems such as being unable to clear session lock records or where it has failed to read session data

**Comment by havenswift-hosting** [comment]
Any chance of getting this into the next version as still seeing problems with multiple sites with session management using memcached.  Current CubeCart coding forces session management to be memcached in standard caching uses that

**Comment by abrookbanks** [comment]
Note added to https://support.cubecart.com/hc/en-gb/articles/360003831737-How-do-I-enable-APC-Memcached-Redis-or-xCache-

**Comment by havenswift-hosting** [comment]
Many thanks Al !  Any ideas on what is causing the odd problems with session management when using memcached ?  Would much prefer to use memcached for sessions but for some sites, the problems seem worse than others, so much so that have to switch off memcached completely - we had exchanged some emails about this previously for reference

**Comment by abrookbanks** [comment]
The only issue I have found is that on submit whilst editing a product it in rare occasions logs the admin user out. Can you remind me of your findings?

**Comment by havenswift-hosting** [comment]
That is the issue but for some sites it is not just rare occasions and makes product editing impossible as logging out (and not saving the changes) happens 75% or more of the time
