### ISSUE TITLE
BUG: Gift Certificate product code

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2502]
If the product code of a gift certificate happens to be numeric, and by chance happens to match an existing product_id in CubeCart_inventory, when you try to buy a gift certificate the product with  matching ID is added to the cart instead making it impossible to purchase the gift card.

**Comment by havenswift-hosting** [comment]
That's a novel solution !

However, the message displayed should say "Gift Certificate code can not be numeric." instead of "Product....."

**Comment by Noodleyman** [comment]
Also needs to fix any existing codes that meet the criteria on update

**Comment by abrookbanks** [comment]
> Gift Certificate code can not be numeric

It's the product code field so message makes sense.

**Comment by abrookbanks** [comment]
Updated product code on upgrade
