### ISSUE TITLE
the stock_level value in the $product array should be a single value

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2504]
When using options, the stock level can return a range, for example 0 - 2. This field should only ever return a single number and be the stock level value from the inventory table. A new field should be added to hold stock level ranges. 

This is causing a problem with some modules, because the range is treated as math. "0 - 2 = -2", which makes the stock level evaluations incorrect.

**Comment by bhsmither** [comment]
Interesting that the value of a string variable is being eval'd.

But this is interesting:
```
http://docs.php.net/manual/en/language.types.string.php#111522
```
It suggests that when casting that string to an integer, the leading zero is ignored (discarded), and the remaining character sequence is valid for a negated integer.

I wonder what the string "3-6" shows up as in your code.

**Comment by Noodleyman** [comment]
I'll have to test it, I suspect you are correct. Ideally, multiple values should each have their own element in the array rather than combined.

it's a simple evaluation of the stock level v's a value. for example, 

if($product['stock_level'] >= 1){
// in stock 
}else{
// out of stock (if stock control is enabled)
}

however, given the 0-2 (thus negative 2), it's out of stock.

**Comment by abrookbanks** [comment]
Why should it be a single value and if so which (or an average)? Do we think it should always take the min value > 0?

Can you explode if there is hyphen and then wrong from max/min?

**Comment by abrookbanks** [comment]
Not sure I used the best summary wording there.🧐
