### ISSUE TITLE
Code Review: UPDATE Query

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2506]
In `User->addOrder()`, the query is updating the user's order count using `DATABASE->misc()` without setting the `cache` parameter to false.

Assuming this then causes `MySQLi->_execute()` to cache the query and result, which is not an array.

Thus, in the `if ($cache_check)` blocks, the PHP function `sizeof()` faults.

Examining the query in `addOrder()`, I believe using the `Database->update()` function will work.

**Comment by abrookbanks** [comment]
Cache disabled but keeping misc which works ok.
