### ISSUE TITLE
Code Review: What Makes a Product Digital?

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2507]
With respect to `products.index.inc.php`, near line 84, the question is:

Would the presence of a value in `digital_path` be all that is required to declare the product as being digital? That is, regardless of `digital` being empty. (Maintaining that something in `digital` also declares the product as being digital.)

If so, this answers the criticism that flagging `digital` with 1 collides with 1 being a FileManager's file_id - when not an image. 

(I'm working on a fork that will allow for multiple digital files per product.)

**Comment by bhsmither** [comment]
Suggest making CubeCart_inventory.digital a SIGNED INT, and using -1 as the flag to indicate this being digital -- that having no companion file in the FileManager. Still can use zero as a reset flag -- not digital.

**Comment by abrookbanks** [comment]
I see where you are coming from as a best practice situation but digital_path always takes president over the numeric value assigned to the digital column. On those grounds as much as this is a bit ugly it should be safe and (touching wood) to date it has been. *I think*
