### ISSUE TITLE
Register/New Customer cart form: jquery.validation failing on ajax call

### ISSUE THREAD

**Issue by mapsedge** [cubecart/v6#2508]
CubeCart v6
Windows Server 2012, IIS 10
Chrome 80.0.3987.149 , Firefox 74.0.1, on Windows 10

jQuery.validation appears to add elements to a stack, then performs an ajax call for server-side validations, specifically email in this instance (about line 1538 in ver.1.17). It appears to be designed such that the form is submitted when the stack is emptied by the **success** method. 

When the ajax call is done, the success method should be called to decrement the stack, but it is not, and so the form never submits. I can duplicate this issue at will.

The dataType parameter can be set to text which allows the Register form to work, but the email validation then fails on the New Customer Checkout form.

The only fix I've found for it is to change the success method to  **complete** (using response.responseText instead of just response). I'm only writing here because I'm not sure what the ramifications are.

**Comment by abrookbanks** [comment]
Thanks for the technical report but can you give basic steps to reproduce this issue?

There are no known issues with any of the form validation with the most recent release and default skin. This isn't an issue I have been able to reproduce.

**Comment by abrookbanks** [comment]
I will reopen once we have more info.
