### ISSUE TITLE
Language Editor Tweaks

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2509]
Because the language phrase edit text entry boxes are 'disabled' until clicked on, and it will not recognize being clicked on when disabled...

Suggest removing the `title` attribute from the textbox/textarea form element, and then adding an edit icon just to the immediate left of the text entry field, with a `title` attribute saying "Click to edit".

**Comment by bhsmither** [comment]
Or, using the `span class="editable">` idea.

**Comment by abrookbanks** [comment]
I can't see the reason for this suggestion. For me I see a list of text fields that can be edited like any other. 

Added cursor: text to each text field however to make it more obviously. Happy to reopen if I've missed the point. Maybe is specific to a certain browser.
