### ISSUE TITLE
Error log is impossible to read when messages are long

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2511]
Ref https://github.com/cubecart/v6/issues/2484

Same issue with error log especially with smarty errors

**Comment by abrookbanks** [comment]
Have you got a screenshot? From what I see they wrap nicely.

**Comment by abrookbanks** [comment]
Sorry I can't reproduce this.
![Untitled](https://user-images.githubusercontent.com/4520803/80075763-1af83a80-8543-11ea-8ba1-80fcf7b9b8dd.png)

**Comment by abrookbanks** [comment]
I will reopen with further info. Thanks Ian.
