### ISSUE TITLE
Stock Level Incorrect Order->_manageStock Processing

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2514]
I see a potential issue - but not yet verified.

For an order currently at Pending, if the **store settings** say to decrease stock when the order goes to Processing or Completed, yet the currently Pending order is then Declined, Failed, or (especially) Cancelled, the stock level is increased without having first been decreased.

See #1960.

**Comment by bhsmither** [comment]
Oh, wait. I now see that a test is made to determine if the stock level has already been updated via a previous process. If not, no adjustment is performed.

**Comment by abrookbanks** [comment]
It looks like this can be closed. Please let me know if not.
