### ISSUE TITLE
Admin Product List for Digital Item Stock May Be Misleading

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2516]
Set a digital product to `Use Stock Level:checked` and `Stock Level:0`. (Clear Cache.)

Verify storefront indicates the digital product is Out of Stock.

View admin's Product Inventory main list.

Note that the stock column for the digital item shows infinity.

In products.index.inc.php, near line 1220, there is this:
```
if ($result['use_stock_level'] == 0 || $result['digital'] > 0 || !empty($result['digital_path'])) {
```
Considering `Catalogue->getProductStock()` respects 'use_stock_level' even for digital products, suggest the test in admin be modified such that:
```
(!use_stock_level OR digital OR dpath) AND !(use_stock_level AND (digital OR dpath))
```
This makes the test fail if using stock levels even though it is digital.

**Comment by abrookbanks** [comment]
Works beautifully. Thank you.
