### ISSUE TITLE
Missing Data Item for Template - (bool) Discount

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2517]
In the template `content.receipt.php`, lines 110-116 provide for showing the total of the discounts applied to the order.

Yet, in `CubeCart->_complete()`, there is no code that assigns anything to $DISCOUNT.

Thus, the customer is not reminded of whether any coupon or GC had been applied resulting in what seems like a miscalculation in the figures shown.

Suggest adding a banner message within code that tests for the order status not being 2 or 3 saying the coupon or GC has not (did not) get consumed.

**Comment by abrookbanks** [comment]
> Suggest adding a banner message within code that tests for the order status not being 2 or 3 saying the coupon or GC has not (did not) get consumed.

I don't see why when we can just add the logic to assign `$DISCOUNT`?

**Comment by bhsmither** [comment]
Some people, **if they over-think it**, may worry that their coupon or GC submission has been 'consumed'.

Maybe a mention of the balance of a GC once CubeCart knows about it, having it in the basket?

**Comment by abrookbanks** [comment]
That would be cool as a feature request. There should be a section to show balance and usage in their account profile.
