### ISSUE TITLE
Coupon and GC Codes to be UTF-8 Capable

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2519]
Feature Request:

For our non-English speaking users, request that GC and Coupon codes using UTF-8 characters survive the `preg_replace()` near line 55 in `products.coupons.inc.php`.

(I have not tested this.)

See:
https://www.php.net/manual/en/function.preg-replace.php#106981
https://www.php.net/manual/en/reference.pcre.pattern.modifiers.php#103348

**Comment by abrookbanks** [comment]
Thanks Brian.
