### ISSUE TITLE
Square Extension - Google pay and Apple Pay button not showing.

### ISSUE THREAD

**Issue by Josh707** [cubecart/v6#2520]
Hello I am new to using Cube Cart still, I have set up the Square payment gateway extension, I tested it out by going to the storefront of my website, I went to order something, but the Apple Pay and Google Pay buttons are not showing, how can I fix this?

Thanks
Josh

![2F1BD262-8304-4E77-8A16-E13991C01631](https://user-images.githubusercontent.com/64953408/81270833-a5d24c80-908e-11ea-9692-30d02dc9d355.png)

**Comment by abrookbanks** [comment]
Odd. It looks like there may just be a CSS clash.

**Comment by Josh707** [comment]
The Square payment by card didn’t work either when I tested it, towards the end after I entered card details and it came up with some error when I wanted to go ahead, anyway for now PayPal will do.

**Comment by dieseld23** [comment]
I'm having the same issues as above.

**Comment by abrookbanks** [comment]
Can one of you please contact support@cubecart.com and provide access to your server so I can investigate for you? I will then get this fixed and release a patch.

**Comment by abrookbanks** [comment]
Closed due to lack of feedback.
