### ISSUE TITLE
ACE Editor Tweak

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2522]
Regarding the offset-ness of the text insertion cursor with respect to the actual text, here is a tweak to fix it:
```
<div id="php_code" style="text-indent:0!important"></div>
```
There is interference caused by layout.css near line 517:
```
.tb-form fieldset > div, div.tab_content fieldset > div { text-indent: 5px }
```

Also, suggest:
```
            editor.session.setUseWrapMode(true);
            editor.setOptions({
                highlightActiveLine: true,
                showPrintMargin: false,
                theme: 'ace/theme/github',
                mode: 'ace/mode/php'
            });
```
The above will enable wrap mode correctly. Otherwise: `misspelled option "useWrapMode"`.

Also, suggest upgrading to ACE 1.4.10 -- but so far, haven't noticed any changes that make the upgrade worthwhile.

Note: The following can display diffs -- compare the original snippet with editing a version in progress???

I tried to get Monaco installed, but failed. Maybe you can do better?
https://microsoft.github.io/monaco-editor/index.html
https://github.com/Microsoft/monaco-editor

I will be looking at CodeMirror.
https://codemirror.net/index.html

**Comment by bhsmither** [comment]
I just found `#php_code{}` in layout.css, near line 1166. Maybe add the new declaration there.

Also, I finally got Monaco (mostly) working. There is some interference with a rule(s) in layout.css that I am tracking down now.

**Comment by bhsmither** [comment]
Regarding Monaco, see:
`https://github.com/microsoft/monaco-editor/issues/1916`

The problem is the same with CubeCart with respect to setting all `tab_content` with `display:none`.  Then having javascript showing one of them on `$(document).ready()`.

**Comment by abrookbanks** [comment]
Thank you that has bugged me for a LONG time.
