### ISSUE TITLE
Feature request : admin option to clear sessions

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2524]
It would be great to have a feature to clear sessions both within the CubeCart table and also the corresponding session file.

A small admin option under maintenance to clear all and also to be able to select by IP address

**Comment by abrookbanks** [comment]
I think this is a good idea but it would be interesting to know why?

**Comment by abrookbanks** [comment]
This is more complex than first thought. Isn't everything?!

**Comment by havenswift-hosting** [comment]
What is the complexity ?

**Comment by abrookbanks** [comment]
Complexity as in we can't clear the local PHP session files due to permissions. Garbage collection will need to remove those.

**Comment by havenswift-hosting** [comment]
Whether you can clear PHP session files will depend on where they are stored (/tmp, another default directory all together with other users or a custom path in user account) and with what permissions (depends on location, PHP handler used etc) and also how they are stored (memcached for example will have different rules)

Does the code as it is attempt to delete the local PHP file and detect whether they can or cant be deleted ?

From what I can see, this also only provides a method to clear all session files and not for specific IP address which is extremely useful when doing testing so is probably more a developers tool

**Comment by havenswift-hosting** [comment]
Would be nice to revisit this at some stage ?
