### ISSUE TITLE
tax_type DB discrepency

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2527]
this can cause issues when working with tax data.

CubeCart_inventory.tax_type allows NULL
CubeCart_pricing_group.tax_type does not allow NULL.

can cause issues when balancing data between inventory and customer group prices if NULL is encountered. the definitions should be the same.

**Comment by abrookbanks** [comment]
Same as in NULL not NOT NULL? I don't know what you mean by balancing data.

**Comment by Noodleyman** [comment]
custom processes can sync prices/data for customer groups as CubeCart only populates it as/when you hit a save button on the product page.  but, you can't insert a NULL value (from inventory) into a NOT NULL field, so it will error the queries. I worked around it, but would be nice to have the price fields defined the same.
