### ISSUE TITLE
Square Extension - API only accepts Integers

### ISSUE THREAD

**Issue by adam12** [cubecart/v6#2529]
I emailed this to the sales@ address as I did the last patch for the Square extension and then followed up, but presuming it was lost.

Force value to be cast as Integer, because occasionally a random floating point will cause Square to fail. I've been using this for many months now without issue. 

Fixes the error message `Expected an integer value` received from Square.

```diff
diff --git a/gateway.class.php b/gateway.class.php
index 8b81aca..f3cb300 100644
--- a/gateway.class.php
+++ b/gateway.class.php
@@ -84,7 +84,7 @@ class Gateway {
 		$request_body = array (
 			"card_nonce" => $nonce,
 			"amount_money" => array (
-				"amount" => $this->_basket['total']*100,
+				"amount" => (int)$this->_basket['total']*100,
 				"currency" => $GLOBALS['config']->get('config', 'default_currency')
 			),
 			"delay_capture" => (bool)$this->_module['auth'],
```

**Comment by abrookbanks** [comment]
Thank you. This has been fixed with 1.1.5.
