### ISSUE TITLE
CubeCart Forums Archiving Current Threads

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2533]
Relates to the CubeCart Forums:

This module:
```
https://www.cubecart.com/extensions/plugins/order-fulfilment-line-item-tracking
```
is still active.

However, the conversation that discusses it is in an 'archived' status:
```
https://forums.cubecart.com/forum/69-extension-discussion/?page=4
https://forums.cubecart.com/topic/53645-order-fulfilment-line-item-tracking/
```
This is an example of a general condition.

**Comment by abrookbanks** [comment]
I've excluded that forum from archiving. It should sort itself out.
