### ISSUE TITLE
Stripe Form Template CSS

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2534]
Trivial:
The CSS in `form.tpl` has special effects for `#card-button span`, but there is no span descendant for `#card-button`.

Also, suggest not using `<label>` as some skins have their own rules that will affect the display of that content. Maybe use a `<p>` tag, or an `!important` class to override.

**Comment by abrookbanks** [comment]
The span does actually get put into the button on successful submit. The then animates ... to deter the customer from clicking more than once. This seems to work.

`label `replaced with `h3` which pads better too.
