### ISSUE TITLE
Code Review: Database->where() ORs and ANDs

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2536]
For example:
```
$whereArray = array(
  '~TESA1 => array('name', 'product_code'),
  'cat_id' => 1
)
```
should result in:
```
WHERE name LIKE '%TESA1%' OR product_code LIKE '%TESA1%' AND cat_id = 1
```
Because of the order of operations, this could return TESA1 found in name irrespective of cat_id.

Please experiment with putting parentheses around `implode(' OR ', $or)`.

**Comment by abrookbanks** [comment]
Issue reproduced and fixed. End result is good.
