### ISSUE TITLE
Code has changed for Zendesk chat - moved from Zopim

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2538]
The key & code format for using their inline chat has changed and the current module no longer works

For example the code that needs embedding is

``

<script id="ze-snippet" src="https://static.zdassets.com/ekr/snippet.js?key=XXXXXXXXXX"> </script>

``

**Comment by abrookbanks** [comment]
As a customer the dashboard still shows me the old code. Is that where you see it? Maybe I'm on a legacy version still. 

![Untitled](https://user-images.githubusercontent.com/4520803/85005704-128e3b80-b151-11ea-9028-8721787815cd.png)

**Comment by havenswift-hosting** [comment]
Yes exactly !  New accounts have completely different login url for the dashboard and use new embedded code.  Legacy accounts still work as well so either needs option or two plugins

**Comment by abrookbanks** [comment]
Ah I see. Thanks. :)

**Comment by havenswift-hosting** [comment]
Any ideas about this ?

**Comment by abrookbanks** [comment]
Fixed with 2.0.0 just now. Just upload and it will convert old zopim accounts to html or allow html to be entered for widget code.
