### ISSUE TITLE
$words regex strips hyphens when searching

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2542]
catalogue.class.php

`$words = preg_replace('/[^\p{Greek}a-zA-Z0-9\s]+/u', '', $search_data['keywords']);`

If searching for product code which can contain a hyphen you won't get a match as the hyphen is stripped.

recommending this be modified to:
`$words = preg_replace('/[^\p{Greek}a-zA-Z0-9\-\s]+/u', '', $search_data['keywords']);`

which allows hyphens.

**Comment by abrookbanks** [comment]
Thanks!!! :)
