### ISSUE TITLE
Only allow webp upload if GD can handle it

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2543]
`Call to undefined function imagecreatefromwebp()` in some OS.

**Comment by abrookbanks** [comment]
Decided against this. Server changes happen regularly. GD issues can come and go.

**Comment by Noodleyman** [comment]
@abrookbanks , can this be revisited if possible? I've seen this happen a few times and it can take a store offline entirely until the image is removed manually. Adding a check may prevent some pain for customers and better improve the stability of CubeCart.

**Comment by abrookbanks** [comment]
It's not because the current version accidentally has a webp image in the image source folder is it? *facepalm* (directed at me)

**Comment by Noodleyman** [comment]
not on this occasion.. :) issue was from an older version and somebody uploaded a webp image

**Comment by abrookbanks** [comment]
I'm not sure what improvements can be made? I'll have a look at the logic as if this only works on upload maybe a check needs to be made on db build.

**Comment by Noodleyman** [comment]
I'm not sure either. other than a quick hunt on here today to see if it's a known issue, I've not done a technical deep dive into it. but, if something could be added it should help reduce issues in the future. :)

**Comment by abrookbanks** [comment]
Ok cool. I'll checkout the logic. Thanks Alec. I hope lockdown life is treating you well.

**Comment by Noodleyman** [comment]
keep forgetting we're in a lockdown... I'm like that guy who lives in the woods and doesn't see anybody for years, emerges once every few years for supplies then back to the cave. but yea, all good thx.

**Comment by abrookbanks** [comment]
Sounds like my kind of heaven!!

**Comment by Noodleyman** [comment]
I'm pretty much prepped for the end of days given how remote we live.. so ya know. not much changed for us. we're really quite lucky

**Comment by abrookbanks** [comment]
Firewood, cider, nettle soup. Sorted.

**Comment by abrookbanks** [comment]
I don't think this is relevant anymore since https://github.com/cubecart/v6/issues/2948
