### ISSUE TITLE
Admin permissions

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2545]
Looking at setting up an admin with restricted access to Orders and (as I very rarely use the permissions functionality) a couple of things have popped up

1) Is it possible to restrict the menu options that are displayed to those ones that they have some access to ie in this case it should only be Orders

2) Why would an admin user with RW access to Orders have access to transactions logs ?  Maybe it is the best place of those available but I think it should be in a separate area of access such as other reports.

3) The new admin user is required for warehouse staff to see current Processing orders, print off the "Invoice" (which can be done from the main screen) but they need full order edit access to be able to change the order status from Processing to Completed.  This however also gives them access to completely change the order - anything that can be done about this ?

**Comment by abrookbanks** [comment]
I'm going to close this for now as a feature request. It needs a complete overhaul TBH. Probably major version rethink.
