### ISSUE TITLE
Code Review: Catalogue->defineOptionsIdentifier()

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2546]
Trivial and inconsequential, but...

Currently, a SQL statement is constructed and then sent to `DB->query()`. There is the possibility nothing will be returned.

`DB->query()` will always return an array, including an empty array, unless there was an actual fault.

When building the `$options_identifier_string`, a test is made against the returned recordset, `is_array()`.

This test will always be true and causes unnecessary work - here and at `Catalogue->getProductData()` where the `$options_identifier` is the MD5 of a zero-length string.

Unless there is an actual desire for this to be this way, suggest either: using `DB->select()` (the `$where` can be a string) in the `if!==false` style, or `if(!empty($option_identifiers)&&is_array($option_identifiers))`.

**Comment by abrookbanks** [comment]
Thanks. I took the safest option.
