### ISSUE TITLE
Code Review: Determining Required Options

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2547]
In `Cart->add()` when adding options to the basket item (near line 351), a query is made for a specific `option_id`.

This query was already made in `Catalogue->getOptionRequired()` near line 988, from `Cart->__construct()` near line 145.

However, the queries are worded slightly different although being exactly the same.

Suggest ordering the columns requested be `'option_type','option_required'` for both instances.

This allows the cache to be used. (Although both variants of the query will eventually get cached.)

**Comment by abrookbanks** [comment]
You have a keen eye! :) Thanks for this.
