### ISSUE TITLE
Memcached clear is too aggressive

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2549]
Clearing cache in one store will delete for all stores

**Comment by abrookbanks** [comment]
Also applies to memcache, redis and xcache.

**Comment by abrookbanks** [comment]
This could relate to bugs around https://github.com/cubecart/v6/issues/2501

**Comment by havenswift-hosting** [comment]
This is a pretty major bug and would explain why we have always seen massively more REDIS and memcached usage than would be expected and https://github.com/cubecart/v6/issues/2501 has meant that we couldnt upgrade any more sites to 6.2.9 (those we had already done, we had to revert to file caching) as we have a large number of sites using memcached across a number of servers and 6.2.9 was unusable

Can 6.2.10 be released soon and can the options requested in https://github.com/cubecart/v6/issues/2501 still be considered

**Comment by abrookbanks** [comment]
asap

**Comment by havenswift-hosting** [comment]
Thanks !

**Comment by abrookbanks** [comment]
I might roll the memcached changes out on hosted.cubecart.com to see how we get on. I think every store is on the latest version.
