### ISSUE TITLE
SameSite attribute - consideration required. 

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2556]
The following attribute isn't defined.. 

A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.

####

Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute
Because a cookie's SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which will prevent the cookie from being sent in a cross-site request in a future version of the browser. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery.

Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie should be sent in cross-site requests. This enables third-party use.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be sent in cross-site requests

**Comment by abrookbanks** [comment]
Sounds like we need SameSite=strict .

**Comment by abrookbanks** [comment]
Might need to fork the cookie JS
https://github.com/carhartl/jquery-cookie/blob/master/src/jquery.cookie.js#L67-L73

**Comment by abrookbanks** [comment]
> Sounds like we need SameSite=strict

I was very wrong there.

**Comment by abrookbanks** [comment]
This should be resolved now.

**Comment by abrookbanks** [comment]
Nothing is ever simple is it?! SameSite can't be used to extend session cookie.

**Comment by abrookbanks** [comment]
This works beautifully now. Browser warnings gone.

**Comment by abrookbanks** [comment]
![Annotation 2020-07-29 151850](https://user-images.githubusercontent.com/4520803/88811749-d79b1100-d1ae-11ea-9680-fd1fc4c4a60b.jpg)
