### ISSUE TITLE
No default favicon

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2557]
CubeCart defines favicon path as:
`<link rel="shortcut icon" href="{$STORE_URL}/favicon.ico" type="image/x-icon">`

But, no icon exists at this location when you install cubecart. a default one should exist to stop a 404 error

**Comment by havenswift-hosting** [comment]
In some ways I agree and CubeCart used to ship with a favicon.ico file (the CubeCart one) which is great for CubeCart especially as many stores never bother to do one themselves but not so great when each upgrade was overwriting those stores where they had created their own !  My view would be to not include it and leave it as it is now

If a new store owner doesn't create their own favicon, then an odd 404 is probably the least of their worries !  Maybe it could be added as a step to Welcome Tour to tell new store owners this is something they should do but then you could add hundreds of steps

**Comment by abrookbanks** [comment]
I think this should say as it is. With the code removed you still get a 404 error as browsers look for it regardless and if we add one it will indeed overwrite with each upgrade.
