### ISSUE TITLE
PayPal commerce - not enabled?

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2558]
Linking an existing, live PayPal business account via ecommerce module. during checkout, get a failure. in developer console, the following error is noted:

_Card processing is not enabled for this merchant_

There is nothing in the documentation to imply what needs to be enabled or the account prerequisites. what is required in the PayPal account settings for the eCommerce module to work?

**Comment by abrookbanks** [comment]
For most established PayPal accounts card processing will work right away. I believe some accounts take time to be manually verified by PayPal before card processing is enabled. At the time of developing the extension there was no means to feed this back to the merchant or provide updates but I do know that this will be available at a later date. When it is we can build it in. 

If cards don't work after a week it might be worth contacting PayPal.
