### ISSUE TITLE
Finding assigned images in admin file manager impossible

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2560]
In sites that have a large number of images and (correctly) create a large hierarchy sub-directory structure in which to store these images, it is impossible to locate where these images are for any specific product. 

Switching between "Show all images" and "Show only assigned images" only works if the correct sub-directory is already open and ideally should also not display all the other sub-directories

Example from a live site with c 15,000 products which are split into 13 top level categories, each of which has large numbers of sub-categories.  The sub-directory structure for images mimics the category structure

When editing a product and on the image tab, I would expect clicking on "Show only assigned images" to open up those directories / sub-directories that contain images for this product and only display those images.  What is does correctly, is display only those images, but the directory stays collapsed so you have to know in which directory these displayed images are located.

It is unlikely for most stores but it should also work if assigned images are spread across more than one directory.

Also ideally, it should not even show any of the other top level directories - in my example store's case, there are many hundreds of directories in the structure

**Comment by abrookbanks** [comment]
I'll see what I can do. Big push for 6.2.10 now....

**Comment by havenswift-hosting** [comment]
Would be great if you can to go alongside your other admin image improvement !  Are you going to be able to get memcache issue  fixed for this version as havent even moved many clients to 6.2.9 due to that

**Comment by bhsmither** [comment]
A couple technical aspects of the FileTree plugin prevents an easy fix.

As a workaround, this is what I did:
```
products.index.inc.php
Find:
        $master_image = isset($_GET['product_id']) ? $GLOBALS['gui']->getProductImage((int)$_GET['product_id']) : '';
        $result[0]['master_image'] =  !empty($master_image) ? $master_image : 'images/general/px.gif';
Add after:
        if (($gallery = $GLOBALS['db']->select('`'.$GLOBALS['config']->get('config', 'dbprefix').'CubeCart_image_index` AS `i` INNER JOIN `'.$GLOBALS['config']->get('config', 'dbprefix').'CubeCart_filemanager` AS `f` ON i.file_id = f.file_id', false, 'i.product_id = '.$product_id, 'ORDER BY i.main_img DESC'))) {
            foreach ($gallery as $key => $image) { $json['image_'.$image['id']] = $image; }
            $GLOBALS['smarty']->assign('GALLERY_JSON', json_encode($json));
        }

products.index.php
Find:
         <div id="imageset" rel="1" class="fm-filelist"></div>
         <div class="master_image">
Add after:
         {if $GALLERY_JSON}<div id="gallery_json">Current images:<ul>{foreach $GALLERY_JSON|json_decode:true as $gallery_image}<li>{if $gallery_image.filepath}/{$gallery_image.filepath}{else}/{/if}{$gallery_image.filename}</li>{/foreach}</ul></div>{/if}
```
This displays a list of all the currently assigned images including their filepath.

**Comment by abrookbanks** [comment]
@bhsmither I was thinking about a similar approach. The fila tree doesn't load all data unless folders are opened which makes it tricky. I'll see where I can go with this. Thanks gents.

**Comment by abrookbanks** [comment]
With the file manager updates this really should go into 6.4.

**Comment by abrookbanks** [comment]
Progress so far. I will try to make it dynamic (linked to the file tree status).

![Screenshot 2020-10-02 101510](https://user-images.githubusercontent.com/4520803/94907547-3ecb8f00-0498-11eb-8c2a-9a88d26ddb24.jpg)

**Comment by abrookbanks** [comment]
This is a significant improvement!

**Comment by Dirty-Butter** [comment]
I'm not sure which change this goes with, but I would suggest the default font size needs to be larger for the folder names in Filemanager and possibly black color.
.fm-item > a so tiny below the folder that I could barely read it - and pale blue makes it even more difficult to read.
