### ISSUE TITLE
Product Options - Bugs with mixture of absolute / non absolute option value

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2566]
Internal ticket #110084.

**Comment by abrookbanks** [comment]
https://github.com/cubecart/v6/commit/1058a06b9690a726555604314f067c3ec8551411 - Fixes total calculations for products with ONE option that is absolute in price.

**Comment by Noodleyman** [comment]
@abrookbanks , can you please add some context to this change? which bugs did this ticket target, what was their behaviour? thanks.

**Comment by abrookbanks** [comment]
Prior to these changes CubeCart was designed to only have one absolute option group which overrides the main price. 

It's been re-coded so you can now have one absolute option group and others too. 

**Case:**
Gift Message: (Optional +£5)
Material: Plastic (Absolute Price £20) / Stone (Absolute Price £30)

Before it would force the price to £20 or £30. The gift message price would get ignored. 

Since these changes it will allow the gift message price to add on.

It does this by essentially adding up the option prices. If there is an option group with absolute price it will subtract the main product cost. That allows much more flexibility.

**Comment by Noodleyman** [comment]
I can see a lot of misconfigured stores running into price issues after upgrading.. might be worth adding a lot of details to this one in the release notes when it's pushed out.  thanks for the details.

**Comment by abrookbanks** [comment]
No I don't think that will be the case at all. All existing option configurations will continue to work with this logic.

**Comment by Noodleyman** [comment]
for stores where they checked absolute for every option, but only one gets applied (as today). this change would modify the result and give them a different price.

I've seen it misconfigured this way a bunch of times and is what I had in mind with the last comment.

**Comment by abrookbanks** [comment]
I see what you are saying. I haven't seen a situation like that before. I can't think of a case a merchant would do that and I certainly haven't come across it before.

**Comment by Noodleyman** [comment]
can confirm, it's out there in the wild.  usually where people experimented with the absolute options until they got the price they wanted and just left it alone. those scenarios will now get a higher price based on aggregated absolute options, minus product price.

also note, that in some cases, the base product price will be zero for these kind of configurations. why is it adding up the absolute prices and subtracting the base price, instead of just using the aggregated option prices?

**Comment by abrookbanks** [comment]
Ok I will add release notes. Thanks for the heads up. I haven't seen such a scenario myself so it may only affect a very small minority or merchants.

**Comment by Noodleyman** [comment]
@abrookbanks 
why is it adding up the absolute prices and subtracting the base price, instead of just using the aggregated option prices?

Reason for asking, the concerns I had with this approach have already become an issue on a site where we applied the changes in this thread because the base price is making the absolute price £0 for the purposes of promotional codes, so you can't enforce a minimum subtotal

**Comment by abrookbanks** [comment]
Reopened. Logic should be changed to detect multiple absolute option groups then fall back to old if > 1. We are then fully backward compatible.

**Comment by abrookbanks** [comment]
I've spent hours on this but the biggest issue seems to be UX. 

I can't think of a real world example where you would want more than one option group with absolute price. Assuming we do then they would need to add up like normal options removing the main product price once? I'm so confused. 

Or would it put the price as the absolute amount for whichever one is selected. On those grounds it shouldn't allow more than one to be selected at a time. 

I've got myself into such a muddle with all this. 

Can you give me an example with math?

**Comment by abrookbanks** [comment]
Closing. I just can't see a reason to have more than one absolute group.

**Comment by Noodleyman** [comment]
can you chance the option checkbox to a radio button so it would only ever allow one to be selected?

**Comment by abrookbanks** [comment]
Sadly not because there will be more than one. Hmmm.. Good idea though. Let me have a ponder. 

![Screenshot 2020-09-22 112401](https://user-images.githubusercontent.com/4520803/93871221-315b1b80-fcc6-11ea-8c68-0f7726690225.jpg)
