### ISSUE TITLE
Link to Open New Window

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2569]
On the Import Code Snippets tab, a link is presented to load a sample XML document.

Suggest converting the document to an HTML page and make the HTML **look** like an XML structure, or provide an XML stylesheet that uses the actual XML document.

Also, suggest using the `target="_blank"` attribute of the link to open a new browser window. Or maybe a ColorBox.

**Comment by abrookbanks** [comment]
Thanks!! :)
