### ISSUE TITLE
HTML error in French Language Pack.

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2570]
Regarding #2569, the fault lies with the HTML in a language string in the French pack.

See: https://forums.cubecart.com/topic/56227-import-code-snippets/

**Comment by abrookbanks** [comment]
It looks ok to me.

`<![CDATA[Un exemple d'un flux XML d'importation peuvent être trouvées <a href="docs/examples/code_snippet_import.xml"> ici </ a>. S'il vous plaît utilisez le lien «Aide» pour plus d'informations.]]>`

**Comment by havenswift-hosting** [comment]
</ a> is wrong

**Comment by abrookbanks** [comment]
Yes. Thanks. Fixed now in 1.0.2.
