### ISSUE TITLE
Show image in master file manager

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2571]
A list of names is not helpful.

**Comment by abrookbanks** [comment]
![Annotation 2020-08-12 123315](https://user-images.githubusercontent.com/4520803/90010603-037ec200-dc98-11ea-8dc7-bce6c21e846c.jpg)

**Comment by havenswift-hosting** [comment]
That is a great feature request that will make things much better 👍  Wonder how it will work when an admin has 10,000 images in one top level directory lol

Would you be able to take a look at https://github.com/cubecart/v6/issues/2560 and add as well as that combined with this will make image management so much better

**Comment by abrookbanks** [comment]
What kind of maniac has 10,000 images in one folder!!! LOL

**Comment by havenswift-hosting** [comment]
As you and I both know - quite a few - have seen 150,000 all in top directory lol

**Comment by abrookbanks** [comment]
So it sounds like I need to add lazy loading. :)

**Comment by havenswift-hosting** [comment]
>So it sounds like I need to add lazy loading

Would be a very good idea.  In fact it is a great idea throughout the store but especially for categories

**Comment by abrookbanks** [comment]
Lazy loading works beautifully. Tested over "Slow 3G" network config in Chrome.

**Comment by havenswift-hosting** [comment]
Excellent addition !

**Comment by cb2004** [comment]
Without looking too much into this, you know about loading="lazy" on image tags is widely supported now so you could let the browser do the work here, no code to maintain

**Comment by abrookbanks** [comment]
> Without looking too much into this, you know about loading="lazy" on image tags is widely supported now so you could let the browser do the work here, no code to maintain

It is 73% supported which is good enough for me. 
https://caniuse.com/#feat=loading-lazy-attr

**Comment by abrookbanks** [comment]
In hindsight. This adds complexity in that the image dimensions have to be set and above the fold shouldn't have the tag added. This makes it difficult for the gallery size buttons. Lets keep the JS library for now.

**Comment by Dirty-Butter** [comment]
I have tried this new code in two installs. Both of them show the link to the folder image should be admin/skins/default/images/folder_large.png. But it does NOT find the image because I have renamed the admin file. When I replace the admin with my naming, the folder image shows up.

**Comment by abrookbanks** [comment]
Allow dynanic admin folder.

**Comment by havenswift-hosting** [comment]
Just wondering if you need an extra check when deleting a folder if it contains images or at least change the popup message that "You are about to delete a folder that contains xxx images"

**Comment by abrookbanks** [comment]
I'll check thanks.

**Comment by havenswift-hosting** [comment]
Also during my testing, I am unable to click into any sub-folder and view images within that folder

**Comment by abrookbanks** [comment]
> Also during my testing, I am unable to click into any sub-folder and view images within that folder

I can't reproduce that.

**Comment by havenswift-hosting** [comment]
> I can't reproduce that.

I have download and replaced all files changed as a result of this and also https://github.com/cubecart/v6/issues/2589 and still have problems.  Is there some sort of caching for these changes - several of the recent changes (including the last one about folder being deleted) arent reflected in the file being download so that could be the cause.  When are you intending to release 6.2.10 ?

**Comment by abrookbanks** [comment]
I just can't reproduce this issue. http://static.cubecart.com/issue-2571-ajax.mp4

**Comment by havenswift-hosting** [comment]
Can grant access to a store where I can reproduce this easily - ping me on WA if you want details

**Comment by havenswift-hosting** [comment]
>Added check/uncheck all toggle

You might want to move this from the bottom to the top (or maybe better to have it in both locations)

**Comment by abrookbanks** [comment]
> I just can't reproduce this issue. http://static.cubecart.com/issue-2571-ajax.mp4

I hope you liked the music! I hadn't mean to keep the sound on. :laughing:

**Comment by havenswift-hosting** [comment]
>I hope you liked the music! I hadn't mean to keep the sound on.

I had mine muted when I first looked but had to go back and check after your comment lol Cant say it is my taste lol

**Comment by abrookbanks** [comment]
Ha nor me really.  Spotify has a mind of its own.
