### ISSUE TITLE
Stop Query From Reading Cache

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2574]
In `Order->_digitalDelivery()`, a SELECT query is made to `Cubecart_downloads` that could read from the cache.

A possible (probable) previous query (or call to `_digitalDelivery()`) resulted as an element in the empty recordset cache.

Suggest setting to false the parameter to read the cache.

**Comment by abrookbanks** [comment]
Thanks!!!!!! :) :) :)
