### ISSUE TITLE
Option Group Description is Customer Facing

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2575]
At checkout (and possibly elsewhere), the Option Group Description is displayed to the customer.

I believe the description is for admin use only (and says so on the Help screen), and may contain verbiage not appropriate for where it gets shown.

In content.checkout.medium-up.php, there is:
```
{if empty($option.option_description)}{$option.option_name}{else}{$option.option_description}{/if}
```
Suggest just using `option_name`.

However, if there is a desire to have the group name be plural, such as **Available Sizes**, and then _Description_ would be the singular choice, such as **Size**, then a better word is needed for this field _Description_. Perhaps give examples next to the fields.

**Comment by NiteTowerDesign** [comment]
Appears this was missed in **element.product.options.php** in 6.4.1
