### ISSUE TITLE
Admin account username is exposed publicly by social - Youtube on Chrome

### ISSUE THREAD

**Issue by Chazeo** [cubecart/v6#2579]
If a user opts to have the browser remember the credentials, the Admin account username is populated to the YouTube field when navigating to Store Settings. It is very likely that someone could miss this by navigating to another tab and saving. 
I have replicated this issue on  GChrome/Windows and Mac, Edge (Chrome) - Firefox does not have this behavior. 
This is under very specific circumstances and security by obscurity is never a solution, however this issue is rather annoying from a usability perspective.

**Comment by abrookbanks** [comment]
Sorry but I can't see how this is possible. 

The login username text field has name="username" id="username".
The YouTube text field has name="config[youtube]" id="youtube".

**Comment by havenswift-hosting** [comment]
Using the browser to save usernames and passwords is not good security but of course a lot of people do it.  I have also seen this happen in various places - SMTP auth password on the settings page is overwritten with the wrong saved password but have also seen a similar thing with the social media entry fields although cant remember which ones

**Comment by abrookbanks** [comment]
This happens ALL the time even though the field has `autocomplete="off"`.

**Comment by hairy-dog** [comment]
No, I don't understand why it happens either, but it does.
  
I think I went into the database to remove it in the end.
  

  

  
  
 -- Iain  

  
  
  
  
  
>

**Comment by abrookbanks** [comment]
I'm going to have to close this unless anyone has any further input as I don't know that there is anything else we can do.

**Comment by hairy-dog** [comment]
Closing an unresolved issue is not good practice.
  

  

  
  
 -- Iain  

  
  
  
  
  
>

**Comment by abrookbanks** [comment]
@hairydogltd agreed but its an impossible task right? Suggestions please.

**Comment by Chazeo** [comment]
Perhaps this is an option? https://stackoverflow.com/questions/55738891/chromes-save-password-functionality-places-a-username-in-an-unrelated-field

**Comment by abrookbanks** [comment]
It's a bit of a dirty work around we shouldn't have to do but could work. I'll experiment.

**Comment by abrookbanks** [comment]
That JS code seems to work well. Lets see how it goes in real world testing.
