### ISSUE TITLE
Code Review: Products/Page Selector Labels

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2580]
When having coded the `content.category.php` template to show Traditional Pagination, and that includes the Page Splits drop-down selector, there is no labeling for the customer to know what this selector does.

Suggest: `large-8` for PAGINATION, `large-4` for the selector, and
```
<option value="{$page_split.url}"{if $page_split.selected} selected{/if}>{$LANG.common.show} {$page_split.amount} {$LANG.settings.product_per_page}</option>
```

**Comment by abrookbanks** [comment]
Thanks.
