### ISSUE TITLE
Add SendGrid Support

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2581]
With so many host with unreliable mail() configurations and blocked outgoing SMTP ports there is a need for an external relay.

**Comment by abrookbanks** [comment]
6.1.10 should be 6.2.0.

**Comment by Dirty-Butter** [comment]
Is there a way to opt-out of using Sendgrid? Or will CC ignore that code if there is not an API key shown? I tried an install with Sendgrid code included in CC and am having problems. I acquired the Sendgrid API key, but I don't know what else I'm supposed to do other than put the key in the blank.

**Comment by abrookbanks** [comment]
That is all you are supposed to do other then domain DNS changes. It's just an alternate way to send email. If your current setup worked ignore it.

**Comment by Dirty-Butter** [comment]
I get this error when I try to change a test order from Pending to Cancelled:
``[<strong>Exception</strong>] /home/butter01/public_html/plushmemories.com/plushtest/classes/sendgrid/lib/SendGrid.php:18 - Too few arguments to function SendGrid::__construct(), 0 passed in /home/butter01/public_html/plushmemories.com/plushtest/classes/mailer.class.php on line 255 and at least 1 expected``

This is on a test site that I have not tried to add a Sendgrid key to. I had also tried it with the same error result on our live site. I did try adding the API key to the live site. Since it did not work I removed all Sendgrid code from the live site for the time being.

**Comment by Dirty-Butter** [comment]
Also, when I ran the SMTP Test on the test site that has never had any API key added - the screen went blank, as in a crash. BUT I did receive the email notice that an SMTP test had completed successfully.

**Comment by Dirty-Butter** [comment]
Sendgrid code now works when I do not input the API key. Emails are sent as they should be with no error messages or crashes.
And the email test does not crash now. BUT the CC message after testing says
 "Testing SMTP with SSL - Success
Test failed to execute."
I assume that second line is for the Sendgrid not in use, but it would help if it actually said "Sendgrid Test failed to execute". If that's not what that is for it needs some kind of change, as it tells me nothing.

**Comment by Dirty-Butter** [comment]
SORRY - NOT RESOLVED for me. I was able to send an email via Contact link and it worked correctly, but when we had a live order using the newest commit the automatic emails that should have been sent to the customer after sale was completed may not have processed correctly. The email log showed them as sent, but I did not get a copy of the sent email as I normally do. SO I have again removed all references to Sendgrid code and now the email copy of the transaction correctly arrives in my inbox. Of course my store is not stock, so this may be some change I need to make in my code where the copy of the customer emails are sent to me.

**Comment by abrookbanks** [comment]
It works flawlessly for me. Did you setup all the DNS steps at sendgrid?

**Comment by Dirty-Butter** [comment]
I did not finish the Sendgrid setup on their site. I did NOT add the Sendgrid API Key - I was trying to get all the new CC, including the Sendgrid option code, to work without actually using Sendgrid at all. I really don't need Sendgrid as far as I can tell. Havenswift's SMTP works just fine. 
Please try removing just the Sendgrid API key from your Advanced settings, with all previous SMTP info in place, and then see if you as the admin receive the appropriate emails when an order is processed.
