### ISSUE TITLE
Code Review: CSRF re: Session Token

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2583]
Is it just me, or is it now possible to be working in administration, open more than one order (customer, document, product) - experimented with four orders - each in a separate tab/window, change something, Save it, and still be able to then continue working/saving the rest of the orders in other tabs/windows without having to reload and get a page with the correct security token?

It seems the security token does not change after each POST -- which used to be how it worked.

(Working to solve: https://forums.cubecart.com/topic/53344-all-in-one-shipping/ beginning with WSD)

**Comment by abrookbanks** [comment]
Yes the security token no longer changes with each post. The loss of multiple tab/windows for this was too much.
