### ISSUE TITLE
Certain Store Settings Placement

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2584]
On the Store Settings, Stock tab, General Stock Settings section, there are a few settings that might be better placed elsewhere:

"Allow delivery to non-invoice address" to the Features tab, Misc section
"Weight Unit" to General tab, Tax, Language, Currency, and Weight section (a new title)
"Display basket weight on checkout" to Layout Settings tab, Layout Settings section

Just my opinion.

**Comment by abrookbanks** [comment]
I agree Brian. Thanks for this.
