### ISSUE TITLE
AIOS Javascript Code

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2585]
In the module's /skin/admin/index.tpl template, there is some javascript code.

Currently, that code conforms to a style that does not conflict with Smarty parsing.

But, perhaps on the next update, consider wrapping this code in `{literal}{/literal}` Smarty tags.

**Comment by abrookbanks** [comment]
Same with the script tag at the bottom.

**Comment by abrookbanks** [comment]
AllInOneShipping-1.0.19.zip available
