### ISSUE TITLE
CCHQ Version Check Server Miscalculates Availability

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2588]
The following tests show that the data returned seems to be the result of a miscalculation of published date for the latest version.

These tests were made by enabling the Request Log for the Dashboard *version check* and sending various 'modified' values for key 44 (All in One Shipping).
```
Today, 12:22
Request Sent (cURL) - https://www.cubecart.com/version-check/6.2.9?version=6.2.9&extensions%5B44%5D=1596699083&extensions%5B105%5D=1474387528&extensions%5B452%5D=1597078286
version=6.2.9&extensions%5B44%5D=1596699083&extensions%5B105%5D=1474387528&extensions%5B452%5D=1597078286
Response received (200 - OK)
{"version":"6.2.9"}

Today, 12:41
Request Sent (cURL) - https://www.cubecart.com/version-check/6.2.9?version=6.2.9&extensions%5B44%5D=1496699083&extensions%5B105%5D=1474387528&extensions%5B452%5D=1597078286
version=6.2.9&extensions%5B44%5D=1496699083&extensions%5B105%5D=1474387528&extensions%5B452%5D=1597078286
Response received (200 - OK)
{"version":"6.2.9"}

Today, 12:48
Request Sent (cURL) - https://www.cubecart.com/version-check/6.2.9?version=6.2.9&extensions%5B44%5D=1096699083&extensions%5B105%5D=1474387528&extensions%5B452%5D=1597078286
version=6.2.9&extensions%5B44%5D=1096699083&extensions%5B105%5D=1474387528&extensions%5B452%5D=1597078286
Response received (200 - OK)
{"version":"6.2.9","updates":{"44":true}}
```
```
1596699083 = 6 Aug 2020
1496699083 = 5 Jun 2017
1096699083 = 2 Oct 2004
```
The first test is, of course, correct.

The second test says I have a version three years old. No notice returned. (I made this test twice.)

The third test says I have a version 16 years old (haha). Notice was returned.

**Comment by abrookbanks** [comment]
A new bug since introducing a better request cache. I believe this is resolved now. The store is cached for an hour so it might not behave until up to an hour after posting this.

**Comment by abrookbanks** [comment]
Closing as I could see the issue. The timestamp wasn't correctly taking the latest one but last listed.

**Comment by bhsmither** [comment]
If you are referring to CubeCart's Request class `cache` attribute and functionality, it turns out this attribute/function is no longer relevant with respect to administrative processes.

That's because, having set the `Request->status` to true, `Request->send()` uses the Cache class to determine if there exists a cached response for this request.

However, in admin, the Cache class status is false. Thus, the check for the existence of a cached response will always return a hard false, as well as attempting to write the response into the cache.

**Comment by abrookbanks** [comment]
No I was referring to cache at CCHQ for storing latest time stamps of extensions.
