### ISSUE TITLE
System Error Log to show URL

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2591]
After having a rouge MySQL error logging the URL will prove very useful.

**Comment by bhsmither** [comment]
Maybe the System Error Log could record the `debug_backtrace()`?

To keep the display clean, put the contents in a (i) bubble that shows a tooltip on hover.

I am going to try:
http://docs.php.net/manual/en/function.debug-backtrace.php#99796

**Comment by abrookbanks** [comment]
Here is an example of error log entry I'm struggling to reproduce.

```
Date Message  Today, 00:23 File: [catalogue.class.php] Line: [1047] "SELECT SQL_CALC_FOUND_ROWS * FROM `cc_CubeCart_inventory` WHERE `product_id` IN (1845,1846,1847,1848,1850,1851,1852,1856,1859,1860,1862,1863,1864,1865,1866,1867,1868,1869,1870,1871,1872,1873,1874,1875,1876,1877,1878,1879,1883,1884,1885,1887,1888,1889,1890,1891,1894,1895,1897,1898,1899,1900,1901,1902,1903,1904,1905,1906,1908,1910,1912,1913,3707,3708,3709,3733,4088,4143,4152,4156,4169,4278,4391,4393,4396,7239,4399,4400,4453,4454,4455,4463,5528,5430,5463,5464,5901,5903,7240,5907,6503,6795,6796,6797,6892,6896) AND cc_CubeCart_inventory.status = '1' AND `live_from` < UNIX_TIMESTAMP() AND ((cc_CubeCart_inventory.stock_level > 0 AND cc_CubeCart_inventory.use_stock_level = 1) OR cc_CubeCart_inventory.use_stock_level = 0) ORDER BY `name` ASC LIMIT 48 OFFSET 1.0618138138181E+15;" - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '1.0618138138181E+15' at line 1
```

**Comment by abrookbanks** [comment]
What do you think? I had to array shift once to break out of the errorLogger method of the debug class. 

![Annotation 2020-09-02 085909](https://user-images.githubusercontent.com/4520803/91955141-a906dd80-ecfa-11ea-805d-760d0d6981fd.jpg)

**Comment by bhsmither** [comment]
That would be a manually constructed querystring with having `page=22121121121211` (assuming 48 products per page) from a "search" -- probably getting a list to display the products of a category.

A debug_backtrace would show where the arguments for `getProductData()` are coming from -- probably `getCategoryProducts()`.

The image above is great, but it is indistinct as to what it belongs to -- obviously that piece of info won't come through on that image, not seeing where the mouse is, but the user would know what log entry the tooltip is referencing.

**Comment by abrookbanks** [comment]
Thanks Brian!

**Comment by bhsmither** [comment]
And we may have to rethink the `create_function()` - deprecated as of PHP7.2.

Try for an anonymous function?

**Comment by abrookbanks** [comment]
You are on the ball today.

**Comment by bhsmither** [comment]
This is what I am going to try:
```
array_walk($backtrace,function($a){print "{$a['function']}()(".basename($a['file']).":{$a['line']});\r\n";);
```

**Comment by bhsmither** [comment]
I have noticed in backtraces that ionCube decoded stuff gets listed as *something* with line number 0.

Might cause *some* confusion tracing it out if it's not listed.

**Comment by abrookbanks** [comment]
Yes I've come across that too.

**Comment by bhsmither** [comment]
If there will be some guidance put on a wiki help page for the debug_backtrace, be sure to mention that the trace shown is only of limited use. Calls to functions no longer mentioned on the stack (*e.g.*., hooks) might very well be the culprit.
