### ISSUE TITLE
Integrate What3Words

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2593]
Checkout process, address book, delivery slip, invoices etc... 

Off by default. 

More info at https://what3words.com

**Comment by havenswift-hosting** [comment]
Decided to put it into 6.2.10 rather than 6.3 then ?!

**Comment by abrookbanks** [comment]
Branches are all messed up. We are skipping the 6.3 branch so it will be 6.4.

**Comment by havenswift-hosting** [comment]
So you arent going for 6.2.10 then and going straight to 6.4 ?  Any chance of Elastic Search being included ?  I have it installed and working on one server already so can do extensive testing when added

**Comment by havenswift-hosting** [comment]
Will be testing the W3W integration for you shortly as well

**Comment by havenswift-hosting** [comment]
You have hard coded text "what3words address (optional)" in several different skin files

**Comment by abrookbanks** [comment]
well spotted

**Comment by havenswift-hosting** [comment]
And some other hard coded wording on the admin side as well

**Comment by abrookbanks** [comment]
Thanks. I will leave this open until I get feedback from the W3W team.

**Comment by abrookbanks** [comment]
Signed off.

**Comment by abrookbanks** [comment]
Add clip to country https://developer.what3words.com/public-api/autosuggest-component

**Comment by abrookbanks** [comment]
Upgrade to use partner API key. (See email from Tom March 15th).
