### ISSUE TITLE
Database Select DISTINCT

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2596]
When passing in an array of columns, currently, only one element can have the key "DISTINCT" and it must be the first. That is because DISTINCT is a modifier on the SELECT keyword, and not part of an expression (column name, etc).

When working through `$columns`, a `$field` having the `$key` of "DISTINCT" is also added to `$group_by`.

This creates a limitation where a query cannot be constructed that has just the single instance of `DISTINCT`, and more than one element in `$group_by`.

Suggest:
```
                        $distinct = null; 
                        if (!is_numeric($key) && in_array(strtoupper(substr($key,0,8)), array('DISTINCT'))) {
                            $distinct = "DISTINCT";
                            $group_by[] = "`$field`";
                            $cols[]  = "`$field`";
```
Then later:
```
        $parent_query = "SELECT $sql_cache $calc_rows $distinct ".implode(', ', $cols)....
```
That still leaves a situation where more than one element in the `$columns` array cannot each have "DISTINCT" as their key.

Which is solved by not using the exact phrase "DISTINCT" for all columns that are to be grouped. Look for only the first eight characters - looking for "DISTINCT" - as the start of a longer key. For example:
```
$GLOBALS['db']->select('CubeCart_order_summary',
array('id','first_name','DISTINCT_last_name' => 'last_name','DISTINCT_email' => 'email'),
false, false, false, false, false)
```

**Comment by abrookbanks** [comment]
I can't see any faults with this. Thanks. Tests came out positive.
