### ISSUE TITLE
Add error log notification tab to dashboard

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2597]
It would be very useful to have this added if there are new / unread errors in the log - most users never go into this option as there is no indication that there are new errors

**Comment by Dirty-Butter** [comment]
A very long time ago CC had that tab if I remember correctly. I would love to see this, as it's too easy to have an issue go unseen for ages.

**Comment by abrookbanks** [comment]
It did. Since then the error reporting level is more sensible so maybe we can add it back.

**Comment by abrookbanks** [comment]
Error types explained.

![Screenshot 2020-09-17 102005](https://user-images.githubusercontent.com/4520803/93451654-5f5bec80-f8cf-11ea-9a4d-da4a3f54e00b.jpg)

**Comment by abrookbanks** [comment]
Dash tab reinstated 

![Screenshot 2020-09-17 102107](https://user-images.githubusercontent.com/4520803/93451768-84505f80-f8cf-11ea-84fa-1908a42b795f.jpg)

**Comment by abrookbanks** [comment]
System error log is for developers not merchants. On those grounds it should not show on the dashboard. There are too many false positive in code that isn't strict.
