### ISSUE TITLE
Feature request : Add ability to use ElasticSearch

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2600]
Search is one of the poorer areas in CubeCart but implementing ElasticSearch would dramatically improve usability, speed and accuracy of responses and also take a lot of strain off of the MySQL server engine.

It would probably need to be implemented as an option to the current search functionality as not all hosting companies would install it locally on the server although an additional option to use an external cloud based solution (these are generally paid for services) maybe could also be considered

**Comment by Dirty-Butter** [comment]
I have been using search code Bsmither devised for our store some years ago, as I require an AND, not an OR type search for our products where order of terms does not change the results. I would not have been able to continue using CubeCart if I had no option other than to use stock CC search code. I look forward to seeing this implemented as an option.

**Comment by abrookbanks** [comment]
I'm pretty confident about how to go about this now so work is planned for 6.5.

**Comment by abrookbanks** [comment]
Linking to 6.5 branch - https://github.com/cubecart/v6/tree/v6.5

**Comment by havenswift-hosting** [comment]
Let me know when you feel this is ready to start testing - more than happy to spend time on this as have ElasticSearch already installed on multiple servers

**Comment by abrookbanks** [comment]
> Let me know when you feel this is ready to start testing - more than happy to spend time on this as have ElasticSearch already installed on multiple servers

I was going to ask if you use localhost but it's already coded to take an array of servers so local or remote will be fine.

**Comment by havenswift-hosting** [comment]
Have it installed locally and likely would not use it any other way.  Being able to use remote would be useful functionality for those wanting to use a third party paid service - very few / none of the generic hosting companies out there will ever install ES so this will be a big differentiator for both of us in hosting terms

**Comment by abrookbanks** [comment]
Very true. It would be an enabler for other hosting. 👍🏻

Good thinking.

**Comment by Dirty-Butter** [comment]
I have a test site with the 6.5 code as of yesterday. And I have joined their website, too. I can give Havenswift access to plushtest if it would be of any help in your testing.

**Comment by abrookbanks** [comment]
It's not ready to be tested yet but I'll say when it is. Quite a lot to do.

**Comment by havenswift-hosting** [comment]
>> And I have joined their website, too. I can give Havenswift access to plushtest

We have Elastic Search installed locally so no need to use an external service (at extra cost)

**Comment by abrookbanks** [comment]
To be reopened later.

**Comment by havenswift-hosting** [comment]
Can this be re-opened especially as so much work was done on it already ?  It would be a major game changer for CubeCart going from a very poor search function as it currently is to the best available

**Comment by abrookbanks** [comment]
My resources are incredibly thin. A big piece of work is about to be released then I'm focussing some time on something else. I really do want to get this on the go again.

**Comment by abrookbanks** [comment]
Reopening to restart development

**Comment by abrookbanks** [comment]
Setting up CA;
https://stackoverflow.com/questions/67108012/where-does-elasticsearch-certificates-located

<img width="732" alt="Screenshot 2023-03-24 at 09 56 18" src="https://user-images.githubusercontent.com/4520803/227489584-39fdc203-61c5-4376-b607-635f96de7fe3.png">
