### ISSUE TITLE
Feature required to search file manager for images and digital files

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2601]

**Comment by abrookbanks** [comment]
![Screenshot 2020-09-10 173250](https://user-images.githubusercontent.com/4520803/92763651-aa37aa80-f38b-11ea-999b-d34883c0d843.jpg)

**Comment by abrookbanks** [comment]
Clicking the search result will open the folder.

**Comment by havenswift-hosting** [comment]
Another fantastic feature added - thanks Al 👍

**Comment by havenswift-hosting** [comment]
Would it be possible to add this search functionality also to the Image tab when editing products ? That way a search can be done for suitable images already uploaded and then one or more can be assigned to the image

**Comment by abrookbanks** [comment]
Yes very easily.

**Comment by abrookbanks** [comment]
maybe even to list the assigned ones.. I'll have a poke tomorrow

**Comment by havenswift-hosting** [comment]
> maybe even to list the assigned ones

Now that would be even better ! Updating and testing as you release so bring it on !

**Comment by abrookbanks** [comment]
![Screenshot 2020-09-11 101536](https://user-images.githubusercontent.com/4520803/92900725-d567db80-f417-11ea-83f7-0497ca00f039.jpg)

**Comment by havenswift-hosting** [comment]
Having the search results on a separate screen works well and being able to select one from the list is good but would it be better and easier to use if instead of that it instead only displayed the images matching the search results ?  This way the images can be seen and one or more chosen (especially when adding images to a product)

**Comment by havenswift-hosting** [comment]
As reported by Rosemary (somewhere), I am also seeing this error reported

[<strong>Deprecated</strong>] /home/XXXXXXXX/public_html/classes/ajax.class.php:55 - Non-static method Ajax::fmSearch() should not be called statically
https://domain.com/admin_AbCdEf.php?_g=xml&function=fmSearch

**Comment by abrookbanks** [comment]
Are you sure it wasn't logged before latest code? I can't reproduce it and I remember change the code to fix that issue during dev.

**Comment by havenswift-hosting** [comment]
I am running latest code as of yesterday evening and I can reproduce it - can provide access to site if you want to look ?

**Comment by abrookbanks** [comment]
Preview in popup.
![Screenshot 2020-09-22 095919](https://user-images.githubusercontent.com/4520803/93862727-65304400-fcba-11ea-87d2-0cfc08fe0951.jpg)

**Comment by abrookbanks** [comment]
Excuse the family snaps. This was over ten years ago in New Zealand. I'm a fat middle aged dad now.

**Comment by havenswift-hosting** [comment]
> Would it be possible to add this search functionality also to the Image tab when editing products ? That way a search can be done for suitable images already uploaded and then one or more can be assigned to the image

Can this not also be added please ?

**Comment by abrookbanks** [comment]
It has been.
