### ISSUE TITLE
Gift Cards and Contact Page - SEO - 6.2.9

### ISSUE THREAD

**Issue by harris-organic** [cubecart/v6#2603]
Gift Cards and Contact Page - SEO
Both Gift Cards and Contact Page have no option to change the title, Custom SEO URL Path and meta description.

The Gift Cards and Contact Page have the same default title, and meta description in 6.2.9, ie /gift-certificates.html and contact-us.html

Also adding a content page for the gift cards and H1, H2 tags would be pleasing .

**Comment by harris-organic** [comment]
"Also adding a content, ie a description page for the gift cards and H1, H2 tags." No content page was added. Should this be raised as a new issue?  ie a description tab, so more information can be provided to the customer instead of adding text through the language file.

**Comment by bhsmither** [comment]
Please elaborate by what you mean "content page". Is that different than what the customer sees having clicked "Gift Cards" on the Shop by Categories list (top bar)?

**Comment by harris-organic** [comment]
A content Page, ie a description tab, so more information can be provided to the customer instead of adding text through the language file. 

Is it possible to add a description tab to use a rich text editor in the gift card section?

I would rather use the editor than write into the 'definitions.xml' every time I need to change the description.

Images: Even though images are defined, the image does not show on the gift card page
