### ISSUE TITLE
Cache files on server

### ISSUE THREAD

**Issue by pmycroft** [cubecart/v6#2604]
Hello all,

We are using the latest version of CubeCart and have discovered that thousands of cache files are being saved in the /cache/ directory on the server, filling it up and costing us server space.

Are they needed and can they be stopped and removed?

TIA.

**Comment by bhsmither** [comment]
We know this happens, but in your case, do you think this might be a bug?

If not, we can discuss it on the forums.

**Comment by pmycroft** [comment]
Hi Brian,

Sorry, but I do not know if this is a bug or not. I see thousands of cache files in that directory and don't know where they are coming from or why.

![Screen Shot 2020-09-15 at 4 49 01 PM](https://user-images.githubusercontent.com/22687467/93404428-004e9700-f83f-11ea-8b6d-7f3f2bcb5ee5.png)

What do you think? TIA.

**Comment by bhsmither** [comment]
Let's discuss this in the forums.

You might also want to read:
https://forums.cubecart.com/topic/54222-inodes-limit-exceded/
and read the Github issues 2026 and 2051.

**Comment by abrookbanks** [comment]
I'm not sure what we can do. There could be a bug or permission issue causing it not to clear. How big is the actual folder in megabytes? Also how much do you pay for hosting (don't answer this)?

Bear in mind that budget hosting companies impose certain resource limits to up-sell more expensive packages. 

It would be better to use a memory based cache such as Memcached. More info here: https://support.cubecart.com/hc/en-gb/articles/360003831737-How-do-I-enable-APC-Memcached-Redis-or-xCache-

**Comment by pmycroft** [comment]
Thanks Al.

I read that thread and will pass on the info to my developer as I am unsure how to do this work and what issues it may cause.

**Comment by abrookbanks** [comment]
Best of luck. Please do post back if you find any issues.

**Comment by abrookbanks** [comment]
Can you try setting up a nightly cron to keep the folder empty?

e.g. `rm -rf /path/to/home/user/public_html/cache/*`

**Comment by abrookbanks** [comment]
I'm going to close this as I just don't think there is anything we can do. It has to be a permission issue at server level. I highly recommend using a memory cache instead of file.

**Comment by pmycroft** [comment]
Hi Al, thanks for trying.

I am now seeing an error on https://www.biggamesportscards.com/, could this be related?

 Warning: Cache data not written. in /homepages/16/d283680407/htdocs/cubecart4/classes/cache/file.class.php on line 262

How can I find a CubeCart dev to help me here and with that cron setup? Thanks.

**Comment by abrookbanks** [comment]
We have [support ](https://www.cubecart.com/technical-support)available if you need us.

**Comment by pmycroft** [comment]
Thanks for replying so quickly, Al. It seems that the server @ 1and1 has filled up again with those cache files so I will need help setting up the memory-based cache.

Does Option 1: $60.00 monthly + $70.00 setup, include the time involved to fix the problem?

TIA!

**Comment by abrookbanks** [comment]
Yes indeed. If we can't sort it we will refund you.

**Comment by pmycroft** [comment]
Okay, I am having a call with the client today so will let you know as soon as I can.

Thanks.

**Comment by pmycroft** [comment]
The client has approved the year contract so I will set that up for $600 now.

**Comment by abrookbanks** [comment]
The cache folder has been cleaned out and a cron setup to pull;

`https://www.example.com/index.php?debug-cache-clear=true` 

This issue is being monitored.
