### ISSUE TITLE
Debug Queries Cached Status to be Tweaked

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2605]
If caching has been disabled, the Queries section of the debug output still shows that queries were written to the cache.

In mysqli.class.php, near line 237, find:
```
            //Cache the result if needed
            if ($cache) {
                $this->_writeCache($this->_result, $this->_query);
            }
```
We will write the query to the cache - which will succeed or fail - the result of the attempt is ignored. One reason writing to the cache will fail is if caching has been disabled.

We then use `_sqlDebug()` to give a message to `Debug->debugSQL()` (which the return value is ignored), which will produce a `[CACHE WRITE]` when it didn't happen.

Suggest:
```
            //Cache the result if needed
            if ($cache && ($this->_writeCache($this->_result, $this->_query)) === false) {
                $cache = false; // Query not cached for some reason. Check error log and cache status.
            }
```

**Comment by abrookbanks** [comment]
Thanks, that's a great find.
