### ISSUE TITLE
Can't complete payment of a Pending Order

### ISSUE THREAD

**Issue by DACS21mm** [cubecart/v6#2606]
I have set the stock to reduce when an order is placed - Order goes to Pending. 

If a customer orders an item which has only 1 left in stock, when the order is made the stock goes to 0 (as expected).

When the customer logs back into that order and selects Make Payment The result is the Out of stock message, so can't complete the order. (although the item is reserved to that order). CC appears to be using the current stock status to decide on out of stock, but in the case of the pending order, the item has already been allocated, so can be paid for.

**Comment by abrookbanks** [comment]
The text "Make Payment" is strictly speaking "Re-order".

I'd suggest changing the store reduction time to "Processing".

**Comment by havenswift-hosting** [comment]
>The text "Make Payment" is strictly speaking "Re-order".

So if an order is at Pending status and a customer tries to "Complete Payment" it is actually trying to create a new order ?

If so, the wording is completely wrong and something like "Create new matching order" should be used instead although even this would be very clunky, confusing and poor UX - why would they want to re-order when they have already placed an order which they simply now want to pay for

Is there any reason why the order details cannot be loaded so the customer can complete payment for that order - this has got to provide the best UX for customers. A check would still need to be made on stock levels when in the basket but you wouldnt have a "re-order" from a customer trying to pay for an item already on an order causing problems

I agree that reducing stock at Processing is normally the best option and you dont get this out of stock problem (as much anyway)  then but there are use cases when reducing stock at Pending needs to be used, however, store owners should be advised / strongly warned that they should set the automatic cancellation of orders at Pending stage to a very short period of time.  That would fit with the use cases where reducing stock at Pending is needed anyway

**Comment by DACS21mm** [comment]
Not sure I understand. The customer has the ability to finish the payment, but that is causing the issue. 
Don't feel that Pending is a Re-Order state, the item is available in the basket and as such Make Payment should 'Work'
By store seduction time I assume you are referring to 'Reduce Stock Levels' in store settings - set to 'When the order is complete'
We are dealing with many single items for sale, so preferred stock reduction at the time of order creation, so as to prevent other online customers being able to select the same item during that time (however unlikely that may be)

**Comment by havenswift-hosting** [comment]
>By store seduction time I assume you are referring to 'Reduce Stock Levels' in store settings - set to 'When the order is complete'

No we are both saying it generally works better to set that to "When the order is Processing" ie paid for

However, with your situation when selling a lot of single items, it makes sense to have it set to "When order at Pending" BUT you have to ALSO change the setting to Cancel Pending orders to a very short time period (I would say approx 20 to 30 minutes) so that the item of stock being reserved in an unpaid for order is released.  This is how ticket systems work although they usually have a visible countdown in place

**Comment by havenswift-hosting** [comment]
However, in your example, a customer returning back to pay for a Pending order where he has reserved the one item of stock still isnt able to make payment which I believe is a bug

**Comment by DACS21mm** [comment]
Given the nature of our ‘shop’ it makes sense to set stock levels at the time of order - so we do need the customers ‘Make Payment’ button work

Regards

Dave Ashton
________________________________

**Comment by havenswift-hosting** [comment]
>Given the nature of our ‘shop’ it makes sense to set stock levels at the time of order - so we do need the customers ‘Make Payment’ button work

Agreed

**Comment by DACS21mm** [comment]
I am still hopeful of a solution to what I feel is a 'bug' in the cubecart system. Our shop is dealing with ONLY single item products, and as such we need to be able to allocate the stock to a customer at order time, NOT on payment. Simply, this does give us the opportunity to discuss with a potential buyer issues of Postage, Shipment etc which may fall out of the automated methods we have created.

**Comment by hairy-dog** [comment]
It feels to me as if a real-world requirement has led to modifying how the software is being used, and the imposed solution simply doesn't work with the existing functional design. So changes are being requested. This really isn't the correct approach. We should be going back to the details of the use case and seeing if there is a better way to do it. Unique products that are sold as one-offs are not rare. 
I'm very aware that I don't understand the requirements actually are, and I decided not think anyone else is either.
Let's hear more about the problem that's being addressed before discussing how to modify the software to enable one particular workaround.

**Comment by hairy-dog** [comment]
"decided not" should read "don't"

**Comment by abrookbanks** [comment]
... to edit :)

**Comment by havenswift-hosting** [comment]
>I'm very aware that I don't understand the requirements actually are, and I decided not think anyone else is either. Let's hear more about the problem that's being addressed before discussing how to modify the software to enable one particular workaround.

I think the OP and myself understand the problem very well and can replicate it in a real world situation. Al and myself have offered ideas for settings changes that will help the situation but this doesnt solve the problem entirely and therefore it is perfectly valid to request that changes are made that prevent the software working correctly in this situation !

**Comment by abrookbanks** [comment]
Yes it needs to just take payment. Regrettably the payment screen is a big part of the checkout with basket so it's not straightforward.

**Comment by DACS21mm** [comment]
Does this mean it will/may be implemented in a future update?

**Comment by abrookbanks** [comment]
Yes. :)

**Comment by bhsmither** [comment]
Has anyone put any work into this? Any notes made?

I want to work on this.

**Comment by abrookbanks** [comment]
Not that I'm aware of.
