### ISSUE TITLE
Invalid Parameter for preg_match()

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2607]
In `Order->validOrderID()`, a `preg_match` pattern uses a dash.

This dash is an actual dash and not a range identifier. So, the dash must either be:
--the first character in the collection, or
--escaped

**Comment by abrookbanks** [comment]
It seems to work fine as it is at https://regex101.com. What do you suggest? 
![Screenshot 2020-09-21 120742](https://user-images.githubusercontent.com/4520803/93759982-1bd0ed80-fc03-11ea-909d-a23ed772b7a4.jpg)

**Comment by bhsmither** [comment]
Sorry, please test the second preg_match: `preg_match('/[\w-\_]/', $order_id)`

**Comment by bhsmither** [comment]
And there should be a `+` after the collection. Otherwise, the pattern represents just one character (of several).

**Comment by bhsmither** [comment]
I tested this at regex101 and it passed.

However, this bug report discusses why this is so:
https://github.com/firasdib/Regex101/issues/1072
It is an issue with PCRE vs. PCRE2.

This page:
https://www.regular-expressions.info/charclass.html
has a summary:
"The hyphen can be included right after the opening bracket, or right before the closing bracket, or right after the negating caret. Both `[-x]` and `[x-]` match an x or a hyphen. `[^-x]` and `[^x-]` match any character that is not an x or a hyphen. This works in all flavors discussed in this tutorial. Hyphens at other positions in character classes *where they can’t form a range* may be interpreted as literals or as errors. Regex flavors are quite inconsistent about this."

**Comment by bhsmither** [comment]
Suggest: `preg_match('/[-\w\_]+/', $order_id)`
Although, the `underscore` is included in `\w`.

**Comment by abrookbanks** [comment]
Thanks Brian.
