### ISSUE TITLE
Code Review: Testing Array Element

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2613]
Trivial Notice:
SEO class, line 131, there is this:
```
if(isset($match[6]) && $match[6][0]=='&'){  
```
The `preg_match()` will return `$match[6]` but it could be empty. Thus, when PHP tests `isset()` with it being true, will then test against `$match[6][0]` which will cause PHP to issue:
```
Notice: Uninitialized string offset: 0
```
Knowing that `$match[6]` will be set, suggest:
```
if(!empty($match[6]) && $match[6][0]=='&'){  
```

**Comment by abrookbanks** [comment]
Thanks again!! :)
