### ISSUE TITLE
Password reset request should be recorded in Email Log

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2618]
As above

**Comment by abrookbanks** [comment]
Should or shouldn't?

**Comment by havenswift-hosting** [comment]
It doesnt appear to be currently (though havent checked code !) and should be

**Comment by abrookbanks** [comment]
It does.

![Screenshot 2020-10-08 105618](https://user-images.githubusercontent.com/4520803/95443944-20acd580-0955-11eb-9647-89a2ddbd89dc.jpg)
![Screenshot 2020-10-08 105602](https://user-images.githubusercontent.com/4520803/95443946-21456c00-0955-11eb-9b34-8a355dcf08d7.jpg)
