### ISSUE TITLE
SendNewsletter Logged Result Optimistic

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2619]
In `Newsletter->sendNewsletter()`, a message gets logged that the (Test)Newsletter was sent before the Mailer actually sends it.

Suggest the code in the `if()` tests, near lines 130 and 149, use the result of the `sendMail()` to determine if the (test)newsletter actually got sent, and log an appropriate message.

**Comment by abrookbanks** [comment]
Good find. Thanks.
