### ISSUE TITLE
Code Check: REGEX

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2620]
A number of statements use this:
```
preg_replace('/[^\w\-\_]/', '', $argument)
```
to remove all occurrences of unwanted characters.

In my opinion, this is faulty in that only the _first_ unwanted character is removed.

Suggest experimenting with:
```
REGEX: [^\w\-\_]
SUBSTITUTION: [empty string]
TEST: .......... (ten periods)
Modifier Flags: None
```
The result at regex101.com gives a result of nine periods.

However, when adding the /g 'global' flag, all unwanted characters are removed.

**Comment by bhsmither** [comment]
Never mind.

PHP does not use the /g modifier. (I am removing regex101.com from my browser's bookmark toolbar!)

**Comment by working-name** [comment]
https://3v4l.org/NM0hl

Think of it as `/g`: `$limit = -1`, whereas no global flag is `$limit =1`. That's how php chose to implement that.

**Comment by abrookbanks** [comment]
Thanks guys. Sounds like this can be closed. :)
