### ISSUE TITLE
Customers cannot register

### ISSUE THREAD

**Issue by channan88** [cubecart/v6#2621]
I have read all the previous posts about customers not being able to register but none of those fixes worked for me. I'm running the latest 6.2.9. Essentially, once a customer fills out the register form and clicks register, the page reloads but nothing actually happens. From then, the shop is essentially broken and you cannot add anything to the basket. I have tried restoring current version, removing some plug-ins and going to the standard foundation skin but nothing has fixed my issue.
My site is shop.perthkeghire.com.au
This is the latest error log:

[<strong>Notice</strong>] /home/perthkeg/public_html/shop/admin_wB5s1r/sources/settings.index.inc.php:186 - Undefined index: path
[<strong>Notice</strong>] /home/perthkeg/public_html/shop/admin_wB5s1r/sources/settings.errorlog.inc.php:69 - Undefined variable: smarty_data
[<strong>Notice</strong>] /home/perthkeg/public_html/shop/admin_wB5s1r/sources/maintenance.index.inc.php:441 - Undefined index: tablename
[<strong>Notice</strong>] /home/perthkeg/public_html/shop/admin_wB5s1r/sources/maintenance.index.inc.php:452 - Undefined index: db_none_selected
[<strong>Notice</strong>] /home/perthkeg/public_html/shop/classes/seo.class.php:501 - Undefined variable: title
[<strong>Notice</strong>] /home/perthkeg/public_html/shop/admin_wB5s1r/sources/settings.errorlog.inc.php:69 - Undefined variable: smarty_data
[<strong>Notice</strong>] /home/perthkeg/public_html/shop/classes/cart.class.php:850 - Undefined index: billing_address
[<strong>Notice</strong>] /home/perthkeg/public_html/shop/classes/cart.class.php:850 - Undefined index: billing_address
[<strong>Notice</strong>] /home/perthkeg/public_html/shop/classes/cart.class.php:859 - Undefined index: absolute_price
[<strong>Notice</strong>] /home/perthkeg/public_html/shop/classes/seo.class.php:501 - Undefined variable: title
[<strong>Notice</strong>] /home/perthkeg/public_html/shop/classes/cubecart.class.php:237 - Undefined index: source
[<strong>Notice</strong>] /home/perthkeg/public_html/shop/classes/cart.class.php:850 - Undefined index: billing_address
[<strong>Notice</strong>] /home/perthkeg/public_html/shop/classes/cart.class.php:850 - Undefined index: billing_address
[<strong>Notice</strong>] /home/perthkeg/public_html/shop/classes/cart.class.php:859 - Undefined index: absolute_price
[<strong>Notice</strong>] /home/perthkeg/public_html/shop/classes/seo.class.php:501 - Undefined variable: title
[<strong>Notice</strong>] /home/perthkeg/public_html/shop/classes/cart.class.php:422 - Undefined variable: stock_warning
[<strong>Notice</strong>] /home/perthkeg/public_html/shop/classes/cart.class.php:850 - Undefined index: billing_address
[<strong>Notice</strong>] /home/perthkeg/public_html/shop/classes/cart.class.php:850 - Undefined index: billing_address
[<strong>Notice</strong>] /home/perthkeg/public_html/shop/classes/cart.class.php:859 - Undefined index: absolute_price
[<strong>Notice</strong>] /home/perthkeg/public_html/shop/admin_wB5s1r/sources/settings.errorlog.inc.php:69 - Undefined variable: smarty_data
<strong>Notice</strong>] /home/perthkeg/public_html/shop/classes/seo.class.php:501 - Undefined variable: title
[<strong>Notice</strong>] /home/perthkeg/public_html/shop/classes/cubecart.class.php:237 - Undefined index: source
[<strong>Notice</strong>] /home/perthkeg/public_html/shop/classes/seo.class.php:501 - Undefined variable: title

Thanks for any help.

**Comment by abrookbanks** [comment]
Please open a support ticket or seek assistance on our forums. This  is not reproducible and needs to be investigated in your hosting environment/configuration.
