### ISSUE TITLE
Code Check: Manufacturer Query Component

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2622]
In `Catalogue->searchCatalogue()`, near line 1797, a string is being added to the `$where` array.

However, unlike everywhere else, this statement does not include a needed SQL keyword -- probably `AND`.

Without this, a malformed query results when search parameters include a selected manufacturer.

**Comment by Dirty-Butter** [comment]
This code change worked for me on 6.2.9 AND it also worked on the current commit of 6.4.0

https://forums.cubecart.com/topic/54048-php-725/?do=findComment&comment=244302

**Comment by Dirty-Butter** [comment]
https://forums.cubecart.com/topic/54048-php-725/?do=findComment&comment=244302

This has fixed the manufacturer search not only in 6.2.9 but also the current commit of 6.4.0

**Comment by abrookbanks** [comment]
Thanks for this.
