### ISSUE TITLE
Missing /images/sources/ Folder

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2623]
According to:
https://github.com/cubecart/v6/commit/aa757bd35e19c21fa02b92cff26e8e91e5ed9823#diff-21b2eed1e328a2c62fe4c17d51188bdea73450f29956dc5c8c95429313ddd72c
there seems to still be a missing /images/sources/ folder.

Not that it would **not** be a real problem for an upgrade to an existing site, but on a fresh install?

**Comment by abrookbanks** [comment]
Silly silly silly. Thanks Brian! :)
