### ISSUE TITLE
Upgrade 6.4.0.sql should be 6.4.0-b1.sql

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2627]
Also scripts/upgrade/6.4.0.php should be 6.4.0-b1.php.

Best scenario is to name them b2 to fix existing beta installs.

**Comment by bhsmither** [comment]
I was going to mention this, but then thought the better idea was to move away from using betas and release candidates as integral steps through the sequential upgrade process.

Just commenting, I feel betas should always be fresh installs. Beta testers could load a fresh install of any previous version (or a copy of an existing installation) as the base version to see how well the upgrade progresses.

**Comment by abrookbanks** [comment]
Agreed but we do need to test upgraded stores too.
