### ISSUE TITLE
Error testing 6.4.0b1

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2628]
Getting this in the PHP error_log on a site running the b1 release

[13-Oct-2020 12:25:47 UTC] PHP Warning:  Invalid argument supplied for foreach() in /home/XXXXXXXX/public_html/classes/ajax.class.php on line 188

**Comment by havenswift-hosting** [comment]
The line in this release is

`foreach ($dirs[$dir] as $parent => $folder) {`

**Comment by bhsmither** [comment]
This is an issue going way back. Waaaaayyyyy back.

**Comment by abrookbanks** [comment]
Thanks chaps.
