### ISSUE TITLE
NOT SOLVED 6.4.0 b2 not creating next custom_oid 

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#2629]
I've tried two test orders taken all the way to PayPal on dirtybutterestates.com live site. Both orders failed to create the next order number.
Error log shows all details of the order, but the last part is Duplicate entry '2020-EC-19' for key 'custom_oid'  - that was the last order placed successfully on 6.2.9.

**Comment by bhsmither** [comment]
Issue #2439 may be applicable.

**Comment by Dirty-Butter** [comment]
I tired replacing stock with your edit, but it still is not creating the order at all.
`$GLOBALS['db']->misc("CREATE TRIGGER `custom_oid` BEFORE INSERT ON `".$GLOBALS['config']->get('config', 'dbprefix')."CubeCart_order_summary` FOR EACH ROW SET NEW.custom_oid = ".str_replace('`id`', "(SELECT `auto_increment` FROM INFORMATION_SCHEMA.TABLES WHERE table_schema = '".$GLOBALS['config']->get('config', 'dbdatabase')."' AND table_name = '".$GLOBALS['config']->get('config', 'dbprefix')."CubeCart_order_summary')", $concat));`

**Comment by Dirty-Butter** [comment]
When I check the CubeCart_invoice_template table in cpanel should I see a list of triggers, because I do not.

**Comment by bhsmither** [comment]
I see that the TRIGGER should be on CubeCart_order_summary.

**Comment by Dirty-Butter** [comment]
Confirmed there is a trigger.
Name custom_oid
Action SET NEW.custom_oid = CONCAT(DATE_FORMAT(NOW(), '%Y-EC-'), LPAD(LAST_INSERT_ID()+0, 2, 0), '')
Time BEFORE
Event INSERT

**Comment by Dirty-Butter** [comment]
After checking all code again I found my mistake. Working properly now.

**Comment by Dirty-Butter** [comment]
Well my test order worked, but now we have a customer whose order does not show anywhere but in the error log. Save error of Duplicate order number, so the order is not created. I have not added the last few days tweaks to dirtybutterestates.com, but they don't seem to have any relationship to order creation.
I chose this site for my live test because we don't advertise it, and it's only had 2 orders this whole year LOL.

**Comment by abrookbanks** [comment]
MySQL triggers are buggy. I don't know how to solve this.

**Comment by Dirty-Butter** [comment]
In my total ignorance of coding, it seems like it would need to take the custom_oid of the most recent order_date in CubeCart_order_summary and plus one it.

**Comment by bhsmither** [comment]
That is one way to do it, but there is a danger of collision.

That is, on a **very, very** busy site, where sales happen on the order of dozens per second, by the time the code gets the latest order number from the database server, adds one to it, and gets ready to save back a new record, there could be several other sales using that and neighboring numbers already.

Even the different trigger suggested above might not be able to get away from this, unless the database server locks the table during the microseconds it takes to execute the trigger.
