### ISSUE TITLE
Problems adding products to cart on small mobile devices

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2631]
Using foundation based skins, when on small mobile devices, the quantity field disappears (normally expect to hit "Add to basket" multiple times to add more than one item to the cart.

However, if you have a minimum purchase quantity set for that product, and that is set to be greater than 1, it is impossible to add products to the cart as it fails this test first

**Comment by abrookbanks** [comment]
Minimum purchase quantity being a mod? Any chance I can take a look at this store?

**Comment by havenswift-hosting** [comment]
It is part of core !  Column on inventory table is CubeCart_inventory.minimum_quantity

**Comment by abrookbanks** [comment]
is it!? Haha ok...

**Comment by havenswift-hosting** [comment]
LOL - Not used by many people and I had to double check it as well

**Comment by abrookbanks** [comment]
This was a really good find thanks Ian.
