### ISSUE TITLE
Email Template Editor to be ACE

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2632]
As commented in #2285, maybe we can try moving to ACE for CC640 -- now that we've got that cursor positioning problem fixed.

**Comment by bhsmither** [comment]
In `documents.email.php`, find near line 185:
```
  <div id="email_html" class="tab_content">
    <h3>{$LANG.email.title_content_html}</h3>
        <textarea name="template[content_html]" id="template_html" class="fck fck-full" data-fck-height="450">{$TEMPLATE.content_html|escape:"html"}</textarea>
```
Change to:
```
  <div id="email_html" class="tab_content">
    <h3>{$LANG.email.title_content_html}</h3>
{* CKEditor  <textarea name="template[content_html]" id="template_html" class="fck fck-full" data-fck-height="450">{$TEMPLATE.content_html|escape:"html"}</textarea> *}
{* The ACE editor *}
    <div id="template_html" style="text-indent:0!important;width:100%;height:600px;border:1px solid grey;"></div>
        <input type="hidden" name="template[content_html]" id="template_content_html" class="textbox">
        <script src="includes/ace/src-min-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>
        <script>
            var input = document.getElementById('template_content_html');
            var editor = ace.edit("template_html");
            editor.session.setUseWrapMode(true);
            editor.setOptions({ highlightActiveLine:true, showPrintMargin:false, theme:'ace/theme/github', mode: 'ace/mode/smarty' });
            editor.setValue(`{$TEMPLATE.content_html|escape:'quotes'}`, 1);
            editor.getSession().on("change", function () { input.value = editor.getSession().getValue(); });
        </script>
        <button type="button" class="button" id="preview_email_template" onclick="previewEmailTemplate()">{$LANG.common.test}</button></span>
        <script>
            function previewEmailTemplate() { $.colorbox({ html:function(){ return editor.getSession().getValue(); } }) };
        </script>
{* *}
```
There is a "Test" button (currently located below the editor) to give as best a colorbox display of the result as is possible.

**Comment by abrookbanks** [comment]
I'm on the fence with this a bit. There seems to be a case for both (html editor is mainly macros and hard to use). What is `yexybox`?

It would be cool if the preview has sample values maybe.

**Comment by abrookbanks** [comment]
The test (preview) doesn't work well because it takes styles from the page.

**Comment by bhsmither** [comment]
The `yexybox` is detritus. I was making experiments at sizing the editor with the `textbox` style. (Fixed OP.)

"Takes styles from the page" - Then that is a fault with the ColorBox plugin. We need to explore if a colorbox can be isolated from outside influence. Calling the colorbox has an `iframe` capability.

I can see enhancing the macro array for `TEMPLATE_MACROS` with placeholder phrases.

**Comment by bhsmither** [comment]
I am experimenting with:
```
function previewEmailTemplate() {
  $.colorbox({
    iframe:true,
    width:400,
    height:300,
    html:function(){
      return editor.getSession().getValue();
    }
  })
};
```
but getting a blank iframe. This is, more or less, exactly what it looks like in the examples.

Experimenting with numerous variations all have results that the content will just not get sent to the iframed colorbox.

**Comment by hairy-dog** [comment]
Is there a way I can make the content editor ONLY offer source editing? At present it drives me loopy. I really don't want ' to be converted to #&39; every time!

**Comment by abrookbanks** [comment]
You can indeed.
https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-startupMode 

To do this edit the file v6/includes/ckeditor/ckeditor.js

Add;
`config.startupMode = 'source';`

**Comment by hairy-dog** [comment]
That seems to have sorted it, thanks. And now the editor doesn't mangle html any more!

**Comment by abrookbanks** [comment]
Great.

**Comment by bhsmither** [comment]
It (CKEditor) will. Give it time.

**Comment by bhsmither** [comment]
Switching to WYSIWYG (non-Source) mode will allow CKEditor to replace certain characters with their entities - if within a "text node" - as that is 'best practice'. That is, quotes to delineate attribute values in tags are not disturbed.

But, if you really want to have real single quotes in text left undisturbed when viewing in non-Source mode, add this to `config.js`:
```
config.entities_additional = ''; // defaults to '#39'
```
Note:
Additionally, CKEditor creates for itself an `iframe`, to display its editing window, and loads additional javascript files, including `config.js`, while in that `iframe`. I have had enormous difficulty forcing Firefox to reload page resources, instead of using its cache, that were called from within that `iframe`. I hope you have better luck.

**Comment by hairy-dog** [comment]
As long as you never click the button to open the non-source editor, it seems to be OK 

#39 is simply wrong. &quot; or &lsqou; or &ldqou; etc are correct. #39 is not. You may as well use '

It's not just that: it also messes with other parts of the html. I'd much prefer to just have a simple text editor

**Comment by abrookbanks** [comment]
Thanks all. I think this makes a lot of sense. The test button is great. Thanks.
