### ISSUE TITLE
PayPal Standard reports an error

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2633]
The test endpoint button for the PayPal standard module appears to be throwing the same error across a number of sites I've checked today.

cURL Error (NA): cURL is installed but may be disabled by the host. cURL exec returns false.

However, the module itself is working correctly and you can checkout as a customer.

**Comment by havenswift-hosting** [comment]
Also have reports of this from several customers - the module does still work and processes transactions

**Comment by hairy-dog** [comment]
Over the last couple of months, various e-commerce website I look after have had numerous problems the PayPal. None of them using cubecart, none of them with anything wrong with them.

**Comment by abrookbanks** [comment]
Move them to PayPal Commerce is the best option but I'll look at this.

**Comment by havenswift-hosting** [comment]
Where possible that has been done with many sites but as discussed elsewhere, there are many sites where PayPal Commerce doesnt work and with it's current implementation, will never be installed by them.  If PayPal Standard is unsupported going forward then errors like this will start to happen and eventually some changes by PayPal will cause this plugin to break and at that stage these customers will almost certainly move away - already moved quite a few from PayPal to Stripe already

**Comment by hairy-dog** [comment]
We have moved everyone onto Stripe.

**Comment by abrookbanks** [comment]
Stripe and PayPal Commerce are my recommendations. The latter is a better technical/feature integration though.

**Comment by abrookbanks** [comment]
The PayPal Standard integration is so old and express checkout which is part of PayPal Commerce has so many clear advantages not to mention direct card payments and alternate payment methods such as Giropay, Credit, Sofort, Ideal etc... We encourage all merchants to make the move as its seems like a no brainer.

**Comment by abrookbanks** [comment]
@havenswift-hosting it would be interesting to know in what way it doesn't work for them? I know my contacts at PP would be genuinely grateful to hear about such cases. It could lead to product or integrational changes to help make it work for them.

**Comment by havenswift-hosting** [comment]
Immediately off the top of my head, two reasons that have been discussed several times before are that Express by-passes customer comments and also the requirement to agree to terms and conditions.  There may be others and by the sound of it @hairydogltd customers may also have specific requirements

**Comment by hairy-dog** [comment]
The reason for the move from PayPal was just reliability. A (varying) percentage of payments were failing, but PayPal support were as useless as ever in investigating or helping to find a fix.

**Comment by abrookbanks** [comment]
How were they failing? Do you mean payment failed or notification to your store failed?

**Comment by hairy-dog** [comment]
Timeouts in PayPal server responses, usually, but not always. Errors that had not been there before (nothing had changed at our end) and that went away when we switched to Stripe.
I think that PayPal servers were overloading due to Covid-related increases in online payments, but that's only my guess. If PayPal support could be persuaded to help and investigate, we might know.

**Comment by abrookbanks** [comment]
I release 1.0.10 which just removes this tool. I've never seen a case where it didn't work. I believe it was to test the HTTP 1.1 protocol when PayPal changed their security requirements which is standard now.
