### ISSUE TITLE
Cubecart 6.04

### ISSUE THREAD

**Issue by windsurfer51** [cubecart/v6#2636]
I am looking through some files and i noticed some peculiarities in admin\skins\default\templates\products.index.php   file

Line 407                <td>{$LANG.catalogue.absolute_price} *</td> (should the asterisk be there ?)
Line 509   <div>* {$LANG.catalogue.absolute_price_explained}</div> (should the asterisk be there ?)

**Comment by windsurfer51** [comment]
Okay that didn't come out right, the asterisk is not showing
![image](https://user-images.githubusercontent.com/73485384/97191071-e0cf5600-177c-11eb-83ba-89c1339d22b9.png)
![image](https://user-images.githubusercontent.com/73485384/97191114-edec4500-177c-11eb-845e-7cefe16313b5.png)

**Comment by bhsmither** [comment]
I think a better solution would be to put a blue 'information' icon that, when hovered over, would pop up a 'tooltip' to show what including this value does to the price of the item.

As it is used here, it is exactly the same that you would see in the text of any article to reference an explanatory footnote elsewhere.
