### ISSUE TITLE
Spell Check

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2637]
For CC640, check spelling:
Value for /language/definitions.xml: group=filemanager: string=search_location
Hard-coded phrase in admin template products.index.php: near line 586:
```
            {if $GALLERY_JSON}
            <div id="gallery_json">
               <p>Other includes images</p>
```
Should be a language string, and grammatically should be "Other included images". Perhaps "Other assigned images".

**Comment by abrookbanks** [comment]
Well spotted. I have to admit that I'll never be able to spell or spot typos!
