### ISSUE TITLE
KB Clarification

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2638]
In:
https://support.cubecart.com/hc/en-gb/articles/360003831737-How-do-I-enable-APC-Memcached-Redis-or-xCache-
suggest mentioning that because the session data location has changed, all users of the site should be fully logged out. Otherwise strange results will manifest.

**Comment by bhsmither** [comment]
Also, all base code suggests the value to use the filesystem as the session repository is `files`.

However, this is stated in the KB:
```
To use Memcache or Memcached whilst keeping standard session storage please add this line to the includes/global.inc.php file (CubeCart 6.2.10 onwards).

$glob['session_save_handler'] = 'file';

If in doubt please set the value to 'file' which will be compatible with all server configurations.
```
I believe the value should be 'files'.

**Comment by havenswift-hosting** [comment]
> To use Memcache or Memcached whilst keeping standard session storage please add this line to the includes/global.inc.php file (CubeCart 6.2.10 onwards).

> $glob['session_save_handler'] = 'file';

> If in doubt please set the value to 'file' which will be compatible with all server configurations.

This whole section is invalid as of 6.4.0 (session handling via memcache has been removed for now) and also prior to 6.2.9 (as it wasnt implemented before then)

**Comment by bhsmither** [comment]
If, as you say, nothing really changed - which I take to mean that this statement is ignored - I shouldn't have lost any sessions.

But I did:
https://forums.cubecart.com/topic/56390-getting-white-screen-after-629-upgrade-from-626/

**Comment by bhsmither** [comment]
Happily, doing the exact same thing as earlier, but switching from `memcached` to `redis`, I did not lose any sessions.

Something, I believe, is still looking at `$glob['session_save_handler']` and not finding 'file'.

**Comment by abrookbanks** [comment]
Thanks. Article updated. 

Memcached session management proved just too buggy. Frustrating.
