### ISSUE TITLE
Memcached Stats

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2639]
In the Memcached class, `_printStats()` function, the data includes:
```
        $output .= "<tr><td>Number of keys that have been requested and found present </td><td>".$data["get_hits"]." ($percCacheHit%)</td></tr>";
        $output .= "<tr><td>Number of items that have been requested and not found </td><td>".$data["get_misses"]." ($percCacheMiss%)</td></tr>";
```
On a newby's initial read, one could infer that the data is for this page request only. But it seems that this is not the case.

I was getting perplexed when the hits value grew into the thousands, and the misses value stayed steady but extraordinarily high.

I concluded that almost all of this is a cumulative report and serves no valid diagnostic purpose with respect to per-page analysis. Much of it can be forever ignored. (But , so what?)

I am not familiar with Memcached, but perhaps there is a way to clear the hits and misses from the memcached server after each page delivery - maybe on cache destruction.

Maybe just report a simple "Cache Used" statement similar to "Files".

And, nobody uses **Mega Bytes** anymore. It's **MiB**.

**Comment by abrookbanks** [comment]
Closing as I think this is fine as it is. Some info might not be that handy but nevermind.
