### ISSUE TITLE
Code Review: Files Cache Usage

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2641]
As best I can tell, most cache stats generally state hits and misses. (The stats also may state a few parameters in Bytes.)

So, I call into question the Usage Report of 'Files' cache being expressed as a total of filesizes (in bytes).

I find this result to be counter to what I would expect, namely, to ask:

How many requests were found in the cache - regardless of the amount of data contained in that hit?

**Comment by abrookbanks** [comment]
<img width="267" alt="Screenshot 2022-12-06 at 15 51 28" src="https://user-images.githubusercontent.com/4520803/205959315-e665c8e7-6cf6-4ab9-8fe7-de58e2c591ca.png">
