### ISSUE TITLE
Code Check: Can Redis->set() Fail?

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2642]
`Redis->write()` (`set()` near line 273 in redis.class.php) is not checked for success (like it is in the other methods of cache).

**Comment by bhsmither** [comment]
Also, can it be set to expire (like it is in memcache/d, and meta in files)?

And there is no check to make sure `json_encode` was successful.

**Comment by abrookbanks** [comment]
From what I can see it doesn't return a boolean value.
