### ISSUE TITLE
Lost Use of Sub-Apps

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2644]
Regarding #1164, it is now (probably) impossible to have a sub-application in a sub-folder. Having lost the rewrite pattern to include `.html` at the end invites a large amount of ambiguity.

Which is to say, an application here:
`www.example.com/myapp/index.php`
**must** have always a findable document.

If the app uses links that presume to use an available default document (i.e., index.php) without having to explicitly include it (CubeCart - looking at you!), gets Cubecart's 404 page.

**Comment by abrookbanks** [comment]
Good to bear in mind. We can cross this bridge if/when it arises.

**Comment by bhsmither** [comment]
I put phpRedisAdmin in a sub-folder. Didn't have to, but I did.

Guess what? No `index.php` on some code.

Took a while to find it, but it was one edit.

I am also finding instances of `?seo_path=` on some URLs. Tracking it down.
