### ISSUE TITLE
Errors appearing in error log

### ISSUE THREAD

**Issue by richosr** [cubecart/v6#2646]
I am getting the following errors appearing in the error log frequently.
Any ideas on how I can resolve these would be appreciated.

![image](https://user-images.githubusercontent.com/992654/97771318-253c6680-1b6e-11eb-8ed4-c7f835b55729.png)

**Comment by bhsmither** [comment]
This is someone yanking your chain.

A search is being made and the page number of the results is being changed to be a stupidly high number -- so high that PHP is converting that number into scientific notation (the E+14 at the end of the number).

True, it is annoying, but not dangerous.

**Comment by abrookbanks** [comment]
I'm pretty sure this is a duplicate which has been fixed but I'm not 100% sure. Please can we reopen if this isn't resolved with 6.4.0 which will have improved backtracking to help debug it too.
