### ISSUE TITLE
Code Check: Taxes

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2651]
Regarding issue #724 and commit https://github.com/cubecart/v6/commit/413844155bd3a82ae485e9690ea8482cec4b22bc, I see that only the pattern for the function `sprintf()` was removed, where I think the intent was to remove the actual function.

PHP 7 is complaining of:
```
Trying to access array offset on value of type bool, '/classes/tax.class.php', line 106
```
which is how I found this (which is a separate issue).

**Comment by abrookbanks** [comment]
Fixed with 2cb8315ff6d51ddc9891dbb3bc488cafa9c32a50 (typo on commit)
