### ISSUE TITLE
Code Check: Variable Types

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2652]
PHP 7 is complaining of:
```
Trying to access array offset on value of type bool, '/classes/tax.class.php', line 106
```
Throughout this class, `_tax_table` and relatives holds an array of floats.

Yet, at the class declarations, these and other attributes are set to be boolean. (Also in `function taxReset()`.)

Perhaps a better choice would be empty arrays?

**Comment by abrookbanks** [comment]
Thanks
