### ISSUE TITLE
[6.4.0/6.4.1] Issue with SQL statement in admin/sources/dashboard.index.inc.php

### ISSUE THREAD

**Issue by wiiaboo** [cubecart/v6#2654]
Since the upgrade to 6.4.x, everytime a user goes to the Admin dashboard, this error shows up in the System Error Logs:
```
File: [dashboard.index.inc.php] Line: [368] "SELECT I.name, I.product_code, I.stock_level AS I_stock_level, I.stock_warning AS I_stock_warning, I.product_id, M.stock_level AS M_stock_level, M.use_stock as M_use_stock, M.cached_name FROM `CubeCart_inventory` AS `I` LEFT JOIN `CubeCart_option_matrix` AS `M` on `I`.`product_id` = `M`.`product_id` WHERE use_stock_level = 1 AND ((M.status = 1 AND M.use_stock = 1 AND M.stock_level <= ) OR (I.stock_level <= )) ;" - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') OR (I.stock_level <= ))' at line 1 
```

Checking the code, the variable that's supposed to have some value is `$condition` (line 343), but I don't see how that's failing to do this check properly:
https://github.com/cubecart/v6/blob/8bb19d46ad36050ecfb7a766f4f5ed20f4a19b4a/admin/sources/dashboard.index.inc.php#L343-L344

My `stock_warn_type` setting is at `0`, by the way (literally `"0"`, checking directly in Cubecart_config.config).
```json
{
    "stock_warn_type": "0",
    "stock_warn_level": "",
    "stock_change_time": "2",
    "hide_out_of_stock": "",
}
```

**Comment by wiiaboo** [comment]
Changing the code to this fixes the SQL statement, but I don't know how correct/safe this is:

```diff
--- a/admin/sources/dashboard.index.inc.php	2020-11-10 22:00:34.506525566 +0000
+++ b/admin/sources/dashboard.index.inc.php	2020-11-11 14:05:58.293851055 +0000
@@ -340,7 +340,7 @@
 $tables = '`'.$GLOBALS['config']->get('config', 'dbprefix').'CubeCart_inventory` AS `I` LEFT JOIN `'.$GLOBALS['config']->get('config', 'dbprefix').'CubeCart_option_matrix` AS `M` on `I`.`product_id` = `M`.`product_id`';

 $fields = 'I.name, I.product_code, I.stock_level AS I_stock_level, I.stock_warning AS I_stock_warning, I.product_id, M.stock_level AS M_stock_level, M.use_stock as M_use_stock, M.cached_name';
-$condition = $GLOBALS['config']->get('config', 'stock_warn_type') == '1' ? 'I.stock_warning' : $GLOBALS['config']->get('config', 'stock_warn_level');
+$condition = $GLOBALS['config']->get('config', 'stock_warn_type') == '1' ? 'I.stock_warning' : (int)$GLOBALS['config']->get('config', 'stock_warn_level');
 $where = "use_stock_level = 1 AND ((M.status = 1 AND M.use_stock = 1 AND M.stock_level <= $condition) OR (I.stock_level <= $condition))";
 // Stock Warnings Sort
 if (!isset($_GET['sort']) || !is_array($_GET['sort'])) {
```

**Comment by bhsmither** [comment]
Your config sample has `stock_warn_level` as being empty.

Please verify in your admin Store Settings, Stock tab, "Global stock warning level" has an integer value being used.

**Comment by wiiaboo** [comment]
> 
> 
> Your config sample has `stock_warn_level` as being empty.
> 
> Please verify in your admin Store Settings, Stock tab, "Global stock warning level" has an integer value being used.

I checked directly on the database, it's `"0"`.

> My `stock_warn_type` setting is at `0`, by the way (literally `"0"`, checking directly in Cubecart_config.config).
> 
> ```json
> {
>     "stock_warn_type": "0",
>     "stock_warn_level": "",
>     "stock_change_time": "2",
>     "hide_out_of_stock": "",
> }
> ```

![screenshot of the html code](https://c.tsu.re/EQ.png)

**Comment by bhsmither** [comment]
I am asking for `stock_warn_level`.

The `$condition` variable will be either the literal string `I.stock_warning` or the value held in the config setting `stock_warn_level`.

**Comment by wiiaboo** [comment]
Oh, OK, I misread and thought they were the same.
But empty is the default. I've never configured this or unset it.

**Comment by wiiaboo** [comment]
Setting it to 0 also fixes it. And I see in setup that the default value is supposed to be `'5'`. My store install comes back from v3 or something, so it's quite old.

**Comment by abrookbanks** [comment]
Thanks this is actually fixed in another issue. Sorry if I missed this one first.
