### ISSUE TITLE
Suggestion to improve font on Admin Search input

### ISSUE THREAD

**Issue by wiiaboo** [cubecart/v6#2656]
https://github.com/cubecart/v6/blob/8bb19d46ad36050ecfb7a766f4f5ed20f4a19b4a/admin/skins/default/styles/layout.css#L838

could instead be
```css
font-family: 'Open Sans', sans-serif, FontAwesome;
```
and then it will look as the rest of the interface, and the Font-Awesome icon will use FontAwesome as expected, at least on Firefox.

**Comment by abrookbanks** [comment]
Thanks for this!! :)
