### ISSUE TITLE
SEO->setdbPath - Check dynamic $type has a valid $item_id

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2657]
As above. It should return false if the conditions are not met.

```
if(in_array($type, $this->_dynamic_sections) && (int)$item_id <= 0) {
  return false;
}
```

**Comment by bhsmither** [comment]
Your fix will certainly work -- until the caller can't handle a `false` result. One such caller is `SEO->buildURL()` at the last `return`.

One (perhaps only) reason this* will happen is during checkout when CubeCart queries for Related Products. If any of the past XX orders have a Gift Certificate (product_id 0 or _null_), CubeCart will include this item in a loop near the end of `CubeCart->_displayBasket()`.

The loop is fetching all that is needed for a product panel, including an SEO-friendly URL, which the GC is not a dynamic section, but calling `buildURL()` is asserting that such is the case.

For the case of a GC, this query:
```
if (($related_products = $GLOBALS['db']->select('CubeCart_order_inventory', array('DISTINCT' => 'product_id'), array('cart_order_id' => $related, '!product_id' => $product_list), false, 3)) !== false) {
```
should have prepared `$product_list` by adding 0 to the array -- to not include a GC as a related product.

* The result of _this_ is that there will be entries on CubeCart_seo_urls having:
```
"184"	".html"	"prod"	"0"	"0"	"0"
"185"	"-p.html"	"prod"	"0"	"0"	"0"
"211"	"-p1.html"	"prod"	"0"	"0"	"0"
```
and the database server reporting:
```
Line: [726] "INSERT INTO `CubeCart_seo_urls` (`type`,`item_id`,`path`,`custom`) VALUES ('prod','','-p.html','0');" - Duplicate entry '-p.html' for key 'PRIMARY'
```

**Comment by bhsmither** [comment]
Another case is when the admin adds an arbitrary item to an existing order, something that isn't in the established inventory.

**Comment by abrookbanks** [comment]
> Another case is when the admin adds an arbitrary item to an existing order, something that isn't in the established inventory.

Figured out where? I appreciate your help because my workload is at 900% right now.

**Comment by bhsmither** [comment]
When an admin adds an arbitrary item to an existing order's inventory, it is impossible for there to be a `product_id`. Thus, when the added arbitrary item gets added to `CubeCart_order_inventory`, it becomes the source of the resulting SEO path problem just like GCs.

Making the change to the Related Products SQL query will also handle this source of incompatible data.
