### ISSUE TITLE
Admin Navigation >>> Marketplace

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#266]
Request that an icon be added next to Plugins: Marketplace to indicate clicking this link will (unless a hook interferes) immediately take to you to an off-site web page.

**Comment by abrookbanks** [comment]
![screen shot 2015-02-23 at 10 29 53](https://cloud.githubusercontent.com/assets/4520803/6326183/f347fce4-bb46-11e4-8a27-a7719e02c9b4.png)
