### ISSUE TITLE
Admin Tabbing Issue When Cache is Disabled

### ISSUE THREAD

**Issue by NiteTowerDesign** [cubecart/v6#2663]
Seems when the cache is disabled it causes a JS issue affecting Admin tabs

Info from browser : 

"Uncaught TypeError: cannot read property 'split' of undefined "
admin.js - 671
var ccp = cc.split("#");

bsmither seems to have dug into it more at [https://forums.cubecart.com/topic/56437-firefox-vs-edge/?do=findComment&comment=244754](https://forums.cubecart.com/topic/56437-firefox-vs-edge/?do=findComment&comment=244754)

**Comment by abrookbanks** [comment]
Thanks so much for this! :)
