### ISSUE TITLE
Code Review: Redirects List Screen

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2665]
The **Item ID** column has a text entry field typed as a number. This adds a spinner to the field that seems to offer so very little UI to the task of choosing the `item_id`.

Mouse-clicking the spinner does nothing.

Keyboard cursor-up and -down works, as does actual text entry.

However, because the path retrieved is variable in length, even if the mouse-clicker spinner worked, the **Destination** column would cause the spinner in the **Item ID** column to be bouncing all over the place.

Suggest re-ordering the table as follows:
Action, Status Code, Page, Redirect from Path, Item ID, Redirect to Destination

**Comment by bhsmither** [comment]
Additionally, the **Item ID** value can be spun down to zero and into the negative numbers.

When the value shown here no longer represents a valid item, the **Destination** field does not clear. And when the value goes to -1 and -2 (but not -3 and beyond), there is shown a **Destination** that corresponds to 2 and 1 respectively.

**Comment by abrookbanks** [comment]
Fab. Thanks!
