### ISSUE TITLE
Code Review: Category SEO Empty Path

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2666]
In `categories.index.inc.php`, near line 84, a test is made for an empty `POST['seo_path']`.

Since POSTing an edited item with an empty path is no longer deleted from the database (was CC629), there is no longer any need to `rebuildCategoryList()` at this point.

**Comment by abrookbanks** [comment]
This has been resolved with https://github.com/cubecart/v6/commit/8de9c4f255d6f807cb7dddd5342dd0e29da8986d 

Thanks.
