### ISSUE TITLE
File: [cart.class.php] Line: [533] "SELECT SQL_CALC_FOUND_ROWS `used` FROM `CubeCart_customer_coupon` WHERE ... OR `customer_id` = LIMIT 1;"

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2667]

**Comment by abrookbanks** [comment]
Typo in commit. See https://github.com/cubecart/v6/commit/08df7335152731b9e005b6b8fd3f284f2e8bce13

**Comment by bhsmither** [comment]
Comment:

If `$customer_id` evaluates to a zero-length-string, then something is not getting set correctly where `$customer_id` is getting a value assigned to it.

That would mean either:
- `$this->basket['customer']['customer_id']` is not set, and `$this->basket['billing_address']['customer_id']` is not set or has no value, or
- `$this->basket['customer']['customer_id']` is set and has no value.

With debug switched on, what does `__basket` show at checkout?

My installation shows: 
`$this->basket['billing_address']['customer_id']` = 5.

So, `5` will show up in the original query as part of the string - not requiring the value to be force cast to an integer and concatenated to the string. Casting any string to an integer will always get you zero.
