### ISSUE TITLE
Make number of times that exit modal is shown configurable

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2668]
Currently, the exit modal only shows once and what would be great, is to make this configurable via a setting

**Comment by bhsmither** [comment]
Currently, showing the modal is determined by the absence of a cookie. No cookie? Show the modal and set a 30 day cookie.

What visitor behavior would this be counting? Is this on a per-customer basis?

**Comment by abrookbanks** [comment]
No it's quite dumb as you outlined.

**Comment by havenswift-hosting** [comment]
>>No it's quite dumb as you outlined.

Just love waking up early and being called dumb :)

>>Is this on a per-customer basis?

No of course not - it would have to be a store wide setting

>>Show the modal and set a 30 day cookie.

That is the whole point - why 30 days - who decides on that ?  This is what should be configurable

**Comment by bhsmither** [comment]
I hear you are asking to make the **time delay** on when the modal reappears (cookie expiration) a store setting.

**Comment by abrookbanks** [comment]
I wasn't calling anyone dumb LOL. I meant the way it currently works is pretty crude and basic (dumb).

**Comment by havenswift-hosting** [comment]
>>I hear you are asking to make the time delay on when the modal reappears (cookie expiration) a store setting.

Simply make the number of days that the cookie is set for configurable

>>I wasn't calling anyone dumb LOL. I meant the way it currently works is pretty crude and basic (dumb).

I realised that - hence the :)  Agreed that it is very basic and this is just a simple enhancement to make it a little more controllable - I am sure there are plenty of other enhancements.  One other option of course would be to never show it to logged in customers already registered for the newsletter
