### ISSUE TITLE
Maintenance Clear Logs (Activity, Error, Request) Leads To Blank Page

### ISSUE THREAD

**Issue by NiteTowerDesign** [cubecart/v6#2669]
As reported by iant [https://forums.cubecart.com/topic/56454-641-bug-report-clear-logs-leads-to-blank-white-screen/](https://forums.cubecart.com/topic/56454-641-bug-report-clear-logs-leads-to-blank-white-screen/l) 

**Steps to reproduce:- (6.4.0 & 6.4.1)** 

1. Admin > Maintenance > Rebuild

2. select clear error , admin activity, requests logs 

3. submit (leads to dead page although the action does appear to be carried out.)

**Comment by abrookbanks** [comment]
Thanks for reporting.
