### ISSUE TITLE
$GLOBALS['db']->insert() no longer returns the insertid on success, instead it is returning boolean true.

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2670]
This was working up until 6.4x

in earlier versions the insert queries would return the inserid, but it looks like it is now only ever returning boolean true which is breaking several bespoke features which are expecting the return to be the insertid.

**Comment by Noodleyman** [comment]
@abrookbanks 
To confirm, if I swap out the class files for DB with that of 6.2.9, everything works correctly. This is impacting a lot of modules and functionality, if it can be looked at as a priority it would be greatly appreciated.

**Comment by abrookbanks** [comment]
Thanks for this Alec.

**Comment by abrookbanks** [comment]
CubeCart too is very dependant on last insert ID and no issues have come up that I've seen. 

I can't see anything relevant changed in those files which quick compare. Was it just those two files you replaced?:
![Screenshot 2020-11-17 162206](https://user-images.githubusercontent.com/4520803/99416709-0c171200-28f1-11eb-963c-6aef2d59b0c4.jpg)
 
![Screenshot 2020-11-17 162134](https://user-images.githubusercontent.com/4520803/99416652-fc97c900-28f0-11eb-9279-ef77e7480c1e.jpg)

**Comment by Noodleyman** [comment]
I just tested each file, one at a time.

swapping out database.class.php between that of 6.2.9 and 6.4.1 is causing/fixing the issue, so it's something specific to that one file or something it references. I'm a little confused by it as well as there is very little difference between the two as you've stated.  I'm working through them to isolate a specific item... yet to find it.

**Comment by Noodleyman** [comment]
root cause is:
```
           if((int)$GLOBALS['session']->get('logins','admin_data') <= 3) {
                $GLOBALS['main']->successMessage($GLOBALS['language']->dashboard['cache_reminder']);
            }
```

**Comment by Noodleyman** [comment]
it's because of adminLog(), which does an insert.. before the return of the insert by the ACTUAL insert query...  as successMessage logs the event...

**Comment by abrookbanks** [comment]
Frustrating. I haven't seen any other bugs around this yet. I'll get it changed for 6.4.2.

**Comment by Noodleyman** [comment]
essentially, you need to call lastinsertid before any other actions write to the DB, however as it's now logging a message, it's writing additional data to the DB as part of the cacheing clear step.

untested, but an actual fix may be to swap these two lines around to capture the ID before cache is cleared

```
                $this->_clearCacheNotice($purge, $affected, $table);
                $insert_id = ($this->insertid()) ? $this->insertid() : true;
```

**Comment by abrookbanks** [comment]
Your fix is better. Please confirm as you have a means to test against your extension.

**Comment by Noodleyman** [comment]
fix confirmed, simply swapping those lines around resolves the issue.

**Comment by abrookbanks** [comment]
Thanks Alec. This should have come up in the long beta period. Never mind.

**Comment by Noodleyman** [comment]
at least it's a simple fix 👍 
unfortunately I wasn't able to do any beta testing due to time constraints

**Comment by abrookbanks** [comment]
No that's fine. Comment wasn't aimed at you.
