### ISSUE TITLE
Add search functionality to language

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2671]
It is often difficult to work out which section a language string is found under, so a search function that scanned all messages and presented any matching text pattern matches and then after selecting one, took the user to that string would be very helpful

**Comment by bhsmither** [comment]
I have started working on this.

**Comment by abrookbanks** [comment]
You absolute legend you!

**Comment by bhsmither** [comment]
This coming along nicely.

Still need to test when the admin is using language A while editing/searching on language B.

**Comment by abrookbanks** [comment]
Brilliant!!

**Comment by bhsmither** [comment]
[Language_Search_Edits.zip](https://github.com/cubecart/v6/files/6246696/Language_Search_Edits.zip)
This is what I have so far. Interested persons should beta test.

1. Choose a language to edit.
2. Enter a word or short phrase into the search field. Do not use 'wildcards' or quotes. The search is verbatim.
3. Click the **Go** button.
4. Results are shown in a table above the Group selector.

**Comment by abrookbanks** [comment]
I've opened this to look at early next week. Many thanks @bhsmither 

It's a long bank holiday here in the UK.

**Comment by abrookbanks** [comment]
Still WIP.
<img width="749" alt="Screenshot 2021-05-13 120457" src="https://user-images.githubusercontent.com/4520803/118117471-96918780-b3e3-11eb-8a62-e3b08f2a8e9e.png">

**Comment by abrookbanks** [comment]
This is much more involved than I first thought....

**Comment by abrookbanks** [comment]
<img width="743" alt="Screenshot 2021-05-13 124853" src="https://user-images.githubusercontent.com/4520803/118121598-9f855780-b3e9-11eb-91df-f7c4a2c026e5.png">

**Comment by abrookbanks** [comment]
Dyslexia got the better of me yet again... be134606c388e7e988b929a0d255e14f46962da2

**Comment by abrookbanks** [comment]
I think this is done and working really well. Thanks for doing the bulk of the legwork @bhsmither 

I'd be interested to see what you make of it.

**Comment by bhsmither** [comment]
Please be sure to catch the hard-coded titles, captions, and instructions. Convert them to strings in the definitions.xml file.

**Comment by abrookbanks** [comment]
Ah!

**Comment by abrookbanks** [comment]
I copied the issue number off last commit. See ac6e1dc9b1d17c0b7213e96854498f00bd3b66ad

**Comment by abrookbanks** [comment]
Happy with this now. Thanks.
