### ISSUE TITLE
Wrong Variable

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2673]
In settings.language.inc.php, near line 216, there is:
```
if (!preg_match('/^(modules)/', $_GET['type'])) {
```
At this point in the admin wanting to make edits to phrases, the key `'type'` is not in the `$_GET` array. It is instead in the `$_POST` array, but all other code wanting to use the key `'type'` gets it from the `$_REQUEST` array.

**Comment by abrookbanks** [comment]
Thanks Brian!
