### ISSUE TITLE
Feature Request: Add "Upgrade Lock" for customised stores

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2676]

**Comment by havenswift-hosting** [comment]
This is a great idea

**Comment by bhsmither** [comment]
What would this do - or prevent from doing?

**Comment by abrookbanks** [comment]
Block the auto update tool executing. Maybe add an email address to contact the right person for upgrade.

**Comment by bhsmither** [comment]
CubeCart has an auto-update tool?

**Comment by abrookbanks** [comment]
Yes in the maintenance section.

**Comment by abrookbanks** [comment]
Auto Upgrade is probably the better term.

**Comment by bhsmither** [comment]
I am recalling how my installation of Wordpress (no longer running) was truely automatic. It relied on a cron job -- no attention needed by me to keep it up to date.

I don't see how CubeCart's "Update" button is on same caliber.

One needs to have agency and manually start an upgrade process.

I am aware of store's changing the teams of techs who manage's the installation. But I would hope that some sort of documentation would indicate that the code is no longer stock. If so, why then would a 'lock-out' feature be necessary?

I guess I'm just nit-picking the term.

**Comment by abrookbanks** [comment]
Definitely nitpicking. 😂
