### ISSUE TITLE
Poorly performing query for popular products based on sales data

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2677]
The query on line 1233 classes/gui.class.php needs some work as it is very poorly performing !

**Comment by abrookbanks** [comment]
This will make a massive difference

**Comment by havenswift-hosting** [comment]
Brilliant - thanks !

**Comment by bhsmither** [comment]
This statement:
```
if (($content = $GLOBALS['cache']->read($cache_id, $serialize)) == false) {
```
says that if the cached file contains something false-like or is missing, then use the empty value in `$content`.

I believe you want:
```
if (($content = $GLOBALS['cache']->read($cache_id, $serialize)) !== false) {
```
which says if the cached file does exist and has valid content, use it. Otherwise, build one.

**Comment by bhsmither** [comment]
Also, the skin template box.popular.php is wrapped in a test for the truthiness of `$POPULAR`, which does not get set.

I would have suggested adding an assignment to `'POPULAR'` being `true` but the template is wanting to loop through it.

And then, where is `$POPULAR_PRODUCTS` used in the skin? (OK, I see that CC5 skins use this approach.)
