### ISSUE TITLE
Content Could Overflow

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#268]
The javascript says to make sure there is 100 extra pixels of `#page_content` to show a `div.tab` with lot's of content. But this check happens only when there is a change of showing a tab.
![admin_php__g statistics](https://cloud.githubusercontent.com/assets/4073092/6323624/a9d06e90-baea-11e4-84f6-5c0c481b9b1e.png)
When showing an initial tab on a fresh page load, this check is not done, and the content could be longer than `#page_content`.

**Comment by bhsmither** [comment]
Yes, the style is of CC5's admin skin, but this **is** CC6's admin.

**Comment by abrookbanks** [comment]
Can you show me an example how where this can be reproduced in v6? I agree that it *could*.. but I can't find any area where it actually does.

**Comment by bhsmither** [comment]
I think the styling of the CC6beta5 admin skin is such that this overflow does not readily present itself.

Now that I am **looking at CC6 admin** and comparing side-by-side the CC5 admin skin vs CC6beta5 admin skin, the one page where the overflow was evident in the CC5 skin does not happen in the beta5 skin. So, `unreproducible` with respect to beta5 skin.

However, on a side-note, I see that the Sales Statistics charts are (in my opinion) twice as tall as they need to be.
