### ISSUE TITLE
Customer Newsletter Unsubscribe Error Message

### ISSUE THREAD

**Issue by NiteTowerDesign** [cubecart/v6#2681]
When a logged in customer unsubscribes from newsletters via the newsletter page (index.php?_a=newsletter) it displays:

> The following errors were detected:
> That email address is not subscribed to our mailing list.

Seems you run 2 delete queries for logged in customers as you pass both the customer id and email address to the unsubscribe function so $removed which is used to determine whether to use setNotify or setError in newsletter.class.php gets overwritten by the last delete query.

**Comment by abrookbanks** [comment]
Got here eventually!! Thanks!!
