### ISSUE TITLE
Code Review: SEO AJAX Request

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2682]
In admin.js, starting at line 974, I can guess the task, but a lot of the details seem to be wrong.

Watching for a change anywhere on the tab_content `id="seo"`. When a change happens, test for the truthiness of the value of that tab_content. The value of the tab_content is an empty string. The test fails and `seo = "no_seo_code"`.

An AJAX request is made:
```
/admin.php?_g=xml&type=no_seo_code&function=get
```
AJAX::load() defaults to a `search('no_seo_code',"")`, which returns `false`.

Whatever is actually returned, is given to `id="htaccess"`, which does not exist.

The `function` data element needs to be reviewed, and the accompanying other data elements need to be corrected as required.

**Comment by abrookbanks** [comment]
I can't figure out what this is for unless it was coded to check if an SEO path was in use and never completed. I also can't see what htaccess has to do with it. 

Maybe this event just needs to be removed.

**Comment by abrookbanks** [comment]
I think this is a hangover from the past and therefore I've removed it. It may be from a version that had SEO on and off.
