### ISSUE TITLE
Code Review: Properly Closing the Database Connection

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2684]
In `mysqli.class.php`, near line 219, when dealing with `$result` being true-like, the `(is_bool)` section does not close the connection, but the `else` section does.

Not sure what best practice is, but perhaps use `$this->_db_connect_id->close()` just above `_stopTimer()`.

**Comment by abrookbanks** [comment]
Why not `$result->close();` just above `$this->_stopTimer();`?

**Comment by abrookbanks** [comment]
Hmm. That seems to cause a crash. It's probably best to leave it as it is.
