### ISSUE TITLE
Image Manager Layout Tweak

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2687]
Regarding #2571, can the code be tweaked to break the floats between the group of folders and the group of images?

**Comment by abrookbanks** [comment]
So folders always show in their own "section" above? I'm not sure of the benefit.

**Comment by bhsmither** [comment]
No real benefit. Just a styling/layout thing. I admit, every filemanager I've ever worked with stacks folders on top of files vertically. But this horizontal, and has a strange 'look'.

**Comment by abrookbanks** [comment]
I'm going to leave this as it is for now because I think it's a better use of space and to me feels natural. Maybe having been  a long term mac user. Maybe a forum poll could be a good idea.
