### ISSUE TITLE
FileManager Tabs Tweak

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2688]
Operationally, the admin FileManager (Images and Downloads) seems to work fine.

My 'nit-pick' is that the **Files** tab is not 'connected' to the Files tab_content **pane** -- stylistically.

That is, clicking the Files tab will reload the page. But I would like to show that this pane of content _stylistically_ belongs to the Files tab.

Luckily, there is a new argument available in ACP->addTabControl.

Therefore, in filemanager.index.inc.php, near the bottom:
```
Find:
$GLOBALS['main']->addTabControl($lang['filemanager']['tab_files'], false, currentPage(array('subdir')));

Change to:
$GLOBALS['main']->addTabControl($lang['filemanager']['tab_files'], 'filemanager', null, null, false, '_self', null, "location.hash='filemanager'; location.reload();");
```
This keeps the functionality, but keeps the subdir, while stylistically connecting the tab to the content - like every other tab everywhere else.

**Comment by abrookbanks** [comment]
Thanks so much this has really pestered me too.
