### ISSUE TITLE
Cookies are corrupting / broken in latest release

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2689]
I've yet to isolate a specific root cause, but there are two live sites I am aware of, both presenting the exact same problem, being...

Session/Cookie data seems to somehow corrupt or contain something invalid, which means various pages on the site do not work correctly until the cookies are manually cleared from the browser, then it works for a few page views and stops again. for example, pressing add to cart does nothing, or logging into the site but then being shown as logged out on various pages.

Something appears to be up with cookies in the 6.4 versions, but I've yet to be able to reproduce it myself to deep dive the problem. 

Raising this for awareness of a general problem until details surface.

**Comment by havenswift-hosting** [comment]
There have been various reports about this on the forums and I have experienced it myself once on one test site that I have upgraded but also cannot reproduce it in order to look deeper

When it happens is there a record in the error_log file with the normal "Session aborted as possible session hijack."

**Comment by Noodleyman** [comment]
I hadn't noted "Session aborted as possible session hijack.", I'll keep an eye out for that.

**Comment by Noodleyman** [comment]
customer_id is not being set correctly in the session data, it logs 0 in CubeCart_sessions as the customer_id.

There are different session ID's between specific pages, almost like an old one was cached for one page... which I assume would cause the hijack error

**Comment by Noodleyman** [comment]
Confirmed. multiple cookies with the same name are being created in the browser, but with different session ID's, (pre-login, and post-login)... and it seems to be flicking between them randomly

**Comment by abrookbanks** [comment]
Possibly relevant Alec.
https://github.com/cubecart/v6/issues/2556

**Comment by abrookbanks** [comment]
Maybe we should revert the SameSite cookie changes.

**Comment by abrookbanks** [comment]
I don't know of a site expressing this behaviour. Maybe one of you guys can kindly try for me removing the SameSite changes in the issue above.

**Comment by Noodleyman** [comment]
example.

two sessions ID's in the DB..
![image](https://user-images.githubusercontent.com/10614018/100107973-2ce7e600-2e62-11eb-9fa7-f89d0b07f7d6.png)

in my existing example, the session_id ending with a1 is being used on all pages on the storefront, apart from one, where it uses the one ending 6b.

There are two cookies, with the same name. one of which is domain wide, (path = /) the other has the full URL of the page defined (path = full path to page). the one with the URL of the page is the session_id ending 6b.. so I assume being more refined to this one page, it's taking priority.

![image](https://user-images.githubusercontent.com/10614018/100108294-894b0580-2e62-11eb-9c89-309d77c2c094.png)

can send you the unmasked content directly, I didn't want to share it on an open forum.

**Comment by abrookbanks** [comment]
So it's a path issue. Can you email it to me? :)

**Comment by Noodleyman** [comment]
this specific example may be, but this is most likely a variant of the underlying issue. @havenswift-hosting , do you have any other example sites you can share?

**Comment by abrookbanks** [comment]
"underlying issue"?

**Comment by Noodleyman** [comment]
> "underlying issue"?

that's what we are trying to figure out 😉

**Comment by abrookbanks** [comment]
Oh yeh. 🤣

**Comment by abrookbanks** [comment]
Virgin Media are up and down every 5 minutes today so I'm handicapped at the moment. I bet the issue is somewhere in the code changes for #2556

**Comment by Noodleyman** [comment]
The example I've provided, I am confident will be related, but different to the other reports that will come in. It's due to the way this specific example is being triggered. This is the only example I have to hand at the moment, and I have not been successful in reproducing other reports from other customers. It appears specific to their computers/machines or network. However, the common thing for the other reports I am aware of is clearing cookies temporarily resolves the issue.

**Comment by abrookbanks** [comment]
I expect it's to do with extending the session cookie expire date on each page load... 🤔

**Comment by abrookbanks** [comment]
I strongly expect its something here:
https://github.com/cubecart/v6/blob/v6-master/classes/session.class.php#L583-L592 

I still can't reach my development store whilst Virgin Media are down. :(

**Comment by abrookbanks** [comment]
I JUST can't win with this. SameSite before PHP 7.3 needs the cookie to be set via header without using `setcookie()`. 

```
public function set_cookie($name, $value, $expire, $options = array())
    {
        $params = session_get_cookie_params();
        $params = array_merge($params, $options); // Allow overwrite for specific cookies    

        $secure = CC_SSL ? ';Secure' : '';
        $samesite = CC_SSL ? 'SameSite='.$params['samesite'].';' : '';
        $httponly = $params['httponly'] ? ';HttpOnly' : '';
        header("Set-Cookie:$name=$value;Expires=".$expire.";".$samesite."Domain=".$params['domain'].";Path=".$params['path']."$secure.$httponly");
    }
```

That code works well (at least on Chrome) but the expire time doesn't update on each page load.

**Comment by abrookbanks** [comment]
I had the expire format wrong. Now this seems to work well.

**Comment by abrookbanks** [comment]
So we really had a number of issues here. Bad path for root level stores. Bad expiry date format and mixed handling of SameSite. 

The only way PHP less than 7.3 can handle samesite is with a header instead of setcookie function. 

I'm confident this is resolved but I'd be grateful of feedback.

**Comment by bhsmither** [comment]
Just mentioning #2659.

**Comment by abrookbanks** [comment]
Thanks yes I had seen and it did influence this. Really appreciate it. I believe that issue can be closed now.

**Comment by Noodleyman** [comment]
Thank you Al 👍

**Comment by abrookbanks** [comment]
And thank you for helping find the problem in the first place.

**Comment by havenswift-hosting** [comment]
> I'm confident this is resolved but I'd be grateful of feedback.

Upgraded two live sites and 3 test / dev sites yesterday evening with this fix so will monitor and let you know if any more problems

**Comment by Noodleyman** [comment]
For the less technical out there, will 6.4.2 be released soon with this fix?

**Comment by abrookbanks** [comment]
> For the less technical out there, will 6.4.2 be released soon with this fix?

Next week. :)
