### ISSUE TITLE
Enhancement to Manufacturers 

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#269]
Currently the manufacturer name and website can be captured.

It would also be good to add a generic "Custom Data" field so any custom information can be stored and added to the store skin if required.

Example: store e-mail address or phone number for internal use.

**Comment by abrookbanks** [comment]
This is a tricky one because the average user will be confused by this so I'm inclined to say no. :(

If we can give it a useful name such as description or something maybe we can do something.

**Comment by abrookbanks** [comment]
.. I don't want to risk usability. It may scare average users off.

**Comment by havenswift-hosting** [comment]
I would agree about not using generic fields but also think that this is an area that could easily be enhanced with some additional commonly used fields.  The whole areas of manufacturers and suppliers are ones that could and should be enhanced either in core or via plugins

**Comment by abrookbanks** [comment]
It could be replaced entirely with a plugin creating a new admin area.

**Comment by Noodleyman** [comment]
Hi Al,

How about this then.. a new list for "Suppliers". very useful for drop shippers who need to know where to place their orders. Doesn't need much enhancement, simply a way to link the product to supplier.

A supplier record should contain generic info, company name / address / tel / e-mail /website to name a few off the top of my head.

I am currently using the manufacturers field for this very purpose.

It could be done using a plugin, but thought it might be nice to get this one out of the box.
