### ISSUE TITLE
Code Review: Databasing Product Reviews

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2690]
In `CubeCart->_product()`, if there are no errors in the POSTed data, an attempt is made to INSERT the `$record` into `CubeCart_reviews`.

It is here that the resultant INSERT_ID must be captured into a variable for later use.

For, between here and when the insert id value gets used, there is work being performed. Note that none of the obvious current work will disturb the the `DB->insertid()` return value from what is expected.

Except for two, perhaps remote, possibilities:
The hook, which can do anything, and
In Debug Mode, where Notices and Warnings about whatever caught PHP's attention will get inserted into the System Error log.

Suggest:
```
Change:
if (($GLOBALS['db']->insert('CubeCart_reviews', $record)) !== false) {
To:
if (($review_id = $GLOBALS['db']->insert('CubeCart_reviews', $record)) !== false) {
```
and
```
Change:
$record['link']   = $GLOBALS['storeURL'].'/'.$GLOBALS['config']->get('config', 'adminFile').'?_g=products&node=reviews&edit='.$GLOBALS['db']->insertid();
To:
$record['link']   = $GLOBALS['storeURL'].'/'.$GLOBALS['config']->get('config', 'adminFile').'?_g=products&node=reviews&edit='.$review_id;

**Comment by abrookbanks** [comment]
Confirmed working.
