### ISSUE TITLE
Note: Your store should only log notice and warning errors if it is in debug mode

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2693]
This statement on the error log page is not accurate as it only applies to PHP. Anything being thrown from the database regardelss of severity is also logged. 

However, I think it would only log errors from the DB anyway.. but might be worth refining to clarify PHP errors. 

a few people assumed the would only see "Unknown or incorrect time zone" notices if they had debug mode enabled.

**Comment by abrookbanks** [comment]
Good point.

**Comment by abrookbanks** [comment]
This could go further but for now the vital one is supressed unless debug mode is on.
