### ISSUE TITLE
UX Review: Taxes

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2696]
On the Tax Classes page, there is an icon (trash bin) leading the phrase "Assign to all products".

An admin might associate the icon to the phrase. That association would be a stretch of the imagination: **_careful_** observation that the icon is a trash bin (typically meaning Delete), which pops up a confirmation dialog, vs. a phrase that also pops up a confirmation dialog. So, there is a 'halt and verify' step involved.

Still, I suggest making both actions an icon, different colors, with some sort of separator between them.

**Comment by abrookbanks** [comment]
Thanks. 

![Screenshot 2020-12-01 085511](https://user-images.githubusercontent.com/4520803/100718189-f0147580-33b2-11eb-9f68-82efdad1b4ca.jpg)
