### ISSUE TITLE
Product Options Serialized Storage

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2698]
Regarding #2562, the edit made in order.class.php near lines 299-305 (https://github.com/cubecart/v6/commit/fdd1e50f4ff81c613fb727cdca2110c285c8c217) does not match the edit made elsewhere (https://github.com/cubecart/v6/commit/7d4343525786f29af4e613404043a3362a7aa3ef).

Specifically, the `else` block is identical to the `if` block.

**Comment by twistedsymphony** [comment]
Is this what's causing the the following issue:

Options when displayed on the Oder summary and printed invoice show the serialized version as opposed to the actual selected option as seen in the photo below:
![cube_cart_options](https://user-images.githubusercontent.com/14942805/100467321-42e2ea00-30a0-11eb-80ae-995ed7365bc1.jpg)

**Comment by bhsmither** [comment]
I am going to say no. Your observation seems to be something different. Please mention the version of CubeCart you are using.

**Comment by rbosma** [comment]
@bhsmither Same problem as @twistedsymphony over here... When generating a print order form....
![order_form](https://user-images.githubusercontent.com/13029406/100513161-65900400-316f-11eb-8b16-20632b813a1a.png)

Viewing the order the product options show normaly...
![view_order](https://user-images.githubusercontent.com/13029406/100513815-3cbc3e80-3170-11eb-9aa9-cc6d6110a25b.png)

Mail to customer with order shows up without product options
![mail to cust](https://user-images.githubusercontent.com/13029406/100513770-febf1a80-316f-11eb-9fcb-04ff0007b924.png)

Happend after the last upgrade from version 6.2.9 to 6.4.1

Went through the template files but couldn't find it.. Products without options showing up fine...

_Fingers crossed for the veterans.. :-)_

**Comment by twistedsymphony** [comment]
Same for me. This happend after I upgraded from version 6.2.9 to 6.4.1

**Comment by abrookbanks** [comment]
Mixed versions of code? I expect you have an outdated /admin_xxx/*.* folder.

**Comment by rbosma** [comment]
Not as far as I know, same date and time stamps as upgrade... Is there any way to check this out if there is a mixture of code?

**Comment by abrookbanks** [comment]
It's a classic upgrade error to upload the admin folder without renaming it admin_xxx matching the value in your includes/global.inc.php file.

**Comment by NT7S** [comment]
I am also having this problem, and yes I did check that my admin_ folder matches the one global.inc.php.

**Comment by bhsmither** [comment]
Are these orders that were placed **after** the upgrade?

Or are they orders placed **before** the upgrade, but are now viewing them in admin **after** the upgrade?

Are these customer-placed orders or admin-created orders?

Are there any order-related plugins installed?

**Comment by rbosma** [comment]
> Are these orders that were placed **after** the upgrade?/
**Yes they are, it happens when the orders are placed and the form is being created, as shown in my screenshots above**
 
> Or are they orders placed **before** the upgrade, but are now viewing them in admin **after** the upgrade?/
**In the admin screen the orders show up fine, it's purely the first output that shows this garble..**
 
> Are these customer-placed orders or admin-created orders?/
**Only with customer placed orders, with admin there's no problem... (At least on my side)** 

> Are there any order-related plugins installed?/
**Only pugs installed on my side that could interfere and being used are:
_Print Order form 1.2.1
Store Collection 1.0.0
AIOS 1.0.19
Per Category 1.0.0_**

**Comment by abrookbanks** [comment]
I can't reproduce this. http://static.cubecart.com/issue-2703.mp4

Are you 100% sure the admin files are up to date? Upload the contents of the /admin folder over your /admin_xyz123 folder manually.

**Comment by abrookbanks** [comment]
Email:
![Screenshot 2020-12-01 084932](https://user-images.githubusercontent.com/4520803/100717619-30272880-33b2-11eb-9aa5-602d7022fc94.jpg)

**Comment by abrookbanks** [comment]
Please open a tech support ticket if you require any further assitance.

**Comment by rbosma** [comment]
I'll give it a try... _I'll be back_

**Comment by rbosma** [comment]
> Are you 100% sure the admin files are up to date? Upload the contents of the /admin folder over your /admin_xyz123 folder manually./

Didn't solve the issue...
![scrn_dump](https://user-images.githubusercontent.com/13029406/100724340-0fb39a00-33c3-11eb-8c6b-fa40c97e7e24.PNG)

Using print order form.. Logged in as customer..

When viewing order in Admin panel, everything shows up fine..

**Comment by bhsmither** [comment]
I am seeing code that suggests the POF gateway is querying for itself the order inventory, and has not been upgraded (looking at v1.2.0) to deal with #2562.

How much of `POF->call()` is already done elsewhere with `Order->getOrderDetails()`?

**Comment by abrookbanks** [comment]
Can you say what the problem is around this?

**Comment by bhsmither** [comment]
In the specific case mentioned two posts above, the POF cannot handle inventory `$item['product_options']` now being recorded in a base64 format. (Lines 86 and 195.)

My suggestion to have POF use `Order->getOrderDetails()` and `Order->assignOrderDetails()` instead of relying on its own implementation of querying `CubeCart_order_inventory` and populating Smarty variables.

This specific case is not the same as the OP.

**Comment by abrookbanks** [comment]
I see... I'll get this done tomorrow. Thanks.

**Comment by abrookbanks** [comment]
PrintOrderForm-1.2.2.zip released.

**Comment by bhsmither** [comment]
Also e-Payments Interac in two places.

And the second occurrence in POF (now line 205 for v1.2.2).
