### ISSUE TITLE
newsletter.class.php:205 - Call to a member function is() on null

### ISSUE THREAD

**Issue by mjvids** [cubecart/v6#2699]
i am getting a error newsletter.class.php:205 - Call to a member function is() on null

please help

**Comment by bhsmither** [comment]
Duplicate of #2655.

In CC641, in admin, Error Log, System Error Log tab, you might see this error. If so, hovering over the error will show a trace of where this error came from.

Can you reproduce this? If so, enable debug mode, cause the error, and look at the System Error Log table.
