### ISSUE TITLE
Empty Cart

### ISSUE THREAD

**Issue by 3dtime** [cubecart/v6#2701]
Hi all,
 i seem to have the age old problem with the cart being empty after item/s have been added, i have done some research but cant seem to find a definitive answer, 2 people have reported this problem both on a phone and on a pc, i have tested it and it seems to work ok for me, i have a basic install of CC with just the PayPal and All in one shipping addons, i did experience this once but after clearing my browser history it started working again for me,
any help would be great.

thanks

Mark

**Comment by abrookbanks** [comment]
See https://github.com/cubecart/v6/issues/2689
