### ISSUE TITLE
Product option unserialize is badly coded #2698 & #2562

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2705]
It needs a dedicated method. Right now its overly confusing.

**Comment by rbosma** [comment]
@abrookbanks 
> Code improved via [269183f](https://github.com/cubecart/v6/commit/269183fbec82c6f04e68634b6969362a93d579ef)

That didn't do the trick on my side... Changed to code to all three files, but outcome is still the same...

**Comment by abrookbanks** [comment]
Please can you contact support@cubecart.com with FTP access.

**Comment by rbosma** [comment]
I will, takes a few minutes...

**Comment by rbosma** [comment]
You have mail
