### ISSUE TITLE
GLOB Consuming Massive Amount of Memory?

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2706]
Please test: (see https://forums.cubecart.com/topic/56507-latest-update/)

The two changed lines in `_clearFileCache()` would find all files that have '.js' somewhere in the filename. I am only seeing there to be just one file found for each skin for each of JS and CSS concatenated/minified files. So, I do not understand what problems the edits to those lines were to accomplish.

Edit: I see '.js' and '.js.cache', '.css' and '.css.cache' files. And I do not see that '.cache' could be anything else.

But, I do not know how glob() works: does it query the OS for a filtered list of filenames (would need to know the OS syntax), or does it get all filenames (potentially in the thousands) and itself filters out what not to return?

**Comment by abrookbanks** [comment]
.cache files need to go into the general cache clear. If you change to say an alternate cache they won't ever get cleared otherwise.

**Comment by abrookbanks** [comment]
Bugs...

**Comment by havenswift-hosting** [comment]
> I am only seeing there to be just one file found for each skin for each of JS and CSS concatenated/minified files.

Not all skins use the concatenation / minification
