### ISSUE TITLE
PHP 8.1 Compatibility

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2708]
This will require a lot of testing! 

e.g. https://www.php.net/releases/8.0/en.php#saner-string-to-number-comparisons

**Comment by bhsmither** [comment]
Not to mention **Smarty** has a lot of work to be done to make it PHP8 Compatible.

Testing the /setup/ of CC642 under PHP8 now.

Setup died on the page asking for database info:
```
  	<h3>Database Settings</h3>
	<fieldset>
	  <div><label for="form-dbhhost" class="help" rel="" title="This is the database hostname e.g. localhost">Database Host</label><span><input type="text" name="global[dbhost]" id="form-dbhost" value="
```
and nothing after that.

**Comment by abrookbanks** [comment]
CubeCart v7 then. Who's in?

**Comment by abrookbanks** [comment]
https://github.com/smarty-php/smarty/issues/605

**Comment by bhsmither** [comment]
I've been watching this.

**Comment by bhsmither** [comment]
If you haven't seen it yet, I've compiled a report on everything (as of that date) I have found to change for PHP8.1:
```
https://forums.cubecart.com/topic/57813-php-81-making-cubecart-compatible/
```

**Comment by abrookbanks** [comment]
No I hadn't seen this. Thank you so much Brian. It will be a big help.

**Comment by abrookbanks** [comment]
Thanks Brian. You put a lot of work into this. Some of it had been done already. :)

The following block still needs attention. I have concerns about customisations especially around combine and minification .... 
```
Go to https://github.com/smarty-php/smarty/releases/latest
and download the latest release of Smarty (currently at 4.1.0).

Within CubeCart's /includes/lib/ folder, rename the existing 'smarty' folder to 'smarty-3133'.
Create a new folder named 'smarty'.

Unzip the Smarty 4.1.0 package and copy over the contents of the 'libs' folder into CubeCart's new 'smarty' folder.
Then, from the 'smarty-3133 folder, copy over the 'filters' folder, the 'plugins/minify' folder, and the 'plugins/function.combine.php' file.

Then, in Smarty.class.php, line 169, from:
    public static $_DATE_FORMAT = '%b %e, %Y';
To:
    public static $_DATE_FORMAT = 'M j, Y';
```

**Comment by abrookbanks** [comment]
All seems to be working well. Thank you boss!

**Comment by abrookbanks** [comment]
Closing this as everything appears to be working fine. Although closed the error log will be continually monitored and any 8.1 compatibility changes made accordingly.

**Comment by bhsmither** [comment]
In my report, I changed gui.class.php, line 361:
```
From:
                if (!in_array($_GET['_a'], array('basket', 'cart', 'complete', 'checkout', 'confirm', 'gateway')) && !$GLOBALS['config']->get('config', 'catalogue_mode')) {
To:
                if (isset($_GET['_a']) && !in_array($_GET['_a'], array('basket', 'cart', 'complete', 'checkout', 'confirm', 'gateway')) && !$GLOBALS['config']->get('config', 'catalogue_mode')) {
```
I find that in some cases, `$_GET['_a']` is not set - viewing the homepage, for example. The change in given in the report causes `displaySideBasket()` to not be executed.

There needs a different solution here. This seems to work:
```
if (!isset($_GET['_a']) || !in_array($_GET['_a'], array('basket', 'cart', 'complete', 'checkout', 'confirm', 'gateway')) && !$GLOBALS['config']->get('config', 'catalogue_mode')) {
```

**Comment by abrookbanks** [comment]
Cool thanks so much for this.

**Comment by bhsmither** [comment]
Please note a second report has been posted to the forum with some additional findings.
```
https://forums.cubecart.com/topic/57813-php-81-making-cubecart-compatible/?do=findComment&comment=251467
```
