### ISSUE TITLE
Google Base Module Price Tweak

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2713]
Google Merchant Center says for its product feed:
https://support.google.com/merchants/answer/7052112?hl=en

 For 'price':

Example
15.00 USD

In the Google Base module /hooks/admin.product.import.format.php, near line 15:

The line that starts with:

$fields = array(

Change:
'price'

to:
'price currency'

**Comment by abrookbanks** [comment]
Fixed in 1.0.3. Thanks.
