### ISSUE TITLE
htaccess typo?

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2715]
newly created htaccess file contains:
`ErrorDocument 404 "<html></html>`

I'm assuming this should be ended with a closing double quote?

**Comment by abrookbanks** [comment]
Thanks.

**Comment by bhsmither** [comment]
NO! Actually, the docs specifically make a note of this, and specify that there should NOT be a closing quote.

I will try to find the spec later.

**Comment by abrookbanks** [comment]
Whoooops

**Comment by bhsmither** [comment]
https://httpd.apache.org/docs/2.4/custom-error.html

In Configuration, discussing `<action>`:

> Text to be displayed (if none of the above). The text must be wrapped in quotes (") if it consists of more than one word.

which, technically, `<html></html>` is just one word. (The use of quotes may have been slightly different in previous versions of Apache.)

https://httpd.apache.org/docs/2.0/custom-error.html
Apache 2.0 says:

> Text to be displayed. Prefix the text with a quote ("). Whatever follows the quote is displayed. Note: the (") prefix isn't displayed.

Other sites expand on this by saying: "Note that the initial quotation mark ( " ) [is simply a specifier that] specifies the character string as text and is not included in the message itself. No closing quotation mark is required." Other types of values for ErrorDocument is a path that starts with a slash, or is a full URL, without quotes.
