### ISSUE TITLE
Possible Installation Anomaly

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2716]
In /setup/db/install/examples.sql, the first query inserts a new category allowing the database to handle the value determined by auto-increment rules.

There could be a _very slight_ possibility that these rules will return a value other than `1`.

If that happens, the second query inserts bad data as the product is referencing a category that does not exist.

As regards to the third query, it too inserts bad data with respect to the cat_id, but avoids doing the same with respect to the product_id by using `LAST_INSERT_ID()`.

If the auto-increment rules could possibly return a value other than `1` for cat_id, then perhaps the installer should force the issue by specifying `cat_id` as `1` in the first query.

**Comment by abrookbanks** [comment]
Thanks.
