### ISSUE TITLE
Request - capture the depth of a category in CubeCart_category

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2717]
Would it be possible to enhance the category data to store the category_depth of each category? 

Example:
Parent => Sub-cat => Sub-cat  
would have a depth of 3

It's useful where you need to know the depth of the category for bespoke modules/features but don't necessarily want to recursively walk all the hierarchies every time to find the solution.

**Comment by abrookbanks** [comment]
In programming count it would be 0, 1, 2 if you are being pedantic.

**Comment by Noodleyman** [comment]
Agreed. I was pondering 0 or 1 when I opened this :)

**Comment by Noodleyman** [comment]
```
function updateCatsWithHierPosition($cat_id = 0, $position = 0){
    if($cat_id == 0){
        $GLOBALS['db']->update('CubeCart_category', array('cat_hier_position' => 0));
        $cats = $GLOBALS['db']->select('CubeCart_category', array('cat_id'), array('cat_parent_id' => 0), array('priority' => 'ASC'));
    }else{
        $cats = $GLOBALS['db']->select('CubeCart_category', array('cat_id'), array('cat_parent_id' => $cat_id), array('priority' => 'ASC'));
    }
    if(isset($cats) && is_array($cats) && !empty($cats)){
        foreach($cats as $cat){
            if($position > 0){
                $GLOBALS['db']->update('CubeCart_category', array('cat_hier_position' => $position), array('cat_id' => $cat['cat_id']));
            }
            updateCatsWithHierPosition($cat['cat_id'], ($position+1));
        }
    }
}
```

just call the function every time a category is saved and it will rebuild all the hierarchies. needs the DB column  added and if implemented in a future version of CubeCart also needs to have the function called once during the upgrade process to populate the values.

**Comment by abrookbanks** [comment]
Works well. Thanks.
