### ISSUE TITLE
Code Review: buildCategoriesDropdown Has No Loop Detector

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2718]
As opposed to `SEO->getDirectory()`, which has a loop detector, `SEO->_getCategoryList()` and `Catalogue->buildCategoriesDropDown()` do not.

(Personally, I think the SEO class should not calculate category paths/directories. Have the Category class do that and pass back the sequence of cat_id numbers to the methods in SEO that will use the sequence.)

**Comment by abrookbanks** [comment]
I don't think _getCategoryList needs one.
