### ISSUE TITLE
Code Check: Databased SEO Paths

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2719]
In /setup/db/upgrade/6.4.0.sql, there is a query that CONCATs ".html" to the values in the `path` column for all rows.

Then, following that, are three INSERT queries that adds 'login', 'register', and 'search' to the table _without_ the ".html" extension.

**Comment by abrookbanks** [comment]
It's intentional. Coming from < 6.4 .html is used everywhere. From 6.4 it could be either so in case of switch both need to be able to work depending on hard code in skin/js. Those rows are required.
