### ISSUE TITLE
Count Issue in Admin

### ISSUE THREAD

**Issue by onebrowncow** [cubecart/v6#2723]
![screenshot-admin-control-panel](https://user-images.githubusercontent.com/13252688/102059892-6a98b880-3de9-11eb-851e-ea6daf79a83e.jpg)

Count (by green arrow) shows the stock warning amount not the unsettled orders amount CC6.4.2

**Comment by abrookbanks** [comment]
Thanks so much for this. I don't think there is a need for it as it's shown in the tab. :O)
