### ISSUE TITLE
Feature Request: quantity in basket in mobile view

### ISSUE THREAD

**Issue by onebrowncow** [cubecart/v6#2724]
![Screenshot_2020-12-14 Handbags Jewellery Home Kitchen Interiors Pottery Mugs Emma Bridgwater Greetings Cards Stationery One](https://user-images.githubusercontent.com/13252688/102123515-dce7b800-3e3e-11eb-8696-255c3fe0dfeb.png)
I'd like the basket quantity to show to customer when they add to basket in mobile view. I've had a quick play with the code in box.basket.php for the results in the attached image after adding a little CSS but I think it needs cleaning up.

It would be great if this was standard as I think customers leave the site if the basket item does not appear to have had anything added.
`<div class="show-for-small-only">
      <div class="show-for-small-only"><a class="right-off-canvas-toggle button white tiny" href="#"><svg class="icon icon-basket icon-x2"><use xlink:href="#icon-basket"></use></svg>
    
       <span class="mini-items">{$CART_ITEMS}</span><br /><span style="font-size:0.626rem;">{$LANG.basket.view_basket}</span></a></div>
    `

**Comment by rbosma** [comment]
Nice one, should definitly put into CC
