### ISSUE TITLE
Search is bringing up items that are disabled

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2727]
Internal ticket 111476.

**Comment by abrookbanks** [comment]
```
SELECT I.*, MATCH (I.product_code,I.name) AGAINST('stamperia' IN BOOLEAN MODE) AS Relevance FROM CubeCart_inventory AS I LEFT JOIN (SELECT product_id, MAX(price) as price, MAX(sale_price) as sale_price FROM CubeCart_pricing_group WHERE group_id = 0 GROUP BY product_id) as G ON G.product_id = I.product_id WHERE I.product_id IN (SELECT product_id FROM `CubeCart_category_index` as CI INNER JOIN CubeCart_category as C where CI.cat_id = C.cat_id AND C.status = 1) AND I.status = 1 AND (MATCH (I.product_code,I.name) AGAINST('stamperia' IN BOOLEAN MODE)) >= 0.5 OR `I`.`manufacturer` IN(36) AND `live_from` < UNIX_TIMESTAMP() ORDER BY `Relevance` DESC LIMIT 12 OFFSET 0
```

<img width="1064" alt="Screenshot 2020-12-18 154209" src="https://user-images.githubusercontent.com/4520803/102632910-9ac4bc00-4147-11eb-88be-58209557bc01.png">

**Comment by bhsmither** [comment]
My experiments show that:
```
OR `I`.`manufacturer` IN(36)
```
should be changed to:
```
AND `I`.`manufacturer` IN(36)
```
or not use 'manufacturer' in certain combinations of query conditionals.

**Comment by bhsmither** [comment]
The above is near line 1851:
```
if(!isset($search_data['manufacturer']) && $manufacturers  = $GLOBALS['db']->select('CubeCart_manufacturers', array('id'), "`name` LIKE '%".$search_data['keywords']."%'")) {
```
That is, if **not** looking for a specific manufacturer (see near line 1796 and issue #2622), but rather if any of the search terms looks LIKE a manufacturer name, then include those products -- using OR -- resulting in a recordset containing products irrespective of any other conditions.

**Comment by bhsmither** [comment]
Looking at the code changes for issue #2397, the query did use:
```
AND `manufacturer` IN ($manufacturers)
```

**Comment by abrookbanks** [comment]
I'm so grateful. Saved me a lot of work this morning which I need now the kids are home and my wife and I juggle work again. 

It's really not much fun in the UK right now. The new strain was an absolute kick in the teeth on Friday.

I'll see how the customer gets on with these changes.

**Comment by tonyrsutton** [comment]
Did the code change work?

**Comment by abrookbanks** [comment]
Ignore the reverted commit above. Wrong issue by typo.
