### ISSUE TITLE
Fatal Error: method_exists() (PHP8)

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2729]
During install, line 71 of /setup/index.php instantiates `Debug`. That means from this point on, errors will get handled by `Debug->errorLogger()`.

In `errorLogger()`, near line 416, references are made against `$GLOBALS['config']` which, during setup, does not hold a Config class object. (In /setup/setup.install.php, line 269, `$GLOBALS['config']` is used to hold an array.)

With `$GLOBALS['config']` not being an object, the PHP function `method_exists()` crashes with a Fatal Error.

**Comment by bhsmither** [comment]
This bug report looks interesting:
https://bugs.php.net/bug.php?id=79623

Will try using "Config" to trigger the autoloader.

**Comment by bhsmither** [comment]
Or, try:
```
From:
$can_log = method_exists($GLOBALS['config'], 'get') ? (bool)$GLOBALS['config']->get('config', 'debug') : false;

To:
$can_log = (is_object($GLOBALS['config']) && method_exists($GLOBALS['config'], 'get')) ? (bool)$GLOBALS['config']->get('config', 'debug') : false;
```

**Comment by bhsmither** [comment]
This works:
`method_exists("Config", 'get')`

but does not solve this:
`(bool)$GLOBALS['config']->get('config', 'debug')`

This actually fixed it:
```
$can_log = (isset($GLOBALS['config']) && is_object($GLOBALS['config']) && method_exists($GLOBALS['config'], 'get')) ? (bool)$GLOBALS['config']->get('config', 'debug') : false;
```
But there is still a ton of entries in the error_log file from unset Smarty variables.

**Comment by abrookbanks** [comment]
From PHP 8.1 we can't write to $GLOBALS so this is going to be a problem.
