### ISSUE TITLE
Mute smarty errors deliberately produced

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#273]
See thread https://forums.cubecart.com/topic/49297-php-warning-does-it-mean-something

**Comment by abrookbanks** [comment]
Hmm I've looked at this before and don't recall any elegant solution.

**Comment by abrookbanks** [comment]
I think this is actually already fixed in v6 but I made some tweaks which may improve it.

**Comment by abrookbanks** [comment]
.. and I'm not able to see these errors in v6 so I think it works.
