### ISSUE TITLE
PHP8: Unset Smarty Variables

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2730]
How did I find #2729?

In /setup/skin.install.php, there is the variable {$FORM} that does does not yet exist on the first display of 80% Complete (database access form).

Undefined things now throw warnings.
```
   8. Debug->errorLogger(
   			$error_no = 2,
   			$error_string = 'Undefined array key "FORM"',
   			$error_file = '/cache/skin/87d06a9d71dd6446a01ecf0d0704a9bee6ca16b5_0.file.skin.install.php.php',
   			$error_line = 188,
   			$error_context = *uninitialized*
   		)
   		/cache/skin/87d06a9d71dd6446a01ecf0d0704a9bee6ca16b5_0.file.skin.install.php.php:188

Line 188 is:
</label><span><input type="text" name="global[dbhost]" id="form-dbhost" value="<?php echo $_smarty_tpl->tpl_vars['FORM']->value['global']['dbhost'];?>

PHP Warning:  Undefined array key "config" in /classes/debug.class.php on line 416
```
https://www.php.net/manual/en/migration80.incompatible.php

I will test if Smarty `muteExpectedErrors()` will solve this.

**Comment by bhsmither** [comment]
Nope.

**Comment by Abelardon** [comment]
I don't think there's a direct support for this in smarty. You can always do this with smarty's {php} tag, however I would strongly discourage you from doing so. Logic doesn't belong in a presentation-level template.

**Comment by abrookbanks** [comment]
I believe this issue is now resolved.
