### ISSUE TITLE
cart.order_pending

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2733]
PHP Notice:  Email content for cart.order_pending doesn't exist in default lamguage. in classes/mailer.class.php on line 132
PHP Notice:  Email content for cart.order_pending doesn't exist in any lamguage. in classes/mailer.class.php on line 129

Happened to notice this in an error log today, seems that "order_pending" doesn't exist, nor can I see it being created by CubeCart. Also, a typo in the error "lamguage".

**Comment by bhsmither** [comment]
Can you provide a backtrace to see what code is requesting the Mailer to send `cart.order_pending`?

I think `cart.order_pending` never did exist. Maybe a plugin?

**Comment by abrookbanks** [comment]
> I think cart.order_pending never did exist. Maybe a plugin?

I think this is store specific.

**Comment by Noodleyman** [comment]
Agreed, although did you address the spelling issue? 😊

**Comment by abrookbanks** [comment]
Yes. Silly typo fixed.

**Comment by Noodleyman** [comment]
Thank you Al 😊
