### ISSUE TITLE
Logged-In Admin, to See Empty, Hidden, Disabled Categories

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2736]
Feature Request:

When a logged-in admin is viewing the storefront, have empty, hidden, and disabled categories be shown (similar in concept to hiding prices until logged in, and hide out-of-stock products).

Perhaps use a non-default link/text color for categories that would otherwise not be shown.

**Comment by havenswift-hosting** [comment]
I disagree with this.  The admin needs to be able to see the store exactly the same as a user sees it.  If they need to be able to see these categories then they can simply put the store into maintenance mode, enable the setting to see these and then view the store front.
