### ISSUE TITLE
Config switch to disable showing of gravatar images

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2737]
We need a config switch (on / off) for the display of gravatar avatar images when a product has reviews.  When gravatar.com is down or unreachable, the call to their site takes a long time before it times out and this can cause multiple problems especially when running a site through Cloudflare for example which then throws a 524 error and temporarily blocks access to the site

**Comment by bhsmither** [comment]
This has been implemented. See: https://github.com/cubecart/v6/commit/f63354bd9eddd9b51e61aa7877194c36a77bef83

In admin, Store Settings, Features tab, Reviews section, "Enable Product Reviews/Comments", set to **Enabled (Gravatar Disabled)**.

Whether this actually works correctly, I have not verified.

**Comment by bhsmither** [comment]
Perhaps using a cURL function with CURLOPT_TIMEOUT or CURLOPT_CONNECTTIMEOUT at 3 seconds?

Perhaps not even test for connected-ness in the core code, but delegate all responsibility of making the connection and dealing with the connection attempt to the skin to make an ajax call - if the skin even wants to use gravatars.

**Comment by havenswift-hosting** [comment]
@bhsmither you are correct - it was done a few years ago after the last major problem that affected hundreds of stores.

I dont believe this should be taken out of core and put into skin control but the suggestion of using a very short time out via curl is a good one.  When there are many tens of customers all saying their product pages arent loading, they dont associate it with gravatar (as most dont have a clue what that is) and wouldnt think to switch that off

**Comment by abrookbanks** [comment]
Relates to #2400 improved fix https://github.com/cubecart/v6/commit/eb16305545f8bd6f100e0c2dcf348d8b915c5dd7
