### ISSUE TITLE
Urgent : Need support for various forms of Google Analytics

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2738]
With the recent release of  [Google Analytics 4](https://blog.google/products/marketingplatform/analytics/new_google_analytics) there are now three different types of analytics that need to be supported

Original Google Analytics
Universal Analytics
Google Analytics 4 - also known as Global Site Tag

GA4 is now the default for new properties and doesnt work in CubeCart as the code is different

**Comment by abrookbanks** [comment]
https://developers.google.com/analytics/devguides/collection/gtagjs/ecommerce

**Comment by abrookbanks** [comment]
They don't half make this confusing. Looks like we need to replace it with:

```
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxxxxxxx-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-xxxxxxxx-1');
</script>

```

https://developers.google.com/analytics/devguides/collection/gtagjs/ecommerce

**Comment by havenswift-hosting** [comment]
It is more complicated than that - you need to be able to support all types of GA code - one isnt suddenly replaced with another.  Other applications are giving the choice between the three different types - for example https://blog.whmcs.com/133669/google-analytics-4-support-in-the-google-analytics-addon

https://support.google.com/analytics/answer/10089681

**Comment by abrookbanks** [comment]
In the meantime .. https://support.google.com/analytics/answer/10269537?hl=en

**Comment by havenswift-hosting** [comment]
Any idea when this is going to be added please GA4 has been out for a very long time now but we really need the option to support all currently offered versions as above

**Comment by russellhurst** [comment]
Has there been any progress in adding Google's GA4 to CubeCart now whilst retaining the original Google Analytics?

**Comment by abrookbanks** [comment]
Just add it to the HTML template files for now.. it takes seconds.

**Comment by hairy-dog** [comment]
I suspect that all are illegal. Use piwik hosted locally.

**Comment by abrookbanks** [comment]
Illegal?

**Comment by bhsmither** [comment]
Silly thing about page resources (google fonts as of recent discussion) being fetched from foreign servers.

**Comment by abrookbanks** [comment]
I'd only be concerned about this is I were not a small business. Crazy.

**Comment by hairy-dog** [comment]
Google tracking has been ruled to breach GDPR in several EU States. There hasn't been a case in the UK, but the same laws apply so it's more a matter of when, not if.

**Comment by havenswift-hosting** [comment]
> Google tracking has been ruled to breach GDPR in several EU States. There hasn't been a case in the UK, but the same laws apply so it's more a matter of when, not if.

It does not breach GDPR in itself but consent to use the cookies required must be obtained but this applies to anything like this including all other tracking / analytic services.  Most often people decline these making them almost worthless

**Comment by havenswift-hosting** [comment]
> Just add it to the HTML template files for now.. it takes seconds.

With the move towards GA4 being the default (and soon to be only) version, perhaps CubeCart should just be updated across the board. So change the admin settings page to indicate that a GA4 code should be entered and then update the code in each of the skin templates.  Will have to be done soon so why not now- think the time has passed to support multiple version of analytics

**Comment by abrookbanks** [comment]
> and soon to be only

Do you know the EoL date for the older ones?

**Comment by havenswift-hosting** [comment]
https://support.google.com/analytics/answer/11583528?hl=en

Seems sensible to me to simply switch CubeCart to use GA4 ASAP - it isnt a big change

**Comment by russellhurst** [comment]
As a website owner it would be great if CubeCart could be switched to GA4 ASAP.

**Comment by abrookbanks** [comment]
I think this need to take the form of a new extension that can take advantage of existing hooks to pul in the JS. Any other way would mean updating every skin file. 

I appreciate your patience with this but I'm at 100%+ capacity until the end of December with a huge sponsored POS project. It's all consuming but I simply have to prioritise it.

Thanks to you all for your support. As you know it's just me.. trying to keep up with support, development and general business admin. My resources are thin at the best of times. We will get this done. In the mean time you should be able to chuck the JS provided by Google into the head section of your stores template file.

**Comment by onebrowncow** [comment]
FYI, tried pasting the GA4 code in to the head as per Google instructions and just ended up with a blank page showing so it isn't always as simple as just chucking it in the head of the template

**Comment by abrookbanks** [comment]
Wrap it in smarty literal tags.

{litertal} .. GA Code .. {/literal}

**Comment by bhsmither** [comment]
It should be a tad more involved than that. If we take it to the forums, maybe we can work it out.

**Comment by onebrowncow** [comment]
Pasted GA script in to the template "element.google_analytics.php" between literal smarty tags, it seems to be working and returning traffic data. Original analytics code left in place.

**Comment by bhsmither** [comment]
Please let us see the code that Google gave you -- x-out any identifying labels. (Be sure to use the code tag for the code -- three backticks to start and end the code block.)

**Comment by onebrowncow** [comment]
This is how my element.google_analytics.php template now looks

```
<!-- Google tag (gtag.js) -->
{literal}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XXXXXXXXXX');
</script>
{/literal}
{if isset($smarty.cookies.accept_cookies) && $smarty.cookies.accept_cookies=='true'}
{literal}<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create', '{/literal}{$ANALYTICS}{literal}', 'auto');
ga('set', 'anonymizeIp', true);
ga('send', 'pageview');
</script>{/literal}
{/if}```

**Comment by abrookbanks** [comment]
I've been working all night on this. I nearly have an extension ready..

**Comment by abrookbanks** [comment]
I've released an extension for this which should work with any skin without coding changes:
https://www.cubecart.com/extensions/plugins/google-analytics-for-ecommerce

**Comment by abrookbanks** [comment]
Any feedback on this one? Is it working out ok?

**Comment by abrookbanks** [comment]
Closing but will reopen if there is reason.

**Comment by demand73** [comment]
I have installed this plugin in version 1.0.2 and when i activate it, it switches the webshop to english and that cant be changed until i deactivate the plugin, my default language is Swedish. Using CC 6.4.9 and Kurouto 1.0.3.
