### ISSUE TITLE
Login page shouldn't have char length min limit

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#274]
https://forums.cubecart.com/topic/49299-v6-passwords-for-existing-customers/#entry206048

**Comment by havenswift-hosting** [comment]
Maybe the "fix" should be to display a better explanation message and a link through to the password reset

**Comment by abrookbanks** [comment]
I'm a bit trigger happy closing things!

**Comment by abrookbanks** [comment]
Works great.
