### ISSUE TITLE
Code Check: Regex Pattern in SSL Class

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2740]
Regarding #2691, the regex:
```
"#^https?://|www.#"
```
may not be what is wanted. The pattern offers a choice of two options: starts-with-**https?://**, or is **www**-any-one-character.

So, **subdomain.wwwhacky.com** matches, with **wwwh** being removed.

It is now possible for `SSL::validRedirect()` to return a false `false`.

Suggest:
```
"#^https?://|^www\.#"
```

**Comment by abrookbanks** [comment]
Thanks for this Brian.
