### ISSUE TITLE
Allow reset of digital downloads for each product (not just via the edit order page)

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2741]
It should be possible to check a box to reset all purchased digital downloads when a downloadable product is updated.

It would also be good to be able to see a list of all orders that contain a specific item whether digital or not.

**Comment by hairy-dog** [comment]
Yes, it's a few years since I asked for this. A way to see who has bough a particular product.
My request fell on stony ground. So several stores didn't move to cubecart after all.

**Comment by abrookbanks** [comment]
A million and one requests have been made that haven't been able to be introduced. I hoped going open source would help but we get next to no contributions.

**Comment by mediadogg** [comment]
Is there a process for contributions to the open source that benefit the contributor? My first request of this feature was met with an offer to provide a quote, so providing the functional change, clearly is deemed to have value. If I wrote the code and it were to be ultimately accepted into production (I assume after rigorous testing), is there some compensation scheme other than the satisfaction of what otherwise would have been a custom change, being preserved going forward?

**Comment by abrookbanks** [comment]
The main benefit would be the reward of giving. The second would be that if you custom developed it just for yourself then you may have to manually add the code back in after every upgrade. Third would be that it helps CubeCart become more popular which means more users which means the project is more likely to live longer thus attracting more contributors.

Fourth would be that we give you credit for you work which we promote. That could be in some way beneficial commercially.

Covid also doesn't help. Working from home with schools closed is a big problem for working families right now. The UK like the US is in an absolute mess.

**Comment by abrookbanks** [comment]
Fourth would be that we give you credit for you work which we promote. That could be in some way beneficial commercially.

**Comment by abrookbanks** [comment]
Covid also doesn't help. Working from home with schools closed is a big problem for working families right now. The UK like the US is in an absolute mess.

**Comment by bhsmither** [comment]
@hairydogltd, I am not finding in the forums your request for a way to see who has bought a particular product.

But I did create a plugin that might suit your needs:
https://forums.cubecart.com/topic/56472-can-you-filter-orders-by-products-sold/

**Comment by hairy-dog** [comment]
It's OK. This was a requirement, so we didn't use cubecart. Years later, migration would be too difficult.

**Comment by Dirty-Butter** [comment]
Being able to search for who bought what would be a nice addition for all orders, not just digital. As it is now I depend on queries via phpMyAdmin to find such information in the order summary table usually.

**Comment by bhsmither** [comment]
I will start working on this.

**Comment by abrookbanks** [comment]
Thanks so much. 🙏🏻

**Comment by bhsmither** [comment]
[2741 - Reset Digital Downloads.txt](https://github.com/cubecart/v6/files/5985117/2741.-.Reset.Digital.Downloads.txt)

**Comment by mediadogg** [comment]
Nice work. I will definitely add this someday, after I learn how to protect it from being removed by upgrades.

**Comment by bhsmither** [comment]
These 'Feature Requests', having been posted in the GitHub, are meant to be part of core code. As such, these edits won't be removed by upgrades. An upgrade will add these edits and make them part of the core code.

**Comment by abrookbanks** [comment]
Yes. I intend to make this part of core. Thanks all.

**Comment by mediadogg** [comment]
What a team!!!!
