### ISSUE TITLE
Spelling typo in admin dashboard message

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2743]
`<![CDATA[This update has been ignored however next time an update is released by the develper a notification will be shown again.]]>`

developer has a typo and punctuation missing

This update has been ignored. However, next time an update is released by the developer, a notification will be shown again.

**Comment by abrookbanks** [comment]
They don't half make this confusing. Looks like we need to replace it with:

```
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxxxxxxx-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-xxxxxxxx-1');
</script>

```

I can't see how this affects ecommerce tracking yet.
