### ISSUE TITLE
Edited Order Keeps Formatted GC Value

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2745]
1. Go through the motions of purchasing a GC, but stop short of actually making payment.
2. In admin, manually edit the order (it shoul dbe databased as pending).
3. The value of the GC is now databased as the locale formatted string of the value.

In `orders.index.inc.php`, near line 357, the value of the GC `custom` serialized GC data is formatted to the locale.

This string gets POSTed.

In `orders.index.inc.php`, near line 126, the POSTed GC data - 'value' is still formatted - is re-serialized to `custom` and databased.

On the edge case where the admin edits an order before the customer actually manages to pay for it, the corrupted 'value' is now part of the CubeCart_order_inventory record, 'custom' string.

It is this string that is used to populate the Gift Card email details. Thus, the customer gets an email that has a "Value" of an oddly formatted number.

Please see: https://forums.cubecart.com/topic/56598-gift-cards-problem/

**Comment by abrookbanks** [comment]
Great finding. Thank you.
