### ISSUE TITLE
Fatal error: MySQL server has gone away in /home/xxx/public_html/classes/db/mysqli.class.php on line 42

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2746]
If MySQL goes down due to an issue like too many connections this error is displayed giving awaye server paths. 

A less informative error is required.

**Comment by ulanded001** [comment]
HI, Same issue, but this time I changed the DB password to be able to acces mysql admin.. 
HOw  or where do I fix the new Password?
Thanks a lot !

**Comment by ulanded001** [comment]
got the solution.. this worked : 

Hi, you can change the database name to work with your store in /includes/global.inc.php as long as the passwords havent changed.
So using ftp open /includes/global.inc.php

You will get:

<?php

$glob['dbdatabase'] = web21-store';

$glob['dbhost'] = 'localhost';

$glob['dbpassword'] = 'my_password';

$glob['dbprefix'] = 'myPrefix_';

$glob['dbusername'] = 'my_username';

$glob['installed'] = '1';

$glob['rootDir'] = '/home/httpd/vhosts/mydomain.com/httpdocs/shop';

$glob['rootRel'] = '/shop/';

$glob['storeURL'] = 'http://www.mydomain.com/shop';

?>

Simply change $glob['dbdatabase'] = web21-store'; TO READ $glob['dbdatabase'] = web233-store';

If the passwords have changed, you will have to access Cpanel / MyPHPAdmin and alter or view the database password and edit the above $glob['dbpassword'] = 'my_password'; with your new password.

Hope that makes sense.

Makes perfect sense, and better still worked like a charm!

Thanks for your help

**Comment by abrookbanks** [comment]
No you've missed the point I'm afraid. Please try our forums or contact support. It sounds likely you need to edit your includes/global.inc.php file.
