### ISSUE TITLE
Customer Details to have Dbl-Opt Indicator

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2747]
Feature Request:

When viewing details about a customer, add an indicator showing if the customer has:
1. Not Dbl-Opt
2. Dbl-Opt
A phrase on the side reminding the admin if this detail matters based on the Config GDPR Dble-Opt setting.

**Comment by havenswift-hosting** [comment]
The current double opt in is only for newsletter signups, not specifically for customers which is a new feature request here https://github.com/cubecart/v6/issues/2748

**Comment by bhsmither** [comment]
It is informative re: Newsletters on the Add/Edit General page, "Subscribed to newsletter?" indicator.

This references https://forums.cubecart.com/topic/56618-newsletter-sign-up-issue-sorry-but-we-have-not-been-able-to-validate-your-email/

**Comment by abrookbanks** [comment]
<img width="530" alt="Screenshot 2021-03-30 112128" src="https://user-images.githubusercontent.com/4520803/112974201-1b815400-914a-11eb-9ab8-ab3b074381de.png">
