### ISSUE TITLE
Downloadable Product Options

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2749]
Thanks to our good friend Brian. 
[Testing-Instructions.txt](https://github.com/cubecart/v6/files/5867111/Testing-Instructions.txt)
[Code-Changes-Instructions.txt](https://github.com/cubecart/v6/files/5867112/Code-Changes-Instructions.txt)

**Comment by bhsmither** [comment]
Please keep in mind the above instructions are for CC629.

Since then, following versions of CubeCart have moved code, so the line numbers will not match and the exact code to find and replace has somewhat changed (streaming feature, etc).
