### ISSUE TITLE
Export Catalogue does not include the Categories field

### ISSUE THREAD

**Issue by tonyrsutton** [cubecart/v6#2750]
Under Inventory -> Export Catalogue - it does not export the Categories field

According to https://support.cubecart.com/hc/en-gb/articles/360003831277-How-do-I-use-the-bulk-product-import-tool-

It appears to be missing the **cat_id** field from it.

Is this a bug? If so, can this please be added in the next release?

Thanks.

**Comment by abrookbanks** [comment]
It could actually have more than one category. Maybe it should add them all with the primary category name first.

**Comment by tonyrsutton** [comment]
Yes, because it will help a lot. And I can then use this field to do an import as well so it will set the correct cats, rather than doing it manually after importing.

Thank you.

**Comment by tonyrsutton** [comment]
@abrookbanks Any chance of including this in the next release? Cheers.

**Comment by abrookbanks** [comment]
Thanks.
