### ISSUE TITLE
Code Review: Redundant Iteration?

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2752]
In `mysqli->_execute()`, `$this->_result` gets built from iterating across `$result->fetch_assoc()`. The opportunity to tweak the recordset row is taken to `strip_slashes`.

Then, in `DB->select()`, `$output` gets built from iterating across `$this->_result`.

Is there a reason why `$output` cannot directly equal `$this->_result`?

Is there a reason why not returning `$this->_result` directly? (line 722)

Perhaps this is vestigial?

As regards #2753, suggest leaving this as is.

**Comment by abrookbanks** [comment]
See https://github.com/cubecart/v6/commit/77971d75bd298445f8c96d72945660fe880ea585
