### ISSUE TITLE
Code Hook Request

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2753]
In `DB->select()`, `$output` gets built from iterating across `$this->_result`.

This affords us an opportunity to tweak the recordset at a common point, instead of at each needed place amongst the codebase.
(See: https://forums.cubecart.com/topic/56623-sorting-is-not-logical/)

Requesting a hook where `$output` is being built from iterating across `$this->_result` via `$row`.

**Comment by abrookbanks** [comment]
I wonder if there is a real word example where this would be useful. If so it may be nice to implement. In the meantime removing the output array is far more appealing.

**Comment by abrookbanks** [comment]
Closing as per feature request guide.
