### ISSUE TITLE
AIOS to Restrict Country and County/State Lists to Only Those Enabled 

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2754]
When AIOS offers a list of Countries when setting up a Zone, all countries are presented.

Likewise, when AIOS offers a list of Counties/States when setting up a Zone, all counties/states are presented.

Request the database queries that fetch from CubeCart_geo_country and CubeCart_geo_zone to respect the `'status'` column.

**Comment by abrookbanks** [comment]
Fixed with 1.0.20.

**Comment by abrookbanks** [comment]
Needs reopening because status can be > 1

**Comment by abrookbanks** [comment]
Fixed for 1.0.20 check for CubeCart_geo_zone status => 1
