### ISSUE TITLE
BUG : seo_url path problem

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2756]
Core 6.4.2 using core foundation skin

If a site has "Add category to product URL path?" SEO store setting set to "top level and all sub-categories" and it seems to be adding the category path again and again for each sub-category level !

On a newly created product this is the url that was generated !!

https://www.domain.co.uk/terrain/terrain/6mm/terrain/6mm/walls-fences/terrain/6mm/walls-fences/brick-walls/terrain/6mm/walls-fences/brick-walls/high/100mm-damaged-high-brick-wall-straight-2-test.html

This should be https://www.domain.co.uk/terrain/6mm/walls-fences/brick-walls/high/100mm-damaged-high-brick-wall-straight-2-test.html

So for each sub-category, it is adding the preceding category path again

so for "6mm" sub-cat it is adding "terrain" again before it
for "walls-fences" sub-cat it is adding "terrain/6mm" again before it
for "brick-walls" sub-cat it is adding "terrain/6mm/walls-fences" again before it
for "high" sub-cat it is adding "terrain/6mm/walls-fences/brick-walls" again before it

**Comment by havenswift-hosting** [comment]
This has only started happening since upgrading the site from 6.2.8 to 6.4.2 so code changes between these versions will be the cause

**Comment by abrookbanks** [comment]
Commit above has incorrect issue ID.

**Comment by bhsmither** [comment]
Is anyone currently working on this?

**Comment by havenswift-hosting** [comment]
Not as far as I am aware - happy to work directly with you on this one - please get in contact

**Comment by abrookbanks** [comment]
Sorry guys I'm still doing less than normal. I'm bloody hoping schools go back on 8th March. I've done a few bits on here but 95% of my time is help desk. I haven't got to this yet.

I'm DESPERATE to see schools open.

**Comment by hairy-dog** [comment]
A friend of mine is a teacher. Over a month ago she said she was staying home until 8th March. Although BJ says it will be decided by the numbers, not the date, that date seems to be established some time ago. Only three weeks!
  

  

  
  
 -- Iain  

  
  
  
  
  
>

**Comment by abrookbanks** [comment]
Both my wife and I work full time. Having both kids at home full time is hell... especially with homeschool.   

We are lucky compared to others. There must be single parents in high rise apartments. I have no clue how they cope.

**Comment by abrookbanks** [comment]
Assumed fixed via #2772. Please let me know otherwise.
