### ISSUE TITLE
Feature Suggestion: Generate Promotional Codes for download

### ISSUE THREAD

**Issue by tonyrsutton** [cubecart/v6#2757]
I'd like to suggest a way to generate Promotional Codes by following a few questions like

Discount Type
Discount Value
Expire Date
Number of codes to be generated

and so on

Once you have answered the questions, I click on the generate button and it will output the Promotional Codes with the codes as random letters that is unique to each of them. Then it allows me to download it as CSV (of the options I picked) so I can use it to print on business cards, etc to be given away or put in the parcel as part of the order.

**Comment by bhsmither** [comment]
Is there some part of this:
https://www.cubecart.com/extensions/plugins/preset-gift-certificate-/-voucher-codes
that might not be a solution? (It is a few years old, so may need to verify with the author about making sure there is a version for PHP7.)

**Comment by tonyrsutton** [comment]
Thanks, yes I did see it, but it's more focused on Gift Voucher, whereas I am looking for Promo Code i.e. 5% off your next purchase.
