### ISSUE TITLE
Code Review: Cookie Construction in Setup

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2758]
Regarding #2689, please review /setup/index.php, line 537:
```
        $same_site = CC_SSL ? 'SameSite=None' : '';
        setcookie('delete_setup', true, time()+7200, "/;$same_site");
```
Here, the path string contains a semi-colon, causing:
PHP Warning:  Cookie paths cannot contain any of the following '**,; \t\r\n\013\014**'

Suggest following the fix in the other issue.

**Comment by abrookbanks** [comment]
See 1ae752eb362df41b1c4a7c851299f5ea16bbc27a
