### ISSUE TITLE
Code Check: SEO Paths Extensions

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2759]
Regarding #2719, where `.html` gets appended, but on a fresh install, the paths do **not** have the `.html` extension.

(It could be something I did, but please check.)

**Comment by abrookbanks** [comment]
This is intentional. New store shouldn't have .html as standard. I hope I understood you ok. 

The seo table should cater for both with and without .html.
https://github.com/cubecart/v6/blob/v6-master/setup/db/upgrade/6.4.0.sql#L38-L40
