### ISSUE TITLE
Text Field - Import Issue

### ISSUE THREAD

**Issue by NaturalSigns** [cubecart/v6#276]
Sorry to say but I can still see an issue with text import in b6.  (i have made a fresh listing and fresh text fields just in case).
Basket looks ok....
![basket](https://cloud.githubusercontent.com/assets/10531097/6349707/07b36d56-bc25-11e4-9140-a22e3f9380f0.jpg)

But print order form misses off some text (also same printing invoice from admin)....
![print order form](https://cloud.githubusercontent.com/assets/10531097/6349711/1674f328-bc25-11e4-937f-ba6f9f5d9c7c.jpg)

Admin inventory is now fixed though! (its not all bad!)
![admin correct](https://cloud.githubusercontent.com/assets/10531097/6349719/3b468de2-bc25-11e4-8542-5c1f371cdc18.jpg)

**Comment by abrookbanks** [comment]
Was this order placed after upgrading to beta 6 or before? I think old orders can't be fixed. :(

**Comment by NaturalSigns** [comment]
Running B6, created a new product with new options just to make sure.  Placed a new order and the above is what i see (i'm afraid)

**Comment by abrookbanks** [comment]
I've reproduced this..

**Comment by abrookbanks** [comment]
Got it. After applying patch only new orders will be fixed. Sorry! Thanks for sharing! :)
