### ISSUE TITLE
Repo to Adopt WIP Protocol

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2761]
Requesting issue tags to indicate if a Feature Request, or Bug, has had work started on it, and to have them put to use as appropriate.

I am interested in solving the occasional Feature Request. But, if there is someone else who has already started solving it, I would want to either collaborate or step-aside. I would not want to be making duplicative efforts.

I understand that, on the possible event someone has said they are working on it, but then quietly gives up, the progress of the Feature Request languishes in nescience. I will leave that up to you to solve that.

**Comment by abrookbanks** [comment]
Good shout thanks for this. I've added it.
