### ISSUE TITLE
Timezone Chooser has Bad Option

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2762]
Regarding #2483, the phrase "Use default server time (X/Y)" is a valid selector option.

And it has a valid meaning: "Unless overridden by another choice, we will use this (X/Y) setting as the local timezone." (settings.index.inc.php, near lines 389-392)

However, POSTing this selector option fails the `preg_match()` giving the configuration a -zls-. (settings.index.inc.php, near lines 138-140)

Until the admin actually changes this to a **real** selector option, displayed times will be wrong.

Suggest putting the phrase "Use default server time (X/Y)" as the `<label>` hint or the form element's hint. And maybe re-phrase it to something like: "(X/Y) is the server's timezone".

**Comment by abrookbanks** [comment]
Option 1 should be empty.

**Comment by bhsmither** [comment]
In my opinion, that empty option should not be there at all.

Please use it as an instruction, not as an unvalued option.

Suggest also that since `ini-get('date.timezone')` can be seen, auto-set the selector for that.

**Comment by abrookbanks** [comment]
With an empty option it knows not to try and set it.

**Comment by bhsmither** [comment]
I concur that the web browser will not include in POST that form element's key (name) with having this unvalued option as the displayed choice.

But the store's configuration remains set with an empty string (ultimately UTC), with a misleading phrase still showing in the selector.
