### ISSUE TITLE
BUG : Sessions being aborted when IP address or user agent changes

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2763]
There is a mechanism to abort sessions if the system detects a change of IP address or a change (however small) in the user agent

I am not sure that this is even needed for users - browser can be updated or people can be logged into a site on multiple devices using different browsers from same address ; or the IP address can change due to dynamic address update or moving between mobile areas.

However, Google have started changing IP address and / or user agent in the middle of crawl sessions leading on some sites to hundreds / thousands of aborted sessions per day which could lead to problems getting a site indexed or updated as quickly and will also lead to sites having bloated session tables

One example from one site and splitting up the error report from the error_log file - this is duplicated thousands of times a day on this one site but also seeing it in multiple other sites.

So here the IP address and user agent changes

Old IP Address: '66.249.70.101' 
New IP Address: '66.249.70.103'

Old User Agent: 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.140 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'

New User Agent: 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.114 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)' in /home/XXXXXXXX/public_html/classes/session.class.php on line 753

As a minimum, known bots need to be excluded from aborting a session in these circumstances but this would then rely on maintaining a list of "known" good bots

**Comment by abrookbanks** [comment]
Relates #2755

**Comment by abrookbanks** [comment]
With HTTP only and Secure cookie flags user agent comparison shouldn't be required. We can see that it causes issues with latest iOS with Safari is an issue too.
