### ISSUE TITLE
PHP Warning from AOIS module

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2764]
Seeing this on a couple of sites - 

PHP Warning:  Invalid argument supplied for foreach() in /home/XXXXXXXX/public_html/modules/shipping/All_In_One_Shipping/shipping.class.php on line 46

**Comment by abrookbanks** [comment]
Hmm that doesn't add up. Are they on the latest version?

Line 46 starts:
```
$this->_item_count = 0;
	if(isset($this->_basket['contents']) && is_array($this->_basket['contents'])) {
		foreach ($this->_basket['contents'] as $item) {
			// XXX May want to exclude digital products from the item count, i.e.
			// if ($item['digital']) continue;
			$this->_item_count += $item['quantity'];
		}
	}
```

**Comment by havenswift-hosting** [comment]
Ooops !  Sorry - updated !

**Comment by abrookbanks** [comment]
Ah cool. Pleased that fixed it.
