### ISSUE TITLE
Customer Cannot Empty Cart

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2765]
There is a customer that has not yet provided a billing address.

This logged-in customer, after clicking 'Add to Basket', the Basket pop-over shows a "Checkout" button.

Click on "Checkout", and this customer is taken to the account page to add an address. {The configuration setting "Jump to basket on add" does not cause any different result.)

Not yet finding it necessary to provide an address, the desired task is simply to empty the Shopping Basket.

This is not possible. "A billing address is required before you can proceed."

Suggest adding a "Empty Basket" link to the Shopping Basket pop-over.

Suggest not inhibiting a "View Basket" button on the pop-over for logged-in customers.

**Comment by abrookbanks** [comment]
<img width="303" alt="Screenshot 2022-12-05 at 15 55 43" src="https://user-images.githubusercontent.com/4520803/205682523-dbb70d23-06b7-4e5d-a689-6081793f449a.png">
