### ISSUE TITLE
BUG: Custom SEO URL Path - not auto generated

### ISSUE THREAD

**Issue by tonyrsutton** [cubecart/v6#2767]
Possible bug on Custom SEO URL Path

**Steps**

Add a product as usual including the Product Name. Save it. Go back to this product you created and click on 'Search Engines' tab. Under "Custom SEO URL Path", you should see the path in there. Observe the path name.

Now, go back to general tab of this product and edit the Product Name. Once edited, go back to Search Engine tab and clear the Path box. I am doing this because of this - "* This will be generated automatically if left empty." so it's empty now that I have cleared it out. I saved it. The Product Name got saved OK, but with the SE path is only generated it based on the OLD PATH and not the new path based on the updated Product Name.

Is this excepted behaviour?

I am on **CC v6.4.2**

Discussion: https://forums.cubecart.com/topic/56651-custom-seo-url-path-not-auto-generated/

**Comment by abrookbanks** [comment]
Thanks for this. I'd say it's a bug.

**Comment by tonyrsutton** [comment]
Thank you. Obviously the link above in my 1st post no longer exists, but as long as you have enough info, then all is good.

Cheers

**Comment by abrookbanks** [comment]
To clarify: Fixed for products and documents. Categories still need doing..

**Comment by abrookbanks** [comment]
This will resolve #2831 which can be closed as a result.
