### ISSUE TITLE
UI Review: FileManager Downloads Action Column

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2769]
**Generally,** the list of anything has certain action icons in the right-most table column, and multi-select checkboxes in the left-most table column. See the Product Inventory table. (Where practical - re: FilePickers)

Suggest the table in Filemanager Dowsloads conform to this general style.

**Comment by abrookbanks** [comment]
<img width="1319" alt="Screenshot 2021-03-08 161226" src="https://user-images.githubusercontent.com/4520803/110348144-3bc96180-8029-11eb-961d-e459c0e3400c.png">

**Comment by abrookbanks** [comment]
Much better. Thanks! :)
