### ISSUE TITLE
Admin Nav Organization

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#277]
Trivial Comments:

In the Advanced section, I think Statistics and Sales Reports are not so much a "maintenance" item. Maybe their own nav section: "Reporting".

The PHP Info link points to: admin.php?_g=misc&node=server-info
However, there is no file `misc.index.php` which is what the breadcrumb "Misc" points to when viewing this page.

I have arguments for both sides of the fence, but the preponderance for me is to put PHP Info on its own tab in Maintenance.

Likewise, for me, I would put the configuration settings for "Performance" on it's own tab in Maintenance. On the tab space for these settings, an advisory that states, "Changing these settings from their default may impact the performance of CubeCart. WARNING: Only change these settings if you are confident you know what you are doing, or having been so instructed by a support technician."

**Comment by abrookbanks** [comment]
I'd like to leave PHP Info where it is for now. Thanks for the cool suggestions.
