### ISSUE TITLE
BUG: Clicking on "More" button at bottom shows new contents above fold on Mobile View

### ISSUE THREAD

**Issue by tonyrsutton** [cubecart/v6#2771]
CubeCart: v6.4.2
PHP: 7.4.13
Database: 5.5.5-10.3.27-MariaDB

Going to one of an Categories and when you scroll down to bottom, there is an 'More' button. I click it. It shows more products then I keep scrolling down to bottom where I see the 'More' button again and so on.

This works fine on my PC (Windows 10, Chrome)

BUT...

On my mobile phone (Android, using Chrome), when I click the 'More' button, it stays there and the new products listing just refresh above the fold. That means I do not see that it has loaded up more products, and that I had to scroll back up to see them.

Just to confirm, I changed the settings on my mobile phone to 'Desktop site' and the behaviour is correct. Just that it doesn't behave the right way when viewing as Mobile.

I don't think this is mean to happen. Therefore I am reporting this as a bug with the Mobile View of CubeCart.

**Comment by abrookbanks** [comment]
Thanks for this.
