### ISSUE TITLE
SEO Path for New Item Foiled in Admin

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2772]
When the admin creates a new category, the code in `category.index.inc.php` does make a trip through `SEO->setdbPath()` to insert a record in `Cubecart_seo_urls`, but is foiled in the attempt because of a new feature that inserts a record in `CubeCart_admin_log` when the admin has logged in for fewer than three times (`DB->clearCacheNotice()` **before** returning out of DB->insert()`.

(Practically, there is no reason to log this message.)

Still making an accurate trace of program execution as this contributes to other weirdness. See:
https://github.com/cubecart/v6/issues/2756

Basically, the insert into `CubeCart_category` results in a `$cat_id` being '0', which `SEO->setdbPath()` cannot use.

It is then up to processes that happen in the storefront that generates the seo_url, which, somewhere, something gets it wrong.

I am starting to think the correct solution would be to use the returned value from `DB->insert()` instead of relying on an immediate call to `DB->insertid()`

See also:
https://github.com/cubecart/v6/issues/93 (should be fixed)
https://github.com/cubecart/v6/issues/2670 (should be fixed)
https://github.com/cubecart/v6/issues/2690 (should be fixed)

**Comment by abrookbanks** [comment]
This makes me mildly anxious.

**Comment by havenswift-hosting** [comment]
Needs some good testing before release lol

**Comment by abrookbanks** [comment]
shouldn't do... should do! LOL

**Comment by abrookbanks** [comment]
All seem to be working fine. Hopefully this is the last of bad ID association. Well done Brian!
