### ISSUE TITLE
Clear Cache Advisory is Logged

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2773]
After any admin action that triggers the Clear Cache Advisory, that advisory gets inserted into the `CubeCart_admin_log` from one to four times, and if the admin is new.

This is not really an issue, as thirty days later, these records will be deleted, but there is no reason to log this anyway.

As mentioned elsewhere, this logging could interfere with what would be the last_insert_id of the previous INSERT statement.

**Comment by abrookbanks** [comment]
Thanks.
