### ISSUE TITLE
Image Tweak

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2774]
The admin skin images 0.png and 1.png are too close to the browser's rendering of a checkbox that is disabled (greyed-out).

Request that two new images be created, darker than the existing images, and the existing images be renamed to 0_disabled.png and 1_disabled.png (for possible future use).

**Comment by abrookbanks** [comment]
I'm failing with this. I'm absolutely hopeless with photoshop.

**Comment by bhsmither** [comment]
![0](https://user-images.githubusercontent.com/4073092/107800534-ba293100-6d13-11eb-8ff3-f972768948c2.png)
![1](https://user-images.githubusercontent.com/4073092/107800562-c44b2f80-6d13-11eb-8793-82407e521852.png)

**Comment by abrookbanks** [comment]
Thanks Brian.
