### ISSUE TITLE
Feature Suggestion - Royal Mail API

### ISSUE THREAD

**Issue by tonyrsutton** [cubecart/v6#2779]
Can we please have CubeCart to use Royal Mail API i.e. a official plug-in from CubeCart?

https://www.royalmail.com/business/tools-services/apis

Thanks.

**Comment by havenswift-hosting** [comment]
Already been tried and failed to get support - see https://forums.cubecart.com/topic/56297-calling-on-all-royal-mail-customers/

**Comment by Rob-Tea** [comment]
I'm probably wrong, but to me it looks like this changed the end of last year (for Royal Mail Click ad Drop) and is now open to all developers... https://clickanddrop.uservoice.com/forums/399930-general/suggestions/37754239-click-drop-rest-api

**Comment by tonyrsutton** [comment]
Yes Rob, this is what I raised this feature suggestion for to have this to use the new Royal Mail API now that it's out of beta.

Thanks.

**Comment by abrookbanks** [comment]
It can only be done via https://storefeeder.com/ which is owned by Royal Mail.

**Comment by abrookbanks** [comment]
Closing this as a duplicate. This is already on radar.
