### ISSUE TITLE
Custom OID query issue.

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2781]
order.class.php:
`$GLOBALS['db']->misc("UPDATE `".$GLOBALS['config']->get('config', 'dbprefix')."CubeCart_order_summary` SET `custom_oid` = `$column` WHERE `custom_oid` = '' OR `custom_oid` = null");`

The query should read "IS NULL", not "= NULL".

**Comment by abrookbanks** [comment]
Thanks.
