### ISSUE TITLE
TAX

### ISSUE THREAD

**Issue by CanadaFB** [cubecart/v6#2782]
We have 2 taxes here. How do you add a second tax?  Can you add 2 taxes i.e. 

5%
7%
Total

Thanks, I have been trying to make this work but maybe it is not possible? What is the solution?

**Comment by bhsmither** [comment]
There is an issue on the GitHub that asks the programmers to fix this.

**Comment by CanadaFB** [comment]
Thank you for confirming that. Do you have a link to the issue you referred to?

**Comment by bhsmither** [comment]
Look at issues 1786, 2453, 2454, and 2559.
