### ISSUE TITLE
Canada Post Extension

### ISSUE THREAD

**Issue by CanadaFB** [cubecart/v6#2783]
Hi,

This does not show up anywhere. I have looked in the Store Settings. I also tried the Rebuild and no luck. Where will it appear?

Of course it is enabled and I have configured it, but nothing.

Can anyone tell me how to fix this, and where exactly it should it show up? This is quite important!

Thank you much.

**Comment by bhsmither** [comment]
This module uses CP's "SellOnline". I read somewhere that CP isn't giving out new merchant accounts that want to use this. I may be wrong. But see:
https://forums.cubecart.com/topic/51911-resolved-canada-post-extension-not-appearing/

**Comment by CanadaFB** [comment]
Thank you very much for the reply. I will follow up with Canada Post. Have a great day.
