### ISSUE TITLE
Printable Gift Invoice, Reciept or Card - Feature Suggestion

### ISSUE THREAD

**Issue by onebrowncow** [cubecart/v6#2784]
When a order is placed with an alternative address to be sent as a gift to a customer, ability to print the order as a gift receipt without prices, shipping or tax shown and including any gift message posted in the message box by the buyer also including both the buyer name perhaps, as example "a gift from John Smith".

This might also be styled up as something more attractive as a gift card rather than an invoice or packing slip with lines like a gift from: buyers name. to: recipients name along with details of the product enclosed and suppliers details.

**Comment by onebrowncow** [comment]
![gift-reciept-blurred](https://user-images.githubusercontent.com/13252688/108057077-05ac4980-704a-11eb-927b-53dbf857e78f.jpg)
this is an image of our modified CC4 invoice which allowed us to print a gift receipt

**Comment by Dirty-Butter** [comment]
I was able to accomplish this by basically cloning all code/files/database entry involved in printing the invoice with appropriate renaming and tweaking. I agree it would be a nice feature to have as stock code that survives upgrades.

**Comment by abrookbanks** [comment]
Closed until feature reviews are next done.
