### ISSUE TITLE
Code Check: AIOS Class

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2785]
Considering that instantiating the AIOS class with no arguments, thus the class defaults to `$basket = false`, suggest that all the setters for the private variables that ask for values from `$this->_basket` be grouped inside an `if()` block testing for the `!empty`-ness of the basket.

PHP complains: Trying to access array offset on value of type bool

Suggest also to give default values on the private variables.

**Comment by abrookbanks** [comment]
When does this happen so I can test?

**Comment by abrookbanks** [comment]
Ignore that I figured it out.
