### ISSUE TITLE
Code Review: A Variable's Use

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2786]
In `Cart->loadShippingModules()`, the variable `$shipping` first is assigned the recordset having the active shipping modules.

This array is iterated to process each module in turn. For each module, `$shipping` is then assigned the class object.

As with standard PHP code processing, the last use of a variable has the last value assigned to it. This means, at the end of the `foreach()` loop, `$shipping` no longer has the recordset.

Suggest a new array type variable be used to hold the collection of class objects. This allows the following hook to access the public items -- like, groupName() -- of the already instantiated shipping classes.

(This is very close to the strategy of having `$GLOBALS` contain an array of class objects.)

Changes to the code:
```
Find near line 1054:

         if (class_exists($module['folder']) && method_exists((string)$module['folder'], 'calculate')) {
             $shipping = new $module['folder']($basket_data);
             $packages = $shipping->calculate();
             // $group_name will overwrite the folder name to make the shipping group on the dropdown configurable
             $group_name = method_exists($shipping, 'groupName') ? $shipping->groupName() : $module['folder'];
             if ($packages) {


Change to:

         if (class_exists($module['folder']) && method_exists((string)$module['folder'], 'calculate')) {
             $shippingClass[$module['folder']] = new $module['folder']($basket_data);
             $packages = $shippingClass[$module['folder']]->calculate();
             // $group_name will overwrite the folder name to make the shipping group on the dropdown configurable
             $group_name = method_exists($shippingClass[$module['folder']], 'groupName') ? $shippingClass[$module['folder']]->groupName() : $module['folder'];
             if ($packages) {
```

**Comment by abrookbanks** [comment]
Thanks for this. 👍
