### ISSUE TITLE
Settings to be part of store's admin console

### ISSUE THREAD

**Issue by tonyrsutton** [cubecart/v6#2787]
When I did a fresh install of the store, I noticed it asked for their email address for mailing list. As I do not want the option of mailing list to be offered to anyone at all but I could not find a way to hide it.

Please can this be setting configurable within the Admin area so it shows/hides the mailing list option?

This is what I had to hide/commented out so far...

skins/foundation/templates/content.register.php

```
<div class="row">
      <div class="small-12 large-8 columns">
         <input type="checkbox" id="mailing" name="mailing_list" value="1" {if isset($DATA.mailing_list) && $DATA.mailing_list == 1}checked{/if}><label for="mailing">{$LANG.account.register_mailing}</label>
      </div>
   </div>
```

skins/foundation/templates/content.checkout.confirm.php

```
<div class="row">
   <div class="small-12 large-8 columns">
      <input type="checkbox" id="mailing_list" name="mailing_list" value="1" {$MAILING_LIST_SUBSCRIBE}><label for="mailing_list">{$LANG.account.register_mailing}</label>
   </div>
</div>
```

It would be awesome if this is admin configurable to hide/show the mailing list option.

Thank you.

**Comment by havenswift-hosting** [comment]
This isnt a store / admin configurable setting - this is specific to whatever skin is being used and so therefore should be controlled by the skin.  Although many people do use Foundation as provided - it was never intended to be used but only as a starting point for other skins to be developed.

We have this as a configurable option in our free Skin Configuration plugin which works with our two skins Retail Therapy and Nautical

**Comment by tonyrsutton** [comment]
Yes, I understand, but it would be good to be part of the 'official' skin and using the IF statement to see if it's enabled/disabled in order to display it or not. This saves time when upgrading to the next version and reduces the amount of editing.

Thanks.

**Comment by havenswift-hosting** [comment]
It will be up to @abrookbanks of course but I would completely disagree that this should be part of core - it is a skin function and not core CubeCart.  You may want this but there will be hundreds or thousands of other things that other people would want and knowing Al's hatred of settings anyway.....  Foundation also isnt really the "official" skin as I said - it was only ever meant to be a starting point for further development and I am constantly surprised that anyone uses it on live stores

**Comment by hairy-dog** [comment]
It's an interesting quandary. Zen Cart has gone down the path of making the starter templates really ugly so that people will design their own, which has given the impression that Zen Cart stores are ugly.
Cubecart has a passable starter skin, so it doesn't look ugly, but that means too many people use it as the "default".
Leaving that aside, I think that allowing store admin users to change website settings is a bit like letting bus drivers adjust the engine management computer. Some may be able to do it safely, but in general, it's not a smart move to allow it.

**Comment by abrookbanks** [comment]
We need a pretty new default skin with plenty of colour schemes.

**Comment by havenswift-hosting** [comment]
>>We need a pretty new default skin with plenty of colour schemes.

Yes 100% but CubeCart also needs 15 to 20 other skins as well - we have a couple and NiteFox is adding some nice ones !  The problem with having one skin even with different colours and especially historically, is that all skins have had pretty much the same boring layout with small tweaks here and there.

However, none of those (except as noted, our two skins) would solve this request.  Core CubeCart and skin functionality are two completely separate things and introducing skin configuration parameters into core CubeCart goes completely against the modularisation that happened so successfully in V5.

>>I think that allowing store admin users to change website settings is a bit like letting bus drivers adjust the engine management computer. Some may be able to do it safely, but in general, it's not a smart move to allow it.

Good analogy !  Some are obviously required and there will always be a need for some "Store Settings"

**Comment by tonyrsutton** [comment]
So what is the difference between what I have suggested here and going in to Store Settings -> Feature and turning off/on for the following:

Enable Product Reviews/Comments
Number of sale items to display

And under Store Settings -> Layout
Products per page
Show 'Latest Products' on homepage?
Number of 'Latest Products' to display

and so on. This is a website settings to me.

My main aim is to have the Newsletter sign up section to be Disabled/Enabled under the Feature tab of the Admin console, so other people who write the skins can include it so people like me can disable/enable it without having to change the coding.

Hopefully this make sense?

**Comment by havenswift-hosting** [comment]
I understand your argument but :

Product reviews and sale items are both functionality being added or not, and while it does affect layout, they arent specifically to do with layout.

For your other examples "Products per page" is deprecated and has been moved to the skin and the Latest Products being there is very old and there is a big argument that this should also be done for that - I am sure that if that functionality was being added now, it would be done via the skin.

I fully understand your desire to exclude the newsletter signup box (we had a number of requests for it, which was why it was added to our skin plugin from very early stages) but as I said that is one of many hundreds of things that could be configured / excluded so where do you stop - you cannot add many hundreds of new configurable options to Store Settings - it would be totally daunting for most users and most of them wouldnt ever be used.  Things like this have to be separated out into the skin

**Comment by abrookbanks** [comment]
I think the way forward for this is for the config.xml file to set the possible options for that skin. A part of the admin control panel should read this and create a page to work with these settings accordingly. This will bring a lot of flexibility.

**Comment by abrookbanks** [comment]
Closing for now to reopen when this work gets underway. Pulling this in in line with a sexier new default skin would be ideal.

**Comment by abrookbanks** [comment]
Relates to #1671
