### ISSUE TITLE
PayPal Commerce Issue

### ISSUE THREAD

**Issue by HookedTackle** [cubecart/v6#2789]
We are trying to instal this Plugin, PayPal Commerce, and seem to be hitting a snag. We get as far as the "return to cubecart'" button and then we see this error message. 

<img width="851" alt="Screenshot 2021-02-18 at 09 16 37" src="https://user-images.githubusercontent.com/79258010/108350874-a92d6380-71dc-11eb-9f24-01d88e3bf327.png">

**Comment by abrookbanks** [comment]
What does the PHP error log show? If you reproduce it and then check the PHP error log it will be one of the latest ones. 

I'd expect it to be something missing in your PHP config required by the script.

**Comment by HookedTackle** [comment]
Hello, no faults have been recorded in the error log but the request log does show an error at certain stages of the process. I have attached what we can see from our end. We managed to get the Paypal Commerce to work by installing an older version but this still was not showing up on our checkout page.

**Comment by abrookbanks** [comment]
I don't see anything attached. When there is a 500 error there will be a corresponding error message. Can't help without knowing that.

I believe this is an issue specific to your web hosting environment and not a bug in CubeCart. Please report back with the error log details.

**Comment by HookedTackle** [comment]
Hello, the error is a 404 error not 500. Again, I have attached a folder to this email with relevant images documenting everything we see. This was working a few days ago and has now suddenly stopped functioning. We are currently unable to take any payment because of this issue at this time.

**Comment by abrookbanks** [comment]
There is nothing attached. This is not an inbox for email. You are replying publicly on GitHub here: https://github.com/cubecart/v6/issues/2789

**Comment by HookedTackle** [comment]
Hello, the error isn’t with the installation of the Paypal commerce anymore, the issue is that even when installed and linked to our account the Payment gateway isn’t showing for customers. This is obviously costing us money every day. I cannot see any reason as to why it would not show on our checkout page. 

regards,

Spencer Howard
spencer@hookedtackle.co.uk

Hooked Tackle Ltd,
88 All Saints Rd
Newmarket
Suffolk.
CB8 8HF.
(01638)661594

**Comment by abrookbanks** [comment]
Please open a technical support ticket or try our forums.
