### ISSUE TITLE
Feature Suggestion: Auto remove Out of Stock products from Latest/Featured Product front page

### ISSUE THREAD

**Issue by tonyrsutton** [cubecart/v6#2792]
I have a few items that are on the front page for Latest/Featured Product and they often goes out of stock as soon as I put them up for sale.

It would be good if it can be auto-removed from Latest/Feature Product when they go out of stock, so it can push any 'in stock' products toward the front page for maximum views.

And once the stock comes back, it's re-added to Latest/Featured products.

**Comment by bhsmither** [comment]
We invite you to explore the setting "Hide out of stock". But keep in mind that if you are logged in as an admin, the "hiding" is disabled.

**Comment by tonyrsutton** [comment]
I did see it, thanks - but I do not wish to hide it as I plan to add the stock notification. Just that I don't want it to appear on front page when the stock is gone but still allow for user to find it via search.
