### ISSUE TITLE
Bug: Items Table formatting misaligned

### ISSUE THREAD

**Issue by tonyrsutton** [cubecart/v6#2793]
v6.4.2

Admin Console -> Customers -> Orders

I have an order where the Item table formatting are misaligned and does not show up correctly. Here's a screenshot

https://pasteboard.co/JPe7BxM.png

As you can see, the £9.00 got pushed down to next row, the 2nd row of £5.00 got pushed down to next row too, and then finally the Subtotal of £14.00 got pushed to the left of the 3rd row

I understand this might be because the Item line might be too long but...

1) If this is a fixed table, it should have given me a maximum characters I could enter for the Item name
2) Resolve this by using a 'floating' table width so it adjusts based on the item name length

So not sure if this is a bug or not but will leave this decision to Al/team

Thanks.

**Comment by abrookbanks** [comment]
Great find. Thank you!

**Comment by abrookbanks** [comment]
<img width="514" alt="Screenshot 2021-03-08 145747" src="https://user-images.githubusercontent.com/4520803/110338219-ac1eb580-801e-11eb-819d-a8cee749b12c.png">
