### ISSUE TITLE
Users Online: 404 Actual Path to be Revealed

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2794]
```
/classes/session.class.php, find near line 631:

'location' => currentPage(),

Change to:

'location' => currentPage() . (strpos(currentPage(),"_a=404")!==false ? "<br />Real:".$_SERVER['REQUEST_URI'] : ""),
```
Little sense in providing a link to a 404 page.
```
statistics.index.php, find near line 234:

<td>{$user.location} <a href="{$user.location}" target="_blank">&raquo;</a></td>

Change to:

<td>{$user.location}{if $user.location|strpos:"_a=404" === false} <a href="{$user.location}" target="_blank">&raquo;</a>{/if}</td>
```

**Comment by tonyrsutton** [comment]
Tested on v6.4.2 - works great, thank you. Would be awesome if this can be merged with the next release @abrookbanks - cheers!

Related discussion topic - https://forums.cubecart.com/topic/56707-tracing-the-404s/

**Comment by abrookbanks** [comment]
I went for a slightly different approach using a strikethrough. Thanks for this its quite simple and powerful!

<img width="220" alt="Screenshot 2021-03-08 100843" src="https://user-images.githubusercontent.com/4520803/110307006-5b936200-7ff6-11eb-8075-1c44127683f9.png">

**Comment by tonyrsutton** [comment]
> I went for a slightly different approach using a strikethrough. Thanks for this its quite simple and powerful!
> 
> <img alt="Screenshot 2021-03-08 100843" width="220" src="https://user-images.githubusercontent.com/4520803/110307006-5b936200-7ff6-11eb-8075-1c44127683f9.png">

Thank you :)
