### ISSUE TITLE
Feature Suggestion: Include what product(s) has been sold in Sales Report & Export

### ISSUE THREAD

**Issue by tonyrsutton** [cubecart/v6#2796]
Admin Console -> Reporting -> Sales Reports

I would like to see what products was sold in this Sales Report so I can work out which products are popular with sales, allowing mw to focus on what to purchase stock.

And the data to be included with the CSV Export.

Thanks.

**Comment by bhsmither** [comment]
In admin, Statistics, Best Selling Products tab, you will get the top-selling items, 15 per page.

We can build a custom export module. I think I have a few laying about that were built for others with the same request.

**Comment by tonyrsutton** [comment]
I did see the Best selling tab, but no export option and no "View All", which means I have to copy & paste page by page which is not practical.

Would be interested to see what model you have if you don't mind?

**Comment by bhsmither** [comment]
See you on the forums!

**Comment by abrookbanks** [comment]
Closing for now as per our guidelines. Thanks for the feature request.
