### ISSUE TITLE
PayPal doesn't work and age verification make bug on cubecart

### ISSUE THREAD

**Issue by Adrienmotblur** [cubecart/v6#2797]
Hi my PayPal module cubecart does not work. Why?WWhen I add age  verification codage on my top web page. Cubecart ask hack... How to create a module and add my code verification age? Hi have see a module for age verification on cubecart website but I do pay for it 🤔.

Thank you. I need to disallow sell to under 18years people.

**Comment by tonyrsutton** [comment]
Please use https://forums.cubecart.com or https://support.cubecart.com/hc/en-gb for knowledge base or support queries.

This is not the right place for support.

Thanks.

**Comment by Adrienmotblur** [comment]
Hi where I do put this post thank? in faq there no solution

**Comment by Adrienmotblur** [comment]
There's French forum?

**Comment by Dirty-Butter** [comment]
https://forums.cubecart.com/topic/55650-paypal-commerce/

**Comment by Adrienmotblur** [comment]
There's French forum? Thank you and for the age verification?
