### ISSUE TITLE
Template Variable Collision

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2799]
Both `GUI->_displaySaleItems()` and `Catalogue->displayCategory()` use `PRODUCTS` as the template array variable.

Normally, this is not a problem.

However, create this scenario:
* Enable Sales Mode - Per Product
* Set to blank or not zero number sale items to display (not really tested)
* Set all applicable product's Sale Price to zero.
* Have a category with zero products in it (probably with a sub-category, but not tested)
* View that category

Note the On Sale box appears with items for sale at $0.00.

Suggested edits:
```
In the skin template box.sale_items.php, find:

{if $PRODUCTS && $CONFIG['catalogue_sale_mode']>0}

Change to:

{if $SALE_PRODUCTS && $CONFIG['catalogue_sale_mode']>0}

A few lines later, find:

{foreach from=$PRODUCTS item=product}

Change to:

{foreach from=$SALE_PRODUCTS item=product}

A few lines later, find:

{if empty($product.sale_price)}

Change to (having a currency symbol makes this not empty):

{if empty($product.sale_price_unformatted)}


In the file /classes/gui.class.php, find near line 1476:

$GLOBALS['smarty']->assign('PRODUCTS', $vars);

Change to:

$GLOBALS['smarty']->assign('SALE_PRODUCTS', $vars);
```

**Comment by abrookbanks** [comment]
This is tricky because 3rd party skins will need updating. I think we have to include the old macro name too `PRODUCTS`.

**Comment by havenswift-hosting** [comment]
If you are going to make the suggested changes to the foundation skin then these could easily be done to third party skins as well - those that are unsupported are missing so many changes / improvements that people shouldnt really be using them and they probably need removing from the marketplace.

I think it is a bad solution testing for the name of a skin as in this commit !

**Comment by abrookbanks** [comment]
Yeah I agree actually. We will need a release note.. skin developers need to be onboard.

**Comment by havenswift-hosting** [comment]
>>We will need a release note.. skin developers need to be onboard.

Complete agree - certainly I and NiteFox will be updating our skins - who else is there ??

**Comment by abrookbanks** [comment]
Ha! Not as may as I would like. :-(
