### ISSUE TITLE
Defect - Fucntion buildURL() does not respect the seo_extension setting correctly which can break storefront links

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2800]
If an SEO URL already exists with a .html extension in the database, then this is returned with .html regardless of the SEO Extension setting.

The function only respects the setting if the database record does not yet exist. this is causing problems for stores who upgraded rather than cleanly installed and changed the setting to not use extensions.

**Comment by Noodleyman** [comment]
additional info:
CubeCart_seo_url.custom = 1 which contains a .html extension, but can't even open those URL's, 404 error.

**Comment by tonyrsutton** [comment]
Thank you for looking into this.

**Comment by Noodleyman** [comment]
I also tracked another, related problem in the httpredir function. 

`        if (!CC_IN_ADMIN && !strstr($destination, '.') && substr($destination, 0, 1)!=='?') { // Add .html if for some reason its missing!!
            $destination = $destination.'.html';
        }` 

This does not respect the extension setting, and in some cases will actually add .html, even though the .html extension is disabled.

**Comment by Noodleyman** [comment]
I added a quick work around, not sure if this is the best solution but it works for now.

```
        if (!CC_IN_ADMIN && !strstr($destination, '.') && substr($destination, 0, 1)!=='?') { // Add .html if for some reason its missing!!
            if(!empty($GLOBALS['config']->get('config', 'seo_ext'))){
                $destination = $destination.'.html';
            }
        }
```

**Comment by abrookbanks** [comment]
I haven't come across this issue on any of the stores I've upgraded. Why would a .html extension exist in the database once upgraded? The upgrade strips it off.

Have you got a real-world example?

**Comment by tonyrsutton** [comment]
Noodleman and I worked on this for my test website - it was a new & clean installation, no upgrades. And we tested this with a test product that was already set up by the new installation.

**Comment by abrookbanks** [comment]
Ah ok that helps then. If I do a clean install how would I reproduce the bug?

**Comment by Noodleyman** [comment]
It relates to modules that call the function to get a url. As the function
doesn't handle the setting in all cases, the URLs returned can be wrong.
There are a couple things going on here, one being that some items in the
db can be stored with a .html extension, which can sometimes drive an
incorrect link. The other being the workaround I put earlier in this item.
Being a bit vague, not at my desk for a couple of days so going from
memory

**Comment by tonyrsutton** [comment]
> Ah ok that helps then. If I do a clean install how would I reproduce the bug?

Do a clean install of CubeCart and keep everything as default setting. Once done, I installed this Back In Stock Notification.

https://www.noodleman.co.uk/downloads.html#backinstocknotifications

Enable it.

Make sure the test product is out of stock (i.e. stock level 0)

Go to the website and go to the test product (while logged off). I click on Notify me when back in stock. Log on/register

Once logged on, it redirect me back to the product but CubeCart added .html to the url, therefore generating an 404 Not Found - this is even when the CubeCart SEO path are set to be disabled for .html

Hope this is enough for you to investigate - thanks.

**Comment by abrookbanks** [comment]
> some items in the db can be stored with a .html extension 

Do you know which ones? I can't think of or see any. Hopefully, we can pick this up in the future. Enjoy your away from desk time.

**Comment by abrookbanks** [comment]
@tonyrsutton thanks I can try that

**Comment by tonyrsutton** [comment]
Did you manage to repro this?

**Comment by tonyrsutton** [comment]
I also spotted this - #2759

Is it related?

**Comment by abrookbanks** [comment]
Sorry I've not got onto this yet.

**Comment by tonyrsutton** [comment]
Can we get this on v6.5, please? Thanks.

**Comment by abrookbanks** [comment]
> > Ah ok that helps then. If I do a clean install how would I reproduce the bug?
> 
> Do a clean install of CubeCart and keep everything as default setting. Once done, I installed this Back In Stock Notification.
> 
> https://www.noodleman.co.uk/downloads.html#backinstocknotifications
> 
> Enable it.
> 
> Make sure the test product is out of stock (i.e. stock level 0)
> 
> Go to the website and go to the test product (while logged off). I click on Notify me when back in stock. Log on/register
> 
> Once logged on, it redirect me back to the product but CubeCart added .html to the url, therefore generating an 404 Not Found - this is even when the CubeCart SEO path are set to be disabled for .html
> 
> Hope this is enough for you to investigate - thanks.

REALLY helpful thanks.
