### ISSUE TITLE
Feature Suggestion: Show image upon hoovering over Product name

### ISSUE THREAD

**Issue by tonyrsutton** [cubecart/v6#2801]
It would be good to have the image to show up when you hoover the mouse pointer over each of the items that was ordered under Admin Console -> Customers -> Orders -> [Order ID] -> Items

Now and then I often having to go to the product itself, then going to Images to see/confirm what it is before adding it to the box.

Having the image to come up when hoovering the mouse pointer over each of the item listed would be a BIG help to pickers and time saving as well.

Thanks.

**Comment by Dirty-Butter** [comment]
I needed this as well, as many plush animals have very similar descriptions and it's easy to send the wrong one if I don't look at the photo before pulling from stock.
I edited the orders.index.php file to use this instead. It requires opening another tab of the item, but that lets me easily read the description for condition if that is also needed.
``              <strong>{$product.quantity} x {$product.name}</strong> - <a href="?_g=products&sort[updated]=DESC&action=edit&product_id={$product.product_id}#image" target="_blank">{$product.product_code}</a> ({$product.line_formatted}) <span>{$product.price_total_formatted}</span>
``
