### ISSUE TITLE
Feature Suggestion: Total Number of item in the Order

### ISSUE THREAD

**Issue by tonyrsutton** [cubecart/v6#2802]
In Order Summary page under Admin Console -> Customers -> Orders -> [Order ID] -> Under Items

It would be awesome to show the total number of items for this order. Now and then, I would have a huge order and I often having to do a count to see how many items IN TOTAL in this order.

Maybe something like 'Items - xx' where xx is the numbers of items just before the list of the items.

**Comment by jasehead** [comment]
I put some code in my orders.index.php template to add product quantities and give a final IN TOTAL number of items - so 3 forks + 7 knives = 10 in total. Is that what you meant?

`{foreach from=$PRODUCTS item=product}{$intotal=$intotal+$product.quantity}{/foreach}`

Then you would use something like this to display the total count:

`(total of {$intotal} items)`

If you just want to count how many product lines then you could say $intotal=$intotal+1, so 3 forks + 7 knives = 2 product lines.
