### ISSUE TITLE
Code Review: Reliance on Plugin Function

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2805]
At numerous places throughout the code, there are hidden checkboxes `class="toggle"` that will eventually end up having a matching `<img>` tag, so that an assertive value of a "0" or "1" will get POSTed.

The code that watches for these hidden checkboxes `class="toggle"` is in the FileTree plugin (near line 364).

Suggest the FileTree plugin manage its own toggle checkbox hidden inputs for the FilePickers, and any other such checkbox hidden input use the same basic code as found in the FileTree plugin, but independent and placed in admin.js.

(This allows for the freedom to use a different FilePicker should that ever come about.)

FYI: I am looking to do something with the AIOS module, and that something involves adding a checkbox hidden input. But I am getting interference from the FileTree code when the `$("a.aios-add").on("click", function()` gets executed. Thus, my point about maintaining separate checkbox hidden inputs.

**Comment by abrookbanks** [comment]
Good shout this. Find and replace made it easy and I can't find any bugs off the back of it.
