### ISSUE TITLE
Can the price to pay be added to the admin products overview screen?

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2806]
Retail price is available, but if the product is on sale then it isn't possible to see the actual price a customer would pay. having the price to pay would be useful if you're working through the list specifically targeting sale items.

this may get a little complex with items that use options with various prices, but adding a price range for options in the price to pay would also be quite a useful addition.

**Comment by Debyred** [comment]
There is no where in Cubecart backend (Admin side) to see what products currently have a 'Sale Price' , this means having to go to your store front and viewing the 'Sale' category, then going back to the backend to find them. Cubecart V3 & V4 used to show the normal price and sale price in the product inventory.

**Comment by hairy-dog** [comment]
What a pity nobody invented tabbed web browsers.

**Comment by Debyred** [comment]
So is it not better to be able to scroll through your product inventory and see at a glance which you have reduced, rather than bouncing back and forth between tabs. Might be ok if you only have a few products with reduced prices but we sometimes have hundreds.

**Comment by Noodleyman** [comment]
Even adding a filter to only show in sale items would do the trick. could even be added to the existing filter list (category).  seems a simple thing to add that a lot of people could make use of.

**Comment by jasehead** [comment]
In the products.index.php template, I added a sale price column between price and stock level like this:

`<td>{$product.price}</td>`
`<td>{$product.sale_price}</td>`
`<td align="center">{$product.stock_level}</td>`

**Comment by Debyred** [comment]
Thank you so much jasehead - that works brilliantly .
I actually ended up using the Translations column (as I don't use translations) and changed the heading name. Can see at a glance which products are on sale.
Made a note in my own changelog so I can redo after any future updates.

**Comment by jasehead** [comment]
Yes, I forgot to say that if you wanted to insert a new column you need a new heading too (between price and stock level):

`<th nowrap="nowrap">{$THEAD.price}</th>`
`<th nowrap="nowrap">{$THEAD.price_sale}</th>`
`<th nowrap="nowrap">{$THEAD.stock_level}</th>`
