### ISSUE TITLE
Possible to by-pass shipping when combination of digital and tangible products

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2807]
This was first discovered on a client site where they are losing hundreds a month in shipping.  Then also validated in our test / dev environment and finally in a fresh 6.4.2 store with only AIOS shipping added.  It makes no difference what sort order is chosen for shipping costs or what skin is used.

If you first add a digital product to the basket and view the basket, then go and add a tangible product that attracts a shipping cost, although the shipping cost is in the dropdown, it is not pre-selected and "Please Select" is shown.  It is possible at this point to  checkout and pay without ever being required to add or pay for shipping.

Video proof already supplied to @abrookbanks

**Comment by abrookbanks** [comment]
Can you reproduce it here where there is one digital item, one physical and two shipping rates using AIOS shipping? Stripe is in test mode. 
https://www.brooky.com/v6 

I can't.

Edit: That URL is connected to a Raspberry Pi that seems to like to crash. Hopefully it will be up.

**Comment by havenswift-hosting** [comment]
Yes I can reproduce and just have with an order placed on the store for a digital and physical order where no shipping is charged. Follow the sequence that I did in the video - I can do it on any store

**Comment by abrookbanks** [comment]
Nice one. I'll check the video again.

**Comment by havenswift-hosting** [comment]
Also couldn't believe that it was possible which is why I tested in multiple stores, multiple skins and multiple configs.  Can walk you through it now if you want or we can do tomorrow - ping me on WhatsApp if you want

**Comment by abrookbanks** [comment]
Thanks Ian.

**Comment by abrookbanks** [comment]
I reproduced it. Add digital first, view basket, back to choose physical then checkout. Brilliant. Thanks.

I'm sure it's simple. Famous last words right?!

**Comment by havenswift-hosting** [comment]
Exactly - amazed not been seen before but client store has a LOT of free digital products that are very often coupled with tangible products.

Sure you will find and fix it !

**Comment by abrookbanks** [comment]
Yeah I can't either. I changed your issue title so not to cause a panic. This probably affects a very small percentage of merchants. I'm on it though.

**Comment by havenswift-hosting** [comment]
I agree it wont be affecting a large majority but a reasonable number do sell digital and tangible products and I would guess that many dont realise that this is happening - this client has now traced that it has been happening for a while before they discovered it - appreciate you looking into it so quickly !

**Comment by abrookbanks** [comment]
Can you try that fix for me. From my testing it works.

**Comment by abrookbanks** [comment]
I'll close once confirmed fixed.

**Comment by havenswift-hosting** [comment]
Thanks Al - Confirm that this solves the problem for sites using Foundation and either of our two skins - unfortunately it doesnt solve it for the client who are using a 3rd party skin but will chat to the developer to get him to look into it.

As far as I am concerned, it can be closed

**Comment by abrookbanks** [comment]
Thanks for your feedback.

**Comment by bhsmither** [comment]
May we ask which third-party skin?

**Comment by havenswift-hosting** [comment]
There was no problem - the solution is good
