### ISSUE TITLE
A New de-DE Definitions XML

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2808]
Attached is the work from forum user MostlyConfused who added almost all the new phrases to the translation definitions file since the existing version. (The email file was not worked on.) This version is deemed **2.0.0**. Hundreds of strings were updated.

Note that the "introduced" attribute did not carry over from the source file.

Also in the ZIP attachment is a second file that has a translation for a few of the extensions.
[de-DE.zip](https://github.com/cubecart/v6/files/6092164/de-DE.zip)

**Comment by abrookbanks** [comment]
Master language updated....

**Comment by abrookbanks** [comment]
Updated and updated extension too. Thanks for this.
