### ISSUE TITLE
Code Review: AIOS v1.0.7 vs 1.0.8

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2809]
Somewhere between 14 May 2015 and 11 Mar 2016, the AIOS shipping.class.php had the following added t it:
```
In the calculate() function:
		if(empty($this->_basket['delivery_address']['country_iso'])) {
			return false;
		}
```
Is there a record why this was deemed necessary?
_"Fix for when shipping estimates are disabled"_

Considering the AIOS module, having analyzed its program flow, has come to be understood as being rather versatile.

So versatile, that "zones", per se, need not be in the context of geographic areas. Especially since there is a "Rest of the World" zone.

So, I have in mind relaxing that test and seeing what happens.

**Comment by abrookbanks** [comment]
Thanks this has been removed. I don't know why it was added.
