### ISSUE TITLE
Feature Suggestion: Users Online - Name the Web Bots

### ISSUE THREAD

**Issue by tonyrsutton** [cubecart/v6#2810]
In Admin console -> Reporting -> Statistics -> Users Online tab

I see all of the Users online. They are named as 'Guest' plus registered customers.  'Guest' is also used for web bots. 

I click on "Display Customers Only"

I see Guest & Registered customers online.

That means somehow CubeCart knows who these web bots are to filter this out.

Can this be changed so instead of 'Guest', it shows up as 'Google', 'Facebook', 'PayPal' and so on - this way, I can see who's on my store.

And make it editable so it allows me to tag the IP to a web bot with a name (i.e. they have new IP address range)

**Comment by abrookbanks** [comment]
Thanks Tony! We will review for next midpoint release.
