### ISSUE TITLE
Print Order Form Followup

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2812]
Concerning issue #2698, the comment made Dec 2 (https://github.com/cubecart/v6/issues/2698#issuecomment-737399830) needs to be followed up.

The customer's email does not include the product's options.

**Comment by bhsmither** [comment]
A suggested fix as detailed at this forum post didn't seem to solve it:
https://forums.cubecart.com/topic/38607-extra-text-field/?do=findComment&comment=246838

Tracing the code.

**Comment by bhsmither** [comment]
Used wrong variable names.

All working now (fingers crossed).

**Comment by abrookbanks** [comment]
Already resolved.
