### ISSUE TITLE
Multi delete function not working in digital file manager

### ISSUE THREAD

**Issue by yarnell902** [cubecart/v6#2813]
hey folks,

In doing some work on the file manager I just noticed that the multi delete does not work while in digital mode. It does work in image mode though. I tried deleting a file and then updating the file list but it did not work. Fresh Install

Ohh, also, I tried the individual delete icon and that does work. Its just the multi delete that does not work.

just wanted to let you know.

**Comment by abrookbanks** [comment]
Reproduced. I'll get it fixed in the next 24 hours.

**Comment by yarnell902** [comment]
great, thanks.
