### ISSUE TITLE
Potential Image Cropper Issue

### ISSUE THREAD

**Issue by yarnell902** [cubecart/v6#2815]
Hey,

I manage to run into another issue with the file manager. We'll I'm not sure if this is an issue or if it was designed this way, but when I open the image cropper and try to crop, the crop window is fixed to the top left corner making it impossible for me to crop the image (unless I actually want to crop the top left corner). When I try to move the crop window I do see the 4 arrows but the crop window will not move.

I've tested it on both my install and your demo site. Same thing on both.

Again, not sure if this was intentional or not but it would be excellent If I could reposition the crop window.

Thanks.

**Comment by abrookbanks** [comment]
Thanks for this.

**Comment by yarnell902** [comment]
Your welcome :-)

**Comment by yarnell902** [comment]
Hey, I updated my files as per your edits and the cropper is still not working.

**Comment by abrookbanks** [comment]
Did you clear your browser cache?

**Comment by yarnell902** [comment]
I did, I tried on crome, firefox and edge. no work.

**Comment by abrookbanks** [comment]
Any JS errors in the console?

**Comment by yarnell902** [comment]
Uncaught TypeError: l is undefined
    drag http://xxx/xxx/skins/default/js/plugins.php?52c11c6ae976461151ad53df32f0589b:145
    jQuery 10

**Comment by yarnell902** [comment]
Uncaught TypeError: l is undefined
    drag http://xxx/xxx/skins/default/js/plugins.php?52c11c6ae976461151ad53df32f0589b:145
    jQuery 10
        _trigger
        _trigger
        e.widget/</h[t]</<
        _mouseDrag
        e.widget/</h[t]</<
        _mouseMove
        e.widget/</h[t]</<
        _mouseMoveDelegate
        dispatch
        handle
plugins.php:145:1479
    drag http://xxx/xxx/skins/default/js/plugins.php?52c11c6ae976461151ad53df32f0589b:145
    jQuery 10

**Comment by abrookbanks** [comment]
Thanks

**Comment by abrookbanks** [comment]
I can't reproduce this I'm afraid. http://static.cubecart.com/issue-2815.mp4 

It may be because JQuery is out of date which as been updated in a different issue.

**Comment by yarnell902** [comment]
I noticed in the video you did not try to move the box around. The issue occurs when you click inside the box and try to drag the box around the image... at least for me it does. So if you try to drag the box to the bottom right corner, for instance.

**Comment by abrookbanks** [comment]
Ah! I'll try that...

**Comment by yarnell902** [comment]
perfect... thank you sir :-)

**Comment by abrookbanks** [comment]
No thank you. It was a classic situation of a developer not looking at real world situation.
