### ISSUE TITLE
Remove ini_set('memory_limit', '256M') from ini.inc.php

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2819]
This line should be removed from the core ini.inc.php

There should be no need  - either an account can change the memory limit themselves or this will fail if the server limit is set any lower.

If the account memory_limit is set higher this then has the negative impact of reducing the limit !

**Comment by abrookbanks** [comment]
Weird I was thinking the same yesterday whilst looking at error reporting (which should be off by default) too.
