### ISSUE TITLE
Potential issue with tax not calculating

### ISSUE THREAD

**Issue by yarnell902** [cubecart/v6#2820]
I'm not sure if this was done by design or not but the tax does not auto calculate when creating/modifying an order. Anyway to get this to auto calculate so we don't have to pull out the calculators?

thanks.

**Comment by rbosma** [comment]
Don't know if done by design. I bypass this issue by logging in as customer and creating the order. 
Would be nice to work in admin mode

**Comment by havenswift-hosting** [comment]
This is one of the very many features in our Enhanced Admin Order Entry plugin. See https://www.cubecart.com/extensions/plugins/enhanced-admin-order-entry

**Comment by abrookbanks** [comment]
Large known slightly annoying complex issue.
