### ISSUE TITLE
REQUEST: Joyride nub position tweak

### ISSUE THREAD

**Issue by yarnell902** [cubecart/v6#2822]
Hey,

I've been trying to figure out how to position joyrides nub position on the bottom right but I can't seem to figure it out, I'm assuming its because its not programmed into the javascript file. Would it be possible to get this functionality added?

Here is a joyride solution I found but it dosn't seem to work with cubecart.
https://codepen.io/adam-huffman/pen/eKgIE

Note the following code
`<li data-id="firstStop" data-text="Next" data-options="tip_location: top; nub_position: left, bottom;">
    <p>nub_position: left, bottom;</p>
  </li>`

**Comment by tonyrsutton** [comment]
It would be good if you explain how it can help CubeCart and what it does for CubeCart.

**Comment by yarnell902** [comment]
Hi tony, at the moment I can only position the nub on the left/right/top/bottom of the joyride tip window. Extending the nub position to top-right or left-bottom or bottom-right would allow for more flexability when positioning the tip window.

Hope that helps.
