### ISSUE TITLE
Update Dropzone

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2823]
4.3.0 to 5.7.3.

**Comment by abrookbanks** [comment]
Customisations taken out of dropzone.js and put into admin.js instead. This should make future upgrades easier.

**Comment by bhsmither** [comment]
The edits to admin.js just may have solved the pickle I got myself into when implementing issue #2816.

I didn't realize CubeCart's DropZone had any customizations.

**Comment by abrookbanks** [comment]
Ah cool! Yeah good to know. To be honest I didn't know it was customised either but a diff showed me. 

This was a great idea. Thanks for suggesting.

**Comment by bhsmither** [comment]
Code Review:

When instantiating the DropZone instance against `$("div.dropzone")` (line 478), we initially pass in the option:
```
url: dropzone_url  // effectively $("div#dropzone_url").text();
```
Then, in the `this.on("processing") override, we re-specify that option (line 498):
```
this.options.url = dropzone_url+subdir;
```
I (emphatically) propose the `subdir` be appended to the existing option value:
```
this.options.url += subdir;
```
I have plans for the initial declaration.

**Comment by abrookbanks** [comment]
That doesn't work because it could get appended more than once... 

e.g. 
?_g=filemanager&product_id=120&subdir=folder1
?_g=filemanager&product_id=120&subdir=folder1&subdir=folder2
?_g=filemanager&product_id=120&subdir=folder1&subdir=folder2&subdir=folder3

**Comment by bhsmither** [comment]
How? Where would the extra subdirs come from?

I will experiment with dropping a **collection** of image files onto the dropzone and see what happens. That is the only way I can see that _might_ cause "processing" to iterate across the collection, appending another `$("#val_subdir").text();` each time. But it would be the same subdir, no?

**Comment by bhsmither** [comment]
Yup. Exactly. On the fourth iteration:
```
?_g=filemanager&product_id=1&mode=image&subdir=Test&subdir=Test&subdir=Test&subdir=Test
```
But all the images ended up in the Test folder!

**Comment by bhsmither** [comment]
Moving my 'plans' into the "processing" override...

**Comment by abrookbanks** [comment]
Sorry I'm lost now. Why would we want to appending of subdir?

**Comment by bhsmither** [comment]
Keep in mind I'm working on issue 2816...

For an infinitesimal erg of optimization, the idea was to actually use what was already given in the initial group of options.

My next experiment will not include an initial url option.

Nope. Needs an action attribute on `<form>` or a non-null initial option. Go to plan "C".

**Comment by abrookbanks** [comment]
OK cool. I'm happy to make changes necessary for #2816.

Maybe the changes above can be part of that issue?

**Comment by bhsmither** [comment]
The changes above will be required for 2816 to succeed.

**Comment by abrookbanks** [comment]
I trust your wisdom as such a devoted CubeCart hero. 👍🏻💥

**Comment by bhsmither** [comment]
No, no. I edited my previous comment.

Please revert that "+=" appending idea.

**Comment by abrookbanks** [comment]
🙃 I've got muddled... reverted
