### ISSUE TITLE
Feature Request : Downloadable Product Options

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2826]
Brian has written the code to add this to core and it has been tested by a couple of people - see https://forums.cubecart.com/topic/56223-digital-files-linked-to-a-products-options/

There have been several discussions about adding this into core but never in a formal way via an issue here - think this would be a great addition to core as often requested

Brian's instructions added as attachments

[Code-Changes-Instructions.txt](https://github.com/cubecart/v6/files/6155436/Code-Changes-Instructions.txt)
[Testing-Instructions.txt](https://github.com/cubecart/v6/files/6155437/Testing-Instructions.txt)

**Comment by bhsmither** [comment]
Possible duplicate of #2749.

**Comment by havenswift-hosting** [comment]
It certainly is !
