### ISSUE TITLE
FileManager Class Enhancement

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2828]
In `filemanager.index.inc.php`, the FileManager class is instantiated with a known `$mode` and `$subdir`. Those modes are 'digital' or (default) 'image'. Shortly after, `FM->upload()` is called.

In `upload()`, legitimate work gets done, but near the end, there is code that assumes this instantiation of FM is for an 'image' mode.

The private method `_assignProduct()` must be rewritten to manage the correct database table depending on if the instantiation is for a downloadable file - that is, `CubeCart_image_index` for an image, and `Cubecart_inventory` 'digital' column for a file. (Calls to `_assignCategory()` and the 'gc' code can be skipped.)

**Comment by bhsmither** [comment]
In filemanager.class.php, near lines 1235-1240, suggest:
```
                    if ($this->_mode == self::FM_FILETYPE_IMG && isset($_GET['cat_id']) && $_GET['cat_id']>0) {
                        $this->_assignCategory((int)$_GET['cat_id'], (int)$fid);
                    }
                    if ($this->_mode == self::FM_FILETYPE_IMG && isset($_GET['gc']) && $_GET['gc']==1) {
                        $GLOBALS['config']->set('gift_certs', 'image', (int)$fid);
                    }
```
Near line 1277:
```
Find:
if ($GLOBALS['db']->select('CubeCart_image_index', false, array('main_img' => 1, 'product_id' => $product_id))!==false) {

Add above:
if ($this->_mode == self::FM_FILETYPE_IMG) {

Find:
$GLOBALS['db']->insert('CubeCart_image_index', $record);

Add after:
} else {
    $GLOBALS['db']->update('CubeCart_inventory', array('digital' => $file_id), array('product_id' => $product_id));
}
```

**Comment by abrookbanks** [comment]
Great stuff thanks!!
