### ISSUE TITLE
Cookies being rejected

### ISSUE THREAD

**Issue by yarnell902** [cubecart/v6#2829]
Hey,

It seems Mozillahas made some updates... I'm getting the following error:

error Cookie “CC_7B4D6A07E5” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by abrookbanks** [comment]
This will be resolved when using SSL SameSite requires SSL I believe.

**Comment by yarnell902** [comment]
Changing the following in classes/session.class.php seemed to do the trick.

From
`if($params['httponly']) {
$attributes .= ';HttpOnly';
}`

To
`if($params['httponly']) {
$attributes .= ';HttpOnly';
$attributes .= ';SameSite=Strict';
}`
