### ISSUE TITLE
CC5 / CC6 - Upgrade Script Bug

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#283]
I doubt this bug will ever hit any product server, and certainly will not hit any Linux servers, however it did trip me up in one my windows based development servers this week.

If your web server install path contains any spaces (Example "C:\Program Files\")  then the process to move & rename images fails because the path becomes invalid.

File: 
setup/scripts/5.0.0b1.php
Line 103.

Rename function will error because the path is invalid.

This happens because the regex gets applied to the entire path to the image during the rename process rather than just the file name, so spaces get replaced with underscores and the path is then invalid.

Here is a fix written the long way for the example:

REPLACE:
rename($filename, preg_replace($regex_slash_keep, '_', $filename));

WITH:
$path_parts = pathinfo($filename);
$path = $path_parts['dirname'];
$fname = $path_parts['filename'] . "." . $path_parts['extension'];
$path = $path . preg_replace($regex_slash_keep, '_', $fname);
rename($filename, $path);

**Comment by Noodleyman** [comment]
Updated the fix, forgot to include a trailing slash after the folder name.

WITH:
$path_parts = pathinfo($filename);
$path = $path_parts['dirname'] . "/";
$fname = $path_parts['filename'] . "." . $path_parts['extension'];
$path = $path . preg_replace($regex_slash_keep, '_', $fname);
rename($filename, $path);

**Comment by Noodleyman** [comment]
actually, just realised that it won't be renaming folders, only files, so the fix I've put in there will only work for file names..

**Comment by Noodleyman** [comment]
THIS takes care of folders and file names.

$path_parts = pathinfo($filename);
$path = $path_parts['dirname'] . "/";
$fname = $_SERVER['DOCUMENT_ROOT'] . preg_replace($regex_slash_keep, '_', str_replace($_SERVER['DOCUMENT_ROOT'], '', $path) . $path_parts['filename'] . "." . $path_parts['extension']);
rename($filename, $path);

**Comment by abrookbanks** [comment]
I hate Microsoft. :trollface:

**Comment by abrookbanks** [comment]
Sorry but I'm keen to leave this as is. Our requirements are for Linux / Unix.
