### ISSUE TITLE
Admin FileManager Not Using DropZone Upload Form Input Name

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2830]
For images:
In `filemanager.index.inc.php`, near line 69, there is:
```
} elseif ($_FILES['file0']['size']>0) {
```
According to the docs from DropZone, the default option for the form element, type=file, name attribute to use is:
`paramName: "file"`

PHP complains that `$_FILES['file0']` has an unknown index and the success message is not queued.

For files:
If, on the other hand, the standard input element has `class="multiple"`, the MultiFile plugin is involved, and it is told to use '$name$i' (which equals "file0").

So, maybe:
```
} elseif ( (isset($_FILES['file0']) && $_FILES['file0']['size']>0) || (isset($_FILES['file']) && $_FILES['file']['size']>0) ) {
```

**Comment by abrookbanks** [comment]
<img width="578" alt="Screenshot 2021-03-29 115927" src="https://user-images.githubusercontent.com/4520803/112827424-3a1e1700-9086-11eb-881a-f2bb704aaa35.png">
