### ISSUE TITLE
Feature Suggestion: Remove spaces in Delivery Tracking textbox

### ISSUE THREAD

**Issue by tonyrsutton** [cubecart/v6#2833]
Admin Console -> Customers -> Orders -> [Order ID] -> Delivery tab

Under Shipping Information -> Delivery Tracking (URL or Code)

Can this text field please be set up so when I copy & paste a tracking code, the empty spaces/space be removed by itself.

i.e.

RA123 456 789 AZ

becomes

RA123456789AZ

This will save us a lot of time when pasting and then editing the tracking code before saving it.

**Comment by abrookbanks** [comment]
My concern with this is merchants using the field the "wrong" way like adding an instruction message.

**Comment by tonyrsutton** [comment]
That's why we have Internal & Note Content - that's what it is for anyway?

Beside the text field description is pretty clear - "Delivery Tracking (URL or Code)" - it doesn't say anything about leaving a note. 

If they did leave a note using this then they're doing it wrong. And we can teach them to use the Note Content. (i.e. RTFM lol)
