### ISSUE TITLE
Auto Generate Code Checkbox Wrong Initial Appearance

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2835]
When adding a new product:

The 'product_code_auto' form element is a `hidden` type, `toggle` class. Yet there is code that adds `checked="checked"` to this form element.

When the javascript* adds the `<img>` tag to hidden `toggle` class inputs, the actual image used is based on the value of the input's `value` attribute.

There is no `value` attribute for the 'product_code_auto' input.

Thus, the image of the checkbox used is `0.png` when the intent is `1.png`.

Suggest in products.index.inc.php, near line 1086:
```
$result[0]['auto_code_checked'] = (empty($result[0]['product_code'])) ? '1' : '0';
```
In products.index.php, near line 169:
```
<div><label for="product_code_auto">{$LANG.catalogue.product_code_auto}</label><span><input name="product_code_auto" id="product_code_auto" type="hidden" class="toggle" value="{$PRODUCT.auto_code_checked}"> <input name="product_code_old" id="product_code_old" type="hidden" value=""></span></div>
```
In admin.js, near line 1024:
```
$("input#product_code").val().length > 0 ? $("input#product_code_auto").val('0') : $("input#product_code_auto").val('1'); $("input#product_code_auto").change();
```

**Comment by bhsmither** [comment]
_Note from above:_ My vote is still to not to place these hidden toggle class input javascript functions into the (customized) filetree plugin. I vote to have them in the general use 'admin.js' file.

**Comment by abrookbanks** [comment]
thanks

**Comment by rbosma** [comment]
@abrookbanks @bhsmither 
Don't know for sure if it happend after this change but for 90% certain.

In my shop it isn't possible anymore to change/toggle the checkboxes in the whole shop. When manuly changing the value in the form and then press 'save' it is changed...

Could one of you kick me in the right direction to look what caused this..
Running latest version of CC with almost all the bug fixes in the meantime...

**Comment by bhsmither** [comment]
We would ask that you force your browser to reload page resources. This is usually done with the keyboard shortcut CTRL-F5.

It may be the case that the new version of the admin.js file has not replaced the cached version your browser may be using.

**Comment by rbosma** [comment]
Done that frequently, doesn't change a thing... 

Wow... Hold on... After clearing cache a dozen of times it seems to work for now...

Thanks @bhsmither  for letting me do same things over... 
don't know why it's working now, because did the same things yesterday and earlier today...

**Comment by bhsmither** [comment]
Let me be clear... I was not referring to Cubecart's cache, but rather the cache that your web browser manages so that repeated requests for images, CSS files, and javascript files can come from its own cache.
