### ISSUE TITLE
Upgrade Script Enhancement

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#284]
The upgrade script has a time limit of 600 defined (10 mins).

This should be set to 0 to disable the time limit all together. I've hit this time limit whilst upgrading a large store and had to increase it before re-running the update.

**Comment by abrookbanks** [comment]
I disagree. Setting this to 0 can cause processes which never end that can crash a server.

**Comment by Noodleyman** [comment]
Then can the time limit be increased to a larger value instead. perhaps 30 mins.

There should be no reason that the process "never ends". it either completes it's job or errors. If it hangs it's because of a flaw in the job it's been asked to do such as a non ending loop.

**Comment by abrookbanks** [comment]
Poor code can cause never ending loops which never end. 30 mins is huge!

**Comment by Noodleyman** [comment]
It is.. although the site i am updating at the moment has taken 45 mins. it's a valid request

**Comment by abrookbanks** [comment]
.. we had a bad piece of code in our software license system years ago. This caused a never ending loop which resulted in a DoS from customers stores on our own server. LOL

**Comment by abrookbanks** [comment]
I don''t think this should go into the code. If you follow this your server will upgrade any inventory size... I've done stores with over 60,000 images this way.

https://support.cubecart.com/index.php?/Knowledgebase/Article/View/218/43/notes-about-upgrading-cubecart-and-resource-limits

**Comment by Noodleyman** [comment]
the max_execution_time change won't work at the php.ini level because the upgrade script overrides it in index.php and sets it to 600, assuming the server supports it.

So, the guide needs to be udpated to reflect that this file should be changed rather than the settings in php.ini

My largest upgrade to date was one of my older stores, 1.2 million products. That one took a long time :)

**Comment by Noodleyman** [comment]
one further update, the time limit works differently between linux and windows. on windows it counts the actual time in seconds that the script has been running. in Linux it counts the CPU time I think. so when doing this on Linux it probably isn't an issue.  in windows you literally get a 10 min window for the entire upgrade.
