### ISSUE TITLE
Incorrect Determination of Like-Items in Basket

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2840]
In catalogue.class.php, (current line 1338, CC642 line 1321), there is:
```
                if (is_array($GLOBALS['cart']->basket) && is_array($GLOBALS['cart']->basket['contents'])) {
                    $quantity = 0;
                    foreach ($GLOBALS['cart']->basket['contents'] as $hash => $item) {
```
We get here from CubeCart's instantiation of the `Cart` class, which runs `__construct()`, which, _if certain conditions are met_, jumps to `add()`, which makes a call to `Catalogue->getProductData()`, which then jumps to `getProductPrice()`, and here we ask for details about `$GLOBALS['cart']` and wanting to iterate across `basket['contents']`.

**However**, at this point, under those certain conditions, the Cart's instantiation has not worked itself back up the stack, thus the `$GLOBALS` array has not yet acquired the ['cart'] key.

PHP issues Notices complaining of "Unknown index 'cart'" and "Trying to get property 'basket' of non-object". This might be PHP 7.4 specific.

At this specific location, CubeCart may get a wrong answer when determining how many like-items are already in the `basket['contents']`.

~~At this location, suggest using `Cart::getInstance()->basket`.~~
Nope. That causes an infinite loop (at least for PHP 7.4). In Debug, it worked for the Database???

Maybe that works in other cases because those other cases, when calling `getInstance()`, the constructor doesn't do much of anything. Certainly not all the work that instantiating the Cart class does.

**Comment by bhsmither** [comment]
This will probably influence #2291, and maybe #2080.

**Comment by bhsmither** [comment]
This is my work-around:
```
/classes/cart.class.php

Find:
    final protected function __construct()
    {

Change to:
    final protected function __construct() { }
    public function preliminary_work() {
--------------------------------------------------------------

/controllers/controller.index.inc.php

Find:
//Initialize cart
$GLOBALS['cart'] = Cart::getInstance();

Change to:
//Initialize cart, then check if item is being added to basket
$GLOBALS['cart'] = Cart::getInstance(); $GLOBALS['cart']->preliminary_work();
```

**Comment by abrookbanks** [comment]
Workarounds are fine by me but I changed the function name to init.
