### ISSUE TITLE
Code Review: Language->loadLanguageXML()

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2841]
In `loadDefinitions()`, the test includes if the variable `$GLOBALS['cache']` is set and not empty (but with what? maybe test for is_object), as well as if the files exist and are readable as an array.

No so for `loadLanguageXML()`. There is no check if the variable `$GLOBALS['cache']` is set and not empty (but with what? maybe test for is_object). The only test is if the files exist.

However, there is no test to make sure these files are readable as an array. In fact, in asking for the file, if the file has expired, it is deleted and `$this->_language_data` (or whatever was asked for) is a boolean false.

(The next occurrence of something triggering the `loadLanguageXML()` of a file that was previously deleted, will cause it to be rebuilt. But that's the **next** occurrence.)

**Comment by abrookbanks** [comment]
The changes with c30daeee10e2e8313f4f177606179e75c2a39073 are causing faults with language caching. Customer complained of a French default language showing english.
