### ISSUE TITLE
Lightbox doesn't zoom on single image

### ISSUE THREAD

**Issue by richguycc** [cubecart/v6#2842]
If I have a product with multiple images, clicking on the main image brings up a gallery of zoomed images. If I have a product with just one image, clicking on the image does nothing. This didn't used to be the case. See thread from forum, the legend that is bsmither had a comment. 

https://forums.cubecart.com/topic/56622-image-zoom-on-products-with-single-image/

**Comment by tonyrsutton** [comment]
I can confirm this as well.
