### ISSUE TITLE
Problem With Database Result

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2843]
This is not yet a real problem, but needs to be aware of.

In `Catalogue->__construct()`, this query is made:
```
SELECT  SQL_CALC_FOUND_ROWS MIN(`live_from`) AS `next_time` FROM `CubeCart_inventory` WHERE `live_from` > UNIX_TIMESTAMP()   LIMIT 1;
```
Followed immediately by:
```
SELECT FOUND_ROWS() as Count;
```
My first point is that this query will always result in a row being returned, even if the WHERE fails to match anything.

According to MySQL docs (as well as MariaDB 10.4.12), for `MIN()`/`MAX()`, if there are no matching rows, there will be a row returned with the value `null`.

(In comparison:
```
SELECT  SQL_CALC_FOUND_ROWS `live_from` AS `next_time` FROM `CubeCart_inventory` WHERE `live_from` > UNIX_TIMESTAMP() ORDER BY `live_from` ASC   LIMIT 1;
```
This returns zero rows.)

My second point is that, for some unknown reason (and I have spent hours testing this), the `FOUND_ROWS()` returns `45`. _I have only eight products._

PHP gives this to CubeCart. Running the same pair of queries with HeidiSQL or MySQL Workbench returns a (correct) value of `1`.

**Comment by abrookbanks** [comment]
Thanks for this.

**Comment by bhsmither** [comment]
Did you make the experiment of testing for the result of `FOUND_ROWS()`?

**Comment by abrookbanks** [comment]
Nope!

**Comment by bhsmither** [comment]
In this case, this isn't a problem to be fixed in CubeCart. Please realize that something wonky is happening, and it just may be some quirk in how PHP reads the response through the MySQLi extension (or MySQLnd - whatever.)

It could be a problem, of course, should code be written in the future that asks for aggregated data with a LIMIT clause.

**Comment by abrookbanks** [comment]
For me it always returns 1. Closing because I don't know what the solution is.
