### ISSUE TITLE
Catalogue->_where_live_from Always Present

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2844]
With respect to #2843, in the Catalogue class, `$this->_where_live_from` starts as a zero-length string.

In `__construct()`, the query as written will always be true-like: a non-empty array `[0]=>(next_time=>null)`.

Thus, `' AND live_from < UNIX_TIMESTAMP() '` will **always** be part of "out-of-stock" queries.

**Comment by abrookbanks** [comment]
Fixed with 5a78ce2b2202f40b1d776a576131e2473486252d
