### ISSUE TITLE
Add List-Unsubscribe header to Newsletter template

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2846]
This should be a simple thing to add as a default part of the Newsletter Email Template and adds credibility to mass sending for newsletters and means that emails are much less likely to be treated as spam

**Comment by abrookbanks** [comment]
Great idea thanks.

**Comment by abrookbanks** [comment]
<img width="616" alt="Screenshot 2021-04-14 164658" src="https://user-images.githubusercontent.com/4520803/114739728-0c50f780-9d41-11eb-933d-02496a62fd31.png">

**Comment by abrookbanks** [comment]
Problem with this is that the unsubscribe URL is correct but it doesn't work via the button in the email.

**Comment by abrookbanks** [comment]
Sadly this just isn't going to work as its email centric for unsubscribing not URL. I can't find a way to trigger a URL to unsubscribe.

**Comment by havenswift-hosting** [comment]
You always need to have the List-Unsubscribe in the header and the unsubscribe url as well.  The List Unsubscribe header doesnt work for all email clients but is beneficial to stop many large email providers from treating an email as spam

https://help.returnpath.com/hc/en-us/articles/222445307-What-is-the-List-Unsubscribe-header-

https://help.litmus.com/article/282-what-is-list-unsubscribe

**Comment by abrookbanks** [comment]
This is hard to test. My email client recognised it with an email unsubscribe but not URL. I can only assume some clients have partly built around RFC2369 but from my testing it doesn't work with ONLY a URL to unsubscribe.

**Comment by abrookbanks** [comment]
So I've recommit this with URL only in the hope that one day some email clients will cope with URL only.

**Comment by abrookbanks** [comment]
> You always need to have the List-Unsubscribe in the header and the unsubscribe url as well. The List Unsubscribe header doesnt work for all email clients but is beneficial to stop many large email providers from treating an email as spam
> 
> https://help.returnpath.com/hc/en-us/articles/222445307-What-is-the-List-Unsubscribe-header-
> 
> https://help.litmus.com/article/282-what-is-list-unsubscribe

I think you misunderstood. The unsubscribe link in the body remains but the header seems to require a mailto to unsubscribe. I'm going to spend a bit more time on this but I think it's only going to work for newsletter systems that allow for unsubscribe by email response not URL.

**Comment by abrookbanks** [comment]
I believe this issue has been implemented correctly. We just have to hope for greater support for URL based unsubscribe headers in the future.

**Comment by abrookbanks** [comment]
<img width="655" alt="Screenshot 2021-04-15 084626" src="https://user-images.githubusercontent.com/4520803/114833050-14537a80-9dc7-11eb-8bdf-b2ccd8da6c41.png">
