### ISSUE TITLE
Checkout on Test site won't work without Captcha enabled

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#2847]
I can't get past the checkout button on a test site where I have recaptcha turned off (site requires password to see). If I turn on captcha, although it does not work, checkout proceeds. The "problem", if you can all it that, is this code on the checkout button:

`button right g-recaptcha`

Seems like there should be some kind of if code for recaptcha, but this is an  abnormal situation - so maybe not an issue at all.

**Comment by abrookbanks** [comment]
Sorry but I can't reproduce this.
