### ISSUE TITLE
Syntax Customers Mailing List

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2848]
In  admin template `customers.subscribers.php`, there is this:
```
<input type="text" name="maillist_format" id="format" class="textbox" value="{$EMAIL_ADDRESS}" title="{literal}e.g. {$EMAIL_ADDRESS} <{$FULL_NAME_SHORT}>{/literal}">
```
Using `<` and `>` inside quotes is usually not a problem for browsers. However, suggest using `&lt;` and `&gt;`.

The `value` attribute is given the Smarty variable `{$EMAIL_ADDRESS}`. This variable has no assignment in the code. Suggest using an empty string. Unless you want the text field actually to return `{$EMAIL_ADDRESS}` as the value - in which case it needs to be inside `{literal}` tags.

The sample given in the `title` attribute is wrong. And the text field needs to be wider. (https://en.wikipedia.org/wiki/Email_address)

Suggest:
```
<input style="width:400px;" type="text" name="maillist_format" id="format" class="textbox" value="" title="{literal}e.g. &quot;{$FULL_NAME_SHORT}&quot; &lt;{$EMAIL_ADDRESS}&gt;{/literal}">
```
The table of subscribers has `<tfooter>` tags. Should be using `<tfoot>` tags.

**Comment by abrookbanks** [comment]
Thanks for this!
