### ISSUE TITLE
Code Review: Customer Subscribers

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2849]
In admin `/sources/customers.subscribers.inc.php`:

With respect to #863, please realize that braces are allowed as characters in the "local-part' of an email address and the associated display name. (https://en.wikipedia.org/wiki/Email_address)

So, what issue does deleting braces and the inner content solve? Does the file delivery function choke on braces?

(I can see an edge case where the delivered file would be used as an input to a mailer parser where braced content would be expanded.)

**Comment by abrookbanks** [comment]
I can't see a need for it. Thanks.
