### ISSUE TITLE
Error on shopfront header - currency symbol

### ISSUE THREAD

**Issue by NaturalSigns** [cubecart/v6#285]
Ref picture below.
![currency symbol](https://cloud.githubusercontent.com/assets/10531097/6372256/b95636f8-bcfa-11e4-829f-d6f9a9fbb1b0.jpg)

**Comment by abrookbanks** [comment]
This is a remnant of an old issue which is now resolved on a new install or upgrade... 

Please login to the admin side of your store and edit the currency symbol in the "Currencies" section. It should be fine then. Sorry about this.
