### ISSUE TITLE
Phrase Review: Search Newsletter Send Log

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2851]
In admin, Mailing List, there is a "Search Email Log" phrase.

When/if there is to be a search filter on admin, Statistics, Email Log, the above phrase could become more misleading than it already is.

Suggest for the phrase `group=newsletter, string=log_search`, "Search Subscriber Newsletter Sent Log".

**Comment by abrookbanks** [comment]
Thank you.
