### ISSUE TITLE
Stripe extension

### ISSUE THREAD

**Issue by makeupfx** [cubecart/v6#2852]
The latest update to the Stripe extension seems to have a bug that names the transaction in Stripe to what
seems to be random numbers instead of the normal "Payment for XXXX-XXXX".

**Comment by abrookbanks** [comment]
Stripe Checkouts session object doesn't allow us to specify the description for the payment intent sadly.
https://stripe.com/docs/api/checkout/sessions/object 

I expect we could open a feature request at Stripe.

**Comment by abrookbanks** [comment]
I figured it out! Fixed in 3.0.4.

<img width="512" alt="Screenshot 2021-04-26 092444" src="https://user-images.githubusercontent.com/4520803/116052540-9d916980-a671-11eb-854a-a773e2075278.png">

**Comment by makeupfx** [comment]
Awesome!! Thank you so much!!
