### ISSUE TITLE
Use Standard OID If Custom OID is Empty

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2853]
If a store owner switches to using Incremental (custom) OID and choosing to **not** apply the custom OID to past orders, there will be instances where the order ID value will not show.

One such instance is the Transaction Logs.

Suggest near line 34 in the admin skin `orders.transactions.php`, this part:
```
{if $CONFIG.oid_mode=='i'}{$transaction.{$CONFIG.oid_col}}{else}{$transaction.order_id}{/if}
```
be replaced by:
```
{$transaction.{$CONFIG.oid_col}|default:$transaction.order_id}
```
In `orders.transactions.inc.php`, near line 32, change to:
```
$oid = $transactions[0][$oid_col] ? $transactions[0][$oid_col] : $transactions[0]['order_id'];
```
This solves the similarly missing data for the Smarty variable `TRANSACTION_LOGS_TITLE` and the breadcrumb.

An identical situation exists in the Orders list.

**Comment by abrookbanks** [comment]
Thanks Brian.
