### ISSUE TITLE
Order search broken when using incremental order numbers

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2854]
Ref : https://forums.cubecart.com/topic/56866-incremental-order-id-removing-all-old-order-ids/

when using incremental order numbers, partial text searching has been removed.

it should also search across original format AND incremental orders for shops switching and retaining old historical order numbers

**Comment by abrookbanks** [comment]
From my testing this is now resolved.

**Comment by havenswift-hosting** [comment]
I will be able to test this later today but thanks for looking at so quickly

**Comment by havenswift-hosting** [comment]
Have tested this myself and also on client store containing a mix of original and incremental order numbers and it works perfectly - thanks !

**Comment by abrookbanks** [comment]
Thanks for testing.
