### ISSUE TITLE
Payment gateways not using Incremental order numbers

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2857]
Following on from other recent issues when using incremental order numbers, several (probably all) payment gateways send the original order number instead of the incremental order number

Tested for :

PayPal Standard (1.1.0 latest) - aware this is no longer "Supported" but for many reasons already given, a very large number of users have to continue using this because of the way that PayPal Commerce works

SagePay (1.0.11 - latest)

Would imagine that most other gateways also dont pass the correct order number so would be worth fixing this for the most commonly used gateways

**Comment by abrookbanks** [comment]
Correct. They all need updating individually.

**Comment by Dirty-Butter** [comment]
This would be a VERY helpful improvement.

**Comment by abrookbanks** [comment]
Closing for now as this is ongoing. We will have to take one at a time.
