### ISSUE TITLE
Feature Suggestion - Manual Order to include PayPal "Pay Now" button - PayPal Commerce Extension

### ISSUE THREAD

**Issue by tonyrsutton** [cubecart/v6#2858]
Once you have the PayPal Commerce Extension plug-in installed, there should be a new 'Pay Now' button being added to the e-mail template when doing a Manual Order via Admin Console -> Orders -> Create Order

Once a manual order is created and saved, the email is sent out to the customer to alert them of a new order with pending status of the order and awaiting payment. Customer click the link in the email to take them to their Account page under Order History and from there, there is a Pay Now button where once clicked, will take them to PayPal page to make the payment. Once paid, the order status is changed to Processing (or whatever the Admin set up the order status is when payment is received)

I strongly believe this will be a great feature to add with the PayPal Commerce Extension plug-in to make things easier for Manual Order/Invoice.

Thank you,

**Comment by havenswift-hosting** [comment]
This is not payment gateway specific (and if it was, functionality should never be included for only one gateway !).  As noted this functionality is already included as part of a plugin

**Comment by tonyrsutton** [comment]
> This is not payment gateway specific (and if it was, functionality should never be included for only one gateway !). As noted this functionality is already included as part of a plugin

OK, how about making it as a hook, so it hooks into whatever payment gateway is installed.

The main aim is for a customer to be able to pay for the order from an invoice that I manually sent out by e-mail.
