### ISSUE TITLE
Newsletter to double opt in only unless allowed by server admin

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2859]
Mailing lists can be very poor quality, especially if bots have taken advantage.

They should only send to double opt in unless setting allows. 

This comes off the back of a hosted customer sending a newsletter to thousands of clearly bot addresses.

**Comment by Dirty-Butter** [comment]
I mail newsletters via MailChimp, so they catch the fake addresses quickly. I do not want double opt in. So I'm not clear on whether you intend to take the option to not double opt in out of the code??

**Comment by abrookbanks** [comment]
It won't affect mailing list export.

**Comment by Dirty-Butter** [comment]
I use a modified Semper Fi extension that coordinates automatically with Mailchimp. I have tried double opt-in in the past, and it caused us to miss a lot of customers because they don't follow through on them.
