### ISSUE TITLE
Foundation to Have JqueryUI

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2860]
Please consider adding jQuery-UI to the Foundation skin.

**Comment by abrookbanks** [comment]
This will add quite a bulk to it's already big overhead. Why do we need it?

**Comment by bhsmither** [comment]
My first thought is third-party extensions. But on second thought, instructions on how to make code changes to the skin might suffice -- to fetch only those jQueryUI modules the extension needs.

(Case in point: a Datepicker for the product options. The HTML 5 input type=date is not sufficient.)

**Comment by abrookbanks** [comment]
I'm going to close this on the grounds of overhead most won't need. Also a developer should know how to add JQuery UI. 

Adding a date field would be great to CubeCart. Maybe there is a standalone datepicker we can use instead of whole UI lib.

**Comment by bhsmither** [comment]
One can download a "custom" package containing any part(s) of the UI set. That's the approach I will use.

**Comment by abrookbanks** [comment]
Yes indeed. Maybe we need to integrate a date field and add it.
