### ISSUE TITLE
Sort By Price - SQL query fault and minor name improvement

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2861]
Admin area -> Settings -> Layout -> Product List Sorting 

The value with name "Retail Price" implies it will only sort on Retail Price, but instead it evaluates the price to pay, which can consider sale price. The name "Retail Price" should be revised to imply "Price to Pay" rather than Retail Price.

A new option should be added to the list explicitly for RRP.

However, the SQL query which is called when using a sort of "Retail Price" has an issue and needs a minor fix. The following IF statement is used:
`IF(`sale_price` > 0, `sale_price`, `price`) AS price_sort`

This is incomplete as often a sale price can be configured and is set higher than RRP (happens a lot). In this case the result of the query is... odd.

revise the query to the following, so that it respects the validity of sale item prices to resolve.
`SELECT *, IF(`sale_price` > 0 AND sale_price < price, `sale_price`, `price`) AS price_sort`

**Comment by abrookbanks** [comment]
Good find thanks!
