### ISSUE TITLE
Product Options Attributes Page, Group Selector to have Fallback Message

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2862]
Having created one or more Option Groups that are other than Select or Radio-button (and saving), then going to Option Attributes tab, the Groups selector is blank.

For the benefit of those who has not yet realized what is happening, suggest adding code that will show an advisory that says something like: "No groups have been created that are eligible for attributes."

Additionally, suggest that the "Add new attribute" be disabled until a group has been chosen.

**Comment by abrookbanks** [comment]
<img width="838" alt="Screenshot 2022-12-06 at 14 47 29" src="https://user-images.githubusercontent.com/4520803/205943890-c497dc91-ef46-4080-b728-a4a1ed409b0b.png">
Big improvement thanks.
