### ISSUE TITLE
Product's Options Checkbox's ID Attribute Duplicated

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2863]
In admin template products.index.php, please note lines 413 and 429:
```
413: <td align="center"><input type="hidden" id="matrix_include_{$option.assign_id}" ...
429: <td align="center"><input type="hidden" id="matrix_include_{$option.set_member_id}" ...
```
where `{$option.assign_id}` and `{$option.set_member_id}` could be the same value.

This will cause image checkbox management via javascript to misbehave.

Perhaps `"matrix_include_member_{$option.set_member_id}"`? (I have not tried this.)

**Comment by abrookbanks** [comment]
Thanks!
