### ISSUE TITLE
Duplicated Code

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2865]
Trivial:

Regarding #654, was there a specific reason to separate out a test for option group type 0 (select) versus option group type 4 (radio)?

Considering the code is exactly the same, I fail to see the reason.

**Comment by abrookbanks** [comment]
I don't really understand what you are saying? What is the same about them?

**Comment by bhsmither** [comment]
In admin template products.options.php, lines 160-173:
```
                  {foreach from=$GROUPS item=group}
                  {if $group.type == 0}
                  <optgroup label="{$group.name}">
                     {foreach from=$group.options key=value_id item=value_name}
                     <option value="g{$group.id}-{$value_id}">{$value_name}</option>
                     {/foreach}
                  </optgroup>
                  {else if $group.type == 4}
                  <optgroup label="{$group.name}">
                     {foreach from=$group.options key=value_id item=value_name}
                     <option value="g{$group.id}-{$value_id}">{$value_name}</option>
                     {/foreach}
                  </optgroup>
                  {else}
```
Note that each `{if}` block has identical code.

**Comment by abrookbanks** [comment]
Thanks!! I was looking for the wrong thing. 🤪

**Comment by bhsmither** [comment]
Those eight lines deleted will cause problems. There is now a `{/if}` with no `{if}`.

Suggest replacing what was:
```
                  {if $group.type == 0}
```
with (5 is checkboxes and 7 is hidden - for when these get implemented):
```
                  {if $group.type == 0 or $group.type == 4 or $group.type == 5 or $group.type == 7}
```
