### ISSUE TITLE
DropZone.js Filesize?

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2871]
Regarding #2823, please confirm that the distributed version in CC643 really must contain 270K of WebPack (and whatever else is in there that does not look like DropZone).

**Comment by bhsmither** [comment]
I see the filesize jump when scanning through the various tags, but I could not find any explanation as to what is going on, other than _maybe_ the developer wants to structure that repository to conform to a package manager, or _maybe_ it is a consequence of DropZone actually being written in this thing called ES5,ES6 (and thus needs a translator/compiler).

**Comment by abrookbanks** [comment]
I can't see a lighter package available.
