### ISSUE TITLE
Standard OID If Custom OID is Empty - Continued

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2878]
Regarding #2853 which solved `orders.transactions.php`, please apply the same solution to: `orders.index.php` (near line 34), `orders.print.php` (near line 203), `dashboard.index.php` (near lines 54 and 143), `reports.index.php` (near line 34), and Foundation template `content.receipt.php` (near line 12).

Also consider adding `title="{$LANG.common.edit}"` to the anchor tags in the admin templates.

**Comment by bhsmither** [comment]
Something not yet obvious is happening here.

_Eventually_, the 'custom_oid' field in CubeCart_order_summary will get filled for those rows that were not forced to be updated. (See `order.class.php` line 901)

So I see this whole thing as moot because _eventually_, that is, once the Store Settings has been Saved (and `$order->setOrderFormat()` has been executed, 'custom_oid' will no longer ever be empty.

**Comment by abrookbanks** [comment]
Thanks
