### ISSUE TITLE
'More \/' button not always appearing

### ISSUE THREAD

**Issue by kealanm1** [cubecart/v6#288]
Hi all,

I seem to be missing the more button on some category pages.

See https://www.gooutdoorireland.com/beta6/torches.html
vs
https://www.gooutdoorireland.com/store/torches.html

data in the DB looks good

Just tried the beta 6 release have tested on v3 and v4 issue did not appear, didnt get a chance to test on v5. 

Login details for FTP and store should be on file

**Comment by abrookbanks** [comment]
I can't see a "More V" button on either URL. I'm not sure I follow.. sorry! Could you do a screenshot?

You can literally drag pictures into the text field on here and it will upload them.

**Comment by kealanm1** [comment]
Sry Al long day didnt explain that well, I cant see the full list of items the more button has vanished! see attached 


![more button](https://cloud.githubusercontent.com/assets/10632959/6375037/73c7f4e8-bd0c-11e4-90f4-825d2e773d7f.png)

**Comment by abrookbanks** [comment]
I'm with you.. the More button will hide once all items are shown. There shouldn't be any more to show.

**Comment by abrookbanks** [comment]
Sorry I see the issue now! Could you send a sales ticket with FTP access so I can take a look at this first hand?

**Comment by kealanm1** [comment]
Perfect Al will send over now

**Comment by abrookbanks** [comment]
:thumbsup: I'll take a look and get to the bottom of it...

**Comment by kealanm1** [comment]
just to throw a spanner in the works, its not like that on all pages heres an example of one where its fine 

https://www.gooutdoorireland.com/beta6/camouflage.html

**Comment by abrookbanks** [comment]
I've actually managed to reproduce it locally... I think the issue is from page 2 onwards..

**Comment by abrookbanks** [comment]
Working now on original URL in report.
