### ISSUE TITLE
Deleting Pending Orders

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2880]
Given the case where the store owner has decided to set inventory to decrement when an order goes to Pending.

When the admin decides to delete a Pending order, `Order->deleteOrder()` does not test for this case. Thus, inventory could be lost.

Suggest using `$this->_manageStock(self::ORDER_CANCELLED, $order_id)` to reclaim the inventory.

(I haven't tested this.)

**Comment by bhsmither** [comment]
The Multi-Order with Multi-Status (and Multi-Action) sends each order through `Order->orderStatus()`, so maybe not to worry about this method of deleting orders.

**Comment by abrookbanks** [comment]
This works from my testing. CubeCart needs a better stock management system. 

Supplier, sold, binned, lost etc..
