### ISSUE TITLE
PayPal commerce  does not populate Gateway correctly

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2882]
Seems to be a bug, noted on a couple of sites and only specific to PayPal commerce.

CubeCart_order_summary.gateway is emptied, so there is no Gateway information at the order summary via the admin area.

The value is set when starting the checkout process, and at some point after is removed, presumably via a return call from PayPal.

**Comment by tonyrsutton** [comment]
I can confirm this bug.

**Comment by abrookbanks** [comment]
This will require paypal_commerce-1.4.4 (to follow) ...

**Comment by abrookbanks** [comment]
1.4.4 released https://www.cubecart.com/extensions/plugins/paypal-commerce
