### ISSUE TITLE
Un-Commenting Smarty Loop Tags

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2885]
In documents.email.inc.php, near line 509, four of Smarty's looping tags are wrapped in HTML comment tags. (The reason is known.)

However, near line 367, those HTML comment tags are removed -- *all* HTML comment tags.

There is no (known) stated advice on not to be coding templates with HTML comments, thus their appearance in customized templates can be expected.

Therefore, suggest formalizing what exactly is to be removed.

Something like (needs to be tested):
```
$_POST['content']['content_html'] = preg_replace_callback(
// wanting to strip '<!--' or '-->' from only certain Smarty keywords
'#<!--{(/?)(section|foreach|foreachelse|for)(.*?)}-->#',
function ($matches) {
return '{'.$matches[1].$matches[2].$matches[3].'}';
},
$GLOBALS['RAW']['POST']['content']['content_html']);
```

**Comment by abrookbanks** [comment]
Fixed with ac73e42e81abc08aebe46406bce5d535d5e6afe0
