### ISSUE TITLE
Trivial : Bank Transfer plugin spelling mistake

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2887]
The plugin description has a spelling mistake

Show bank account details for internet beanking transfer.

**Comment by abrookbanks** [comment]
Thanks Ian. I hope you are well.

**Comment by havenswift-hosting** [comment]
Very well just very busy at the moment !

**Comment by abrookbanks** [comment]
I've got a satanic three year old who can come and stay and help out if you like? 😂
