### ISSUE TITLE
Code Clarity

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2888]
In /classes/cubecart.class.php, near line 833, there is:
```
if ($GLOBALS['session']->has($term, $namespace = 'search')) {
```
This comment:
https://www.php.net/manual/en/functions.arguments.php#71198
suggests that an assignment as the function call argument is not illegal, and could be useful if the function's argument is accepted by reference.

But I do not see that in this case. `$namespace` is not used anywhere in this method, and there is no hook that could otherwise use it.

PHP8 introduced 'named arguments', but the line shown here is syntactically incorrect for that feature.

**Comment by abrookbanks** [comment]
Thanks Brian.
