### ISSUE TITLE
PayPal 422 Response to Log Reason

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2896]
According to:
`https://developer.paypal.com/docs/api/reference/api-responses/`
there could be a response payload containing a description of the error.

If so, request that it be contained in the Request Log.

**Comment by bhsmither** [comment]
I am looking at this in paypal.class.php:
(Disclaimer: I have _nada_ knowledge about PayPal.)
```
    private function _errorDetected($result)
    {
        
        if($result->server_response_code > 0 && !in_array($result->server_response_code, array(200, 201, 202, 203, 204, 205, 206, 207, 208, 226))) {
            $GLOBALS['gui']->setError('An API error occured. Please try later.');
            return true;
        }
```
Assume that the HTTP Response code is 422. The above test is true, an unhelpful message gets displayed somewhere -- maybe, and nothing else gets done. It is now questionable if the following test is ever executed.
```
        $result = json_decode($result, true);
        if (isset($result['name']) && $result['name'] == 'UNPROCESSABLE_ENTITY') {
            foreach ($result['details'] as $value) {
                $GLOBALS['gui']->setError($value['description']);
            }
            return true;
        }
        return false;
    }
```
_If executed_, who gets to see the description? The customer? And when? (See disclaimer.)

**Comment by tonyrsutton** [comment]
Another linked thread - https://forums.cubecart.com/topic/57753-paypal-ecommerce-in-error-log/

**Comment by abrookbanks** [comment]
This is incredibly complex. 6.4.8 better logs 422 errors in the request log. Lets look from there on.. 

Relevant: https://github.com/cubecart/v6/commit/37daf45925065144074d01388c8c28819197fb24
