### ISSUE TITLE
Validate product options on server side

### ISSUE THREAD

**Issue by romanklabal** [cubecart/v6#2897]
When you have a product with multiple required options, you can simply right click the `<select>` in the browser inspector on a product page, remove it from DOM, submit the add to basket form, and CubeCart will add the product without the required option to the basket.

Just tested it on the CC6 demo website.

Looking at the code, the `Cart::add()` method should probably have an additional check to see if all the required options (maybe just their count would do?) are present in the productOptions POST array.

**Comment by romanklabal** [comment]
Additionally, there does not seem to be any check implemented for the productOptions option value. Meaning that you can edit the `<option>` value to a random number using inspector, submit the form and the product will be added (with a unique hash, probably calculated based on the made up group/value pair) to the basket with the product option omitted.

I have resorted to pulling the options via `Catalogue::getProductOptions()` in the `Cart::add()` method and verifying if all the options are present and their value exists.

**Comment by abrookbanks** [comment]
Closed as feature to do.
