### ISSUE TITLE
Eliminating a Bottleneck

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2898]
For reference: https://forums.cubecart.com/topic/57024-500-internal-error-on-update-file-list/

In the Filemanager class, there three instances of PHP's function `md5_file()`. One instance, in the upload() method, is probably of no concern. The other two instances, however, should be dealt with.

This came about with managing a super-large file that is the `digital_path` download of a product. The argument being made is that (especially with the new feature to stream a download) the size of product's files could legitimately be larger than 4GiB, possibly being as large as 7GiB*. (Granted, this is an outlier.)

It's been shown that the bottleneck happens when `md5_file()` is reading the file from storage. A number of factors are in play, but getting the super-large file read from the drive will take longer than what the admin or customer is expecting. (An SSD would be quicker, a RAM drive nearly instantaneous.)

CubeCart uses `md5_file()` to calculate the `md5hash` that will (1)populate the `CubeCart_filemanager` table in `buildDatabase()`, and (2)gather file info in `getFileInfo()` when delivering a file from a local product's `digital_path`.

For (1), the database table needs to be able to hold a filesize value larger than 4GiB, and there needs to be a different means of calculating the md5 hash.

For (2), I find no code that actually uses the md5 hash of the file when delivering that file. (But a hook could still want to use it.) Suggest not calculating the md5 hash of a super-large local file specified by the product's `digital_path`.

* Note: from information generally available, a 7GiB file can be read from a spinning platter drive, if everything is optimized, in just under 60 seconds. This is the default timeout that the web server waits for a response from PHP.

**Comment by abrookbanks** [comment]
I'm trying to decide if a large INT or VARCHAR is the best option here. I think there are cases where 2.14... GB isn't enough. 

Researching...

**Comment by abrookbanks** [comment]
I think it needs to be BIGINT.

**Comment by abrookbanks** [comment]
So this solution allows for md5_file on upload but not on rebuild for files over 10Mb. I believe the md5 check was added for two reasons (neither actually used).

1. Check that the file delivered is as expected.
2. Check for duplicates of the same file. 

Neither scenario is checked for now.
