### ISSUE TITLE
Clarify GC Conversion Message

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2901]
In products.coupons.inc.php, lines 69-70, the code is looking for the order specified to make a coupon into a GC, This code implements the 'Incremental' OID scheme.

However, the advisory phrase "To use a promotional code as a gift card ... must be a real order number ..." does not mention that the Order Number **must** be of the format that conforms to the current administrative setting for the OID scheme.

Suggest adding, after the text entry field for the Order Number, an appropriate example of the format to use:
`"ex: Incremental -> ABC001"` (derived from admin-supplied pattern)
`"ex: Traditional -> 201215-060708-1234`

**Comment by abrookbanks** [comment]
It would probably make more sense to detect. If the format is traditional we know where to look. If not we try new.
