### ISSUE TITLE
Detritus in URI

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2905]
Minor:

The ,htaccess rewrite will deliver `/index.php?seo_path=`, with which the function `currentPage()`, in a certain case, will not remove.

In `functions.inc.php`, line 264 suggests that a non-empty `seo_path` value will get SEO'd.

But nothing is done with an empty `seo_path`. Thus, `?seo_path=&...` is found in various locations.

**Comment by abrookbanks** [comment]
Sorry but I don't follow this one. What is the problem and how can it be reproduced?

**Comment by abrookbanks** [comment]
I *think* I follow what you are saying. Please let me know if I have misunderstood.
