### ISSUE TITLE
CubeCart seems to have broken itself

### ISSUE THREAD

**Issue by JDMtom** [cubecart/v6#2908]
Im not sure when exactly this started happening but within the last 24 hours. 

CubeCart store hosted on PayMonthly Servers. 

Error logs show this : 
![image](https://user-images.githubusercontent.com/90796241/133492983-ce1426cd-bcf5-4694-8239-3ee411e5968b.png)

And the site wont load any content. 

Any Ideas?

**Comment by JDMtom** [comment]
Also - I am no longer able to log in to the control panel of the store. Gives incorrect password error. When trying to reset password, I get incorrect email/username.

**Comment by bhsmither** [comment]
I have an idea, but let's take this to the forums.

**Comment by JDMtom** [comment]
> I have an idea, but let's take this to the forums.

Yer just realised I was clicking on the wrong forum so it was sending me here, Will recreate the post now however I think i have found the issue. Will Put more detail in forumn post

**Comment by abrookbanks** [comment]
Sorry you are having problems but this is a technical support issue. We have [support available](https://www.cubecart.com/technical-support) if you would like our staff to resolve this. I'm sure we can get you back on your feet quickly.
