### ISSUE TITLE
data-equalizer not working

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#291]
https://forums.cubecart.com/topic/49320-foundation-format-product-listing-grid-size/?p=206181

![screen shot 2015-02-26 at 09 15 08](https://cloud.githubusercontent.com/assets/4520803/6389036/011f888e-bd98-11e4-8725-7e95d07a11b8.png)

**Comment by abrookbanks** [comment]
# After

![screen shot 2015-02-26 at 09 16 05](https://cloud.githubusercontent.com/assets/4520803/6389049/1eb671fa-bd98-11e4-9b41-cf2b45d29bf0.png)

**Comment by Dirty-Butter** [comment]
Category pages still have this issue for me. I've installed the #291 commit. Maybe it depends on a previous fix to another issue????? Is there a way to install ALL the fixes since 6.0.0b6 was released?

**Comment by abrookbanks** [comment]
It's a bit flakey... so we need to call the equalizer 10ms after the render.. this stops it trying to do it before the action is complete...

**Comment by abrookbanks** [comment]
This slight change to the cubecart.js file fixes it for me.

**Comment by Dirty-Butter** [comment]
Still not working for me. See bottom of listings:
https://dirtybutter.com/plushcatalog/food-related-advertising.html

**Comment by abrookbanks** [comment]
Hmmmm.. can you change this line in the cubecart.js file from:

```setTimeout("equalize()",duration+10);```

To:
```setTimeout("equalize()",duration+50);```

**Comment by Dirty-Butter** [comment]
No. I changed it to 100 and that didn't fix it, either.

**Comment by abrookbanks** [comment]
Ok thanks I've reopened this and I'll have a rethink.

**Comment by abrookbanks** [comment]
Ok I finally found the correct way to do this. jQuery "when.. done". This should make sure the equalize ONLY happens after the page has completely rendered so we are not guessing with when to do it.

**Comment by Dirty-Butter** [comment]
I'm sorry to report that it's still not working for me on Categories.

**Comment by abrookbanks** [comment]
Maybe I need to take a look at your store. Hmmmmmmmmmmmmmmmmmmmm.

**Comment by Dirty-Butter** [comment]
https://dirtybutter.com/plushcatalog/food-related-advertising.html
All I've changed is cosmetic color, text.

**Comment by abrookbanks** [comment]
Is it just this one thats wrong? Right now the equalization is on the middle part.
![screen shot 2015-02-27 at 14 27 50](https://cloud.githubusercontent.com/assets/4520803/6414105/fdc7f68a-be8c-11e4-9f57-232d3b70871c.png)

**Comment by abrookbanks** [comment]
I've reproduced it here too... its actually a different cause... I'm looking into it... 

![screen shot 2015-02-27 at 14 37 52](https://cloud.githubusercontent.com/assets/4520803/6414310/4412d32a-be8e-11e4-9496-c645237b9920.png)

**Comment by abrookbanks** [comment]
I'm confident this is fixed now. Some HTML needed updating. Will reopen if issue persists.

**Comment by Dirty-Butter** [comment]
Thanks!! And Congrats!

**Comment by abrookbanks** [comment]
Hooray! Thanks for putting up with me Rosemary. :)

**Comment by Dirty-Butter** [comment]
Quite the contrary!! Thanks for putting up with ME!! My Senior Moments are turning into Senior Hours and Days of late. I apologize for so many unnecessary GitHub entries of late. At least every once in a while, like this one, I do spot a bug.

 

Rosemary

**Comment by abrookbanks** [comment]
Your input is always valid and much appreciated. Thank you.
