### ISSUE TITLE
Count() in Coupons Re: Manufacturers

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2911]
In `products.coupons.inc.php`, near line 55, there is the serialization of `$_POST['coupon']['manufacturer']`, which is an array. Unless there is no selection. Thus, the serialization results in `N;`.

Then, in `Cart->discountAdd()`, near line 579, a test is made for empty-ness. The value is not empty, and it will be unserialized as _null_. Thus, the `count()` function that follows will have PHP throw a Warning about the argument being uncountable.

**Comment by abrookbanks** [comment]
Thanks.
