### ISSUE TITLE
Quantity discounts available shows even when none are set

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2913]
In element.product.call_to_action.php

{if isset($PRODUCT.discounts)}

should be changed to 

{if !empty($PRODUCT.discounts)}

**Comment by bhsmither** [comment]
I concur this is better logic control as it deals with the mistake of code setting `$PRODUCT.discounts` but with nothing to set it with.

So, we may also want to find out why the core code (or plugin code) is setting this with no data.

If doing this, also change the template code in `content.product.php` near line 104.

**Comment by abrookbanks** [comment]
Thanks!
