### ISSUE TITLE
Feature Suggestion: Start date for Promotional Code

### ISSUE THREAD

**Issue by tonyrsutton** [cubecart/v6#2915]
We currently have an End Date for the Promotional Code.

But it would be good if we have the Start date as well. This way, we can distribute the promo code with a specific start date so they can't use it until the specific date.

It's about control at the end.

Would be awesome to have this added - thank you.

**Comment by abrookbanks** [comment]
Got there eventually!!

**Comment by tonyrsutton** [comment]
Yay! Thank you. :)
