### ISSUE TITLE
Dimensional Unit Default and Assertion

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2916]
Feature Request:

I disagree with the solution implemented in #2221.

True, the probability that the inventory could be a mix of Imperial and Metric sizes would be low, but not impossible.

I have a task to add other units of length that are at different scales of convenience (e.g., mm, yd), and, perchance, that have little to no culturally paired association with weight (e.g., au, nmi).

**Comment by abrookbanks** [comment]
More complexities come into play when the product dimensions are eventually passed to a shipping provider. One unit works for that but not a mixture. Holding for now but totally understand all the arguments here.
