### ISSUE TITLE
BUG: Database Maintenance - Missing options after doing a maintenance 

### ISSUE THREAD

**Issue by tonyrsutton** [cubecart/v6#2919]
CubeCart v6.5.0-b2
PHP v7.4.21

Advanced -> Maintenance -> Database tab

Select all checkboxes, pick one of the Action (e.g. Repair) and click the Submit button.

Once it was run, scroll down to bottom, you only see a 'Submit' button with no other options. I had to refresh the page to get the options back. It's the same with all actions (Optimize, Repair, etc)

Bug?

**Comment by tonyrsutton** [comment]
This also exists on CubeCart v6.4.2

**Comment by bhsmither** [comment]
After the operation completes (e.g., REPAIR), the list shown is the result report of having the operation performed on the table(s).

That is to say, the first screen is the "Determine what you want to do against which tables you want to work on., while the second screen is the results of that work.

Are you suggesting the page show both the 'choose the work' listing every time, **as well as** the results listing (as appropriate)?

**Comment by tonyrsutton** [comment]
Yes, I think it would make sense. 

Think about the end user's point of view - what does the 'Submit' button does after the action? What am I submitting?

**Comment by bhsmither** [comment]
"_What am I submitting?_"

Well, there is that.
