### ISSUE TITLE
Corrupted Variable

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2922]
In `products.import.inc.php`, line 91 creates `$value`.
```
foreach ($data as $offset => $value) {
```
Later, line 110 also creates `$value`.
```
foreach ($image_splits as $value) {
```
Then, however, lines 145 and 148 is expecting to use `$value` created at line 91.

But `$value` now has contents acquired by the last iteration of the loop at line 110.

It is known that variables created as operatives in a foreach loop are not private. Example:
```
<?php  
$colors = array("red", "green", "blue", "yellow"); 
$value = "Test";
foreach ($colors as $value) {  echo "$value <br>"; }
echo "<br>$value <br>";
?>
```
Suggest using distinctive variable names for the value operative in foreach loops. (Although not an issue, see also line 63.)

**Comment by bhsmither** [comment]
Could be not an issue at all, because line 110 is within a block of code that deals with the 'image' column, which does not exist in CubeCart_inventory. Thus, the code at lines 145 and 148 is moot when the map_offset is referencing the 'image' column.

**Comment by abrookbanks** [comment]
Fixed for good practise whether bug or not.
