### ISSUE TITLE
Untrimmed Value

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2923]
In `products.import.inc.php`, line 112:
```
$image_path = preg_replace('/^[.\/]/', '', dirname($value));
```
may not get what is needed.

Example: `./first/second/image.jpg`

`dirname()` returns: `./first/second`

`preg_replace()` will find the period (the one instance of the collection), but not the slash (requires a second instance of the collection).

Worse, `dirname()` does not trim, so when splitting $value on commas, yet there is a space after the comma, the `preg_replace()` will not find anything because the space is at the start of the string.

Suggest trimming `$value` on line 112 to include periods, then deleting the leading slash. Then testing for `../` anywhere in `$value` (directory traversal).

**Comment by abrookbanks** [comment]
Thanks again Brian!
