### ISSUE TITLE
Potential Issue

### ISSUE THREAD

**Issue by ChrisNColeman** [cubecart/v6#2924]
With CubeCart  6.4.4 and PHP 7.4.

 [Deprecated] /home/jennifer/public_html/admin_URxvyJ/sources/dashboard.index.inc.php:265 - implode() [function.implode.php]: Passing glue string after array is deprecated. Swap the parameters

Chris.

**Comment by bhsmither** [comment]
This was fixed in CC640:
https://github.com/cubecart/v6/commit/b366d549e68861b9b70a2fcb0937d8d704f0e2ed#diff-39595ce96d24cdfee6acfb48d660315f2bf72f648689d5046cbceed4bc95f153
The admin folder being used by CubeCart might be from an earlier version.

**Comment by ChrisNColeman** [comment]
Yes looks like the upgrade did not complete - i'll do it again ..

C.
