### ISSUE TITLE
Your Logo?

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2928]
It may be my browser, but I cannot find your [CC] logo anywhere on your site (except as a favicon).

**Comment by abrookbanks** [comment]
Our site? CubeCart.com? 

I'm not sure I follow. 

![Screenshot 2021-11-02 162440](https://user-images.githubusercontent.com/4520803/139905369-2a713aa7-e561-4638-8992-03d4191edabb.jpg)

**Comment by bhsmither** [comment]
By "[CC]" I mean the light blue "cube" having the white letters CC on the front face.

True, it is part of the "[CC] cubecart" branding, but seen only in the application - not anywhere on your corporate site.

**Comment by abrookbanks** [comment]
Bit of a mixed message going on there. 😂

We could do with a bit of branding attention I think.
