### ISSUE TITLE
review snippet error

### ISSUE THREAD

**Issue by rds34** [cubecart/v6#2929]
Hi
Getting review snippet errors via google search console

**Comment by tonyrsutton** [comment]
Thanks for your post, but that's not enough details, sorry. And this is the wrong place to discuss the issue. Please use https://forums.cubecart.com with more details (versions, screenshot, etc etc) and if one of us decides it's a bug, it will be reported on here. Thanks.

**Comment by rds34** [comment]
Hi
Al brooks ask me to post it & sent the link.

Im using the latest version of cubecart.

Images attached 
![Doc1](https://user-images.githubusercontent.com/27129577/140609276-ba54acfd-32e6-4558-8108-3d61a2c5bb7c.jpg)
![Doc2](https://user-images.githubusercontent.com/27129577/140609290-b72c5964-c6da-42f2-a560-bce6ec847e48.jpg)
![Doc3](https://user-images.githubusercontent.com/27129577/140609293-8159bf5c-aca4-4f1e-a4ee-7b8a91b9aefc.jpg)

**Comment by tonyrsutton** [comment]
>>Al brooks ask me to post it & sent the link.

Yes, but you didn't include enough details, which I why I asked. Sorry.

>> Im using the latest version of cubecart.

Is that CubeCart 6.5.0 Beta? Or 6.4.4 ?

What skin are you using?

Thank you.

**Comment by rds34** [comment]
6.4.4
Cinda

**Comment by abrookbanks** [comment]
```
{literal}
      <script type="application/ld+json">
    {
      "@context": "https://schema.org/",
      "@type": "Product",
      "brand": {
        "@type": "Brand",
        "name": "{/literal}{$MANUFACTURER|strip_tags|trim}{literal}"
      },
      "description": "{/literal}{$PRODUCT.description|strip_tags|trim|regex_replace:"/[\r\n]/" : " "}{literal}",
      "sku": "{/literal}{$PRODUCT.product_code}{literal}",
      "mpn": "{/literal}{$PRODUCT.mpn}{literal}",
      "image": "{/literal}{$PRODUCT.source}{literal}",
      "name": "{/literal}{$PRODUCT.name}{literal}",
      
      "review": [
         {/literal}{foreach from=$REVIEWS item=review}{literal}
         {
        "@type": "Review",
        "reviewRating": {
          "@type": "Rating",
          "ratingValue": "5"
        },
        "author": {
          "@type": "Person",
          "name": "{/literal}{$review.name}{literal}"
        },
        "datePublished": "{/literal}{$review.date_schema}{literal}",
        "reviewBody": "{/literal}{$review.review|regex_replace:"/[\r\n]/" : " "}{literal}"
      }{/literal}{if !$review@last},{/if}{/foreach}{literal}
      ],
      "aggregateRating": {
        "@type": "AggregateRating",
        "ratingValue": "{/literal}{$REVIEW_AVERAGE}{literal}",
        "bestRating": "5",
        "ratingCount": "{/literal}{$REVIEWS|@count}{literal}"
      },
      "offers": {
        "@type": "Offer",
        "url": "{/literal}{$VAL_SELF}{literal}",
        "priceCurrency": "{/literal}{$CONFIG.default_currency}{literal}",
        "price": "{/literal}{$PRODUCT.price_to_pay|regex_replace:'/[^0-9.]+/':''}{literal}",
        "priceValidUntil": "{/literal}{$smarty.now+15780000|date_format:"%Y-%m-%d"}{literal}",
        "itemCondition": "{/literal}{if $PRODUCT.condition=='New'}https://schema.org/NewCondition{else}https://schema.org/UsedCondition{/if}{literal}",
        "availability": "https://schema.org/InStock",
        "seller": {
          "@type": "Organization",
          "name": "{/literal}{$CONFIG.store_name}{literal}"
        }
      }
    }
    </script>
    {/literal}
```

**Comment by rds34** [comment]
Hi Al That's exactly what I thought it was. Lol Thank you for your help had this issue for a while now.Regards RichardOn 7 Dec 2021 12:14, Al Brookbanks ***@***.***> wrote:
{literal}
      <script type="application/ld+json">
    {
      ***@***.***": "https://schema.org/",
      ***@***.***": "Product",
      "brand": {
        ***@***.***": "Brand",
        "name": "{/literal}{$MANUFACTURER|strip_tags|trim}{literal}"
      },
      "description": "{/literal}{$PRODUCT.description|strip_tags|trim|regex_replace:"/[\r\n]/" : " "}{literal}",
      "sku": "{/literal}{$PRODUCT.product_code}{literal}",
      "mpn": "{/literal}{$PRODUCT.mpn}{literal}",
      "image": "{/literal}{$PRODUCT.source}{literal}",
      "name": "{/literal}{$PRODUCT.name}{literal}",
      
      "review": [
         {/literal}{foreach from=$REVIEWS item=review}{literal}
         {
        ***@***.***": "Review",
        "reviewRating": {
          ***@***.***": "Rating",
          "ratingValue": "5"
        },
        "author": {
          ***@***.***": "Person",
          "name": "{/literal}{$review.name}{literal}"
        },
        "datePublished": "{/literal}{$review.date_schema}{literal}",
        "reviewBody": "{/literal}{$review.review|regex_replace:"/[\r\n]/" : " "}{literal}"
      }{/literal}{if ***@***.***},{/if}{/foreach}{literal}
      ],
      "aggregateRating": {
        ***@***.***": "AggregateRating",
        "ratingValue": "{/literal}{$REVIEW_AVERAGE}{literal}",
        "bestRating": "5",
        "ratingCount": ***@***.***}{literal}"
      },
      "offers": {
        ***@***.***": "Offer",
        "url": "{/literal}{$VAL_SELF}{literal}",
        "priceCurrency": "{/literal}{$CONFIG.default_currency}{literal}",
        "price": "{/literal}{$PRODUCT.price_to_pay|regex_replace:'/[^0-9.]+/':''}{literal}",
        "priceValidUntil": "{/literal}{$smarty.now+15780000|date_format:"%Y-%m-%d"}{literal}",
        "itemCondition": "{/literal}{if $PRODUCT.condition=='New'}https://schema.org/NewCondition{else}https://schema.org/UsedCondition{/if}{literal}",
        "availability": "https://schema.org/InStock",
        "seller": {
          ***@***.***": "Organization",
          "name": "{/literal}{$CONFIG.store_name}{literal}"
        }
      }
    }
    </script>
    {/literal}

**Comment by abrookbanks** [comment]
Better code:

```
<script type="application/ld+json">
    {
      "@context": "https://schema.org/",
      "@type": "Product",
      {/literal}{if !empty($MANUFACTURER)}{literal}
      "brand": {
        "@type": "Brand",
        "name": "{/literal}{$MANUFACTURER|strip_tags|trim}{literal}"
      },{/literal}{/if}{literal}
      "description": "{/literal}{textformat wrap_char=" "}{$PRODUCT.description|strip_tags|trim|replace:'"':'\"'}{/textformat}{literal}",
      "sku": "{/literal}{$PRODUCT.product_code}{literal}",
      "mpn": "{/literal}{$PRODUCT.mpn}{literal}",
      "image": "{/literal}{$PRODUCT.source}{literal}",
      "name": "{/literal}{$PRODUCT.name}{literal}",
      {/literal}{if !empty($REVIEWS)}{literal}
      "review": [
         {/literal}{foreach from=$REVIEWS item=review}{literal}
         {
        "@type": "Review",
        "reviewRating": {
          "@type": "Rating",
          "ratingValue": "5"
        },
        "author": {
          "@type": "Person",
          "name": "{/literal}{$review.name}{literal}"
        },
        "datePublished": "{/literal}{$review.date_schema}{literal}",
        "reviewBody": "{/literal}{textformat wrap_char=" "}{$review.review|strip_tags|trim|replace:'"':'\"'}{/textformat}{literal}"
      }{/literal}{if !$review@last},{/if}{/foreach}{literal}
      ],
      "aggregateRating": {
        "@type": "AggregateRating",
        "ratingValue": "{/literal}{$REVIEW_AVERAGE}{literal}",
        "bestRating": "5",
        "ratingCount": "{/literal}{$REVIEWS|@count}{literal}"
      },
      {/literal}{/if}{literal}
      "offers": {
        "@type": "Offer",
        "url": "{/literal}{$VAL_SELF}{literal}",
        "priceCurrency": "{/literal}{$CONFIG.default_currency}{literal}",
        "price": "{/literal}{$PRODUCT.price_to_pay|regex_replace:'/[^0-9.]+/':''}{literal}",
        "priceValidUntil": "{/literal}{$smarty.now+15780000|date_format:"%Y-%m-%d"}{literal}",
        "itemCondition": "{/literal}{if $PRODUCT.condition=='New'}https://schema.org/NewCondition{else}https://schema.org/UsedCondition{/if}{literal}",
        "availability": "https://schema.org/InStock",
        "seller": {
          "@type": "Organization",
          "name": "{/literal}{$CONFIG.store_name}{literal}"
        }
      }
    }
    </script>
```
