### ISSUE TITLE
Trivial Comments

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#293]
Comments:

Not to be a nimrod or anything, but I didn't expect the getInstance() method to end up in alphabetical order. That's the one method (with all static methods) I would expect to see stay above the `//==[Public]==` line.

I also have some headaches when a function/method finishes with an outlier response. An outlier response of a function (*my term*) would be not relevant data, but an action/event outside it's sphere of responsibility.

Compare the functions httpredir() and SEO::__construct(). In keeping within the sphere of responsibility, __construct should not be the function that exits PHP. No part of SEO (perhaps not any class) should be responsible for exiting PHP.

httpredir() seems fairly competent to do that.

**Comment by abrookbanks** [comment]
Thanks Brian. I've made some changed but this is probably ongoing a bit. Closed for now. 

BTW you are a nimrod! Just joking! Hehe. Really appreciate your feedback. It felt wrong moving the static instances when I did.. What was I thinking... I want CC6 to be polished.
