### ISSUE TITLE
Gallery List in Admin May Be Incomplete

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2933]
In `Filemanager->assignProductImages()`, we see that there is a good-faith effort to make one of the newly added images to be the `main_img` - if there wasn't one chosen to start with.
```
// If no default image was chosen pick last one and let staff member know
```
Note: `(int)$img_add[0]` seems to be selecting the **first** of the new images chosen.

However, playing Devil's Advocate, let's say that something has set the `main_img` column in CubeCart_image_index to "0" for all records with a given `product_id`.

Granted, the admin should see that, in this anomalous situation, CubeCart is showing a transparent pixel as the Main Image, but...

The `product.index.php` template has this code:
```
{foreach $GALLERY_JSON|json_decode:true as $gallery_image}
{if $gallery_image@index > 0}
```
which means that only the second and after array elements (images) will be shown - where iterating over `$GALLERY_JSON` may then have any one of the otherwise assigned images not showing -- because there is no Main Image to be the actual first element in the array to skip over.

Suggest testing:
```
{if empty($gallery_image.main_img)}{* The string "0" is considered empty, so not the main_img. *}
```
This will then show all images that are not the `main_image` in the 'Other included images" list. The admin will then have a blatant and direct view that "Oops! One of these images should actually be the Main Image."

**Comment by abrookbanks** [comment]
If no main image is assigned it will just take the first one and show the remainder in the gallery. On these grounds that merchant will see the current setup and be able to edit the master image if they want to. I don't think anything needs changing. Screenshot attached shows the behaviour if main_img is set to 0 for all assigned images. 

The merchant should only think it's not right and edit accordingly. 
<img width="770" alt="Screenshot 2022-07-07 at 14 54 26" src="https://user-images.githubusercontent.com/4520803/177791015-ffb41764-90c5-4c38-82ca-67e5da932788.png">
