### ISSUE TITLE
Form Element Not Processed

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2937]
In the admin template customers.subscribers.php`, there is:
```
<select name="multi_subscriber_action">
```
This form element is not processed in `customers.subscribers.inc.php`.

However, there is:
```
if (isset($_POST['rem_subscriber']) && is_array($_POST['rem_subscriber'])) {
```
which does process the selected line items, but it seems there should be a check for the affirmative selection of the 'Delete' option of the drop-down chooser.

Currently, clicking the Go button will begin the removal of the selected line items, but it seems not checking the actual choice to Delete does not conform to the programming that other admin functions which use this approach.

For example, at some point in the future, when additional functions are to be  affected against the selected line items, the programming will come around to use the more common approach.

Suggest:
```
switch ($_POST['multi_subscriber_action']) {
  case 'delete':
    if (isset($_POST['rem_subscriber']) && is_array($_POST['rem_subscriber'])) {
```

**Comment by abrookbanks** [comment]
Thanks. This has been resolved already in 6.4.4 I believe.
