### ISSUE TITLE
Square Payment Gateway 1.1.6

### ISSUE THREAD

**Issue by harris-organic** [cubecart/v6#2939]
I have had a few instances where the customer has paid twice for the same order and yesterday THREE times when using the square extension. My cart also has a Paypal option. There are no double/triple payments with PayPal. 

In my Square account the time stamp, $ value and order number are the same in the transaction list, but there is only one order.
However, in the transaction logs, the transaction IDs are different.

gBuCw8mOax80D6D5Albqrq3eV | Success | $93.85 | Square | Nov 23 2021, 01:46 am |  
aK6Pjv1RYyC9sGDscMcwP7heV | Success | $93.85 | Square | Nov 23 2021, 01:46 am |  
EzUdWJIWPXnfbvjQtVFvNgneV | Success | $93.85 | Square | Nov 23 2021, 01:46 am

If two/three payments are made with the time stamp, $ value and order number can we have a message to say double/triple payment has been made?
AND
refund payments are listed on the transaction logs as debits, not credits
OR 
the Square extension software is modified so that only one payment can be made per order.

**Comment by harris-organic** [comment]
Just had an email from Square saying they are changing the way the OAuth service handles the redirect URL.
Will the extension be updated to provide this URL or will the extension stop working?

**Comment by abrookbanks** [comment]
I've released 1.1.7 which disables the submit button payment submit. This prevents the customer clicking it more than once which is probably the cause.

**Comment by harris-organic** [comment]
Thanks, Al,

 

Seasons greetings.

 

kindest regards

 

Duncan Harris
