### ISSUE TITLE
Classes to make URLs

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#294]
Foundation beta6:

I understand that CC6 is "SEO Only". But I request that the classes be responsible for constructing any and all URLs.

I see in the template box.session.php that all the links are hard-coded. For examples:
`{$STORE_URL}/index.php?_a=profile`
`{$STORE_URL}/login.html`
box.navigation.php
`{$STORE_URL}/gift-certificates.html`

I also see that the CC6 classes still make available the `{$URL}` variable that CC5 skins use. (So no loss there.)

**Comment by abrookbanks** [comment]
Hmm.. agreed this needs sorting. I'm just not immediately sure how.
