### ISSUE TITLE
Inclusive Taxes Maths May Be Faulty

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2940]
Please see:
[https://forums.cubecart.com/topic/57397-options-pricing-now-incorrect/](https://forums.cubecart.com/topic/57397-options-pricing-now-incorrect/)

**Comment by abrookbanks** [comment]
I'd like to look at this in a support type scenario. I believe the merchant in question has a very modified store for lengths and types of option to calculate totals differently.
