### ISSUE TITLE
highlight search keyword for elasticsearch

### ISSUE THREAD

**Issue by chongshengdz** [cubecart/v6#2941]
highlight search keyword for elasticsearch

**Comment by chongshengdz** [comment]
highlight search keywords in search results for elasticsearch

**Comment by abrookbanks** [comment]
Can you provide a bit more information?

**Comment by chongshengdz** [comment]
> Can you provide a bit more information?
highlight search keywords in search results like Google does.

![highlights](https://user-images.githubusercontent.com/30888843/144056994-dae4dfd5-3ce1-4d40-bb15-ef7067494811.jpg)

**Comment by tonyrsutton** [comment]
So basically making the words (that you're looking for) appear in bold.

My additional suggestion -  it would be good to give us the choice of what colour/format to use i.e. bold, or yellow highlighter

**Comment by chongshengdz** [comment]
RED WOULD BE FINE AND EASY TO RECOGNISE.

**Comment by hairy-dog** [comment]
It should wrap the highlighted text in a span with a specific class. The stylesheet should define how that class is rendered.

**Comment by abrookbanks** [comment]
> So basically making the words (that you're looking for) appear in bold.
> 
> My additional suggestion - it would be good to give us the choice of what colour/format to use i.e. bold, or yellow highlighter

Well this would be via CSS in the skin. It would be mad to have it as a config option.

**Comment by abrookbanks** [comment]
Closing whilst this branch is on hold.
