### ISSUE TITLE
A Smarty Variable That Is Set, but Empty, Still Iterates

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2944]
(I really thought that a Smarty variable set to false would not iterate. But it is happening. Maybe check Smarty version.)

In the admin source file `settings.errorlog.inc.php`, near line 71, `$admin_error_log` is assigned to Smarty `ADMIN_ERROR_LOG`. A `false` could be that value. Now that it is set, even being `false`, Smarty will try to iterate through it - and succeed once.

This results in a one row table with nothing displayed but a checkbox with no value.

(Again, this could be the result of the version of Smarty I am using.)

Suggest putting the Smarty `assign()` statement inside the `if` block. That way, `ADMIN_ERROR_LOG` will not get set if there are no records found, and the `{foreachelse}` block will be displayed.

**Comment by abrookbanks** [comment]
Thanks for raising this. It has pestered me for a while and I meant to log an issue.
