### ISSUE TITLE
Google reveiw snippets (using latest Version cubecart in Cinda skin)

### ISSUE THREAD

**Issue by rds34** [cubecart/v6#2945]
To the owner of https://www.extremeracing.co.uk/:

Search Console has identified that your site is affected by 1 Review snippets issues:

Top Warnings

Warnings are suggestions for improvement. Some warnings can affect your appearance on Search; some might be reclassified as errors in the future. The following warnings were found on your site:

Invalid object type for field "author"

We recommend that you fix these issues when possible to enable the best experience and coverage in Google Search.

**Comment by havenswift-hosting** [comment]
This is not an issue with CubeCart but is a problem with the Cinda skin and you could try contacting the developer.  Alternatively, use our Google Microdata plugin seen here https://www.cubecart.com/extensions/developer/havenswift-hosting

**Comment by rds34** [comment]
Hi

Thank you for the information it was very helpful in solving this issue.

We are currently on PHP Version 7.4.26 will the plugin work?

Regards

Richard

**Comment by havenswift-hosting** [comment]
Yes the plugin will work on 7.4 - it does require ionCube to be activated but any decent hosting will allow you to do that yourself within your hosting control panel if it isn’t activated server wide

**Comment by rds34** [comment]
Still getting the same errors
![same errors](https://user-images.githubusercontent.com/27129577/144747597-4ea8ea6f-f891-4e2a-8f67-f54e297ebd4d.jpg)

**Comment by rds34** [comment]
I jumped the gun slightly still waiting to hear back regarding ioncube

Regards

Richard

**Comment by abrookbanks** [comment]
Please contact the developer

**Comment by rds34** [comment]
Hi Al

I have tried but his website is unavailable & doesn’t seem to be on cubecart with the cinda skin either

Do you have any working contact details for him?

Regards

Richard

**Comment by abrookbanks** [comment]
Thats a shame. No we have the same contact methods as you. If you have tech support access we can look into it for you.

**Comment by rds34** [comment]
I used to but the last time I tried to login the section had gone, is it else where?On 6 Dec 2021 10:51, Al Brookbanks ***@***.***> wrote:
Thats a shame. No we have the same contact methods as you. If you have tech support access we can look into it for you.
