### ISSUE TITLE
PayPal Commerce : Issue with shipping

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2946]
In paypal_commerce/hooks/class.cubecart.construct.confirm.php

we have the following code

`
 // Check we deliver to this country
 $country_status = $GLOBALS['db']->select('CubeCart_geo_country', array('status'), array('iso' => $address['country_iso']));
 if(!$country_status || $country_status[0]['status']=='0') {
        $GLOBALS['gui']->setError("Sorry but we are not able to ship to your country at this time.");
        $GLOBALS['session']->delete('paypal_orderId','paypal_commerce');
         httpredir('index.php?_a=basket');
 }
`

As well as having hard coded language text, this takes no account of whether an order is digital only, where this check should not be done.

This is actively affecting at least two clients and causing lots of orders to be lost

**Comment by abrookbanks** [comment]
Thanks Ian. Fixed with 1.5.1.

**Comment by havenswift-hosting** [comment]
Thank you for turning that around so quickly !

**Comment by bhsmither** [comment]
Does this answer the question for when the entire inventory of digital products are geo-fenced?

**Comment by abrookbanks** [comment]
> Does this answer the question for when the entire inventory of digital products are geo-fenced?

I'd have thought that any GEO fencing for availability should be higher down the line. For example on the product detail page based on GeoIP data. "Sorry this item isn't available in your region".

I'm not sure but I'd hedge a bet most merchants don't want geo fencing on digital products.
