### ISSUE TITLE
Feature request: customer reminder email when order status is Pending

### ISSUE THREAD

**Issue by SteveCGS** [cubecart/v6#2947]
When a customer does not complete payment for an order we have been manually emailing them recently to find out why. In about half the cases the customer has not realised that payment was not successful, or had got distracted before completing payment. The rest had just changed their mind or shipping costs had put them off (for US customers, we are in the UK).

Is it possible to send an email to a potential customer who has gone to the trouble of creating an order and supplying their details etc, but has not completed payment? Ideally this would be sent after a period of time from creating the order, say 30 minutes or so.

**Comment by tonyrsutton** [comment]
I support tis feature request - it will be very useful as I too face the same issue!

**Comment by Dirty-Butter** [comment]
I manually send an email as well. Would love to see this feature included.

**Comment by bhsmither** [comment]
There is this:
```https://www.cubecart.com/extensions/plugins/abandoned-carts-capture-missed-opportunities```

**Comment by SteveCGS** [comment]
> There is this: `https://www.cubecart.com/extensions/plugins/abandoned-carts-capture-missed-opportunities`

I installed this extension but it only works with abandoned carts rather than _orders_, that is to say a customer who is logged in and adds products to the basket but doesn't take the further step of going to a payment gateway, Once they do go to a payment gateway, the Abandoned Carts extension stops tracking the basket and so no email is sent out,

I emailed the developer and was told the feature we are looking for is going to be added early next year (2022).

**Comment by abrookbanks** [comment]
Closing as a feature request to be assigned a milestone later. This is a good one.
