### ISSUE TITLE
Remove 350Kb image upload limit

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2948]
As subject suggests. Dropzone has a built in tool to resize the image.

See resizeWidth or resizeHeight https://docs.dropzone.dev/configuration/basics/configuration-options 

Instead replace the 350Kb limit with the PHP ini limit dynamically. 

Preliminary tests showed that uploading a 4.71MB JPG with 4000 x 3000 pixels file with `resizeWidth` set to 500 resulted in a 54Kb file of 500 x 375.

**Comment by abrookbanks** [comment]
This works beautifully with large images but changes all to jpg. Does it matter?

```
$("div.dropzone").dropzone({url: dropzone_url, resizeWidth: '1200', resizeMimeType: 'image/jpeg', acceptedFiles: 'image/gif,image/jpeg,image/png,image/webp', renameFile: function (file) {
            return file.name.substr(0, file.name.lastIndexOf(".")) + ".jpg";
        }, init: function () {
                this.on("complete", function (file) {
                    if($("div#imageset.fm-filelist").length) {
                        if (this.getUploadingFiles().length === 0 && this.getQueuedFiles().length === 0) {
                            var t = $("#val_admin_file").text();
                            $("div#imageset.fm-filelist").fileTree({
                                root: "/",
                                script: "./" + t,
                                group: '1',
                                name: 'imageset',
                                unique: false
                            });
                        }
                    }
                });
                this.on("processing", function(file) {
                    var subdir = '';
                    if($("#val_subdir").length) {
                        subdir = '&subdir='+$("#val_subdir").text();
                    }   
                    this.options.url = dropzone_url+subdir;
                });
            }
        }); 
```

**Comment by tonyrsutton** [comment]
I think PNG would be the best file format for the Web.

**Comment by hairy-dog** [comment]
You can think what you like, but I know that png is NOT the best format for the web.

**Comment by abrookbanks** [comment]
Agreed. I will investigate if that is possible.

**Comment by abrookbanks** [comment]
> You can think what you like, but I know that png is NOT the best format for the web.

😂 yes there is no black and white answer to that. SVG, WEBP, requiring transparency, scaling etc... 

Well Dropzone has a built in tool to get the client to resize the image and set the quality before upload. If we go this route we can lose the annoying 350Kb restriction and know that the uploaded image will be suitable. Say 1200px max at 80% quality.

From my testing it only works reliably when the original image is converted to jpeg format.

Plenty of work to do here still but so far it's looking like we either keep things as they are or force jpeg conversion and remove the upload limit size.
