### ISSUE TITLE
Code Check

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2949]
In `catalogue.class.php`, near line 2111, there is (shortened):
```
if (($gallery = $GLOBALS['db']->select( ... ))) {
```
Note the leading and trailing doubled parentheses.

We assume what is meant is:
```
if (($gallery = $GLOBALS['db']->select( ... )) !== false) {
```
However, the expression `$gallery = false` might make this a moot point, but the overall coding style for database calls implies that the truthiness of this expression be tested. Expanding on that, if the expression should evaluate to something other than false-like, but still not be iterable, PHP will complain that `foreach` has a bad argument, `json_encode` will return false (which might be disagreeable with the skin's javascript), and `return` will return a type of 'unknown variable'.

**Comment by abrookbanks** [comment]
Thanks Brian.
