### ISSUE TITLE
Feature Suggestion - NOT to send email when cancelling an Pending order

### ISSUE THREAD

**Issue by tonyrsutton** [cubecart/v6#2951]
Now and then, I will have a customer who somehow placed 2 x same orders. One as Pending with the other one as Processing.

I keep one and cancel the other one. But this send out the email notification, making them to think I've cancelled the order when I have not.

It would be good to allow me to cancel the Pending order without sending an email. Currently, I change the email address to mine, cancel it and then changing it back.

I do know the option to Delete the Pending order, but I wasn't sure if the stock level will be restored or not?

Thanks.

**Comment by abrookbanks** [comment]
<img width="725" alt="Screenshot 2022-07-06 at 09 43 08" src="https://user-images.githubusercontent.com/4520803/177509146-1b99deb7-18b7-4a91-806e-c0ff2cbd1f1c.png">

**Comment by tonyrsutton** [comment]
You da man, thank you.

**Comment by abrookbanks** [comment]
Thanks for your patience!! I need more of me.
