### ISSUE TITLE
Property of Non-Object

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2952]
(With respect to #2896,) There may be a problem with code in the PayPal Commerce file `paypal.class.php`, the `_errorDetected()` function.

At line 190 (and elsewhere), a JSON-formatted string - in this PayPal case - is returned from `$request->send()` and assigned to the variable `$result`.

This string is sent to `_errorDetected()`, but is then treated as an object prior to being `json_decoded()`. And regardless, `server_response_code` is not in the JSON string (I assume).

There is a public property of the Request class (local variable `$request`) named `server_response_code`.

In the various functions in `paypal.class.php` where we get the result of `$request->send()`, perhaps the JSON string could be decoded, the `$request->server_response_code` gets added to the array, and encoded back to a JSON string.

Then, in `_errorDetected()`, decode `$result` first, check the response code, then also check for `'UNPROCESSABLE_ENTITY'`, **logging** the `$value['description']` even if still wanting the customer to see what data item was disagreeable on a GUI error banner.

**Comment by abrookbanks** [comment]
From 6.4.8 the request class will better handle errors from PayPal.

Changed to:

```
trigger_error($value['description'], E_USER_NOTICE);
``` 

with generic front end message. 1.7.5 released
