### ISSUE TITLE
Mailer->sendEmail Contents

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2957]
`Mailer->sendEmail()` has `$contents` as a default is `false`.

Later, we are looking at `$contents['to']`. If no `$contents` were provided to the function, PHP might complain about accessing an index on a boolean.

Later, `$contents` is sent to `_parseContents()` where `$contents` is processed only if it is string (returning a string), or an array (returning an array). Otherwise, returning `false`.

After `_parseContents()`, `$contents` is only worked on if it is an array.

Suggest the default variable type for `$contents` be an empty array, and to put `$contents` into an array if it arrives as a string.

**Comment by abrookbanks** [comment]
Are you referring to `admin/sources/maintenance.index.inc.php`?

**Comment by bhsmither** [comment]
`/classes/mailer.class.php`

**Comment by abrookbanks** [comment]
I decided that _parseContents when given a string should still return a string. Right now there is no case where this would actually be used (unless I missed it). By returning an array I believe it would need to be put into either an HTML or pain text key. Let me know if you disagree or if I got this wrong.
