### ISSUE TITLE
PayPal button on Product Page

### ISSUE THREAD

**Issue by claudia39** [cubecart/v6#2959]
Would be nice to have a PayPal pay button on the product page.  That way the customer can bypass the checkout process by using their PayPal account directly

**Comment by abrookbanks** [comment]
This is being looked into. :)

**Comment by claudia39** [comment]
Have you decided not to add the PayPal button to the product page?

**Comment by abrookbanks** [comment]
Working on this today...

**Comment by abrookbanks** [comment]
<img width="745" alt="Screenshot 2022-07-14 at 15 25 30" src="https://user-images.githubusercontent.com/4520803/179005824-1507fdfa-7f6d-4510-8ee0-1829e42ce075.png">

**Comment by abrookbanks** [comment]
All done. Please use the 1.7.0 version upwards.

**Comment by claudia39** [comment]
Yeah!  Thank you!

**Comment by abrookbanks** [comment]
Let me know how you get on.

**Comment by claudia39** [comment]
I tried it and this is what I get – See attached file.  I know before this version if I enabled the buy later message on the product page, the message showed many times.  Also in the current version the PayPal button doesn’t show on the product page unless I had the buy later message enabled – and it still shows many times.  Also any way to have Venmo optional along with the buy later message?

**Comment by abrookbanks** [comment]
I don't see an attached file. Can you email support@cubecart.com with the attached files and access to the files? Thanks.
