### ISSUE TITLE
Search Words

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#296]
When a search phrase is used such as, `Tesa31, Test`, the search may fail.

This is because catalogue.class.php, `searchCatalogue()`, starting line 1591 (beta6):
```
} else {

  $rlike = '';
  if (!empty($search_data['keywords'])) {
    $searchwords = preg_split( '/[ ,]/', $GLOBALS['db']->sqlSafe($search_data['keywords']));
    foreach ($searchwords as $word) {
      $searchArray[] = $word;
    }
```
`preg_split( '/[ ,]/'` will split on either a space or a comma, but for only one of the two characters at that location in the string.

In the example given above, the result might be:
```
[0] => "Tesa31,"
[1] => "Test"
```
The PHP manual at http://us1.php.net/manual/en/function.preg-split.php, `example #1`, suggests:
`preg_split( '/[\s,]+/'`
This splits on any whitespace character or the comma for an unlimited series, such as:
`Tesa31,,\t  , ,, \n\r  , , Test`
Think of the phrase, 'idiot proofing'.

**Comment by abrookbanks** [comment]
Thanks Brian.
