### ISSUE TITLE
Null for Array Parameter for Function

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2961]
In `products.index.inc.php`, near line 1006, there is:
```
function option_matrix($unique_groups)
        {
            $no_groups = count($unique_groups);
            if ($no_groups <= 1) {
                return $no_groups ? array_map(function ($v) {
                    return array($v);
                }, $unique_groups[0]) : $unique_groups;
            }
```
Having set `$unique_groups` to an empty array, if there are no options, there will be no elements in `$unique_groups`.

Later, at line 1024, calling `option_matrix()` with that empty array will cause PHP to warn about `$unique_groups[0]` being null for the `array_map()` function.

It seems as if PHP is executing the true part of the ternary structure regardless if it will actually be used.

Suggest a standard `if(){}else{}` structure:
```
if ($no_groups <= 1) {
  if ($no_groups) { return array_map(function($v){return array($v);}, $unique_groups[0]); } else { return $unique_groups; }
}
```

**Comment by abrookbanks** [comment]
Thanks this works well.
