### ISSUE TITLE
More Loaded gets Browser Stuck at that Stage

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2963]
Minor issue, but may cause some confusion for the visitor.

Given a category with 9 products in it, and the skin configured to default 4 products per page.

The first page view shows 4 products. Click **More**.

The new page view (same page with the incoming product list appended) now shows 8 products. A cookie has been set.

Visiting any other page* does not delete this cookie. Clicking on the NavBar link for this category restores you to the number of products shown when last visited -- in the following manner: The initial 4-product page is shown, a 'click' is simulated causing the fetching of the second group of products, a 'click' is simulated causing the fetching of the third group of products, and so on until enough page requests have been made to get to the "page number" where you were last on this category.

For a store owner to put hundreds of products in a category, resulting in dozens of pages, this looped action might get stupid ridiculous.

A minor point, as mentioned, as the visitor could simply scroll up to get to items higher up the list.

* The cookie is for the most recent category that had the More button clicked - discarding any knowledge about any other category that had the More button clicked
* The code suggests that clicking in the Search text entry box will delete the cookie.
* The cookie lasts 10 minutes
* Will viewing Sale Items also delete the cookie?

**Comment by abrookbanks** [comment]
This is a significant improvement and puts the client to work instead of repeat lookups.
