### ISSUE TITLE
Multiple Delete Customer

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2964]

**Comment by bhsmither** [comment]
I have done this. Code to follow soon.

**Comment by abrookbanks** [comment]
That would be a great contribution. Thank you. 😃

**Comment by bhsmither** [comment]
Two files to modify.
[Multi-Delete Customers.txt](https://github.com/cubecart/v6/files/8044921/Multi-Delete.Customers.txt)

**Comment by abrookbanks** [comment]
Thanks so much for this Brian.

**Comment by MarlineSim** [comment]
Hello,

Where do I find the files to edit them. It's been a while since I've edited my cubecart.
