### ISSUE TITLE
Bad Call for Class Method

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2965]
In `setup/setup.install.php`, line 112, there is a call for `$e->message`.

All other CubeCart code uses `$e->getMessage()`, and the docs at:
`https://www.php.net/manual/en/class.exception.php`
suggest `$message` is protected, where `getMessage()` is used to fetch it.

**Comment by abrookbanks** [comment]
Thanks.

**Comment by abrookbanks** [comment]
See f0cf22a7eba7eb8d4091e72ca42444b768b41d95
