### ISSUE TITLE
Email Validation

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2966]
Work on this was started and some preparation code was added but it was never completed.  So many potential customers enter their own email address incorrectly plus this would also help cut down on spam customer registrations

**Comment by abrookbanks** [comment]
Hi Ian, I'm not sure what you are telling me. Is this a bug or extended validation steps?

**Comment by havenswift-hosting** [comment]
Extended validation - too many email addresses are entered incorrectly. So it either needs double entry and comparison or an email sent to entered address with a link which needs to be clicked on before signup or order can be progressed

**Comment by abrookbanks** [comment]
> email sent to entered address with a link which needs to be clicked on before signup or order can be progressed

I'm not saying this shouldn't be a feature but it's a huge barrier to sale. I've never come across this feature on an ecommerce store before. Double entry is not so bad but still an extra field to complete.

**Comment by tonyrsutton** [comment]
Perhaps add this feature and leave the settings for us to control?

I would also find it useful.

**Comment by lyndsiesal** [comment]
I sell digital products and I have several customers each week who contact us that they have not received order emails and it's almost always that they typed their email address wrong, so an extra field to verify what they typed would be very helpful.

**Comment by hairy-dog** [comment]
I think that you are thinking of email confirmation. I'm guessing that validation is when you email a token to check the address and the registration awaits that.

**Comment by Dirty-Butter** [comment]
I currently have double entry coded into my registration. It saves a lot of trouble trying to contact careless customers.

**Comment by abrookbanks** [comment]
<img width="509" alt="Screenshot 2022-03-14 at 10 58 46" src="https://user-images.githubusercontent.com/4520803/158159022-d3b18247-70bb-4211-8c81-5e28b1093681.png">

**Comment by tonyrsutton** [comment]
That seems to be a good workaround.

Perhaps disable copy & paste functionality on the 2nd field box? This way, the user is forced to manually type in the email address to confirm their correct email address.

**Comment by tonyrsutton** [comment]
Also - "Please check your emails match"

Perhaps "Please check your e-mail address matches" ?

**Comment by abrookbanks** [comment]
<img width="732" alt="Screenshot 2022-03-14 at 11 14 20" src="https://user-images.githubusercontent.com/4520803/158161231-b5236d28-4840-4beb-8214-8913d97c091a.png">

**Comment by abrookbanks** [comment]
Thanks for the feedback so far. I'll leave this open for now. Let me know what you think.

**Comment by havenswift-hosting** [comment]
> Thanks for the feedback so far. I'll leave this open for now. Let me know what you think.

This is a big improvement thanks and allowing store owners to choose to enable or not is great

> Perhaps disable copy & paste functionality on the 2nd field box? This way, the user is forced to manually type in the email address to confirm their correct email address.

I would also agree with this as an extra feature

> I'm not saying this shouldn't be a feature but it's a huge barrier to sale. I've never come across this feature on an ecommerce store before.

Many sites have email confirmation as part of the registration process but again make it store owner configurable and then they have the choice

**Comment by abrookbanks** [comment]
Thanks guys. Hmm disable copy and paste that's a new one to me.. I'll look into that. :)

**Comment by abrookbanks** [comment]
Well that was easy. :)

**Comment by tonyrsutton** [comment]
Perfect, thank you.
