### ISSUE TITLE
Square module: SqPaymentForm will be deprecated 2022/07/21

### ISSUE THREAD

**Issue by adam12** [cubecart/v6#2970]
Opening this for posterity as it looks to affect the current version of the Square plugin.

The migration guide Square provides is linked here: https://developer.squareup.com/docs/web-payments/migrate

**Comment by abrookbanks** [comment]
This has been done with 2.0.0 but now has a cost unless a CubeCart customer. 
https://www.cubecart.com/extensions/payment-gateways/square-payments 

Other free alternate solutions such as PayPal Commerce are available.

**Comment by hairy-dog** [comment]
This seems like quite a high price for an add-on. 
Is this expensive because it was a huge amount of work, or because is seen as a luxury item, or for some other reason?

**Comment by abrookbanks** [comment]
The PayPal alternative is free and IMO better.

**Comment by hairy-dog** [comment]
I am not a fan of PayPal or its owners

**Comment by abrookbanks** [comment]
Do you mind me asking why?

**Comment by abrookbanks** [comment]
It is completely new integration which took two hole days to develop. After around 18 sales at £40 it can be made free.
