### ISSUE TITLE
Spam on Forum

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#2972]
I've given up reporting spam on the forum, as nothing is being done about it. I've messaged you several times, Al, with no response. Feel free to delete this issue, but please deal with the spam or expect the forum to lose its usefulness.

**Comment by tonyrsutton** [comment]
I agree, I have been reporting them too. It's getting out of control. :/

@abrookbanks - have you considering giving a Mod status to someone trusty who can delete these spam now and then? I'm happy to throw my name in as I've been forever marking these posts as spam.

**Comment by abrookbanks** [comment]
Sorry I've not been getting any forums notifications for some reason. 

I've contacted the software provider and they haven't given me any useful help to get on-top pf this spam. You'd think you can block links on new accounts or make them manually approved... no.

I'd love to welcome you guys as mods!! Thank you.

**Comment by tonyrsutton** [comment]
Thanks. We'll look after your forum, so you can focus on CubeCart :)

**Comment by havenswift-hosting** [comment]
DB and I have both previously been mods and am always happy to help again

**Comment by abrookbanks** [comment]
My time is really streached. Thank you so much for your time. I can promise you it's hugely appreciated.

There are some issues here I must address for the next release.

**Comment by Dirty-Butter** [comment]
I don't have time to be a mod, but I will be glad to report spam as long as it's being taken care of.
