### ISSUE TITLE
Bug : adding product with multiple compulsory options doesnt work

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2973]
This is verified with latest CubeCart and using unmodified foundation

The problem is if you try to add products from a Category listing page and that product has two compulsory product options

If there is more than one compulsory product option then it seems to do one of two things : a) an option from each compulsory option set is chosen at random or b) an option is chosen at random from only one of the compulsory option sets, and the product is added to the basket with some options not chosen at all

1) From the above pages, if trying to add a product with a single compulsory option, then it works correctly
2) If you try to add a product from the product page either with one or two compulsory options, then this works correctly

**Comment by abrookbanks** [comment]
What am I doing wrong? Both these options are required.

https://user-images.githubusercontent.com/4520803/159275794-6087f699-6a31-4ac3-ae79-a197a989fdb9.mp4

**Comment by havenswift-hosting** [comment]
We have not been able to 100% reliably work out the set of circumstances.  However, try making one of the options have a default - it then seems to take the default and ignore that the second option is compulsory

**Comment by abrookbanks** [comment]
Happy to look again once we have steps to reproduce.

**Comment by havenswift-hosting** [comment]
I did offer you admin and file access to this site so you can see it for yourself.  This is happening using core CubeCart and foundation skin

**Comment by abrookbanks** [comment]
I haven't been able to reproduce it.

**Comment by havenswift-hosting** [comment]
> I haven't been able to reproduce it

Probably just means that something in the two environments is different but as I have said this is core CubeCart with almost no plugins so a "custom" site cant be blamed

**Comment by abrookbanks** [comment]
I do believe you. :)

**Comment by havenswift-hosting** [comment]
Well the offer is still there and would cheer up a very unhappy customer

**Comment by abrookbanks** [comment]
I don't need an offer. I need clear steps to reproduce the issue. I haven't been given this which makes it absolutely impossible to look into.
