### ISSUE TITLE
Putting multiple files in one folder

### ISSUE THREAD

**Issue by CQer789** [cubecart/v6#2974]
Hi everyone,
I sell digital downloads only (sheet music and audio files), some of the sheet music has multiple parts, ie. there is one score that has all the instruments on one sheet and then the separate parts can be bought separately.
However, to do that, I need to put the individual sheets of the parts in one folder, but CC does not seem to allow me to do that.
Is there a way that can be achieved, please?
Thank you in advance.

**Comment by tonyrsutton** [comment]
Hi, please use https://forums.cubecart.com for discussions. This Github is really for bug reports.

Thanks.
