### ISSUE TITLE
PHP 8 New Parameters Requirements

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2975]
With respect to #2728, please give some effort to find and fix all scenarios where a non-optional parameter follows an optional parameter.

So far, `/classes/db/database.class.php` lines 175 and 267.

**Comment by abrookbanks** [comment]
It's a MUCH bigger deal than this. 
https://php.watch/versions/8.1/GLOBALS-restrictions

**Comment by abrookbanks** [comment]
Even if we recode around this no existing extensions will work. I doubt. Any thoughts? In my eyes we are stuck at PHP 7.4.

**Comment by bhsmither** [comment]
This is how I read the notice:
`\$GLOBALS[ =,.]+` will find:
```
$GLOBALS with a following space and/or equals and/or comma and/or period for 1 to many times.
```
A Regex search across the CC644 codebase showed no results.

A Regex search on just `^\$GLOBALS$` showed no results.

A Regex search on `\$GLOBALS\[` (brackets for using a key for the array element) shows 5088 instances.

I am confident there is no statement in CC644 that assigns or modifies `$GLOBALS` **to the whole of it's existence**, which is how I read the notice.

Always use a key into the `$GLOBALS` array and there won't be a problem. That's what I'm going to say.

This issue was posted to the Github from a conversation in the forums. Surely, that OP would have reported much, much more than just the specific warning.

**Comment by abrookbanks** [comment]
> It's a MUCH bigger deal than this. https://php.watch/versions/8.1/GLOBALS-restrictions

Well I was wrong. My local dev environment is now PHP 8.1 and it's working. Working my way through these..
