### ISSUE TITLE
$0.00 Cart should bypass collection of personal information - option

### ISSUE THREAD

**Issue by RonSharcott** [cubecart/v6#2976]
Many items will have a $0.00 cost (especially when digital). A cart may be full of these "Giveaways" (also known as Lost Leaders). The check out process forces people to reveal personal information for shipping and account setup. 

There should be a setting in the Settings section to skip the account setup if the cart is $0.00. Some sites might want to collect information on these type of "sales" but others may respect user's privacy. The data collected is only needed for a monetary exchange.

If there is a way to do this that I have not found, please let me know. Cracking the code is not the best option because future updates will likely overwrite any changes. It would be good to have this option built in so it is stable with future upgrades.

**Comment by hairy-dog** [comment]
I'm struggling to understand this.
If the product is free, that doesn't mean you don't need a delivery name and address. 
Perhaps if a product is both free and downloadable, it's different.
It is illegal to collect any personal details that aren't needed, so no sensible store does this. You do need a name and address to deliver to, regardless of price.
What "personal information" is to be bypassed for a free backer?

**Comment by hairy-dog** [comment]
.... basket

**Comment by abrookbanks** [comment]
This is a business specific requirement which isn't really in the global scope of CubeCarts main audience. It would need to be developed as a bespoke customisation.

**Comment by RonSharcott** [comment]
When  a customer selects an item from your store that is $0.00 you should have the option to send that customer straight to their downloads avoiding the requirement to fill out a lot of personal information. So, if the cart total is $0.00 then bypass the collection of information. 

Regardless, because Cubecart is data driven and more about collecting data I have moved on. Sorry that a simple concept as giving something away for free shouldn't have to cost the buyers personal information was so hard to understand.

**Comment by abrookbanks** [comment]
@RonSharcott please don't think this has been dismissed just because it's been closed. All new feature requests are closed until they are added to the roadmap. Hopefully CC can work for you in the future and sorry it's not right for you at this time. CubeCart has been ultimately designed for at cost catalogues. Hopefully you can find a different product that does fit your specific business needs.

**Comment by RonSharcott** [comment]
Sorry, bad morning and I didn't think it was that difficult of a concept. A feature like that would then allow freebees to be given away easily but still allow for cost items to go through accounts. I tried looking at the guest account but that doesn't seem to work or at least work as expected.

**Comment by abrookbanks** [comment]
Also how is a basket handled with a mix of free (instant access) and billing details required items for tax/shipping concerns?

**Comment by RonSharcott** [comment]
If the basket is above $0.00 then it goes through the regular routine because something costs and may need to be shipped or warrantied.

"If Cart is 0 cost then complete transaction without collecting information"

**Comment by abrookbanks** [comment]
@RonSharcott maybe just an instant link in the product detail page to download there and then. This would be a pretty simple change. The add to basket button could just read "Download". This is probably an hour or two to build.

**Comment by RonSharcott** [comment]
What I am working with is simple little Google Maps routes planned and downloadable as KMZ files. They sit in the store with a description, a pic and the ability to download. The basket allows for several to be selected before completing the transaction. Obviously, they are not worth anything other than the time to put them together and they don't appreciate. Eventually some items may be sold for $ but right now it acts as a service without having to hand code every page and have a sloppy presentation. Does that help to put it in perspective?

**Comment by hairy-dog** [comment]
If you are simply offering a free download, there is no need for any online store. Just put a link into a simple web page.
  

  

  
  
 -- Iain  

  
  
  
  
  
>

**Comment by RonSharcott** [comment]
Still not getting it are you hairy

**Comment by abrookbanks** [comment]
@hairy-dog I think @RonSharcott wants to be able to turn on purchases in the future for some products.

I think the only feasible way to do this is to allow free products to have the option of an instant download (bypassing basket). That would be simple enough to do.

**Comment by RonSharcott** [comment]
@abrookbanks pretty close. A link in the description looks too hackish and doesn't allow for the collection of a few items to be processed all together. Why not treat them as proper items than to just make it look like a dump screen where you put your trash.

**Comment by hairy-dog** [comment]
Oh, I get it. The problem is that I think the premise of the issue is nonsense

**Comment by RonSharcott** [comment]
Great community you have here Cubecart

**Comment by abrookbanks** [comment]
> Why not treat them as proper items 

Simply because it significantly complicates the issue. Bypassing all the required checkout fields and fundamentally altering the whole checkout process is heavy going which is unlikely to make it into development.  

Am I right in guessing that you haven't found any off the shelf solution that can do this?

**Comment by RonSharcott** [comment]
Yes, I have a solution that can bypass the account requirements. 

@abrookbanks Can you lock this conversation. There really is no need for it to go any further.
