### ISSUE TITLE
Validate customer registration for same first & last name

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2977]
This is mainly to prevent spambots.

**Comment by abrookbanks** [comment]
See f0fa7347580bcd183574dfbc41792e610a5826e6 typos in commit.

**Comment by bhsmither** [comment]
If the purpose is to foil bots, which probably do not process any human-readable response, why display a message?

My vote is to just bounce them to _Yahoo!_.

**Comment by romanklabal** [comment]
I believe this check should be removed, otherwise people like [Mr. Pavel](https://en.wikipedia.org/wiki/Pavel_Pavel) will not be able to purchase anything. God forbid he would be sent away without any explanation to Yahoo.
