### ISSUE TITLE
Bug : Add to cart issues

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#298]
As per https://forums.cubecart.com/topic/49337-v6-add-to-cart-problems/

**Comment by kealanm1** [comment]
Hi Havenswift, 

I raised something similar earlier in the process https://github.com/cubecart/v6/issues/104 perhaps there is some similarity in the issue. Back in beta 3 I struggled to add individual products from the latest products section, I was getting multiple entries when adding the 2nd/3rd etc.. items to the basket.

Kealan

**Comment by abrookbanks** [comment]
I would say this is a pretty epic bug and it concerns me there may be others this significant gone unnoticed. I think we'll have to have another beta release. :unamused:
