### ISSUE TITLE
Use of BOOL for TINYINT Column Type

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2981]
In `CubeCart->getDocument()`, near line 155, there is this in the statement:
```
array('doc_home' => true, 'doc_status' => '1')
```
The schema for `CubeCart_documents.doc_home` is a data type of `tinyint`. While `true` does resolve to a `non-zero-ish` value (non-strict), there is trouble on the horizon.

PHP 8.1 says: Argument of type bool for ctype_alnum() will be interpreted as string in the future." (This relates to `Database->where()` near line 926:
```
if (isset($value) && !ctype_alnum($value) || $value=='NULL' || is_null($value) || $value=='NOT NULL') {
```
Suggest:
```
array('doc_home' => '1', 'doc_status' => '1')
```

**Comment by abrookbanks** [comment]
Resolved as part of #2708 Thanks!
