### ISSUE TITLE
Stripslashes With Null Argument

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2983]
This is deprecated - unknown for how long it has been so.

There are a few places where an array is passed to `array_walk_recursive()` which will callback `stripslashes()` and `custom_urlencode()`.

In `custom_urlencode()`, there is no check against a `null` being passed in. (See `Database->strip_slashes()`.)

Additionally, in `controller.index.inc.php`, near line 83, there is:
```
$_GET['_a']  = (isset($_GET['_a'])) ? $_GET['_a'] : null;
```
(which is present in early versions of CC5)

Is this statement still necessary?

`$_GET` is examined in `currentPage()`, resulting in "Deprecated" messages.

**Comment by abrookbanks** [comment]
Pretty confident this has now been covered. Thanks.
