### ISSUE TITLE
Use Unknown Variable

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2984]
In `Catalogue->imagePath()`, the variable `$image` is initialized only if `$mode` is other than "source", and `if (isset($skins['images'][$mode]))` is true.

However, `$image` is the argument to `filesize()` which is called after the `$mode`'s if/else structure.

Suggest putting the `filesize()` test within and at the bottom of the `if (isset($skins['images'][$mode]))` block.

**Comment by abrookbanks** [comment]
Thanks.
