### ISSUE TITLE
Invalid Return Type

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2986]
For PHP 8+: (unknown when this actually became an issue)
"Returning bool from comparison function (uasort) is deprecated."

In `function cmpmc()`, a false could be returned. This function is called from various places as a callback to PHP's sorting functions.

In `Catalogue->getProductOptions()`, for example, `$array` is sent for sorting via `uasort()` (near line 1250).

However, `$array` contains a number of indexed elements where the values are themselves an associative array. In addition to the indexed elements, there is one other element: `['priority']=>value`.

Because there is no `['priority']['priority']`, `cmpmc()` returns `false` to `uasort()`. This is deprecated.

Will experiment with not returning anything.

Seems to have quieted the Deprecated message. Need to look for instances where the returned `false` is being used.

One place where a test is made for where a sorted array is still an array.

**Comment by abrookbanks** [comment]
Thanks.

**Comment by abrookbanks** [comment]
Solution was buggy.
