### ISSUE TITLE
Array Offset on BOOL

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2987]
In `User->registerUser()`, near line 844, a query is made that could set `$existing` to `false` - which is good.

However, later near line 921, a test is made on `$existing[0]['type']` which causes PHP to complain:
"Trying to access array offset on value of type bool."

Suggest:
```
if (is_array($existing) && $existing[0]['type']==2) {
```

**Comment by abrookbanks** [comment]
Thanks. We still have no solution for PHP 8.1 especially with 3rd party extensions coded the same way.

I fear there is no way ahead.
