### ISSUE TITLE
Strict Argument Type #2

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2988]
The database table `CubeCart_option_matrix` has a NOT NULL restriction for the 'options_identifier' column.

Yet, `Catalogue->getProductData()` defaults to _null_ for the optional argument `$options_identifier`.

This _null_ is passed to the where array argument when fetching `$products_matrix_data`.

In `Database->where()`, near line 927, the _null_ is passed into `preg_match()`. PHP throws a message:
"Passing null to parameter#2 ($subject) of type string is deprecated."

Suggest casting parameter#2, `$value`, to a string.

The same for `preg_match()` on `$key` near line 874,

Also, near lines 890 and 944, the _null_ is the argument for `strtoupper()` - which is deprecated.

**Comment by abrookbanks** [comment]
Covered in #2708
