### ISSUE TITLE
Choice of gateway required even when only one enabled

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#299]
See https://forums.cubecart.com/topic/49334-v6-single-gateway-payment-method-shows/

**Comment by jeff1452** [comment]
This is not a freaking "feature" if we choose to only install one gateway every other provider of this service skips the display of the gateway - this is a bug costing me sales...  fix it.  Too many checkout pages gets a customer spooked these days.

**Comment by abrookbanks** [comment]
If you can provide more detailed information about your specific situation maybe we will reopen this as I don't thing the original issue would cost sales.

I need you to tell me;
- the current behaviour.
- the expected behaviour.
- steps to reproduce (if necessary).
