### ISSUE TITLE
Code Check #3: Gallery: Wrong Message Displayed

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2990]
In 'element.product.vertical_gallery.php', if there are **not more than** one gallery images (that is, `count($GALLERY)` is one, or is false-like), a Smarty `foreach` loop object does **not** get instantiated.

This means, on line 30, `$image` is not created, nor is `$image@total` available.

Thus, the 'tap_gallery' message gets displayed when 'tap_enlarge' is the message that should get displayed.

Suggest:
```
      {if count($GALLERY) > 1}
         <a href="#" class="open-clearing" data-thumb-index="0"><img src="{$PRODUCT.medium}" alt="{$PRODUCT.name}" id="img-preview"></a>
         <p class="show-for-small-only">{$LANG.catalogue.tap_gallery}</p>
      {else}
         <div data-clearing><a href="{$PRODUCT.source}"><img src="{$PRODUCT.medium}"></a></div>
         <p class="show-for-small-only">{$LANG.catalogue.tap_enlarge}</p>
      {/if}
```

**Comment by abrookbanks** [comment]
Thanks!
