### ISSUE TITLE
Smarty Syntax Error

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2991]
In the template 'element.markup.json-ld.php', please find:
```
"priceValidUntil":"{/literal}{$smarty.now+15780000|date_format:"%Y-%m-%d"}{literal}"
```
Apparently, the `date_format` modifier is being applied to only the timestamp integer, thus converting it to a string. After which, then, the statement is wanting to sum the string to `$smarty.now`.

Suggest:
```
"priceValidUntil":"{/literal}{{$smarty.now+15780000}|date_format:"%Y-%m-%d"}{literal}"
```

**Comment by abrookbanks** [comment]
thanks
