### ISSUE TITLE
Third-Party Update: Zurb Foundation

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2992]
Suggest updating Zurb's Foundation package to v5.5.3 (currently 5.5.2).

**Comment by bhsmither** [comment]
I am also going to test if the latest (v6.7.4) works.

**Comment by abrookbanks** [comment]
I'm struggling to even get hold of the packages. I think ours has been customised so those customisations need to be pulled out first.

**Comment by abrookbanks** [comment]
I can't really come across a good way to do this. The current version seems very stable.
