### ISSUE TITLE
Code Check: Related Products

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2994]
In `CubeCart->_displayBasket()`, starting near line 1882, there is the effort to collect products that are 'related'.

First step is to get a list of orders that have the same products as those found in the current order.

Second step is to coalesce a list of the products from all these other orders, **but not to include** in this list any product found in the current order. This list is the 'related' products.

Consider that a 'related' product could be a gift card with 'product_id' of 0.

Third step is to iterate through the list, and where work is performed only if the 'related' product is not one of the products in the current order. This determination was already enforced in the query of the second step. (Note below.)

The work effort starts with assigning `$related` with the return from `Catalogue->getProductData($related['product_id'])` where the return value is `false` when the 'product_id' is zero.

This will then throw many errors about "array offset on BOOL", "automatic conversion of false to array is deprecated", and undefined keys.

At the end of the work effort, a test adds to `$related_list` only if 'product_id'>0.

Suggest move the test currently at the end of the work effort into the test at the third step. Such as:
```
From:
if (!in_array($related['product_id'], $product_list)) {
To:
if (!empty($related['product_id']) && !in_array($related['product_id'], $product_list)) {
```
(Note: I was going to suggest in the second step that 0 be added to the array `$product_list`. Such as:
```
From:
array('cart_order_id' => $related, '!product_id' => $product_list)
To:
array('cart_order_id' => $related, '!product_id' => array_merge($product_list,array(0)))
```
Somehow, that doesn't work. The function `where()` strips out empty values.)

**Comment by bhsmither** [comment]
Regarding the second step: not quite completely enforced. If the current order has a product with 'product_id' of 0, then the function `where()` will remove it from the list of 'product_id' values to not look for.

**Comment by abrookbanks** [comment]
Thanks again Brian. This code change was already present. Thorough work here.. much appreciated.
