### ISSUE TITLE
Time Display in Upgrade History

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2996]
Currently, in maintenance.index.php, near line 172:
```
<td>{$version.time|date_format:"%A, %e %B %Y"}</td>
```
Prefer to use CubeCart's `formatTime()` like many other places in the code.

This easily solves PHP's eventual removal of strftime() also (used by Smarty's date_format modifier, but 'fixed' in Smarty 4).

Suggest in maintenance.index.inc.php:
```
$versions = $GLOBALS['db']->select('CubeCart_history');
$version_history = array();
if ($versions) {
    foreach ($versions as $version) {
        $version['time'] = formatTime($version['time']);
        $version_history[$version['version']] = $version;
    }
}
```
And for the skin:
```
<td>{$version.time}</td>
```

**Comment by abrookbanks** [comment]
Thanks.
