### ISSUE TITLE
Code Check: Date Code

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2997]
In catalogue.class.php, near line 412, there is:
```
$review['date_schema'] = formatTime($review['time'], '%G-%m-%d', true);
```
`['date_schema']` is used in element..markup.json-ld.php at:
```
"datePublished":"{/literal}{$review.date_schema}{literal}",
```
Is `%G` the actual desired date code? There are the occasions where the ISO 8601 year returned is not the actual year the event happened.

**Comment by abrookbanks** [comment]
Thanks!
