### ISSUE TITLE
Code Check: No Shipping to be Found After Free Shipping Coupon Applied

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2998]
In `Cart->discountAdd()`, near line 666, the code will add a "free shipping" coupon to the `basket`, and also unset `basket['shipping']` and `basket['default_shipping_set']`.

On the rebound, at various locations, such as `Cart->_applyDiscounts()`, elements of `$this->basket['shipping']` is used.

Since `$this->basket['shipping']` no longer is set, PHP will complain, and PHP 8 might complain bitterly.

**Comment by abrookbanks** [comment]
I can't reproduce any problems with PHP 8.2. Saying this there have been numerous other code changes to check for e.g. `if (isset($this->basket['shipping'])..`.

On those grounds this issue may have been fixed already. Fortunately using a discount code for free shipping isn't causing any upset (or notices or warnings).
