### ISSUE TITLE
AutoSave User's Cart Checkbox

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#30]
Intentionally deleted, missing, or moved?

**Comment by abrookbanks** [comment]
It's intentionally removed and on by default. We want purchases to be as easy as possible! :-)

**Comment by Dirty-Butter** [comment]
I agree! Thanks!

**Comment by abrookbanks** [comment]
Excellent. I closed this then but haven't licked it so it can be debated still if anyone feels the need. :)
