### ISSUE TITLE
Foundation skin with documents on top

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#300]
I have noticed that the documents for the Foundation skin are now appearing in the footer. This has drastic SEO implications as previously they were located "above the fold" and you are telling Google they are important. By moving the documents to the footer you are saying to Google they have less value and consequently will have a rankings drop. Many of us CubeCart 5 owners would appreciate it if they where located near the top again to preserve the rankings of these URLs.

**Comment by abrookbanks** [comment]
You can make any changes you want to the skin layout. More skins will be available in the future.
