### ISSUE TITLE
Modified Contact->email_content can cause unexpected issues

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#3001]
modified language string, Contact->email_content.. if by some random chance somebody adds an additional percent symbol (as I found somebody did today) it will prevent the contact form from working entirely. 

This is due to:
`$mailer->Body = sprintf($GLOBALS['language']->contact['email_content'], $_POST['contact']['name'], $_POST['contact']['email'], $department, $enquiry);`

An exact number of parameters are passed, which causes the function to return false as an additional % character triggers the need for an additional parameter. 

Not sure this is a defect, but is certainly something that may require some improvement.

**Comment by bhsmither** [comment]
Curious to know what the inadvertent problematic `%-conversion specification` string was.

**Comment by abrookbanks** [comment]
This customer added ip address to the language string. After upgrade the code went back from:

```
$mailer->Body = sprintf($GLOBALS['language']->contact['email_content'], $_POST['contact']['name'], $_POST['contact']['email'], $department, $enquiry, get_ip_address());
```

To:

```
$mailer->Body = sprintf($GLOBALS['language']->contact['email_content'], $_POST['contact']['name'], $_POST['contact']['email'], $department, $enquiry);
```

**Comment by bhsmither** [comment]
I got caught on that elsewhere. (I forget where.)

I am going to try using Smarty to construct this email body.

**Comment by abrookbanks** [comment]
I can't really see what we can do here. Prior to PHP 8 it will return false on failure but that would need to be coded into the customised code. If the store us upgraded properly keeping the customisation it will work.
