### ISSUE TITLE
"continue shopping" and the "empty basket" tabs

### ISSUE THREAD

**Issue by harris-organic** [cubecart/v6#3002]
We have noticed that the tabs, "continue shopping" and the "empty basket" tabs disappear at the checkout on a mobile.
![image](https://user-images.githubusercontent.com/13449078/168607891-2ad4329e-5571-40bc-bcd8-d0f4309877ac.png)

![image](https://user-images.githubusercontent.com/13449078/168607977-d7fc880e-fb0e-402b-815d-f679f9eae547.png)

As increasing numbers of customers order on mobile devices, the "continue shopping" and the "empty basket" tabs would offer better customer service.

**Comment by hairy-dog** [comment]
Disappeared, or just slid below the fold?

**Comment by harris-organic** [comment]
I reckon It has slipped below the fold. 
As a pretty standard Foundation page, does anyone else see this?
The elements on google developer dont change when switching from PC to mobile.
<div class="clearfix" id="checkout_actions">  etc..

**Comment by abrookbanks** [comment]
I believe they are set to not show on small devices. The customer can remove each basket item individually and click the logo at the top of the page to return to the homepage. Obviously on small devices space is an issue.

I suppose it may be possible to solve by showing just the icon without text for home and empty basket.

I'll experiment.

**Comment by abrookbanks** [comment]
<img width="405" alt="Screenshot 2022-06-29 at 09 36 15" src="https://user-images.githubusercontent.com/4520803/176391702-15ea2199-cc0f-45bb-a5bd-ee00419564d2.png">

**Comment by harris-organic** [comment]
Thanks Al,

Will that come with 6.4.6?

**Comment by abrookbanks** [comment]
It will indeed. :) Thanks for your kind patience.
