### ISSUE TITLE
Language string not editable

### ISSUE THREAD

**Issue by hairy-dog** [cubecart/v6#3007]
I wanted to change a phrase in the checkout, to make it clearer that you need to register or log in before checkout is available. 
A quick search told me that it is checkout/reminder_unpaid_items but that doesn't appear in the list of strings in my languages/checkout section in the editor.
So I looked in the database, and there it is. No problem editing the string in the database, and after a clear cache, the page now says what I want it to. However, the previous wording is what appears in the language text search, and that string still doesn't appear in the list of editable strings.
This is freshly updated to 6.4.5 using English (UK) language. I think it's more likely that I'm doing something wrong than revealing a bug, but what?

**Comment by abrookbanks** [comment]
Good find. Thanks for this.
