### ISSUE TITLE
Per_Cat Activated When Not Needed

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3013]
In `cart.class.php`, near line 737, `Per_Category_Line` is instantiated. The `__construct()` method executes.

The value `$this->_basket['delivery_address']['country_iso']` is assigned to `$iso`.

There is a case where there may not be a 'delivery_address' available in the basket. If not, PHP complains about an undefined array key, followed by trying to access array offset on value of type null.

If there is no 'delivery_address', **suggest** not bothering the Per Category module. Line 735:
```
if (file_exists($sbc_path) && isset($ship_by_cat['status']) && $ship_by_cat['status']) {
Change to:
if (isset($this->basket['delivery_address']) && file_exists($sbc_path) && isset($ship_by_cat['status']) && $ship_by_cat['status']) {
```
Suggest also analyzing why have code here (`Cart->get()`) that involves a shipping module, instead of where all other shipping calculations are enumerated.

**Comment by bhsmither** [comment]
Somewhat related, in `cart.class.php`, lines 113 and 742 gets a value for `$tax_on`. Lines 114 and 745 tests for it's presence in `$this->basket[$tax_on]`.

But lines 896, 927, 1083 do not. PHP will complain.

**Comment by abrookbanks** [comment]
As far as I can see $tax_on should be set in those locations. Keeping an eye on the error log...
