### ISSUE TITLE
PayPal Commerce - PayPal takes priority after login but should offer standard gateway selections

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#3014]
If a store has multiple gateways, for example Print Order Form, PayPal Commerce, SagePay, WorldPay then those payment methods are offered via checkout as a selection.

If you are logged in as a customer, add items and go to checkout you are offered the choice of Gateways. 

However, if you are not logged in, add items.. go to checkout and then login you are redirected directly to index.php?_a=gateway#login which defaults to PayPal checkout only, example screen shot below:
![image](https://user-images.githubusercontent.com/10614018/172311129-e1707f94-f013-4ea0-ba35-052a935d73ef.png)

This bypasses all other gateway options, which is undesireable within a multiple gateway enabled store. 

This appears to be an issue with the PayPal Commerce module specifically. 

May be related with https://github.com/cubecart/v6/issues/3015 in some way. After I manually modified the priority I now get directed to the checkout page, but on choosing the next step in checkout it still rediects to the PayPal only checkout step.

**Comment by abrookbanks** [comment]
Does 1.6.3 fix this?
