### ISSUE TITLE
"No index used in query/prepared statement" 

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#3019]
SELECT * FROM `CubeCart_hooks` WHERE `CubeCart_hooks`.`enabled` = '1' ORDER BY `priority` ASC ;

Relates to line 446 of classes/hookloader.class.php

I can't find any fault here.

**Comment by abrookbanks** [comment]
Reproducible just by turning debug mode on.

**Comment by havenswift-hosting** [comment]
Need an index on "priority" column - any column in a WHERE, ORDER BY, GROUP BY etc needs to have an index

**Comment by abrookbanks** [comment]
You'd think... makes no difference. Changing to varchar(1)  also makes no difference.

**Comment by abrookbanks** [comment]
Urgh.. it was totally unrelated. Ignore me.. I think I need to go back to the pub.

**Comment by havenswift-hosting** [comment]
Still good to add that index though
