### ISSUE TITLE
Packaging shipping weight is not shown in the total weight with AIOS.

### ISSUE THREAD

**Issue by harris-organic** [cubecart/v6#3021]
"At the check out the packaging shipping weight is not shown in the total weight." with 1.0.24
Bsmithers quote
"In the AIOS shipping class file, the basket details are copied into the class's parameters so that the class can incorporate the total product weight, basket sub-total, and count the number of products (optionally not count digital items).

What will need to happen is for the shipping module to change the basket details adding a calculated - likely a fixed - shipping carton weight to the basket's (total) 'weight'.

What needs to be verified is, how reliable will be this new weight value. If the basket 'weight' is calculated for every page load, then the reliability should be high. But if ever the shipping class is called to recalculate shipping costs where the basket 'weight' already includes a previous shipping weight addition, then there is now two additions.

Or, the shipping class can add a separate shipping weight detail to the basket. That would require a small edit to the checkout template, admin order summary page, and the database. Not needed anywhere else because the customer never sees how the shipping charges are calculated.

And then there needs to be consideration given to how to deal with the possibility that there may be more than one shipping module enabled, each advising the basket of their respective shipping carton weights."

Further to the above, the packaging weight is used in the1.0.24 AIOS weight calculation (weight based rate), but the additional weight is not shown, in the checkout show weight option.

**Comment by hairy-dog** [comment]
In other (using other platforms) stores I maintain, the basket has a weight, which is the weight of the individual items, plus a fixed amount (a store-wide setting) plus a small percentage (also a store-wide setting) of the total weight of the products in the basket. Once set up, this works very well most of the time.

**Comment by abrookbanks** [comment]
From testing it doesn't show for any shipping extension...

**Comment by abrookbanks** [comment]
Closing for now.

**Comment by harris-organic** [comment]
Hi Al, does that mean the "feature request" label  3 weeks ago is now solved or put on the back burner for later? 
I can not see any changes to AIOS weight.

**Comment by abrookbanks** [comment]
It's on hold for now. This will be reopened when we can get to this.
