### ISSUE TITLE
FREQ - Option to exclude categories from a shipping option in AIOS

### ISSUE THREAD

**Issue by rbosma** [cubecart/v6#3022]
Would be nice to have an option in AIOS te exclude some categories from a shipping option in AIOS..
As a store wich ship out orders nationwide..
And also frozen products only in our county... 
We're having issues with customers ordering frozen products who aren't living in the county... 

Eventhoug we have a small comment in the shipping line (Don't use this if your utside the county)

**Comment by abrookbanks** [comment]
This could be a feature for all shipping extensions. Closed for now. Reopen on dev.

**Comment by havenswift-hosting** [comment]
Noodleman has a plugin which does something similar on a product by product basis - see https://www.noodleman.co.uk/link-cubecart-products-to-specific-shipping-services.html

**Comment by abrookbanks** [comment]
Great to see a solution!!
