### ISSUE TITLE
Misaligned Subjects in Italian Pack

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3024]
With respect to #3009, see also:
```
https://forums.cubecart.com/topic/57911-data-inversion-order-number-price/
```
The it-IT language pack.

**Comment by abrookbanks** [comment]
Updated with:

> `Il totale dovuto per l'Ordine numero <strong>%2$s</strong> è di <strong>%1$s</strong>`

**Comment by abrookbanks** [comment]
Thanks.
