### ISSUE TITLE
Best Sellers Box Has Stale Hide Prices Setting

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3026]
Set the store setting to "Hide prices until logged in". Clear Cache. Log out as admin.

Visit the storefront as a visitor. Note the prices are hidden.

Log in. Note the prices are visible, but for Best Sellers are still hidden.

Clear Cache (?debug-cache-clear=true). Note all prices are visible.

Log out. Note the prices are hidden, but for Best Sellers are still visible.

**Comment by bhsmither** [comment]
The situation seems to be that `GUI->_displayPopularProducts()` uses a cached array of product details if a cache file exists: `hash.popular_products.lang.cache`.

This cache file contains prices (and many other details, including which actual products are most popular at any given moment) that were relevant to the specific customer group or visitor when the details were cached immediately after having cleared the cache.

Suggest not caching popular_products.

**Comment by abrookbanks** [comment]
Thanks it seems the only option.
