### ISSUE TITLE
Best Sellers - currency not changing

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#3028]
When I change currency, products in Best Sellers box do not change currency

**Comment by tonyrsutton** [comment]
Have you tried clearing the cache within the Admin console?

**Comment by sumwonlost** [comment]
When USER change currency (front-end), everything changes except Best Sellers.  Nothing to do with clearing cache.

**Comment by bhsmither** [comment]
Duplicate of #3026.

**Comment by sumwonlost** [comment]
Thanks for bringing it to my notice, however as I said I have been away for 4 yrs and it was an issue then.  It took that long for somebody to find it?  How many CC users are there, especially those that provide hosting that one of their users did not bring it to their attention earlier?
