### ISSUE TITLE
Logout skin issues

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#3029]
Eg.  If a store has 2 skins (foundation & xyz).  In Admin, Foundation is set as main skin and allow Everyone to change skin.

In frontend, if Customer change skin to XYZ and then Login, when they logout it revert to the Foundation skin and not the skin the Customer selected (XYZ).  

It isn't a XYZ skin issue as same applies vice-versa

**Comment by bhsmither** [comment]
When the customer *logs out* (and this applies to the admin logging out as well), CubeCart *destroys* the cookie-based *session*. Thus, there is no way for CubeCart to know who is actually visiting the store. The skin the customer has chosen to see is saved as an element of the session data.

**Comment by sumwonlost** [comment]
I've been away for past 4 yrs and had no involvement with CC, I have to check but sure it was working correctly in previous versions CC5 - CC6.2.  When Customer logged out it displayed the selected skin and not default store skin.

**Comment by abrookbanks** [comment]
It did behave differently in past versions but there was good reason for this change. As far as I'm concerned it's behaving appropriately. A log out should fully log the session out.

**Comment by sumwonlost** [comment]
Assume store has 4 different skins and customer is comfortable using 1 (not default) and use it without issue whether logged out or in but when logout it reverts to default, seems stupid that they now have to change skin again.

Furthermore, if customer leave site then come back, they should come back to their selected skin.  This aspect of the cookie should not be destroyed.
