### ISSUE TITLE
SHOPPING_CART smarty variable not working correctly

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#303]
After adding an item to the basket the smarty variable "SHOPPING_CART" gets repopulated with the contents of /templates/box.basket.php

The default skin doesn't use this variable but some V5 skins do. this is a useful variable when you want to add a box to show the basket contents / prices.

However, in V6 this smarty variable isn't working correctly. After adding an item to the basket smarty is not updating the basket contents dynamically. After refreshing the page it shows the correct values.

the following code is called in gui.class.php
		$content = $GLOBALS['smarty']->fetch('templates/box.basket.php');
		$GLOBALS['smarty']->assign('SHOPPING_CART', $content);

		if (isset($_GET['_g']) && $_GET['_g'] == 'ajaxadd') {
			return $content;
		} else {
			return true;
		}

I can see the correct response in the $content variable being returned to the add call, but smarty isn't dynamically updating the values within the skin.

you can validate this in the foundation skin as well by adding the SHOPPING_CART variable to the skin.

**Comment by abrookbanks** [comment]
This variable is working fine for me. 

# Code Screenshot

![screen shot 2015-03-03 at 09 07 55](https://cloud.githubusercontent.com/assets/4520803/6459271/17b0cdce-c185-11e4-87e0-b5ff15c3d32d.png)

# Output Screenshot

![screen shot 2015-03-03 at 09 08 20](https://cloud.githubusercontent.com/assets/4520803/6459274/1e0e7a2c-c185-11e4-9656-e664ba4975a5.png)
