### ISSUE TITLE
Coupon Maxed Out at Checkout Error Clarification

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3031]
When a coupon has reached its overall maximum usage, and when the coupon has been used for the maximum number of times per customer, the error message is the same.

Suggest that the phrase,
```
"Sorry, but you, personally, are no longer permitted to use this code again."
```
Or,
```
"Sorry, but that code has been used to it's maximum <em>per-user</em> allowance."
```

**Comment by abrookbanks** [comment]
Thanks for this.
