### ISSUE TITLE
Per-User Coupon Not Specified When Checking for Previous Usage

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3032]
See:
https://forums.cubecart.com/topic/57956-coupon-limit-per-customer-apparently-counting-before-checking/

CubeCart queries for records from `CubeCart_customer_coupon`, requesting the `used` value, where the `email` or `customer_id` matches the logged in customer.

The problem here is that the query does not specify *which* coupon is being tested for. Thus, if the customer has used *any* coupon previously, there will be a record of it - a false positive of testing for *this specific* coupon.

In the file /classes/cart.class.php, near line 541, find:
```
$usage = $GLOBALS['db']->select('CubeCart_customer_coupon', array('used'), "`email` = '$email' OR `customer_id` =  ".(int)$customer_id, false, 1, false, false);
```
Suggest:
```
$usage = $GLOBALS['db']->select('CubeCart_customer_coupon', array('used'), "`coupon` = '$code' AND (`email` = '$email' OR `customer_id` =  ".(int)$customer_id.")", false, 1, false, false);
```

**Comment by abrookbanks** [comment]
Excellent. Thank you!
