### ISSUE TITLE
"Authorize.net Accept Hosted" - Uncaught SyntaxError: Invalid or unexpected token (at payment:24:842)

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#3033]
As part of building the checkout form, var g_pageOptions pulls in the store name.

However, should the store name contain quotes... for example Chris' then this Gateway does not work.

Special characters / quotes need to be handled, currently they are not.

**Comment by abrookbanks** [comment]
Where is `var g_pageOptions`? I searched but I can't find it.

**Comment by Noodleyman** [comment]
In the JS via checkout. add a single quote to the store name.

then go via checkout. The form itself won't load properly, it's on that page in the souce.

**Comment by Noodleyman** [comment]
as in... go rought through the checkout process to the step that should take payment. that form is unable to load.

**Comment by abrookbanks** [comment]
Thanks for this. It's fixed with 1.0.8.

**Comment by Noodleyman** [comment]
Cheers :)
