### ISSUE TITLE
Better Logical Expression

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3037]
In `cubecart.class.php`, near lines 1199-1209, the logical expressions might not evaluate to what is wanted.

There is: `A && B || C`. `A` can falsify `A && B`, but PHP will still attempt to evaluate `C`, and in so doing will complain that `$this->_basket['billing_address']['estimate']` is accessing an offset on null.

Suggest: `A && (B || C)`.
```
if (isset($this->_basket['billing_address']) && ($this->_basket['billing_address']['user_defined'] || $this->_basket['billing_address']['estimate']) ) {
```

**Comment by abrookbanks** [comment]
Good find. Thank you.
