### ISSUE TITLE
payment gatways no longer working after update 

### ISSUE THREAD

**Issue by tvvault** [cubecart/v6#3038]
when customers pay and select card it now comes up with 

Many thanks for your order! The order status is currently pending but it will automatically update to processing once payment is confirmed. Normally this is automated and will happen within the hour but please do contact us if you require more information.

with no option to even pay by stripe

**Comment by tvvault** [comment]
even the text is now missing Pay with Debit and Credit Card

**Comment by tvvault** [comment]
update after a few tests ALL payment gateways are not working tried them all 

when customer hits secure checkout they are kicked straight to pending offering no payment gateways at all

**Comment by tvvault** [comment]
does not fix it at all please note your update has now killed my shops earnings

**Comment by abrookbanks** [comment]
@tvvault - I'd suggest restoring a backup until the new release is ready.
