### ISSUE TITLE
Duplicated Modules

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3039]
Somewhere not yet found, when bringing up a module for editing the settings, a new instance of the record appears in the database table `CubeCart_modules` when the settings are saved.

(This may be the cause of #3038. Nope. It's not. Well, maybe. I had to clear the cache.)

**Comment by bhsmither** [comment]
An edit made for CC646 in /classes/module.class.php, near line 454, there is:
```
if(isset($xml->info) && is_array($xml->info)) {
```
At this point in the code, `$xml->info` is not an array, but rather an XML object.

Therefore, the population of `$this->_info` does not happen and all sorts of mayhem ensues.

Suggest:
```
            if(isset($xml->info)) {
                foreach ((array)$xml->info as $key => $value) {
                    $this->_info[$key] = (string)$value;
                }
            }
```

**Comment by bhsmither** [comment]
Also, in this file, at line 41, suggest:
```
    private $_info   = array();
```

**Comment by bhsmither** [comment]
The store admin will need to use an external database utility to delete the duplicate rows in the database table `CubeCart_modules`.

**Comment by tvvault** [comment]
i have done the changes and still the same problem please fix this 

please bear in mind that when you release something to public and break my cubecart it affects my livlyhood

**Comment by tvvault** [comment]
when the customer goes to checkout the Choose Payment Method is now blank with nothing to show therefore every cutsomer who has visited my site cannot pay for anything since this update

**Comment by ahrwh** [comment]
Having the same problem.

**Comment by abrookbanks** [comment]
> please bear in mind that when you release something to public and break my cubecart it affects my livlyhood

We've had to make significant updates to get CubeCart working with PHP 8. Sadly often bugs only come to light with real world testing. This is one of those cases. Fortunately this is a full time business and we are working on this on a Sunday.

It will be promptly patched and fixed most likely tomorrow.

**Comment by abrookbanks** [comment]
SimpleXMLElement is returning a different data structure with PHP 8 as far as I can see. Reiterating though the returned XML object is not the same now!

**Comment by abrookbanks** [comment]
Any XML value with `<![CDATA[ ]]>` wrapper is handled differently. This could be a PHP bug...

**Comment by abrookbanks** [comment]
See this example form the free shipping config xml file. The CDATA values are returned as empty objects.
```
<installer version="1.0">
  <info>
	<uid>shipping-Free_Shipping@cubecart.com</uid>
	<type>shipping</type>
	<name><![CDATA[Free_Shipping]]></name>
	<description><![CDATA[Free Shipping Module]]></description>
	<version>1.0.0</version>
	<minVersion>5.0.0a</minVersion>
	<maxVersion>5.1.*</maxVersion>
	<creator><![CDATA[CubeCart]]></creator>
	<homepage><![CDATA[http://www.cubecart.com]]></homepage>
	<block>false</block>
  </info>
</installer>
```
```
object(SimpleXMLElement)#36 (2) {
  ["@attributes"]=>
  array(1) {
    ["version"]=>
    string(3) "1.0"
  }
  ["info"]=>
  object(SimpleXMLElement)#37 (10) {
    ["uid"]=>
    string(35) "shipping-Free_Shipping@cubecart.com"
    ["type"]=>
    string(8) "shipping"
    ["name"]=>
    object(SimpleXMLElement)#39 (0) {
    }
    ["description"]=>
    object(SimpleXMLElement)#40 (0) {
    }
    ["version"]=>
    string(5) "1.0.0"
    ["minVersion"]=>
    string(6) "5.0.0a"
    ["maxVersion"]=>
    string(5) "5.1.*"
    ["creator"]=>
    object(SimpleXMLElement)#41 (0) {
    }
    ["homepage"]=>
    object(SimpleXMLElement)#42 (0) {
    }
    ["block"]=>
    string(5) "false"
  }
}
```

**Comment by abrookbanks** [comment]
Please find patch above. Please make the code amendments and run the following SQL query:

```
DELETE FROM `CubeCart_modules` WHERE `module` = '';
```

**Comment by abrookbanks** [comment]
@tvvault 

> when the customer goes to checkout the Choose Payment Method is now blank with nothing to show therefore every cutsomer who has visited my site cannot pay for anything since this update

This is a different issue. Please see https://github.com/cubecart/v6/issues/3045

**Comment by ahrwh** [comment]
No problem, Al. I know and trust the dedication of you and your team. And I think you know that the “please bear in mind…” comment below was not from me.

 

Bill Ahrens

**Comment by bhsmither** [comment]
"SimpleXMLElement is returning a different data structure with PHP 8"

I cannot concur. The language files are still loading.

**Comment by abrookbanks** [comment]
> "SimpleXMLElement is returning a different data structure with PHP 8"
> 
> I cannot concur. The language files are still loading.

Well it does seem to be but I totally see where you are coming from. I had to add flags to the class constructor to get the CDATA libs to load. The patches work well but I may have overlooked something else.
