### ISSUE TITLE
Call to Member on a Non-Object

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#304]
\classes\seo.class.php on line 726
`if($GLOBALS['cache']->read($cache_id)) {`

Here is an XDEBUG trace:
```
1. {main}() L:\WebServer\htdocs-CC600b6\index.php:0
2. include() L:\WebServer\htdocs-CC600b6\index.php:20
3. SEO::getInstance() L:\WebServer\htdocs-CC600b6\controllers\controller.index.inc.php:48
4. SEO->__construct() L:\WebServer\htdocs-CC600b6\classes\seo.class.php:305
5. Debug->__destruct() L:\WebServer\htdocs-CC600b6\classes\debug.class.php:0
6. Debug->display() L:\WebServer\htdocs-CC600b6\classes\debug.class.php:138
7. currentPage() L:\WebServer\htdocs-CC600b6\classes\debug.class.php:318
8. SEO::getInstance() L:\WebServer\htdocs-CC600b6\includes\functions.inc.php:234
9. SEO->__construct() L:\WebServer\htdocs-CC600b6\classes\seo.class.php:305
10. SEO::_checkModRewrite() L:\WebServer\htdocs-CC600b6\classes\seo.class.php:92
```
It seems that, during shutdown, Debug->display() wants to get the current page. But several classes have already been destroyed. The function currentPage() calls SEO - which has already been destroyed - so when SEO is getting instantiated again, SEO::_checkModRewrite is called which calls for Cache...

Boom!

**Comment by bhsmither** [comment]
I do not (yet) know how the program flow went from step 4 to step 5.

**Comment by abrookbanks** [comment]
I have no clue how to fix this.

**Comment by abrookbanks** [comment]
I can't reproduce this at all. Do you know a way to reliably reproduce this?
