### ISSUE TITLE
No Such Variable

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3042]
Minor:

In `cubecart.class.php`, near line 1751, a reference is made to `$data['tax_inclusive']` which may not exist.

Suggest:
```
if (!empty($data['tax_inclusive'])) {
```

**Comment by bhsmither** [comment]
In `tax.class.php`, depending on `productTax` argument `$tax_inclusive`, near line 106, either `$this->_tax_table_inc[$tax_id]` or `$this->_tax_table_add[$tax_id]` may not exist.

Suggest:
```
$taxes[$tax_name]['value'] = $taxes[$tax_name]['value']??0 + (float)($this->_tax_table_inc[$tax_id]??0+$this->_tax_table_add[$tax_id]??0)*$this->_adjust_tax;
```

**Comment by abrookbanks** [comment]
Thanks!
