### ISSUE TITLE
Code Check: Unset Variable

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3043]
Minor:

In `CubeCart->_listPaymentOptions()`, lines 2292-2293, suggest they are coded the same as the (semi-deprecated) `CubeCart->_displayGateways()`, lines 2036-2037.

**Comment by bhsmither** [comment]
Also, in `Order->orderStatus()`, in the `case self::ORDER_PROCESS`, the variable `$complete` comes into existence only here.

Near the end of the method, there is a test for `$complete` which will not exist for any other case.

Suggest:
```
            // Set status to complete if it is digital only
            if (!empty($complete)) { // isset and true-like
```

**Comment by abrookbanks** [comment]
> status to complete if it is digital

This part seems to be fixed already.

```
if (isset($complete) && $complete) { 
``` 

> Minor:
> 
> In `CubeCart->_listPaymentOptions()`, lines 2292-2293, suggest they are coded the same as the (semi-deprecated) `CubeCart->_displayGateways()`, lines 2036-2037.

I believe this may be resolved already. I see no `unset` in this function. Please let me know if I am mistaken and I can reopen.
