### ISSUE TITLE
$_SERVER and $_ENV Arrays or Their Elements May Be Not Set

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3044]
See:
```
https://odd.blog/2015/02/12/php-notice-undefined-variable-_server-in/
```
I was tracking down some very odd error messages and discerned that some or all of the $_SERVER array was not set.
```
Undefined array key "HTTP_USER_AGENT"
```
and numerous others.

I do not know what CubeCart can do to get these variables "just-in-time" set. I would think using them as arguments to a function would do it, but apparently not. (re: `Session->_http_user_agent()`)

They are read in `ini.inc.php` -- so I don't know what is going on.

Just something you might want to add to your list of troubleshooting tips.

Personally, I created a `.user.ini` file.

**Comment by abrookbanks** [comment]
Thanks Brian. This is one I'll keep an eye on for now. I don't think a .user.ini file will work as many merchants will already have customised ones unless it checks for one first and can write to it or give a warning to add this.

**Comment by bhsmither** [comment]
I think I narrowed the source of what causes the `Undefined array key "HTTP_USER_AGENT"` message.

I use the "Payment Test Gateway" which makes a CURL post to `_g=rm&type=gateway&cmd=process&module=Payment_Test_Gateway`.

The CURL post does not include setting the HTTP_USER_AGENT header item (or *any* header item).

**Comment by abrookbanks** [comment]
I see. So cURL doesn't set the HTTP_USER_AGENT so it never gets set but of course a browser does.

I guess the question lies if we should build a CubeCart user agent into the request class. 

e.g. CubeCart/6.4.7 (Apache/2.4.54 (Unix) OpenSSL/1.1.1q PHP/7.4.32)

```
'CubeCart/'.CC_VERSION.' ('.$_SERVER['SERVER_SOFTWARE'].')';
```

**Comment by abrookbanks** [comment]
Let me know how this goes. I don't think we need the `$_SERVER['SERVER_SOFTWARE']` bit.

**Comment by abrookbanks** [comment]
Closing for now as assuming I've understood correctly this should solve it.
