### ISSUE TITLE
Code Check: Stripe Gateway

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3046]
Looking at v3.0.7:

In the module file /skin/checkout.php, near line 5, there is this **part** of the line:
```
index.php?_g=rm&type=plugins
```
In the module file `gateway.class.php`, near line 135, there is the same thing.

The Stripe module is located, according to the `config.xml` file,  in the `/modules/gateway/` folder.

**Comment by abrookbanks** [comment]
Thanks Brian. Fixed in 3.0.9.
