### ISSUE TITLE
Stripe Module vs. Stripe's Latest API

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3050]
According to:
```
https://stripe.com/docs/upgrades#2022-08-01
```
there is no longer any data referencing a `'payment_intent'` when initially creating a session. In the `gateway.class.php` file:
```
$session = $stripe->checkout->sessions->create($session_data);
$stripe->paymentIntents->update($session['payment_intent'],array('description' => 'Payment for order '.$order['cart_order_id']));
```
where `$session['payment_intent']` is _null_, causing an exception to crash PHP later:
```
/Stripe/stripe-php-7.83.0/lib/Service/AbstractService.php->buildPath()
```
Suggest any of three solutions:
1. Comment/Remove the `$stripe->paymentIntents->update()` statement in the gateway class file,
2. Give critical instruction in the module's admin settings to choose a specific API version (2020-08-27) in their Stripe Merchant Account Dashboard page,
3. Have the module send a special Header specifying the API version to use.
```
2. https://stripe.com/docs/upgrades#api-versions
3. https://stripe.com/docs/api/versioning
```

**Comment by abrookbanks** [comment]
Thanks. This has been fixed with 3.0.8. Testing checkout and elements with success.
