### ISSUE TITLE
Null For Type String

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3051]
In `Database->update()`, the supplied argument `$record` may contain an element with a value of _null_.

If so, PHP complains that using _null_ for argument type _string_ is deprecated in `substr()`.

Suggest:
```
foreach ($record as $field => $value) {
    if (in_array($field, $allowed) && !is_numeric($field)) {
        if (($number = substr((string)$value, 1)) && is_numeric($number) && $skip_math_fields!== 'all' && !in_array($field, $skip_math_fields) && isset($value[0]) && ($value[0] == '+' || $value[0] == '-')) {
```
One might also worry about UTF character strings -- and use `mb_substr()` -- but here, the code is only interested in:
```
(+|-)[numeric]
```

**Comment by bhsmither** [comment]
In `Mailer->loadContent()`, the default value for the argument `$language` is _null_.

PHP complains that using _null_ for argument type _string_ is deprecated in `preg_match()`.

Suggest:
```
public function loadContent($content_type, $language = '', $data = false, $default = false, $panic = false)
```

**Comment by abrookbanks** [comment]
Thanks Brian. All seems good but more testing will come.
