### ISSUE TITLE
PPCP - Under PHP 8.1 throws thousands of warnings

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#3052]
The changes needed for core for 8.1 are likely going to be needed for all plugins - for example PayPal Commerce under 8.1 throws huge numbers of notices, warnings etc into the PHP error_log

**Comment by bhsmither** [comment]
Any sense of how many are **not** 'Undefined variable' and 'Undefined array key' for PayPal Commerce?

**Comment by havenswift-hosting** [comment]
Nope - deleted the 9MB with several hundred thousands lines added to the error_log file created in a few hours and downgraded client back to 7.4

**Comment by claudia39** [comment]
I saved a compressed file of the error log when it was at about 24000 lines.  Do you want me to email it to you Brian?  Also sinceI've been put back to PHP 7.4 I've gotten a few PayPal warnings.  Should I send you those too?
Claudia

**Comment by bhsmither** [comment]
If the error_log relates to the PayPal module (or any other module), then yes. Otherwise, because I have been working through the core code with PHP8.1, I won't find much that I haven't already reported.

So, yes, email it to me.

**Comment by claudia39** [comment]
And here are the errors I got today 
[30-Aug-2022 03:32:10 America/Louisville] PHP Warning:  Undefined global variable $cart in /home/claudias/public_html/modules/plugins/paypal_commerce/paypal.class.php on line 435
[30-Aug-2022 03:32:10 America/Louisville] PHP Warning:  Attempt to read property "basket" on null in /home/claudias/public_html/modules/plugins/paypal_commerce/paypal.class.php on line 435
[30-Aug-2022 03:32:10 America/Louisville] PHP Warning:  Trying to access array offset on value of type null in /home/claudias/public_html/modules/plugins/paypal_commerce/paypal.class.php on line 435
[30-Aug-2022 03:32:10 America/Louisville] PHP Warning:  Undefined variable $disable_funding in /home/claudias/public_html/modules/plugins/paypal_commerce/paypal.class.php on line 697
[30-Aug-2022 06:24:53 America/Louisville] PHP Warning:  Invalid Security Token in /home/claudias/public_html/classes/sanitize.class.php on line 155

**Comment by claudia39** [comment]
Did you get the attachment?

**Comment by bhsmither** [comment]
Nothing sent directly to me from you.

**Comment by bhsmither** [comment]
I haven't found anything that screams "Fix me now!" that hasn't already been made an issue.

A lot of log entries (again, these errors are not important) can be quieted with this:
https://github.com/smarty-php/smarty/issues/789

**Comment by abrookbanks** [comment]
Yes it needs an update but from my testing works fine on PHP 8.1. I'll get around to this asap.

**Comment by abrookbanks** [comment]
Hi @bhsmither 

Are you working on this one? I don't want to step on your toes if so. Let me know if not and I'll jump on this. Happy to take this on if you want to share findings so far?

**Comment by bhsmither** [comment]
I am not.

**Comment by abrookbanks** [comment]
Ok thanks. I'm not sure how I got the impression you were.

**Comment by bhsmither** [comment]
These are the errors that were logged in an error report sent to me that relate to PPCP:
```
Undefined global variable $cart in /paypal_commerce/paypal.class.php on line 435
Attempt to read property "basket" on null in /paypal_commerce/paypal.class.php on line 435
Trying to access array offset on value of type null in /paypal_commerce/paypal.class.php on line 435
Attempt to read property "server_response_code" on string in /plugins/paypal_commerce/paypal.class.php on line 972
Undefined variable $disable_funding in /paypal_commerce/paypal.class.php on line 697
Undefined variable $placement in /paypal_commerce/hooks/class.gui.head_js.php on line 57
Undefined global variable $_GET in /paypal_commerce/hooks/class.gui.head_js.php on line 13
Trying to access array offset on value of type null in /paypal_commerce/hooks/class.gui.head_js.php on line 13
Undefined global variable $_GET in /paypal_commerce/hooks/class.gui.head_js.php on line 33
Trying to access array offset on value of type null in /paypal_commerce/hooks/class.gui.head_js.php on line 33
Undefined global variable $_GET in /paypal_commerce/hooks/class.gui.head_js.php on line 86
Trying to access array offset on value of type null in /paypal_commerce/hooks/class.gui.head_js.php on line 86
Undefined array key "digital_only" in /paypal_commerce/paypal.class.php on line 1099
Undefined array key "delivery_address" in /paypal_commerce/paypal.class.php on line 1102
Trying to access array offset on value of type null in /paypal_commerce/paypal.class.php on line 1102
Undefined array key "billing_address" in /paypal_commerce/paypal.class.php on line 1110
Trying to access array offset on value of type null in /paypal_commerce/paypal.class.php on line 1110
Undefined array key "shipping" in /paypal_commerce/paypal.class.php on line 1082
Trying to access array offset on value of type null in /paypal_commerce/paypal.class.php on line 1082
```

**Comment by abrookbanks** [comment]
Thanks.

**Comment by abrookbanks** [comment]
Your version of PayPal Commerce must be out of date as I can't match up most of these errors.

**Comment by havenswift-hosting** [comment]
It was running the latest version at the time

**Comment by abrookbanks** [comment]
1.7.2 released which should catch most if not all. If you do find more let me know.
