### ISSUE TITLE
PHP8: Order Class vs. Payment Gateways

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3057]
Now, for PHP8, what was a Notice is now an Exception. See:
```
https://forums.cubecart.com/topic/58033-set-order-to-processing-then-nothing/
```
While in admin (manually moving an order to Processing, for example), the Cart class has not been instantiated.

Moving an order to Processing, a call is made (at orders.index.inc.php, line 208) to `$order->orderStatus()`.

In `orderStatus()`, `Gateway` is instantiated (line 503).

In (almost) all gateways, in `__construct()`, the class wants to fetch _by reference_ `$GLOBALS['cart']->basket`.

PHP8 now issues a Warning that `'cart'` is an unknown index, and also throws an Exception because of wanting to work directly on `basket` as a property of something that doesn't exist.

The solution would seem to involve a fix **in every module** that wants the Cart class, to test for its existence first.

Or perhaps, because at this point in the Order class code there is a trivial test/call for `Gateway->processingEmail()`, such that a phantom object can be used:
```
if (!isset($GLOBALS['cart'])) {
  $GLOBALS['cart'] = (object) array('basket' => array()); // phantom object
  $cart_is_phantom = true;
}
... // do Gateway->processingEmail()
if ($cart_is_phantom) unset($GLOBALS['cart']); // don't need this anymore
```

**Comment by abrookbanks** [comment]
Thanks for this. It's a sensible work around.

**Comment by bhsmither** [comment]
I am questioning the placement of this new code.

If the solution is to have a phantom object ready **before** the Gateway class runs its constructor, then the new code should be **before** the `new Gateway()` statement.

**Comment by abrookbanks** [comment]
Sorry but I'm completely lost with this. Can you suggest a change?

**Comment by bhsmither** [comment]
Perhaps we can now exclusively rely on #3140, and not implement this phantom cart idea.

**Comment by abrookbanks** [comment]
Good point!
