### ISSUE TITLE
PHP8 Deprecated: Null for Type String

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3058]
In `orders.index.inc.php`, near line 307, there is _this part_:
```
str_replace('-', '', $summary[0]['ship_date'])
```
The 'ship_date' column has a default `null` for data type `DATE`.

Suggest either a default string of '0000-00-00' (see CubeCart_coupons), or:
```
str_replace('-', '', $summary[0]['ship_date']?:"0")
```

**Comment by abrookbanks** [comment]
Thanks
