### ISSUE TITLE
Address Book Question

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#306]
When showing the list of addresses of the "Your Address Book", there are the three columns:
Billing Address
Delivery Address
Delivery Address (Default)

The database records which one (and only one) of these is the `billing` address, and which one (and only one) is the `default` delivery address.

The list of addresses shows *every* address as a Delivery Address - so why have that column anyway? Future Expansion? Template lines 38-40 have a hard-coded checkmark.

If future expansion, one can assume any other address is a viable delivery address -- except the record holding the `billing` address. This record *might* be a delivery address - not guaranteed.

Also, in cubecart.class.php, line 451:
`$_POST['description'] = $GLOBALS['language']->account['billing_address'];`
There is no 'billing_address' key in the "account" group. Perhaps the "address" group?

Maybe fix the language key, but then rethink the logic. Why, with a POSTing with a missing 'description' field, default to describing it as a "Billing Address"?

**Comment by abrookbanks** [comment]
I think the logic behind having the "Delivery Address" column is so that they know it can be used as delivery address. I appreciate its not truly necessary but I think it lays everything on the table.

**Comment by abrookbanks** [comment]
I see where you are coming from about cubecart.class.php (line 451) but the address description is required. This is really just an emergency fallback if JS is disabled in the browser. Being purest it should only have Billing Address if its not set as a delivery address. 

![screen shot 2015-03-03 at 09 59 53](https://cloud.githubusercontent.com/assets/4520803/6460075/1119bc44-c18c-11e4-866d-6e0601db3836.png)

**Comment by abrookbanks** [comment]
Added the following logic..

```
if($_POST['billing']==1 && $_POST['default']==1) {
	$_POST['description'] = $GLOBALS['language']->address['billing_delivery_address'];
} elseif($_POST['billing']==1) {
	$_POST['description'] = $GLOBALS['language']->address['billing_address'];
} elseif($_POST['default']==1) {
	$_POST['description'] = $GLOBALS['language']->address['delivery_address'];
} else {
	$_POST['description'] = $GLOBALS['language']->address['extra_address'];
}
```
