### ISSUE TITLE
Search Returns Page 1 Results Regardless of Specified Page Number in Certain Cases

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3066]
In `Catalogue->searchCatalogue()`, if the fulltext mode cannot be used because of word(s) that are shorter than `$max_word_len`(*), line 1907 calls `searchCatalogue()` with rlike and the specified `$page` number.

If the fulltext mode returns nothing (`$search = false`), line 1942 calls `searchCatalogue()` with rlike but **NOT** with the specified `$page` number, rather with `$page=1`.

If the rlike mode returns nothing (`$search = false`), line 1999 calls `searchCatalogue()` with like but **NOT** with the specified `$page` number, rather with `$page=1`.

**Comment by abrookbanks** [comment]
Thanks.

**Comment by bhsmither** [comment]
No!

The solution is to pass along the page number at lines 1942 and 1999 by using `$page`.

If the customer is wanting page 3 (directly as from a pagination series), lines 1942 and 1999 would force the customer to page 1 -- for all time.

**Comment by abrookbanks** [comment]
But the whole point of those lines of code are to change the search method and thus back to page one is it not?? It would be on page one anyway so this isn't even necessary.

**Comment by bhsmither** [comment]
The **entire three-step search process** is performed _for each search request_: fulltext->rlike->like.

First, the customer requests page 1 (by default). Fulltext finds nothing, line 1942 recurses to use rlike for a page=1 LIMIT X OFFSET Y recordset, and RLIKE does find results.

Then, after having viewed page 1 results and **going to page 2**, fulltext finds nothing (again), but line 1942 recurses to use rlike for a page=1 LIMIT X OFFSET Y recordset -- not a page=2 LIMIT X OFFSET Y recordset.

The same for line 1999.

**Comment by abrookbanks** [comment]
I disagree. It's supposed to try FULLTEXT if that fails it tries RLIKE and if that fails LIKE. It's not supposed to continue searching from the current page for different methods.
