### ISSUE TITLE
Gift Cards - SEO

### ISSUE THREAD

**Issue by harris-organic** [cubecart/v6#3069]
For Gift Cards 
1. Allow images to be placed on the gift card page. Selected images do not show in 6.4.7.
2. Add Image alt and title tags
3. Add a description tab to allow easy editing of content on the Gift card page

**Comment by abrookbanks** [comment]
I'm not sure #3 is needed because the existing text can be edited in the admin control panel. 
<img width="1175" alt="Screenshot 2022-11-18 at 14 51 35" src="https://user-images.githubusercontent.com/4520803/202732660-3b11489d-945a-4f9e-a235-f70e7c743cc2.png">

**Comment by bhsmither** [comment]
Points 1 and 2 should be solved in other issues.
I am working on a feature enhancement that will assign multiple images to the GiftCard system, allowing the customer to choose from among the images which image is wanted to be applied to the GiftCard email and physical card. (As well as a content editor for additional page content.)

**Comment by harris-organic** [comment]
#3.
Editing phrases is not suitable for SEO. ie adding H2 tags etc. Please allow editing in a description tab.

In CC649 I can add an image, however, the image does not show up at the checkout. Can someone confirm this?

Looking forward to seeing multiple images.

**Comment by abrookbanks** [comment]
Probably due to custom or ported skin. Only the core foundation skin will have been patched.
