### ISSUE TITLE
Adding tax rule to "EU" group does not include all EU countries

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#307]
My store is configured in the UK, when adding tax rules for the EU countries group it did not include "UK" in the added country list.

Some other countries are also missing when directly compared with the list found here:
https://www.gov.uk/vat-eu-country-codes-vat-numbers-and-vat-in-other-languages

**Comment by abrookbanks** [comment]
Thanks Alec. 

This failed:
````
UPDATE `CubeCart_geo_country` SET `eu` = 1 ...
````

This works:
```
UPDATE `CubeCart_geo_country` SET `eu` = '1' ...
```
