### ISSUE TITLE
Social Login

### ISSUE THREAD

**Issue by feagle1991** [cubecart/v6#3070]
hello ,
is there any possibility for social login ? it's handy nowadays

**Comment by hairy-dog** [comment]
Handy so that shoppers can be tracked across every place they visit? 
Social login is for cretins. So of course it's popular.

**Comment by abrookbanks** [comment]
PayPal Commerce allows for quick checkout with PayPal login so I suppose we check one of these boxes already. It would be good however to see more choices.
