### ISSUE TITLE
Currency Update to be in a Class

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3071]
Currently, obtaining and setting currency exchange rates happen during setup (setup.install.php line 272) and in admin (settings.currency.inc.php line 22).

Request that this functionality be put in a class. Suggest the CubeCart class. Or maybe in the functions.inc.php file.

This allows for a hook to be used from a cron job call to get the exchange rates updated on a set schedule.

The cron job call would be something like:
```
index.php?_g=currency_update&access=123456
```
where the hook `class.cubecart.construct.g_switch` would check for the correct access code, request the rate file, update the database, and exit.

Or maybe not use a hook at all, but establish a permanent `_g` method.

**Comment by abrookbanks** [comment]
e.g. ?_g=cron&_m=updateExchangeRates

**Comment by abrookbanks** [comment]
<img width="1034" alt="Screenshot 2022-11-16 at 14 32 31" src="https://user-images.githubusercontent.com/4520803/202208178-60f176bf-a792-4880-8e7c-a57ddb52949a.png">

**Comment by abrookbanks** [comment]
Closing for now. This is quite powerful already. If you can think of any available tasks to add let me know.
