### ISSUE TITLE
Add ability to edit meta information to images such as alt tag & title tag

### ISSUE THREAD

**Issue by harris-organic** [cubecart/v6#3072]
Add the 
![title-alt-tags](https://user-images.githubusercontent.com/13449078/197395943-24d42338-f85a-41e6-b4f3-ef8f9a47d68f.PNG)
ability to edit meta information to images such as alt tag #353.
I refer to #353, however, in version 6.4.7, I can not find a way of changing or inserting alt tags and title tags for images.

On category pages, the alt tag on the main image is linked to the page title and there is no title tags.
on my product pages, there is no image title or title tags.

A feature request for 6.5.0?

**Comment by havenswift-hosting** [comment]
This would be a useful addition for all images. Our own skins allow the addition of alt and title tags (and variable position on the homepage) for slideshow images but being able to do it for all images would be great

**Comment by bhsmither** [comment]
Just personal curiosity: what would you want the `alt` and `title` attributes for the image shown above to say?

**Comment by harris-organic** [comment]
Its all about SEO. Here is an overview of what alt tags do for SEO. https://blog.hubspot.com/marketing/image-alt-text.

**Comment by bhsmither** [comment]
Just FYI: it seems a good chunk of the code to add custom title and description data has been added via the recent feature of 'streamable' media (#2611).

So, this could be easier than anticipated.

**Comment by abrookbanks** [comment]
Yes we can add these extra fields. Skin changes will be required. I'll have a look into this.

**Comment by hairy-dog** [comment]
It's NOT all about SEO. It's about accessibility. 

An alt tag is supposed to describe the image for someone who can't see it. 

A title is meant to explain the purpose of the object and destination of a link for someone who can't see the context. 

The SEO benefit derives from better accessibility.

**Comment by abrookbanks** [comment]
Yes indeed. :)

**Comment by abrookbanks** [comment]
This is work in progress. The back end is done with a number of improvements such as image preview, update feedback and file name validation. Changing the extension isn't prohibited. It was possible to rename without an extension before. Definitely a bug.

<img width="1415" alt="Screenshot 2022-11-15 at 13 13 23" src="https://user-images.githubusercontent.com/4520803/201928653-3db8d795-dd1a-4ce0-86a8-291203f72233.png">

**Comment by abrookbanks** [comment]
I'll reopen if there is feedback/bugs found.

**Comment by harris-organic** [comment]
Hi Al, which skin files need to be updated to have this feature, please?

**Comment by bhsmither** [comment]
Practically every Foundation file that shows images.

Please click the links above - "Proposed Solution" and "Subcategory alt/title tags" - for the difference page where, on the left panel is a list of all files affected. Of interest, for you, are the Foundation skin files.

Also, pay attention to #3126 which fixes a syntax error in one of the Foundation skin files.
