### ISSUE TITLE
$DATA.gateway in admin emails is NULL most of the time

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#3077]
Had a customer request the DATA.gateway be added to email templates to admins so they know if they need to chase for a bank payment. However, in testing it appears that _most of the time_ when the mail is sent the gateway value is NULL when the mail is sent, but the correct Gateway is set in the database CubeCart_order_summary table. 

You can test by adding this field to the mail template HTML, placing an order, then reviewing the mail log. Repeat the process a few times.

I've tested with cache on and off just in case, but same result.

**Comment by abrookbanks** [comment]
Thanks Alec I'll give this a go.

**Comment by abrookbanks** [comment]
Hi Alec, I set the order status for admin order notifications to "pending" and placed a test order. I edited the email template for order notification to put {$DATA.gateway} at the top and it did populate.

<img width="558" alt="Screenshot 2022-11-15 at 08 48 19" src="https://user-images.githubusercontent.com/4520803/201873056-a1b8a530-466d-4b39-b229-0bc53a741761.png">

I think the issue may concern if there is either only payment gateway or if the skin in use doesn't allow for the chosen payment method on checkout. Can you reproduce this with the default skin? I fear without the "choose payment option" on checkout the value may not get populated.

**Comment by abrookbanks** [comment]
Yes I think this may be the option. The solution may be to add this block of code:
https://github.com/cubecart/v6/blob/v6.4-master/skins/foundation/templates/content.checkout.php#L36-L56 

This will post the chosen payment method to the basket data which then gets saved to the order_summary table.

**Comment by abrookbanks** [comment]
Hmmm.. the code to `Order::getInstance()->placeOrder();` is triggered when the gateway parameter isn't set. 

Messing with that is likely to cause an upset so I'd recommend adding the linked to code on my last response to the checkout process. That should get it behaving as you want.

**Comment by abrookbanks** [comment]
Closing but happy to reopen with feedback.
