### ISSUE TITLE
Initial Preview Image Overlays Master Image in FilePicker

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3083]
When the Images tab content is first shown, the `preview_image` sub-block is being displayed on top of the `master_image_block`.

Not allowing the mouse cursor to hit any of the FilePicker filenames, view the Images tab (of a **Product**, **Category**, or **Gift Certificate**).

Right-click on the **Main Image** image and select Inspect Element (or similar). This will bring up the browser's Developer Tools with the relevant code highlighted. Note that `preview_image` is being displayed.

The `<img>` in the `preview_image` block does not have a `title` attribute. (Why would it? You would be hovering over the filename.)

Thus, with the `preview_image` block initially showing the `master_image`, there is no `title` attribute to show.

Only after hovering over a filename then moving out, will the javascript cause the `preview_image` to no longer display, allowing the `master_image` to show along with its `title` attribute.

Suggest that the `<img>` in the `preview_image` block be coded to have `style="display:none;`, relying on the javascript to display it, or not, as required. This allows the `master_image` in the `master_image_block` to show, along with its `title` attribute, initially.

**Comment by abrookbanks** [comment]
> When the Images tab content is first shown, the preview_image sub-block is being displayed on top of the master_image_block.

Is it? Sorry I'm lost with this one. How do I reproduce it? 

<img width="1088" alt="Screenshot 2022-12-05 at 13 54 37" src="https://user-images.githubusercontent.com/4520803/205654269-9662a387-8660-4a78-be7e-0fdfded0e71b.png">

**Comment by bhsmither** [comment]
Upon reaching the Images tab, **do not allow the mouse cursor to move across the File Picker file list**, rest the mouse cursor on the image of the person sitting in the "Other included images" area.

Note that there will be a tool-tip showing the path where this image can be found.

Now, again, **do not allow the mouse cursor to move across the File Picker file list**, rest the mouse cursor on the image in the Main Image area.

Note that there is _no tool-tip being shown_.

That is because the image being shown (at this point) is actually part of the "preview_image" block of code. At this point, the "preview_image" block of code **is not initially hidden**. Therefore, it is sitting exactly right on top of the (unfortunately) obscured "master_image_block" code.

(Looking at the code in the browser's Developer Tools will reveal this.)

Now, rest the mouse cursor on any of the file names in the file list. The "Main Image" title and block of code gets completely hidden, and the "Preview Image" title and block of code is unhidden.

Finally, move the mouse cursor out of the file list and rest the mouse cursor on the image in the now unhidden Main Image area (the Preview Image area is now hidden).

Note that there is now a tool-tip showing for the Main Image.

**Comment by abrookbanks** [comment]
Thanks for clarifying...
