### ISSUE TITLE
FileManager Cannot Insert Same-Named File

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3084]
In FileManeger class, near line 1265, there is:
```
$existing = $GLOBALS['db']->select('CubeCart_filemanager', 'file_id', array('filepath' => $filepath_record, 'filename' => $newfilename));
if ($existing!==false && (int)$existing[0]['file_id']>0) {
```
When the case is that an image has been uploaded via FileManager, Images, the record is accurately created and the image is stored in the type=1 chosen folder.

However, this case also has the same-named file uploaded via FileManager, Downloads. When this happens, the record is **updated** to hold the data relevant to a downloadable file, and the file is stored in the type=2 chosen folder.

This causes the image to disappear from the Product, Image tab, Filepicker list.

Note that the CubeCart_filemanager table holds `null` if there is no chosen sub-folder under the type's respective root folders.

Suggest querying for `$existing` where 'filepath', 'filename', **and 'type' match**.

(Obvious solution is to not use the same name, or save in a differently named subfolder.)

**Comment by abrookbanks** [comment]
Thanks.
