### ISSUE TITLE
After upgrading to 6.4.7 (from 6.2.8) it is not possible to set orders to "Processing"

### ISSUE THREAD

**Issue by bos4711** [cubecart/v6#3085]
After this upgrade, something broke. When customers pay with Paypal, earlier the order was automatically set to "Processing". Now it's set to "Pending", and if we manually set it to "Processing" we are shown an entirely blank page without any errors. Reloading the URL gets back to the order with "Pending" still set. It is possible to change to "Completed" (which completes the order as it should), but "Processing" is broken.

First image shows the order prior changing to Processed (and then Save), second image shows the result.

![2022-11-28_212322](https://user-images.githubusercontent.com/11036018/204374036-b59f4fd9-29c4-42ca-b2e1-b64d2d904cef.png)

![2022-11-28_212333](https://user-images.githubusercontent.com/11036018/204374040-8133ee28-2ff7-409e-b314-b608240459ad.png)

**Comment by abrookbanks** [comment]
Please check your PHP / admin control panel error log.

**Comment by bos4711** [comment]
"[<strong>Exception</strong>] /customers/2/b/5/(domain_name)/httpd.www/store/classes/order.class.php:191 - method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given"

**Comment by abrookbanks** [comment]
There is no such line of code on line 191 with function method_exists.

**Comment by bos4711** [comment]
What do I know? I'm just copying the error message we get.

**Comment by abrookbanks** [comment]
Sounds like its not been upgraded properly or has mods. This is a support issue not a github issue.

**Comment by bos4711** [comment]
I am so sorry for trying to help improve CubeCart by reporting errors, but not knowing which is what.

**Comment by abrookbanks** [comment]
Sarcastic attitude not required. I'm saying this issue looks to be specific to your store and needs to be treated as an individual support case. We have hundreds of merchants on 6.4.7 with PayPal Commerce. Such a **huge** blocking bug would be been found by now over and over again.

**Comment by abrookbanks** [comment]
Still unable to reproduce this but the latest commit should work. Thanks to the anon help here. :)
