### ISSUE TITLE
Admin Order to Completed May Send Unwanted Email

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3088]
In Store Settings, "Allow order "Processing" status to be skipped?" is not checked. That is, Processing must happen.

An admin updates an order from Pending directly to Complete, and has the order's "Do not send email notifications on status change" box checked. A call is made to `Order->orderStatus(3, 'order_id', force, send_email=false)`.

At `orderStatus(), case ORDER_COMPLETE`,  when the determination is made to recurse into `orderStatus(2, 'order_id')`, the `send_email` setting is lost - defaulting to true.

**Comment by abrookbanks** [comment]
Good find. Thank you.
