### ISSUE TITLE
Enhancement Request - Auto Install Moudules on upgrade

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#309]
not an urgent request at all and not critical.

When upgrading from CC3 or CC4 it would be helpful if CC6 would auto download / install any moudles from the marketplace that are currently enabled within the store config.

The DB contains the configuration for the modules, but not the modules themselves. Unless a note of all enabled modules was taken before the upgrade it is difficult to figure out which modules need to be installed from the marketplace.

For example, "All in One Shipping" enabled in CC3 or 4. When upgrading, the script will see this was an ebabled shipping module and try and grab it from the marketplace. After the upgrade has finished the all in one module is available in the "Manage plugins" list.

**Comment by abrookbanks** [comment]
test
