### ISSUE TITLE
Undefined Variable #2

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3091]
Minor:

In `CubeCart->_displayBasket()`, when working through `$contents`, the variable `$product_list` does not get initialized if `$contents` contains only a Gift Certificate.

Later, near line 1896, `$product_list` is undefined.

Suggest testing for emptiness first:
```
if (!empty($product_list) && is_array($product_list) && ($related_orders =
```
This will fail the test immediately.

**Comment by abrookbanks** [comment]
Thanks.
