### ISSUE TITLE
Offset on Int

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3094]
Minor:

Under several situations, shipping gets set to 0. For example, see cubecart.class.php, near line 1840.
```
$GLOBALS['cart']->set('shipping', 0);
```
There are other places in the code, in this class and others, not necessarily using this exact same statement, that sets 'shipping' to the scalar value 0.

There are numerous places in cubecart.class.php that use `$this->_basket['shipping']` where the value of that array element is also an array. For example, see cubecart.class.php, near line 1865.
```
$GLOBALS['smarty']->assign('SHIPPING_VALUE', (isset($this->_basket['shipping'])) ? $GLOBALS['tax']->priceFormat($this->_basket['shipping']['value'], true) : '-');
```
The problem is that there is _at least_ one place where `$this->_basket` is assigned by reference from `$GLOBALS['cart']->basket`. See cubecart.class.php, near line 638.

Effectively, what happens to `Cart->basket` also happens to `CubeCart->_basket`.

Therefore, PHP complains about trying an offset on an integer value.
- - - - - - - - - - - - - - - 
Also, in cart.class.php, near line 1126, using the `$GLOBALS['cart']` instead of `$this`. No big deal, really.

**Comment by abrookbanks** [comment]
Thanks.
