### ISSUE TITLE
Shipping method by group of cusomer (B2B / B2C)

### ISSUE THREAD

**Issue by b-aeby** [cubecart/v6#3095]
Hello,
I'm using all in one shipping. Would it be possible to define different shipping rules depending on the customer group?

Example:
- Group : "B2C"
    - shipping cost 7CHF if basket amount <= 70CHF
    - free shipping if basket > 70CHF
- Group : "B2B"
    - shipping cost 10CHF if basket amount <= 250CHF
    - free shipping if basket > 250CHF

I would be happy to contribute but don't know where to start...
Kind regards
Benjamin

**Comment by abrookbanks** [comment]
Great idea. Hopefully following more demand we can implement this. Closing for now.
