### ISSUE TITLE
Deprecated: False to Array

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3096]
In products.index.inc.php, near line 1030, `$possible = false:`.

Later, near line 1046, `$possible` is being used to hold an array.

This auto conversion is deprecated.

Suggest initializing `$possible` to an empty array, then near line 1051, testing for `!empty($possible) && is_array($possible)`.

**Comment by abrookbanks** [comment]
Fixed with c5ec70742a404057c523663d81cd90904e6c3216 

I hadn't sen this.
