### ISSUE TITLE
Code Check: Offset on Type Bool #2

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3097]
Minor:
In the Module class, near line 148, `$module_lang_node` strips out underscores.

Then, `Language->getStrings()` uses that modified name to fetch the specified sub-array from `Language->_language_strings`.

This will fail, `$lang = false`, because (all modules I looked at) the module.definitions.xml file's `<group name>` will contain underscores -- and it is this spelling of the `node` that finds its way into `_language_strings`.

Thus, near line 150, PHP throws this error on `$lang['module_title']`.

Note 1: the AIOS module does not have a `'module_title'` string in the language file, anyway.
Note 2: Knowing the the Module class loads the language strings, why is it necessary, in the AIOS module, to also have essentially the same statements? Well, other than to get needed strings that the Module class failed to get.

**Comment by abrookbanks** [comment]
Thanks!!
