### ISSUE TITLE
CKEditor Link Tool to fetch FileManager Mode 2 (Documents, not Images)

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3098]
Feature Request:

See:
```
https://forums.cubecart.com/topic/58176-creating-a-link-to-a-pdf-file/
```

Request that the toolbar button in CKEditor that gives a dialog window to create a Link (as opposed to the toolbar button for an Image), and in that dialog window that offers a Browse Server feature, to have Cubecart's FileManager return a list of files (mode 2).

Currently it returns the same list as the Image dialog window, Browse Server (mode 1).

**Comment by bhsmither** [comment]
This is a solution to a different issue.

**Comment by abrookbanks** [comment]
Yes this was part of the thread but it belonged in a different issue I hadn't seen at the time.

**Comment by abrookbanks** [comment]
This is fabulous. Huge thanks.

**Comment by bhsmither** [comment]
I have yet to try the "Added + Guidance" edit, but it seems to me that placing a Smarty variable in a string that is itself represented by a Smarty variable is not (yet) do-able.

**Comment by abrookbanks** [comment]
whoops well spotted
