### ISSUE TITLE
Code Check: AIOS Admin

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3101]
In the AIOS module file index.inc.php, near lines 120-124, there is:
```
	if ($rate_records) {
		$rates = $rate_records;
	} else {
		$rates = $rate_records;
	}
```
The variable `$rates` is not seen until near line 422 when it gets assigned to something else.

Were these lines meant to do something - but perhaps having the wrong variable name?

**Comment by abrookbanks** [comment]
Fixed with 1.0.25. Thanks. This code was removed.
