### ISSUE TITLE
Cookie Consent Not for Robots

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3104]
If a web-bot ignores the `robots.txt` file, or the site owner chooses not to put in the work to create one, or (more likely) wants the site to be scraped, but...

Consider detecting robot user-agent-strings via well-known regexes. See:
```
https://github.com/atmire/COUNTER-Robots
```
The argument could be made that web-bots do not need to consent to the use of cookies.

The regex list could be auto-updated every six months via a cron-job.

This will reduce (somewhat) the record count of the CubeCart_cookie_consent table.

Also consider adding a limit to the log (similar to the email log) set to a minimum of some sensible time delay -- maybe 365 days?

**Comment by havenswift-hosting** [comment]
Both great ideas

**Comment by abrookbanks** [comment]
This is a killer as there is no way to reliably detect bots unless we use a 3rd party tool such as CloudFlare which maintains it's own list of safe bots. Having to close for now unless we restrict it to only the very well known ones. e.g. https://radar.cloudflare.com/traffic/verified-bots
