### ISSUE TITLE
Debug Section to be in a Popup

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3105]
After making an experiment involving 4000 images, I wish for the following feature enhancement:

Rather than scrolling down through that list (even with lazy-load), request that the debug section be shown in a separate window (similar in concept to Smarty's debug console).

**Comment by bhsmither** [comment]
My solution. In debug.class.php:
```
Near line 378, find:
echo implode(($has_debug_spool) ? $GLOBALS['session']->get('debug_spool') : array()).$content;

Change to:
                echo ''
                    .'<script type="text/javascript">'
                    .'_cubecart_console = window.open("", "console:'.md5($_SERVER['REQUEST_URI']).'", "width=1024,height=600,left=50,top=50,resizable,scrollbars=yes");'
                    .'_cubecart_console.document.write(`';
                echo strtr(addslashes((string)''
                    .'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">'
                    .'<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">'
                    .'<head>'
                    .'<title>CubeCart Debug Console</title>'
                    .'</head>'
                    .'<body>'
                    .implode(($has_debug_spool) ? $GLOBALS['session']->get('debug_spool') : array()).$content
                    .'</body>'
                    .'</html>'
                  )
                , array("`" => "")
                );
                echo ''
                    .'`);'
                    .'_cubecart_console.document.close();'
                    .'</script>'
                    .'';
```
I will probably make this optional, as I find I am constantly closing popup windows.

**Comment by abrookbanks** [comment]
It would be cool if each page load appended content to the open popup instead of having a new one.

e.g. If you scroll down the popup it will append each page load with Debug Output - https://www.example.com/page1.html, Debug Output - https://www.example.com/page2.html etc... 
<img width="1036" alt="Screenshot 2023-02-28 at 09 20 50" src="https://user-images.githubusercontent.com/4520803/221808692-e7799cfb-c2fd-45b9-a549-34e3447d4b82.png">

**Comment by abrookbanks** [comment]
It could even be tabbed at the top.

**Comment by bhsmither** [comment]
Something is not quite right with this. It may have to do with having more than one `console:cubecart_debug` active at the same time (having added the relevant code found in 2.cubecart.js to admin.js).

I get a mostly consistent "TypeError: can't access dead object" when switching to a new page in admin. And adding more content _used to work_ on the storefront.

**Comment by abrookbanks** [comment]
I added the JS for the admin control panel but I can't reproduce this error.

**Comment by bhsmither** [comment]
My research suggests it is a Firefox "memory saving" consequence.

Also, Smarty has a `window.close()` command, but Smarty is not expected to add any more content to an already opened window.

**Comment by abrookbanks** [comment]
Ok. Let me know if you think there are any actions that should be taken. 😊

Thanks for all your reports recently. Super helpful.
