### ISSUE TITLE
Unable to install CubeCart 6.4.8 version.

### ISSUE THREAD

**Issue by shree0** [cubecart/v6#3108]
Hi,

I am trying to install the CubeCart 6.4.8 version using PHP 7.2 and 8.0 but I am getting the following during 1st step of the installation. `....../classes/language.class.php:106 - Undefined constant "ADMIN_CP" `  I am not getting how to resolve this error. Please help.
Thanks.

**Comment by abrookbanks** [comment]
Christ knows how this didn't come up when I did my test upgrade in PHP 8.
