### ISSUE TITLE
Language File to Have Comments and Editor List to Show Them

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3111]
Feature Request:

In admin, Languages, when editing language strings, request that there be shown suggestions or restrictions.

Such as, `contact['email_content']` requires no more, no less than four `%s` specifiers. This is because its use in cubecart.class.php, near line 1574:
```
$mailer->Body  = sprintf($GLOBALS['language']->contact['email_content'],
   $_POST['contact']['name'],
   $_POST['contact']['email'],
   $department,
   $enquiry);
```
the `sprintf` function has that restriction.

The short comment could be stored as an attribute in the `<string>` tag, and shown in a new column of the Edit Phrases table or indicated as a blue 'info' icon in the 'actions' column.

**Comment by abrookbanks** [comment]
Cool idea. It may be possible to detect macros matching %s, {$..} etc.. and automate it.

**Comment by bhsmither** [comment]
This is what I did:
```
settings.language.inc.php, lines 185 and 202:
From:
$value = (isset($custom[$name])) ? $custom[$name] : $default;
To:
$value = (isset($custom[$name])) ? $custom[$name] : $default; $countPlaceholders = countPlaceholders($value);

Lines 192 and 209:
From:
'multiline' => detectEol($value),
To:
'multiline' => detectEol($value), 'placeholders' => (!empty($countPlaceholders) ? "There must be $countPlaceholders placeholder".(($countPlaceholders > 1) ? "s. Unless using n\$ position specifiers, their existing order in the string must stay that way." : ".") : null),
```
Also:
```
settings.language.php, line 155:
From:
<td class="actions">
To:
<td class="actions">{if $string.placeholders}<a href="#" id="placeholder_{$string.name}" title="{$string.placeholders}"><i class="fa fa-info-circle"></i></a>{/if}
```
Also:
```
functions.inc.php:
function countPlaceholders($value){
  $pattern = "/(?<!%)%{1}(?!%)/";
  preg_match_all($pattern,$value,$matches);
  if(is_array($matches)) return count($matches[0]);
}
```
Then I would, if so inclined, change the 91 strings that have percent placeholders that are not using position specifiers to use them.

**Comment by abrookbanks** [comment]
This is great thanks. I changed the (i) to click to an alert.
<img width="760" alt="Screenshot 2023-07-06 at 11 08 05" src="https://github.com/cubecart/v6/assets/4520803/079e0725-3ba0-4bd6-bee9-0e68557618bc">

**Comment by bhsmither** [comment]
_Oh, no!_ Take careful note of `Argnum`:
```
http://docs.php.net/manual/en/function.sprintf.php
```
"An integer **followed by a dollar sign $**, to specify which number argument to treat in the conversion."

**Comment by abrookbanks** [comment]
Whoops. Praise the lord for find and replace!!
