### ISSUE TITLE
SearchCatalogue Hide Out of Stock Test Cause Faults

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3115]
In `Catalogue->searchCatalogue()`, where `$search_data` is a string representing the 'cat_id' to show (see line 2040), the test at line 1781-1783 faults with "access offset of type string on string".

Suggest moving this test to after line 1786, where there is:
```
if (!empty($joins) || is_array($search_data)) {
```
Which brings up another situation. When there are `$joins`, then `is_array()` is irrelevant. The `$search_data` could still be a string or _null_.

Then, immediately following, there are "access offset of type string on string" problems.

**Comment by abrookbanks** [comment]
Thanks. I hadn't seen this.
