### ISSUE TITLE
Code Check: Rogue Use of Variable

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3116]
In `Language->__construct()`, there is:
```
if($cache && $GLOBALS['cache']->exists('lang.domain.list')) {
```
The variable `$cache` is not, and can never be at this point in the code, initialized.

(Looks very similar to a line in `listLanguages($cache)` (line 719). Maybe copy-pasta?)

**Comment by abrookbanks** [comment]
Fixed with https://github.com/cubecart/v6/commit/8c19a53f2940f05bf4f45c746e99c9ce04190e08
