### ISSUE TITLE
Code Check: Wrong Variable

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3117]
Relates to #2853.

In the template dashboard.index.php, near line 143, there is (line broken for clarity):
```
<td>
  <a href="?_g=orders&action=edit&order_id={$order.cart_order_id}&source=dashboard" title="{$LANG.common.edit}">
    {$order.{$CONFIG.oid_col}|default:$order.order_id}
  </a>
</td>
```
For `default:$order.order_id`, there is no array element `order_id`.

Suggest `default:$order.cart_order_id`.

**Comment by bhsmither** [comment]
Same in orders.index.php, line 34.

**Comment by bhsmither** [comment]
Same in dashboard.index.php, line 54.

**Comment by abrookbanks** [comment]
Thanks!
