### ISSUE TITLE
Undefined Array Keys

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3118]
Minor (for PHP 8):

In Catalogue->imagePath(), there is near lines 1559-1564:
```
            if(!empty($result[0]['alt']) && !isset($this->image_tags[$img]['alt'])) {
                $this->image_tags[$img]['alt'] = $result[0]['alt'];
            }
            if(!empty($result[0]['title']) && !isset($this->image_tags[$img]['title'])) {
                $this->image_tags[$img]['title'] = $result[0]['title'];
            }
```
Until the admin creates `alt` content for the image's FileManager record, Catalogue's `image_tags['image_path_as_key']` array element will not exist.

Thus, line 270, 702, 1630, and 2154 will have PHP throw an error.

**Comment by bhsmither** [comment]
Suggest (line 1630 is an example for the others):
```
$product['image_tags'][$image_key] = $GLOBALS['catalogue']->image_tags[$product[$image_key]] ?? array();
```
Use the null-coalescing operator to assign an empty array if Catalogue->image_tags[key] where key is not defined.

**Comment by abrookbanks** [comment]
Thank you.
