### ISSUE TITLE
No Image Default Filename in Skin Config

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3119]
QUESTION:
Is there still a reason to not have a default filename for 'category', 'enlarge', and 'large' types in the skin's config.xml file?

Considering there are several functions that scan through all listed `<image>` reference types, if 'default' be an empty string, there may be problems.

(Specifically, the new code dealing with the custom 'alt' attribute for images. See: #3118)

**Comment by abrookbanks** [comment]
I couldn't tell you why they are marked as not needed. Can't see ay harm in adding the default value.
