### ISSUE TITLE
Wrong Variable in Template

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3120]
In catalogue.class.php, near line 1630, there is:
```
$product['image_tags'][$image_key] = $GLOBALS['catalogue']->image_tags[$product[$image_key]]);
```
(and similar statements in a few other places - see: #3118.)

Smarty debug shows this section of values for $product:
```
  ctrl_purchase => true
  out => false
  thumbnail => "http://(x)/images/cache/FL1000-d.190.jpg"
  image_tags => Array (12)
    thumbnail => null
    category => null
    subcategory => null
    gallery => null
    checkout => null
    normal => null
    enlarge => null
    tiny => null
    small => null
    medium => null
    large => null
    source => null
  category => "http://(x)/images/cache/FL1000-d.800.jpg"
  subcategory => "http://(x)/images/cache/FL1000-d.105.jpg"
```
The variable being used in the template content.category.php, near line 74 (line broken for clarity), is:
```
<img
    src="{$product.thumbnail}"
    alt="
    {if isset($product.image_tags.alt) && !empty($product.image_tags.alt)}
      {$product.image_tags.alt}
    {else}
      {$product.name}
    {/if}
    "
    {if isset($product.image_tags.title)}
      title="{$product.image_tags.title}"
    {/if}
>
```
Note that the code creates an array sub-level in `['image_tags']` that uses the `$image_key` (such as 'thumbnail', 'category', etc) as an index.

This index is not used in the template variable.

Suggest `$product.image_tags.thumbnail.alt` and `$product.image_tags.thumbnail.title`.

**Comment by bhsmither** [comment]
Needs to examine every line that uses this new `['image_tags']` array.

**Comment by abrookbanks** [comment]
Thank you.
