### ISSUE TITLE
Colorbox Content CSS Bleeds to Whole Document

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3127]
FYI:

When viewing the HTML Content, being composed in the editor, in the colorbox via the Test button, any general CSS rules will cause the whole page to acquire that styling.

For example, bring the "Default Email Template" up for editing. Note the `<style>` rules that specify a font-size for html, body and table elements.

Click the Test button to show that content in the colorbox.

Note that the entire page is now showing, as a base size, a font-size of 14px. Change to 24px. View again. Big lettering everywhere.

Just making note of it.

**Comment by abrookbanks** [comment]
This seems to work well but I'm not sure if quotes could be a problem.

**Comment by abrookbanks** [comment]
Seems ok.
