### ISSUE TITLE
YouTube icon URL

### ISSUE THREAD

**Issue by chilled35** [cubecart/v6#313]
Whatever URL information put in the admin panel is hard coded to http://www.youtube.com/user/xxxxx

This is incompatible with channel links that take the form:

https://www.youtube.com/channel/UCIbGXvyF779_BqB2V6imZ-A

Fix for this is to have the admin enter the full URL as shown above, rather than limit it to a user URL.

**Comment by abrookbanks** [comment]
![screen shot 2015-03-03 at 15 06 29](https://cloud.githubusercontent.com/assets/4520803/6465129/e7938c12-c1b6-11e4-9d24-51ad85abf950.png)
