### ISSUE TITLE
Admin category listing to show number of products

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#3131]
It would be very useful to show a count of the number of products in each category - maybe between "Category Name" and "Translations" columns

**Comment by bhsmither** [comment]
In categories.index.php, suggest:
```
From:
      <td>{$LANG.settings.category_name}</td>
      <td>{$LANG.translate.title_translations}</td>
To:
      <td>{$LANG.settings.category_name}</td>
      <td>Prod P/A</td>
      <td>{$LANG.translate.title_translations}</td>
From:
        {$category.cat_name}
        {/if}
        </td>
        <td style="text-align:center" class="language_list">
To:
        {$category.cat_name}
        {/if}
        </td>
        <td style="text-align:center">{$category.pri_alt}</td>
        <td style="text-align:center" class="language_list">
```
In categories.index.inc.php, suggest:
```
Near line 445, from:
            $category['children'] = currentPage(null, array('parent' => $category['cat_id']));
            $category['translate'] = currentPage(null, array('action' => 'translate', 'cat_id' => $category['cat_id']));
            $category['edit']  = currentPage(null, array('action' => 'edit', 'cat_id' => $category['cat_id']));
To:
            $cat_sel = $GLOBALS['db']->select('CubeCart_category_index', array('primary'), array('cat_id' => $category['cat_id']));
            $category['pri_alt'] = (array_count_values(array_column($cat_sel, 'primary'))['1'] ?? '--').'/'.(array_count_values(array_column($cat_sel, 'primary'))['0'] ?? '--');
            $category['children'] = currentPage(null, array('parent' => $category['cat_id']));
            $category['translate'] = currentPage(null, array('action' => 'translate', 'cat_id' => $category['cat_id']));
            $category['edit']  = currentPage(null, array('action' => 'edit', 'cat_id' => $category['cat_id']));
```
The new column will show a number/number that represents the number of products where this category is the primary category, followed by the number of products that claim this category as an alternate category.

**Comment by abrookbanks** [comment]
This gives me an error.

> categories.index.inc.php:443 - array_column(): Argument #1 ($array) must be of type array, bool given

Will see if I can fix it.

**Comment by bhsmither** [comment]
So `$cat_sel` is false because there is nothing in CubeCart_category_index having that 'cat_id'?

Did you create a category without having assigned any products to it yet? Ok, that's legit.

**Comment by bhsmither** [comment]
This is my fix, although I do not know why this wasn't noticed:
```
$cat_sel = $GLOBALS['db']->select('CubeCart_category_index', array('primary'), array('cat_id' => $category['cat_id'])) ?: array();
```
Gives `$cat_sel` an empty array if nothing found.

**Comment by abrookbanks** [comment]
Something still odd. This store has hundreds of products...
<img width="564" alt="Screenshot 2023-04-21 at 08 44 15" src="https://user-images.githubusercontent.com/4520803/233574959-fcf0b69a-8ed0-42b7-9234-e1bee071e40c.png">

**Comment by abrookbanks** [comment]
Actually that's right! This shops mostly has products in the subcategory.

**Comment by abrookbanks** [comment]
Thanks.

**Comment by abrookbanks** [comment]
Should we just show the total? I find this confusing to look at.

**Comment by abrookbanks** [comment]
.. sorry for the message trail. Or show total but hover a title saying the primary/additional ratio.

**Comment by havenswift-hosting** [comment]
I also find this a bit confusing - I think just a simple count for products in that specific category would be clearer

**Comment by abrookbanks** [comment]
> I also find this a bit confusing - I think just a simple count for products in that specific category would be clearer

Yes I agree. We can add a title tag for the split.

**Comment by abrookbanks** [comment]
Mouse pointer isn't in the screenshot but on hover of the count number we can break it down. 
<img width="633" alt="Screenshot 2023-04-21 at 09 13 32" src="https://user-images.githubusercontent.com/4520803/233581401-b6f6084b-f52f-48fb-9f9e-90ee2554e364.png">

**Comment by bhsmither** [comment]
Is there a way to indicate additional info available via hover? Maybe append the white 'i' in blue circle icon?

**Comment by abrookbanks** [comment]
Does this look weird?
<img width="636" alt="Screenshot 2023-04-21 at 09 29 12" src="https://user-images.githubusercontent.com/4520803/233586554-0d669102-00ca-4e4b-b917-b30115ac4a14.png">

**Comment by abrookbanks** [comment]
IMO the ABBR tag looks better.
<img width="648" alt="Screenshot 2023-04-21 at 09 30 52" src="https://user-images.githubusercontent.com/4520803/233587063-95b8478f-aa75-436e-8fc7-a3ba30b0f576.png">

**Comment by abrookbanks** [comment]
On two lines it looks better still. 

<img width="644" alt="Screenshot 2023-04-21 at 09 33 27" src="https://user-images.githubusercontent.com/4520803/233587593-7703cf26-d2d5-4504-9bcc-53590c5895f8.png">

**Comment by abrookbanks** [comment]
I think this is good now. Thanks all.

**Comment by bhsmither** [comment]
The last edit I see is opening with `<abbr>` but closing with `</span>`.

**Comment by abrookbanks** [comment]
Thanks. I think the (i) looks bad personally. I've got vision problems at the moment so your QA is much appreciated.

**Comment by abrookbanks** [comment]
Maybe a count including all subfolders would be even better.🫣

**Comment by bhsmither** [comment]
Because I run a 4k monitor, these little dots (via `<abbr>`) are so barely visible - absolutely overlooked unless you know that they are there. Also, personally, the little dots under the number is not familiar to me - I do (did) not know what that means.

**Comment by bhsmither** [comment]
Might want to give some thought to incorporating the Search icon in the Actions column -- co-opt its tooltip.

**Comment by abrookbanks** [comment]
Probably the best overall solution. 
<img width="590" alt="Screenshot 2023-06-29 at 14 08 46" src="https://github.com/cubecart/v6/assets/4520803/02d1a98f-c282-4f58-a020-cf8c3f0cc00b">

**Comment by havenswift-hosting** [comment]
That is great thanks !
