### ISSUE TITLE
Input.Toggle Getting Img Copies Over Attributes

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3135]
Feature Request:

In the admin.js file, near line 249, is code to create an `<img>` for each hidden `input.toggle:hidden` element.

Request, to transfer over, _at least_, the style attribute of the `input.toggle` tag.

Even though the style may not be appropriate to the hidden `input.toggle`, once transferred to the image, the styling could be very appropriate.

For example, in AIOS /skin/admin/index.tpl, `<a><img>` tags near lines 138 and 141 has `style="padding:0 5px;"`.

When adding a `input.toggle` here alongside, which will then show a checkbox image, there will be a desire to also apply the same `style="padding:0 5px;"` to that image that was obtained from the hidden `input.toggle` style attribute.

Other transferred attributes may be useful.

**Comment by abrookbanks** [comment]
Nice! :)
