### ISSUE TITLE
SEO Category Path Malformed - Wrong Variable Name

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#314]
seo.class.php, lines 243-247 (current code listing):

```
if($GLOBALS['config']->get('config', 'seo_cat_add_cats') == 0) {
  // Get last part of path
  $cat_parts = explode('/', $path);
  $path = array_pop($path_parts);
}
```

`$path_parts` <> `$cat_parts`

**Comment by abrookbanks** [comment]
When I changed this code from your replated report I told myself to be careful... not careful enough it seems! Thanks Brian.

**Comment by chilled35** [comment]
Code tweaked on live site, fixed :)
