### ISSUE TITLE
Menu Style Broken

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#3141]
<img width="403" alt="Screenshot 2023-01-20 at 08 00 10" src="https://user-images.githubusercontent.com/4520803/213645733-1aadd368-c28f-4c5a-8654-76496a96f906.png">

**Comment by bhsmither** [comment]
This is what I did. It maintains the relative widths of the `<li>` boxes to the root font size - if someone wants to zoom the text in the viewport to 200% or 50%:
```
ul.quick_links li#help_menu ul li {
    list-style: none;
    text-align: left;
    float: left;
    border: none;
    width: 8rem; /* keeps relative width */
}
```
and
```
#breadcrumbs ul.quick_links li {
    float: left;
    padding: 5px 1rem 5px 0.5rem;
}
```
and
```
ul.quick_links li#help_menu ul {
    display: none;
    position: absolute;
    background-color: #F9F9F9;
    padding: 0;
    margin: 5px 0 0 -0.5rem;
    border: 1px solid #D0D0D0;
    border-right: none;
}
```

**Comment by abrookbanks** [comment]
A much better solution. Thank you.
