### ISSUE TITLE
Deprecated: Null to Type String

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3143]
PHP8:

In the admin skin file orders.paypal-tooltip.php, line 1, if `{$SUMMARY.gateway}` is not defined (that is, _null_), PHP throws "Passing null to type string in stristr()".

Suggest:
```
{if !empty($SUMMARY.gateway) && $SUMMARY.gateway|stristr:"paypal" && $SUMMARY.gateway!== 'paypal commerce'}
```
(Perhaps eventually, make sure CubeCart_order_summary column 'gateway' defaults to a zero-length-string.)

**Comment by abrookbanks** [comment]
Thanks for this.
