### ISSUE TITLE
Suggestion: If more than 1 quantity, make the box highlighted in different colour

### ISSUE THREAD

**Issue by tonyrsutton** [cubecart/v6#3148]
Now and then, when customers orders a lot of items, sometimes you may miss out the number of quantity due to overcrowding of texts under the Items box.

Suggestion: If there is more than one quantity, how about making the box field to be highlighted in different shades of colour so we can easily spot it has more than one quantity.

Found under Dashboard -> Orders -> xxxxxx-xxxxxx-xxxx

Thoughts?

**Comment by bhsmither** [comment]
Would this be regarding the Order Summary, General tab, Items table? And/Or the layout one gets when printing the order to a hard copy (useful for warehouse stock pickers)?

A separate column can be made to show just the quantity, and on the hard copy, another separate blank column for the stock picker to validate how many of that item was actually put in the package.

**Comment by abrookbanks** [comment]
I'm not clear either. Can you drag a screenshot into this text field to show us?

**Comment by tonyrsutton** [comment]
Basically, trying to make it clearer for the item picker to know it has more than one quantity on the order and by making the order line to be highlighted, it gets their attention that it contains more than one quantity.

Now and then, we miss out that it has more than one quantity. So, by highlighting it, it grabs their attention.

Hope this is more clearer?

Thanks,

**Comment by bhsmither** [comment]
Please let us know what the item picker is looking at where the confusion exists. The admin screen Order Summary on a laptop? A hard copy printout of something?

**Comment by abrookbanks** [comment]
Do you think if it showed item price and line price it might make it clearer that it's more than one? Making it stand out over one doesn't give me a warm feeling.

**Comment by abrookbanks** [comment]
Is this better?

<img width="733" alt="Screenshot 2023-02-01 at 12 12 34" src="https://user-images.githubusercontent.com/4520803/216039631-aeaaf838-35e9-4916-acbc-014712d62716.png">

**Comment by tonyrsutton** [comment]
I think it's an improvements, thank you. Will see how we get on with this. :)

Cheers

**Comment by abrookbanks** [comment]
Making the quantity look different for values over 1 isn't easy to achieve without it being a bit odd. Other merchants wouldn't want this. Having a different price each then price should help draw attention. 

If you have any suggestions to further improve it I'm all ears. Closing for now. Thanks again Tony.
