### ISSUE TITLE
Request: Updating 'custom_oid' is Not Wanted

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3149]
With respect to #2878, it was said:

> once the Store Settings has been Saved (and $order->setOrderFormat() has been executed, 'custom_oid' will no longer ever be empty

With respect to #2461. it was said:

> the secondary question of why use the Cart_order_summary.**id** value for the custom_oid when in Incremental mode where the custom_oid column is currently null or a zls.

This happens in `Order->setOrderFormat() where `$force_past_oids = false` (from admin, Settings near line 31, `(bool)$_POST['oid_force']`).

I assert that the block of code at lines 918-920 never was appropriate -- but especially now that the templates have default data when `custom_oid` is _null_.

Request that when `$force_past_oids = false`, that there is nothing that will be done with respect to updating the `custom_oid` column in CubeCart_order_summary.

**Comment by abrookbanks** [comment]
Thanks.
