### ISSUE TITLE
Recursed Function Does Not Bubble Data Back Up

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#315]
In GUI->_displayRandomProduct(), there are two conditions where the function recurses into itself.

These two occasions are inconsequential as the conditions are tested before any data is gathered and assigned to the template.

However, there is a hook offering to modify the `$product` array.

I want to test for the condition of the product being out of stock. If so, recurse into this function.
`if ((int)$stock_level <= 0) { $p++; $this->_displayRandomProduct($p); }`

The nature of calling a function is that the set of variables used inside the function are contained within the function unless an argument is passed by reference, a variable is (made) global inside the function, or data is returned out of the function.

Currently, this function makes available its results to Smarty->assign(). When PHP is recursing out, the prior recursion's `$product` is still in play and is made available to Smarty->assign(). And so forth.

Therefore, I need this function to return a valid `$product` - to have the result bubble up.
```
  } elseif ($p<20) { // doesn't meet WHERE criteria
    $p++;
    $this->_displayRandomProduct($p);
  }
  if ($random_product) return $product;
}
```
Then I can have the hook's `$product` completely replace the next-level-up 'out of stock' `$product`.
`if ((int)$stock_level <= 0) { $p++; $product = $this->_displayRandomProduct($p); }`

**Comment by abrookbanks** [comment]
Thanks for this Brian.
