### ISSUE TITLE
Code Review: Logging Deprecated Errors

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3151]
In Debug class, `errorLogger()`, for the switch's default stanza, there is the added test for deprecated type. (Added in #954, but cannot determine why the test was added at this location.)

Suggest moving this test to its own `case` stanza, and include a `$log = $can_log;` statement.

So, until all of PHP 8.1's new restrictions on function parameters, etc. are dealt with, turning off debug mode should silence these deprecated notices from getting logged.

**Comment by abrookbanks** [comment]
Good find. Thanks.
