### ISSUE TITLE
Unknown Admin

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3152]
Very minor:

When a CubeCart process adds a note to an order, such as when a Discount Coupon is used, the entry made to CubeCart_order_notes with having `admin_id=0`.

Also, in orders.index.inc.php, near line 511, the array `$author` is built from CubeCart_admin_users.

Because there is no admin having the admin_id of '0', PHP complains near line 521, that `$author[0]` has an undefined array key (the zero comes from `$note['admin_id']`).

Since the `$author` array contains the admin's names, suggest that:
```
$author[0] = "An Internal Process"; // maybe find/create a language phrase
```
Also, since `$author` is built only from the foreach loop, and that loop only executes if there are records returned from a query to CubeCart_admin_users (when would that ever fail???), suggest:
```
From:
$note['author']  = $author[$note['admin_id']];
To:
$note['author']  = $author[$note['admin_id']] ?? "Name not available";
```

**Comment by abrookbanks** [comment]
`Nobody` seemed to make the most sense to me. 

Thanks for this.

**Comment by bhsmither** [comment]
Please examine the two lines changed.

The variable `$LANG` is not correct. Please use `$lang`.
