### ISSUE TITLE
Sessions failing on *some* mobile network providers

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#3155]
*Edited from an email...*

I have been able to narrow down the circumstances when it happens and also had cPanel engineers take an extensive look into the problem – they have said it isnt down to cPanel or the server configuration.

 
So the situation now is that I can reliably reproduce it on this (and other sites) as follows :
 
Website : https://www.***.com/admin_DiBXwq.php
Admin user :    ***
Pass : ***
 
Initially, the behaviour seemed random even after noticing that it was only affecting apple devices but after lots of work trying to figure out what is happening, it seems that any user (whether admin or customers on the front end) that attempts to login from Apple devices with IP address from some non-UK IP addresses (it isn’t as clearcut as all non-UK but will explain later) “appear” that they are unable to login to the application.

It is not relevant to which browser is being used and no pattern with iOS version.

I can reproduce this at will using my own iPhone and iPad. When connected to my UK based wifi, all works fine.  I have a Spanish mobile contract so when disconnected from wifi and therefore using a Spanish IP address, the login fails but then using a VPN to then connect back to a UK IP address via the mobile signal, it works fine.  Using a VPN to connect from some other countries also fails so it isn’t limited to Spanish IP addresses which supports my client’s experiences from France, Netherlands etc although surprisingly connections from the USA (and Portugal ??) work fine

Earlier I said that it “appears that they are unable to login to the application” as when this is failing, the login page refreshes and they are left still at the login page.  However, checking within the application if I am logged into another session on a device (for example a PC connected via wifi using a UK based IP address) where it works, I can see that they are actually logged in OK and I can see the non-UK based IP address but the application thinks for some reason that they arent logged in and doesn’t take them from the login page.

This was the final reply from cPanel – I am not sure how helpful it will be to you but any help you can give me would be much appreciated !
 
 
I was able to reproduce on iOS but only after connecting through Spain.

![C6FB1270AFDF4DBC9CF4D63FC87BE2A3](https://user-images.githubusercontent.com/4520803/216079706-815fbaa5-33fc-48d9-ab18-eead0670841a.png)

 
I have reviewed the server's PHP configuration and overall have not found anything to suggest that cPanel is related to the issue.
 
Although I haven't found anything to suggest that cPanel is related I did want to see if I could find some information to help get you started in the right direction.
 
I traced the PHP process while reproducing the issue. The script I'm using here gets rid of all of the PHP processes for the user who's home directory I'm in and then waits for new PHP processes to spawn, upon which time the script attaches a trace to the new PHP process:

```
[03:15:43 saturn root@94511317 /home/xxx]cPs# user=$(pwd | cut -d \/ -f 3); x=1; killall -6 -u $user; while [ $x = 1 ]; do process=$(pgrep -u $user); if [ $process ]; then x=0; fi; done; strace -vvttff -o php.$process.strace -s 500 -p $process
strace: attach: ptrace(PTRACE_SEIZE, 27617): No such process
[03:16:23 saturn root@94511317 /home/xxx]cPs# user=$(pwd | cut -d \/ -f 3); x=1; killall -6 -u $user; while [ $x = 1 ]; do process=$(pgrep -u $user); if [ $process ]; then x=0; fi; done; strace -vvttff -o php.$process.strace -s 500 -p $process
strace: Process 28318 attached
strace: Process 28334 attached
strace: Process 28383 attached
strace: Process 28408 attached
strace: Process 28409 attached
strace: Process 28442 attached
strace: Process 28456 attached
strace: Process 28474 attached
strace: Process 28477 attached
^Cstrace: Process 28318 detached
```
 
I make sure to run this just before I press the login button so I don't capture other visitor's PHP processes.
 
Once I'm done reproducing the issue I use CTRL-c to stop the trace.
 
That produces a number of trace files named similarly to: `php.28318.strace.xxxxxx` where xxxxx is the forked process IDs.
 
In order to merge all of the trace files into one ordered file I use the `strace-log-merge` utility and then pipe that to the less utility:
 ```
[03:16:52 xxx root@xxx /home/xxx]cPs# strace-log-merge php.28318.strace | less
```
 
There is a massive amount of useless data to wade through so it can be difficult to find anything useful in a trace, but I did run across the following which shows that the CubeCart application is associating both IP and User Agent data with each session in the database:
 
```
28474 03:16:47.071986 sendto(4, "%\0\0\0\3SHOW COLUMNS FROM CubeCart_sessions;", 41, MSG_DONTWAIT, NULL, 0) = 41
28474 03:16:47.072047 poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 86400000) = 1 ([{fd=4, revents=POLLIN}])
28474 03:16:47.072516 recvfrom(4, "\1\0\0\1\6F\0\0\2\3def\22information_schema\7COLUMNS\7COLUMNS\5Field\vCOLUMN_NAME\f!\0\300\0\0\0\375\1\0\0\0\0E\0\0\3\3def\22information_schema\7COLUMNS\7COLUMNS\4Type\v
COLUMN_TYPE\f!\0\367\377\10\0\374\21\0\0\0\0E\0\0\4\3def\22information_schema\7COLUMNS\7COLUMNS\4Null\vIS_NULLABLE\f!\0\t\0\0\0\375\1\0\0\0\0C\0\0\5\3def\22information_schema\7COLUMNS\7COLUMNS\3Key\nCOLUM
N_KEY\f!\0\t\0\0\0\375\1\0\0\0\0K\0\0\6\3def\22information_schema\7COLUMNS\7COLUMNS\7Default\16COLUMN_DEFAULT\f!\0\367\377\10\0\374\20\0\0\0\0@\0\0\7\3def\22information_schema\7COLUMNS\7COLUMNS\5Extra\5EX
TRA\f!\0Z\0\0\0\375\1\0\0\0\0\5\0\0\10\376\0\0\"\0 \0\0\t\nsession_id\vvarchar(32)\2NO\3PRI\373\0&\0\0\n\rsession"..., 32768, MSG_DONTWAIT, NULL, NULL) = 797
28474 03:16:47.072622 sendto(4, "\212\0\0\0\3SELECT  SQL_CALC_FOUND_ROWS * FROM `CubeCart_sessions` WHERE CubeCart_sessions.session_id = '441367c6a70ca309d8f1c0b78701a2a8'   LIMIT 1;", 142, MSG_DONTWAIT,
NULL, 0) = 142
28474 03:16:47.072682 poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 86400000) = 1 ([{fd=4, revents=POLLIN}])
28474 03:16:47.072880 recvfrom(4, "\1\0\0\1\t]\0\0\2\3def\21xxx_cubecart\21CubeCart_sessions\21CubeCart_sessions\nsession_id\nsession_id\f!\0`\0\0\0\375\3P\0\0\0c\0\0\3\3def\21xxx_cubecart\21Cub
eCart_sessions\21CubeCart_sessions\rsession_start\rsession_start\f?\0\n\0\0\0\3!\0\0\0\0a\0\0\4\3def\21xxx_cubecart\21CubeCart_sessions\21CubeCart_sessions\fsession_last\fsession_last\f?\0\n\0\0\0\3)
@\0\0\0Y\0\0\5\3def\21xxx_cubecart\21CubeCart_sessions\21CubeCart_sessions\10admin_id\10admin_id\f?\0\n\0\0\0\3!\0\0\0\0_\0\0\6\3def\21xxx_cubecart\21CubeCart_sessions\21CubeCart_sessions\vcusto
mer_id\vcustomer_id\f?\0\n\0\0\0\3)@\0\0\0Y\0"..., 32768, MSG_DONTWAIT, NULL, NULL) = 884
28474 03:16:47.073047 sendto(4, "\205\1\0\0\3INSERT INTO `CubeCart_sessions` (`admin_id`,`customer_id`,`ip_address`,`location`,`session_id`,`session_last`,`session_start`,`useragent`,`acp`) VALUES ('0','0
','45.128.39.216','','441367c6a70ca309d8f1c0b78701a2a8','1671333407','1671333407','Mozilla/5.0 (iPhone; CPU iPhone OS 15_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.3 Mobile/1
5E148 Safari/604.1','1');", 393, MSG_DONTWAIT, NULL, 0) = 393
 ```

PHP itsself is unaware of those things. Considering this problem is tied so closely to the UserAgent and IP address it would make sense for this issue to be related to that functionality of the application.
 
I realize that you're already familiar with the application and that you're already collaborating with the developers, and you've not made significant progress. Regardless, this type of issue is best handled by a PHP developer with extensive experience with the application. 
 
I'm hoping that maybe the trace that I generated may be of some assistance, or possibly even the knowledge that the application is managing User Agent and IP address data in the database.
 
I've since moved the trace data to the following folder:
`/root/xxx/94511317/xxx/`
 
You can review it further with the following command:
`strace-log-merge /root/xxx/94511317/xxx/php.28318.strace | less`

**Comment by abrookbanks** [comment]
It sounds like the cPanel engineer is suggesting that the IP address and user agent are the issue. CubeCart does store this against the session but absolutely does not validate the session against IP and/or user agent. 

The only connection is the session cookie. The session clearly isn't holding.

Can you check the session cookie on each page load? It will be named something like `CCS_F05EE4CE32` or `CC_F05EE4CE32` if the page isn't under SSL. Does it change on each page load?

**Comment by abrookbanks** [comment]
@havenswift-hosting maybe you can try this fix for https://github.com/cubecart/v6/issues/3156

**Comment by abrookbanks** [comment]
I appreciate you can reproduce this via Spanish networks but I still have no means to be able to reproduce this.

**Comment by havenswift-hosting** [comment]
It is very simple - use a free VPN such as Tunnelbear from an Apple device and then connect to any Spanish, French, Dutch server through them.  Isnt limited to that one VPN provider either

**Comment by abrookbanks** [comment]
Thats exactly what I did with Safari on mac. Session holds. I'll try again.

**Comment by havenswift-hosting** [comment]
Dont know about Mac - dont have one so never tried - reproduceable 100% on iPhone and iPads

**Comment by havenswift-hosting** [comment]
Also which site are you trying it on - the customer site in question ? Lots of problems in the past that havent been reproduceable in your dev that can in real world sites.  Just about to test #3156 although this customer isnt on quite the latest version

**Comment by abrookbanks** [comment]
I was able to reproduce it on your customers store just now with safari on mac via tunnelbear in spain but not on my development store or a store hosted elsewhere.

**Comment by abrookbanks** [comment]
Have you tried cloning this store to a different server and (preferably)/or locally to see if its still reproducible?

**Comment by abrookbanks** [comment]
The weird thing is that the session holds. It will keep the basket. The login fails and doesn't even give an error message it just reloads the page. It's as if the post variable are wiped away preventing it from actually logging in.

Any security software on the server that could be doing that or modification?

**Comment by abrookbanks** [comment]
Anything to do with litespeed or a litespeed security setting?

**Comment by havenswift-hosting** [comment]
> Have you tried cloning this store to a different server and (preferably)/or locally to see if its still reproducible?

Reproduceable on different stores on different servers

> Anything to do with litespeed or a litespeed security setting?

Dont use litespeed - do use lsapi PHP Handler via Cloudlinux

> Any security software on the server that could be doing that or modification?

No

> maybe you can try this fix for #3156 

This makes no difference

Wondering whether it is anything to do with the fact that these stores have a modified session path and session lifetime

session.gc_maxlifetime is set to 172800
session.save_path is set to /home/xxxxxxxx/sessions

Cant think why this would only affect Apple devices from certain countries but will be one thing that is session related that will be different

**Comment by abrookbanks** [comment]
Can you PM me anther store with the issue on a different server to see if I can see anything?

I'm convinced the post variable for login are going astray.

**Comment by abrookbanks** [comment]
Can I take an anonymised (no customer data or orders etc) copy of the store to test or ask the merchant for permission for us to access? Hopefully it can be reproduced locally to debug.

**Comment by havenswift-hosting** [comment]
You have permission and details to access this store and if you need cPanel access, I can provide that in a secure way

**Comment by abrookbanks** [comment]
FTP access would be needed. The backup tool in CubeCart will fail I expect.

**Comment by havenswift-hosting** [comment]
Let me know a secure way to pass details and you can have full cPanel

**Comment by abrookbanks** [comment]
Hi Ian, please split it across https://support.cubecart.com/hc/en-gb/requests/new and send a separate email to support@cubecart.com or my personal email which you know.

**Comment by abrookbanks** [comment]
Turned out the be a cloudflare network issue.
