### ISSUE TITLE
Amzin Bootstrap Responsive skin no longer works on PHP 8.0 and up

### ISSUE THREAD

**Issue by royallopez** [cubecart/v6#3157]
#Amzin Bootstrap Responsive skin no longer works on PHP 8.0 and above

## Service provider server details

- Distributor ID:	Debian
- Description:	Debian GNU/Linux 10 (buster)
- Release:	10 (10.3)
- Codename:	buster
- PHP 8.0.27 (cli) (built: Jan 13 2023 10:38:43) ( NTS ) ( though php 8.1 gives the same problem)

### Technical Details 
- CubeCart Version   6.4.9 
- PHP Version  8.1.14
- MySQL Version 10.4.27-MariaDB-1:10.4.27+maria~deb10

Our customers thoroughly enjoy the Amzin skins as so do we. It is a very functional, straightforward skin that really works well.

Our hosting provider originally had PHP 7.5 but recently migrated to PHP 8.0/8.1. 
Since then, the Amzin skin does not function at all, with just the works "Best Seller" appearing on the screen for the storefront.

We confirmed this by setting up a little dev environment and switching from PHP7.5 to PHP 8.1 and PHP 8.1. The skin definitely does not respond to PHP8.0 and above.

We would be extremely grateful if someone could investigate this issue and advise us of any progress. We have looked at some alternative skins, but Amzin would really be first price.

Please advise if there is any other information that is required from us.

All the best...

**Comment by bhsmither** [comment]
Amzin skin works fine for me.

You have verified that Foundation works without error? If so, then we cannot blame the CubeCart core code.

But if, when using Foundation under PHP 8.1, then it may be the case that the CubeCart core code is faulting.

We can discuss some troubleshooting procedures at the forums.

Meanwhile, look at any and all error logs.

**Comment by abrookbanks** [comment]
Thanks this has been fixed with amzin_v106_cc643.zip
