### ISSUE TITLE
Foundation skin - view order

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#316]
As a customer viewing a historic order the date/time that the order was placed is missing from the order details page in the default foundation skin.

Wasn't sure if this was intentional or not, but really should be in there :)

**Comment by Noodleyman** [comment]
The only $SUM smarty variable I can find that is related to order date/time is the "order_date" field from the order_summary table.

but, this field is sent to smarty as a unix timestamp rather than a formatted date. I wasn't able to see any formatted date available for use on this page. is it possible to make an addition and add it?

**Comment by Noodleyman** [comment]
I always seem to find a work around after opening these tickets hehe.

{$SUM.order_date|date_format:"%A, %B %e, %Y, %R"}

using smarty to format the time, however it would be nice if there was a pre formatted string using the standard cubecart "Date & Time format" settings.

**Comment by abrookbanks** [comment]
Thats one way to do it for sure...

**Comment by abrookbanks** [comment]
![screen shot 2015-03-04 at 11 02 21](https://cloud.githubusercontent.com/assets/4520803/6482463/f8ec943e-c25d-11e4-83f8-d7ea508a2453.png)
