### ISSUE TITLE
Change in Coupon Text Field to Announce

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3166]
(Not confirmed of the outcome) It may be possible to enter a coupon code, but fail to click "Apply" or "Update Basket", and then click "Checkout with PayPal" special button, maybe resulting is no discount being applied. (See:
```
https://forums.cubecart.com/topic/58240-free-shipping-coupon-codes/
```
Maybe effect some sort of visual tickle when the contents of this field changes, such as an initially dimmed button to become quite bright and flashy - as absurd as that need seems to be.

**Comment by abrookbanks** [comment]
GIF (works better in real life)
![Screen Recording 2023-06-30 at 10 11 05](https://github.com/cubecart/v6/assets/4520803/e5de9ad5-5ff1-4ba8-a960-11a80c04223b)
