### ISSUE TITLE
Code Enhancement

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3174]
In the admin skin products.options.php, each tab has its own `form_control` block of code.

Suggest having just one `form_control` just above the closing `</form>` tag.

Also, there is no `$PLUGIN_TABS` capability.

Suggest adding that just above the `{include}` statement.

**Comment by bhsmither** [comment]
Ok, I see #2862 put a `form_control` button on each tab. But I don't understand why - other than to suppress showing a Save button on the Attributes tab if there are no attributes to add.

**Comment by abrookbanks** [comment]
Yes I think it was to give more control over it. We don't want at all the time.
