### ISSUE TITLE
When adding a line to an order it nolonger defaults with 1

### ISSUE THREAD

**Issue by Lastwolf1882** [cubecart/v6#3176]
When manually adding items to an order in admin, the default quantity of 1 is only appearing for first item, for every additional item is is blank as shown in images

old behaviour
![eg1](https://user-images.githubusercontent.com/75647158/220414351-4041bb19-423d-463d-9013-bca491a14b6a.gif)

6.4.9 + Behaviour
![eg2](https://user-images.githubusercontent.com/75647158/220414494-923ea7af-085c-4b2b-b0bd-3dae2a5d5057.gif)

**Comment by bhsmither** [comment]
When, after having clicked the white-plus-green-circle, the new inline added blank table row does contain a value attribute, but the browser is not showing that value in the textbox form element.

There is also the ability to add a new blank line. That is, click the green button and a new blank row appears, whereas previously, the validator would insist on a Product Name be entered before allowing the green button to perform its function.

Probably related to employing the new "Dirty" plugin.

**Comment by abrookbanks** [comment]
This is wierd because it does have a value of 1. 

<img width="650" alt="Screenshot 2023-02-27 at 13 36 43" src="https://user-images.githubusercontent.com/4520803/221578102-4bbf004e-0320-4663-8658-244e9d969da7.png">

**Comment by Lastwolf1882** [comment]
it's not showing or entering the value, if you add the item it is '0' upon reloading.

**Comment by abrookbanks** [comment]
Thanks I figured it out.
