### ISSUE TITLE
Option Group Sortable is Getting Sorted by Type

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3178]
In `Catalogue->displayProductOptions()`, an `$optionArray` is fetched from `getProductOptions()`. This array elements seem to be ordered according to the `priority` column of `CubeCart_option_groups` (that's how the query is constructed), where the first level key seems to be the option_type (unchanged ordering) and second level key is option_id (unchanged ordering).

However, six lines later the `$optionArray` is given to `ksort()` where the result has been sorted by the first level key = option type.

I find no reason for this `ksort()` to happen.

This `ksort()`would negate the group's priority feature, were it not for...

Six lines later, the option group's (`$option` in the `foreach()`) 'priority' value is copied to `$group_priority` then gets unset.

The problem is that `$group_priority` is never used. One can assume it will be used to resort the array somehow, somewhere, so that the option groups will be displayed according to their desired ordering.

**Comment by abrookbanks** [comment]
From my testing neither code sections are needed to respect the priority.

**Comment by abrookbanks** [comment]
Problems with unexpected options showing.

**Comment by bhsmither** [comment]
Where is `$group_priority` used?

I used the following:
```
                        $this->_options_line_price -=  $value['option_price'];
                    }
                }
            }
        }
        $option_list[$value['option_id']]['priority'] = $group_priority;
    }

    break;
case self::OPTION_TEXTBOX:  ## Textbox options
case self::OPTION_TEXTAREA:  ## Textarea option
```

**Comment by abrookbanks** [comment]
Seems god to me. I still don't fully get how this is working but it does.
