### ISSUE TITLE
6.0.0b6 Breadcrumb Menu Error

### ISSUE THREAD

**Issue by chilled35** [cubecart/v6#318]
http://thebarrymusicshop.com/ernie-ball-super-slinky-9-gauge-strings.html << This shows a new product added to the shop, upon hovering over breadcrumb menu, all section menus resolve to www.barrymusicshop.com/.html rather than the actual category URLs.

![screen shot 2015-03-04 at 11 34 03](https://cloud.githubusercontent.com/assets/7206451/6482848/828b7c74-c262-11e4-9d92-41d636a035b5.png)

Here the cursor is hovering over 'Electric', yet the browser status suggests the broken URL mentioned above.

![screen shot 2015-03-04 at 11 35 43](https://cloud.githubusercontent.com/assets/7206451/6482868/b96c39cc-c262-11e4-90ea-71c802ad61c3.png)

Usual admin - maintentance - clear [all] caches doesn't resolve the issue.

**Comment by bhsmither** [comment]
This has been fixed in beta7 issue #314.

**Comment by abrookbanks** [comment]
Thanks Brian. Please let me know if the issue persists after B7.

**Comment by abrookbanks** [comment]
... we must be near final now. :)
