### ISSUE TITLE
Option Image Picker Not Working

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3180]
Even on your demo site, the Image Picker popup (as best I can tell) is not sending the 'message' event data to the main window.

**Comment by bhsmither** [comment]
It is working with this change. See:
```
https://forums.cubecart.com/topic/58252-trouble-assigning-images-to-options/#comment-253504
```

**Comment by abrookbanks** [comment]
Weird it's fine on my development store. I'll give it some testing.

**Comment by abrookbanks** [comment]
Thanks this works well.
