### ISSUE TITLE
No Option Image When Image Title Not Set

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3181]
With respect to #3147, in the element.product.horizontal_gallery.php (element.product.vertical_gallery.php) template, the `<img>` tag at line 15 (26) has `id="product_image"` and `id="img-preview"`.

`#img-preview` is used to manage the gallery hover special effect.

`#product_image` (used by #3147) appears only if `{$PRODUCT.image_tags.medium.title`} is set.

Also look at line 17 (29).

**Comment by abrookbanks** [comment]
Thanks. I believe this is fixed with 3d159ba832ace9ccec7b4882846056c05a2baca4
