### ISSUE TITLE
string name "upload_destination" is defined twice in definitions.xml

### ISSUE THREAD

**Issue by canoine** [cubecart/v6#3183]
Hello devs,

Not a real problem, but, in /language/definitions.xml, the same line appears twice, lines 1282 and 1286 :

`    <string name="upload_destination" introduced="6.1.2"><![CDATA[Upload Destination]]></string>
`

As I'm trying to keep the same line numbers into my french translation, the generated shift made me scratch my head some time. :)

**Comment by abrookbanks** [comment]
Good find. Thanks!
