### ISSUE TITLE
Code Check: Contents of a Variable

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3185]
In hookloader.class.php, near line 291, there is:
```
if (file_exists($this->_hook_dir.'/'.$hook['plugin'].'/'.$hook['filepath']) && $this->_security_check($hook['filepath'])) {
```
The function `_security_check()` will always return true, but could modify the `$hook['filepath']` variable.

However, the function `file_exists()` is using `$hook['filepath']` before the security check has its look at it.

In which order PHP executes these two function calls (compile vs run-time) is not known. But if the parts of the expression is performed left to right, then suggest that the security check do its job, then check if the hook file is where it should be (not necessarily where the database record says it is at).

I have not tested with bad 'filepath' strings.

**Comment by abrookbanks** [comment]
It also needed an `ltrim` to remove potential starting slash to prevent `/home/xxx/public_html/modules/plugins/xxx/hooks//hook.php`
