### ISSUE TITLE
Bad Argument

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3189]
In `GUI->_displayPopularProducts()`, if `DB->query()` returns an empty recordset (which it can, unlike `DB->select()`), the following `else` block sets `$vars` to "none".

In the skin template box.popular.php, a test is made for a true-like value for `{$POPULAR}`, which "none" satisfies.

Smarty then objects to this string expecting an array.

Suggest reviewing the history to determine if there is a need to keep "none" as a valid value for Smarty `{$POPULAR}`. (Maybe a CC5 skin?)

Otherwise, suggest:
```
            $vars = array();
            if ($products) {
                foreach ($products as $product) {
```
and deleting:
```
            } else {
                $vars = 'none';
```

**Comment by abrookbanks** [comment]
Can't see it on old skins. Thanks.
