### ISSUE TITLE
6.0.0b6 Shop Currency Symbol Missing

### ISSUE THREAD

**Issue by chilled35** [cubecart/v6#319]
![screen shot 2015-03-04 at 11 30 13](https://cloud.githubusercontent.com/assets/7206451/6482895/fbcd0de6-c262-11e4-96cf-447d6e0efbd0.png)

As shown above, the " & pound ; " should resolve with the correct £ symbol, likewise, attempting to change the currency, neither does the Yen or Euro symbol resolve, yet curiously, the pound symbol appears to in the cart total.

**Comment by bhsmither** [comment]
Please see issue #285.

**Comment by abrookbanks** [comment]
I think this is a valid bug but it can be fixed easily by just editing the currency symbol in the admin CP currencies section. The front end forces HTML entities so old values from upgrades of &pound; is no longer parsed as HTML. 

The upgrade script needs to modify these HTML encoded values to be a plain string..

**Comment by chilled35** [comment]
Re-jigged the currency symbols in the admin panel, sorted :)
