### ISSUE TITLE
Early Return Out of AJAX->search()

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3191]
In `AJAX->search()`, there is a hook, then a switch.

If the switch argument is not one of the cases, `default` returns out of the search method right at that point with a hard _false_. Or a hard _false_ if either method argument was empty.

Knowing that PHP cannot return out of a function directly from an included script (hook), the question is, how does the result of the custom search get returned out of the search method?

Not having a `default` case, execution would continue after the switch block and return out of the search method with json encoded `$data` (be that search results or an empty array).

However, the hook could be moved to be the statements of the `default` case. (PHP does not allow an include to be _**the**_ case block, but can be _**in**_ a case block.) A hook here allows for custom search location types. (But not overriding or overloading the existing search types: see #759.)

**Comment by abrookbanks** [comment]
Safest solution was to add a new hook as the original was suggested and most likely used by a developer.

**Comment by bhsmither** [comment]
The added hook is appropriate to find other data. But the default case **_still_** returns out of `Ajax->search()` with a hard _false_. Is this desirable?

This means the hook can only **do** something (such as _push_ data out), but not respond with data via the `$data` variable - like all other cases.
