### ISSUE TITLE
No IP address logged

### ISSUE THREAD

**Issue by hukala** [cubecart/v6#3192]
In includes\functions.inc.php, there is function get_ip_address() for various purposes. But in our current installation of 6.4.9 version, it doesn't work.
In admin panel ...?_g=settings&node=logs#logs_admin, I see logins without ip address. We also get notifications through Security Suite plugin withou IP addresses. 
It was working until december of 2019 when we upgraded Cubecart to some of previous versions, I don't know which one.
Is it because of special setting or because of server hosting configuration or is it a bug?

**Comment by bhsmither** [comment]
In admin, at the bottom of the Navigation pane, click on PHP Info. Scroll down that screen to the 'PHP Variables' table near the bottom.

Find any of these variables: 'HTTP_CLIENT_IP', 'HTTP_X_FORWARDED_FOR, 'HTTP_X_FORWARDED', 'HTTP_FORWARDED_FOR', 'HTTP_FORWARDED', 'REMOTE_ADDR'.

Also see #2336.

**Comment by hukala** [comment]
HTTP_CLIENT_IP, HTTP_X_FORWARDED, HTTP_FORWARDED_FOR nor HTTP_FORWARDED doesn't exists, HTTP_X_FORWARDED_FOR is defined and also REMOTE_ADDR / $_SERVER['REMOTE_ADDR'], both are ipv4 addresses. But
HTTP_X_FORWARDED_FOR is doubled: 90.64.73.64, 90.64.73.64
I don't know why. HTTP_X_REAL_IP and REMOTE_ADDR / $_SERVER['REMOTE_ADDR'] is only 90.64.73.64

**Comment by bhsmither** [comment]
The function will use 'HTTP_X_FORWARDED_FOR first, if found, regardless what it is. Later, whatever it is is filtered against what PHP expects a IPv4 to look like.

Versions of CubeCart from CC625 and before, did make sure that a 'comma-separated multiple IP address' value had only the first address used - assuming this is the real client's address versus any other address that proxies add onto.

So, for you, skip over the possibility of using the doubled address value:
```
From:
    $ip = getenv('HTTP_CLIENT_IP')?:
    getenv('HTTP_X_FORWARDED_FOR')?:
    getenv('HTTP_X_FORWARDED')?:
To:
    $ip = getenv('HTTP_CLIENT_IP')?:
//  getenv('HTTP_X_FORWARDED_FOR')?:
    getenv('HTTP_X_FORWARDED')?:
```
For this issue, suggest adopting CC625's explode on comma.

**Comment by hukala** [comment]
Thanks, works.

**Comment by abrookbanks** [comment]
Is this with Apache?

**Comment by hukala** [comment]
No idea. I have not changed anything explicitly, but maybe when I upgraded Cubecart, I needed to change PHP/Apache version within my provider configuration of website and some settings changed there. Who knows.
Maybe someone knows which PHP/Apache setting is connected to IP address providing.,
