### ISSUE TITLE
Data for Math - SQL Check

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3196]
In statistics.index.inc.php, near line 170, a query gets the quantity sums of each product **sold** found in the CubeCart_order_inventory table. That is, 'Processing' or 'Complete'.

Later, another query gets the quantity sum of all products found in the CubeCart_order_inventory table. That is, _all order statuses_.

Suggest this `$divider` quantity sum be only for all products **sold**.

**Comment by abrookbanks** [comment]
Good find. Thanks.
