### ISSUE TITLE
PHP8 and count()

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3197]
In `DB->numrows()`, a test is made against `$this->result` for being not empty. If so, `count()` is made on that result.

However, in `mysqli.class.php`, near line 219, a test is made against `$result` (the answer back from the database having executed the query).

If `$result` is true-like, the next line tests if `$result` is boolean. Obviously, it has to be _true_. Thus `$this->_result` gets set to _true_.

A boolean _true_ is not valid for `count()` and PHP faults with a Fatal Error.

**Comment by bhsmither** [comment]
One might ask, why call `DB->numrows()` after sending a query that is expected to return a boolean.

This was experienced with a bad query that caused the database server to return an error. The Debug class got involved and inserted a record into the error log table, which then caused `$this->_result` to be _true_. Additionally, the error log tables were trimmed of outdated records, which also made `$this->_result` _true_.

Then when execution resumes in `DB->numrows()`, with `$this->_result` having been compromised, PHP crashes.

**Comment by abrookbanks** [comment]
Check against array for count and alway return a consistent int. In any tests 0 should (still hopefully) be considered false. 

Keeping up with PHP these days is hell.
