### ISSUE TITLE
Q: Bouncing POST to Querystring

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3200]
Since CC500, in statistics.index.inc.php, there is:
```
if (isset($_POST['select']))
{
	httpredir(currentPage(null, $_POST['select']));
}
```
If there are notes as to why this is required/desired, please share them.

**Comment by bhsmither** [comment]
My thoughts about this involves the persistence of the querystring vs. the POST payload, when fetching page 2, etc.

**Comment by abrookbanks** [comment]
A good find. Thanks!
