### ISSUE TITLE
PHP8.2 - Series of Warnings

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3203]
In database.class.php, near line 1030, `$this->_error` is a deprecated 'dynamic property'. That is, it was not declared in the class header.

**Comment by bhsmither** [comment]
The Dynamic Properties issue can be mitigated by setting a class attribute. See:
```
http://docs.php.net/manual/en/migration82.deprecated.php
```
It should be known that `__set()` and `__get()` will still throw a deprecated error if creating a class attribute inside these functions. That is, you can't rely on `__set()` to dynamically set an undeclared variable within `__set()` itself.

**Comment by bhsmither** [comment]
In cart.class.php, near line 426, `$stock_warning` could be undefined. Suggest adding a statement near line 291:
```
$quantity = (is_numeric($quantity) && $quantity > 0) ? $quantity : 1;
$stock_warning - false;
```

**Comment by bhsmither** [comment]
In cart.class.php, line 755, `$this->_total_tax_add` has not been declared as a class attribute. Suggest adding after line 77:
```
    private $_total    = 0;
    /**
     * Cart taxes added (not used - for the benefit of hooks?)
     *
     * @var float
     */
    private $_total_tax_add = 0;
```
Perhaps residue from before getting a separate Tax class?

**Comment by bhsmither** [comment]
In tax.class.php, line 440, starts looping through the tax table. If nothing in the table applies, lines 441-469 never gets executed.

Thus, the `return` at line 471 has the undefined variables `$amount`, `$tax_name`, and `$percent`.

**Comment by bhsmither** [comment]
In cubecart.class.php, line 660, `$this->basket` may not yet have the array structure the statement is asking for.

An experiment such that:
```
$basket = array();
$echo = $basket['key1']['key1A']['key1A1']['key1A1a']??'a key is missing';
echo $echo;
```
produces the output "a key is missing". This experiment implies that no matter how deep into an array one is trying to get to, the Null Coalescing Operator seems to work on the whole thing.

So, testing for `isset()` against each level of the array seems to be unnecessary.

Suggest:
```
if ($_GET['_a'] == 'basket' && $this->_basket['billing_address']['user_defined'] ?? false) {
```
Also, lines 696 and 697.

**Comment by abrookbanks** [comment]
Another PHP version another boatload of ballache... 

I expect _total_tax_add is residue but safest to keep in.

**Comment by abrookbanks** [comment]
@bhsmither - I'd be **hugely grateful** if you can review my changes for this one, especially concerning https://github.com/cubecart/v6/issues/3203#issuecomment-1475703698

**Comment by bhsmither** [comment]
In SEO class, `$this->_url`, a class property, is being dynamically created. Suggest adding after line 84:
```
    private $_sitemap_base_url = '';
    /**
     * Standard Dynamic URL
     *
     * @var string
     */
    private $_url = '';
```

**Comment by bhsmither** [comment]
In Cart class, near line 954, there is:
```
if (isset($this->basket[$tax_on]['state_id']) && isset($this->basket['shipping'])) {
    $GLOBALS['tax']->productTax($this->_shipping, $this->basket['shipping']['tax_id'], false, $this->basket[$tax_on]['state_id'], 'shipping');
}
```
It may be the case that, even though `$this->basket['shipping'] is set, `['tax_id']` is not.

Suggest:
```
if (isset($this->basket[$tax_on]['state_id']) && ($this->basket['shipping']['tax_id'] ?? false)) {
```
The parentheses around the Null Coalescing Operator expression is needed because it has lower precedence than `&&`.

**Comment by bhsmither** [comment]
In many admin source files, there is:
```
$GLOBALS['smarty']->assign('PLUGIN_TABS', $smarty_data['plugin_tabs']);
```
where ['plugin_tabs'] only comes into existence from the hook just above it.

Suggest:
```
$GLOBALS['smarty']->assign('PLUGIN_TABS', $smarty_data['plugin_tabs'] ?? false);
```

**Comment by bhsmither** [comment]
In All_in_One_Shipping class, `$this->_db`, a class property, is being dynamically created. Suggest adding after line 15:
```
class All_In_One_Shipping {
  private $_db;
```
Probably need to check all modules that want to use the database.

**Comment by bhsmither** [comment]
In Cubecart class, near line 1806, there is:
```
if (isset($this->_basket['shipping']) && $this->_basket['shipping']['offset'] == $offset) {
```
It may be the case that, even though $this->basket['shipping'] is set, ['offset']` is not.

Suggest:
```
if (($this->_basket['shipping']['offset'] ?? false) == $offset) {
```

**Comment by bhsmither** [comment]
In `Cubecart->_download()`, near line 2164, `FileManager->getFileInfo()` could return false or an array that might not contain the key ['stream']. If false, PHP will complain about trying to convert a false to an array.

Suggest:
```
$download['file_info'] = $filemanager->getFileInfo($download['product_id']) ?: array(); // Make sure this is an array
if(($download['file_info']['stream'] ??= 0)==1) { // Make un-streamable if FileManager does not otherwise indicate - for template
```

**Comment by bhsmither** [comment]
In the Request class, `$this->_request_path` is being dynamically created.

**Comment by bhsmither** [comment]
In the Admin class, near line 407, _but not used anywhere else_, `$this->_blocked` is dynamically created. Maybe exists for a hook's benefit?

**Comment by bhsmither** [comment]
In Archive class, `$this->_zip is being converted to an object, but was initialized as boolean false.

PHP complains about auto-converting false to array, so maybe also false to object. (Not verified.)

**Comment by abrookbanks** [comment]
Closing for now. This will be ongoing.
