### ISSUE TITLE
Upgrade Smarty to Latest Version

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3204]
As above.

**Comment by bhsmither** [comment]
The latest version (4.3.0) will complain about the use of PHP functions **as modifiers** - not to rely on Smarty continuing to allow (most?) functions as variable modifiers.
The following statements would need attention. Suggest massaging these variables in PHP.
```
Foundation:
\templates\box.off_canvas.left.php(44)
\templates\element.markup.json-ld.php(1)
Admin:
\templates\orders.paypal-tooltip.php(1)
\templates\products.index.php(200)
\templates\products.index.php(232)
\templates\filemanager.index.php(72)
\templates\settings.language.php(106)
\templates\products.importing.php(15)
\templates\statistics.index.php(234)
\templates\plugins.index.php(53)
```
Apparently, one can still use PHP functions using the PHP function signature. For example, in admin template products.importing.php, line 15:
```
From:
<p>{$LANG.catalogue.importing_progress|sprintf:$DATA.imported:$DATA.total}</p>
To:
<p>{sprintf($LANG.catalogue.importing_progress,$DATA.imported,$DATA.total)}</p>
```

**Comment by abrookbanks** [comment]
I'm not seeing any complaints about piped functions (modifiers) after upgrade.

**Comment by bhsmither** [comment]
Re-asserting this.

**Comment by abrookbanks** [comment]
Thanks again Brian.

**Comment by bhsmither** [comment]
In this code, as it currently exists, in products.index.php, line 241, there is:
```
From:
<label for="category_{$k}">{$k|ucfirst}</label>
To:
<label for="category_{$k}">{ucfirst($k)}</label>
```

**Comment by abrookbanks** [comment]
Fantastic thanks.

**Comment by bhsmither** [comment]
Please check line 224 in customers.index.php:
```
		  <span class="capitalize">{$address.line1}, {if !empty($address.line2)}{$address.line2}</span>, {/if}<span class="uppercase">{$address.town}</span>, {if !empty($address.state_name)}{$address.state_name}, {/if}</span>{$address.postcode}, {$address.country_name}
```
The first closing `</span>` is inside an `{if}` block.

And the last closing `</span>` tag has no matching opening `<span>` tag.

**Comment by abrookbanks** [comment]
Thanks Brian.
