### ISSUE TITLE
Related OOS Faults PHP

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3205]
In Cubecart class, near line 1920, the code iterates across the collection of related products. If a related product is out of stock, or has no enabled assigned category, the call to `Catalogue->getProductData()` returns false.

Thus, for the remainder of that loop, PHP complains about `$related` having "offsets on bool", "conversion of false to array", etc.

Suggest testing the return of `getProductData` for false and continuing to the next related item.

Also suggest, for the initial query for `$related_products`, that the number of records requested (hard-coded for three???) be increased (doubled?), then process only three **in-stock** results.

**Comment by abrookbanks** [comment]
Fixed with c542650fa204228eec3199bf303947136b75c1c4
