### ISSUE TITLE
DebugConsole for All

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3206]
In Foundation 2.cubecart.js, a function is provided for the call `debugConsole()` that is pasted into the output generated by `Debug->display()`.

Suggest making this function universally available no matter what skin is being used. (Unless you have reasons.)

Which probably means to:
paste the actual function onto the `$output` array, or
echo it out, such as (Debug class, starting at line 376):
```
} else {
    echo '<script type="text/javascript">
    function debugConsole(content) {
    _cubecart_console = window.open("", "console:cubecart_debug", "width=1024,height=600,left=50,top=50,resizable,scrollbars=yes");
    _cubecart_console.document.write(`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"><head><title>CubeCart Debug Console</title><style>body{margin:0}</style></head><body>`+content+`</body></html>`);
    }
</script>';
```
Then, delete the function from the skin's javascript file.

**Comment by abrookbanks** [comment]
Good plan!! Thanks.
