### ISSUE TITLE
Rogue Smarty Variable

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3207]
In the admin template customer.index.php, line 160, there is, at the end of the line:
```
{$CUSTOMER.subscription_status}
```
This will not display on the web page, as it is between a `<select><option>` sequence, but because it is an array, Smarty will issue a warning "Array to string conversion".

(Probably came about from #2747.)

**Comment by abrookbanks** [comment]
Thanks! It's surely a mistake.
