### ISSUE TITLE
Logic Check

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3208]
In the admin source categories.index.inc.php, near line 457, an `if()` block tests three things. Any one of those things could be false, causing the `else` block to execute.

One of those things tested is `isset($_GET['parent']`. It might not be set.

Yet, that is the thing that the `else` block wants to use.

Suggest starting with a test for `$_GET['parent']` with a common query, then `if/else` against `$category_list`.

**Comment by abrookbanks** [comment]
Thanks.
