### ISSUE TITLE
Plugins Present but not Setup

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3211]
In `Hookloader->scan_all_plugins()`, a collection of folders comes from globbing the plugins folder.

If there exists a folder that has not been processed - that is, there is no row for it in the CubeCart_config table - PHP complains that array key ['status'] is undefined.

Suggest:
```
From:
if (!$plugin['status']) {
To:
if (!($plugin['status'] ?? false)) {
```

**Comment by abrookbanks** [comment]
Thanks.
