### ISSUE TITLE
Misplaced Return

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3212]
In `FileManager->getFileInfo()`, if the `$product` has something in the `digital_path`, then the `else` block starting at line 941 executes.

However, if neither the `if(URL)` block nor the the `elseif(exists)` block execute, `$data` will be unknown when returning out of the function.

Suggest putting `return $data;` inside the `elseif(exists)` block. Then, program execution can fall through to `return false;`.

**Comment by abrookbanks** [comment]
Thanks
