### ISSUE TITLE
Using an Apostrophe in Description Breaks Layout

### ISSUE THREAD

**Issue by SteveCGS** [cubecart/v6#3223]
If I use an apostrophe in the main description, part of the description text appears at the top of the page.

I can't use & a p o s ; because the editor changes it back to & # 3 9 ;

![apostrophe-error](https://user-images.githubusercontent.com/23212582/228346003-3c8963b4-26fa-46d2-aadf-c93215a59226.jpg)

Screenshot attached.

**Comment by abrookbanks** [comment]
That's odd because it should be HTML encoded. Are you on the latest version and if so when you edit the product and save does it fix it?

**Comment by abrookbanks** [comment]
I can't reproduce this. I believe this needs to be looked at as a support case situation.
