### ISSUE TITLE
reCAPTCHA challenge configuraiton

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#323]
I think there is room for an enhancement here, but not urgent.

If reCAPTCHA is enabled, but the keys have not been configured a reCAPTCHA challenge is still presented to the user but it is not possible to complete the challenge.

the CAPTCHA challenge should only be presented if the configuration is complete.

**Comment by abrookbanks** [comment]
Latest build should cater for this already;

```
{if $RECAPTCHA==='2'}
      {if empty($CONFIG.recaptcha_public_key) || empty($CONFIG.recaptcha_secret_key)}
      <p>reCAPTCHA public and/or private key has not been set!</p>
      {else}
      <div class="g-recaptcha" data-sitekey="{$CONFIG.recaptcha_public_key}"></div>
      {/if}
{else}
```
