### ISSUE TITLE
CubeCart v6.5.1 not working on PHP 7.1

### ISSUE THREAD

**Issue by pinalgirkar** [cubecart/v6#3230]
Hello,

I was in the process of manual installation of _**CubeCart 6.5.1**_ on **CentOS-7(Core) with _PHP 7.1.33, MYSQL 5.7.37 , Apache 2.2.34._**

However after successful installation, when I try to access the _store front page_ and _admin panel_ it shows the blank page. When we increase the _**PHP version to**_ _**7.4**_ and it loads perfectly fine.

What could be the issue?.

Could you please replicate this issue on your end and fix this?.

**Note:-** System requirements link which was followed (https://www.cubecart.com/hosting-requirements)

**Comment by abrookbanks** [comment]
Yes. PHP has moved SO fast in the last six months is been a headache keeping up.

Related: https://github.com/cubecart/v6/issues/3227 

The hosting page has been updated. Thanks.
