### ISSUE TITLE
Code Check: Smarty Variable?

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3232]
In element.markup.json-ld.php, near column 951, there is:
```
{literal}?search%5Bkeywords%5D={search_term}&_a=category","query-input":"required name=search_term"}}{/literal}
```
Is `{search_term}` supposed to be a Smarty variable? Or is this the proper syntax for whatever consumes this data structure?

**Comment by abrookbanks** [comment]
I think it's supposed to be like this?

<img width="1467" alt="Screenshot 2023-03-31 at 15 16 18" src="https://user-images.githubusercontent.com/4520803/229146055-1417ede2-403d-4b9c-8534-4625f6a6494d.png">

**Comment by abrookbanks** [comment]
Closing as I think it's correct.
