### ISSUE TITLE
Options Can Be Multiple Selectable

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3237]
In `Catalogue->defineOptionsIdentifier()` (and possibly elsewhere), the `$optionsArray` might be an array of arrays -- specifically if an option group is a collection of same-named checkboxes (or, for whatever reason, a collection of hidden inputs having the same name attribute).

Therefore, suggest:
```
Line 204, from:
foreach ($optionsArray as $value) {
  if (is_numeric($value)) {
    $assign_ids[] = $value;
  }
}
To:
foreach ($optionsArray as $value) {
  if (is_numeric($value)) {
    $assign_ids[] = $value;
  }
  if (is_array($value)) {
    foreach ($value as $val) $assign_ids[] = $val;
  }
}
```

**Comment by abrookbanks** [comment]
Thanks
