### ISSUE TITLE
GA Plugin, Attribute Value

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3239]
In the GA plugin, the module.definitions.xml has, as a definitions group name, `google_base`.

(Regardless that the Google Base plugin seems to have disappeared) Suggest the value of this attribute be `google_analytics`.

**Comment by bhsmither** [comment]
Also, code check:

In the hook class.gui.head_js.php, line 19 and 24, the use of `{$ga_config['UA_ID']}` seems appropriate.

However, line 22 has `{dataLayer.push(arguments);}` which violates Smarty's requirement that non-Smarty code requires whitespace inside of braces, or must use `{literal}`.

**Comment by abrookbanks** [comment]
Fixed with 1.0.3.
