### ISSUE TITLE
Help: Find $lang

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3241]
_For the storefront_, nowhere is found any code that sets `$GLOBALS['lang']` (aka and is the same as `$lang` in the global scope). 

Help?

**Comment by bhsmither** [comment]
I say this variable does not get set in the storefront. To test:

In controller.index.inc.php:
```
At about line 97, add this statement:
var_dump($GLOBALS['catalogue']->_optionDescriptions()); die(); // assuming the method is still public
```
The output will be:
```
array (size=9)
  0 => null
  1 => null
  2 => null
  3 => null
  4 => null
  5 => null
  6 => null
  7 => null
  8 => null
```
with the associated errors logged:
```
Warning:  Undefined global variable $lang
Warning:  Trying to access array offset on value of type null
```

**Comment by abrookbanks** [comment]
Thanks.

**Comment by bhsmither** [comment]
Suggest also not to use `$lang` but instead `$GLOBALS['language']` at:
filemanager.class.php (239)
mysqli.class.php (260)
controller.admin.session.false.inc.php (21, 31, 33)
controller.admin.session.true.inc.php (50, 98)

Note that filemanager.class.php, line 239 is in `assignProductImages()`, which currently is used only in admin products.index.inc.php. Thus, use of `$lang` here conforms to the general use of `$lang` everywhere in admin. But, since `assignProductImages()` is accessible from anywhere, including the storefront, using `$GLOBALS['language']` should be preferred.

Also note that in mysqli.class.php, line 260 is in the function `_setup()`, which is called from the storefront context (as well as admin). If `_setup()` needs to die, nothing will show because of using `$lang`.

**Comment by abrookbanks** [comment]
Thank you.
