### ISSUE TITLE
PHP 8.2 Deprecation

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3242]
Continuing with #3203:

Debug class with respect to `$this->_messages`.

**Comment by bhsmither** [comment]
In admin sources file settings.language.inc.php, near line 249, suggest:
```
if (!preg_match('/^(modules)/', $_REQUEST['type'] ?? '')) {
```

**Comment by abrookbanks** [comment]
Thanks so much!! :)

**Comment by bhsmither** [comment]
I think this was overlooked:
Dynamic assignment in Debug class with respect to `$this->_messages`.

**Comment by abrookbanks** [comment]
Thanks... I'll check on Monday

**Comment by bhsmither** [comment]
In cubecart.class.php, near line 1603, because the key 'parse' might not yet be known, suggest:
```
(($contact['parse'] ?? '0') =='1')
```

**Comment by abrookbanks** [comment]
Thanks!!
