### ISSUE TITLE
Feature request - who had bought this product?

### ISSUE THREAD

**Issue by hairy-dog** [cubecart/v6#3245]
This is an issue for me yet againn. I want to be able to see who has bought a particular product. 

As things stand I can either write a database query to list the orders that contain a specified product, or I can look at each of the orders in turn to look for the product in question. Either approach is a bit of a pain.

I'm sure I'm not the only person who needs this facility. Why isn't it a part of CubeCart?

**Comment by harris-organic** [comment]
Could this request be part of a larger query to the Cubecart database? 
Asking the right sales queries of a database can help you better understand your customers and prospects, identify opportunities, and close more deals. Here are some sales queries you may want to ask of a database:

Demographic data: Who are your current customers and prospects? What is their age, gender, location, and occupation?

Buying behavior: How do your customers and prospects buy? What triggers their buying decisions, what are their pain points, and what are their budgets?

Customer interactions: How have your customers and prospects interacted with your company in the past? What products or services have they purchased, how often do they buy from you, and what feedback have they provided?

Sales pipeline: What is the current status of your sales pipeline? How many leads are in each stage of the sales process, and what is the conversion rate at each stage?

Sales performance: What is the performance of your sales team? How many deals have they closed, what is the average deal size, and what is the win rate?

By asking these types of sales queries of your database, you can gain valuable insights into your customers and prospects, as well as your sales process and performance. This can help you make data-driven decisions to improve your sales and drive business growth through Cubecart.
Is there scope for this?

**Comment by abrookbanks** [comment]
Lets do this..

**Comment by abrookbanks** [comment]
<img width="761" alt="Screenshot 2023-04-21 at 14 58 19" src="https://user-images.githubusercontent.com/4520803/233655112-e481ec03-11fe-4928-8f6f-e513ca871e81.png">

**Comment by abrookbanks** [comment]
<img width="111" alt="Screenshot 2023-04-21 at 15 04 18" src="https://user-images.githubusercontent.com/4520803/233656493-14bfe41b-9925-4694-9400-2b9bb9bba149.png">

**Comment by hairy-dog** [comment]
It would be good if the "Total sales" number was a link to a list of orders that included the product. Basically a drill down to see the number as a list.

**Comment by abrookbanks** [comment]
Great idea!

**Comment by harris-organic** [comment]
Could a dated filtered report become of this idea?
ie
![image](https://user-images.githubusercontent.com/13449078/233752575-9b141891-97cb-4e11-bc2e-913f7eb338f9.png)

Having the ability to sort each column would be even better, however, to download the data to a CVS file would also suffice.

**Comment by abrookbanks** [comment]
Looking good now. @harris-organic I'll give a bit of thought into this. We could add start and end dates onto the products stats page maybe with quick links to last 12 months etc..
<img width="875" alt="Screenshot 2023-04-26 at 16 36 12" src="https://user-images.githubusercontent.com/4520803/234627589-5f3bf6fd-d2df-496e-85cb-2090db44a0d3.png">

**Comment by bhsmither** [comment]
Please check the edits made to DB->select(). The `@param` details seem to be mixed up, compared to what the function signature says.
https://github.com/cubecart/v6/commit/eb910c440a6287493221a092c82ab16ea02bf829#diff-4e8dc33154e96a6f40e9d0bb5933a10f038ebc6e49208009f6609eaa784829dd

Suggest:
```
     * @param bool $cache
     * @param array $group_by
     * @return array|false
```

**Comment by bhsmither** [comment]
Also in DB-select(), this edit now at line 730:
```
$this->_found_rows = (count($count)>1) ? count($count) : $count[0]['Count'];
```
The variable `$count` contains a two-dimensional array of integers. This statement seems to say, If the number of array elements is greater than one, then use the number of array elements - _regardless of the values in those elements_. Otherwise, use the _value_ in element[0].

Suggest:
```
$this->_found_rows = (count($count)>1) ? array_sum($count) : $count[0]['Count'];
```
(I have not verified this works on a two-dimensional array, but the function's docs don't say it won't.)

Actually, using `array_sum()` by itself should work.

**Comment by abrookbanks** [comment]
I think itay be best to remove the group by parameter and use the query function instead. I'll do this tomorrow.

**Comment by bhsmither** [comment]
Not that it matters, but language phrase 'orders.per_order' was introduced in 6.5.2.

**Comment by bhsmither** [comment]
I think #2596 solved this.

So, the query could be something like:
```
$customers = $GLOBALS['db']->select(
  '`CubeCart_order_inventory` AS `I`
     INNER JOIN `CubeCart_order_summary` AS `S`
     ON `I`.`cart_order_id` = `S`.`cart_order_id`
     INNER JOIN `CubeCart_customer` AS `C`
     ON `S`.`customer_id` = `C`.`customer_id`',
  array('DISTINCT'=>'`S`.`customer_id`', '`C`.`first_name`', '`C`.`last_name`', 'SUM'=>'`I`.`quantity`'),
  '`S`.`status` IN(2,3) AND`I`.`product_id` = '.(int)$_GET['product_id'],
  'SUM(`I`.`quantity`) DESC',
  $per_page,
  $page,
  false,
  array('`S`.`customer_id`'));
```
Scratch the above. Came up on some limitations in DB-select() that makes the above difficult if not impossible. I will still experiment.

**Comment by bhsmither** [comment]
The latest edit to statistics.product.inc.php has a hard-coded `'product_id' = 10` component.
https://github.com/cubecart/v6/commit/f87f6d900de5a5bf597770f596470b98a7fbe0d4#diff-d76d4f6142b4357235c9df49f90e421480967c9780979a66eae033eda96bf2f6

**Comment by abrookbanks** [comment]
Ha! Whoops. Good job you are on the ball!!!

Thanks.
