### ISSUE TITLE
Code Check: Un-named Form Element

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3246]
In the admin skin template settings.tax.php, near line 161, there is an input with no name attribute, using the Smarty variable `$FORM_HASH`.

The only code that assigns a value to $FORM_HASH is in products.index.inc.php.

Other than the corresponding template products.index.php, there are three more templates that has $FORM_HASH but no corresponding code that assigns a value to it.

**Comment by abrookbanks** [comment]
I think this was something experimental that got left in and stupidly copied to other forms.

I've removed it.. lets see if there is any collateral damage.
