### ISSUE TITLE
Exception on Auto-Upgrade

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3249]
In the admin sources file maintenance.index.inc.php, line 63, use of PHP's function `fread()` is made against all the files in the downloaded CubeCart-6.5.1.zip file.

PHP's `fread()` function must have the value for the second parameter, `length`, to be greater than zero.

It seems there are _at least_ two files in the package that are zero-length:
/classes/elasticsearch/vendor/hamcrest/hamcrest-php/generator/parts/functions_footer.txt
/classes/elasticsearch/vendor/hamcrest/hamcrest-php/generator/parts/functions_imports.txt

Because the values of parameters of `fread()`, at this location in the code, is to get the entire file read into a variable, suggest either:
```
$v_content = fread($v_file, filesize($file) + 1);
```
or use `file_get_contents()`, or check the filesize first and, if zero, just assign a zero-length-string to `$v_content`.

The function `fread()` will stop reading when the operating system indicates the EOF, so assuring the value of the second parameter is greater than zero, at this location in the code, is inconsequential.

**Comment by bhsmither** [comment]
Please re-examine your fix:
```
$filesize = filesize($file);
$v_content = ((int)$file_size > 0) ? fread($v_file, $filesize) : '';
```
The test is using `$file_size` which is the **wrong name** of the variable holding the size of the file.

**Comment by abrookbanks** [comment]
This is exactly the kind of QA CubeCart needs. Thanks so much Brian.
