### ISSUE TITLE
Debug Contents

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#325]
There is various code that adds, changes, or deletes POST and GET array elements. By the time Debug->display() is executed, these arrays may have changed from what was actually POSTed or GETed.

But the RAW arrays have not.

Request an enhancement that Debug->display incorporate the RAW sub-arrays. For example:
```
GET:
'seo_path' => 'path-to-cat1' [RAW]
```
-- if they don't already still exist in GET.

**Comment by bhsmither** [comment]
I also have a headache with `Debug->_makeExport()` where `var_export()` is used.

I would surround it with `<pre>` and wrap it in `htmlspecialchars()` as well, just in case `$value` happens to contain valid HTML.

**Comment by bhsmither** [comment]
I'm using, for now:
```
//Get the super globals
if (($ret = $this->_makeExportString('GET', merge_array(array('Initial:' => $GLOBALS['RAW']['GET']), array('Final:' => $_GET)))) !== false) {
  $output[] = $ret;
}
```

**Comment by abrookbanks** [comment]
I like this. Thanks Brian.
