### ISSUE TITLE
404 on Auto Upgrade

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3250]
In admin sources file maintenance.index.inc.php, line 273, the browser is told to fetch the page at `/setup/index.php?autoupdate=1`.

In setup/index.php, line 603, starts a `foreach()` loop that sets to read-only all files that match the pattern for the global settings file(s).

We know that the `foreach()` function does not unset the variables used for the key and the value when exiting the loop.

Thus, `$global_file` at line 615 might hold the filename _of a past version_ of the global settings file - a version where the value of the `$glob['adminFile']` and `$glob['adminFolder']` is not current.

If so, that results in a 404 response.

Suggest using a different variable name for the `foreach()` loop's value.

**Comment by abrookbanks** [comment]
Good find. Thanks!
