### ISSUE TITLE
Use Cache for Requests

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3253]
In admin, the Cache is switched off.

When adding/editing a product, a Request is made to Google's taxonomy. The Request's response is set to be cached.

However, reading and writing to the cache, being switched off, fails.

Suggest to test on `Cache->read()` and `->write()` if the `$id` contains 'request':
```
if (!$this->status && !preg_match('/^request\./', $id)) { // cannot use cache
```

**Comment by abrookbanks** [comment]
And `->exists()`

**Comment by abrookbanks** [comment]
Absolutely excellent find!
