### ISSUE TITLE
Feature Tweak: Notify Admin on Store URL Rename

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3258]
During install/upgrade, in Setup near line 552, begins the code to rename the admin.php script and admin folder. This section of code has a step to email the admins a message.

This step is hard-coded to use PHP's `mail()` function. In turn, PHP requires its PHP.INI file to have the info that points to an installed client or other MTA.

Consider that, even though it is common, a server environment is not required to have such a capability. (PHP does not crash if there is nothing to accept the `mail()` message.)

Suggest, that if there are Config elements that suggest an established email configuration, to use it (PHPMailer).

**Comment by abrookbanks** [comment]
This is definitely a good idea but really it's a "nice to have". Closing for now for higher priorities. 

Thanks again Brian. I'm very appreciative for all your contributions.🙌🏻
