### ISSUE TITLE
Code Check: Extension Info

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3260]
On a very fresh install, visiting the Dashboard for the first time, CubeCart_extension_info has records for AIOS and PPC.

However, CubeCart_modules will only have a record for AIOS.

In dashboard.index.inc.php, near line 131, starts code that does some housekeeping.

The `$status` variable could come back as _false_ when an extension has not been setup.

PHP complains on line 138.

Suggest testing `$status !== false` or force a value:
```
... 'folder' => $parts[3])) ?: array(0 => array('status' => 0));
```

**Comment by abrookbanks** [comment]
Thanks
