### ISSUE TITLE
Code Check: Statistics - Search Terms

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3261]
In statistics.index.inc.php, near line 244, `$smarty_data[7]` is created. But then, this code switches to using `$smarty_data['search_terms']`.

Suggest either:
```
From:
$smarty_data[7] = array();
To:
$smarty_data['search_terms'] = array();
```
or move away from numeric indexes and use the name of the section being graphed (i.e., [8] is ['best_customers']).

**Comment by abrookbanks** [comment]
Thanks.
