### ISSUE TITLE
Styling: Email Log .row_error

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3263]
In admin layout.css, near line 658, there is:
```
tbody tr:nth-child(even) td {
    background-color: #edf4f7
}
```
Near line 1258, there is:
```
.row_error {
    background-color: #FF0000;
    color: #fff;
    padding-left: 5px;
    border-bottom: 25px solid #FFF;
}
```
In statistics.emaillog.php, there is:
```
		{if !empty($log.fail_reason)}
		<tr>
			<td class="row_error" colspan="9">{$log.fail_reason}</td>
		</tr>
		{/if}
```
For every time a table row gets added to show the fail reason, then the table striping becomes skewed such that any fail reason row could become the 2n'th row.

Generally, a css rule that comes after any other css rule overrules - the background-color in this case. However, 'specificity' causes `tbody` to have priority.

Suggest `.row_error` to have `!important` at least on `background-color`.

**Comment by abrookbanks** [comment]
Thanks!!!!!
