### ISSUE TITLE
Tweak: Editable Field

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3264]
In orders.index.php, near line 417, I made this edit:
```
From:
<span class="editable" name="inv[{$product.id}][name]">{$product.name}</span>
To:
<span style="display:inline-block;width:98%;" class="editable" name="inv[{$product.id}][name]">{$product.name}</span>
```
This makes the entire width of the table cell recognize that there is a mouse hovering in it, instead of just over the text.

Then, in admin.js, near line 839, I did:
```
From:
var e = $(this).attr("name")
To:
var e = $(this).attr("name"), s = $(this).attr("style"),
```
This captures the style of the span, to be used for the `<input>` as follows, near line 853:
```
From:
$(a).addClass("textbox"), $(a).attr("name", e), $(this).replaceWith(a)
To:
$(a).addClass("textbox"), $(a).attr("name", e), $(a).attr("style", s), $(this).replaceWith(a)
```
I passed over the width:98%, otherwise `table#order-builder .textbox` gives only 100px.

**Comment by abrookbanks** [comment]
Fantastic thank you.
