### ISSUE TITLE
Code Check: Remote Page

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3268]
Inconsequential: 

In the Cubecart class, working through the `_a` switch, there is no specific case for 'remote' or 'rm'. Nor is there a private function to catch it.

In the SEO class, 'remote' is found in the `$_ignored` array.

For its intended purpose (using `_g` to call extension methods), I do not see the reason why there would be `_a=remote`.

But if there was an extension that needed SEO to ignore this page, that extension could use `addIgnore()`.

**Comment by abrookbanks** [comment]
Sorry I'm completely lost. What are you suggesting?

**Comment by bhsmither** [comment]
Maybe this was just an observation - seeing that there is 'remote' in the `_ignored` array, so _perhaps there was supposed to be_ a matching switch case, to join the other switch cases seen in `_ignored`, and/or a matching private function to join the other private functions that deal with the `_a` querystring key.

Taking this further, the `_ignored` array does **not** have:
404, cancel, cart, document,  category,
newsletter, template, vieworders, orderhistory

Maybe, on 4/23, when I noticed #3267, I was just in a mood to be consistent and complete - whether or not it is important that SEO "ignore" these `_a` values.

**Comment by abrookbanks** [comment]
Thanks for sharing but I think, as all works ok, we can leave it as is.
