### ISSUE TITLE
Mobile Skin Support.

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#327]
It looks like support for mobile skins is not in CC6, but was in CC5.

In CC5 two options were available:
Default front-end mobile skin 
and 
Disable mobile skin

in CC6 neither options exist and when you use a mobile device to access the store it loads the main store skin.

**Comment by Noodleyman** [comment]
looks like it ONLY shows those settings if you have a mobile enabled skin installed, so not really an issue, but I don't see the need to hide the settings as seeing them there lets people know they can create a mobile skin

**Comment by hairydogltd** [comment]
CC6 skins have a responsive skin by default, using vast arrays of js libraries to do it. I'm talking about several hundred megabytes extra. How can that make sense?

Not wanting all that overhead, I have used a CC5 skin, added a 2k mobile stylesheet, and a one-line statement in the html to conditionally load the mobile stylesheet if the window is narrow.

I'm not sure what the reason for the separate mobile skin was, but it is a totally outdated concept and is better avoided. Simply use the same elements for all user agents, but display them differently for different sizes of screen.

For an example of this, take a look at http://www.hx2.co.uk/store - view it with a 1024px or wider window, with a 750-ish wide window and with a 300px wide window to see how the same HTML is displayed with a tiny difference in stylesheet. 

The design is to the client's initial spec, but I expect it will be different when it goes live on its actual address: this is just a development server. You could buy stuff there, but be aware that nothing will actually be delivered!

**Comment by abrookbanks** [comment]
It would be interesting to see benchmark test results for page load speed with empty cach on both. I'd have though with decent modern network connections it's fairly negligible.

Don't forget that the default foundation skin has designed to be easy to take forward. Not all our users are competent building a slimline responsive build effectively from scratch with JUST the bits needed from nothing. If that method works for you.. Great!!

**Comment by abrookbanks** [comment]
... If you have made a lightweight responsive skin others may benefit from please do share if in the marketplace!! :)

**Comment by hairydogltd** [comment]
I don't actually care if a fast connection will make it load nearly as fast. 

I care that several hundred of megabytes of pointless bloat is avoidable. 

I care that some people have slow, unreliable internet connections. 

I care that Google ranking varies with load speed.

I didn't build it entirely from scratch: it was based on a v5 skin.Wasn't all that hard to do. What was hard was making it pixel-perfect to the client's spec. Which I'm now told was just a rough interim outline. Hmm.

As for making a lightweight responsive skin, as v5 skins are not fully compatible with v6 it would be a second-rate product. And I'm not sure it's a responsive skin. It is just a skin which also has a "narrow window" stylesheet. I'm not entirely sure how "responsive" is defined, but it does seem to involve different html for different devices.

**Comment by abrookbanks** [comment]
> some people have slow, unreliable internet connections.

That's me ironically. :) Plus.net tried to sell me fibre the other week and Three seem to think I'll have 4G at home soon...

In reality we still have to call the woman in the local switchboard to make a phone call that's not in a 3 mile radius and not a single mobile company has a phone signal. LOL a fem2cell takes up about 90% of my broadband when in use. :)

**Comment by abrookbanks** [comment]
All 35 miles north of Central london.

**Comment by abrookbanks** [comment]
Back to the point though... It sounds like you are churning out some really great stuff. Keep up the good work. 👍

**Comment by hairydogltd** [comment]
If I ever get a skin that feels finished enough, I'll share it.

On the broadband issue: when I'm away in my motorhome, I use a Huawei E5776 4G mi-fi unit. I am very seriously impressed with it. 

Its predecessor was OK but needed to be rebooted every six or seven hours, but this runs for weeks on end. And the performance is great. On a remote part of the NE coast, north of Hartlepool, with almost no signal showing, I was getting 35Mb/sec downloads. That's as good as the FTTC here at home! 

This was in EE - and they do a 15GB/month for £20 data only sim deal (I use whatever is cheap, but EE seems best) It might be worth checking your EE coverage. I find it to be pretty good nearly everywhere, but you may be unlucky. Three is next best, but not quite as good

**Comment by hairydogltd** [comment]
Bother: I meant to mention using an external antenna on a high pole - that makes a huge difference!
