### ISSUE TITLE
More Annoying Edits

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3271]
Just making mention of edits I made to keep PHP 8 from logging Warnings on unknown stuff.

products.index.inc.php, line 740:
There is a hook just above this, so this code must be to accommodate the result of that hook. The variable `$external_categories` is tested for being an array. If `$external_categories` does not exist, then _false_ is used. Regardless, the variable is being type cast to a boolean. The skin is expecting `$EXTERNAL_CATS` to be an array.

PHP 8 says `$external_categories` is unknown.
```
From:
if(is_array($external_categories)) {
    $GLOBALS['smarty']->assign("EXTERNAL_CATS", (bool)($external_categories ?? false));
}
To:
$GLOBALS['smarty']->assign("EXTERNAL_CATS", $external_categories ?? false);
```

**Comment by bhsmither** [comment]
If a product has no options, then $option_list` will be unknown.
products.index.inc.php, line 844:
```
if (isset($option_list) && is_array($option_list)) {
```

**Comment by bhsmither** [comment]
If a product has no option matrix, `$smarty_data['option_matrix']` will be unknown.
products.index.inc.php, line 1103:
```
From:
        $GLOBALS['smarty']->assign('OPTIONS_MATRIX', $smarty_data['option_matrix']);
To:
        $GLOBALS['smarty']->assign('OPTIONS_MATRIX', $smarty_data['option_matrix'] ?? false);
```

**Comment by bhsmither** [comment]
If a product has no short description, the use of htmlentities will throw a Deprecated message.
products.index.php, line 259, _in part_:
```
From:
class="textbox fck" type="text">{htmlentities($PRODUCT.description_short, ENT_QUOTES, 'UTF-8', true)}
To:
class="textbox fck">{if $PRODUCT.description_short}{htmlentities($PRODUCT.description_short, ENT_QUOTES, 'UTF-8', true)}{/if}
```
Is the use of `type="text"` appropriate here?

Note that the `textarea` for 'description' is not using `htmlentities()`.

**Comment by bhsmither** [comment]
When requested to Add Category, there will be no 'cat_id' in the querystring.
categories.index.inc.php, line 335:
```
$GLOBALS['smarty']->assign("REDIRECTS", $GLOBALS['seo']->getRedirects('cat', $_GET['cat_id']));
```
A few lines later begins an `if/else` block testing `isset($_GET['cat_id']`.

Suggest _moving_ the above line into the `if $category exists` block.

**Comment by abrookbanks** [comment]
Thanks so much Brian.

**Comment by bhsmither** [comment]
When having edited an item and not having built an Option Matrix, `$_POST['option_matrix']` will not be known.
products.index.inc.php, line 252:
```
From:
if (is_array($_POST['option_matrix'])) {
To:
if (isset($_POST['option_matrix']) && is_array($_POST['option_matrix'])) {
```

**Comment by abrookbanks** [comment]
Thanks.

**Comment by bhsmither** [comment]
In settings.language.inc.php, the block of code that starts at line 36 could be entered if expr1&&expr2 is true, regardless of expr3, which might not be set.

If so, PHP complains at line 43 about the unknown key ['delete'].

Suggest:
```
if (isset($_POST['delete']) && is_array($_POST['delete'])) {
```
Likewise, the block of code could be entered if expr3 is true, regardless of expr1&&expr2, which might not be set.

If so, PHP complains at line 54 about the unknown key ['string'].

Suggest:
```
if (isset($_POST['string']) && is_array($_POST['string'])) {
```

**Comment by abrookbanks** [comment]
Thanks. PHP loves a whine and a moan more than my local facebook group.

**Comment by bhsmither** [comment]
A specific sequence of events will lead to code being executed at line 111 in settings.language.inc.php.

However, not sure where in this sequence it happens where `$_REQUEST['title']` is set but is not a non-empty string (or array with at least one element).

PHP complains "Uninitialized string offset 0".

**Comment by bhsmither** [comment]
In settings.hooks.inc.php, near line 127, a call is made to `Hooks->scan_all_plugins()`. The return (given to `$plugins`) will always be an array, but perhaps empty.

Now at line 222, `$plugins` is true, but could be empty. As such, `$smarty_data['plugins']` will not be known at line 227.

**Comment by bhsmither** [comment]
In products.index.inc.php, near line 744, when adding a new product, `$_GET['product_id']` to find redirects is not known.

Suggest _moving_ this statement after line 766 where it the product is known to being edited.

**Comment by abrookbanks** [comment]
Thanks!!!
