### ISSUE TITLE
Foundation: Duplicate Category Name

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3272]
When the screen is 'large', the Top Bar Nav will show a duplicate name of the root category as a child when hovering over a category that has a drop-down. (This duplicated name is helpful when the screen is 'small'.)

I wish to not see this when the screen is 'large'.

In element.navigation_tree.php, line 16, _in part_:
```
From:
<li itemprop="name">
To:
<li class="hide-for-large-up" itemprop="name">
```
I haven't validated this for the second and beyond level descendants.

**Comment by abrookbanks** [comment]
Agreed. Thanks for this.
