### ISSUE TITLE
"More" functionality not working in search

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#3273]
6.5.1 Standard foundation skin

Do a search and first page of products is displayed. Scroll to botton and click more and the first page is duplicated again (and again each time more is clicked)

**Comment by bhsmither** [comment]
Please see:
```
https://github.com/cubecart/v6/issues/3066
```
and a lengthy conversation on the forum:
```
https://forums.cubecart.com/topic/58299-pagination-does-not-work-after-upgrade-to-650/
```

**Comment by havenswift-hosting** [comment]
OK thx - had missed that

**Comment by bhsmither** [comment]
I would say to keep this open as this problem does, in fact, still need to be fixed.

**Comment by havenswift-hosting** [comment]
Any news on getting this fixed ?

**Comment by abrookbanks** [comment]
There is a huge amount to take in here. 

Changing:

`$this->searchCatalogue($original_search_data, 1,..`

to;

`$this->searchCatalogue($original_search_data, $page,..`

doesn't make sense to me. Are you sure?

**Comment by abrookbanks** [comment]
I can't find a fault with this but it makes me nervous.

**Comment by abrookbanks** [comment]
Coincidentally I just got a support ticket about this. Code fix with $page definitely works.
