### ISSUE TITLE
Empty Area Possible

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3274]
If there is no Sale Items box to show (config.catalogue_sale_mode=0), and no Popular Products to show (config.catalogue_popular_products_count=0), and no inventory item has its 'featured' value set, then the right-side (aka `id="sidebar_left"`) is empty - at the 'large' screen width.

Is there anything else that could be shown here - at 'large' - if those three boxes do not show?
```
{if !($CONFIG['catalogue_sale_mode']>0 || $POPULAR || $featured)}
show something
{/if}
```
Reclaiming those three columns into the twelve makes everything huge.

**Comment by abrookbanks** [comment]
I don't know what else could go there. I've never come across this issue in reality. Interesting find but closing for now.
