### ISSUE TITLE
More Data Logged in Admin Log

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3275]
Feature Request:

When logging a message to CubeCart_admin_log, include the cat_id(s), product_id(s), and doc_id(s) that were affected.

**Comment by abrookbanks** [comment]
This has crossed my mind before too. Thanks. 

<img width="982" alt="Screenshot 2023-04-26 at 09 54 51" src="https://user-images.githubusercontent.com/4520803/234523926-c502bbb2-5541-49f6-8030-3ee27a435152.png">
