### ISSUE TITLE
Code Check: Product's Category Assignments

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3276]
In product.index.inc.php, line 332, starts the processing of categories that were chosen to be assigned to the product being added/edited.

Just after the `if()` block closes at line 354, a test is made against `$category_assigned`. If there is no `$_POST['categories']`, `$category_assigned` is not known. There is no hook that could set it.

This test at line 355 has no relevance to anything outside the code processing the `$_POST['categories']`.

Suggest _moving_ lines 355-357 to just above the closing brace at line 354. The

**Comment by abrookbanks** [comment]
Good find. Thanks so much.
