### ISSUE TITLE
Missing Language Strings

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3277]
In settings.redirects.inc.php, lines 56 and 58, the requested language strings do not exist in definitions.xml.

**Comment by bhsmither** [comment]
There is a commit:
https://github.com/cubecart/v6/commit/72cfcd01b091136b7e73c20dddb445bdc2c6b0f2#diff-c08481ed5b77c3e3e0dcd4b9319e1a10c29d2a9951880c6f0f5dc833ab928bf1
that says this was done, but a banner at the top of the page says this commit does not belong to any branch. Maybe because CC63X does not exist, and this edit didn't make it to CC64X?

**Comment by bhsmither** [comment]
And there is a word misspelled.

**Comment by bhsmither** [comment]
The word is still misspelled.
Failed to delete _redierct_.

**Comment by abrookbanks** [comment]
I knew that!!!🫥
