### ISSUE TITLE
DISTINCT Columns

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3278]
With respect to #2596, there is a statement that is ruining the development of 'DISTINCT'.

At line 641, `$distinct` is set to an empty string. This is proper.

However, at line 660, which is inside a `foreach($columns)` block, `$distinct` is also being set to an empty string.

This means that if there is a column that _does not_ contain 'DISTINCT' as part of the $key, which comes _after_ the column that _does_ contain 'DISTINCT' as part of the $key, will have reset `$distinct` to an empty string, and it will stay that way.

(My suggestion in 2596 was, apparently, faulty.)

**Comment by abrookbanks** [comment]
Thanks. Removing line 660 allowed for more columns after the distinct.
