### ISSUE TITLE
Code Check: Response of a Request

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3279]
In products.index.inc.php, near line 729, a `$request->send()` is made.

Should the result be _false_, then `$google_cats` will remain _false_ (set at line 720).

Only if the `$response` is _true-like_ will `$google_cats` be set to an array.

But if at _false_, PHP will complain about trying to access array offset on bool at line 733.

Suggest _moving_ lines 733-735 to just after line 730:
```
        if ($response = $request->send()) {
            $google_cats = explode("\n", $response);
            if (strstr($google_cats[0], 'Google_Product_Taxonomy_Version')) {
                unset($google_cats[0]);
            }
        }
```

**Comment by abrookbanks** [comment]
Thanks. NIce find.
