### ISSUE TITLE
Code Check: Data Prep for TextArea Boxes

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3283]
There may be a reason for _singling out_ the product main textareas:
See: https://github.com/cubecart/v6/issues/3271#issuecomment-1521140891

In the admin skin products.index.php, near line 256 and 259, uses:
```
{if $PRODUCT.description}{htmlentities($PRODUCT.description, ENT_QUOTES, 'UTF-8', true)}{/if}
```
but not in the $DISPLAY_TRANSLATE_FORM section, where a variable modifier `|escape:"html"` is used.

Perhaps `htmlentities()` is preferred over `|escape:"html"`?

Also, this variable modifier is used for prepping the data for the category and document template pages.

**Comment by abrookbanks** [comment]
Thanks. We need to be leaving the escape function anyway.
