### ISSUE TITLE
Use of PHP_EOL?

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3285]
In settings.language.inc.php, lines 184 and 201, use is made of the constant PHP_EOL, which says, "The correct 'End Of Line' symbol for this platform."

I advise against using this, as it just may be the case the string contains x0D0A where PHP_EOL on a Unix system should be x0A. Thus, no multiline.

**Comment by abrookbanks** [comment]
I'm not sure how to go about this one Brian. From my experience PHP_EOL has always worked. Does this really need changing?

**Comment by bhsmither** [comment]
The context of my concern is output shown on a native display on a platform that differed from the platform that created the text.

By 'native display', I mean like a terminal window, or a stupid-simple utility (like Windows' Notepad). I do NOT mean a text editor/reader, or web browser, that can auto-detect and correct for any of the various line-end values.

**Note:** This came to my attention when I noticed that the use of PHP_EOL is _only used in **two** script files_ (well, other than Elasticsearch:100'S, PHPMailer:once, Sendgrid:once).

In settings.language.inc.php, it is used to test if the server-specific line-end exists in a phrase that came from `$GLOBALS['language']->getDefinitions()`, which is likely a text file created somewhere else.

In order.class.php, a record is being assembled where the notes array is getting seamed together with the server's line end. Why the server's line end? The log will most likely be read in CubeCart's admin, where _any_ line end should pass through `nl2br()`.

**Comment by abrookbanks** [comment]
Got it. Thanks. This commit seems to do the job well.

**Comment by abrookbanks** [comment]
From my testing all good.
