### ISSUE TITLE
Language Editor: Lost Revert Icon

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3286]
After changing a phrase (the changed phrase did get saved in CubeCart_lang_strings), then revisiting that phrase group in the editor, I expect to see the Revert icon (clock). I have seen it before.

It is not showing now.

**Comment by bhsmither** [comment]
Also getting 'Undefined array key' at line 62 in settings.language.inc.php -- but only after POSTing changes.

The first time this happened, the undefined key was referring to `$type`. The second time was referring to `$name`. (Different phrases in the same group.)

**Comment by bhsmither** [comment]
I got the clock back (but not yet tested for correct reversion).
```
From:
            foreach ($definitions as $name => $data) {
                if(isset($_GET['key']) && $_GET['key']!==$name) continue;
                $default = (isset($strings[$name])) ? $strings[$name] : $data['value'];
                $defined = (isset($strings[$name]) || isset($custom[$name])) ? true : false;
                $value = (isset($custom[$name])) ? $custom[$name] : $default;
                $assign = array(
To:
            foreach ($definitions as $name => $data) {
                if(isset($_GET['key']) && $_GET['key']!==$name) continue;
                $default = $data['value'];
                $defined = (isset($strings[$name]) || isset($custom[$name])) ? true : false;
                if (isset($custom[$name])) { $value = $custom[$name]; }
                elseif (isset($strings[$name])) { $value = $strings[$name]; }
                else { $value = $default; } // Lost mind on multi-ternary order by parentheses
                $assign = array(
```

**Comment by bhsmither** [comment]
Looking at `$base_strings` when saving a phrase to be changed, it only contained what was already changed (external language pack(s) or database):
```
The $base_strings are:
address => array (size=1)
  'state' => string 'County' (length=6)
catalogue => array (size=2)
  'latest_products' => string 'Recent Pages' (length=12)
  'gift_certificate' => string 'Gift Certificate' (length=16)
```
So, line 62 will cause PHP to complain when changing anything else.

**Comment by bhsmither** [comment]
Code Review:
In dealing with line 62, it was discovered that if `$base_strings[$type][$name]` does not exist, the result of `htmlentities()` is something that loosely equals a zero-length string.

From the Language Editor, one can POST an empty string value of an array element.

Therefore, the test at line 63 fails because of the loose equality, and no work is done.

But if there is to be a solution to PHP's complaint, be sure it is not loosely unequal to `$value` being an empty string. Suggest, an empty string?
```
$basic = htmlspecialchars($base_strings[$type][$name] ?? "", ENT_COMPAT, 'UTF-8', false);
if ($basic !== $value) {
```

**Comment by abrookbanks** [comment]
> I got the clock back (but not yet tested for correct reversion).
> 
> ```
> From:
>             foreach ($definitions as $name => $data) {
>                 if(isset($_GET['key']) && $_GET['key']!==$name) continue;
>                 $default = (isset($strings[$name])) ? $strings[$name] : $data['value'];
>                 $defined = (isset($strings[$name]) || isset($custom[$name])) ? true : false;
>                 $value = (isset($custom[$name])) ? $custom[$name] : $default;
>                 $assign = array(
> To:
>             foreach ($definitions as $name => $data) {
>                 if(isset($_GET['key']) && $_GET['key']!==$name) continue;
>                 $default = $data['value'];
>                 $defined = (isset($strings[$name]) || isset($custom[$name])) ? true : false;
>                 if (isset($custom[$name])) { $value = $custom[$name]; }
>                 elseif (isset($strings[$name])) { $value = $strings[$name]; }
>                 else { $value = $default; } // Lost mind on multi-ternary order by parentheses
>                 $assign = array(
> ```

This didn't work for me. It showed every field with revert clock. I'll do some more tests...

**Comment by abrookbanks** [comment]
I'm no longer able to reproduce any of these issues.

**Comment by abrookbanks** [comment]
Something wired is going on with `$base_strings = $GLOBALS['language']->loadLanguageXML($_GET['language']);`

From my testing it's only returning a partial result.

**Comment by abrookbanks** [comment]
Got it. Thanks!

**Comment by bhsmither** [comment]
My long-time understanding of the Language Editor's 'Revert Clock' was to indicate a phrase that has overridden a stock phrase that came from CubeCart_lang_strings (that is, the phrase was changed at some point in the past), as well as edited - but not yet saved - phrases.

Therefore, my understanding was that clicking the 'Revert Clock' restored the phrase to the stock value.

Now, once an edited phrase is saved, there is no clock. And so, apparently, there is no way to undo the databased custom phrase. (You could edit the phrase back to its stock value - assuming you remember what that was.)

**Comment by abrookbanks** [comment]
OK so it works on the default language but not others...

**Comment by abrookbanks** [comment]
Broken for extensions uugh

**Comment by abrookbanks** [comment]
```$strings = $GLOBALS['language']->getStrings($module_name);```

This is returning custom strings when it shouldn't.
