### ISSUE TITLE
Make Elasticsearch settings fixed

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#3287]
They should not be editable by the merchant in "managed" situations. I'm forever putting them right again.

**Comment by bhsmither** [comment]
Is this to say that the settings in Store Settings, Advanced tab are not personal to the subscriber of the hosted account (like the MySQL server access settings are in /includes/global.inc.php)?

I had given some thought to recommending _moving_ the ElasticSearch settings to globals.inc.php, or, perhaps, to Maintenance (with warnings of dire consequences if changed).

**Comment by abrookbanks** [comment]
With our hosting at least every store has a separate index and auth. We've just had one merchant that keep managing to change it then preventing it working. All others have been ok. Putting this on hold for now.
