### ISSUE TITLE
Style Tweak: Phrase Table

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3289]
In the admin skin layout.css, line 658, there is a rule that applies a background color **to the cells** of the even rows of a tablebody.

Line 1069 has a rule that overrides the background color **to the cells** of the `phrases` table having a class of `actions`.

Line 1066 has a rule that overrides the background color **to anything** having a class of `custom-phrase`. _In this case_, it is applied **to the row** where the phrase has been edited (via javascript).

What seems to be happening is that a table cell inherits from its ancestors unless specifically told otherwise - which, here, it is.

So, even though there is `tr.custom-phrase`, the styling on the cells in an even row stay pale blue instead of acquiring pale green.

Suggest javascript applies `custom-phrase` **to the cell** in the row where the phrase has been edited.

**Comment by abrookbanks** [comment]
Thanks. It works well.
