### ISSUE TITLE
v6.0.0b7 Admin Maintenence Layout Issue

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#329]
https://forums.cubecart.com/topic/49359-v600b7-admin-maintenence-layout-issue/

**Comment by abrookbanks** [comment]
Issue comes from dynamic ```<div class="custom-checkbox">``` added into span tag. 

```
<div>
   <label for="clearCache">Clear cache</label>
   <span>
      <div class="custom-checkbox"><input type="checkbox" id="clearCache" name="clearCache" value="1" original="1"></div>
      </span>
</div>
```

**Comment by abrookbanks** [comment]
This fixes it but breaks the striping:

```fieldset span div.custom-checkbox{float:left;}```

I'm thinking out loud for when I get back from a PayPal meeting in 20 mins..
