### ISSUE TITLE
Code Review:

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3291]
In `Cubecart->_getLiveHelp()`, the class is instantiated and loaded with that extension's configuration.

However, `$section` and `$method` are not known.

PHP will complain about unknown variables.

Also, when checking `method_exists()`, with `$method` not known, nothing gets called and nothing ends up in `$social_html`.

Suggest:
```
private function _getLiveHelp($section, $method = 'invocationHTML')
```

**Comment by abrookbanks** [comment]
Excellent. Thanks.
