### ISSUE TITLE
Tax is sometimes applied to shipping twice

### ISSUE THREAD

**Issue by problemgenerator** [cubecart/v6#3302]
I've noticed some occasions where additional tax is being applied to amounts that should be already be inclusive of tax. In my setup I've only noticed this happening to shipping prices when sending the buyer off to a gateway, but I'm not sure if it's also happening elsewhere. Totals are displayed correctly during checkout, but when sent to the gateway the total amount has extra tax applied.

This seems to happen when a shipping price is specified as tax-inclusive (in the All In One Shipping module), but gets its tax amount calculated as if the price was tax-exclusive. The price is still calculated correctly regardless of whether it is specified as tax-inclusive or tax-exclusive.

e.g. A tax-inclusive shipping option with a price of $22.00 and a 10% tax rate should have its price and tax calculated as $20.00 + $2.00, but is incorrectly calculated as $20.00 + $2.20.

I noticed this after upgrading to v.6.5.1, so I checked what had changed and found 9e60961 which added these three lines:

https://github.com/cubecart/v6/blob/9e6096167760f2ee77d35c84f9e1d3ef7acb8854/classes/tax.class.php#L440-L442

This overwrites `$tax_inclusive`, always setting it to `false` even if it was passed to the function as `true`. I've tested adding some debug logging before and after this new line and can see that it's changing the value. I don't think `$tax_inclusive` needs to be initialised here, since it already has a default value in the function arguments. Commenting out this line seems to fix the issue for me.

Apologies if I'm using the wrong terminology here, I don't have a lot of experience with CubeCart.

**Comment by abrookbanks** [comment]
Thanks so much for such a thorough outline of the problem. Super helpful. 

Looking back at this code change these parameters were defined there to keep PHP 8 happy. Thats the sole reason. However `$tax_inclusive` is already defined in the function parameters so I see no harm at all removing that line of code.

Thanks again.
