### ISSUE TITLE
Skin Sub-Themes to Persist on Upgrade

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3305]
Requesting the means to have **Foundation** skin sub-themes persist across upgrades.

Currently, added `<style>` nodes to Foundation's config.xml will be lost when upgraded.

The basic solution is to copy Foundation to another name/folder and create the sub-themes on that. Thereafter, one must endevour to keep the derived skin matched to Foundation.

There is the cached file info.skins.list, but for obvious reasons, this will not persist.

A possible solution is to database info.skins.list in CubeCart_config.

Then, in `GUI->listskins()`, query for the list, convert to an array, then overload that array with the skin's config.xml file. Thus, changes found in config.xml after an upgrade compared to what had existed before the upgrade will get incorporated, while custom additions will still persist. (If overloading the array changed the array, maybe write an updated config.xml file.)

(I have not tried this.)

**Comment by abrookbanks** [comment]
Leaving as possible feature request for now.
