### ISSUE TITLE
On Sale box - misprezentation

### ISSUE THREAD

**Issue by nklisic** [cubecart/v6#331]
When is sale mode disabled, in front page on sale box i visible in cases when use list product by category. 

![cubecart_sale_mode](https://cloud.githubusercontent.com/assets/10867308/6522521/0041467e-c3e6-11e4-8358-0250cf5b31cf.jpg)

**Comment by abrookbanks** [comment]
I can't reproduce this issue. Are you using beta 7? Have you tried clearing the cache in the maintenance section?

# Before
![screen shot 2015-03-06 at 09 00 08](https://cloud.githubusercontent.com/assets/4520803/6522652/43ee7c72-c3df-11e4-94e9-ae26a2cec444.png)

# After
![screen shot 2015-03-06 at 09 00 15](https://cloud.githubusercontent.com/assets/4520803/6522661/4b7daf6c-c3df-11e4-9eda-6ff274056ec3.png)

**Comment by nklisic** [comment]
Hi Al,
Yes, I use 6.07b. Now I set to zour CubeCart demo store Sales Mode -
disabled and clear cache. Take a look on a any category page. Please back
Store Settings to original state after finish browsing.

2015-03-06 10:01 GMT+01:00 Al Brookbanks <notifications@github.com>:

**Comment by abrookbanks** [comment]
I'm sorry I just can't reproduce this. Please can you submit a support ticket and we will take a look.

**Comment by nklisic** [comment]
Hi Al,

Here is link where you can see what is a bug. Sale mode is *disabled*.  You
must browse inventory by *category.*

http://www.maxilandbakery.com/inventory/bakery/bread.html

Regards,
nklisic

2015-03-09 9:38 GMT+01:00 Al Brookbanks <notifications@github.com>:

**Comment by abrookbanks** [comment]
Please can you send FTP and admin login to our sales dept. and I’ll pick it up.

https://support.cubecart.com/index.php?/Tickets/Submit <https://support.cubecart.com/index.php?/Tickets/Submit>

**Comment by nklisic** [comment]
Hi Al,

FTP: username: maxiland, passw: cubecart
Admin CC panel: usename: demo, passwd: demo (full admin access) This is
demo store, you can do anything with data.

Regards,
Nebojsa

2015-03-09 10:52 GMT+01:00 Al Brookbanks <notifications@github.com>:

> Please can you send FTP and admin login to our sales dept. and I’ll pick
> it up.
>
> https://support.cubecart.com/index.php?/Tickets/Submit <
> https://support.cubecart.com/index.php?/Tickets/Submit>
>

**Comment by abrookbanks** [comment]
This is a public forum!!!! I deleted your passwords. Please send them to the helpdesk as I requested.
