### ISSUE TITLE
More... Cookie Not For Admin in Debug

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3311]
One of the ways to page through Foundation's category pages is the "More..." code. This uses a cookie to remember the category, page number last viewed, and the location (distance down the page?), and will return to that location when returning to that page within 10 minutes.

However, there possibly exists the case where the admin, when developing the store, possibly customizing the skin, needs to return (or refresh) and see **just** page one.

A possible solution is to add a button next to the More button (in Debug mode and only for an admin session) that will kill the CCScroll cookie.

**Comment by abrookbanks** [comment]
Agreed but any developer should know they can easily kill the cookie in the browser developer tools.

**Comment by bhsmither** [comment]
A developer? Of course.

But, wanting to see page=1, a store admin? Maybe, maybe not.

**Comment by abrookbanks** [comment]
Leaving closed for now.
