### ISSUE TITLE
Tweaks for Accessibility

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3312]
(As per Google, of course.)

In content category.php, there is:
```
<input type="text" name="quantity" value="{$product.minimum_quantity|default:'1'}" maxlength="3" class="quantity text-center">
```
and
```
<input type="number" name="quantity" value="{$product.minimum_quantity|default:'1'}" min="{$product.minimum_quantity}" maxlength="3" class="quantity text-center" disabled>
```
And also in element.product.call_to_action.php and content.homepage.php.

There should be a programmatically associated label with these inputs.

Suggest `aria-label="enter quantity"`.

Also, compared to element.product.call_to_action.php, the other inputs here do not limit the product's `maximum_quantity`.

**Comment by bhsmither** [comment]
(As per Google, of course.)

There should be accessible names for buttons and icons.

In box.basket.php, there is:
```
<div class="text-right"><a href="#" id="basket-summary" class="button trans small"><svg class="icon icon-basket"><use xlink:href="#icon-basket"></use></svg> {$CART_TOTAL}</a></div>
```
and
```
<div class="show-for-small-only"><a class="right-off-canvas-toggle button trans tiny" href="#"><svg class="icon icon-basket icon-x2"><use xlink:href="#icon-basket"></use></svg></a></div>
```
Suggest in the `<a>` tag, `title="Your shopping cart total is {$CART_TOTAL}"`.

**Comment by bhsmither** [comment]
In main.php (43, bars and search), main.checkout.php (38, bars), and box.search.php (19, search), suggest `title="something_appropriate"`.

**Comment by abrookbanks** [comment]
Thanks.
