### ISSUE TITLE
Skins to Use Constants

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3313]
Coding Request:

Apparently, Smarty can reach into the classes to find the constants.

As an example, in the admin skin filemanager.index.php, numerous statements make a comparison to the public constants in the FileManager class. So, request that `FileManager::FM_FILETYPE_IMG` be used instead of '1', and `FileManager::FM_FILETYPE_DL` be used instead of '2'.

Maybe look for other skin templates that use the constant values instead of the constant names.

**Comment by bhsmither** [comment]
I do not find any instance of this in Foundation. The template element.product.options.php already complies.

**Comment by bhsmither** [comment]
Find in products.options.php (74, 106, 176, 182)

**Comment by abrookbanks** [comment]
Thank you.
