### ISSUE TITLE
Keeping Skins up-to-date

### ISSUE THREAD

**Issue by DiMarca-Online** [cubecart/v6#3314]
Please keep all additional skins like Basix, Dillion and Amzin (gifted to CubeCart by NiteFox) up to date with all recent version changes for example those needed for ElasticSearch.

Thank you.

**Comment by abrookbanks** [comment]
Some have already been updated already. Please check the change log for each. We get to them as we can. 

Officially hosted customers (hosted.cubecart.com) and those with a support plan get priority I'm afraid.

**Comment by DiMarca-Online** [comment]
Thank you.

**Comment by abrookbanks** [comment]
Closing as this is ongoing. I believe the skin you are interested in is already ready for ES.
