### ISSUE TITLE
More "page=all"

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3315]
With respect to #3133, if a skin's config.xml file does not have the proper 'layout' > 'products' > 'perpage' structure, PHP will complain in database.class.php, at line 507, about a bad array for `array_key_last`. An Exception occurs.

Suggest that `DB->pagination()` use `GUI->itemsPerPage()` which has a proper fallback.

If using that, then `itemsPerPage()` will need to be enhanced with another parameter that would specify which element to return:
```
public function itemsPerPage($list_id = 'products', $page_key = 'perpage', $list_amount = "default")
...
                ksort($this->_skin_data['layout'][$list_id]['perpage'], SORT_NUMERIC); // just in case
                if ($list_amount == "default" && $default) {
                    return (int)$amount;
                } else if ($list_amount = "last") {
                    return (int)array_key_last($this->_skin_data['layout'][$list_id]['perpage']);
                } else if ($list_amount = "first") { // for some future reason
                    return (int)array_key_first($this->_skin_data['layout'][$list_id]['perpage']);
                }
...
```
The above could use some polishing. I haven't tried this.

**Comment by abrookbanks** [comment]
Database class may want to use ACP->itemsPerPage or GUI->itemsPerPage. Leaving the past part for now. Modern skins should have $skin_data['layout']['products']['perpage'] set and old ones can have it added.

**Comment by abrookbanks** [comment]
Sorry I'm half asleep we are using.. GUI->itemsPerPage()
