### ISSUE TITLE
Updating Review, False Positive

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3318]
In tracing the code flow, discovered that updating a review to an intentionally non-existent record will have `DB->update()` return `true` (because, factually, the database did not fail in its duties) even when the review did not get updated.

This may relate to a fix on `DB->update()` many dozens of versions ago, when the result was `false` where nothing was actually updated.

I _think_ the solution was to check `DB->affected()` immediately after the `DB->update()`, and if >0, then yes the update happened, if 0, then no update happened (for whatever reason), and if -1 then the update attempt faulted.
```
See: http://docs.php.net/manual/en/mysqli.affected-rows.php
```

**Comment by abrookbanks** [comment]
Thanks affected() worked well
