### ISSUE TITLE
Extensions to Declare Requirements

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3320]
Feature Request:

Request and require that extensions have, in their config.xml file, a node to itemize requirements (using established names and versions).

Then, when CubeCart is enumerating modules to list in Manage Extensions, interrogate the config.xml file looking for the requirements, and if provided, test the environment for those resources. If the test results in a fail, list the module, but...

- disable the status checkbox,
- display the extension name in italics,
- disable the 'Edit' icon,
- keep the 'Delete' icon,
- add a red 'Info' icon with a tooltip listing the resources not found

For example, a particular extension requires:

- PHP 8.1.+ (does not include 8.2)
- ionCube loader v12.0.+
- PDO_MySQL v8+

If any of these fail, do not allow the extension to be energized.

**Comment by abrookbanks** [comment]
Nice idea
