### ISSUE TITLE
"New version available, but..."

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3321]
When CubeCart publishes a new version, and the admin code makes the checks, the banner reads, for example:
```
Version 6.5.1 is available but you are running 6.4.5.
```
When a newer version requires a bump in the PHP version to run successfully, suggest to add the hint:
```
And your environment will require PHP8.2, but you are running PHP7.4.33.
```

**Comment by abrookbanks** [comment]
Great idea.

**Comment by abrookbanks** [comment]
Closing as a feature request for now.
