### ISSUE TITLE
Cannot go to Forum

### ISSUE THREAD

**Issue by claudia39** [cubecart/v6#3322]
Using several different browsers I have not been able to got to CubeCart's forum.  It keeps saying Cloudfare has to verify the security of my site, but then just keeps spinning and never gets to the forum. https://forums.cubecart.com/

**Comment by bhsmither** [comment]
You have a add-on for your browser that disallows javascript to run, until you give it permission for that site.

You will need to give permission to:
```
*.cloudflare.com
(including challenges.cloudflare.com)
```
I run NoScript (need to allow scripts) as well as uMatrix (need to allow scripts, frames, xhr). Took me more than a day to figure out what could be happening.

**Comment by claudia39** [comment]
I don't have any add-ons in Firefox. When I go to about:config (After internet search of how to enable javascript in FF) it was always set to true. I don't know what else to do.  I wanted to go to the forum because the additional columns I created in admin - Products won't let me sort them even though I can't see where the basic codes is any different than the columns I can sort

**Comment by bhsmither** [comment]
Do you have a multi-function anti-virus application on your computer?

**Comment by claudia39** [comment]
No ... just windows defender

**Comment by bhsmither** [comment]
Do you have another computer - without WD?

If not, can you switch off WD for just a couple of minutes - long enough to test if WD is causing the problem?

**Comment by claudia39** [comment]
Turning off WD didn't do anything.  Still can't get on the forum

**Comment by bhsmither** [comment]
Try this site:
```
https://www.projecthoneypot.org/search_ip.php
```
and enter your local IP address. If you do not know it, use:
```
www.showmyip.com
```
to learn what it is.

According to the info I read, Cloudflare queries the HoneyPot Project for bad IP addresses.

Do you have a mobile device that can use the internet _not_ via your in-house wifi?

**Comment by bhsmither** [comment]
I have no answer to why all of your browsers won't get past the Cloudflare thing, but, for Firefox, in Settings, Privacy & Security, if Tracking Protection is on, try turning it off for the short time it takes to try the forums. Maybe Cloudflare wants to 'fingerprint' your browser.

**Comment by claudia39** [comment]
honeypot says this.  A little while ago my email quit working and I contacted Ian. It was a cPanel issue and they logged it as a bug and gave Ian a workaround.  Could this be it?
The Project Honey Pot system has detected behavior from the IP address consistent with that of a [mail server](https://www.projecthoneypot.org/list_of_ips.php?t=s). Below we've reported some other data associated with this IP. This interrelated data helps map spammers' networks and aids in law enforcement efforts. If you know something about this IP, please [leave a comment](https://www.projecthoneypot.org/ip_98.211.12.144#comments).

**Comment by claudia39** [comment]
I can go to the forum on my phone

**Comment by bhsmither** [comment]
The IP address(es) that is used for your store(s) won't be the same as the IP address of your Internet service at your house.

The HoneyPot page told me that since I was accessing them from the same IP that I had checked, I could whitelist my IP.

Maybe you could do the same? Is your home IP address static (you would pay extra for this on your home Internet bill) or dynamic (could change on occasion, but cable service is known to be mostly steady)?

**Comment by claudia39** [comment]
Got up this morning and I could get on the forum from my computer.  Don't know what happened.  For days I couldn't get on!

**Comment by bhsmither** [comment]
I think Al switched it off.

And the spam is back.

**Comment by claudia39** [comment]
man!!!!  Honeypot is going to whitelist my IP, but I wonder if this is happening to anyone else?

**Comment by bhsmither** [comment]
Maybe others may try to follow CubeCart on Twitter (although, maybe there hasn't been a posting there in years).

**Comment by claudia39** [comment]
Well I hope Al doesn't keep it off just because of me.  I can get on the forum from my phone if need be.

**Comment by abrookbanks** [comment]
We've had **horehounds** levels of spam so I put it in Attack Mode. It blocks too many genuine visitors. The level has now been reduced to high and should work .
