### ISSUE TITLE
Debug exceptionHandler to Record Stack Trace

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3324]
Feature Request:

As does the errorHandler(), making a request that the exceptionHandler() also include the statck trace.

See:
```
https://forums.cubecart.com/topic/58561-exception-error-what-could-be-causing-this
```

**Comment by abrookbanks** [comment]
Works really well. Thank you!

**Comment by bhsmither** [comment]
I was really hoping a better solution to the Smarty component of this solution could be developed. Perhaps an OOP trick to tie in to `class Smarty_Internal_Undefined, public function __call($name, $args)`, maybe as a Smarty plugin to survive upgrading the library.

Even though the forum post did modify a core file in the Smarty library, that was only an expedient solution to get that store back online.

**Comment by abrookbanks** [comment]
Do we need to keep the code in Smarty?

**Comment by bhsmither** [comment]
Given that Smarty does not publish a major library upgrade all that often (i.e., v3 to v4), I think the edit to that core code file should remain to catch these particular Smarty exceptions.

**Comment by abrookbanks** [comment]
I agree.
