### ISSUE TITLE
PPCP $state

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3326]
In the edit made in PPCP to get version 1.8.4, there is (split lines for readability):
```
$field = (
($result['purchase_units'][0]['shipping']['address']['country_code']=="AU" && strlen($state)==3)
||
($result['purchase_units'][0]['shipping']['address']['country_code']=="US" && strlen($state)==1)
) ? 'abbrev' : 'name';
```
Please verify that the length of the string for the abbreviation of a US $state value is '1'.

And for Australia, according to CubeCart_geo_zone, `country_id=13` has two and three letter abbreviations (unless PayPal doesn't serve those regions?).

**Comment by abrookbanks** [comment]
strlen($state)==1 was plain stupid. Thanks so much for this. Changed to... 

```
$field = (
($result['purchase_units'][0]['shipping']['address']['country_code']=="AU" && strlen($state)<=3) 
||
($result['purchase_units'][0]['shipping']['address']['country_code']=="US" && strlen($state)==2)) ? 'abbrev' : 'name';
```
