### ISSUE TITLE
DropTable List on New Install

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3327]
A number of tables are not included in the /setup/db/install/table_drop.sql file.

Of course, there may be good reason to not drop a particular table even when wanting to start fresh.

The tables not included are:
404_log, admin_error_log, code_snippet, cookie_consent, customer_coupon,
domains, email_log, extension_info, invoice_template, manufacturers,
newsletter_subscriber_log, option_matrix, order_history, request_log,
saved_cart, seo_urls, shipping_rates, shipping_zones, system_error_log

**Comment by abrookbanks** [comment]
Thanks!!!
