### ISSUE TITLE
Table Exists on Fresh Install Retry

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3328]
Should there be a second+ attempt at a fresh install, the database sever will complain that some tables already exist.

This is because some `CREATE` statements in /setup/db/install/structure.sql do not qualify the command with `IF NOT EXISTS`.

The tables are:
domains, newsletter_subscriber_log, invoice_template, cookie_consent, customer_coupon

**Comment by abrookbanks** [comment]
Thank you!
