### ISSUE TITLE
Redirect Type to be Managed in Controller with Hook

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3329]
In the template settings.redirects.php, near line 36, starts a hard-coded selector for `id="redirect_type"`.

Suggest this list be built in settings.redirects.inc.php, so that plugins can use a provided hook to add their own dynamic/static custom page types.

**Comment by bhsmither** [comment]
Also, the `$REDIRECTS` array, having `$redirect['type']`, to also have `$redirect['type_phrase']`, so that plugins can use a provided hook to add their own custom page phrases.

**Comment by abrookbanks** [comment]
Brilliant. Thank you.
