### ISSUE TITLE
US Lang Pack Missing Email Phrase

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3333]
The file email.definitions.xml has"
```
<email name="newsletter.verify_email">
```
but the email file in other language packs does not, except for en-GB.

Scanning the code of CC651 for "email.definitions.xml" has zero hits. This leads me to believe that there is no fallback that would take advantage of using email phrases from the (master?) file email.definitions.xml.

**Comment by abrookbanks** [comment]
Added to 1.0.3 and tested. Thanks!!
