### ISSUE TITLE
Template Code

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3334]
In documents.email.php, in the tab content `div` panel at line 83, if there could be the case of not having `$EMAIL_IMPORT` while having `$EMAIL_EXPORTS`, there will be missing the `<h3>` title of the content panel.

Suggest moving the `<h3>` tag above the `{if isset($EMAIL_IMPORT)}` statement.

Also suggest that if both are not set, do not add a tab control and do not show the tab panel content.

Also suggest renaming the tab control to 'Import/Export'.

**Comment by abrookbanks** [comment]
All done. Thanks. I can't see a scenario when they wouldn't be set to not show the tab though.
