### ISSUE TITLE
PHP8 Again

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3336]
In products.index.inc.php, near line 375, there is:
```
$_POST['previous-tab'] = ($_POST['submit_cont']) ? $_POST['previous-tab'] : null;
```
The `['submit_cont']` will not be in POST if it wasn't clicked.

Not that it matters much here, as `$_POST['previous-tab']` is not used elsewhere in this file.

**Comment by bhsmither** [comment]
In seo.class.php, near line 431, in the function `getRedirects()`, there is:
```
if(ctype_digit($item_id) && !empty($type)) {
```
PHP is complaining that `ctype_digit()` must be a string.

**Comment by abrookbanks** [comment]
Thank you.
