### ISSUE TITLE
Pagination HTML

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3337]
I disagree how the pagination looks.

Currently, it is:
```
[<] [1] [2] [3] [4] [5] [>] ... [12]
```
where [>] is a link to the next page.

Personally, I prefer:
```
[<] [1] [2] [3] [4] [5] ... [12] [>]
```
Also, the pagination on the Dashboard, Stock Warnings tab doesn't look right.

Code Check: look at settings.geo.com, lines 67-70, to use the code for dashboard.index.php, line 313.

**Comment by bhsmither** [comment]
Other templates to look at:
customers.subscribers.php (62)
settings.errorlog.php (58)(119)
products.coupons.php (50)(83)
settings.logs.php (35)(68)(95)
dashboard.index.php (214)(248)(313)
reports.index.php (62)
statistics.emaillog.php (75)

**Comment by abrookbanks** [comment]
Thanks Brian.
