### ISSUE TITLE
Another PHP8

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3338]
In products.coupons.inc.php, the variable `$incexc` comes into existence only between lines 144-157, when editing an existing coupon with products assigned.

Later, at line 184, `$incexc` is in a test. PHP will complain when adding a coupon (and maybe when editing a coupon with no products assigned).

Suggest using `isset()` as part of the test.

**Comment by bhsmither** [comment]
In customers.index.inc.php, line 340, PHP will complain if `$_POST['multi-action']` does not exist (if the first expression fails).

**Comment by bhsmither** [comment]
With respect to #3335, at line 495, when editing an existing email content template, `$_GET['content_type']` is not a known variable.

Suggest:
```
Line 486, from:
$data  = $content[0];
To:
$data  = $content[0]; $existing = $GLOBALS['db']->select('CubeCart_email_content', array('DISTINCT' => 'language'), array('content_type' => $_GET['content_type']));

Line 495, from:
if($existing = $GLOBALS['db']->select('CubeCart_email_content', array('DISTINCT' => 'language'), array('content_type' => $_GET['content_type']))) {
To:
if (!empty($existing)) {
```

**Comment by abrookbanks** [comment]
Thank you.

**Comment by abrookbanks** [comment]
All seem fine after. Thank you.
