### ISSUE TITLE
Editing Email Content

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3339]
When editing an Email Content template, on the General tab, one can choose a different language.

Given the case that one edits "Admin: Order Received" for English (UK), the POST will also include the `$_POST['content']['content_id']`.

Choose English (US) from the drop-down (or some other language listed) and Save.

It may just so happen that there already exists "Admin: Order Received" for English (US) in the database. That is not a problem at this point. The 'CubeCart_email_content' table does not require any uniqueness among records.

But now, "Admin: Order Received" for English (UK) no longer exists. There will be two USA flags in the Translations column. When querying for "Admin: Order Received" for English (US) in the Order class, it is questionable which record will be at index 0.

Suggest, not providing a language selector when editing an existing Email Content template.

**Comment by abrookbanks** [comment]
<img width="695" alt="Screenshot 2023-07-06 at 10 41 03" src="https://github.com/cubecart/v6/assets/4520803/1013ac77-1df7-473e-a9eb-a6b125bc9a9a">
