### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by kalyncomputers** [cubecart/v6#334]
This may be a silly one for some people but....

Would it be possible to add a feature regarding images, i.e. list all products or categories without images?

I know you can list all products and see if there is an image attached to a product but when you have a couple of thousand products that is tedious.

I also know that most people won't have any use for this but I have some clients who, not being very computer literate have managed to create both products and categories that don't have any images or they have managed to delete an image by mistake.

Tim

**Comment by abrookbanks** [comment]
It's not a silly one. Maybe we can add this as a feature in a future release.
