### ISSUE TITLE
Editing Email Permissions

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3340]
In documents.email.inc.php:
The admin requires Read permission.

After that, the admin requires Delete permission to delete a Template template (536), but not a Content template (449).

Otherwise, Edit permission is required to finalize adding/editing a Content template (367), but work is being done and message banners queued before eventually checking for Edit permission at $proceed (353).

No permission is required to import or export Content template files, or change the default Template template.

Just an observation.

**Comment by abrookbanks** [comment]
Thank you.
