### ISSUE TITLE
This caused my storefront to crash, I guess the ??= is an not allowed php7 tag.

### ISSUE THREAD

**Issue by cobaltjeh** [cubecart/v6#3341]
https://github.com/cubecart/v6/blob/822b0252743fe06f3bab487f243d64d9c58564c0/classes/cubecart.class.php#L2184C24-L2184C85

[<strong>Exception</strong>] public_html/classes/cubecart.class.php:2175 - syntax error, unexpected '='

**Comment by bhsmither** [comment]
It is new to PHP 7.4.

For CC652 (not yet published), in CubeCart's file ini.inc.php, line 13, a test is made to make sure this version of CubeCart is running under PHP 7.4 or newer. If not, CubeCart is supposed to die.

For CC651, line 2173 has the above statement with the "null-coalescing assignment" operator, and in ini.inc.php, the test is made against PHP 7.1. That test against PHP 7.1 is an unfortunate bug.

**Comment by cobaltjeh** [comment]
I am running PHP 7.3.33, so that confirms it.

**Comment by abrookbanks** [comment]
Yes sorry. PHP 7.4 min. CubeCart is checking incorrectly. Its been hard to keep up with min versions. PHP requirements have moved very quickly recently.
