### ISSUE TITLE
Code Check: Newsletter Subscription Status

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3342]
With respect to #2747, the template customers.index.php, lines 173-175, has these variables: `$CUSTOMER.subscription_status.0.status`, and `$CUSTOMER.subscription_status.0.dbl_opt`.

This only works if there is a record in CubeCart_newsletter_subscriber. Otherwise, `$CUSTOMER.subscription_status` is false.

Suggest using: `$CUSTOMER.subscription_status.status` and `$CUSTOMER.subscription_status.dbl_opt`.

Therefore, also in customers.index.inc.php;
```
Line 453:
From:
$customer['subscription_status'] = $GLOBALS['db']->select('CubeCart_newsletter_subscriber', false, array('email' => $customer['email']));
To:
$customer['subscription_status'] = array('status' => '0', 'dbl_opt' => '0');
if(($cns = $GLOBALS['db']->select('CubeCart_newsletter_subscriber', false, array('email' => $customer['email']))) !== false) {
  $customer['subscription_status'] = $cns[0];
}

Line 457, in part:
From:
? $_POST['customer'] : array('subscription_status' => false);
To:
? $_POST['customer'] : array('subscription_status' => array('status' => '0', 'dbl_opt' => '0'));
```

**Comment by abrookbanks** [comment]
Thank you.

**Comment by bhsmither** [comment]
Take note of the suggested change in the template.

**Comment by abrookbanks** [comment]
Whoops! Thank you!!
