### ISSUE TITLE
Emails to Multiple Admins

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3345]
Outlier condition, probably, maybe...

Should the situation be that there is more than one administrator that is enabled to "Receive order notifications", while also having a different "Default Language" choice, then...

In `Order->_notifyAdmins()`, the return is a comma-separated string of email addresses.

But no consideration is given to which language to use for each admin to receive the emails.

**Comment by abrookbanks** [comment]
This is a bit more complicated than I first hoped.

**Comment by hairy-dog** [comment]
Also an outlier case, but perhaps as likely. 

Admins speak different languages. Orders with comments in a particular language (or at least are from a customer with that language chosen as default) might best be routed to an admin who understands that language.

Or maybe it's getting a bit too complex.

**Comment by abrookbanks** [comment]
It's a good idea. I can't believe we have many merchants with multilingual staff but it doesn't mean we shouldn't support this.

**Comment by abrookbanks** [comment]
It's annoying I started to code this but got to a bottleneck as it loads the email template and then sends the same content to all.
