### ISSUE TITLE
Customer Language Indicator on Edit Customer Screen

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3346]
Feature Request:

When adding or editing a customer, provide a selector to choose, indicate, change the Language that will get stored in CubeCart_customer, 'language' column.

When viewing the customer list, show a flag (maybe just as a prefix on the customer name).

**Comment by bhsmither** [comment]
For a case study, see:
```
https://forums.cubecart.com/topic/58606-email-templates/
```

**Comment by abrookbanks** [comment]
Thank you.

<img width="906" alt="Screenshot 2023-07-17 at 10 21 07" src="https://github.com/cubecart/v6/assets/4520803/865a3dce-6151-40ba-83b7-765368cbb74f">
<img width="577" alt="Screenshot 2023-07-17 at 10 22 19" src="https://github.com/cubecart/v6/assets/4520803/59a81d9a-5b54-4ae0-b1d2-ba3c1ba24852">
