### ISSUE TITLE
Selected pages cycle back to homepage

### ISSUE THREAD

**Issue by chilled35** [cubecart/v6#335]
http://thebarrymusicshop.com/martin-sp-12-54-gauge-strings.html << attempt to visit this page of a newly created product, the site redirects back to the homepage.  Sitemap and caches cleared.

**Comment by hairydogltd** [comment]
Which pages don't go to the home page?

**Comment by abrookbanks** [comment]
Hmm I can't reproduce this one. If anything I'd imagine there to be a 404 not found error. I hope we can reproduce this for you to fix it.

**Comment by bhsmither** [comment]
If you can look at your database using an external utility, such as phpMyAdmin usually found in your hosting control panel, look at CubeCart_seo_urls. Find a record where the path is:
`martin-sp-12-54-gauge-strings`
What is its `type` and `item_id`?

**Comment by abrookbanks** [comment]
Please let unknown if you can still reproduce this and we can reopen this.

**Comment by chilled35** [comment]
Sorry for the delay in getting back to ya... busy taking photos!!

So...I've no idea what's happened, perhaps it may have been a cache issue on my browser, since the site appears to be working just dandy.  As it transpired the other day when I logged this 'bug', the only pages that didn't refresh back to the homepage were the contact us form, along with the cart (having managed to add something to it).

I'll ensure my cache/cookies are cleared next time something daft happens. :|

**Comment by bhsmither** [comment]
This might be related to issue #330.

**Comment by hairydogltd** [comment]
It wasn't your browser cache: I saw the same problem and had never visited your site before. It's fine now.  I wonder if there was a problem with the server's time settings

**Comment by chilled35** [comment]
I've no idea to be honest... I'm less than impressed with the hosting service that the site sits on, but, as I've said elsewhere, I have no say in where the site is hosted, sadly.  I'm just helping out my brother-in-law who works at the music shop since I've had previous experience with CubeCart....

**Comment by abrookbanks** [comment]
I've been able to reproduce this. It's because the cache has cached no data before its been set. Either a cache clear or admin login fixes it... proper solution is required.
