### ISSUE TITLE
Function Arguments Wrong Order

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3351]
In the Foundation template element.markup.json-ld.php, find this:
```
"price":"{/literal}{preg_replace($PRODUCT.price_to_pay,'/[^0-9.]+/','')}{literal}",
```
Please note that the 'subject' must be the last argument.

Suggest:
```
"price":"{/literal}{preg_replace('/[^0-9.]+/','',$PRODUCT.price_to_pay)}{literal}",
```

**Comment by bhsmither** [comment]
The change appeared here:
https://github.com/cubecart/v6/commit/9d443336331dd17165ea0c60ad057b39f163bf4a#diff-2b71f6891a7af8516499917cb35d065eecc2639bce5af5fa2b5068b6f746abbc
```
From:
"price":"{/literal}{$PRODUCT.price_to_pay|regex_replace:'/[^0-9.]+/':''}{literal}",
To:
"price":"{/literal}{preg_replace($PRODUCT.price_to_pay,'/[^0-9.]+/',''}{literal}",
```

**Comment by abrookbanks** [comment]
Thanks!!!
