### ISSUE TITLE
PHP 8.2 GD Dynamic Property

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3353]
In the GD class, `_gdImageArray` is not declared.

**Comment by bhsmither** [comment]
In Module class, near line 474, `$this->_settings` is given a module's settings, whatever they may be.

Then, near line 187, where the `$value` of each array element of `$this->_settings` is being passed through `str_replace()`, where `$subject` must be a string or an array of strings.

Some modules, perhaps freshly installed or not using a generally expected module setting, will have some settings not yet set. (One example is the AIOS, which has no value set for 'countries' and 'disabled_countries' because it does not use `CubeCart_modules.countries` database column.)

Suggest working with `$value` in a way where not yet set values (that is, _null_) are properly dealt with.

Perhaps:
```
$GLOBALS['smarty']->assign('MODULE', $basesettings);
// Assign checked & selects
if (is_array($this->_settings)) {
  $filter_result = array_filter( $this->_settings, 'is_scalar' );  // removes all NULLs
  foreach ($filter_result as $setting => $value) {
  $value = str_replace(array('.', '-'), '_', $value);
```

**Comment by abrookbanks** [comment]
Thank you it works really well.
