### ISSUE TITLE
GD Resize to Maintain Transparency

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3355]
Feature Request:

I have been trying various sample code found elsewhere to get my source images (well, specifically, the no-image.png skin files) to survive getting resized through the GD class while maintaining what is transparent.

**Comment by hairy-dog** [comment]
I've found that web browsers do a great job of resizing images. So I take a completely different approach...

**Comment by abrookbanks** [comment]
I don't think this is needed. Since {a recent version of CubeCart} images are converted to JPG by the browser automatically. 

I'm not sure if the browser would convert a transparent PNG to JPG successfully. Something to try I suppose.

**Comment by hairy-dog** [comment]
Why not use webp? That gives small file sizes and supports transparency.

**Comment by bhsmither** [comment]
> Since {a recent version of CubeCart} images are converted to JPG by the browser automatically.

Sorry? That seems to make no sense.

**Comment by abrookbanks** [comment]
We took the 350kb limit off the upload filesize and swapped to any filesize but dropzone uses the browser to max the image at 2000 pixels but always convert to JPG. Keeping the same mime type didn't work.

**Comment by bhsmither** [comment]
Interesting.

But I will continue to try as that is how I want my skin to behave (currently experimenting with no-image.png), and also knowing that I can FTP massive amounts of images and then (probably) 'Update File List".

**Comment by abrookbanks** [comment]
OK cool. :) Let us know how you get on as it probably is still worth adding for your case at hand. I had a quick search but it doesn't seem that there is an obvious answer.
