### ISSUE TITLE
Code Check: Undefined Array Key

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3360]
In cubecart.class.php, compare lines 1224 and 1227.

For line 1224, PHP reports an undefined array key 'billing_address'.

Suggest 1224 grouping by parenthesis match line 1227.

**Comment by bhsmither** [comment]
In cart.class.php, near lines 1069-1073, the variable `$basket_data` could get set to boolean _false_, yet the next line wants to see `$basket_data` as an array.

Perhaps:
```
From:
$basket_data = ($this->basket) ? $this->basket : false;
To:
$basket_data = ($this->basket) ? $this->basket : array();
```
And if that happens, line 1084 has nothing to iterate on.

**Comment by abrookbanks** [comment]
Thank you.

**Comment by bhsmither** [comment]
Please do not overlook CubeCart class, line 1224, parenthesis grouping.

**Comment by abrookbanks** [comment]
Whoops!! Thank you.
