### ISSUE TITLE
USPS Ground Advantage for USPS shipping extention

### ISSUE THREAD

**Issue by exibar** [cubecart/v6#3364]
there is no option in the 1.15 version of the USPS shipping module for the new Ground Advantage that replaced first class mail.
this results in ONLY priority mail showing up as an option for me.
the request log file clearly shows ground advantage coming abck from the API, however, there is no option for us to choose that mail option :-(
 one request log entry:
<MailService>USPS Ground Advantage&amp;lt;sup&amp;gt;&amp;#8482;&amp;lt;/sup&amp;gt; Cubic</MailService>

the Module need fixing and is broken right now, please please please fix this.

thank youj!

**Comment by exibar** [comment]
I have modified the code to work with ground advantage, where can I put it in Git?

**Comment by bhsmither** [comment]
Thank you for your work. It is much appreciated.

The CubeCart CEO should be getting in touch with you Monday.

**Comment by exibar** [comment]
> Thank you for your work. It is much appreciated.
> 
> The CubeCart CEO should be getting in touch with you Monday.

 I'm sure he will be, LOL.
