### ISSUE TITLE
usps Ground Advantage replaced First Class

### ISSUE THREAD

**Issue by exibar** [cubecart/v6#3365]
ground advantage has replaced first class mail as of this month.
I have modified the code to allow for ground advantage.

where can I upload the new code?

**Comment by abrookbanks** [comment]
2.6.1 - https://www.usps.com/business/web-tools-apis/2023-web-tools-release-notes.pdf 

You can send it to support@cubecart.com. Huge help. Thank you.

**Comment by abrookbanks** [comment]
1.1.6 released. Thanks for sharing your findings.
