### ISSUE TITLE
CKEditor Dialogs Acquire CSS from Admin

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3368]
Just FYI:

View the Description tab for a product. Click the `Link` toolbutton. Switch to the Advanced tab. Note that "Force Download" is offset a bit from the left edge.

That is because the admin's layout.css rule for `input[type=checkbox]` (line 58) sets the opacity to zero. There is a checkbox here, but not visible.

**Comment by abrookbanks** [comment]
Good find. Thanks. I wish we could lose the image checkboxes and go with default browser theme.
