### ISSUE TITLE
Allow for promo code stacking

### ISSUE THREAD

**Issue by patcou** [cubecart/v6#3369]
Hello everyone, I introduce myself, Patrick. I am a new cubecart user that I installed for a running association. The idea is to create an online store for our members on running clothes. 
First of all, I thank the creators of this solution which works well. 
On the other hand I am confronted with a problem, I have a series of clothes to which the members will be able to apply a coupon. On another series of clothes, they can apply another reduction coupon. However, I did several tests and it does not seem possible to combine several coupons on an order. Do you have the same problem and would it be interesting to combine the coupons. 

Thank you. 

Best regards. 
Patrick.

**Comment by abrookbanks** [comment]
Thanks Patrick and welcome to CubeCart. It's great to have you.  I'll do my best to look into this sometime this week.

**Comment by abrookbanks** [comment]
I've put this down as a feature request. This can be reopened when/if it reaches the development roadmap.
