### ISSUE TITLE
Code Check: searchCatalogue()

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3370]
How probable is it that there could be a call to `Catalogue->searchCatalogue('scalar_string')`?

Edit: Yes, at cubecart.class.php, near line 893:
```
$GLOBALS['catalogue']->searchCatalogue($_GET['cat_id'], $page, $catalogue_products_per_page);
```
If so, PHP will complain about using an `illegal string offset` on scalar at catalogue.class.php, near line 1853:
```
            if($GLOBALS['config']->get('config', 'hide_out_of_stock')=='1') {
                $search_data['inStock'] = true;
            }
```
Everywhere else I looked, there is testing against `$search_data` array elements.

**Comment by abrookbanks** [comment]
Did I get that right?

**Comment by bhsmither** [comment]
A numerical value is also a scalar.

I will experiment on the `function searchCatalogue()`.

**Comment by bhsmither** [comment]
Let's put a pin in this.

Near line 1827 (CC651), there is:
```
        // Presence of a join is similar to presence of a search keyword
        if (!empty($joins) || is_array($search_data)) {
```
Only because `$joins` is empty does the test therefore rely on `$search_data` being an array (not a scalar) to do any kind of searching. Thus, there will not be the case where `$search_data` could be a scalar.

EXCEPT: What happens when `$joins` is not empty? That means `$search_data` does not have to be an array. `$search_data` could be a scalar value - a cat_id or 'sale', for example.

The next code that deals with `$joins` is at line 1986 where `$joinString` could be an empty string. So, nothing to worry about here when `$joins` is a scalar.

**Comment by abrookbanks** [comment]
Closing for now and I don't know how to move forward.
