### ISSUE TITLE
Gift card assistance

### ISSUE THREAD

**Issue by swim426** [cubecart/v6#3372]
This is my first post so I apologize if I'm in the wrong spot or misunderstanding something
I made a gift card for our store and it worked yesterday, I was able to purchase a gift card for 10 dollars and send it to myself.
Today I had a customer try to buy a gift card but the option to pick a value is gone and I cant get it to show on the website.

**Comment by abrookbanks** [comment]
Sorry this is not a bug or a support channel. Please try our forums or https://www.cubecart.com/technical-support
