### ISSUE TITLE
Make it easier to select image for options

### ISSUE THREAD

**Issue by mrobertbell** [cubecart/v6#3374]
It is wonderful to be able to assign an image to each product option, but it's a bit of a pain to find the appropriate image in its folder when there are many products. If the search function cannot easily lead to a list with plus signs, perhaps a filter to list only assigned images could be implemented.

**Comment by abrookbanks** [comment]
This code navigates to the folder the option image resides in. Instead of having to remember or navigate back it will load the folder it lives in. 
e.g. `/images/source/aaa/bbb/image.jpg` if clicked will load the folder `/images/source/aaa/bbb`
