### ISSUE TITLE
PPCP: Heredoc Syntax

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3375]
In the file class.gui.head_js.php, there are three instances of using Heredoc syntax. The first instance is not compatible with PHP 7.2, which says:

> Prior to PHP 7.3.0, the closing identifier must begin in the first column of the line.

Unless there is a particular reason to indent the closing identifier, suggest placing it at column one of the line.

(I did not find any other instances of heredoc that has the closing identifier not at column one (paypal.class.php).

**Comment by abrookbanks** [comment]
Thanks. This will be fixed for the next release. I'm just waiting to finalise some stuff with PayPal.
