### ISSUE TITLE
PayPal Commerce stuck in "Processing"

### ISSUE THREAD

**Issue by ZeroProtons** [cubecart/v6#3378]
PayPal Commerce is stuck in "Processing" when in fact the "Order (is) Complete".
After purchase, a customer will see a perpetual circular arrow 'processing' GIF and be confused, waiting for it to complete processing.
It is possible for a customer to hit any button and bypass the screen.
Normally an invoice/transaction page would appear and a customer would need to press any button to continue(1). 

This appears to be a PayPal Commerce App issue.
"Pending" displays properly when a transaction is started but then stopped.
"Cancelled" displays properly when a purchase is cancelled or refunded 100% by the PayPal server.
Everything else seems to working great!

This behavior started early this year, and then fixed by our consultant programmer.
Then, around May or so, we noticed a very brief and tiny message on our CC dashboard saying that PayPal Commerce had be "updated".
Regrettably the problem was back!  It appears our installation was over-written with updated but faulty code.
It then occurred to us that a similar update over-wrote our function PayPal Commerce early in the year, causing the first issue.
We tried having our consultant correct the problem again, but this seems to be a **recurring issue** for every PayPal "update".
Then yesterday, another PayPal Commerce Update notice appeared.  To our dismay, this issue has not been fixed in this release.  Had we corrected it in the last few weeks, our work would likely have been overwritten again yesterday.  The "Processing" issue is definitely a "CubeCart as the creator of the PayPal module" issue.

(1) As a feature request:  Ideally, on return from a successful PayPal transaction, the screen should go to a web page of our choosing.  PayPal setup should have a checkbox [ ] and an [address box for a URL] so that a customer goes straight to new web page.  There is no point for a customer to be hanging around looking at an invoice (or now, seeing a swirling processing graphic).

**Comment by abrookbanks** [comment]
Thanks for the feedback. We have had a small amount of merchants reporting double payments on rare occasions. We have spent hours on end trying to reproduce this. This is the first clue we have had and hopefully it's the same issue. 

You don't have a screenshot do you or are able to reproduce this at all? I'll have a look at the code for a "processing" gif or any processing animation....

**Comment by abrookbanks** [comment]
Is this the gif or it is a series of dots?
![loading](https://github.com/cubecart/v6/assets/4520803/9d7bf904-42f5-4358-a208-61e3132f365f)

**Comment by abrookbanks** [comment]
Ignore the above. We have released 1.8.7 which add a click to continue. 
<img width="375" alt="Screenshot 2023-08-29 at 12 50 49" src="https://github.com/cubecart/v6/assets/4520803/80ad1dd5-4e17-4467-85fe-c8d5610ae4ea">

**Comment by abrookbanks** [comment]
Closing until we hear a need to reopen. Hopefully not.
