### ISSUE TITLE
Search Engines tab Bug

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#338]
There are 2 options, "Add category to product URL path?" and "Add subcategories to category URL path?" in the Search Engines tab. Have selected "no" for both and does not change URL for either?

**Comment by bhsmither** [comment]
I *think* these settings affect new products and new categories only.

This is what should happen, if I'm correct: If you edit an existing category, and blank out the field "Custom SEO URL Path" on the Search Engines tab, then a new SEO URL will be generated that incorporates the settings mentioned above.

If this isn't what you are observing, please let us have a step-by-step sequence that will reproduce the effect you see.

**Comment by abrookbanks** [comment]
Exactly right. It will only do this for new products or if the existing one has the current path removed. CubeCart won't interfere with existing SEO paths on upgrade.
