### ISSUE TITLE
Code Check: DateInterval::format() Placeholders

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3381]
In statistics.product.inc.php, near line 36, there is:
```
return $dtF->diff($dtT)->format($GLOBALS['language']->statistics['dhms']);
```
where the language phrase is:
```
%a days, %h hours, %i minutes and %1$s seconds
```
I assert that `%1$s` got caught up in the sprintf() modifications to the language strings.

**Comment by abrookbanks** [comment]
Good find. Thanks.
