### ISSUE TITLE
Use Clearing Lightbox for all Cases

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3388]
Feature Request:

When there is more than one image assigned to a product, there is shown a set of thumbnails. There also exists the code to use a Clearing Lightbox (a feature of the Foundation system).

When there is only one image assigned, the Clearing Lightbox is not enabled. Instead, the code provided is a hard link to the source image. This causes the browser to show a raw image - no HTML wrapper.

The Clearing Lightbox has access to, and shows, the image's 'title' attribute. A raw image has no accompanying data.

For the sole purpose of showing the 'title' attribute (perhaps given to the data-caption attribute?), request that the template code use the Clearing Lightbox even when there is only one image assigned.

Please see:
```
https://forums.cubecart.com/topic/58681-image-alt-and-title/
```

**Comment by abrookbanks** [comment]
Thank you!
