### ISSUE TITLE
Canonical URL's are not working correctly.

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#339]
If you are on a category page and sort the products in a different manner canonical URL is incorrect. This issue was also present in cc5. Brian Smither has written a code snippet for me which works flawlessly. Just copy him if necessary.
 {php}
$meta_canonical_path = '';
switch (strtolower($_GET['_a'])) {
  case 'document':$meta_canonical_path = $GLOBALS['seo']->getdbPath('doc',$_GET['doc_id']);break;
  case 'product':$meta_canonical_path = $GLOBALS['seo']->getdbPath('prod',$_GET['product_id']);break;
  case 'category':$meta_canonical_path = $GLOBALS['seo']->getdbPath('cat',$_GET['cat_id']);break;
  case 'certificates':$meta_canonical_path = $GLOBALS['seo']->getdbPath('certificates',0);break;
  case 'search':$meta_canonical_path = $GLOBALS['seo']->getdbPath('search',0);break;
  case 'contact':$meta_canonical_path = $GLOBALS['seo']->getdbPath('contact',0);break;
  case 'saleitems':$meta_canonical_path = $GLOBALS['seo']->getdbPath('saleitems',0);break;
  case 'login':$meta_canonical_path = $GLOBALS['seo']->getdbPath('login',0);break;
  case 'register':$meta_canonical_path = $GLOBALS['seo']->getdbPath('register',0);break;
}
if ($meta_canonical_path !== "" ) { // not a zero length string
  $meta_canonical_url = $GLOBALS['storeURL'] . "/" . $meta_canonical_path . ".html";
} elseif ($meta_canonical_path === "") { // is a default zero length string
  $meta_canonical_url = $GLOBALS['storeURL'] . "/";
}
$GLOBALS['smarty']->assign('META_CANONICAL', $meta_canonical_url);
{/php}

**Comment by abrookbanks** [comment]
https://github.com/cubecart/v6/commit/8196d4113f0ad9258c8be98dfe56be9d3d3b4f61 typo on commit issue number
