### ISSUE TITLE
Report for any period of all product sales

### ISSUE THREAD

**Issue by harris-organic** [cubecart/v6#3392]
Report for any period of all product sales - Feature request
In the support forum, there is a query about statistics.  https://forums.cubecart.com/topic/58258-statisticsbest-selling-products/#comment-255149
I have read through the above and wonder if on the statistics page. /shop/admin_xxxxx.php?_g=statistics#stats_prod_sales There could be a date range as there is in the filter tab for the report filter.  /shop/admin_xxxxx.php?_g=reports
That way one could get a report for any period of all product sales.

**Comment by bhsmither** [comment]
Working on it.

**Comment by abrookbanks** [comment]
> Working on it.

Cool. 😎

**Comment by harris-organic** [comment]
Hi Al,

Hope you are busy.

 

Just checking if an update to my site is on your todo list?

 

 

kindest regards

 

Duncan Harris

https://www.harrisorganicwine.com.au <https://urldefense.com/v3/__https:/www.harrisorganicwine.com.au__;!!IMEGuS19XJ1G!ht0F3rIgDn7TuLnO8FH1MHUEyvcPwEs0jJQ1EjtATjEq2bnmZEnzzP9BgZXEPj_7-OhTVs51ux22$>

**Comment by abrookbanks** [comment]
Hi Duncan, please don't reply to this email is it goes to a public website here: https://github.com/cubecart/v6/issues/3392

**Comment by abrookbanks** [comment]
<img width="776" alt="Screenshot 2024-03-18 at 14 02 11" src="https://github.com/cubecart/v6/assets/4520803/3187466d-8e03-445c-9940-f78d35a9dd8c">

**Comment by abrookbanks** [comment]
<img width="766" alt="Screenshot 2024-04-12 at 09 36 59" src="https://github.com/cubecart/v6/assets/4520803/34d1e347-68e7-4b8a-8841-bc31960e0eff">

**Comment by hairy-dog** [comment]
Just a thank-you for this. It's very much a must-have for a couple of online stores that I look after, and it makes CC a viable solution.

**Comment by abrookbanks** [comment]
This is done. It will be released next week.
