### ISSUE TITLE
Product Statistics: Add an Edit Link

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3393]
Feature Request:

On the Product Statistics page, please add a link to the admin product edit page for that product.

**Comment by abrookbanks** [comment]
<img width="863" alt="Screenshot 2023-10-03 at 09 35 40" src="https://github.com/cubecart/v6/assets/4520803/c8d85013-2095-4798-a83d-27ce911a7874">

**Comment by abrookbanks** [comment]
Thanks!
