### ISSUE TITLE
PHP 8 Warning

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3397]
In orders.index.inc.php line 307, when the admin is reviewing an order where that order may have been administratively created, there may not be any serialized data held in CubeCart_order_summary, 'basket' column.

If not, `$basket_array` will be _false_.

**Comment by abrookbanks** [comment]
Thanks.

**Comment by bhsmither** [comment]
Then, statements that want to use `$basket_array` should prepare for unknown array keys:
```
$basket_array['weight'] ?? 0
```

**Comment by abrookbanks** [comment]
Good point!

**Comment by abrookbanks** [comment]
Thanks again.
