### ISSUE TITLE
RSS Feed Interference

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3398]
The Dashboard is wanting to fetch the latest news from the RSS server located at the forums. Cloudflare's 'Anti-Bot' protection mechanism ("Verifying your site is secure.") interferes with every ancillary function of the forums, from getting user profile popups, to ajax-requested 'mentions' list, to re-editing code windows, etc, to fetching the RSS feed.

**Comment by abrookbanks** [comment]
Thanks! I missed to whitelist this URI...

**Comment by abrookbanks** [comment]
Fixed now via Cloudflare.
