### ISSUE TITLE
Titles for certain pages

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#340]
Pages like Contact Us, Sale Items and Gift Certificates do not have the ability to set their own page titles which creates duplicate title page errors in Webmaster Tools. Please add this feature.

**Comment by bhsmither** [comment]
This might be interesting:
https://forums.cubecart.com/topic/48636-add-meta-titles-and-decription/

**Comment by bondimedical3** [comment]
It does fix the issue but as you say it is a hack and will be overwritten whenever you update the store.

**Comment by bhsmither** [comment]
I mention it here as an avenue towards incorporating it, or something like it, in the core code.

The Github is not the place to propose 'hacks'.

**Comment by bondimedical3** [comment]
Oh...sorry.
