### ISSUE TITLE
Feature request : add order ID for admin log

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#3404]
Ref : https://github.com/cubecart/v6/issues/3275

Any reason why the order number wasnt added when this was done as this would add to the very useful addition above

**Comment by abrookbanks** [comment]
Great idea. Thanks!

**Comment by bhsmither** [comment]
And customer_id, and admin_id when adding/editing admins, code snippet_id, coupon_id, manufacturer id, module_id, newsletter_id,  etc, etc, etc.

**Comment by abrookbanks** [comment]
Implemented with #3487 ... more scenarios could be added.
