### ISSUE TITLE
Admin links, page=all

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3406]
There seems to be some bad math happening when calculating the data for pagination for lists in admin.

For example, show Countries/Zones. Note the pagination. Click on the [2] pagination link.

Now, manually change `page-country=2` to `page-country=all` in the address bar and have the browser go there.

Seemingly, all records are listed but the pagination sequence is not right.

Other lists, receiving a manual `page=all` appropriately crafted querystring behave differently.

(Regardless that there is no actual 'All' link that gets built into the pagination string.)

**Comment by abrookbanks** [comment]
https://github.com/cubecart/v6/assets/4520803/ff47575b-8829-401d-885b-b69ac1219cfe
