### ISSUE TITLE
Gateway - Feature Request

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#341]
I have take this idea from Magento. They have the ability to set different gateways for different countries. There are hundreds of reasons why merchants would require this and I believe it would greatly improve the functionality of CubeCart as an e-commerce store.

**Comment by bhsmither** [comment]
There are "Allowed Zones" and "Disabled Zones" that imply one may choose which country the gateway is eligible to be used.

If you have tried this, does it not work for you?

**Comment by abrookbanks** [comment]
Brian is right. We have this functionality already. From my testing it works fine.

**Comment by bondimedical3** [comment]
If for example I want to have a gateway only display in Australia, what settings should I put in? Do I just add 'Australia' to "Allowed zones" or do I have to add every country into "Disabled zones"?

**Comment by abrookbanks** [comment]
Either will work. Least admin is to add Aus to the allowed. This will disable all others and only allow Aus.

**Comment by bondimedical3** [comment]
Fantastic. I have wanted this feature for years and didn't realise it was there all the time!
