### ISSUE TITLE
hCaptcha always fails

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#3411]
`$g_result->success` should be `$h_result->success`

**Comment by Noodleyman** [comment]
glad you added this here. I was getting tripped up by the same issue so saved me debugging time. thanks Al :)

**Comment by abrookbanks** [comment]
Sorry this oversight on my part caused you some bother.

**Comment by Noodleyman** [comment]
Nay bother, stuff happens. glad it was already found as saved me tracking it :)

**Comment by abrookbanks** [comment]
Have a great day Alec. :)
