### ISSUE TITLE
Registered Customer Login Issue / No Reply from Support Email

### ISSUE THREAD

**Issue by ekpsupplies** [cubecart/v6#3419]
Hi,

Can someone help us please, Wednesday evening our website has stopped customers from logging in if they are registered, and the checkout will not allow the customer to proceed to the check out phase because their email address is registered and it requires them to login.

We have tried to email the support email but unfortunately not receiving a reply.

Our website is hosted through cubecart hosted, any help would be greatly appreciated as this is severely effecting our sales now

Thanks.

Dean.
EKP Supplies

**Comment by abrookbanks** [comment]
For some reason emails weren't logged in the help desk. This issue was resolved after fixing a corrupt session table. 

Apologies for the communication issues.
