### ISSUE TITLE
PayPal Express opening on a different url - Affects Analytics

### ISSUE THREAD

**Issue by Caranxnet** [cubecart/v6#3421]
Hi Al,

I have a "little" problem here. Have a loo at the image. Looks like when people make a payment with the fast PayPal gateway, as highlighted, the website takes them to : https://www.caranx.net/index.php?_a=confirm and not to https://www.caranx.net/index.php?_a=complete.

This means that every payment done through PayPal fast lane is not registered in Analytics, and we have trouble following the sales and improve the ads campaign.

Is there a way that from there, people could be redirected to https://www.caranx.net/index.php?_a=complete instead?

Thanks for helping out

ciao

Nicola
![caranx-net-index-php-_a-gateway](https://github.com/cubecart/v6/assets/116885861/36d0605b-5146-4a9a-b9d9-70f64af0f4b4)

**Comment by abrookbanks** [comment]
On successful payment the customer will be redirected to the confirmation screen. It is this page that logs the sale with Google (assuming they have accepted the cookie usage).

**Comment by Caranxnet** [comment]
Al,

 

I’d like to re-open this because I don’t know if you fixed the problem or not

 

Hi Al,

I have a "little" problem here. Have a loo at the image. Looks like when people make a payment with the fast PayPal gateway, as highlighted, the website takes them to :  <https://www.caranx.net/index.php?_a=confirm> https://www.caranx.net/index.php?_a=confirm and not to  <https://www.caranx.net/index.php?_a=complete> https://www.caranx.net/index.php?_a=complete.

This means that every payment done through PayPal fast lane is not registered in Analytics, and we have trouble following the sales and improve the ads campaign.

Is there a way that from there, people could be redirected to  <https://www.caranx.net/index.php?_a=complete> https://www.caranx.net/index.php?_a=complete instead?

Thanks for helping out

ciao

Nicola

 

 

De: Al Brookbanks ***@***.***> 
Enviado el: lunes, 13 de noviembre de 2023 9:30
Para: cubecart/v6 ***@***.***>
CC: Caranxnet ***@***.***>; Author ***@***.***>
Asunto: Re: [cubecart/v6] PayPal Express opening on a different url - Affects Analytics (Issue #3421)

 

On successful payment the customer will be redirected to the confirmation screen. It is this page that logs the sale with Google (assuming they have accepted the cookie usage).

**Comment by abrookbanks** [comment]
Nicola please can you email support {@} cubecart dot com for technical support.

**Comment by Caranxnet** [comment]
Sorry, my bad 😊

 

De: Al Brookbanks ***@***.***> 
Enviado el: jueves, 16 de noviembre de 2023 11:58
Para: cubecart/v6 ***@***.***>
CC: Caranxnet ***@***.***>; Author ***@***.***>
Asunto: Re: [cubecart/v6] PayPal Express opening on a different url - Affects Analytics (Issue #3421)

 

Nicola please can you email support {@} cubecart dot com for technical support.
