### ISSUE TITLE
Word Choice

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3422]
In admin, Statistics, Best Customers tab, if the query returns no results - because no orders exist as Complete (status=3) - the 'else' phrase displayed is from `[statistics][notify_customers_none]` = "No customers exist.".

That cannot be absolutely true.

Suggest: "No existing customers have had their order completely fulfilled."

**Comment by abrookbanks** [comment]
Thanks! Good find.

**Comment by abrookbanks** [comment]
See: 2442aaabccb450457fddab8205d2864e38f555e6 

Typo on commit.
