### ISSUE TITLE
Code Tweak 2

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3429]
In `ACP->addTabControl()`, the `$name` argument is not assured to be a string (mostly never will happen when using `$lang` elements - but there are hooks that invite mayhem).

Later, in `ACP->showTabs()`, the tab name is given to PHP's function `ucfirst()`. If the argument is not an actual string, PHP may complain.

Suggest in `addTabControl()`:
```
From:
if (!empty($name)) {
To:
if (!empty(settype($name,'string'))) {
```

**Comment by abrookbanks** [comment]
Thanks.
