### ISSUE TITLE
SQL Errors after b7 clean install

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#343]
The below errors are in the error log immediately after doing a clean b7 install.

Yesterday, 18:21 	File: [seo.class.php] Line: [610] "INSERT INTO `CubeCart_seo_urls` (`type`,`item_id`,`path`,`custom`) VALUES ('prod','1','test-category/test-product','0');" - Duplicate entry 'test-category/test-product' for key 'PRIMARY'

	Yesterday, 18:21 	File: [seo.class.php] Line: [610] "INSERT INTO `CubeCart_seo_urls` (`type`,`item_id`,`path`,`custom`) VALUES ('login','','login','0');" - Duplicate entry 'login' for key 'PRIMARY'

	Yesterday, 18:21 	File: [seo.class.php] Line: [610] "INSERT INTO `CubeCart_seo_urls` (`type`,`item_id`,`path`,`custom`) VALUES ('register','','register','0');" - Duplicate entry 'register' for key 'PRIMARY'

	Yesterday, 18:21 	File: [seo.class.php] Line: [610] "INSERT INTO `CubeCart_seo_urls` (`type`,`item_id`,`path`,`custom`) VALUES ('cat','1','test-category','0');" - Duplicate entry 'test-category' for key 'PRIMARY'

	Yesterday, 18:21 	File: [seo.class.php] Line: [610] "INSERT INTO `CubeCart_seo_urls` (`type`,`item_id`,`path`,`custom`) VALUES ('saleitems','','sale-items','0');" - Duplicate entry 'sale-items' for key 'PRIMARY'

	Yesterday, 18:21 	File: [seo.class.php] Line: [610] "INSERT INTO `CubeCart_seo_urls` (`type`,`item_id`,`path`,`custom`) VALUES ('certificates','','gift-certificates','0');" - Duplicate entry 'gift-certificates' for key 'PRIMARY'

	Yesterday, 18:21 	File: [seo.class.php] Line: [610] "INSERT INTO `CubeCart_seo_urls` (`type`,`item_id`,`path`,`custom`) VALUES ('search','','search','0');" - Duplicate entry 'search' for key 'PRIMARY'

	Yesterday, 18:21 	File: [seo.class.php] Line: [610] "INSERT INTO `CubeCart_seo_urls` (`type`,`item_id`,`path`,`custom`) VALUES ('prod','1','test-category/test-product','0');" - Duplicate entry 'test-category/test-product' for key 'PRIMARY'

	Yesterday, 18:21 	File: [seo.class.php] Line: [610] "INSERT INTO `CubeCart_seo_urls` (`type`,`item_id`,`path`,`custom`) VALUES ('saleitems','','sale-items','0');" - Duplicate entry 'sale-items' for key 'PRIMARY'

	Yesterday, 18:21 	File: [seo.class.php] Line: [610] "INSERT INTO `CubeCart_seo_urls` (`type`,`item_id`,`path`,`custom`) VALUES ('doc','2','about-us','0');" - Duplicate entry 'about-us' for key 'PRIMARY'

	Yesterday, 18:21 	File: [seo.class.php] Line: [610] "INSERT INTO `CubeCart_seo_urls` (`type`,`item_id`,`path`,`custom`) VALUES ('doc','3','terms-and-conditions','0');" - Duplicate entry 'terms-and-conditions' for key 'PRIMARY'

	Yesterday, 18:21 	File: [seo.class.php] Line: [610] "INSERT INTO `CubeCart_seo_urls` (`type`,`item_id`,`path`,`custom`) VALUES ('doc','4','privacy-policy','0');" - Duplicate entry 'privacy-policy' for key 'PRIMARY'

	Yesterday, 18:21 	File: [seo.class.php] Line: [610] "INSERT INTO `CubeCart_seo_urls` (`type`,`item_id`,`path`,`custom`) VALUES ('doc','5','returns-policy','0');" - Duplicate entry 'returns-policy' for key 'PRIMARY'

	Yesterday, 18:21 	File: [seo.class.php] Line: [610] "INSERT INTO `CubeCart_seo_urls` (`type`,`item_id`,`path`,`custom`) VALUES ('contact','','contact-us','0');" - Duplicate entry 'contact-us' for key 'PRIMARY'

	Yesterday, 18:21 	File: [seo.class.php] Line: [610] "INSERT INTO `CubeCart_seo_urls` (`type`,`item_id`,`path`,`custom`) VALUES ('prod','1','test-category/test-product','0');" - Duplicate entry 'test-category/test-product' for key 'PRIMARY'

	Yesterday, 18:21 	File: [seo.class.php] Line: [610] "INSERT INTO `CubeCart_seo_urls` (`type`,`item_id`,`path`,`custom`) VALUES ('prod','1','test-category/test-product','0');" - Duplicate entry 'test-category/test-product' for key 'PRIMARY'

	Yesterday, 18:21 	File: [seo.class.php] Line: [610] "INSERT INTO `CubeCart_seo_urls` (`type`,`item_id`,`path`,`custom`) VALUES ('prod','1','test-category/test-product','0');" - Duplicate entry 'test-category/test-product' for key 'PRIMARY'

	Yesterday, 18:21 	File: [seo.class.php] Line: [610] "INSERT INTO `CubeCart_seo_urls` (`type`,`item_id`,`path`,`custom`) VALUES ('saleitems','','sale-items','0');" - Duplicate entry 'sale-items' for key 'PRIMARY'

	Yesterday, 18:21 	File: [seo.class.php] Line: [610] "INSERT INTO `CubeCart_seo_urls` (`type`,`item_id`,`path`,`custom`) VALUES ('prod','1','test-category/test-product','0');" - Duplicate entry 'test-category/test-product' for key 'PRIMARY'

	Yesterday, 18:21 	File: [seo.class.php] Line: [610] "INSERT INTO `CubeCart_seo_urls` (`type`,`item_id`,`path`,`custom`) VALUES ('prod','1','test-category/test-product','0');" - Duplicate entry 'test-category/test-product' for key 'PRIMARY'

**Comment by abrookbanks** [comment]
Did the database already exist before install? If so you should have used the "Drop Tables" checkbox.

It looks like you have installed into an existing database that already had table and data schema.

**Comment by Noodleyman** [comment]
no, was a clean, empty database before install.

**Comment by Noodleyman** [comment]
The only thing that was different about this install is that I got the .htaccess error because it couldn't create it.

I changed permissions, refreshed the page and then put the permissions back again. Perhaps that somehow triggered the SQL errors?

other than that, it was a clean install with nothing out of the ordinary.

**Comment by abrookbanks** [comment]
OK thanks for the info. I can't reproduce it. I don't see this ticket as a problem unless the php error log is reporting this issue over and over and over..

**Comment by abrookbanks** [comment]
I can't reproduce this. At the same time it's not really an issue. The path has a unique column so long as everything settles this doesn't matter at all.
