### ISSUE TITLE
Choice of Variable Name

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3432]
Trivial:

In `Catalogue->searchCatalogue()`, there is a variable named `$max_word_len`. It holds the value from `DB->getWordSearchLen()` which gets the database's _minimum_ word length for a FULLTEXT search.

Suggest `$fulltext_min_word_len`. (There are two instances of this variable.)

Also, there is a variable named `$search_str_len`. The name is somewhat misleading.

Suggest `$longest_search_word_len`. (There are six instances of this variable.)

**Comment by abrookbanks** [comment]
Thanks.
