### ISSUE TITLE
Product Listing Sort by Image

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#344]
Regarding #334, in products.index.inc.php, near line 1219:
```
'image'   => $GLOBALS['db']->column_sort('image', $lang['catalogue']['title_image'], 'sort', $current_page, $_GET['sort']),
```
This implies that the product listing can be sorted by image. Current database schemas do not record the image name in CubeCart_inventory -- which would be needed for the query near line 1252:
```
if (($where === false || strlen($where) > 0) && ($results = $GLOBALS['db']->select('CubeCart_inventory', false, $where, $_GET['sort'], $per_page, $page)) !== false) {
```

**Comment by abrookbanks** [comment]
Good find thanks Brian.
