### ISSUE TITLE
Preview Icon for Category List, Documents List

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3447]
In admin, Product Inventory list, the Magnifier icon is used to preview that product by bringing up a new browser tab to show the product on storefront.

Currently, however, the Categories list use the magnifier icon to go to the Product Inventory list having been filtered against the assignment to a specific category.

Request that the magnifier icon be used to preview that category in a new browser tab to show the category on storefront. (Might save some clicks when drilling down.)

Request that a different icon be used to indicate going to a filtered listing - such as a funnel.

Request that the item's popularity not be incremented (if not already).

Request the same for Site Documents.

Request that since the preview pages come from an admin command, they be shown regardless of status, visibility, or stock level hidden states (if not already).

**Comment by abrookbanks** [comment]
Really like this. Thank you!
