### ISSUE TITLE
Possible security issue

### ISSUE THREAD

**Issue by PumpkinCreek** [cubecart/v6#3448]
I received this message from a client today:

"When I try to login to your site, I am warned (and blocked) by my security software, which tells me that there is malicious password stealing software on your login page."

I am using cubecart version 6.5.3

The client's security software is Bitdefender.

**Comment by abrookbanks** [comment]
The clients website may have malware on it. I would suggest giving it a thorough clean:
https://forums.cubecart.com/topic/51310-how-to-clean-up-a-hacked-cubecart-store/ 

That forums post is old but the principle still applies. If you want us to do this for you we are happy to under our [technical support services](https://www.cubecart.com/technical-support).
