### ISSUE TITLE
Admin Layout

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3457]
Very inconsequential:

Show the Dashboard.
Collapse all of the Nav Menu headings.
Reload the Dashboard.

Note that the Extensions block overflows the bottom edge of the main content area.

Switching to a different tab recalculates the min-height of that area.

Suggest the CSS rule:
```
#dashboard .extension-container {
	width: 1000px;
	display: inline-block;
}
```

**Comment by abrookbanks** [comment]
Excellent find. Thank you.
