### ISSUE TITLE
Tab Content Too Tall

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3458]
I am not able to reproduce it on the Demo site.

Note: have all Nav sections collapsed so to make that height as small as possible.

In the Dashboard, switching to Stock Warnings shows an abnormally tall `<div id='page_content'>`.

Entering Stock Warnings directly (`admin.php?#stock_warnings`), shows the height correctly, but tab to another pane, then back to Stock Warnings, and the height is abnormally tall.

(On the Demo site, it seems the height of the tab content is somewhat sticky, in that switching to a less populated tab content, does not shorten the content area - with a few exceptions.)

**Comment by bhsmither** [comment]
(In my browser:)
By adjusting the width of the Stock Warning table (originally 70% and having 20 rows) from 82% to 84% to 86%, the height of the tab content went from 1162, to 1062, to 829 when tabbing out of Stock Warnings and back into it. 94% is 779 pixels high, 96% at 762 high, 98% at 646 high, and 100% **(or no width at all)** at 638 high.

Have you ever seen the width of a table affect of the result when javascript calculates its height?

Applying a width to the table for Unsettled Orders also causes the calculated height to be too large.

**Comment by abrookbanks** [comment]
I can't reproduce this on my development store.

**Comment by abrookbanks** [comment]
I can't reproduce this still. Happy to look again if I can.
