### ISSUE TITLE
Per Page Control Missing

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3459]
Inconsequential:

In Dashboard, Stock Warnings, the Per Page drop-down selector is not present.

Related code in the source script for `##Stock Warnings` could be copied over from `##Pending Orders Tab`.

**Comment by abrookbanks** [comment]
<img width="1020" alt="Screenshot 2024-03-18 at 16 06 57" src="https://github.com/cubecart/v6/assets/4520803/d81320c8-638b-46ce-a52c-c4e62b46dbde">
