### ISSUE TITLE
HOOK_TAB_CONTENT

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#346]
If there is **not** a reason to leave out:
`$GLOBALS['smarty']->assign('HOOK_TAB_CONTENT', $GLOBALS['hook_tab_content']);`
from /admin/sources/settings.index.inc.php as next to the last statement, please add it.

Maybe because there are no hooks in settings.index.inc.php either.

I didn't check all the other files in sources.

**Comment by bhsmither** [comment]
Seems like HOOK_TAB_CONTENT is found only in products.index.inc.php.

**Comment by abrookbanks** [comment]
Danke!
