### ISSUE TITLE
Subscriber Log Phrase to Use Template Title

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3462]
Info Enhancement:

In admin, Mailing List, clicking on the `Log` link brings up a box showing records from CubeCart_subscriber_log.

A typical phrase from a record would be: `Newsletter with subject "Another Test" (ID #2) sent.`

This comes from `Newsletter->sendNewsletter()` where `2` is `$contents[0]['template_id']`.

Request that, instead of `$contents[0]['template_id']`, that the 'title' be used from `CubeCart_email_template` where `template_id=$contents[0]['template_id']`.

Also, `Newsletter with subject "Another Test" (ID #2) sent.` might be better placed in the language pack.

**Comment by abrookbanks** [comment]
Thanks!
