### ISSUE TITLE
Positive ID

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#347]
In the admin template settings.index.php and categories.index.php, for example, there is an outer block (in these cases, a `<form>` block) that offers a positive id (in these cases, 'form_settings' and 'cat_form').

I request that the admin templates be optimized in a way that every template (except element files that would be repeated) have some sort of HTML node that wraps the template entirely with an id attribute.

Perhaps `<section>`.

This would assist plugins that have javascript to positively specify a jQuery selector.

**Comment by abrookbanks** [comment]
I like this idea. Maybe we can get it into 6.1
