### ISSUE TITLE
FEATURE REQUEST:  connect into Paypal / shipstation for tracking info

### ISSUE THREAD

**Issue by exibar** [cubecart/v6#3474]
hiya!
    I would LOVE if cubecart would have a connection into Shipstation / Paypal for perhaps an hourly pull for tracking numbers and automatically update the order status to shipping from processing when the tracking number is added.
   Bonus points if cubecart could watch the tracking and update when item is delivered!

  thanks!
  Mike B

**Comment by exibar** [comment]
looks like Zencart can do it... we should be able to as well I'd think! :-)

https://help.shipstation.com/hc/en-us/articles/360026141731-Zen-Cart

**Comment by abrookbanks** [comment]
Closing to reopen if/when this starts development.
