### ISSUE TITLE
Admin product sorting by stock level doesnt work

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#3475]
Admin -> Products clicking on stock level (which is supposed to be a sortable column) actually sorts by price !

Validated in multiple stores - it gives url ?_g=products&node=index&sort[price]=ASC

**Comment by abrookbanks** [comment]
Am I in the wrong place? It's not sortable on my store.
<img width="1371" alt="Screenshot 2024-01-19 at 14 50 19" src="https://github.com/cubecart/v6/assets/4520803/23bdd6d7-15e2-47ed-a28e-e29ad41aa51d">

**Comment by havenswift-hosting** [comment]
![Admin-Control-Panel](https://github.com/cubecart/v6/assets/6114431/84a245cc-3596-49cf-8217-660f46448a28)

No, just my monitor not showing the field division lines and thinking the one next to "stock" was for stock which on a large screen, it looks much closer to.

In this case, can you please add it - simple and useful

**Comment by abrookbanks** [comment]
Unfortunately this isn't possible because it's dynamic against the product options matrix table. It would be possible if the store didn't use stock level at option level I suppose.

**Comment by abrookbanks** [comment]
Ok we can do this but only for stores that don't use the option_matrix table for stock.

**Comment by havenswift-hosting** [comment]
For stores that use matrix stock levels, would it not be possible to use the lower matrix level when doing a low to high sort and the upper matrix level when doing a high to low sort ?

**Comment by abrookbanks** [comment]
Not without very heavy complex SQL.

**Comment by bhsmither** [comment]
Perhaps a query very much like what is used to populate the Dashboard, Stock Warnings tab?

Do not filter out by 'stock warning level', and accept the result that when sorting by stock level, the list will contain all the variations, but perhaps not when sorting by any other column.
