### ISSUE TITLE
Style Conflict

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3479]
Trivial:

In 'Gui->addBreadcrumb()', the breadcrumb array element 'title' is wanting to have `ucfirst()`.

However, the foundation CSS rule near line 2230 makes the display of list items in breadcrumbs fully uppercase.

Should CubeCart HQ really want only upper-case-first, suggest adding an overruling rule in `cubecart.css`.
```
text-transform: none !important;
```

**Comment by abrookbanks** [comment]
Thanks.

**Comment by abrookbanks** [comment]
I reverted this as I think the idea is to apply UCFirst to skins that don't uppercase the text. Maybe I'm just used to it but for me the uppercase breadcrumb looks right. In older skins however the UCFirst would come into play.
