### ISSUE TITLE
FileManager $_sub_dir Might Be NULL

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3481]
Minor:

In filemanager.class.php, near line 714, there is:
```
$sub_dir = (substr($this->_sub_dir, 0, 1) == '/') ? $this->_sub_dir : '/'.$this->_sub_dir;
```
PHP8 complains if `$this->_sub_dir` is null, being deprecated for `substr()`.

It might be possible to assign the class attribute `$_sub_dir='';`.

Maybe easiest is to append a space to the test expression, then compare the zeroth position in the string:
```
$sub_dir = (($this->_sub_dir.' ')[0] == '/') ? $this->_sub_dir : '/'.$this->_sub_dir;
```

**Comment by abrookbanks** [comment]
Thank you.
