### ISSUE TITLE
File Manager: Image on Edit Details Tab

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3486]
Feature Request:

Very minor--

When providing details for an image on the Edit File page, there is a full scale image below the form control block.

Given that a full scale image could be really big, suggest scaling it down, and also moving it above the details entry block. Such as:
```
{if isset($mode_form)}
   <div id="fm-details" class="tab_content">
   <h3>{$LANG.filemanager.title_file_edit}</h3>
   {if $FILE.type == 1}
   <img src="{$FILE.filepath}{$FILE.filename}" alt="{$FILE.alt}" title="{$FILE.title}" style="max-height:200px;" /><br />
   Actual dimensions: {$FILE.width}px x {$FILE.height}px
   {/if}
  <fieldset>
  <div>
    <label for="filename">{$LANG.filemanager.file_name}</label>
```

**Comment by abrookbanks** [comment]
Thank you I followed this but added a link to load the master image in a new tab.

<img width="569" alt="Screenshot 2024-03-13 at 12 30 09" src="https://github.com/cubecart/v6/assets/4520803/f8472c24-823f-4e2c-b91a-ed04b9e0e5a7">
