### ISSUE TITLE
element.social.php missing from skins

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#349]
missing from the Skins from the marketplace for V6, so you get a white screen and an exception in the error log.

I put the file from foundation in place and the other skins started to work.

**Comment by abrookbanks** [comment]
This is not an issue in 6.0.0 (see https://github.com/cubecart/v6/commit/20db56c9a2b55dc341cfac4d33009e906fe95d91) and the old skins do not need that file to work.

**Comment by Noodleyman** [comment]
on a clean B7 install, grabbing the Kurouto skin from the marketplace (When filtered by V6 skins). the skin doesn't work

you get a white screen and exception.

Definately an issue or a disconnect somewhere as the V6 skin isn't working in V6 ;)

**Comment by Noodleyman** [comment]
once I put the file there from the foundation skin, it worked

**Comment by abrookbanks** [comment]
Yes B7 but not in final 6.0.0 released this morning.

**Comment by abrookbanks** [comment]
> once I put the file there from the foundation skin, it worked
Agreed that will fix it. It's not a good fix though and isn't necessary with 6.0.0 final.

**Comment by Noodleyman** [comment]
Ah, sorry I hadn't realised that 6.0 final was out today. DOH!

**Comment by abrookbanks** [comment]
Well its about time you "Followed" the news and announcements forums and Twitter/Facebook.  :stuck_out_tongue_closed_eyes:
