### ISSUE TITLE
Email content lost on save

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#3494]
The page reloads with no content in the code editor.

**Comment by bhsmither** [comment]
There is something about this not working correctly.
The content from `{$CONTENT.content_html|escape:'quotes'}` is appearing below the editor box.

**Comment by bhsmither** [comment]
Try this for near lines 131 and 217:
```
<input type="hidden" name="template[content_html]" id="template_content_html" class="textbox" value='{$TEMPLATE.content_html|escape:'quotes'}'>
```
The value of the `value` property is enclosed in single-quotes.

**Comment by bhsmither** [comment]
But now, when using apostrophes in the content **and saving**, extraneous content comes back below the editor window.

**Comment by bhsmither** [comment]
This is what I did on lines 139 and 225:
```
editor.getSession().on("change", function () { input.value = editor.getSession().getValue().replace(/'/g,"&#39;"); });
```
but this changes all apostrophes - including tags' single-quoted property values.

Ugh!

**Comment by abrookbanks** [comment]
We could go back to the base64 decode and encode method.

```
<input type="hidden" name="template[content_html]" id="template_content_html" class="textbox" value='{base64-encode($TEMPLATE.content_html)}'>
```

```
editor.getSession().on("change", function () { input.value = atob(editor.getSession().getValue()); });

```

**Comment by abrookbanks** [comment]
I got it working using this:
https://stackoverflow.com/questions/30106476/using-javascripts-atob-to-decode-base64-doesnt-properly-decode-utf-8-strings

**Comment by abrookbanks** [comment]
Content from input.value instead of feeding in raw value with last commit.

**Comment by abrookbanks** [comment]
I'm closing this because I'm confident we have a good solution. (Until you tell me otherwise - LOL)

I wanted to use pure the pure `atob` function but encountered encoding issues. The function `b64EncodeUnicode` seemed to work well.
