### ISSUE TITLE
Invoice Template to Have Language Code

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3497]
Feature Request:

Consider that the CubeCart_order_summary has a `lang` column to indicate the language of the customer that was in use when the order was made (if I recall). When fulfilling the order, an "Invoice Document" is generated.

There is no i18n of that document (like there is for any of the Site Documents).

**Comment by abrookbanks** [comment]
Closing until this reaches development.

**Comment by bhsmither** [comment]
My experiments:
```
orders.index.inc.php, near line 629, find:
            $smarty_data['list_orders'][] = $summary;
            unset($summary, $address);

ABOVE that, add:
$GLOBALS['language']->change($summary['lang'] ?? $GLOBALS['config']->get('config','default_language'));
$summary['language_strings_to_use'] = $GLOBALS['language']->getStrings();
```
This requires overwriting $LANG when compiling the Sales Invoice.
```
orders.print.php, near line 183, find:
  {if isset($ORDER_LIST)}
  {foreach from=$ORDER_LIST item=order}

AFTER that, add:
  {$LANG=$order.language_strings_to_use}
```
This seems to be the simplest, but least optimum as it sends to Smarty an entire language pack for each order.
