### ISSUE TITLE
Code Review: CSS Helpers

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3498]
The Foundation CSS ruleset has:
```
.row .row { margin: 0 0.9375em } // line 142
.row .row.collapse { margin: 0 } // line 151
```
Then there is the `cubecart.helpers.css` ruleset.

The question is, how important are these helper rules? Should the helper rules always overrule the Foundation rules?

The Foundation rules have greater specificity than the helper rules.

If the helper rules need to be more important, then they would need the `!important` designation.

**Comment by abrookbanks** [comment]
The helper rules shouldn't clash with foundation rules so this shouldn't make a difference. The idea is that these are some extra tools for quick layout jobs. I don't think adding the `!important` designation should be needed.

**Comment by abrookbanks** [comment]
I don't think any action needs to be taken here. They load last so should always be available.
