### ISSUE TITLE
Google Analytics Module

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3499]
The module has this check:

If:
Cookie Compliance Dialog is not enabled
OR
the site visitor has already accepted the use of cookies (visitor has a cookie that says cookies are allowed)
OR
Collect Stats Regardless is enabled
THEN
include the GA javascript in the web page.

Given the first test is enabled, and the third test not enabled. So those evaluate to false.

That leaves only the second test that must evaluate to true. If the Google site visit (to check the operational validity of the code) has not already accepted the use of cookies, the code will not be present. (As I understand the code.)

Question:
Is Google smart enough to realize this? Does Google just assume that the GA code will be present regardless of any country's laws regarding the required acknowledgement and acceptance of the use of cookies?

**Comment by abrookbanks** [comment]
This is being resolved with https://github.com/cubecart/v6/issues/3613
