### ISSUE TITLE
Unknown Array Keys

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3504]
In products.index.inc.php, near line 880, a distinct `$result[0]` is created when adding a new product . When first loading the Add New Product page, there is nothing in `$_POST` (at line 886).

Therefore, references to `$result[0]` further down the script might have unknown array keys (other than the four that were set). Of those found, these cause PHP to issue warnings:

Group pricing: lines 923,924
Manufacturers: line 1107

**Comment by abrookbanks** [comment]
Thanks.
