### ISSUE TITLE
Unknown Array Key

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3507]
In `User->isBot()`, the web server might not include 'HTTP_USER_AGENT' when passing to PHP the `$_SERVER` array. Particularly when the client app does not send one, such as when implementing CURL (see #3044). (Another instance was dealt with in the Session class: #3252.) PHP further complains about passing a _null_ to `strtolower()`.

Suggest:
```
$agent = strtolower($_SERVER['HTTP_USER_AGENT'] ?? 'curl');
```
The string 'curl' is in the `$_bot_sigs` array.

If a web request does not contain a User Agent string, assume it is from something that is of no interest.

**Comment by abrookbanks** [comment]
Thanks.
