### ISSUE TITLE
Code Review: Product Reviews Detail

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3514]
In `Catalogue->productAssign()`, lines that work with `catalogue['review_info']` (1679-1683), the true block assigns the language string to Smarty, while the false block sets the `$product['review_info']`.

Please consider moving the code in the false block out of the `if` structure and doing away with the false block.

There is no apparent reason why this detail should be missing if `$product_view` is _true_ - regardless whether or not it would be displayed somewhere.

**Comment by abrookbanks** [comment]
Good find thanks.
