### ISSUE TITLE
Code Check: P Nesting DIV

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3515]
In Foundation's element.product.review.score.php, there is a `<div>` block nested inside a `<p>` block.

A valid structure cannot have block-level elements inside `<p></p>`, which can only contain inline elements.

Viewing this code in a debugger will show that, automatically, the `<p>` block gets closed, then the `<div>` block is present, then a new (in this case empty) `<p></p>` block appears.

**Comment by bhsmither** [comment]
Suggest changing the ratings `<p>` tags to `<div>` tags.

The Review Info `<div>` block could be moved out of the ratings block, or kept nested - it doesn't matter.

Request that the star ratings `<div>` and the Review Info `<div>` both be given ID attributes.

**Comment by abrookbanks** [comment]
Thanks so much.

**Comment by bhsmither** [comment]
Please note there was a request that the star ratings `<div>` and the Review Info `<div>` both be given ID attributes.

**Comment by abrookbanks** [comment]
Whoops! Done now. Thanks. I'm pleased you QC a lot of these, much appreciated.
