### ISSUE TITLE
Code Review: Unsetting Variables

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3516]
In `Catalogue->productAssign()`, when finished calculating the average review score, the variables `$score` and `$count` are unset. These variables only exist in this function, and as best I know, they dissolve when exiting this function.

There is a hook later in this function that may want to use `$score` and `$count`.

Please consider keeping them available.

**Comment by abrookbanks** [comment]
Also 

```
$user = (array)$GLOBALS['user']->get();
```

is unused.

**Comment by abrookbanks** [comment]
VS code is really good at finding unused vars.
