### ISSUE TITLE
Passing Null to Type String

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3519]
In orders.index.inc.php, line 621, `$summary['ship_date']` might be _null_, but this is an illegal variable type for `str_replace()`.

Suggest, for this part:
```
str_replace('-', '', $summary['ship_date'] ?? 0)
```

**Comment by bhsmither** [comment]
Then, on line 623, `$summary['ship_tracking']` might be _null_, but this is an illegal variable type for `preg_replace()` found in `parseUrlToLink()`.

Suggest, for this part:
```
parseUrlToLink($summary['ship_tracking'] ?? '');
```
or, catch all occasions:
```
function parseUrlToLink($text = '', $target = '_blank')
```

**Comment by abrookbanks** [comment]
Thanks.
