### ISSUE TITLE
PHP Script Header in Script

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3521]
Bizarre!

In orders.index.inc.php, near line 661, there is:
```
$cleanup = '<?php unlink(__FILE__); ?>';
```
Normally, prepending `//` in front will comment out that line and PHP should ignore it.

But no! Doing this causes, in this particular instance, PHP to complain about an unclosed brace at line 568.

Doing this:
```
/* $cleanup = '<?php unlink(__FILE__); ?>'; */
```
works.

Just something to be aware of.

**Comment by abrookbanks** [comment]
That is weird! Thanks for sharing.
