### ISSUE TITLE
Stray Space

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3537]
In the admin template products.options.php, near line 36, there is a `&nbsp;`.

Unless that is necessary for some reason (it has been there since initial import), request that it be removed.

That column is set to 300px. When the description text is clicked on and the cell contents turn into a text edit field, that field has a class that is 300px wide. The `&nbsp;` thus wraps to a new line.

It's a trivial matter.

Additionally, to prevent wrapping (it is a personal choice), I added `style="white-space: nowrap;"` to the `<tr>`.

Additionally, in layout.css, near line 244, I made this change:
```
From:
.editable:hover::after {
    font-family: FontAwesome; content: " \f040";
}

To:
.editable::after {
    font-family: FontAwesome; content: " \f040"; visibility: hidden;
}
.editable:hover::after {
    font-family: FontAwesome; content: " \f040"; visibility: visible;
}
```
This prevents the width of the columns from expanding to accommodate the edit icon. The icon is now permanently present but hidden unless the cell is hovered.

Additionally, the Group Type column is set at 150px. When it turns into a selector, it expands to class 'textbox' (which is 300px).

An experiment will be performed to read the DOM 'clientwidth' for that cell/column and try to create a selector that is that width (which might be larger than 150px depending on the cell contents).

**Comment by abrookbanks** [comment]
Thanks. It's much nicer now.
