### ISSUE TITLE
Field 'skin' doesn't have a default value

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#3552]
File: [settings.index.inc.php] Line: [177] "UPDATE `CubeCart_logo` SET `status` = '0',`skin` = DEFAULT,`style` = DEFAULT WHERE CubeCart_logo.logo_id = '13';" - Field 'skin' doesn't have a default value

Relates to #3495

**Comment by abrookbanks** [comment]
Reverted changes.
f131f1ac3133674c9e22bf7aaad6d37ec975f8e2
2596e542cdcac2e696bb6b9ba62de294ff30b7ec

**Comment by bhsmither** [comment]
Interesting, as my database server categorizes this as a Warning.
```
10.4.12-MariaDB-1:10.4.12+maria~bionic-log
```
CubeCart's database class requests the errors from the previous statement, so I don't see these warnings. But using an external client, the client as a matter of course, gets Warnings (which incidentally includes any errors in the response). However, the row does get updated.

Still, it is still a concern.

**Comment by abrookbanks** [comment]
I'm leaving this one for now. It seems to open a can of worms. Pinning down all these notices and warnings is a huge amount of work and knocks stability. I'm not bothered about them unless there is an important bug off the back of it.
