### ISSUE TITLE
VAT issue in 6.5.4

### ISSUE THREAD

**Issue by desktop-solutions** [cubecart/v6#3557]
I recently upgraded six sites to 6.5.4. Those customers are reporting an issue with VAT doubling to 40%. 

Is there a fix for this?

**Comment by desktop-solutions** [comment]
Looking at the affected sites the vat calcs just don't make sense
![image](https://github.com/cubecart/v6/assets/10652121/95fbc872-b353-4325-aea1-742b3ef710c7)

**Comment by outrank-james** [comment]
This looks to still be an issue - Prices are entered in the backend exclusive of VAT

(£5.00 ex vat = £6.00 inc vat - which would make VAT £1.00 (for the product) plus the shipping vat of 0.74p - total vat £1.74)

![Screenshot 2024-05-20 at 12 09 28 pm](https://github.com/cubecart/v6/assets/47569353/e60a52b8-04b2-4cf8-bcf2-4f130158bf76)

**Comment by abrookbanks** [comment]
Are you on 6.5.5?

**Comment by outrank-james** [comment]
@abrookbanks - Yes updated last week

**Comment by outrank-james** [comment]
Ok I think I've found the issue - looks to be related to "shipping" side of things - removing VAT from Shipping fixes it.

**Comment by outrank-james** [comment]
Coming back to this - so when disabling VAT for shipping checkbox - the price of vat for the product is calculated correctly. 

The website is using "By Weight" shipping module - which has a price Inclusive of VAT - so it would need to remove the VAT from the shipping price
![Screenshot 2024-05-20 at 1 04 49 pm](https://github.com/cubecart/v6/assets/47569353/c065b70a-f333-4b4d-94fb-d83888520797)
![Screenshot 2024-05-20 at 1 05 12 pm](https://github.com/cubecart/v6/assets/47569353/be266239-e18e-4293-8904-91485b1619b1)

**Comment by abrookbanks** [comment]
Thanks for the info.

**Comment by abrookbanks** [comment]
Please find fix above. Sorry for any inconvenience caused.

**Comment by outrank-james** [comment]
> Please find fix above. Sorry for any inconvenience caused.

I've tested the code tweaks and can confirm that's resolved the issue.
