### ISSUE TITLE
Exif Is An Optional Extension

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3559]
With respect to #3478, the EXIF library is an optional extension.

Suggest that gd.class.php, line 103 be coded to test for the existence of `exif_read_data()`, giving an empty array to `$this->_gdImageExif` if the function does not exist.

Also pre-assign `private $_gdImageExif;` as an empty array.

Also suggest, during install/update, add checking for the Exif library being available and enabled.

**Comment by abrookbanks** [comment]
Thanks.
