### ISSUE TITLE
SQL Syntax Error

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3560]
In /setup/db/install/structure.sql, line 63, the column specification for `item_id` calls for `VARCHAR(255) UNSIGNED NULL`. Text-type data cannot be Unsigned. The database server will issue a error.

And, for me, the CREATE statement failed (at the database server level), and no table got created.

(The upgrade SQL statement for 6.5.4.sql has `VARCHAR(255) NULL DEFAULT NULL`.)

**Comment by bhsmither** [comment]
Also, when creating the CubeCart_inventory table, the column specification for `maximum_quantity` calls for `INT(10) NOT NULL DEFAULT '0'`.

However, in examples.sql, the record being inserted into CubeCart_inventory gives _NULL_ for `maximum_quantity`. The database server will issue an error.

And, for me, the INSERT statement failed (at the database server level), and no record got inserted.

**Compare** the upgrade SQL script 6.5.4.sql that alters the CubeCart_inventory column `maximum_quantity` that calls for `INT NULL DEFAULT '0'`.

**Comment by bhsmither** [comment]
Also, creating CubeCart_inventory, the column specification for `product_parse` calls for `tinyint(1) unsigned NOT NULL DEFAULT '1'`.

**Compare** that with the ALTER statement in /setup/db/upgrade/6.5.4.sql where the column specification for `product_parse` calls for `INT UNSIGNED NOT NULL DEFAULT '0';

This also applies to `cat_parse` in CubeCart_category.

**Comment by abrookbanks** [comment]
Thank you!
