### ISSUE TITLE
Missing Template Variable

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3561]
Very minor:

During install, when presenting the form to collect database details, the Smarty variable `$FORM` has not yet been assigned. This assignment happens only if the form needs to be displayed again (setup.install.php, near line 166). PHP issues a few error messages per instance of the missing $FORM array when executing the compiled skin script.

(Not verified) Maybe, near line 64, after `$step = 5;`, assign an empty array to the Smarty template variable 'FORM'.

**Comment by abrookbanks** [comment]
Also unnecessary  `rel=""` in the labels of the skin file.
