### ISSUE TITLE
Low Contrast

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3566]
With the edit to layout.css, line 668, from #3543, all tables with striped rows now have a higher specificity, thus overruling any lesser specificity having a distinct other class of style.

For example, `.row_warn/.row_error` at line 1296/1302, will no longer paint the row orange/red when showing warnings/errors in admin, Maintenance, Database tab, showing rows with contrary indexes (ex, CubeCart_404_log).

**Comment by abrookbanks** [comment]
Also a list layout bug.

<img width="1218" alt="Screenshot 2024-04-23 at 09 32 05" src="https://github.com/cubecart/v6/assets/4520803/5e89d1a5-f7b8-4f9b-be2b-b6ddb7531935">

**Comment by abrookbanks** [comment]
Thanks!
