### ISSUE TITLE
DB Table CREATE AUTO_INCREMENT=Num

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3579]
In structure.sql, a few tables have the table expression `AUTO_INCREMENT=#`.
CubeCart_currency
CubeCart_filemanager
CubeCart_geo_country
CubeCart_inventory
CubeCart_order_history
CubeCart_seo_urls
CubeCart_email_log

Maybe this matters not at all, but raises the question why this is there.

**Comment by bhsmither** [comment]
Also, in CubeCat_order_summary, the `title_d` column was missed when changing these `title` columns to `varchar(16)`.

**Comment by abrookbanks** [comment]
Thanks.
