### ISSUE TITLE
Show Prices Inc/Ex VAT (cubecart/v5.2.14#87)

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#358]
Please see: cubecart/v5.2.14#87

**Comment by Noodleyman** [comment]
I already have a free plugin to do this

**Comment by abrookbanks** [comment]
Great! Maybe you can add a link here for other.

**Comment by abrookbanks** [comment]
closed by accident

**Comment by Noodleyman** [comment]
quite simple, really only useful if you have a single tax rate. if you have complex tax rules it isn't so great. It uses hard coded tax rates in the hooks. if you use a rate other than 20% you need to update the math. I didn't go to town on it as it's a free one. :)

http://www.noodleman.co.uk/show-prices-with-vat.html

http://www.noodleman.co.uk/downloads/show_vat_prices/1.0.0-show_vat_prices.zip

if there is enough interest I might do a commercial version, although i won't if it will be added in a future V6 update :)

**Comment by havenswift-hosting** [comment]
>>I already have a free plugin to do this

That is great and I will take a look at it - is it in the marketplace yet ?

**Comment by Noodleyman** [comment]
module is available to do this here:
https://www.cubecart.com/extensions/plugins/show-prices-with-and-without-tax-/-vat

does this ticket still need to be open?
