### ISSUE TITLE
Foundation Mobile Site

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#359]
The quantity box on the product page on the mobile site is cut off and only half displays?

**Comment by abrookbanks** [comment]
Do you have a screenshot? If you do please just drag it into this comment text field and it will upload automatically. If not can you tell me which skin you are using?

**Comment by bondimedical3** [comment]
It's the Foundation skin. Just view a product of your own demo store on a mobile.

**Comment by bondimedical3** [comment]
By the way I have noticed this issue on category pages as well. Can you fix this?

**Comment by abrookbanks** [comment]
This was fixed yesterday too https://github.com/cubecart/v6/commit/f32af183eac99cddc624b71c260343d97ad702e4

**Comment by bondimedical3** [comment]
On the category page in the "Sort by" drop down menu, the downward arrow is very close (in fact touching) the last closing bracket. Is it possible to move this over slightly?

**Comment by bondimedical3** [comment]
![screenshot_2015-03-17-14-46-20](https://cloud.githubusercontent.com/assets/10808588/6681153/cfabe090-ccb5-11e4-8b1d-2ee8a3b76a77.png)
I have tested this on an iPhone 5 an the issue with the downward arrow is worse to the point where it is cutting off text. Please look at this "Sort by" box

**Comment by abrookbanks** [comment]
Fixed here: https://github.com/cubecart/v6/commit/07d98710e9e843d4e97ac4a9cf724547d3d0c485

**Comment by bondimedical3** [comment]
Great thanks. Can you also move the whole box over for small devices as there is plenty of room and it causes the word "by" to appear under the word "Sort"?

**Comment by abrookbanks** [comment]
Yes that's part of the code fix done this morning.

**Comment by abrookbanks** [comment]
![screen shot 2015-03-17 at 12 35 45](https://cloud.githubusercontent.com/assets/4520803/6687348/2d76eb70-cca2-11e4-8906-bcec7e81e40b.png)

**Comment by bondimedical3** [comment]
Great work.

**Comment by abrookbanks** [comment]
Thanks. Sorry if these have inconvenienced you. We should have 6.0.2 in Tuesday next week.
