### ISSUE TITLE
Style Anomaly

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3595]
In the admin, Downloads, Downloadable Filemanager, when hovering over the table - anywhere - the entire table acquires the `#filemanager div div:hover` style.

An experiment near line 678:
```
From
#filemanager div div:hover {
To:
#filemanager #fm-wrapper div:hover {
```
gives single-line hover styling. (I changed all relevant selectors to `#filemanager #fm-wrapper`.) However, the pale-blue colored lines are overruled with `!important`. So, that was removed.

Obviously, I don't know how the other selectors will now behave.

**Comment by abrookbanks** [comment]
Thanks.
