### ISSUE TITLE
What is max size of the stock logo space in v6? 

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#36]
It would be helpful to put this info on the Store Logos tab of Store Settings. And I'd like to know it now for experimenting.

**Comment by abrookbanks** [comment]
Being responsive there is no max size. :) All images are sized to 100% of the area they are placed into. This allows them to fit dynamically to the device they are displayed on. 

I would have thought that proportions are more important. I'd suggest creating an image with the right proportions to the grid element they fit into at the maximum size. 

For example in the stock skin this area is 250 x 122. Maybe that is the most optimised size. 

![screen shot 2015-01-09 at 15 26 21](https://cloud.githubusercontent.com/assets/4520803/5681873/1974c7c2-9814-11e4-8dac-239709ff37e7.png)

**Comment by Dirty-Butter** [comment]
250x122 is what I wanted, and I'm pretty sure others will, too. I put my current logo in, expecting the Search box to shrink so it would fit LOL - not thinking about having to edit main.php. I do plan to figure out how to change the size of sections, but not yet.
