### ISSUE TITLE
Obsolete Macro Keys

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3607]
Related to #3122, there are more macro arrays that still have `'{$DATA.id}'` as the key name for the incremental order id element. (Only the line near line 60 was changed.)

**Comment by abrookbanks** [comment]
Thanks.

**Comment by bhsmither** [comment]
The task was to remove `{$DATA.id}` and use in its place `{$DATA.custom_oid}`.

**Comment by abrookbanks** [comment]
Whoops.

**Comment by abrookbanks** [comment]
Thanks again.
