### ISSUE TITLE
Products Per Page option missing in 6.0.0

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#361]
Within store setting, the "Products Per Page" option has been removed. not sure if this is intentional or not so raising a ticket

**Comment by abrookbanks** [comment]
Removed intentionally. Please look at the "layout" section of the config.xml file in the foundation skin folder. It adds page split functionality. That part of the foundation template canbe added to your skin too if you want. This way the user can decide how many products to display per page.

**Comment by Noodleyman** [comment]
what if you don't want to use page split functionality? :)

**Comment by abrookbanks** [comment]
You don't need too it will just use the default value. Checkout lines 19 onwards here:
https://github.com/cubecart/v6/blob/master/skins/foundation/config.xml
