### ISSUE TITLE
Stock and dropdown menu - Could they be improved?

### ISSUE THREAD

**Issue by Caranxnet** [cubecart/v6#3612]
Good morning,

I believe there's a small flaw on the product page when it comes to the current stock and drop down menu.

We have the drop-down menu and then the "existencias" tab (in my Spanish version) below the images, while we could sort everything out with a single one. In other webs, side of the product on the drop-down menu there is the stock amount, is easy and fast to see, no need to scroll any further. This is an issue that many other stores don't have and yes, I think is a problem. I do receive many phone calls by people asking me if there's stock on this or that, I think this is a sign good enough to fix it.

The 0 stock that shows when no item is selected, why is there? 

![example stock 01](https://github.com/cubecart/v6/assets/116885861/0481d4fe-8bf2-4aba-a2b9-1d40335f7d5a)

Imagine I have 5 models of a reel, 4 are in stock and one isn't. To the distracted eye, that 0 stock means what he sees, and he leaves. Just put the stock level on the drop-down menu, and we're set, people will see it straight away and, even better, add a line where you can read either the stock level, the "not available at the moment" or even "open for pre-sales".

**Example: Shimano Vanford 2500HG - stock 2 - price 199€ Everything on the same line in the drop-down menu**

![Uploading example stock 02.png…]()

Another important thing is that if you look for Shimano Vanford 2500 in Google, many stores will take to the right place and the proper default position on the drop-down or whatever menu. Straight away, you can see the product availability and the matching price. Nothing hidden, no surprises. People don't want to be seduced and then let down, and if the basic small model of a reel price is 100€ and the biggest one is 200€, people need to know that straight away, again no surprises. I personally had complaints about it and I have to tell them to go down to the existencias tab to see the prices of each one. For SEO and sales purposes, having the drop-down menu adapting to the Google search would be a great asset.

Please take a look into that, I believe is very important to fix it to make our customer experience better

thanks, ciao

Nicola

**Comment by abrookbanks** [comment]
Looking at your store the area circled area is not standard functionality. You'd need to speak to your developer.

**Comment by havenswift-hosting** [comment]
Hi Al

Nicola hasnt described the issues especially well and while that tab does come from Alec's product options plugin (in an attempt to improve the functionality of product options) it isnt relevant here.

There are 4 issues he is currently having

1) When you first visit a product page, the stock level shows as 0 - this is due to there being no default selected option

2) The drop down list contains product options that are out of stock - some people would want this and others ldont, so this should be configurable.

3) The default product option selection doesnt seem to work - this would partly help with issue 1

4) There is no way to define a url to go to a specific product option and have those details displayed. If a store is advertising a specific product option for a product, then it would be great to be able to go to the product and have that specific option pre-selected.

**Comment by hairy-dog** [comment]
I'd add to the wishlist the possibility of having all the options in the dropdown list, but with the out of stock ones greyed out.
  
Having a url that is to a product with specified options pre-selected would be useful too!
  

  

  

  
  
  
  
  
>

**Comment by abrookbanks** [comment]
That's very helpful thanks @havenswift-hosting

**Comment by Caranxnet** [comment]
Adding a bit more to Ian's suggestions

2 The drop-down list contains product options that are out of stock - some people would want this and others ldont, so this should be configurable.

It would be great if on any line of the drop-down menu we have the real stock of the products variations and the individual price Below an example. 

![stock example](https://github.com/cubecart/v6/assets/116885861/25cf0836-4bb3-49ff-a1c3-62c346d2f71d)

Hope this helps

ciao

**Comment by abrookbanks** [comment]
From my research on current development store with **default** foundation skin.

1. See attached screenshots. I don't show stock level as 0 on the foundation skin. It shows min to max levels. 
2. This would be a nice feature. CubeCart checks stock when you add it to the basket. Maybe this can be bought forward.
3. This works on default foundation skin (see screenshot).
4. This would be lovely as a feature request!

<img width="747" alt="Screenshot 2024-07-03 at 09 12 22" src="https://github.com/cubecart/v6/assets/4520803/852bbd8c-ce84-473d-9327-f49c24b3e47e">
<img width="1143" alt="Screenshot 2024-07-03 at 09 26 06" src="https://github.com/cubecart/v6/assets/4520803/3c777e87-e8b7-4a6f-8609-09f82ba78710">
<img width="769" alt="Screenshot 2024-07-03 at 09 12 46" src="https://github.com/cubecart/v6/assets/4520803/8ed0c77b-7880-4b23-a6fa-ce58518a99ef">

**Comment by Caranxnet** [comment]
Good day, do we have any news about this issue?

Thanks, ciao
