### ISSUE TITLE
Google Consent Mode

### ISSUE THREAD

**Issue by Caranxnet** [cubecart/v6#3613]
Good morning,

Apparently, Google is requesting the Consent Mode for the ADS campaigns, for example in remarketing. I have attached the links to the issue, please take a look at them.

https://cmppartnerprogram.withgoogle.com/
https://support.google.com/tagmanager/answer/10718549?hl=en
https://developers.google.com/tag-platform/security/guides/consent?consentmode=advanced&hl=es

Do you think this could be added to the website?

Thanks, regards

Nicola

**Comment by russellhurst** [comment]
Hello,

I'm being told by my SEO people that Google Consent Mode v2 for cookie data needs to be actioned straight away as without it there is a risk that our Google Ads will be disabled.

If it cannot be done they suggest that I pay around £160 a year to use one of Google's approved partners! 

Regards,
Russell

**Comment by abrookbanks** [comment]
I'll do my best week commencing 29 July.

**Comment by abrookbanks** [comment]
It's a lot of work so I'll probably make it free to subscribers and cost to non.

**Comment by russellhurst** [comment]
That's great news - for subscribers, do you mean those with your technical support package?

**Comment by abrookbanks** [comment]
WIP:
<img width="1076" alt="Screenshot 2024-07-31 at 11 46 12" src="https://github.com/user-attachments/assets/421b3e54-e885-4150-8934-e7ea18b4b69b">
<img width="746" alt="Screenshot 2024-07-31 at 11 46 32" src="https://github.com/user-attachments/assets/88827513-75a6-455e-bbfc-a2834ff94b1d">

**Comment by abrookbanks** [comment]
Hi @Caranxnet & @russellhurst !

I have an extension for you. Please open a support ticket with FTP access / hosting login and I'll install it for you. 
https://www.cubecart.com/extensions/plugins/google-tag-manager-analytics-ads-with-consent

**Comment by Caranxnet** [comment]
Hi Al,

 

I’m a bit lost on my actual ftp, not sure it works. I can either add you as administrator or please contact Ian to get access

 

Thanks, ciao

 

Nicola

 

De: Al Brookbanks ***@***.***> 
Enviado el: viernes, 2 de agosto de 2024 10:16
Para: cubecart/v6 ***@***.***>
CC: Caranxnet ***@***.***>; Mention ***@***.***>
Asunto: Re: [cubecart/v6] Google Consent Mode (Issue #3613)

 

Hi @Caranxnet <https://github.com/Caranxnet>  & @russellhurst <https://github.com/russellhurst>  !

I have an extension for you. Please open a support ticket with FTP access / hosting login and I'll install it for you.
https://www.cubecart.com/extensions/plugins/google-tag-manager-analytics-ads-with-consent

**Comment by abrookbanks** [comment]
@Caranxnet I can't get FTP to work. I've tried FTP with passive/active connections but it's failing. 

> Could not accept a data connection: Operation timed out.

Your cPanel is logging in but then failing with a broken page then logs me out immediately. Maybe there is a problem or fault.

**Comment by abrookbanks** [comment]
I think you guys are on the same server. cPanel is broken. 
<img width="1177" alt="Screenshot 2024-08-02 at 09 43 56" src="https://github.com/user-attachments/assets/2a3cc4da-51d2-43f2-b2a5-15014473d214">

**Comment by Caranxnet** [comment]
See Al,

 

I don’t even know what you are talking about. Please contact Ian

 

Tx 

 

De: Al Brookbanks ***@***.***> 
Enviado el: viernes, 2 de agosto de 2024 10:40
Para: cubecart/v6 ***@***.***>
CC: Caranxnet ***@***.***>; Mention ***@***.***>
Asunto: Re: [cubecart/v6] Google Consent Mode (Issue #3613)

 

@Caranxnet <https://github.com/Caranxnet>  I can't get FTP to work. I've tried FTP with passive/active connections but it's failing.

Could not accept a data connection: Operation timed out.

Your cPanel is logging in but then failing with a broken page then logs me out immediately. Maybe there is a problem or fault.

**Comment by russellhurst** [comment]
Hello Al,

 

I can log in to cPanel just fine for my low level looking at things however FTP is not something I dare to delve into.

Your FTP login should have given you access to this area:  /home/ropesdir/public_html and if it helps the manual settings for your FTP account is:

FTP Username: ***@***.***
FTP server: ftp.ropesdirect.co.uk
FTP & explicit FTPS port:  21

 

Other than that I’m with Caranxnet in that you’ll need to ask Ian.

 

With kind regards,

Russell Hurst

 

G R Hurst & Co

Ludham Road, Catfield, Great Yarmouth, Norfolk NR29 5PY

*  +44 01692 670940
*  +44 01692 670970
*  ***@***.***> ***@***.***     

*  <http://www.grhurst.co.uk/> www.grhurst.co.uk 

P Please consider the environment before printing this mail
