### ISSUE TITLE
Dropdown list not populated

### ISSUE THREAD

**Issue by AirborneSapper** [cubecart/v6#3615]
In the unsettled orders tab the "then" dropdown list (at the bottom of any listed orders) is not populated

The same dropdown list available via the Customers/Orders section is populated

Please refer to the two images, which illustrate the difference outlined above

We are using CubeCart 6.5.5. Any assistance appreciated, thank you

![Blank Dropdown](https://github.com/cubecart/v6/assets/174530910/bb676d92-d5ff-4244-9a05-cf252b9d9975)
![Populated Dropdown](https://github.com/cubecart/v6/assets/174530910/83c3e957-804a-43fc-ae27-389fb8f1fd6c)

**Comment by abrookbanks** [comment]
Please see https://github.com/cubecart/v6/issues/3576
