### ISSUE TITLE
CSS question

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#362]
First - CONGRATS on v6.0.1!!
Second a question - I started working on cosmetic changes to foundation.css and cubecart.css on 6.0.0b1. Has anything changed in the foundation.css file that has changed since then? The minified versions make it impossible for me to tell if any actual changes have been made.

I try to unminify foundation so I could compare, but spacing was so different it didn't help much. But I did notice some places have em and some have rem, such as 1.25rem;
Should I try to fix that or leave it alone? Mine are all em.

**Comment by abrookbanks** [comment]
Hi Rosemary, the foundation.min.css file is intentionally hard to read as it is optimized. At the same time you are not supposed to make changes to it (but you can if you want). I would suggest overwriting styles instead. 

CubeCart uses the most basic Foundation integration "CSS Hacking". More info here:
http://foundation.zurb.com/docs/css.html

**Comment by abrookbanks** [comment]
.. Maybe the foundation.css file shouldn't be minified.

**Comment by abrookbanks** [comment]
I have removed minification.

**Comment by Dirty-Butter** [comment]
Thank you for unminifying. I had initially asked on the forum about how to deal with it, and Bsmither answered at that time that he didn't think it sped things up that much (that is if I understood him correctly). Anyway, I have my own copy of foundation, renamed to blue, so my changes will not be overwritten.

Overwriting styles sounds great in theory, but the process of changing even minor color changes in so very many lines of code makes it MUCH easier to test and then make the change in foundation. Each change I made has been commented, so I can find it again, and maybe even be of some help to someone else on the forum.

So I take it there have been no changes to the foundation.css file.
 That's good for me LOL.
PS - I think you meant Minification in ISSUE title

**Comment by abrookbanks** [comment]
No changed just easy to read now. :)

**Comment by bhsmither** [comment]
I have learned that `em` and `rem` are legitimate CCS3 units of measure.

An `em` is the width of the letter `M` in the font that is in play at that location. Thus, a font that is displaying 10pt will have a width of a `10pt M`. A font that is displaying 16pt will have a width of a `16pt M`.

A `rem` is slightly different in that this is the width of the letter `M` using the font in play at the top-most node of the document. Thus, an initial font declared for the `<body>` tag, for example, which would be for the overall width of the whole page, would be the width of that font size `M`.

**Comment by abrookbanks** [comment]
I came to the same conclusion. I assume the R in "rem" is for relative?

**Comment by abrookbanks** [comment]
I'm wrong it's "root"..

Great explanation here:
https://j.eremy.net/confused-about-rem-and-em/

**Comment by bhsmither** [comment]
Also, I have come to terms with foundation.css being minified. I now know that the file cubecart.default.css (and any other file with the sub-style name in it) will overrule foundation.css.

What is critical for a skin developer is to have an environment that will display the rule/properties in play for any targeted node in the HTML. Firefox with Firebug is very good for this.

I would imagine there are other browser add-ons, as well as full development environments (Dreamweaver, Rapid CSS, TopStyle, Visual Studio Express), that would be of benefit to the skin designer.

It's the learning curve that will kill you.

**Comment by abrookbanks** [comment]
That's how I work too. Many others don't and I want it to be as easy to work with as possible. If it helps lesser experienced devs this file shouldn't be minified in my opinion. Maybe a comment can be added to to top to recommend minification once done.

**Comment by bhsmither** [comment]
Also, Foundation comes from http://foundation.zurb.com, so I just downloaded the latest package (v5.5.1 at the time, whereas CubeCart has v5.4.7) and it has an expanded foundation.css file.

I edited the template main.php to call foundation.css instead of foundation.min.css.

Correct me if I am wrong, but there is no CubeCart specific CSS in foundation.min.css.

**Comment by abrookbanks** [comment]
Correct .. BUT the version of Foundation CSS you are using has !important declared after the "hide" css class. This will break some of the jQuery show/hide toggles!!

This was only recently added in foundation framework and has proven controversial!

**Comment by abrookbanks** [comment]
.. Maybe the hide classes in the HTML markup should be replaced with ```style="visible:none"``` instead.
