### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3624]
Because the PHP script is loading a template array with actual HTML code (instead of a flag), in admin script products.index.inc.php, near line 931,
```
details['selected'] = ($tax_id == $tax_type) ? 'selected="selected"' : '';
```
should have a leading, property-separating space.
```
details['selected'] = ($tax_id == $tax_type) ? ' selected="selected"' : '';
```

**Comment by abrookbanks** [comment]
Thanks.
