### ISSUE TITLE
Smarty Combine Creates Bad URLs

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3628]
(Checked with CC653, cache:files, debug:off.)

When the Smarty combine function groups CSS files into the combined single file, CSS rules that have a path to a separate resource acquires a path that starts at the server's root.

Examine the combined file and search for:
```
.chosen-container-single .chosen-single abbr
```
Then find the `background:url(x)` declaration. Note that `x` is a path that does **NOT** start with the **web server**'s docroot.

**Comment by abrookbanks** [comment]
Any real life examples?

**Comment by bhsmither** [comment]
I also verified this with the demo store.

This the mentioned URL found in 9b8b1.css.foundationdefault_20240806111746.css:
```
background:url(/home/ccmarket/subdomains/demo.cubecart.com/public_html/cc6/cache/chosen-sprite.png)
```

**Comment by abrookbanks** [comment]
Kool. Thanks.

**Comment by abrookbanks** [comment]
👀 
<img width="1198" alt="Screenshot 2024-08-29 at 14 34 14" src="https://github.com/user-attachments/assets/cfa9c169-eee7-4c70-aaf6-80772f04da9f">

**Comment by bhsmither** [comment]
This is what worked for me (so far):

From:
```
$min = CSSMin::minify(preg_replace('/url\\(((?>["\']?))(?!(\\/|http(s)?:|data:|#))(.*?)\\1\\)/', 'url("' . $dirname . '/$4")', $min));
```
To:
```
$min = CSSMin::minify(preg_replace('/url\\(((?>["\']?))(?!(\\/|http(s)?:|data:|#))(.*?)\\1\\)/', 'url("' . dirname(CC_ROOT_REL . $file['name']) . '/$4")', $min));
```

**Comment by abrookbanks** [comment]
Wow well done that works a treat! :)

**Comment by bhsmither** [comment]
In the screen shot above, what developer's application is that?

**Comment by abrookbanks** [comment]
It's just a screenshot from VSCode which is my daily editor.
