### ISSUE TITLE
Fail to Load an Image

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#363]
In my installations of beta7 and 600, there is something different about how the filetree plugin finds:
`<div style="display: none" id="val_skin_folder">{$SKIN_VARS.skin_folder}</div>`

In the FileTree Picker, in 600, I get image not found indicators. I get actual images in beta7.

The error console in Firefox indicates that:
`a("#val_skin_folder:).text()`
returns an empty string.

I haven't found the difference that would explain this as yet.

**Comment by bhsmither** [comment]
Can't reproduce this in CC601.

**Comment by abrookbanks** [comment]
Strange.. a site wide search on ```a("#val_skin_folder:).text``` returns no results for me.

I'd have thought it should be:

```("a#val_skin_folder:).text```

.. but thats guessing. 

If this can't be reproduces in 6.0.1 I'll close it for now. We can reopen if the issue does actually exists.
