### ISSUE TITLE
Empty include_path

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3634]
Question:

What would happen if the `php.ini` file has a bad 'include_path'? Such as something that would cause (autoloader.class.php) `self::$_paths` to be an array with one or more elements having a zero-length-string as a value?

The code at lines 90-101 will then be looking for a file that has a leading slash.

Also, all the tests in `autoload()` returns true. Then, if all tests happen to fail, why does the function still return true?

**Comment by abrookbanks** [comment]
Thank you.
