### ISSUE TITLE
Variable Used Twice for Different Purposes

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3636]
In catalogue.class.php, near line 1329, the variable `$prices` is assigned an array.

Later, near line 1405, `$prices` (which was not unset from its prior use) acquires more elements to its array.

(The problem doesn't show up because line 1422 is using the array keys, as `$quant`, in a comparison expression where the result of comparing incomparable values is undefined (as of PHP8) and should not be relied upon.)

**Comment by abrookbanks** [comment]
Thank you.
