### ISSUE TITLE
Missing Order Number to View Order

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3638]
When a non-logged-in customer uses the link found in the Order Confirmation email, when first presented with the Order Lookup form, the Order Number is taken from the web address given to the customer in their email, "/index.php?_a=vieworder&cart_order_id=xxxx".

If a non-logged-in customer just happens to want to visit "/index.php?_a=vieworder" _without providing the cart_order_id part_, that will generate an 'Undefined array key' error in /classes/cubecart.class.php, line 2789.

Suggest:

$cart_order_id = Order::validOrderId(trim($_GET['cart_order_id'] ?? '')) ? trim($_GET['cart_order_id'] ?? '') : '';

**Comment by abrookbanks** [comment]
Thank you.
