### ISSUE TITLE
Issue with new product images configuration

### ISSUE THREAD

**Issue by Caranxnet** [cubecart/v6#3641]
Hi Al,

I have noticed you changed the images uploads for the product pages, thanks. Thus, there is a problem, or either I didn’t grasp how it works. When you want to match a color code with a photo, it is now impossible. The + sign that you could usually find near the images and would allow you to do it has disappeared and now, if you mark the image upload button in the product options page, it shows the image but still there’s no way to add it to the color code. Hope the screenshot helps understand what I say

![image option page](https://github.com/user-attachments/assets/9af1266d-f416-4ef6-aca1-a181cc4f7535)

Thanks, ciao

Nicola

**Comment by abrookbanks** [comment]
Are you on the latest version? 
<img width="696" alt="Screenshot 2024-09-11 at 16 57 50" src="https://github.com/user-attachments/assets/55e07246-55bd-464f-a689-d93d0648c1e7">

**Comment by Caranxnet** [comment]
What is the latest version?

**Comment by abrookbanks** [comment]
6.5.6 click the overview tab on the dashboard as you login to the back end to find your version.
