### ISSUE TITLE
Go Daddy Installatron Cube Cart 6.5.4 - Backed up - failed admin after maintainance upgrade - uninstall restore - broke still

### ISSUE THREAD

**Issue by CoolGames** [cubecart/v6#3646]
Started with fresh install in existing empty public_html directory
On Go Daddy used Installatron to install Cube Cart and made PDF of setup forms for install.
Used it with red area saying it needed upgrade.

Used Go Daddy cPanel backup to save initial working site.

Read about and used maintenance to do upgrade and when admin URL accessed received 404 not found.

Compressed the whole directory and downloaded to view files from install after upgrade.
Uninstalled then restored the initial backup.

Tried deleting browser cookies for cube cart to no avail.
No longer able to do Cube Cart admin login in failed upgrade directory.
Even tried a new Installatron install in same directory and still no setup or login happening.

It appears upgrade has contaminated the browser in original directory.

Restoring backup to new directory works with save login / password even after repeated uninstall and restore.
A fix is to delete 24 hour data in browser and now the admin login works.
I will try to upgrade the restored backup to 6.5.6 from 6.5.4 and verify it caused the 404 error.

**_It appears the upgrade is allowing pressing continue while proceeding and it is not required._**

Also the continue disappears when complete leaving no action available and 404 then occurs when trying to do admin login.

![Upgrade - no action - Screenshot_2024-09-26_18-27-23](https://github.com/user-attachments/assets/3a1afb53-8f0c-4d3b-b216-37673ae268ba)

This is the error log from backup before upgrade edited to wrap lines.

[Edit - error_log.txt](https://github.com/user-attachments/files/17156326/Edit.-.error_log.txt)

**Comment by abrookbanks** [comment]
Please contact Installatron https://installatron.com/support?s=089eff7b18466ef1d9b524a07e0cd72e 

We do not maintain their packages or develop their automations.
