### ISSUE TITLE
Can't edit shipping rates

### ISSUE THREAD

**Issue by hairydogltd** [cubecart/v6#365]
Running 6.0.1, with All in One Shipping module installed, I don't seem to be able to edit any shipping rates. I can add them and delete them, but can't amend any existing ones.

**Comment by abrookbanks** [comment]
Thanks for this. I want to get CubeCart managed plugins into GitHub. I'll try to look at this tomorrow or Friday. I expect it's a JS issue..

**Comment by abrookbanks** [comment]
This is fixed with 1.0.4 here: https://www.cubecart.com/extensions/shipping-methods/-all-in-one-shipping
