### ISSUE TITLE
Product Stock Level is sometimes cached 

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#3651]
Looks to be a bug as the stock level should always be a real time quantity. 

catalogue.class.php calls getProductdata(), which uses a query to get product data. This comes from cache.

Later, there is an option to lookup the actual stock amount, but this does not get merged into the $product array.
`$stock_level = $this->getProductStock($product['product_id'], null, true);`

Thus, the stock level cans ometimes reflect the cached stock value which can result in selling out of stock items. two options to resolve.
1)
Find: 
`$result = $GLOBALS['db']->select('CubeCart_inventory', false, $where, $order, $per_page, $page);`

Replace with:
`$result = $GLOBALS['db']->select('CubeCart_inventory', false, $where, $order, $per_page, $page,false, false);`

however, this change doesn't use cache for any of the product data, thus perhaps a better solution is:
 ```
           // Get Stock Level
            $stock_level = $this->getProductStock($product['product_id'], null, true);
            $product['stock_level'] = $stock_level;
```

I was able to replicate this on a test store after tracking an issue with out of stock inventory being sold.

**Comment by abrookbanks** [comment]
Thank you.
