### ISSUE TITLE
Space for Images

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#366]
In Foundation, space for images is defined by the CSS which will cause some images to get bigger or smaller depending.

But the image keys specified in config.xml set them to fix dimensions.

As an example: View a category with sub-categories, and the subcategories have a mix of those having an image assigned and not having an image.

Those that show the noimage.png will scale because noimage.png is already at 270x270. But the 'subcategory' sized image is stuck at 70x70.

So, when the space for:
```
.small-block-grid-6 > li {
    list-style: outside none none;
    width: 16.6667%;
}
```
 gets bigger than 70x70, the image caption could have some of it inline with the image.

In cases such as this example, but not limited to this example, it becomes important to force a new line between the image and caption.

**Comment by abrookbanks** [comment]
Thanks for this Brian!

**Comment by bhsmither** [comment]
With respect to this, I must conclude that making the subcategory-sized rendered image bigger was only intended to solve the situation at this particular location -- in a round-about way.

I must also conclude that should a person really want a 70px image and edits config.xml to get it, it will also be incumbent on that person to make sure there is a `<br />` separating the image and it's caption.

**Comment by jasehead** [comment]
I've just edited my content.category.php to add the break between the image and the title - use <br> to adhere to the break tag used in the rest of the foundation skin (not <br />). My problem with the title is, if a subcat image was narrow and the subcat name began with small words, then the first small word would appear next to the image and the rest of the text would appear underneath the image. Not great - HAD to insert a <br> after the </a> around line 29 - it should already be in the code.

However, if you changed medium-block-grid-6 to a smaller number (3 or less), not using a <br> would allow the subcat name to display next to the image - which is an interesting look.

**Comment by jasehead** [comment]
+1 for adding a break tag between image and caption.

I've just edited my content.category.php to add the break between the image and the title - use a basic html break tag to adhere to the break tag used in the rest of the foundation skin (a break with no end slash).

My problem with the title is, if a subcat image was narrow and the subcat name began with small words, then the first small word would appear next to the image and the rest of the text would appear underneath the image. Not great - HAD to insert a break tag after the around line 29.
