### ISSUE TITLE
File: [catalogue.class.php] Line: [216] - Unknown column in 'where clause'

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#3662]
There seems to be a product option bug, related to the $assign_ids in catalogue.class.php. The SQl query generated to check CubeCart_option_assign expects all values to be INT, but options can be passed as other values such as strings. 

Can be replicated using a text option, add that item to basket, check error log.

```File: [catalogue.class.php] Line: [218] "SELECT `option_id`, `value_id` FROM `CubeCart_option_assign` WHERE `matrix_include` = 1 AND `assign_id` IN (fffffffffffffffffffffffffffffffffffffffff) ORDER BY `option_id`, `value_id` ASC " - Unknown column 'fffffffffffffffffffffffffffffffffffffffff' in 'where clause'```

In the example above, fffffffffffffffffffffffffffffffffffffffff was the value in the text option.

**Comment by abrookbanks** [comment]
Hmmm... the assign ID should only ever be numeric.

**Comment by abrookbanks** [comment]
Closing for now. It would be interesting to know why a text value is getting into there when it shouldn't. 

Happy to reopen if you feel there is an issue still.
