### ISSUE TITLE
Sorry but that voucher is category specific

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#3663]
On CubeCart 6.5.6, clean install using Foundation.

A promotional code associated with a category gets applied correctly at checkout and shows the discount amount in the totals, however the checkout also throws an error "Sorry but that voucher is category specific" even though the product is in the correct category.

![image](https://github.com/user-attachments/assets/6fc39483-4c38-4a57-9d29-d3a4fb62ff03)

**Comment by Sciewher242** [comment]
Thank you for sharing..
[JCPenneyKiosk](https://jcpenneykiosk.fyi)

**Comment by abrookbanks** [comment]
Thanks for your patience.

**Comment by Noodleyman** [comment]
weeeeeeee :)

Thanks Al

**Comment by abrookbanks** [comment]
Sorry it took so long.

**Comment by abrookbanks** [comment]
Trying to get ready for 6.5.7
