### ISSUE TITLE
Category page - Sort By contains no valid options

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#3665]
Using PHP 8.3, clean CubeCart install on version 6.5.6 where I added a new category and two products. There are no valid sorting options available.

![image](https://github.com/user-attachments/assets/02c91d29-6667-45f0-9cbd-22bb415bbcbd)

**Comment by bhsmither** [comment]
See:
https://forums.cubecart.com/topic/59328-sort-menu-blank/
https://github.com/cubecart/v6/issues/3626

**Comment by Washington776** [comment]
Thank you for sharing information..

**Comment by Noodleyman** [comment]
Thank you @bhsmither

**Comment by abrookbanks** [comment]
Thanks guys.
