### ISSUE TITLE
Category page - Sort By returns "This category doesn't exist." error

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#3666]
Using an instance where I am not seeing the error, #3665, also using CubeCart 6.5.6. Sort appears to be broken. 

Applying any sort order in a categoory view returns the following error:
![image](https://github.com/user-attachments/assets/bd251bbc-8d08-41b0-8e9c-20111ab4fed7)

I've been tracking this backwards, and I am still reivewing, however the crux of the specific issue above stems from cubecart.class.php, _category() method. 

```
        $search = false;
        if (isset($_POST['sort'])) {
            list($field, $order) = explode('|', $_POST['sort']);
            $_GET['sort'][$field] = $query['sort'][$field] =  $order;
            if (isset($_GET['search'])) {
                foreach ($_GET['search'] as $key => $value) {
                    $query['search'][$key] = $value;
                }
            }
        }
```
The sorting code above gets triggered, but does not set $search = true, but does set some data in $query.

Later, the following gets triggered because $query is not empty. but since $search is still false it does not append the cat_id to the redirect. Thus the error on the storefront about no category. 
  ```
      if (!empty($query)) {
            $query['_a'] = $_GET['_a'];
            if ($search || (isset($_GET['cat_id']) && $_GET['cat_id'] == 'sale')) {
                $query['cat_id'] = $_GET['cat_id'] ?? null;
            }

            ksort($query);
            httpredir('?'.http_build_query($query, '', '&'));
        }
```

I added $search = true; within the sorting code block and this solved the category not found issue, however the sort order is not actually applied. thus it's not fully resolved. I'm still poking around so will update as/when I solve it.

Sorting seems very broken in CubeCart 6.5.6.

**Comment by abrookbanks** [comment]
This is now fixed (in a different issue).
