### ISSUE TITLE
Improve searching

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#3673]
I know that Elastic Search is a massive improvement but many / most people are unable to use this.

what would be very useful and hopefully not much work would be to allow the store owner to select which fields are included in a store search so they could themselves limit it to product name only or use all current fields but exclude description.  A tab in settings which lists all fields that are currently used and then allows them via a tick box to include / exclude any would work great

**Comment by abrookbanks** [comment]
You'll need this in the global.inc.php file:

```$glob['search_columns'] = array('name', 'description', 'product_code');```

Delete as appropriate. Apples to RLIKE, LIKE and FULLTEXT
