### ISSUE TITLE
Drop-Down Category Menu issue with large number of subcategories

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#368]
See our Animals Category - https://dirtybutter.com/plushcatalog

Any suggestions??

**Comment by hairydogltd** [comment]
My suggestion is that the list is too long. You should NEVER offer a list of more than nine items. Break it up in some way.

**Comment by Dirty-Butter** [comment]
Thanks for the input, but that's not going to be easy. I had, however, thought about breaking our Animal Categories down into Alphabetical groups of Brands, like A-C, and use the Brands as Subcategories. We have over 3k items and will eventually have close to twice that at least. Stuffed Animals come in LOTS of brands! 
I am hoping for an alternative sidebar nav as a choice within Foundation or as a Marketplace plugin, perhaps based on the one already included for small screens, with different styling.  The sooner the better, please!

**Comment by abrookbanks** [comment]
I agree with hairydogltd but it's a bit idealistic. I was taught at uni that THE number for lists etc should never be more than seven. In reality breaking down "Animals" into groups isn't easy. 

Animals > 4 Legs
Animals > Fluffy
Animals > Hairless

.. I can't see a way to do it without it becoming cryptic.

I would suggest keeping it as is (breaking down if possible) but maybe making the dropdown items more condensed by tweaking the CSS.

**Comment by abrookbanks** [comment]
.. maybe a kind sole on the forums can help with this. My client side isn't terribly strong.
