### ISSUE TITLE
Fatal Error in Catalogue Class Determining Sale Price

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3682]
Not yet confirmed:

Please examine the situation where the store is in Global Sale mode, and then in the catalogue class, near line 1385, follow `$product_price`.

Assume `$product_price` is a string value.

The first operation deletes the 'zero to many' characters if it is not a digit or period. However, (not yet confirmed), PHP may still consider `$product_price` to be a string that will not be treated as numeric in the equation that follows.

A test to make sure `$product_price` is numeric seems to have fixed it:
```
$product_price = preg_replace('/[^0-9.]*/', '', $product_price);
settype($product_price, "float");
$product_data['sale_price'] = $product_price - ($product_price / 100) * $GLOBALS['config']->get('config', 'catalogue_sale_percentage');
```

**Comment by abrookbanks** [comment]
Thanks Brian!
