### ISSUE TITLE
6.0.0 - Invalid compiled template

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#369]
Randomly getting this error when trying to load a plugin page. I've got cache disabled.

[Exception] /var/www/html/6.0.0/includes/lib/smarty/sysplugins/smarty_internal_templatebase.php:176 - Invalid compiled template for 'admin/index.tpl'

No changes have been made to the template file and it's working fine in CC5.

any suggestions?

**Comment by abrookbanks** [comment]
The construct in the classes/modules/class.php file sets the default template to be index.tpl in the modules/*/*/admin folder. Does this exist and have the right name?

**Comment by Noodleyman** [comment]
Hi,

Looks like you made an adjustment, but to answer your earlier question, yes the file exists. If I renamed or removed the file the error changed to file not found rather than a compilation error.

**Comment by abrookbanks** [comment]
That's odd. No issues with file permissions?

**Comment by Noodleyman** [comment]
not that I can figure out. I changed the file / folder permissions to 777 just in case, but no change. Are there any other permissions I should check?

**Comment by abrookbanks** [comment]
Hmmmmm can I take a look first hand?

**Comment by Noodleyman** [comment]
Sure, lets sort something out later today or monday. it's on an internal server so need to poke a hole in a firewall or do a screen share.

**Comment by abrookbanks** [comment]
ok cool
