### ISSUE TITLE
ES Sync

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3692]
Maybe I am not understanding something about this Github...

When viewing the code for **v6.5-master** in the file catalogue.class.php, `searchCatalogue()`, there is not this statement:
```
$this->_search_mode = $search_mode;
```
but when viewing the Tag **v6.5.6**, that statement is present.

Isn't the "master" supposed to be the most recent with respect to the code base?

Only two of the three edits for https://github.com/cubecart/v6/commit/e7b9fde64bf28550043f19d34fd18f4785e3b2e7 are found in "master".

**Comment by abrookbanks** [comment]
The code should have been fully removed. Thank you.

**Comment by bhsmither** [comment]
Is there an issue number that reverts https://github.com/cubecart/v6/commit/e7b9fde64bf28550043f19d34fd18f4785e3b2e7 ?

**Comment by abrookbanks** [comment]
I'm not sure there is. The sort was disabled for when ES was being used until the functionality was built in which it now is.
