### ISSUE TITLE
AIOS Compatibility w/PHP7.2

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3693]
On the edge case where AIOS (only v1.0.26 examined) is running under PHP 7.2, the HEREDOC statement in shipping.class.php, lines 89-95, with the closing identifier `DebugOutput;` **not** beginning in the first column of the line, PHP will throw an Exception.

**Comment by abrookbanks** [comment]
Thank you. This is fixed in 1.0.27.
