### ISSUE TITLE
AIOS on PHP8.3: Unsupported Operand Types

### ISSUE THREAD

**Issue by Simon-3ft** [cubecart/v6#3694]
Not sure if this was specifically the upgrade to PHP8.3, or something else in the PHP config.

Receiving the following errors with AIOS
`[<strong>Exception</strong>] /##redacted-path##/modules/shipping/All_In_One_Shipping/shipping.class.php:41 - Unsupported operand types: float + string`

Latest (1.0.27, was also on 1.0.26)
`$this->_weight += (float)($this->_settings['packagingWeight'] > 0) ? $this->_settings['packagingWeight'] : 0;`
Change to
`$this->_weight += (float)($this->_settings['packagingWeight'] > 0) ? (float)$this->_settings['packagingWeight'] : 0;`

As far as I can tell, it wasn't a data content issue, but this resolves the problem either way

Apologies for not doing a fork and pull request, but I don't seem to be able to find the AIOS repo (it looks like old code in the CCv5 repo, but nothing in CCv6)

**Comment by abrookbanks** [comment]
Thank you. This is fixed in 1.0.28.
