### ISSUE TITLE
dashboard.index.inc.php:225 - implode(): Argument #2 ($array) must be of type ?array, string given

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#3695]

**Comment by bhsmither** [comment]
Line 225 doesn't have `implode()` in it.

Line 285 has the only instance of `implode()` in this file. And `array_keys()` (arg#2 of `implode()`) does return an array. (However, I do not yet know what `array_keys()` returns when its $array argument does not exist - but that is highly unlikely. Could it return a string?!?)
