### ISSUE TITLE
Enhancement Request: Customer Groups & Pricing

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#370]
I use customer groups quite a lot in some of my plugins, especially related to VAT. one of the areas that would be great to improve is the way prices are split by customer group. to clarify.

It is good to be able to set different prices per customer group, but I often see people update the retail price group and forget about the others. Their prices then become incorrect for specific customers. It would be really useful to have an option, perhaps a simple checkbox to use the retail price for all customer groups.

The other settings such as tax rules to be applied would still need to be applied per customer group.

Making it a configurable option will solve this issue for people who use tax groups in this way, whilst those who use it to discount prices for specific customers will not be effected.

**Comment by abrookbanks** [comment]
Thanks this is a good suggestion. Once 6.0 has settled we will look though these feature requests and make a shortlist.

**Comment by harolato** [comment]
Yeah, this would help a lot. At first I thought this was a bug until I found this feature request.

Currently I'm using customer groups as an indicator for customer accounts imported from previous online store. So to update products price I have to go through group price and type same thing as in retail price.

**Comment by Noodleyman** [comment]
Where on the roadmap is this feature request? 
I've been doing this for some of my customers via a custom plugin, but would be VERY handy to make it a core feature.

**Comment by havenswift-hosting** [comment]
Any chance of getting this feature request added - I also have many clients that use customer groups especially for wholesale or trade pricing and being able to use the bulk price change tool for customer groups would be so good !

**Comment by abrookbanks** [comment]
You can sponsor it if you like. ;)
