### ISSUE TITLE
RSS Feed and etc May Not Be That

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3700]
If sufficient time has elapsed, Cloudflare will intercept the cURL request for
```
https://forums.cubecart.com/forum/1-news-announcements.xml
(maybe?) www.cubecart.com/version-check/CC_VERSION
(maybe?) www.cubecart.com/extensions/json
```
and presents the challenge page, which is unexpected in the Request class, and throws a lot of errors when trying to work it as an XML document (see dashboard.index.inc.php, line 455, 112(?), and 105(?).

The recent extension check and version check gets a custom user-agent, and if this is the key to detouring around Cloudflare, then the RSS request should also get that user-agent.

* 'Maybe' is just a guess as I really do not see Cloudflare intercepting 'www' traffic - only 'forums' traffic. If that's the case, then the RSS request URL needs to be whitelisted.

**Comment by abrookbanks** [comment]
Thank you. I added an exception for the challenge for that path.

```
(http.host eq "forums.cubecart.com" and http.request.uri.path ne "/forum/1-news-announcements.xml")
```

**Comment by abrookbanks** [comment]
<img width="995" alt="Screenshot 2024-12-31 at 12 37 34" src="https://github.com/user-attachments/assets/2d093767-bbfe-42ef-8a53-4d2b3f30aa26" />
