### ISSUE TITLE
Adding a New Category with Image

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#377]
I have not experimented with this as yet.

In categories.index.inc.php, near line 86, starts the logic block for inserting a category in the database.

If the admin Add Category screens suggest that uploading/choosing an image is permitted on a new category, then the $image_id of that image (from $_POST['image'] for the array element that is enabled) is not getting into $_POST['cat']['cat_image'].

I think a routine similar to lines 45-56 should be in the block for inserting a category.
```
if (isset($_POST['image']) && is_array($_POST['image'])) {
  foreach ($_POST['image'] as $image_id => $enabled) {
    if ($enabled == 1) {
      $_POST['cat']['cat_image'] = (int)$image_id;
      break; // find and use first enabled image -- there can be only one!
    }
  }
}
```

**Comment by abrookbanks** [comment]
Excellent. Thank you.
