### ISSUE TITLE
Layout on Admin Manage Plugins page wrong

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#378]
The two tick boxes for "Backup if already exists" and "Abort if backup fails" dont line up with wording
![image](https://cloud.githubusercontent.com/assets/6114431/6653875/2a641a18-caa2-11e4-80f5-f3ad95d504fb.jpg)

**Comment by bhsmither** [comment]
Actually, this happens on a number of pages.

**Comment by abrookbanks** [comment]
Thanks. Can't believe we are neary on 400 bugs for v6. I'm exhausted.
