### ISSUE TITLE
PayPal Gateway - Bug

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#379]
If you are on the PayPal payment page and you press cancel to return to the merchant website it says processing on the merchant site then returns to the PayPal payment page again?

**Comment by abrookbanks** [comment]
Moved issue.

**Comment by bondimedical3** [comment]
When is this issue getting fixed?

**Comment by abrookbanks** [comment]
This is fixed in 1.0.1 released just now:
https://www.cubecart.com/extensions/payment-gateways/paypal-standard

To upgrade just use an install token.
