### ISSUE TITLE
What is the purpose of Create an Email Template?

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#38]
I THOUGHT this was going to allow the admin to create a new email to send from within Admin, based on some need in our store, even if I had to send it manually. Ideally I would have been able to use a Snippet to trigger this email in some way.

I like to email abandoned cart Pending customers, as I sometimes complete a sale by doing so.
I went through the process of adding a Template, expecting it to save and show in the list of emails as Admin: Abandoned Cart email. All my new template info DID save, but in order to save at the Email Templates tab, I had to uncheck the Default Emails and check my Abandoned Cart email.

When I looked back at the Email Content tab, my new Abandoned Cart email is not there, and there doesn't seem to be any mechanism for connecting it to Admin:, User:, etc.

I don't understand what purpose creating another Default email Template would be. Did I just misunderstand this new feature, or is it not working correctly?

**Comment by bhsmither** [comment]
An email "template" is the super-structure: logo, thankyou, etc, and then most important, the {$content}. You can create a new super-structure for customer communications emails, or a different base layout of a newsletter email. I guess sort of like the Fusion skin layout panel for the widgets and location of static things -- common to every page.

Each and every email "content", the specifics of what you want the email to say based on the situation, gets put in {$content} in the designated template.

CubeCart will not email just the "template". As yet, CubeCart does not let you add a new "content" item.

**Comment by abrookbanks** [comment]
I'm very keen to add the ability to add emails and add email trigger points in the code so you can choose which email sends at any one of the triggers.

**Comment by Dirty-Butter** [comment]
Thank you for the explanation, Brian. And Al, I certainly hope the capability for Admin to add emails/trigger points can be added to v6!!
