### ISSUE TITLE
Card Capture Gateway - Bug

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#380]
On the payment page there is a clickable link "What's this?" for the Card Security Code. This should display a popup but instead goes to a new page and displays a gif image in the corner? The cursor for the Card Security Code also begins in the center and should be on the left hand side?

**Comment by abrookbanks** [comment]
I moved this issue to a new repo for this module. See above.

**Comment by bondimedical3** [comment]
When is this issue being fixed?

**Comment by abrookbanks** [comment]
![screen shot 2015-03-26 at 12 00 25](https://cloud.githubusercontent.com/assets/4520803/6845758/b55845b6-d3af-11e4-9be3-d8be51085e51.png)

**Comment by abrookbanks** [comment]
BTW this fixes ALL payment gateways with 

> (What's this?)

It detects the old colorbox and replaced with Foundation Reveal.

**Comment by bondimedical3** [comment]
I have tried this and the popup is now working. However the second issue is not fixed. Can you make it so the the cursor for the Card Security Code begins on the left hand side instead of the centre of the box?

**Comment by abrookbanks** [comment]
I'm not sure what you mean by this?

**Comment by bondimedical3** [comment]
If you type a number in the Card Security Code box its in the middle?

**Comment by abrookbanks** [comment]
Ok I thought you meant cursor hand on (What's this?) text.

**Comment by abrookbanks** [comment]
Ok I raised a new issue about this #426 as the whole form needs to be rebuilt for small, medium & large screens.
