### ISSUE TITLE
Order Confirmation and Admin Email - Bug

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#381]
The date and time which appears in the order confirmation and administration email is a random number?

**Comment by abrookbanks** [comment]
Please can you add a screenshot? It would help massively.

**Comment by bondimedical3** [comment]
![screenshot_2015-03-15-20-02-59](https://cloud.githubusercontent.com/assets/10808588/6655318/b49e0a5c-cb4e-11e4-8ed3-015587e479ce.png)

**Comment by abrookbanks** [comment]
Thanks that's a great help.

**Comment by Dirty-Butter** [comment]
Bsmither fixed this in the forum:

https://forums.cubecart.com/topic/48727-date-issue-with-5213/?hl=%2Bemail+%2Bdate

**Comment by abrookbanks** [comment]
Thanks!
