### ISSUE TITLE
Call to Member on a Non-Object

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#382]
Very similar to #304, when PHP is shutting down and Debug is getting destroyed, Debug->display() wants to call the currentPage().

currentPage() wants to pass the page through SEO, which has already destructed. So when SEO starts up again, SEO->_getCategoryList() is called.

So, the Database class has already destructed and select() is called on a non-object.

I think this issue and #304 both originate with Debug->display() wanting to get currentPage() near line 331.

With CC6's insistence on forcing SEO-style page names, maybe currentPage(), at the end of the function, can test for the instantiation of the SEO class, and if not there, at least deliver the non-seo_path variant of the URL without crashing.

**Comment by bhsmither** [comment]
In currentPage(), I did this:
```
if( !isset($GLOBALS['seo']) || !is_object($GLOBALS['seo']) ) return $currentPage;
// $_GET['seo_path'] should never be set... but if it is this will fix it
```
In SEO->_checkModRewrite(), I did this:
```
$cache_id = 'seo_check';

if( !isset($GLOBALS['cache']) || !is_object($GLOBALS['cache']) || $GLOBALS['cache']->read($cache_id)) {
  return false;
} else {
```

**Comment by abrookbanks** [comment]
Well this make a lot of sense. From my tests it works fine too.

Thank you.
