### ISSUE TITLE
Programming Tweak

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#383]
In Catalogue->imagePath(), there is:
```
if($skins['styles'][$GLOBALS['gui']->getStyle()]['images']) { // do we use a seperate style folder for images?
```
`GUI->getStyle()` may return something that cannot be used as an index. (Think Crosshatch and Maurice.)

Suggest:
```
if(!empty($GLOBALS['gui']->getStyle()) && $skins['styles'][$GLOBALS['gui']->getStyle()]['images']) { // do we use a seperate style folder for images?
```

**Comment by bhsmither** [comment]
And GUI->getProductImage().

**Comment by bhsmither** [comment]
`!empty($GLOBALS['gui']->getStyle())` won't work in this location.
`$GLOBALS['gui']->getStyle() == ''`

**Comment by abrookbanks** [comment]
I'm not sure I follow. Your first comment makes sense. 

What about GUI->getProductImage()?

Also are you suggesting ```!empty($GLOBALS['gui']->getStyle())``` should be replaced with ```$GLOBALS['gui']->getStyle() == ''```? Those are opposite. So wouldn't you mean ```$GLOBALS['gui']->getStyle() != ''```

**Comment by bhsmither** [comment]
I do mean mean `$GLOBALS['gui']->getStyle() != ''`.

Thanks for catching that.

**Comment by abrookbanks** [comment]
Thanks. All seems to work fine still.

**Comment by abrookbanks** [comment]
I've had to revert to the old code as this introduced new bugs with missing image placeholders.

**Comment by Dirty-Butter** [comment]
The icons on Small view need larger tap targets, too. In fact the one that is on left canvas is not even ON the image.
