### ISSUE TITLE
Hide price until logged in - inconsistent display

### ISSUE THREAD

**Issue by nklisic** [cubecart/v6#384]
When the store mode 'Hide prices until logged in' is enabled, in latest product you have active Add To Chart button. On category product list you have wrong label on button (Out of stock),

'Hide prices until logged in' have affect on storefront when admin is logged.

Please see attached screenshot.
![cubecart_hp](https://cloud.githubusercontent.com/assets/10867308/6658449/e94b2454-cb69-11e4-80dc-b75a44515424.jpg)

**Comment by abrookbanks** [comment]
Thanks for this! It has been resolved now.
