### ISSUE TITLE
Inherited Tax

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#385]
If this is still a work in progress, then ignore.

In Tax->productTax(), there is:
`$this->_tax_table_applied[$tax_id] = 'inherited';`

In this if() block, `$tax_id` is unknown.

**Comment by abrookbanks** [comment]
This isn't work in progress. Sometimes an accumulative tax rate need to be set based on proportional amounts of tax in the basket. Say a £500 dress has 5% tax and a £100 TV has 20% tax. The shipping tax may need to inherit the average tax rate from the basket data. So it you be something like 15% in this case. Overhauling the tax in CC took a couple of weeks so I am in fear of making changes. I can however see that this is bad.

**Comment by abrookbanks** [comment]
I can't see any adverse affects from setting this to have the same value as tax_type. Thats better than setting an array key as null.
