### ISSUE TITLE
Database Backup - Allow 3rd Party

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#392]
The CubeCart backup only backs up CubeCart core tables, it does not backup any third party tables used by plugins.

for more critical plugins this could cause an issue in a disaster recovery scenario.

Tested using 6.0.1 but also noted the same in V5.

**Comment by abrookbanks** [comment]
If you were to use the naming convention;

CubeCart_{AUTHOR}_{MOD}_{TABLE_NAME} they will get backed up. Any table matching "CubeCart_" will get included in the backup.

**Comment by Noodleyman** [comment]
Ah,

I wasn't aware of that. 

I, and I assume many others avoided using the CubeCart naming convention to make it easier to segment the core tables from custom tables.

Would it be possible to to include tables that are not prefixed with CubeCart?

Or, even checking for a "plugin_" prefix for non standard tables?

**Comment by abrookbanks** [comment]
We need a CubeCart university and more documentation. :) I need 20 arms and 10 brains to do this!

**Comment by Noodleyman** [comment]
:+1: 

Would it be possible to to include tables that are not prefixed with CubeCart?

Or, even checking for a "plugin_" prefix for non standard tables?

**Comment by bhsmither** [comment]
I actually do not see where **CubeCart** is a necessary condition.

What I do see is the need for the database's prefix to be found.

**Comment by abrookbanks** [comment]
Ah it might be that then! It would be possible to add an option to backup all. Maybe this is a good idea...

**Comment by Noodleyman** [comment]
Thank you Al :)

**Comment by abrookbanks** [comment]
Done! :)
