### ISSUE TITLE
Files Backup - Skip Images source and cache folder

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#393]

**Comment by Dirty-Butter** [comment]
First backup I've been able to make from within CC in ages!! Thank you! But the wording needs to indicate that images are not included.

**Comment by abrookbanks** [comment]
Great I'm pleased it works.

**Comment by Dirty-Butter** [comment]
There's a checkbox on Database Backup with no explanation of what it is for.

**Comment by abrookbanks** [comment]
Mine looks like this...

![screen shot 2015-03-17 at 13 39 06](https://cloud.githubusercontent.com/assets/4520803/6688425/0a487c3c-ccab-11e4-9819-232d62625962.png)

Maybe download the latest build and upload the languages/* files.
