### ISSUE TITLE
Downloading Customized Foundation - question/suggestion

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#396]
I've discovered that it's much easier to specify the colors I want for the Storefront by downloading the Customized Foundation files from Zurb than trying to get consistent appropriate colors myself. I wish I had realized that a lot sooner.

Would this be a good suggestion for CC to make?

**Comment by abrookbanks** [comment]
Thats cool to hear. The same can be done with a find and replace. I'll bear this in mind however. Please note that the Foundation skin hasn't been tested with Foundation Framework 5. In the latter released of v4 they added !important to some of the CSS like the hide class. This may break some of the dynamic functionality in the skin for show/hide regions.

**Comment by Dirty-Butter** [comment]
I struggled with Find and Replace, based on Firebug, although I did that for most places. I expect my skill level is similar to many CC users, or maybe even a little higher.
So is it possible to get the customized version of Foundation v4?

**Comment by abrookbanks** [comment]
> So is it possible to get the customized version of Foundation v4?

Not that I have been able to find.

> Is it possible to edit the few places that v5 might break CC version?

I think its just a matter of removing ```!important``` from the ```.hide``` class.

**Comment by abrookbanks** [comment]
I have upgraded foundation Framework to 5 for 6.0.2 and there is no problem with you taking your own copy with changed colours. All will work fine.
