### ISSUE TITLE
Layout on Admin Order Summary Wrong

### ISSUE THREAD

**Issue by nklisic** [cubecart/v6#397]
Several cosmetic and one display error. (Product Options are not visible on the Item section)
![cc_admin_order_summary](https://cloud.githubusercontent.com/assets/10867308/6690529/5f5769c0-ccc1-11e4-84ff-f998c9718db9.jpg)

**Comment by abrookbanks** [comment]
Row height fixed in other bug report. I have right aligned the prices. I'm not able to reproduce missing product options. It may be that this order was placed prior to v5 or v6 in which case they may not show and there is no fix due to legacy data.

**Comment by abrookbanks** [comment]
![screen shot 2015-04-16 at 10 58 43](https://cloud.githubusercontent.com/assets/4520803/7178553/92dda8f4-e427-11e4-9707-3d1397acab68.png)

**Comment by abrookbanks** [comment]
![screen shot 2015-04-16 at 10 58 43](https://cloud.githubusercontent.com/assets/4520803/7178574/c891e230-e427-11e4-8572-b27a5eb7557a.png)
