### ISSUE TITLE
Foundation Mobile Dropdown menu not working correctly - Bug

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#399]
The drop down menu on the mobile site does not expand to show all categories. If you view your demo store on a mobile, Press "Shop by Category", then " TV & Home Cinema" it only shows the first two categories and "LED TV's" is missing?

**Comment by abrookbanks** [comment]
This seems to be a bug in Foundation Framework..

**Comment by bondimedical3** [comment]
Can you tell me which slider you will be using now?

**Comment by abrookbanks** [comment]
"Orbit" in foundation framework has been depreciated so we should change it anyway.. From what I have read http://bxslider.com/ is one of the best recommended to replace it.
