### ISSUE TITLE
Checkout fails to update

### ISSUE THREAD

**Issue by dcorc** [cubecart/v6#406]
If I go to "basket" (as a customer), I can update quantities, remove items, and prices change accordingly.

However, if I go to "checkout", I see the options to change quantity and update basket, but when I try to do so, the quantity changes but prices do not update.

this is v6.0.1

**Comment by abrookbanks** [comment]
I can't reproduce this. I managed to change the quantity all all stages of checkout.  Please note that there was a bug around this where by the mobile view quantity field was overwriting the medium-up view. Please make sure your template files are up to date.
