### ISSUE TITLE
Mobile Checkout Step 2 text misaligned 

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#409]
![screenshot_2015-03-21-18-18-38](https://cloud.githubusercontent.com/assets/10808588/6764166/01ef2a50-cff7-11e4-8d18-3b8876a58201.png)
The text does not align with the check boxes?

**Comment by abrookbanks** [comment]
Thanks, I made it less wordy.. 
![screen shot 2015-03-24 at 08 29 01](https://cloud.githubusercontent.com/assets/4520803/6797924/e64b89aa-d1ff-11e4-8e7f-8389529a16c4.png)
