### ISSUE TITLE
Zip/Country Shipping Estimate needed

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#410]
This needs to be on Basket, prior to customer having to give detailed information.
See https://forums.cubecart.com/topic/49255-shipping-estimate-mod-for-cc5-like-the-one-for-cc4-from-estelle/

As it is now, I have all s/h estimated info removed from Basket as a workaround for this missing function.

**Comment by abrookbanks** [comment]
Work in progres... 

![screen shot 2015-05-29 at 18 15 13](https://cloud.githubusercontent.com/assets/4520803/7888203/b1ba128e-062e-11e5-8d76-6d8741c9d9cf.png)

![screen shot 2015-05-29 at 18 16 03](https://cloud.githubusercontent.com/assets/4520803/7888218/cb4f5114-062e-11e5-8764-8b9f14cc9d0e.png)

**Comment by havenswift-hosting** [comment]
Looking good and great that this extremely important functionality is being added to the next version !

**Comment by abrookbanks** [comment]
Done. Works great on all devices.

**Comment by Dirty-Butter** [comment]
Is this supposed to show if customer clicks Secure Checkout on basket pop-up? Seems to me it would be better if it did, or is this something I'm still having trouble with?

**Comment by abrookbanks** [comment]
It's only been added for the basket.
