### ISSUE TITLE
HTML Tweak

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#411]
In admin, Edit Product, Categories and Options tabs, a few of the columns of checkboxes have the hover area skewed to the right of the image.

I see these lines of code at 347, 384, 394, 395, 397, for example:
```
<td align="center"><input type="checkbox" name="option_update[{$option.assign_id}][option_negative]" {if isset($option.option_negative) && $option.option_negative == 1}checked="checked"{/if} value="1"></td>
```
Suggest:
```
<td align="center"><input type="hidden" id="option_negative_{$option.assign_id}" class="toggle" name="option_update[{$option.assign_id}][option_negative]" value="{$option.option_negative}"></td>
```
Be observant of other classes on some of those lines.

This keeps these checkboxes coded, to what seems to the **prevalent** method, of how to use images instead of actual checkboxes.

**Comment by bhsmither** [comment]
And line 355, but I can't get it to check all the other checkboxes.

**Comment by bhsmither** [comment]
For this "Check All" checkbox, keeping the original code, but removing `position:absolute;` from the `input[type="checkbox"]` CSS rule, the hover area now sits on top of the box image.

Still not making the other boxes checked.

**Comment by Dirty-Butter** [comment]
The icons on Small view need larger tap targets, too. In fact the one that is on left canvas is not even ON the image.

**Comment by abrookbanks** [comment]
Removing the absolute position from the checkbox css fixed this for me.

**Comment by abrookbanks** [comment]
I'm going to close this as it seems to work really well. Tested in multiple areas of the admin CP. 

The screenshots show the actual checkbox with opacity removed...

Before Fix:
![screen shot 2015-03-24 at 09 30 06](https://cloud.githubusercontent.com/assets/4520803/6798793/80577ba0-d208-11e4-8825-79279d351952.png)

After Fix:
![screen shot 2015-03-24 at 09 30 23](https://cloud.githubusercontent.com/assets/4520803/6798794/877da5e4-d208-11e4-8238-30d12ad080c1.png)
