### ISSUE TITLE
Google Base Export requires update for tax

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#412]
Stumbled across an issue today where Google are threatening to suspend a CubeCart stores account because the feed is being sent using the base prices are not inclusive of TAX.

The store uses ex VAT prices, and then uses tax rules to calculate tax during checkout. 

If you are VAT registered google require the feed file prices to be inclusive of tax, but currently it only sends excluding tax.

**Comment by hairydogltd** [comment]
What I've done to get round this with other shops (on Zen Cart) is to set the prices to be VAT-inc, generate the feed file, then set the prices back. Not a pretty fix, but it does work.

**Comment by Noodleyman** [comment]
I've worked around this issue using one of my modules, however where does this sit on the roadmap? It's a critical issue for some businesses and a gap in standard functionality.

**Comment by havenswift-hosting** [comment]
We have solved this and a number of other issues with the Google Shopping export in a plugin (Google Merchant Centre Plugin) which is currently available on our own website (https://www.havenswift-hosting.co.uk/clients/cart.php?gid=19) and will be available on the extension store very shortly
