### ISSUE TITLE
billing and delivery postcodes?

### ISSUE THREAD

**Issue by dcorc** [cubecart/v6#416]
Curious to know why line 62 of https://github.com/cubecart/v6/blob/master/skins/foundation/templates/content.checkout.confirm.php

reads:

     {$DELIVERY.state}, {$BILLING.postcode}<br>

surely that should be 

 {$DELIVERY.state}, {$DELIVERY.postcode}<br>

but I'm wondering if there's a deeper problem of confusion of delivery and billing postcodes, as when I look at my sagepay login, it is reporting the billing address with the delivery postcode!?

**Comment by dcorc** [comment]
Curiouser and curiouser - when I look at the sagepay module's

gateway.class.php

."&CustomerEmail="		.$this->_ci($this->_basket['billing_address']['email'], CLEAN_INPUT_FILTER_TEXT)
			."&CustomerName="		.$this->_ci($this->_basket['billing_address']['first_name']." ".$this->_basket['billing_address']['last_name'], CLEAN_INPUT_FILTER_TEXT)
			."&BillingSurname="		.$this->_ci($this->_basket['billing_address']['last_name'], CLEAN_INPUT_FILTER_TEXT)
			."&BillingFirstnames="	.$this->_ci($this->_basket['billing_address']['first_name'], CLEAN_INPUT_FILTER_TEXT)
			."&BillingAddress1="	.$this->_ci($this->_basket['billing_address']['line1'], CLEAN_INPUT_FILTER_TEXT)
			."&BillingAddress2="	.$this->_ci($this->_basket['billing_address']['line2'], CLEAN_INPUT_FILTER_TEXT)
			."&BillingCity="		.$this->_ci($this->_basket['billing_address']['town'], CLEAN_INPUT_FILTER_TEXT)
			."&BillingCountry="		.$this->_ci($this->_basket['billing_address']['country_iso'], CLEAN_INPUT_FILTER_TEXT)
			."&BillingPostCode="	.$this->_ci($this->_basket['delivery_address']['postcode'], CLEAN_INPUT_FILTER_TEXT)


last line there of the excerpt, calls the delivery postcode instead of the billing postcode (presumably hence why it shows up thus, over at sagepay)

**Comment by abrookbanks** [comment]
Thanks the template has been patched and SagePay 1.0.2 just released here: https://www.cubecart.com/extensions/payment-gateways/sagepay-form

You can upgrade using an install token.
