### ISSUE TITLE
Bxslider

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#419]
The bxslider in 6.0.2 is not working even on your demo store?

**Comment by bhsmither** [comment]
I see the images, and the prev/next buttons work, but it's not doing it on it's own.

Maybe a config array should be in the page? But I would think if no config array, then the thing should be cycling through by default.

**Comment by bhsmither** [comment]
Found the inline config array.

**Comment by bhsmither** [comment]
I made the statement look like:
`$('.bxslider').bxSlider({auto:true,captions:true});`

**Comment by bhsmither** [comment]
In jquery.bxslider.css, line 196, is this correct?
`background: #666\9;`

**Comment by abrookbanks** [comment]
The demo store works fine (try a hard refresh). Please submit a support ticket if you require assistance.

**Comment by abrookbanks** [comment]
Just to add;

According to the documentation auto slide shoud debut to true with no setting. The hex color cod should be correct unless it's a bug in BXSlider itself.

**Comment by abrookbanks** [comment]
Slash should be ok:
http://stackoverflow.com/questions/12500732/what-does-mean-in-a-css-hex-color-notation

**Comment by bondimedical3** [comment]
Demo store is definitely not working. Have tried on mobile, tablet and notebook and as Brian has pointed out it does not start automatically.

**Comment by bondimedical3** [comment]
Have cleared cache in browser and makes no difference?

**Comment by abrookbanks** [comment]
You are right. It's off by default. 
http://bxslider.com/options#auto Brians code is correct.

**Comment by Tidal-Wave** [comment]
Just to add, The hex code thing was an old browser hack, and can safely be removed. It actually has already been removed upstream.

**Comment by abrookbanks** [comment]
Ah thanks for that. I'll get it upgraded to https://github.com/stevenwanderski/bxslider-4/releases/tag/v4.2.3
