### ISSUE TITLE
Feature Request - SMTP Test Function

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#427]
It would be really helpful to have a "test" button in the "Store Settings ==> Advanced" page of the admin area.

After being pressed it would validate the SMTP connection details are working. connect to the SMTP server, check for errors etc. It is sometimes difficult to know if SMTP is working correctly when mails do not arrive and would be ideal to be able to quickly perform a test to validate.

**Comment by abrookbanks** [comment]
Great idea. I like this.

**Comment by bhsmither** [comment]
Would you be willing to test?
https://forums.cubecart.com/topic/49495-testing-the-stores-email-settings/

**Comment by bhsmither** [comment]
I think I see how this could fail if the password contains characters otherwise illegal to be in the querystring.

Suggestions?

**Comment by bhsmither** [comment]
Why pass the password in the querystring? As an additional (although thin) layer of security.

If someone manages to submit this request outside the admin environment, the password would need to be known -- instead of defaulting on the Mailer class getting the password from Config.

There is also the test for CC_IN_ADMIN as another (thin) layer of security.

**Comment by Noodleyman** [comment]
Morning,

I got around to testing this today, I like it! does what it needs to do.

One thought though, might be better to take the current mail settings from the form fields rather than the config, this will allow it to be tested before saving.

**Comment by bhsmither** [comment]
Nothing wrong with saving first. Doing so won't break anything, or make anything else begin trying to email prematurely. If it doesn't work, you are still on the page to try something else.

**Comment by abrookbanks** [comment]
Love this! I'm going to polish it up for 6.0.3 thanks Brian.
