### ISSUE TITLE
New install of V6 - homepage document says Welcome to CubeCart 5

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#428]
As above

**Comment by abrookbanks** [comment]
Wow what a cracker. :P

**Comment by abrookbanks** [comment]
Hmm latest build has:

```<string name="default_doc_title_welcome" introduced="5.0.0"><![CDATA[Welcome to CubeCart]]></string>```

Maybe this is an installation bug?

**Comment by havenswift-hosting** [comment]
Installation of 6.0.2 via installatron done 10 minutes ago testing you know what !

**Comment by abrookbanks** [comment]
This is definitely an Installatron issue.
