### ISSUE TITLE
2700 item import broken into way too many 3 and 4 item imports

### ISSUE THREAD

**Issue by davshirley** [cubecart/v6#429]
Makes it impossible to to remove the previous import since you'd have to click through 500 or so checkboxes.  What could be happening?

In the remove previous import tab I see:

4 Imported Products	Today, 22:58
	2 Imported Products	Today, 22:58
	4 Imported Products	Today, 22:58
	2 Imported Products	Today, 22:58
	4 Imported Products	Today, 22:58
	2 Imported Products	Today, 22:58
	4 Imported Products	Today, 22:58
	2 Imported Products	Today, 22:58
	2 Imported Products	Today, 22:58
	2 Imported Products	Today, 22:58
	2 Imported Products	Today, 22:58
	2 Imported Products	Today, 22:58
	4 Imported Products	Today, 22:58
	4 Imported Products	Today, 22:58
	2 Imported Products	Today, 22:58
	2 Imported Products	Today, 22:58
	2 Imported Products	Today, 22:58
	4 Imported Products	Today, 22:58
	4 Imported Products	Today, 22:58
	2 Imported Products	Today, 22:58
	2 Imported Products	Today, 22:58
	4 Imported Products	Today, 22:58
	4 Imported Products	Today, 22:58...... etc.

**Comment by davshirley** [comment]
Oh should have mentioned that is on version 6.02...  Sorry.

**Comment by abrookbanks** [comment]
Thanks for this. We will get it fixed up early next week.

**Comment by abrookbanks** [comment]
Thank you. I have added a fix here. Only imports after the above fix is applied will be resolved.
