### ISSUE TITLE
Phone number - Bug

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#430]
There is a bug in CubeCart which has been there since I have been using CubeCart 4 and is still there in CubeCart 6. If someone make an international order and enters there phone number with a + sign in the front it gets saved as a random number. Many customers use this format eg +45809567432, a phone number from Denmark and if you try to save it or change the order from pending to processing then it changes to a random number. Can you fix this so it accepts the + sign in the front?

**Comment by abrookbanks** [comment]
I can't reproduce this. Screenshot attached. Maybe you can submit a support ticket.
![screen shot 2015-03-30 at 11 49 28](https://cloud.githubusercontent.com/assets/4520803/6894978/ed6709bc-d6d2-11e4-9231-4f980249cf61.png)

**Comment by bondimedical3** [comment]
If you change the order to processing then the phone number will change.

**Comment by abrookbanks** [comment]
Sorry I'm with you now. I can't read! Thanks for this its fixed now for 6.0.3.
