### ISSUE TITLE
Image Cache

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#436]
not a massive issue as I am sure most people will have the cache on, BUT if you disable the CubeCart cache, images are still trying to be served from the cache directory.

If you clear the cache and have cache disabled you have no images. In this scenario it should be using the source image scaled to the appropriate size rather than break the image link.

**Comment by abrookbanks** [comment]
I think really image cache is a misleading name. CubeCart needs other sizes of the master image. It just can't resize them on every page load or the server will probably explode. The images/cache folder would probably be better named image/variants or something. I don't think any changes can be made here.

**Comment by Noodleyman** [comment]
I agree, but thought it would be worth mentioning. 

With cache disabled, images should still work in some form. I would suggest just loading the source file and resizing on the fly. Not a great solution I know, but at least the images would work if somebody opted to have the cache disabled for whatever reason.

**Comment by abrookbanks** [comment]
I don't agree I'm afraid. It just sounds like unnecessary development which will introduce bugs into skins that don't have all image dimensions set. Imagine 600px side thumbnails in category product list. I would have said that if any change is to be made it's terminology based.
