### ISSUE TITLE
Option adds rather than subtracts discount on product page

### ISSUE THREAD

**Issue by richguycc** [cubecart/v6#437]
The Foundation skin recalculates the price of a product when an option is applied, which is a nice touch. However it adds a discount rather than subtracting it on the product page, although the discount is correctly applied in the basket:

The product page on arrival
![screen shot 2015-03-31 at 12 20 52](https://cloud.githubusercontent.com/assets/11737150/6919024/3fe92d9a-d7ab-11e4-90e6-b4841219d672.png)

The price rises by £2 rather than falling
![screen shot 2015-03-31 at 12 21 30](https://cloud.githubusercontent.com/assets/11737150/6919029/520e0914-d7ab-11e4-8b2b-2baa78528602.png)

But everything is fine in the basket
![screen shot 2015-03-31 at 12 22 21](https://cloud.githubusercontent.com/assets/11737150/6919041/749e844a-d7ab-11e4-8490-a525dc7b822a.png)

**Comment by abrookbanks** [comment]
Thanks for this. Please find fix above. Screenshots below of results..

![screen shot 2015-03-31 at 15 23 38](https://cloud.githubusercontent.com/assets/4520803/6921022/03552a46-d7ba-11e4-8cb6-2a311a5c440d.png)
![screen shot 2015-03-31 at 15 23 46](https://cloud.githubusercontent.com/assets/4520803/6921023/057c9174-d7ba-11e4-9374-ec71ab9492f8.png)
![screen shot 2015-03-31 at 15 23 53](https://cloud.githubusercontent.com/assets/4520803/6921026/085476dc-d7ba-11e4-9fda-cdfac47ade4f.png)
