### ISSUE TITLE
upgrade from v5 to 6 , reviews preventing the page to load

### ISSUE THREAD

**Issue by rbckits** [cubecart/v6#438]
upgrade from 5 to 6 went ok , but some pages were not loading getting a page not found and a 503 error, , it did take some time to find out what the problem was, deleting the review on the page was the solution , disabeling the review option did not help , other skin did not help , deleting the review was the only bad option to get the pages running

**Comment by abrookbanks** [comment]
Can you tell me how I can reproduce this or provide the exact PHP error message? I have nothing to work with here yet.

**Comment by rbckits** [comment]
simple just dial in a review , and the page can not load any more , 
should  i make a page to see it ? i have disabled reviews now on my page 
, exact maessage is that the page is not there , sorry i do not know the 
exact error , something a 404

have made it working 
http://www.rbckits.com/shop/wave-waterplane-short-kit.html tere is a 
review on this page

it says 503 service unavalble


  Service Unavailable

The server is temporarily unable to service your request due to 
maintenance downtime or capacity problems. Please try again later.

Additionally, a 404 Not Found error was encountered while trying to use 
an ErrorDocument to handle the request.

nee more , i leave the page for now today and remove it after your 
answer ok ?

Thanks

Rob


Al Brookbanks schreef op 1-4-2015 om 11:07:
>
> Can you tell me how I can reproduce this or provide the exact PHP 
> error message? I have nothing to work with here yet.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cubecart/v6/issues/438#issuecomment-88405279>.
>

-- 
**************************
R.Bulk computerfreeswerk
Rontgenweg 16G
2408AB Alphen aan den Rijn
T 0031(0)172533954
F 0031(0)842290410
M 0031(0)654318182
www.rbckits.com
info@rbckits.com
***************************

**Comment by abrookbanks** [comment]
Hi Rob, our demo store is fine:
https://demo.cubecart.com/cc6/tv-home-cinema/3d-tvs/sony-kdl-32hx753-3d-tv.html

**Comment by abrookbanks** [comment]
Maybe show that error screen to your web hosting company and ask them to help you find the full error message.

**Comment by rbckits** [comment]
will do do not understand why it is not working with them

let you know

grts

Rob

Al Brookbanks schreef op 1-4-2015 om 13:54:
>
> Maybe show that error screen to your web hosting company and ask them 
> to help you find the full error message.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cubecart/v6/issues/438#issuecomment-88449402>.
>

-- 
**************************
R.Bulk computerfreeswerk
Rontgenweg 16G
2408AB Alphen aan den Rijn
T 0031(0)172533954
F 0031(0)842290410
M 0031(0)654318182
www.rbckits.com
info@rbckits.com
***************************

**Comment by abrookbanks** [comment]
Have you tried adding a review to our demo store? There may be a server issue blocking it or something else. The actual error message is key here. 503 error just means there has been an error it doesn't tell us what it is.

**Comment by rbckits** [comment]
just did , do not know how to approve it , btw my recaptcha is also not 
working , just have a blank window where the circle should be

grts

Rob

Al Brookbanks schreef op 1-4-2015 om 15:32:
>
> Have you tried adding a review to our demo store? There may be a 
> server issue blocking it or something else. The actual error message 
> is key here. 503 error just means there has been an error it doesn't 
> tell us what it is.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cubecart/v6/issues/438#issuecomment-88481268>.
>

-- 
**************************
R.Bulk computerfreeswerk
Rontgenweg 16G
2408AB Alphen aan den Rijn
T 0031(0)172533954
F 0031(0)842290410
M 0031(0)654318182
www.rbckits.com
info@rbckits.com
***************************

**Comment by rbckits** [comment]
well this works at your side..

i have tried recaptcha differnet ways but at the end i have to dissable 
it as customers can not buy they can not pass the screen as the 
recaptcha is not working , i am a liitle short in tim eto try more with 
recaptch , it doe snot work here..

grts

Rob



Al Brookbanks schreef op 1-4-2015 om 15:32:
>
> Have you tried adding a review to our demo store? There may be a 
> server issue blocking it or something else. The actual error message 
> is key here. 503 error just means there has been an error it doesn't 
> tell us what it is.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cubecart/v6/issues/438#issuecomment-88481268>.
>

-- 
**************************
R.Bulk computerfreeswerk
Rontgenweg 16G
2408AB Alphen aan den Rijn
T 0031(0)172533954
F 0031(0)842290410
M 0031(0)654318182
www.rbckits.com
info@rbckits.com
***************************

**Comment by abrookbanks** [comment]
Why don't you rename the skins/foundation folder to skins/foundation-01APR15 then upload the default files. See if it works then.

**Comment by rbckits** [comment]
ok will give that a try , let you know

grts

Rob

Al Brookbanks schreef op 1-4-2015 om 16:02:
>
> Why don't you rename the skins/foundation folder to 
> skins/foundation-01APR15 then upload the default files. See if it 
> works then.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cubecart/v6/issues/438#issuecomment-88493147>.
>

-- 
**************************
R.Bulk computerfreeswerk
Rontgenweg 16G
2408AB Alphen aan den Rijn
T 0031(0)172533954
F 0031(0)842290410
M 0031(0)654318182
www.rbckits.com
info@rbckits.com
***************************

**Comment by rbckits** [comment]
did not work also, any options ?

grts

Rob


Al Brookbanks schreef op 1-4-2015 om 16:02:
>
> Why don't you rename the skins/foundation folder to 
> skins/foundation-01APR15 then upload the default files. See if it 
> works then.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cubecart/v6/issues/438#issuecomment-88493147>.
>



---
Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
http://www.avast.com

**Comment by abrookbanks** [comment]
There is nothing I can do without knowing what the PHP error or server error message is. If you want to open a technical support ticket we can look deeper into this.

**Comment by rbckits** [comment]
ok fine tell me the way to go and we do so

grt

Rob

Al Brookbanks schreef op 2-4-2015 om 09:34:
>
> There is nothing I can do without knowing what the PHP error or server 
> error message is. If you want to open a technical support ticket we 
> can look deeper into this.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cubecart/v6/issues/438#issuecomment-88794339>.
>

-- 
**************************
R.Bulk computerfreeswerk
Rontgenweg 16G
2408AB Alphen aan den Rijn
T 0031(0)172533954
F 0031(0)842290410
M 0031(0)654318182
www.rbckits.com
info@rbckits.com
***************************

**Comment by rbckits** [comment]
Hello Al

problem solved.. with the provider.. as cc search for a avatar outside 
the shop .. gravata, that could not be found ,, th eprovider came to the 
idea to look for the ip settings.. it was ip6 , how and why , it was not 
ment anyway , so returnd to ip4 setting and it works again, recaptch 
works also, only new recapcha does not work

grts
Rob

Al Brookbanks schreef op 2-4-2015 om 09:34:
>
> Closed #438 <https://github.com/cubecart/v6/issues/438>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cubecart/v6/issues/438#event-271440614>.
>

-- 
**************************
R.Bulk computerfreeswerk
Rontgenweg 16G
2408AB Alphen aan den Rijn
T 0031(0)172533954
F 0031(0)842290410
M 0031(0)654318182
www.rbckits.com
info@rbckits.com
***************************

**Comment by abrookbanks** [comment]
great!!
