### ISSUE TITLE
No Image Available Shown Full Size

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#439]
"No Image Available" image (NIA) occupies a space equivalent to its dimensions in the checkout page of Foundation.

In content.checkout.medium-up.php, the width of the second column is set at "120", but image variants of 50px are put here, and the NIA expands that column to 270px.

**Comment by bhsmither** [comment]
![checkout](https://cloud.githubusercontent.com/assets/4073092/6930384/06310432-d7c0-11e4-882b-470761ff24a7.jpg)

**Comment by abrookbanks** [comment]
Hmm I remember this issue in the past. Mine does this:

![screen shot 2015-04-01 at 10 05 00](https://cloud.githubusercontent.com/assets/4520803/6937844/9f739be6-d856-11e4-8ec5-f244e9ac0242.png)
 Line 73 of products.index.php should read:

```<a href="{$product.image_path_large}" class="colorbox" title="{$product.name}" target="_blank"><img src="{$product.image_path_tiny}" style="max-width: 30px; max-height: 30px" alt="{$product.name}"></a>```

**Comment by bhsmither** [comment]
Your image is of the admin screen.

I am referring to the storefront View Basket screen during checkout.

**Comment by abrookbanks** [comment]
So it is... how the heck did I miss that.
