### ISSUE TITLE
Admin menu not lined up

### ISSUE THREAD

**Issue by webspinning** [cubecart/v6#442]
Hi one of my customers has just upgraded to the latest cubecart version and the admin screens are not presenting correctly - looks like an issue with the left hand menu bar - assume you are aware and investigating?

**Comment by abrookbanks** [comment]
Can you do a hard refresh? 

Windows: Ctrl + F5
Mac: Cmd + r

**Comment by abrookbanks** [comment]
This is either caused by a browser cache or mix of old and new files.

**Comment by webspinning** [comment]
perfect, thank you for getting back so quickly.
