### ISSUE TITLE
Product Reviews - Only submit if logged in

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#443]
As you may be aware the product reviews feature in CubeCart allows spammers to very easily submit hundreds of fake reviews just for the sake of getting a link or citation to their website in an attempt to boost their rankings. Currently you are using Recaptcha to prevent this but it is still easy for black hatters to get around this with powerful software like Xrumer and it is only a matter of time before they figure out how to get past the new Recaptcha where you click the box in CubeCart 6. What I would like to request (and I got this from Magento and it works very well) is to add a feature in the Admin where customers need to be logged in before they can submit a review. Would you be able to add something like this?

**Comment by abrookbanks** [comment]
Sounds great. Thanks for this.

**Comment by havenswift-hosting** [comment]
You could enhance this by having selectable settings for

1) Require customer to be logged in
2) Require that there is an order by that customer for the product they are trying to review

Most store owners would want to select both of these but there would be some that wouldnt so it cannot be forced
