### ISSUE TITLE
CubeCart V6 Bug Creating order manually, wrong VAT price

### ISSUE THREAD

**Issue by NorbertHUS** [cubecart/v6#446]
At Admin-Order, then Inventory.
Once you’ve selected the product it shows the price including VAT where it should give the price excl. VAT. We manually have to recalculate the right price excluding VAT.
Please solve.

**Comment by abrookbanks** [comment]
We will tackle this as part of #355

**Comment by NorbertHUS** [comment]
Hi Al,

 

After looking at both bugs, I see no solution has actually been provided yet.

When to expect?

 

 

 

Kind regards,

 

Logo Ultimate Sports Blauw klein

 

Norbert Hesse

 

Gronausestraat 185

7533 BZ

Enschede

0031-(0)53-436 35 00

www.ultimatesports.nl <http://www.ultimatesports.nl/> 

 

The General Terms of Delivery, as they have been lodged with the Chamber of Commerce in Enschede under no. 08110010, shall apply to all our offers and agreements.


DISCLAIMER

This e-mail message is intended exclusively for the addressee(s)and may contain confidential information.

If this e-mail message is not intended for you, we kindly but firmly request you return the e-mail message forthwith and remove all related information from your computer(s).

No rights may be derived from the contents of this message and any attached documents.

 

Van: Al Brookbanks [mailto:notifications@github.com] 
Verzonden: dinsdag 21 april 2015 14:24
Aan: cubecart/v6
CC: NorbertHUS
Onderwerp: Re: [v6] CubeCart V6 Bug Creating order manually, wrong VAT price (#446)

 

We will tackle this as part of #355 <https://github.com/cubecart/v6/issues/355> 

—
Reply to this email directly or view it on GitHub <https://github.com/cubecart/v6/issues/446#issuecomment-94775122> .Afbeelding verwijderd door afzender.



---
Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
http://www.avast.com

**Comment by abrookbanks** [comment]
You should be able to manually update the VAT for now. This is on hold until this section is rebuilt for the next mid point release of CubeCart.
