### ISSUE TITLE
<br /> still in use in FCKEditor

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#448]
All the rest of Foundation is no longer using ```<br/>```, but has changed to ```<br>```. But the Smarty FCKEditor boxes, such as product description and documents, plus others, still revert to ```<br/>```, even when ```<br>``` is saved. (I couldn't figure out how to get the code to show, so I left the leading birdbeak off.)

**Comment by abrookbanks** [comment]
http://docs.cksource.com/CKEditor_3.x/Howto/HTML_Output

**Comment by abrookbanks** [comment]
Thanks Rosemary.
