### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#450]
In Encryption->setup(), reference is made to `$GLOBALS['config']->get('config', 'license_key')`.

In the last versions of CC, this value may or may not exist. A result of `md5()`'ing a null value can happen - not to sure about a false value unless auto-typed to a string of '0'.

But what happens when the store has been upgraded from a licensed version where the encryption was setup with the license key, but now there is no license key to decrypt?

**Comment by abrookbanks** [comment]
Thanks Brian.
