### ISSUE TITLE
Canada Post

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#451]
I'm looking at CanadaPost's online docs and not seeing where the URL:Port as specified in the class file is valid.

**Comment by bhsmither** [comment]
I found something at:
http://sellonline.canadapost.ca/FAQ.html

**Comment by abrookbanks** [comment]
> Will Sell Online work if there is a firewall between Sell Online’s server and I ?

> Yes. You have to inform your system administrator that you need to perform TCP (not UDP) socket communication between your computer and the Sell Online server (IP adress=sellonline.canadapost.ca Port:30000). He will need to reconfigure your company’s firewall to allow you such operation.

Crazy they use this port. It's geared up to larger organisations not small ones on basic hosting.
