### ISSUE TITLE
Shipping description on order print incorrect

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#457]
6.0.2 the order prints Shipping (By_Weight) rather than the correct shipping description ie First or Second Class

![shipping](https://cloud.githubusercontent.com/assets/6114431/7044865/378c8b26-ddf8-11e4-8d80-66fcdd5e4c06.jpg)

**Comment by abrookbanks** [comment]
This is because the email templates are at v5 still. There is no process in the upgrade to convert them. You can reimport them by deleting them then using the import tab to reimport. 

I don't really have a fix for this.

**Comment by abrookbanks** [comment]
.. its about the only thing that changes in the email templates from v5 to v6.
