### ISSUE TITLE
Add Language on Translate Document issue

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#46]
I have US English language installed, but only UK choice shows up when I try to put Documents in new language.

**Comment by bhsmither** [comment]
Assuming the document is already in English, the drop-down selector should have every language you have installed, except the language(s) this document already has a translation for.

To test, install the Spanish language. See what gets listed in the selector.

**Comment by Dirty-Butter** [comment]
I installed Spanish, cleared cache, and went to Documents. UK and Espanol showed in drop down choices for Translation, but not US. I checked to be sure store was in US. Changed the homepage document to Spanish and saved. On going back to translations to change it back to English (UK), THEN the English (US) choice was there!

**Comment by Dirty-Butter** [comment]
Today the US choice is showing on the store I did NOT install Spanish. Could the problem be in CC not clearing cache properly? 
I had a terrible time yesterday getting the browser to show some fairly simple edits. I was blaming it on FF, and it may well be, but perhaps it is a CC clearing cache issue?

**Comment by Dirty-Butter** [comment]
Just to be sure this is a bug, I installed a new database v6 today from scratch. Immediately installed US English, and again it does NOT show up as a translation choice for a document, even after clearing all caches, including browser, and verifying it shows in the Language folder after cache clear.

**Comment by Dirty-Butter** [comment]
I just gave the Homepage Document my title, and now US shows up as a language choice.

**Comment by abrookbanks** [comment]
OK so if there are no possible ways to translate (i.e. one language pack) it will tell the user that they need to add the master language first. Also cache cleared on language "plugin" install.
