### ISSUE TITLE
Checkbox for Single Image does NOT save as STAR - bug?

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#460]
I lost a few images on last download/upload and had to go in and re-associate the image with the appropriate product. When I went to the Images tab on the product and put a check in the box by the correct image and saved, I did not get the expected results. I did see the image on the storefront, so did not realize anything was wrong. 

BUT no image thumbnail showed on the Products Summary page, and Google still did not have an image associated with the item. I finally realized that checking in the box was not enough, but that I had to click twice to get the star image. Since these items only had the one image, it did not occur to me that they would not be saved as the primary image.

**Comment by bhsmither** [comment]
And so, you are recommending that if a product has only **one** image "indicated" (checked or starred), that Cubecart should "assume" that this is meant to be the "Main Image" however it was that the admin made the image to product association?

I can see this as being helpful for a noob admin, but once the legend at the top of the file picker is noticed, and the actual image for the Main Image selection appears to the right of the file picker, how it all works should snap in to focus.

Am I missing something?

**Comment by Dirty-Butter** [comment]
I take it this is the way it's always been. As my normal process is to upload the image and then save FROM the Image tab of the Product listing, it was never an issue for me before. The change to checkbox was enough different for me to not think about double clicking. I'm adding some products today and will pay attention to whether or not the upload/save from the Image tab automatically assumes star or not.

**Comment by Dirty-Butter** [comment]
Just as I thought - when the association of image to product is made by uploading the image and saving from within the Image tab of the new Product Listing - the single image is automatically created as the primary starred image. When I have had more than one image in past situations, I did have to specify which was the starred one, although I could usually create them in an order that would create the starred one for me - the last one uploaded, if I remember correctly.

**Comment by abrookbanks** [comment]
There are a lot of possible scenarios here. From what I have found;

- adding a new image (upload) marks it as primary
- adding one existing image doesn't make it as primary

Movie here: http://static.cubecart.com/github-issue-460.star.mp4

Are we all looking at the same issue?

To correcting this would be to make the manually assigned image primary by default.

**Comment by abrookbanks** [comment]
I'm not not even able to reproduce the movie. :-/ Might call it quits for a week.
