### ISSUE TITLE
CCv6.0.2 Admin/Statistics: No Best Selling Products or Best Customer data after upgrade

### ISSUE THREAD

**Issue by jasehead** [cubecart/v6#462]
I've upgraded from CCv3.0.17 to CCv.6.0.x a few times. On the admin/statistics page there is no data in the tabs for Best Selling Products and Best Customers, even though there is historical statistical data for Sales, Most Viewed and Search Terms.  I do remember that previous upgrades from v3 to v5 did have the Best Selling/Best Customers data - so that part of the upgrade did work OK for v5.

**Comment by bhsmither** [comment]
In the file /admin/sources/statistics.index.inc.php:
```
Find near line 181:
$smarty_data[5] = array();
Change to:
$smarty_data['product_sales'] = array();
Find near line 188:
$smarty_data[5][] = $result;
Change to:
$smarty_data['product_sales'][] = $result;
Find near line 284:
$smarty_data[8] = array();
Change to:
$smarty_data['best_customers'] = array();
Find near line 291:
$smarty_data[8][] = $result;
Change to:
$smarty_data['best_customers'][] = $result;
```

**Comment by jasehead** [comment]
Perfect. Thank you :)

**Comment by havenswift-hosting** [comment]
Hey jasehead - no point closing this until Al has reviewed the proposed fix provided by Brian and then included into core code for next release !

**Comment by abrookbanks** [comment]
Thanks I fixed this now.
