### ISSUE TITLE
Foundation Mobile Site Extras box cut off

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#463]
If you view your demo store and view a product such as the 3D TV on a mobile the Extras box is cut off with the down arrow cutting text off?

**Comment by abrookbanks** [comment]
Thanks for this. I'm struggling to understand what the "Extra box" is?

**Comment by bondimedical3** [comment]
Where you select the Installation Service for the 3D TV

**Comment by abrookbanks** [comment]
Thanks for this! :)
