### ISSUE TITLE
Javascript Load Order

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#465]
In /foundation/js/, the files have number prepended to them to aid the operating system in giving PHP's `glob()` function a sorted array.

Yet, in the GUI class, near line 161, there is a flag that specifically tells `glob()` to not sort what was given to it, thus rendering the numerical prefix irrelevant.

Suggest removing the GLOB_NOSORT flag.

**Comment by abrookbanks** [comment]
Thanks Brian!
