### ISSUE TITLE
Add to basket - frontend problem

### ISSUE THREAD

**Issue by nklisic** [cubecart/v6#468]
I testing master version, after last updates click on add to basket button causes irregularity in store front-end layout.
![add_to_basket](https://cloud.githubusercontent.com/assets/10867308/7180244/2b75d286-e440-11e4-9c80-bc48f1eddaf7.jpg)
Cacshe has been deleted. Try on project.payroll.rs

**Comment by abrookbanks** [comment]
Fix one issue.. create another.. I'm looking at this now. Thanks..

**Comment by abrookbanks** [comment]
Accidental bug introduced here: https://github.com/cubecart/v6/commit/cbbac8b11d02b744e056720cf811b2cf44acad25#commitcomment-10755461

**Comment by abrookbanks** [comment]
Fixed now. Sorry for any inconvenience caused.
