### ISSUE TITLE
Wrong Price for Best Sellers Box

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#469]
Still working this through, but I see that CC6 has added prices to the array of products in GUI->_displayPopularProducts(). This is CC6's "Best Sellers" box.

All values end up being *null* (and nothing is displayed), except (as observed) when the product has a Quantity Pricing schedule **and** the customer has placed enough quantity in the basket to meet the first price discount point.

That is, the price of the item is 8.99, and at five units, the price is 7.99. With an empty basket, no price is displayed in the "Best Sellers" (popular products) box. When the basket contains a quantity of five for this item (or more), then the price of 7.99 is displayed for that item in the "Best Sellers" (popular products) box.

**Comment by abrookbanks** [comment]
I've not been able to reproduce this one. Please let me know if you find anything else and I'll reopen.

**Comment by bhsmither** [comment]
One more condition: Source data for popular products = Views.

In GUI->_displayPopularProducts(), if popular products is Sales-based, the query includes price and sale_price. Thus, in the end, the Best Sellers box will show Price and Sale Price.

However, if Views-based, the query does **not** include price and sale_price. Thus, in the end, the Best Sellers box will not show any prices.

Except for the original problem mentioned at the start. Still tracing that out.

In Views mode, I get the price of the first quantity price level. In Sales mode, I get --Regular Price-- and a sales price that I don't know where that figure comes from.

**Comment by bhsmither** [comment]
The Sales Price I had a question about above is good. I was looking at the wrong item because the order of items shifted.

**Comment by bhsmither** [comment]
However, if I have a quantity of this item in the basket, and the quantity price is lower than the sale price, the quantity price shows in the Best Sellers box as a regular price.

This item is normally 8.99, on sale for 6.99, with price breaks at 5@7.99, 10@6.99, 15@5.99.

So, having a quantity of 15 in the basket, the Best Sellers price shows 5.99 as a regular price. 5.99 is also shown in Latest Products as a regular price. 5.99 is showing as a lined through invalid regular price in the Sale Items box. 5.99 as a regular price in the View Category page, and as a regular price on the View Product page (until the javascript immediately changes the regular price to equal the sale price).

**Comment by abrookbanks** [comment]
Thanks I added those columns. I think the best sellers box has to always assume a quantity of 1.
