### ISSUE TITLE
Languages List Toggle Won't

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#47]
The icon to switch between Enabled and Disabled for each language on the list of languages won't switch.

**Comment by bhsmither** [comment]
It actually changes the value of the hidden input, but not change the image.

**Comment by bhsmither** [comment]
I must have done something that killed the javascript. Now it seems to be working after I implemented  #44.

**Comment by abrookbanks** [comment]
I wan't able to reproduce this either. I closed this for now. It can be reopened if necessary.
