### ISSUE TITLE
Newsletter Bug

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#476]
Using 6.0.2, if you want to send a newsletter having only "plain text content", nothing gets added to the sent newsletter.

Steps to reproduce:

1) log in as admin
2) Go to newsletters -> Create Newsletter
3) fill out the form and select template "Default Newsletter",
4) leave HTML Content blank
5) Put anything at all in the Plain text content
6) <save>
7) from your newly created newsletter go to the "Sent Test Email" tab and send the mail to yourself.

The mail arrives using the default newsletter template, but no content is added to the template.

**Comment by bhsmither** [comment]
I cannot duplicate this result.

The email sent as a test does arrive with both components -- HTML and plain text. The HTML component has the newsletter HTML template stuff and exactly what I entered in the HTML tab, nothing for the body's actual content. The plain text component has the newsletter plain text template stuff and exactly what I entered in the plain text tab, the phrase "Testing." for the body's actual content.

**Comment by Noodleyman** [comment]
not sure what is different between your install and mine. I am using a clean 6.0.2 install.

If you leave the HTML tab as is, no content then the plain text doesn't get added to the mail, which is the error. 

From your description above you have suggested that you have populated both tabs.

No matter what combination of settings i've tried it only ever sends the newsletter using the inputs from the HTML tab and never from the plain text content.

My assumption would be that if no HTML content has been supplied, and also no template specified the mail body would simply be plain text as per the plain text tab.

**Comment by bhsmither** [comment]
You haven't mentioned it, but allow me to ask that you verify that you can/have set your email program to view the "plain-text" component of the email.

*"and also no template specified"*
CubeCart will always use a template as listed in admin, Email Templates, Email Templates tab. (There is a situation I am not happy with: there is only one checkbox allowed to be checked. So, when sending newsletters, the one template checked will be used, even if it is the Default Email template. So, if you setup a newsltter campaign, you need to first uncheck the Default Email, check the Default Newsletter, Save, then send the campaign.)

**Comment by abrookbanks** [comment]
I can't reproduce this either. It worked as expected. The HTML part is empty and plain text shows. Raw message here:

![screen shot 2015-04-20 at 15 25 43](https://cloud.githubusercontent.com/assets/4520803/7232120/b835a50a-e771-11e4-99d4-b462ae9b6ea5.png)

**Comment by abrookbanks** [comment]
Happy to reopen if this can be reproduced.  :)
