### ISSUE TITLE
Addthis Plugin

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#480]
I have installed the Addthis Plugin and am using Foundation and have noticed the word "Share" is too low down and even touches the icons. Can you align this better?

**Comment by abrookbanks** [comment]
I released 1.0.1 here: https://www.cubecart.com/extensions/social-plugins/addthis

You can upgrade using an install token. It will remove the "Share" text. This brings inline the display of large and small.

**Comment by bondimedical3** [comment]
For products the new version is okay but for documents its very low to the black bar. Can you put some padding on the bottom?
