### ISSUE TITLE
6.0.2 to 6.0.4 Upgrade error message

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#482]
File: [database.class.php] Line: [484] "ALTER TABLE `CubeCart_inventory` ADD `minimum_quantity` INT( 10) NOT NULL DEFAULT '0' " - Duplicate column name 'minimum_quantity'

**Comment by abrookbanks** [comment]
Thats actually an expected result in most cases. You store has it from a past upgrade.. it was missing from the install database scheme so in some cases its needed. CubeCart will soft error and continue so this is all fine. :)

**Comment by Dirty-Butter** [comment]
glad it wasn't a problem

**Comment by abrookbanks** [comment]
Thanks Rosemary. Hope you are well.
