### ISSUE TITLE
Add remove line item from basket in mobile view

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#484]
There is no ability to remove items from the shopping basket page on the mobile site. Please add this.

**Comment by Dirty-Butter** [comment]
I see a minus and a plus sign where a customer could zero out the item Just tested, and it worked for me. The only thing I noticed that might be worth tweaking is there is no "home" icon after zeroing out. The customer has to click on the logo to get back to the homepage to continue shopping.

**Comment by abrookbanks** [comment]
This can be achieved by setting the quantity to zero and then click update. Maybe it not friendly enough.

**Comment by bondimedical3** [comment]
I don't think that is clear enough for customers. The medium and large versions have a symbol next to the product to delete it from the basket. The first time I looked at it I had no idea how to remove an item.

**Comment by abrookbanks** [comment]
Ok I'll take a look at this.

**Comment by briansandall** [comment]
@abrookbanks @bondimedical3 It looks to me like this issue has been resolved somewhere along the way:
![cc_484](https://cloud.githubusercontent.com/assets/14335170/21573611/59e21548-ce9b-11e6-9558-3d5355042250.jpg)
Unless there is a specific mobile version of the site I'm unaware of that is missing this functionality?

**Comment by Dirty-Butter** [comment]
I have the trash can - not sure when this was fixed.
