### ISSUE TITLE
Reordering from Order History - Duplicate Invoice ID

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#485]
> We have had a customer advise us that when they try to reorder from their order history, once through the checkout and redirected to PayPal, they are presented with an error saying that the invoice as already been paid. Is this a a problem we need to fix from a cubecart or paypal perspective?

**Comment by Dirty-Butter** [comment]
Using the LoginAs function, I tried this. It worked fine IF we had more of the item in stock. However, if we were sold out - the browser loads again and nothing happens. There should be an error message that we no longer have it in stock.

**Comment by abrookbanks** [comment]
Thanks Rosemary.
