### ISSUE TITLE
Returning Logged in Customer Behaviour

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#486]
When a customer returns to the site and logs in, they see their name in the Header. Unless they know to click on it, they do not realize they have options. Not even hover shows them they have more screens available. Suggest this be more obvious.

**Comment by abrookbanks** [comment]
Yes I agree.

**Comment by Dirty-Butter** [comment]
Your icon-chevron-down solution in the forum did not work for me, but &#x25BC; did work. I also added this to language and currency. Works much better when it's obvious there are choices.

**Comment by abrookbanks** [comment]
Thanks Rosemary.
