### ISSUE TITLE
Search bug?

### ISSUE THREAD

**Issue by davshirley** [cubecart/v6#487]
I noticed that it I have an item with a part number of "A1234" and I search for "1234" it isn't found.  I guess I am asking for partial word search and it looks like cube cart only searches on complete words.  Is there a way that you can enable the searching of partial words?  Perhaps a store option that could be set?

**Comment by bhsmither** [comment]
Do you have a conversation started on the forums? If so, let us know where. If not, maybe join this conversation:
https://forums.cubecart.com/topic/46555-is-there-any-way-to-improve-customer-search-experience/

If you are comfortable with making code edits, the last few posts of that conversation seems to be what others have said works for them.

**Comment by abrookbanks** [comment]
This certainly could be improved. We need a search as you type dropdown too.

**Comment by Noodleyman** [comment]
Hi Al,

I am just checking in if this is something that can be added to one of the version 6 updates? 

It's a reasonably simple change to both search methods (LIKE and FULLTEXT).

**Comment by abrookbanks** [comment]
Not sure I understand. CC falls back to like search if fulltext fails?

**Comment by Noodleyman** [comment]
yes it does, but neither currently offer matches on partial product codes which is the feature request ;)

**Comment by abrookbanks** [comment]
Hmm I thought it did do a partial search;

```
for ($i=0; $i<$noKeys; ++$i) {
							$ucSearchTerm = strtoupper($searchArray[$i]);
							if (($ucSearchTerm != 'AND') && ($ucSearchTerm != 'OR')) {
								$regexp .= '[[:<:]]'.$searchArray[$i].'[[:>:]].*';
							}
						}
						$regexp = substr($regexp, 0, strlen($regexp)-2);
						$rlike = " AND (I.name RLIKE '".$regexp."' OR I.description RLIKE '".$regexp."' OR I.product_code RLIKE '".$regexp."')";
```

**Comment by Noodleyman** [comment]
Here is an example from the CubeCArt demo site.

Search for "KDL-32HX753" you get the matching product.

If you then search for "DL-32HX753", no results. 

https://demo.cubecart.com/cc6/

**Comment by bhsmither** [comment]
There is a difference between RLIKE and LIKE. They use different sets of pattern characters.

`$regexp .= '[[:<:]]'.$searchArray[$i].'[[:>:]].*';`
The code `[[:<:]]` is a word boundary for RLIKE, meaning anything not a CTYPE. So, this is not a partial word pattern.

LIKE uses only a percent and underscore as pattern characters.

**Comment by Noodleyman** [comment]
@abrookbanks, any progress with this topic?

**Comment by abrookbanks** [comment]
I'm content this works well. Search has 3 fallback attempts now.

1. Fulltext
2. RLIKE
3. LIKE
