### ISSUE TITLE
Captured card details not displayed even under SSL

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#489]
An order was "paid" using the card capture gateway and looking at the order record via MySQL the encoded details are stored in the offline_capture field.  If viewing the SSL tab without SSL it correctly shows "View under SSL" but switching to SSL page, all fields are blank

**Comment by havenswift-hosting** [comment]
This appears to be a problem with orders placed when running V3 and upgrading to V6.  Orders placed and paid using V6 are OK

**Comment by SemperFiWS** [comment]
The same thing occurs for stores upgraded from CC4 using the card capture gateway.

When this:
```php
$card = unserialize($decrypt->decrypt(stripslashes($summary[0]['offline_capture'])));
```
executes for a CC6 order you will get an array like this:
```php
Array ( [card_type] => VISA [card_number] => 4111111111111111 [card_expire] => 12/2018 [card_valid] => [card_issue] => [card_cvv] => 123 )
```
but for old orders you will get nothing.

A possible solution would be changing this:
```php
				$card = unserialize($decrypt->decrypt(stripslashes($summary[0]['offline_capture'])));
```
to this:
```php
				$card = unserialize($decrypt->decrypt(stripslashes($summary[0]['offline_capture'])));
				if(empty($card)){
					// Decrypt CC3/CC4 Card Details
					$card = unserialize($decrypt->decryptOld(base64_decode($summary[0]['offline_capture']), $summary[0]['cart_order_id']));
				}
```
in the '/admin/sources/orders.index.inc.php' file.

Then adding this:
```php
	/**
	 * Decrypt CC3/CC4 data 
	 *
	 * @param string $data
	 * @param string $cart_order_id
	 * @return string/false
	 */
	public function decryptOld($data, $cart_order_id) {
		$keyArray = array($cart_order_id);
		$this->_td_old	= mcrypt_module_open(MCRYPT_RIJNDAEL_256, '', 'ecb', '');
		$this->_iv_old	= mcrypt_create_iv(mcrypt_enc_get_iv_size($this->_td_old), MCRYPT_RAND);
		$this->_ks_old	= mcrypt_enc_get_key_size($this->_td_old);
		$this->_key_old	= substr(md5(implode('@', $keyArray)), 0, $this->_ks_old);
		if (!empty($data)) {
			mcrypt_generic_init($this->_td_old, $this->_key_old, $this->_iv_old);
			$stringDecrypted = mdecrypt_generic($this->_td_old, $data);
			mcrypt_generic_deinit($this->_td_old);
			return trim($stringDecrypted);
		}
	}
```
in the '/classes/encryption.class.php' file.

**Comment by abrookbanks** [comment]
Thanks Daren I have added this now.

**Comment by jasehead** [comment]
This is still an intermittent issue with CC v6.0.12 - order paid using card capture gateway, transaction log shows it so, credit card details field all blank, phpMyAdmin shows encoded details are stored in the offline_capture field.

Is there a fallback method for getting cubecart to decode and display the credit card details?

Does cubecart generate a key which later expires and so is unable to decode the data?

**Comment by abrookbanks** [comment]
I can't reproduce. Please can you provide reliable steps to reproduce this.

**Comment by jasehead** [comment]
Like I said - this is an intermittent problem so it's difficult to pin down.  In my first 13 card orders I had 2 with no details displayed.

My first theory was an admin login issue (maybe another tab open or another browser session) but after today's order with blank credit card details I think that unlikely - unless cubecart somehow thinks that other sessions are still open even when browsers and devices have been shut down.

My second theory is that time plays a part.  I've found that processing credit card orders quickly avoids the problem, and that leaving card orders for between 12 and 24 hours seems to increase the likelihood that the card details will be blank.  Maybe cubecart generates a fresh encoding key and aged orders can no longer be decoded for display?

I'll use some dummy card numbers and test the time theory.

**Comment by abrookbanks** [comment]
Line 102 of the galeway.class.php file of the card capture module uses the order number as the encryption key. 

Line 288 of admin/sources/order.incex.php file uses the same to decrypt. 

Maybe you could hard code both of those to use your own constant key. 

```
$this->_encryption->setup(false, 'abc123xyz');
```
```
$decrypt->setup(false, 'abc123xyz');
```

**Comment by abrookbanks** [comment]
p.s. Don't use that key.

**Comment by abrookbanks** [comment]
I just wondered if the client is use the browser back button and maybe a new order number is generated?!

**Comment by jasehead** [comment]
Not seeing any pattern in the transaction log or history of the three orders with blank card details to indicate that customers used the back button mid-order or that it caused the problem if they did. The two customers I've spoken to reported that they had no issue during checkout and didn't notice anything unusual.

Impatient customers could click the submit button twice though (which happens with add to basket on slow connections) - could repeatedly clicking submit in checkout cause an issue?

For your suggestion of decrypt key, could I paste in the order number for a one-off decrypt to see if I can get missing card details to show or is the order number as a key itself encrypted?

I have one current order with no card details showing - ideally I'd like to be able to retrieve those details for processing instead of having to contact the customer and ask for their details again.

**Comment by jasehead** [comment]
Pasting in the order number as a one-off decrypt key didn't work - still no card details.

**Comment by abrookbanks** [comment]
I meant hard code your own public key. Then when new orders are placed see if it's more reliable.

**Comment by jasehead** [comment]
Does encryption.class.php also play a part in this?  If the crypt for credit card details uses both the config enc_key and the order id to encode/decode then a change in either one of these would cause an issue.  What if encryption.class checks for a key but the check fails and it ends up overwriting the existing enc_key with a new one?

**Comment by abrookbanks** [comment]
Yes it used for the encryption.
