### ISSUE TITLE
Create Order Enhancement Request

### ISSUE THREAD

**Issue by mackecm2** [cubecart/v6#491]
We would like to use the Create Order option in the V6 Admin Panel to enter orders on behalf of customers who phone and/or email our client with orders.

It would be really helpful if the following fields could be auto-populated as we enter the customer and product details:

Shipping Method (drop-down list if there is more than one option)
Shipping Price to be calculated when the Inventory details are added
Tax to be calculated when the Tax Class is selected.

**Comment by abrookbanks** [comment]
:+1:

**Comment by havenswift-hosting** [comment]
We are currently working on a plugin that will add lots of additional functionality to the admin order program, including this.  This will take all features from our CubeCart V4 Enhanced Admin Order Entry mod that arent already in V6 and add them as a plugin - all of the above will be included

**Comment by mackecm2** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by mackecm2** [comment]
Any progress to report on this?

**Comment by abrookbanks** [comment]
No. If there is you will get an email notification or something will be posted here.

**Comment by mackecm2** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by havenswift-hosting** [comment]
Our plugin is just about ready for release and is in final testing - I will update here and it will also be added to the marketplace

**Comment by havenswift-hosting** [comment]
Our Enhanced Order Entry plugin has now been released - details here https://www.havenswift-hosting.co.uk/cubecart-enhanced-admin-order-entry-plugin/
