### ISSUE TITLE
Position of basket box on desktop site - Checkout button invisible

### ISSUE THREAD

**Issue by nklisic** [cubecart/v6#496]
When have number of different items in basket more than 14 on desktop site, fixed positions of basket box make checkout button invisible.

![desktop_basket_content](https://cloud.githubusercontent.com/assets/10867308/7410391/ab42cda4-ef2e-11e4-935e-95c5cf066289.jpg)

**Comment by abrookbanks** [comment]
I see the issue! So we either need a scroll bar of some form or to just show the last x number of items added..

**Comment by nklisic** [comment]
I think that second suggestion is better. You can show 10 last items in basket. This is enough for any resolution and screens.

**Comment by abrookbanks** [comment]
This is work in progress. Changing to a bulleted list condenses it considerably..

**Comment by havenswift-hosting** [comment]
If having a fixed list, then it should show the last X number in reverse order BUT a scrollable list of all items in reverse order would be much better so all items can be seen with most recently added at the top

**Comment by abrookbanks** [comment]
Used array_reverse so the newest items is always at the top
