### ISSUE TITLE
Category drop down menu bug

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#500]
For medium devices the Category Name appears twice in the drop down menu. So in your demo store TV & Home Cinema appears a second time in the drop down menu. This is not necessary as the customer can get to this page simply by clicking the top of the menu (And also you say "TV & Home Cinema 3 times"). This menu should be arranged as is for large devices where the category name doesn't show a second time in the drop down menu.

**Comment by abrookbanks** [comment]
This is fixed with commit 0c34a2c49ee833259e9e16244631c96fc987b785

Thanks for the report.
