### ISSUE TITLE
Enhancement Request: Export URL

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#501]
It appears that the export URL's are hard coded to use 5,000 items per page, I am currently testing using the google base feed.

When using a store with a very large number of products the default feed URL's will not contain all of the products. In my testing when increasing the quantity of products in the URL to over 10,000 I was met with a white screen and no data.

Recommending that multiple URL's appear for export URL's just like they do for manual downloads based on 5,000 products per page, that way people can easily copy/paste without having to know they need to adjust the URL for multiple pages/files.

**Comment by abrookbanks** [comment]
I'm not sure how to go about this. The export URL is designed for automated synchronizations so adding pagination or multiple links from a UX perspective isn't ideal.

**Comment by Noodleyman** [comment]
the main issue is the export link is hard coded to 5,000 products.

if you have more than this and are not aware of how to change the links, or that you should change the links then you may just assume it has sent all of your inventory.

In a store with 30k products, the current system only allows you to export 5,000 of them easily.

**Comment by abrookbanks** [comment]
Maybe the limit should be removed however any store with a large inventory is going to crash when PHP runs out of memory and/or time.

**Comment by Noodleyman** [comment]
sounds like it definitely needs an enhancement to be able to support people using large stores ;)

the work around for the store i've been working on was to paginate the results and create a feed for each. it's not ideal but is what was driving the original request

**Comment by abrookbanks** [comment]
I think the only solution for now is to increase the export limit which is in the above commit. Maybe in the future CubeCart can write and edit a file as products are edited and it can be downloaded. Having PHP generate a large export feed on the fly is just too heavy. I doubt this will be a requirement of the majority of our customer base who generally have small inventories.

**Comment by Noodleyman** [comment]
Is there a new ticket open for that as an enhancement? :+1:
