### ISSUE TITLE
Non-INI'd PHP Files

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#502]
Request re: plugins.php

For sites running PHP 5.2 or 5.3, magic_quotes still defaults to On.

In the plugins.php file, the code is using file_get_contents() which is affected by magic_quotes.

Request that the same ini_set() commands used in ini.inc.php be included here.

With magic_quotes on, the javascript file returned by the server has the quotes escaped and escaped quotes could cause otherwise inexplicable `javascript illegal character` issues, thus crashing javascript and making CubeCart non-operative.

**Comment by abrookbanks** [comment]
Thanks Brian!
