### ISSUE TITLE
A True Short Description

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#503]
Enhancement:

Currently, CubeCart takes the existing "Full Description" of the product, strips out all HTML tags, and truncates the remainder to a length specified by the General Settings "Product Precis".

There is a need for a terse and concise description for a product. It could be anything from a simple sentence to a list of bullet points.

Please see:
http://www.cubecartforums.org/index.php?showtopic=19270

**Comment by abrookbanks** [comment]
Thanks you this works great. I also added it to export and import catalogue.
