### ISSUE TITLE
Database bug causing missing images in Admin

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#504]
After upgrading a CubeCart 5 store to CubeCart 6 I noticed some images where missing in the Admin. I had images in folders and separate images. The images in folders all appeared in the Admin but the individual images did not. I went into phpMyAdmin and looked at the table CubeCart_filemanager and I noticed that the filepath field for the missing images was blank. This needs to be set to "NULL" in order for the images to appear in the CubeCart Admin and the upgrade did not set this. Please fix this for the next release.

**Comment by abrookbanks** [comment]
After upgrade if you have this issue sadly its not fixable. This issues has raised its head occasionally over the last few years and I've never been able to get to the bottom of it. I've put this as "wontfix" but its not forgotten. I upgrade on average three stores a day and it's not that common. When it does happen next I'll take another look. 

Sorry to be so defeatist on this issue.
