### ISSUE TITLE
Enhancement Request: Including JS in the admin skin

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#506]
within the admin skin file main.php there is a smarty variable for the purpose of adding custom JS skin files.

{EXTRA_JS}

Currently there is not a standard process for populating this smarty variable. It is up to the developer to write a processes to populate it.

The issue is that every developer does this in a different way, and at some point one plugin will overwrite another when setting the value unless the code first checks for it's existence and then appends to it.

Ideally the values of this smarty variable should be set in the same way JS files get included in the front end skin, using a hook and adding paths to an array which is then added to the smarty variable. This would standardise the processes and remove the likelihood of future conflicts.

**Comment by Noodleyman** [comment]
For reference, here is the process I am using today in the controller.admin.php hook, to do this to avoid conflicts, although it isn't preventing another plugin from overwriting it.

$arr = array();
if(isset($GLOBALS['smarty']->tpl_vars['EXTRA_JS']->value)){
	foreach($GLOBALS['smarty']->tpl_vars['EXTRA_JS']->value as $js){
		$arr[] = $js;
	}
}
$arr[]= $GLOBALS['storeURL'] . "/modules/plugins/map_option_image/js/jquery.function.js";
$GLOBALS['smarty']->assign('EXTRA_JS',$arr);

**Comment by abrookbanks** [comment]
I completely understand your logic and the possible issues. I can't think of a way around it. If we change it to expect an array another developer could just write an array overwriting existing ones.  

Any suggestions?

**Comment by Noodleyman** [comment]
I would make a new smarty variable available which in the skin loops an array and adds the paths.

then, add a new hook which can be used to add more items to the array. $js[] = "path"; 

this way people will start adding to the array instead of populating a single value ;)

**Comment by abrookbanks** [comment]
But in the admin/skins/templates/main.php we already have:

```
      {if is_array($EXTRA_JS)}
      {foreach from=$EXTRA_JS item=js_src}
      <script type="text/javascript" src="{$js_src}"></script>
      {/foreach}
      {/if}
```

Isn't that enough? It's been a heavy week.. maybe this is one for Monday (Tuesday).

**Comment by Noodleyman** [comment]
Ah, so all that is needed is the new method of populating that array.

but there is no code that populates "EXTRA_JS" already.

just roughing it, something like this:

$extra_js = array();
foreach ($GLOBALS['hooks']->load('admin.js') as $hook) include $hook;
$GLOBALS['smarty']->assign('EXTRA_JS', $extra_js);

then it is a simple case of people using the hook and adding to the array rather than having to define the smarty variable itself.

**Comment by abrookbanks** [comment]
Something like that yes. My brain has melted.

**Comment by abrookbanks** [comment]
I wouldn't have been able to do that without you. I need some beers now I think.

Let me know if you see an issue with that commit.
