### ISSUE TITLE
Upload images to specific subfolder during Add Product process

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#510]
I would like to be able to upload images to a specific image subfolder from the Image tab during Product creation. I've tried opening the correct folder, then uploading the image. But it currently goes into the source directory, not the subfolder.

**Comment by Dirty-Butter** [comment]
I think this is in 6.1.7?????

**Comment by abrookbanks** [comment]
It is indeed. Thanks so much Rosemary.
