### ISSUE TITLE
Can't export language from 6.04

### ISSUE THREAD

**Issue by demand73** [cubecart/v6#511]
When try to export my Swedish translation for a friend from admin page / Languages / Swedish / merge to file and click export i get HTTP 500 internal server error.

If i use the download link under action i get the old XML file i used from the beginning.

I solved this by giving him a backup on the CubeCart_language_strings 

Regards
Krister

**Comment by abrookbanks** [comment]
Thanks for your bug report Krister. I've not been able to reproduce this issue and it works on my development store. I expect its a file permissions issue in that the web server (probably running as "nobody") doesn't have permission to write to file and it has a 500 error. It's impossible to know for sure without seeing the actual error in the PHP error log.
