### ISSUE TITLE
Language Infiltration

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#512]
In admin, Languages, note the language being used in the dark session bar at the top, such as the phrase "Welcome back Admin - Log Out" for English (US).

Click the edit icon of a foreign language (such as Dansk).

Note that the session bar phrase is now in that language (but no where else).

**Comment by bhsmither** [comment]
This happens in CC5216, as well.

**Comment by bhsmither** [comment]
And the <title> tag in the HTML.

**Comment by abrookbanks** [comment]
Am I reproducing this correctly? http://static.cubecart.com/github-issue-512-not-reproducible.mp4

**Comment by abrookbanks** [comment]
Closing but I'll reopen if/when I can reproduce.
