### ISSUE TITLE
T&C Agree Logic

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#514]
I think the logic is not quite right for the Registration page.

In CubeCart->_register(), near line 2662, if there is no document identified as a 'doc_terms' document, then there will **not** be the checkbox on the registration form.

Then, in User->registerUser(), near line 681, there is this logic:
A. Disable checkout terms - unchecked = true
B. 'doc_terms' document present = true
C. POST['terms_agree'] is set = true

A & ((B & C) !== true) :: looking for a true result.

A solution is when B is false. 
T & ((F & T) !== true)
T & ( F !== true)
T & ( T )
Result: true, therefore an error message. But there is also no checkbox.

I suggest testing if(B) first, and if true, then if(A & !C).

When upgrading to CC4/5/6 from CC3, I think there is no attempt to inform the admin that CubeCart really needs a 'doc_terms' document. Maybe a red banner along with "Setup folder exists" and "Cache Disabled", etc.

**Comment by abrookbanks** [comment]
Thanks Brian. This makes sense.
