### ISSUE TITLE
Tax Rounding Issue

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#515]
Using a clean install of 6.0.4 and the test product with standard pricing.

Price: £10
Sale Price: £6.99

Defined the tax rate of the test product to be 20%, standard tax.

Set the tax to be "Inclusive" of the price.

Sale mode set to "Per Product"

Adding the product to the basket the total should come to £6.99, but the total is calculated as £6.98 because the calculated price of the product is incorrect. The product price is calculated as £5.82, but it should be £5.83.

It should be calculating as follows when tax is inclusive:
6.99 / 1.2 =- 5.825
5.825 rounds up to 5.83

The checkout process is not rounding up on this occasion, but it should do.

The checkout price does not match the product price due to the tax calculation error.

**Comment by abrookbanks** [comment]
This fixes this scenario but I live in fear that it may cause an issue elsewhere. Time will tell. :)
