### ISSUE TITLE
Modules Having Rich Text

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#518]
If there is ever the case where a plugin is using a rich text input, the Module class must be able to save it properly.

In `Module->__construct()`, a call is made at line 109 to `$this->module_settings_save()` passing `$_POST`. There must be a way for the $GLOBALS['RAW'] to be incorporated, but not a blanket acceptance.

Perhaps a config.xml node where RAW variables are declared:
`<rawvars><var>content_html</var></rawvars>`

Then, in a new Module->_enumerateRawVars(), have:
```
// Fetch package declared raw variables
if (file_exists($this->_path.'/'.$this->_package_xml)) {
  $xml = new SimpleXMLElement(file_get_contents($this->_path.'/'.$this->_package_xml, true));
  ## Parse and handle XML data
  foreach ((array)$xml->rawvars->var as $value) $this->_rawvars[] = (string)$value;
}
```
Then at some point before line 109, have something like:
```
$this->_enumerateRawVars();
foreach($this->_rawvars as $key) $_POST['module'][$key] = $GLOBALS['RAW']['POST']['module'][$key];
```
Also declare `private $_rawvars = array;` at the top.

**Comment by abrookbanks** [comment]
Works great from my testing with a few tweaks.
