### ISSUE TITLE
Add to Basket shown when product availability less than zero

### ISSUE THREAD

**Issue by jasehead** [cubecart/v6#521]
I use negative numbers to keep track of stock on backorder.  CCv6 foundation skin hides the Add to Basket button when the stock level is zero, but when it is BELOW zero the button appears again and takes the user to an out-of-stock item they can't purchase.  I'm guessing the code involved is {if $PRODUCT.available == '0'} found on the following pages:
* skins/foundation/templates/content.category.php (lines 105, 164)
* skins/foundation/templates/content.homepage.php (line 46)
* skins/foundation/templates/content.product.php (line 116)

Can this be changed from a string match to an integer so it checks for availability less than or equal to zero?

**Comment by abrookbanks** [comment]
Thanks! I've done this now.
