### ISSUE TITLE
Options Matrix getting updated incorrectly

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#524]
From the admin area when managing a product the option_matrix table gets updated / refreshed.

Part of this process matches the option matrix record to the option identifier, however it does not also match on product_id

this causes all records in the table with duplicate options identifiers to be incorrectly updated and can impact other products.

Line 1139 in products.index.inc.php
$GLOBALS['db']->update('CubeCart_option_matrix', array('cached_name' => $option_group['options_values'], 'status' => 1), array('options_identifier' => $option_group['options_identifier']));

needs to include product id

**Comment by abrookbanks** [comment]
Thanks Alec. I would have forgotten if you hadn't have made the report.
