### ISSUE TITLE
Dashboard Pending Reviews Tab

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#526]
The tab shows the total count of reviews available, not the count of **pending** or "to be approved" reviews.

Currently, dashboard.index.inc.php, line 200:
```
$reviews_count = $GLOBALS['db']->count('CubeCart_reviews', 'id');
```
Suggest:
```
$reviews_count = $GLOBALS['db']->getFoundRows();
```

**Comment by abrookbanks** [comment]
Works great thanks!
