### ISSUE TITLE
HTML Validation

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#527]
In Foundation, element.product_reviews.php, there is:
```
<p class="pagination_top">
  <span class="pagination">{if isset($PAGINATION)}{$PAGINATION}{/if}</span>
  {$LANG.catalogue.average_rating}: <strong>{$REVIEW_AVERAGE}</strong>
</p>
```
while `{$PAGINATION}` is element.paginate.php, which is an unordered list.

It is said that only inline elements may be inside `<p>` tags.

Suggest `<div>` instead of `<p>`.

**Comment by abrookbanks** [comment]
Thanks Brian.. I'm very slowly getting through these. I REALLY struggling to keep on top of everything. It's a huge help you provide suggested fixes as it saves me a lot of time. Massively appreciate it.
