### ISSUE TITLE
Require Rating in Reviews not working

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#528]
See unresolved discussion in forum - https://forums.cubecart.com/topic/49718-need-help-with-some-tweaks/

**Comment by Dirty-Butter** [comment]
All the code for this solution is in the thread linked above.

I had downloaded a customized version of Foundation back in the beta days, so I was finally able to get this solved - because I have foundation.abide.js installed. I'm now running 5.5.2 foundation and 5.5.2 Abide. 
Bsmither helped me keep the unstarred "comments" from previous reviews from being included in the Average Rating for a product.
And I modified element.product_review.php to use Abide.
Bsmither showed me how to get rating added to 3.cubecart.validate.js, and I figured out how to get the error message to show.
Suggest you consider adding Abide to the next release and use it for the element.product_review.php file.

**Comment by abrookbanks** [comment]
Using Abide means that all the javascript validation would need rewriting. Adding it doubles the functionality up so thats best avoided. If we coded the stars to default to one and have a minimum value of 1 would that be a sufficient fix?

**Comment by abrookbanks** [comment]
I haven't been able to fix the client side coding but I have added server side validation which I hope is adequate. Ideally it should have both server and client side validation. Client for good UX and server for good strength. 
![screen shot 2015-05-22 at 13 37 28](https://cloud.githubusercontent.com/assets/4520803/7770562/d10aaf7e-0087-11e5-9572-b0cb04d96db2.png)
