### ISSUE TITLE
Hooks requests

### ISSUE THREAD

**Issue by JenGitHub** [cubecart/v6#529]
Requests for hooks:

1) move class.order.order_status hook after getOrderDetails so assignOrderDetails can be used in hook.  Alternatively add a hook for each case orderstatus

2)add hook to tax.class productTax function.  In my case I need to modify tax based on affiliate location but can't find any hooks in this class

**Comment by abrookbanks** [comment]
Hi Jen,

1) you can use the hook "class.order.order_status".
2) new hook added "class.tax.producttax"
