### ISSUE TITLE
Digital Options - Custom File Path Broken

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#530]
From some tests I ran today, at a customers live store and one of my CC6 demo stores, it appears that the custom file path as a digital option is broken.

Test 1
Path: /home/xxxxxx/downloads-dummy/test.zip
Note: This is above the public_html directory
Download Link Result: Fails.

Test 2
Path: /home/xxxxxx/public_html/cc6demo-plugins/testing/test3.zip
Note: Direct link (http://cc6demo-plugins.semperfiwebservices.com/testing/test3.zip) works.
Download Link Result: Fails.

Test 3
Path: http://cc6demo-plugins.semperfiwebservices.com/testing/test4.zip
Download Link Result: Successful.

So it appears that is you enter a full URL it will work but if you use any path it will fail.

**Comment by bhsmither** [comment]
I have analyzed this:
https://forums.cubecart.com/topic/49723-digital-downloads-not-working/?do=findComment&comment=208660

If CC6 follows CC5, then the wording for the Custom File Path needs updating to reflect the fact the path **starts** with a relative folderpath/filename located in the /files/ directory. That is to say, the CubeCart absolute root path (e.g., /home/xxxxxx/public_html/cc6demo-plugins/) will be prepended to what is in the Custom File Path field.

**Comment by SemperFiWS** [comment]
This information presents a couple of problems.

1. The clients store I was referring to has over 5000 digital products.
These all are stored in directories above the public_html directory.
They didn't use the 'custom root path' setting in settings, just the 'custom file path' for all their digital products.
Since upgrading to CC6, downloads do not work and they have been manually emailing the purchased product(s) to their customers.
Seeing their digital products worked flawlessly before the upgrade they are furious that the system is now completely broken and are not going to be interested in editing 5000 products.

2. The ability to store digital products above the public_html directory needs to be reinstated. Close to every store I have encountered that sells digital products has been following this practice for years. It is not a good idea to enforce that they have to edit all their digital products to use a directory with the public_html directory either before or after upgrading just so downloads will continue to work.

**Comment by bhsmither** [comment]
Hmmm, according to what I said at https://forums.cubecart.com/topic/48371-digital-download-locations/?do=findComment&comment=201160 the Custom File Path should work as is, not as I said earlier.

But I will double check.

**Comment by bhsmither** [comment]
Well, here's what I have found: CubeCart will use the Custom File Path (CFP, or the 'digital_path' in the Inventory table) *as is*, but there is a bug in the code.

In filemanager.class.php, near line 621, where `$data` is being built if the CFP does not look like a URL and if the file actually exists where the CFP says it is located. If so, then `$data['is_url']` is set to `true`. This is not correct.

At line 362, this begins the determination on how to deliver the file. Line 365, being falsely told this file is a URL, will tell the browser to 302 Redirect to fetch it directly.

Try changing the statement at line 627:
```
'is_url' => false
```

**Comment by SemperFiWS** [comment]
Very well spotted Brian, that does fix the problem.
Thank you, very much appreciated.

**Comment by abrookbanks** [comment]
What the hell would we all do without Brian!!! Thanks so much. I've commit this code change for 6.0.5.

:dancers::dancers::dancers::dancers:

**Comment by abrookbanks** [comment]
Duh screwed up the issue number.. Please see: 5f2334728c07c180d62af79df4af866f43cda6f4
