### ISSUE TITLE
Admin CP: Filter products by category after editing a product

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#531]
This can cause an empty list. Fix is to either remove certain variables from the master form or to change the dropdown menu to have a javascript action.

**Comment by bhsmither** [comment]
This fix is not implemented for the case of "Any" from the drop-down.

In the case of "Any", the letter filter section should remain.

**Comment by abrookbanks** [comment]
Thanks Brian.

**Comment by bhsmither** [comment]
But wait! There's more!
https://forums.cubecart.com/topic/50122-resolved-product-sort-after-filtering-on-back-end/
