### ISSUE TITLE
Caching pages using HTTPS when Enable SSL = No

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#534]
Ran into this little gem today. 

The website currently has a self signed certificate, so it can accept https requests. However, I don't want it using it just yet.

Search engines have been crawling the site, and trying to use HTTPS. As they hit a page using https the content is getting written to CubeCart cache.

When a user comes to use the site using http, the cached pages are using https. the URL's are throwing a certificate warning.

within the store config the "Enable SSL" setting is set to "No". When set to no CubeCart should capture https requests and redirect back to http, or disable caching of pages when a https URL is used and the Enable SSL option set to no.

**Comment by abrookbanks** [comment]
Relates to #535

**Comment by Noodleyman** [comment]
this is actually a different issue, although both relate to cache.

links using HTTPS are getting cached when HTTPS is disabled in the store config. This shouldn't happen because it will cause users who load the cached pages to be directed to https links which can cause certificate errors.

if https is disabled in the store settings, it shouldn't be possible to load a cart page using https.

**Comment by abrookbanks** [comment]
Agreed but the cause and fix is the same.

**Comment by Noodleyman** [comment]
not necessarily :)

no change needs to be made to the cache system here. The cache behaviour reported is mealy a symptom of the main issue, which is it is possible to load https pages when the SSL option is set to off. The setting is not being respected.

With SSL disabled, there should be a redirect from https to http

**Comment by abrookbanks** [comment]
Maybe the simplest way to solve this is to never cache if the current domain (or IP) doesn't match one specified in either the SSL or "standard URL" value?

**Comment by abrookbanks** [comment]
Infact the cookie domain is probably the best one to use.

**Comment by Noodleyman** [comment]
the SSL domain would make sense because the SSL certificate would be for a specific domain.

**Comment by abrookbanks** [comment]
Fix only allows cache on correct domain. Works great from my testing. Wow what a simple fix.
