### ISSUE TITLE
Wording for Error

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#536]
In orders.index.inc.php, near line 440, if the database returns a false (because of orders not found), the error message displayed to the admin is: `['orders']['error_print_generate']`.

While the end result is true, the cause can be better disclosed. Suggest instead near line 523: `$GLOBALS['main']->setACPWarning(sprinf($lang['orders']['order_not_found'],''));`

Also, the phrase for orders.error_orders_delete in definitions.xml has a misspelling.

**Comment by abrookbanks** [comment]
Thanks Brian.
