### ISSUE TITLE
Printing Invoice from admin area

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#538]
If you want to build a custom invoice there is currently a limitation.

the "country_d" and "state_d" values get converted from the internal ID to the correct value.

However, if you try and use the non delivery values "state" and "country" in the template the numerical ID's are only available.

This is because the delivery variables are translated from ID to text in orders.index.inc.php, but this should also be done for the billing address.

**Comment by bhsmither** [comment]
Suggest using the Order method getOrderDetails().

The Order class is instantiated and *perhaps* the results from the method can replace lines 441-491.

**Comment by abrookbanks** [comment]
Please let me know if Brians suggestion is not suitable. Sounds like it should be. :)

**Comment by Noodleyman** [comment]
Brians suggestion would require end users making changes to the core files or using a hook.

something as fundamental as a billing address should be output as part of the core and not require any code changes to use.

Should a customer want to add the billing address to the invoice it should only require a redesign of the skin file, not require core code edits or the use of hooks.

It's a minor change to add it to V6.

**Comment by abrookbanks** [comment]
OK I agree lets do this..

**Comment by Noodleyman** [comment]
thank you :+1:

**Comment by abrookbanks** [comment]
Does https://github.com/cubecart/v6/commit/b1bdeaa2ba1fd99733fcc5a782c3b83ada1d66e5 do the job for you?

**Comment by abrookbanks** [comment]
I just tested it and it does work work. You can get the "raw" database values from the "raw" key of the order summary and items.

**Comment by Dirty-Butter** [comment]
orders.index.inc.php still has the "raw" array in it with 5/26/15 v6-master.zip. Orders crashed for me, but worked when I took those 2 references to raw out.

**Comment by bhsmither** [comment]
I'm at a loss with this approach to getting a solution to what was initially observed: we need the state/county `name` and the country `name` from the respective key numbers from the billing columns of the CubeCart_order_summary table.

The simplest solution is to duplicate lines 481 and 482:
Find:
```
$summary['state_d'] = (is_numeric($summary['state_d'])) ? getStateFormat($summary['state_d']) : $summary['state_d'];
$summary['country_d'] = getCountryFormat($summary['country_d']);
```
Add after:
```
$summary['state'] = (is_numeric($summary['state'])) ? getStateFormat($summary['state']) : $summary['state'];
$summary['country'] = getCountryFormat($summary['country']);
```
My suggestion about using Order->getOrderDetails() is predicated on not duplicating code unnecessarily (and fixing bugs in only one location). If getOrderDetails() can give us everything we currently get from the range of line numbers stated, I suggest we use it -- *and there are hooks available!!!* 

Also, I don't follow the comment "require end users making changes to the core files or using a hook." The suggestion is to improve the core files and publish them as the next version of the core files. That's what happens in the Github (as opposed to the Forums). Making the end user do anything, or implement a hook, is irrelevant.

**Comment by Noodleyman** [comment]
Sorry Brian,

I might have taken your comment out of context, I assumed it was meant for the users to make that change to get it to work. Looking back, clearly it's a suggestion to how to fix it in the code for a future release. My bad!

:+1:

**Comment by abrookbanks** [comment]
There was a parse error in the patch above. A later commit fixed this:
https://github.com/cubecart/v6/commit/e35a67e1ee535279342a9939103ac64d8106feba

**Comment by Noodleyman** [comment]
Hi Al,

this needs to be re-opened as it is not resolved in 607. To fix the issue the following needs to happen.

in admin/sources/orders.index.inc.php around line 494:
FIND:
$summary['state_d'] = (is_numeric($summary['state_d'])) ? getStateFormat($summary['state_d']) : $summary['state_d'];

AFTER ADD:
				$summary['state'] = (is_numeric($summary['state'])) ? getStateFormat($summary['state']) : $summary['state'];
				$summary['country'] = getCountryFormat($summary['country']);

**Comment by abrookbanks** [comment]
Thanks Alec. :-)
