### ISSUE TITLE
Category Translation

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#539]
In the file /admin/sources/categories.index.inc.php, near line 142:

Find:
if (isset($_POST['translate']) && isset($_POST['cat_id']) && is_numeric($_POST['cat_id'])) {

Add After:
$_POST['translate']['cat_desc'] = $GLOBALS['RAW']['POST']['translate']['cat_desc'];

**Comment by abrookbanks** [comment]
Thanks!! :godmode:
