### ISSUE TITLE
Checkout registration, cannot proceed if SSL is set to only on sensitive pages 

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#541]
How to replicate:
- set 'SSL' to 'only on sensitive pages'
- add a product to basket
- click view basket
- click checkout
- fill out registration fields
- complete recaptcha
- choose a payment method

Then try clicking on either the update or checkout buttons, both do nothing, no error displayed.

**Comment by SemperFiWS** [comment]
If you have 'SSL Priority' set to all, this problem does not occur.

I attempted to replicate this at the official CC6 demo store (http://demo.cubecart.com/cc6/), but setting 'only on sensitive pages' results in this:
The page isn't redirecting properly
Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

Side Note:
The official CC6 demo store needs to be upgraded to 6.0.4.

**Comment by abrookbanks** [comment]
What does your browser console log say?

**Comment by abrookbanks** [comment]
I think we need to depreciate sensitive page only SSL.
