### ISSUE TITLE
Checkout registration, changing country triggers all require field error messages

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#542]
How to replicate:
- add a product to basket
- click checkout
(https://demo.cubecart.com/cc6/index.php?_a=checkout)
- fill out the contact details fields
- start filling out the billing address fields
- change the country

You will then see something like this:
![checkout-required-checkout-registration-fields](https://cloud.githubusercontent.com/assets/6945093/7759695/a04ec628-ffe1-11e4-80d6-dbc8a2383736.png)

It would be better if the validation triggers on submit rather than on selecting a country.

**Comment by abrookbanks** [comment]
If you do happen to work out a bug fix for any off the issues that you report I'd be grateful. I'm struggling to keep up right now.

**Comment by abrookbanks** [comment]
Great find. Thanks! :)
