### ISSUE TITLE
Missing item in order admin

### ISSUE THREAD

**Issue by veShop** [cubecart/v6#545]
Hi, 

I'm setting up a new site with cubecart v6. Currently I just in testing phase. I've notice that when we place an order and complete payment we get an empty completed page and the 
items do not show up in the order admin page. It does display the correct amounts just no item detail. Did I miss a configuration somewhere? 

Regards,
VeShop
![emptyitem](https://cloud.githubusercontent.com/assets/12600047/7801191/5a002830-02e6-11e5-8480-d3007de5a9f3.gif)
![untitled-1](https://cloud.githubusercontent.com/assets/12600047/7801192/5a08f438-02e6-11e5-8d28-631f765c57e9.gif)

**Comment by bhsmither** [comment]
Probably not.

We just need to figure out what is unique about your installation and determine what is causing no products to appear in the admin's Order Summary.

CubeCart's customer Order Complete page is rather devoid of detail. It is not obvious what to do next (click on the store logo to get back to the storefront).

**Comment by abrookbanks** [comment]
Please can you send a technical support ticket and we will take a look at this. I'm certain this is a database problem due to bad upgrade.
