### ISSUE TITLE
Option Value Name DB Field

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#548]
Is too small, currently limited to 30 characters. This should be increased to accommodate larger option names / values.

I am often finding valid reasons to have to increase this myself for other people. Recommending a resize from 30 to 128.

CubeCart_option_value.value_name

in order to do this it needs to be changed from "VARBINARY" to "VARCHAR"

**Comment by bhsmither** [comment]
Or BLOB.

**Comment by abrookbanks** [comment]
Thanks for this. :)

**Comment by Noodleyman** [comment]
why is this field a blob / binary field and not a text field?

Wouldn't it be better to have it as a text field that can be indexed?

**Comment by bhsmither** [comment]
I recall another table column getting switched to BLOB because of (if I recall correctly) foreign character problems.

I wasn't promoting one data type over another, just mentioning other possibilities. Each has their pros/cons.

**Comment by abrookbanks** [comment]
yeah varchar should be fine and its nice to be able to read the database via phpMyAdmin. I changed it. Brian was right about character set issues. Storing in binary circumvents that issue. It should be fine as a varchar from recent CC versions.
