### ISSUE TITLE
Enhancement to the MySQLi connection

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#550]
Would it be possible to add an extra setting to the MySQLi connection in a future release.

mysqli_options($conn, MYSQLI_OPT_LOCAL_INFILE, true);

Adding the MYSQLI_OPT_LOCAL_INFILE setting can enable the ability for bulk loading files into MySQL using the MySQL "LOAD DATA"  command. This is very useful feature when bulk importing data from a flat file in the correct format as it's very efficient. 

Currently using a CubeCart DB connection, this method isn't possible.

As a work around in my existing code I have had to make a new MySQLi connection using traditional methods with this setting so I can use the "load into" command. The down side to this is it isn't possible to use MySQL temporary tables this session creates because they are separate connections.

**Comment by abrookbanks** [comment]
I don't know how compatible this is and if there are any security consequences.  

You can parse bulk SQL queries with Datacase_Controller->parseSchema in the classes/db/database.class.php file. 

If you follow the format of the upgrade SQL files it will split each query on "; #EOQ" and soft error if the SQL query fails.

**Comment by Noodleyman** [comment]
It's more about efficiency and making the SQL server do the work rather than the web server. Dropping in a 250mb csv file using the "load data" method is very quick and efficient and can be done using a single SQL query, MySQL parses the file directly into the target table, where as making PHP parse the file, and wrap those into queries it's a lot more intensive and will use lots of repeating SQL statements.

I believe the setting defaults to Off, unless it has been defined in the servers php.ini file.

http://php.net/manual/en/mysqli.options.php

It does also require the MySQL server to have the ability to use these statements enabled for it to work. 

More info here:
https://dev.mysql.com/doc/refman/4.1/en/load-data-local.html

**Comment by havenswift-hosting** [comment]
There would be no security consequences of adding this within CubeCart - as has been pointed out by Alec, this still needs to be enabled at a server level as it is disabled by default.

**Comment by abrookbanks** [comment]
So for 95% of stores it's unlikely to work by the sounds...

**Comment by abrookbanks** [comment]
Ian do you think there is any harm adding this? I fear people upgrading to see fatal errors if its not allowed. Hopefully for those that don't have it it has a soft error. Saying this a catch all could be braced around it.

**Comment by havenswift-hosting** [comment]
Cant see that there is any harm at all adding this

**Comment by abrookbanks** [comment]
Hokey Cokey... Hows this .. ?

**Comment by abrookbanks** [comment]
Seems to work ok so closing. :P
