### ISSUE TITLE
Possible search issue(s) for upgraded stores

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#551]
Scenario
A CC3 store gets upgraded to CC5 or CC6.
After upgrading entering anything in either the search box or the advanced search consistently returns nothing found.

Temporary Workaround
To get around this, the search function can be altered so 'fulltext' is bypassed completely.

Possible Solutions
There is different ways to address this better than the code hack mentioned above.
1.
Change the search function so if nothing is returned via 'fulltext' it automatically tries to use the old method.
2.
As part of the upgrade, rebuild this 'fulltext' index that the search uses.
3.
Add the ability to rebuild this on the 'Rebuild' tab on the 'Maintenance' page.

**Comment by SemperFiWS** [comment]
Additional information...

I was hoping to provide a current live store example of this happening.
Next time a customer freshly completes an upgrade, I will add the example.

There is also another scenario where if you enter an exact product code, a whole stack of irrelevant results are returned.
This I can provide an example:
http://www.hardware-store.dk/index.php?_a=category&search[keywords]=SFTESTSEARCH

**Comment by bhsmither** [comment]
The links you tried to make earlier do not work the way you think in Github. Please let us see the entire web address instead of making a *hash-digit* friendly portion.

**Comment by SemperFiWS** [comment]
They were not meant to be links so I have altered them.
I have also removed the additional information as a 3rd party search was being used at that store.

**Comment by abrookbanks** [comment]
> 1. Change the search function so if nothing is returned via 'fulltext' it automatically tries to use the old method.

It should do that anyway?

> 2. As part of the upgrade, rebuild this 'fulltext' index that the search uses.
> 3. Add the ability to rebuild this on the 'Rebuild' tab on the 'Maintenance' page.As far as I am aware this can just be done by doing an optimize on the table in question?

This can be achieved with an "Optimize" on the table in question which can be done via the admin control panel. 

I'm not entirely sure any action needs to be taken with this issue.

**Comment by SemperFiWS** [comment]
You are correct regarding it attempting the old search if nothing found via full text.

This can be closed or deleted as the store owner had previously altered the 'searchCatalogue' function and those changes were causing the problem.

**Comment by Noodleyman** [comment]
I had this problem in a store I upgraded, I found the full text index didn't exist in the store. I manually created it and it started to work Ok.
