### ISSUE TITLE
Server side password validation

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#554]
whilst solving an issue today I noticed that there appears to be a lack of password validation on the server side in CubeCart.

By removing the "required" attribute from the password boxes on the checkout/registration form and leaving the password fields blank the blank password is accepted as valid.

It is then possible to log in using a blank password.

Passwords should be checked both on the client and server side of the registration process.

Out "in the wild" I have seen a scenario where this behaviour can cause a problem with password resets. If you have a blank password and use the forgot password process the cart will log you in as the first customer it can find with a blank password. 

You get logged in as the other customer who also has a blank PW without using the login process.

**Comment by abrookbanks** [comment]
Great find Alec!
