### ISSUE TITLE
definitions.xml grammar

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#557]
These need an apostrophe:
<string name="macro_sender_name_first" introduced="6.0.0"><![CDATA[Sender's first name.]]></string>
    <string name="macro_sender_name_last" introduced="6.0.0"><![CDATA[Sender's last name.]]></string>

**Comment by abrookbanks** [comment]
They do? I can write code by my English writing skills are horrendous. What should they be?

**Comment by abrookbanks** [comment]
This just made my mind boggle http://www.grammarbook.com/punctuation/apostro.asp

**Comment by Dirty-Butter** [comment]
Currently is says Senders first name - should be Sender's first name. I've had mine changed for a long time, but figured you were through with most of the crucial bug fixes and it was time to mention it. :)

**Comment by abrookbanks** [comment]
Ahh! I though thats how it was and you were saying it was wrong. Silly me. Fixed now. Thanks Rosemary! :)
