### ISSUE TITLE
Question - Something Timed Out???

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#56]
I have 6408 images in the images_index. I installed a test v6site using my current database images, image index, categories, and products. The last 50 or so images were listed in v6 Filemanager, but not associated with the product the way the rest were (not sure how many, as I started out finding images from Product Image Tab one at a time).

Have I hit some kind of timeout, since the number of image_index is so large?? Any suggestions about how to proceed, other than the time consuming job of doing each product manually?

**Comment by abrookbanks** [comment]
"I installed a test v6site using my current database images, image index, categories, and products"

Upgraded or installed and copied over? The latter I have never tried and I would expect problems.

**Comment by abrookbanks** [comment]
I closed this as its more of a support issue than a v6 issue. Happy to discuss via email or fourms etc..

**Comment by Dirty-Butter** [comment]
A little more information from me before you table this completely:

I have 2 installs of 6.0.0b2 - 
1. One is upgraded from Clean 6.0.0b1 - has 2 products with 1 image installed. Storefront and Admin; are OK. Filemanager loads properly.

2. The other started as a copy of my live v5.2.16 database, then upgraded to 6.0.0b1, without dropping tables, THEN just now upgraded from 6.0.0b1 - - - -
 ALL 3K+ Products, 139 Categories/Subcategories, and 6K+ Images (with exception of last 50 or so as mentioned above) show on Storefront and Admin. BUT Filemanager will not load and images do not load on Product Image tab in Admin.

**Comment by Dirty-Butter** [comment]
Filemanager working properly today. Must have been a server issue. Thanks for your time!!!

**Comment by abrookbanks** [comment]
Excellent!! :)
