### ISSUE TITLE
ACP search slider is a pain and slides in too early.. 

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#563]

**Comment by Dirty-Butter** [comment]
Very glad to have this easier to use, but the only way I have found to close it when I don't click on the search results is to refresh the page.

**Comment by abrookbanks** [comment]
Hmm what browser do you use?

**Comment by Dirty-Butter** [comment]
FireFox latest - not an issue unless I do NOT click on a search result, such as not found or just seeing quickly if we have a certain item listed.

**Comment by abrookbanks** [comment]
Ok cool. Lets see how people get on generally. If we need to make more changed we will.. it sounds like we might.
