### ISSUE TITLE
Adding plugin language strings to the $LANG array

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#566]
I've noticed that language strings defined within plugins only appear to be available within the $LANG variable when loading the plugin template files.

For example:
$LANG.my_language_group.my_string would work within the plugin with the language group "my_language_group" defined.

However, if I try to load the same language string from another area of the cart, say the product edit page then the language strings from the plugin are not available.

Ideally all enabled plugins should have their language files added to the global $LANG array and be available in all areas.

**Comment by bhsmither** [comment]
Works for me.

In a hook, I have `$GLOBALS['language']->additional_product_fields['module_title']`. In a template that gets used in the Add/Edit Product panels, I have `{$LANG.additional_product_fields.module_title}`. In a template that is shown as the plugin's settings panel, I have `{$LANG.additional_product_fields.module_title}`. And it all works fine.

**Comment by Noodleyman** [comment]
Hi Brian,

And if you add "{$LANG.additional_product_fields.module_title}" directly to the admin skin or somewhere in the store skin itself without using a hook?

Without specifically loading the language via a hook, it doesn't work.

It could be loaded via controller.admin / controller.index but it shouldn't need to be

**Comment by bhsmither** [comment]
In /classes/module.class.php, line 137, I see code that loads the language strings. But I think module.class.php is used by the admin section, and I haven't confirmed it is called by any other controller or sub-system.

But the hookloader.class.php, in the `load()` function, calls `_plugin_language()`, and that loads the plugin's language file for every hook loaded.

Reading into what you've said above, I get that what you want is to have the language strings from a plugin to be available in areas where the plugin is not having any effect on CubeCart's actions.

**Comment by bhsmither** [comment]
"And if you add `{$LANG.additional_product_fields.module_title}` directly to the admin skin or somewhere in the store skin itself without using a hook?"

My answer: Then what's the point of your plugin?

**Comment by Noodleyman** [comment]
In a perfect world no code edits to any files would ever be needed, yet we don't live in an ideal world. So really the answer is to have the plugin call the controller hook to force it to load language strings to the global language array?

New example of a limit which is bugging me today on the same topic.....

I have a "module.definitions.xml" file in my plugin. Within this I have some language strings defined.

<?xml version="1.0" encoding="UTF-8"?>
<definitions version="1.0">
 <group name="batch_email_process">
  <string name="module_title"><![CDATA[Its a title!]]></string>
  </group>
</definitions>

within the index.tpl file which is called I can access the language strings OK as follows.
{$LANG.batch_email_process.module_title}

However, if I want to access the language strings from, the index.inc.php file I can't because they are not included in the global language array.
$GLOBALS['language']->batch_email_process['module_title'];

if I dump the language array  "batch_email_process" doesn't exist yet. So, this is a limitation because it isn't possible to build strings based on the language file within index.inc.php to output to the module configuration page.

**Comment by bhsmither** [comment]
"However, if I want to access the language strings from, the index.inc.php file I can't because they are not included in the global language array: `$GLOBALS['language']->batch_email_process['module_title'];`"

I have always thought the following observation was particularly wierd in that why wouldn't `$GLOBALS['language']` be available to admin /source/ code files. At the top of every *.index.inc.php file in /admin/sources/ is `global $lang;`. Let's see if/when the plugin language strings show up in that variable.

**Comment by bhsmither** [comment]
But probably not until something loads the plugin, and that doesn't happen until the first hook gets loaded.

**Comment by bhsmither** [comment]
I added this to one of my plugin's /admin/index.inc.php file:
`$GLOBALS['main']->setACPNotify($GLOBALS['language']->additional_product_fields);`
I get the complete list of that module's language strings.

**Comment by bhsmither** [comment]
I just ran across what you may have been describing. Assuming the plugin is enabled with an active hook:
{$LANG.plugin_name.phrase_key} is available to the skins.
$GLOBALS['language']->plugin_name **is** available to admin /source/ files.
$lang['plugin_name]['phrase_key'] **is not** available to admin /source/ files.

**Comment by Noodleyman** [comment]
I do tend to have a way of describing things in a way that only farmers would understand :)

It isn't impossible to get the data, but the way it should be available doesn't always work. This is especially painful if you prebuild HTML which gets output to a smarty variable and uses language strings.

I've worked around it recently by using one of your suggestions and force loading the definitions using: 

$GLOBALS['language']->loadDefinitions('MYDOCUMENTGROUP', CC_ROOT_DIR.CC_DS.'modules'.CC_DS.'plugins'.CC_DS.'MYPLUGINNAME'.CC_DS.'language', 'module.definitions.xml');

It's not ideal as it only looks specifically at the one xml file.

**Comment by Noodleyman** [comment]
Morning Brian,

I ran into this again today, and used your suggested method of 
$GLOBALS['language']->plugin_name

Works well :)

cheers
