### ISSUE TITLE
Latest 6.05 v6-master.zip MAJOR ISSUE

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#567]
I didn't expect you to be working today, but since you are - there are a couple of issues with last night's v6-master that need fixing before 6.0.5 goes public.

content.checkout.confirm.php

It is NOT POSSIBLE to checkout unless the delivery address is provided, and checking the billing and shipping address are the same doesn't accomplish that (because of the nosubmit???).

There are some stray </span>'s

Also, the upgrade script calls for changes to email files that are not possible.

SEE https://forums.cubecart.com/topic/49800-errant-error-message-on-contentcheckoutconfirmphp/

**Comment by Dirty-Butter** [comment]
Also, there needs to be a <--- PLEASE SELECT --> for Countries.

**Comment by abrookbanks** [comment]
Hi Rosemary, the master build isn't always stable. 

Why does there need to be <--- PLEASE SELECT --> for countries? Surely as a required field it should just default to one.

**Comment by abrookbanks** [comment]
.. testing the checkout on the current build seems fine. I'll do more tests prior to release (planned for tomorrow).

**Comment by abrookbanks** [comment]
I've closed this as I'm still working on this area prior to release. I'll perform some AB testing tomorrow.

**Comment by Dirty-Butter** [comment]
I figured you were planning on a release, since you're working lol. We are in the US, so it shows United States in the field. Our customers are usually not web savvy. I've seen this before when they were in another country and couldn't get to checkout because they had not changed the address to their country.

**Comment by Dirty-Butter** [comment]
I upgraded https://dirtybutterestates.com to 6.0.5 with my cosmetic changes and plugins. But I kept the stock CC files, with no edits at all. I STILL cannot get checkout to work unless I create an actual delivery address. I'm thinking IF I swapped and put the Delivery Address section first and the checkbox fixed to indicate the billing is the same as the delivery it might work.

**Comment by abrookbanks** [comment]
Can you reproduce this on the demo store? https://demo.cubecart.com/cc6 it is using 6.0.5.

**Comment by Dirty-Butter** [comment]
It works on the demo - I'm at a loss - the GitHub master worked up through 5/27.

**Comment by Dirty-Butter** [comment]
I tried it with stock Foundation, and it works correctly. So it's something I can eventually find. Sorry to waste your time, but didn't expect cosmetic changes to affect operation. May be in the js section?

**Comment by Dirty-Butter** [comment]
I found it. In the 3.cubecart.validate.js I had added two validation sections, one for the rating and another to require departments in emails. When I used stock file the checkout works properly.

**Comment by abrookbanks** [comment]
Excellent. Well done Rosemary.
