### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#570]
According to:
https://forums.cubecart.com/topic/49767-upgrade-new-installation/#comment-209162
the Readme is not correct.

**Comment by abrookbanks** [comment]
Thanks Brian this was already changed with commit ad045c37e552ba2e58ae1954ef40c39a2aedd334 last week.

**Comment by abrookbanks** [comment]
I'll add some rewrite rules to the helpdesk.
