### ISSUE TITLE
Upgrade Smarty

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#571]
As above v6.0.5 currently uses 3.1.15

**Comment by abrookbanks** [comment]
This has been rolled back due to admin block. Maybe this version of Smarty is buggy.

**Comment by Dirty-Butter** [comment]
What version did you revert it to? Is it OK to get the version from the smarty github download?

**Comment by abrookbanks** [comment]
Thats the one I used and all hell broke loose. The PHP it generated was corrupt with parse errors. This is a very low priority issue. The current version is very stable and recent.

**Comment by abrookbanks** [comment]
Just striving for perfection... :)

**Comment by Dirty-Butter** [comment]
Striving is always worthwhile! :)

**Comment by abrookbanks** [comment]
Sadly the love of beer gets in the way or striving for a six pack (or achieving it actually). Haha

**Comment by abrookbanks** [comment]
This issue persists with smarty 3.1.2. Issue raised. 

https://github.com/smarty-php/smarty/issues/60

**Comment by abrookbanks** [comment]
Fixed thanks to @uwetews
