### ISSUE TITLE
BUG: Tracking number missing in order history

### ISSUE THREAD

**Issue by KSD2** [cubecart/v6#572]
In CC5 a customer could open his order history and check the tracking number of his order.
In CC6 the tracking number is missing there.

Instead of this, there is a link. This link must be entered manually while entering delivery data.
None of our delivery partners has such kind of link (with parameter) for us.

With 2000 deliveries a month you can imagine, how much work this is.

The tracking number MUST be visible on the order history page.

This is a BUG.

We already submittet a ticket for this, but no help.

**Comment by abrookbanks** [comment]
Thanks for this. This is much improved now but is skin specific so code changes need to be made to the content.receipt.php file. 

# With URL
![with url](https://cloud.githubusercontent.com/assets/4520803/8233607/176635fe-15cf-11e5-8ef5-c79bd9dafdac.png)

# With Tracking Code
![with tracking code](https://cloud.githubusercontent.com/assets/4520803/8233613/1eb5f042-15cf-11e5-9f34-2aa29741fe33.png)
