### ISSUE TITLE
Small view top nav icons badly aligned

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#573]
![image](https://cloud.githubusercontent.com/assets/4520803/7922068/abc4d6e6-08a1-11e5-8a15-35b5ac2e1db9.jpg)

**Comment by Dirty-Butter** [comment]
This worked for me on main.php

<div class="small-12 medium-8 large-6 columns nav-boxes"> {* DIV CLASS  NAV BOXES *}
                  <div class="row"> {* ROW 1 SMALL *}
<div class="show-for-small-only text-center">
  <a href="#" class="left-off-canvas-toggle button white tiny"><i class="fa fa-bars fa-2x"></i></a>
  <a href="#" class="button white tiny show-small-search"><i class="fa fa-search fa-2x"></i></a>
  <a href="#" class="right-off-canvas-toggle button white "><i class="fa fa-shopping-cart fa-2x"></i></a>
  <div id="smallt-basket-detail" class="hide panel radius small-basket-detail-container js_fadeOut"><i class="fa fa-check"></i> Added to Basket</div>
</div>
<div class="right text show-for-medium-up">{include file='templates/box.basket.php'}</div>
		 {include file='templates/box.currency.php'}
		 {include file='templates/box.language.php'}
		 {include file='templates/box.session.php'}
</div> {* END ROW 1 SMALL *}
<div class="row hide" id="small-search"> {* HIDDEN SEARCH BOX THAT SHOWS AFTER ICON CLICKED ON SMALL  *}
			<div class="medium-5 columns">
{include file='templates/box.search.php'}</div>
</div> {* END HIDDEN SEARCH *}

**Comment by abrookbanks** [comment]
Mini basket min-width moved to viewport of medium and above.
