### ISSUE TITLE
Admin Order Creation with Digital Downloads

### ISSUE THREAD

**Issue by svrabel** [cubecart/v6#577]
Creating an order with only digital products from Admin does not generate an email with links or update the customer's digital downloads. 

This link below discussed a fix for CC 5.2.2, but it doesn't appear to be integrated into CC6 yet.
https://forums.cubecart.com/topic/47668-admin-created-orders-now-with-downloads/

**Comment by abrookbanks** [comment]
Thanks for pointing me to this. I thought this functionality existed already! It didn't. The commit above works well from my testing but only if a customer exists already.
