### ISSUE TITLE
Required value missing on Company Address line

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#581]
content.checkout.confirm.php
    <div class="small-12 large-8 columns"><label for="addr_line1" class="show-for-medium-up">{$LANG.address.line1}</label><input type="text" name="billing[line1]" id="addr_line1" MISSING  value="{$BILLING.line1}

**Comment by Dirty-Butter** [comment]
How do I get ALL the code I pasted to show here??

**Comment by abrookbanks** [comment]
Have a look at https://guides.github.com/features/mastering-markdown/

Screenshot.. 
![screen shot 2015-06-03 at 16 58 27](https://cloud.githubusercontent.com/assets/4520803/7964819/ccc68dc8-0a11-11e5-9127-f710f9f6f8d5.png)

**Comment by abrookbanks** [comment]
Line 111 of content.checkout.confirm.php looks ok to me:

```<div class="small-12 large-8 columns"><label for="addr_line1" class="show-for-medium-up">{$LANG.address.line1}</label><input type="text" name="billing[line1]" id="addr_line1"   value="{$BILLING.line1}" placeholder="{if $ADDRESS_LOOKUP}{$LANG.address.address_lookup}{else}{$LANG.address.line1} {$LANG.form.required}{/if}" autocomplete="off" autocorrect="off" class="address_lookup"></div>```

**Comment by Dirty-Butter** [comment]
I have
````
<div class="small-12 large-8 columns"><label for="addr_line1" class="show-for-medium-up">{$LANG.address.line1}</label><input type="text" name="billing[line1]" id="addr_line1"  required value="{$BILLING.line1}" placeholder="{if $ADDRESS_LOOKUP}{$LANG.address.address_lookup}{else}{$LANG.address.line1} {$LANG.form.required}{/if}" autocomplete="off" autocorrect="off" class="address_lookup"></div>
````
We had a customer order go through without a street address when the "required" in front of value="{$BILLING.line1} was not there.

**Comment by abrookbanks** [comment]
Thats strange as that looks ok. There is server side and client side validation so its double weird!
