### ISSUE TITLE
Redirect loop for 404

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#582]

**Comment by Dirty-Butter** [comment]
I had to delete my .htaccess file and let CC create another one when using 06/03 v6-master. The Store front loaded with the .htaccess file the new code tried to "fix", but Admin would caused a loop.
Was that expected?

I did add back in this section before Rewrite Base /:
`````
RewriteCond %{HTTPS} off

RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteCond %{REQUEST_URI} !=/favicon.ico
  RewriteRule ^(.*)\.html?$ index.php?seo_path=$1 [L,QSA]
`````

**Comment by abrookbanks** [comment]
Theres been a bit of work here over the last 24 hours with some commits in the last hour. I think its stable as of the time of writing this.

**Comment by Dirty-Butter** [comment]
I tried the latest v6-master, but my old .htaccess file still causes the loop. How can I send you some files?

**Comment by abrookbanks** [comment]
I've tried this build on a couple of store upgrades today. Seems ok. I'd upload the latest /classes/* files too as there are relevent code changes in there.

**Comment by Dirty-Butter** [comment]
I already had the latest changes to cubecart.class.php. Here are the parts that don't show up in the one CC created, other than the redirect to non www:
#301 Redirect Old File
Redirect 301 https://dirtybutterestates.com/index.php?_a=error&doc_id=13 https://dirtybutterestates.com/page-not-found.html
Redirect 301 https://dirtybutter.com/1969-chevrolet-caprice/photo-gallery-1969-chevrolet-caprice/  https://dirtybutter.com/1969-chevrolet-caprice/1969-chevrolet-caprice-photos/

Options -Indexes
ErrorDocument 404 /page-not-found.html
ErrorDocument 400 /400-bad-request.html
ErrorDocument 401 /401-restricted-page.html
ErrorDocument 500 /500-server-problem.html
ErrorDocument 302 /302-moved-temporarily.html
# Use PHPcur as default
AddHandler application/x-httpd-phpcur .php
<IfModule mod_suphp.c>
    suPHP_ConfigPath /opt/phpcur/lib
</IfModule>
<Files 403.shtml>
order allow,deny
allow from all
</Files>
