### ISSUE TITLE
Stock Reporting

### ISSUE THREAD

**Issue by The-Model-Tree-Shop** [cubecart/v6#585]
I am having issues with the stock in CC6 where if I use the global stock setting my products appear to be out of stock (See pic1), if I set individual levels then only the first item reports stock and always the same stock regardless of the product (see lines 1&2 of images 2&3). The customer can also buy as much as he likes despite my settings set to do not allow out of stock purchases... HELP Please!

![stock01](https://cloud.githubusercontent.com/assets/12745472/7981674/6e21587e-0aa8-11e5-8142-bd1c6076f878.png)
![stock02](https://cloud.githubusercontent.com/assets/12745472/7981676/6e31849c-0aa8-11e5-905e-27b78a65dce2.png)
![stock03](https://cloud.githubusercontent.com/assets/12745472/7981675/6e2d35a4-0aa8-11e5-933f-5e5d84bc8a7e.png)

**Comment by abrookbanks** [comment]
I'm sorry but I do not now how to reproduce this or what action to take. Please send a tech support ticket with steps to reproduce.
