### ISSUE TITLE
6.0.5 SQL Upgrade Fails on `CubeCart_email_content`

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#587]
The SQL queries to update content_html is bad.

**Comment by Dirty-Butter** [comment]
First UPDATE line with 
````
{$DATA.ship_method|replace:&#39;_&#39;:&#39; &#39;}
````
 in it shows zero changes and this error message:
File: [maintenance.sql.inc.php] Line: [24] "UPDATE `CubeCart_email_content` SET `content_html` = replace(`content_html`, '{$DATA.ship_method|replace:'_':' '}', '{$DATA.ship_method}'); " - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '_':' '}', '{$DATA.ship_method}')' at line 1

I only have USPS shipping - maybe it did not apply to me?
Second Update query has one successful completion.

**Comment by abrookbanks** [comment]
Empty rows just means that no changes needed to be made. :) Happy days.
