### ISSUE TITLE
Product Codes

### ISSUE THREAD

**Issue by The-Model-Tree-Shop** [cubecart/v6#589]
My products within each catagory all get overwritten with the same product code and stock level for all the products within that category - this leads to inaccurate stock levels allowing customers to overorder or not be able to order items because the system is incorrectly reporting zero stock.

![stock04](https://cloud.githubusercontent.com/assets/12745472/8003635/37be9a98-0b71-11e5-8728-ca3bb080d95f.png)
![stock05](https://cloud.githubusercontent.com/assets/12745472/8003636/37c1957c-0b71-11e5-9a16-7d5c12f7674a.png)

**Comment by abrookbanks** [comment]
The commit above fixes this BUT.. it's can't fix any damage done. That's the rubbish news.

**Comment by havenswift-hosting** [comment]
Was this issue caused by changes in 6.0.5 ?  Do you know when 6.0.6 is likely to be released ?

**Comment by abrookbanks** [comment]
Yes. There was the need to specify an option_matrix update to specify the product id. A silly mistake put the product id into the update data instead of the where data!

We can avoid stupid things like this with a QA team. Hopefully as we grow we can afford to do this.
