### ISSUE TITLE
Close </span> in skins/foundation/templates/element.breadcrumb.php

### ISSUE THREAD

**Issue by jasehead** [cubecart/v6#590]
Change line 15 from this:
      ```<li><a href="{$STORE_URL}"><span class="show-for-small-only"><i class="fa fa-home"></i></span><span class="show-for-medium-up">{$LANG.common.home}</a></li>```

to this:
      ```<li><a href="{$STORE_URL}"><span class="show-for-small-only"><i class="fa fa-home"></i></span><span class="show-for-medium-up">{$LANG.common.home}</span></a></li>```

**Comment by jasehead** [comment]
Sorry - html didn't work.  The issue is that there is a span close tag missing towards the end of line 15 - it should be added between $LANG.common.home and the anchor close tag.

**Comment by Dirty-Butter** [comment]
I just learned how to show code here today!
Put a row of ticks before and after your code.
````
code
````
See the Markdown supported link right top of this comment box.

**Comment by abrookbanks** [comment]
Thank you.

**Comment by bhsmither** [comment]
From above: The close-span tag should be added between `{$LANG.common.home}` and the close-anchor tag.

That's not where it ended up in CC606. There are "nesting problems".

**Comment by Dirty-Butter** [comment]
Is this correct?
````
  <li><span class="show-for-small-only"><a href="{$STORE_URL}"><i class="fa fa-home"></i></a></span><span class="show-for-medium-up"><a href="{$STORE_URL}">{$LANG.common.home}</a></span></li>
````

**Comment by bhsmither** [comment]
That will also work. It is properly nested.
