### ISSUE TITLE
Duplicate class in  skins/foundation/templates/content.recaptcha.php

### ISSUE THREAD

**Issue by jasehead** [cubecart/v6#591]
Change line:
    ```<div class="recaptcha_only_if_incorrect_sol" class="error">Incorrect please try again</div>```

to this:
   ``` <div class="recaptcha_only_if_incorrect_sol error">Incorrect please try again</div>```

**Comment by jasehead** [comment]
Try again.  Change
div class="recaptcha_only_if_incorrect_sol" class="error"
to
div class="recaptcha_only_if_incorrect_sol error"

**Comment by abrookbanks** [comment]
Thanks I fixed this. Be sure to read up on GitHub Markdown.. https://guides.github.com/features/mastering-markdown/
