### ISSUE TITLE
Notify admin via email when order is cancelled

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#592]
As per forum topic https://forums.cubecart.com/topic/49838-cancelled-orders/

**Comment by Noodleyman** [comment]
Where is this on the roamap, should be quite a simple/quick thing to add?

Thanks,

**Comment by havenswift-hosting** [comment]
Many people have resorted to removing the cancel order link which contravenes distance selling regulations and there are many on the forums plus quite a few of our own customers that are getting caught out.  There is a simple solution to sending an email to admin when an order is cancelled
