### ISSUE TITLE
6.0.5 http:// on SSL store Sitemap 

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#597]
See https://forums.cubecart.com/topic/49856-ccv605-sitemap-issue-with-http-url/
I went from over 3000 indexed on Google to 41 indexed the day I upgraded to 6.0.5. I checked yesterday on Google, trying to help another forum member, and saw I had major problems.

**Comment by QuotesUK** [comment]
Yes, I spotted this today. The site is configured as HTTPS but the sitemap that is generated uses the HTTP prefix for all the URLs.

If anyone is affected by this a quick workaround:
1/ download the sitemap.xml.gz
2/ unpack the file to sitemap.xml
3/ search and replace the http:// to https://
4/ upload the sitemap.xml file, tell Google and Bing to use this file instead

Comments:
a/ make sure you leave the 2nd line as http://www.sitemaps.org/schemas/sitemap/0.9, without HTTPS
b/ remove the URL for certificates if you don't have any (avoids a redirect)
c/ edit your homepage URL to remove index.php

By the way, Dirty-Butter, Google says they use sitemaps as a hint, not a directive, so having URLs missing from your sitemap is not going to get your pages de-indexed. However webmaster tools doesn't seem to count them unless the protocol is matching. Your pages are probably still indexed if you do a normal web search.

**Comment by Dirty-Butter** [comment]
Bsmither said to delete the standard url from ssl tab each time you make settings changes.

**Comment by QuotesUK** [comment]
Thank you. He is right (as usual) but maybe some of the canonical redirecting is sacrificed as a result of this... the https non-www url is not redirecting to the preferred https://www ...I'm reluctant to investigate further because it is a live site so can't say for sure.

**Comment by abrookbanks** [comment]
Thanks both.

**Comment by Dirty-Butter** [comment]
This is still an issue for me, but I wanted to wait for 6.0.6 to see if it resolved itself. If I let CC set the standard url in SSL tab, I get http://. With the new code change in 6.0.6 that gives me the homepage in the sitemap as https:// as it should, but the product url's are still http:// in the sitemap. The only way I can get a correct sitemap without editing the created one is to delete the standard url - then let CC replace it with https:// on Save.

![httpsitemapissue](https://cloud.githubusercontent.com/assets/6146505/8315714/271a20f4-19b8-11e5-9c16-20df16f06f7f.jpg)
