### ISSUE TITLE
Cannot Search For Product Code

### ISSUE THREAD

**Issue by Dyoung0606** [cubecart/v6#599]
In our CubeCart store we have a product with code "e-ster-6" (without the quotes).
On our main page, doing a search for "e-ster-6" (again, without the quotes) yields no results.
In previous versions of CubeCart (5.0.SomethingOrOther), this search would work without incident (that is, would show products with the product code being searched).

This is not a duplicate of issue #487 since that issue is specifically regarding subsets of product codes.
The discussion on https://forums.cubecart.com/topic/46555-is-there-any-way-to-improve-customer-search-experience/ does not offer any notes on how to fix. Someone did mention in that discussion that hyphens in product codes are problematic, as of this writing nothing in that discussion describes how to fix.

Please fix CubeCart so it once again includes product_code in the search results.

**Comment by Dyoung0606** [comment]
It's worth mentioning that this issue is present in the outward facing store only.  On the admin screen (whatever.com/admin) searching for a product code works without incident.

**Comment by Dirty-Butter** [comment]
The reason i did not address the hyphen issue in that thread is my product codes were for my use only. I just did a find replace query to change the hyphen to an x.

**Comment by Dyoung0606** [comment]
So, what I'm hearing is, the inability for customers to search by product code is still an outstanding issue?

**Comment by Dirty-Butter** [comment]
Well, I just tried changing one of my product codes back to having a hyphen, and search on the store worked. I use Bsmither's changes to Search that you linked to in your OP.

**Comment by Dirty-Butter** [comment]
It occurred to me that you may be talking about having a hyphenated term, such as a product code no., in the Title of an item, rather than the Product Code found in its own field. I think there's code now that prevents 2 hyphens in a row from being created for urls.

**Comment by Dyoung0606** [comment]
Well, specifically here's my problem.

Browse on over to http://www.youngdesignsjewelry.com
In the search box, type "n-stone-27" (without the quotes).  No results come up.
Now browse to http://www.youngdesignsjewelry.com/store/orange-mop-riverstone-necklace.html
Note that item has product code "n-stone-27".
The search failed to find the product, even using an exact search on the product code.

**Comment by Dirty-Butter** [comment]
Have you tried using the search code Bsmither created for my store? Your kind of search works on mine.

 

Rosemary

 

 <https://dirtybutter.com/plushcatalog> Dirty Butter Plush Animal Shoppe

 

“Whosoever therefore shall humble himself as this little child, the same is greatest in the kingom of heaven.”

 

Matthew 18:4 KJV

**Comment by Dyoung0606** [comment]
I did make that change and there was no difference in the search results.  :(

**Comment by abrookbanks** [comment]
The fallback to "LIKE" search from "FULLTEXT" wasn't working right. This is resolved now. Thanks.
