### ISSUE TITLE
6.0.0b2 Documents Issue

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#60]
Install of US English went beautifully! Store Settings provided US as language choice automatically.

But Documents still does not offer US as a choice. In last version I was able to change the title of the homepage from Welcome to Cubecart to something else, save, and then US showed as a choice.

But now I "saved" the new document title, but original title remained, and US still is not a language option.

Since Setup provides a drop down list of currencies, why not provide a dropdown list of languages, so the install is in the correct language?

**Comment by Dirty-Butter** [comment]
Working now. Looks like this was a FireFox cache problem, not a CC issue. Sorry.
But I still wonder why it's not possible to install in the native language.

**Comment by abrookbanks** [comment]
Pleased it works. This is one of those big debatable ones. We have about as many US users as UK. In the UK pretty much all software defaults to en-US so thought as we are a GB company it should default to GB. Maybe it can pluck the chosen language on install dynamically. We obviously want to keep everyone happy... Upgrading from v5 to v6 will keep en-US. 

Thinking cap is on.

**Comment by abrookbanks** [comment]
I wonder if it should ship with the "main languages"... 

en-GB
en-US
es-ES
fr-FR
dk-DK

Any extras like Turkish or Hebrew can be installed later. The idea is to keep it as lightweight as possible. Most store owners will only want one master language.

**Comment by Dirty-Butter** [comment]
v5 gave the choice on the install of UK and US

**Comment by havenswift-hosting** [comment]
Keeping v6 lightweight has got to be better rather than shipping with all languages so if you can ask what main language they want to use as part of the installation (in dropdown) and then if not en-GB which is the default then download that language file at that point

**Comment by abrookbanks** [comment]
I think this has been resolved for new installs and upgrades so long as the upgrade instructions are followed and the old v5 language packs still exist. 

From this I have opened issue #90 as a future enhancement.
