### ISSUE TITLE
Enable multiple email templates

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#600]
It is possible to create multiple email templates but you can only enable one of them at a time.  You should be able to create multiple different ones, enable as many as you want and then choose which one you use for each newsletter.

It allows you to choose a disabled email template for a newsletter (maybe shouldnt appear in the dropdown if disabled) and then if you send a newsletter like that it doesnt use the template settings

 It would also be great to be able to define multiple email templates and then assign different templates to different emails rather than having to use the default emails one

**Comment by bhsmither** [comment]
Just FYI -- I have been working (as much and as often as I can) to greatly enhance the email template system.

**Comment by havenswift-hosting** [comment]
The OP just covers a couple of bugs which need fixing ASAP but there is a lot that could be done with the email template system to improve / enhance it so is your work going to be a commercial plugin which you will make available ?

**Comment by abrookbanks** [comment]
Hi Brian, do you think this is something you are keen to contribute? Should I hold back looking at this?
