### ISSUE TITLE
Hide Coupon Field

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#601]
Request:
If there are no non-expired coupons, and no gift certificates with a balance, then do not show the "Enter Coupon" HTML section at checkout (maybe an admin Store Setting?).

**Comment by abrookbanks** [comment]
This is a debatable one... you could argue;

1. It may be nice for the customer to know that sometimes we do have discount codes
2. It may prompt to start a live chat to ask for a discount.

Maybe other reasons. :)
