### ISSUE TITLE
EU Country List

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#604]
In /setup/db/install/data.sql, the list of country ISOs for setting `eu`='1' has errors:
UK has an ISO of GB
GR (Greece) is missing
EL needs to be BE for Belgium

**Comment by bhsmither** [comment]
Also in the overall list of countries, it seems Angola (AO, iso3???) and Armenia (AM) are missing.

**Comment by bhsmither** [comment]
Maybe "Nagorno-Karabakh Republic" ?

**Comment by abrookbanks** [comment]
It's confusing because EL is the VAT prefix for Greece. It looks like I used that instead of the correct 2 digit ISO. The nice thing is MySQL seem to fail softly on updates with an `IN` array so some of them got updated correctly. This is fixed now. Thanks.
