### ISSUE TITLE
reCaptcha with Foundation gives mixed content / SSL issues

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#605]
If using Foundation with Forced SSL and the old reCaptcha then navigating to the checkout (as a guest) gives the following mixed content problems.  The protocol should be removed so that it wirks in either case.

Mixed Content: The page at 'https://www.domain.co.uk/index.php?_a=confirm' was loaded over HTTPS, but requested an insecure script 'http://www.google.com/recaptcha/api/reload?c=03AHJ_Vuu1tTayAuIMH7vzxjLSYwMI…dzvYlSks5RtfarloX-cY2MHayGUuh7nuWRU6n_QfXLqBRIsxBb6m8iyqy8eo9zw9SsM-MpmeYg'. This content should also be served over HTTPS.
index.php:1 Mixed Content: The page at 'https://www.domain.co.uk/index.php?_a=confirm' was loaded over HTTPS, but requested an insecure image 'http://www.google.com/recaptcha/api/image?c=03AHJ_Vut86UR3i82tKkBsKPvuFcEbS…dzvYlSks5RtfarloX-cY2MHayGUuh7nuWRU6n_QfXLqBRIsxBb6m8iyqy8eixzw9Sp4Jr8iBhQ'. This content should also be served over HTTPS

**Comment by abrookbanks** [comment]
Thanks Ian
