### ISSUE TITLE
Hiding categories with no products

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#607]
An enhancement is required to the way categories are hidden if they contain no products.

With "Display empty categories" set to "No":

Adding a new empty category called "Top". This does not get displayed as expected

Add a "Mid" category as a child to "Top". Category top is now displayed in the store, but "mid" is not.

Ideally this should hide all parent categories if all child categories are empty rather than showing the parent simply because it has a child category.

**Comment by havenswift-hosting** [comment]
Agreed - if all sub-categories are empty then categories above them should also be hidden

**Comment by abrookbanks** [comment]
This is already a very heavy area of CubeCart. I've put this as a feature request as I think it needs a complete rewrite. Adding this in is going to cripple large stores.

**Comment by Noodleyman** [comment]
quick way to fix this is to keep a cached product count against the category record which is updated on product save in the admin area. Can also be done using a simple SQL query with very little overhead. total products would be the better solution as the info can be used elsewhere in the site. Is there an ETA on this feature?

**Comment by abrookbanks** [comment]
Deleted feature requests..

**Comment by abrookbanks** [comment]
> quick way to fix this is to keep a cached product count against the category record which is updated on product save in the admin area. Can also be done using a simple SQL query with very little overhead. total products would be the better solution as the info can be used elsewhere in the site. Is there an ETA on this feature?

It's not that simple at all when you bring in product availability, stock at top level/product option etc...

**Comment by abrookbanks** [comment]
Sorry but I've given up on this one.

**Comment by Noodleyman** [comment]
it's not that bad... :)

What was the complexity with product availability?

**Comment by abrookbanks** [comment]
Maybe I can delegate this one to you. :)

**Comment by Noodleyman** [comment]
I already solved it in the past using a single SQL query, but assumed I overlooked something to do with availability (which wasn't relevent for the site I fixed it on). What are the complexities?

**Comment by abrookbanks** [comment]
> I already solved it in the past using a single SQL query, but assumed I overlooked something to do with availability (which wasn't relevent for the site I fixed it on). What are the complexities? will take a look when I get a moment

I can't remember but its a lot more complex that that. Option matrix stock, availability setting and more probably.

**Comment by Noodleyman** [comment]
I've solved most of these in modules over the past few months, if you can outline what the complex parts we're and where you got with it then I can probably just straighten it out for you.  The Ebay module does most of this when making choices about stock levels, it includes matrix rules / product rules, but also takes it to another level as it has ebay specific stocking rules as well.
