### ISSUE TITLE
Unknown SEF 302's to Same

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#612]
(More experiments necessary)
If I make a page request to:
www.example.com/linking-policy.html
but I do not have a document by that name, I get:
HTTP/1.1 302 Found
Location: /linking-policy.html

My browser eventually tells me that the page is not redirecting properly.

**Comment by bhsmither** [comment]
This happens on CC602 as well.

**Comment by bhsmither** [comment]
Experiments show that in SEO->getItem():
```
} else {
  // Retry once incase emties have been cached
  if(!$GLOBALS['session']->has($path, 'seo_retry')) {
    $GLOBALS['cache']->clear();
    $GLOBALS['session']->set($path, '1', 'seo');
    httpredir(CC_ROOT_REL.$path);
  } else {
    httpredir('index.php');
  }
}
```
`set($path, '1', 'seo');` should be `set($path, '1', 'seo_retry');`

**Comment by abrookbanks** [comment]
Thanks Brian this issue was fixed already here: https://github.com/cubecart/v6/commit/44d8abb7f92ddc799b173693267138221a2d15ea
