### ISSUE TITLE
Customer order count showing at zero

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#613]
It seems that in some circumstances the customer order count is showing as zero when they do have order. Error log shows errors on trying to insert duplicate customer data.

**Comment by abrookbanks** [comment]
Internal ticket 102477.

**Comment by havenswift-hosting** [comment]
Would be great to get this one fixed and included if possible in 6.0.7 as have a couple of customers with this

**Comment by abrookbanks** [comment]
Really struggled to reproduce this one even though I've seen the issue. I'll take another look.

**Comment by abrookbanks** [comment]
I just can't reproduce this now. Closing until I see it again somewhere.
