### ISSUE TITLE
DISABLED Certificates in Sitemap

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#614]
seo.class.php should have an IF for the Certificates code, so it does not show in the sitemap if it is disabled in Store Settings. For now I just have it commented out. 

Google sees the a= certificates sitemap link as a duplicate metadata to the homepage when it's in sitemap.xml, but not in use in the store.
````
	/*	# Gift Certificates
		$this->_sitemap_link(array('url' => $store_url.'/index.php?_a=certificates'));
 */
````

**Comment by abrookbanks** [comment]
Same for sale items. Fixed that too.
