### ISSUE TITLE
No make payment link for admin created pending orders

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#616]
If a store admin creates an order via admin and sets the status to pending, there is no make payment link displayed for the customer on the view orders page.

The simple fix is to replace this:
$order['make_payment'] = ($order['status'] == 1 && !empty($order['basket'])) ? true : false;
with this:
$order['make_payment'] = ($order['status'] == 1) ? true : false;
in the '/classes/cubecart.class.php' file.

A better fix might involve populating '$order['basket']' when creating the order via admin, as if the customer had created the order themselves.

**Comment by abrookbanks** [comment]
For me that code change just showed an empty basket and didn't work. I've put this down as a feature request.

**Comment by SemperFiWS** [comment]
Yeah I noticed that myself after testing it.
This I assume is because there is no basket contents at that point for the customer.
So my better fix looks like it is what is required to fix the problem properly.

**Comment by Dirty-Butter** [comment]
Would the "better fix" mean that admin created orders would supply the correct shipping handling and tax amounts?

**Comment by Noodleyman** [comment]
This should be quite a simple thing to address, is there an ETA for this on the roadmap?

**Comment by abrookbanks** [comment]
> This should be quite a simple thing to address

It's really not as the purchase link rebuilds the order from the saved basket. There is no saved basket for ACP generated orders.

**Comment by Noodleyman** [comment]
for ACP orders, re-populate the checkout page with the order items, and send the customer back to the checkout to select a payment method?

**Comment by abrookbanks** [comment]
Yeah it's doable for sure.
