### ISSUE TITLE
Duplicate Call Undoes Hook

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#618]
In `Order->orderStatus()`, calls are made to `getSummary()` and `_getInventory()`. Then there is a hook.

The hook could add more things to the Summary details and/or Inventory details.

Later in `case ORDER_PROCESS`, another call is made to `_getInventory()` cancelling any work done by the hook.

Same for `case ORDER_COMPLETE`.

Suggest we assume the Inventory Details will remain **useable** throughout the class as desired by the intent of the hook.

**Comment by abrookbanks** [comment]
I'm in fear of creating bugs. ARe you suggesting the extra calls to _getInventory are removed? In theory they shouldn't be needed. I'm not sure why they are there.
