### ISSUE TITLE
Add cost price to order inventory

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#619]
It would be good to add this as standard in V6.

When an order is placed the cost price should be captured at the order inventory level. This makes it easier to review what the cost of your item was at the time it was sold.

**Comment by havenswift-hosting** [comment]
I completely agree as cost prices can change day to day and to be able to record this would be great

**Comment by bobdonkey** [comment]
Yes this would be a nice feature.

**Comment by Noodleyman** [comment]
this is a very very simple, quick thing to add. is there an ETA on this being added?
