### ISSUE TITLE
Cannot add items to basket

### ISSUE THREAD

**Issue by Octaneflyer** [cubecart/v6#63]
Hi

I have upgraded to CubeCart-6.0.0b2.zip and cannot add anything to the basket even with the default foundation skin or the Vector Fusion skin I normal use.  when debugging I have many undefined index errors.  Possibly this is something I am missing but can you please advise?

Thanks
Mark

**Comment by abrookbanks** [comment]
Hmmm.. have you cleared your browser cookies? If the store is accessible via a domain and you would like us to take a direct look. Maybe send FTP access via our secure helpdesk. I would be more than happy to take a look. https://support.cubecart.com/index.php?/Tickets/Submit

**Comment by Octaneflyer** [comment]
Hi, yes cleared all cache and cookies... I will send a support ticket now.. thanks

**Comment by abrookbanks** [comment]
Thank you!

**Comment by Octaneflyer** [comment]
After further testing seems to be the Fusion skin that is not woking correctly, some items are not displayed and add to basket doesn't work.  I will switch to the foundation skin for the moment and wait for the issues to be resolved by ShopDev.  Sorry to have troubled you.

**Comment by abrookbanks** [comment]
OK thanks so much for the feedback. ShopDev is unlikely to get back to you I'm afraid. We have had many accounts that support goes unanswered. Best of luck.
