### ISSUE TITLE
Set order to complete, text area product option values disappear

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#630]
Checkout:
![textarea-options-bug-01-checkout](https://cloud.githubusercontent.com/assets/6945093/8292505/0c8c2a4e-18fe-11e5-987d-cfb23f52c01e.png)

Pending:
![textarea-options-bug-02-pending](https://cloud.githubusercontent.com/assets/6945093/8292512/13bd89fc-18fe-11e5-8b1d-9f3281e4161b.png)

Processing:
![textarea-options-bug-03-processing](https://cloud.githubusercontent.com/assets/6945093/8292516/1ad5777c-18fe-11e5-9ea0-2a1ee46e9fdd.png)

Complete
![textarea-options-bug-04-complete](https://cloud.githubusercontent.com/assets/6945093/8292521/211628ac-18fe-11e5-9157-322efd5e6c6a.png)

**Comment by SemperFiWS** [comment]
Both text input and drop down values are not affected.

**Comment by abrookbanks** [comment]
I can't reproduce this on the latest build. This issue has been fixed already.

**Comment by abrookbanks** [comment]
I think this can be closed. I hope. :pray:

**Comment by fourhands** [comment]
Just upgraded to 6.0.8 and experiencing the same problems with the text input boxes when changing the order status. As soon as a change is implemented I can no longer see what the customer ordered. Hope there is a fix for this.

**Comment by abrookbanks** [comment]
I just opened https://github.com/cubecart/v6/issues/929
