### ISSUE TITLE
Upgrade to  6.05 doesn't change Order status from Pending to processing with Paypal express

### ISSUE THREAD

**Issue by tonyhugs** [cubecart/v6#632]
All orders processed with paypal express via "all in one shipping"  no longer update the status to Processing as they have always done  in V5 ..

It would be nice if there was a link back to Paypal to update the status there to "sent" , just as  does with Ebay ...

**Comment by abrookbanks** [comment]
Please can you take a look at this https://support.cubecart.com/Knowledgebase/Article/View/213/41/orders-placed-with-paypal-are-not-automatically-changing-status-to-processing and sent a support ticket if you still require assistance.

**Comment by abrookbanks** [comment]
I'm looking into this one..

**Comment by abrookbanks** [comment]
No issues have been found please can you check the IPN history and send a tech support ticket.

**Comment by abrookbanks** [comment]
Checking again..

**Comment by abrookbanks** [comment]
OK I think the order status was cached when it shouldn't have been. Commit above should resolve. It worked for me. 

You can test it in sandbox mode here: http://brooky.com/ipn/
