### ISSUE TITLE
All in one shipping

### ISSUE THREAD

**Issue by hebcat** [cubecart/v6#634]
"All in one shipping" does not display the list of countries, when creating a new zone.

![all-in-one-shipping-cc6](https://cloud.githubusercontent.com/assets/13016191/8304823/50ddebc6-19a1-11e5-9ca9-2e50bd55538e.jpg)

Working with version 1.0.6
Onto CC 6.0.0b1 
Tried in both Firefox 38.0.5, and Chrome 43.0.2357.130 (same issue)

**Comment by havenswift-hosting** [comment]
6.0.0b1 - seriously ?  Please try upgrading to latest 6.0.6 and test again.  This shipping module is used on hundreds and hundreds of stores with no issues - you will however have hundreds of issues running the initial beta release of V6

**Comment by hebcat** [comment]
It's a store whose development has been put on hold for a couple of months. I will try upgrading.

**Comment by abrookbanks** [comment]
Please upgrade both CubeCart and the All in One Shipping extension to fix this.

**Comment by hebcat** [comment]
Thanks, and yes the upgrade did the trick. I hadn't realised I'd been working with a beta version.
