### ISSUE TITLE
Setup directory not always deleted

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#635]
When doing an upgrade from within admin, sometimes the setup directory is deleted and other times it isnt

Have seen the following recorded in the error_log when it isnt deleted

[23-Jun-2015 12:47:41 UTC] PHP Warning:  fread() [<a href='http://docs.php.net/manual/en/function.fread.php'>function.fread.php</a>]: Length parameter must be greater than 0 in /home/XXXXXXXX/public_html/admin/sources/maintenance.index.inc.php on line 237

**Comment by abrookbanks** [comment]
The above fix will stop the Warning in your report. I think however the recursive delete of the setup folder may fail if a php error log file gets written in it. Apache may not have permission to delete it and as a result this will fail. 

The best fix is to make the setup process code beautiful and not log any errors. This is ongoing.

**Comment by abrookbanks** [comment]
.. a better solution may be to keep the setup folder and password protect it if a working store is found.
