### ISSUE TITLE
Compiled Template Crashing

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#638]
A change in template coding may be causing some issues with getting to the Dashboard. I don't have all the particulars.

See:
https://forums.cubecart.com/topic/49960-no-access-to-dashboard-after-upgrade/

I posted a question on Smarty's Bugs forum:
http://www.smarty.net/forums/viewtopic.php?t=25579

**Comment by bhsmither** [comment]
Here is my best guess as to what happened:
CC605 uses Smarty 3.1.15 and has this code:
`{foreach from=$CUSTOM_QUICK_TASKS item=$task}`

CC606 uses Smarty 3.1.25 and uses this code:
`{foreach from=$CUSTOM_QUICK_TASKS key=k item=task}`

The upgrade process is **supposed** to delete all compiled templates from the Smarty cache.

My best guess is that this did not happen. Smarty 3.1.25 used a Smarty 3.1.15 cached compiled template.

CubeCart does not collect debug data about whether Smarty recompiled a template or used a cached template, so this is the basis for my guess.

I will also have to assume that Smarty does not check for Smarty version mismatches between itself and compiled templates -- then recompiling on a detected mismatch.

**Comment by abrookbanks** [comment]
That logic sounds right to me.
