### ISSUE TITLE
Tax not recalculated/updated after order change in admin -> inventory panel 

### ISSUE THREAD

**Issue by rbosma** [cubecart/v6#639]
When changing an order in the admin panel, the tax isn't updated. First I thought it was only on my install, but after checking the Cubecart Demo it seems it also has the same problem. For me it's a big issue but also for others I asume.

I hope it hasn't been mentioned before, but couldn't find it.

**Comment by havenswift-hosting** [comment]
We are currently working on a plugin that will add lots of additional functionality to the admin order program, including this

**Comment by abrookbanks** [comment]
This issue is massive and is going to need significant development time. Please for now update manually.

**Comment by Noodleyman** [comment]
This is addressed in the module:
https://www.cubecart.com/extensions/plugins/enhanced-admin-order-entry

**Comment by havenswift-hosting** [comment]
It does and this issue should be closed
