### ISSUE TITLE
Text product options show "(+£0.00)" on fresh install of CC 6.0.0b2 

### ISSUE THREAD

**Issue by NaturalSigns** [cubecart/v6#64]
New beta update looks to have fixed the product options being shown correctly, but if you use Textarea - Singleline or Multiline.  It will show up "+£0.00" on the storefront next to the field name, i think costs should not be showing on text fields.

Also sorting of products doesn't seem to work, always sorts by A-Z when i try.

**Comment by abrookbanks** [comment]
Please follow issue #67 concerning sort.
