### ISSUE TITLE
Add filter by manufacturer

### ISSUE THREAD

**Issue by bobdonkey** [cubecart/v6#641]
When browsing categories, or in search results, it would be very useful to have a filter by manufacturer. This should only show manufacturers for products which are actually in stock.

**Comment by havenswift-hosting** [comment]
Our Enhanced Manufacturers plugin adds this functionality along with a lot of other features.  It is t yet on the CubeCart Marketplace (will be added soon) but is available directly here: https://www.havenswift-hosting.co.uk/clients/cart.php?gid=19

**Comment by Noodleyman** [comment]
https://www.cubecart.com/extensions/plugins/enhanced-admin-order-entry
