### ISSUE TITLE
Add option to set grid view by default

### ISSUE THREAD

**Issue by bobdonkey** [cubecart/v6#642]
As above, it would be good to have this on all pages as an option to set as default.

**Comment by Noodleyman** [comment]
@abrookbanks , this is a very simple skin change to make work, literally two code changes.  does it require a feature request or should it be considered part of store skin customization?

**Comment by abrookbanks** [comment]
The foundation skin was designed to be a blueprint to customise it where you want. My take on this is that the foundation skin should be cloned and customised to how you want it. For this reason I will close this issue. Any merchants needing help making customisations such as this can open a tech support ticket.
