### ISSUE TITLE
CC5-CC6 Upgrade, Social Plugins Not Displayed

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#643]
When upgrading a CC5 store to CC6, the links to social plugins are not displayed on the manage plugins page in store admin.

Additionally they are not accessible via the link they were in CC5.

CC5 Link - admin.php?_g=modules&type=social&module=Facebook
CC6 Link - admin.php?_g=plugins&type=social&module=Facebook

The location
e.g.
/modules/social/Facebook
is the same in both CC5 and CC6 stores.

**Comment by abrookbanks** [comment]
I can't fix this. Older version of these modules didn't have a config.xml file which are now required.

**Comment by SemperFiWS** [comment]
The CC5 modules do have config files.
e.g.
```<?xml version="1.0" encoding="UTF-8"?>
<installer version="1.0">
  <info>
	<uid>facebook@cubecart.com</uid>
	<type>social</type>
	<name><![CDATA[Facebook]]></name>
	<description><![CDATA[Facebook - comments and like buttons]]></description>
	<version>1.0.0</version>
	<minVersion>5.0.0a</minVersion>
	<maxVersion>5.1.*</maxVersion>
	<creator><![CDATA[CubeCart]]></creator>
	<homepage><![CDATA[http://www.cubecart.com]]></homepage>
	<block>false</block>
  </info>
</installer>```
/modules/social/Facebook/config.xml

**Comment by abrookbanks** [comment]
Yes thats the fix. :)
