### ISSUE TITLE
Optimize categories menu

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#644]
In stores with a large amount of categories and levels of sub-categories, enabling 'Expand category navigation tree' will pretty much cripple a store.

A specific example of a store affected by this:
- 750 categories
- 7964 products
- 11399 entries in the 'CubeCart_category_index' table

With 'Expand category navigation tree' disabled, caching enabled and debug enabled there is less than 100 queries loading the home page.

With 'Expand category navigation tree' enabled, caching enabled and debug enabled there is 3000+ queries loading the home page.

It appears that something like this:
SELECT COUNT(cat_id) AS Count FROM `CubeCart_category` WHERE CubeCart_category.cat_parent_id = '756' AND CubeCart_category.status = '1'; -- (0.00066494941711426 sec) [CACHE WRITE]
SELECT `path` FROM `CubeCart_seo_urls` WHERE CubeCart_seo_urls.type = 'cat' AND CubeCart_seo_urls.item_id = '234' ; -- (0.00021600723266602 sec) [CACHE WRITE]
happens for each and every category in the store.

**Comment by SemperFiWS** [comment]
Having a max depth setting for the expanding category tree in admin might also help with this.

If you want access to the live store where this was observed, just let me know.

**Comment by bhsmither** [comment]
I think, way back when, I tried to optimize this by loading the entire category table into an array, then building the category tree from that array.

**Comment by abrookbanks** [comment]
> happens for each and every category in the store

Agreed but it should then read from cache instead. This whole process is fairly monstrous but once created the whole HTML is cached.

Definitely room for improvement.

**Comment by abrookbanks** [comment]
I know that some higher end ecommerce system require the category tree to be built manually as HTML to help reduce load.
