### ISSUE TITLE
Automatically backup files + database when upgrading

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#648]
When using the upgrade via store admin, have a database and file backup run first.
If successful, continue on with upgrade as normal.
If unsuccessful, throw a warning that the backups failed, but allow store owner to continue with the upgrade.

**Comment by havenswift-hosting** [comment]
If this functionality is introduced it should only be optional and not default to doing backups in this way

**Comment by Noodleyman** [comment]
Does this really n eed to be a feature request. It's a recommendation to automate a backup, which is something the person doing the update should be responsible for ensuring is taken, and backed up correctly. Automating it may add a false level of confidence that the customer has a backup, when in fact they may not.

**Comment by havenswift-hosting** [comment]
I completely agree and dont think this should be included at all even as an option but certainly not as default behaviour
