### ISSUE TITLE
Widget IDs

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#65]
The sub-major areas need to have IDs.

For example: The div block that represents the Homepage document area and the Latest Products area need to each have unique identifications.

Case Study: "Permissions Gateway"
Only if there is a **logged in** user, the Homepage document could display specific content, including javascript that will "unhide" certain areas that would be not be displayed by default, such as the Latest Products, right side-panel, navigation bar and search bar areas.

When not logged in, only the Homepage document displaying content specific to not being logged in, Documents bar, top header and Logo would be visible.

This is a horrible example as it would be easy to bypass these display effects. But without unique IDs, such effects would be very difficult.

**Comment by abrookbanks** [comment]
GREAT suggestion. Thank you brian. This has been implemented with naming convention consistency. 

e.g. box.featured.php = "box-featured"

etc..
