### ISSUE TITLE
Radio Product Options - Creating An Option Set

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#652]
When creating an option set, you can only select a complete radio button list.
It is not possible to select specific option attributes belonging to the group.

Example
![radio-options-bug-1](https://cloud.githubusercontent.com/assets/6945093/8414356/78e06040-1e65-11e5-9a65-7aac1d093c51.png)

**Comment by abrookbanks** [comment]
Fixed with https://github.com/cubecart/v6/commit/f0d74ee1c96df2e32dea778ce5733e63877b36d9 thanks again Daren.
