### ISSUE TITLE
Radio Product Options - Assigned Option Set

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#653]
When you assign radio options via an option set to a product:
- just the group is displayed (rather than each attribute)
- therefore you cannot set negative/price/weight for each attribute

Example
![radio-options-bug-2](https://cloud.githubusercontent.com/assets/6945093/8414438/f2f261b2-1e65-11e5-93aa-55b072d15812.png)

**Comment by SemperFiWS** [comment]
If you assign manually you can select specific attributes and set the negative/price/weight for each attribute

**Comment by abrookbanks** [comment]
Fixed with https://github.com/cubecart/v6/commit/f0d74ee1c96df2e32dea778ce5733e63877b36d9 thanks again Daren.
