### ISSUE TITLE
Various Modules - General Tab Loads Nothing

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#655]
Olark
Plugin URL: admin.php?_g=plugins&type=livehelp&module=olark
General Tab URL: admin.php?_g=plugins&type=livehelp&module=olark#olark
Div ID Is: Olark
Div ID Should Be: olark

Zopim
Plugin URL: admin.php?_g=plugins&type=livehelp&module=zopim
General Tab URL: admin.php?_g=plugins&type=livehelp&module=zopim#zopim
Div ID Is: Zopim
Div ID Should Be: zopim

Charity Clear
Plugin URL: admin.php?_g=plugins&type=gateway&module=CardStream&variant=CharityClear
General Tab URL: admin.php?_g=plugins&type=gateway&module=CardStream&variant=CharityClear#CharityClear
Div ID Is: CardStream
Div ID Should Be: CharityClear

EBS
Plugin URL: admin.php?_g=plugins&type=gateway&module=EBS
General Tab URL: admin.php?_g=plugins&type=gateway&module=EBS#EBS
Div ID Is: ebs
Div ID Should Be: EBS

HiPay
Plugin URL: admin.php?_g=plugins&type=gateway&module=Hipay
General Tab URL: admin.php?_g=plugins&type=gateway&module=Hipay#Hipay
Div ID Is: hipay
Div ID Should Be: Hipay

OkPay
Plugin URL: admin.php?_g=plugins&type=gateway&module=OKPay
General Tab URL: 
Div ID Is: OKPAY
Div ID Should Be: OKPay
Both zone tabs also do not work for this one. 

Optimal Payments
Plugin URL: admin.php?_g=plugins&type=gateway&module=OptimalPayments
General Tab URL: admin.php?_g=plugins&type=gateway&module=OptimalPayments#OptimalPayments
Div ID Is: optimalpayments
Div ID Should Be: OptimalPayments

Realex
Plugin URL: admin.php?_g=plugins&type=gateway&module=Realex-1.0.1
General Tab URL: admin.php?_g=plugins&type=gateway&module=Realex-1.0.1#Realex-1.0.1
Div ID Is: Realex
Div ID Should Be: #Realex-1.0.1

Skrill/Moneybookers ewallet
Plugin URL: admin.php?_g=plugins&type=gateway&module=moneybookers&variant=moneybookers_ewallet
General Tab URL: admin.php?_g=plugins&type=gateway&module=moneybookers&variant=moneybookers_ewallet#moneybookers_ewallet
Div ID Is: moneybookers
Div ID Should Be: moneybookers_ewallet

UPG
Plugin URL: admin.php?_g=plugins&type=gateway&module=UPG
General Tab URL: admin.php?_g=plugins&type=gateway&module=UPG#UPG
Div ID Is: upg
Div ID Should Be: UPG

Shopzilla
Plugin URL: admin.php?_g=plugins&type=plugins&module=shopzilla
General Tab URL: admin.php?_g=plugins&type=plugins&module=shopzilla#shopzilla
Div ID Is: Shopzilla
Div ID Should Be: shopzilla

**Comment by SemperFiWS** [comment]
Ignore Zopim as that is not an official CubeCart module.

**Comment by SemperFiWS** [comment]
The Icepay layout is a complete mess.

The Online Bank Transfer plugin throws these errors:
[Warning] /controllers/controller.admin.session.true.inc.php:45 - file_get_contents(/modules/gateway/moneybookers/config.xml) [function.file-get-contents.php]: failed to open stream: No such file or directory
[Exception] /controllers/controller.admin.session.true.inc.php:45 - String could not be parsed as XML

**Comment by abrookbanks** [comment]
HOURS OF FUN! hehe. Thanks for this Darren. I'll try and do it today... I have even printed it off so I can scrawl though it as I go.

**Comment by abrookbanks** [comment]
All done. Thanks!! :)
