### ISSUE TITLE
System Error Log

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#657]
Suggest passing PHP's error messages in the Debug class through htmlspecialchars().

Unconverted strings could make the System Error Log and the debug output affect the HTML display.

**Comment by abrookbanks** [comment]
Good idea. Thanks.

**Comment by bhsmither** [comment]
Please reexamine this.
`Debug->display()` calls `$this->_errorDisplay()`. _errorDisplay glues the messages with a `<br />` tag, which display() then immediately strips out.

Suggest gluing with `PHP_EOL`. Then process the string with `strip_tags()`, then `htmlspecialchars()`, then `nl2br()`.

**Comment by bhsmither** [comment]
Also, the point of this issue relates to entries in the database table CubeCart_system_error_log. When at admin, Error Log, System Error Log tab, the display uses the exact, unprocessed contents of the records.

Suggest processing the error string in Debug->errorLogger() prior to INSERT into the database.
