### ISSUE TITLE
Display of price & weight when adding new option

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#659]
![display_problem_options](https://cloud.githubusercontent.com/assets/6114431/8450440/31291676-1fdb-11e5-9d87-53bbbce38d9e.png)

**Comment by abrookbanks** [comment]
I can't reproduce this. What browser are you using?

Movie: http://static.cubecart.com/github-659.mp4

**Comment by abrookbanks** [comment]
Closed for now but happy to reopen if I can get steps to reproduce this and it is reproducible.
