### ISSUE TITLE
Unique IDs - Important?

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#66]
Question: How important is it for the CubeCart code, and current programming practices in general, that HTML node id attribute values be unique?

In content.homepage.php, each item in the Latest Products area is wrapped in a `<form>` block, and each form ends up with `id="add_to_basket"`.

**Comment by abrookbanks** [comment]
I think they should be unique so this is a bug as far as I am concerned.

http://www.w3.org/TR/WCAG20-TECHS/H93.html

**Comment by abrookbanks** [comment]
Changed from form#add_to_basket to form.add_to_basket with no repercussions.
