### ISSUE TITLE
Products Per Page - CC5/Custom Skins

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#660]
The 'catalogue_products_per_page' setting was replaced with a hidden field and the new code in the skins 'config.xml' file.
For stores running either a CC5 or custom skin, the store admin cannot alter the amount of products displayed per page.

Restoring the field and making a note about the 'config.xml' would be a simple solution.

**Comment by SemperFiWS** [comment]
Also, there is a typo in the comment code that has been added to the '/admin/skins/default/settings.index.php' file.
i.e.
section of the skins config.xml file wich includes page splits.

**Comment by Noodleyman** [comment]
I requested this in the past, but was told that it won't be fixed.

See:
https://github.com/cubecart/v6/issues/361

and:
https://github.com/cubecart/v6/issues/474


You can get this working in a custom skin, or CC5 skin by adding the following to the config.xml file. I've used this work around on a couple of custom skins, but it does remove the nice feature for the users to easily update the value.

  <layout>
	<products>
		<perpage default="true" amount="48" />
	</products>
  </layout>

**Comment by abrookbanks** [comment]
I don't really like this but.. 

![screen shot 2015-09-03 at 16 18 29](https://cloud.githubusercontent.com/assets/4520803/9662478/7ccc0a80-5257-11e5-854f-7393af304720.png)
