### ISSUE TITLE
Digital Item w/CFP Cannot Be Undigitalized

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#661]
Enter a Custom File Path. Item becomes digital. (CubeCart_inventory.digital = 1, digital_path = "path')

Empty the Custom File Path. Item remains digital.(CubeCart_inventory.digital still = 1)

Starting at line 78:
`$_POST['digital_path']` is empty, and `$_POST['download']` is not set (no changes recorded from the File Picker). Therefore, re-use `$old_product_data[0]['digital']` which is 1.

**Comment by bhsmither** [comment]
Suggest (starting near line 82)
```
if (!isset($_POST['download'])) { // No changes recorded in File Picker
  if ($old_product_data[0]['digital'] > 1) { // Danger, as the FileManager file_id may be 1!
    $record['digital'] = $old_product_data[0]['digital'];
  } else {
    $record['digital'] = 0;
  }
```

**Comment by abrookbanks** [comment]
Thanks Brian. From my testng that works very well. :grin:
