### ISSUE TITLE
Multiple installations on one host

### ISSUE THREAD

**Issue by munroa** [cubecart/v6#663]
If you have two installations for example one at / and one at /dev/. You can login to the admin account on /dev/ and gain access to the admin account at / without knowing any of admin credentials for /

**Comment by bhsmither** [comment]
If they share the same database, yes. That's because the "cookie" is valid for both installations.

To make the installations distinct, change the session name from PHPSESSID to something else.

**Comment by munroa** [comment]
They're using two separate databases.

**Comment by bhsmither** [comment]
I stand partially corrected. There is only minimal info stored in the CubeCart_session database table. The bulk of CubeCart's session data is stored in PHP's session file. The filename of that session file uses the value of the 'session name' cookie (**PHPSESSID** unless you change it).

Also, CubeCart sets PHP's "session.cookie_path" to the value it calculates for "rootRel". In one installation, that will be "/" and in the second installation, that will be "/dev/". But "/" is probably universal to the root folder and everything below it.

**Comment by abrookbanks** [comment]
Attempt to make session ID "unique" between install paths. This should resolve it in 99.99% of cases unless hash happens to be the same (unlikely).

**Comment by bhsmither** [comment]
With /classes/session.class.php, line 615 in place, is ini.inc.php, line 51 still necessary?

Is there ever a case where ini.inc.php gets called but session.class.php would **not** get instantiated when it should have? I'm worried about a side-effect of having the statement to name the session so late in the startup sequence -- although perhaps nothing actually matters until the session actually starts.

**Comment by bhsmither** [comment]
One side-effect is with the ini-custom.inc.php and ssl-custom.inc.php files -- if they want to play around with the cookie(s) sent with the request vs what is being established in the code, then there will be a mismatch.

If these files want to use the name of the session as established just a few statements prior, then the name changes, that would cause some consternation.

**Comment by bhsmither** [comment]
Where is the constant ROOT_REL being defined?

I find CC_ROOT_REL defined in ini.inc.php.
