### ISSUE TITLE
PHP notice (undefined index: perpage) fix in gui.class.php at line 519.

### ISSUE THREAD

**Issue by Swiftyhu** [cubecart/v6#665]
Change
```
if((int)$_GET[$page_key]>0) {
```
to
```
if(isset($_GET[$page_key]) && (int)$_GET[$page_key]>0) {
```

**Comment by bhsmither** [comment]
CubeCart's coding practice is to not worry about Undefined indexes. You will eventually find there are dozens of statements that use undefined indexes.

**Comment by havenswift-hosting** [comment]
Would still be good if they were found and fixed in core code though so if you can list any that you know about here, then it is trivial for them to be changed in core for thenext release

**Comment by Noodleyman** [comment]
I agree, would be nice to have these addressed moving forward. I guess it's time to start opening tickets for them as/when we find them, although it might cause Al to have a meltdown ;)

**Comment by havenswift-hosting** [comment]
They should all be easy to fix but I agree having 50 or a 100 new git issues would be a bit overwhelming - maybe report them in this one issue ?

**Comment by abrookbanks** [comment]
Agreed it would be good to get this improved over time. I've worked with Laravel a lot recently and it forces best practise which is no bad thing. Fixed... only a few hundreds left probably. :)

**Comment by abrookbanks** [comment]
https://github.com/cubecart/v6/commit/0c54969d6e67dcc3b947ed459487abece03f9fbf (not sure where 519 came from!)
