### ISSUE TITLE
Line up sections in Latest Products

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#669]
In Foundation skin within the Latest Products if the image sizes are different, the product title still starts the same distance down within the box.  However, if the product titles are different lengths with some over one line and some over two, the price and Add to Basket button are at different heights.

**Comment by abrookbanks** [comment]
I can't do a lot about this. It's a Foundation quirk. It's only possible to equalize all boxes to the same height not same row to same height. Foundation takes the height of the biggest box and applies to all.
![screen shot 2015-08-20 at 11 23 05](https://cloud.githubusercontent.com/assets/4520803/9381340/4b06488c-472e-11e5-9d4e-1321e64f2d01.png)
