### ISSUE TITLE
Pinterest Plugin insecure urls

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#670]
The Pinterest Social Plugin has http:// url's in line 31 in social.class.php, but Pinterest uses https://.

**Comment by Dirty-Butter** [comment]
admin/index.tpl needs to have all http: removed as well.

**Comment by abrookbanks** [comment]
It doesn't matter for anchor links and no data is pulled into the browser from an external source. Pinterest will redirect from http://... to https://.. automatically. 

Thanks.
