### ISSUE TITLE
Possible bug in "Import Subscribers" within Admin Control Panel interface

### ISSUE THREAD

**Issue by ellermanj** [cubecart/v6#672]
When I use the admin control panel interface to add one or more comma separated email addresses to the subscription list, there is a problem.  While the email addresses appear in the list of email subscribers, and appear to look OK in the GUI, if I try and send emails to those users it fails, and if I export the subscription list to a text file, those addresses that were added via the GUI bulk import do not appear in the exported text file.

Adding users on at a time via the shop front GUI, or a user adding their account to the subscription list by clicking the URL on the shop front works fine.  There are no problems with those user email addresses.  The problem only appears to be with those addresses added through the admin control panel interface.

Cubecart version 6.0.5

**Comment by ellermanj** [comment]
Cubecart version 6.0.5

**Comment by abrookbanks** [comment]
Thanks for this!! It's fixed for the next release. The database table CubeCart_newsletter_subscriber needs to have the status set to 1.
