### ISSUE TITLE
Feature Request: Custom URL for Categories

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#673]
It would be really helpful to be able to specify custom URL's at the category level. If left unconfigured it would work as it does today, however if a custom URL has been specified it would load that URL when clicked instead.

This would be extremely useful when linking to affiliate products etc because you can include the categories within your own menu structure easily.

**Comment by abrookbanks** [comment]
Great idea. Like it.

**Comment by Noodleyman** [comment]
I see you liked the idea, and you closed it. will this go into a future release?

Cheers

**Comment by abrookbanks** [comment]
Whoops! That was a mistake.

**Comment by Noodleyman** [comment]
:+1:  Cheers Al :)

**Comment by Noodleyman** [comment]
is there an ETA on this feature?

**Comment by briansandall** [comment]
@Noodleyman I'm not sure I understand what you need, as custom category URLs are already supported:
![cc673](https://cloud.githubusercontent.com/assets/14335170/21278947/ad63c112-c392-11e6-91aa-48a42c9a81dc.jpg)

The only issue I can see is that if you try to add nesting that doesn't exist, e.g. `test-category/sub-category`, only the parts before the slash get used when loading a product; if just viewing the category, however, the entire path is used.

Perhaps you can elaborate on what you need that cannot currently be accomplished?

**Comment by briansandall** [comment]
I think I may have found the issue: setting a custom category URL works, but that custom URL is not used when auto-populating product URLs.

For example, if I have a Product A in Category C, the generated URL for the product is `c/a` which will in turn be used to construct a link to `store_url/c/a.html`. Setting the URL for Category C to `custom` does NOT affect the URL built for the product, so rather than `custom/a` we still have `c/a`.

Is the above an accurate description of your issue @Noodleyman ?

**Comment by briansandall** [comment]
How about this? https://github.com/briansandall/v6/commit/33c23950b2c8727aa21955ad04f24af3a45f0322

**Comment by Noodleyman** [comment]
Custom SEO URL path is not the same as a custom URL. The SEO friendly URL path is the URL used to access the category within the store.

The request is to add the ability to add a custom URL to categories, so if you click on the category it will take you to whatever URL you have mentioned.

Essentialy, the EXACT same behaviour as found in documents. you can click a document link and it redirect you to whatever URL you specified offsite.

The benefir of this is that you can create custom navigation menus using categories in your menu's if required (which was the requirement when I raised this ticket18 months ago).

**Comment by briansandall** [comment]
Ah, so a way to add arbitrary items to the menu - I can see how that would be useful.

I haven't played with hooks much, but would the `class.gui.display_navigation.make_tree` hook in `Gui::_displayNavigation()` work for this purpose?

If not, then I don't imagine it would be too difficult to add an `absolute_url` checkbox field for `CubeCart_seo_urls` and check that before building URLs, e.g.:
```
// seo.class.php line 165-166
// change from:
if (($item = $GLOBALS['db']->select('CubeCart_seo_urls', array('path'), array('type' => $type))) !== false) {
    return $url.$item[0]['path'].$this->_extension;

// to something like:
if (($item = $GLOBALS['db']->select('CubeCart_seo_urls', array('path','absolute_url'), array('type' => $type))) !== false) {
    return (empty($item[0]['absolute_url']) ? $url.$item[0]['path'].$this->_extension : $item[0]['path']);
```
That would allow it to work for products as well as categories.
