### ISSUE TITLE
new ReCaptcha doesn't work on some skins

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#674]
I got caught out by this today, I enabled the "New ReCAPTCHA" settings, it works OK in foundation skin, but in Kurouto the recaptcha doesn't load.  

This in turn causes the challenge to always fail.

**Comment by abrookbanks** [comment]
Thats right. I'm not going to develop the v5 skins to have this feature I'm afraid. :(

**Comment by Noodleyman** [comment]
I think there is room for an enhancement here. 

Observation:
You have the skins listed in the market place as supported in V6, but this feature within those skins doesn't work with V6.


Suggestion:
If using a known V5 skin, remove the ability to select the "New Recapture" from the settings page because it will prevent frustrations trying to get it to work and make for a better customer experience.

**Comment by abrookbanks** [comment]
Thats a good idea.

**Comment by Noodleyman** [comment]
Can the ticket be reopened and labelled as an enhancement for a future release? :)

**Comment by Noodleyman** [comment]
Thank you Al :+1:

**Comment by abrookbanks** [comment]
I'd like to reopen this as Kurouto etc should support the new Recaptcha. Clients on the support helpdesk request this a lot.

**Comment by abrookbanks** [comment]
Thanks for this. Since 6.1.7 the settings will tell the user which options are available to them which will save confusion.

**Comment by demand73** [comment]
Is there any work being done with making Kurouto V6 compatible? or atleast working with the new recapcha? google will inactivate recapcha V1 2018-03-31. I like the Kurouto skin and there is still many stores using it cause Foundation is so ugly =) and the #1883 solution with disable reCaptcha V1 will render Kurouto webshops unusable.

**Comment by abrookbanks** [comment]
Reopened to integrate reCaptcha V2.

**Comment by abrookbanks** [comment]
This will be completed by Friday 2nd March.

Notes below as a reference to assist me with upgrades.. 
The following code will also be added so the default homepage document images display neatly.

```
.bxslider img {
    width: 100%;
    height: auto;
}
```

Following line required in main.inc.php template:
```
{include file='templates/content.recaptcha.head.php'}
```

**Comment by abrookbanks** [comment]
Kurouto 1.0.3 Released - https://www.cubecart.com/extensions/skins/kurouto

**Comment by abrookbanks** [comment]
Crosshatch 1.0.3 Released - https://www.cubecart.com/extensions/skins/crosshatch

**Comment by abrookbanks** [comment]
Mauris 1.0.3 Released - https://www.cubecart.com/extensions/skins/mauris

**Comment by abrookbanks** [comment]
Mican 1.0.3 Released - https://www.cubecart.com/extensions/skins/mican

**Comment by abrookbanks** [comment]
Mobile 1.0.3 Released - https://www.cubecart.com/extensions/skins/mobile

**Comment by abrookbanks** [comment]
Nota 1.0.3 Released - https://www.cubecart.com/extensions/skins/nota

**Comment by Noodleyman** [comment]
You've been busy :)

I was curious if there is any documented steps that can be given to people who may be running custom versions of the themes you've updated and want to apply it manually?

**Comment by abrookbanks** [comment]
@Noodleyman Yup.. https://forums.cubecart.com/topic/53722-recapcha-ending/?do=findComment&comment=231955

**Comment by abrookbanks** [comment]
I've done this many times for customers on the [Technical Support & Management](https://www.cubecart.com/technical-support) plan it's pretty much second nature.

**Comment by abrookbanks** [comment]
Vanilla 1.0.3 Released - https://www.cubecart.com/extensions/skins/vanilla

**Comment by abrookbanks** [comment]
Now for the WebCity skins.. tea break first..

**Comment by abrookbanks** [comment]
e-Sharp 1.1 Released - https://www.cubecart.com/extensions/skins/e-sharp-by-webcity

**Comment by abrookbanks** [comment]
e-Scalar 1.1 Released - https://www.cubecart.com/extensions/skins/e-scalar-by-webcity

**Comment by abrookbanks** [comment]
e-Shift 1.1 Released - https://www.cubecart.com/extensions/skins/e-shift-by-webcity

**Comment by abrookbanks** [comment]
e-Trend 1.1 Released - https://www.cubecart.com/extensions/skins/e-trend-by-webcity

**Comment by abrookbanks** [comment]
e-Tone 1.1 Released - https://www.cubecart.com/extensions/skins/e-tone-by-webcity

**Comment by abrookbanks** [comment]
All officially maintained skins have now been updated... right who's round is it? Hehe.

**Comment by demand73** [comment]
Super thanks, it works like a charm.

**Comment by abrookbanks** [comment]
Great! It's been on my radar a while. The EoL date was the required kick up the backside. Have a nice day.

**Comment by bhsmither** [comment]
(Haven't actually verified this yet...)
I see that Kurouto/1.0.3 has had what appears to be a recent version of Foundation's content.recaptcha.php.

Is this intentional?

I just wonder what I would be missing since SVG and Foundation classes are not part of any other CC5 skin.

**Comment by abrookbanks** [comment]
Yes it's intentional. The SVG images are only used with the phased out version. reCaptcha V2 will work fine.
