### ISSUE TITLE
Mini Basket Not Automatically Updating in Mobile Mode

### ISSUE THREAD

**Issue by onebrowncow** [cubecart/v6#675]
In the mobile sized version of CC6 the toggled mini basket fails to update with products being added to the basket in particular after the first item is added the second and sometimes third items added fails to show in the toggled mini basket even though it is present on the main view basket page. Visiting the main basket page or refreshing the browser seems to trigger the ajax process and the mini basket will then continue to add products as normal. See discussion here: https://forums.cubecart.com/topic/50037-mini-basket-not-automatically-updating-in-mobile-mode/

**Comment by abrookbanks** [comment]
Thanks. From my testing Brian's fix works really well.
