### ISSUE TITLE
Additional customisation of the homepage

### ISSUE THREAD

**Issue by bobdonkey** [cubecart/v6#676]
At the moment it is only possible to show Popular & Latest Products on the homepage, as well as one document. It would be nice to allow some more customisation to the homepage using the foundation skin out of the box. Currently the layout is very restrictive, only allowing for one document, and the latest products in the centre. You could add for example:

- Allow multiple documents on the homepage
- Add option of popular products in the centre
- Add option of featured products in the centre
- Add option of sale products in the centre
- Add ordering of all of the above on the homepage

These changes would allow a great deal more customisation without resorting to editing the html.

**Comment by havenswift-hosting** [comment]
The Foundation skin is deliberately a basic layout (or foundation !) meant to be built on.  There are several skins in development (including two due for release shortly by us) that build on this. The above functionality shouldnt be part of the skin but should be achieved by using plugins - in fact we already have a plugin that allows for multiple documents to be displayed on the homepage and the order of these can be set so you can have additional documents above or below the main "homepage document"

**Comment by bobdonkey** [comment]
Hi, thanks, I understand it is meant to be a foundation, but not many people are going to create a plugin just to change the layout.
If you have made one already, please let me know where it is, I cannot find it on the plugins section of the cubecart site. I have sent a PM.
Thanks

**Comment by havenswift-hosting** [comment]
Plugin is not yet available on our website or the marketplace (although will be very soon) as only just completed - replied to your PM with details of demo available

**Comment by abrookbanks** [comment]
This can all be done using either code hooks or full blown plugin. You just need to add it and adjust the HTML accordingly.
