### ISSUE TITLE
{Bug} - Option Matrix Negative Values

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#677]
If you have a negative value in any of the option matrix fields and then press the save or save and reload button the submitted values change. 

Example:
Stock Level field = -1

When submitted 
-1 +- -1 = -2
-2 +- -2 = -4
and so on.

When in actual fact it should store the explicit field value.

The problem can be replicated for all fields related to the option matrix (including custom added ones).

Some customers do use negative numbers in their stock levels to signify special meanings which is how I spotted this issue as the values keep changing when a product is updated.

**Comment by abrookbanks** [comment]
Another excellent find from the man of the land of cider.

**Comment by Noodleyman** [comment]
Appplezzzzzzzzzzzzzzzzzzzzzzzz

:)
