### ISSUE TITLE
Documentation / Wiki

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#679]
One of the drawbacks to CubeCart is the lack of user guides and proper user targeted documentation. It would be very handy to have formal documentation aimed towards end users, and would be fantastic if we can get a wiki for developers as well.

So, formally requesting 
A) CubeCart end user documentation
B) Developer Wiki

Cheers

**Comment by havenswift-hosting** [comment]
Both of these could be done via a single wiki with front end and developer sections.  MediaWiki is Open Source and is what runs wikipedia.org so many people are familiar with it.  It is also relatively easy to install although care has to be taken over allowing open registration as it can easily be abused by spam registrations.  I am sure that there would be plenty of people that would be interested in helping to contribute pages and these could be granted access to update pages  

wiki.cubecart.com or maybe cubecart-wiki.com ?

**Comment by bhsmither** [comment]
I perceive this documentation site isn't being used very well:
http://www.cubecartforums.org/docs/

It could be because the markup is not familiar?

I managed a MediaWiki site once. That markup is strange as well.

I also have a SDK site I own and I use BBCode. That's a strange one.

I think, any solution would need to have a much more intuitive (read: MS Office-like) toolbar set for formatting and styling.

**Comment by bhsmither** [comment]
Then there is this site:
https://wiki.cubecart.com/Main_Page

**Comment by abrookbanks** [comment]
Agreed this would be great. There is just NO way I have the resources. Any volunteers? ;)

**Comment by Noodleyman** [comment]
I would be happy to help out / contribute if you want to compile a plan?

That is if you can cope with my Somerset translation of technical explanations... 

"If Farmer A has one hay stack, and Farmer B has three hay stacks... profit?" :)

**Comment by abrookbanks** [comment]
ROFL! That would be great!

**Comment by havenswift-hosting** [comment]
I would also be happy to help but if it isnt already restricted to specific logins then it should be done ASAP.  I am sure that others would be interested as well but maybe dont just open it up initially to just amyone

**Comment by abrookbanks** [comment]
Great stuff guys. I'm so behind with github.... really need more arms and brains. 

I'm off to Thailand in October for a break but I think I have to take my laptop with me. Boooooooo.

**Comment by Noodleyman** [comment]
Al,

just an observation.. you asked for volunteers, but then closed this item, so I suspect it dropped off your radar / list.

Doesn't this item need to remain open?

**Comment by abrookbanks** [comment]
It’s not really relevant to the codebase. Issues on GitHub should only really be related to the actual code.
