### ISSUE TITLE
{BUG} - 606 - plugin directory name can not contain "admin"

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#681]
This one tripped me up for a while today

When creating a module / plugin, if the folder name contains the string "admin" in any form it gets stripped from the path when including a language file resulting in an invaid path which causes a  PHP error and the inability to load the module.

examples directory names:
"my_admin_plugin" translates the path to be "my__plugin".
"badmington" translates the path to be "bton"

From apache log file:
PHP Fatal error:  Invalid language path: A:\\Noodles Stuff\\Development Web Server (Apache)\\htdocs\\cubecart_dev\\6.0.6\\modules\\plugins\\bton\\/language - badminton - module.definitions.xml in A:\\Noodles Stuff\\Development Web Server (Apache)\\htdocs\\cubecart_dev\\6.0.6\\classes\\language.class.php on line 647, referer: https://noodle-mini/cubecart_dev/6.0.6/admin.php?_g=plugins

**Comment by abrookbanks** [comment]
Thanks Alec! :)
