### ISSUE TITLE
secure trading 

### ISSUE THREAD

**Issue by cloot1** [cubecart/v6#683]
Any news of a plugin for this for version 6?

**Comment by Noodleyman** [comment]
Can you expand on what you mean by "Secure Trading" ?

**Comment by cloot1** [comment]
Hi Sorry.
I mean this.. http://www.securetrading.com/cart/cubecart/
for version 6

**Comment by havenswift-hosting** [comment]
A github issue is probably not the bets place to be requesting new modules especially payment gateways - CubeCart already comes with a large range and third parties have written almost the same number again so it is unlikely any more will be added to core.

V5 and V6 are generally code compatible so have you tried running the V5 version supplied on that website - it is almost certainly going to work.  Those ones were also written by themselves so you would also be better off directing any questions to them

**Comment by cloot1** [comment]
No I haven't tried the cubecart 5 plugin.. but will do. I expected if it is not in the cubecart 6 section it would not work though..
I also contacted secure trading and they said 'CubeCart have unfortunately not got back to us yet regarding this, however we do not believe it's very likely that they will be making a new module for us at present.'

**Comment by havenswift-hosting** [comment]
>>I expected if it is not in the cubecart 6 section it would not work though..

As I said, the vast majority of modules for V5 will work for V6

**Comment by abrookbanks** [comment]
The v5 module provided by Secure Trading will work with CubeCart v6. 

http://www.securetrading.com/wp-content/uploads/2013/07/st-cubecart-5.1.0-stpp.stapi-2.5.6.zip

**Comment by cloot1** [comment]
thank you!
