### ISSUE TITLE
Database Residue May Give Wrong Stock Levels

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#686]
See:
https://forums.cubecart.com/topic/50069-stock-and-comment-box/#comment-210850

**Comment by bhsmither** [comment]
Updating a product's options matrix will update all ***value sets*** of records equally. So, how the multiple sets came to be, is probably from a fault in earlier versions of CubeCart.

This may be the cause of different reporting. If there are multiple sets of option matrix values, then:

Catalogue->getProductStock() will get the highest stock level regardless of ***value set***, or will get the **first** record (index=0) regardless of how many records in the recordset - which depends on the order the database server returned that recordset. It might not be in matrix_id order!

In products.index.inc.php, line 1178, a SUM of all stock levels for the product is used to update the overall stock level, resulting in a value multiplied by the number of ***value sets***.

At line 1148, if several ***value sets** are returned, only the **last** set appearing in the recordset is held in the array, as each each ***value set*** over-writes the previous one. As mentioned before, the order the database server returns the records may not be in matrix_id order.

So, perhaps there is a cause to execute a function in setup to scan for and delete any residual records in CubeCart_option_matrix table to delete duplicate records on the `product_id + options_identifier` pair of columns.

**Comment by abrookbanks** [comment]
From 6.0.6 and 6.0.7 (when available) the residue will be fixed by simply loading the edit product view in the admin control panel. I suppose it would be possible to write a script on upgrade to check and correct any db residue. Due to the very procedural means the admin/sources/products.index.inc.php file is written this is not straightforward.

**Comment by abrookbanks** [comment]
It may be possible to strip this code out and put nicely into the catalog class. It could then be called in a product ID loop on upgrade. This is all fair and good but it could crash an upgrade for a large product inventory. 

I don't know what the best thing is to do other than writing a specific paginated script just to fix this. I feel I have no choice but to close this for now and fix on a case by case situation.

**Comment by Noodleyman** [comment]
if anybody needs to clean this up manually the following SQL stratements work great.

INSERT INTO
 temp_option_matrix
SELECT
 *
FROM
 CubeCart_option_matrix
GROUP BY
 product_id,
 options_identifier,
 cached_name,
 stock_level,
 product_code
 

TRUNCATE TABLE CubeCart_option_matrix;

INSERT INTO
 CubeCart_option_matrix
SELECT
 *
FROM
 temp_option_matrix;

drop temp_option_matrix;
