### ISSUE TITLE
Set Cookie Expire Time Bug

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#687]
The following block of code sets the expire time to false (I think) is not in admin.

$this->_session_timeout = (ADMIN_CP) ? 60 * 60 * 168 : 60 * 60 * 1; // 7 days

Testing needed.

**Comment by bhsmither** [comment]
It is a *ternary* decision block.
```
(ADMIN_CP)       <= implied if
? 60 * 60 * 168   <= return this expression if true
: 60 * 60 * 1;       <= return this expression if false
```

**Comment by abrookbanks** [comment]
Right. I didn't see the colon... Anyhow the cookie time is buggy which is the main reason behind this report.

**Comment by bhsmither** [comment]
Can you elaborate?

**Comment by abrookbanks** [comment]
Not had a chance to look at bugs for a week or more but if you debug the expire time on set_cookie in the session class it doesn't seem to add on the specified seconds.

**Comment by bhsmither** [comment]
Does for me, but then, I will not use IE. Maybe the problem is localized to IE.

**Comment by abrookbanks** [comment]
The code I was looking at wasn't default code in a customer store.
