### ISSUE TITLE
Maintenance > Query Database - Only accepts one query at a time

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#688]
If you paste this:
```ALTER TABLE `CubeCart_inventory` ADD `test_field_01` TINYINT(1) NOT NULL DEFAULT '0' ;```
it will work just fine and return the amount of rows correctly.

But if you paste this:
```ALTER TABLE `CubeCart_inventory` ADD `test_field_02` TINYINT(1) NOT NULL DEFAULT '0' ;
ALTER TABLE `CubeCart_inventory` ADD `test_field_03` TINYINT(1) NOT NULL DEFAULT '0' ;
ALTER TABLE `CubeCart_inventory` ADD `test_field_04` TINYINT(1) NOT NULL DEFAULT '0' ;
ALTER TABLE `CubeCart_inventory` ADD `test_field_05` TINYINT(1) NOT NULL DEFAULT '0' ;```
it gives a success message of 1 row affected.

Plus the fields are not added to the table.

In the error log is this:
```File: [maintenance.sql.inc.php] Line: [23] "ALTER TABLE `CubeCart_inventory` ADD `test_field_01` TINYINT(1) NOT NULL DEFAULT '0' ;
ALTER TABLE `CubeCart_inventory` ADD `test_field_02` TINYINT(1) NOT NULL DEFAULT '0' ;
ALTER TABLE `CubeCart_inventory` ADD `test_field_03` TINYINT(1) NOT NULL DEFAULT '0' ;
ALTER TABLE `CubeCart_inventory` ADD `test_field_04` TINYINT(1) NOT NULL DEFAULT '0' ; " - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALTER TABLE `CubeCart_inventory` ADD `test_field_02` TINYINT(1) NOT NULL DEFAULT' at line 2```

**Comment by bhsmither** [comment]
MySQL does not like compound statements without some preparation.
http://dev.mysql.com/doc/refman/5.6/en/sql-syntax-compound-statements.html

I've seen, but not tested, code in CC606 that does permit multiple statements be submitted. CubeCart will determine if the POSTed string has `; #EOQ` anywhere in it and if so, sends the string to Database->parseSchema() where, there it is split into individual queries (by `; #EOQ` or by `; *newline*`) for execution in order.

If `; #EOQ` is not found, the entire string is sent *as is* to Database->query() where it is executed untouched.

**Comment by abrookbanks** [comment]
Thanks Brian. You are right. If #EOQ is detected CubeCart will use the parseScheme for multiple queries. :zap:

**Comment by havenswift-hosting** [comment]
Maybe add some text to this effect to that page - this would also be a good thing to have in the new wiki !

**Comment by abrookbanks** [comment]
Done. 
![screen shot 2015-07-17 at 11 40 27](https://cloud.githubusercontent.com/assets/4520803/8745522/a771a3c6-2c78-11e5-93e6-c9564ebe3c1e.png)
