### ISSUE TITLE
Admin Product Search - Triggers security alert

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#689]
When using the admin product search for a product, you will get this:
Security Alert: Possible Cross-Site Request Forgery (CSRF) or browser back button used.

How To Replicate
- log into admin
- click search
- enter a product name you know exists
- select that product when it is displayed
- click go

**Comment by bhsmither** [comment]
Cannot duplicate.
When I see the product that is suggested after typing in a few letters, I click on the suggested name and a page request is immediately performed and the browser receives the Edit Product page. There is no "click go".

**Comment by havenswift-hosting** [comment]
I am also not able to duplicate this but this issue is already logged under https://github.com/cubecart/v6/issues/631

**Comment by abrookbanks** [comment]
I can. This will happen if the AJAX search populates the dropdown but the results are ignored and search button clicked. Effectively the search is run twice on the old session token.

**Comment by abrookbanks** [comment]
Now when results are round and clicked on the "Go" buttons are disabled and hidden.
