### ISSUE TITLE
Duplicate Manufacturers possible

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#691]
We have several hundred manufacturers in our list, so I normally view all before adding another, just to be sure we don't already have it listed. At some point I didn't do that and just noticed I had the same brand listed twice. After making sure all products were listed under the first id#, I deleted the second. To be sure it really was a bug in the current version, I intentionally added a duplicate name. No error or warning was provided, and it saved as normal, with a new id#.

**Comment by abrookbanks** [comment]
Thanks for this! Nice suggestion which has been implemented. 
![screen shot 2015-08-19 at 10 30 36](https://cloud.githubusercontent.com/assets/4520803/9353053/750f71de-465d-11e5-9512-01cbbe0b8cbd.png)
