### ISSUE TITLE
Fatal Error! No Valid Language Found!

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#692]
For a certain upgrade path, the result may be a white screen.

In language.class.php, if processing makes it to line 94, then there must be the language file present as specified in config['default_language'].

* Already having a prior version of CC6 running happily,
* and you have a default language **not** en-GB (en-US, for example),
* then working with a ***completely new installation*** of CC606,
* but using the prior globals.inc.php that points to the existing database,

Processing will fall through to line 96 and PHP's Fatal Error.

Knowing that a completely new installation has no language other than en-GB, I suggest that part of line 94:
```
($GLOBALS['config']->has('config', 'default_language') && !$GLOBALS['config']->isEmpty('config', 'default_language'))
```
also include a test for the existence of that previous default language file. If the language file does not exist, then, of course, use the (expression is false) "en-GB" language.

**Comment by abrookbanks** [comment]
Thanks Brian.
