### ISSUE TITLE
Change country code to country name during checkout

### ISSUE THREAD

**Issue by nathanbright** [cubecart/v6#693]
Issue defined here (including screenshot of relevant checkout page):
https://forums.cubecart.com/topic/49882-resolved-change-to-address-items

That thread includes a proposed change to /classes/cubecart.class.php to add the full country name to the checkout billing details via country-code lookup

The change also needs to be applied to delivery address

**Comment by nathanbright** [comment]
Proposed code

/classes/cubecart.class.php
function _checkout() 
setting up the billing address array
'country_iso'  => getCountryFormat($_POST['billing']['country'], 'numcode', 'iso'),
'country_name'  => getCountryFormat($_POST['billing']['country'], 'numcode', 'name')
setting up the delivery address array
'country_iso'  => getCountryFormat($_POST['delivery']['country'], 'numcode', 'iso'),
'country_name'  => getCountryFormat($_POST['delivery']['country'], 'numcode', 'name')

In the Foundation skin, templates/content.checkout.confirm.php
change
      {$BILLING.country_iso}
to
      {$BILLING.country_name}
and change
      {$DELIVERY.country_iso}
to
      {$DELIVERY.country_name}

**Comment by abrookbanks** [comment]
Thank you this is a nice improvement.
