### ISSUE TITLE
Cant change some product images 

### ISSUE THREAD

**Issue by kealanm1** [cubecart/v6#695]
I have a large number older products (carried from I believe v4, possibly v3), that I have no control over the product images in use. The image manager does not display any highlighted images in some instances and only the primary starred image on others and no secondary images in either case.

This issue appears to only affect the admin panel and not the front. The affected products all carry images, some multiple images with no issue to customers and no issue to new products. Running cc v6.0.6  but this issue has persisted since at least v5 when it was first noticed. Unsure where to raise but it was suggested as another user was having a similar problem. https://forums.cubecart.com/topic/50093-product-image-question/

**Comment by abrookbanks** [comment]
Hi Kealan,

This is a very fundamental part of CubeCart's functionality and no known issues are known here. The fact it existed since v5 hints that there is possible a data problem that the upgrade wouldn't be able to rectify. 

Please do log a support ticket if you require official support.

**Comment by kealanm1** [comment]
Hi Al,


I appreciate your taking the time to reply directly to me on this. I also
thought that this was unusual and not explicitly a v6 issue however Dirty
Butter suggested that this would be the best place to submit the issue as I
was not alone in this problem.

https://forums.cubecart.com/topic/50093-product-image-question/

I will resume the conversation on the forums as this appears to have
affected more than myself perhaps Brian will dig me out as always!


Kind regards


Kealan Morrissey

**Comment by abrookbanks** [comment]
We have official support packages if you need us to take a look for you.

https://www.cubecart.com/technical-support
