### ISSUE TITLE
New hook - Categories.index.inc.php

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#696]
It would be very helpful to have a hook that allows us to easily manipulate the categories array used in the admin skin.

in cateories.index.inc.php

FIND:
$GLOBALS['smarty']->assign('LIST_CATEGORIES', true);
$GLOBALS['smarty']->assign('CATEGORIES', $category_list);

ADD BEFORE:
foreach ($GLOBALS['hooks']->load('admin.category.pre_smarty') as $hook) include $hook;

There is already a pre_display hook, but the problem is that it is before the steps that gather the category data so can't be used.

**Comment by bhsmither** [comment]
Also in products.index.inc.php, line 720. There is a pre_display hook but it comes before the gathering of the requisite data at line 821. So, there's no chance to add/edit/delete any of that data via hook and make it available to the template.
