### ISSUE TITLE
Admin Product List Sort Indications

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#699]
In Database->column_sort(), links are being created that will include as part of the querystring the intended direction of the **next** sort -- which should be (and is) the _opposite_ of the _currently_ displayed sort.

That is, when the list is _currently_ sorted by Name[ASC], the **Product Name** column header has a link that contains `sort[name]=DESC` -- the opposite of the current sort.

However, the link's `title` attribute and `FA indicator` say and show the opposite of that opposite -- ASC.

Also, as a feature enhancement, include a current sort indicator. That is, a green FA icon in the column header next to the opposite-direction FA icon (the one that also serves as an anchor tag for the opposite sort URL).

Also, split the `FA 'two-headed' sort` icon so that the admin can choose which next sort to perform: ASC or DESC without having to first get the default ASC, then going again for the DESC.

**Comment by abrookbanks** [comment]
But the link shows what the *next* page is. Therefore it's correct as it is? I've been smashing the code out today so excuse me if I missed something but I'm pretty sure it's right as it is.

Thanks for the improvement suggestions. Low priority but noted.
