### ISSUE TITLE
Request: New Hook - catalogue.class.php

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#700]
Request for a new hook to make it easier to modify product information in the category view. Currently it isn't possible.

ADD BEFORE:
return (isset($productList) && is_array($productList)) ? $productList : false;

The current hook, class.catalogue.category_product_list only lets you modify the list of product_id's to include in the call to the getProductData function rather than manipulate the product data itself.

**Comment by Noodleyman** [comment]
Although....

I was able to hook into it using class.catalogue.product_data instead, but this may end up applying my code to more than just the category view which could have negative impacts on other areas of the store

**Comment by abrookbanks** [comment]
Do you think this still warrants a new hook?

**Comment by Noodleyman** [comment]
Yup, would still be very handy to have so that you can easily manipulate the array data within the category view before smarty gets to it.

**Comment by abrookbanks** [comment]
Oakey Coakey. Thanks!
