### ISSUE TITLE
Deletion of Plugins

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#701]
This is more of a general enhancement ticket. It would be great if there was some way an uninstall script could be fired for plugins if they are deleted.

For example, if a plugin makes  a change to a DB table when installed, it would be good to have this DB changed removed when the plugin gets deleted.

Naturally It would require each plugin to have it's own cleanup scripts which if found would get called before the files get deleted. Perhaps something as simple as "cleanup.sql" in the root of the plugin directory etc.

**Comment by bhsmither** [comment]
A suggested solution (fairly tested) is at:
```
https://forums.cubecart.com/topic/58170-plugin-remove-db-table-on-plugin-delete/
```
