### ISSUE TITLE
Hide "More"

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#702]
In Foundation's content.category.php, line 213, a comment is posted to add the "hide" class to the More button.

That won't work because:

There are priorities that CSS rules will be applied to an element. Any rule seen later will overrule a previous rule.

In the foundation.css, the `'hide` class comes before the `.button` class. The `.button` class has `display:inline-block` and that styling is what will be applied.

However, `.hide-for-small-up` is seen at the very near end of the foundation.css file, and thus will have priority over `.hide` and `.button`.

So, suggest that the wording of this comment (any other templates where CC5-style pagination is available) be such that:
`{* Add "hide-for-small-up" to the class attribute to not display the more button *}`

**Comment by abrookbanks** [comment]
Thanks!! :palm_tree:
