### ISSUE TITLE
Call to Non-Object

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#703]
In SEO->generatePath(), in case:viewcat, the following statement faults:
`$GLOBALS['cache']->delete('seo.category.list');`

Request Headers:
`POST search.html?_a=category`

Received by PHP:
`POST => Array(
    [search] => Array(
            [keywords] => Abercrombie
            [priceMin] => 
            [priceMax] => 
        )
    [sort] => name|DESC
)`
`GET => Array(
    [seo_path] => search
    [_a] => category
)`

The stack trace:
```
 1. {main}() \index.php:0
 2. include() \index.php:24
 3. Cubecart->loadPage() \controllers\controller.index.inc.php:118
 4. Cubecart->_category() \classes\cubecart.class.php:359
 5. httpredir() \classes\cubecart.class.php:771
 6. Debug->__destruct() \classes\debug.class.php:0
 7. Debug->display() \classes\debug.class.php:138
 8. currentPage() \classes\debug.class.php:336
 9. SEO->SEOable() \includes\functions.inc.php:245
10. SEO->generatePath() \classes\seo.class.php:581
11. Fatal error:  Call to a member function delete() on a non-object in \classes\seo.class.php on line 242
```
(At `5.`, I am tracing a "Too Many Redirects" error.)

Received by the browser:
`302 Found:`
`Location: ?_a=category&search[keywords]=Abercrombie&search[priceMin]=&search[priceMax]=&sort[name]=DESC`

**Comment by bhsmither** [comment]
This may be an issue with the current state of the GIT repo.
https://forums.cubecart.com/topic/50144-htaccess-searchhtml-err_too_many_redirects/#comment-211262

**Comment by abrookbanks** [comment]
Yes it's ok now. The bad code was in commit https://github.com/cubecart/v6/commit/6e69045aacf73b6a80b2ddeb813e2b9aa53ec288 which when reverted resolved this issue.
