### ISSUE TITLE
Auto Added records in CubeCart_pricing_group do not respect tax_inclusive flag

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#705]
When you add a new customer group to the store and edit products CubeCart_pricing_group gets populated with a clone of the retail price group data.

However...

The "tax_inclusive" flag does not get copied and defaults to 0 which can cause a disconnect if a product is set to tax_inclusive = 1.

**Comment by abrookbanks** [comment]
Great find thanks Alec!
