### ISSUE TITLE
Paths to CC5 plugins in CC6 not valid

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#706]
At some point in the early versions of CC6 the path used to access plugins changed.

This used to work:
?_g=modules&type=plugins

but in more recent versions it doesn't and this has to be used instead:
?_g=plugins&type=plugins

It would be handy to have an alias in CC6 so that both methods would work, unless there is a technical reason why it can't be done in CC6.

Cheers :)

**Comment by abrookbanks** [comment]
Hmm..

```?_g=plugins&type=plugins``` doesn't work for me.

**Comment by abrookbanks** [comment]
I figured it out. :)
