### ISSUE TITLE
Display indication if tax is or is not included in price

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#707]
see https://forums.cubecart.com/topic/50148-displaying-if-tax-is-included-or-not/

**Comment by Noodleyman** [comment]
I've a module that can also do this

https://www.noodleman.co.uk/show-prices-with-and-without-tax-vat.html

**Comment by abrookbanks** [comment]
Really want to get this into 6.1

**Comment by havenswift-hosting** [comment]
I can confirm that Noodleman's plugin works extremely well and we are using it on one customer site already plus the skin changes required for it to work are built into our three V6 skins and you can see it working in Nautical, Retail Therapy and Party Time skins on https://www.cubecart-demo.co.uk

Assume that you can now close this issue and also issue number 358 which deals with the same thing
