### ISSUE TITLE
Foundation Tweak

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#711]
It makes no visual difference, but may have some affect somehow else. Like maybe the equalizer.

In content.homepage.php, line 27, the anchor tag has a class of 'th' and the image tag does not.
In content.category.php, lines 72-74 and 133, the image tag has a class of 'th' and the anchor tag does not.
In content.product.php, line 147, the image tag has a class of 'th' and the anchor tag does not. (Line 22, neither tag has class of 'th'.)

I recommend giving the anchor tag the class as that will make the entirety of the anchor tag's contents set the boundaries of the anchor tag.

**Comment by abrookbanks** [comment]
thanks Brian
