### ISSUE TITLE
Maximum Image Size should be a configurable value

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#712]
discussed briefly with Al, opened a ticket for this to review another day :)

CubeCarts default max image upload size is 350KB, however in an age where internet connections are becoming faster and screen resolutions higher there is a growing need for higher quality images.

The size limit isn't there just for fast browsing of the store, it is also there to stop GD going into meltdown and running out of memory on some servers, especially shared hosting. 

With this in mind I think it would be a better solution to make this setting configurable via the store settings. Perhaps a select list with some predefined values to stop people putting in excessive values. perhaps 50Kb increments up to 1.2Mb?

The default value should be the same as it is today, 350. 

If people run into memory problems then they can lower the value until they find what is right for their server, but it also means people who happen to have the available resources are able to make use of them as they wish without having to make file edits.

Cheeeeeeeeeeeeeeeeeeeeers :)

**Comment by Noodleyman** [comment]
Any timeline on this request? As it stands a handful of stores now have to remember to modify the value in the class files after each upgrade. Moving it to a setting is quick, and easy to do.

**Comment by marcotoki** [comment]
comentario
