### ISSUE TITLE
Start using session_name('something_cubecartish')

### ISSUE THREAD

**Issue by Swiftyhu** [cubecart/v6#713]
I upgraded my cubecart from 6.0.4. to 6.0.6.... Or at least I tried to...
My browser sent back 2 cookies named 'PHPSESSID' to the server...
Whenever I clicked the 'Continue' button on the update/setup page it just went back to the same page...
0%...

I checked the POST data that my browser sent to the server and there was the 2 PHPSESSID...

I think that session_name function will resolve the issue...
![cubecart](https://cloud.githubusercontent.com/assets/1039712/9013031/a490d266-37b9-11e5-9764-6665c8d97a91.png)

**Comment by abrookbanks** [comment]
Thank you this is a good suggestion and I've added it for the next release.
