### ISSUE TITLE
Customer groups & Tax Rules - Shipping modules

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#716]
CubeCart supports customer groups, and at the product level you can define different prices and tax rules based on customer group membership. 

However, at the shipping module level you can only supply a single tax rule and it does not respect group membership.

This can cause a disconnect for customers who are making use of different tax rules, for example retail customers being charged VAT at 20%, and EU customers who are vat registered who shouldn't be charged VAT.

During checkout, shipping will only ever apply the one tax rule as it isn't possible to define the tax rule by customer group as it is the products.

I work around this using some creative methods in my VAT modules, but it would be nice to add support for it to CubeCart as currently it is a disconnect between the way products and shipping works.

**Comment by abrookbanks** [comment]
Agreed Alec this would be spiffing. Hope we can start on 6.1 soon.

**Comment by Noodleyman** [comment]
any movement on this request? It's the biggest disconnect with customer groups and tax systems with the only solution being a custom module at the moment.

**Comment by abrookbanks** [comment]
All feature requests are now closed but have no milestone. We will review them in the future and reopen and add a milestone once in development.

We have a lot of feature requests on here as open issues which makes CubeCart look buggy and unkempt. This way we see only current bugs and work in progress. :)
