### ISSUE TITLE
Hidden Prices - Configure display

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#717]
When you hide prices until logged in, prices become X.XX...

It would be nice if the value displayed could be configured via the store admin area, making it easier for less technical people to configure / setup.

I know it is possible to do this reasonably easy via a store skin edit etc, but just thinking of ways to make it easier for end users who may not feel confident in editing skin files. :)

**Comment by abrookbanks** [comment]
It can be (to a certain extent) :)
![screen shot 2015-08-19 at 10 12 42](https://cloud.githubusercontent.com/assets/4520803/9352680/0ecabfa2-465b-11e5-894c-efb157ba33a2.png)
