### ISSUE TITLE
Adding item to basket

### ISSUE THREAD

**Issue by munroa** [cubecart/v6#718]
Upgraded from v5 to v6 and using the default skin I get this error in the PHP log when I try to add an item to the basket:

PHP Fatal error:  Call to a member function lineCalc() on a non-object in /home/site/public_html/classes/cart.class.php on line 794

And this in the console:

POST http://site.com/product.html?_g=ajaxadd 500 (Internal Server Error)
n.ajaxTransport.k.cors.a.crossDomain.send @ jquery.min.js:4
n.extend.ajax @ jquery.min.js:4
add_to_basket @ 2.cubecart.js:351
$.validate.submitHandler @ 3.cubecart.validate.js:30
h @ jquery.validate.min.js:9
(anonymous function) @ jquery.validate.min.js:9
n.event.dispatch @ jquery.min.js:3
n.event.add.r.handle @ jquery.min.js:3

**Comment by bhsmither** [comment]
Upgrading from CC5 to CC6 by using a completely new installation of the codebase - as opposed to replacing the existing CC5 codebase in the same folders - means that CC6 has records in the database referring to the shipping module, 'Per_Category', and 'Per_Category' is enabled, but that module is not available to CC6.

A fresh install of CC6 requires that you download any module from the Extensions Marketplace (https://www.cubecart.com/extensions) you plan to use.

**Comment by rylanb** [comment]
I'm also having this issue. Is there an area in the database to turn off this option?! Totally screwed up my site upgrading to V6.

**Comment by abrookbanks** [comment]
You haven't followed the upgrade instructions properly so this is a user error and not a v6 bug. Please delete the modules folder, upload the modules folder from v6 and reinstall the extensions you want from the extension market place. If you need further support please send a tech support ticket.

**Comment by rylanb** [comment]
Are you referring to these instructions: https://support.cubecart.com/Knowledgebase/Article/View/229/43/how-do-i-upgrade-from-cubecart-v5-to-v6

with no mention of ANY sort of delete the modules folder and then reupload? I followed those TO the letter. Uploaded the v6 folder after unzipping and then ONLY put up the global.inc.php again so that it had settings. I just checked and the folder structure matches precisely. See attached screenshot. 
<img width="1552" alt="screen shot 2015-10-24 at 2 28 52 pm" src="https://cloud.githubusercontent.com/assets/435953/10712590/9b0216c6-7a5b-11e5-922e-586ffb92e751.png">

**Comment by abrookbanks** [comment]
You are correct in that it doesn't need deleting with a v5 to v6 upgrade. I'm not sure what has caused this issue. I'd estimate that I have upgraded 200+ v5 to v6 stores now and have never seen this problem. Please raise a support ticket if you require any further assistance.

**Comment by rylanb** [comment]
Just to note per my edit that I had to go into the CubeCart_modules database table and turn off all shipping modules that had a status of 1 to 0.

**Comment by bhsmither** [comment]
Similar to this issue is a fix #270 that tested for the existence of the module.

The problem with having made 200+ upgrades is that you have forgotten how to screw it up.<grin>

**Comment by abrookbanks** [comment]
OK so this will happen if the v3 or v4 store had the by category module and it hasn't yet been reinstalled for v6. I've been able to reproduce this and fix is on its way..

**Comment by abrookbanks** [comment]
Thanks for your patience with me folks. This issue only occurs under quite a specific upgrade pattern.

**Comment by bhsmither** [comment]
Please re-examine the statement added for this fix.
```
$ship_by_cat = array('status', false);
```
This statement assigns to `$ship_by_cat` the array:
```
[0] => (string) "status"
[1] => (bool) false
```
I believe this is was not your intent as evidenced by `$ship_by_cat['status']` being true or false.

Suggest:
```
$ship_by_cat = array('status' => false);
```

**Comment by abrookbanks** [comment]
Thanks Brian!
