### ISSUE TITLE
Suggest Maintenance Open to Rebuild Tab

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#72]
My most common use of Maintenance is to Empty Cache or Rebuild Sitemap. Maybe that's not true for the majority. If it is, I suggest making the Rebuild Tab first in the Maintenance screen, so clicking it automatically opens that tab first.

**Comment by abrookbanks** [comment]
Your wish is my command. (I watched Aladdin last night). RIP Robin Williams.
