### ISSUE TITLE
Import Catalogue Cannot Unlink(importdata.tmp)

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#721]
In products.import.inc.php, line 270, $source is `$in = fopen()`'d for reading and used to create sub-files. The sub-files are properly `fclose()`'d, but not `$in`.

Later, $source is opened again to get the header row, and closed.

Next, an attempt to unlink($source) fails because the file is still open for reading.

**Comment by abrookbanks** [comment]
Thanks Brian.
