### ISSUE TITLE
When printing order in admin area with swedish characters CC 6.0.6 doesn't show them correct

### ISSUE THREAD

**Issue by demand73** [cubecart/v6#722]
When printing order in admin area with swedish characters in the form like name or address CC doesn't show the swedish characters correct (ÖÄÅöäå).
But if i do it from users account pages or the Print Order Form it works fine.

![admin-area](https://cloud.githubusercontent.com/assets/12296274/9056470/74acc4ce-3a93-11e5-976e-925311e27316.jpg)
![account-area](https://cloud.githubusercontent.com/assets/12296274/9056478/81154db2-3a93-11e5-8a8a-c2f27eea9cb7.jpg)

**Comment by Noodleyman** [comment]
looks like a database collation issue. What collation is your database in?

**Comment by demand73** [comment]
Well if it was DB related it shouldnt work in shop interface. The problem exists only when printing from admin area. When printing for example the recipt as customer it works fine and its related to the routine that makes the printable page in admin area does not encode foreign characters. In the shop area it does that. Have a idea for a fix but not the time until the weekend. I have UTF8. 

/Krister

**Comment by Noodleyman** [comment]
I've seen this exact behaviour when the DB was having collation issues, specifically related to the printed form.

What specifically is your database collation set to?

is this a new / clean install or an upgraded store that already contains data etc?

**Comment by demand73** [comment]
Its utf8_unicode_ci and in the the tables also. This is a new clean install of 6.0.1 that have been upgraded when new releases have come.

I also have a webshop that’s upgraded from 4.x.x on a different server that does the same and I did a clean 6.0.6 install and just added a customer and a manual order and it still messes up characters.. 

 

 

Från: Noodleyman [mailto:notifications@github.com] 
Skickat: den 6 augusti 2015 18:02
Till: cubecart/v6
Kopia: demand73
Ämne: Re: [v6] When printing order in admin area with swedish characters CC 6.0.6 doesn't show them correct (#722)

 

I've seen this exact behaviour when the DB was having collation issues, specifically related to the printed form.

What specifically is your database collation set to?

is this a new / clean install or an upgraded store that already contains data etc?

—
Reply to this email directly or view it on GitHub <https://github.com/cubecart/v6/issues/722#issuecomment-128419000> . Web Bug from https://github.com/notifications/beacon/ALugUjb4wcMmczRkxKdagsnV4D9IOl-Vks5ok3yKgaJpZM4FlIAv.gif<http://www.mailscanner.tv/1x1spacer.gif> 


-- 
This message was scanned by ESVA and is believed to be clean. 
Click here to report this message as spam. <http://www.demand.nu:7777/cgi-bin/learn-msg.cgi?id=9940C27F04.AFD82>

**Comment by demand73** [comment]
If using the wrong collation the characters looks bad in the admin arean just looking at a customer’s info in the web gui.. In my case it looks fine until I click the print out button and the print out page loads.. then it messes up.

 

Från: Noodleyman [mailto:notifications@github.com] 
Skickat: den 6 augusti 2015 18:02
Till: cubecart/v6
Kopia: demand73
Ämne: Re: [v6] When printing order in admin area with swedish characters CC 6.0.6 doesn't show them correct (#722)

 

I've seen this exact behaviour when the DB was having collation issues, specifically related to the printed form.

What specifically is your database collation set to?

is this a new / clean install or an upgraded store that already contains data etc?

—
Reply to this email directly or view it on GitHub <https://github.com/cubecart/v6/issues/722#issuecomment-128419000> . Web Bug from https://github.com/notifications/beacon/ALugUjb4wcMmczRkxKdagsnV4D9IOl-Vks5ok3yKgaJpZM4FlIAv.gif<http://www.mailscanner.tv/1x1spacer.gif> 


-- 
This message was scanned by ESVA and is believed to be clean. 
Click here to report this message as spam. <http://www.demand.nu:7777/cgi-bin/learn-msg.cgi?id=9940C27F04.AFD82>

**Comment by abrookbanks** [comment]
I can't reproduce this. I expect too that its an encoding issue too. Maybe at database level if not table level. If you can send a tech suport ticket we can take a look for you. My findings below (including a pic of me when I was 4 impressing granny).

![screen shot 2015-08-19 at 10 41 01](https://cloud.githubusercontent.com/assets/4520803/9353272/0b6037c6-465f-11e5-8946-37d8d51c3d30.png)

**Comment by demand73** [comment]
I did find the error just in case anyone else stuble on this.. In my case the default charset in httpd.conf was set to iso-8859-1 and not UTF-8. Strange thou that it only shows in Admin area.

**Comment by abrookbanks** [comment]
Ok so the charset of PHP was wrong. Pleased its fixed.
