### ISSUE TITLE
CKEditor messing with Smarty variables in documents

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#723]
When using the "Parse Smarty Tags" option within documents, the ckeditor is messing with the variables

1) It replaces the double quotes character (") with `&quot;` which then causes a compile syntax error if the document is saved again as it complains about the `&`

2) It adds `<p>` and `</p>` around smarty {if}, {else} and {/if} - in fact around probably any smarty syntax

**Comment by Dirty-Butter** [comment]
GitHub messed up the examples you meant to show - maybe markdown will display it properly??

**Comment by havenswift-hosting** [comment]
Thanks - updated and added a bit more explanation as well

**Comment by abrookbanks** [comment]
I honestly think we have to ditch rich text editor for any content with smarty. I have tried EVERYTHING.

At best I can make it ignore smarty variables but they they don't even show in the rich text editor which is no good. Right now we have a fudge which works for most smarty code but not all.  

I don't know if there is another editor we can replace CKEditor that works with smarty too. I'm giving up on trying to resolve issues around CKE and Smarty.
