### ISSUE TITLE
Tax May Not Get Applied to Shipping

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#725]
In Cart->loadShippingModules(), there is:
```
$packages_with_tax[] = array_merge($package,array('tax' => $GLOBALS['tax']->productTax($package['value'],$package['tax_id'],$package['tax_inclusive'],0,'goods',false)));
```
The `0` is to identify the `$state` (numerical state_id of the "tax on billing|delivery address"), and the `'goods'` is to identify `$type` (what this tax applies to 'goods'|'shipping') in the function's argument list.

This is not a correct list of arguments to calculate the tax on shipping `$packages`.

Suggest:
```
public function loadShippingModules() { dbgClue(__METHOD__);

  if (($shipping = $GLOBALS['db']->select('CubeCart_modules', array('folder', 'countries'), array('module' => 'shipping', 'status' => '1'))) !== false) {
    $tax_on = ($GLOBALS['config']->get('config', 'basket_tax_by_delivery')) ? 'delivery_address' : 'billing_address';
```
```
$packages_with_tax[] = array_merge($package,array('tax' => $GLOBALS['tax']->productTax($package['value'],$package['tax_id'],$package['tax_inclusive'],$this->basket[$tax_on]['state_id'],'shipping',false)));// 0,'goods',false)));
```
In Cart->get(), near line 805, is a correct call that calculates taxes on shipping for the Per_Category module.

**Comment by abrookbanks** [comment]
Thanks for this Brian.
