### ISSUE TITLE
Populate Products smarty variable missing tax information

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#728]
Smarty variable $POPULAR_PRODUCTS does not contain "tax_type" or "tax_inclusive" however this information IS available in all other areas of the store in product variables.

Can this please be added to keep it in line with other areas of CubeCart?

**Comment by bhsmither** [comment]
$POPULAR_PRODUCTS is a string that is the final rendered template box.popular.php and matches the skin that is in use.

I, too, am disappointed the data collected for the template is very limited.

The $POPULAR variable holds the same product data in an array. The function `GUI->_displayPopularProducts()` can simply gather x-number of product_ids, then sending the bunch to Catalogue->getProductData().

My main gripe is that there are too many custom queries, when Catalogue->getProductData() can be used for nearly everything.

**Comment by abrookbanks** [comment]
I don't like this either. I'm going to put this as a feature request to get uniform data with consistency for a future release.

**Comment by Noodleyman** [comment]
any movement on this feature request?
