### ISSUE TITLE
Animated Gifs don't work.

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#729]
If you use the file manager to upload an animated gif to a category image, when viewing from the store front it only ever shows the still image.

It looks like the cache process actually breaks it by only taking the first frame.

**Comment by havenswift-hosting** [comment]
This is almost certainly GD that is doing this - as standard it doesnt work with animated gifs although there are solutions available

**Comment by Noodleyman** [comment]
work around is to manually upload the files elsewhere and link to them, although not ideal. would be nice if there was a solution for it to avoid hassle

**Comment by abrookbanks** [comment]
Thats right GD can't work with animated gif. :(

**Comment by Noodleyman** [comment]
It is actually possible, just requires a bit of effort to get right. There is a class which can do this with minimal effort here:
http://www.phpclasses.org/package/7353-PHP-Resize-animations-in-files-of-the-GIF-format.html

Essentially it's a case of detecting if an animated gif has been uploaded. if it has you have to break it out frame by frame. resize each frame then merge back to an animated gif.

**Comment by abrookbanks** [comment]
I changed it to a feature request. I can't see this being implemented though unless the demand is there.

**Comment by Noodleyman** [comment]
a more simple work around.. don't resize animated gif's.

**Comment by abrookbanks** [comment]
Well that sounds simple but not immediately straightforward in practise.
