### ISSUE TITLE
Product checkbox to toggle coupons or sale pricing

### ISSUE THREAD

**Issue by tbonerocketeer** [cubecart/v6#730]
I would like to see a check box created under the product that can be checked to allow coupons or sale pricing or unchecked to not allow them. I have many items that I cannot offer discounts on due to selling agreements or profit margins so I would like the site to not allow them if I run a x% off sale, or a coupon code. I would accept a category restriction for the same thing as well.

**Comment by bhsmither** [comment]
Would you be willing to beta test a solution I have just now finished(?) writing? It's a global setting. If the product is on sale, then no coupon can accept that product for a discount.

This doesn't precisely match your criteria. A store sales mode of "Global Percentage" puts all products on sale, so then with this solution, no coupon could be used.

"Coupon does not include items on sale." I've seen that in B&M stores a lot.

**Comment by tbonerocketeer** [comment]
I might be able to. I'm not fully following what this does though. If an item is on sale, then coupons won't work?

**Comment by bhsmither** [comment]
The edits will cause CubeCart to not allow the coupon to discount any item that is on sale. The discount will apply to any item that is not on sale as otherwise permitted.

**Comment by tbonerocketeer** [comment]
I can't run full store sales as some products are not allowed to be discounted per manufacture agreements.

Thanks 
Chris Short

**Comment by bhsmither** [comment]
I conclude that you will then necessarily put the store in "Per Product" sales mode. Thus, any product where the sale price is greater than zero and less than the retail price will be on sale at the sale price.

The fact that an item is on sale could be construed as *having a discount*. Applying the value of a coupon against the order, or specific items in the order, is also construed as *having a discount* against the item. But for the purposes of clarity, I wish to keep distinct the concept of an item being on sale and an item enjoying a coupon-based discount.

If the store setting is to not allow items on sale to be discounted with a coupon, then the item will still sell at the sale price, not at the sale price less the discount offered by the coupon.

Now, as for items that must be sold at retail, period, a coupon then must be constructed such that it **excludes** these specific items. Or, if it is more feasible, **include** only those items you want to push harder.

I have not lost sight of the fact that you may want to offer a "Black Friday" sale where everything (if allowed) is on sale at 5% off. (Except where such identified products cannot be on sale.)
