### ISSUE TITLE
FedEx: Test for SOAP

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#731]
It appears that the extension SOAP can be tested for.

Suggest that the admin control panel for FedEx include a test for SOAP if SOAP not enabled/available, display a warning banner.

**Comment by abrookbanks** [comment]
Done thanks!! Also corrected GPL license version, email address and config.xml file for version numbers. 
![screen shot 2015-08-19 at 10 02 36](https://cloud.githubusercontent.com/assets/4520803/9352530/d972fa0a-4659-11e5-8df1-557085af9eab.png)
