### ISSUE TITLE
Account creation and field parsing bug

### ISSUE THREAD

**Issue by ellermanj** [cubecart/v6#736]
Identified in 6.0.6.

If I create a user account with a space after the title (eg: "Mrs " with a space at the end of the word Mrs), the account does some strange things.  I can create the account just fine as a user, I can set all the user details and save the account, but when I try and log in to the website to place an order, it sends me into an endless loop, and doesn't actually log me in.  Rather than giving me an "invalid name or password" error, it just refreshes the same page as if I haven't even logged in, asking for my username and password again, and not logging me in.

I haven't tested other combinations of spaces before and after the titles, names, passwords, etc, but it would appear that there needs to be more checking of the field data before it does into the database. It creates a user account that can never be logged into, unless the admin deletes the space at the end of "Mrs " and saves the account.

**Comment by ellermanj** [comment]
Seems like it may also be happening if there is a space in other fields too, like a street address.

**Comment by abrookbanks** [comment]
Fixed trim of white space on user data and address. I've not been able to reproduce the endless loop with the given steps to reproduce. I expect something else is causing it. If you can log a support ticket or provide steps I can reproduce we can take a look again.
