### ISSUE TITLE
Site Document Stripping Content

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#743]
Try to save a site document with this:
```<i class="fa fa-angle-double-right" style="color: #F4DB5A;"></i> ```
and it will get stripped out completely.

**Comment by abrookbanks** [comment]
I think its time we ditched FCKEditor.

**Comment by abrookbanks** [comment]
You might be able to work around it with something crappy like:

```<i class="fa fa-angle-double-right" style="color: #F4DB5A;">&nbsp;</i>```

**Comment by abrookbanks** [comment]
This issue concerns 3rd party code.
