### ISSUE TITLE
Issues with Product Feeds

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#745]
Ran into an issue today in CC 606 which had the most recent version of "Google Base" and "Shopping.com" product feeds installed

google merchant was throwing lots of errors. Whilst looking into it I found that the google base URL was actually returning the shopping.com file format.

Once I disabled the shopping.com feed the same URL loaded the google feed data correctly.

Looks to be a bug in the way multiple feed modules behave together.

**Comment by abrookbanks** [comment]
Thanks Alec, it was a bug in the shopping.com plugin. I've released 1.0.1 into the marketplace.
