### ISSUE TITLE
Can add line breaks in language strings when editing

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#751]
> I just modified the text template for Contact Form by following: Settings > Languages > English (UK) > Contact > email_content. I changed the default to:

> %s <%s> wrote on the Contact Form%s: %s

> The problem is that I don't know how to insert a line break right before the %s at the end. I tried to use \n, but it appears the html tag got stripped by the strip_tags function. I remember the default text template can give line breaks. However, now it cannot even after I clicked the "revert" button.

**Comment by bhsmither** [comment]
Related to various other reports.

One of which was to set an attribute on the <string> node to flag if this string *obviously* should be shown as a muti-line text area instead of a text input.
