### ISSUE TITLE
CubeCart_image_index - duplicate entries after product image selection edit

### ISSUE THREAD

**Issue by RedKiteDesigns** [cubecart/v6#753]
The image_index table fills up with duplicate rows as you edit which images a product will use.
My development site has three products: two have three images each and one has just two.

After editing the image selection for product_id = 2 the index table looks like this

![image_index](https://cloud.githubusercontent.com/assets/13659798/9466022/68521fac-4b29-11e5-9e64-cd9f20e30360.jpg)

It doesn't seem to cause any problems but it's obviously nonsense.

db sana in application sano !!!

**Comment by Noodleyman** [comment]
I've also seen this behaviour

**Comment by RedKiteDesigns** [comment]
Further investigation reveals more interesting points about product images.

If you clear all the image check boxes for a product and click 'save and reload':
- all the entries for that product in image_index are cleared
- but when the page reloads the filemanager window is completely empty and un-navigable
- so you have to go back to 'products' and work forward to re-select images.

I hope to investigate further and maybe even find a proper fix!

**Comment by RedKiteDesigns** [comment]
And here is the fix ...

admin/sources/products.index.inc

Line 372: 
```php
	if (!in_array($image_id, $removed_images)) {
```
Change to:
```php
	if (!in_array($image_id, $removed_images) && !in_array($image_id, $img_add)) {
```

**Comment by Noodleyman** [comment]
Best to have this re-opened so it gets fixed in the next release of CubeCart

**Comment by abrookbanks** [comment]
Thanks Clive, I've rolled this into the master build now.

**Comment by RedKiteDesigns** [comment]
Hi Noodleman

 

Closed by mistake – Al has reopened & re-closed it now.

 

ATB

 

Clive
