### ISSUE TITLE
Improve the Customer Search function in admin area

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#758]
This ideally should also search for customers based on address, company name etc.  Currently it only searches based on last name, first name and e-mail address

Should be a simple case of enhancing the SQL query as defined in ajax.class.php on line 73. Join to address book, return distinct values etc. 

if (($results = $GLOBALS['db']->select('CubeCart_customer', false, array('~'.$search_string => array('last_name', 'first_name', 'email')), false, false, false, false)) !== false) {

**Comment by abrookbanks** [comment]
Definitely room for improvement here. Thanks for this Alex. "concat" could be handy too for first and last name.

**Comment by Noodleyman** [comment]
might be a good idea to double check the table indexes as part of the update to ensure fast searching ;)

Also, more of a minor annoyance is that when you select a customer from the instance search, it takes you to the customer, making the submit button below unnecessary. If you click the submit button after making a selection you get a security error and have to do the whole thing again. I would recommend either removing the submit button from the admin search, or disable the button using a script on click of a search result.

**Comment by abrookbanks** [comment]
I've made the search button disable on "drop down" click for 6.0.7 :)

**Comment by Noodleyman** [comment]
yayyyyyyyy :dancer:

**Comment by havenswift-hosting** [comment]
We are in the final stages of development of our Enhanced Admin Order Entry plugin for V6 and the only functionality from our V4 mod that is pretty much impossible to add without changing core code is the enhanced search which this would cover extremely well.  Any chance this could be added for inclusion in 6.0.8 please ?

**Comment by Noodleyman** [comment]
This is now possible using this module:
https://www.cubecart.com/extensions/plugins/enhanced-admin-order-entry
