### ISSUE TITLE
Feature Request - Check for php-xml when installing

### ISSUE THREAD

**Issue by demand73** [cubecart/v6#760]
When installing a new CC it would be nice if it checked for php-xml in the requirements check. It took a while for me to figure out why exporting languages and sitemap didn´t work and gave me a 500 message.

**Comment by abrookbanks** [comment]
![screen shot 2015-09-02 at 08 42 31](https://cloud.githubusercontent.com/assets/4520803/9625505/a098478a-514e-11e5-98d5-03e7d7530193.png)

**Comment by abrookbanks** [comment]
Thanks for this! :)
