### ISSUE TITLE
Worldpay Payment Gateway Module - Redirect issues

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#762]
After making a payment with the worldpay gateway module, worldpay calls the return URL. The order status becomes updated to processing but there is no redirection from the worldpay payment summary page.

This means the customer basket does not get reset / cleared between orders.

**Comment by havenswift-hosting** [comment]
I can also confirm this - we have a client using WorldPay that also has the same problem although interestingly this did used to work ?!

**Comment by abrookbanks** [comment]
Can you set the return URL to be like this...

http://www.example.com/store/index.php?_a=complete

**Comment by Noodleyman** [comment]
Nope, because that wouldn't trigger the update of the order status via the module. The current return URL uses return.php within the module itself.

**Comment by abrookbanks** [comment]
can you not add that as well as the call URL? Alternatively... change the URL to have 

```cmd=call```
instead of
```cmd=process```

The in the gateway.class.php file move the code in the call method to the process method.

I think I tried that and never got it to work.

**Comment by Noodleyman** [comment]
Not tested this as I haven't time today, but I think the processing of "complete" in the URL happens before the loading of the module, so it would either be one or the other.

I think the module itself needs an update to use the most recent methods as per the developer guide.

See page 35..
http://support.worldpay.com/support/kb/bg/pdf/rhtml.pdf

**Comment by abrookbanks** [comment]
I honestly don't this this is possible.. However I do see a great work around here:

http://stackoverflow.com/questions/8232607/how-do-i-create-returning-page-setting-with-worldpay

Create a page for success and fail with:

```<p><a href="http://www.example.com/store/index.php?_a=complete">Redirect back to my shop</a></p>```

**Comment by abrookbanks** [comment]
Nothing to change. The above can be implemented if you want.

**Comment by Noodleyman** [comment]
The article is no longer valid as you don't upload pages to the worldpay config area.

there are variables to pass with config in them.

To solve this issue the following needs to be added to the $hidden array in the gateway.class.php file


'successURL' => $GLOBALS['storeURL'] . '/index.php?_a=complete'

**Comment by abrookbanks** [comment]
Thanks Alec .. 1.0.3 released.
