### ISSUE TITLE
Gift Certificates not being sent to recipient

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#764]
See thread https://forums.cubecart.com/topic/50238-gift-cerificate-not-being-sent/

**Comment by abrookbanks** [comment]
This works for me. Maybe there is a specific condition to reproduce this.

**Comment by abrookbanks** [comment]
The code does send the email from the email address set in the stores settings with a header of "Reply-To" as the recipient. It could be blocking the email actually sending based on it not liking that.

**Comment by The-Model-Tree-Shop** [comment]
This still appears to be an issue for my customers - does anybody have the fix?

**Comment by The-Model-Tree-Shop** [comment]
I changed the setting in Store Settings/Features for Force Order Completed Emails to enabled - then the system didn't send emails. I have re-entered my password & saved and now gift certs get sent! and emails are being sent :-)
Merry Christmas
Steven

**Comment by havenswift-hosting** [comment]
Hi Al

It looks like the  "Force Order Completed Emails" settings needs to be enabled for Gift Certificate emails to be sent !

Ian
