### ISSUE TITLE
Mobile device Hamburger and Search symbol

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#766]
![screenshot_2015-08-29-12-48-43](https://cloud.githubusercontent.com/assets/10808588/9560241/d3015842-4e4c-11e5-92a9-47014b5b2c19.png)
These 2 symbols have dropped down on mobile devices and leaves a lot of empty space. They need to be move back to  the top as they were before.

**Comment by abrookbanks** [comment]
I :heart: hamburgers! 

I can't reproduce this. What device are you using?
![screen shot 2015-09-01 at 17 53 45](https://cloud.githubusercontent.com/assets/4520803/9610591/781afbe4-50d2-11e5-8032-c203be1e72fb.png)

**Comment by abrookbanks** [comment]
## iPhone below ##

![photo 01-09-2015 17 55 06](https://cloud.githubusercontent.com/assets/4520803/9610620/bc0b3cba-50d2-11e5-9a73-4b8f10c080cf.png)

**Comment by bondimedical3** [comment]
![iphone5](https://cloud.githubusercontent.com/assets/10808588/9622162/c97b039e-5172-11e5-8d2b-ce36af8f4e7d.jpg)
I have used an iPhone 5 simulation website and the same issue is there. I myself have tried it on the Samsung Galaxy S3, S4 and S5 all of which have the issue. I am not sure how you got your iPhone to work, have you cleared the browsing data on your phone?

**Comment by abrookbanks** [comment]
I changed logo to be 40% then button to 60% instead of 50/50 to make sure it looks right on all small devices.

**Comment by abrookbanks** [comment]
## Result ##
![photo 01-09-2015 17 55 06](https://cloud.githubusercontent.com/assets/4520803/9624491/6752e54c-5145-11e5-9f07-62f6c11c5974.png)

**Comment by bondimedical3** [comment]
Hello AL. In the fix for this you have not included medium devices. Is this correct?

**Comment by abrookbanks** [comment]
No need from my testing.. 
![screen shot 2015-09-03 at 08 24 38](https://cloud.githubusercontent.com/assets/4520803/9652669/62d5c0e0-5215-11e5-9c3f-ee25413b4ea1.png)
![screen shot 2015-09-03 at 08 24 49](https://cloud.githubusercontent.com/assets/4520803/9652671/65b86d94-5215-11e5-809c-a0b2dd244c0b.png)
![screen shot 2015-09-03 at 08 25 03](https://cloud.githubusercontent.com/assets/4520803/9652672/69840e38-5215-11e5-850a-ae607b1c535f.png)
![screen shot 2015-09-03 at 08 25 17](https://cloud.githubusercontent.com/assets/4520803/9652677/6d5e2d7c-5215-11e5-9d69-770693699219.png)
![screen shot 2015-09-03 at 08 25 25](https://cloud.githubusercontent.com/assets/4520803/9652683/6fd59450-5215-11e5-9d59-e012ce90fa8d.png)
