### ISSUE TITLE
Unnecessary Category link on mobile devices 

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#767]
![screenshot_2015-08-29-12-48-59](https://cloud.githubusercontent.com/assets/10808588/9560269/69e4667c-4e4e-11e5-9fb8-7c0f4571c62f.png)
The link "TV & Home Cinema" is unnecessary on this page and confuses customers. It provides no value as the page itself has no links and needs to be removed as has been done on medium devices.

**Comment by abrookbanks** [comment]
This is a duplicate and fixed in a recent release. It was a bug in the version of Foundation Framework used. Please upgrade your skin or Foundation Framework to latest version.

**Comment by bondimedical3** [comment]
I have just installed CubeCart 6.0.6. You had the same issue on medium devices and this has been fixed. I am talking about small devices. That screenshot is from your own demo store?

**Comment by abrookbanks** [comment]
Yes that's the demo store. I'm sure this is resolved in a past update. It even affected our website which was using an old version of foundation framework. If you are in 6.0.6 then I think your skin is out of date.

**Comment by bondimedical3** [comment]
How can the skin be out of date when it came with 6.0.6?

**Comment by abrookbanks** [comment]
If you have customised your skin and renamed the folder to prevent changes getting overwritten on upgrade your skins is still on its original version. This is not an issue in the latest build.

**Comment by bondimedical3** [comment]
I haven't customized the skin, renamed folders or anything. The issue is even on your own demo store?

**Comment by abrookbanks** [comment]
I think its supposed to be like that then. You are free to make any customisations you want.

Documentation here: http://foundation.zurb.com/docs/components/topbar.html

**Comment by bondimedical3** [comment]
It is a pointless link. There are no links to categories on the page and it has been removed for medium devices. It should be removed for small as well.

**Comment by abrookbanks** [comment]
If you want to change the default functionality that is the official documentation for how the Foundation Framework works. If you are not technical to make the customisations you'll need to find someone who is. CubeCarts Foundation skin is built with the default functionality of the Foundation Framework.
