### ISSUE TITLE
Card Capture Bug

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#768]
![screenshot_2015-08-29-13-18-11](https://cloud.githubusercontent.com/assets/10808588/9560324/a6ae4652-4e50-11e5-8482-40a9f8ec7b34.png)
When you click the "What's this" link for CVV the image has the word "undefined"?

**Comment by abrookbanks** [comment]
Thanks this has been fixed with 1.0.3 release of the extension.
https://www.cubecart.com/extensions/payment-gateways/credit-card-capture
