### ISSUE TITLE
Mobile Address Book Bug

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#774]
![screenshot_2015-08-30-15-48-23](https://cloud.githubusercontent.com/assets/10808588/9565895/c4f0ca52-4f2e-11e5-8952-c9e1b3e57b96.png)
The address book on small devices has badly overlapping text. Please fix.

**Comment by abrookbanks** [comment]
Thanks for this. Solution screenshot below.. 
![screen shot 2015-09-01 at 17 34 11](https://cloud.githubusercontent.com/assets/4520803/9610169/c886ce1c-50cf-11e5-84d5-7924ea2ae9dd.png)
