### ISSUE TITLE
Mobile Your Account page Bug and overall Mobile site Bug

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#775]
The Your Account page in the customers profile has a border on the left but nothing on the right hand side? There is also an issue with left hand and right hand borders on the whole mobile site, there are none and all text, buttons, images etc touch the edge of the screen?

**Comment by abrookbanks** [comment]
The mobile skin is for v5. It's not part of the v6 package. It can be tweaked with any CSS changes you want.

**Comment by abrookbanks** [comment]
Did you mean Foundation skin in "small" (mobile) view? A screenshot would help loads if you have time.

**Comment by bondimedical3** [comment]
Yes. I am talking about the Foundation skin in mobile view. You should be able to see the issues on your own demo store.

**Comment by abrookbanks** [comment]
Thanks I'll try that..

**Comment by abrookbanks** [comment]
Thanks for this.
