### ISSUE TITLE
Hook Can Kill Gateway Callback Execution

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#776]
In cubecart.class.php, near line 204, we start with a `switch($_GET['_g'])` to `case:rm` or `case:remote`.

Then we `switch($mod_type)` which the only two valid choices are **plugins** or **gateway** (`case:plugins` or `case:gateway`) - which does not matter as yet.

We next call for any `hooks`, followed immediately by testing if `$plugin` is set.

The assumption is that the hook will set a value to `$plugin` if appropriate. `$folder` is then set to 'plugins' or 'gateway'.

The problem is that if an enabled hook sets `$plugin`, *for any reason*, even when the plugin does not have anything to do with the gateway being called back, the appropriate `$class_file` for the gateway will not get loaded.

This hook is the only hook for the ['_g'] switch case.

The code in this case strongly implies that ['_g'] is the key to use for ajax and other requests for small snippets of data, and empty-content responses (just a 200 OK is sufficient).

On the other hand, the only name of the file to get included is a gateway class file, so the implication is that whatever hook is in play had better identify a gateway that works like a gateway.

But if this one and only hook simply sets `$plugin`, then no other remote gateway will work.

**Comment by bhsmither** [comment]
Suggest for switch($_GET['_g']), case:default, a hook be implemented similar to switch($_GET['_a']), case:default.

Perhaps named: class.cubecart.construct.callback.ajax

**Comment by abrookbanks** [comment]
I added a warning. I'm not entirely sure what else can be done. PayPal Pro/Express uses this hook I believe which is very popular.
