### ISSUE TITLE
AddThis widget SSL Bug

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#778]
The last icon which opens all the other Bookmark sites does not reference https but is only http?

**Comment by abrookbanks** [comment]
I can't reproduce this. Please can you submit a tech support ticket or provide more information.
![screen shot 2015-09-01 at 17 24 30](https://cloud.githubusercontent.com/assets/4520803/9609972/9197475c-50ce-11e5-8812-cb28904ebf49.png)

**Comment by bondimedical3** [comment]
Hello Al. I am not talking about the AddThis widget breaking the SSL. I am talking about when you move a website over to SSL. Whenever you do this you must ensure every element of the website uses HTTPS, this includes widgets, javascript, CSS files, images and CDN's. If you hover your mouse over the last + icon in the AddThis widget you will notice the url is http. This can also be seen in the source code for the page?

**Comment by abrookbanks** [comment]
Default functionality in CubeCart or any CubeCart developed extensions will switch over with SSL with no problem. Please avoid absolute links in documents and code customisations where possible. 

This will always be an ongoing issue and there is no automated fix that can be applied.

**Comment by bondimedical3** [comment]
That link should be to changed to https. Even AddThis have a https version of the page. You need to update your code. You don't have half the widgets on an https site still running http?

**Comment by abrookbanks** [comment]
No change is needed. Anchor links in a secure page do not need to be under SSL as no external data is loaded into the page.
