### ISSUE TITLE
Additional Options causing error that won't go away...

### ISSUE THREAD

**Issue by BN83** [cubecart/v6#779]
When you don't select an option in the dropdowns, it comes up with:

"The following errors were detected: Please select required options before adding to your basket."

and adds "?error=option" to the URL. However when you then correct the error, it doesn't seem to remove the error, however it does add the item to the basket.

Any solutions?

**Comment by abrookbanks** [comment]
I can't reproduce this. Movie here: http://static.cubecart.com/github-779.mp4

Please provide screenshot and/or steps to reproduce.

**Comment by BN83** [comment]
Sorry, should've added its drop down menus.

https://www.thebimstore.com/hardware/workstations/start-bim-suite-and-workstation.html

**Comment by abrookbanks** [comment]
This is an issue with a 3rd party skin. Please seek support from your developer or raise a tech support ticket with our staff.
