### ISSUE TITLE
Printing invoice from admin area not working?

### ISSUE THREAD

**Issue by BN83** [cubecart/v6#780]
When you go to print an invoice from the admin area, it's going to the page with this in the address bar:

admin.php?_g=orders&node=index&sort%5Border_date%5D=DESC&print%5B0%5D=150827-012142-9573

But then just loading the page with the list of orders?

**Comment by abrookbanks** [comment]
I can't reproduce this. Please can you send a tech support ticket if you need us to take a look. 

Thanks.
