### ISSUE TITLE
Card Capture Bug #2

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#784]
![screenshot_2015-09-03-16-25-38](https://cloud.githubusercontent.com/assets/10808588/9651800/9ee58d98-5258-11e5-83c1-25837eabf7c4.png)

The expiry date and security code boxes are too small on mobiles?

**Comment by bondimedical3** [comment]
Similar issue on medium devices

**Comment by abrookbanks** [comment]
Thanks this is fixed in CardCapture-1.0.5.zip

**Comment by bondimedical3** [comment]
![screenshot_2015-09-04-12-28-42](https://cloud.githubusercontent.com/assets/10808588/9675430/b9d9a1c2-5300-11e5-8fbc-540b24df8bbc.png)
The mobile version still looks bad. The beginning of the word Sept shows in the first box where the down arrow is and the year is obscured by the down arrow?

**Comment by abrookbanks** [comment]
It's not responsive at all. I fudged in a few bits for a slight improvement. Maybe I'll release a responsive version of this module.
