### ISSUE TITLE
CC Security Mod wording, checkbox issue

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#785]
I do have some criticism of the mod's wording that says to Please add your IP address to Trusted Sites. There is no indication this should only be done if it is a Dedicated IP.

After Ian fixed my 403 issue I decided to try leaving my IP address as trusted, but to Disable Use only trusted IP and just get an email if an untrusted IP logged in.

But I discovered that if there IS a trusted IP in the list - it is not possible to save the plugin setting with use only trusted IP to login unchecked - it checks itself back on Save!

**Comment by abrookbanks** [comment]
If you don't have a dedicated IP address "Only allow trusted IP addresses to login" must not be enabled. I'll add a note.

**Comment by abrookbanks** [comment]
![screen shot 2015-09-03 at 16 32 41](https://cloud.githubusercontent.com/assets/4520803/9662856/6b7dfdea-5259-11e5-9777-958c668ac4b7.png)

**Comment by Dirty-Butter** [comment]
IF there is a trusted IP listed, it is not possible to leave the Allow only checkbox unchecked. It fills itself on Save.

**Comment by abrookbanks** [comment]
Fixed with 1.0.3. Thanks Rosemary and thanks for your patience. 
https://www.cubecart.com/extensions/plugins/cubecart-security-suite
