### ISSUE TITLE
Feature Request - exclude products from sitewide sale and discounting with coupons

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#786]
See thread https://forums.cubecart.com/topic/50161-feature-request/

**Comment by abrookbanks** [comment]
Thanks!

**Comment by Noodleyman** [comment]
@abrookbanks , this feature was requested again on the forums today by somebody else. Can you clarify where this feature sits on the development roadmap?

Thanks,

**Comment by abrookbanks** [comment]
You are very welcome to form and pull request Alec.

**Comment by Noodleyman** [comment]
Sure, if somebody wants this feature bad enough and is willing to pay for my time to write it, I am more than happy to add it to the core product.

**Comment by abrookbanks** [comment]
I didn't mean to close this.
