### ISSUE TITLE
Major conditional block error in edit product region

### ISSUE THREAD

**Issue by hairydogltd** [cubecart/v6#79]
When installing  CC6b2 from scratch, or after upgrading a fresh install of CC5, if there are no product options set up, it is not possible to add or edit products.

**Comment by abrookbanks** [comment]
Steps to reproduce?

**Comment by hairydogltd** [comment]
It's pretty easy to reproduce: do a clean install and try to add a product or edit the sample product.

I've installed 6b2 twice, and upgraded from a fresh install of 5, always the same.But there isn't much to do a screen capture of: the product details pages are all completely blank.

**Comment by abrookbanks** [comment]
I can't reproduce this at all. Any chance I can take a look at your store? No support plan needed. If you can send the URL, admin login and FTP is possible via our sales dept I'd love to take a look.

https://support.cubecart.com/index.php?/Tickets/Submit

**Comment by hairydogltd** [comment]
Fresh install made, login details sent

**Comment by abrookbanks** [comment]
Thanks. :+1:

**Comment by abrookbanks** [comment]
All seems ok now. I have patched your store  Iain. Thanks for taking the time to report your findings.
