### ISSUE TITLE
Import Catalogue add weight

### ISSUE THREAD

**Issue by bsapackman** [cubecart/v6#796]
NIce if you can add weight when importing other mics categories save lot time 

 thank you

**Comment by abrookbanks** [comment]
From what I can see you already can. Please reply back if I missed something and this can be reopened. 
![screen shot 2015-09-16 at 13 13 21](https://cloud.githubusercontent.com/assets/4520803/9904339/d7cd3766-5c74-11e5-928e-7e031bbb3b86.png)
