### ISSUE TITLE
Cannot save manuualy created order

### ISSUE THREAD

**Issue by QuantumEnt** [cubecart/v6#798]
Just installed 6.0.7 and went to add a new order manually. As soon as the customer was selected from the 'Find Customers' box on the billing tab the Save button disappeared and the order could therefore not be saved. I've rolled back to 6.0.6. until this is fixed.
As a side note, I've noticed that on both 6.0.6 and 6.0.7 when I pull in the customer information for a manual order the word 'Quantum' is added to the Mobile field. This is my user name so it shouldn't be there.

**Comment by abrookbanks** [comment]
Relates to fix for #689

**Comment by QuantumEnt** [comment]
This is not the same issue.

 

Very best regards,

-----------------------------------------------------------------------
Andy Hunt - Quantum Enterprises
4 The Old School House, Lower Sea Lane, Charmouth, Dorset, DT6 6LJ. UK 

 <http://www.quantumenterprises.co.uk/> http://www.quantumenterprises.co.uk/ 

Tel. +44 (0)845 299 7299

 

QUANTUM ENTERPRISES: A WORLD OF ENTERTAINMENT including, 

Handwriting Fonts | Logo Fonts | Handwriting Analysis | The 'Original' Round Tuit | 

Web Design | Web Hosting | Genealogy Detective | Jigsaw Doctor | QE Promotions | 

Fractals | Fossil Beach | Jigfont | Far Future Merchandise | Dream Aquarium

SUBSCRIBE TO OUR NEWSLETTER AT:  <http://www.quantumenterprises.co.uk/newsletter.html> http://www.quantumenterprises.co.uk/newsletter.html

Read our Blog:  <http://www.quantumenterprises.co.uk/blog> http://www.quantumenterprises.co.uk/blog

Follow us on Facebook:  <http://www.facebook.com/quantumenterprisesuk> http://www.facebook.com/quantumenterprisesuk

Follow us on Google+:  <https://plus.google.com/+QuantumenterprisesUk/posts> https://plus.google.com/+QuantumenterprisesUk/posts

Follow us on Twitter:  <https://twitter.com/Quantum_Ent> https://twitter.com/Quantum_Ent

Follow us on Linkedin:  <https://www.linkedin.com/company/quantum-enterprises> https://www.linkedin.com/company/quantum-enterprises

 

--------------------------------------------------------------------------------------------------- 

This E-Mail and any attached files are Confidential and may be legally privileged. 

This e-mail, together with any attachment(s) is for the exclusive and confidential information of the addressee(s). Any other distribution, use or reproduction without the sender's prior consent is unauthorised and strictly prohibited. If you receive this message in error, please notify the sender immediately, and delete the message without making any copies. All text and images in this communication are the copyright of the respective sender and/or Quantum Enterprises. No reproductions are allowed whatsoever without the express written permission of the respective owner, and any such use would be a breach of copyright. 

E-mail transmission cannot be guaranteed to be secure or error free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. No responsibility is accepted by Quantum Enterprises for any loss or damage incurred through use of this e-mail. We advise you to carry out your own virus check before opening any attachment, as we cannot accept any liability for damage received as a result of any software virus.

**Comment by abrookbanks** [comment]
No its not the same issue at all. But the cause relates to the fix of the other issue (hence the reference).

Thanks for reporting this.

**Comment by mackecm2** [comment]
I had the same problem when upgrading to 6.0.7, but applying the fix has resolved it.

**Comment by QuantumEnt** [comment]
Where is the fix?

 

Very best regards,

-----------------------------------------------------------------------
Andy Hunt - Quantum Enterprises
4 The Old School House, Lower Sea Lane, Charmouth, Dorset, DT6 6LJ. UK 

 <http://www.quantumenterprises.co.uk/> http://www.quantumenterprises.co.uk/ 

Tel. +44 (0)845 299 7299

 

QUANTUM ENTERPRISES: A WORLD OF ENTERTAINMENT including, 

Handwriting Fonts | Logo Fonts | Handwriting Analysis | The 'Original' Round Tuit | 

Web Design | Web Hosting | Genealogy Detective | Jigsaw Doctor | QE Promotions | 

Fractals | Fossil Beach | Jigfont | Far Future Merchandise | Dream Aquarium

SUBSCRIBE TO OUR NEWSLETTER AT:  <http://www.quantumenterprises.co.uk/newsletter.html> http://www.quantumenterprises.co.uk/newsletter.html

Read our Blog:  <http://www.quantumenterprises.co.uk/blog> http://www.quantumenterprises.co.uk/blog

Follow us on Facebook:  <http://www.facebook.com/quantumenterprisesuk> http://www.facebook.com/quantumenterprisesuk

Follow us on Google+:  <https://plus.google.com/+QuantumenterprisesUk/posts> https://plus.google.com/+QuantumenterprisesUk/posts

Follow us on Twitter:  <https://twitter.com/Quantum_Ent> https://twitter.com/Quantum_Ent

Follow us on Linkedin:  <https://www.linkedin.com/company/quantum-enterprises> https://www.linkedin.com/company/quantum-enterprises

 

--------------------------------------------------------------------------------------------------- 

This E-Mail and any attached files are Confidential and may be legally privileged. 

This e-mail, together with any attachment(s) is for the exclusive and confidential information of the addressee(s). Any other distribution, use or reproduction without the sender's prior consent is unauthorised and strictly prohibited. If you receive this message in error, please notify the sender immediately, and delete the message without making any copies. All text and images in this communication are the copyright of the respective sender and/or Quantum Enterprises. No reproductions are allowed whatsoever without the express written permission of the respective owner, and any such use would be a breach of copyright. 

E-mail transmission cannot be guaranteed to be secure or error free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. No responsibility is accepted by Quantum Enterprises for any loss or damage incurred through use of this e-mail. We advise you to carry out your own virus check before opening any attachment, as we cannot accept any liability for damage received as a result of any software virus.

**Comment by abrookbanks** [comment]
> Where is the fix?

Click the "Fixed issue" link above.

**Comment by mackecm2** [comment]
... what Al said :)

**Comment by QuantumEnt** [comment]
Ok, thanks.

 

I’m new to Github and still finding my way around.

 

Very best regards,

-----------------------------------------------------------------------
Andy Hunt - Quantum Enterprises
4 The Old School House, Lower Sea Lane, Charmouth, Dorset, DT6 6LJ. UK 

 <http://www.quantumenterprises.co.uk/> http://www.quantumenterprises.co.uk/ 

Tel. +44 (0)845 299 7299

 

QUANTUM ENTERPRISES: A WORLD OF ENTERTAINMENT including, 

Handwriting Fonts | Logo Fonts | Handwriting Analysis | The 'Original' Round Tuit | 

Web Design | Web Hosting | Genealogy Detective | Jigsaw Doctor | QE Promotions | 

Fractals | Fossil Beach | Jigfont | Far Future Merchandise | Dream Aquarium

SUBSCRIBE TO OUR NEWSLETTER AT:  <http://www.quantumenterprises.co.uk/newsletter.html> http://www.quantumenterprises.co.uk/newsletter.html

Read our Blog:  <http://www.quantumenterprises.co.uk/blog> http://www.quantumenterprises.co.uk/blog

Follow us on Facebook:  <http://www.facebook.com/quantumenterprisesuk> http://www.facebook.com/quantumenterprisesuk

Follow us on Google+:  <https://plus.google.com/+QuantumenterprisesUk/posts> https://plus.google.com/+QuantumenterprisesUk/posts

Follow us on Twitter:  <https://twitter.com/Quantum_Ent> https://twitter.com/Quantum_Ent

Follow us on Linkedin:  <https://www.linkedin.com/company/quantum-enterprises> https://www.linkedin.com/company/quantum-enterprises

 

--------------------------------------------------------------------------------------------------- 

This E-Mail and any attached files are Confidential and may be legally privileged. 

This e-mail, together with any attachment(s) is for the exclusive and confidential information of the addressee(s). Any other distribution, use or reproduction without the sender's prior consent is unauthorised and strictly prohibited. If you receive this message in error, please notify the sender immediately, and delete the message without making any copies. All text and images in this communication are the copyright of the respective sender and/or Quantum Enterprises. No reproductions are allowed whatsoever without the express written permission of the respective owner, and any such use would be a breach of copyright. 

E-mail transmission cannot be guaranteed to be secure or error free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. No responsibility is accepted by Quantum Enterprises for any loss or damage incurred through use of this e-mail. We advise you to carry out your own virus check before opening any attachment, as we cannot accept any liability for damage received as a result of any software virus.

**Comment by abrookbanks** [comment]
@mackecm2 - Is that a tasty beer in your Avatar? How's the new liver? :beer:

**Comment by mackecm2** [comment]
The beer was surprisingly good considering how strong it was.
At £60 a bottle there were 10 of us sharing the beer having stumped up £6 each, so my liver emerged relatively unscathed.

**Comment by abrookbanks** [comment]
Reminds me of those dangerous Brewdogs Pubs.

**Comment by mackecm2** [comment]
Yeah very similar to Brewdog; both Scottish breweries, both brew totally mental beers.

**Comment by kultvintage** [comment]
Hi there - I'm having the same problem, but can't find a "Fixed Issue" button anywhere on this page - maybe I'm looking straight at it - but could you please tell me how to find the fix.
Thanks
Cherrie

**Comment by mackecm2** [comment]
![image](https://cloud.githubusercontent.com/assets/7928551/10241360/d05385a4-68df-11e5-882a-2223095522bb.png)
