### ISSUE TITLE
Renamed Admin Folder issue?

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#801]
I've renamed my admin folder and fixed the global includes per CC Security Mod, and everything is working just fine. But when I messed up the Trusted IP address a few weeks ago, I ftp'd the old Admin folder back to the site and changed the global includes to admin, thinking that would get me back into my backend. It didn't, of course, but I've been busy and hadn't deleted the admin folder, so it's still there.

Currently my globals include is set to the renamed admin, and the renamed admin works correctly. BUT, out of curiosity to see what would happen, I opened store_url/admin.php AND I see the login screen and IT LOGGED ME IN!!

Did I forget to change some other setting to the renamed admin, or is this a bug?

**Comment by abrookbanks** [comment]
Nothing to be concerned about it will just use the same session name regardless of admin folder.
