### ISSUE TITLE
Mailing list subscription box is wonkey on desktop view

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#802]
![screen shot 2015-09-10 at 10 02 53](https://cloud.githubusercontent.com/assets/4520803/9784442/22e3ea1e-57a3-11e5-8e8f-6991c1385c2e.png)

**Comment by abrookbanks** [comment]
Relates to https://github.com/cubecart/v6/issues/771

**Comment by abrookbanks** [comment]
> Actually in  box.newsletter.php  only line 25 needs to change to "medium-3".

> Line 24 with "medium-9" is OK.  The total space =9+3 =12 and the word
"Subscribe" fits nicely in the "3" space.

**Comment by bondimedical3** [comment]
This makes the word Subscribe cut off on medium devices?
