### ISSUE TITLE
Better control of featured & popular products

### ISSUE THREAD

**Issue by RedKiteDesigns** [cubecart/v6#808]
The Label "Latest Products" is displayed even if :
Show 'Latest Products' on homepage? = No
or
Number of 'Latest Products' to display = 0

Similarly, If Number of popular products to display = 0 
an empty "Best Sellers" box is displayed.

Change content.homepage.php, line 18

{if isset($LATEST_PRODUCTS)}
to
{if !empty($LATEST_PRODUCTS)}

and wrap content of box.popular.php with test for empty array

e.g.

{if !empty($POPULAR)}
< div class="panel" id="box-popular "> 
       etc .......

< /div >
{/if}

**Comment by abrookbanks** [comment]
Thanks Clive.
