### ISSUE TITLE
Unable to use payment gateways in localhost (Wamp)

### ISSUE THREAD

**Issue by kuopassa** [cubecart/v6#809]
I've installed 2Checkout and Payson payment gateways in CubeCart 6, which in turn is installed in localhost with Wamp. Installing those plugins seem to work with the token tool, but using either of those gateways is impossible. This is the error message that occurs:

[Error] I:program-fileswamwwwcubecart-607classeslanguage.class.php:656 - Invalid language path: I:program-fileswamwwwcubecart-607modulesgateway2Checkoutadmin/language - 2Checkout - module.definitions.xml

Perhaps this is because my directory has backwards slashes and they get stripped from code? Like this:

I:\program-files\wam\www\cubecart-607\

Becomes

I:program-fileswamwwwcubecart-607

Any easy fix available?

**Comment by abrookbanks** [comment]
CubeCart requires Linux OS as per our requirements. 

https://www.cubecart.com/hosting-requirements
