### ISSUE TITLE
Cannot change plugin settings

### ISSUE THREAD

**Issue by BridgeUK** [cubecart/v6#810]
I've installed the PayPal plugin using the thunderbolt method, when I go to edit the settings for the plugin all I get is a white page, I have tried other plugins and the same problem is present.

CubeCart version: 6.0.7
OS: Windows 7 using UwAmp

**Comment by kuopassa** [comment]
Does this* sound familiar? :-)

https://github.com/cubecart/v6/issues/809

**Comment by BridgeUK** [comment]
ah, yes it does :-)

**Comment by abrookbanks** [comment]
Please use Linux OS. We recommend https://www.virtualbox.org/ to setup a free VM.
