### ISSUE TITLE
Re-Opening of "SQL Injection" after upgrade...

### ISSUE THREAD

**Issue by mike4kz** [cubecart/v6#811]
Hi,

I have upgraded recently to 6.0.7, and got another alert from ScanMyServer. It's a different "vector" (as far as I can remember), however the same threat...

![2015-09-16 07_06_47-scanmyserver information](https://cloud.githubusercontent.com/assets/5414129/9903166/0a319612-5c42-11e5-8bd0-76b0f0b8e580.jpg)

**Comment by abrookbanks** [comment]
Closed.. issue #752 has been reopened.
