### ISSUE TITLE
Ajax Email Too Busy

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#813]
The Validator on the #newsletter_form submits an ajax call for every character typed after the validator deems the email to be valid.

Thus, an email of admin@thisismyreallylongdomainname.com will cause approx 32 ajax calls, and each will cache a completely irrelevant SQL query - even the last query is irrelevant because there will be a new email or a removed email from the table, which causes a SQL cache purge if I'm not mistaken. Anyway, a whole lot of work for nothing.

The person entering the email address in the Newsletter Subscribe/Unsubscribe field *knows* the email is not valid up until the last character is entered. And a submit will reveal if the email exists if unsubscribing, and cannot already exist until the entire email is submitted for subscribing.

So there is probably no need to validate this form for anything at all.

**Comment by bhsmither** [comment]
To reproduce this, be sure to click into the 'Email' field, then click out (onBlur). Then click in the field and start typing slowly.

**Comment by bhsmither** [comment]
The Validator is blocking the form's submission because when having entered the email address of an email that exists, the ajax call received a false from CubeCart. What the validator does with this false, I cannot yet determine, but the form will not submit.

**Comment by abrookbanks** [comment]
Thanks Brian.
