### ISSUE TITLE
Product Option name displayed instead of description

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#815]
I'm not sure if this is intentional or not, but it seems inconsistent - when viewing a product from the product page, the product options (e.g. dropdowns) use the 'Description' field from the option, whereas the product option summary on the checkout / view cart pages use the 'Name' field, which may or may not be a human-friendly name.

A simple example: a store carries both Shoes, T-Shirts, and Pants (Trousers), all of which have different size option groups. The owner names them 'Shoe Size', 'Shirt Size', 'Trouser Size' in order to easily distinguish them when adding product options from the admin panel; the description, however, should be 'Size' for all 3 groups, and customers should only ever see them as 'Size' - they will clearly understand from the context to what 'Size' is referring.

Not a huge deal, but I feel it would make the customer experience more consistent from shopping to checkout, as well as from the admin side where we may expect the Description to be used in all cases.

**Comment by briansandall** [comment]
Sorry for all the noise - forgot to isolate the commit the first time, then there was a stray line ending :$

**Comment by abrookbanks** [comment]
Fixed with commit https://github.com/briansandall/v6/commit/ac78ae06584154d902d78584b527fc2b39889bda

**Comment by abrookbanks** [comment]
This pull request has been reverted. Screenshot below:

![screen shot 2015-09-30 at 08 15 41](https://cloud.githubusercontent.com/assets/4520803/10186759/761a7506-674b-11e5-9a44-085bc0e66e47.png)

**Comment by abrookbanks** [comment]
# After revert:

![screen shot 2015-09-30 at 08 16 47](https://cloud.githubusercontent.com/assets/4520803/10186785/a57768e0-674b-11e5-94b9-120845d9a15c.png)

**Comment by briansandall** [comment]
It works fine on my end with the change:

BEFORE 815
![cc_pre815](https://cloud.githubusercontent.com/assets/14335170/10199357/29f36034-6755-11e5-90cd-dc62648e7a83.png)

AFTER 815
![cc_815](https://cloud.githubusercontent.com/assets/14335170/10199312/eebdabc8-6754-11e5-883c-2fe63bc52e1f.png)

**Comment by briansandall** [comment]
Note how the first picture the option names, which were meant to be unique so as to be easily identifiable when selecting them, are used, whereas in the second the actual description is used which is what one would expect the customer to see.

I tested with the change using the 6.0.7 build as the base (since that's what I'm currently building my store with), rather than with the most recent Github version, so perhaps that has something to do with it?

**Comment by abrookbanks** [comment]
Hmm with your pull I found it worked sometimes and not others. It always worked before so decided to revert.

**Comment by briansandall** [comment]
That's very strange to be observing inconsistent behavior with such a seemingly innocuous change as this... I wonder what it could be? Is it inconsistent with the same product, or with different products?

In the latter case, it could be that the description for the option was left blank, in which case it would need to default to the name.

Another thing: content.checkout.small.php has the same display code, so would also need to be changed to match content.checkout.medium-up.php, whatever the result of this discussion may be.

**Comment by abrookbanks** [comment]
I haven't had the time to go into the depth of it but it seems ok before so just reverted back.

**Comment by briansandall** [comment]
My suspicion seems to be correct - after deleting the description for one of the options, with #815 applied:
![cc_815_test](https://cloud.githubusercontent.com/assets/14335170/10199887/0d8ba44e-6758-11e5-97fa-a0d9a6c86d2f.png)
Note how it is completely missing the option description just like in your screenshots.

Here is the fixed version:
![cc_815_fixed](https://cloud.githubusercontent.com/assets/14335170/10200046/ef02f6ac-6758-11e5-9189-4bafce1bd41a.png)

Note how the name is used if the description is missing, but the description is preferred. I'll put together another pull request that fixes this issue, as well as include the checkout.small file in the fix this time.
