### ISSUE TITLE
Country and State fields need to be required - Bug

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#817]
On the confirm page of the checkout the "Country" and "State" fields need to be made "required" otherwise customers do not fill them out.

**Comment by bondimedical3** [comment]
The state field has the word required written in it but can still be left blank.

**Comment by harolato** [comment]
cubecart.class.php
search for $required_fields array. There's a state mentioned in it.

**Comment by bondimedical3** [comment]
I am not sure what that means but if customers don't fill in the state they can proceed to the next step and  there is a '0' put into the billing and shipping address.

**Comment by harolato** [comment]
Oh, the states should be added through administration panel: 
Countries/Zones -> Add zone

When customer chooses country he has to pick one of the states from drop down list.

**Comment by bondimedical3** [comment]
Yes but if a customer doesn't pick a state they are able to proceed with the checkout and a '0' appears in the address.

**Comment by abrookbanks** [comment]
This is turning out to be extremely complex due to dynamic state text/select fields.

**Comment by bondimedical3** [comment]
I have just tried not selecting any "State" in 6.0.9 any the issue is still the same. No error message is produced and it simply continues with the checkout and puts a '0' there?
