### ISSUE TITLE
Copyright removal

### ISSUE THREAD

**Issue by tbonerocketeer** [cubecart/v6#819]
Can we list an option to remove the powered by logo from the bottom pages rather than a manual edit.

**Comment by briansandall** [comment]
You don't have to manually edit any files: go to Store Settings -> Copyright and deleting the contents, then click 'Save.'

**Comment by tbonerocketeer** [comment]
There isn't anything there.

**Comment by briansandall** [comment]
Do you mean the 'eCommerce by CubeCart' line at the bottom of the page? That's separate from the copyright, and you're right, I don't see any way to remove that without manually editing the page.

**Comment by tbonerocketeer** [comment]
Yes. That's what I'm talking about.

Thanks 
Chris Short

**Comment by opensourceCoding** [comment]
I'm against @tbonerocketeer's feature request for the easy removal of the "eCommerce by CubeCart", if a business "has" to remove it they should go into the code and remove it manually.

@tbonerocketeer, a business is getting 10 years worth of coding free-of-charge and also getting continued updates free-of-charge as well as security updates free-of-charge and all abrookbanks asks for in return is a footer message saying the shopping cart is powered by CubeCart, it's not a lot to ask is it? I'm not trying to sound mean or anything it's just CubeCart is free of charge and abrookbanks asks for so little in return.

**Comment by tbonerocketeer** [comment]
Ok, I didn't think of it like that. However, I was a paying cubecart user, starting with v3. During that time, I also paid for copyright removal. If this feature is added, I have no issue with a fee to remove it being charged.

Thanks 
Chris Short

**Comment by abrookbanks** [comment]
I'm sorry but this isn't something that will be integrated. You can fork of a skin by renaming its main folder and editing the confg.xml file to match. Updates won't overwrite your code changes then (including footer link).
