### ISSUE TITLE
Please add Structured Data to Foundation

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#82]
I've tried unsuccessfully to add the structure data code Google recommends, eg. http://data-vocabulary.org/Offer, etc.,  to my Blueprint content.product.php. It would be great if this could be added to the stock Foundation skin.

https://developers.google.com/custom-search/docs/structured_data

**Comment by Dirty-Butter** [comment]
This is even more important with the tab for Specifications, as all the information that Google expects to to have for Searches is NOT on one page any more. I tried to pull the info out of the tab and put it back on the main product listing, but it was not responsive.

**Comment by Dirty-Butter** [comment]
Revisiting this request. With the Specification tab, there is no way to use the Google Data Highlighter to improve Google Search visibility. This is an important part of page rank with Google. Foundation handled mobilegeddon with flying colors, but without front page search position, customers are less likely to visit a Foundation skin store.

**Comment by Noodleyman** [comment]
This is resolved via this plugin:
https://www.cubecart.com/extensions/plugins/google-schema-org-microdata-plugin

**Comment by Dirty-Butter** [comment]
I tried that plugin on the free trial. My CC is FAR from stock, so it wasn't surprising that the plugin did not work properly for me. This STILL seems like it should be part of stock CC.

**Comment by Noodleyman** [comment]
I've tested it out, and it's worked really well for me. It adds all the supported elements that there is data and passed all the google tool checks. Are you running into errors with the parsing of the data from the pages?

**Comment by Dirty-Butter** [comment]
I'm not saying the plugin doesn't work on a stock install. I feel sure it does. I have all the metadata correctly added to the product page, and Google is accepting the Automatic Item Updates for my store. IMHO I don't think this should be a paid solution, but rather should be in the stock code.
