### ISSUE TITLE
Change the way caching works

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#822]
There are problems and bugs with the way that caching currently works - see https://forums.cubecart.com/topic/50008-problem-with-the-cache

**Comment by abrookbanks** [comment]
You'll get this error if the memcached class is not available in the PHP configuration. In other words memcached is not installed. Please be careful not to confuse memcache (without the d).

The $globals['config'] variable only loads the same include auto detection would.

```
	public static function autoload_cache() {
		global $glob;

		//If the configuration has a DB try to load that one first
		if (isset($glob['cache']) && !empty($glob['cache'])) {
			if (file_exists(CC_ROOT_DIR.'/classes/cache/'.$glob['cache'].'.class.php')) {
				include CC_ROOT_DIR.'/classes/cache/'.$glob['cache'].'.class.php';
				return true;
			}
		}

		//Try to pick the best opcode cache
		if(class_exists('memcached')) {
			include CC_ROOT_DIR.'/classes/cache/memcached.class.php';
			return true;	
		}
		if(class_exists('Memcache')) {
			include CC_ROOT_DIR.'/classes/cache/memcache.class.php';
			return true;	
		}

		if (extension_loaded('APC') && ini_get('apc.enabled')) {
			include CC_ROOT_DIR.'/classes/cache/apc.class.php';
			return true;
		}

		if (extension_loaded('XCache') && ini_get('xcache.size') > 0) {
			$enable_auth = ini_get('xcache.admin.enable_auth');
			if (!$enable_auth || $enable_auth == strtolower('off')) {
				include CC_ROOT_DIR.'/classes/cache/xcache.class.php';
				return true;
			}
		}

		//Default to file cache
		include CC_ROOT_DIR.'/classes/cache/file.class.php';
		return true;
	}
```

**Comment by havenswift-hosting** [comment]
That would be fine except it is memcached that is running and not memcache !

root [~]# /etc/init.d/memcached status
memcached (pid 19197) is running...

There is also the first point from the answer that is a problem

**Comment by abrookbanks** [comment]
But is it configured with PHP?

**Comment by havenswift-hosting** [comment]
The real issue here is having the entry in the global.inc.php file especially when it is added during an upgrade

Having the entry in the global.inc.php such as below

$glob['cache'] = 'file';

means that in the Admin Store Settings it isnt possible to change and save that as enabled but even more confusingly the config array in the database is actually set as enabled

In my opinion, the entry in the global.inc.php file should not be automatically added on an upgrade (although understand the reasons as the caching is coded currently which causes problems on some servers where memcached is installed but not available to be used).  I think a much better solution would be to change the enable / disable caching in the settings to a choice between disable and the list of caching options so you can choose which caching is used and not use the global.inc.php file at all

**Comment by abrookbanks** [comment]
That would be nice but the cache class is the first one to be initiated. The config class isn't even a twinkle its its mother's eye yet.  I'll create a helpdesk article.

**Comment by havenswift-hosting** [comment]
OK that is a problem - didn't think to look at that, but it makes sense.

In that case can you look at the situation where if there is an entry in the global.inc.php file, the enable / disable functionality doesnt work.

It would still be nice to be able to control it from the Store Settings in the way I described so could you simply write to the global.inc.php file from the Store Settings still giving the option to set which caching to use and not use the config class at all.  Upgrades adding the "files" method by default mean having to manually delete it or change it to the correct one in order to use any other method such as APC or memcache(d)
