### ISSUE TITLE
Add checkbox support to product option display

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#823]
As above.

**Comment by bhsmither** [comment]
It seems that multiple select**ed** values per attribute is coming.

So, also, please add to class Catalogue:
`const OPTION_MULTISELECT`

**Comment by bhsmither** [comment]
I would really like to get a glimpse of how you plan to adapt checkboxes into the option matrix.

I'm stumped.

A lot of the option code can be streamlined if the form inputs are *all* of the syntax
```
name = "productOptions[{$option.option_id}][{$value.assign_id}]"
value = "{$value.assign_id}" {* if appropriate *}
```
But a multi-select in the options matrix??? I'm having a hard time coming up with an innovative solution to that. For now, I am specifying that multi-selects be disallowed in the matrix.

**Comment by Noodleyman** [comment]
handled via:
https://www.cubecart.com/extensions/plugins/absolute-matrix-option-prices-price-list-hide-out-of-stock-matrix-options
