### ISSUE TITLE
Feature request: Product dimensions

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#828]
Please consider adding product dimensions (length, height, and width) - in addition to weight, these are often very important product characteristics, even moreso should one wish to use them while calculating shipping costs.

I have already added these for my own project, but I think many store owners may wish for the same thing so I have separated the changes into a [mergable branch](https://github.com/briansandall/v6/tree/issue828).

Please review the changes and comments, then let me know if you would like me to make any further changes before submitting a pull request (or not make a PR at all, if you don't want these changes or already have them planned for 6.0.9). Thanks!

**Comment by briansandall** [comment]
Added a [commit](https://github.com/briansandall/v6/commit/73fcba447098ce032341b8ab6c2049972e5c7313) that would allow dimensions to be dynamically updated based on #814.

This is really nice for products with major size discrepancies between different options, especially when combined with a shipping module that accounts for that when calculating costs.

**Comment by briansandall** [comment]
Rebased the original branch on top of the latest master branch and reversioned for 6.0.9. Say the word and I'll make a PR.

Combined issue814-828 branch uses the latest version of 814 (i.e. issue814_fixed).

**Comment by briansandall** [comment]
Here are some screenshots of the end results:

Store settings page - select measurement unit next to weight unit:
![cc_828-store](https://cloud.githubusercontent.com/assets/14335170/11072064/e5e5e344-8798-11e5-988e-2bd7459ab04b.png)

Product page - dimensions added after weight:
![cc_828-product](https://cloud.githubusercontent.com/assets/14335170/11072079/fae13fc8-8798-11e5-91d8-b8cb97835040.png)

Product options page - options may also modify product dimensions:
![cc_828-options](https://cloud.githubusercontent.com/assets/14335170/11072100/1b054f4c-8799-11e5-9714-4fdcbddfd44a.png)

Shopping view displays product dimensions in the Specifications tab (which is dynamically updated if using the merged issue814-828 branch):
![cc_828-spec](https://cloud.githubusercontent.com/assets/14335170/11072129/451fbe20-8799-11e5-93a8-0e24365b394d.png)

**Comment by vorien** [comment]
I'd really like to use this functionality.  Is there any way to turn it into an extension?

**Comment by briansandall** [comment]
@vorien There are probably already extensions that add this type of functionality. Unfortunately, I do not have time to make extensions myself, and as you can see there has not been any response from the developers yet on whether the above will be integrated into CubeCart's core.

If you are familiar at all with Git, you are more than welcome to cherry pick the above commits into your own project, though they are now almost a year old and may need some updating. Good luck!

**Comment by vorien** [comment]
Thanks for the quick reply.
I'm not familiar enough with cubecart to do the conversion, but I figured I'd check.  I haven't seen any extensions that implement dimensions by option, so maybe there's no demand for it.

M

**Comment by briansandall** [comment]
If you don't see any extensions that meet your needs and you aren't comfortable implementing the above changes yourself, you may want to consider contacting some developers and requesting a custom extension. I'd offer to do it, but I've never made a proper extension before and am in the middle of another project.

I believe SemperFi and Noodleyman both do custom work and they seem easy to contact either here or on the CubeCart forums. If you really want this functionality, they would be a good place to start.

**Comment by abrookbanks** [comment]
Opening for 6.2.

**Comment by abrookbanks** [comment]
![screen shot 2018-02-27 at 15 25 33](https://user-images.githubusercontent.com/4520803/36737235-80e03eec-1bd2-11e8-9bd7-20389df3c4e3.png)
![screen shot 2018-02-27 at 15 25 25](https://user-images.githubusercontent.com/4520803/36737236-80fa7262-1bd2-11e8-8e3f-72f5af2539e3.png)

**Comment by abrookbanks** [comment]
Functionality around this can be expanded on later..

**Comment by abrookbanks** [comment]
![screen shot 2018-02-27 at 15 26 46](https://user-images.githubusercontent.com/4520803/36737301-a3e610f6-1bd2-11e8-8a6e-51f79f838a2c.png)

**Comment by abrookbanks** [comment]
Reopening because we need this info on product import and export.

**Comment by Dirty-Butter** [comment]
Somehow or another Length had been added to the Inventory structure in my database. It is not in use. Also, will there be a way to set either inches or centimeters as stock choice?
And this represents packaged size, right - not actual size of item? We bubble wrap most items, so volume in box is larger than actual item.

**Comment by abrookbanks** [comment]
Hmm.. I don't see any duplicates in the SQL.. and fields look ok.

![screen shot 2018-03-02 at 09 56 58](https://user-images.githubusercontent.com/4520803/36893486-1b872f12-1e00-11e8-96a2-bfc48b6ea4e3.png)

**Comment by Dirty-Butter** [comment]
Must be something I had because I tested Daren's Dimension plugin. As long as you don't see it, np.

**Comment by claudia39** [comment]
So this isn't to be used for shipping dimensions eventually (future shipping plugin) as those dimensions  would be larger than the item dimensions, plus you would also need the girth in some instances?

**Comment by abrookbanks** [comment]
No it's not. One step at a time..

**Comment by briansandall** [comment]
Girth is derived from the base dimensions, so wouldn't have its own database field.

For my own store, I simply note that these are shipping dimensions, not the actual product dimensions.

Not sure if it's a US vs UK thing, but UPS expects parameters named length, width, height (in order from largest to smallest) rather than width, height, depth.

**Comment by claudia39** [comment]
Yeah, I was wondering about the wording. I'm in the US.  I'll just change depth to width and width to length. I have an Excel worksheet that figures the girth for me.  I had already setup in my date base "item size" and just typed in the dimensions say 5-1/2W x 10-3/4L x 5H. Anyway this can show fractions instead of decimals?

**Comment by briansandall** [comment]
If you're interested, I wrote my own [shipping module](https://github.com/briansandall/CubeCart_Awsp_UPS_Module) for UPS that uses the shipping dimensions for more accurate shipping rates. It expects the database columns to be named `product_length`, `product_width`, and `product_height`, though, so you'd have to alter the upgrade script a little or wait until I update it to use whatever is in the final CubeCart v2.0.

Displaying as a fraction instead of a decimal would probably require some hard-coded conversions... for my own store, I simply round up to the nearest inch anyway since that's what UPS will do.

**Comment by claudia39** [comment]
Thanks briansandall, but I use USPS mostly and I love the AOIS shipping mod.  I can get by using the decimals. Thanks for all answers to my inquiries!

**Comment by Dirty-Butter** [comment]
In 6.2.0 Store Settings>Stock already asks if weight should be Metric or Imperial - wouldn't it make more sense to have a setting that chooses Metric or Imperial for ALL the weight and dimension settings? Otherwise every new listing has to be chosen for inches or centimeters and all existing listings will have to have a query run I suppose to set the correct one. Some sellers will need both measuring systems for different products, but wouldn't most need just one of them or at least have a preponderance of one system?

**Comment by claudia39** [comment]
Agree Dirty-Butter!
