### ISSUE TITLE
Admin Create Order - Disappearing Save + Save & Reload Buttons

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#831]
Click the orders link.
Click the create order tab.
Click the billing tab.
Type a known customer into the find customers input.
Click on the result displayed.
The fields will get populated correctly.
But the save + save & reload buttons will disappear.

**Comment by SemperFiWS** [comment]
Same goes if you select a found product via the product name input on the inventory tab.

**Comment by bhsmither** [comment]
This is a known issue. See fix pertaining to Issue #798.

**Comment by SemperFiWS** [comment]
Thank Brian, much appreciated.
