### ISSUE TITLE
Values Offset Should be Absolute

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#832]
Related to issue #677, I see that code changes in the Database->update() allows for a trigger word to defer all fields against changing an existing value **by** an amount, to changing an existing value **to** an amount.

I suggest that in products.index.inc.php, line 99 (to start):
```
if ($GLOBALS['db']->update('CubeCart_inventory', $record, array('product_id' => $_POST['product_id']), true, array('stock_level'))) {
```
to use the trigger word 'all' so that *every* field is given the value as entered.

There is no function in the admin Add/Edit Product screen to change a value **by** an amount. Thus, *every* field that could contain a string or numeric value that has the '-' or '+' leading character should be databased exactly as entered.

**Comment by abrookbanks** [comment]
Thanks Brian this makes a lot of sense.
