### ISSUE TITLE
Card Capture Mobile Bug

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#833]
![screenshot_2015-09-26-15-10-45](https://cloud.githubusercontent.com/assets/10808588/10115970/220df7ea-6461-11e5-9d42-ab07f0666d96.png)
The white part for the "What's this" is massive and needs to be reduced on mobiles.

**Comment by abrookbanks** [comment]
![screen shot 2015-09-29 at 11 28 20](https://cloud.githubusercontent.com/assets/4520803/10161610/365ce4fc-669d-11e5-9225-6af03d52f8c5.png)
