### ISSUE TITLE
Shipping Title Missing

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#834]
On mobiles (basket and confirm page) there is no heading under the word "Subtotal" to indicate that the next row is the shipping cost?

**Comment by abrookbanks** [comment]
Thanks for this. Preview of fix below:
![screen shot 2015-09-29 at 10 29 23](https://cloud.githubusercontent.com/assets/4520803/10160401/3386f0ea-6695-11e5-9283-60b63bde3abb.png)

**Comment by abrookbanks** [comment]
Improved... 
![screen shot 2015-09-29 at 10 35 33](https://cloud.githubusercontent.com/assets/4520803/10160501/e2c04a16-6695-11e5-9770-9bd1389deb14.png)
