### ISSUE TITLE
Search Button Disappears in Search Orders Tab

### ISSUE THREAD

**Issue by svrabel** [cubecart/v6#835]
After upgrading to 6.0.7, the search button disappears after selecting a customer name from the drop-down list.

The problem is evident using Safari and Firefox.
<img width="752" alt="screen shot 2015-09-26 at 9 30 48 pm" src="https://cloud.githubusercontent.com/assets/8190196/10120678/1a97c650-6496-11e5-9828-0fbdc7457fbf.png">
<img width="728" alt="screen shot 2015-09-26 at 9 30 33 pm" src="https://cloud.githubusercontent.com/assets/8190196/10120679/1aa45cee-6496-11e5-89f8-fd1ec0c3d68a.png">

**Comment by abrookbanks** [comment]
See #798
