### ISSUE TITLE
Catalogue Export - Product price does not respect tax rules

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#836]
There needs to be an enhancement within the admin/sources/products.export.inc.php file to handle product feed prices with tax.

Currently the price is taken directly from the CubeCart_inventory table and then there is a check to see if we should use the sale price or retail price in the feed data.

However, if you are VAT registered and using tax rules to add VAT to your prices, then the prices you send to google are incorrect as the VAT has not been added.

If you are VAT registered, google require you to send the prices +vat, however CubeCart currently sends exVAT.

It should be enhanced to respect tax rules, and possible add a configurable option to include/exclude tax on a per feed basis.

**Comment by bhsmither** [comment]
Personally (and I mean *personally*), I would include in the admin.product.import.format hook that I am obviously using to customize the array to fit the intended destination -- Google UK, Google USA, Amazon, etc.

In the hook, I would figure out what tax values I wanted to accompany the output and whether they are to be included in the price.

**Comment by Noodleyman** [comment]
I agree. It would be nice to have the data selection as well as field formats totally contained within the modules, thus making it easier to manage moving forward on a per feed basis.

**Comment by Noodleyman** [comment]
any movement on this feature request?
