### ISSUE TITLE
Order Complete Page text is misaligned

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#838]
For medium and up devices the text in the Order Summary box is misaligned. The second row of "Price Each" and "Quantity" is too far to the right. All the prices in the "Price" column are too far to the right.
For small devices all text is aligned however there is no border on the right hand side and the edge of the box is simply on the edge of the screen.

**Comment by abrookbanks** [comment]
## Before
![screen shot 2015-09-29 at 15 27 56](https://cloud.githubusercontent.com/assets/4520803/10167048/c30cd2ba-66be-11e5-9406-813ca150f5a8.png)

## After
![screen shot 2015-09-29 at 15 27 45](https://cloud.githubusercontent.com/assets/4520803/10167053/c7116916-66be-11e5-919f-ac7dc63c89b7.png)
