### ISSUE TITLE
Add CubeCart v4 SEO URL Mode

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#842]

**Comment by abrookbanks** [comment]
This is much more complex than first thought.

**Comment by bhsmither** [comment]
What is the goal? What is difficult about CC4-style friendly URLs that aren't handled by the .htaccess file and/or ini.inc.php script?

That solves understanding the URL arriving that is the page request. Is the goal to **generate** CC4-style friendly URLs?

**Comment by abrookbanks** [comment]
The goal is to have the SEO paths stored in the database with v4 format rather than just recognising old URL's and adapting accordingly.

e.g. product-name/prod_1 

It think its fine to use the existing code but CC needs to rewrite to a permanent redirect. Checking this..

**Comment by bhsmither** [comment]
I still have to ask, why?

**Comment by abrookbanks** [comment]
I'm looking into it...

**Comment by SemperFiWS** [comment]
I was actually about to create an issue that relates to this.

One of my clients wanted 301 redirects of all their CC3 category/product/document urls.
To achieve that I ended up replacing this:
```
if (isset($_GET['act'])) {
	switch ($_GET['act']) {
	case "viewDoc":
		$_GET['_a'] = 'document';
		$_GET['doc_id'] = (int)$_GET['docId'];
		break;
	case "viewCat":
		$_GET['_a'] = 'category';
		$_GET['cat_id'] = (int)$_GET['catId'];
		break;
	case "viewProd":
		$_GET['_a'] = 'product';
		$_GET['product_id'] = (int)$_GET['productId'];
		break;
	}
}
```
with this:
```
if(isset($_GET['act']) && !empty($_GET['act'])) {
	if($_GET['act']=='viewCat' is_numeric($_GET['catId'])){
		$redirect_url = 'Location: index.php?_a=viewCat&catId='.$_GET['catId'];
	} else if($_GET['act']=='viewCat' $_GET['catId']=='saleItems'){
		$redirect_url = 'Location: index.php?_a=viewCat&catId=saleItems';
	} else if($_GET['act']=='viewProd' is_numeric($_GET['productId'])){
		$redirect_url = 'Location: index.php?_a=viewProd&productId='.$_GET['productId'];
	} else if($_GET['act']=='viewDoc' is_numeric($_GET['docId'])){
		$redirect_url = 'Location: index.php?_a=viewProd&docId='.$_GET['docId'];
	} else {
		$redirect_url = 'Location: index.php';
	}
	header($url, false, 301);
}
```

I have mentioned this here, instead of in a new issue as outlined above, because I think that redirecting the old URL is a better idea then preserving the old URL in the database.
in the 'ini.inc.php'file.

**Comment by SemperFiWS** [comment]
Something similar could/should also be implemented to handle CC4 urls too.

**Comment by bhsmither** [comment]
I see the code above as happening at the very beginning of waking up CubeCart -- saves a lot of processing effort.

But I also see in the SEO class some code that says, in effect, if we did not arrive here using the CC5/6-style of friendly URL, then (302?) bounce.

Ok, if so, then this fails the objective of a 301 bounce.
