### ISSUE TITLE
Flags - Add to CURRENCY array

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#844]
the LANGUAGES array as used in smarty contains a link to the flags icons that exist in the /languages/flags directory.

It would be really handy to have these also linked in the CURRENCIES array so we can easily use flags in custom currency menus.

I think the currency flags can be added/deleted as languages get added/removed, so this is a complication. it might be worth just bundling all of the image flags with the base install and not delete the image on removal of a language.

**Comment by abrookbanks** [comment]
Not sure how to handle this. I'd like to move to one image sprite to be honest. Leaving as a feature request for now.

**Comment by Noodleyman** [comment]
I realised that it might not be a good idea to use the same images, for example EUR for euros has it's own flag, but not specific to any country/language. I think perhaps bundling flag icons based on currency would be quite handy and take up a very small size. One to think about for the future :)

**Comment by abrookbanks** [comment]
Thanks for the suggestion Alec. We must be due to start 6.1 soon.
