### ISSUE TITLE
XSS on product search 

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#846]
See internal ticket 103160.

**Comment by havenswift-hosting** [comment]
As the fix for this is now public, which means that to hackers, the security issue is also public, does this mean that 6.0.8 is going to be released immediately or do you recommend everyone patches until it is released

**Comment by abrookbanks** [comment]
It will be released on Monday. We never release on a Friday.

**Comment by abrookbanks** [comment]
This is very low risk. It's only single and double quotes that are not sanitized and I haven't been able to actually create a XSS threat. There is a second security report concerning persistent XSS on product reviews which is slightly higher risk. 

Release on Monday.....

**Comment by havenswift-hosting** [comment]
I agree as it completely makes sense not to release at the end of the week but maybe details of the fix should have been held out of the public domain until just before the fix was due to be released.  Do you recommend that the patch is applied manually to any / all sites based on your understanding of the severity or not of this issue ?

**Comment by abrookbanks** [comment]
I had to commit the code changes when patching it which meant it coming into GitHub. Maybe I could have held off syncing. The threat is low so it not a real concern. 

Patches are all core level and not skin level so a full upgrade on monday or to the latest build (which is stable) would be fine.

**Comment by abrookbanks** [comment]
I wish GitHub has a feature to censor an issue for a time period.

**Comment by abrookbanks** [comment]
https://github.com/isaacs/github/issues/481
