### ISSUE TITLE
New Hook - functions.inc.php - httpredir

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#848]
It would be very helpful to have a new hook at the start of the httpredir function to allow selective overrides of redirects.

foreach ($GLOBALS['hooks']->load('httpredir.pre') as $hook) include $hook;

my specific use case is that I need to prevent a redirect based on customer group membership for a couple of pages. Having the hook allows me to check for the conditions and return false to the function thus preventing a redirect.

**Comment by bhsmither** [comment]
I think any hook, if at the end of a (strategically written) function, can replace the value about to be returned with a custom value derived by the hook. That happens all the time in class methods.

The situation with httpredir is that it is coded with the full expectation that it is (one of) the terminus of PHP script execution. Any call to httpredir is planned and expected to be the end.

I have also tried to find a way to *escape* out of a function via another function call or an include. I think PHP does not provide a way.
