### ISSUE TITLE
Not possible to supply a return value to a function via a hook

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#849]
Bit of an odd one, and not something that end users would pick up on, but when writing modules this can prove a bit of an issue.

If you add a custom hook to a function (For example https://github.com/cubecart/v6/issues/848) and try and supply a return value to the function via the hook, it does not get respected.

Using the linked hook as an example. Via my module I include the hook and in the hook I added the following code to check it was being called.
die("I am a hook");

The hook is triggered and I see my message. (cart in catalogue mode, trying to force the checkout page).

If I then replace the die call with "return false;" in an attempt to supply a return value to the function in which the hook exists, it does not get respected.

If I replace "foreach ($GLOBALS['hooks']->load('httpredir.pre') as $hook) include $hook;" with "return false;" it works correctly.

There is some issue which prevents hooks from passing return values to functions from which they may be called.

**Comment by Noodleyman** [comment]
turns out... this is actually working as expected... and PHP is annoying..

http://www.php.net/manual/en/function.return.php

using "return" within an include file, returns a value to the "INCLUDE" function, rather than the function in which the include was called. not a cart issue, but a PHP design thing.

**Comment by bhsmither** [comment]
`foreach ($GLOBALS['hooks']->load('httpredir.pre') as $hook) $httpredir.pre_return[] = include $hook;`
might work.

I have not found a way to make it so that a hook would, in effect, manipulate the function call stack. That is, return directly to point `A` from point `A.1.1`, bypassing `A.1`.
