### ISSUE TITLE
Coupons Get Dumped

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#852]
Please check the logic flow:

In Cart->discountAdd():
`if(empty($coupon['cart_order_id'])) {` // This is not a GC
`unset($this->basket['coupons'][$key]);` // Unset all prior accepted coupons
`if ($coupon['whatever'] {` // Bad voucher, do not accept

Suggest that testing this voucher for acceptance comes first, and if accepted, *then* dump the previous coupon.

**Comment by abrookbanks** [comment]
Thanks Brian. Logic move to after validation.
