### ISSUE TITLE
Social Plugins Conflict

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#854]
Setup both of these:
- https://www.cubecart.com/extensions/social-plugins/addthis
- https://www.cubecart.com/extensions/social-plugins/pinterest

in a CC6 store.

With both enabled, add this with or without pinterest, neither plugin will displayed on the product or document pages in the store.

**Comment by SemperFiWS** [comment]
Additionally, it appears the pinterest plugin itself does nothing.

**Comment by abrookbanks** [comment]
Maybe a custom skin issue?

![screen shot 2015-12-17 at 12 09 12](https://cloud.githubusercontent.com/assets/4520803/11869351/0c184eae-a4b7-11e5-8463-ad4afdee0345.png)

**Comment by abrookbanks** [comment]
Happy to reopen if you disagree.
