### ISSUE TITLE
Admin Edit Product Gets Complete Page on AJAX

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#855]
Maybe it's something I did on CC606 (have not confirmed this on 607 or 608), but when the admin selects a product to edit, observing the Net Waterfall shows an AJAX request for the current page, then an AJAX request to the FileManager Group=1, then another AJAX request for the current page, then an AJAX request to the FileManager Group=2.

**Comment by bhsmither** [comment]
This goes back to at least CC5213.

**Comment by bhsmither** [comment]
In jquery.filetree.js (find the copy in /js/plugins/), about line 72:
```
} else {
  // AJAX request
  $.ajax({
    complete: function(XMLHttpRequest, textStatus){$('.wait').removeClass('wait');},
    dataType: 'json',
    global: false
  });
  $.getJSON(o.script, {'_g': 'xml', type: 'files', q: 'list', dir: t, group: o.group}, function(data){
```
A call is made to jQuery.ajax(). According to the docs:
http://api.jquery.com/jQuery.ajax/
At its simplest, the $.ajax() function can be called with no arguments:
`$.ajax();`
Note: Default settings can be set globally by using the $.ajaxSetup() function.
This example, using no options, **loads the contents of the current page**, but does nothing with the result.

Suggest that the filetree plugin be changed such that:
```
} else {
  // AJAX request
  $.ajaxSetup({
```
The minified version in /admin/skins/default/js/plugins/ will need to be edited as well, and possibly re-minified.

The advisory on the jQuery.ajaxSetup() page:
http://api.jquery.com/jQuery.ajaxSetup/
states that all subsequent uses of the jQuery.ajax() and related functions will use these settings, unless overridden somehow -- such as using jQuery.getJSON().

**Comment by abrookbanks** [comment]
I can reproduce this on the current build but its proving hard to pin down. Adding console debug data it only seems to run the ajax request once.. still looking..

![screen shot 2015-12-11 at 16 07 20](https://cloud.githubusercontent.com/assets/4520803/11748694/63eebd1a-a021-11e5-93df-ed80a33ff925.png)

**Comment by abrookbanks** [comment]
I just haven't been able to find anywhere debugging that calls twice. Maybe it's a behavioural property of Jquery or Jquery bug. Closing for now.

**Comment by Dirty-Butter** [comment]
Revisiting this, based on forum thread https://forums.cubecart.com/topic/51321-admin-script-error/
