### ISSUE TITLE
Order of Order History Logging

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#856]
It's small thing, but it may matter somewhere.

When admin moves an order from Pending straight to Completed, the Order class will first make sure that the order goes through Processing (if `config['no_skip_processing_check']` is set to do so).

But when entering the Order->orderStatus() function, one of the **first** things it does is log into the order history table the status being requested.

Thus, the order history table will show, in order, for this scenario, an order at Pending, then Complete, then Processing.

It *may* be important to know how the order status was managed in a way that the sequence of history table records imply as being not correct.

Suggest that the call to log in the order history table be moved to just above:
```
// Set status to complete if it is digital only
if ($complete) {
```

**Comment by abrookbanks** [comment]
Sorry I put this as unsure in the fear of upsetting email logic, over logging etc...

Maybe a better approach is to have a second history table for user defined history or something. I'm going to close this but please feel free to many any comments. This is certainly noted.
