### ISSUE TITLE
6.0.8 With over 1300 products in shop description not shows in listing

### ISSUE THREAD

**Issue by demand73** [cubecart/v6#858]
I now have over 1300 products in the shop and products with productid over 1000 starts to not show description in product listing. But it shows when looking at the products page.
In my attached image CC1206-104 has a product_id that is 1041 and the product CC1206-103 has a product_id that is 1044. 1041 does not show description in listing and 1044 does show and this continues, three products shows description and then one misses and repeats until around 1250 then description in the listing is not showing at all. (always shows in the individual product and i tested with a different skin with the same result). Any good ideas?
![products_with_id_over_1300](https://cloud.githubusercontent.com/assets/12296274/10383266/17e2ae66-6e2d-11e5-8c21-66a580d2c4e5.jpg)

**Comment by bhsmither** [comment]
To have just these products show in this list, is it, like, Page 12 (or whatever) of the category 'Keramisk kondensators'? Or is this the result of a Search for anything that starts with "CC12"?

**Comment by demand73** [comment]
Thats correct its in the paging list of a category, but its no differens if i search for "cc1206" the same Products are missing description in paging list even with a search. you can check it out live at  http://www.demand.nu/retrotech the higher Product_ids are in category "Kondensatorer/Keramiska 0805 (2012)" are all blanks and the "show Three and miss one" is in the category "Keramiska 1206 (3216)" 
![product](https://cloud.githubusercontent.com/assets/12296274/10388333/4550e732-6e69-11e5-9d2a-42681b335847.jpg)

**Comment by bhsmither** [comment]
I see that sorting by other than Name (Price DESC, for example), the products with missing descriptions are the same ones, but the "show 3 miss 1" is no longer pertinent.

For that category, "Keramiska 1206 (3216)", it is the same products: 474, 334, and 104 regardless of sort. So, that eliminates a lot of Category class code as being suspect.

Please look directly at the database (using phpMyAdmin, for example) at the CubeCart_inventory table. Scroll to the records near product_id 1043. Examine the "short_description" column.

Are the contents any different than product_id 1046? For the items with no description, the HTML shows just `<br>`. An item with a description does not have a `<br>`.

Can you confirm that the items without a description (actually, having only a `<br>`) showing **were** or **were not** *cloned* from a parent product?

**Comment by demand73** [comment]
All these products are cloned and its strange that some of them have the <br> i tested to remove the br to see if that makes a difference and it doesnt. After some more testing i found one product with product_id around 560 that had brand <NULL> after removing that <NULL> the show three and no show one stopped. But i found many more with brand <NULL> so i will clean upp the database a bit to se if the others starts working. Does not really get why it mather or how comes it differs. Always used the cubecart upgrade scripts.

**Comment by bhsmither** [comment]
Certainly, if the parent has `<br>` in the Short Description (which you can't see in the editor's normal mode), all items cloned from it will also have that same Short Description.

The 'brand' column defaults to `null`, so that's a strange observation.

**Comment by demand73** [comment]
Now i have cleaned up the database and all products have '' instead of NULL in col brand and now it seems to work. Problem is that when i add a new product then brand eq NULL.. Strange problem and i can not get what this have with anything to do and adding new products with brand eq NULL doesnt seem to break anything.

**Comment by bhsmither** [comment]
Your experiences are interesting. The latest version of CC6 does not use the 'brand' column.

That column was introduced in CC521 to satisfy those conditions where, for legal reasons, mentioning product names must also include the brand. So, it's there, and the column can be imported and exported. The admin Add/Edit Product screen has that text field to enter a brand commented out.

So, why your CubeCart installation is getting confused over this is very strange.

**Comment by demand73** [comment]
This is very strange, all capacitors in the above example where clones from within CC of each other but wasnt all a like. Some had brand=`<NULL>` and some had not, some had description_short=`<BR>` and some had google_category=`<NULL>`. I did a script that unified all those parameterns in the database and removed all the `<BR>` in short and then Heureka its works. When i now ad new products the nulls are back as i should as they are default and as i am not using those fields and it still works.. Well well i will check this futher when i add next big batch of products and see if any problem apears.

For now this issue can be closed because i cant replicate the problem again myself.
Thanks for the brainstorming.
