### ISSUE TITLE
modifying language strings for plugins in the admin area

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#859]
Noted a little oddity with this today. I installed the french language into my test system, after which I went to "Languages --> French" and selected my plugin from the plugins list.

I changed all of my language strings and saved and changed my UI language to french. The strings did not change. I played around with it for a while and found it started to work once I added the fr-FR.xml file to the modules/languages directory, at this point the strings started to get updated with the MODIFIED strings in the admin area.

A little confusing, so it might need some improvements in the future. Perhaps and one of, or a combination of the following.

1) Only list the plugins in the phrase group that have corresponding XML files that match the language being configured. 

2) When configuring a language, if no underlying XML file exists for the language, create it. Clone the module.definitions.xml file so it will just work.

3) remove the dependency on the underlying XML file. After I placed the file, all of the modified strings started to work rather than those defined in the french xml file.

**Comment by SemperFiWS** [comment]
See #230 

Additionally, for my plugins I include a bar bones XML file for each available language generally with an entry like this:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<language version="1.0">
  <info>
    <title>English US</title>
    <code>en_US</code>
    <character_set>utf-8</character_set>
    <version>1.0.0</version>
    <minVersion>6.0.0a</minVersion>
    <maxVersion>6.0.*</maxVersion>
  </info>
  <translation>
    <string>
      <name>module_title</name>
      <value><![CDATA[AJAX Configurable Search Box Plugin]]></value>
      <type>sfws_ajax_configurable_search_box</type>
    </string>
  </translation>
</language>
```
