### ISSUE TITLE
Child Category will not Save

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#86]
using 6.0.02b clean install (without any 03GitHub commits), as well as  02b clean install WITH 03 Github commits

I notice after creating an additional Category, which is saved in the CubeCart_category table, that the new table does NOT show in the category_index table. Also, I could not create a child category of the default table, either, after I had renamed it. Not sure if I would have been able to before renaming.

**Comment by hairydogltd** [comment]
I was about to report this too!
There is a workaround: create the category as a root category, then go back to edit it and change its parent.

**Comment by Dirty-Butter** [comment]
hairydogltd - I was able to use your work-around, BUT the child, once it saved, did not show on the Categories in the Storefront Header. I had assumed it would.
I'm currently using 02b using all 03b GitHub edited files

**Comment by abrookbanks** [comment]
Fixed. It was caused by old JS which wasn't compatible with the latest upgraded version of jQuery.
