### ISSUE TITLE
SEO issues with SSL

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#860]
https://www.example.com/abc.html - Works

http://www.example.com/abc.html - redirects to;

https://www.example.com.au/index.php?seo_path=abc

**Comment by SemperFiWS** [comment]
How about adding something like this:
```
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```
to the .htaccess file if SSL is enabled?

**Comment by abrookbanks** [comment]
Thanks for the suggestion. I actually tried something similar on the customers website to no avail.

**Comment by Dirty-Butter** [comment]
Maybe this would work - part of v4 SEO Backward Compatibility in our htaccess:
```
  RewriteCond %{QUERY_STRING} (.*)$
  RewriteCond %{REQUEST_FILENAME} !-f
 # RewriteRule prod_([0-9]+)(\.[a-z]{3,4})?$ index.php?_a=product&product_id=$1&%1 [NC]
###BSMITHER VERSION TO FIX GOOGLE WARNINGS
RewriteRule p(rod)?_([0-9]+)(\.[a-z]{3,4})?$ index.php?_a=product&product_id=$2&%1 [NC]
```

**Comment by abrookbanks** [comment]
I don't seem to be able to reproduce this anymore.
