### ISSUE TITLE
Assigned Value Too Late

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#862]
Presuming the hook at 'class.cubecart.contact' could also be used to make a custom test for valid form submission, setting `$error = false;` after the hook, prevents this.

Suggest moving
```
$error = false;
$required = array('email', 'name', 'subject', 'enquiry');
```
to just after `if(isset($_POST['contact'])){`.

**Comment by abrookbanks** [comment]
Thanks Brian. Great suggestion.
