### ISSUE TITLE
Hard Coded Admin File Reference Causes 404 Error

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#864]
In the '/admin/index.php' file there is this:
```php
if (file_exists('..'.DIRECTORY_SEPARATOR.'admin.php')) {
	header('location: ../admin.php', true, 301);
	exit;
```
which should be replaced with perhaps this:
```php
require '../includes/global.inc.php';
if (file_exists('../'.$glob['adminFile'])) {
	header('location: ../'.$glob['adminFile'], true, 301);
	exit;
```

**Comment by abrookbanks** [comment]
That would defeat the object of having the ability to change the name of it unless the admin folder name was also changed which it might not be.

**Comment by abrookbanks** [comment]
Instead the redirect should be removed and the admin.php file (or whatever its name is) should be accessed directly.
