### ISSUE TITLE
Clean Install issue, 6.0.8

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#865]
This might just be me having one of those days, but I've replicated it more than once so thought I would put it out there for other people to validate / test if I have had enough coffee this morning ;)

Trying to do a clean install of 6.0.8, setup gives the white screen at the very first stages of the install. I checked my apache error log and found that the setup was trying to include the 'includes/globals.inc.php' file, which it can't because it hasn't been created yet. This in turn led the installer to crash out.

To install 6.0.8 I had to copy a globals.inc.php file from another working 6.0.8 install and update it's values to work with my new DB. This solve the issue.

I suspect upgrading won't cause this problem because you will have the file, but a clean install doesn't work without adding it.

**Comment by abrookbanks** [comment]
Sorry I haven't been able to reproduce this one. All but one global file include is conditioned around the file existing. The only one that isn't is after install/upgrade is complete.

I'll be happy to take another look if you can give STR.
