### ISSUE TITLE
Foundation: Product Image Placement and Magnify

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#866]
This is a complicated description, so have patience.

I am installing the **Magnifier**  javascript plugin into Foundation - the jquery plugin that has been used in some CC5 skins and still ships with CC6.

The problem is that the 'dio-sensor' gets positioned too far down the page by roughly 45 pixels.

After extensive analysis, I have come to this conclusion: the Menu Bar (`<nav id="box-navigation">`) is being modified by the javascript after the browser has calculated the position of all the HTML nodes that has _layout_ (_irrelevant to explain_).

That is, the browser knows where the product image is, but then javascript changes the Menu Bar in such a way that could reduce its height from being two rows high to being only one row high. This happens when the javascript executes a `removeClass('has-dropdown')` on any `<li>` that does not have `<ul>` child nodes. Doing so removes the down-arrow symbol for that list item, thus shortening the width of that list item, thus shortening the overall width of the complete set of list items on the Menu Bar, thus there is the possibility of reducing the height of the Menu Bar from X rows to something less than X rows.

For each row that "disappears", that amount of document space collapses and everything below it moves up -- except that (my educated guess) the DOM does not update the calculated positions of the HTML nodes.

Thus, the sensor is not sitting accurately on top of the image.

So far, I have changed the javascript in 2.cubecart.js from:

```
    $(".category-nav li").each(function(index) {
        if (!$(this).has("ul").length) {
            $(this).removeClass('has-dropdown');
        }
    });
```

to

```
    $(".category-nav li").each(function(index) {
        if ($(this).has("ul").length) {
            $(this).addClass('has-dropdown');
        }
    });
```

but more experiments are needed to see what happens when adding the class with respect to the number of rows the Menu Bar ends up with and whether the DOM has the correct calculated positions.

There may be a trick that would force the browser to recalculate the node positions, or maybe the order in which the javascript files are executed matters, or maybe make sure the magnify() command is executed after the javascript changes the Menu Bar.

Or experiment with a different magnify-on-hover plugin.

**Comment by bhsmither** [comment]
Also, these experiments were conducted on Firefox 41. I do not have a Chrome, Opera, or IE browser, nor any actual mobile device to determine if the cause of this offset effect happens on these other browsers.

**Comment by bhsmither** [comment]
I also edited the element.navigation_tree.php to remove the existing `class="has_dropdown"`.

**Comment by bhsmither** [comment]
I've found that this Magnifier works fine with an unmodified Foundation skin:
http://thdoan.github.io/magnify/

**Comment by havenswift-hosting** [comment]
Do you have details of specific changes needed to add this please ?  The Magnifier certainly looks good and I think it is a feature useful in all skins

**Comment by bhsmither** [comment]
This is where I am at in Foundation (CC608) -- it's not finished, still working on getting the magnifier to hold the new, swapped secondary image from the gallery.
content.product.php
```
<div class="row">
  <div class="small-5 medium-7 columns">
{if $PRODUCT.magnify}
    <a href="{$PRODUCT.source}" class="magnify open-clearing" data-thumb-index="0" title="{$PRODUCT.name}" rel="">
      <img src="{$PRODUCT.medium}" alt="{$PRODUCT.name}" id="img-preview" />
    </a>
    <p class="hover_zoom">{$LANG.catalogue.hover_zoom}</p>
{else}
    <a href="#" class="open-clearing" data-thumb-index="0"><img src="{$PRODUCT.medium}" alt="{$PRODUCT.name}" id="img-preview"></a>
{/if}
{if $GALLERY}
```
2.cubecart.js
```
    $('a.magnify > img#img-preview').magnify();
    $(".image-gallery").hover(function() {
        var src = $(this).attr("data-image-swap");
        $('#img-preview').attr("src", src);
     /* $('a.magnify > img#img-preview').magnify(); */
        $('a.magnify').attr({href: gallery_json[id].source}).unbind().magnify(src);
    });
```
main.php
```
      <link href="{$STORE_URL}/skins/{$SKIN_FOLDER}/css/cubecart.helpers.css" rel="stylesheet">
      <link href="{$STORE_URL}/skins/{$SKIN_FOLDER}/css/magnify.css" rel="stylesheet">
      {if !empty($SKIN_SUBSET)}
and
            <script src="{$STORE_URL}/skins/{$SKIN_FOLDER}/js/vendor/jquery.bxslider.min.js" type="text/javascript"></script>
            <script src="{$STORE_URL}/skins/{$SKIN_FOLDER}/js/vendor/jquery.magnify.js" type="text/javascript"></script>
            {foreach from=$BODY_JS item=js}{$js}{/foreach}

```
Put the magnifier script in the /js/vendor/ folder and magnifier css file in /css/ folder.

**Comment by abrookbanks** [comment]
I've put this as a feature request. The reason the magnify JS was left is was because some legacy v5 skins look for the /js folder in the CubeCart package. I wanted to remove this folder but for that reason thought it best to be left in. The Foundation skin has been developed to use as much as the default Foundation Library as possible. It can of course be customised.

I don't know of you have seen this? https://www.cubecart.com/extensions/plugins/magic-zoom-plus9241
