### ISSUE TITLE
Login during Checkout sends customer back to Homepage

### ISSUE THREAD

**Issue by claudia39** [cubecart/v6#867]
Hi,
Ok a registered customer who is not logged in places an item in their cart and then views their cart. They look it over and click the "secure payment" button. This leads them to the addition of either register or login in on the checkout page. When this customer logs and again clicks "secure payment" instead of continuing the checkout process it takes them to the homepage of the store. If they click "update cart" if takes them to their account page instead of continuing the checkout process. Why? That would tick me off if I was the customer and may lead to abandoned carts. Anyway to change this so the checkout process is continued instead?
Thanks,
Claudia

**Comment by claudia39** [comment]
Is someone going to look into this?

**Comment by abrookbanks** [comment]
I can't reproduce this behaviour. Please can you submit a tech support ticket with admin login and FTP access to your store and we will look into it for you.
