### ISSUE TITLE
Mobile Device Order complete page

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#868]
There is no border on the right hand side of the Order Summary box and it touches the edge of the screen?

**Comment by abrookbanks** [comment]
![photo 11-12-2015 15 16 41](https://cloud.githubusercontent.com/assets/4520803/11747296/535a0a1a-a01a-11e5-898c-8ce4fa52b97d.png)

**Comment by bondimedical3** [comment]
![screenshot_2015-12-12-12-56-33](https://cloud.githubusercontent.com/assets/10808588/11759547/717ed41a-a0d0-11e5-8718-f18cacc48b01.png)
This is what I see on a Galaxy S5 mobile?
