### ISSUE TITLE
The SEO path specified is already in use with another item. A unique one has been specified for you. Please check and amend if necessary.

### ISSUE THREAD

**Issue by davshirley** [cubecart/v6#87]
6.0.0b2 Imported a bunch of items (2755), and then removed that import and reimported them after adding some more fields to my excel sheet.

Now all the new items generate the error: The SEO path specified is already in use with another item. A unique one has been specified for you. Please check and amend if necessary.

How to fix?  Store is new.  Just wipe it and start over?

**Comment by abrookbanks** [comment]
How did you remove th
