### ISSUE TITLE
State field in checkout pages.

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#871]
This box is not required and a '0' appears on the confirm page if it is not filled out?

**Comment by Dirty-Butter** [comment]
I see the zero sometimes for USA customers, but we also sell internationally, and not all countries use state/province postal divisions. It needs to be required IF country requires it - and perhaps not even shown as a choice if not needed by that country???

**Comment by bondimedical3** [comment]
You will see the zero for USA customers because it has not been filled out by them. Customers at present can skip this box regardless of the country.

**Comment by abrookbanks** [comment]
Relates to #817

**Comment by abrookbanks** [comment]
This is fixed with #817.
