### ISSUE TITLE
Feature request: Show product weight or total weight in ACP

### ISSUE THREAD

**Issue by demand73** [cubecart/v6#872]
Hi it would be nice to be able to see the orders total weight in order summary or delivery tab around shipping info in the ACP. Everything about webshops is around shipping and it would be nice to be able to check what CC thinks the order weights versus reality. I cant find any existing way to find this out other then make a own order with the same products and then look in the checkout.

**Comment by bhsmither** [comment]
You can try this until the programmers develop the official code:
In the admin template orders.index.php, near line 381, find:
```<th colspan="3">{$LANG.basket.shipping}</th>```
Change to:
```<th colspan="3">{$LANG.basket.shipping} for {$OVERVIEW_SUMMARY.display_weight}</th>```
Near line 301, find:
```<div><label for="sum_ship_method">{$LANG.orders.shipping_method}</label><span><input type="text" id="sum_ship_method" name="summary[ship_method]" placeholder="{$LANG.orders.shipping_method_eg}" value="{$SUMMARY.ship_method}" class="textbox"></span></div>```
Change to:
```<div><label for="sum_ship_method">{$LANG.orders.shipping_method} for {$OVERVIEW_SUMMARY.display_weight}</label><span><input type="text" id="sum_ship_method" name="summary[ship_method]" placeholder="{$LANG.orders.shipping_method_eg}" value="{$SUMMARY.ship_method}" class="textbox"></span></div>```
Near line 179, find:
```<div>{$LANG.basket.shipping}:<span>{$OVERVIEW_SUMMARY.shipping}</span></div>```
Change to:
```<div>{$LANG.basket.shipping} for {$OVERVIEW_SUMMARY.display_weight}:<span>{$OVERVIEW_SUMMARY.shipping}</span></div>```
Then in the source file orders.index.inc.php, near line 254, find:
```// Make some values frendlier```
On new lines, add the following after:
```
$summary[0]['basket'] = unserialize($summary[0]['basket']);
$summary[0]['display_weight'] = $summary[0]['basket']['weight'].$GLOBALS['config']->get('config','product_weight_unit');
```

**Comment by havenswift-hosting** [comment]
We have an Enhanced Admin Order Entry plugin that will be released this week that greatly enhances the functionality of this option especially for store owner manually entered orders (full functionality details will be released soon) but the display of the total order weight is one of many additional features that have already been added

**Comment by bhsmither** [comment]
Will this be incorporated into the core CubeCart code?

**Comment by NaturalSigns** [comment]
This would be a great addition to the core code, as mentioned by demand73, i also tend to mock up a new order to get the associated weight.

**Comment by abrookbanks** [comment]
Thanks for this. I've added this to core for 6.0.9.

**Comment by abrookbanks** [comment]
![screen shot 2015-11-11 at 16 27 25](https://cloud.githubusercontent.com/assets/4520803/11096280/1f5a602a-8891-11e5-9eb0-19d8e8432c1d.png)

**Comment by demand73** [comment]
Thanks looks super good.
