### ISSUE TITLE
Disabling Product Reviews Will Break Required Product Options Error Message

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#873]
If you set 'Enable Product Reviews/Comments' to not checked, then try to add a product to basket that has required options - without selecting the option - the 'This field is required' error message will not get displayed.

Possible solution...

Remove or copy this:
```
<div class="hide" id="validate_field_required">{$LANG.form.field_required}</div>
```
from the '/skins/foundation/element.product_reviews.php' file.

Add it to the '/skins/foundation/content.product.php' file.

**Comment by abrookbanks** [comment]
Thanks Daren.
