### ISSUE TITLE
Edit Address Problem.

### ISSUE THREAD

**Issue by ChrisNColeman** [cubecart/v6#874]
Logged in custtomer on checkout selects edit address and then decides address is ok, therefore does not need to edit it but finds cannot return to checkout.

Actually its simple to get arround this by adding a space to one of the address fields but customer would not know that.

Tried with foundation skin, same result..

**Comment by bhsmither** [comment]
This has been a long-lived problem with the database class. The MySQL server will return *zero records were "affected"* which the database class interprets as an effective *false*. The code that received the data from the web form and called the update() function interprets the *false* as a failure.

This happens all throughout CubeCart all the way back to CC3.

Suggest putting a "Cancel" button on the form that points to:
```
?_a=addressbook&action=cancel&redir=confirm
```

**Comment by ChrisNColeman** [comment]
Yes, did that - Thanks.

**Comment by bhsmither** [comment]
That worked?
Please post your code changes so that the developers can evaluate and incorporate it. Then let them close the issue.

**Comment by ChrisNColeman** [comment]
Oh sorry ..

Actually I added the following in the skin --

<input type="submit" value="Cancel" class="button_submit" 
	  onclick="window.location='{$STORE_URL}/index.php?_a=confirm';return false"  />

**Comment by bhsmither** [comment]
That edit would work in a very specific scenario.

However, the button link will need to point to where the customer was, which was not always the checkout process.

**Comment by abrookbanks** [comment]
Thanks for this. My fix has a dynamic link based on referrer.
