### ISSUE TITLE
Possible to change user during PayPal checkout

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#875]
Summary: Logging in as a different user during checkout with PayPal can cause the currently logged in user's data (e.g. email and name, possibly others) to change to that of the PayPal user, with the result that the PayPal user now seems to be logged in to CubeCart and able to view all of the previous user's order history, etc. Of course, it is still the same user logged in, but their information has changed.

I haven't had a chance to check for what may be causing this and it may not even be CubeCart's fault, but I suspect it is since it is the CubeCart customer's data that is being changed.

HOWEVER, while checking out using a different email with PayPal (Pro), I have access to ALL previous addresses:
![cc_paypal_mixup](https://cloud.githubusercontent.com/assets/14335170/10623309/e49242e6-7742-11e5-9407-362866df40f9.png)

I logged in as the test buyer during that transaction, but it is still shipping to the guest user John Doe and has access to his information... I have no idea what's going on on this page...

It's somewhat complicated but I'll do my best to provide steps to reproduce it - bare with me, here.

First Transaction:
1. Go to your (offline) store and buy something as a guest; checkout with PayPal
2. There should now be a new customer entry in the database for the guest

Second Transaction:
1. Setup a PayPal test account with at least one user
2. Buy something using this user, opting to create an account during checkout
3. Checkout with Credit Card, NOT PayPal (also works if you checkout with PayPal, but then you probably have to log out, close the browser, and log back in before the next transaction)
3. There should be a new customer again in the database, and you should be logged in as that customer

```
SELECT email, first_name, last_name FROM cubecart_customers;

====================================================
email                                |      first_name    |    last_name           
====================================================
john@doe.com                |      John              |    Doe
test-buyer@hotmail.com  |     Test                |   Buyer
```

Third Transaction:
1. Still logged in as the 2nd user, buy something else
2. Checkout with PayPal, but enter a different email address, such as that of the first buyer or a second PayPal test account
3. Upon returning to the website, your username has changed! Check out the database:
```
SELECT email, first_name, last_name FROM cubecart_customers;

====================================================
email                                |      first_name    |    last_name           
====================================================
john@doe.com                |      John              |    Doe
test-buyer2@hotmail.com  |    John                |   Doe
```
Very curious, since I logged in (to PayPal) using a second test account (note the change in email address), but somehow ended up with John Doe's name... You can keep doing this back and forth and sideways and each time you decide to log in with a different account your data will change.

NOTE: I did not close my browser between any of the transactions except after the first, as that one was performed weeks ago. I'm highly suspect there is some nasty SESSION caching / transferring going on between the API calls - hope no one shops on a public computer!

**Comment by briansandall** [comment]
Does this issue perhaps belong somewhere else that specifically deals with the PayPal payment modules? If so, where would that be?

While I don't see this as a major security issue (since to pull it off, the attacker would already need access to your cubecart account), it would be very frustrating as a user of the store to have the email you use to login or the name it addresses you as suddenly change just because you used a different PayPal account to checkout.

**Comment by abrookbanks** [comment]
This is intentional. CubeCart always takes the values provided by PayPal as most up to date and correct and updates CubeCart accordingly.

**Comment by briansandall** [comment]
Aha, so that is what was happening.

So it's not possible for a customer to use a non-PayPal email address to register and still pay with PayPal without replacing their email address? Or to maintain separate addresses, e.g. if they want to ship it somewhere else besides their main address?

It still doesn't explain why logging in as a different customer and going to pay by PayPal showed the previous customer's information, though - any ideas what might be going on there? I know it's somewhat convoluted to reproduce, but here are the steps that reliably do so for me:

1. Make a guest purchase and checkout with PayPal using an account you have
   * Note that the address the customer entered in CubeCart is not used at all - whatever address is on file with PayPal is used instead unless the customer clicks 'Update Cart' before clicking on 'Checkout with PayPal'

2. Log out afterward if it logged you in automatically (i.e. the PayPal account email has a registered account on the CubeCart site, even if the guest user email address didn't)

3. Make another guest purchase without closing the browser - when you click 'Checkout with PayPal', you are still logged in as the first user from step 1 - you're not asked to log in again, nor must you enter a password, yet you have all the information for whomever just used the site.

4. Not only that, but once the transaction is completed, the 'guest' user is now logged in again to the site under the previous customer's credentials.

I haven't tried closing the browser in between or deleting cookies / history in between, but that shouldn't be required - anyone using a public computer that leaves the browser open, while that's stupid on their part, leaves themselves open to this vulnerability.

**Comment by abrookbanks** [comment]
Are you saying that the addresses of a different customer show? I've seen this once before and can happen if there are addresses assigned to customer_id greater than the next auto increment on the CubeCart_customers table. 

So say there is an address for customer id 10 and the auto increment level on the customr_id table is 9. The next registered customer gets this address assigned to them.

**Comment by briansandall** [comment]
Not exactly, no. What I'm saying is that if you make a purchase as a guest and checkout with PayPal, the next person to make a guest purchase using the same computer gets to do so on YOUR PayPal account, and if your account is registered with CubeCart, that second user will get logged in automatically as you after their transaction.

**Comment by abrookbanks** [comment]
But surely only if you have PayPal set to keeping you signed in and you let someone use your PC?

**Comment by abrookbanks** [comment]
sorry if I'm being thick.. long day

**Comment by briansandall** [comment]
Hm, that could be, though I'm using a sandbox test account and don't see anywhere in the account settings that it has an option for 'keep me logged in' except for mobile, and that is not currently enabled (plus I'm not using mobile).

So is the answer "Don't shop on public computers?" People definitely shouldn't anyway, but unfortunately many people are not very aware of safe browsing practices.

Do you think there is any way to force a login for PayPal when the user is not logged in to CubeCart? Or would that not be desirable?

**Comment by briansandall** [comment]
Seems to be an [issue with PayPal](http://community.ebay.com.au/t5/Buying/How-can-I-turn-off-the-automatic-sign-in-to-PayPal-when-I-pay/td-p/1035123?rmvSB=true) and some other sites, not necessarily with CubeCart.
