### ISSUE TITLE
Querystring _a=receipt to be an Ignored Section

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#876]
Please see:
https://forums.cubecart.com/topic/50458-print-invoices-pdf/

Because 'receipt' is not an ignored section, SEO->generatePath() will be called. Then, generatePath() will return a non-sensical string, and SEO->__construct will call httpredir() with that corrupted querystring.

**Comment by abrookbanks** [comment]
Thanks again Brian!!
