### ISSUE TITLE
Product options matrix page_content div height insufficient

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#879]
It appears the div with id "page_content" has height styling applied dynamically - from where, I'm not sure - but with enough product options in the mix it is not calculated correctly:
![cc_matrix_overflow](https://cloud.githubusercontent.com/assets/14335170/10672290/d8c629fc-78a3-11e5-8c51-20cb2e8fa10c.png)

With the dynamic styling removed via browser dev tools, the page renders as one would expect, i.e. the browser determines how much space to allot the div based on the actual content, rather than an apparently arbitrary height styling:
![cc_matrix_overflow_fixed](https://cloud.githubusercontent.com/assets/14335170/10672307/f88100d2-78a3-11e5-86d6-8f96d3deb71f.png)

**Comment by bhsmither** [comment]
The height of the page_content area is adjusted so that it is at least 100 pixels taller than the height of the navigation stack. This is managed in the admin skin javascript file admin.js.

**Comment by bhsmither** [comment]
Using my dev tools, I really loaded up the contents of the Combination cells in the Options Matrix table for the sole purpose of making #page_content much taller than the nav stack.

The height of the #page_content did not change.

However, changing the element style from `height` to `min-height` now allows the #page_content to grow as necessary.

The issue is -- the #page_content height is known and so is the nav stack height before the function is called in admin.js to apply the css rule to #page_content. Why, then, is the function getting the calculation wrong?

Could the browser be using the fact that `tbody td {height:25px;}` is the wrong approach - especially when the table row could get to be far taller than 25px?

**Comment by bhsmither** [comment]
Issue #55 was supposed to have fixed this.

**Comment by bhsmither** [comment]
I think using `$("#page_content").css('min-height',e + 100 +'px')` is a better solution.

A solution is also needed to determine if the particular tab's content height should reset the #page_content height back to nav stack height + 100.

For example, my browser lets me drag to enlarge the height of the description editor window. I can make the editor window ridiculously tall. I then switch to a different tab. I then switch back to the Description tab. The #page_content min-height gets set to the ridiculously tall #page_content height plus 100 pixels. But when switching to the Translations tab, the height of #page_contents remains ridiculously tall.

**Comment by bhsmither** [comment]
Actually, regarding the third comment, it's all working fine for me.

In the template products.index.php, near line 517, I replicated `{$row.options_values}` a few dozen times. That really made the Options Matrix table very tall. Switching to the Options tab did calculate and set a new and appropriate height value.

My comment just above about resetting the height still stands, however.

@briansandall, it would be interesting to see if this problem exists on a different browser. I am using Firefox 40.

**Comment by briansandall** [comment]
@bhsmither I'm using Chrome; just tried in Firefox and it had the same issue, but resolved itself after refreshing the page... and now it's working in Chrome?!

Wait, in Firefox, it happens the first time the page loads; after a refresh it looks good, but clicking 'Products', selecting 'Edit' for the product with many options, and then clicking the 'Options' tab results in the same incorrect height; refreshing again fixes it.

But trying the same in Chrome results in a perfect-looking page every time, refresh or no, even though that's where I first observed the issue. Could it be cached? No, clearing the cache was the same.

Aha! I just figured it out - it happens when you resize the browser window to make it narrower than the table requires to fully display! Refreshing the page with the narrower window width will result in the height recalculating correctly, but the first time you navigate to the page with a narrow window width or if you resize it from a sufficient width, it will display this issue.

**Comment by bhsmither** [comment]
Resizing the window will cause the table contents to wrap or unwrap, making the table taller or shorter, but **not* re-triggering the javascript to recalculate the height.

So, back to the use of `min-height` as a better solution.

**Comment by briansandall** [comment]
What if we simply re-trigger the JS when the window is resized?
`window.addEventListener('resize', name_of_admin.js_size_function);`
Or, since it looks like the admin.js function is anonymously applied to each tab, reproduce the logic as required:
```
window.addEventListener('resize', function(event) = {
    // recalculate content height
});
```

**Comment by abrookbanks** [comment]
Thanks for all the info chaps. Lets see how we get on using min-height.. from my testing this works great. I had experience this bug before but hadn't raised an issue so thanks for doing that.
