### ISSUE TITLE
Absolute price added to base, shows as sale

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#880]
If a product has a sale price and an option with an absolute price, the absolute price displays as if it were a sale on top of the combined original price + absolute price:
![cc_880-2](https://cloud.githubusercontent.com/assets/14335170/10672735/c0d39516-78a6-11e5-8949-c935daa7447c.png)
![cc_880](https://cloud.githubusercontent.com/assets/14335170/10672736/c4a3ef60-78a6-11e5-9676-3a112f55b1bc.png)

**Comment by briansandall** [comment]
I'm not sure what the original design specification was, or what others might expect, but I would expect a product with an absolute price that is on sale to display the absolute price on the left in black and crossed out, with the current sale price on the right (provided the sale price is lower).

However, I can see that causing problems, for example if there were several options each with a different absolute price (which can easily happen if updating prices automatically from a price list, for example), yet there is only one possible sale price for the product as a whole. It's quite likely that the one sale price will be too low for some options and possibly too high for others.

The only way I can see to allow options with absolute prices to go on sale is to also include a sale price for each option, which would then allow options to be put on sale individually, e.g. you ordered way too many yellow socks and no one's buying them, so you want to put just yellow on sale, but keep blue and red at the normal price.

**Comment by briansandall** [comment]
Latest commit on branch 'better880' is the same as the one on the 902 branch but only requires the changes from the 814-fixed branch, not 902.

**Comment by abrookbanks** [comment]
Fixed with merge f5ac1cd30fce5bdec20d8fbebf2726a7ce61f362

Thanks again.
