### ISSUE TITLE
Allow price to be set per product option combination, not just per option

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#881]
Imagine a store that sells socks of various sizes in Blue and Yellow.

Larger sizes cost consistently more as the material costs increase, as does the blue sock due to the higher cost of that specific dye, and the store owner would like to have prices that match.

So far, so good - CC can already handle that, as each option can have a modifier to the base price.

Imagine, however, that there is a specific combination, Blue Size 20, for example, that is not manufactured regularly due to lower demand and thus has a higher production cost at the factory, and that cost is passed on to the distributors.

We can't alter the individual option modifiers without increasing the cost of all our other socks to noncompetitive prices. That won't do. But we also can't offer that Size 20 Blue sock at a profitable price - we will probably be selling it at a loss.

If we were able to set prices per full product option combination (i.e. in the options matrix), however, we could easily offer all of our products with appropriate pricing. The only alternative is to separate the options into multiple products, but that is a poor alternative, in my opinion.

This is also related to issue #880 in that sale prices should also be adjustable at the full option combination level.

While I don't have a store that sells socks, I have products with options that result in similar dilemmas, and the ability to set pricing as described above would be very useful.

**Comment by briansandall** [comment]
Related to issue #620 - if the option_matrix were to include 'price', 'cost_price', and 'sale_price' columns, things would be peachy.

I've got a [WIP branch](https://github.com/briansandall/v6/commits/902_prod_avail) that implements the 'price' and 'sale_price', among other things, and it would be trivial to add the 'cost_price' to it as well.

If you want to add just the price columns, it shouldn't be difficult to separate all that out into a separate branch; however, I think that adding the price columns to the matrix should include the other changes in order to be useful, unless you only add the 'cost_price' column.

**Comment by Noodleyman** [comment]
You can do this via:
https://www.cubecart.com/extensions/plugins/absolute-matrix-option-prices-price-list-hide-out-of-stock-matrix-options

**Comment by briansandall** [comment]
@Noodleyman Thanks, but as you can see I in my post above I have already implemented it for my own store. This issue and the feature branch I linked are suggestions to add to the core code as I feel this is something that should be part of the default package.

**Comment by havenswift-hosting** [comment]
This is one case where I also believe that the functionality should be part of core - it is impossible to correctly set prices as in the original example. and with Brian providing code hopefully this can be tested and added quickly.

**Comment by briansandall** [comment]
@abrookbanks Is this something you would like me to update and create a PR for, or do you have other plans for this?

**Comment by abrookbanks** [comment]
@briansandall That would be great. This area is complex though so it will need good testing.

**Comment by briansandall** [comment]
You got it. Looking back over my wip branch, it looks like it was on a completely different topic... but I know I've got that code around here somewhere :P

**Comment by briansandall** [comment]
So, many commits ago that branch actually did resolve this issue, but entwined in that are quite a few changes specifically to the way prices are calculated, mainly addressing issues raised in #902.

I could try to separate these changes out, but it doesn't make much sense (to me) to do so. We could resolve #902, #620, and #880 (again), parts of #1097, and possibly #1068 and #1170 all in one go. It would also be simple to address #1118 once these changes are in place (I have in my own store).

I'll try to push an updated version with all the changes on Monday - if you get a chance to play around with it using some products with a variety of options, that would give you a good feel for how the pricing is functioning. We can discuss any changes on the PR thread and I'll update it as we go.

**Comment by briansandall** [comment]
Alright, after tumbling down the rabbit hole for a while, I've finally got a wip branch that could form the foundation for resolving issues listed above. Note that it is very much a work in progress and I have not thoroughly tested every aspect of it. Any help in that regard would be much appreciated.

Also, this does not yet add the price fields to the matrix; I have another branch off of this one in the works that does so, but I'd like to hammer out the details and issues with this one first.

You can see the full set of changes (here)[https://github.com/cubecart/v6/compare/master...briansandall:issue881_poc3].

Key points have been made in each of the commit messages, but I'll summarize below. This is going to require some rigorous testing and collaboration if it is to see fruition.

All suggestions, critiques, and concerns welcome.

### Changes

1. Absolute prices: previously, if an option with an absolute price was selected, any price modifications from options appearing prior were ignored, while those from options appearing after were applied. Now, all price modifications from all options are applied on top of the absolute price.

Alternatively, we can opt to not apply any price modifications in such cases, but we should at least consider allowing modifications from non-required options to allow for truly optional options to affect price, e.g. a t-shirt with an absolutely priced option as well as an additional option to add a name tag for +$5.00.

Once matrix-level pricing is implemented, we could consider removing option-level absolute pricing entirely, though we may have to keep it for legacy purposes. In either case, we should provide better documentation for end users detailing how all the different types of pricing interact.

2. Multiple absolute prices selected: previously, the price for the option that displays last on the page was used; now, the highest of all selected absolute prices is used instead. While it is arguable that only one option with an absolute price should be present, this change helps keep the price from being completely dependent on layout in the event that a store manager decides they need multiple absolute prices.

### Known and Potential Issues

1. This has NOT been tested with customer pricing groups or quantity-based pricing, nor does `Catalogue::getProductPrice` tie into it at all. In fact, that method doesn't seem to take options into account at all when fetching the price, so I'm not sure how that is supposed to work.

2. Text options have not yet been integrated.

3. `Catalogue::getProductData` is called in lots of places but it does not iterate over selected options; compare that to the logic in `Cart::get` which is what I used as a model for the new AJAX call in `Cubecart::loadPage`. Potentially affected locations include `Cart`, `Catalogue`, `Cubecart`, `Order`, and plugins such as PayPal. This will require some serious investigation.

4. Mini-basket may not display prices accurately, but actual basket does. This shouldn't be too hard to track down and fix.
![cc881-mini-1](https://cloud.githubusercontent.com/assets/14335170/18924119/de3662c6-8563-11e6-8b73-4c6d0af5b913.jpg)

**Comment by briansandall** [comment]
Note also that after fixing the mini-basket display, I believe I may have slightly understood the `option_price_ignoring_tax` variable:

I still assert that it does, in fact, include tax as evinced by the following lines:
```
$price_including_tax = $option['option_price']; // previously 'display_option_tax', assigned to 'option_price_ignoring_tax' / 'price_including_tax'
if (!empty($product['remove_options_tax'])) {
	$GLOBALS['tax']->inclusiveTaxRemove($option['option_price'], $product['tax_type']);
}
```
However, it starts with a zero value and is a representation of the total sum of optional price modifiers (or absolute prices). As such, we can probably revert commit 2551834 or perhaps instead rename to `option_price_including_tax`.
