### ISSUE TITLE
Feature Request - Hook Execution Priority

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#883]
Ran into a scenario today where two modules are not playing nice together, both are using the same hook.

The changes that both the hooks make will work together, but only if executed in a specific order.

the hook in module A should be called before the same hook in module B.

It would be really handy if it were possible to assign run orders / priorities for hooks within the admin area to resolve such conflicts easily.

**Comment by bhsmither** [comment]
I foresee this as there **always** being this danger - any hook not playing nice with another - guaranteed when the publisher is not the same.

The CubeCart_hooks table has a priority column, as does the CubeCart_code_snippet table.

In the plugin's config.xml, the <hook> node can have a priority attribute:
`<hook trigger="class.gui.body_js" enabled="1" priority="50">`

Perhaps an honest evaluation of just how important one's hooks are to the scheme of things may ameliorate some of the consternation.

I do not disagree with administrative control over hook priority, but the responsibility to solve that falls squarely on the publisher of the plugin, when rendering support to their customer.
