### ISSUE TITLE
Update Button In Checkout Triggers Errors / Does Nothing When On Log In / Register Step

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#885]
How to reproduce:
- go to https://demo.cubecart.com/cc6/
- add a product to the basket
- click the secure checkout link

If you are now at either of these:
- https://demo.cubecart.com/cc6/index.php?_a=checkout
- https://demo.cubecart.com/cc6/index.php?_a=confirm
with the login or registration form displayed and try to
a) update a product quantity
b) apply a coupon
all the required field errors will get triggered.

Product quantity will not get updated and coupon will not be applied.

Seeing there is no real need to display basket contents at this step, would not displaying the basket contents be the best solution?

**Comment by abrookbanks** [comment]
I don't see the problem with this as it is. After the form has been completed it will update and quantity / coupon applied.

**Comment by abrookbanks** [comment]
Ideally the whole basket would be ajaxy. Something for version 7 maybe!
