### ISSUE TITLE
Customer List 'Orders' Column May Be Out of Sync

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#887]
From several suspect sequences of events, the `order_count` column of the CubeCart_customer table may not get updated.

In admin, Customers, the table offers to sort the list by **Orders** and the existing query will sort on the `order_count` column.

However, the **displayed value** in the table comes from a different source -- a separate query that counts records in the CubeCart_order_summary table for that customer_id.

Suggest that having retrieved the count of orders for a customer_id, if `count !== ['order_count']`, update the customer record.

**Comment by bhsmither** [comment]
But this will only happen for the customers on the currently displayed page of 20 records.

Next, asking for a sort on 'order_count' will still get a sorted list with differently displayed values. Refreshing that same page will get a possible different collection of 20 records, still with differently displayed values.

**Comment by abrookbanks** [comment]
Fix for issue #887 (after upgrade to 6.0.8). After this it should stay in sync. If not a new we'll have to look into it.
