### ISSUE TITLE
Enhancement : Allow AusPost shipping module to split orders into multiple parcels

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#889]
The maximum weight that AusPost can take is 22 kg so if an order is greater than this it gives the normal "No suitable shipping methods for your order".  With an order of 26 kg why not simply split it into two different parcels, one of 22 kg and one of 4 kg (obviously taking into account the packaging weight)  and then combine the shipping costs for display purposes.  An admin visible only note could be added to the order showing what weights each parcel should be

**Comment by briansandall** [comment]
I've developed a [library](https://bitbucket.org/briansandall/awsp-ship/commits/all) that could help you implement it yourself, if you need. It's completely free to use and has many advantages over the typical shipping module implementations, one of which is the ability to split orders into multiple packages as needed.

It doesn't yet describe how to box the items, but it shouldn't be too difficult to write some code that re-runs the packing algorithm and outputs the size of each box and which items it should contain.

I have already written a UPS module using this library for CubeCart that is nearly ready for release; I'd be happy to share it if you need an example, or perhaps the CubeCart team will consider updating the current shipping modules to use this library.

**Comment by havenswift-hosting** [comment]
We immediately implemented a solution for a customer that allows for any weight.  It was based on the original 1.0.0 and havent looked to see what changes would be needed for the latest version.  The only changes were to shipping.class.php which is attached

[shipping.class.zip](https://github.com/cubecart/v6/files/821543/shipping.class.zip)
