### ISSUE TITLE
Subscribe to mailing list box auto-fills after every step in checkout

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#890]
While checking out, each time the cart is refreshed or the customer moves on to the next step, the checkbox is checked again even if they unchecked it previously.

**Comment by abrookbanks** [comment]
I can't reproduce this issue. Am I doing something different?

Movie: http://static.cubecart.com/github-890.mp4

**Comment by briansandall** [comment]
Unfortunately I don't have movie-making software...

It seems to happen when the shipping updates, when clicking 'Update Cart', or when clicking 'Make Changes' which seems to trigger either of the above.

Perhaps you could try it with the UPS shipping module installed and using a real address (doesn't have to be yours).

**Comment by abrookbanks** [comment]
I'll try that. If you use a Mac you can do a screen recording with Quicktime.

**Comment by briansandall** [comment]
<grumble> Windows... </grumble>

**Comment by abrookbanks** [comment]
I still can't reproduce this...

New Movie: http://static.cubecart.com/github-890-2.mp4

**Comment by briansandall** [comment]
I'm trying to make a video with Open Broadcaster Software for Windows, but having some technical issues, but here's what I did:

1. Installed UPS module, not All-in-One Shipping
2. Add item to cart
3. Fill out form like you did, though I un-selected 'Create Account'
4. Use a real world address
5. Un-select 'Subscribe to Mailing List'
6. Click 'Secure Checkout'
7. Click 'Make Changes' under 'Delivery Address'
8. Box is re-checked

This is using the default CubeCart v6.0.8 skin, which is apparently different than the one in the demo store, as this is what it looks like for me:
![cc_subscribe2](https://cloud.githubusercontent.com/assets/14335170/12053831/cc248e28-aed1-11e5-9617-db17ee32e960.png)

**Comment by abrookbanks** [comment]
I reproduced it. Thanks. Its coming to the end of the day.. I'll fix this in the morning.

**Comment by abrookbanks** [comment]
Found the culprit. Thanks!!

**Comment by briansandall** [comment]
Cheers!
