### ISSUE TITLE
Option to disable newsletter / mailing list

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#891]
For stores that do not send out newsletters, it would provide a more seamless customer experience if the 'Newsletter Subscriptions' link did not appear in their account options and the 'Subscribe to mailing list' option did not during checkout.

A simple 'Disable' box for Newsletters in the admin panel coupled with a check in the appropriate areas would probably suffice.

**Comment by briansandall** [comment]
Similarly, being able to disable 'Digital Downloads' so that the link does not appear in the customer account would be useful for those that do not sell digital products.

**Comment by havenswift-hosting** [comment]
Plus one for this
