### ISSUE TITLE
Admin Safe Mode

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#892]
Feature Request:
When a plugin no longer works (due to CC upgrade?), or when a programming mistake happens on a code snippet, and PHP crashes shortly after login, suggest a means whereby: the admin can have a **_safe mode**_ login where all plugins and code snippets are not engaged, and a very simple, minimal functions, fool-proof, **_safe mode**_ admin skin is employed.
- Plugins and snippets can report that they are still enabled, such that the admin can switch them off.
- The error logs can be examined.
- Repair of database tables can be executed.
- Whatever else first tier tech support may suggest (less need for FTP, Cpanel, database access).

**Comment by abrookbanks** [comment]
Really nice idea Brian! :+1:
