### ISSUE TITLE
[Notice] /classes/cart.class.php:635 - Undefined index: options_identifier

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#893]
To reproduce the error, use a fresh install of 6.0.8 with default test products; turn on debugging, add product to basket, and go to view basket.

Changing the [final argument](https://github.com/cubecart/v6/compare/master...briansandall:issue893?expand=1) in the call to getProductData to `(isset($item['options_identifier']) ? $item['options_identifier'] : null)` removes the error.

Are all products expected to have an options_identifier, even when they don't have options, or is null (the default for getProductData) acceptable?

**Comment by bhsmither** [comment]
I find "Undefined Index" and "Undefined variable" in dozens of statements. It's a **[Notice]**, so it doesn't affect PHP's execution of the code in any way.

Getting these notices serves to point out there may be a variable accidentally misspelled.

I just ignore them.

**Comment by briansandall** [comment]
It may not affect PHP's execution, but if there is a misspelling or the element is otherwise absent when it is expected not to be, that could potentially have more serious implications as far as business logic is concerned.

We can't really expect an end-user to know which of these notices, if any, might be important and which can safely be ignored. For example, I get many undefined indexes related to taxes in my store - as a user, should I be worried that my store will not be applying taxes? Is it a setting I missed, or something deep in the code that is broken?

In my opinion, undefined indexes could be handled better: if it truly is unimportant, as in the variable doesn't need to be set for the logic to function properly, then a fix like the PR I submitted would be appropriate to remove the notice entirely; if it is important, then either an alert-box needs to be raised asking the store admin to set the value (if it's a store setting, such as taxes), and/or the code needs to be reviewed to find why the value is not set as expected.

**Comment by abrookbanks** [comment]
Thanks. It's good to nip a few of these where possible.
