### ISSUE TITLE
User->getMemberships Function

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#896]
Feature Request
Add to the User class a public function that:
```
@param int $customer_id
@return false/recordset('*') // all columns ON 'group_id'
// * = array('membership_id','group_id','group_name','group_description')
// with appropriate hook before return
```
and use this in place of relevant statements in Catalogue->getProductPrice() and GUI->_displaySaleItems().

**Comment by abrookbanks** [comment]
Thanks Brian. This is tidy.. we need more methods like this.

**Comment by bhsmither** [comment]
Also, a comment on commit 92c0c39:
The function User->getMemberships() implies it will accept an integer, but no enforcement of that takes place. If an array of customer_ids were given to the WHERE parameter of DB->select(), we know that the query will thus have `WHERE customer_id IN (1,2,3,4,5)`.

The likelyhood of that happening is small, but since this is a public function, who knows what badly written plugin will pass in.

Suggest testing for an integer, and if not, at least then test for an array and cast array[0] to int.
