### ISSUE TITLE
error 310 when customer has no email address

### ISSUE THREAD

**Issue by mackecm2** [cubecart/v6#897]
A minor issue which was first noticed today, but may have been around since we upgraded to version 6.
My client manually registered a customer using the “Add Customer” screen in the Admin Panel (admin.php?_g=customers&action=add). The customer had no email address, so he entered “none” in the email field.
Having completed the registration, he then selects the “Login as…” tab from the Edit Customer screen, intending to enter an order for this customer.
However when he does this, the web page fails to load with http error 310, with the message “This web page has a redirect loop (ERR_TOO_MANY_REDIRECTS)” in Chrome, and “The page isn't redirecting properly - Firefox has detected that the server is redirecting the request for this address in a way that will never complete.” In Firefox.
FYI when I changed the email address from ”None” to ” anyone@something.com”, it seemed to resolve the problem.
CubeCart Version 6.0.8
Crosshatch front-end skin, default admin skin
PHP Version 5.4.43
MySQL Version 5.5.42-37.1-log

also reported in Cubecart Technical Support Forum, https://forums.cubecart.com/topic/50500-error-310-when-customer-has-no-email-address/

**Comment by abrookbanks** [comment]
Thanks for this! :)
