### ISSUE TITLE
Payment plugin's setting page not working on CubeCart-6.0.8

### ISSUE THREAD

**Issue by nvphuc1989** [cubecart/v6#900]
HI CubeCart team,

I have installed the Authorize.net (AIM & SIM) extension (https://www.cubecart.com/extensions/payment-gateways/authorize-net-aim-sim) on CubeCart version 6.0.8. In the Manage Plugins page, I click the Edit button for Authorize.net plugin but getting a blank page. I have tried with other payment plugins and still got the same issue.
Here is the error log:
>[Exception] cubecart608controllerscontroller.admin.session.true.inc.php:51 - String could not be parsed as XML

Please help to check. Thanks.

**Comment by bhsmither** [comment]
Please see this post:
https://forums.cubecart.com/topic/50423-resolved-xampp/#comment-213055

**Comment by abrookbanks** [comment]
CubeCart hasn't been developed for Windows server. 
https://www.cubecart.com/hosting-requirements

**Comment by briansandall** [comment]
For a fix such as bhsmither mentioned, see this branch:
https://github.com/briansandall/v6/commit/aa2d4aca979ee49237a72843d116a6922fbe08c4

**Comment by abrookbanks** [comment]
Strictly speaking CC hasn't been developed for WIndows but making this change won't add any over head so happy to do so. Thanks!

**Comment by briansandall** [comment]
That's a nicer solution than what I had - glad to see it added!
