### ISSUE TITLE
Absolute pricing bugs

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#902]
The way absolute pricing is currently handled fails pretty miserably under certain circumstances. 

Right now, every option is iterated over and if it says it uses an absolute price, it resets the price, BUT any options that follow can modify that supposedly 'absolute' price. Any options that came before, however, do not - whether they are supposed to or not I'm not sure, but I don't think so.

Absolute price ignoring previous price modifications:
![cc_901](https://cloud.githubusercontent.com/assets/14335170/10979633/5cbbb394-83b2-11e5-938b-ecd616f820e2.png)

Absolute price overwriting previous absolute price:
![cc_901-2](https://cloud.githubusercontent.com/assets/14335170/10979635/5f156f86-83b2-11e5-920b-47c784b322f4.png)

Absolute price modified by later option (see also issue #880):
![cc_901-3](https://cloud.githubusercontent.com/assets/14335170/10979638/6077e7f0-83b2-11e5-83b3-ff88badbfe62.png)

Obviously these are contrived examples, but they illustrate cases where the logic clearly fails and could potentially result in incorrect prices being charged to customers.

Recommendations:
1. Either allow absolute pricing ONLY on one option set (e.g. either 'Check Box' or 'Option B', but not both), OR choose the greater of all absolute prices encountered during the loop. I vote for the first option, as having multiple absolute prices is illogical (so I doubt anyone has done it, but an error notification could be beneficial).
2. Either check if ABSOLUTE_PRICE is defined before applying any option modifiers, OR, if modifiers should affect absolute pricing as well, track the total of all option modifiers and apply them after the final absolute price is determined.
3. However absolute pricing is handled, it should be made clear to store owners how, exactly, it should work. My understanding of the term 'absolute', for example, gives me the impression that picture no. 2 is a bug, but it may be intended for other options to modify absolute pricing.

**Comment by briansandall** [comment]
Please see https://github.com/briansandall/v6/commits/issue814-902 for a WIP fix that is based on my issue #814 branch.

**Comment by briansandall** [comment]
Thinking about it some more, I think all option modifiers should be applied to the price, whether absolute or not. Consider:

Required 'Size' option determines the base cost but, for whatever reason, the store owner prefers to set them as 'absolute' costs instead of in relation to the base product. However, you can choose to add a name patch for $1 more, regardless of size.

The only time I can think of that an absolute price should truly be absolute would be if it were added as a new column to the options matrix AND every option combination was included in that matrix. Any option not included in the matrix that has a non-absolute price should have that price adjustment made.

E.g. Sizes (S, L) + Colors (Red, Blue) are in the matrix. S-Red is $10, S-Blue is $11, L-Red is $15, and L-Blue is $17 (pricing not currently possible, as the Blue option costs more in size L than S). 

Now we can also add the name patch for $1 to any of these, but that option is not included in the matrix, which is fine. If it were, those prices would also have to be set to match; if left empty, they would use the standard options price calculations.

As such, any price set at the matrix level is considered 'absolute' insofar as it is absolute within the matrix options, but behaves the same as previous absolute pricing in that it is modified by extraneous options.

Does that sound about right? How was the option pricing originally envisioned?

**Comment by briansandall** [comment]
Here's an image showing the logic of the latest commits:
![cc_902-1](https://cloud.githubusercontent.com/assets/14335170/11049065/88855246-86f0-11e5-8cea-24803c941f3d.png)
Note how the first product has 2 options both with absolute pricing - the highest of these is used.

In the second example, the absolute price is the last option, which would normally ignore any previous option price modifications; here it (correctly?) applies them all.

@abrookbanks et al. it would be very useful to get some feedback on what the pricing model / logic is or needs to be, if possible. Cheers.

**Comment by abrookbanks** [comment]
This hasn't been developed for use with multiple options groups.

**Comment by briansandall** [comment]
Thanks for the clarification, Al.

Hopefully we'll see some documentation someday on how the options / option matrix pricing works so users don't run into unexpected issues such as demonstrated above.

Probably only people like me (a coder trying to break stuff) will ever break it as is, but in my experience it's always good to both handle edge cases and make it clear to users how they are handled.

**Comment by abrookbanks** [comment]
I've always struggled with resources for things like that. :(

**Comment by briansandall** [comment]
It's certainly not an easy task, I'll grant you that, especially with continually evolving code.

Still, I feel that option handling, especially the option matrix, is one of the key features of CubeCart that puts it miles ahead of the competition (at least it's the feature that ultimately made my decision), and having some solid documentation about it (with particular attention to pricing assumptions) would be very useful and could also be used as a sort of advertising.

**Comment by abrookbanks** [comment]
Cool! Thanks Brian. I'll see what I can do. :neckbeard:

**Comment by Noodleyman** [comment]
I've resolved this issue by developing an absolute pricing module for use with the option matrix.

see:
https://www.cubecart.com/extensions/plugins/absolute-matrix-option-prices-price-list-hide-out-of-stock-matrix-options

**Comment by briansandall** [comment]
@Noodleyman This issue is about resolving logical inconsistencies within the core code, so a plugin is not the type of solution I'm looking for (though the additional features such as your new product options tab is nice and suitable for a plugin).

I have already made the appropriate code changes to resolve this issue on the branch referenced multiple times above - just waiting for Al to chime in with how he would like to proceed.
