### ISSUE TITLE
Admin Bug

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#904]
If you press any tab like Dashboard or a Product tab the Admin jumps too low and you can't see any of the other tabs?

**Comment by bhsmither** [comment]
An effect like that would be incredibly obvious. So, we may need to see screenshots, or have access to your store's admin to check the HTML and CSS for ourselves.

**Comment by bondimedical3** [comment]
This is happening on all CubeCart 6 Admins. Have a look at the Demo store. If for example you are processing an order you need to continually go between the Overview, Billing, Delivery, etc tabs. Every time you you click on a tab it scrolls down and all other tabs are cut off requiring you to scroll up. It's occurring on all Admin pages with tabs.

**Comment by bhsmither** [comment]
Just not seein' what your' describin'.

**Comment by bondimedical3** [comment]
Log into the demo store. Click on "Unsettled Orders" - screen scrolls down and need to scroll up to access other tabs. Click on an order number then the "Billing" Tab - screen scrolls down and need to scroll up to access other tabs. Click on "Delivery" - screen scrolls down and need to to scroll up to access other tabs.

**Comment by briansandall** [comment]
I can confirm this behavior, but oddly for me it only happens on every other tab click, regardless of the tab.

1. Click any admin section, e.g. 'Store Settings' - all tabs are visible

2. Click any of the other tabs - tabs are no longer immediately visible

3. Scroll back up, click any other tab - tabs stay in visible position

4. Repeat steps 2 and 3 as often as desired to observe the effect

**Comment by bhsmither** [comment]
Nope. Not seeing it.
CubeCart's Demo Store
Store Settings
General tab is active by default.
Click Layout tab, still at the top of the page.
Click Logos tab, still at the top of the page.
Advanced, Features, Extra tabs, still at the top of the page.

**Comment by bhsmither** [comment]
Does you browser scroll the page as far down as as is necessary to bring the Save button into view?

If so, that may be a feature/function/setting of the browser - which would be a stupid setting.

**Comment by briansandall** [comment]
No, it doesn't have any setting like that. However, any hash-link, e.g. '#Logos', will try to place that element as high on the page as it can, i.e. at the top. I don't know why mine is alternating like it is.

It works perfectly fine in Firefox, btw, so it is definitely a browser-compatibility issue.

**Comment by havenswift-hosting** [comment]
I can also confirm this behaviour but also see slightly different symptoms.  Using Chrome on Windows in the Admin Store Settings it shows this behaviour all the time regardless of which tab is clicked. Safari on an iPad doesnt do this at all

**Comment by bondimedical3** [comment]
Hello Brian. Have you tried testing this in the Chrome browser?

**Comment by bhsmither** [comment]
Looking at the History of edits made to admin/skins/default/templates/settings.index.php, I find no change in the HTML that would cause me to think that this is an issue caused by a code edit new to CC608.

I conclude that this anomaly would be displayed **by Chrome** on any version of CC6's admin skin, and I will go further to include CC5's admin skin.

Javascript displays or hides the respective `<div>` for each tab's content. Maybe a recent problem with Chrome in that it wants to scroll where the `<div>` would be if all tabs' contents were not hidden.

Apparently, there have been problems with Chrome in the past where `<a name="spot">` -- which is supposed to scroll to this point -- didn't, or scrolled elsewhere.

I don't do Chrome. Chrome is the new IE.

But, let me find a laptop I'm about to trash and I'll try it.

**Comment by bondimedical3** [comment]
It doesn't happen on CubeCart 5

**Comment by bhsmither** [comment]
Testing with CC605, I see this now with Chrome (latest version). It scrolls to just after the `<div id="Whatever" class="tab_content">`.

I added text just after the `<div>` tag and that's where it scrolled to.

*Almost all time.* Weird.

**Comment by abrookbanks** [comment]
This took significantly longer to fix that it should have! :)
