### ISSUE TITLE
VAT number printed twice on Printed Receipt / Invoice

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#905]
If a store has a VAT / tax number entered in the store settings, then it is printed twice on the receipt - firstly under the store address and then incorrectly under the customer address.

Solution : edit print.receipt.php

Remove line 50
{if !empty({$order.vat_number})}<br>{$LANG.settings.tax_vat_number}: {$order.vat_number}{/if}

**Comment by abrookbanks** [comment]
Thanks for this Ian but what you are saying doesn't match the current release https://github.com/cubecart/v6/blob/f4e4be31ef966e18668e053b219074557f2e5f2c/skins/foundation/templates/print.receipt.php

That file only has the stores VAT number once under the store address. I'll reopen if you think I am wrong.

**Comment by havenswift-hosting** [comment]
Line 35 and line 50 show the same Store VAT number - line 35 is correct location under the store's address and line 50 is incorrect as it is under the customer's address.  I dont know whether you were planning on printing the customer's VAT number there which would make sense except it isnt stored anywhere !

**Comment by abrookbanks** [comment]
You are right!! Thanks!!
