### ISSUE TITLE
Negative values added together

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#907]
Another edge case for ya ;)

Entering a negative value for weight in the Product Options screen works fine (e.g. the option weighs less than normal); however, if the value is already negative and you edit it to another negative value, the values are added together, instead of set to the value you entered.

E.g. enter '-1.0', save and reload, enter '-1.0' again, save and reload. Expect to see '-1.0', observed value is '-2.0'.

Zero and positive values work as expected.

**Comment by bhsmither** [comment]
This is related to issue #832.

**Comment by briansandall** [comment]
Thanks - I hadn't seen the previous issues on this.

Seems like the fix from #677 needs to be applied to the regular options, too, and probably everything - are there any cases where one would actually want the values to be additive? There must have been for it to be set up that way, but I can't think of any.

**Comment by bhsmither** [comment]
The database class has been coded to add/subtract from the current value in the database table column for, like, since day one.

I suppose it was one of those "unrealized assumptions" about certain properties having initially set negative values.

**Comment by briansandall** [comment]
Why would a property with an initial negative value (or any value) want to add a value upon updating, though? Unless it's a property such as 'total sales' that is supposed to be cumulative, but then why not use SUM? That just doesn't make sense to me, but it is what it is.

If has been an underlying assumption from the beginning, chances are that changing it now will have all sorts of unforseeable consequences. It'll probably take some serious digging. :\

**Comment by abrookbanks** [comment]
Thanks for sharing.
