### ISSUE TITLE
Partial word matches on searches

### ISSUE THREAD

**Issue by davshirley** [cubecart/v6#908]
This has probably been beat to death already but I can't seem to find a resolution.  I have over 3000 items in the database under a manufacturer's product codes.  We have common model numbers in the description along with a bunch of other data.

The problem is that people will search for products using abbreviated model numbers.

Example:
In the description we might have "CF42DT/E/835 20871" (that's a model number) but people will only search for "CF42" because that is all that they know this item as.  Enabling partial word matches would solve this.  How can I enable that?

**Comment by bhsmither** [comment]
There is this:
https://forums.cubecart.com/topic/49330-fuzzy-search/#comment-211807

Here is another conversation:
https://forums.cubecart.com/topic/46555-is-there-any-way-to-improve-customer-search-experience/

**Comment by davshirley** [comment]
hmmm this pulls up nothing on the latest cube cart.  Maybe I am operating it incorrectly.  Does it do partial word searches as is or do I have to use wildcards or regex or something in my searches?

**Comment by bhsmither** [comment]
If you are interested in the experiment, you will need to make the edits. This has not been implemented in the actual distribution.

If you have made the edits to your installation, and you are not getting what you wanted, then more experimenting needs to be done.

**Comment by davshirley** [comment]
Then I'd like to suggest that this be changed to a feature request since the inability to search products like this pretty much eliminates cube cart as a viable shopping cart system for anyone that has a large inventory of products.

**Comment by abrookbanks** [comment]
This has been implemented for 6.1.
