### ISSUE TITLE
CubeCart, Ltd SSL Cert Problem

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#909]
Current response to arriving at Maintenance, Upgrade tab (set skiplog to false):

Request Sent - https://www.cubecart.com/version-check/2.3.22?version=6.0.8
version=6.0.8
Error:
cURL Error (60): SSL certificate problem: unable to get local issuer certificate
Response received - *empty*

(I need to compare code to make sure it's not my fault.)

Yes, I think it's my fault. If the problem is truly with the *web server* in use, then I may need to upgrade my web server.

**Comment by bhsmither** [comment]
I found this problem when I viewed the Upgrade tab. The button that should have said "Force Upgrade" was empty and the form action URL was:
**?_g=maintenance&upgrade=**<empty>**#upgrade**

That means the logic at line 564 in maintenance.index.inc.php:
```
if (($response = $request->send()) !== false) {
```
could be improved to show some sort of *Failed to get latest version. Contact Support.* message.

**Comment by abrookbanks** [comment]
Our SSL is configured ok as far as I can see (for Google Chrome anyway). 
![screen shot 2015-11-11 at 08 34 53](https://cloud.githubusercontent.com/assets/4520803/11087099/27187f1e-884f-11e5-80c1-852310cb1dae.png)
