### ISSUE TITLE
Matrix Options Get Reset When Updating A Product

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#91]
Steps to reproduce:
1) Create a new option group, example (Colour) <save>
2) Add option attributes (Blue, Green, Red)
3) Assign the options to a product <save / Reload>
4) add options to options matrix <save / reload>
5) Enable matrix stock levels, setup stock levels, product codes <save / reload>

6) Create a new option group (Size) <save>
7) Add option attributes (Small, Large)
8) Assign options to the same product as before <save / reload>
9) Add new options to matrix (save / reload)

Existing options in the matrix get dropped, and re-created so all stock levels and product codes are dropped and need to be manually setup again.

**Comment by abrookbanks** [comment]
This is because the possible matrix combinations are now different. I don't see how this can be fixed. Happy to reopen if I missed anything.
