### ISSUE TITLE
Extra Slash

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#911]
In ini.inc.php, these are set:
```
define('CC_CACHE_DIR', CC_ROOT_DIR.'/cache/');
define('CC_FILES_DIR', CC_ROOT_DIR.'/files/');
define('CC_SKIN_CACHE_DIR', CC_CACHE_DIR.'skin/');
define('CC_CLASSES_DIR', CC_ROOT_DIR.'/classes/');
define('CC_INCLUDES_DIR', CC_ROOT_DIR.'/includes/');
define('CC_LANGUAGE_DIR', CC_ROOT_DIR.'/language/');
```
Note they all end in a slash.

In autoloader.class.php, autoload function, several statements want to work with paths that have the above constants, then append a slash, followed by some other considerations.

Not a big deal as double-slashes in path names are generally a forgivable syntax error.

**Comment by abrookbanks** [comment]
Thanks Brian. Ideally for consistency the slash should probably be removed removed from these ini values to match CC_ROOT_DIR which is used extensively. 

In fear of upsetting 3rd party code I corrected the paths in the Autoloader class.
