### ISSUE TITLE
Limit to number of matrix entries per product?

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#920]
In my store, I have a product with 4 options with 9, 3, 3, and 3 choices respectively, for a total of 248 possible combinations that I'd like to be in the matrix.

After adding these options and ticking the box to include them in the matrix, the matrix grid generates correctly, but clicking 'Save' or 'Save and Reload' almost immediately redirects me to the Dashboard with a 'CSRF / back-button used' alert message and an 'invalid security token' warning, even if I try without going to the Options tab of the product.
`[Warning] C:\wamp\www\git\cc\classes\sanitize.class.php:112 - Invalid Security Token`

My other products can still be edited normally, even one with 108 matrix entries.

Note also that the matrix entries for the troublesome product have not actually been generated yet in the database - it seems to be this part that is baulking.

Any ideas on what may be causing this and / or how to get around it?

**Comment by bhsmither** [comment]
This is the same *coincidental* limit that the AIOS module has -- there will come a point where the number of POSTed key/value pairs exceeds a system-level limit.

In AIOS, for each Zone added, there is about 100 relevant key/value pairs. So, ten Zones gets you 1000 POSTed pairs.

In the Options Matrix, each combo row has eight pairs, plus the top Product Options table has a possible six pairs per row.

The very last key/value pair in the POST is the security token. This token, if missing or wrong, abandons the task at hand and delivers the Dashboard.

A standard PHP installation has a setting, `max_input_vars` set to 1000. Any POSTed pairs after the 1000th pair is discarded and a Warning is logged to PHP's error_log.

So, the solution is to find a way to adjust PHP's `max_input_vars` to some ridiculous value, such as 50000.

This setting can be changed in a 'per-directory' PHP.INI file or PHP's main PHP.INI file. (I do not know if it can be changed in Apache's .htaccess file with php command directives.)

Also, suhosin overrules PHP's `max_input_vars`:
suhosin.get.max_vars
suhosin.post.max_vars 
suhosin.request.max_vars

**Comment by briansandall** [comment]
You, sir, deserve a cookie. Seriously. I knew about request variable limits, but for whatever reason that didn't even cross my mind.

For anyone else with this issue, you will most likely need to restart the server before the new PHP settings take effect - for me, I'm still testing locally, so that was not a problem.
