### ISSUE TITLE
Document editor image preview filled with latin

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#922]
The text is not editable for me (using Firefox) so I can't delete it, but it doesn't seem to show up in the site's HTML (e.g. on the front page for the slider), so it may only be visible in the editor:
![cc_latin_image](https://cloud.githubusercontent.com/assets/14335170/11544713/2f39a484-98f8-11e5-9198-3893190f4888.png)
Is there some purpose to displaying this text in the image preview? If not, it would make the interface more intuitive to remove it.

**Comment by bhsmither** [comment]
It gives you a visual sense of how text will wrap and flow around the image.

This is part of the programming of the third-party rich-text editor (CKEditor) and is beyond the scope of CubeCart.

"Lorem ipsum" has been found to contain a good variety of word length, counts of letters with ascenders and descenders, and variable sentence length. In the world of typography and typographic layout, those considerations when developing the design of a publication are very important.

**Comment by briansandall** [comment]
Gotcha. I wasn't sure what the purpose was, since in my experience 'Preview' doesn't mean showing content that's not there. Makes sense, though, just not very intuitive. Cheers.
