### ISSUE TITLE
Email Test Failed Reason to be Displayed

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#924]
In AJAX::SMTPTest(), if `$email_test_results` is empty (including a false, a zero, a zero-length-string), the not too helpful response is "Test failed to execute.".

Suggest:
`$json = "Test failed to execute. ".$test_mailer->ErrorInfo;`

(I don't have a malfunctioning mailer, so I haven't tested this.)

**Comment by abrookbanks** [comment]
Thanks again Brian!
