### ISSUE TITLE
Invoice total is correct but item price is wrong when a product is discounted between adding to cart and checking out.

### ISSUE THREAD

**Issue by mackecm2** [cubecart/v6#925]
CC Version 6.0.8

Client's description of issue:
"order from 28 November the customer did not complete.  We sent him a reminder but in the meantime we decide to drop the sale price of one item to £5.  The customer has completed the order today (8th December) and the same order has come through on email again but still shows the original sale price despite showing the overall correct price with the reduction, which means the invoice generated by CubeCart reads incorrectly."

I can see that the customer in question checked out on 28 Nov but could authorise his card payment on SagePay. I assume that the customer the quit the session without emptying his basket, and when he came back a week later his basket was still cached.

I have amended the invoice on Cubecart to straighten things out, and suggested to the client that they should clear the cache in the Admin panel whenever they change the price of any product, but I think that there is scope for a code enhancement here to check baskets against the current database prices before initiating checkout.

I leave it up to you guys to decide whether this is a bug or a feature; let me know if you think my assumption regarding the cached basket is correct. I believe this could be related to the issue reported in #532.

**Comment by abrookbanks** [comment]
Adjusting a product price will not update orders placed prior to this.
