### ISSUE TITLE
Why Does This Variable Exist?

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#927]
In Functions currentPage(), I would like to know the history of `$one_time`. Is it vestigial?

Referencing #861

**Comment by abrookbanks** [comment]
I expect this was a "good idea" that was forgotten about due to poor planning.

**Comment by bhsmither** [comment]
I think we need it.

Even with fix bf92747 (#913), I am finding the possibility that `SEO->SEOable()` can return something not quite right.

That's because `SEOability()` and `generatePath()` do not use the `_ignored` array.

So, the preg_match() in SEOability will separate the email address at the '@' or '%40' character.

In currentPage(), if we use $one_time to skip SEOability(), that may answer my concerns.

**Comment by abrookbanks** [comment]
OK thanks Brian I reverted this.
