### ISSUE TITLE
404 Page has wrong server response code

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#928]
I am glad to see there is a 404 page now however it returns a server response code of 302 instead of 404. You can check server responses with https://urivalet.com/ and enter a bad URL like https://demo.cubecart.com/cc6/tv-home-cinema/2d-tvs.html

**Comment by abrookbanks** [comment]
Hmm Chrome disagrees...

![screen shot 2015-12-14 at 11 49 44](https://cloud.githubusercontent.com/assets/4520803/11780296/d0a056c4-a258-11e5-89bd-de0ca94d101a.png)

**Comment by bhsmither** [comment]
In my opinion, CubeCart's **404 - Page Not Found** is a wrongful impingement (usurpation?) on the true and established meaning of the server response code 404.

In CubeCart, this message is located in the Foundation template file `content.404.php`. You are free to change the wording to whatever fits your sensibilities.

But for this template to imply, by default, that *the server could not find this page* is simply not true.

The fact is that *CubeCart cannot find the requested data* to display on the page (technically, the query to the database to find the item, category, document, or one of several other pages based on the `seo_path` had returned a false response).

On the other hand, the great uneducated masses do not know, nor care, how their page requests are developed, so the end result being the same - not getting what was asked for - allows for some leniency on the response.

**Comment by bhsmither** [comment]
In my one experiment using a misspelled seo_path, CC608 causes the web server send a 302 back to the same address -- on the possibility that the requested seo_url had not gotten cached (a `SESSION` variable named 'try_again', I think).

Then, in `CubeCart->_404()`, the statement:
```
header("HTTP/1.0 404 Not Found");
```
is issued.

However, I did not get this header. I got 200 OK. That suggests to me that if my web server has a choice of sending a HTTP 1.0 header, it will, but if my web server is told to only use HTTP 1.1 headers, then maybe 200 OK is the expected final header received.

**Comment by bondimedical3** [comment]
I have used the Moz Toolbar to check the server response code of the 404 page and that also says 302. You can look deeper into whats happening with the toolbar and it actually says 404 first then 302 second. I think the 302 comes from SSL use which is a bug Cubecart has had for a long time.

**Comment by bondimedical3** [comment]
This is another popular tool which says the server response is 302 http://tools.seobook.com/server-header-checker/ - there seems to be many 302 redirects which causes all the results, as if there is some kind of loop.

**Comment by bondimedical3** [comment]
Hello Al. I have noticed that if you test the URL a second time it comes up as a 404. So clear the browsing data in your browser and check the server headers with your Chrome tool. It will show 302.

**Comment by abrookbanks** [comment]
The .htaccess file will always load index.php as all parameters are served from there first. I don't think this can be changed.

**Comment by bondimedical3** [comment]
A 404 page with a 302 server response code 😭

**Comment by abrookbanks** [comment]
As Brian said strictly speaking it's not a 404 code and its found by the server before anything can be done to determine if the content is found or not.

**Comment by bondimedical3** [comment]
Can you implement this?
http://mobile.htmlgoodies.com/beyond/reference/article.php/3472591/How-Do-I-Create-a-Custom-404-Error-Page.htm

**Comment by abrookbanks** [comment]
All data is passed into the index.php file which is found. Your link above would only work if the index.php file is not found. So no that's not possible.

**Comment by bondimedical3** [comment]
My apologies. The actual page itself does have a 404 response code. What is happening is that there is a 302 redirection to the 404 page (most likely because there is no redirect set in place). Can you change this to a 301 redirect which is what it should be?

**Comment by abrookbanks** [comment]
No because the index.php file exists as explained previously.
