### ISSUE TITLE
Force change of admin directory and admin.php on installation / upgrade

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#930]
I think it would be a good idea to force the change of name of the /admin directory and admin.php file name on installation and if possible on an upgrade

**Comment by abrookbanks** [comment]
I like this idea but I don't like how user friendly it makes install/upgrade. It could be automated but a lot of servers will fail trying. Something to think about.

**Comment by havenswift-hosting** [comment]
Changing these is one of the highlighted security issues when testing Magento 1 stores, so much so that it is done automatically when installing Magento 2 now and works well

**Comment by abrookbanks** [comment]
![screen shot 2016-09-02 at 13 35 34](https://cloud.githubusercontent.com/assets/4520803/18203987/2e5b0560-7112-11e6-916b-82af6bbc244c.png)

**Comment by havenswift-hosting** [comment]
Is this for new installs only or upgrades from 6.1.0 upwards

**Comment by abrookbanks** [comment]
New installs only.

**Comment by havenswift-hosting** [comment]
What the reasoning for not adding the same for upgrades ?   If the security reasons are valid for new installs then I think they are equally valid for current sites being upgraded.

**Comment by havenswift-hosting** [comment]
Excellent ! Will help prevent brute force attamepts against the admin login

**Comment by abrookbanks** [comment]
It's has that for years. ;)

**Comment by havenswift-hosting** [comment]
Agreed and probably less than 1% of sites actually use it !
