### ISSUE TITLE
Free-entry State Name w/Number Gets Wrong Result

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#931]
Please see:
https://forums.cubecart.com/topic/50613-something-changes-the-name-of-the-department-automatically/

I have yet to fully trace this out.

In Functions, getStateFormat(), if the $input cannot be found, the return is the $input.

However, this query:
SELECT * FROM CubeCart_geo_zone WHERE id = "13 Bouches-Du-Rhone" will actually have a recordset containing the row:
13 226 CO Colorado
There will be a **Warning** issued, but not an **Error**.
`Truncated incorrect DOUBLE value: '13 Bouches-Du-Rhone'`

It seems that the database query engine casts the input to match the column type (may be configurable), thus matching on the "13".

Calls to the function, such as in CubeCart->_checkout() where a state name has been POSTed such that it starts with a number, the values for `state` (and `state_d` elsewhere) acquire unintended values.

For now, suggest in getStateFormat() (and getCountryFormat() -- although I do not actually see problems in this regard) to test for ctype_digit() for the `id` column:
```
if($match == 'id' && !ctype_digit($input)) return $input;
```
That is, if matching on 'id', but the input does not look completely like an integer, bounce out.

**Comment by Dirty-Butter** [comment]
I just had an issue with this where the customer used ONLY the Department number, 67, which was incorrectly interpreted as British Columbia in the emails.

**Comment by bhsmither** [comment]
Well, then the code suggestion above won't work if the *only* thing present is the number.

Maybe the address block text entry field form element needs to be restricted to accepting only alphabetic letters.

**Comment by Dirty-Butter** [comment]
The customer address book apparently handled the 67 correctly, as it has bas-rhin there. I had changed the Order Billing and Delivery address Department to Bas-Rhin. So maybe there is some slight difference in the coding of those two files.

**Comment by bhsmither** [comment]
In CubeCart_geo_country, France is 'numcode' 250.

In CubeCart_geo_zone, where 'country_id' is 250, there are no records.

This relationship sets up the ability to convert the text entry for State/County/Province into a drop-down selector preloaded with the known States for the selected Country.

France does allow for that to happen. Thus, the addressbook entry may have been created without the inclusion of the number of the French Department, or later changed by the customer. With that, it seems likely the address filled out using the address blocks on the checkout page had the number.

**Comment by Dirty-Butter** [comment]
I looked back through the database at all our orders from France. Most left the State box blank. A few did type in the actual words for the department. It just so happens that 67 is the ISO code for the Canada Zone of British Columbia. 
I would say the best choice would be to ignore any numerical entry and only use the customer's alphabetical entry. IF CC has the zone code, the alphabetical name of the "state" will be databased as the numerical code.

**Comment by bhsmither** [comment]
Perhaps a different approach would be to load up the CubeCart_geo_zone table with the French Departments. I would hope the French people would know what Department they live in.

However, I ran across a bit of info that implied France is going to change the Departments to a lesser quantity.

**Comment by abrookbanks** [comment]
Thanks everyone. :)
