### ISSUE TITLE
Quantity Will Not Update in _a=basket

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#935]
This is POSTed data as seen by FireFox's developer's console.
The first group is from the medium-up div. The second is from the (display:none) small-only div.
```
quan[f8263c560a33bbc1312f3112c0c3d9a9]	3
shipping -hash-
estimate[country] 840
estimate[state] Colorado
estimate[postcode]
quan[f8263c560a33bbc1312f3112c0c3d9a9] 2
estimate[country] 840
estimate[state] Colorado
estimate[postcode]
shipping -hash-
coupon
update Update Basket
```
Just to verify, I munged the hash of quan[] of the small-only and resubmitted.
```
quan[f8263c560a33bbc1312f3112c0c3d9a9] 3
shipping -hash-
estimate[country] 840
estimate[state] Colorado
estimate[postcode]
quan[munged_hash] 2
estimate[country] 840
estimate[state] Colorado
estimate[postcode]
shipping -hash-
coupon
update Update Basket
```
This time, the quantity updated -- obviously because the second input is now a different variable name.

See #406.

This is CC608.

**Comment by abrookbanks** [comment]
This is because JS is required to determine which fields to work with. If the page is resized a refresh is required to get the appropriate fields enabled/disabled.

**Comment by bhsmither** [comment]
The page is not getting resized. Whatever JS is needed to filter only the fields of the form in the appropriate div apparently isn't working.

The shipping hash is also not getting updated because the small-only shipping hash is overwriting the medium-up shipping hash when received by PHP and put in the $_POST array.

**Comment by bhsmither** [comment]
Ok, my bad. I had some custom code that was crashing the script before the script disabled the field.

I will continue to experiment.
