### ISSUE TITLE
[Mobile] Price text not contained in checkout box

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#936]
Prices over $1000.00 (and possibly even just $100.00) do not fit inside the allotted width of the basket description on the checkout page for the average mobile user.

Tested on FireFox using the demo store:
![cc_mobile_checkout](https://cloud.githubusercontent.com/assets/14335170/11938211/1a6fb702-a7ce-11e5-9a30-15175899db21.png)

**Comment by abrookbanks** [comment]
Thanks

**Comment by briansandall** [comment]
Since this is basically the same issue, I'll put it here, too:
![cc_936-2](https://cloud.githubusercontent.com/assets/14335170/12057815/ceb822ee-aef9-11e5-9b53-77079687916e.png)

Same class, content.checkout.small.php, lines 22-24:
```
<div class="small-3 columns">
{$item.line_price_display}
</div>
```
CSS isn't my strong suit, though, so I'll let you handle it (again) ;)

**Comment by abrookbanks** [comment]
Hmm I can't reproduce that. 

![screen shot 2016-01-05 at 16 40 43](https://cloud.githubusercontent.com/assets/4520803/12121106/7cf98c5a-b3cb-11e5-8e05-c1df88ee6e86.png)

**Comment by briansandall** [comment]
The cart total display is fine after the previous fix - this time it occurs when the item price itself (for 1 item) is over $1,000.

You can see even in your screenshot how the individual item price isn't lined up the same as the quantity price just below it, and it will render outside the border if large enough.

**Comment by abrookbanks** [comment]
Thanks for the clarification. This is better.. 

![photo 05-01-2016 18 30 51](https://cloud.githubusercontent.com/assets/4520803/12123844/0061b1bc-b3db-11e5-9ff1-4a5302ee6820.png)
