### ISSUE TITLE
Install Cubecart v6 caused 403 Forbidden error

### ISSUE THREAD

**Issue by Belle111** [cubecart/v6#937]
I have just installed cubecart v6 on a new domain & it has caused a 403 Forbidden error. I can't access the page or the admin link at all so can't even uninstall it. Page was accessible before the installation. Had nothing loaded on it prior to installation.
Any ideas? Thanks.

**Comment by abrookbanks** [comment]
This is either an mistake on install of server security software is blocking it. Please send a tech support ticket of you would like us to investigate.

**Comment by havenswift-hosting** [comment]
A 403 Forbidden error is almost always caused by mod_security blocking access but this should not happen on a new installation (V6 actually causes almost no issues with mod_security anyway) so this is likely caused by a misconfiguration of your hosting account - speak to your hosting company

**Comment by Belle111** [comment]
Thank you for your comments. :-)

**Comment by Belle111** [comment]
I'll contact the hosting company & see what they can do. if I need to lodge a tech support ticket, where do I do that? Cubecart only allows tech support for paying customers. Thanks.

**Comment by abrookbanks** [comment]
> Cubecart only allows tech support for paying customers.

Thats right. If you want us to look at it you'l have to purchase a support plan. I don't believe this is a technical fault with CubeCart but we could have a look into it and it may be possible to make specific changes to make it work with your hosting environment. CubeCart works on the vast majority of web hosting configurations. 

We offer the produce 100% free of charge but have to charge for official staff time.

**Comment by Belle111** [comment]
Awesome, thanks for the clarification.

**Comment by abrookbanks** [comment]
Thanks for understanding and for your support. Please be sure to check out hosting requirements:
https://www.cubecart.com/hosting-requirements
