### ISSUE TITLE
Print Invoice Bug

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#946]
When you press "Print Invoice" (at order complete or from your account) you are presented with a form your printer will print. The word "Quantity" and the amount are misaligned?

**Comment by abrookbanks** [comment]
Looks ok to me. Happy to reopen if you can provide more detail. 
![screen shot 2016-01-05 at 09 40 15](https://cloud.githubusercontent.com/assets/4520803/12111836/60b594a2-b390-11e5-8589-d33285bb0338.png)

**Comment by bondimedical3** [comment]
I just tried it on my tablet and it looks just like your screenshot. But when I did it on my Desktop computer earlier today there where no dark and bright background rows?

**Comment by bondimedical3** [comment]
This is how the box looks like to me.
![print invoice](https://cloud.githubusercontent.com/assets/10808588/12131991/8ba92940-b46b-11e5-82c5-3ce7b9049c73.png)

**Comment by abrookbanks** [comment]
This is to save printer ink I believe. It's standard in Zurb Foundation framework. Screen display differes to print. You can change it if you want.

**Comment by abrookbanks** [comment]
http://stackoverflow.com/questions/5110833/css-how-to-print-a-table-with-background-color-without-print-settings-changes

**Comment by abrookbanks** [comment]
Movie shows that table background is a browser setting: http://static.cubecart.com/github-946-table_backgrounds.mp4
