### ISSUE TITLE
Cust Login - Jump to Account , Home Choice

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#950]
Feature Request:

When a customer logs in (not during checkout), they are taken to their Accounts page.

Request an admin setting (Store Settings, Layout tab, Layout Settings section):
Jump to Account/Home/Current on login: 0=>'Account',1=>'Home',2=>'referringPage'

**Comment by abrookbanks** [comment]
Thanks for this Brian. I'm not a fan of settings. Maybe the user should have the choice.. proceed to account or reload page. Hmm... something to think about. Thanks!

**Comment by briansandall** [comment]
When I'm browsing a site and need to log in, I always like it when I am redirected back to whatever page I was looking at after completing the login process, so my vote is for automatic redirect to referring page.

**Comment by havenswift-hosting** [comment]
I don't have a problem with settings at all and think it greatly adds to the flexibility within a store and would add a lot more rather than less !  However, if it has sent going to be a setting then it should always redirect back to the page you came from and not to the account page.
