### ISSUE TITLE
Suggestion: Remove 'delete' capability from stock warnings

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#953]
I had my first encounter with stock warnings today, luckily in my test store, as I clicked the red trash can next to the warning assuming it would only delete the warning. A pop-up asked if I was sure I "wanted to delete?" and I clicked 'yes', since I wanted to get rid of the stock level warning. Oops.

Again, luckily this was a test store, as it actually deleted the product, even though the product was on several pending orders.

Anyway, here are a few ideas to make this more user-friendly:
1. Don't allow deleting products from the stock warnings page, i.e. remove the trash can icon / link entirely.
2. If for whatever reason people want to be able to delete products no longer in stock from that page, make it a 'soft' delete, i.e. set the product status to '0' instead of actually deleting it. The product won't show up in the store anymore, but is still easily recoverable for the admin and available for any pending orders. If they REALLY want to delete it, they can do so from the 'Products' page.
3. If neither of the above fits the design goal, improve the pop-up confirmation dialogue to explain what, exactly, we are confirming the deletion of. Given the context, I really did think I was simply removing the stock warning message: "Yeah, I saw it, now go away." In hindsight, of course, it makes perfect sense, but a heads up for new users would be very helpful.

**Comment by havenswift-hosting** [comment]
I agree that it could / should be explain a bit better - maybe the verification message should be clear that this is deleting the stock item completely and a user should confirm this each time (your option 3)

However, removing the ability (option 1) or even setting it to status 0 (your option 2) will not suit a lot of people and goes back on the reason it was added in the first place not so long ago.

Many users have many thousands of products and products can often be discontinued or even be one-offs and so this ability was added as the only easy way to remove these products that are no longer in stock and for these users will never be in stock again

**Comment by briansandall** [comment]
Agreed, which is why I ended up with option 3 - even with a few dozen products it can become tedious to find the one you want to delete, let alone thousands. I can definitely see the utility of having the option there, it just took me by surprise.

**Comment by havenswift-hosting** [comment]
Another example that people are doing this and deleting stock items without realising (https://forums.cubecart.com/topic/51673-deleting-a-stock-warning-deletes-the-_item_/) - option 3 to add a big warning popup box is really needed !

**Comment by briansandall** [comment]
It may also be beneficial to prevent or require further confirmation to delete a product that is on an open order.

Imagine this scenario:
1. Customer places order for last remaining quantity product A
2. Product A now has a stock of 0 (though it could just be low enough for a stock warning)
3. Admin looks at stock warnings, sees product A is out of stock, and deletes it.
4. What happens now to the customer's order??? The product they ordered no longer exists!

**Comment by abrookbanks** [comment]
Fixed with pull request https://github.com/cubecart/v6/pull/1407
