### ISSUE TITLE
Google Product Feed Issues

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#957]
When submitting a feed to Google shopping there are a few issues

1) Product identifiers provided but "product_identifers" flag is set to "false"

2) Missing microdata for condition - see https://support.google.com/merchants/answer/6183460?hl=en-GB.  This relates to https://github.com/cubecart/v6/issues/933

**Comment by havenswift-hosting** [comment]
The issue with the product identifiers is a bug in the code.  It is only checking to see whether the MPN and GTIN are entered and if so setting the product_identifier to TRUE and if not then to FALSE.  Google considers other fields for product identifiers (such as brand) but also this code takes no account that barcodes can be entered in the other fields such as EAN

**Comment by abrookbanks** [comment]
I dont understand what needs changing for point 1. Point 2 is a feature request right?

**Comment by havenswift-hosting** [comment]
1) If product identifiers are supplied as part of the feed, then the "product_identifiers" flag needs to be set to true and not false.

2) This could be considered a feature request as it is missing functionality

**Comment by havenswift-hosting** [comment]
There are more changes going to be required for the Google feed and some users are starting to see warning messages in their account console telling them of a change that is about to happen (see attached image)  and also see the following links saying this change will happen in February !

https://support.google.com/merchants/answer/2704214
https://support.google.com/merchants/answer/2700371
![diagnostics 2016-01-29 18-59-33](https://cloud.githubusercontent.com/assets/6114431/12701730/b6635218-c812-11e5-82d2-b3baeeb97f9e.png)

**Comment by havenswift-hosting** [comment]
Hi Al - the last reported issue (prices including VAT in the feed) is now massively urgent as sites are now being banned completely from Google Shopping due to it - can you please take a look at this ASAP so that we can patch sites until the next release

**Comment by abrookbanks** [comment]
I'm absolutely flat out. CubeCart is open source so maybe a developer can look at this and contribute back. I'll look if/when I can.

**Comment by havenswift-hosting** [comment]
We have just released a plugin called "Google Merchant Centre Feed" which replaces and improves on the old "Google Base" plugin this is immediately available from our own website https://www.havenswift-hosting.co.uk/clients/cart.php?gid=19 and will also shortly be available on the Extensions Marketplace.

Our plugin specifically adds / fixes the following

* Optional choice of creating an XML feed rather than standard text version
* Fixes problems for stores that hold product prices without tax where Google requires the export to include tax within the exported price
* Correctly selects the barcode based on which fields (GTIN, ISBN, EAN, UPC, JAN etc) are completed based on store location
* Correctly sets the "identifier_exists" attribute based on whether the correct identifiers are set

Google Merchant Centre is also shortly to require product landing pages to contain the correct microdata which then matches the data supplied in the feed.  We will be shortly adding this information to our three skins !
