### ISSUE TITLE
Reports of orders being deleted when order items remove in admin CP

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#959]
Internal helpdesk ticket 103641

**Comment by SemperFiWS** [comment]
A customer of mine mentioned something similar to this.
In their case the order wasn't actually being deleted, but the order date was getting set to 0.
As a result it would go to the end of the orders list making it appear deleted.
Doing an order search for it retrieves the order successfully.

**Comment by abrookbanks** [comment]
hmmmmmm

I need to experiment with this still.

**Comment by abrookbanks** [comment]
Closing for now as I haven't heard of a case of this for a long time. It may be related to #1012 which is now resolved.
