### ISSUE TITLE
USPS New Changes Jan 17 2016 

### ISSUE THREAD

**Issue by LaughingHorse1** [cubecart/v6#961]
I'm wondering if anyone has tested and checked if the new USPS API changes will be affecting the USPS plugin.

This is a final reminder that on January 17, 2016, in conjunction with the USPS Price Change, USPS will implement updates and additional features to the suite of Web Tools APIs. Updated release notes are available now at https://www.usps.com/business/web-tools-apis/documentation-updates.htm

Impacted APIs will include, but are not limited to, the following:

    Domestic Price and Label APIs
    International Price and Label/Customs Forms APIs

The Web Tools external testing environment is now available. For instructions on accessing the test environment, please see the release notes under the Announcements section at https://www.usps.com/business/web-tools-apis/welcome.htm

**Comment by abrookbanks** [comment]
https://forums.cubecart.com/topic/50755-usps-new-changes-jan-17-2016/

**Comment by abrookbanks** [comment]
Thanks. We have released 1.1.3 here https://www.cubecart.com/extensions/shipping-methods/united-states-postal-service-usps
