### ISSUE TITLE
Minor skin issue: small search bar doesn't auto-hide

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#963]
To reproduce, resize the window until the search icon appears in the top nav bar, click the icon to open the small version of the search bar, then with it still open increase the window size until the normal search bar appears:
![cc_search](https://cloud.githubusercontent.com/assets/14335170/12362679/815b9774-bb79-11e5-99c2-8455c6f44569.png)
Unlikely that users in the wild will encounter / notice this, but there it is.

**Comment by abrookbanks** [comment]
If you resize the page to mobile and refresh it works as expected. CubeCart takes the viewport size on page load. Adding logic to work on page resize shouldn't be necessary and would add significant overhead which should be needed. 

Quit a lot of the Foundation framework works this way.
