### ISSUE TITLE
Incorrect paths for bxslider images

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#966]
In jquery.bxslider.css there are multiple paths to two different images but these are wrong

url('images/bx_loader.gif')
and
url('images/controls.png') (which is used multiple times)

Should be changed to
url('../images/bxslider/bx_loader.gif')
and
url('../images/bxslider/controls.png')

Or alternatively the images moved to the indicated location.

Additionally, the controls.png image should be losslessly compressed

**Comment by bhsmither** [comment]
In CC609's Foundation folder, I find:
css/images/bx_loader.gif and controls.png
This is in addition to:
images/bxslider/bx_loader.gif and controls.png

**Comment by havenswift-hosting** [comment]
Already sorted then !
