### ISSUE TITLE
Product Title Length Suggestions

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#97]
I used the edits discussed near the end of this thread:

https://forums.cubecart.com/topic/47604-resolved-way-to-set-product-name-length/?hl=%20title%20%20limit

Based on this thread, I edited my Admin product listing and css files to use Fixedsys font and box length set to handle best SEO practices of the Title Boxes on General and on Search Engines tabs.

I also see a need in Foundation for Product Listings boxes to have something like a standard maximum length. 

![foundation product title spacing dirty butter plush 2015-01-20 11-35-33](https://cloud.githubusercontent.com/assets/6146505/5822800/bb28c600-a09c-11e4-9999-16ab7079600f.jpeg)

**Comment by abrookbanks** [comment]
I'm not sure how to handle this. Should CubeCart force certain lengths or should the merchant be educated to limit them? I'm struggling to come to a conclusion.

**Comment by hairydogltd** [comment]
I suggest making it so that only the recommended length is visible in the box, but if people want to type more in, they can. 

Sometimes SEO recommendations are simply wrong, but the only way to find out is to break some rules and see what happens.

**Comment by Dirty-Butter** [comment]
I agree that allowing text past the visible box makes sense, as the edits I use do that. The standard box is very short. I'm just saying the length might as well be a meaningful length, and Google's requirements would be a logical way to set that visible length.
