### ISSUE TITLE
Memcached virtually unusable for most now.

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#970]
I have had a chat with Brian on the forums and in order to get Memcached working now you have to add a line in global.inc.php:
$glob['memcached_servers'] = array(array('host_machine','host_port'));
This is something most hosting companies won't allow. Can you guys change this. It was working fine in 6.0.8?

**Comment by bhsmither** [comment]
I would say this is working no differently than in CC608. I find no changes between CC608 and CC609 that would explain why memcached appears to have "work fine" in your CC608 installation.

**Comment by havenswift-hosting** [comment]
I disagree.  We use Memcached across most of our different servers and have upgraded sites to 6.0.9 and have had no problems at all - all sites work perfectly !  I also don't understand why you think hosting companies would have a problem you adding that line to your own global.inc.php file although this should only ever be needed if the Memcached server is not localhost or is using a different port
