### ISSUE TITLE
Required JS not working correctly in all cases

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#979]
This issue has been replciated using IE7, Safari 6 and Safari 9 and validated using the foundation skin on the latest CC release , .10

If you define multiple radio button option sets, all of which are required, in newer versions of chrome, IE and Firefox you will get a warning/error if you have not selected one item from each required option set. If you only select options from some of the sets, not all, it will warn you which sets are still to be populated.

However, in some browsers the behaviour changes. If you select just one option from a single option set, it assumes that ALL option sets have been completed and submits the form. Only those fields that the customer selected are added to the product when added ot the basket.This is allowing the customer to bypass some required options, possible some that impact the price.

Two things going on here:
1) Differences in the way the JS code is being handled cross browser.

2) A lack of enforcement on the server side of required options. The server side should be checking that all required options have been selected in case there are issues / manipulations on the client side.

The issue was reported to me via a real world customer who ran into this problem on more than one occasion recently, I then verified / validated the issue.  The best solution would be to add server side checks to prevent any client side manipulation / cross browser problems.

**Comment by abrookbanks** [comment]
IE7 and IE8 are not supported.
http://foundation.zurb.com/sites/docs/v/5.5.3/compatibility.html 

I'll check this in Safari 9....

**Comment by Noodleyman** [comment]
Yup, which is why it's critical there is server side validation because there are many users out there who still use IE7/8 etc. It will also prevent manipulation of the order data being added to the cart. 

constraints should be validated on both client and server side. 

As a work around I forced the first radio option to be checked using smarty. It means at least a default value is always selected.

**Comment by Noodleyman** [comment]
Just confirming that you won't be adding server side validation to backup the JS?

It seems like a standard thing to do, so was surprised with the status.

**Comment by abrookbanks** [comment]
Thats correct. CubeCart is heavily JS dependant.
