### ISSUE TITLE
Blank screen during virgin install on latest V6.0.0b2

### ISSUE THREAD

**Issue by davshirley** [cubecart/v6#98]
Get this in the logs.  Any ideas why?

PHP Warning:  preg_match() expects parameter 2 to be string, object given in /home/webq/domains/webquarry.com/public_html/alamo/v6/classes/language.class.php on line 1016
[Tue Jan 20 10:56:10 2015] [error] [client 50.141.71.1] PHP Warning:  include() [<a href='http://docs.php.net/manual/en/function.include.php'>function.include.php</a>]: Failed opening '/home/webq/domains/webquarry.com/public_html/alamo/v6/includes/global.inc.php' for inclusion (include_path='.:/usr/local/lib/php') in /home/webq/domains/webquarry.com/public_html/alamo/v6/setup/index.php on line 295
[Tue Jan 20 10:56:10 2015] [error] [client 50.141.71.1] PHP Warning:  mysqli::mysqli() [<a href='http://docs.php.net/manual/en/mysqli.mysqli.php'>mysqli.mysqli.php</a>]: (28000/1045): Access denied for user 'root'@'localhost' (using password: NO) in /home/webq/domains/webquarry.com/public_html/alamo/v6/classes/db/mysqli.class.php on line 28
[Tue Jan 20 10:56:10 2015] [error] [client 50.141.71.1] PHP Warning:  mysqli::mysqli() [<a href='http://docs.php.net/manual/en/mysqli.mysqli.php'>mysqli.mysqli.php</a>]: (28000/1045): Access denied for user 'root'@'localhost' (using password: NO) in /home/webq/domains/webquarry.com/public_html/alamo/v6/classes/db/mysqli.class.php on line 28
[Tue Jan 20 10:56:10 2015] [error] [client 50.141.71.1] PHP Fatal error:  Access denied for user 'root'@'localhost' (using password: NO) in /home/webq/domains/webquarry.com/public_html/alamo/v6/classes/db/mysqli.class.php on line 30

**Comment by abrookbanks** [comment]
"Access denied for user 'root'@'localhost'"

Your database details entered are wrong.

**Comment by davshirley** [comment]
This is during running setup.  The config file that contains the db credentials hasn't even been created yet.  You get this error just running setup/index.php for the very first time.

**Comment by abrookbanks** [comment]
I see! Thanks for the clarification.

**Comment by davshirley** [comment]
For what it is worth, the php.ini on this box has some commands disabled:

disable_functions = exec,system,passthru,shell_exec,escapeshellarg,escapeshellcmd,proc_close,proc_open,dl,popen,show_source

I don't see it complaining about any of this stuff in the logs through.

**Comment by davshirley** [comment]
V5 seems to install without issue...

**Comment by abrookbanks** [comment]
I just tried a fresh install with error reporting set to full and I can't reproduce this. What steps are taken to get the blank screen? Is this after the database details are entered?

**Comment by davshirley** [comment]
No.  It is before.  It is the very first time of going to the site after uploading all the files.  If I manually create the global.inc.php file, I get the final screen of the install process where I can then restart the install.  If I click the "start again" button, the install goes perfectly.

If I touch global.inc.php before install, it fails.  I have to build a valid global.inc.php with proper ownership and permissions to get to the final screen where I can then "start again" to do the install.  All folder permissions are correct.  They would have to be for the install to succeed on the second run through.

Feel free to look around if you like.

http://www.webquarry.com/alamo/v6/setup/index.php

I'm just playing with the software so you can't blow anything up.  Let me know where I can send login info to you if you like.

**Comment by abrookbanks** [comment]
> If I manually create the global.inc.php file

I'm not sure why you want to do that? Does this issue only happen once that has been done. Sorry I'm really muddled with this one.

> disable_functions = exec,system,passthru,shell_exec,escapeshellarg,escapeshellcmd,proc_close,proc_open,dl,popen,show_source

That shouldn't be relevant. 

Is this completely virginal? If you make a new folder and upload the 6.0.0b3 files can you reproduce this immediately? If so may we have FTP access to check it out. You can whizz them over securely via sales dept https://support.cubecart.com/index.php?/Tickets/Submit

**Comment by abrookbanks** [comment]
I have been able to reproduce this now.

**Comment by davshirley** [comment]
Sorry for the delay.  Glad to see you got it sorted.  I loaded the latest snapshot and can confirm that all is well.  It is refreshing to see the quick response times not just on this but on all the other issues.  Helps make the decision which cart to use.  Well done!

**Comment by abrookbanks** [comment]
Really appreciate the feedback.
