### ISSUE TITLE
Upgrade from v4 to 610 failed ..

### ISSUE THREAD

**Issue by ChrisNColeman** [cubecart/v6#981]
On a windows system upgrading from v4 -

In function -

```php
 5.0.0b1.php

At -

## rename images and folder acordingly   (*??*)
function update_image_paths($pattern, $flags = 0) {
	global $regex_slash_keep;
	foreach (glob($pattern, $flags) as $filename) {
		rename($filename, preg_replace($regex_slash_keep, '_', $filename));
	}

	foreach (glob(dirname($pattern).'/*', GLOB_ONLYDIR|GLOB_NOSORT) as $dir) {
		update_image_paths($dir.'/'.basename($pattern), $flags);
	}

}
update_image_paths(CC_ROOT_DIR.'/images/source/*');
,,,



After running the update a few times I renamed the sink directory to remove the hyphens 
(Jennifers-v4-upgraded -> JennifersUpgradeToV610) which worked but later on in the process the following messages were generated  in the php_log -   

[23-Jan-2016 17:31:09 UTC] PHP Warning:  rename(D:\wss\JennifersUpgradeToV610/images/source/0052CosmTryWS.jpg,D__wss_JennifersUpgradeToV610/images/source/0052CosmTryWS.jpg) [<a href='http://docs.php.net/manual/en/function.rename.php'>function.rename.php</a>]: The system cannot find the path specified. (code: 3) in D:\wss\JennifersUpgradeToV610\setup\scripts\upgrade\5.0.0b1.php on line 103
 
Which did not matter because the directrory had already been renamed, but somethings not rght - Scottie.

**Comment by bhsmither** [comment]
We know that Windows operating systems are not supported.

However, it is trivial to allow for the existence of the operating system's `DIRECTORY_SEPARATOR` character. In fact, in ini.inc.php, the constant `CC_DS` is set to be that character.

As with other issues regarding this, suggest in 5.0.0b1.php, near line 81, assuming the forward slash is intended to be the "everybody but Microsoft" directory separator:
```
Was:
$regex_slash_keep = '#[^\w\.\-\_\/]#i';
Now:
$regex_slash_keep = '#[^\w\.\-\_\'.CC_DS.']#i';
```

**Comment by abrookbanks** [comment]
Windows servers running PHP *should* accept forward slash as directory separator.

**Comment by bhsmither** [comment]
From PHP to Windows:
Windows will accept the forward slash in directory strings that PHP gives to Windows.

Going in the other direction:
PHP scripts (aka CubeCart) working with the strings that Windows gives to PHP must deal with the backslashes when working with the paths. Thus, PHP has the constant DIRECTORY_SEPARATOR.

In the case above, it is PHP that is changing a string supplied by Windows -- not Windows doing something with a path supplied by PHP.

**Comment by Noodleyman** [comment]
@abrookbanks , this request is about a window system which CC doesn't officially support, shouldn't this be closed?

**Comment by abrookbanks** [comment]
Closing. I've actually done quite a few successful upgrades in Windows servers and the support knowledge base shows how URL rewrites can be made under IIS.
