### ISSUE TITLE
Deprecated Message

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#984]
With PHP 5.6, a message about `mysql` being deprecated is being displayed.

Suggest in ini.inc.php, near line 19:
```
From:
error_reporting(E_ALL ^ E_NOTICE);

To:
error_reporting(E_ALL ^ (E_NOTICE | E_DEPRECATED | E_USER_DEPRECATED) );
```
This will suppress these messages until the Debug class resets it and captures it.

**Comment by abrookbanks** [comment]
Thanks Brian.
