### ISSUE TITLE
Catalogue#getManufacturer does not return what it claims

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#986]
The docs claim it will return an array (i.e. containing the manufacturer data) or false, but instead it returns a String containing either an HTML link to the manufacturer URL or simply the manufacturer's name.

Here's an implementation that would match the current documentation:
```
public function getManufacturer($manufacturer_id) {
	$manufacturer = $GLOBALS['db']->select('CubeCart_manufacturers', false, array('id' => $manufacturer_id));
	return ($manufacturer ? $manufacturer[0] : false);
}
```
In which case Catalogue#displayProduct line 280 would need to be changed to use the code that used to be in Catalogue#getManufacturer:
```
if (($manufacturer = $this->getManufacturer($product['manufacturer'])) !== false) {
	if (filter_var($manufacturer['URL'], FILTER_VALIDATE_URL)) {
		$GLOBALS['smarty']->assign('MANUFACTURER', '<a href="'.$manufacturer['URL'].'" target="_blank">'.$manufacturer['name'].'</a>');
	} else {
		$GLOBALS['smarty']->assign('MANUFACTURER', $manufacturer['name']);
	}
}
```
Another option would of course be to change the docs to state what is actually returned, but returning an array containing the manufacturer details is far more useful than a single very specifically formatted string.

The method as used internally by CubeCart is only used in that one location on line 279, but it is a public method so there could be ramifications for any plugins, skins, etc. that may have relied on the previous behavior.

**Comment by bhsmither** [comment]
It is unfortunate about this method's comment header block -- there are numerous other methods' comment header blocks that are plain wrong or missing. I am confident that the developers are aware of this wide-spread deficiency.

When I wrote a plugin for drop-shipping, I determined this method was not suitable for my purposes. I expect every developer to make tests to determine such things. Of course, I agree that the comment blocks really should match the inputs and outputs.

**Comment by briansandall** [comment]
How many developers other than Al are working on CubeCart? I was under the impression it was practically a solo project, though I've Technocrat's name in quite a few places within the code.

Personally, now that the project is open source, I would like to see some standardization of code style, documentation, etc., so that there are clear guidelines for potential contributors (e.g. 'Do we use tabs or 4 spaces? Hm, 3 spaces here? Oh, but only 2 here... hmm...') and maintainers (e.g. 'This PR is unacceptable due to not meeting style and/or commit guidelines - please fix the following issues and resubmit it').

Diversity in life is wonderful; diversity within a code base is not :P

**Comment by abrookbanks** [comment]
It's just me at the moment but I've had full time staff in the past. Technocrat was hired for some development work some time back after my full time developer left.

**Comment by abrookbanks** [comment]
This is really crappy but there are lots of skins that are dependant on the function returning a string. I think this is a minor irritation we have to live with.

**Comment by briansandall** [comment]
Bummer. Maybe we can change it in the next major version, since all the skins would have to be updated then anyway? It would be so much more useful to return an array...
