### ISSUE TITLE
Email log required

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#989]
Every email needs to be logged in a table with;

- Subject
- Date
- From
- To
- HTML Message
- Text Message

**Comment by abrookbanks** [comment]
```
CREATE TABLE `CubeCart_email_log` (
  `id` int(11) NOT NULL,
  `subject` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `content_html` text COLLATE utf8_unicode_ci NOT NULL,
  `content_text` text COLLATE utf8_unicode_ci NOT NULL,
  `to` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `from` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `result` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
ALTER TABLE `CubeCart_email_log`
  ADD PRIMARY KEY (`id`);
ALTER TABLE `CubeCart_email_log`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;
```

**Comment by abrookbanks** [comment]
Change end of Mailer->sendEmail() to;

```
			// Send email
			$result = $this->Send();

			$email_data = array(
				'subject' => $this->Subject,
				'content_html' => $this->_html,
				'content_text' => $this->_text,
				'to' => $email,
				'from' => $this->Sender,
				'result' => $result
			);

			$GLOBALS['db']->insert('CubeCart_email_log', $email_data);

			return $result;
```

**Comment by bhsmither** [comment]
*"Every email needs to be logged"*

Why?

Is this a case of "trust but verify"?

**Comment by abrookbanks** [comment]
So many merchants don't know what emails come out of CubeCart and when. This is part of email overhaul with add/edit/delete of existing emails and new triggers making it a whole lot more customisable.

**Comment by abrookbanks** [comment]
6.1 is going to focus on this area

**Comment by abrookbanks** [comment]
![screen shot 2016-01-27 at 16 27 02](https://cloud.githubusercontent.com/assets/4520803/12620135/dfe85e2e-c512-11e5-9aa9-5a2edcef3c14.png)

![screen shot 2016-01-27 at 16 27 11](https://cloud.githubusercontent.com/assets/4520803/12620125/d8bc2bc6-c512-11e5-8175-76591e8d8405.png)

**Comment by havenswift-hosting** [comment]
I think this is a great idea but searching tools will be vital and an easy way to delete large numbers of historical records also important.

**Comment by abrookbanks** [comment]
Yup I wonder if it should default to only storing the last 100 emails.

**Comment by briansandall** [comment]
Depending on the popularity of one's store, 100 emails may not cover a very long period of time; perhaps a better solution would be to limit based on date rather than the number of emails, e.g. store emails for the last 2 weeks (or however long the store owner wishes).

**Comment by havenswift-hosting** [comment]
Hi Al

While this a great new function, I think simply keeping a fixed 45 days worth of emails is not going to suit many people.  That could not be long enough for some stores and could be far too many for others - I know you dislike Store Settings for some reason but often it is the only way to be able to tune a store on a case by case basis

**Comment by briansandall** [comment]
I agree with @havenswift-hosting - is there any specific reason you (Al) prefer not to add this feature as a store setting? Everyone likes at least the option to customize ;)

**Comment by abrookbanks** [comment]
See issue #1004

**Comment by abrookbanks** [comment]
This branch got lost and needs to be reintegrated.
