### ISSUE TITLE
Store logging needs to be improved

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#991]
Following on from the improved email logging that is being added, general logging across the whole of CubeCart really needs to be improved. An improvement to what is logged (everything) and the detail in which it is logged is really needed.  Obviously the log could get very large very quickly so a way to search by a variety of parameters would be needed as would a simple way to delete large numbers of entries (all before a certain date, all between certain dates etc)

**Comment by abrookbanks** [comment]
Can you give me an example?

**Comment by abrookbanks** [comment]
I'll close this now then as we can work from the other issue. :)
