### ISSUE TITLE
Bug : Language creation problems

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#992]
Creating a new language using the Admin built in function doesnt work - it appears that the empty xml file is created using the wrong format - ie creating Italian (it-IT) creates the following which is missing quite a few required fields and has some in the wrong format !

<?xml version="1.0" encoding="UTF-8"?>
<language version="2.0">
 <info>
  <title><![CDATA[Italiano]]></title>
  <locale>it-IT</locale>
  <character_set><![CDATA[utf-8]]></character_set>
  <version>1.0.0</version>
  <minVersion>6.0.10</minVersion>
  <maxVersion>5.0.*</maxVersion>
 </info>
</language>

**Comment by abrookbanks** [comment]
This was fixed for 6.1.0 #1230
