### ISSUE TITLE
Hook Request - Admin Categories/Customers/Manufacturers/Products Tabs

### ISSUE THREAD

**Issue by SemperFiWS** [cubecart/v6#993]
File: /modules/plugins/hooks.xml
Find This:
```
 <hook trigger="admin.category.save.post_process" deprecated="" />
```
Below That Add This:
```
 <hook trigger="admin.category.tabs" deprecated="" />
```

File: /admin/sources/categories.index.inc.php
Find This:
```
			// Stuff
			if (isset($catData['cat_image'])) {
				$GLOBALS['smarty']->assign('JSON_IMAGES', json_encode(array($catData['cat_image'])));
			}
```
Below That Add This:
```
			foreach ($GLOBALS['hooks']->load('admin.category.tabs') as $hook) include $hook;
			$GLOBALS['smarty']->assign('PLUGIN_TABS', $smarty_data['plugin_tabs']);
```

File: /admin/skins/default/templates/categories.index.php
Find This:
```
	<div><a href="{$TRANSLATE}">{$LANG.translate.trans_add}</a></div>
  </div>
  {/if}
```
Below That Add This:
```
  {if isset($PLUGIN_TABS)}
	{foreach from=$PLUGIN_TABS item=tab}
		{$tab}
	{/foreach}
  {/if}
```

Implementing this will allow new tabs to be added to the admin add/edit category page after the translations tab.

**Comment by SemperFiWS** [comment]
File: /modules/plugins/hooks.xml
Find This:
```
 <hook trigger="admin.customer.list" deprecated="" />
```
Below That Add This:
```
 <hook trigger="admin.customer.tabs" deprecated="" />
```

File: /admin/sources/customers.index.inc.php
Find This:
```
	$GLOBALS['smarty']->assign('CUSTOMER', $customer);
	$GLOBALS['smarty']->assign('DISPLAY_CUSTOMER_FORM', true);
```
Above That Add This:
```
	foreach ($GLOBALS['hooks']->load('admin.customer.tabs') as $hook) include $hook;
	$GLOBALS['smarty']->assign('PLUGIN_TABS', $smarty_data['plugin_tabs']);
```

File: /admin/skins/default/templates/customers.index.php
Find This:
```
		  <a href="#" class="add" target="membership" title="{$LANG.common.add}"><i class="fa fa-plus-circle" title="{$LANG.common.add}"></i></a>
		</div>
	  </fieldset>
	</div>
	{/if}
```
Below That Add This:
```
	{if isset($PLUGIN_TABS)}
	  {foreach from=$PLUGIN_TABS item=tab}
		{$tab}
	  {/foreach}
	{/if}
```

Implementing this will allow new tabs to be added to the admin add/edit customer page after the groups tab.

**Comment by SemperFiWS** [comment]
File: /modules/plugins/hooks.xml
Find This:
```
 <hook trigger="admin.product.manufacturers.save.post_process" deprecated="" />
```
Below That Add This:
```
 <hook trigger="admin.product.manufacturer.tabs" deprecated="" />
```

File: /admin/sources/products.manufacturers.inc.php
Find This:
```
	$GLOBALS['smarty']->assign('DISPLAY_FORM', true);
```
Above That Add This:
```
	foreach ($GLOBALS['hooks']->load('admin.product.manufacturer.tabs') as $hook) include $hook;
	$GLOBALS['smarty']->assign('PLUGIN_TABS', $smarty_data['plugin_tabs']);
```

File: /admin/skins/default/templates/products.manufacturers.php
Find This:
```
  {/if}
  <input type="hidden" name="token" value="{$SESSION_TOKEN}">
</form>
```
Above That Add This:
```
  {if isset($PLUGIN_TABS)}
	{foreach from=$PLUGIN_TABS item=tab}
		{$tab}
	{/foreach}
  {/if}
```

Implementing this will allow new tabs to be added to the admin add/edit manufacturer page.

**Comment by SemperFiWS** [comment]
File: /modules/plugins/hooks.xml
Find This:
```
 <hook trigger="admin.product.import.format" deprecated="" />
```
Below That Add This:
```
 <hook trigger="admin.product.tabs" deprecated="" />
```

File: /admin/sources/products.index.inc.php
Find This:
```
		$GLOBALS['smarty']->assign('FORM_HASH', md5(implode('', $result[0])));
		$GLOBALS['smarty']->assign('DISPLAY_PRODUCT_FORM', true);
```
Above That Add This:
```
		foreach ($GLOBALS['hooks']->load('admin.product.tabs') as $hook) include $hook;
		$GLOBALS['smarty']->assign('PLUGIN_TABS', $smarty_data['plugin_tabs']);
```

File: /admin/skins/default/templates/products.index.php
Find This:
```
      <div><a href="{$TRANSLATE}">{$LANG.translate.trans_add}</a></div>
   </div>
   {/if}
```
Below That Add This:
```
   {if isset($PLUGIN_TABS)}
      {foreach from=$PLUGIN_TABS item=tab}
		{$tab}
      {/foreach}
   {/if}
```

Implementing this will allow new tabs to be added to the admin add/edit product page after the translations tab.

**Comment by bhsmither** [comment]
There is most of this already:
In controller.admin.pre_session..inc.php:
```
$GLOBALS['hook_tab_content'] = array();
```
**ONLY** in products.index.inc.php and settings.index.inc.php:
```
$GLOBALS['smarty']->assign('HOOK_TAB_CONTENT', $GLOBALS['hook_tab_content']);
```
In acp.class.php, showTabs():
```
foreach ($GLOBALS['hooks']->load('admin.tabs') as $hook) include $hook;
$GLOBALS['smarty']->assign('TABS', $tabs);
```
The admin template, element.hook_form_content.php, uses `$HOOK_TAB_CONTENT`.
The admin template, main.php, uses `$TABS`.
Many, if not all, templates have:
```
{include file='templates/element.hook_form_content.php}
```
To finish this, the Smarty assignment for `HOOK_TAB_CONTENT` needs to be added to all other `whatever.index.inc.php` source files.

**Comment by SemperFiWS** [comment]
I looked into using 'element.hook_form_content.php'.
But as noted above it has not been completely implemented.

Plus I wanted to target the add/edit page of those 4 components specifically.
e.g.
![sfws-hpfc-04-admin-category](https://cloud.githubusercontent.com/assets/6945093/12721763/5bd5f72a-c8cf-11e5-9f87-45c4409798db.png)

**Comment by bhsmither** [comment]
If your hook examines the values for the _g, node, and action keys, maybe that will get you what you want?

**Comment by SemperFiWS** [comment]
The changes above were added via pull request #980 and do what is required without having to examine the values.

Thank you Al, very much appreciated.

**Comment by SemperFiWS** [comment]
Slight tweak to the '/admin/sources/customers.index.inc.php' change so customer data is available:
```
	$GLOBALS['smarty']->assign('CUSTOMER', $customer);
	foreach ($GLOBALS['hooks']->load('admin.customer.tabs') as $hook) include $hook;
	$GLOBALS['smarty']->assign('PLUGIN_TABS', $smarty_data['plugin_tabs']);
	$GLOBALS['smarty']->assign('DISPLAY_CUSTOMER_FORM', true);
```

**Comment by abrookbanks** [comment]
I've closed this as I believe the merge fixed it. Can you let me know if not and we can reopen it. 

Cheers. :)
