### ISSUE TITLE
PHP memory error

### ISSUE THREAD

**Issue by davshirley** [cubecart/v6#994]
I'm seeing this error in the logs when attempting to edit category images for a site with a large amount (over 3K) of images:

PHP Fatal error:  Allowed memory size of 136314880 bytes exhausted (tried to allocate 16152 bytes) in /home/xxx/domains/xxx.com/public_html/classes/gd.class.php on line 101, referer: https://www.xxx.com/admin.php?_g=categories&action=edit&cat_id=7

I tried setting the server to give 250M limit to php and confirmed that via phpinfo(); but the error remains.  Is this a code issue or should I be looking for some other cause?

**Comment by bhsmither** [comment]
This will not be an issue with the **number** of images (unless you have, perhaps 3 million image files), but rather the filesize of one particular image. Find the filesize of the largest image you have and replace that image (resize the width and height of it by half) with a smaller image and try again.

**Comment by davshirley** [comment]
I did find where ini.inc.php was artificially capping the ram at 128M and I didn't see that before in phpinfo.  (Looked at the wrong column... D'oh)  After upping that men limit to 150M I no longer get the error but the image box on the category edit screen still comes up blank even though there is an image assigned to the category being edited.

Is images/source the only place I should be looking or are some hidden elsewhere?

**Comment by davshirley** [comment]
Think I found it.  New error was "Maximum execution time of 120 seconds exceeded in..." but I had to wait 120 seconds for it appeared in the logs so i missed it before.  increase php to 240 seconds and got the list.  That was the first time through the long list of image files.  Now it pops up right away so I assume that a cache was being built...

Would your theory on oversize files also contribute to being slow to build that list?  If so, perhaps that needs optimizing.  Does it really need to read the CONTENTS of the files just to build an array of filenames?

**Comment by bhsmither** [comment]
In admin, there is no cache being used (not exactly true). If anything (and I doubt this), CubeCart was rendering all the image variants (placed in /images/cache/) for the image filetree. In my opinion, however, CubeCart renders the variants *on demand* and populating the filetree with filenames is not a trigger for *on demand* rendering.

* There is a Request cache, used to hold the Google taxonomy and maybe one or two other things.

**Comment by davshirley** [comment]
Ok.  lets close this out.  If I see this happen again I'll run a trace on the server process and see if I can get a view of what it is doing.
