### ISSUE TITLE
Sales Mode Logic for Sitemap and Category Menu - enhancement request

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#995]
The only time it makes sense to me for a link to sales items to show in the Sitemap or on the Category menu is the situation where some, but not all, items are on sale.
With that in mind, Bsmither helped me change the code in seo.class.php to 
`````
		# Sale Items 
if(
    $GLOBALS['config']->get('config', 'catalogue_sale_mode') !== '0'
    &&
    $GLOBALS['config']->get('config', 'catalogue_sale_mode') !== '2'
) {
		$this->_sitemap_link(array('url' => $store_url.'/index.php?_a=saleitems'));
		}
`````
For box.navigation.php instead of {if $CTRL_SALE}
`````
if(
    $GLOBALS['config']->get('config', 'catalogue_sale_mode') !== '0'
    &&
    $GLOBALS['config']->get('config', 'catalogue_sale_mode') !== '2'
) {

`````
See forum discussion https://forums.cubecart.com/topic/50837-sitemap-sale-mode-logic/

**Comment by abrookbanks** [comment]
Thanks! :)
