### ISSUE TITLE
Update File List - Bug related to md5 hash

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#996]
Tested using 6.0.10.

This is a bug that relates to the filemanagers ability to rebuild the filemanager records for images based on the files in the source directory.

Line 213 of filemanager.class.php does a hash check of the file being processed against the filemanager table. If it finds a match it will NOT add the record / filename (even if it's missing).

If you have duplicate images with different file names, only the first one in a-z order will be added, the others are ignored.

This query should be updated to match on both md5hash AND filename to solve the issue. It currently only matches on md5 hash and image directory.

**Comment by bhsmither** [comment]
Maybe adding to the WHERE array `'filename' => $record['filename']` to discriminate between same image but different filename.

**Comment by Noodleyman** [comment]
yup, thats how I patched it on my customers instance to resolve the issue.

**Comment by abrookbanks** [comment]
Thanks Chaps.
